### ISSUE TITLE
Enhancement: Historical usage reporting for self-hosted instances

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#10001]
## Issue - Enhancement

For many of the deployments we'll have within the Public Sector, we won't have access to our instances or their databases. The best we'll be able to do in order to track usage and negotiate/update our license fees will be to ask the DevOps/SRE support staff who operate our instances to run a command and send us the result.

In a future, ideal state. There will be a dashboard where they can click a button and it'll download a file they can send to us. For now, let's start by defining a GraphQL query they can run and then send us the output 

### Acceptance Criteria (optional)
A DevOps/SRE individual with `su` access to one of our deployments can:

   - Run a GraphQL query that accepts the following parameters:
      - optional: the start date to run history, defaults to all history
      - optional: the end date to run history, defaults to now
      - optional: a boolean flag that aggregates across all orgs, or one row for each org
      - optional: a list of orgIds to include in the result, defaults to all orgs

   - ...and can return the following data:
      - Some identifiable information about which deployment this is
      - One row/list item for each month and org (unless aggregating across all orgs) in the reporting period:
         - the last day of the month
         - the name of the org (and orgId) the data pertains to (unless aggregating)
         - the number of unique users who signed up for Parabol within the period
         - ~the number of unique users who logged into/connected to Parabol within the period~
         - the number of users who participated in a meeting within the period
         - the number of meetings ran within a period

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick here is the shape of the stats query I had in mind...

**Comment by jordanh** [comment]
cc @dbumblis-parabol

**Comment by mattkrick** [comment]
is there a disk we could save it to? if so, we could use a cronjob.
alternatively, we could add a feature to GraphiQL that downloads the response as a file so they don't have to copy/paste.

we should sign the payload, although if the app can sign the payload, they could manually sign the payload, too. So, the best bet is obfuscation-- make the secret hard to get at and/or the generation of the checksum difficult.

**Comment by tianrunhe** [comment]
Fruit of thoughts: can we reuse/build on top of https://action.parabol.co/usage ?

**Comment by jordanh** [comment]
> is there a disk we could save it to? if so, we could use a cronjob.
alternatively, we could add a feature to GraphiQL that downloads the response as a file so they don't have to copy/paste.
we can also pre-load the query we want them to run in the app

You know... they do have a logging system so we could just emit these data in their logs every once in a while. Perhaps that would be good ergonomics?

**Comment by mattkrick** [comment]
ha! i like that. cron job that just spits to the console?
honestly, whatever works for them works for me.

**Comment by jordanh** [comment]
Note: we cannot provide:

> the number of unique users who logged into/connected to Parabol within the period

As we only keep `lastSeenAt` on the `OrganizationUser` table. Today we have no audit trail for connections.
