### ISSUE TITLE
Rename Jira Server -> Jira Data Center

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#10051]
## Issue - Enhancement

We met with the Atlassian Solutions Architecture team and they noted that Jira Server is no longer a supported product; we should rename and refresh the iconography to call Jira Server Jira Data Center

### Acceptance Criteria (optional)

   - Jira Server name and icon -> Jira Data Center in all places
      - Team Dash Integrations
      - Sprint Poker panel
      - Stand-ups panel
   - optional: Text added to Jira Data Center integration menu that Jira Server is also supported

**Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by charlesmathias** [comment]
Another in-app location to update: Plans & Billing page, in the description of Enterprise features

**Comment by Dschoordsch** [comment]
Can we continue using the "Jira Software" logo, or which one should it be? https://atlassian.design/resources/logo-library

**Comment by Dschoordsch** [comment]
@tianrunhe Shall I also rename the analytics events? https://github.com/ParabolInc/parabol/blob/9c2d59d3780422a9d1449be86bac60b86429c726/packages/client/modules/teamDashboard/components/ProviderRow/JiraServerProviderRow.tsx#L78

**Comment by Dschoordsch** [comment]
I will only do UI changes. There is not much value in renaming all GraphQL types and classes. We can do that if we touch the code anyways, like when implementing OAuth2 for it.
