### ISSUE TITLE
Invite Links not working

### ISSUE THREAD

**Issue by kendradixon** [ParabolInc/parabol#10085]
We've had a handful of inquiries from users stating the invite links are not working. User trying to accept invites are stating they are receiving a server error message or nothing happening at all.

Example noted:
I have an issue with team invitation, I can't accept invitation from my team, and I can't join them. I tried to do it via e-mail invitation and therefore directly on the website. Email invitation redirect me to the blurred parabol page, the invitation from the notification on the parabol page does not work at all.

**Comment by Dschoordsch** [comment]
Sentry Issue: [ACTION-PRODUCTION-JJY](https://parabol.sentry.io/issues/5675689474/?referrer=github_plugin)
