### ISSUE TITLE
Update copy when creating meeting recurrence to show first meeting in series

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#10112]
When a [user](https://parabol.slack.com/archives/C4JAUUZ9P/p1723625575001099?thread_ts=1723625526.311249&cid=C4JAUUZ9P) 🔒 creates a recurring meeting on Parabol, the copy is currently:

> “The next meeting in this series will be called “Retro - Month date”“

This is confusing copy to the user: are we referring the meeting we're about to create or the one after?

Copy could read:
> “The first meeting in this series will be “Retro - Month date”“

**Comment by jordanh** [comment]
Closing in favor of #10113
