### ISSUE TITLE
Design: when I am an org admin, and I'd like to invite a user to a team

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#10150]
### Design issue

We've received #10012 a good amount of feedback that org admins would like to not only create teams, but invite users to those teams.

In the original implementation of the org admin view, we simply tried to repurpose the email Invitation modal. It had some technical/permissions difficulties and so we decided to ship without it. Let's re-consider what to do here afresh.

## Design checklist

- [ ] Can users be invited to teams via email and via a link?
- [ ] If I've just created the team, who becomes a member or Team Lead by default?
   - [ ] Can I reassigned the Team Lead role to someone who hasn't accepted an invitation yet?

**Comment by tianrunhe** [comment]
I'm working on a sortable org member view [here](https://github.com/ParabolInc/parabol/pull/10146). Your design might need to "rebase" on this

**Comment by ackernaut** [comment]
[Here are my recommendations](https://www.notion.so/parabol/Org-Admins-can-create-teams-assign-team-leads-and-invite-to-teams-without-being-on-the-team-5524294270ff4545aec0e7f6f2accf9a?pvs=4#1213b8ee377480a79efeddf3b117b349) (🔒 ) for this UX including nice-to-haves. If we decide to build any part of it we can use the notes to create small implementation issues with AC.
