### ISSUE TITLE
Non-Enterprise accounts see Org Admin teaser on Teams page

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#10158]
A user recently said:

> "We have never been prevented from adding more than 2 teams to this organization since we started using Parabol"

In his email, he shared a screenshot of his Teams on the org settings page.

My hypothesis is that this user wasn't even aware that we had a higher tier as there aren't many limits or pointers to upgrade.

Org Admin features could be teased on the Teams page.

**Comment by charlesmathias** [comment]
My idea here is for any Billing Leader of a Starter or Team org, we show something similar to:

<img width="1310" alt="Frame 8 (1)" src="https://github.com/user-attachments/assets/9947b272-c810-4fba-99b9-33131c48bb5e">

**Comment by tianrunhe** [comment]
<img width="949" alt="Screenshot 2024-09-18 at 15 48 33" src="https://github.com/user-attachments/assets/f5682ba7-2ad5-4c7d-8b8a-2d1d27dd85e7">

@charlesmathias WDYT?

**Comment by charlesmathias** [comment]
Wow! Thanks @tianrunhe. My questions:
- who would see this message? What about if there weren't any additional/hidden teams in the org?
- Is "Hidden Teams" scrollable if there are many teams? Are the hidden teams blurred in the background?
- The alignments seems of in the box below "Hidden Teams". Can you make everything sit in the middle?

Tagging @ackernaut to get his design eyes on this, also

**Comment by tianrunhe** [comment]
> Who would see this message?

We can show this for billing leads only? Or team leads?

> What about if there weren't any additional/hidden teams in the org?

We can hide the view then

> Is "Hidden Teams" scrollable if there are many teams? Are the hidden teams blurred in the background?

It's just a placeholder there so it's not scrollable or clickable. It is **not** that we are masking any real teams here (which could be easily detoured by changing front-end HTML elements).

**Comment by charlesmathias** [comment]
I think it's simpler if all users see this, where there are additional teams. I agree removing the view when there aren't any extra teams.

One thought: could we include the number of additional teams? Eg "3 Hidden Teams". And it uses the same style as the heading "2 teams" in your screenshot above.

**Comment by ackernaut** [comment]
A few points of feedback here:
- It seems there’s a very light gray and white in the section. It looks a little unintentional. The whole box should be white.
- I’m not sure the header needs to be a lighter gray. I’m wondering if it’s supposed to be a disabled element? I would make the header the same color as the others and remove the arrow/caret > as folks can’t really go anywhere.
- I think if the section has a white background, says ## Hidden Teams per Charles suggestion, above the description light, and the button will be enough in the box.
- Everything should be centered vertically with vertical padding more or less like each team section above
- The header will feel right being aligned with the team names, but I wonder if hang the lock beside the ## Hidden team headers and description

**Comment by ackernaut** [comment]
Maybe something [like this](https://www.figma.com/design/JYFQNSeutaa0wW4PwpMND0/Team-and-Members-Management-(OrgAdmin)?node-id=225-1667&node-type=frame&t=VWk3LA9QXzDBQkKs-11)?

Also, another thing that is weird to me in the view above is seeing the Team Lead badge by the team name. I understand it to mean that it is a team where I am the team lead. However the role badges tend to make more sense by people as it qualifies the member (on a list of members). Here it gives me a little UX confusion as if it’s qualifying the team. Maybe we could put this information [in the meta line](https://www.figma.com/design/JYFQNSeutaa0wW4PwpMND0/Team-and-Members-Management-(OrgAdmin)?node-id=225-1667&node-type=frame&t=VWk3LA9QXzDBQkKs-11)?

**Comment by charlesmathias** [comment]
Thanks, @ackernaut! Your suggestion looks a lot better than mine... @tianrunhe are you able to update to reflect Terry's suggestions here?
