### ISSUE TITLE
Update copy for Non Org Admins on Integration Settings page

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#10226]
Right now, if any non Org Admin goes to the Integration Settings page. They see that only an org admin can "manage integrations".

This is confusing because a user may ask:
- but I am the Billing Leader, so am I the Org Admin?
- who is the Org Admin?
- How do I get this thing to work?!

I propose the following change:
![Copy change Int settings](https://github.com/user-attachments/assets/c85cb51e-a58d-4008-8d6a-4cfcbc4bd678)

The link takes the user to the Plans & Billing page where they can see Org Admin (and soon GitLab Server) on the list of Enterprise features.

If they do have Enterprise and an Org Admin, they'll see their Org Admin - who they can contact to ask to set up the integration.

**Comment by gcrickman** [comment]
A comment from a [user](https://app.hubspot.com/contacts/3888472/contact/69555179832) 🔒 that found the Gitlab private server integration:

> Hello, We are testing the product but I can't add a gitlab private server to my org I just created, the add server button is greyed out without stating what is the reason why it's not available. Do you have an idea why ?
> Thanks!
