### ISSUE TITLE
Bug: Reply/threading broken

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#10222]
## Issue - Bug

As of today, while using our Discussion thread feature. Hitting Reply and typing a message does not display the Reply in the thread. It isn't clear (i.e. I haven't triaged) if the mutation is actually properly created the thread in the DB.

### Acceptance Criteria (optional)
Users can:
   - Create and view threaded replies in Discussions
   - Create and view threaded replies in the Demo

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
could not reproduce, but found a bug where you couldn't thread on a task, so i fixed that
