### ISSUE TITLE
ENDTIME NOT DATE

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#10411]
## Issue - Bug

- **How serious is the bug?** P2
- **OS:** macOS / Linux / Windows / ? - 
- **Browser:** Chrome / Safari / Lynx / ? + version -
- **Node version:** `node --version` v20.11.0
- **NPM version:** `npm --version`

Logs are flooded with tons of "ENDTIME NOT DATE [...]" logs. That [log line](https://github.com/ParabolInc/parabol/blob/b5bd2b46d88df1e13d5a12a925642b9e47b1b5a1/packages/server/graphql/public/types/NewMeetingStage.ts#L39) was added two weeks ago. 

### Acceptance Criteria (optional)

Users can:

- Do this
- Do that
- Cannot do that
  Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
fixed in 8.1.0
