### ISSUE TITLE
Bug: demo comments are broken

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#10621]
After recent changes, when a bot or user types a comment into the demo they get what looks like JSON:

![image](https://github.com/user-attachments/assets/8f45e591-3210-4c00-93a8-ebb0a60b5d5c)

### Acceptance Criteria (optional)

Users can:

- see comments rendered correctly

  Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
I assume it was fixed by #10623
