### ISSUE TITLE
Archive: that's all folks!

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#1450]
## Issue - Enhancement

When a user scrolls to the end of the archive, I want to see something that tells me there are no more items to paginate to, so I can be sure I'm done

### Acceptance Criteria
1. Create multiple project cards, enough so that when they are archived they will have to be paginated
2. Archive them all
3. Go to the archive, keep paginating until there are no more archive cards to display
4. Show a message at the bottom, _"That's all folks!_ There are no further Tasks in the archive."

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Reopening issue

**Comment by artygus** [comment]
hi! I'll do it for 11 points

**Comment by jordanh** [comment]
Hi there @artygus – sounds good to us! Since this is your first E4E mission, could you join our developer Slack so I can provide and get some more information from you? We're at: https://slackin.parabol.co/

**Comment by rakhi2104** [comment]
Hey @jordanh, can I get more details on this?

**Comment by simplywondrous** [comment]
Hi @jordanh, if this is still open I'll take this up :)

**Comment by jordanh** [comment]
@simplywondrous this is still up for grabs! It's yours for 12 points. I've updated the project board to reflect that :)

**Comment by shapel** [comment]
@jordanh you can find my PR for this issue

**Comment by shapel** [comment]
👋 @jordanh don't forget to give me points 🤓
