### ISSUE TITLE
Migration path to React v17.0.0

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#1938]
This video with 2 live demos is pretty great: https://deploy-preview-596--reactjs.netlify.com/blog/2018/03/01/sneak-peek-beyond-react-16.html

And here is the latest blog post: https://deploy-preview-596--reactjs.netlify.com/blog/2018/03/27/update-on-async-rendering.html

Here's the proposed roadmap for us (standing for acceptance criteria):
- Today: Don't accept any new PRs that use `componentWillMount, componentWillReceiveProps, componentWillUpdate`. If you touch anything inside these lifecycle functions, the PR should upgrade to the new lifecycle function as shown in the links above (you can also check out QueryRenderer.js in our own repo as an example)
- Tomorrow: Don't spend too much time worrying about React-Loadables. The upcoming suspense API will have that functionality built-in. It's gonna be really, really good.
- v17.0.0-alpha: Before v17 is released, refactor the ~43 affected components. Should take a couple hours (albeit it's gonna be a not-so-fun day).

Effort: 11 points

**Comment by ackernaut** [comment]
This looks really good, @mattkrick !

**Comment by mattkrick** [comment]
Great article put out to show how to use a naive memoizer function to avoid the overly complex getDerivedStateFromProps: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization

I think they wrote that for us, since that's the example I asked them about a month ago. Pretty solid advice! We should keep it in our back pocket when we convert the rest of our components over.

**Comment by jordanh** [comment]
Scubbed.

I believe we should treat this issue like a "Deprecation issue" in that we are introducing a new pattern to support React 17. Let's keep this issue open until we've migrated over. This comment will reset the clock on iceboxing.

**Comment by jordanh** [comment]
See also:

   - #3324
   - #3325
 
Also needs updating:

   - The confetti cannon

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.
