### ISSUE TITLE
Customizable Team dashboard columns

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/parabol#212]
## Issue - Enhancement

User teams work on different cycle lengths and rhythms. They frequently voice the desire to customize their column headings to match their use needs.

### Acceptance Criteria (optional)
Users can:
   - re-name the existing 4 columns on Team Dashboards, as a paid (Pro) feature
 
**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is most certainly still a thing. However as per our ice-boxing policy. Let's icebox it for now and re-open a design issue when the opportunity arises.

This is a good candidate for us to sell to a potential client as a sponsored design cycle.

**Comment by tayamueller** [comment]
from [this Pro Billing Leader](https://app.hubspot.com/contacts/3888472/contact/1305601/):

> btw, why is the order of columns different when viewing the tasks at „my dashboard“ and viewing them during the meeting. This is confusing when you remember „Done“ is on the left on my dashboard and then you want to put something on done during a meeting and you accidentally put it in the wrong column, as there „done“ is on the left. This happens quite often ;) Is this configurable?

**Comment by carsten-z** [comment]
If not making this customizable, then just make it look the same on personal dashboard and during the meeting. currently at "my dashboard" "done" is on the right and during the meeting its on the left. thats confusing...

**Comment by jordanh** [comment]
@carsten-z it was a design choice on our part – when folks give their updates they are encouraged to start with "since last week I finished X, this week I'm focused on Y."

I agree though: not everybody wants this. We should eventually make it configurable.

- - -
(scrubbed issue, added milestone)

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/1377251) writes:
> We would like the ability to edit and add/remove kanban board/swimlanes.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/6592301?) writes:

> For the “Tasks” screen(I think it is the dashboard), I miss either a column of “Won´t Do”, or to be able to add a custom task category for items that are not in the Future/Stuck/InProgress/Done. Sometimes I find that we agree on action points during a retro that during the course of a sprint or sprints we will detect that are no longer of value. I would still like to keep them there to show what we thought in the past, but in a different category.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11722351) 🔒 writes via Live Chat:

> User: I am from Portugal, working like Agile Coach and my company ~redacted~ here use some Daily Board. Parabol Will help us a Lot, but without change the (column) names, I can not present to my team

> Me: Do you need to only change the names, or be able to add new columns too?

> User: Change names and add New columns

> Me: Did you know we integrate with other tasking systems? So, if you don’t like the way our tasks are arranged, you can have them export to Jira or GitHub

> User: Not yet, First this feature is Just to present to my coach colleagues

> Me: One last question – if we had an integration to Planner, would you still need to be able to customize our columns or would you rather just use Planner?

> User: Both, Planner and parabol. And why parabol? Very diff name to associate

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/6454701) 🔒 says: 

> I would like to be able to rename columns like active, future and stuck.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/2440801) 🔒 writes:
> Maybe this is our company specifically, but we don't tend to use the Future/Stuck/Active page. We have tried, but especially the way our retros run, we look for potential solutions and then the Producers go off and generate tasks. We don't come up with specific tasks DURING retro since we only have so much time.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/3284401) 🔒  writes via support: 

> It would be really great to be able to change the column headings. I always run my retro's with variants of "What worked" "What could be improved" "What should we change for next time". The last column goes into the backlog or is notes for actions to change in the next sprint. In that context, I have no idea what to do with "Future" "Stuck" "Active" and "Done".

**Comment by mattkrick** [comment]
my gut tells me the right way to handle this is a lot more effort than making the column names mutable.
iceboxing for now until we dedicate some real effort to how we handle tasks

**Comment by ackernaut** [comment]
>Columns on KanBan board, change the status, limited space on card, would like to be able to comment on dashboard like a backlog item or change the column headers/add more

**Comment by ackernaut** [comment]
Related to #4610

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/13053751) 🔒 writes (referring to Sprint Poker)

> A new column on my Team's Dashboard for items that are to be pointed would be really helpful. Right now, I am putting all Tasks that need to be pointed into our Future column, which works for now. It would be great to have a 5th column that is something like..."To Be Pointed" or something along those lines.

**Comment by jordanh** [comment]
The present thinking is to:

* layer on inspirations to the product to make external tasking more interesting
* deemphasize the kanban in our product to reduce the obviousness of this tension
* decide what to do later around Parabol native tasking

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/14061851) 🔒  writes:

> make the task board more flexible (custom rows?)

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/10206002) 🔒  writes:

> From what we can see, Parabol will only allow 4 set headings for cards – is this non-customizable?  They would need flexibility there.

**Comment by jordanh** [comment]
Adding feedback from #4610 below

**Comment by jordanh** [comment]
## Client Request: Custom Kanban Column Headers

From a 🔐 [client](https://app.hubspot.com/contacts/3888472/contact/12975601):
"Our team has started to use our Parabol board for a range of different types of retro tasks that extend beyond simple action items and we're using columns to organise and visualize them.We'd love to be able to rename the columns - and even add additional columns to the team dashboard. In a similar way to how different teams use different names for their Trello board columns, and their Azure Devops board columns.

I think we might like something along the lines of:
Do this sprint (this would replace 'Active')
Do this quarter (this would replace 'Stuck')
Future / Todo / Maybe (one of those)
Done

One way that Parabol works well for us is that we are always looking to check off and complete tasks. We review our board regularly and if a card is in the active column longer than a sprint cycle it becomes apparent to the team that it's in a 'Stuck' or 'Stale' state and we usually discuss what we can do to move it along on our board. The 'Stuck' column is a little redundant to us as stuck items will always remain in the 'Active' column. 

We use Azure DevOps for work tasks and we use Parabol for retro / team agile process tasks. It seems to benefit us to keep these two areas of concern separated so we aren't looking for a way to transfer tasks to-and-from DevOps."

### Acceptance Criteria
Users can:
   - Team leaders can name the Kanban columns anything they want
   - Customize the number of columns per team board

**Comment by jordanh** [comment]
>Columns on KanBan board, change the status, limited space on card, would like to be able to comment on dashboard like a backlog item or change the column headers/add more

**Comment by jordanh** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/13321151) 🔒  says:

> In the board where you track action points there is no posibility to change the title of the column. It could be useful

**Comment by jordanh** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/22446251) 🔒 writes: 

> is it possible to add a new column in the dashboard?

**Comment by jordanh** [comment]
We had +2 requests for this during this [User Feedback Retro](https://action.parabol.co/new-summary/2AvrebtSAE)

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/34039001) 🔒  writes into the chat:

> Hi! I was wondering if I can create another column in check-in meeting?

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/16931301) 🔒 says:

> The kanban board can't be customized. I'd like a way to edit the columns to better fit our needs.

**Comment by enriquesanchez** [comment]
From the [Parabol Customer Feedback Survey](https://parabol.slack.com/archives/C08FL5UE7/p1633422567280700) 🔒, users expressed particular enthusiasm for a customizable task board.

**Comment by drewhousman1010** [comment]
An [engineering manager](https://app.hubspot.com/contacts/3888472/contact/53969051) 🔒  just said that the number one thing his engineers want is to be able to edit the dashboard columns. He said if we could do that it would be a lot easier to get everyone on board to buy an enterprise plan.

**Comment by mattkrick** [comment]
My .02 on the priority of this one:
- This one has been hanging out since 2016 primarily because it's not a product differentiator. 
- We'll NEVER be as good of a tasking system as jira, github, trello, asana, et al. That market is crazy saturated
- Rather than just making column names editable and allowing add/delete functionality, the current thinking is we want to establish "integration-based triggers" or "2-way sync"
- These triggers act kinda like zapier. When a card moves from "active" to "done" in jira, then it moves to "done" in parabol. When a github-integrated task in parabol moves to "done" in parabol, it moves to "Finished" in github. 
- Supporting this sync provides a new/novel feature that encourages integrations. It's something that not a whole lot of other apps can provide, so we won't be feature chasing.
- All that said, we haven't designed anything, we just have thoughts floating around. @jordanh could probably add more detail here

**Comment by ackernaut** [comment]
@mattkrick I like that idea, that we build to help them sync state in the places where these things really live. Gonna simmer on that thought. I agree on not chasing feature parity with task management in general.

**Comment by drewhousman1010** [comment]
Super interesting, thanks for the detailed thoughts @mattkrick. Plus one to you and Terry on not feature chasing. But what qualifies as feature chasing? (scratches chin, looks thoughtfully into distance) 

The way I see it, and I the way I think users see it, is that editing the column names is akin to editing the name of a group of cards. It feels more like something that just makes sense in terms of UI.

**Comment by ackernaut** [comment]
>The way I see it, and I the way I think users see it, is that editing the column names is akin to editing the name of a group of cards. It feels more like something that just makes sense in terms of UI.

I think that’s a good point. Some basic utility just makes sense. I think we can tackle basic utility by bundling it in when we have a workflow that ranks enough to make the cut of what we spend time building. Because of course we’ll only have so much capacity to build new things at any given time. I think the syncing workflow is strategic enough and perhaps you can name your groupings on both ends (Parabol <=> Integration) and it warrants custom lanes as a result.

**Comment by jordanh** [comment]
Iceboxing. Have a feeling this one will come back again ...

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/109792951) 🔒 writes: 

> Is there a way to change tasks column names?
