### ISSUE TITLE
Due dates on archived task cards

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#2219]
## Enhancement

Currently one can change the due date on a card in the archive.

### Acceptance Criteria

- Disallow changing due dates on archived task cards
- [Audit](https://github.com/ParabolInc/action/issues/2219#issuecomment-523516595) and disable all editing and editing state feedback

**Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
EE: 10.5

**Comment by jordanh** [comment]
@ackernaut, I edited your issue :)

**Comment by ackernaut** [comment]
This is still a thing. Also, in the archive you can simply tap on a card and it shows an editing state. So the best fix whenever we get to this is to disable all editing and editing state feedback. Updating AC.

**Comment by jefftorcato** [comment]
Hi, I would like to complete this task for 10.5 points.

**Comment by jordanh** [comment]
@jefftorcato this one is all yours! Could you write me at jordan@parabol.co and we'll get you all set up to contribute to Parabol?

**Comment by NikAiyer** [comment]
I'll take a look at this one

**Comment by sinansonmez** [comment]
It seems like this issue is closed by #4047, right? If there is still some work to be done, I can take a look

**Comment by Dschoordsch** [comment]
Yes, that was fixed long time ago
