### ISSUE TITLE
Design new org change user summary email

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#2542]
AC
- [ ] email includes datetime, invited by name, name, & email (& avatar?) of users that have joined the org in the last 7 days
- [ ] "The following X Users were invited to your organization this week. To see how this affects your monthly invoice, click here."
- [ ] If any of these users were added in error, simply remove them HERE and you won't be charged."
- [ ] TODO: look to the slack email for inspo on how to say the above politely
- [ ] UNCERTAIN: if the inviter is also the billing leader, how do we avoid asking them to approve the changes that they themselves made?

Effort: 12 points

**Comment by mattkrick** [comment]
@jordanh this should be top priority since we've got pro users but we aren't sending them an email when they add people...

**Comment by jordanh** [comment]
I want to defer this one until _just_ after our next paying conversion

**Comment by ackernaut** [comment]
In the 20% bucket of the current sprint

**Comment by jordanh** [comment]
Iceboxing for now
