### ISSUE TITLE
Retaining retro columns in grouping, export

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#2557]
From [a Scrum Master](https://app.hubspot.com/contacts/3888472/contact/1885451) of a [15-person Pro team](https://app.hubspot.com/contacts/3888472/contacts/list/view/all/?query=%40reachmee.com):

> In the group phase, and in the CSV export, it would be really convenient if the columns were retained somehow. For some retro formats it really doesn’t make sense to group across columns, and having them all in a card soup makes it difficult.  😊

### AC (solution candidates)
- [x] Card colors by column (related solution brought up by another user) #2472 
- [x] Include the prompt for each reflection in the CSV export
- [x] Include all reflections (not just the ones voted) (done)
- [x] Cards stay in columns during the Group phase

### EE 10.5

**Comment by jordanh** [comment]
This came up again in a [user tweet](https://twitter.com/frot_io/status/1088803040587640832):

![image](https://user-images.githubusercontent.com/103000/51763133-9a6c3500-2086-11e9-8b18-d84b260eeb7e.png)

**Comment by jordanh** [comment]
Related to: 

- #2426 (auto-grouping as suggestions)
- #2566 (pre-sort reflections)

**Comment by robert-ventura** [comment]
@jordanh: I'm the one who sent in the feedback originally and having the option of a columnar layout would be perfect. 👍

**Comment by jordanh** [comment]
Thank you for the validation @robert-ventura!

**Comment by ackernaut** [comment]
From another user:
>With my team we are currently trying your tool for our retrospectives. We are quite satisfied :) But there is a step which really bothers us :/ 
In the grouping steps, the stickies are not ordered at all. It's really hard to find them in order to discuss about them. Do you think it would be possible to order them by category (from the previous step) or per person?

**Comment by jordanh** [comment]
via @tayamueller, user feedback submission (see #2774):

> During a retrospective (S-S-C format), after we enter our reflection cards, when we go to the Group phase, the cards are no longer grouped by "Start, Stop, Continue" which makes it really hard to work through all the reflections and group them. This seems very messy atm."

**Comment by ackernaut** [comment]
Another user wrote in via email:
>We use the 4Ls retrospective style and after the retro I downloaded the CSV I can not see which lines are regarding Liked, Lacked, Learned, Longed For. Is there an away to see all the [lines] the by Tag?

**Comment by ackernaut** [comment]
Feedback from [user](https://app.hubspot.com/contacts/3888472/contact/5290451/) via email:
>Two of the biggest things I’d like to see added are 1) being able to add more cards to the retro board after they are all showing (often ideas are hatched during the conversation after all the post its are up on the board) and 2) having the cards ordered in groups/columns. If I am doing a start/stop/continue retro, I’d like to see all the START cards in one group—same with STOP, and CONTINUE. Though I do LOVE how I can combine similar cards.

**Comment by ackernaut** [comment]
>Another piece of feedback, at grouping stage the categories (sad/mad/glad, continue/stop/start, etc.) get mixed which is not ideal as positives status such as glad and continue get into groups with 'negatives'. Would be good to be able to filter these out as we go over those only to praise and thanks but not to discuss and assign tasks.

**Comment by jordanh** [comment]
We think this should be resolved now by including colored prompt labels on reflection cards. Also, prompts are now in the CSV. Will reopen if this tension persists.
