### ISSUE TITLE
Pre-sort reflections

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#2566]
AC
- [ ] reflections that appear on the initial group phase load are in close proximity based on their estimated similarity of content

Effort: 11 points

**Comment by mattkrick** [comment]
this feels a little bandaid-ish. i'm cool with that, but i'd like to have an end goal in mind while building it out.

- should proximity be shown in 2D, or just 1D? e.g. the card below is closely related to the one above vs. just left to right, top to bottom. in a masonry layout, i think 1-D is assumed. if we turn it into a canvas & move away from the grid, we could play with spacing a little more

- is grouping a collaborative process? i know the gut reaction is yes, but when there are a ton of cards, i think the answer is no, which makes me question if it should be collaborative for small numbers

- should we keep the grid layout? or is a freeflow graphql visualization more appropriate?

- how do we get folks to title their single-card groups? efficiently solving this problem is nlogn, so ideally, we want someone to read a card, see if it fits in an existing group, and if not, create a new group. how can we encourage this behavior?

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
