### ISSUE TITLE
Safeguard accidental ending of meetings

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#2728]
## Issue - Enhancement

[A user ](https://app.hubspot.com/contacts/3888472/contact/1121551) reported:

> We also accidentally 'concluded' a retro while it was still in progress and couldn't find a way to bring it back.

### Acceptance Criteria (optional)
Users cannot:
   - accidentally end a meeting without confirmation (perhaps via a modal)

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut if this is done, can you open an implementation issue for it?

**Comment by jordanh** [comment]
Haven't heard additional user feedback around this. Iceboxing for now

**Comment by jordanh** [comment]
Pulling this out of the old ice box, just got some fresh feedback from a user:

> Hi,
> There is currently no way for you to un-end a meeting, which can happen easily due to the prominent “end meeting” button.
> There is also the issue where you can go back, but everything you do is broken due to the meeting already having been closed, but this is not explained as the reason.
> I hope this helps, and you fix the underlying issues.

 

All the best,

**Comment by mattkrick** [comment]
fixed via tooltip
