### ISSUE TITLE
Confluence integration design

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#2731]
## Issue - Enhancement

I spent an hour speaking with [this Techstars mentor and prospective enterprise user ](https://app.hubspot.com/contacts/3888472/contact/3259151?_ga=2.111752708.1231942865.1552856552-878808957.1506393023) collecting the following AC.

They conduct and capture their retros in Confluence today using a similar format as specified below. I think it's a good starting place for us, too.

### Acceptance Criteria (optional)
Users belong to a team can:
   - **Add the Confluence integration**:
      1. Select the Confluence integration from the team settings page
      1. Hit a button to "Link My Account" and complete OAuth with Atlassian / Confluence – **Oauth may not be possible, design out the true flow**
      1. See a listing of meeting types supported by Parabol below header labeled `Export meeting summaries:`
         1. Under each meeting type find the control `Add Space`
         1. When clicked, select a Confluence space user has permissions to export to
         1. After configured, provide delete controls to remove the configuration

   - **Have a meeting summary automatically exported to Confluence Space as a Page:**
      - Title is `Date – Team – Retrospective`
      - Attendee table (present yes or no)
      - Header for each theme
         - Verbatim reflections given as table with columns `Prompt` and `Reflection Text`
         - Take-away tasks given in table with columns `Assigned to`, `Due Date`, and `Task` (task text should be rich i.e. links should be clickable)

- **Design uncertainty:** 2
- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
As per @mattkrick we'll have to do some research into authenticating with Confluence. Perhaps we should add an integration or 2 to our own Confluence instance and see what it looks like – are API keys the only way to do this? Ugh, if true.

**Comment by ackernaut** [comment]
- [Example in Confluence for a single retro meeting](https://parabol-action.atlassian.net/wiki/spaces/PTM/pages/3801319?atlOrigin=eyJpIjoiMzUxMDFkMjk1Nzk1NDRiZjk1NGUzMzNiMGZjYTFjNzkiLCJwIjoiYyJ9)
- [Meeting Notes index in Confluence](https://parabol-action.atlassian.net/wiki/spaces/PTM/pages/3964946/Meeting+notes?atlOrigin=eyJpIjoiMzUxMDFkMjk1Nzk1NDRiZjk1NGUzMzNiMGZjYTFjNzkiLCJwIjoiYyJ9)

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/5157151/) wrote into Contact to request this feature.

**Comment by jordanh** [comment]
[A prospect](https://app.hubspot.com/contacts/3888472/contact/3350251/) requested this:

> "Do you have a Confluence integration?"

Before a meeting starts, they want to configure their retro meetings to be published to Confluence with a table of themes, and reflections augmented with the prompt that generated them

They'd also like a list of tasks generated, optionally with an @mention of the Confluence user who the task was assigned to, and cc @mentions for any @mentions in the Parabol task (tricky!)

They'd also like a different class of option, just a set of notes, ideally with a new note-taking area given for each theme

**Comment by jordanh** [comment]
A prospect requested:

> "Do you have a Confluence integration?"

I asked, "how would you expect it to work?"

> "We'd like to take a Takeaway Task and have it begin to create a page in Confluence we could expand on later

☝️ this is an interesting use case. It makes me think that Confluence isn't about sending retro summaries (alone), but more as a place to draft working agreements. I like this idea more

**Comment by ackernaut** [comment]
That’s perfect. In abstract, I wish I could create a link on text anywhere and create a named doc by type of my choice. This way one could thread in the right space with the right kind of artifact. Back to our UX, representing this with an integrated card is just more of an object-oriented UI. Ultimately it’s really just a shortcut for a “Made a Thing in Space about Topic” task where the intent is to keep the workflow moving forward.

**Comment by jordanh** [comment]
See: https://support.hugo.team/article/348-about-confluence-hugo

**Comment by gcrickman** [comment]
Sat in on a retro with [a user](https://app.hubspot.com/contacts/3888472/contact/8385701) 🔒  and his team, here are some notes and quotes regarding confluence:

Started retro in confluence with sprint report - rating sprint from each person
-went over tickets, reaching goals, props and praises
A user was switching between confluence and Parabol to wite reflections

> Love action items but forget about them, sometimes we just put them in Confluence

**Comment by mattkrick** [comment]
i don't see this happening in the next year, iceboxing

**Comment by garethaledavies** [comment]
Response from someone who entered our inactive user flow. Reason for churn:

> It doesn't integrate with Confluence

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/22796701) 🔒  mentions:

> Confluence export would be cool - I have a wiki page for a specific retro, what the action items were.

**Comment by drewhousman1010** [comment]
A[ user ](https://app.hubspot.com/contacts/3888472/contact/66525901) 🔒 asks:

> If you have made comments in Parabol can those be integrated into Jira or Confluence?

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/73832801) 🔒 writes: 

> hello please advise if it possible to safe all summary from the Retro Meeting to Confluence?
