### ISSUE TITLE
Disable retrospective anonymity 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#2806]
## Issue - Enhancement

[A user gave us](https://app.hubspot.com/contacts/3888472/contact/3670601) the following feedback:

> We used your tool parabol for a retro today and realized there was a significant drop of involvement during the discussion phase which we feel might be owing to comments being anonymous…Is there a way to show who the comment is by at that stage?

### JTBD

When I run a retro in a culture where we individually discuss each reflection we wrote, I want to be able to see who wrote them, so that as a facilitator I can call on each person to share and add color

Just before I start a retro, I want an option to disable anonymity, so that we can have each card author be identified to share more color on their reflections

### Acceptance Criteria (optional)

Pending more feedback...

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/3861651) said:

> Good to have option for things not to be anonymous. It’s a cultural choice. It’d be great to be able to see who authored each card. A facilitator control to be able to enable this would be useful.
> 
> Showing the cards in the brainstorming phase is not interesting.

In particular, the user is pointing at a facilitator control that would show who wrote each card. It would save time from having to ask "who wrote this one?"

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/5294101) said:
> Requiring everyone to use the first 15+ minutes of our meeting to create cards on the board - along with the complete anonymity - has really encouraged them to open up and speak their truth (and what good is a retro without truth?)!

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/6231351) said: 

> ...we'd like to see who wrote each card in our retrospectives. Is this possible?

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/7111951) 🔒 said:

> Ability to have anonymous and non anonymous retros

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/7408551) 🔒 said:

> ability to conceal or reveal identity, distinguish unique comments, are cards from same person or different people?

**Comment by mattkrick** [comment]
> We used your tool parabol for a retro today and realized there was a significant drop of involvement during the discussion phase which we feel might be owing to comments being anonymous…Is there a way to show who the comment is by at that stage?

The threaded discussion solves this tension

> Good to have option for things not to be anonymous. It’s a cultural choice. It’d be great to be able to see who authored each card. A facilitator control to be able to enable this would be useful.
Showing the cards in the brainstorming phase is not interesting.
In particular, the user is pointing at a facilitator control that would show who wrote each card. It would save time from having to ask "who wrote this one?"

This is a desire for autocracy, will not implement.

> ...we'd like to see who wrote each card in our retrospectives. Is this possible?

valid. can make it easier by offering a toggle

> Ability to have anonymous and non anonymous retros

valid, note this is for the whole retro, not just single items. if I'm participating & i don't feel comfortable sharing, i won't share. IMO this is a slippery slope because it makes it easy to have a bad meeting, which means we're not adding the value we should be.

> ability to conceal or reveal identity, distinguish unique comments, are cards from same person or different people?

this is interesting. the desire is to give all cards by the same author a tag. that tag doesn't necessarily have to be the author's name

**Comment by gcrickman** [comment]
A user writes via chat:

> I don't want to turn off anonymity, I just want to be able to see who authored reflections if for example some rules were broken (e.g. being civil). Basicaly we have 3 retrospective rules: 1. Be civil 2. Be anonymous no one can force you out and 3rd added later: if 1 is broken it revokes 2.
> IMHO it is a valid use case.
> 
> So I am looking for a feature that will allow e.g. organisation owner to discover who was an author of specific reflection after the meeting. Does that feature you talked about will do that?

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/6576801) 🔒  writes: 

Is there a comment a chance to disable comments for the administrator (my team is very childish and they use it improperly – eyes rolling)?

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10447851) 🔒  writes:

> I think defaulting contributions/"reflections" from the team to be anonymous and invisible until the grouping stage is a good basic restriction, but there are times when I'd like to encourage my team to be more open and collaborative in their idea generation.
> Before my team went remote, we would "turn over our cards" one at a time, each person briefly reading out their contribution with a very brief statement. This helped everyone make sure they all understood what was being suggested or described before we got to a grouping phase and also helped spur additional thoughts sometimes.
> 
> With the cards being anonymous, it's uncomfortable and time consuming to ask "hey who wrote this, what does it mean".
> Although sometimes anonymous is great, the openness and ownership that comes from putting your name to a contribution, and the brainstorming activity of seeing ideas as they come in, can also help advance a team.
> 
> I'm wondering what kind of options can be added to this phase of the parabol retro to allow agile coaches to further tailor it to their teams particular need in that retro. (similar to the ability to control the vote settings, which was a great addition btw!)

**Comment by gcrickman** [comment]
[User](https://app.hubspot.com/contacts/3888472/contact/11132301) 🔒  feedback: 

> We want to be able to toggle anonymity, it's easier to discuss if we know which idea was authored by who, our workaround is to include initials

**Comment by shawneeatparabol** [comment]
[User](https://app.hubspot.com/contacts/3888472/contact/8445901/)🔐 writes in that they are having uncomfortable retros due to anonymity of cards and would like to be able to see who is writing incomplete and inappropriate cards.

**Comment by gcrickman** [comment]
[User](https://app.hubspot.com/contacts/3888472/company/2151698217/) 🔒  feedback:

> One thing that might be useful is to have non-anonymous reflections as an option, sometimes we use initials to identify who wrote a card, everyone takes turns explaining the cards they wrote

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/17236501/) 🔒  writes:

> We find that accountability works better when reflections aren't anonymised. (Adding context helps too!) A group our size (10) also found it pretty tough to group answers into themes, even when we wrote our initials on the cards. It took ages to assign to themes.

**Comment by wverdese** [comment]
+1We start our retrospectives with the[ prime directive](https://retrospectivewiki.org/index.php?title=The_Prime_Directive), to give the participants the confidence

**Comment by wverdese** [comment]
+1

We start our retrospectives with the[ prime directive](https://retrospectivewiki.org/index.php?title=The_Prime_Directive), to make the participants feel in a safe space, where they feel confident and accountable for sharing their observations while in a safe space. 
Then we introduce them to a tool that collects their input anonymously, which kinda drives them in the opposite direction.

Until this is not addressed, I'm afraid we can't use Parabol for remote retrospectives. In fact, I won't recommend this tool to any team that wants to build a team where everybody trusts each other and share their knowledge.

**Comment by jordanh** [comment]
@wverdese thank you for the feedback

Clarifying question: is it insufficient to ask folks to write their initials/names on the reflection cards?

**Comment by wverdese** [comment]
@jordanh thanks for following up so quickly.
We tested this workaround. Despite the fact that it's hard to find each person's entry on the board, it messes up with the clustering feature.
e.g. if you group together:
- "Walt: better communication"
- "Jordan: communicate better"
the title of the cluster will be something like:
- "Walt Jordan communication"

**Comment by jordanh** [comment]
@wverdese this was the kind of thing I needed to hear! Ok, I think you may have tipped the scales toward us doing something here...

**Comment by jordanh** [comment]
[A customer](https://app.hubspot.com/contacts/3888472/contact/18850151) writes:

> the feature we would love to have in my team would be to be able to reveal the tickets one author by one author. So that a person is able to easily filter and show to the other the very tickets he/she wrote. To emphasize why he/she has put them, what do they mean. And after everyone has explained his/her thoughts, making everything visible for everyone.

**Comment by drewhousman1010** [comment]
A[ user](https://app.hubspot.com/contacts/3888472/contact/14061851/) 🔒  writes: 

"It'd be interesting if retros could be non-anonymous 

We have a high trust level within the team so it's not as helpful to have anonymity. I'd like to be able to see who didn't vote yet. 

Also, in terms of clicking 'next,' it's hard for the facilitator to know if they need more time or if they should give a nudge when everything is anonymous."

**Comment by jordanh** [comment]
A user writes:
> As a Facilitator; I want to have some way of quickly scanning the list of participants in a Board, with a view of which ones have/haven’t added reflections to it; so that I can determine whether a sufficient # of participants have shared, to be able to accomplish the goals of the Retro.
> 10-12 participants – hunch that only ~4-5 have entered data, but no way of confirming that

Texture behind this feedback. User is a consultant using Parabol at BigOrg. They use Parabol like a survey, gathering up information across a number of stakeholders async. They want to be able to ping stakeholders who haven’t answered yet to make sure they have their feedback incorporated before meeting with a subset of the group to process the remainder of the feedback sync

**Comment by jordanh** [comment]
@ackernaut I am sensing there might be an interesting design BP in processing the feedback from this thread into a set of lo-fi solutions. WDYT?

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/16498501) 🔒 says: 

> It would be great to have the option for non-anonymous retros. Our team adds names to all our cards. Anonymity is not important for high trust teams that do sprint retros consistently.

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/20980601) 🔒 says: 

> I'd like the ability to run retros without anonymity. People on my team always put their names on cards. They want to be identified with the cards they wrote and it slows the meeting down when we have to be anonymous.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/17542651) 🔒  writes:

> can we do non-anonymous retros? We go through groupings, get to reviewing cards, and the first question is always 'whose card is this?'

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/37130451) 🔒  says:

> I would like to non-anonymize cards. I find non-anonymous interactions are better. If you want to say something you should be able to say it transparently and the team should be okay with that. If I could have the option I would turn off anonymity." 


A recording of these comments as part of a grain story can be found in "notes" [here ](https://app.hubspot.com/contacts/3888472/contact/37130451)🔒 :

**Comment by gcrickman** [comment]
this [user](https://app.hubspot.com/contacts/3888472/contact/25168451) 🔒  mentioned they could also benefit from non-anonymous reflections for brainstorming purposes. In this case, it would be so others can ask the person who wrote the card questions. It sounded like something they would like to do prior to a retro, maybe a separate phase?

Here's paraphrasing what was said: 

Kind of brainstorming, different members can write their thoughts that aren't  hidden from others (notes) brainstorming, open stickers and then stickers can be moved to different areas, connect some thoughts from a specific topic
Could make for a more open discussion, want the option to make the reflections non-anonymous. Use as a base for discussions, maybe when we have a group of notes we can gather this in the retro template

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/18394951) 🔒  writes:

> We've been using Parabol for a while and one thing that would be nice is to have an option to make the notes non-anonymous or at least non-anonymous by default with an option to submit anonymously. I think there are some situations where knowing who wrote the card saves time and leads to more productive conversations. We're a small team anyway so the game of "I didn't write this" creates a weird dynamic and as the facilitator, I'd prefer to only discuss topics that people are comfortable coming forward with. There are other venues to bring up more sensitive topics that aren't suited for a project retro for example.

**Comment by jordanh** [comment]
Came up a few times in [this user feedback retro](https://action.parabol.co/meet/6hx9Th8FMc/discuss/1) 🔒

**Comment by nickoferrall** [comment]
One way we could approach this is:
- Have the option of disabling anonymity while defaulting to anonymous
- If anonymity is disabled, the author’s name is added to the reflection by default, but there’s an option of adding an anonymous reflection too, in the same way that users can currently add anonymous comments

**Comment by jordanh** [comment]
Removing from backlog and closing in lieu of Discussion: https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/54665901) 🔒 writes:
> One other thing I’d love to see in Parabol is the option to have a name tied to a card. Thats one thing in fig jam that we’ve liked. I also realize that some people may want anonymous retros, but for our case we talk through everything very openly.

**Comment by jordanh** [comment]
See: #5419

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/78659101) 🔒 asks:

Hi! Can I turn off anonymity while running a retro?

**Comment by ackernaut** [comment]
Closing in favor of forward motion seen in the design issue #5419
