### ISSUE TITLE
Retro discuss thread designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#2808]
### Acceptance Criteria
- Design uncertainty 3, lo-fi concepts explored and validated internally
  - Sketch candidate solutions, features, states
- Design uncertainty 2, mid-fi concepts explored and validated internally
  - Figma prototype/concepts that support best ideas
- Find 3 users who run async and validate concepts
- Write implementation issue(s)

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick and @ackernaut how did we decided we were going to handle the number of votes? Is it, "if you ever connected to the retro link, will add 5 votes for you"?

**Comment by mattkrick** [comment]
correct

**Comment by ackernaut** [comment]
Upgrading to level 2 (make some mid-fi concepts) but will sketch more ideas if needed to move faster toward better Figma prototype(s)

**Comment by jordanh** [comment]
[A prospect](https://app.hubspot.com/contacts/3888472/contact/3350251/) writes:

> When we are discussing the reflections in each theme, I think I want to be able to take notes under a theme.

**Comment by ackernaut** [comment]
Another [user](https://app.hubspot.com/contacts/3888472/contact/1274051/) 🔒 writes:
> comments on ideas and action items
