### ISSUE TITLE
Refactor Provider into GitHubAuth

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#2812]
Each provider has different requirements. We broke out Atlassian, GitHub is half broken out...

AC
- [ ] Provider table is replaced with GitHubAuth
- [ ] Provider GQL type goes away
- [ ] can access auths from User object (+ teamId arg)
- [ ] removeProvider gets refactored into 2 mutations
- [ ] addProvider gets refactored into 2 mutations

effort: 11 points

**Comment by jordanh** [comment]
Scrubbed. Added to project, added label and milestone.

**Comment by jordanh** [comment]
Scrubbed. Tightened AC

**Comment by mattkrick** [comment]
keeping open, we'll address this in the planning poker GH integration

**Comment by mattkrick** [comment]
removing stale. it seems that a GH poker integration in imminent.
