### ISSUE TITLE
refactor service provider logos from images to svg components

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#2823]
AC
- [ ] remove `.svg` uses of logos (eg github)
- [ ] use `GitHubSVG` instead

Effort: 10.5 points

**Comment by ackernaut** [comment]
The only caveat here is that I think we may want to use full color logos for cards, and flat logos for UI. I’m ok making 2 components: `ThingLogo` and `ThingLogoFlat`

**Comment by jordanh** [comment]
Scrubbed. Added to project, added label and milestone.

**Comment by jordanh** [comment]
Iceboxing for now
