### ISSUE TITLE
Fix Variable '$teamId' is not in scope.

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#2826]
currently can't share fragments between queries & subs because the queries have an extra variable in the scope (teamId). need to frame the fragment in such a way that it can be shared. will probably require writing an updater.

AC
- [ ] AtlassianAuth fragments are shared with team subscription

Effort: 11 points

**Comment by jordanh** [comment]
Scrubbed. Added to project, added label and milestone.

**Comment by jordanh** [comment]
@mattkrick says:

> This will come back to bite us, when it's ready [to].

Iceboxing for now
