### ISSUE TITLE
Remove link unfurling on Slack messages from Parabol integration

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#2877]
Today, slack notifications from our app are ugly:
```
Parabol APP [4:22 PM]
*Parabol Testing has started a meeting!
To join, click here: https://action.parabol.co/meeting/Sk6yiuiwG
action.parabol.co
Parabol is a free online retrospective tool. Try it without creating an account. Parabol features custom templates, powerful analytics, multi-user grouping, rich text editing, integrations, and gorgeous meeting summaries. Tasks are assigned and tracked so your team can continuously improve.
```

AC
- Remove link unfurling on Slack messages from Parabol integration

Effort: 10.5 points

**Comment by mattkrick** [comment]
is this really emergency?

**Comment by jordanh** [comment]
Scrubbed. Added milestone.

**Comment by jordanh** [comment]
Scrubbed.

This Issue is now available for our community to implement under our _Equity for Effort_ program.

**Comment by mikennaji** [comment]
Whats specification on this? 

Remove link unfurling on Slack messages from Parabol integration...

Is the intent want to make the readout nicer or just remove  

"Parabol APP [4:22 PM]
*Parabol Testing has started a meeting!
To join, click here: https://action.parabol.co/meeting/Sk6yiuiwG
action.parabol.co
Parabol is a free online retrospective tool. Try it without creating an account. Parabol features custom templates, powerful analytics, multi-user grouping, rich text editing, integrations, and gorgeous meeting summaries. Tasks are assigned and tracked so your team can continuously improve.

Thank you!

**Comment by nickoferrall** [comment]
Closing this issue as #4988 resolves this
