### ISSUE TITLE
Emojis not encoded properly in CSV export

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#2947]
## Issue - Bug

A user requested this one:

> Hi,
>
>When I download the CSV with I can notice some weird characters if the user use emojis
>
> ![unnamed](https://user-images.githubusercontent.com/103000/59293480-221c9f80-8c34-11e9-94ac-35c994be358c.png)
>
>Maybe when exporting the emoji should be converted into a code like `:stopwatch:`

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Download a CSV file containing emojis and see them properly encoded, or, see a English textual representation of them

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
It might be that the .csv file does not state that it's UTF-encoded.

**Comment by mikennaji** [comment]
10.5 points to 🎾 this 🦗 !
