### ISSUE TITLE
Asana integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#2950]
Collecting feedback here on requests for an Asana integration:

[A user](https://app.hubspot.com/contacts/3888472/contact/3191701) writes:

> We used parabol for our leadership meeting today. Loved it. Way better time management and intentionality. It also got more voices involved through the solo updates. 
>
>Initial asks (product feedback)
>-Asana integration (you know this)

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now. Will reopen upon additional user feedback

**Comment by jordanh** [comment]
Pulling this one out of the ol’ icebox:

[A user](https://app.hubspot.com/contacts/3888472/contact/130951) writes:
> Biggest blocker for recommending Parabol at the moment is the lack of support for syncing tasks to Asana.

**Comment by kael-shipman** [comment]
+1 for Asana integration

**Comment by acressall** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/94401051) writes:

> Is an asana integration on your roadmap??

**Comment by acressall** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/103845451) 🔒 writes:

> Hey, one of my coworkers recommended this tool for use with sprint planning and retros. I absolutely love the layout and the forward thinking on spint-planning/retros. I think the final clincher for my team would be integration with Asana (our current scrum tool). Any chance thats on the roadmap?

**Comment by kateEcobb** [comment]
would love to see this!

**Comment by drewhousman1010** [comment]
An [Enterprise user](https://app.hubspot.com/contacts/3888472/record/0-1/17842337337) 🔒 writes: 

> Would there be any plans to have Asana integration for Parabol? My new team uses Asana heavily, and it would be nice to have the integration to increase usage of Parabol.
