### ISSUE TITLE
Azure DevOps integration requests

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3004]
Tracking requests and feedback for an integration with Microsoft Azure DevOps. Any details directly from users (leave comments!) or verbatim data from users as to what features they’re looking for in an integration only make this issue mucho more better.

**Comment by ackernaut** [comment]
From a first user and developer:
>For now I’m seing a few options:
Parabol users, would finish the retrospective meeting, create tasks, with the possibility to export to the Azure DevOps projects
Here they could be simply created as workitems (of type epics, user stories, tasks or bugs or whatever)…it would be cool the UI in parabol allowed you to specify the kid of workitem
Again they could create workitems, but in a way that would be synced with the Retrospective extension.
Let me understand how Retrospective works
Pretty sure they still use workitems, and then they have a specific UI to show the retrospective meetings outcomes.
But still, everything should be based on basic concepts in VSTS.

**Comment by ackernaut** [comment]
From [another user](https://app.hubspot.com/contacts/3888472/contact/6419051/):
>Hey! I really am enjoying the look of Parabol, and I'm bringing it to my team soon. I just wanted to put the request in for an integration with Azure DevOps for task creation and tracking.

**Comment by ackernaut** [comment]
From another [user](https://app.hubspot.com/sales/3888472/contact/7167401):
>Microsoft's own solution of "Azure DevOps" wasn't capable of performing retrospective meetings among teams are not colocated, and parabol solved the issue for us. Thank you for your application and the effort you put into it. I personally suggested Microsoft to develop a retrospective section within Azure DevOps which is powered by parabol :) I hope it will happen in near future.

**Comment by jordanh** [comment]
From prospect who started a chat on our marketing page:

> Hey guys, is there a Azure DevOps integration planned for the future?

> Is this something your team would use?

> Yes...it would be nice to have retrospective tool easy to use in azure

**Comment by sheldonhull** [comment]
I think that #3499 is a duplicate. This is a great tool and would love to see Azure DevOps integration added. Adding my +1 and will ask all the folks I know to also add a plus one to the main thread to show support.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/12393401) 🔒 writes:

> I have one question regarding the integration features of Parabol: Is there a plan to integrate Parabol into Micosoft Teams and/or Microsoft DevOps (cloud and on-premise)?

**Comment by jordanh** [comment]
[A user (soon to be enterprise customer)](https://app.hubspot.com/contacts/3888472/contact/7270101) 🔒 writes:

> Our IT department uses Microsoft DevOps. Could you add this integration?

**Comment by garethaledavies** [comment]
Someone I did Sprint Poker outreach to:

> I’m one of the very few who has used JIRA recently. And, even though it’s built by Atlassian here in Australia, I don’t like it much at all.
> 
> Let me know if you have an integration with Azure DevOps coming up and I’ll review Parabol for my YouTube channel.

**Comment by jordanh** [comment]
@gcrickman please continue to log the feedback you here too. We want all the signal we can around this item

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/15617101) 🔒  mentioned:

> If you add tasks - We would want a link with Azure DevOps

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/8796601) 🔒 mentioned while discussing Sprint Poker:

> Would be useful to have a MS DevOps integrations, we don't use Jira

**Comment by jordanh** [comment]
A signed enterprise trial 🔒 shared:
> our teams all use Azure DevOps, and we'd love a DevOps integration so Sprint Poker and retros would be even more useful

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/3538751) 🔒 writes:

> Hey, are you guys planning an integration with azure devops? Would be nice to use the new sprint poker feature on azure devops workitems...

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/29584251) 🔒  writes:

> I guess it would be nice to add Azure DevOps Integration.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/10688651) says:

> We would like an Azure DevOps integration

**Comment by rceleslie** [comment]
+1 to ADO integration

**Comment by sheldonhull** [comment]
Still would like to see this so bumping with a comment. Azure DevOps isn't going away for a long while for most enterprises, despite the initial GitHub migration hype.

**Comment by jordanh** [comment]
> Still would like to see this so bumping with a comment. Azure DevOps isn't going away for a long while for most enterprises, despite the initial GitHub migration hype.

You'll be happy to learn we're actively developing this integration now. Please [follow along here](https://github.com/ParabolInc/parabol/milestone/125)!

**Comment by jordanh** [comment]
Grooming: Closing this discussion issue as we've committed ourselves to action
