### ISSUE TITLE
Navigating card groups in retro

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3021]
From Sam @ The Ready [via Twitter](https://twitter.com/samspurlin/status/1149668481501036545)

>Idea for you based on The Ready's retro yesterday: When sorting cards into piles, new piles should "float" to the top so it's easier to distinguish single cards from piles. We had over 100 cards going and it was a little tough to navigate.

**Comment by ackernaut** [comment]
Some more design feedback from Springboard design student, Kashif Ross, paraphrased:
- Folks can’t see what cards are in a group unless the click on them
- Are there ways to show the cards in a group without having to open the group?
- Can the cards use less height overall?

**Comment by ackernaut** [comment]
Somewhat similar feedback from a [user](https://app.hubspot.com/sales/3888472/contact/6507651):
>Allowing the submitted topics to be arranged more easily. One idea around this was perhaps to allow users to create some topics manually at the top of the arrangement area, rather than only being limited to dropping cards on each other.

**Comment by jordanh** [comment]
Scrubbed.

There will never been an end to group phase discussion threads. Will reopen this one when we get more feedback here
