### ISSUE TITLE
New meeting lobby designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3028]
### Acceptance Criteria
Design uncertainty: 2
#### Artifacts
A set of clickable concepts for both mobile and laptop+ that illustrate how a user can:
- Navigate to the new meeting view (simple examples, not scoped to solve all the AI involved)
- Name the meeting
- Select the meeting type and/or
- Select the meeting template
- Select the team that owns the meeting
- Invite by email or invite link
- Configure custom extras such as:
  - Opting in to the Social Check-In round
  - Opting in to Slack notifications?
- See any inline tips
- See any help menus
- Start the meeting
- Stretch concept: a user can see recently held meetings and choose to run one again
#### Testing
Tested with users:
  - 1 lead tester via video sync
  - 1 lead tester via async comments (experiment)
  - 3 random User Bobs
#### Implementation
- Implementation issue written

### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Validation for naming meetings. [A user](https://app.hubspot.com/contacts/3888472/contact/7288801) writes: 

> Could you please consider making the title of a retrospective editable? My team is at Sprint 60 an currently I have Retro#1 which is hard to map on our actual sprints.
