### ISSUE TITLE
Create new team race condition 🏁

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3043]
### Steps:
- Create a new team
- Instead of being redirected to the new team, you see the invitation required dialog
- You also see the confirmation snackbar
- Bug is intermittent, no better steps yet
- You can go to `/me` and then you should see the new team in the left navigation and can click through to it

**Comment by ackernaut** [comment]
I’ve seen this about 3 times now, a few times locally, and maybe even once on staging but couldn’t reproduce.

**Comment by ackernaut** [comment]
This happens more often when creating a new organization using the new team form.

**Comment by ackernaut** [comment]
Saw this again while creating a new team on an existing org on staging, testing `v4.1.0`. I could see my team when refreshing.

**Comment by jordanh** [comment]
I think I saw it on dev, but haven't seen it on production. Will leave on backlog and add repo steps if seen again

**Comment by ackernaut** [comment]
I wonder if this is related. I created a new user on staging but didn’t have a team or org. I then created a first org and first team using the new team form.

**Comment by jordanh** [comment]
Haven't seen this awhile. Iceboxing for now
