### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for com...

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3047]
Updated 05/07/2021:

https://sentry.io/organizations/parabol/issues/2239143092/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

```
Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

Affecting 12 users in last 14 days

**Comment by tianrunhe** [comment]
Reopening as it appears in Sentry again: https://sentry.io/organizations/parabol/issues/2239143092/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

**Comment by tianrunhe** [comment]
Sentry issue: [ACTION-PRODUCTION-5A7](https://sentry.io/organizations/parabol/issues/2239143092/?referrer=github_plugin)

**Comment by Dschoordsch** [comment]
Sentry issue: [ACTION-PRODUCTION-9MT](https://sentry.io/organizations/parabol/issues/2639345595/?referrer=github_plugin)

Happened 11 times to 11 users in past 30 days

**Comment by jordanh** [comment]
No longer occurring. Closing
