### ISSUE TITLE
Rebrand Action in landing page

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3057]
AC:
- [ ] Indexed materials now point to check-in (check-in or Check-in, not Check-In)

https://www.google.com/search?q=site%3Aparabol.co+action&oq=site%3Aparabol.co+action&aqs=chrome.0.69i59j69i58.2968j0j7&sourceid=chrome&ie=UTF-8

Effort: 11 points

**Comment by avivapinchas** [comment]
There's only one thing mentioning 'action' meetings, and it's a blog post, so not too worried about it. Closing this as 'done'.
