### ISSUE TITLE
Relay compile error when run yarn workspace parabol-server relay

### ISSUE THREAD

**Issue by nhannv** [ParabolInc/parabol#3078]
## Issue - Bug

- **OS:** Windows
- **Browser:** Chrome
- **Node version:** v11.14.0
- **NPM version:** 6.4.1
- **RethinkDB version:** 2.3.6-windows (MSC 190024215)

I just pull the latest master then run `yarn` and `yarn dev` as normal. I got stuck at relay-compiler with this error message:

```
ERROR:
Parse error: Error: RelayFindGraphQLTags: Operation names in graphql tags must be prefixed with the module name and end in "Mutation", "Query", or "Subscription". Got `Components` in module `pages`. in "node_modules/react-transition-group/www/src/pages/index.js"
```

This is because we are running relay-compiler to compile graphql code in folder `client` including node_modules folder. I checked in index.js of react-transition-group module, it contains graphql query with the operation name is `Components`, this is not following convention of GraphQL tags which required operation name be prefixed with the module name and Query.

I already tried to exclude node_modules in relay-complier but not work. So I deleted the folder react-transition-group then run `yarn dev` and it works. This is just a work around because it will fail when rerun yarn command.

**Comment by jordanh** [comment]
@nhannv our codebase has changed quite a bite since you reported this. We're going to close this issue for now. Would you mind commenting if it is still an issue with a fresh checkout?
