### ISSUE TITLE
Payload optimizations

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3079]
A list of low hanging fruit if we want to decrease page load speed:
- [ ] inline font requests in the HTML file. Since fonts rarely change, i'd be OK with doing this as a one off & just fetching them from google fonts.
- [ ] combine service worker and precache manifest. the perfect service worker file is a single line that calls `importScripts(hashedScript)`. Since this gets called a lot to determine validity, it's advantageous to keep it short.
- [ ] remove pieces of Relay. Aside from react dom, Relay runtime is one of the biggest assets we serve. getting rid of parts (eg network cache, publish queue, etc) woudl save a few KB
- [ ] inline client keys in the webpack build. since we build once per environment, it's safe to just inline the keys. this is the last step to having a static html file. Once we get that, we can server it via S3 if we want.

EE 12 points

**Comment by jordanh** [comment]
Scrubbed, iceboxing
