### ISSUE TITLE
Design Dashboard Skeleton

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3080]
AC
- [ ] design a skeleton of the dashboard. show what it should look like without having any data. 

After the design is complete, we can turn it into HTML & send that HTML down. After everyone abandoned SSR, this is the happy medium that everyone came to (see github. their skeleton is super clean!)

**Comment by ackernaut** [comment]
How can I see GitHub’s skeleton?

**Comment by mattkrick** [comment]
![Screenshot from 2019-08-05 17-30-54](https://user-images.githubusercontent.com/5514175/62502939-d22b0680-b7a6-11e9-9752-4c50ec3395c3.png)

**Comment by jordanh** [comment]
Scrubbed, iceboxing
