### ISSUE TITLE
Android editor crashes discuss phase

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3114]
### Repro
- This has been intermittent
- I think it only happens on Android Chrome (can’t repro on laptop)
- Advance to the discuss phase
- Tapping to create the first task card causes a crash
- I think this is [the issue](https://sentry.io/organizations/parabol/issues/1170816149/?project=107196) in Sentry

### AC
- No crashing when creating a task card
### EE
- 10.5 pts

**Comment by jordanh** [comment]
Scrubbed, iceboxing
