### ISSUE TITLE
Group phase prompt colors implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3124]
Based designs from #3104 

See #3033 

### Acceptance Criteria
- The [template editor has a menu](https://www.figma.com/file/d2OGg3CGIPCBb5IIGf40x6to/Custom-Reflection-Prompts?node-id=187%3A0) that allows users to select from a limited palette (similar to Google Calendar)
  - The same color can’t be used twice per template
  - A checkmark shows which color is selected
  - The other colors in use for the current template being edited are at a lower opacity
  - A user can select one that’s already in use, but it updates the other prompt to randomly have a color not in use
  - Currently we limit a template to have 12 prompts, so I recommend offering a palette of 12 colors
- The prompt headers have a color indicator ([see Figma](https://www.figma.com/file/d2OGg3CGIPCBb5IIGf40x6to/Custom-Reflection-Prompts?node-id=169%3A1964))
- The reflection cards have a watermark ([see Figma](https://www.figma.com/file/d2OGg3CGIPCBb5IIGf40x6to/Custom-Reflection-Prompts?node-id=169%3A1964)). Optional: on hover it has a title tag or tooltip with delay stating the prompt (this might be handy if the card’s in a context without the header)
- Here’s an example of [the Reflect phase](https://www.figma.com/file/d2OGg3CGIPCBb5IIGf40x6to/Custom-Reflection-Prompts?node-id=201%3A3876) w/ prompt color indicators
- [Default templates](https://parabol-community.slack.com/archives/C0NAJHETD/p1583862851007600?thread_ts=1583859232.000800&cid=C0NAJHETD) have their colors assigned; [migration needed](https://parabol-community.slack.com/archives/C0NAJHETD/p1583862960007800?thread_ts=1583859232.000800&cid=C0NAJHETD)?
- The demo is updated to use the prompt colors

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
In Figma:
- The [latest concepts](https://www.figma.com/file/d2OGg3CGIPCBb5IIGf40x6to/Custom-Reflection-Prompts?node-id=172%3A129) for adding prompt color selection to the template editor
- What [a default palette of 12 might look like](https://www.figma.com/file/d2OGg3CGIPCBb5IIGf40x6to/Custom-Reflection-Prompts?node-id=169%3A1964) on prompts and cards

**Comment by jordanh** [comment]
A user writes:

> Amazing product, just thought I'd suggest to add the respective labels after grouping cards during liked/lacked/longed, could be good to see if the groups contain mostly positive or negative cards when expanding the groups (or during the voting).

**Comment by jordanh** [comment]
Closing in favor of #3774
