### ISSUE TITLE
Kanban/Task/Grouping multiselect and select all

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3136]
## Issue - Enhancement

I imagine we'll wait until we refactor the Kanban to be tag-driven. However, I want to open this in response to some recent user feedback. [A user](https://app.hubspot.com/contacts/3888472/contact/2529551) writes: 

> It would be handy if we could Archive all ‘Done’ tasks on the team dashboard. Now we need to do them one by one. We normally do this and the beginning of each sprint.

### Acceptance Criteria (optional)
Users can:
   - Select all cards by hitting a control at the top of a Kanban column
   - On mobile: long press a card to initiate selection, tap to select subsequent cards
   - Apply operations to multiple cards:
      - On Kanban/Task contexts:
         - Move cards to Archive 
         - Move cards to another column
         - Apply a new due date
         - Publish to the same integration destination (shown as a intersection set between all available integrations across those cards)
      - When grouping:
         - Move cards to new/existing group
         - If grouped, ungroup cards

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/6592301?) writes:

> For completed tasks, which I´m currently moving to Done, I miss the option to hide those cards. I feel that this can be done through the “Archive” option, but since I don´t yet know how to get to those, I am a little hesitant.

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/34963301) 🔒 writes: 

> Kills me that I cannot select all tasks in a column.
