### ISSUE TITLE
Preserve Group/Agenda context when creating task

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3137]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/2529551) wrote in with the following feedback:

> It would be nice if there was a link between the ‘Group of notes’ of the retrospective and the tasks that were created for it. Now the task should be very descriptive. We did not know this at the beginning and the name of the task weren’t clear anymore the next sprint
>
> An example would be ‘Builds fail every week’ and with task ‘Check with Support’ in place of ‘Check with support why the builds are failing every week.’

Some open questions when exploring this issue:

   - Where would the meta information appear? On a card back? On the face?
   - How would this meta work with integrations? Would it become part of the title or description (i.e. a comment in GitHub)?
   - Should this just be text, or a link to a meeting summary? Or a link to the exact phase and stage where the Task Card was created?

### Acceptance Criteria (optional)

- A set of lo-fi designs exploring this concept
- A round of internal validation

- **Design uncertainty:** 3
- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Another [user](https://app.hubspot.com/sales/3888472/contact/3430851) commented:
>From our own perspective, I think what we could find extra useful would be that the action items [tasks] would be connected to the agenda items- it's more a functionality thing because otherwise we need to repeat the agenda in the action items and starts becoming annoying if you have 20-25 items.

**Comment by ackernaut** [comment]
Another [user](https://app.hubspot.com/contacts/3888472/contact/1274051/) 🔒 mentioned this:
>possibility to see the idea the action item relates to

**Comment by jordanh** [comment]
We're eventually going to do this. I know it. I feel it in my bones. But for now, to the icebox with you!
