### ISSUE TITLE
Node process monitoring

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3143]
## Issue - Bug

After resizing our infrastructure, the node process is still leaking memory. The only difference now is the container is running out of memory not the host. We should make our deployment resilient to this condition. Some options:

### Acceptance Criteria (optional)

For discussion:

1) Increase the container memory allocation – which would buy us more runway
2) Create a data monitor that could detect and alarm the condition before it starts
3) Introduce a node process runner, like pm2
4) ?

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
what's it mean when the container is running out of memory & not the host?
you mean we're artificially preventing the container from using the full 16GB?

i'm fairly confident it's sentry, or at least how our code works with sentry. we should turn it off for a week & see.

**Comment by mattkrick** [comment]
mem leak ded
