### ISSUE TITLE
Image-related Security Issue #35

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3146]
## Issue - Bug

See: https://github.com/ParabolInc/action-devops/issues/35

While here, we'd likely also tackle server-side processing and uploading of avatar images. (TODO: find and link other issues)

### Acceptance Criteria (optional)
Users can:
   - Security issue is resolved

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
See also: https://github.com/ParabolInc/action-devops/issues/27

**Comment by jordanh** [comment]
Iceboxing for now

**Comment by mattkrick** [comment]
fixed
