### ISSUE TITLE
Meeting architecture / Meeting as API

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3149]
Starting a discussion thread here...

I've been thinking some about the future architecture of the product. Some users ([this one](https://app.hubspot.com/contacts/3888472/contact/6303601), [this one](https://app.hubspot.com/contacts/3888472/contact/6995801), and [this one](https://app.hubspot.com/contacts/3888472/contact/7113051) have asked for a Task Integrations API. I'm sure we'll need to tackle that. This issue isn't about that.

This issue is about extensibility along different lines: being able to implement custom meeting phases.

If we break down our retrospective meeting, we could consider each phase an independent piece of logic with an input and output interface. The following isn't completely accurate, but for illustration purposes:

- Check-in:
   - Input interface: none
   - Output interface: none
- Reflect:
   - Input interface: object: template columns
   - Output interface: list: reflection cards
- Group:
   - Input interface: list: reflection cards
   - Output interface: object: groups of reflection cards
- Vote:
   - Input interface: list: groups of reflections cards
   - Output interface: object: groups of reflection cards with votes
- Discuss:
   - Input interface: object: groups of reflection cards with votes
   - Output interface: object: groups of reflections cards with votes & task cards
- Summary:
   - Input interface: object: groups of reflections cards with votes & task cards
   - Output interface: link to summary

Imagine if a user wanted to fulfil the following JTBD:

When I want to conduct a brainstorming session with multiple cycles of convergence and divergence, I want to add as many reflect, group, and vote phases into the meeting on the fly as I want, so that I can get the kind of creative result me and my team are looking for

Imagine if the reflect interface were extended in the following way:

- Reflect:
   - Input interface: object: template columns **or groups of reflection cards**
   - Output interface: list: reflection cards

Then you could chain these phases together:

- Reflect:
   - Input interface: object: template columns **or groups of reflection cards**
   - Output interface: list: reflection cards
- Group:
   - Input interface: list: reflection cards
   - Output interface: object: groups of reflection cards
- Reflect:
   - Input interface: object: template columns **or groups of reflection cards**
   - Output interface: list: reflection cards
- Group:
   - Input interface: list: reflection cards
   - Output interface: object: groups of reflection cards
...

In the future, we should start by thinking about how to design a brainstorming meeting in which the phases and phase order are much more configurable. Then, we should think about how the architecture breaks down. Lastly, we should think about if an API could be exposed to allow for third-party extensibility.

### Related issue(s)
   - https://github.com/ParabolInc/action/issues/3030

**Comment by ackernaut** [comment]
Feedback from [user](https://app.hubspot.com/sales/3888472/contact/5978551):

>I would like to be able to customize the steps within a retrospective meeting.

>Within the Retro, we sometimes start with grouping before discussing. Also after discussing and summarizing not always a voting is needed, as the most important topics are obvious before. So having here the opportunity to also customize the steps would be great.

Basically I take it as they would like to group then discuss and skip the vote phase.

**Comment by jordanh** [comment]
As we think about how to implement #3861, be good to consider how to make it easier to implement future meetings types.

Scrubbed, iceboxing

**Comment by ackernaut** [comment]
From [this customer](https://app.hubspot.com/contacts/3888472/contact/3645601/):

>Us: Besides retrospectives and story point estimation, are there any other remote meetings or collaboration workflows that are a challenge for your team? Would you describe your biggest challenge?
>
> Customer: None, really. For the exiting retrospectives though I would appreciate the option to have several "Reflect" phases. I.e. After you vote for a cluster have another "Reflect" phase to gather suggestions for that cluster in a quick brainstorming.

**Comment by ackernaut** [comment]
>"Can you do two rounds of voting? Eg Round 1 – have people vote only on a single column's theme (which is past-oriented), then discuss that theme. Round 2 have people vote on the next theme (which is future-oriented), and discuss those items." ([see this](https://action.parabol.co/meet/1HJ2knTyhy/discuss/4) 🔒 )
