### ISSUE TITLE
Invoices correctly show coupon discount

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3154]
some customers have discounts applied & i have no idea how those are being handled in our system, but i doubt it's the right way. 

stuck on #3153
 
AC
- [ ] invoices are accurate

Effort: 12 points

**Comment by jordanh** [comment]
This one is now unblocked. I am going to promote it (slightly) on our backlog, rather than icebox it

**Comment by mattkrick** [comment]
looks like we already did this work but didn't close the issue & then proceeded to forget about doing the work.
<img width="612" alt="Screen Shot 2020-03-18 at 4 35 34 PM" src="https://user-images.githubusercontent.com/5514175/77009784-880e2400-6936-11ea-93b7-8ea98e66432c.png">
