### ISSUE TITLE
Audited json for emojis available on cards

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3156]
### Acceptance Criteria
- ​Updated the list of emoji characters available with more options
### Estimated Effort
- 10.5 pts

**Comment by jordanh** [comment]
Moving to Equity for Effort. Please bid on this if you, a community member, would like to pick this one up

**Comment by mikennaji** [comment]
Hi @jordanh 

I would love to take this on for 10.5 points!
