### ISSUE TITLE
unobtrusive scrollbars

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3167]
We tried doing custom scrollbars in the past, but things got difficult so we stopped since it was taking too long.

I'd still like to implement them so everyone gets the same beautiful experience that macOS users get. 

this article that was just published has a pretty cut & dry way of getting 90% there: https://www.filamentgroup.com/lab/scrollbars/

AC
- [ ] unobtrusive scrollbars implemented in the dashboard left nav

Effort: 11 points

**Comment by jordanh** [comment]
Scrubbed, iceboxing
