### ISSUE TITLE
Chore: refactor field components

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3173]
*Fields aka inputs and textareas

### Acceptance Criteria
- Limits the size variants, probably to small and default (refer to latest designs)
- Favors composability with emotion over crufty variables, props and shaping functions
- Reduces use of the deprecated `ui.js` and any helper functions

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now
