### ISSUE TITLE
Chore: refactor button sizing

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3174]
### Acceptance Criteria
- Favors composability with emotion over crufty variables, props and shaping functions
- Reduces use of the deprecated `ui.js` and any helper functions

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now
