### ISSUE TITLE
Chore: remove ui.js

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3175]
### Acceptance Criteria
- Comes after #3174 and #3173 
- Moves remaining values to enums or utils, scoped to purpose
  - Default menu dimensions
  - Settings layout
  - `HUMAN_ADDICTION_THRESH` and `MAX_WAIT_TIME`

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
