### ISSUE TITLE
Chore: move email components to TSX

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3176]
### Acceptance Criteria
- Convert remaining email components to TSX
- `styles/email.js` needs to use `paletteV2` and `typographyV2`
- Remove unused templates and components, if any

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a thing, but iceboxing for now
