### ISSUE TITLE
Chore: refactor paletteV2 variants

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3177]
### Acceptance Criteria
- Naming convention idea: `[PROPERTY]_[PURPOSE]` or `[PURPOSE]` over `[COLOR]` or [`COLOR_NUM`] ([see additional comment](https://github.com/ParabolInc/action/pull/3166#discussion_r326438686))
- Reduce repeated colors if they can share a semantic name
- Scrub components and swap const names as needed

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut took an action to write an updated version of this issue in order to phase in a new pattern and phase out the old pattern. Classic refactor.
