### ISSUE TITLE
Adds menu-based grouping per reflection card

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3187]
Based on design efforts from #3064 

A related group may be buried in another column, which I can’t see on mobile or very easily on a laptop. So this menu is designed to help folks send cards along.

### Acceptance Criteria
- Each card as an icon bottom right ([needs some iteration](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi/Meeting-Layout?node-id=402%3A14044))
- When tapping on mobile, it brings up [a dialog](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi/Meeting-Layout?node-id=403%3A71), as I think a menu would be too clumsy
- When tapping on laptop, it brings up [a menu](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi/Meeting-Layout?node-id=404%3A72), as I think a dialog would be too intrusive
- I’m open to consolidating on the dialog/menu usage or a better pattern
- In the dialog/menu, the first options are suggested groups based on natural language, then the user can scroll through the other groups
- When the user selects a group the card goes to that group and the dialog/menu closes. We may consider some kind of quick feedback like a very brief toast “Card grouped! Undo” but that may be too much
- There is a separated item allowing one to ungroup a card if it’s in a group
- The ungrouped card goes back to its prompt column
- We may feel the need to add a search input later, but can defer

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here are [the most refined UI concepts](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi/Meeting-Layout?node-id=535%3A75521) we have so far

**Comment by jordanh** [comment]
Scrubbed, iceboxing
