### ISSUE TITLE
Reset retrospective templates to default

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3209]
Capturing feedback from users here.

[A user](https://app.hubspot.com/contacts/3888472/contact/1377251) writes:

> We would like the ability to reset the Templates back to default. We are probably doing it wrong but we customize and existing template and can't seem to get it back.

**Comment by ackernaut** [comment]
Good capture. I also wonder about a “Copy this template” or “Copy a template” function.

**Comment by jordanh** [comment]
Iceboxing for now. Will revisit this AC when we look at sharing templates and UGC.
