### ISSUE TITLE
Shortcut (nee Clubhouse) integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3210]
Tracking user feedback.

[A user](https://app.hubspot.com/contacts/3888472/contact/1377251) writes:

> [We'd like to see an] integrations with Clubhouse, a tool similar to Jira Cloud.  https://clubhouse.io and https://techcrunch.com/2019/09/10/clubhouse-announces-new-collaboration-tool-and-free-version-of-its-project-management-platform/

**Comment by jordanh** [comment]
Haven't heard any more requests for this one, iceboxing closing for now.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/16956001) 🔒  writes via support:

> Hi there,
> Will you be considering integration with Clubhouse?
> Thanks,

**Comment by jordanh** [comment]
Reopening with new activity

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/34968051) 🔒  writes:

> Clubhouse.io is a pretty good planning tool and will likely grow in popularity. Please add an integration for it.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/28392901) 🔒 writes:

> Any plans to integrate your new Planning Poker tool with Clubhouse in addition to JIRA?

**Comment by jordanh** [comment]
Note: Clubhouse is about to be rebranded

**Comment by gcrickman** [comment]
We have gotten 2 requests over the past couple of days:

A [user](https://app.hubspot.com/contacts/3888472/contact/54747601) 🔒  writes: 

> does parabol have integration with clubhouse (now shortcuts)?


A [user](https://app.hubspot.com/contacts/3888472/contact/52486451) 🔒  writes:

> Love the tool! I've been using it for team retrospectives and it is slowly starting to make our retro workflows more streamlined. 
> 
> Request: any chance you could get shortcut.com (JIRA alternative) integrated into Parabol? This could help us run sprint poker on the tool a well!
>

**Comment by drewhousman1010** [comment]
An anonymous person wrote into support chat and asked:

> Have you thought about an integration with Shortcut (formerly clubhouse)?

**Comment by moekify** [comment]
Also interested on this one :)

**Comment by kendradixon** [comment]
Customer wrote into support with this feature request:

> I've used the integration with JIRA in the past with great success, and my current company uses Shortcut instead, so it'd be awesome to get similar/the same functionality with it also.
