### ISSUE TITLE
Control to indicate when it's time to move on

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3211]
## Issue - Enhancement

Opening to capture user feedback here.

Over the years we've had requests for tools to maintain equal airtime #933 and provide a timer #2952. It seems there is still an appetite for controls that satisfy one of 2 jobs:

When I have nothing more to add during an phase, I want a control to indicate its ok to move on, so the meeting can keep moving

When I am ready for an agenda item to be over (perhaps because one or more people are taking all the airtime), I want to indicate I'm ready to move on, so the meeting can be a good use of my time

### Acceptance Criteria (optional)
To be added later.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/1377251) writes:

> A way for people to say they're done filling out cards so the facilitator doesn't keep asking if everyone's done. I only use the timer when we're taking a long time, but I don't want people to feel rushed and also don't like asking if people are done (it's awkward). It would be nice if there was like a "done" button for people to mark when they're done writing cards that lets the facilitator see how many people are still writing cards so they can have time to do so.

**Comment by mattkrick** [comment]
- done isn't a 1-way flag. i can think i'm done, get a new idea, then be undone
- someone can forget to click the done button
- someone can forget to unlcick the done button when they have a new idea

overall, a "done" button is just a heuristic. 

I think a better heuristic is the one we have in place that checks to see who is typing. after all, that's what IMs & chat rooms do to discourage 2 people from talking at the same time.

**Comment by ackernaut** [comment]
From another [user](https://app.hubspot.com/sales/3888472/contact/4361701) 🔒:
>Could there be a "done" button for each person to select when they're done typing cards during the retrospective meetings? There's often an awkward pause when I look around and nobody has typed for a little bit, but I don't want to rush people or anything, so we just sit there until I finally ask "are we ready to move on?". Several of my developers mentioned that they would love to just click a button that says they're done and the facilitator can see when each "here" person has marked that they're ready to move forward to the next step (grouping).

**Comment by jordanh** [comment]
From another [user](https://app.hubspot.com/contacts/3888472/contact/1274051):

> [Important to us]: I'm ready button at every stage

**Comment by jordanh** [comment]
Some thoughts I've been having on this:

Designwise, I'd much rather have a control that provides ambient information than one that _requires_ folks press it to move on. It would be sort of like how voting works today: it's a counter. You can move on before the thing hits zero.

**Comment by mattkrick** [comment]
If we do it, i'd want it to be playful.

Idea:
- button bar goes away
- facilitator has a round "next' button
- Instead of a "next" button, participants get a "ready" button
- both ready & next buttons look identical, except for the label
- there's a progress ring around the button. clicking "ready" increments the progress. The increment animation makes the button 5% bigger, then while it's shrinking back to normal size, animates the filling of the ring (e.g. fills it from 25% to 50%)
- clicking again reduces the fill, but no change in the button size to show that it's not happy about it

**Comment by ackernaut** [comment]
@mattkrick I really like your idea. I think the goal would be to enhance with more contextual clues while maintaining a good baseline UX and UI. e.g. as facilitator I can move forward regardless, I can see folks are typing or not, but if folks indicate then I have an explicit idea of how many folks are ready

**Comment by jordanh** [comment]
[A customer](https://app.hubspot.com/contacts/3888472/contact/3034601) writes:

> First let me say, I love your product. It's fantastic. I would like to suggest that in the "reflect" step of your retrospective meetings you add a feature to allow users to mark themselves as "Done" putting in input. That way we can move on once everyone is done.

**Comment by jordanh** [comment]
@ackernaut I think we have a path forward to go to a medium-fidelity solution for this issue. May I ask you to create a design issue?

**Comment by ackernaut** [comment]
Sounds good, I saw that latest bit come in. I’ll create a design issue.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/7111951) 🔒gave us the following feedback:

> Team health check feature (this one is considered to be used by two teams at least in a future)
