### ISSUE TITLE
Clarify instructions for deleting a team

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3220]
From [user](https://app.hubspot.com/contacts/3888472/contact/6910801/), thread [here](https://parabol.slack.com/archives/CN6V74LAE/p1569958473140300):
>One task I just completed was deleting a team. I liked that I had to type the team name to confirm the delete, but found I was a little lost on what to do next since there wasn't any type of button to commit my entry. I figured out hitting Enter worked as submit (or maybe it was just navigating away from the field). it would be helpful if there was a little clearer indication of what to do next, maybe in the instructions where it says "Type your team name" could be "Type your team name and hit Enter" or something along those lines (if you don't want to go through the effort of adding a button!)

### AC
- Decide on next steps (probably just updating the label)
### EE
- 10.5 pts

**Comment by jordanh** [comment]
Stale, I think this tension may have gone away anyhow
