### ISSUE TITLE
remove proration invoice item lines for prorated enterprise clients

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3230]
the current "upcoming invoice" for enterprise clients has a TON of errors in it due to proration.
we need to manually remove these invoice lines to fix the proration.

AC
 - [ ] ~proration ii lines removed~
 - [ ] recent enterprise upcoming invoices looked at, new issue opened with more granular AC

Effort: 6 hours

Edited by: @jordanh

**Comment by jordanh** [comment]
Going to keep this open for now but change the AC. I will edit @mattkrick's comment above to reflect new effort

**Comment by mattkrick** [comment]
work to be done: go through each enterprise client & delete all the proration lines before their year long contract renews

**Comment by jordanh** [comment]
During scrub, @mattkrick, "likely affects customers who upgraded to enterprise prior to June, 2020."

We'll likely have to catch these on their renewal windows and manually adjust. The ol' cost of doing business.

Iceboxing
