### ISSUE TITLE
Group topic order in summary

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3277]
### Repro
- I held a retro with single-card and multi-card groups, both with and without votes
- The single card groups came first sorted by vote
- The groups came next with 0 votes for the first and 2 votes for the second

### AC
- I would expect it be sorted strictly by voteCount

### EE
- 10.5pts

_Originally posted by @ackernaut in https://github.com/ParabolInc/action/issues/3275#issuecomment-542414843_

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/3157551) 🔒 writes:
> In the retro summary that is produced. It would be good if the issues discussed were grouped and ordered in the same way they were discussed, and also if topics that weren’t discussed were indicated in some way (like a cut-off line or something).

**Comment by jordanh** [comment]
Came up during scrub. Triviality and new capacity had us decide to do it this week as one of the first items for Nick O'Ferrall to tackle

**Comment by mattkrick** [comment]
See https://github.com/ParabolInc/parabol/blob/share-temlates-backend/packages/server/graphql/types/RetrospectiveMeeting.ts#L101

**Comment by nickoferrall** [comment]
It looks like this has already been fixed [here](https://github.com/ParabolInc/parabol/commit/a9a59224e8f828b48c3c3a2b5a9236fd6431d253) so I'm closing this issue for now
