### ISSUE TITLE
See an updated org billing view when first adding the CC

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3281]
When I first add a CC on an org, it would be cool for the billing view to update when the upgrade modal is closed.

### AC
- The billing view is updated to show the additional billing sections, if possible

### EE
- 10.5 pts

_Originally posted by @ackernaut in https://github.com/ParabolInc/action/issues/3275#issuecomment-542418725_

**Comment by jordanh** [comment]
Scrubbed, reprioritizing

**Comment by NikAiyer** [comment]
Looking into this one

**Comment by jordanh** [comment]
I this one also got done. Not sure. Iceboxing.
