### ISSUE TITLE
Agenda UX from team dash during action meeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3283]
As of now, the agenda list in the team dash shows the latest state from an active action meeting (completed items, where the facilitator is by virtue of not being synced in the meeting, updated order, etc.).

We should probably wait to design UX for the agenda list when we revisit IA for multiple meetings and mobile-friendly dashboard views.

In the short term, we could consider disabling the agenda list from the team dash when the active meeting is happening. However, I don’t mind seeing latest state from the active meeting until we redesign.

### AC
- Write a design issue
- Decide or not to make a short term update, like disabling

### EE
- 10.5 pts

**Comment by jordanh** [comment]
Iceboxing for now
