### ISSUE TITLE
Client-side segment identify() call, email added to page event

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3286]
## Issue - Enhancement

Today we are unable to track ad spend to sign-ups or page loads in HubSpot. 

### Page Loads

`page()` events need the email trait. [See this page](https://segment.com/docs/connections/destinations/catalog/hubspot/):

```A traits.email value must be included and either a page or track call must be called.```

### Ad attribution

Working with HubSpot support, it's because the HubSpot API must be called from the client's web browser in order to push tracking cookie data up to HubSpot.

Google Tag Manager allows us to inject Javascript upon certain client-side events (i.e. page loads and whatnot).  I'd like to harvest the user's email and hand it to the HubSpot API via a call to `analytics.user().traits().email` and push the ad attribution data if there is data to send and the email exists.

### Acceptance Criteria (optional)
When a new account creation is successfully created:
   - Initiate a client-side call to Segment's `identify()` call with some basic traits information on each new page load. Traits to include:
      - The user's id
      - The user's email
   - Each client-side `analytics.page()` includes the email trait, if known

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**EDIT:** 2020-Apr-30 updated description and AC

**Comment by jordanh** [comment]
@mattkrick after thinking about it a bunch, this is an approach I've landed on to make tooling for tracking ad ROI

**Comment by mattkrick** [comment]
not sure i follow. why are we involving segment in this? segment already calls identify on the server

here's how i'd do it:
- client calls `login`
- server responds with `User` and `isNew === true`
- client calls hubspot API with `User.email` if `isNew === true`

**Comment by jordanh** [comment]
The reason I don't want to do it that way, is I don't want to build the HubSpot API into our app, rather, I want to store the data someplace accessible to Google Tag Manager. Segment analytics feels like a reasonable store.

As a secondary benefit, calling identify() with the updated user id would allow us to send page events using the real id, not with the alias id. Not all Segment destinations support aliases.

If this is still confusing, we can upgrade the bandwidth and talk about it. There is some subtly here.

**Comment by mattkrick** [comment]
yeah, we'll have to discuss. we don't have an email until the login event. if we have to listen for that event, it has to be part of the app, right?

big picture, i suppose i don't understand why we have all the analytics for an app that is behind a login portal. if we can link a user to an anonymous analytics id

**Comment by jordanh** [comment]
Discussed during scrub, iceboxing. I suspect as @avivapinchas evolves our paid strategy, this one will come back

**Comment by jordanh** [comment]
Pulling this one back out of the Icebox.

As I was researching and writing #3797, I discovered that we can't handle our own page track events. We need to use the client-side HubSpot tracker to get page view events into HubSpot.

What we observe today is the first user that signs up or any user that transits our marketing site gets their page views accounted for. Other users do not:

![image](https://user-images.githubusercontent.com/103000/80653549-4f7e6180-8a2f-11ea-9151-ef000fd591b5.png)

Page tracking is all done clientside today in https://github.com/ParabolInc/parabol/blob/d4639749d29c4317c13d9cc9c46fce69ae78c8a2/packages/client/components/AnalyticsPage.tsx#L40

In some cases, `analytics.user().traits().email` will be set. In most cases it won't be. If the email is absent, then HubSpot's `page()` tracking calls will not work (the only way for HubSpot to update a Contact record is via an email address, not an id).

Before, segment used to recommend we call identify once. Not it appears like we can't over identify. Read this ([from here](https://segment.com/docs/connections/spec/identify/)):

![image](https://user-images.githubusercontent.com/103000/80656395-f2d27500-8a35-11ea-818f-d57b4422c167.png)

I think to fix this, we need to identify on the client, and the server.

**Comment by mattkrick** [comment]
the business requirements are to put an email on a page event.
the identify call only adds a userId to the page event.
so, we now manually add an `email` field to page events, we do not call identify on the client.
