### ISSUE TITLE
Team View: Avatar menu options

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3300]
on the team dash, the avatars should have at least the following:
- Remove from team
- promote to team leader
- Free at 10:00am (if gcal is integrated)
- Currently in X meeting (if parabol meeting)
- Local time: 9:00am
- start video
- see calendar (if gcal integrated)

**Comment by jordanh** [comment]
Moving this to "Look and Feel" milestone to simplify organization

**Comment by jordanh** [comment]
This is a very good list of things

**Comment by jordanh** [comment]
Related directly to: #3458 

Iceboxing
