### ISSUE TITLE
timezones, offset, & latency

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3316]
There are 3 things we want from the client:
- latency (do we show their team members that they got sketchy internet)?
- server offset (how far off is their computer clock vs. our server clock?)
- timezone (should i message my team member now?)

latency can only be solved via heartbeat, so our server should store the time the keepalive was sent, diff from the last keepalive, and send that diff to the client.

server offset + timezone is something the client has to tell us, probably once per connection.
to get the offset, the client has to tell the server what time it thinks it is. then the offset is serverTime - clientTime - (roundTripTime /2). we probably don't need sub-second accuracy, so we can estimate roundTripTime to be like 300ms. then, we can kick that latency can down the road.

for timezone, client just needs to send up their UTC offset. they could probably send both upon connection.

the trick is when to send. we don't fire an actual gql mutation for login. instead, we just connect via websocket. we could piggyback this & add a `tz` param to the url that holds `new Date().getTimezoneOffset()` and `ts = Date.now()`

for the stage timer, we also need the local client time.
so, in addition to the scheduledTimeEnd, we need to send the serverTime. 
the client does `serverTime - Date.now() - 150ms` to figure out their offset.
then, the client sets a `localScheduledTimeEnd` which is the only thing the view layer needs to read.
this should fix #3294

**Comment by jordanh** [comment]
Scubbed, ixeboxing
