### ISSUE TITLE
Migrate from DraftJS to ProseMirror

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3324]
Our fork of DraftJS has served us well for years. However, it has a few drawbacks:
- No bullets/numbering/sub-trees
- No collaborative editing
- No pictures
- No tables
- Bad paste support
- not `StrictMode` compliant (ie it will block us from upgrading react)

Atlassians' AtlastKit, which is built on top of prosemirror, solves ALL of these. An unbiased review is here: https://juretriglav.si/open-source-collaborative-text-editors/. The only question is when.
Since React's Concurrent Mode is still experimental, I think the answer is not yet.

However, the longer we delay migrating to the new react, the longer we delay migrating to the new relay, which means extra tech debt along the way. Ideally, we do this ~2 weeks before react v17 lands.

**Comment by ackernaut** [comment]
He needed to do some work to get AtlastKit up to speed (built the server parts, replaced the icons). Do you expect we would do similar work?

**Comment by mattkrick** [comment]
since we're in the atlassian marketplace, i think we legally can use their icons under their license.
the server is just for collab editing. we can kick that can down the road

**Comment by mattkrick** [comment]
upon digging into atlaskit, it looks like they aren't compliant with the next version of react either: https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/packages/editor/editor-core/src/editor.tsx

they're also pretty bloaty, so it _may_ benefit us to use a prosemirror base, use atlaskit pieces where it makes sense (like the document schema) and write the rest

**Comment by mattkrick** [comment]
Promoting this, the issue should NOT be iceboxed. staying with draft-js is accruing a huge amount of tech debt & as we move towards recorded video, we'll likely want to embed it in a text editor. We still have to build android fallbacks for each new rich text experience we offer.

The _right_ way to do this is very difficult without https://www.w3.org/TR/uievents/, which was previously https://www.w3.org/TR/2009/WD-DOM-Level-3-Events-20090908/. That's because there are some key combos like pressing backspace where you don't know if you're deleting a character or a block of code & you can't call preventDefault at the right time. So, it's easier to just use prosemirror as it offers some guarantees out of the box (like cross-browser/device compat).

I think the way forward is to use the Atlassian document schema, as it looks well thought out. Then, we can offer our own UI on top.

**Comment by ackernaut** [comment]
Should we add AC and EE here?

**Comment by ackernaut** [comment]
The updated editor should:
- Handle formatting
- Handle inline links
- Handle inline mentions
- Handle inline tagging (e.g. `#private`, `#archived`, `#[retro card no.]`, etc.)
- Handle emoji (switch to emojimart?)
- Be able to include an uploaded video snippet (max 30 sec?)
- Be able to include an image like a GIF

One idea re: the short video snippet. Perhaps one day we make a thing that looks like a templated thread (e.g. we’re gonna thread on a decision) and that allows for the top comment to have a longer video snippet to give the background (say 2 mins instead of 30 secs).

**Comment by mattkrick** [comment]
discussion complete, i think we can move on to implementation
