### ISSUE TITLE
Actual meeting participants

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3342]
From a [user](https://app.hubspot.com/sales/3888472/contact/6507651):
>…a way to indicate members are watching a meeting, instead of participating, or a way to manually remove team members from a meeting. We've had instances where people were in the meeting who weren't present and we couldn't remove their votes etc (Although it was obviously fine to just proceed on to the next step, so no biggie!)

### Questions
- How many cases are there for sub-groups of a team to hop into a meeting together?
- Is there a better way to show who’s participating?
- How can we make participant interactions more clear, like how many votes are remaining?

**Comment by jordanh** [comment]
Already implemented!
