### ISSUE TITLE
Shared goals even over individual tasks

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3343]
A [user](https://app.hubspot.com/contacts/3888472/contact/8034101/) 🔒  wrote in via love@:
>I figured I would actually take action on the feedback you’re asking for after round 2 of using this for squad retrospectives. So here goes nothing!

>The biggest thing I’m finding trouble with at the end of the meeting is the collaboration and call to action towards one high-level or general improvement that the squad would like to make in the next sprint – a “delta plus”, if you will. The meeting ends a little abruptly and everyone goes their separate ways with a bunch of different tasks, many of which I’ve written to keep the discussion flowing. We typically like to have one, focused improvement that we’d like to make as a team and not as much a bunch of separate tasks to take on as individuals.

>So my feature request: “As a Parabol facilitator, I’d like the app to help my squad generate a delta plus so that we can all leave the meeting focused around the most important improvement we can make next sprint.”

**Note**: this user responded to some more questions in the email thread. You can see the reply in Hubspot “_Re: Coming down to a final action item_”

**Comment by jordanh** [comment]
Sounds like weak signal for prioritizing once all tasks have been created.

Iceboxing for now
