### ISSUE TITLE
1:1 meetings: user feedback and research

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3344]
This is the place to capture and discuss user feedback re: 1:1 meeting UX.

Cross-linking to [our private doc](https://docs.google.com/document/d/1bnFEQFASOCdIEUMZabzHnqHtDByNOe1UgFl5hkdNmUc/edit#heading=h.sower0r4cm8f) 🔒

**Comment by ackernaut** [comment]
+1 from [user](https://app.hubspot.com/sales/3888472/contact/7111951):
>1:1 meetings would be very cool. Currently we do 1:1's and share agenda and action points in different places with different tools, so it could help standardise, how we do 1:1's.
>Overall, I am(an my team) are very happy with the retro tool. It gave us more quality retros and saved some stickies :) Thank you!

**Comment by ackernaut** [comment]
I think our next steps here are:
- Work on discussion thread designs #3334 
- Find the common and unique UX patterns in a discussion thread for the following cases: Retro topics, Check-In agenda items, 1:1 agenda items, async threads + decisions
- Gather pen-and-ink, concepts, and prototypes of a 1:1 UX
- Reach out to our folks who opt in for feedback: ask for a show of hands who does 1:1s already, invite those to a video meeting, ask them about their 1:1 process today (10 mins), get feedback on our concepts (10 mins), and of course check in about what’s working/missing in general

As for this issue, I realized it didn’t have AC and EE so we can keep it open but remove it from the sprint board. We can add more data, and the link to the project notes are in the top comment.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
