### ISSUE TITLE
Google calendar integration designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3345]
[Some folks](https://app.hubspot.com/contacts/3888472/contact/19701) have given us feedback that their calendar is their task list. This is pretty smart, because it recognizes tasks are not going to get done unless time is reserved to do them. Entire products revolve around this concept: https://www.timehero.com/

Designing a GCal integration would allow us to further provide value to an individual and team. The following JTBD are envisioned:

   - When I want to put a task on my calendar, I want to do so from the Task card, so my commitment is broadcast to my teammates and the task is captured in the place I work from

   - When I want to schedule jam time with my colleague(s), I want to be able to do it directly from a meeting, so that we don't have to switch apps

   - When I want to schedule the next meeting, I want to be able to do it from within the meeting we're having now, so I don't have to take care of it later

I imagine the Task surface be extended in the following way:

   - The Publish button is extended with a GCal integration
   - @mentions can be used to invite others
   - If a Task is promoted to become a GCal Task, the calendar is extended to show date, time, and duration
   - In the future, the calendar component suggests a conflict-free time / easily shows conflicts
   - In the future, a Parabol meeting link is automatically generated

AC:

   - Sketch of Target
   - Sketch of 1st implementation

Design uncertainty: 3

**Comment by jordanh** [comment]
Related to: #3392

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/5397101) writes:

> Integration with Google tasks and calendar, please!

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/5397101) writes:

> I'd like to see calendar reminders for my actions that have a deadline

**Comment by jordanh** [comment]
Internal validation, via #3523:

> Issue - Enhancement
> Especially when planning out-going marketing, I/we need to establish a cadence of publishing, sending so that we're not overwhelming users with too much at one time and also not leaving long gaps of silence. To do that, it's helpful to be able to see a calendar view for planned marketing activities like blog posts, emails, etc., so you can easily identify gaps and overlap and then adjust.
>
>Acceptance Criteria (optional)
>Users can:
>
>View tasks with deadlines on a calendar
>Move tasks to different dates to change the deadline

**Comment by jordanh** [comment]
Scrubbed. This is going to come back. I know it. Iceboxing.

**Comment by jordanh** [comment]
Reopening as primary place to spool up user feedback

**Comment by garethaledavies** [comment]
A [user](https://www.notion.so/parabol/Elina-Minnie-c8e01f8717bc404eaf6b1a1416028c36?pvs=4) requested a Google Calendar integration
