### ISSUE TITLE
Clear UX for retro template customization

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3365]
With a fresh team, a user will see 5 templates and the option to customize. When templates are added, the customize option may be out of sight (see images below). As we redesign the lobby, I wonder if we can make the feature to customize very apparent, even before opening the menu. Some options:
- Change the label near or inside the dropdown control, visible when it’s closed
- Move the customize option to the first position, followed by a divider and the existing templates
- Something else
<img width="427" alt="Screenshot 2019-11-19 17 39 33" src="https://user-images.githubusercontent.com/307286/69196372-f01d3c80-0af3-11ea-8dd0-9a189309c415.png">
<img width="433" alt="Screenshot 2019-11-19 17 13 37" src="https://user-images.githubusercontent.com/307286/69196371-f01d3c80-0af3-11ea-9988-17df255e31d2.png">

**Comment by jordanh** [comment]
Re-evaluate during design for #3867 

Placing in icebox
