### ISSUE TITLE
Wonky timeline sidebar notes

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3366]
A few things I noticed:
- The cards are draggable but the updated order seems random or broken
- The featured card is larger than some max-width of the task cards
- The Active Tasks label isn’t aligned with cards

<img width="352" alt="Screenshot 2019-11-19 17 35 40" src="https://user-images.githubusercontent.com/307286/69196654-ae40c600-0af4-11ea-88df-b1dd7471efe2.png">

### AC
- Fix alignment issues
- Disable or fix DND to have some ordering logic

### EE
- 10.5 pts

**Comment by jordanh** [comment]
Scrubbed iceboxing
