### ISSUE TITLE
Meeting type illustrations for meeting lobby

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3369]
## Issue - Enhancement

When a user visits our new meeting lobby, they'll be able to pick which type of meeting they'd like to start.

### Design assets

Link to Figma assets: https://www.figma.com/file/2CdDxgchV8PHXT8YfWfGpw/Meeting-Lobby

### Acceptance Criteria (optional)
Illustrations for:
   - Retrospective meeting
   - Check-in meeting (aka an [Action Meeting](https://www.parabol.co/getting-started-guide/action-meetings-101))
   - One-on-one meeting: "a free-form meeting for pressing issues, brilliant ideas and chronic frustrations"

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick and @ackernaut: is the above list complete?

We want these as SVG right?

What aspect ratio?

**Comment by mattkrick** [comment]
that's all correct! SVG yes, not sure about aspect ratio. anywhere between 4:3 and 16:9 i'd assume

**Comment by ackernaut** [comment]
SVG is ideal as long as the details (textures, color gradations) can be vector. The TL;DR of the aspect ratio is definitely between 4:3 and 16:9. The long explanation…

It depends on the background of the graphic.

If the background is transparent, we could center it as we need. If it’s a flat color, we can extend/crop that flat color. If there’s a rich background, well we could hide overflow to a point, essentially cropping it.

This [laptop view](https://www.figma.com/file/2CdDxgchV8PHXT8YfWfGpw/Meeting-Lobby?node-id=8%3A0) uses a 16:9 frame, but the illustration graphic is roughly 4:3 centered in the frame.

This [mobile view](https://www.figma.com/file/2CdDxgchV8PHXT8YfWfGpw/Meeting-Lobby?node-id=8%3A311) was based on the height of the view and image and is centered. The space for the illustration is not quite 16:9 but the centered image, once again, is roughly 4:3.

Those designs are finalized but they show how we can lay the images out in various canvases.

**Comment by ackernaut** [comment]
Also, does it make sense to work on a concept for a custom meeting “Build Your Own” or one that is simply based on some agenda items “Bring Your Own Agenda” or a quick video call? We can always make a second pass.

**Comment by ackernaut** [comment]
Future: an illustration for decision meetings/loops e.g. governance, etc.

**Comment by mattkrick** [comment]
this is complete
