### ISSUE TITLE
Designed scheduling a future meeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3392]
From #3330 

### AC
Designed concepts for the following:
#### Schedule Later Modal (/new-meeting)
- [ ] When "Schedule Later" is clicked, a modal similar to the timebox modal opens.
- [ ] It has Date & Time fields
- [ ] If GCal is connected, a button exists that says "Add to Calendar". When clicked, a GCal meeting is pre-filled including all invites on that team, based on their email addresses & a permalink.
- [ ] If GCal is not connected, a button exists that says "Add to Google Calendar" which opens an Oauth2 prompt & then redirect to above.
- [ ] The permalink is generated when the "Schedule" button is clicked. That means the meeting is created at that time, too.
- [ ] Below there is a click-to-copy permalink to the new meeting.
- [ ] There is an OK button at the bottom. Clicking OK sets the date/time on the created-but-not-started ("future") meeting
- [ ] A future meeting doesn’t appear as an active meeting until 5 minutes prior to start

#### Editing a Future Meeting (/edit-meeting/:meetingId)
- [ ] This looks identical to /new-meeting, except there is also a red DELETE button to the left of the Schedule Later button
- [ ] Every field that gets updated triggers an updateFutureMeeting mutation

#### Note
- See #3461 and #3454 as they would allow for editing a scheduled meeting

### EE
- 10.5 pts

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/5397101) writes:

> I'd like to schedule a recurring retro in Parabol and have it appear in my Google calendar (and in my teammates')

**Comment by ackernaut** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/8749601/) 🔒 gave feedback ([doc](https://docs.google.com/document/d/1cPk8cIcl2uZBNEaOVINVuU-K2_p-fbvP9D4UKvSZ6dE/edit#) 🔒):
>With Outlook/Webex [it would be 100% helpful] if you could set up recurring meetings for the next 6 months with each event having a correct link to the meeting. The team has a set rhythm.

**Comment by gcrickman** [comment]
[A customer](https://app.hubspot.com/contacts/3888472/deal/657210686) 🔒  writes via chat:

> how do  I have the same people attend without having to invite them each time I start a retro?  Can I have a standing retro with parabol in my 365 calendar and invite my team members? how?

**Comment by gcrickman** [comment]
A user writes via chat:

> How can I schedule a sprint retrospective for a future date and send the link to the group members?

**Comment by jordanh** [comment]
Repurposing as a Batting Practice

**Comment by ackernaut** [comment]
Our designs for setting up a meeting series will make this issue obsolete. I’ll close and reference this issue there.
