### ISSUE TITLE
Building fails with `Module not found: Error: Can't resolve 'fs'...`

### ISSUE THREAD

**Issue by jingman** [ParabolInc/parabol#3408]
When I build with `yarn build`, it errors out with...

<img width="1382" alt="Screen Shot 2019-12-05 at 3 11 01 PM" src="https://user-images.githubusercontent.com/99067/70274559-fb1dd100-1771-11ea-947b-428ad1cfdc5c.png">

<details>
<summary><strong>📃 Full log output</strong></summary>
<pre>
➜  action git:(fix-build-from-scratch) ✗ yarn build
yarn run v1.19.2
$ yarn workspace parabol-server build
$ yarn build:relay && yarn build:client
$ yarn update-schema && yarn build:relay-unsafe
$ node utils/updateSchema.babel.js && yarn tsgen
Schema updated!
$ gql2ts ../../build/schema.json -e $(pwd)/../client/types/config.js -o ../client/types/graphql.ts && eslint --fix '../client/types/graphql.ts'
$ relay-compiler --customScalars.Email=string --customScalars.DateTime=string --customScalars.URL=string --noFutureProofEnums --src ../client --exclude '**/__generated__/**' --exclude '**/githubSchema.graphql' --schema ../../build/schema.json --extensions js ts tsx --artifactDirectory ../client/__generated__ --language typescript --client-schema ../client/clientSchema.graphql --persist-output graphql/queryMap.json --watchman false
$ webpack --config webpack/webpack.prod.config.js
ℹ ｢atl｣: Using typescript@3.7.2 from typescript
ℹ ｢atl｣: Using tsconfig.json from /Users/jingman/repos/jingman/action/packages/client/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
✖ ｢atl｣: Checking finished with 17 errors
Hash: f1c6394f992193ecff73
Version: webpack 4.41.2
Time: 63141ms
Built at: 12/05/2019 2:58:23 PM
Entrypoint app = vendors~app_b4e952f02b5c89ecfeb9.js vendors~app_f1c6394f992193ecff73.js.map app_7cbc65d606dc09fa77e0.js app_f1c6394f992193ecff73.js.map
   [2] /Users/jingman/repos/jingman/action/node_modules/react-router/esm/react-router.js + 1 modules 29.2 KiB {188} [built]
       |    2 modules
  [24] /Users/jingman/repos/jingman/action/node_modules/@emotion/core/dist/core.browser.esm.js + 5 modules 36.2 KiB {188} [built]
       |    6 modules
  [27] /Users/jingman/repos/jingman/action/node_modules/history/esm/history.js + 2 modules 30.6 KiB {188} [built]
       |    3 modules
  [42] ../client/utils/constants.ts 4.12 KiB {177} [built]
  [57] (webpack)/buildin/global.js 472 bytes {188} [built]
  [65] ../client/components/AtmosphereProvider/AtmosphereProvider.tsx + 1 modules 11.1 KiB {177} [built]
       | ../client/Atmosphere.ts 10.2 KiB [built]
       |     + 1 hidden module
 [155] ../client/components/LoadingComponent/LoadingComponent.tsx + 1 modules 9.71 KiB {177} [built]
       |    2 modules
 [260] multi ../client/client.tsx 28 bytes {177} [built]
 [333] ../client/cdnFallback.js 259 bytes {177} [built]
 [406] ../client/scrollIntoViewIfNeeded.js 1.58 KiB {177} [built]
 [407] ../client/client.tsx + 12 modules 35.4 KiB {177} [built]
       | ../client/client.tsx 3.42 KiB [built]
       | ../client/Root.tsx 381 bytes [built]
       | ../client/styles/theme/globalStyles.ts 3.65 KiB [built]
       | ../client/hooks/useLocalQuery.ts 1.09 KiB [built]
       | ../client/styles/theme/fontLoader.js 3.26 KiB [built]
       | ../client/mutations/ResetPasswordMutation.ts 927 bytes [built]
       |     + 7 hidden modules
[2048] ../client/modules/demo/LocalAtmosphere.ts + 19 modules 82 KiB {104} [built]
       | ../client/modules/demo/LocalAtmosphere.ts 2.5 KiB [built]
       | ../client/modules/demo/ClientGraphQLServer.ts 43.8 KiB [built]
       | ../client/modules/demo/handleCompletedDemoStage.ts 3.83 KiB [built]
       | ../client/utils/autogroup/groupReflections.ts 3.48 KiB [built]
       | ../client/utils/autogroup/getGroupSmartTitle.ts 946 bytes [built]
       | ../client/utils/sleep.ts 95 bytes [built]
       | ../client/utils/startStage_.js 172 bytes [built]
       | ../client/utils/unlockAllStagesForPhase.ts 469 bytes [built]
       | ../client/utils/unlockNextStages.js 1.34 KiB [built]
       | ../client/modules/demo/initBotScript.ts 11.9 KiB [built]
       | ../client/modules/demo/entityLookup.ts 1.75 KiB [built]
       | ../client/modules/demo/getDemoEntities.ts 433 bytes [built]
       | ../client/validation/normalizeRawDraftJS.ts 1.94 KiB [built]
       | ../client/utils/makeDiscussionStage.ts 401 bytes [built]
       | ../client/utils/makeGroupsToStages.ts 232 bytes [built]
       |     + 5 hidden modules
[2052] ../client/components/TeamInvitationRoot.tsx + 10 modules 21 KiB {158} [built]
       |    11 modules
[2062] ../client/components/InvitationLinkRoot.tsx + 4 modules 5.25 KiB {99} [built]
       |    5 modules
[2067] ../client/components/DemoMeeting.tsx + 2 modules 2.6 KiB {84} [built]
       | ../client/hooks/useMetaTagContent.ts 385 bytes [built]
       |     + 2 hidden modules
    + 2079 hidden modules

WARNING in /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.spec.js 53:37-93
Critical dependency: the request of a dependency is an expression
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm lazy ^.*\.js$ namespace object
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/codemirror-graphql/hint.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/QueryEditor.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/GraphiQL.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/index.js
 @ ../client/modules/admin/containers/Graphql/GraphqlContainer.tsx
 @ ../client/components/PrivateRoutes.tsx
 @ ../client/components/Action/Action.tsx
 @ ../client/Root.tsx
 @ ../client/client.tsx
 @ multi ../client/client.tsx

WARNING in /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.spec.js 57:37-93
Critical dependency: the request of a dependency is an expression
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm lazy ^.*\.js$ namespace object
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/codemirror-graphql/hint.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/QueryEditor.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/GraphiQL.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/index.js
 @ ../client/modules/admin/containers/Graphql/GraphqlContainer.tsx
 @ ../client/components/PrivateRoutes.tsx
 @ ../client/components/Action/Action.tsx
 @ ../client/Root.tsx
 @ ../client/client.tsx
 @ multi ../client/client.tsx

WARNING in /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.spec.js 61:37-93
Critical dependency: the request of a dependency is an expression
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm lazy ^.*\.js$ namespace object
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/codemirror-graphql/hint.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/QueryEditor.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/GraphiQL.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/index.js
 @ ../client/modules/admin/containers/Graphql/GraphqlContainer.tsx
 @ ../client/components/PrivateRoutes.tsx
 @ ../client/components/Action/Action.tsx
 @ ../client/Root.tsx
 @ ../client/client.tsx
 @ multi ../client/client.tsx

WARNING in /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.spec.js 68:37-99
Critical dependency: the request of a dependency is an expression
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm lazy ^.*\.js$ namespace object
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/codemirror-graphql/hint.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/QueryEditor.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/GraphiQL.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/index.js
 @ ../client/modules/admin/containers/Graphql/GraphqlContainer.tsx
 @ ../client/components/PrivateRoutes.tsx
 @ ../client/components/Action/Action.tsx
 @ ../client/Root.tsx
 @ ../client/client.tsx
 @ multi ../client/client.tsx

WARNING in [at-loader] ./graphql/mutations/createReflection.ts:103:58 
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.group' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ./graphql/mutations/removeReflection.ts:63:58 
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.group' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ./graphql/mutations/voteForReflectionGroup.ts:116:9 
    TS2345: Argument of type 'NewMeetingPhaseTypeEnum.discuss' is not assignable to parameter of type 'NewMeetingPhaseTypeEnum'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:20:28 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:20:61 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:24:26 
    TS6133: 'event' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:24:33 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:25:14 
    TS2339: Property 'skipWaiting' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:40:32 
    TS6133: 'url' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:51:27 
    TS6133: 'event' is declared but its value is never read.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:51:34 
    TS2304: Cannot find name 'ExtendableEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:52:14 
    TS2339: Property 'clients' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:61:31 
    TS2304: Cannot find name 'FetchEvent'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:90:6 
    TS2339: Property 'oninstall' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:91:6 
    TS2339: Property 'onactivate' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:92:6 
    TS2339: Property 'onfetch' does not exist on type 'ServiceWorkerGlobalScope'.

WARNING in [at-loader] ../client/serviceWorker/sw.ts:92:20 
    TS2304: Cannot find name 'FetchEvent'.

ERROR in /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/__tests__/validateWithCustomRules-test.js
Module not found: Error: Can't resolve 'fs' in '/Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/__tests__'
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/__tests__/validateWithCustomRules-test.js 1:0-34 9:29-41
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm lazy ^.*\.js$ namespace object
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/file.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-utils/esm/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphql-language-service-interface/dist/index.js
 @ /Users/jingman/repos/jingman/action/node_modules/codemirror-graphql/hint.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/QueryEditor.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/components/GraphiQL.js
 @ /Users/jingman/repos/jingman/action/node_modules/graphiql/dist/index.js
 @ ../client/modules/admin/containers/Graphql/GraphqlContainer.tsx
 @ ../client/components/PrivateRoutes.tsx
 @ ../client/components/Action/Action.tsx
 @ ../client/Root.tsx
 @ ../client/client.tsx
 @ multi ../client/client.tsx
Child InjectManifest:
    Entrypoint undefined = sw.js 0_17147692c8fb01f7627b.js.map
    [0] ../client/serviceWorker/sw.ts 3.01 KiB {0} [built]
Child html-webpack-plugin for "index.html":
    Entrypoint undefined = index.html
    [0] /Users/jingman/repos/jingman/action/node_modules/html-webpack-plugin/lib/loader.js!./template.html 1.79 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /Users/jingman/n/bin/node
Arguments: /usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js build
Directory: /Users/jingman/repos/jingman/action/packages/server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</pre>
</details>

I **do not** get this error when I use `yarn dev`.

---

- **OS:** macOS Catalina
- **Node version:** `v12.13.1` (installed via `n`)
- **NPM version:** `6.12.1`
- **RethinkDB version:** `rethinkdb 2.3.6 (CLANG 11.0.0 (clang-1100.0.33.8))`

**Comment by jordanh** [comment]
Stale, cannot reproduce
