### ISSUE TITLE
Suppress summary email and history event for some meetings

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3410]
## Issue - Enhancement

_Currently gathering feedback from users to determine what the AC might be._

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/6592301?) writes:

> I would like to DELETE a retro session. Some people are still beginning to understand how parabol works, which leads to some confusion. One of the things that happens most is that, since anybody can start a retro, they will join the site and start one even if there is already one or the format of that retro is different ( like lean coffee, or a more informal approach). As a result, I am often “stuck” in the retrospective page and if close the session, I will get a notification email and will appear in the history of retrospectives. Since I´d like to “keep the house clean”, I´d love to have the option to end a meeting and categorize as “not useful”, so it will not show in the history.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11250151/) 🔒 writes via support email:

> Hi, thanks for the nice tool. Unfortunately I accidentally created a meeting with the wrong template. Is it possible to delete it?

**Comment by gcrickman** [comment]
A user writes via chat: 

> so how do i cancel a meeting ? so that it does not send the email

**Comment by jordanh** [comment]
Users may now archive meetings from the timeline, however all team members will still receive a meeting summary.

The remaining tension is how to cancel a meeting that was started by mistake.

Going to icebox this for now, but if we hear about this tension again from users we should consider reopening.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/905301) 🔒 asks:

> How can I unsubscribe from all email notifications (Meeting summary, check- ins etc)

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/16931301) 🔒 says:

> Desired behavior:
> 
> Additionally to “End meeting” there should be possibility to Cancel the meeting
> 

> Scenario is the following:
> 
> You want to play around with Parabol. You create a new meeting in your team workspace.
> Or, alternatively, think of you’re creating a new meeting but then realizing that you have chosen wrong template, etc
> Now you want to cancel this meeting
>  
> 
> Current behavior:
> 
> You click “End meeting” button and meeting gets closed.

> But then all team members receive confusing email with a summary of the meeting which none of them have participated in

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/28136401?interaction=email) 🔒  writes:

> Hi - how do we delete unused meetings? we can go end them, but would rather not spam everyone who was in them. Thanks!

**Comment by mattkrick** [comment]
The email preferences piece of this is still outstanding & handled in https://github.com/ParabolInc/parabol/issues/4538

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/28003151) says:

> I'd like the ability to delete meetings without ending them

**Comment by ackernaut** [comment]
[This user](https://app.hubspot.com/contacts/3888472/contact/10273201/) 🔒  accidentally created a sensitive retro on the wrong team. I’m guessing they removed everybody from the team so that they couldn’t see the meeting or get the summary. The user asked us to delete the meeting manually. Hopefully designs from #5255 help users see more clearly what team they are on when starting a meeting

**Comment by enriquesanchez** [comment]
A [user](https://app.hubspot.com/live-messages/3888472/inbox/2403417446) 🔒 says:

>How can I delete an active meeting I don't need? I do not want to end the meeting and send an email to all team members.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/70593151) 🔒 writes: 

> Can you delete a meeting? If you accidentally created it

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/61207451) 🔒 mentioned during a feedback session that they would like settings to control who gets the meeting summary. They want to be able to end a meeting that was started accidentally without the summary going to every one. They would also prefer if only those in a meeting received the summary email rather than the whole team.

**Comment by acressall** [comment]
Noting that @enriquesanchez designed a concept that could solve the "accidental meeting" problem https://github.com/ParabolInc/parabol/issues/6572

**Comment by avivapinchas** [comment]
@mattkrick You rated this as 34 points in our Sprint Poker meeting. Could you propose a way to break down this issue into something easier to prioritize?

**Comment by enriquesanchez** [comment]
Closing in favor of #6572. [A milestone has been created](https://github.com/ParabolInc/parabol/milestone/137) to track this work.
