### ISSUE TITLE
make it obvious a meeting has ended

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3421]
now that meetings have their own routes, i can visit an old meeting & it looks like it's still in session. it should be black & white or have a watermark or something to say it's over.

AC
- [ ] ended meeting designed

effort: 12 points

**Comment by mattkrick** [comment]
bumping priority as the sentry logs show it's very apparent that folks aren't sure a meeting has ended.
as a bandaid i removed the facilitator bar, but more is needed

**Comment by mattkrick** [comment]
link to design to review?

**Comment by ackernaut** [comment]
Here’s [the link](https://www.figma.com/file/1DSwgYv0nRffpvb0Jnuc6G/Meeting-IA?node-id=77%3A5380) and [the notes](https://www.notion.so/parabol/Design-notes-Mar-2020-7cf55a8090764f01b30e60a804288d3c#94999959e21f49139107da80cdd5b4c8)

**Comment by mattkrick** [comment]
feel good about this, we've got overwhelming signal we need to show comments post-meeting & i think this is the cheapest way to get there. will begin implementation
