### ISSUE TITLE
Jira integration per team vs per user

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3425]
From [user](https://app.hubspot.com/sales/3888472/contact/8030801) 🔒 :
>I want to use the Jira integration more, but it requires every person to set it up for themselves directly for each team. I'd like to configure it once for the entire organization for example. Maybe that doesn't make sense in other clients but at least being able to do it within a single team would be nice.

### Note:
I know we’ve gone back and forth on integration account logic here, but it’s worth noticing the friction to using the feature. Here we can capture additional user feedback and ideas on how to lessen the friction.

**Comment by ackernaut** [comment]
#2773 is probably the latest issue thread on this

**Comment by jordanh** [comment]
Another user writes:

> Hi there,Hope you're having a wonderful holiday -I've added a JIRA integration to our Parabol account but it only seems to work on tasks assigned to me and not to other members on our team. We all use the same JIRA, so I'm not sure why that is?It would be very tedious to have to ask all of our team members to add the JIRA integration when one of us connecting as an admin should suffice.

**Comment by jordanh** [comment]
Considerations when enhancing Jira integration for Sprint poker (see: #4004 and #4005).

Scrubbed. Iceboxing for now
