### ISSUE TITLE
In Task Dashboard, sort task items by date

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3431]
Recording user feedback here. No AC yet.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/1274051) writes:

> [It is very important to us that we can] in dashboard sort action items by date

**Comment by mattkrick** [comment]
could be created at, due at, or updated at.
iceboxing until we take a first pass at a search/filter ability on My Tasks
