### ISSUE TITLE
Reactji constraints as templating

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3438]
This is not validated but…

[(See concept)](https://www.figma.com/file/GeEy1MNpxhFn9m0w9QKtOo/Reactji?node-id=4%3A47), the only idea I can think that may have legs is our desire for templates to be intentional and hopefully more useful. Going to capture as an idea for discussion; will probably get iceboxed:
- By default, reflections could have any no. of reaction, and nudges for everybody to indicate from some set of reactji could be informal, on the fly (e.g. hey add a thumbs up or down here)
- With some intention, during retro template editing, the prompts could include what reactji are available for the cards under that prompt
- Possible reuse: for general discussion threads, comments could have reactji and perhaps thread/comment authors could pick which reactji they want on a card or in a thread when looking for specific feedback (e.g. thumbs up, down); there might be a way to do this inline per comment in this case

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now
