### ISSUE TITLE
Search enhancements designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3449]
Based on outcomes from [here](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853)
### Acceptance Criteria
- [ ] Gathered and reviewed any existing user feedback
- [ ] Designed concepts exploring ([see latest](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=132%3A1)):
  - Contextual filters inline for timeline and tasks views
  - Search results in a rich menu
  - Search filter controls in a rich menu
  - Layout and UI design in dashboard IA
  - Examples of all types of data for both results and filter

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
