### ISSUE TITLE
Optional search affordance iteration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3450]
Based on the outcome [here](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853)

If we want to implement an iteration of a search UI that follows the updated IA but the deep search enhancement #3449 is not designed, we could offer simple filtering of timeline items and tasks items and hide the search when a dashboard view is not searchable.

### Acceptance Criteria
- [ ] Timeline can be searched by meeting name
- [ ] Stretch: can filter timeline by team
- [ ] My tasks can be filtered by a search query (like we had before)
- [ ] While the team kanban still exists we maintain this affordance but following the new design and IA (in top bar)
- [ ] Search UI is not in view when on a settings page

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is another one that'll come back around. Iceboxing for now
