### ISSUE TITLE
Designed timeline updates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3456]
This is a continuation of [outcomes](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853) from Dashboard IA design efforts. [See latest work in Figma](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=75%3A1270) — I think we’re _real_ close here, just need to refine details before writing an implementation issue.

### Proposal / Background
I propose that we add active and scheduled meetings at the top of the timeline view. This should be the primary way a person sees these meetings. The meetings menu #3454 is a global but secondary way to see them. Other than connecting straight to a meeting, the timeline is the default view when a user signs up or signs in. In this way they can see active and scheduled meetings without having to scroll or tap anything.

Additionally, we need to further refine filtering and searching the timeline (e.g. by team) and note that the primary FAB of the timeline is to start a meeting (taking the user to the single meeting lobby).

**Note**: doing this alongside #3449 (search and filtering design) and a fresh issue for a single task kanban [TK issue] is probably a worthwhile cluster of work in a single sprint since the UX/UI is related, but probably not completely coupled.

### Acceptance Criteria
Concepts showing:
- [ ] active and scheduled meetings
- [ ] suggested actions (maybe these become sidebar items?)
- [ ] how to search the timeline
- [ ] filters (consider take-aways from filter designs in #3449)
- [ ] sidebar updates (implementation can fix #3366) 
- [ ] how the FAB collapses (on scroll, etc.)

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I hope this work is considered as part of efforts to refresh the team dashboard view. Iceboxing for now
