### ISSUE TITLE
Single tasks kanban view

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3457]
This is a continuation of [work from Dashboard IA efforts](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853).

The idea holds that we have a single place where I can see any task for any team I’m on. At a minimal I can filter by team, user, and archive. See [latest in Figma](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=95%3A636)

We probably need to refine some things before we can write a clean implementation issue.

### Acceptance Criteria
Designed concepts exploring:
- How the columns look on mobile (like Retro prompt columns)
- The primary FAB is probably to add a task to the active column
- How does search and filtering work? See #3449 and consider designing for both issues at the same time; also consider how the timeline #3456 is searched and filtered
- In the future:
  - we probably should have a way to link to and highlight a task on the kanban
  - cards will probably expand showing activity (e.g. where did the task originate? in a thread from a Retro, a 1:1, etc.)
  - perhaps we offer a list view
  - we may add column customizations (see #212)
  - tasks will probably persist in threads that can be referenced and maybe afford continued discussion (e.g. a thread gets started in a meeting but persists in another place)

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Some variant will of this come back. Iceboxing for now
