### ISSUE TITLE
Team view designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3458]
A continuation of [outcomes](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853) from Dashboard IA work

The main idea here is that the team view is no longer a task board, but a place to the see the purpose, roles, and souls of team, and to manage the team settings. We may eventually show relationships of sub-teams, or ways to access insights. From here we will have quick links to jump to the timeline or tasks, filtered to the team. The primary action is to start a meeting. A secondary action is to add agenda items. Also, folks will probably see a person, tap on them, and start a video chat, or see their personal API/meta.

Here’s the latest [design work](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=93%3A4)

### Acceptance Criteria
Designed concepts for both mobile and laptop+ showing:
- See [comment below](https://github.com/ParabolInc/parabol/issues/3458#issuecomment-597143046)
- Team purpose
- Team settings (billing, archive, integrations)
- Team members (editing roles, invite, remove, linking to team member profile, starting a video call with a team member, etc.) this designs for #3300
- Shortcuts to views filtered by this team: timeline, tasks, maybe in the future knowledge or notes
- The primary FAB is to start a meeting with this team; it takes a user to the meeting lobby with the current team already selected
- How to add to the agenda
- Related to #3459 for a single team member view
- See #4059 for more v1 considerations

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
We have a problem with folks missing out on the integrations we offer. I think this is one thing we should solve for in the team view. I see two purposes to this team space:
1) Primary: [how to connect with my team](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=93%3A4)?
  - I can start a meeting with my team
  - I can tap on a teammate’s avatar to start a video chat if they’re online and available
  - I can tap through to a teammate’s profile view to see their roles, API, quick filters, etc.
  - I have quick links to see the timeline or task board filtered by this team
  - I have links to team knowledge and tools (by integration)
  - I can see a way to jump into active topic threads
  - I can build an agenda for the next check-in meeting
2) Secondary: how to manage my team?
  - I can clearly see and add integrations
  - I can invite to the team
  - I can manage roles
  - I can add a team purpose
  - I can tap through to the parent organization (and billing)

**Comment by gcrickman** [comment]
A user 🔒 writes:

> When I click a team, I see the most recent meeting, but no clear way to find all meetings/activity for that team. The only way I could find to do this was by going to Timeline, but it's not organized by Team.

**Comment by avivapinchas** [comment]
From our chat around driving conversions, we noted some opportunities that may fit for the Team view design: 
- Notifications to upgrade may fit here 
- 'Refer another team' could fit here as well - this would prompt users to add additional teams or suggest Parabol to other leads within their org

**Comment by ackernaut** [comment]
Here’s the latest, brief look at [team view UX concerns in Figma](https://www.figma.com/file/FPfSkx0ShYNglKBsHbYaig/Team-View?node-id=0%3A1)

**Comment by jordanh** [comment]
Here's a great list of things @mattkrick thought about in #3300:

> on the team dash, the avatars should have at least the following:
>
> Remove from team
> promote to team leader
> Free at 10:00am (if gcal is integrated)
> Currently in X meeting (if parabol meeting)
> Local time: 9:00am
> start video
> see calendar (if gcal integrated)

**Comment by jordanh** [comment]
Feedback from [a user](https://app.hubspot.com/contacts/3888472/contact/5529051) 🔒 :

> Hi there,Is there a clear way to find all of the retros for a given team? When I click a team, I see the most recent meeting, but no clear way to find all meetings/activity for that team. The only way I could find to do this was by going to Timeline, but it's not organized by Team.Thanks!Jared

**Comment by jordanh** [comment]
Edited above, user opting in to review designs

**Comment by mattkrick** [comment]
See #4059 for my list of things to include in a v1

**Comment by jordanh** [comment]
I held a feedback session with team leads from [this large company](https://app.hubspot.com/contacts/3888472/company/1696726269/) 🔒, they share one friction in particular they'd like resolved:

> We have begun to open meetings earlier, and collect reflections over longer periods of time. We also are letting discussions take longer to resolve, so we don't end the meetings. Because the meetings stay open, we want the ability to export the CSV file even if the meeting hasn't been closed. We'd also love the ability to view the meeting summary, also if the meeting isn't closed.

Allowing a CSV export from a timeline view of meetings seems like a doable thing... ("progressive export"?)

**Comment by ackernaut** [comment]
Replying the comment just above ⬆️  — I’m really glad folks are articulating their async intent, it’ll help us build a case for async-first design choices.

**Comment by mattkrick** [comment]
interesting use case.
for poker, i'll keep this in mind & try to make `endMeeting` be as lightweight as possible.
most of the things done to end a meeting are computing expensive things & storing them so the summary is cheap to produce.
it'll take some extra care to work around that

**Comment by jordanh** [comment]
This is still important. Iceboxing for now. A new version will come back around, I'm sure of it
