### ISSUE TITLE
User profile view designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3459]
This is a continuation of [outcomes](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853) from Dashboard IA efforts

### Acceptance Criteria
Note: we can really iterate on this one slowly
See latest designs and comments [here](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=93%3A4)
Design concepts showing:
- A user can edit their own information when tapping on their user menu or user hub info #3453 
- Others can view the profile from a team view #3458 
- Contextual link back to a team view #3458
- Shows a user’s team membership
- Shortcut links to see this user’s tasks on the single task board #3457 
- **Future, high priority**: shows how to start a video chat with this person, that opens up a discussion thread that can be used to jot notes or create tasks, reflections, etc. that can be upgraded to a meeting to invite others. Having open video streams flows in and out of meetings without starting or ending because a meeting started or ended. See [comment](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=93%3A4&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15442252)
- **Future**: shows a team member’s working preferences API as optional info a user can add
- **Future**: shows a user’s roles, maybe an integration with another system

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This one'll come back...
