### ISSUE TITLE
Lo-fi concepts for upgrading notes/comments to other objects

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3460]
See the background [here](#3391) and [here](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853)

### Acceptance Criteria
Sketches, concepts showing:
- optional, clever, user-friendly ways to upgrade a note or comment to another thing (e.g. reflection, task, agenda item, etc.)
- we may constrain what type of upgrades can be made by the UX of any given thread (e.g. comments can only become tasks in a Retro discussion thread)
- ideas on how to validate
- consider how to reply to an object or thread on an object (e.g. start a thread on a task)
- note the efforts of #3334 (discussion threads) and #3344 (1:1 meetings)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut says, this issue was born out of:
> how do I capture my idea or tension on the fly

Also:
> if it's important, it won't go away. It'll come back

**Comment by jordanh** [comment]
Scrubbed iceboxing for now
