### ISSUE TITLE
Retro template enhancement: overall description

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3466]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/6201001) writes:

> User: [I want] in idea phase additional text field for guidelines
>
> Me: We have a description field folks can use in our retrospective template editor for this purpose. Is it insufficient?  
>
> User: AfaIk, the descriptions are per column and thus don't get read outside the context of the column. I had a retro where I wanted to give a written guideline before the dive into the columns. Something that was relevant to all columns.

Opening this as a discussion issue to ideate and track additional user feedback.

**Comment by jordanh** [comment]
In the template editor, this could just be a free-form rich text field. Not sure how it would display in our design. Perhaps something that could be collapsed by the user?

Might be good for UGC (see #3465)

**Comment by ackernaut** [comment]
Yeah, perhaps we make the template more prominent in the lobby when the retro meeting is focused.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
