### ISSUE TITLE
Retro template enhancement: column voting permissions

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3467]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/6201001) writes:

> User: [We'd like to] pick columns that you can vote on
>
> Me: This is interesting, why?

> User: Like above, I love the positive and funny stuff my team shares but the voting is not a sign of agreement but rather a sign of "this is worth to discuss - we need to do something about it".
Now that I think about it - I always found the thumbs-up sign really misleading. It is too strongly associated with the facebook like. No matter how often I tell this to the team they always use some of the votes to highlight or like the funny stuff. This keeps them from voting the discuss worthy stuff.

Opening this as a discussion issue to talk about and track additional user feedback.

**Comment by jordanh** [comment]
For me, I'm not sure if it's worth adding the complexity of configurable column permissions or just to make it easier to up the number of votes people can get during the run time of the meeting.

(See #3249)

**Comment by ackernaut** [comment]
Yes, I think a mix of customizing vote count and reactji on cards may be utilitarian enough for most use cases.

**Comment by mattkrick** [comment]
i think the reactjis satisfies this pain point. i'm OK with closing this

**Comment by mattkrick** [comment]
i think the reactjis satisfies this pain point. i'm OK with closing this

**Comment by jordanh** [comment]
scrubbed, iceboxing for now

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/26621001) 🔒 says: 

> The main problem we have is that during the voting session, sometimes everyone votes on positive things and not negative things. Then we don't get to talk about improvements. It would help if we could choose which column we'd like to vote on instead of voting on every column.
