### ISSUE TITLE
Upcoming meeting notifications

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3485]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/8802601) 🔒 wrote:

> Thanks for your reply! What I actually meant by this question was; for example each Monday at 1500pm we have a meeting. What I'd like to do is let Parabol send around a notification with the topics that are on the agenda every Monday morning at 900AM. So people can use the time to go through pre-reads and stuff like that and prepare well for the meeting in that way.
Is that something you facilitate? Thanks.
 
AC will be updated with additional thoughts and information from users.

### Acceptance Criteria (optional)
A lo-fidelity design where users can:
   - Configure a meeting to send out a notification with the upcoming agenda, and any attached cards

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Related to:
#2921
#3454
#3392
#3461
#3345

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
