### ISSUE TITLE
Attach cards to agenda item

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3486]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/8802601) 🔒 wrote:

> Thanks for your reply! What I actually meant by this question was; for example each Monday at 1500pm we have a meeting. What I'd like to do is let Parabol send around a notification with the topics that are on the agenda every Monday morning at 900AM. So people can use the time to go through pre-reads and stuff like that and prepare well for the meeting in that way.
Is that something you facilitate? Thanks.

AC will be updated with additional thoughts and information from users.

### Acceptance Criteria (optional)
A lo-fi design where users can:
   - Promote a card to create a new agenda item
   - Promote a card to append to an existing agenda item
   - View the details of an agenda item
   - Remove cards attached to an agenda item

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### See also: 
- #3485 Upcoming meeting notifications

**Comment by ackernaut** [comment]
Related:
- #3334 (each agenda item is a topic with a top-level, thread-able object)
- #1083 (from the archives)

**Comment by jordanh** [comment]
See also: #3542

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
