### ISSUE TITLE
Subscription reliability feedback

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3498]
Right around our update to use uws (#3444, etc.) and/or more agressive dataloader caching (#3455 was it?) , I've been getting more feedback from users that Parabol has been acting flakey. I'm going to collect these anecdotes here to see if there is any pattern among them

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/8749601) writes:

> I am actually unsure if we are going to use Parabol now. This morning during our retro we had unexpected errors that caused us to pivot. When I went to start the meeting the dial kept turning and the meeting never started. I have 4 teams so this cannot happen without causing mass headache.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/32901) writes:

> Our action meeting got stuck where I couldn't create a task card. I had to keep refreshing. After a few tries, it finally let me

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/8349451) writes:

> The web interface is clunky/laggy. Oftentimes, we can't tell if the numbers / statuses being displayed are a reflection of reality or not. And one thing that's rather frustrating: if you press escape after clicking into a grouped set of cards, it somehow removes that group from your view altogether. You need to reload to find that group again. And reloading takes an unexpectedly long time, which leads to periods of ~30 sec where we're all staring at a screen and waiting.

**Comment by jordanh** [comment]
An enterprise [user](https://app.hubspot.com/contacts/3888472/contact/3595501) writes:
>Cool, thanks!  @Jordan Husney is there a bug right now when one tried to "end meeting" ?  The page sticks, but it looks like it did end the meeting because I get an auto-email with the summary.

**Comment by ackernaut** [comment]
There’s something I’ve noticed a few times on the team dashboard. I’ve made updates to a few cards, say the text on one and the status of another. I come back later to see that those changes didn’t persist. I’ve refreshed, applied my changes again, and then see that the changes did persist the second time. I shrugged it off as being a local hiccup in my browser. Is this a caching or connection issue?

**Comment by jordanh** [comment]
> There’s something I’ve noticed a few times on the team dashboard. I’ve made updates to a few cards, say the text on one and the status of another. I come back later to see that those changes didn’t persist. I’ve refreshed, applied my changes again, and then see that the changes did persist the second time. I shrugged it off as being a local hiccup in my browser. Is this a caching or connection issue?

This is something Sasha has experienced too. I believe she can reproduce it reliably. Not sure if this is the same, or a new issue entirely. I will reach out and see if she can make it so

**Comment by ackernaut** [comment]
Re: task issue behavior
- I leave the team dash open in a tab for a while
- I return to the tab
- I try to add a new task, I get the placeholder state but I can’t type into it to type
- I blur, the empty card doesn’t go away
- I refresh, it works

**Comment by ackernaut** [comment]
⬆️ possibly related: #3502

**Comment by mattkrick** [comment]
yeah, this definitely seems all related!
should probably be top priority.
just gotta figure out a case where we can reproduce reliably.

**Comment by mattkrick** [comment]
@ackernaut what branch is that on? #3494 has a fix for the editing status that could cause that, but if not it could be the same root cause

**Comment by mattkrick** [comment]
can't repro, so just some stabs in the dark:
- bumped uWS to the latest version (uses MakeCallback. fixes memleak issue with uncaught exceptions, probably doensn't fix this)
- don't reuse dataloader across queries for the same viewer (all happens on the server, so again, probably not the cause)
- remove batching from websocket messages. really not sure how this could fix anything, but trying to minimize the delta

**Comment by jordanh** [comment]
Are these out in prod now, or options to try?

**Comment by jordanh** [comment]
A user 🔒 writes:
> Seems like a great tool, sometimes we need to refresh the page because it stops working or freezes, but other than that, is a great tool.

**Comment by mattkrick** [comment]
Latest changes out in prod

**Comment by jordanh** [comment]
Closing this one. Is resolved!
