### ISSUE TITLE
Push tensions/reflections/ideas; user feedback and research

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3506]
We have a hunch that folks need to capture tensions, reflections, and ideas just-in-time with low friction. We’ve discussed various ways: as a Slack integration, as a first-class affordance in the app, as a reminder and respond-to email, etc. and in various contexts like mobile, or before the meeting as pre-work.

### AC
- Added user verbatims
- Added related issues and links
- Wrote user job stories
- Offered candidate solution ideas

### EE
- 10.5 pts

**Comment by ackernaut** [comment]
Related:
- #3391 (UX theory and discussion)
- #1307 (push agenda items via Slack)

**Comment by ackernaut** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/32901/) 🔒 writes (see [thread](https://parabol.slack.com/archives/C836NA350/p1579805420047300) 🔒):
>I could imagine myself having iMessage conversation with Parabol to capture tensions

**Comment by jordanh** [comment]
Scrubbed. Iceboxing

**Comment by jordanh** [comment]
Missed closing this when iceboxing. Doing it now
