### ISSUE TITLE
Help menu added to top-right user hub

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3509]
We deferred doing this in #3453

### AC
- Adds some mix of useful options (e.g. resources, shortcuts, report bugs, give feedback, [see Figma](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15398908))
- Consider [moving the help menu options](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=100%3A1&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#16961605) to left nav instead of top bar for mobile

### EE
- 10.5 pts

**Comment by mattkrick** [comment]
i think keyboard shortcuts + blog posts is too minimal an offering. before building this i'd like to add either "report bugs" or "give feedback", otherwise folks will click the icon, assume that's all there is to it, and not click again.

**Comment by ackernaut** [comment]
Next step forward: add a link to our general contact form until we have a more specific channel
