### ISSUE TITLE
Separate and/or sort columns with many tasks 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3521]
### Issue - Enhancement

When there are more than 10(ish) cards in a column, it starts to feel unwieldy. It's hard to get a sense of what tasks are relevant for the particular moment/time and feels like there's so much to do. This is particularly relevant with the 'Future' column, but even 'Active' can feel rather long. 

### Acceptance Criteria (optional)
Users can:
   - See a subset of tasks based on timeframe or other criteria 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

I think there's a lot to discuss around how and if we'd make changes to resolve with, so too early to estimate effort.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
