### ISSUE TITLE
View tasks with dates on a calendar 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3523]
### Issue - Enhancement

Especially when planning out-going marketing, I/we need to establish a cadence of publishing, sending so that we're not overwhelming users with too much at one time and also not leaving long gaps of silence. To do that, it's helpful to be able to see a calendar view for planned marketing activities like blog posts, emails, etc., so you can easily identify gaps and overlap and then adjust. 

### Acceptance Criteria (optional)
Users can:
   - View tasks with deadlines on a calendar
   - Move tasks to different dates to change the deadline

**Comment by mattkrick** [comment]
man this is good.
my gut reaction to this is a google calendar integration.
you integrate your GCal with your parabol team & then when you set the due date on a task, it sets it on your GCal. Optionally, you can set a specific time, too.
Then, to view e.g. the publish schedule, you just look at your GCal.

(other calendars can come later, too. GCal is just an easy first step)

**Comment by jordanh** [comment]
> my gut reaction to this is a google calendar integration.
> you integrate your GCal with your parabol team & then when you set the due date on a task, it sets it on your GCal. Optionally, you can set a specific time, too.

This is what [this user](https://app.hubspot.com/contacts/3888472/contact/19701) 🔓 has been asking for forever. This user is very important to me.

**Comment by jordanh** [comment]
@avivapinchas would implementing a version of issue #3345 resolve your need?

**Comment by avivapinchas** [comment]
It sounds like a good option that would likely bring on more tensions. Trying to imagine the future (always a fruitful endeavor 😜), the challenges I imagine coming up are: 
- Different types of things - Ideally would want to see which of the things on the calendar are posts vs email vs landing pages vs meeting vs just tasks 
- Different teams - At scale, it might matter which team in Parabol is doing each thing
- Managing GCal vs proj management tool - Would probably want to integrate anything we're producing with some task management tool, which would add another layer of complexity here. I imagine that task management tool is where I'd manage making the things happen. 

What I *really* like about this is that it provides visibility for the whole team around 'what's on the calendar'.

**Comment by mattkrick** [comment]
> Different types of things - Ideally would want to see which of the things on the calendar are posts vs email vs landing pages vs meeting vs just tasks

In the app we've only got meetings & tasks, so I think Post/Email/LandingPage would all exist under Task. To add granularity we'll add a tagging system so you can e.g. tag a Task as a "Email Publish" or similar & that'd propagate to the integration. 

> Different teams - At scale, it might matter which team in Parabol is doing each thing

I'd imagine the tasks live on the person's calendar & then the Team Calendar would be populated by the total of the personal calendars

> Managing GCal vs proj management tool - Would probably want to integrate anything we're producing with some task management tool, which would add another layer of complexity here. I imagine that task management tool is where I'd manage making the things happen.

So say the task management tool is Jira, then we'd pull that info from Jira & feed it to GCal. Goal is to have a single source of truth (Jira) and we just add functionality (e.g. put it on your calendar, show you what's changed in the last week, etc)

**Comment by avivapinchas** [comment]
> To add granularity we'll add a tagging system so you can e.g. tag a Task as a "Email Publish" or similar & that'd propagate to the integration.

Awesome - that would work well 

> I'd imagine the tasks live on the person's calendar & then the Team Calendar would be populated by the total of the personal calendars

I *think* the way this might make sense in GCal is to have a 'team' calendar and then individuals are _invited_ to the event. AFAIK, there isn't a thing in Gcal to roll-up people calendars into a 'team', and I also would want the items from this integration to be distinct from other meetings and events I have scheduled. 

> Goal is to have a single source of truth (Jira) and we just add functionality (e.g. put it on your calendar, show you what's changed in the last week, etc)

Awesome - that's great!

**Comment by mattkrick** [comment]
this is looking like it'll be more than 6 months out, so closing for now (we can & will reopen this or create a new similar issue!)

Here's how I see this playing out:
1. The next step is building a GCal integration so folks can schedule meetings in the future.
2. Then, we build a list view in addition to the kanban view for Tasks
3. Finally, We build a calendar view
