### ISSUE TITLE
Microsoft Teams Apps Integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3538]
## Issue - Enhancement

[A customer](https://app.hubspot.com/contacts/3888472/contact/9565001) 🔒 writes:

> Ability to add an app in Microsoft teams under group tabs so we can easily centralize the portal for all users

Should we add Azure Devops #3004, Planner Task #3537, and Teams chat integrations. Adding a Teams Apps integration could be a clever way to distribute our product.

Collecting more feedback here as other users write in.

**Comment by shawneeatparabol** [comment]
I have a 2 customers this would be helpful for (nice to have, not need to have) and believe in general our larger sized clientele would find this particularly useful:
[customer 1](https://app.hubspot.com/contacts/3888472/company/3223836226) 🔒 
[customer 2](https://app.hubspot.com/contacts/3888472/company/3191366316) 🔒

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/15842151) 🔒 requested:

> Many of our clients have sunset Slack within their organization and migrated over to teams. It would be nice if Teams were integrated to Parabol

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/12393401) 🔒 writes:

> I have one question regarding the integration features of Parabol: Is there a plan to integrate Parabol into Micosoft Teams and/or Microsoft DevOps (cloud and on-premise)?

**Comment by jordanh** [comment]
[A user (soon to be enterprise customer)](https://app.hubspot.com/contacts/3888472/contact/7270101) 🔒 writes:

> We see you have a Slack integration. Could you add Microsoft Teams, too? That's what our organization uses.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11480301) 🔒 said (during a feedback call):

> Having a MS Teams integration would help us get your tool approved by IT because without it you look like "another tool" and not part of something that we already use

**Comment by shawneeatparabol** [comment]
Another [customer](https://app.hubspot.com/contacts/3888472/company/4192496869/) who is a consultancy has requested this on behalf of his [clients](https://app.hubspot.com/contacts/3888472/company/4502307268), who he is introducing to the platform to try and convert. He anticipates many of his clients wanting this.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10483251/) 🔒  writes in via email:

> Hi, I would like to ask if you planning some integration for MS Teams?

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/8626801) 🔒  said:

> An integration with Microsoft Teams would be useful.

**Comment by mattkrick** [comment]
oh i'm sure this'll come back. iceboxing.

**Comment by treyparabol** [comment]
A [https://app.hubspot.com/contacts/3888472/contact/69539001] user 🔒 writes:

Just wondering if you are working on a Teams integration. Thanks!
