### ISSUE TITLE
Async conversation around agenda items 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3542]
## Issue - Enhancement

When I add an item to an agenda, I imagine it could sometimes be resolved async. To do that now, I'd need to ping in a Slack channel for others to see it and discuss the item. It's disconnected from where team conversation is happening (Parabol) and it can easily get lost in the chatter of the day. 

It could be cool to have the option to resolve agenda items async, maybe through comments directly in Parabol. Alternatively, an automatic Slack ping with a linked thread could work too. 

### Acceptance Criteria (optional)
Users can:
   - See an agenda item has been added without needing to look at the agenda items 
   - Have a threaded conversation about that item before a meeting

**Comment by jordanh** [comment]
Noted while scrubbing, "the resolve verb is interesting here."

Relating to #3454

Iceboxing for now.

**Comment by jordanh** [comment]
See also #3345
