### ISSUE TITLE
Assign task to whole team

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3548]
A user wants to assign a task to the whole team.
Possible flows:
- [ ] add a whole team avatar in the assign menu. clicking it clones the task for each team member. once clicked, `isCloned` is turned to true so you can't do it again
- [ ] shift + click or long press the reassign button & it turns into clone mode so you can copy it to someone else

**Comment by jordanh** [comment]
Still a thing, for sure. How many times will it come up before we design?

Iceboxing for now.
