### ISSUE TITLE
Definition of Done / Working Agreements

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3549]
As the Team view moves away from a kanban, we'll need some more fields like a team charter, handbook, etc. One requested field is the "Definition of Done".
Once set, we could use this definition as the placeholder for a new Task.
This is probably something that is only editable by the team lead.

AC
- [ ] A "Definition of Done" Editable input lives someone on the new team page. it has a max length of 500 chars-ish?
- [ ] it's only editable by the team lead
- [ ] if < 200 chars, it becomes the placeholder

Effort: 12 points

**Comment by jordanh** [comment]
Scubbed. Iceboxing.

A thought that came up as we work on Sprint Poker: template library for tasks and AC on integrated tasks
