### ISSUE TITLE
Add Team Icon

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3558]
## Issue - Enhancement

I can add an image to my personal profile, giving myself a unique identity, but I can't add an image to my team. If I'm on multiple teams, I end up with several of the same icon in the navigation, and it takes a bit longer to identify which team I want to click on. It's also a lost opportunity to give the team a sense of who it is within Parabol. 

### Acceptance Criteria (optional)
Users can:
   - I can add an avatar or icon for each team I'm a member of

**Comment by jordanh** [comment]
We know this is going to come back around. It's just a matter of when.

Scrubbed. Iceboxing
