### ISSUE TITLE
Options for types of check-ins (Red-yellow-green) 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3559]
### Issue - Enhancement

While the social check-in works well for some teams, others may want different types of check-ins, for example: a red, yellow, green check-in to give a quick sense of how everyone's feeling at the start of the meeting. You could do this right now by just editing the social check-in question, but it'd be cool if you could set it to be this way and/or get some special features when you do this kind of check-in (ex: a team weather map that shows you how you've been feeling over time). 

Related: #3535 

### Acceptance Criteria (optional)
Users can:
   - Set a different type of check-in question

**Comment by gcrickman** [comment]
A user 🔒 writes: 

> I wanted to know if I can do something different than asking those questions, for example inserting a Thermometer where everyone can select how he/she is feeling or inserting emojis where each can select which emoji represents his feelings best

**Comment by ackernaut** [comment]
This reminds me of #1532 and #1531 (oldies!)

**Comment by jordanh** [comment]
Scubbed. Iceboxing.

Deserves to be revisited in context of stand-ups or team health analytics.
