### ISSUE TITLE
Design custom max votes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3570]
Users want to customize how many votes each person gets & how many votes they can cast on each reflection group. Since this is a meeting setting, it should probably live in some kind of an input in the /new-meeting view

Ideas:
- 2 numeric inputs (good, but allows for errors, e.g. too big a number, max votes < max group votes, etc.
- 2 dropdowns (fewer errors, can adjust values after each field is updated)
- a slider with 2 dots (sliders are good for large numbers like volume sliders 0-100, maybe 0-10 isn't big enough)
- 2 steppers (a la airbnb) https://www.nngroup.com/articles/input-steppers/. this feels right for smaller, more exact values. when the max votes stepper is smaller than the max group votes, it updates both

AC
- [ ] When starting a retro, a user can select how many votes each person gets
- [ ] When starting a retro, a user can select how many votes each person can cast for a single reflection group
- [ ] it's impossible to have an invalid value or error message (e.g. when 1 updates & the other is relationally invalid, the other updates)

**Comment by ackernaut** [comment]
See the proposed implementation #3611

**Comment by ackernaut** [comment]
I’m going to take another cycle on this design and look at options for customizing in the vote phase. Status: In Progress

**Comment by ackernaut** [comment]
Here’s [a concept for settings in the live vote phase](https://www.figma.com/file/e2A3pX6HjPzL9udOIkyJkQ/Retro-Voting?node-id=38%3A284)
>Do it live!
