### ISSUE TITLE
Help me find my active meeting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3586]
A user writes:

![image](https://user-images.githubusercontent.com/103000/74788455-9ea55a80-5266-11ea-9ca0-41e552f50da1.png)

This may be a duplicate issue (@ackernaut please guide me) addressing an existing tension. ​What I think might resolve this continuing down the road of the FAB and having it flip to "Join or Start Meeting" if there is at least one active. Clicking it, would show the n-most recent meetings, or a link to the universal lobby where the lobby would list _all_ meetings.

**Comment by jordanh** [comment]
[A customer](https://app.hubspot.com/contacts/3888472/contact/1430601) 🔒  +1'd this request on a private slack.

**Comment by mattkrick** [comment]
During sprint planning we agreed to make the current "active meeting" button loader.

AC
- Louder active meeting button when it needs your attention.
- a snackbar pops up if a meeting has been started within the last 5 mins

**Comment by ackernaut** [comment]
🎨 Concepts for consideration:
- [Using a snackbar](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=95%3A913&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#19495969)
- [Highlighting a phase](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=95%3A913&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#19496070) that the user hasn’t viewed
- [Making the top bar control louder](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=95%3A913&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#19496112)

**Comment by jordanh** [comment]
After reviewing the freshest designs, comments (on this thread an in Figma), I'd like to advocate as AC:

AC

- a snackbar pops up if a meeting has been started within the last 5 mins
- Putting active meetings at the top of the timeline
- Changing the loudness of the top-bar control
   - When there is a notification I haven't seen, style the top-bar control as the primary CTA
   - When I've toggled the top-bar control and there are active meetings, style the top-bar control with the current "red dot" state

Also:
   - Fixing #3619 will help
   - Designing and implementing the team sheet (with a list of active meetings on the sheet) will also help

@ackernaut what do you feel we could proceed with the above AC? Clarifying questions? Reactions?

**Comment by ackernaut** [comment]
### Questions
>When there is a notification I haven't seen, style the top-bar control as the primary CTA

What happens to the Start New Meeting FAB?

>When I've toggled the top-bar control and there are active meetings, style the top-bar control with the current "red dot" state

Do you mean that opening the menu will change the toggle from a primary styling to the alert dot styling?

### Reactions
- +1 for the snackbar
- +1 for the active meetings at the top of the timeline. This will need a quick design pass.
- IMO I’d rather defer making changes to the top-bar menu and the primary FAB until we figure out a cleaner UX. This one still feels too murky. I think we’ll get improvement out of shipping the first 2 bullets. Next step would be a single design cycle scoped to the menu and FAB.

**Comment by jordanh** [comment]
> What happens to the Start New Meeting FAB?

I figured we'd just leave it for now (dueling CTAs!), unless you have a design idea you've got a lot of confidence in.

> Do you mean that opening the menu will change the toggle from a primary styling to the alert dot styling?

Yes, exactly

> IMO I’d rather defer making changes to the top-bar menu and the primary FAB until we figure out a cleaner UX. This one still feels too murky. I think we’ll get improvement out of shipping the first 2 bullets. Next step would be a single design cycle scoped to the menu and FAB.

Safe to try. Some progress over no progress. Write up an implementation issue and let's close this one?

**Comment by ackernaut** [comment]
Moving forward with #3651 #3514 #3650

**Comment by ackernaut** [comment]
3 more users from [this org](https://app.hubspot.com/contacts/3888472/company/2150406832/) 🔒 shared that members of their teams have trouble finding the meeting. What works for them is sharing the direct link to the meeting once it’s started.
