### ISSUE TITLE
Tasks not sending to GitHub 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3587]
### Issue - Bug

I was trying to get a screenshot of a Team Dashboard with a GitHub issue. The board already has a JIRA issue. 

I: 
- Connected GitHub to my account on that team 
- Navigated to the team dashboard 
- Clicked the upload icon for the task I wanted to send over 
- Searched for the right GitHub repo and selected it

Then: 
- I saw the 'GitHub' look for the task for a second, before it reverted to the vanilla version of the task
- The status hung on 'Editing' for a while (several minutes) 
- Upon refreshing, the card did not show it had synced to GitHub
- The issue did not appear in the GitHub repo 

Here's a GIF: 
![github-int-issue](https://user-images.githubusercontent.com/11621016/74788446-99e0a680-5266-11ea-9275-0c488dce5afc.gif)

- **OS:** macOS X Version 10.11.6 
- **Browser:** Chrome 
- **Estimated effort:** 11 points 

### Acceptance Criteria (optional)
Users can:
   - Send a task from Parabol to GitHub 
   - Send tasks to GitHub on a board with JIRA tasks

**Comment by jordanh** [comment]
Added milestone. Added to project sprint board.

**Comment by mattkrick** [comment]
can't reproduce, we'll need to dig into this a bit more.
@avivapinchas can you try this again & let me know the time (+/- 1 min) that you do it? i can then check the error logs & see what shows up

**Comment by avivapinchas** [comment]
Sure thing! Tried it again just now at 5:39 p.m.  CST on 3/17/2020.

**Comment by mattkrick** [comment]
GitHub returns the error "You do not have permission to assign issues in this repository".

Next steps:
- make sure that this message lands in the card footer so the user can see the error
- on error, try using a team member's credentials to see if they can assign tasks.
