### ISSUE TITLE
Demo enhanced to accept template parameter

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3590]
## Enhancement

When I am evaluating Parabol and I've landed on the marketing site expecting me to be educated about a specific type of retro template, I want to start a demo that uses that template, so that I can see how it works

## AC

- [ ] One additional template is chosen aside from "Working and Stuck", then:
   - [ ] Can start the demo with specified retro template 
   - [ ] Demo generates reflections under the appropriate​ columns
   - [ ] Demo groups content under the appropriate columns

**Comment by mattkrick** [comment]
hope to reopen this one soon! will wait for tension to come from marketing
