### ISSUE TITLE
Version mismatch errors reported to user as an action to take

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3595]
## Issue - Enhancement

Currently, when there is a client/server version mismatch we report it as "You found a bug!" even when it's expected behavior:

![image](https://user-images.githubusercontent.com/103000/75282043-36ee9280-57c5-11ea-915e-e40adf90e2ac.png)

When a version mismatch is detected, we should instead tell the user that a thing isn't working because they need to refresh and update their application version instead of reporting it to them as a bug.

### Acceptance Criteria (optional)
When a version mismatch occurs:
   - Say, "Refresh to upgrade!" and explain in place of "You found a bug!"
   - Suppress the Sentry error report

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i don't think this has happened since this issue was filed.
