### ISSUE TITLE
Implement v1 retro discussion thread

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3600]
## Lean first version 🏃 

Updating this from #3545 as a checklist for v1

See Figma:
- [Components on parade](https://www.figma.com/file/UhuGb8dL15bf3ylXoVqS1m/Retro-Discuss-Thread-v1-Prototype?node-id=297%3A77124)
- [Laptop+ prototype](https://www.figma.com/proto/UhuGb8dL15bf3ylXoVqS1m/Retro-Discuss-Thread-v1-Prototype?node-id=321%3A84198&viewport=25%2C644%2C0.03271079808473587&scaling=scale-down)
- [Mobile concepts WIP](https://www.figma.com/file/UhuGb8dL15bf3ylXoVqS1m/Retro-Discuss-Thread-v1-Prototype?node-id=226%3A836)

**Acceptance criteria** is below. **Estimated effort** is a single sprint.

### Adding comments and tasks
- The initial state has a comment input and a separated “Add a Task” button in expanded form
- The expanded control collapses TBD 1) on scroll 2) after a delay 3) after first interaction
- After the first letter is added to the comment field, the task control animates to be the send control
- Comments can be added by pressing enter or the `send` icon
- Comments can include rich copy like task cards (e.g. bold, italic, links, @mentions, etc.)
- When tapping to add a task, the task appears in the thread like a comment in the focused state with the placeholder. Blurring without typing removes the comment/task from the thread
- When comments or tasks are added they animate in, and the thread scrolls so that they are in view if the thread’s not already in that position

### Presenting comments and tasks
- Each comment has an avatar, name, and timestamp
- Bonus points: tapping on the timestamp toggles created/edited time (e.g. `1 hr ago` / `Edited 5 mins ago` where the edited timestamp has the explicit label)
- Task presentation includes:
  - Avatar and name of who created the task
  - A control to reply in the top-right; for v1 we want to try tasks without the ability to add reactions
  - A task card that can be edited or deleted using the task card controls
  - There is no comment, the input becomes the task card description

### Editing/deleting comments
- Authors get a `more_vert` menu control, top-right
- They can edit and delete their comment via menu options
- Editing: comments are edited inline; pressing enter saves the comment and exits editing mode
- Deleting: the message deletes, animating away. Bonus points: either an inline link (indented to where comment copy is located) or a snackbar offers an action “Undo”
- Anon/Public: folks should copy/paste a comment, delete a comment, and create it again if they want to switch from public to anonymous and vice versa

### Reacting to comments
- The initial control (icon: smiley with +) to add reactions is top-right
- Once a reaction has been added the control is inline with the added reaction starting in the bottom-left
- Authors can react to their own comments from an option in the more menu
- No reactions on tasks

### Replying to comments
- Top comments are level 0, replies to comments are level 1
- Level 1 comments are indented, the avatar being left-aligned with the copy of the level 0 comment
- Replies to comments on level 1 are also level 1 comments with the same indention
- Replies to comments on level 1 use the @name of the person who wrote the comment that is being replied to
- The initial control to reply is top-right; it’s always top-right on a task comment
- Once reactions have been added the reply control is bottom-left, before the reactions and reaction control
- Authors can reply to their own comments from an option in the more menu
- The same UI control (and UX) for adding comments or tasks is used to reply with comments and tasks, just indented and raised to the elevation (see Figma)

### Thread layout
- The thread fills the vertical space in a column (laptop+, right of the reflection card grid) or underneath 1 main block of content (mobile, reflection card stack)
- The empty state uses the meta style and encourages the user to add the first comment or task
- The input is fixed at the bottom of the thread
- Scroll to the latest comments at the bottom of the thread

### Reflection cards in the group
- Each reflection has a simple number relative to the group in the top-right (e.g `#2`). In the meantime folks can simply call out or type the number. In the future this will be smart meta that affords filtering options and relates comments and tasks to individual cards.

### Laptop+ layout, Discuss phase view, aka grid + thread column
- The reflection cards are on a grid, using the space that remains after sidebars are opened or closed and the thread column is in place
- The reflections cards are fixed at 296px wide
- The width of the thread column is 344px on a laptop+ view using the reflection card grid
- We can max out the grid on wider displays, say to 4 or 5 cards wide
- Once the feature is available the thread will be filterable by a single card, but use the same layout

### Mobile layout, Discuss phase view option, aka stack and thread
- The meeting chrome is in place (top and bottom bars, etc.)
- The Retro topic information is at the top (title, upvotes, no. reflections)
- The reflection card stack is in place
- The thread vertically fills the view between the stack and the meeting bottom bar or bottom of view
- The thread is probably 100% of the viewport width for mobile, or we can set a max-width to keep it lined up with the card stack
- Tapping the stack shows all cards in a dialog; close to return to the stack and thread
- The user can scroll everything between the Retro topic information and the input and bottom bar. This means that the reflection card stack is at the top of the scrollable space and scrolls away. We should probably default to being scrolled to the top 0 position for mobile. To see all the comments below one must scroll.
- Consider animating the input control to be a FAB on scroll. Tapping the FAB expands to the comment + add task control.

### Adding comments publicly or anonymously
- The avatar near the input can be tapped to toggle public or anonymous comments
- Hover the user avatar to see the anon avatar and a tooltip or vice versa
- Notes: this pattern could be reused when adding reflections. We could consider exposing this as a saved team setting in the meeting lobby. Defaults: anonymous reflections in the Reflect phase; public comments in the Discuss phase
- Anonymous comments have the anonymous avatar
- The public/anonymous state can be changed by the author when editing (tapping the avatar while in editing mode)
- Tasks added in anon mode have the #private tag
- As the #private tag can be added and removed from a task in the thread, the thread and any replies shows to all users or is hidden to all except the owner. We hide any replies to the owner when in private mode.

## Future features 👾 👾 👾 

Each one of these will probably have its own issue:

- Designed: filtering retro discussion threads #3601
  - Referencing reflection cards inline in comments and tasks
  - Filtering by reflection including tapping cards to add the filter, a control for removing/changing at least on mobile, etc.
- Highlighting which comments/tasks the viewer has not seen #3602
- Facilitation focus (can see what the facilitator references but is not tethered, like the reflect phase)
- Collapsing comments in the middle of the thread, or collapsing the replies, etc.
- Adding a video comment instead of a text comment #3603
- Adding a “discuss this later” control and meeting placeholder card-like artifact

**Comment by ackernaut** [comment]
Adding so I don’t lose the text; scrubbing more now…

**Comment by ackernaut** [comment]
@mattkrick let me know if any details are murky, off-spec based on Figma, or out-of-scope for v1

**Comment by mattkrick** [comment]
Deleted Threadable Logic. There are 4 options:
- delete removes it & all children immediately
- delete removes it & all children on refresh
- delete just removes the parent & leaves a tombstone
- delete remove it if no children, or leaves a tombstone if it has children

last option is what slack, reddit do, so i say we implement that.
the trick is the tombstone cannot be a task itself, otherwise it'll show up on the task board.
So, we need to know how to persist a task as a tombstone in the DB.

today, we hard delete tasks.
that's not lovely, so for comments we'll just soft delete them.

i think the tombstoning should probably happen when the thread children try to look up a parentId & it isn't there.
if not found, we simply create a tombstone placeholder, which is a threadable.
to mark it as a tombstone, we could put an `isTombstone` flag on it, or set the content to something like `tombstone`. the first is more expressive, so we'll do that.
