### ISSUE TITLE
Highlighting new comments in the retro discuss thread

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3602]
A continuation of #3600, see [Figma](https://www.figma.com/file/UhuGb8dL15bf3ylXoVqS1m/Retro-Discuss-Thread-v1-Prototype?node-id=311%3A107383)

### Acceptance Criteria
- When there are new comments/tasks added to a retro discussion thread that a user has not seen, they are highlighted
- TBD remove highlight on those that are viewed after a delay or interaction
- TBD what to do, if anything, when new comments/tasks are added while I’m looking higher up in the thread

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
hot, but lots of a work
