### ISSUE TITLE
Show column source on Reflection card during Group phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3604]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/3326051) 🔒 (click through to see video) pointed out to us that members of his team are annoyed our Reflection cards don't show the Reflection prompt source when they are dragged across columns.

### Acceptance Criteria (optional)
When Users group Retro Reflection Cards across columns:
   - Cards from a different column display the prompt in their footer (as they do during the Discuss phase)

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut does this AC seem about right to you?

**Comment by ackernaut** [comment]
We tried that when we updated to column grouping, but the animations were troublesome and janky with the card height being different at times. We yanked that and opted to wait for the prompt coloring, but that’ll take more work.

**Comment by ackernaut** [comment]
The prompt coloring would make a nice BP!

**Comment by jordanh** [comment]
Duplicate of #3124
