### ISSUE TITLE
Enhanced emoji picker for card surfaces

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3605]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/3326051?) 🔒 writes:
> My team gets annoyed when they type `:` to see the emoji menu, it's all happy faces. But mostly, they are annoyed that they can't see which emoji they can pick from.

**Comment by jordanh** [comment]
Is there another emoji picture we can change to easily?

**Comment by mattkrick** [comment]
we basically do what slack does, not sure how to improve. i think using emojimart like reactjis would be a step backwards
