### ISSUE TITLE
Implement custom voting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3611]
See #3570 

#### Customizing from the vote phase
- The vote phase header shows: My Votes, Team Votes, Vote Settings
- Tapping the Vote Settings menu reveals controls:
  - Votes per participant
  - Votes per topic
- Votes per topic can’t be more than votes per participant. We can update both values at once if they bump total per user down or bump total per topic up.
- Let’s set it to a minimal of 1 and a max of 12 to hear from folks.
- Existing votes per user and per topic that are above the limit once the limit is decreased are popped from the user or topic
- The vote settings are stored on the team for the next meeting

#### Casting votes
- See [component variants](https://www.figma.com/file/e2A3pX6HjPzL9udOIkyJkQ/Retro-Voting?node-id=24%3A610) and [an example UI](https://www.figma.com/file/e2A3pX6HjPzL9udOIkyJkQ/Retro-Voting?node-id=24%3A1871)
- Each group gets a `thumb_down` to decrease, a count, and a `thumb_up` to increase
- Disable the controls logically (e.g. all `thumb_up` controls are disabled if I’ve used my max number of votes everywhere)
- Count is blue where I’ve voted; count is 0 with mid-gray color otherwise
- The header “My Votes Remaining” uses a number count instead of icons at all breakpoints
#### Future considerations
- Using a chrome-less input to set the vote count settings instead of just the controls
- Using a fancy ✨ formula for setting the default number of votes based on the number of participants and the number of comments/topics

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
love it, love it all.
the "right size based on reflection count" is an interesting idea, so is the changing while in mid meeting.
you're probably gonna hate me for this, but what if we _only_ let them change it mid meeting? that would keep the "New Meeting" view a little cleaner.

we put steppers on the header of the vote phase for the facilitator.
participants see the same header, just without the steppers.
if i already cast 5 votes & the facilitator tries to set the max to 4, it says it can't do it.
we persist the number of votes they had last time
if we have a "right size me" option, then we persist that too

**Comment by ackernaut** [comment]
I can go ahead and take a pass at showing the controls in the vote phase header. I like the idea of not taking anything away real-time. They can always verbally ask folks to hold off, or remove votes, if they are sync and really need to be precise about fewer votes. I’ll ping in Figma.

**Comment by mattkrick** [comment]
yeah, the alternative would be removing the last vote by the person who now spent too many, but that feels like taking something away, little surprising.
i wish there were a way to "right size" without adding an additional "wtf-does-this-checkbox-do" control. maybe after 12 it turns into "right size"? 
that said, i'm happy bumping the limit up to 99 just because we can

**Comment by ackernaut** [comment]
A concept in progress for [settings in the vote phase](https://www.figma.com/file/e2A3pX6HjPzL9udOIkyJkQ/Retro-Voting?node-id=38%3A284)

**Comment by jordanh** [comment]
[A user writes](https://app.hubspot.com/contacts/3888472/contact/10810251) 🔒 :

> One thing I miss is the possibility to change how many votes one person has.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10972401) 🔒 writes:

> is there a way to change the number of votes each tm gets for topics?

**Comment by jordanh** [comment]
@ackernaut I am thinking we shouldn't delay this any more for a BP. It feels too 🔥 for our users

**Comment by ackernaut** [comment]
Hot diggity dawg!
