### ISSUE TITLE
Summary UX explored

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3622]
### Background

Today we have a summary that both renders as an email and a permalink in the web app. The first thing to validate is what’s really helpful to the user? Are they looking back? Are they sharing with others?

I’ve probably heard the most about the CSV and having all the topics included in the summary, even those that don’t receive votes, because currently there’s no other way this data remains accessible to the user. Folks don’t want to lose data.

Also, now meeting links live on and can be revisited, but the meeting is in a read-only state once it’s completed. We can explore the difference in walking backing through an old meeting vs prescribing a summarized form. Where’s the value?

Some ideas:
- The meeting summary is just a responsive web app view. The email is just a highlight, but to see the whole summary users must click through to the web app view. Sharing this with others who are not a part of the team or the org could trigger some kind of sign-up, sign-in, get accepted flow where they can at least see summaries because they are now an org member or team subscriber. This would be a way to engage existing and new users, causing them to hit the web app. [See Slack](https://parabol.slack.com/archives/C836NA350/p1580414688011000)
- The meetings become more like living workspaces that can be revisited or be in some archived state
- More pondering [in Notion](https://www.notion.so/parabol/Re-evergreen-meeting-spaces-b3f153845ca54817a15c1e9799573faa
) 🔒 

### Acceptance criteria
- One or many proposed user journeys are sketched out with accompanying written notes
- The ideas are reviewed as a team
- One idea is selected and we write any necessary design or implementation issues

### Estimated effort
- 11 points

**Comment by jordanh** [comment]
This is UI level feedback, but worthwhile to capture. A user 🔒 writes:

> The layout of the summary is quite long and narrow which is hard to share as a picture on desktop on slack for example. It would be great if I one could switch to a 16:9 format for this case.

**Comment by ackernaut** [comment]
Yes, this is why I want an abbreviated summary email that taps through to a full responsive summary. I want to decouple those 2 artifacts so that we can do the right thing with the summary view and not depend on the One Thing™ being email-friendly (i.e. long column with bad HTML).

**Comment by ackernaut** [comment]
[Add feedback in Figma](https://www.figma.com/file/FbeY0diFSt5is9999TEJAo7I?node-id=42%3A1265&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#21239707), if you’d like (comments here are okay, too)

- Your team did the thing
- Quick stats (tapping a blue link goes to Topic 1)
- See the Meeting Summary (can see tasks per team member, tap individual topics, get to team dash)
- Give us feedback

![Basic email template](https://user-images.githubusercontent.com/307286/77354278-8a92c400-6d10-11ea-9b35-c3604f2a7fe4.png)

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/12836851) writes 🔒:

> The only thing I've noticed so far that could use some extra love is the retrospective summary — I feel a lot of weight has been put on the tasks, but not so much on the visibility of reflections that led to those tasks. Before switching to Parabol, we'd generate a Confluence page with a summary of our sticky notes and the discussions we had around them, which we would use this as team documentation. The tasks/action points would usually be few and short-lived, but the decision making would stick. With Parabol, I could either download the CSV of the retro and manually generate the confluence pages, or link up to the summary page but both miss the comments/discussion we had about the topics, which makes it harder to compile a decision log — so we're still running double books.

See also #2731

**Comment by jordanh** [comment]
@ackernaut one question on the more svelt summary email: how do we envision folks being able to share their retro summary data with external stakeholders? This is a JTBD the wordier summary takes care of today that we must consider as we evolve...

**Comment by jordanh** [comment]
[A user writes](https://app.hubspot.com/contacts/3888472/contact/11939551) 🔒: 

>I noticed that in the summary you list all retrospective topics, but they are not grouped by prompt (but they are in the csv summary, which is good).
> According to me, it would be very useful to have topic prompt even in the online and email summary, because the mean of a topic may be misunderstood without such information.

Should we display these in a forwardable artifact, adding the prompt context would be useful

**Comment by ackernaut** [comment]
> @ackernaut one question on the more svelt summary email: how do we envision folks being able to share their retro summary data with external stakeholders? This is a JTBD the wordier summary takes care of today that we must consider as we evolve...

Yes, if a literal, full summary is needed to share with others outside of the app, then the condensed concept doesn’t cut it. I was thinking it could tease those folks to come inside and poke around, and at least have some view-only access if they really don’t use the app.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/12492001) 🔒  writes: 

Good morning. I ended a session after the grouping phase. How do I get all of the reflections in an excel format? When I click on “export to csv” in the summary email, nothing comes up.

**Comment by ackernaut** [comment]
> [A user](https://app.hubspot.com/contacts/3888472/contact/12492001) 🔒 writes:
> 
> Good morning. I ended a session after the grouping phase. How do I get all of the reflections in an excel format? When I click on “export to csv” in the summary email, nothing comes up.

To be clear, if the user doesn’t advance to the Discuss phase, the CSV/reflections aren’t included in the summary? Is there a summary or timeline event when ending at Group?

**Comment by gcrickman** [comment]
> > [A user](https://app.hubspot.com/contacts/3888472/contact/12492001) 🔒 writes:
> > Good morning. I ended a session after the grouping phase. How do I get all of the reflections in an excel format? When I click on “export to csv” in the summary email, nothing comes up.
> 
> To be clear, if the user doesn’t advance to the Discuss phase, the CSV/reflections aren’t included in the summary? Is there a summary or timeline event when ending at Group?

Correct, the summary doesn't show any of the reflections if the user doesn't advance to the discussion phase also there seems to be no output option for a CSV if the meeting was not advanced to the discussion phase. There is a timeline event where you can view the reflections under "see the discussion" but the "review a summary" is empty.

**Comment by ackernaut** [comment]
Re: ending at the Group phase, I see as I tried it just now. The timeline event takes you to the last phase of the meeting before it was ended and the summary is empty. Interesting find!

**Comment by tianrunhe** [comment]
The [current implementation](https://github.com/ParabolInc/parabol/blob/27923023f5abac84cf1bf091ce771582796b56a4/packages/server/graphql/types/RetrospectiveMeeting.ts#L106-L114) basically says the `reflectionGroup` need to have its id registered in the discussion stage to be returned. I assume the id association only happens when the discussion phase starts. Therefore if user has not entered that phase, they won't have those topics exported.

I think this might be a bug but would like @mattkrick to chime in if there's any implementation thinking behind it.

**Comment by jordanh** [comment]
Adding feedback from [a user](https://app.hubspot.com/contacts/3888472/contact/16890601) 🔒 :

> I need to keep artifacts of the meeting.  While it is possible to print the summary to PDF, it is a lot of pages.  It would be helpful if the print CSS for the page would make better use of the space on a sheet of paper.

**Comment by mattkrick** [comment]
![Image from iOS (46)](https://user-images.githubusercontent.com/5514175/97195954-208c4280-1769-11eb-8a94-563a5c9f82e8.jpg)

from @avivapinchas wrt summary trends

**Comment by gcrickman** [comment]
[User](https://app.hubspot.com/contacts/3888472/contact/19891251) 🔒  feedback:

> Is there a way we can export the meeting summary in an Excel Document instead to CSV? What options can I do to make that possible?

**Comment by jordanh** [comment]
Related: #4950
