### ISSUE TITLE
DnD Grouping on mobile iOS, dragging card position incorrect

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3633]
## Issue - Bug

When I drag a card on iOS, the drag position is incorrect. The result of this behavior is, when I drop the card, it creates or adds the card to the wrong group.

- **OS:** iOS
- **Browser:** Safari
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - drag cards during the Group phase and have them drop on their intended target

**Comment by mattkrick** [comment]
there's no way i could ever fix this without an iOS device

**Comment by mattkrick** [comment]
the iOS emulator _should_ be able to reproduce this, if it's still an issue?

**Comment by ackernaut** [comment]
I can check real quick on an iPad.

**Comment by ackernaut** [comment]
I ran a quick test on the iPad (iOS 13.6.1) using Safari. I had no problems with DnD when grouping in a retro or changing columns on the team task view.

**Comment by mattkrick** [comment]
👍  closing as it's working as intended
