### ISSUE TITLE
emoji mart fixups

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3639]
AC
- [ ] autofocus on open
- [ ] persist frequently used in the local storage
- [ ] consider allowing folks to tab through options in the menu (currently pressing tab closes the menu altogether)

ee 10.5

**Comment by jordanh** [comment]
Needs EE sir @mattkrick

**Comment by jordanh** [comment]
@mattkrick could we evolve this into a front-end BP?

**Comment by mattkrick** [comment]
nah, just too basic
