### ISSUE TITLE
Designed UI options for users to indicate they’re ready to move on

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3640]
### Acceptance Criteria
- Explored [solution candidates](https://github.com/ParabolInc/parabol/issues/3211) (Is it an explicit control? What are the heuristics?)  
- Sketched and/or created lo-fi concepts
- Wrote notes on solution candidates
- Reviewed concepts internally with the team
- If needed, created a clickable prototype
- Reviewed concepts externally, ideally with a few of the users who gave the related feedback
- Wrote implementation issue(s)

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/7111951) 🔒gave us the following feedback:

> Nice to have: Button, which specifies, that you are done with writing retro points, so the team sees and knows, when everyone is done writing/brainstorming

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/7111951) 🔒 writes:

> Nice to have: Button, which specifies, that you are done with writing retro points, so the team sees and knows, when everyone is done writing/brainstorming.

**Comment by ackernaut** [comment]
See [concepts in Figma](https://www.figma.com/file/n0V5H6PBU0Pf35ctWPlWol/Ready-to-advance?node-id=0%3A1) 🔗 and [related notes](https://www.notion.so/parabol/Design-notes-Mar-2020-7cf55a8090764f01b30e60a804288d3c#00ca54b947fb4fddb13e3ba49f267625) 🔒
