### ISSUE TITLE
Make Google Cloud Language Manager API optional

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3641]
## Issue - Enhancement

For developers who don't have a Google Cloud account or wish to not use Google Cloud, we should make the Google Cloud Language Manager API optional.

### Acceptance Criteria (optional)
Developers and users can:
   - Choose not to use the Google Cloud Language Manager API by unsetting the `GOOGLE_APPLICATION_CREDENTIALS` env var
   - When cards are grouped, they are simply named "Group"
      - Bonus: an algorithm completely internal to the Parabol app choose a significant ngram

- **Estimated effort:** 12-15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by AndreasUfert** [comment]
This is essential for self hosted instances. We really would like to run Parabol for our team but we are limited to AWS resources only.

**Comment by shapel** [comment]
@jordanh is this still actual?

**Comment by shapel** [comment]
@jordanh just a friendly ping ;)

**Comment by nbartels** [comment]
Thanks at @radicand - you saved my day! Maybe it should be possible to disable the Manager via an environment value like GOOGLE_CLOUD_DISABLED or something.

**Comment by Dschoordsch** [comment]
Failing to initialize the `GoogleLanguageManager` [here](https://github.com/ParabolInc/parabol/blob/dab03ac8125ed6a9b596c8e9e1cf26d404eb7914/packages/server/graphql/mutations/helpers/getReflectionEntities.ts#L29) can just fall back to create the new group title in some different way.

**Comment by nbartels** [comment]
I'm wondering what's the idea of this manager, I'm not that deep in TS, so it's a bit hard to understand. It's about getting the topic from a text?

**Comment by Dschoordsch** [comment]
@nbartels the idea of the manager is to create a group name for reflections. Each time you add a card to a group, a group name is suggested based on the contents of all cards, unless you've chosen a custom title already.

**Comment by rafaelromcar-parabol** [comment]
A self-hosted client cannot share reflections in retros due to not having those vars set.

We should add a new variable: `GOOGLE_CLOUD_NATURAL_LANGUAGE='true|false'` to enable or disable this feature, as right now GCP credentials are not only used for this but also for the GCS file store provider. One might want to set up GCP credentials  not wanting to use Natural Language API.
