### ISSUE TITLE
UTM query strings removed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3647]
# Enhancement

## AC

- ~Removed all `?utm.*` strings from links in the product (e.g. the demo)~
  - There are currently no `utm_*` params in the web app
- Removed all `?utm_*` strings from the marketing website (e.g. the homepage)
  - [x] Removed from the homepage content
  - [x] Removed from the global top navigation
  - [x] Removed from the pricing page
  - [x] Removed from Retro 101 page CTAs
  - [x] Updated GitHub repo links from `/action` to `/parabol`

👀 look for:

- `utm_source`
- `utm_content`
- `utm_medium`
- `utm_term`
- `utm_campaign`

**Comment by ackernaut** [comment]
There are no `utm_*` params in the web app. They are only used on the website. Updated AC.

**Comment by ackernaut** [comment]
@avivapinchas I removed the `utm_*` params from the checklist above. Let me know if you see any that I may have missed, and just assign me a specific Parabol task card.
