### ISSUE TITLE
Scrubbed 101 links, action to check-in

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3648]
### AC
When you tap the 101 link, it opens to the new URL
- in the help menu
- in the invite email

### EE
- 10.5​ pts

**Comment by ackernaut** [comment]
@avivapinchas just to confirm: will `https://www.parabol.co/getting-started-guide/action-meetings-101` become `https://www.parabol.co/getting-started-guide/check-in-meetings-101` or did you have a better URL in mind?

**Comment by avivapinchas** [comment]
@ackernaut I've changed the URLs like this: 
`getting-started-guide/action-meetings-101` >> `/resources/check-in-meetings`
`getting-started-guide/retrospective-meetings-101` >> `/resources/retrospective-meetings`
`resources/mission-driven-teamwork/07-action-meetings-keeping-the-team-in-sync` >> `resources/mission-driven-teamwork/check-in-meetings`

I created redirects in Hubspot, so folks who hit the old links will be redirected.

**Comment by ackernaut** [comment]
@avivapinchas thank you, I’ll get to this soon. :)
