### ISSUE TITLE
Agenda phase task card layout overlaps with space

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3649]
### Issue - Bug

In the agenda phase, with several tasks, the space for a task overlaps with a current task. 
![Screen Shot 2020-03-10 at 10 57 22 AM](https://user-images.githubusercontent.com/11621016/76342197-32010700-62cc-11ea-80a7-3b3e88381787.png)

- **OS:** macOS version 10.11.6
- **Browser:** Chrome Version 80.0.3987.122

May be similar to #2455

- **Estimated effort:** 10.5

### Acceptance Criteria (optional)

In the agenda phase, tasks do not overlap with spaces.

**Comment by ackernaut** [comment]
Looks like #2514 strikes again!

**Comment by jordanh** [comment]
Suggested AC:

- [ ] Make Check-In meeting agenda item phase similar to the Retro meeting's Discuss phase – i.e. use threaded discussion component instead

**Comment by mattkrick** [comment]
obviated by threaded discussions
