### ISSUE TITLE
Added snackbar for recently started meetings

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3650]
### Acceptance Criteria
- See [concept in Figma](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=429%3A8324)
- A snackbar appears over any dashboard view when a meeting has started LT 5 minutes ago
- Copy variant ideas:
  - The MEETING_NAME meeting started just now. Join Meeting
  - The MEETING_NAME meeting started N minutes ago. Join Meeting
- The snackbar goes away when 5 minutes have elapsed
- When 2+ meetings have started LT 5 minutes ago, the snackbar shows the oldest one to avoid changing the context on the user without them catching it OR come up with a better heuristic

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10555451) 🔒 writes:

>There were times were teammates wouldn't see the board. We worked around this by DM them the URL of the board directly and they were able to join the retrospective.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/9989151) writes 🔒 :

> The only way it seems that they know is that a tiny dot appears next to the chat/notification icon at the top of the screen. Maybe they can be trained to look there, but it seems like there ought to be more of a notification popping up somewhere.

**Comment by jordanh** [comment]
Putting this one at the top of the next sprint...

**Comment by mattkrick** [comment]
what if the user refreshes the page?
- [ ] the snackbar should reappear if the user refreshes the page
- [ ] the snackbar should never pop up when the viewer is in the middle of a meeting or anything except the dashboard
- [ ] if the viewer is coming from the meeting, it'll still show up
