### ISSUE TITLE
Designed improvements to meeting menu and FAB

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3651]
We need to continue the design efforts from #3586 around improving the meeting menu and FAB.

### Acceptance criteria
- Provided sketches, concepts, and/or clickable prototypes to illustrate:
  - Improved states for the meeting menu that help folks know what needs their attention, see #3533 and [concepts in this comment](https://github.com/ParabolInc/parabol/issues/3586#issuecomment-593549728)
  - Improved states for the Start New Meeting fab, if any, in relationship to the improved meeting menu
  - Consider the active meeting callout in the meeting lobby #3461
  - Consider the addition of active meetings to the timeline #3514 
  - Consider the addition of the recently started meeting snackbar #3650 
- Reviewed as a team
- Reviewed externally, preferably with the users who gave the feedback
- Wrote 1 or many implementation issues

### Estimated effort
- 11 pts

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11184901) 🔒  said during a feedback meeting:

> Finding the meeting needs to be more prominent.

Seems to be the same as #3586

**Comment by gcrickman** [comment]
[User](https://app.hubspot.com/contacts/3888472/contact/7032301) 🔒  feedback:

> Its not obvious for a first time user to identify how to join a retro meeting I believe there is an icon at the top right but its out of the way and doesnt jump out.

**Comment by jordanh** [comment]
The upcoming meetings view makes this obsolete. Iceboxing
