### ISSUE TITLE
Release test for v5.0.0 👾

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3658]
## The basics
Run through this list at least once:
- [x] Smoke tested the Demo, unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notification
- [x] Added GitHub, verified issue created
- [x] Added Jira, verified issue created
- [x] Smoke tested the Retro meeting with 2 players
- [x] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [x] Upgraded to Pro
- [x] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)
## What’s changed
- [x] Tested #3597 → Threads
- [x] Tested #3635 → Lobby layout
- [x] Tested #3656 → Resource links

**Comment by ackernaut** [comment]
### A group disappeared when closing the dialog
- I think I’ve had enough coffee and I’m not crazy
- I closed a reflection group during the Demo Group phase, then it disappeared
- I seem to remember having dragged a card out of the group before closing
- The script creatures were dragging other cards while I was interacting with the dialog
- I can’t reproduce

**Comment by ackernaut** [comment]
### Discuss layout clips scrollable components
- In the Demo Discuss phase
- I can’t scroll to see all of the reflection cards (some are clipped)
- I can’t fully scroll the thread to see everything in it
- This layout problem persists as I add comments/tasks to the thread, but the orientation of the layout seems to change, I guess as the thread gets taller

![Screenshot 2020-03-17 10 12 59](https://user-images.githubusercontent.com/307286/76870686-0768fe00-6838-11ea-9dcd-9acbf17e9ded.png)

**Comment by ackernaut** [comment]
### Dev error advancing through Demo discussion topics

I got this error when advancing quickly through a few topics in the Demo Discuss phase. When I go to those topics I see the dev error message and a problem handling edges of a null object.

>An error has occurred! We’ve alerted the developers. Try refreshing the page

```
instrument.js:102 TypeError: Cannot destructure property 'edges' of 's' as it is null.
    at DiscussionThread.tsx:32
```

**Comment by ackernaut** [comment]
### Anonymous comments in thread
- When the comment first appears I see my avatar flash for a second, then I see the anonymous avatar. It makes me wonder if others see that, too. I check and they don’t but it doesn’t feel right.
- When 2 folks add anonymous comments it’s hard to know which are mine. Mine will have the vertical ellipsis. I think we consider putting “You” or “Psst, you” instead of “Anonymous” when they’re mine and “Anonymous” for everybody else

**Comment by ackernaut** [comment]
### Adding tasks when in anonymous comment mode
- Should we default to these being #private when I’m in anonymous mode? I see that the tasks are hidden when the #private tag is added, and they are shown again when the tag is removed.

**Comment by ackernaut** [comment]
### Meeting lobby layout on mobile
- We set the lobby to be centered vertically. I’m thinking at mobile widths, we wait until a minimal viewport height to center. This way when you’re switching meeting types on mobile the content won’t jump around. Either that or we put a min-height on the inner container. That may be easier.

**Comment by mattkrick** [comment]
> A group disappeared when closing the dialog

i dont' doubt it, we'll just need a repro to tackle it

> Discuss layout clips scrollable components

reflection column fixed, but i can't repro the problem in the thread

> Dev error advancing through Demo discussion topics

can't reproduce, but put a safety around it

> Anonymous comments in thread

optimistic update fixed
`Anonymous (You)`

> Adding tasks when in anonymous comment mode

i think coupling the 2 when they mean very different things would get confusing for folks, but happy to revisit if we get crap for it

> Meeting lobby layout on mobile

yeah, fixing the height of the top sounds good. fixed
