### ISSUE TITLE
server error on `createTask`

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3669]
## Issue - Bug

App version `v5.0.0`. Steps taken:

1. Create task, note that optimistic task is created then disappears when error returned from server
2. See error in console `Network` tab, Websocket trace

More:

1. If you reload, pending `createTask` succeeds
2. You can complete task card
3. Subsequent new task creation attempts fail

- **OS:** macOS
- **Browser:** Chrome
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Reliably create tasks

**Comment by mattkrick** [comment]
fixed in 5.0.1
