### ISSUE TITLE
Upon upgrade: why was my cc declined?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3671]
## Issue - Enhancement

Opening to track.

[A user](https://app.hubspot.com/contacts/3888472/contact/3322301) 🔒 wrote while upgrading:

> Hi there! I am trying to input my payment information for a Pro account but the credit card I'm using is saying it's declined. Is there a way to know why? Is the subscription rate in USD?

**Comment by mattkrick** [comment]
fixed by adding the error props to the sentry error.
