### ISSUE TITLE
Seeing discussion items after meeting completition

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3672]
After launching our threaded retro discussion feature in `v5.0.0`, we started to get feedback that folks would like to see the discussion items after the meeting.

People may be entering discussion items thinking they are commitments to a next step, such as "let's greet each other on Slack when we start work tomorrow!"

I'll log feedback here and offer a few thoughts below. I'll also invite users to comment on this thread as I reply to incoming feedback.

This Issue will be closed when we've got some next steps we can add to our development backlog.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/9763801) 🔒 writes:

> I updated to the latest version of Parabol before my meeting this morning, which included a new way of taking notes for tasks/comments. I made several comments throughout the meeting that were not included anywhere in the meeting summary. Is it possible to retrieve those? Or where may I find those?

**Comment by jordanh** [comment]
A user writes:

> I facilitated a quick retro (mad, glad, sad) for my team today, we summarised action points as comments in the “discussion”-part. Is there any way to summarise these topics with comments afterward? The main summary is a bit too extensive and I can’t see any comments there.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10810251) writes 🔒:
> We wrote some “Discussion & Take-away Tasks”. But in the Meeting Summary, there is only one task. Is there a possibility to see what we’ve wrote during the retro in the “Discussion & Take-away Tasks”?

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11103201) 🔒 writes: 👍 

> We just had a retro and took a ton of important notes using the parabol tool. It looks like in the summary _none_ of the comments we wrote are available for review. There is a place to review action items, but we did not schedule any “tasks” to anyone.
>
> Is there a way we can view these, or recover them? It’d be really wonderful if we could. Let me know if there is anything we can do to help.

**Comment by gcrickman** [comment]
A user writes:

> Is there a way to find the comments in a retrospective after the session has ended?

**Comment by tianrunhe** [comment]
To add on this, today we can link back to completed meeting to see discussions but that only applies for retro meeting, not check-in meeting:

![](https://user-images.githubusercontent.com/1879975/86163253-d6e66080-bac4-11ea-9367-90c849a04e11.png)

**Comment by avivapinchas** [comment]
>  I'll also invite users to comment on this thread as I reply to incoming feedback.

This brings up questions for how users engage with those new comments: 
- How do I know that someone has added a comment in a Thread I participated in or might be interested in? 
- Is it a notification? Does it solely live within Parabol? How do integrations like Slack factor into this?

**Comment by jordanh** [comment]
Closing with #3870
