### ISSUE TITLE
Make notifications panel taller / longer 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3675]
## Issue - Enhancement

Currently, notifications open in a fairly small panel, which requires lots of scrolling to see notifications. If we made the panel taller, it would be easier to get a sense of notifications. Especially since these tend to come in batch after a meeting, it would be useful to see more of them at once. 

![Screen Shot 2020-03-20 at 4 48 13 PM](https://user-images.githubusercontent.com/11621016/77208803-9bea8f00-6aca-11ea-94ac-255004ef8327.png)

### Acceptance Criteria (optional)
Users can:
   - Open the notification panel and see several notifications 
   - Scroll to see additional notifications 
   - Backlogged design issue addressing related tensions: clear all notifications, etc.
   - Segment event added:
      - `Notification menu opened`
      - `Notification item linked clicked`

- **Estimated effort:** 11 points

**Comment by ackernaut** [comment]
Thanks for capturing! I’ve noticed this, too. With AC, EE, and a milestone it can be added to the backlog of the sprint board

**Comment by jordanh** [comment]
Definitely still and issue. I'm_certain_ we'll get to this someday.

Scrubbed today. Iceboxing by policy. Will be re-opened / linked to when we prioritize in the future. Likely during a dashboard IA / UX / UI overhaul
