### ISSUE TITLE
Spanish documentation / l18n

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3677]
Opening an Issue to track the number of user requests for Spanish documentation or localization.

We'll close this thread when it either goes stale or we have a resolution into a new issue.

**Comment by jordanh** [comment]
A user writes 🔒:

> Do you have help instructions in Spanish?

**Comment by mattkrick** [comment]
google analytics says 1% of users have their language set to spanish. feels safe to push this out

**Comment by mattkrick** [comment]
with 1 request, feels safe iceboxing

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/28106751) 🔒 writes:

> Subject: Spanish Translation
> Message: I don't know if you are already working on different languages, but if you are, I would love to help with the spanish translation.

> I work with international teams, mostly english speaking, but some just speak spanish. Having the UI and suggestions available in spanish would definitely help.

**Comment by jordanh** [comment]
We'll @gcrickman reopened. Going to keep open until it goes stale again

**Comment by mattkrick** [comment]
stale again
