### ISSUE TITLE
Make ended meetings easy to re-enter

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3680]
@ackernaut 

i'll be building this out today, please comment/edit the AC as you see fit

AC
- [x] Phase completed banner added per #3421
- [x] reflect phase shows all reflections even after grouping (if not too hard)
- [ ] timeline artifacts point to the meeting, not the summary
- [ ] goto summary link added in left nav (if meeting not killed)
- [x] meeting completed tag added in top left

Effort: 11 points

**Comment by ackernaut** [comment]
Very cool! Here are some inline comments from Figma:

- [Re: completed state and bottom bar](https://www.figma.com/file/1DSwgYv0nRffpvb0Jnuc6G?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#20952649)
- [Re: timeline events](https://www.figma.com/file/FbeY0diFSt5is9999TEJAo7I?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#20954912)
- [Re: summary, a direct link per topic could be helpful](https://www.figma.com/file/FbeY0diFSt5is9999TEJAo7I/Retro-Meeting-Summary?node-id=26%3A314)
