### ISSUE TITLE
Error when installing on windows using gitbash

### ISSUE THREAD

**Issue by imranazad** [ParabolInc/parabol#3681]
I've installed yarn and followed all the instructions on the readme but when running yarn dev I get the following errors:

`yarn run v1.22.4
$ yarn workspace parabol-server dev
$ node webpack/buildDll.js && node server.babel.js
buildDll.js: using cached DLL
Error: ENOENT: no such file or directory, scandir 'C:\_src\parabol\build'
    at Object.readdirSync (fs.js:921:3)
    at makePathnames (C:\_src\parabol\packages\server\utils\StaticServer.ts:46:1)
    at C:\_src\parabol\packages\server\utils\StaticServer.ts:65:1
    at Array.forEach (<anonymous>)
    at new StaticServer (C:\_src\parabol\packages\server\utils\StaticServer.ts:62:1)
    at Object.<anonymous> (C:\_src\parabol\packages\server\utils\serveStatic.ts:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module._compile (C:\_src\parabol\node_modules\pirates\lib\index.js:99:24)
    at Module._compile (C:\_src\parabol\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at newLoader (C:\_src\parabol\node_modules\pirates\lib\index.js:104:7)
    at newLoader (C:\_src\parabol\node_modules\pirates\lib\index.js:104:7)
    at Object.newLoader [as .ts] (C:\_src\parabol\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\_src\\parabol\\build'
}`

and then I get a multitude of other errors:

`��� Ready for Action ���
i ｢hot｣: WebSocket Server Listening on localhost:8082
i ｢hot｣: Applying DefinePlugin:__hotClientOptions__
i ｢hot｣: webpack: Compiling...
i ｢hot｣: webpack: Compiling Done
× ｢wdm｣: Time: 17326ms

ERROR in ../client/Atmosphere.ts
Module not found: Error: Can't resolve '../server/graphql/queryMap.json' in 'C:\_src\parabol\packages\client'
 @ ../client/Atmosphere.ts 192:31-72 290:31-72
 @ ../client/components/AtmosphereProvider/AtmosphereProvider.tsx
 @ ../client/Root.tsx
 @ ../client/client.tsx
 @ multi ../client/client.tsx
`

What am I doing wrong?

**Comment by ackernaut** [comment]
We recently pushed updates. I would double check the readme and that you’ve pulled latest.

Is the database running? Have you tried `yarn build`?

We can chat faster (when available) on our [dev community Slack instance](http://slackin.parabol.co/)

**Comment by imranazad** [comment]
@ackernaut thanks for the swift response.

So I've just cloned a fresh copy and went through all the installation instructions and I'm still getting the same error.

Here's the output from yarn build

`yarn run v1.21.1
$ yarn workspace parabol-server build
$ yarn build:relay && yarn build:client
$ yarn update-schema && yarn build:relay-unsafe
$ node utils/updateSchema.babel.js && yarn tsgen
Schema updated!
$ gql2ts ../../build/schema.json -e $(pwd)/../client/types/config.js -o ../client/types/graphql.ts && eslint --fix '../client/types/graphql.ts'
/../client/types/config.js was unexpected at this time.

C:\_src\parabol\packages\server>  "C:\_src\parabol\packages\server\node_modules\.bin\\node.exe"  "C:\_src\parabol\packages\server\node_modules\.bin\\..\..\..\..\node_modules\gql2ts\dist\index.js" ../../build/schema.json -e $(pwd)/../client/types/config.js -o ../client/types/graphql.ts
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 255
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Users\iazad\.yarn\releases\yarn-1.21.1.js build
Directory: C:\_src\parabol\packages\server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I can confirm the database is running and all the tables appear to be there.

**Comment by mattkrick** [comment]
ah, forgot to mention `yarn build:relay` updated the readme. thanks for the report! if this doesn't work feel free to ping again to reopen!

**Comment by imranazad** [comment]
@mattkrick 

Thanks for getting back to me. I tried that but that didn't work unfortunately. I'm still getting errors:

`$ yarn && yarn db:migrate && yarn build:relay && yarn dev
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "immutable@3.8.2" is incompatible with requested versio
n "immutable@~3.7.6"
warning Resolution field "immutable@3.8.2" is incompatible with requested versio
n "immutable@~3.7.4"
warning Resolution field "immutable@3.8.2" is incompatible with requested versio
n "immutable@~3.7.4"
warning Resolution field "immutable@3.8.2" is incompatible with requested versio
n "immutable@~3.7.4"
warning Resolution field "immutable@3.8.2" is incompatible with requested versio
n "immutable@^4.0.0-rc.12"
success Already up-to-date.
Done in 1.82s.
yarn run v1.21.1
$ yarn workspace parabol-server db:migrate
$ yarn db:migrate-up-all
$ node database/migrate.babel.js up --all
Migrating DB actionDevelopment
[migrate-rethinkdb] No new migrations
Done in 5.02s.
yarn run v1.21.1
$ yarn workspace parabol-server build:relay
$ yarn update-schema && yarn build:relay-unsafe
$ node utils/updateSchema.babel.js && yarn tsgen
Schema updated!
$ gql2ts ../../build/schema.json -e $(pwd)/../client/types/config.js -o ../clien
t/types/graphql.ts && eslint --fix '../client/types/graphql.ts'
/../client/types/config.js was unexpected at this time.

C:\_src\parabol\packages\server>  "C:\_src\parabol\packages\server\node_modules\
.bin\\node.exe"  "C:\_src\parabol\packages\server\node_modules\.bin\\..\..\..\..
\node_modules\gql2ts\dist\index.js" ../../build/schema.json -e $(pwd)/../client/
types/config.js -o ../client/types/graphql.ts
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
error Command failed.
Exit code: 255
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Users\abc\.yarn\releases\yarn-1.21.1.js build:relay
Directory: C:\_src\parabol\packages\server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about thi
s command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
`

**Comment by mattkrick** [comment]
are you running in powershell? trying googling for "was unexpected at this time". Unfortunately none of us use windows. If you still can't fix it, I'd suggest loading a linux VM & running there

**Comment by imranazad** [comment]
No just in gitbash I've also tried in CMD. Righto, thanks.
