### ISSUE TITLE
Implemented next version of meeting bottom bar

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3688]
### Acceptance Criteria
- TK ackernaut (taking a Parabol card / Slack reminder to write out draft of specs)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
speced in #3698
