### ISSUE TITLE
Allow For Un-anonymous reflections

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3702]
Some users would like to put their name on the reflection they write during a retrospective.

Acceptance Criteria
- The design for this should look similar to the discussion thread comments for anonymous commenting
- The viewer should be able to toggle anonymity on/off for each reflection
- When a reflection is written with an author, it should be visible on the card in the group/vote/discuss phases

**Comment by jordanh** [comment]
Duplicate of #3772
