### ISSUE TITLE
Allow Users to Revisit Check-in Meetings

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3704]
Similar to #3683, but for Check-in Meetings

Acceptance Criteria
- [ ] after a phase is complete it says "Phase Completed"
- [ ] after a meeting is completed, it says "Meeting Completed" in the left nav header
- [ ] can go to the timeline view & see the ended meeting. It includes the total tasks & comments & agenda item discussed
- [ ] from the timeline event can go back into an old meeting to see the discussion

Estimate: 6 hours

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/15184101) writes:

> Hello! My team has been using Parabol for Team Check-ins and it's working great for tasks, but we're having an issue figuring out how to get back and see the agenda topics (and notes commented on them) for past check-ins. How do we go back and do that?
> 
> Thanks so much for your help!
