### ISSUE TITLE
Add Team Filter to Timeline

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3715]
Today, we don't have a search bar on the timeline view. This makes is hard to see all the meetings for a particular team.
This work unlocks the Team View since Team View will have a link to the timeline with a set teamId parameter.

Acceptance Criteria
- [ ] At the top of the timeline there is a Team filter dropdown that looks like the Team filter dropdown in the Tasks view
- [ ] Clicking the dropdown shows every active team that a user is apart of
- [ ] Selecting a team will show the timeline items for the selected teamId
- [ ] the teamId state is kept in the query params, e.g. /me?teamId=<abc123>
- [ ] clearing the filter returns the current events

Estimate: 20 hours

**Comment by jordanh** [comment]
Going to icebox this one per policy. @ackernaut please fish out if this becomes a crucial part of future IA/UX
