### ISSUE TITLE
Blank summary emails

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3719]
### Steps

- Start a meeting and terminate it early
- Look for a blank summary email
- I’ve confirmed this in the production, staging, and local envs

### AC

- We don’t send a blank email for a meeting that is terminated early

### EE

- 1 hr

**Comment by jordanh** [comment]
I have reproduction steps! Huzzah! The clue was in a report from a user.

Repro steps:

1. Start retro
2. Enter some reflections (I use 'foo' 'bar' and 'biz' in one column), proceed to group
3. Create no groups, proceed to vote
4. Spend 1 vote on first group, proceed to Discuss
5. Enter Comment, "hello, world."
6. Enter Task, "hello, world."
7. Using leftnav, navigate back to Group
8. Click on "End Meeting."

Note blank summary!

**Comment by jordanh** [comment]
Probably even better than above is link to broken summary from a real user: https://action.parabol.co/new-summary/4Um6wlBG3v

**Comment by mattkrick** [comment]
Looks like we could revisit the end meeting logic.
When a meeting is "killed" (ended before getting to the last phase), should we:
- send a "meeting completed" segment event? or send a "meeting killed" event?
- create a timeline event on the timeline?
- send a meeting summary?

@avivapinchas i got a feeling you got some good opinions on this
