### ISSUE TITLE
Allow viewing a meeting for a team member who joined after it was completed

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3721]
`activeMeetings` shows all meetings
however, looking up a meeting only returns a meeting if you were a member of it.
we need to have the same logic for both

AC
- [ ] perms rethought & inmplemented

Estimate: 2 hours

**Comment by mattkrick** [comment]
this is still a nasty bug with a growing amount of tech debt attached to it. removing stale tag

**Comment by jordanh** [comment]
This is probably going to look like Slack, where when you invite a new person we ask if the new users should be able to see the old objects

**Comment by jordanh** [comment]
@mattkrick I wonder if we should close this in favor of a design issue?

**Comment by jordanh** [comment]
See also: #4539, #4540, #4688

**Comment by jordanh** [comment]
Closing in favor of linked issues
