### ISSUE TITLE
Add Mailgun Logger

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3724]
Mailgun only saves data for 5 days at our current level.
There's a tool that will query mailgun every x days & persist it to a DB
We should probably do that.
https://github.com/jackjoe/mailgun_logger

AC
- [ ] mailgun logger deployed & run via cron job

Estimate: 8 hours

**Comment by abhiaiyer91** [comment]
How is the system deployed today? What frequency is the cron job?

**Comment by mattkrick** [comment]
currently we don't use this at all. it'd be great if you wanted to set it up!

**Comment by mattkrick** [comment]
flagging as devops. this would be a fine first step after getting postgres set up.

**Comment by Dschoordsch** [comment]
This is about logging, right? Shouldn't this be send to Datadog instead, maybe sth. like https://github.com/darron/mailgun_datadog
