### ISSUE TITLE
Add more Segment events to better understand user behavior 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3726]
### Issue - Enhancement

Currently, mostly log behaviors around running or not running a check-in or retro meeting. I'd like to better understand how/if users are engaging with other features. 

Here's a wishlist: 
- Connected Jira, Github or Slack - we know the number of tasks sent, but not whether the integrations are connected in the first place. If they're not connected, that would tell us it may be an education issue. If they are connected and not using it, it points to a different question. 
- Slack notification sent, including which type (start meeting, end meeting, time limit) - This would tell us what parts of this integration are used most. 
- Ran social check-in, incl type of meeting as a parameter - This would tell us how popular this feature is. We could use that information to decide if we want to highlight social check-ins more. 
- Used Retro Template, incl 'customize' - This would tell us which formats are most popular. We can then share those trends, write more about popular formats, or introduce novel formats to teams that may benefit from them. 
- Mentioned on task -  This would tells us whether folks are mentioning each other, which would let us know if that's a feature that folks are discovering or if we need to introduce it more. 
- Set task deadline - This would tell us if deadlines are part of teams' workflows. Again, could point to us sharing more about this feature. 
- Reflection added - We could understand how many reflections are typically added per person or per retro, and then potentially advise teams who are adding fewer reflections. 
- Link clicked: page where clicked (timeline, tasks, team, notif menu, etc.), what it is (discussion, summary, task, etc) - This would tell us how folks are engaging with different parts of the app. Right now, we know people visit the Timeline, but not if they then do something when they get there. Knowing this would tell us if investing further in that experience is worth it. 
- Notification menu opened - We have a notification menu for when you're tagged, but I don't believe we know if people are looking at it. This would tell us whether to invest in that feature. 
- Added agenda item - We could understand how teams are engaging between meetings. Since check-in meetings are less common, I imagine this is an undiscovered feature, but want to validate this and also see if teams that do run check-ins are using it at least. 
- Upgrade modal viewed - would tell us how effective the modal is 
- Upgraded offline - would tell us when teams upgrade outside of the modal (ie via a sales convo), so we can better understand conversions 
- For all events (ex:  'WebSocket connected' event, 'Meeting completed' event, & above), add 'subscription type' parameter (personal, pro or Enterprise) 

I realize some of this data may be available in a place I'm not familiar with, so if it is, please just let me know! 

### Acceptance Criteria (optional)
Users can:
   - Include the above in an Amplitude funnel 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Closed in favor of smaller issues opened above 👆
