### ISSUE TITLE
Add more Segment events to understand conversions 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3729]
### Issue - Enhancement

As part of issue #3726, add events to better understand conversions: 
- Upgrade modal viewed - would tell us how effective the modal is
- Upgraded offline - would tell us when teams upgrade outside of the modal (ie via a sales convo), so we can better understand conversions
- For all events (ex: 'WebSocket connected' event, 'Meeting completed' event, & above), add 'subscription type' parameter (personal, pro or Enterprise)

### Acceptance Criteria (optional)
Users can: Include the above in an Amplitude funnel

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by avivapinchas** [comment]
Don't see the `credit card modal opened` event in Amplitude - reopening

**Comment by jordanh** [comment]
Client-side events are presently broken in production, but fixed on a branch. Going to park this issue in Stuck until deployed and then will retest
