### ISSUE TITLE
Add more Segment events to understand how users move through the app 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3730]
### Issue - Enhancement
As part of issue #3726, add events to better understand user flow:
-  Link clicked: page where clicked (timeline, tasks, team, notif menu, etc.), what it is (discussion, summary, task, etc) - This would tell us how folks are engaging with different parts of the app. Right now, we know people visit the Timeline, but not if they then do something when they get there. Knowing this would tell us if investing further in that experience is worth it.
- Notification menu opened - We have a notification menu for when you're tagged, but I don't believe we know if people are looking at it. This would tell us whether to invest in that feature.

### Acceptance Criteria (optional)
Users can: Include the above in an Amplitude funnel

### Estimated effort: X points (see CONTRIBUTING.md)

**Comment by avivapinchas** [comment]
I don't see these events added in Amplitude - reopening this issue

**Comment by jordanh** [comment]
See #3729
