### ISSUE TITLE
Add more Segment events to understand retro behavior 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3731]
### Issue - Enhancement
As part of issue #3726, add events to better understand which retro features are used more often: 
- Used Retro Template, incl 'customize' - This would tell us which formats are most popular. We can then share those trends, write more about popular formats, or introduce novel formats to teams that may benefit from them.
- Ran social check-in, incl type of meeting as a parameter - This would tell us how popular this feature is. We could use that information to decide if we want to highlight social check-ins more.
- Reflection added - We could understand how many reflections are typically added per person or per retro, and then potentially advise teams who are adding fewer reflections.

### Acceptance Criteria (optional)
Users can: Include the above in an Amplitude funnel

### Estimated effort: X points (see CONTRIBUTING.md)

**Comment by mattkrick** [comment]
- Meeting Completed event has meetingTemplate name
- will add `hasIcebreaker` boolean to Meeting Completed
- Reflection Added event will be created with userId, teamId & meetingId
