### ISSUE TITLE
Add more Segment events to understand integration usage 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3733]
### Issue - Enhancement
As part of issue #3726, add events to better understand conversions:
- Connected Jira, Github or Slack - we know the number of tasks sent, but not whether the integrations are connected in the first place. If they're not connected, that would tell us it may be an education issue. If they are connected and not using it, it points to a different question.
- Slack notification sent, including which type (start meeting, end meeting, time limit) - This would tell us what parts of this integration are used most

### Acceptance Criteria (optional)
Users can: Include the above in an Amplitude funnel

### Estimated effort: X points (see CONTRIBUTING.md)

**Comment by mattkrick** [comment]
integrations look like:
```
segmentIo.track({
      userId: viewerId,
      event: 'Added Integration',
      properties: {
        teamId,
        service: 'Atlassian'
      }
    })
```

slack notifications look like:
```
segmentIo.track({
      userId: viewerId,
      event: 'Added Integration',
      properties: {
        teamId,
        service: 'Slack'
      }
    })
```

**Comment by avivapinchas** [comment]
The Slack event looks like it's adding the integration - are there events added also for notifs being sent?
