### ISSUE TITLE
Timeline bug IPhone SE

### ISSUE THREAD

**Issue by mikennaji** [ParabolInc/parabol#3737]
## Issue - Bug

[Timeline won’t open on IPHone SE]

![5807A029-774E-40E5-980A-53652EFA5607](https://user-images.githubusercontent.com/11260020/78908969-d6ec3c80-7a50-11ea-81aa-2c8f532b46f9.png)

- OS : iPhone SE
-Browser : Safari 

Edited by @jordanh EE and AC removed

**Comment by jordanh** [comment]
- Estimated effort: 4 hours

 Acceptance Criteria (optional)
   - Sentry scrubbed for matching exception
   - Root cause identified and fixed or new issue opened

**Comment by jordanh** [comment]
Adding to sprint. @ackernaut could you try to repro or ask for clarification?

**Comment by ackernaut** [comment]
I’m unable to reproduce this on an iPhone using Safari. @mikennaji are you still seeing this issue? In the screen shot above it looks like you’re using Safari, is that correct?

**Comment by mikennaji** [comment]
Yes I’m using safari . The timeline opens in iPhone XR and fails on an iPhone SE . @ackernaut

**Comment by ackernaut** [comment]
Good to know @mikennaji thanks! What version of iOS is running on the iPhone XR, and what version on the iPhone SE?

**Comment by mikennaji** [comment]
@ackernaut The IOS XR is 13.3.1(17D50)  and IOS SE is 11.2.6(15D100)

**Comment by ackernaut** [comment]
I suspect that the older version of iOS is also running an older version of Safari and we might find a bug there in how the production JavaScript is being run. Is it possible to update the iPhone SE to a new version and try again? Being a small team that provides a largely free and OS tool we are currently unable to support older browsers and operating systems as a default policy unless we have a strong case to do the work (e.g. a security issue). I’m closing this issue, but we can continue the conversation as needed.
