### ISSUE TITLE
Stress Test a Meeting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3739]
Background: We have some clients who want to run retrospectives with 60+ people. This might make our server catch fire. To find out, we need to test. This is hard for us to test today.

Acceptance Criteria:
- [ ] Using autocannon (or similar) create a stress test that takes the # of participants as input & records CPU & memory consumption
- [ ] the meeting should be as real-world as possible. 
- [ ] connectSocket event should fire for each
- [ ] every participant creates 8-10 reflections 
- [ ] the pub/sub has to publish the results to all the other users
- [ ] grouping 2 cards together involves ~100 drag & drop location update events
- [ ] votes are all spent for every participant
- [ ] 2 tasks & 3 comments are created for every participant for every discussion topic
- [ ] build a trigger (e.g. graphql mutation on the internal schema or script to run) so we can test this on the staging server
 
Estimate: 30 hours

**Comment by mattkrick** [comment]
keeping open for a future BP

**Comment by jordanh** [comment]
Going to keep this open, good BP material
