### ISSUE TITLE
Retro: Move my reflections between columns during Reflect

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3740]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/406101/?_t=1586618614998) 🔒 writes:

> It's a pain in the butt that you can't move cards between categories during the Reflect phase once you've made them

### Acceptance Criteria (optional)
Users can:
   - move a Reflect card between reflection columns during the Reflect phase

- **Estimated effort:** 4 hours, 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by 87prashant** [comment]
Is this issue still active?

**Comment by Dschoordsch** [comment]
I think this needs some design first as it doesn't seem straight forward for me how you would move a card, especially when more than one reflection was added already.

**Comment by Dschoordsch** [comment]
@87prashant if you feel comfortable proposing a design to solve this, you can still do it if you want.

**Comment by 87prashant** [comment]
I haven't tried it yet but I guess the same way we do in the group phase: After opening the reflection list and we could drag the reflection to the other columns
