### ISSUE TITLE
GitHub project-inspired Task assignment picker

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3754]
The GitHub UX/UI pattern for picking from among multiple kinds of things is smart:

![image](https://user-images.githubusercontent.com/103000/80516339-2cbd5180-8938-11ea-82a4-dcfd536a4c20.png)
​
We could use a similar design pattern for:

- Choosing to assign a project to a team member or a different team entirely
- Choosing to promote a Task to a Note (in a future version of Parabol)
- etc

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11902251) 🔒  writes:

> I was thinking about my feedback: being able to un/assign tasks from a person: you should be able to assign multiple people to a task (group them as a role would be a nice touch) and assign all at a touch of the button – but these should not go to a standard task Kanban board.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/19655801) 🔒  writes:

> Is there a way to assign multiple users to a task?

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for how.
