### ISSUE TITLE
Add "Confirmation" Flow to next button

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3755]
People advancing before they are ready is bad

AC
- [ ] when there are 3+ people in a meeting and fewer  than n - 1 people are ready, clicking "next" requires a double click within 3 seconds
- [ ] end meeting confirmation added, too

Estimate: 4 hours

@jordanh EDIT: added end meeting AC

**Comment by jordanh** [comment]
@ackernaut could you give a touch up to how the countdown works? Is it a circle that counts up or counts down? Does the label say confirm?

**Comment by ackernaut** [comment]
> @ackernaut could you give a touch up to how the countdown works? Is it a circle that counts up or counts down? Does the label say confirm?

Response: [see comment in Figma](https://www.figma.com/file/n0V5H6PBU0Pf35ctWPlWol?node-id=38%3A2946&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#24164562)
