### ISSUE TITLE
Add Segment events to understand user creation 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3756]
### Issue - Enhancement

Currently, we track account behaviors, but not (afaict) creating accounts, properties of teams. Would love to track: 
- Account created: A user account is created. Including a parameter for something like 'source' to indicate if the account came from a meeting invite, a team invite, or if they signed up themselves without being invited. 
- Org created: An organization is created, including when it's created because the user created an account. This would help us understand the lifecycle of organizations, so how long till they have a first meeting or a second team. Knowing that would allow us to better time communications to them. 
- 'Team Number' property on 'New Team' event: This would be a property for what number team it is, so for ex the 3rd team created in the org would show '3'. We'd use this to, for example, create a funnel showing what users do after they create their 3rd team. 
- 'Meeting Number' property on 'Meeting Completed' event: similar to the above, this would show what number meeting it is for a given team. If a team had run 2 meetings, this would who '2'. 
- Invited via email: we currently track when a user sends an invitation, but when someone is invited. Having this event would let us understand the flow from being invited to accepting and doing other things. 

### Acceptance Criteria (optional)
Users can:  Include the above events in an Amplitude funnel

**Comment by mattkrick** [comment]
Questions:

> An organization is created, including when it's created because the user created an account. 

I'm a little unclear on what this means. Would the following suffice?
- When an organization is created because a user signed up organically (not from an invitation), we send an "Org Created" event with `isInitialOrg` set to `true`
- When an organization is created because the User clicked "New Team" and added a new org, we send an "Org Created" event with "isInitialOrg" set to `false`

> Invited via email

There's some overlap between this event & `Account created`. if a new user accepts an invitation from a meeting, you want both an `account created(team invite)` and an "invite accepted" event? what properties would you like to include on the  event?

**Comment by avivapinchas** [comment]
> When an organization is created because a user signed up organically (not from an invitation), we send an "Org Created" event with isInitialOrg set to true
> When an organization is created because the User clicked "New Team" and added a new org, we send an "Org Created" event with "isInitialOrg" set to false

Yep, that's perfect 

> There's some overlap between this event & Account created. if a new user accepts an invitation from a meeting, you want both an account created(team invite) and an "invite accepted" event? what properties would you like to include on the event?

So this event would be for being _sent_ an invitation, and then if they went ahead and accepted and created an account, then we'd get the `account created` event too. Presumably, almost 100% of folks who are sent an invitation then go ahead and sign-up, but we don't firmly know that, and perhaps they're getting stuck before they create an account. Does that make sense? 

In terms of properties, I see using this in a few ways: 
- To create a funnel from invited - accepted - completed meeting - don't think we need any properties for this
- To understand how different types of invites (meeting invite vs team invite) perform in terms of getting sign-ups, so probably a property for 'type' 
- Maybe also to understand how many invites are sent at a time on average, so with a funnel for `sent invite` and then `invited by email`?

**Comment by mattkrick** [comment]
oh shoot, i'm lost again.

- what's the difference between the current `Invite Email Sent` and `Invited via Email`?
- if i invite someone who is already a parabol user, the `account created` event won't fire, so our funnel metrics will look worse than they actually are. (e.g. invite 10 people, 8 are already on parabol, 2 sign up, funnel says only 20% signed up from an email)

**Comment by mattkrick** [comment]
Invite Non-Parabol User(sender, receiver, type: meeting | team) -> account created(whether invited or not) -> meeting

**Comment by mattkrick** [comment]
Note: Invite Non-Parabol User should be filtered to showing only uniques. It's possible a non-user is invited by 10 people before they sign up. if that occurs & then they sign up, that the funnel will be artificially high or low, depending on how account created is handled.

**Comment by mattkrick** [comment]
> meeting invite, a team invite, or if they signed up themselves without being invited.

i can tell ya if they were invited vs. not invited, but the difference between meeting invite & team invite would be involved to figure out. plus, it may not mean much since someone could join a meeting invite after the meeting expired, join a team invite when a meeting is in session.

**Comment by avivapinchas** [comment]
Invited vs not invited should be good to start! The real gold is just knowing the account was created, all else is gravy (she says, mixing metaphors in a truly painful way).

**Comment by mattkrick** [comment]
gold in your gravy??? oh you fancy

**Comment by mattkrick** [comment]
- we already had the `New Org` event, so i kept the name but added a `fromSignup` boolean that is true if the org was created when the user signed up without being invited

- 'Team Number' includes archived teams. can change if you want, but i figure more teams = more attachment, and archiving a team probably doesn't remove that

- 'Meeting Number' already exists on the meeting completed event. it's inside the `traits` object.

 - 'Invite Non-Parabol User' has an `inviteTo` field that is `meeting | team`. it'll say `meeting` if the invite was _sent_ from a meeting. this doesn't mean that the recipient joined during that meeting (they could have accepted at a later date).
