### ISSUE TITLE
Make Slack notifications prettier, more contextual  

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3764]
## Issue - Enhancement

Right now, our Slack notifications are pretty plain and not very attractive, esp with the UTM parameters showing: 
![Screen Shot 2020-04-20 at 2 19 59 PM](https://user-images.githubusercontent.com/11621016/79791276-a9d24080-8312-11ea-97d2-c45abc6220d9.png)

We could make these prettier and more helpful by: 
- If we show the link, shorten it to hide the UTM parameters
- Pull in the title of the org & meeting - ex: "Parabol Product Retro #51" - to give more context to the meeting 
- Make the 'join' CTA more prominent 

Similarly, for 'end of meeting' notifications, we could: 
- Have a slightly different format depending on meeting type, like we do in the Timeline view in Parabol 
- Include metrics from the summary in the notification, like number of reflections, topics, comments and tasks 
- Include a link to jump back into the meeting to read comments, similar to what we do in the timeline 

Examples of more helpful Slack notifications from other apps: 
![Screen Shot 2020-04-20 at 2 20 07 PM](https://user-images.githubusercontent.com/11621016/79791839-92e01e00-8313-11ea-9d4a-44a338abe3dd.png)

![Screen Shot 2020-04-20 at 2 28 35 PM](https://user-images.githubusercontent.com/11621016/79791842-95427800-8313-11ea-8e46-60d7e6289428.png)

### Acceptance Criteria (optional)
Users can:
   - Understand what organization, team and meeting they're being invited to from a Slack notification 
   - Join the Slack meeting with one click
   - See Slack notifications for meetings as distinct from other Slack messages

- **Estimated effort:** 2 days ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed

**Comment by jordanh** [comment]
This is going to come back one day, I can feel it. I suggest we tackle this when we tackle #3538 (MS Team integration) and redesign our text-surface interactions/appearance whole cloth

**Comment by avivapinchas** [comment]
Bringing this back, since we're close to launching Sprint Poker - it's more confusing with additional meeting types. 

Also noting that this issue conflicts with #2877

**Comment by enriquesanchez** [comment]
Adding my +1 to Aviva's suggestions. Displaying the meeting title, a friendlier link, and a more obvious CTA would make these notifications much more useful.

I also really dig the idea of a different format for the meeting summary. We could take some of the info we include in the summary emails and condense it to more appropriately fit the Slack format.

**Comment by enriquesanchez** [comment]
Here are some follow up explorations, taking into consideration @avivapinchas's ideas above. The goal is to make our notifications more informative, more engaging, and overall friendlier. We also want to display a different format depending on the meeting stage (start or end).

### For the meeting start:

<img width="515" alt="start" src="https://user-images.githubusercontent.com/3276087/114104059-ceab2500-988f-11eb-9399-7e384022f4e5.png">

We can display a short message stating that the meeting has started, as well as the meeting info: team, meeting title, and link (ideally we can display a short link).

I think we can also include a 'Join meeting' CTA to make it obvious and easier to join.

While having both the link and the CTA may feel redundant, I think that the link can be helpful in case you want to have it handy to share the meeting with someone else.

### For the meeting end:

<img width="515" alt="end" src="https://user-images.githubusercontent.com/3276087/114104336-4711e600-9890-11eb-97ac-562153a8a7e2.png">

A different format that starts by stating that the meeting has ended, and then continues with the meeting info (team and title) and a summary of the meeting.

This summary is the same one we currently display in the Parabol timeline:

<img width="635" alt="Screen Shot 2021-04-08 at 2 56 58 p m" src="https://user-images.githubusercontent.com/3276087/114104400-6741a500-9890-11eb-883c-40496ca86eed.png">

In then ends with two buttons: 'See discussion' and 'Review Summary'. Again, these two are actions we currently display in the summary card above.

---

I want to be mindful of having these notifications be concise and sufficiently useful, and would love to hear if you think these explorations are in line with that. 

I'll also love to hear if you think we should be adding other meeting details to both the start and end formats. I may have missed something.

👍

**Comment by avivapinchas** [comment]
I like these! 

I think we could make the copy friendlier, like: 
` 👋  Meeting started - `
and
` Meeting completed 🎉 ` 

Also one more use to consider: we do have another Slack notification, which gets triggered when a facilitator sets a deadline for a phase, and hits the `notify via Slack` option 
![Screen Shot 2021-04-08 at 7 50 24 PM](https://user-images.githubusercontent.com/11621016/114113182-ad543400-98a3-11eb-9e04-07b1db4a416f.png)

![Screen Shot 2021-04-08 at 7 47 48 PM](https://user-images.githubusercontent.com/11621016/114113192-b1805180-98a3-11eb-903d-a642538712af.png)

**Comment by enriquesanchez** [comment]
Thank you for the feedback @avivapinchas! 🙌

Here's a second round taking into consideration your suggestions. I also added the additional format for scheduled phases. Let me know what you think.

Meeting has started:
<img width="515" alt="start" src="https://user-images.githubusercontent.com/3276087/114430839-77a19a80-9b84-11eb-92b4-c8fa4062f597.png">

Meeting has ended:
<img width="515" alt="end" src="https://user-images.githubusercontent.com/3276087/114430862-7c664e80-9b84-11eb-961a-151364cea34f.png">

Meeting phase has begun:
<img width="515" alt="scheduled" src="https://user-images.githubusercontent.com/3276087/114430915-88521080-9b84-11eb-8b66-a851eec67b88.png">

I've updates the button of the main CTA to be solid green. I think it does make a big difference and makes the CTA more obvious.

For the scheduled phase example, I added a secondary action for "Set reminder". I think this would be a useful option to have assuming we can use Slack's own `/remind` feature.

**Comment by avivapinchas** [comment]
@jordanh how come this was closed? Is there a new issue covering this work?

**Comment by jordanh** [comment]
Honestly I'm not sure how this got closed. Was I sleep walking? Not I'm questioning everything.

Reopening.

@enriquesanchez next step would be to create an implementation issue, link it here, and close this one when completed.

**Comment by enriquesanchez** [comment]
Created implementation issue https://github.com/ParabolInc/parabol/issues/4911
