### ISSUE TITLE
Optimization - Resources

### ISSUE THREAD

**Issue by 2009anandsingh** [ParabolInc/parabol#3770]
**## Issue - Enhancement**

The tool is working absolutely good and happy using it. One observation, that it consumes huge amount of compute when the meetings are live going on.

Not aware at code level, but any machine with low compute, will not be able to handle this application at all.

**Approx ~ 7 GFLOPS is consumption as per latest observation.**

## Reproducing the above observation
1. Your team size > 9 members online at same time and contributing
2. Machine configuration - i5 7th Generation (Intel), 16GB RAM
3. Browser used - Google chrome (version 80.xx)
3. You will find that your CPU goes with 45-50%.

### Acceptance Criteria (optional)
Users can:
   - Use meeting possibly via their hand held devices

### Efforts

Not sure about the effort, but generally speaking, the way sync happens should be improved.

**Comment by jordanh** [comment]
Clarifying question: do you see a clear change in CPU usage when moving from 8 to 9 active users? Are you running in production or in development `yarn start` vs `yarn dev`?

**Comment by jordanh** [comment]
Iceboxing
