### ISSUE TITLE
Improve the Users Present & Active in Meeting

### ISSUE THREAD

**Issue by sheldonhull** [ParabolInc/parabol#3773]
## Issue - Enhancement

It was a little confusing to my team the first time we used to figure out who was present. The avatar icons while nice didn't provide name. Additionally, it seemed to be limited to 5 users and other users didn't seem to show up.

Would like to suggest improving the display of who is present by name, status icon, and avatar instead, allowing a team to start up a retro easily without wondering if everyone is present.

### Acceptance Criteria (optional)
Users can:
   - See the current present users avatar and name
   - Inactive users go from green to gray status icon

**Comment by jordanh** [comment]
Our team scrubbed this issue today. We completely agree with you. Today, we tell you there is overflow (i.e. more than 5) but we don't give you an affordance to be able to see it!

@ackernaut here has been hard at work on some designs, if you're willing we'd love to connect with you, @sheldonhull, for feedback. Would you be willing?

Related issues: #3181

**Comment by jordanh** [comment]
@ackernaut I think what's needed here is a new issue with AC related to current designs. Could open a new issue and close this one as a duplicate?

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/14411601) 🔒  writes:


> Hi! just want to tell you that, in a meeting, the list of "online people" is not working. it's not showing everybody (but they joined the meeting and could correctly participate) Thanks

**Comment by jordanh** [comment]
Iceboxing this one for now; will see if presence issues represent themselves
