### ISSUE TITLE
Add multi-provider email support

### ISSUE THREAD

**Issue by mygalus** [ParabolInc/parabol#3782]
## Issue - Enhancement

Mailgun is a good solution but not trust by all compagnies.
I would like to add support for

- [x] Google imap 
https://developers.google.com/gmail/imap

- [ ] AWS SES (Simple Email Service) 
https://aws.amazon.com/ses/
(need to be tested - but already use with S3 on production ->
In case you run your application on AWS you could trust your server with IAM Role,
if you allow SES to it, you can send email without password provisioning.)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
The bottom half of this issue has gone stale, closing for now
