### ISSUE TITLE
Manually Adjust Upgrade Org Team Member count

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3784]
It is possible for a company's userbase to be split across different organizations.
When a company upgrades, we should consolidate all those users and teams into a single organization. However, we can't do this without human confirmation since the billing leader may want to exclude certain teams/people.

To accomplish this, I propose adding an `onUpgradeIncludeTeamIds` field on an organization.
This field can be populated via graphiql by the SDR.
When that organization upgrades, they will be billed for the number of users in their organization _plus_ the number of users in every team in the `onUpgradeIncludeTeamIds` array. On completion, those teams become part of the paid org.

AC
- [ ] When an SDR told a user that they have 33 people in their company, clicking the "upgrade" button should show 33 users (even if their current organization only has 14). 
- [ ] After upgrade, those teams that brought the total up to 33 should be moved to the pro org

**Comment by jordanh** [comment]
I've been thinking about this one for a bit now. There are a couple of tensions I sense.

Externally there is some pricing tension experienced by the cc cardholder. This manifests as "I didn't know about the others and I don't want to pay for them!" It also manifests as "you're more expensive than alternative X."

Then, there is a tension I experience. It's often the case the thing _we_ want is for an organization to upgrade to Enterprise (especially if, well, they are an enterprise). The criteria for this are:

1. Do you have more than 49 users active users?
2. Do you meet regularly (i.e. is attachment super strong?)
3. Are you a BigCo™ who would benefit from enterprise features?

It leads me to wonder—might it make it easier for everybody if we had a _flat rate_ for up to 49 users (i.e. a new Pro tier) and _everything_ above 49 users was enterprise. Plus, could we price the new Pro tier to meet or exceed the value of a per-term pricing structure from one of our alternatives in the marketplace?

I've wondered if:

- Pro conversion rates would go up
- Average revenue per user would go up
- Establishing a paying relationship earlier would make Pro -> Enterprise conversions possible
- We'd further harm our competitor

I'm looking for cons...

@mattkrick @avivapinchas ?

**Comment by gcrickman** [comment]
This may need a separate backlog issue but it seems right to put it here for now. When an Org upgrades and the teams are merged into the paid account, the billing leader should be able to at least see all of the teams that are under their Org but not necessarily the content for every team.

Here's a feature request I got from [a user](https://app.hubspot.com/contacts/3888472/contact/10154751) 🔒  : 

I'm running retro's at a high level across multiple teams - want to be able to see tasks across all team members across and teams

**Comment by mattkrick** [comment]
this dovetails nicely into team of teams.

**Comment by mattkrick** [comment]
the current thinking here is to have 1 org per real-world company. the challenge is figuring out which domains are shared email services & which ones aren't (e.g. is gmail.com a shared email service or is it a company? hotmail.com? microsoft.com?)

**Comment by avivapinchas** [comment]
For larger orgs, my sense is that the 3 levels of hierarchy (team > org > several orgs that make up a company) are useful. Leaders want a container for their set of teams that has separate billing (and presumably permissions) than other leaders, who have their own teams and separate budgets. 

@mattkrick Would your current thinking mean that there's only 2 levels of hierarchy? That you have to upgrade an entire company?

**Comment by mattkrick** [comment]
that's a really good point. here's how i've been thinking about it:
- A Team is composed of Users and Teams
- The top-level Team is what we call an Organization today. It's responsible for the billing of all its sub-teams.
- A Company is a group of top-level teams that share an email domain. This is just for sales/marketing & doesn't do anything in the app

This has 2 drawbacks that become apparent if large enterprises have multiple, discrete teams that pay us:
- there is no over-arching big brother entity that can look across organizations
- the SAML record must be shared across both teams

 I think the first drawback could be seen as a feature, and for sales/marketing we could certainly connect the dots to calculate group savings, etc.

The 2nd drawback is likely only theoretical, as companies will likely never have multiple different SAML provisionings because that'd defeat the purpose of SAML


An alternatives includes:
- Each team has the ability to be billable & choose which Users to "sponsor" or pay for. This gets crazy complicated because if a User loses their sponsorship, they'll need another team to sponsor them before they can use the app again

**Comment by avivapinchas** [comment]
I'm finding the language a bit confusing (team vs org, what it means today, what it means _later_), so I drew this out to check that I understand. Here's what I'm hearing: 
![Image from iOS (47)](https://user-images.githubusercontent.com/11621016/103565840-a7a31880-4e86-11eb-8565-edb1a6a43ba6.jpg)

A is individual users
B is what we call Teams today - and I imagine should stay as 'teams'. Being a member of a team lets you see Team things. 
C is Orgs today, which in future we could call 'team of teams' or 'departments' or something else. This is the level where billing happens - you pay for a set of teams. 
D is what Hubspot calls Companies - it's based on domain, it cannot be changed. For larger orgs, this might include many C 'sets', and for smaller orgs, D and C might be the same. 

IMO, the features that matter here are: 
- As a billing leader, you can see the D level within your app experience somehow. Right now, it's just a sales/marketing thing, and isn't reflected within the app, which leads to people being confused. 
- As a leader, you have a level that's larger than team (B) but smaller than Company (D) that you can control.

**Comment by mattkrick** [comment]
> As a leader, you have a level that's larger than team (B) but smaller than Company (D) that you can control.

Does team of teams solve this? You can arbitrarily nest teams inside of each other so it can mimic a functional hierarchy

> As a billing leader, you can see the D level within your app experience somehow.

what's the purpose? this is a pretty large risk today because i could sign up as alsjdf@microsoft.com & then get access to every single microsoft employee on the system.

**Comment by avivapinchas** [comment]
> Does team of teams solve this? You can arbitrarily nest teams inside of each other so it can mimic a functional hierarchy

I _think_ so - though I'd suggest we need a diff name for levels B & C or it'll get confusing to explain. 

Does team of teams mean a team (B) can only be part of one team of teams (C)? 

> what's the purpose? this is a pretty large risk today because i could sign up as alsjdf@microsoft.com & then get access to every single microsoft employee on the system.

Today, we attempt to convert an entire Company. Often, the response from a leader at the Company is, "We only have x teams - what are you talking about?" They can only see the teams /orgs that they're part of, so they're confused when asked to consider the usage of the whole Company. 

Your point on security is well-taken - I imagine we'd need some controls on this. I also imagine you'd only be able to see maybe the names of the other teams, but not PII like user names or email addresses. 

Alternatively, we'd need to adjust our sales & marketing practices to convert a team of teams (C) rather than a company (D).

**Comment by jordanh** [comment]
Iceboxing per policy. I think this is going to come back around. First, we should focus effort on the visibility side of this user tension and offer them a place to visit in order to see all of the teams (and orgs?) related to their company.
