### ISSUE TITLE
Triage billing bugs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3786]
AC

- [ ] quantity mismatch fixed

​

Estimate: 8 hours

**Comment by jordanh** [comment]
If you view billing for user `auth0|5c61415221a1c8594fb7293e` you'll note the following upcoming invoice for 2021:

![image](https://user-images.githubusercontent.com/103000/80519548-051cb800-893d-11ea-97b5-b49f9a17c928.png)

- Enterprise upgrade was given granting up to 249 users
- "65 new users added" is incorrect
- Estimate totals are incorrect

**Comment by mattkrick** [comment]
dupe of #3803
