### ISSUE TITLE
Add annotations to Sales tools to understand how sales activities impact usage

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3788]
## Issue - Enhancement

We want to make sure that Sales activities prompting folks to upgrade aren't then having an adverse impact on usage. 

To do that, we need to see when Sales activities happened in the same views where we look at usage. 

### Acceptance Criteria (optional)
Users can:
   - Add an annotation for a Sales activity, such as sending an initial email
   - View annotations in the Sales dashboards where we can see activity 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Where would else aside from HubSpot would these annotations appear? Today, all communications are kept (and are reportable) in the HubSpot CRM.

**Comment by avivapinchas** [comment]
Hubspot is a good spot (hehe) for seeing how sales efforts impact an individual user & the deal they're associated with, but afaik, isn't super helpful for seeing how a sales activity impacts Parabol activity within an org or for seeing trends across orgs. 

When you suggested this during our discussion around conversion Ideas, I was picturing an annotation in the Sales Dashboard tools that show us active users, something like this: 
![Image from iOS (1)](https://user-images.githubusercontent.com/11621016/81111738-25bbb380-8ee3-11ea-8d9a-00cf7a4c0a40.jpg)

At a more complex level, it would be great to be able to see the week-over-week or month-over-month average active user growth/decline annotated with sales activities, something like this: 
![Image from iOS (3)](https://user-images.githubusercontent.com/11621016/81112153-d629b780-8ee3-11ea-86fb-2a3b4cf6c4b9.jpg)

The latter feels more like an ad hoc analysis, where the former might be helpful to have in our tooling consistently.

**Comment by jordanh** [comment]
Move to Growth team sprint board

**Comment by avivapinchas** [comment]
Closing in favor of backlog on Notion
