### ISSUE TITLE
Automatically apply conversion prompt to potential customers

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3789]
## Issue - Enhancement

Users who pass the 'Pro' threshold aren't currently prompted to upgrade. To increase conversions from free users to paid customers, we want to automatically apply the existing conversion prompt (snack bar & during-Retro modal) to users organizations that have held 2+ meetings of >3 people and have >3 teams active on Parabol.  

Dependencies: 
-  #3787 and #3788 are meant to de-risk this effort. 
- Adding events for the data needed to track the success of this effort is logged as #3729 

### Acceptance Criteria (optional)
- Facilitators within organizations that have 2+ meetings of >3 people and >3 teams overall see a prompt to upgrade between the Vote and Discuss phases of a retro. 
- Billing Leaders of organizations with 2+ meetings of >3 people and >3 teams overall see the snackbar prompting them to contact us . 
- Parabol team can create funnels in Amplitude showing how many users viewed the conversion prompt then upgraded or clicked 'upgrade later'. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Removing from backlog and labelling discussion as we collect data from related issues. This will build confidence in next steps

**Comment by avivapinchas** [comment]
@jordanh We now have those data-related issues shipped. I propose we automatically apply the prompt to: 
- Organizations that are streaking - at least one team meeting monthly 
- Have more than 3 active teams  - ie three teams that have met in the past month 
- Have less than 20 AUs

**Comment by shawneeatparabol** [comment]
I would like to propose that we build in a foundation period to allow for as much organic growth as possible before deploying the prompt, and so that we are more likely to only target small companies with this strategy rather than enterprise orgs we want to engage in a human conversation. 

Can we add in the requirement that they have been streaking for 3 months?

**Comment by avivapinchas** [comment]
> Can we add in the requirement that they have been streaking for 3 months? 

I believe our definition for a 'streaking org' is at least one team that's been meeting monthly for at least 90 days

**Comment by avivapinchas** [comment]
This might be a fantastic issue to help us shape or launch an AB testing framework as discussed in #1838

**Comment by jordanh** [comment]
Iceboxing for now
