### ISSUE TITLE
Updated design of conversion prompt snackbar to increase conversions 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3790]
## Issue - Enhancement

Conversion prompt snackbar for billing leaders currently looks like this: 
<img width="371" alt="Screen Shot 2020-04-28 at 4 48 39 PM" src="https://user-images.githubusercontent.com/11621016/80541070-20ed8180-8970-11ea-8c6e-9f997a94dbe6.png">

To increase conversions, we should update this to: 
- Change CTA to 'Upgrade now', which open the credit card form modal 
- De-emphasize the 'dismiss' option 
- Update copy to: 'Looks like you've outgrown our free tier!` 

To evaluate effectiveness of the snackbar, we should add Segment events to track: views, clicks on 'upgrade now' and clicks to dismiss. 

### Acceptance Criteria (optional)
- Users can upgrade directly by clicking through the snackbar prompt. 
- Parabol team members can see how effective the snackbar prompt is by creating funnels in Amplitude. 

- **Estimated effort:** 6 hours

**Comment by jordanh** [comment]
Scrubbed, ready to implement

**Comment by jordanh** [comment]
Iceboxing for now
