### ISSUE TITLE
Explore potential designs for additional upgrade mentions 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3791]
## Issue - Enhancement

Currently, users are only prompted to upgrade if they're a facilitator between the Vote and Discuss phase in retros or if they're a Billing Leader. This issue is to explore other potential designs of upgrade mentions. 

Ideas discussed: 
- Persistent banner, badge or similar in Social Check-in, Reflect & Discuss stages for Facilitators & attendees (these would have different messaging).
- Persistent banner, badge or similar on Timeline & Team pages
- In right-hand sidebar across all non-meeting screens, indicate teams that are beyond the free tier 
- Update 'Summary' emails to include mention of upgrading.

Example of similar thing in a different tool: 
<img width="610" alt="Screen Shot 2020-04-28 at 4 58 47 PM" src="https://user-images.githubusercontent.com/11621016/80541881-9dcd2b00-8971-11ea-81f8-a02130db3aa0.png">

Suggested messaging: 
> We're glad you're getting so much value out of Parabol! At your size, you fit our Pro tier. We'd appreciate you supporting the product you're enjoying by subscribing. 

Some personal opinions: 
- @mattkrick said he doesn't like being interrupted by a conversion prompt and gave the example of a personal finance app that includes a modal he has to dismiss 
- @jordanh shared the above image and said he likes persistent notifications like this
- I agreed with the above, and shared that I don't like fake-pushy messaging (DO IT NOW OR ELSE!)

**Comment by jordanh** [comment]
AC:
   - Lo-fi designs on Figma board that can be broken into separate issues
   - Next hi-fi design issues created

EE:
  - 6 hours

**Comment by jordanh** [comment]
Scrubbed

**Comment by jordanh** [comment]
Iceboxing for now
