### ISSUE TITLE
Users can initiate live chat within the app 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3792]
## Issue - Enhancement

Currently, users need to navigate back to our marketing site to initiate live chats with us. We believe we're missing out on some support requests due to this non-obvious path, as well as some conversion opportunities. 

### Acceptance Criteria (optional)
   - Design that places Live Chat within the dashboard context
   - Implementation issue opened with AC and EE that can be backlogged

- **Estimated effort:** 6 hours

EDIT: @jordanh edited AC and effort

**Comment by jordanh** [comment]
Scrubbed

**Comment by jordanh** [comment]
This is also very much still a thing. I'd like to see it make its way into designs within #4321

**Comment by jordanh** [comment]
Going to keep this one open but stick it on a new milestone; likely won't get to this until we prioritize journeys that encourage organic upgrades, but this will be a key feature

**Comment by jordanh** [comment]
Iceboxing, but we'll likely get to this issue (by reopening or rewriting) when we focus on conversion later this year
