### ISSUE TITLE
Make data on user streaks available within Hubspot, app 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3793]
## Issue - Enhancement

We believe that whether a team is having a 'streak' (defined as: met >monthly for the last 90 days) is a meaningful indicator of whether they're ready to convert. Currently, this data is available as a report, but isn't pulled into Hubspot or other areas where we could trigger different experiences based on it. 

Ideally, we'd want to know this on a users, team and org level. 

### Acceptance Criteria (optional)
Parabol team can: 
- Automate emails & similar in Hubspot based on whether a user, team or organization is having a 'streak'. 
- Personalize the in-product experience, such as conversion prompts and notifications, based on whether a user, team or organization is having a 'streak.' 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
max streak and current streak are now available on hubspot contacts. max team streak is available on hubspot companies
