### ISSUE TITLE
Add small amount of content to login page

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3796]
for SEO purposes, we should add some copy to the login page so google has something to munch on that isn't the meta.

AC
- [ ] SEO-driven copy written & put somewhere on the signup/login page

Estimate: 4 hours

**Comment by avivapinchas** [comment]
Suggested copy: 
> Free retrospectives that get teams talking
> Parabol helps make good teams _great_ by

**Comment by avivapinchas** [comment]
This issue is still relevant - adding a bit of copy to the login page should help with SEO.

**Comment by jordanh** [comment]
Trivial, this time actually reprioritizing it

**Comment by jordanh** [comment]
Wow. This got marked stale again. I am going to put this in the next sprint
