### ISSUE TITLE
Fix Cypress Tests that fail in CI

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3799]
Cypress tests fail in CI: https://circleci.com/gh/ParabolInc/parabol/8996
Currently I'm ignoring the tests so I can push to staging.

Looks like there are a few causes. 1 is the rate limiter gets triggered, we need a request to not go out to google when in test mode.

AC
- [ ] Tests pass in CI

Estimate: 6 hours

**Comment by NikAiyer** [comment]
PR #3869 Fixes the rate limit issue

**Comment by NikAiyer** [comment]
PR #3907 fixes the issue with failing tests in CI
