### ISSUE TITLE
Retro demo broken

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3801]
## Issue - Bug

![image](https://user-images.githubusercontent.com/103000/80753400-0cc99180-8ae2-11ea-922e-a2d83cb9188e.png)

Repro:
1. Open demo in Firefox
2. Note that robots do not submit cards

Other note: not sure why Firefox yields a cross-origin error, but Chrome does not. Not sure if that exception is halting the demo or not

- **OS:** macOS
- **Browser:** Firefox
- **Estimated effort:** 8 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
   - Bug triaged and new bug with underlying cause backlogged or fixed

**Comment by jordanh** [comment]
Oh shoot, it looks broken when unauthenticated. Not sure if it is intermittent or not.

Repro'd using Chrome Incognito

**Comment by mattkrick** [comment]
i think this is a problem with refreshing, or by some other means re-entering the demo.
this has existed since it was built, but made a fix nonetheless

**Comment by mattkrick** [comment]
fixed in 5.5.1
