### ISSUE TITLE
Comments should be able to be promoted to tasks

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3804]
When I've mistakenly entered a commend I wished instead to be a task, I want an affordance for me to be able to change the comment into a task, so that I don't have to copy the comment text, paste into a new task, and delete the old commend (that's too cumbersome!)

AC:
   - A medium-fi design for the above

EE:
  -  ​6 hours

**Comment by mattkrick** [comment]
FWIW we explored this when designing the discussion thread, but decided against it in the name of a simpler UI. i think the only way to do this is to put it in the "more" options menu as something like "Promote to Task".

IMO we should wait for a _lot_ of user signal before implementing this. i'm all about simplicity as a feature.

**Comment by ackernaut** [comment]
First, I’d rather validate a concept that improves the UX around folks clearly knowing that they’re commenting or adding a task.

**Comment by mattkrick** [comment]
i think we'd have to first validate that comments are being created when they wanted to create a task.
we could check that by querying for deleted comments in a given meeting & seeing if there are any tasks that have similar content. 
i'm OK with kicking this down the road until some more users ask for it

**Comment by mattkrick** [comment]
going stale makes me think there's not enough tension around this.
if we wanted to measure tension, we could see how many tasks were created < 1 minute after a deleted comment with similar content.

closing until the tension comes up
