### ISSUE TITLE
kill children processes if main thread crashes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3809]
in development, we should gather up a list of signals that cause the main thread to crap out & then listen to those & kill the children to make sure we don't have any orphan processes running amuck. Example here: https://github.com/nodejs/help/issues/1790

**Comment by jordanh** [comment]
Still a thing. We should fix it. It'll come back one day.

**Comment by bukowa** [comment]
It's back ? :D

**Comment by Dschoordsch** [comment]
@bukowa Is it?

**Comment by bukowa** [comment]
> @bukowa Is it?

I don't know, that's why I am asking :D

**Comment by Dschoordsch** [comment]
🤷
