### ISSUE TITLE
Facilitated thread templates, UX explored

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3815]
Folks may benefit from a facilitated discussion thread either within a meeting or in an async ‘threads’ space (e.g. on a team, on a task) or some sub-phase of the discussion phase to guide comments and takeaway tasks.

#### Facilitation ideas:

- Decision making
- 5 whys (link to feedback?)
- Contributing factors / Potential solutions ([see feedback](https://www.g2.com/products/parabol/reviews/parabol-review-4194625))
- Folks can write their own thread templates

### Acceptance criteria

- User feedback gathered
- Job stories written
- Candidate solutions listed, described by writing and basic sketches
  - Discuss sub-phase
  - Thread prompt workflow (in meeting, in another thread space like on a team or task, etc.)
  - Others?
- Pitched ideas to users who gave feedback
- Reviewed by team for next steps

### Estimated effort

- 8 hrs

**Comment by ackernaut** [comment]
Related to #3337

**Comment by jordanh** [comment]
Still good. Iceboxing for now
