### ISSUE TITLE
Re-rendering Task in DOM for Discussion Phase demo cypress tests

### ISSUE THREAD

**Issue by NikAiyer** [ParabolInc/parabol#3816]
In the Disucussion Phase, creating a new task causes the element to re-render, causing this error:
cy...() failed because the element you are chaining off of has become detached or removed from the dom

Clicking add task in the discussion phase causes the task to be rendered, and then re-rendered when the attribute forceSelection is added to the element. Adding a small wait seems to fix this issue (as it allows it to finish re-rendering), but is not an ideal solution to the issue.

**Comment by jordanh** [comment]
This is fixed
