### ISSUE TITLE
Missing controls to add comment/task to thread

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3818]
### Background
Two users from the same organization wrote in that the controls to add the first comment or task in a thread are missing:

The first [user](https://app.hubspot.com/contacts/3888472/contact/6217701/) 🔒 writes:
>Hi there. I love Parabol. It mostly works great for my remote teams. However, lately as the team leader I have not been able to add tasks in the review section after the voting. One of my team members can write a note and from there I can add the action item task but I do not have the publicly comment or add task on my screen. What can I do?

The second [user](https://app.hubspot.com/contacts/3888472/contact/7815351) 🔒 writes:
>Hello,
I like very much your tool but I am facing an issue at the end of each of my retrospectives for a couple of weeks.
In the Discussion and takeaway tasks column, I can't add any comments.
It's written "✍️ Be the first to add a comment or task" but there is no call to action.
I have to ask one of my team members to add a comment and then I am allowed to add comments.
Can you help me please?

See screen shot from the first user:
![missing thread controls](https://user-images.githubusercontent.com/307286/81120231-e052b280-8ef1-11ea-80f8-1650d2e9c722.png)

See [support call notes](https://app.hugo.team/notes/interactions/f0cea4c3-db55-48ac-8f7f-8f3a1a32f8df) 🔒 

### Triage
I think it’s a browser layout issue. I think the flex layout is collapsing the control container or pushing the control container out of the viewable box (because the upper section with the header and prompt ‘ ✍️ Be the first…’ is taking up 100% of the vertical space).

3 folks on their team reported the problem and all had Chrome 77 on Win 10. Their teammate that could add the first comment or tasks reported to have Chrome 81 on Win 10.

### Acceptance criteria
- Verified bug
- Pushed a fix if small (probably is) or scope fix

### Estimated effort
- 2 hrs

**Comment by ackernaut** [comment]
I asked folks having the issue to try upgrading Chrome (from v77 to v81+). I got a confirmation from [a user](https://app.hubspot.com/contacts/3888472/contact/8480451) 🔒 :
>Chrome upgrade did enable my ability to add comments and tasks.

There are truly many combinations of browser and OS version out there, it’s like a game of whack-a-mole chasing down layout and JS bugs.

I think we should be in the habit of asking for this information when the UI/UX bug is mysterious. This tool https://www.whatsmybrowser.org/ gives folks a short link that they can copy to share their information.

**Comment by jordanh** [comment]
Iceboxing.

The answer is, "upgrade your Chrome version"
