### ISSUE TITLE
Pinned Agenda Items

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3839]
In a check-in meeting, teams have a common set of agenda items that they always discuss (metrics, calendar events, the sprint, etc.). It would be nice if those items were pre-populated, or "pinned".

Acceptance Criteria
- [ ] When hovering over an agenda item, a "pin" icon appears at the right.
- [ ] When hovering the pin icon, a tooltip animates in telling them this will pin the item for their next meeting
- [ ] when the pin icon is clicked, the icon changes to the unpin icon. 
- [ ] the pin/unpin state is propagated to all team members via the team graphql subscription
- [ ] When the check-in meeting is ended and the agenda item list is flushed, it is repopulated with all the pinned items

Here's a rough idea:
<img width="768" alt="Screen Shot 2020-05-12 at 8 31 40 AM" src="https://user-images.githubusercontent.com/5514175/81713681-07960c00-942b-11ea-8adc-6fea6fd69b82.png">

**Comment by jordanh** [comment]
History: the tension relieved by this feature was first described in #871
