### ISSUE TITLE
Schedule meeting in summary emails is buggy 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3845]
## Issue - Bug

In Summary emails for Check-in Meetings, we include links to schedule the next meeting. When I click on that button for GCal: 
- A new tab opens with a meeting in a week on GCal 
- There's a meeting link in the 'location' field 

If I schedule that meeting, then later click on the 'location' link - I'm redirected to Google Maps, which is confused about where this digital location is. 

If I copy/paste the meeting link rather than clicking through the GCal meeting, I'm directed to my previous meeting, which is completed. 

### Acceptance Criteria (optional)
Users can:
   - ~Schedule a Check-in Meeting from the Summary email for a Check-In meeting~
   - ~The scheduled meeting includes a valid meeting link that doesn't redirect to Google Maps~
   - GCal and Outlink calendar section removed from the summary email

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is so trivial, we should just go head and do this next sprint. Will reprioritize

**Comment by jordanh** [comment]
Game time decision to be made by a developer AC:

- Either remove GCal and Outlink entries or,
- Update GCal entry to use meeting description field instead of location

**Comment by avivapinchas** [comment]
@nickoferrall Yep, I don't see it either - I think it was removed at some point.
