### ISSUE TITLE
Segment event and property refactor for Growth team

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3854]
## Issue - Enhancement

Once we were a little company without a Growth team. Once our only means of getting data from Segment events into a Hubspot Contact property was to call Segment `identify()`. Bygone are those days of innocence.

### The Why
Parabol's Growth team exists to grow our community of users and customers. Marketing endeavors to deliver the right message the right time, to the right people. Sales desire to focus limited time speaking to contacts over our tier limit who find Parabol a must-have product, rather than merely a nice-to-have one. Today both of these pursuits are made difficult by not having enough data, freshly delivered within Parabol's marketing & sales platform.

Now that we have the means (via HubSpot functions, see: #3705  #3752 #3797) and done the analyses to determine a minimal set of new eventing data to collect to resolve current needs and enable the future, we can get scooting.

### Context, please

Until now, we've been relying on Segment `properties` and `traits` fields when emitting an analytics event. There is also `context`. `context` [is documented](https://segment.com/docs/connections/sources/catalog/libraries/server/node/) the following way:

> A dictionary of extra context to attach to the call. Note: context differs from traits because it is not attributes of the user itself.

Where `traits` are supposed to be reserved for attributes pertaining to an individual user, `context` can be used arbitrarily to interpret events differently. In our case, we can use `context` for hinting how to update HubSpot Company records. Read on below.

### Companies and Orgs

Relating a Parabol User to a HubSpot contact is trivial because ontologically speaking they are similar. Relating a Parabol Org and HubSpot Compay, not so much.

The root of the problem is Parabol Orgs and HubSpot Companies are related to one another via a many-to-many relationship: a Parabol Org may relate to many HubSpot Companies and a HubSpot Company may relate to many Parabol Orgs. Further HubSpot Company records default to associating HubSpot Contact records by email domain. HubSpot Company records can, therefore, be considered as objects that default to housing email-domain level data.

Generally, this is fine, as our sales folks sell to companies. Parabol Orgs end up being both a logical grouping and construct for providing more ways a company can divide billing among several budgets.

The question becomes: when and how to HubSpot Company-records get updated? Do we emit special `X Event Company Update` events or do we augment our current events to update HubSpot Company Records when and how we want? If we assert that our event stream should follow user behavior closely, and avoid becoming a message bus for data synchronization, then we can use `context` to help augment existing events.

This suggests the following design principles:

- For team-level events, emit a context variable when a company update should happen. If events are being sent for more than 1 team member, only set this context variable on a single event.

- Add context variables to report on which email domain is org majority. This heuristic allows us to related an org to a company in a meaningful way

- Company-level (i.e. domain-level) data should be kept in `context` to keep those properties from polluting our user event stream (in tools like Amplitude)

Add context variable if org streak is highest for domain 

#### Updated Events:

  - **Event:** `Invite Accepted`
   **Context:**
         - `domainList`: (list of str) an ordered list of email domains affected by this update, will always be a single element for this event
         - `domainOperationList` (list of str) a single item corresponding to the entry in `domainList`. Set to `"update"` if the domain was affected, else set to `null`. If `null`, the remainder of context is not set
         - `domainTeamCountList`: (list of int) a single item corresponding to the entry in `domainList` set to the number of unarchived teams for each affected email domain

  - **Event:** `Meeting Completed`
    **Context:**
         - `domainList`: (list of str) ordered list of email domains who just met
         - `domainOperationList` (list of str) an ordered list where each value corresponds to `domainList` and is set to `"update"` only if _all_ of the following conditions are met: (1) this is the 1st `MeetingCompleted` event sent for a meeting, and, (2) at least one meeting participant matches the corresponding `domainList` entry. Otherwise the item is `null`. If all items in the list are `null` then the remainder of the context section is left empty
         - `domainCurrentMonthlyStreakList`: (list of int) ordered list where each value corresponds to `domainList` and set to how many months consecutive each email domain has met across _all orgs related to each email domain_
         - `domainHighestEverMonthlyStreakList`: (list of int) ordered list where each value corresponds to `domainList` and set to the longest monthly consecutive streak that domain has ever achieved across all related orgs
         - `domainTotalMeetingsList`: (list of int) ordered list where each value corresponds to `domainList` and set to the total number of meetings ran by each email domain across all orgs
    **Properties:**
          - `userHighestAnywhereMeetingNumber`: (int) the highest meeting number across all teams this user has completed, _across all orgs and teams_
          - `userCurrentOrgMonthlyStreak`: (int) how many months consecutive has this user met, _across all orgs and teams_
          - `userHighestAnywhereMonthlyStreak`: (int) the greatest number of months consecutively this user has ever met, used to help judge the lost "value" of the churned user, _across all orgs and teams_

  - **Event:** `New Team`
   **Context:**
         - `domainList`: (list of str) ordered list of email domains affected by this update
         - `domainOperationList` (list of str) an ordered list where each value corresponds to an item from `domainList`. Set to `"update"` if the domain was affected, else set to `null`.
         - `domainTeamCount`: (list of int) each item corresponds to `domainList` and is set to the number of unarchived teams for each affected email domain
     **Properties:**
        - `orgTeamCount`: (int) the new total of teams on the Org

#### New Events:

  - **Event:** `Account Deleted`
   **When:** sent when an account is deleted
   **Context:**
        - `domainList`: (list of str) ordered list of email domains affected by this update, will always be a single element for this event
        - `domainOperationList` (list of str) a single item corresponding to the entry in `domainList` and set to an ordered list where each value corresponds to an item 
        - `domainActiveUsersList`: (list of int) a single item corresponding to the entry in `domainList` and set to the total number of _active_ users with the same email domain
        - `domainTotalUsersList`: (list of int) a single item corresponding to the entry in `domainList` and set to the total number of non-deleted users with the same email domain
     **Properties:**
        - `orgTeamCount`: (int) the new total of teams on the Org

  - **Event:** `Team Archived`
    **When:** sent when a team is archived
   **Context:**
         - `domainList`: (list of str) ordered list of email domains affected by this update
         - `domainOperationList` (list of str) an ordered list where each value corresponds to an item from `domainList`. Set to `"update"` if the domain was affected, else set to `null`.
         - `domainTeamCount`: (list of int) number of unarchived teams for each affected email domain
    **Properties:**
        - `orgTeamCount`: (int) the new total of teams on the Org

  - **Event:** `User Removed from Team`
   **When:** sent when a user is removed from a team
   **Context:**
         - `domainList`: (list of str) an ordered list of email domains affected by this update, will always be a single element for this event
         - `domainOperationList` (list of str) a single item corresponding to the entry in `domainList`. Set to `"update"` if the domain was affected, else set to `null`. If `null`, the remainder of context is not set
         - `domainTeamCountList`: (list of int) a single item corresponding to the entry in `domainList` set to the number of unarchived teams for each affected email domain
     **Properties:**
        - `name`: the name of the team
        - `teamId`: (str) the current teamId
        - `orgId`: (str) the current orgId

  - **Event:** `User Role Billing Leader Granted`
     **When:** sent when a user is made team lead
     **Properties:**
        - `orgId`: (str) the current orgId
        - `numFreeOrgsLeading`: (int) the total number of personal-tier orgs (including this one) the user now leads, _across all orgs_
        - `numPaidOrgsLeading`: (int) the total number of non-personal-tier orgs (including this one) the user now leads, _across all orgs_

  - **Event:** `User Role Billing Leader Revoked`
     **When:** sent when a user is made team lead
     **Properties:**
        - `orgId`: (str) the current orgId
        - `numFreeOrgsLeading`: (int) the total number of personal-tier orgs (including this one) the user now leads, _across all orgs_
        - `numPaidOrgsLeading`: (int) the total number of non-personal-tier orgs (including this one) the user now leads, _across all orgs_

  - **Event:** `User Role Team Lead Granted`
     **When:** sent when a user is made team lead
     **Properties:**
        - `orgId`: (str) the current orgId
        - `teamId`: (str) the current teamId
        - `numTeamsLeading`: (int) the total number of teams (including this one) the user now leads, _across all orgs_

  - **Event:** `User Role Team Lead Revoked`
     **When:** sent when a user has stopped being team leader
     **Properties:**
        - `orgId`: (str) the current orgId
        - `teamId`: (str) the current teamId
        - `numTeamsLeading`: (int) the total number of teams (including this one) the user now leads, _across all orgs_

  - **Event:** `User Went Active`
    **When:** sent anytime a user changes from being marked inactive to being marked as active on an org, including after account creation
    **Context:**
        - `domainList`: (list of str) ordered list of email domains affected by this update, will always be a single element for this event
        - `domainOperationList` (list of str) a single item corresponding to the entry in `domainList` and set to an ordered list where each value corresponds to an item 
        - `domainActiveUsersList`: (list of int) a single item corresponding to the entry in `domainList` and set to the total number of _active_ users with the same email domain
        - `domainTotalUsersList`: (list of int) a single item corresponding to the entry in `domainList` and set to the total number of non-deleted users with the same email domain

  - **Event:** `User Went Inactive`
     **When:** sent when a user is marked inactive
     **Properties:**
        - `userCurrentMonthlyStreak`: (int) set to 0, see: `Meeting Completed` event, above

Notes:
   - Supercedes #3797 
   - Prioritize above: #3731, #3733 

### Acceptance Criteria

- Designed critiqued and smaller issues re-added to backlog for execution

- **Estimated effort:** 8 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@NikAiyer for context, these are the changes we gotta get into the product before we continue with the HubSpot stuff ^

**Comment by jordanh** [comment]
@mattkrick the big idea in this change set is that we begin tracking per-domain statistics in the DB in addition to the per-org stuff. This will do a complete of things for us:

1. We'll be able to create segment events that will update Company objects up in HubSpot (I'll give you the nickel and dime tour to show you why that's vital for our sales team) and,
2. One day we can expose these per-domain statistics on some kind of user-facing report, perhaps to prove "oh, no, in fact, your org has 42 teams, not just your own 2 personal teams"

I'm sure you'll have many, many questions about this. Let's discuss together in the context of the Growth team stuff before going back and forth here

**Comment by mattkrick** [comment]
Supplemental working doc here: https://www.notion.so/parabol/Analytics-Data-Schema-1e311e3f1c4c44a3be59bfff8d8d954e

The main strategy is:
1. Get page events working in hubspot again
2. have segment function stalk to hubspot to update attributes. to create those attributes, it will reach out to our server to get what it needs.

there is some concern with giving segment a private key that can query our data. to minimize the risk, let's say each event can query data for 1 minute. to do that, we'll need to send a key that includes a timestamp on each event. if we want to be fancy, that key can then get hashed with a server key. then, that secret must get sent back to us. `hash2(hash1(timestamp))`. 
hash1 private key is something that only the parabol server knows
hash2 private key is something the parabol server & the segment server knows

by using a double hash, we prevent against a MITM attack between us & segment. we also prevent against an attack where the segment keybase is compromised. However, is the keybase is compromised AND the events are intercepted, then the attacker has access to our data for 1 minute. to mitigate this, we need to scope the data to an analytics schema. this may make it into v1, or may not

**Comment by mattkrick** [comment]
- When a user authenticates, we want to call identify with their email & id.
- identify persists the userId & email in the localStorage & in a cookie, external to app code
- when a user hits the page again, the values are retrieved, no identify necessary unless the cookies & cache got cleared but our app items didn't, so we probably shouldn't trust it
- for those that are currently logged in, we'll need to identify if they aren't identified already.

- token? 
  - yes: email/id?
    - identify
  - no: fetch email/id, cache, identify
- wait for authentication event

authentication success?
  - cache email/id, identify
