### ISSUE TITLE
Fix GraphQLRedisPubSub unsubscribe multiple channels

### ISSUE THREAD

**Issue by bryanjhv** [ParabolInc/parabol#3855]
## Issue - Enhancement

https://github.com/ParabolInc/parabol/blob/0985778ffb8ff6577987e434cee8c1d989f478f8/packages/server/utils/GraphQLRedisPubSub.ts#L58-L70

I think the `return`s here should be changed to `continue` given `channels` is an array and `unsubscribe` could potentially be called with an array of more than one element.

- **Estimated effort:** 11 points

**Comment by jordanh** [comment]
@mattkrick to triage when scheduled, comment added if not necessary to process the entire list

**Comment by jordanh** [comment]
@bryanjhv btw, thank you so much for your 👀 on this

**Comment by jordanh** [comment]
@mattkrick this code either needs a comment or a fix, will prioritize to triage

**Comment by mattkrick** [comment]
this is a good find. how we use it, there's an implicit contract of all-or-none, but implicit contracts aren't great. turned into continues!
