### ISSUE TITLE
Join snackbar doesn’t always show

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3857]
### Repro

- I had a tab open, including closing and opening the laptop
- I saw the newly started meeting added to the upper-left menu
- I didn’t see the join snackbar until refresh
- My guess is that this behavior is very intermittent

### AC
- Reproduced and underlying cause triaged, new issue opened or fixed if trivial

**Comment by jordanh** [comment]
Iceboxing for now
