### ISSUE TITLE
Page View analytics call email trait added

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3860]
## Issue - Bug

Related to: #3286 

Page event needs email moved to traits object here: https://github.com/ParabolInc/parabol/blob/43bc265566eb513356a4087fa2c412846d973f37/packages/client/components/AnalyticsPage.tsx#L50

TK: research resolution

- **Estimated effort:** 1 hour ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Comment by mattkrick** [comment]
closed in favor of #3854
