### ISSUE TITLE
Planning poker concepts designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3861]
### Acceptance criteria
- Gathers notes from user inquiry
- Sketches gathered and notes written
- Targets Jira, HN thread feedback
- Internal validation (including video, lo-fi, clickable prototype, etc.)
- Concepts validated with users

### Estimated effort
- 12 hours

**Comment by ackernaut** [comment]
- [First sketches in Figma](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Planning-Poker-Sketches?node-id=0%3A1)
- [First notes in Notion](https://www.notion.so/parabol/Planning-Poker-2bf25b59fd044b82b8318fc39bbbe60f) 🔒

**Comment by ackernaut** [comment]
An update:
- [More sketches via Procreate and Sprink](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Planning-Poker-Sketches?node-id=27%3A7)
- Drafting [user job stories in Notion](https://www.notion.so/parabol/User-job-stories-3805ea1665444ae38baff8d66f6745ba) 🔒

**Comment by jordanh** [comment]
Closing in favor of #3887 and #3888
