### ISSUE TITLE
Sharing Templates to Other Teams

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#3867]
Template Issue - Enhancement

A [customer](https://app.hubspot.com/contacts/3888472/contact/9633201)🔒reported that the following feature would save them time as they expanded their footprint within the platform:

"When we find that a specific template works really well it would be great if we could make them available templates to the other teams instead of having to manually recreate it in each team."

**Comment by ackernaut** [comment]
Thanks for capturing! This is a duplicate of #3465 — I’ll add the comment there and close this one.
