### ISSUE TITLE
Add thread comments to CSV export

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3870]
[An enterprise customer](https://app.hubspot.com/contacts/3888472/company/1696726269/) 🔒 asked if it was possible to export comments from the Retro.

### Acceptance criteria
- [ ] Added column to indicate row type (reflections, task, ...)
- [ ] Added timestamp column to order comments
- [ ] Thread comments are added to the CSV as new column
### Estimated effort
- 2 hour

EDIT: @jordanh added addn'l AC during sprint planning

**Comment by tianrunhe** [comment]
Adding my insights after reviewing the code base a little bit more:

1.  Might be an existing bug/feature missing? The action meeting summary does not show a link to discussion threads even if there are some comments. As compared to a retro meeting:

![](https://user-images.githubusercontent.com/1879975/84838221-a98eb280-afee-11ea-80c2-0c3392f0fa59.png)

2\. I have hard time understanding the A/C:

1.  Do we wanna a separate "Export comments to CSV" button? (my interpretation is no but that gives me confusions on following items)
2.  If we stick into one CSV, how are the thread comments fitted in? For example, in Retro meeting CSV, each row is one reflection. However in one reflection topic, we could have multiple comments about that reflection topic. How would the CSV look like? All the comments concatenated in one column? That seems not aligned with the other A/C "Added timestamp column to order comments" so it looks like we then wanna one comment per row? Will that make the CSV too large? As all the comments within one topic will basically duplicate all of the columns other than comment content and timestamp.

Am I completely misunderstanding this...?😳

**Comment by mattkrick** [comment]
1. i'd say no csv button, they can click it when they click the summary. we should certainly add a "see the discussion "link to check-in meetings, but i think that's a separate issue
2. yeah, this is the multiplicative explosion i alluded to. today, we have a "type" column that is a  Task or Reflection. we need to add a 3rd type "Comment". then, each row will either me a task, reflection, or comment. we also need another column so they can sort by the createdAt timestamp & read the comments in order

**Comment by avivapinchas** [comment]
> we also need another column so they can sort by the createdAt timestamp & read the comments in order

For the 'comment' type, could / should we also include a column like 'topic' and the topic they referred to? Sorting by 'create date' works to see it linearly, but if you wanted to see comments for a given topic, it'd be weird. 

Feel free to disregard if that adds complexity, just adding my 2 cents as a lover of spreadsheets :P

**Comment by tianrunhe** [comment]
OK, so here is what I have for CSV export on Action Meeting:

![](https://user-images.githubusercontent.com/1879975/85089339-45f3b900-b197-11ea-801d-b275629d066a.png)

Insights:

1.  Tasks are exported first as before, adding creation timestamp. Also if the task was created during agenda discussion period, it will show which agenda it is (as seen on row 2)
2.  Comments and replies are exported after tasks. User column is corresponding to the author of that comment/reply.
3.  Replies will have a 'replyTo' column to indicate which comments they are replied to.

For Retrospective Meeting:

![](https://user-images.githubusercontent.com/1879975/85089562-cb776900-b197-11ea-8a81-83b01848ad6a.png)

Insights:

1.  Exports are grouped/ordered by reflection group.
2.  Currently no author for the comments/replies are shown as we don't show users for the reflections for anonymity (**do we want to show users for comments/replies only but leave the reflections empty?**)

**Comment by mattkrick** [comment]
looking sharp! Just a couple final touches:
- lets rename `User` to `Author` since a task could be authored by Tony & assigned to Thor, but `User` doesn't tell us which one it is
- in checkin meetings, to make it easy on pivot tables, the `status` column should always have the same value for any given `user`. it should be a non-null "absent" or "present".
- I like your insight 2, we should add an author column & just put "Anonymous" for anonymous reflections, comments, or replies.

**Comment by tianrunhe** [comment]
Thanks for comments Matt. 1 and 3 are easy to change.

Regarding your point 2, there is an issue. Looks like after a checkin meeting ends, a user who was absent from the meeting can still go into the meeting/discussion and make a comment, which brings to questions:

1.  From tech perspective, the author of the comment might not be present in the meeting but in `Comment` type, there is only the [`User`](https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/types/Threadable.ts#L30) field, no connection to a MeetingMember type where the  [checked in status](https://github.com/ParabolInc/parabol/blob/b478fffc84092860e16e46214d9a0c7ad91e3d50/packages/server/graphql/types/MeetingMember.ts#L18) is so it will require some effort to build that connection there
2.  If a user can leave comments after the meeting ends, then from the perspective of exporting to CSV, I guess the best we can do is to assure the exported data is up to date when the export button is clicked?

Also another question: are we okay with a limit of 1000 comments for now? It's aligned with the current limit on the discussion thread, as seen [here](ec14407#diff-0852f54f7ec8501e8b6a55b2bd7c00cbR72).

**Comment by mattkrick** [comment]
1. let's just generate a hash table from the meetingMembers & then for comments just look up the status, e.g. `userPresence = {user123: 'absent', user456: 'present'}`
2. after a meeting ends, presence should not change. sure, items could get added, but i think that's an edge case. export accurate at the time of clicking sounds good to me

yeah, 1000 comment limit seems good. that's more of a backend constraint to make sure no jerks try to DOS our poor little server.
