### ISSUE TITLE
Ad attribution architecture

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3873]
## Issue - Enhancement

@avivapinchas and a vendor of ours was discussing ad attribution. **The problem:** when we spend money on an Ad, we want to know whether or not there was a return on investment so that we can steer our spend strategy.

Often Ad providers provide a means to synthesize an event from something like a page visit (by looking at the URL). This works great for "viewed page" or "viewed product demo" but doesn't work great for "Account Created" because there are so many ways to create an account (via the signup page vs. accepting an invite) and we can't just look at a URL and say, "yes, that means a new account was made." We'd have to emit an event.

Rather than pollute our codebase with tracking pixel event code (yuck), it'd be best to locate this place as close to where the ad JS is loaded. The JS is loaded via GTM. So putting it in there makes sense.

GTM, when loaded via Segment, can also catch segment events. See: https://segment.com/docs/connections/destinations/catalog/google-tag-manager/ Hooray!

The only challenge is, the `Account Created` event is emitted from the server, not the client. Now, we probably don't want to change that (so we can always catch the event). But, it would be nice to have it on the client too.

As a special bonus: we can also fix #3286 using this (closing that issue, as this supersedes it)

Some ideas for doing that:
1. We stream a copy of `track()` event parameters from the server to the client re-emit them as client-side `track()` events, adding `{ context: { source: 'client' } }` . We filter any `context.source == 'client'` events from reaching Segment destinations other than GTM.
2. We introduce a new event on the client `[CE] Account Created` (where [CE]) means "Client Event") and block all [CE] from going anywhere but to the GTM destination

I don't like either of these solutions very much. Weighing them: 1. means we can uncouple making app changes from changing which events we can use for ad attribution. 2. means we'd have to update the app if we wanted a new event to attribute

Any other options we can think of?

**Comment by avivapinchas** [comment]
@jordanh @mattkrick How can we move this one forward? Any objections?

**Comment by mattkrick** [comment]
i need some more info
- what parameters are we sending?
- where do those parameters come from?
- where do we send them? segment? direct to GTM?

**Comment by jordanh** [comment]
Curious to know your preference here between 1 and 2:

**Comment by jordanh** [comment]
Closing for now
