### ISSUE TITLE
If an update or agenda item isn't covered, it shouldn't be closed out 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3880]
##  Issue - Bug

Today, we went to run a retro for the Growth team, but accidentally started a Check-in meeting. Realizing our mistake, we ended the meeting. Unfortunately, ending the meeting had some unintended effects: 
- Cards in 'done' were archived, even though we hadn't gotten to the updates phase
- Agenda items were cleared out, even though we hadn't discussed them. This is particularly a bummer because afaict, those items are just lost - they're not in the summary or in Parabol. 

Now, for our next check-in meeting, we'll be missing the completed tasks and we need to remember what agenda items we'd added and add them again. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
In a Check-In meeting, if users do not get to an item, that item isn't 'closed'. Meaning: 
- Users can end a meeting before the 'updates' phase without archiving their Done cards
- Users can end a meeting before reaching an agenda item, and that item will not be archived/removed

**Comment by mattkrick** [comment]
first bullet seems great.
@jordanh had the opinion that unreached agenda items should not be preserved (let the tension rise again). @jordanh do you still feel that way?

**Comment by ackernaut** [comment]
To solve for the case of accidentally starting the wrong meeting type and foot-gunning the purpose of reviewing what was done and preserving valid ‘next meeting’ agenda items:

- When a meeting is ended early:
  - Only archive ‘Done’ cards if the agenda phase been reached
  - Only archive agenda items if the agenda phase has been reached

How does that sound?

**Comment by avivapinchas** [comment]
What if someone doesn't use an Icebreaker, so they essentially start the meeting in 'Updates'? 

Otherwise, sounds good to me

**Comment by ackernaut** [comment]
> What if someone doesn't use an Icebreaker, so they essentially start the meeting in 'Updates'?
@avivapinchas I think the condition for reaching the Team Agenda phase still works? If folks notice they’re in the wrong meeting (Updates?) and bail, then I assume they won’t advance to the Team Agenda phase.

**Comment by avivapinchas** [comment]
Oh I'm sorry I misread what you wrote! I thought you'd said to archive Done cards when the team reaches Updates, but I see you said when the team reaches Agenda. 

Yep, that makes sense to me - I think that would work well.

**Comment by jordanh** [comment]
@mattkrick weighing in.

Let's adjust AC to:
> Archive Done cards if the Updates phase has been completed
