### ISSUE TITLE
end meeting confirmation revised

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3886]
Some users are struggling to see that the end meeting confirmation is a confirmation. We have some ideas for how to fix this [here](https://www.notion.so/parabol/End-Meeting-Confirmation-Fix-ups-6572e185a78a4afdb6a3a64251c1a5c5) 🔒 

AC:
   * ​Confirmation revision(s) designed
   * Implementation made or implementation issue created

EE: 8 hours

**Comment by ackernaut** [comment]
See [private team notes](https://www.notion.so/parabol/End-Meeting-Confirmation-Fix-ups-6572e185a78a4afdb6a3a64251c1a5c5) 🔗  🔒

**Comment by ackernaut** [comment]
Closing and writing an implementation issue:
- Here’s [the clickable prototype in Figma](https://www.figma.com/proto/n0V5H6PBU0Pf35ctWPlWol/Confirm-Ready-and-End-Meeting?node-id=214%3A9561&viewport=245%2C457%2C0.5&scaling=scale-down)
- Here are [the notes in Notion](https://www.notion.so/parabol/End-Meeting-Confirmation-Fix-ups-6572e185a78a4afdb6a3a64251c1a5c5#a812eb874aa549f58bd316af14190bc9) 🔒
