### ISSUE TITLE
Applying coupons for Pro upgrades

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#3893]
## Issue - Enhancement

In our current state Pro billing happens immediately and any discounts given for the subscription must be done retroactively as a refund for the first month. Coupons will apply to subsequent months.

The proposal is to allow the coupon to be applied to an account before the billing information is entered. So far we have 2 ideas:

1. Generate coupon codes and add a coupon field when entering billing information for an upgrade

2. Attach a coupon to a specific user on the backend before they upgrade so it will apply on the first invoice

I'm in favor of option 2 as users who upgrade may try to search for coupon codes if they don't already have one and it prevents user error in entering coupon codes.

Related to closed issue #2972

Until we have acceptance criteria and estimated effort the issue will remain open for further discussion.

**Comment by shawneeatparabol** [comment]
Upvoting this

**Comment by jordanh** [comment]
Iceboxing for now
