### ISSUE TITLE
Migrate slack before Dec 4

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3900]
Slack integration needs to be migrated before December 4.
https://api.slack.com/authentication/migration?utm_medium=referral&utm_source=apiblog&utm_campaign=fy20-Q401-granular-permissions

Estimate: 20 hours

**Comment by mattkrick** [comment]
we've kicked this can down the road as long as we could.
we need to do this in the next sprint to ensure we hit the Dec 4 deadline

**Comment by avivapinchas** [comment]
Copy recommendation [here](https://docs.google.com/document/d/13At7-pbn-zBrSWcuFYJ245mSYq9dY4SmyDgSbz_Q3oQ/edit) 🔒

**Comment by mattkrick** [comment]
Next steps:
- submit to slack for approval
- as soon as approved, we will push the updated code to prod & alert everyone via slack
- the update via slack will tell folks that their integration has gone away & they need to re-integrate
- the updated code will wide out everyone's current slack integration (so sending the slack message must come first)
