### ISSUE TITLE
Creating tasks during the discussion phase

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#3901]
**Update**: folks are confused by the UI for comments and tasks in the discussion thread. They sometimes create comments thinking of them as tasks, or get stuck trying to find how to create a task.

**Original description**: Our current interface for threaded discussions during the discussion phase of a retro has confused some users when it comes to creating tasks vs. adding comments. We may need to re-configure the UI to make task creation more distinguishable from comments. This will remain a discussion item until acceptance criteria and estimated effort have been established.

### Acceptance criteria
- Sketched an end-to-end experience of a UI solution and validated it with the Product team
- Created a high-fidelity concept of the main UI view, including important states (e.g. empty) as needed
- Wrote the acceptance criteria to build it

### Estimated effort
- 20 hours

**Comment by shawneeatparabol** [comment]
I have also heard this feedback from customers

**Comment by jordanh** [comment]
@gcrickman and @shawneeatparabol: a reminder from your friendly PM, please securely link which users you're getting this feedback from so we can collect more info/tally/test solutions

**Comment by jordanh** [comment]
[Here's verbatim video](https://drive.google.com/file/d/1CUZOESAu29y1ILE6Q0TUB0sfF-h13l-h/view?t=5m28s) 🔐 from [a user](https://app.hubspot.com/contacts/3888472/contact/19482951) 🔐, showing how this design confused them

**Comment by ackernaut** [comment]
[This person](https://app.hubspot.com/contacts/3888472/contact/16890601/) reported confusion about adding tasks vs comments, including screenshots (see attachments in the email). One screenshot shows a thread with comments that sound like tasks.

>I ran a meeting with Parabol and I noticed that the summary email had none of the 4 Task/Discussion events we created in the meeting.  That makes the Summary email much less useful.

>I looked at past summaries and they appear to be present.  A screenshot of one of the items with what I expected to be tasks is below. Do I need to do something to get the comments to be tasks?

**Comment by ackernaut** [comment]
[This person](https://app.hubspot.com/contacts/3888472/contact/16890601/) 🔒  writes in again:

>Recently, I was again bit by the UI ambiguity between Discussion items (which are not logged in the summary) and Tasks (which are). After the meeting was over I added the missing tasks. They appear to be part of the meeting, but the summary emails went out before the change.

>Is there a way to re-send the summary emails?

The answer is no, but the user could share a link to the summary in the browser with the team (via email, chat) to boost signal. The team members have the sumary link on their timeline card as it is.

**Comment by ackernaut** [comment]
From [this person](https://app.hubspot.com/contacts/3888472/contact/23714751/)
>Where did you get stuck? What did you find confusing?
>In the discussion, the "Add Task" should be put in the center in my opinion.

**Comment by ackernaut** [comment]
This is also related to #3392 re: output in a thread

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/2140401) 🔒 says:

> I add comments when I meant to add tasks

**Comment by jordanh** [comment]
With our latest shipped designs, this should be fixed now
