### ISSUE TITLE
deleteUser() mutation does not update HubSpot "Is User Removed?"

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3904]
## Issue - Bug

Title describes issue

### Acceptance Criteria (optional)
"Is User Removed?" updates when `deleteUser` mutation is called

- **Estimated effort:** 4 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed on master
