### ISSUE TITLE
Search Bar Enhancements

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3912]
Today, our Team View is just a kanban board. We want to change that to be the place to add agenda items, view team members, start video calls, host meetings, set up integrations, and link out to filtered views (e.g. link to timeline view filtered by that team). See #3458.

Before implementing the new Team View, we need to add the ability to search for archived tasks on the My Tasks view as well as filter by Team & User. Currently, My Tasks can only filter by Team.

Option 1: The search is contextual (ie unique to the My Tasks view). Changing search criteria updates the kanban
- Recent/Favorite searches should be persisted 
- A User multi-select should be available
- A Team multi-select should be available
- An "Archived" checkbox should be available

Option 2: Global search, results appear inside the search component & don't edit the kanban view. 
- Has Timeline Events section (broken down by type, e.g. meeting, new team member)
- Tasks section
- This isn't great because some folks may just want a lay of the land

Option 3: Keep filters outside of the search bar
- Add "Archived" and "User" filters below the search bar
- This is the quick & dirty solution

@tianrunhe @ackernaut i'm leaning towards options 1 since it seems like the most fully baked solution. if you have other ideas let me know here!

**Comment by jordanh** [comment]
A [user writes](https://app.hubspot.com/contacts/3888472/contact/6576801):

> It's me again, hope you are well.
> Can I request a feature?
> Problem:
> I have multiple meetings/retros with different people and I cannot filter tasks related to meeting/retro. I would like a filter by event (meeting/retro) so that I can show only the action related to that event. At the moment the only filter is by team member and not for event. Thanks

**Comment by mattkrick** [comment]
i think we should postpone until we do a little revamp on the dashboard IA
