### ISSUE TITLE
Deleted billing leader on Pro account

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3914]
If a user invites others, upgrades to Pro, then deletes their account, the org gets left without a billing leader:
- Create an account (user A)
- Invite 2 others
- Upgrade to Pro
- Delete user A
- Other users are still in the org (good) but there’s no billing leader (sad panda)

_Originally posted by @ackernaut in https://github.com/ParabolInc/parabol/issues/3910#issuecomment-642101627_

**Comment by jordanh** [comment]
Still a thing, iceboxing for now
