### ISSUE TITLE
Clean up User records & cache in redis

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3916]
marketing & sales needs a lot of user details attached to every segment event.
today, we just cache the email, we should really be caching the entire user doc.
done right, we can use this for graphql queries, too.

Unused user fields:
- welcomeSentAt
- cacheExpiresAt
- cachedAt
- emailVerified (it exists on the subdoc)
- name
- nickname

mutations that need cache busting: tbd

AC
- [ ] unused fields audited and removed
- [ ] a redis dataloader (may not actually be a DataLoader) is created. it only hits rethinkdb on cache miss
- [ ] all mutations that update the User doc invalidate the cache
- [ ] ~~tier added to all segmentIo.track events~~

**Comment by avivapinchas** [comment]
> is tier the same as highestTier?

Essentially, yes. Since a user can be in multiple Orgs, which are on different tiers, there's no single 'tier' necessarily. 

> if the tier is personal, pro, or enterprise could amplitude determine that "paid" means pro or enterprise?

Yep, you can typically select multiple values, so that should work.

**Comment by mattkrick** [comment]
checking in amplitude, looks like `highestTier` is gonna have to live on the user itself, not the track event, so we'll have to make a call to identify on upgrade/downgrade. will create a new issue to track that
