### ISSUE TITLE
Database Strategy, Remote Caching, postgres

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3918]
Today, we have a local cache (dataloader) and a noSQL DB.
As we grow, we should start thinking about moving away from RethinkDB and into postgresql (maybe using the knex query builder since that's pretty close to reql)
Additionally, we need to start thinking about adding a remote cache (redis) that sits between our DB and our local cache.

The ideal flow for queries is: graphql resolver -> dataloader -> redis -> DB.

The marginal benefit of a dataloader in front of redis is the batching functionality. Additionally, we can incrementally add caching to it, it's not all or none.

While we're at it, it'd be good to make it more difficult to return stale data. Today, it's pretty easy to get stale data by querying something using the dataloader, then mutating that thing without updating the cached version.

in a perfect world, resolve functions have no idea what DB the data lives in, where the caches are, etc. of course this isn't always possible for complex, DB actions, but for simple ones, we should be. able to abstract a lot of it away.

something like `db.update(table, id, props, dataLoader)` or `db.get(table, id)`

`update` accepts a dataLoader for the sole purpose of cache invalidation.
if a record is found in that dataloader, it'll update it. 

a good place to start with this is the User table. since that table is hit on almost every query, it'll have the biggest impact.

**Comment by jordanh** [comment]
This reads as all kinds of right to me

**Comment by mattkrick** [comment]
There are 2 valid strategies for handling JSON in redis: https://stackoverflow.com/a/18991212/3155110

1. We serialize the entire document & store it as a string
2. We use a hash map
3. use ReJSON, which is a redis module

1 is simpler, but more memory & CPU intensive. we'd have to serialize/deserialize. we'd have to get the whole document when we just want a single field. we'd have to implement record locking and read then write to guarantee no conflicts.

2 is more efficient, but would require special handling for JSON structures (e.g. our meeting documents that have phases & stages nested inside them, values can only be strings).

3 is kinda a compromise 

i think to start with, i'll do the dumbest thing possible & go with the first option.

**Comment by mattkrick** [comment]
few strategies to update the cache:
1. write to rethinkdb, clear the redis cache. this is the fastest way to write, but then reading that document requires a cache miss to redis, followed by a hit to rethinkdb
2. write to rethinkdb, update the redis record if exists. requires parsing, merging, stringifying & optionally setting the value in redis. chances are these can be completed before the update to rethinkdb returns
3. write to rethinkdb, update to redis record even if it doesn't exist. this requires possibly requesting the new document from rethinkdb and then writing that to the cache. i think this is too heavy handed. if the object wasn't cached before, it may not need to be cached in the future.

**Comment by mattkrick** [comment]
the cache can have a `write` or a `clear` (or both)

if only clear, every mutation to the db needs to be followed by a clear & a prime, if possible.
Priming will require an update object or JS function to merge into the existing cached value.
A call to to the DB & a separate call to the cache feels error prone, so we should try to add a write command & use that whenever possible.

if they're together, it'd be nice to be like rethink & accept either an object or a function.
if it's an object, then we can use it to update the local & redis cache.

if it's a function, it could be a reql function or a JS function. Having both a JS & a reql function seems overly verbose for marginal savings.
if it's a reql function, then we'll have to bust the local & redis cache. we could optionally get the new value back to prime the caches. 
if it's a JS function, then we'll have to hit rethink twice, 1 to read, use the JS updater, then 1 to write. since rethink is the most expensive part of the equation, this feels bad.

so, a write call should take in an updater that's either an object or a reql function. if it's an object, we can update the local & redis cache. if it's not, then we could either clear the caches or we could return the new doc from the DB. chances are, if you write a change, you'll want to soon read it, so the db write should return the new doc when the updater is a reql function. if it's an object, we can do the update on our own.

finally, we can batch writes or handle them separately. batched writes give up the isolation in ACID, but i'm OK with that.

so,
if the updater is a function, we leave the to-be-stale records in the local & remote cache & schedule the change in rethink. we get back the result & populate each cache with it on return. the write is complete when everyone acks: rethink, redis, and local.
if the updater is an object, we update the local cache if possible, then update the redis cache if possible, then update rethink. there's no need to wait for rethink to ack because subsequent reads and writes will hit the fresh local cache, but we might have to to keep things simple.

**Comment by mattkrick** [comment]
done in #3924
