### ISSUE TITLE
Snackbar floats about 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3934]
## Issue - Bug

After fixing #3759, the snackbar no longer covers the bottom bar, but rather floats towards the top of the screen: 
![Screen Shot 2020-06-16 at 3 16 13 PM](https://user-images.githubusercontent.com/11621016/84827773-92e65c80-afea-11ea-8b07-a6941cdd5614.png)
![Screen Shot 2020-06-16 at 3 20 33 PM](https://user-images.githubusercontent.com/11621016/84827781-94b02000-afea-11ea-8777-3984952e3163.png)

I've noticed this for both the conversion prompt and the 'XX wants to join this meeting' notifications. Depending on the size of the window, the prompt can hide behind the browser URL bar, so all you see is a shadow at the top of the window. 

### Acceptance Criteria (optional)
Users can:
   - Snackbar chills in a place that makes sense

**Comment by mattkrick** [comment]
any steps to reproduce reliably?

**Comment by avivapinchas** [comment]
🤔 Maybe it got fixed? It was happening consistently for me - mostly the prompt hiding behind the URL bar - but I can't repro it right now. Will keep an eye out for it again and jot it down 👍

**Comment by avivapinchas** [comment]
Got this again today - 
![floating-prompt](https://user-images.githubusercontent.com/11621016/86058838-1cece700-ba27-11ea-86c7-5937a4fdf432.gif)

This was during a Check-in meeting on the demo team I have. You can see at the start of the GIF that there's just a shadow towards the top - that's actually the prompt hiding. 

This was on my laptop screen, where last week I was using my second monitor and I wasn't seeing this, so not sure if window size is maybe a factor?

**Comment by mattkrick** [comment]
any actions before it happened? resizing the window, etc?

**Comment by avivapinchas** [comment]
Looked out for this during my last meeting - didn't resize. I typically notice the shadow at the top of the window, and then resize so I can actually see the dismiss button. It's happened at each check-in meeting that I've had this week, and this week I've been using my monitor and seeing it there.

**Comment by nickoferrall** [comment]
Hey @avivapinchas, I'm having difficulty reproducing this one. Does the snackbar only float about with the "free tier exceeded" and "XX wants to join this meeting" notifications or for all snackbar notifications? And is this happening on Chrome?

I've taken a look at a few different snackbars on Chrome and Safari and on different screen sizes but they're all behaving nicely so far. 

How can I reproduce the "XX wants to join this meeting" notification? I can see that notifications are triggered when someone is invited to a team or when a teammate starts a meeting, but how does someone request to join a meeting?

**Comment by avivapinchas** [comment]
> Does the snackbar only float about with the "free tier exceeded" and "XX wants to join this meeting" notifications or for all snackbar notifications? 

I'm not sure - I haven't noticed other snackbar notifications in meetings at all, so I've seen this with every snackbar in-meeting notification, ie these two. 

> And is this happening on Chrome?

Yep - Chrome Version 83.0.4103.116

> Just want to check if it's continued to occur during the past month?

Since I mostly have meetings with folks already on the teams and we turned off the 'free tier exceeded prompt' for anyone who is part of any Pro org (here), I wouldn't have gotten many snackbar notifications, so I haven't noticed it. 

If you've checked on a few different browsers and aren't seeing it, then maybe we don't need to worry about it anymore. 

Maybe we can test by me creating a team, starting a meeting and you ask to join the meeting, and see how that notification shows up for me? I just feel uneasy that it's unclear how it would've gotten fixed, when it was already kinda funky to repro in the first place.

**Comment by mattkrick** [comment]
Let's try in this file:
https://github.com/ParabolInc/parabol/blob/share-temlates-backend/packages/client/hooks/useSnackbarPad.ts#L11

Doing this:     `const snackbarOffset = bbox ? Math.max(window.innerHeight - bbox.top, 48) : 48`

**Comment by nickoferrall** [comment]
Thanks @avivapinchas and @mattkrick - I'll include this line in my next PR and then close the issue 👍  If the bug pops up again, we can reopen it and see if we can reproduce it

**Comment by mattkrick** [comment]
come to think of it, we'll probably need to bump it a little higher, maybe 
`const snackbarOffset = bbox ? Math.max(window.innerHeight - bbox.top, 96) : 48`?
