### ISSUE TITLE
Implement Archived Checkbox Filter for Task View

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3935]
Acceptance Criteria
- [ ] ~~On the route /me/tasks, next to the "All Teams" filter in the header, an additional "All Team Members" is added. Clicking it shows a dropdown with all the current users that are on the same teams as the viewer. Selecting a team member filters the tasks to only show tasks for that user.~~
- [ ] On the route /me/tasks, next to the new "All Teams Members" filter in the header, an "Show Archived Tasks" checkbox is added. Clicking it shows all the turns the kanban view into the archive tasks view. It loads the first 40 tasks that match the Team ~~& Team Member~~ filter. (for example if team is set to "Team A" ~~and team member is set to "Matt"~~ it shows the first 40 archived tasks ~~that were assigned to Matt~~ on Team A.
- [ ] In the archive view, if 0 results are returned & the Team ~~or Team Member filter~~ is set, a message appears saying no archived tasks exist for that filter.
- [ ] In the archive view, when the viewer scrolls to the end of the page, the next 40 results are loaded for ~~the combination of~~ the Team ~~& Team Member filter~~. The server should not return tasks that do not match the Team ~~or Team Member filter~~. 

Estimate: 30 hours

**Comment by tianrunhe** [comment]
Clarification question: when the kanban view turns into archived tasks view, do we present them in their corresponding columns?

**Comment by mattkrick** [comment]
nope, because 99% of them will be in the "done" column, so we'd be wasting some valuable real estate.
ideally we'd like a masonry grid, but react-virtualized doesn't offer that, so i think it has to be a fixed-height grid like it is today

**Comment by tianrunhe** [comment]
Screenshots for my current implementation, wanna get some early feedback:

![](https://user-images.githubusercontent.com/1879975/85636490-948cd180-b635-11ea-966d-a2bf1a568b4d.gif)

**Comment by mattkrick** [comment]
that is absolutely perfect!

**Comment by tianrunhe** [comment]
@mattkrick The updated A/C makes more sense😀. Does the second one (team member filter) duplicate with a lot of the A/Cs on #3933? Do we want to close that one in favor of this + the URL pattern?

**Comment by mattkrick** [comment]
ah good catch, forgot about that one. i'll remove that the team member filter from this AC so we can do them 1 at a time

**Comment by tianrunhe** [comment]
The first A/C in this issue still mentions team member filter, which to my understanding is the same as the "user filter" mentioned in #3933. But I guess in general we are moving some features from the team view to the task view, so let's talk about release phases. Here's my thought:

<table><tbody><tr><td>Phase</td><td>Team View</td><td>Task View</td></tr><tr><td>Phase I</td><td><ul><li>Archived Tasks button and route removed</li></ul></td><td><ul><li>A "Show Archived Tasks" checkbox added next to the team filter, toggling it will show/hide archived tasks corresponding to the team selected in the team filter.&nbsp;</li><li>Search bar still works when the view toggles to archived tasks.</li></ul></td></tr><tr><td>Phase II</td><td><p>Need discussion here. Possible choices:</p><ol><li>Keep it as-is</li><li>Completely remove the task columns and only leave org route, team settings and agenda topics.</li></ol></td><td><ul><li>Team member filter added next to the team filter:<ul><li>Selections in the filter should be all of the team members in the selected team in the team filter, plus a default selection "All team members"</li><li>If the team filter is selected as "All teams", then the selections in the team member filter should list all of the team members for all of the teams the viewer is in</li></ul></li><li>Both task and archived task view should work corresponding to the filters</li></ul></td></tr><tr><td>Phase III</td><td>Team View redesigned</td><td>Task view becomes the central place to see tasks</td></tr></tbody></table>

I think for this issue, as a starting point for the migration, it should be in Phase I (i.e., we only move the archived task feature, not the team member filter). @mattkrick Let me know what you think.

**Comment by mattkrick** [comment]
Great layout! Here are my thoughts:
For phase 1, let's not touch the team view, let's _just_ add the "Show archived tasks" to the Task view. That way folks don't have to change their habits until the new way is without a doubt the better way.

Phase 2:
- Team View: let's keep the team view as is until the new version is designed & built, then we can switch over to that all at once. that way it doesn't feel like we're slowly taking functionality away from the users
- Task View: Looks good! Good catch with the ambiguity between "User Filter" and "Team Member filter". We should call it "Team Member filter" but internally, we're actually filtering by User (since filtering by team member would imply a team filter, too)

Looks like a great design! Let me know if you run into any issues.
