### ISSUE TITLE
Lighten up the gray "ready" checkmark in meeting control bar

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3936]
Got some user feedback that the contrast between the gray & blue on the "ready" button isn't great.

AC:
we should lighten it up (or darken the blue?) to make the contrast higher so it's really obvious when "ready" has been selected

Estimate: 1 hour

**Comment by mattkrick** [comment]
@ackernaut assigning you just in case you want a lil palate cleanser

**Comment by ackernaut** [comment]
Yeah, I can try a lighter variant of the gray, and maybe some other ideas. Also, we recently switched from blue to green for the confirmed ready state and the progress circle.

**Comment by ackernaut** [comment]
Bad idea: add a tooltip ‘Set as Ready’ and ‘Set as Not Ready’

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/15839801) 🔒 writes:

> The color change when you click the ready button is super subtle even for someone who's not color blind. It would be easier to tell if you've clicked it if the whole button changed color and not just the checkbox within the circle.

**Comment by gcrickman** [comment]
[User](https://app.hubspot.com/contacts/3888472/contact/7032301) 🔒  feedback: 

> The "Ready" button, its very difficult to tell whether you have clicked that or not as the change is very subtle.  I doubt this would pass Accessibility standards.

**Comment by mattkrick** [comment]
@nickoferrall would you mind taking a stab at this & just picking a lighter gray variant?
