### ISSUE TITLE
Skipping voting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3937]
## Issue - Enhancement

When my team doesn't want to vote, I want to set the vote count to 0 and proceed.

[A user](https://app.hubspot.com/contacts/3888472/contact/15436351) 🔒  wrote:

>  We just started using it for our retros this week and the team seems to like it.  The team isn’t interested in doing voting at this time and I had some trouble setting the vote to 0 so that we could skip that step.  Is that how I would go about skipping the vote?

### Acceptance Criteria (optional)
Facilitators can:
   - Set the number of votes to 0
   - If set to 0, they can skip the vote phase entirely

- **Estimated effort:** 4 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Opening up as a Discussion to spool up team feedback

**Comment by jordanh** [comment]
Iceboxing for now

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/28413301) 🔒  writes:

> It would be nice to be able to skip the "Vote" stage of the retro process entirely. It feels like it's just adding overhead, especially for a small team.

**Comment by drewhousman1010** [comment]
I wrote down the following feedback from a [user ](https://app.hubspot.com/contacts/3888472/contact/12361501) 🔒 on a call: 

> Sometimes her team doesn't vote. She wants to be able to skip the voting phase entirely.
