### ISSUE TITLE
Notification preferences / disable email

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3939]
At long last, we're beginning to collect signal from user about their notification preferences.

Soon, it will be time to design notification preferences – likely living under the User Profile.

Questions to consider:

- What to do with meeting summaries?
- What to do with in-app notifications?
- What to do with marketing subscriptions?
- Today, we only support email for notifications. Should we provide other channels in the future (i.e. Slack App messages?)

Spooling up feedback here until this thread results in a clear next step

**Comment by jordanh** [comment]
A [user writes](https://app.hubspot.com/contacts/3888472/contact/12649051) 🔒 :

> My Feedback: I don’t want to be forced receiving this summary every time we have a meeting. My can’t I unsubscribe from this?

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/16071101) writes 🔒 : 

> Thanks for your response. I know it's not your fault. But your answer is incomplete, as you can see by the attached examples where there unsubscribe message does not show up 

This user is referring to automatic meeting summaries which cannot be unsubscribed in notification preferences.

**Comment by jordanh** [comment]
[A user writes](https://app.hubspot.com/contacts/3888472/contact/17792801) 🔒 :

>  Hi guys, i have some "handling" questions:- I need to close a meeting without sending a summary e-mail to everybody on the team. How do I do that?- Do I get a summary when I did not participate in a Retro?

After a bit of discussion, I asked:

> 1) If a meeting begins and ends quickly (i.e. it was started by mistake), ask to send the meeting summary
> 2) If a meeting has only one participant, ask to send the meeting summary
> 3) At the end of the meeting, always ask to whom and how to send the meeting summary
>
> Which of these options sound best? Is there another option we should consider?

They replied:

> I would recommend 3), because I have the option to choose. Maybe you only want to do Check-In or Retro only with a part of the team for a certain reason. Then you do not need to create a separate Team first. 

This make me wonder if components of a solution might be:

* Team-level notification preferences, with a preference for where we send meeting summaries
* When end meeting is pushed, a single CTA that appears on the activity to send the meeting summary
* A secondary action that can be taken on any completely activity, to send the activity to anybody via email and/or a sharing link to distribute it via Slack, etc.

**Comment by ackernaut** [comment]
Via [this person](https://app.hubspot.com/contacts/3888472/contact/905301/) 🔒 
>‘How can I unsubscribe from all email notifications (Meeting summary, check- ins etc)’

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/29813051) 🔒 wanted to unsubscribe from meeting summary emails, places they looked:

- Team Settings
- Notifications menu
- Bottom of the summary email for an unsubscribe link

Note: all automated emails need to have unsubscribe links to be strictly legal in all countries

**Comment by mattkrick** [comment]
Closing in favor of #4538
