### ISSUE TITLE
make startNewMeeting, endNewMeeting meeting type specific

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3940]
starting and ending a meeting both have a bunch of logic that is very specific to the meeting type. while down the road we'll have custom meeting types & need a generic `startCustomMeeting` mutation, for now the logic is a little spaghetti-ish by combining both types in the same mutation.

Acceptance Criteria
- [ ] `startCheckinMeeting` mutation created
- [ ] `startRetrospectiveMeeting` mutation created
- [ ] `startNewMeeting` is deprecated (but not removed, we'll do that later)
- [ ] `endCheckinMeeting` mutation created
- [ ] `endRetrospectiveMeeting` mutation created
- [ ] `endNewMeeting` is deprecated (but not removed, we'll do that later)

Estimate: 6 hours

**Comment by abhiaiyer91** [comment]
i read the `startNewMeeting` API and it looks like the only specific logic is around `retrospectives`.

https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/mutations/startNewMeeting.ts#L76

Do you want to extract some the shared logic between these mutations?

**Comment by mattkrick** [comment]
there's a fair bit of stuff for the check-in meetings, too: https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/mutations/startNewMeeting.ts#L91-L121

the agendaItem stuff should get removed for retrospective meetings, too (that's a current bug).

up to you on how to extract, it's really more art than science
