### ISSUE TITLE
Send user properties to Amplitude 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3943]
## Issue - Enhancement

We currently send a few properties to Hubspot as Contact properties that would be helpful to have in Amplitude as user properties: 
- Is Patient 0 
- Monthly Meeting Streak Current
- Monthly Meeting Streak Max 
- Parabol Meeting Count 

We can sometimes finagle similar data by doing stuff like `User performed X...` but the charts end up silly and imperfect. Having these as User properties would let us run user composition analysis and segment funnels by these attributes. 

### Acceptance Criteria (optional)
Parabol team members can:
   - Segment funnels based on patient 0, meeting count, and streak length 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by avivapinchas** [comment]
Related to #4048, specifically [this comment about the Marketing Dash](https://github.com/ParabolInc/parabol/issues/4048#issuecomment-707916232): adding the 'streaking' property in Amplitude would let us report on what percent of users are streaking as part of our monthly review.

**Comment by jordanh** [comment]
Iceboxing for now. I have a feeling this one will come up again
