### ISSUE TITLE
Task board integrations to Slack

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#3944]
My [client](https://app.hubspot.com/contacts/3888472/company/3141106646) would like tasks from the Parabol task board integrated over to Slack, with notifications:
" the feature i want is the possibility to have a random actionable reminder from the action board through slack."

**Comment by shawneeatparabol** [comment]
Hi @jordanh this has been requested by prospective [customer](https://app.hubspot.com/contacts/3888472/company/3141106646)🔐 and I think it would be valuable for many of our clients.   I haven't seen activity on the issue to calling attention to it.

**Comment by jordanh** [comment]
This issue will continue to need to be shaped and refined before we'll take next steps. Some questions to ask folks who request it:

1. What task notifications would you like to receive?
   1. When tasks are created?
   1. When tasks are archived or deleted?
   1. When task text is updated?
   1. When tasks change status?

1. What other Slack notifications do you envision?

1. Would you prefer getting notifications as they happen, or as a summary of changes?

1. Are Task reminders only set for tasks with a Due Date sent? When are they sent?

1. Are any notifications ever sent via email?

1. Should you be able to configure which notifications you get?

**Comment by jordanh** [comment]
Without clarifications, will icebox
