### ISSUE TITLE
Remove promptTemplateId from ReflectPhase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3949]
to enable public templates we need to know which templates are popular.
to do that, we need to know how many meetings have run a particular template.
to do that, we have to index on the templateId for the NewMeeting table
to do that, we need to promote the promptTemplateId to being a field in the retrospective meeting instead of being a field on the reflect phase
to not break currently running meetings, we need a buffer period where folks can create meetings & it'll add it to both locations
Once deployed, we can stop writing the reflect phase

AC
- [ ] promptTemplateId is no longer added to the reflect phase

Estimate: 1 hour

**Comment by mattkrick** [comment]
enough time has passed, let's go ahead & do this. should be quick & easy

**Comment by jordanh** [comment]
Will prioritize, bumping back to the inbox
