### ISSUE TITLE
Demo Meeting Summary uses reflectionGroup length from the last run rather than the current one

### ISSUE THREAD

**Issue by NikAiyer** [ParabolInc/parabol#3950]
When running the demo, if the user changes the number of groups to different values for different runs, the demo summary will use the values from the last run rather than the current run. For example, if the demo ended with 7 topics from 7 groups, if they run again and create 3 groups instead, 7 groups will still show up in the demo summary, with non-existent topics showing up with 0 upvotes. This will also happen the other way, where if 3 groups are created the first time, then only 3 groups will show up in the next run. If the page is refreshed, the correct values will show up.

Users can:
   - Run through the demo and create 7 reflection groups and upvote them
   - See that there are 7 groups in the demo summary
   - Run through the demo and create 3 reflection groups and upvote them
   - See that there are still 7 groups in the demo summary

EE: 16 hours

**Comment by jordanh** [comment]
Perhaps this was fixed? Either way going to close and stick in the icebox
