### ISSUE TITLE
Add SAML via graphiql

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3951]
Adding new enterprise clients doesn't require any programming, so we should make it possible for a CSM to do the work.

Acceptance Criteria:
- [ ] graphql mutation added to the private schema `enableSAMLForDomain(domain, url, metadata)`
- [ ] the above mutation adds a record to the SAML table with domain, url, metadata fields.

Estimate: 4 hours

**Comment by abhiaiyer91** [comment]
Where's the business logic for adding records to the SAML table?

**Comment by mattkrick** [comment]
this is it, it's just 1 insert call.
anything in particular i can help you find?

**Comment by abhiaiyer91** [comment]
@mattkrick Where in the codebase is SAML managed today. I can read that and implement something.

**Comment by mattkrick** [comment]
if you do a search through the code base for `'SAML'` it should pop up all instances that hit the SAML db table

**Comment by mattkrick** [comment]
fixed in #3986
