### ISSUE TITLE
Optimize metric queries

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3952]
## Issue - Enhancement

Each wee we try to run this GraphQL query to update our metrics. Currently, this query fails because it is too slow.

```query
query getAllCounts ($OneWeekAgo: DateTime = "2016-01-01T00:00:00.000Z") {
  personalOrg: suOrgCount(includeInactive: false, tier: personal)
  proOrgs: suOrgCount(includeInactive: false, tier: pro)
  enterpriseOrgs: suOrgCount(includeInactive: false, tier: enterprise)
  personalUsers: suUserCount(includeInactive: false, tier: personal)
  proUsers: suUserCount(includeInactive: false, tier: pro)
  enterpriseUsers: suUserCount(includeInactive: false, tier: enterprise)

  logins: logins(after: $OneWeekAgo, isActive: false) {
  	total
  }
  
  signups: signups(after: $OneWeekAgo, isActive: false) {
  	total
  }
}
```

### Acceptance Criteria (optional)
Users can:
   - rewrite backend implementation in TypeScript
   - migration to add index for `inactive` field

- **Estimated effort:** 16 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick I was thinking @tiffanyhan could tackle this one for us

**Comment by mattkrick** [comment]
@tiffanyhan this one is for you if you'd like it!
