### ISSUE TITLE
TS error expecting type SegmentClientEventEnum

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3953]
I’m running `v5.11.0` locally and seeing:
```
Writing ts
ERROR:
Variable '$event' was defined as type 'String!' but used in a location expecting the type 'SegmentClientEventEnum!'
```
### Acceptance criteria
- Triaged and TS error fixed
### Estimated effort
- .5 hr

**Comment by mattkrick** [comment]
as a tangent i fixed this in #3931 but if there is more immediate tension we can cherry pick it out
