### ISSUE TITLE
Bottom bar covers commenting in Check-in Meetings

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3959]
## Issue - Bug

With smaller windows, bottom bar covers the commenting field in the discussion thread: 
![Screen Shot 2020-06-25 at 12 52 52 PM](https://user-images.githubusercontent.com/11621016/85772942-f5261800-b6e2-11ea-888d-3b525bcf44de.png)

- **OS:** macOS
- **Browser:** Chrome Version 83.0.4103.116 (Official Build) 

### Acceptance Criteria (optional)
Users can:
   - Enter comments without being blocked by the bottom bar

**Comment by mattkrick** [comment]
this isn't how it should be. the discussion panel should sense the bottom bar & scootch up.
what are the steps to reproduce? are you changing the window size? is it for the retro or checkin?

**Comment by avivapinchas** [comment]
This is during a check-in meeting, and yes, I was changing the window size - doesn't look to happen if the window size is already small.

**Comment by jordanh** [comment]
Must add window resize listener
