### ISSUE TITLE
Deprecate CustomPhaseItem in favor of ReflectPrompt

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3962]
When building out retro meetings, I think i swung a little too far on abstracting out meeting concepts.
A `CustomPhaseItem` is pretty esoteric & is going to be very different from other phase items for other meeting types. We should call em what they are: Reflection prompts.

AC
- [ ] `CustomPhaseItem` table is renamed to `ReflectPrompt` & all references updated
- [ ] `ReflectPrompt` has index added for `templateId` 
- [ ] `customPhaseItemsByTeamId` dataloader is replaced with `reflectPromptsByTemplateId` & all references updated

Estimate: 8 hours

**Comment by NikAiyer** [comment]
Working on this one

**Comment by NikAiyer** [comment]
How is a change like this deployed? Does RethinkDB have some failover that allows old code paths to still work?

If I rename the table before shipping new references will this break? Whats the best way to make this backwards compatible?

**Comment by tianrunhe** [comment]
I think you need to write [migrations](packages/server/database/migrations)

**Comment by mattkrick** [comment]
before a new version of the app is deployed to production, we back up the database & then run database migrations.
That migration should add a new table and copy all the old data over to it.
Then, in the future when no one is writing to that old table, we can run another migration to delete the old table.
