### ISSUE TITLE
Reliably profile graphql queries

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3964]
Now that we have a rudimentary caching system, we should start profiling graphql queries to figure out where the bottlenecks are.

### Background
- Profiling at _just_ the query level is too broad, a single graphql query may contain 100+ DB hits where only 1 is misbehaving
- In the past, we tried using datadog's APM service for profiling, but it caused some lag. that said, I'm up for trying it again & watching it very closely (ie turning it off/on with a ENV variable so if it starts crashing prod we can turn it off real fast)
- There may be other profiling tools out there. I know apollo engine has a built-in profiler, but it's also got a large overhead
- I'm not opposed to building one in house if we can make it more performant than the others. It was done a looong time ago: http://hueypetersen.com/posts/2015/11/06/instrumenting-graphql-js/

Requirements:
- [ ] A tool is implemented that allows me to find the graphql fields that take the longest time to resolve.
- [ ] the tool also includes everything necessary to reproduce the longrunning query (query string, variables)

Acceptance Criteria:
- [ ] All options are explored & a plan is created & presented to product team on which option looks best
- [ ] The plan includes comparison against different options & rough time estimates for each

Estimate: 12 hours

**Comment by jordanh** [comment]
Iceboxing per policy. Will likely get to #4298 first.
