### ISSUE TITLE
Sometimes duplicate agenda items

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3967]
Sometimes I’ve seen duplicate agenda items. I’m not sure how to reproduce, but I suspect some silly meeting state? Maybe a meeting ended early? Here’s a snippet from our Product team dash. Note, there are 2 non-pinned items below the pinned items, not shown:

![Screen Shot 2020-06-29 at 12 35 07](https://user-images.githubusercontent.com/307286/86037715-6f1d1080-ba05-11ea-8ebf-a8917e026fe2.png)

### Acceptance criteria
- [ ] Triaged the issue

### Estimated effort
- 2 hours

**Comment by ackernaut** [comment]
Per @avivapinchas — maybe this happens after a Retro (i.e. different type) is run on the same team.

**Comment by jordanh** [comment]
This happens because we don't check if the meeting that just ended was a retro meeting

**Comment by tiffanyhan** [comment]
this also happens when a check-in meeting is "killed" e.g. it ends before any agenda items are able to processed
