### ISSUE TITLE
Gitlab Integration

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#3971]
[User](https://app.hubspot.com/contacts/3888472/contact/13317301) requests a one-way hook from Parabol to Gitlab, similar to the integration we currently have with Github.

**Comment by jordanh** [comment]
I was wondering when we'd hear about this the first time.

What I _really_ want to do is think about how we might make adding integrations easier for open-source contributors in general. It makes it so well-intended folks who have the capability to add integrations, can't—as what happened when a contributor tried to add Azure Devops in #3004 (see also: #3499).

Today there isn't an integration abstraction. Integrations are deep, and therefore tricky to implement and take _a lot_ of system knowledge.

**Comment by jordanh** [comment]
See also #1285, 4 other requests for GitLab – starting over a year ago

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/15472001) 🔒  writes via support: 

integration request - gitlab integration for creating issues

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/20598201/) writes: 

> Subject: Integrations with Gitlab CE and RocketChat
> Message: Hi there, maybe create an integration with this is useful too. My team uses Gitlab and RocketChat it would be great if exists.

**Comment by jordanh** [comment]
Updating this issue.

We're contractually obligated to deliver a GitLab integration by 2020 Jan 01.

First step will be to design it, so I've updated this issue accordingly.

### Acceptance Criteria (optional)
Users can:
   - CRUD Mattermost integration on their team
   - Publish integrated task cards as Gitlab Issues
   - Query Issues in Sprint Poker, add them to Scope
   - Research question answered: are their custom sizing/pointing dimensions?
      - If so: set Estimate score to dimension(s)
      - If not: specify Estimate output is only a comment
   - Set of implementation issues created

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Related #4008

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/34888151) 🔒 writes: 

> We would love to see a GitLab Integration

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/37765951) 🔒  writes:

> A Gitlab integration would be very helpful!

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/27581051) 🔒  writes:

> Curious if integrating with gitlab is on your future roadmap? Similar to your Jira integration, I'd like assigned tasks to generate gitlab issues... possibly super easy with CSV export from parabol.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/23438401) 🔒 writes:

> Currently, I'm teaching Cloud Native Development using GitLab pipelines, and the GitLab PM features.  I believe Parabol only integrates with GitHub?  That said, I start a new class on Monday, and will be out of pocket until mid November.  We will be using your Retros for this class (weekly retros).  I would be happy to talk more with you about it then.

**Comment by jordanh** [comment]
Closing this, as #5564 and #5639 adequately capture next steps
