### ISSUE TITLE
Add UTM parameters to Slack timer reminders

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3976]
## Issue - Enhancement

Similar to #3685, add UTM parameters to meeting 'timer set' reminder send as part of Slack integration. 

Should be: 
- Source  = `slack timer notice`
- Medium = `product`
- Campaign = `invitations` 

### Acceptance Criteria (optional)
Parabol team can:
   - See what traffic comes to our site from the Slack timer reminders 

- **Estimated effort:** 2 hours

**Comment by jordanh** [comment]
Iceboxing per policy. If this is still important to you @avivapinchas, we will reopen and prioritize. It would be trivial to do.
