### ISSUE TITLE
Client side debug setup and enabled

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#3979]
## Issue
There are currently some gotchas (around `sourceMap` configuration) that prevents developers to debug from client side (i.e., in a browser).

### Acceptance Criteria
- [ ] Developer can debug the client locally using breakpoints in VS Code
- [ ] Documentation for how to set it up is in Notion

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tiffanyhan** [comment]
hey @tianrunhe what happens when you try and set a breakpoint, I'm assuming in Chrome devtools? I was able to set a breakpoint and pause execution of client side js without doing anything special config wise.

**Comment by tianrunhe** [comment]
Oh I'm referring to similar pattern as #3958 : you set the breakpoint in VS code, on a client side TS/TSX file and are able to debug through. I wonder if we need to modify the client side web-pack config as well. Also there seems to have special configs needed to be done in VS code and Chrome (e.g., [this guide](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#:~:text=To%20debug%20the%20client%20side,the%20Debugger%20for%20Chrome%20extension.&text=Open%20the%20Extensions%20view%20(Ctrl,button%20for%20Debugger%20for%20Chrome.)). I think it'd be valuable to have this documented too.

**Comment by tiffanyhan** [comment]
Oh rad! I wasn't aware of the extension. I've only debugged client side code straight from browser. I definitely prefer to be able to do in VSCode though. 

I tried debugging from VSCode with the chrome extension and was able to get it working with the same config `devtool: 'eval-source-map'`. 

I'll write PR and docs tmrw or some time other this weekend ^___^

**Comment by tiffanyhan** [comment]
Here's the [docs in Notion](https://www.notion.so/parabol/How-to-Debug-client-code-using-breakpoints-in-VSCode-8c0009485fbf4d539e9cb05258bde2c0).

**Comment by tianrunhe** [comment]
PR and doc reviewed. Feel free to merge and close this issue. Great job!👍
