### ISSUE TITLE
Documenting to writing, updating and running Cypress test locally

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#3980]
## Issue
There is currently no documentation on how to create/update/run Cypress tests locally, even though they are running in our CircleCI. This could potentially lead to a bad commit which fails the test in staging, but could be easily caught and fixed locally before submission. Being able to create/update/run the tests locally is a step forward toward a full Continuous Delivery pipeline. Imagine the world there developers can push to `master`, which triggers a set of integration tests to run and automatically reject the change if a test failed.

### Acceptance Criteria
- [ ] Documentation for how to create/update/run Cypress tests locally exist in Notion and verified by other developers.

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
[Doc](https://www.notion.so/parabol/How-to-run-Cypress-tests-locally-2f0ae15b5fe0433da6c855cea371b20d) created.

**Comment by jordanh** [comment]
This looks wonderful 🤩
