### ISSUE TITLE
Bug if too many meeting templates

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#3988]
#3988  Issue - Bug
[A user](https://app.hubspot.com/contacts/3888472/contact/11242501) 🔒  writes: 

> Just dropping you a message regarding a bug I found while using Parabol.
> 
> When having over 10 (custom) meeting templates in Parabol, the list is longer than the modal with templates, resulting in text (and the ‘Add template’ button) being showed against a transparent background (and therefore unreadable). A scroll bar is more appropriate here 😉. Also see the attached screenshot.
> 

![Parabol_Overflow](https://user-images.githubusercontent.com/60167404/87332729-3aad6680-c566-11ea-881d-920fb3a6e240.PNG)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
closing in favor of #3931
