### ISSUE TITLE
Update CircleCI config to push cypress screenshots to S3

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3992]
​

AC

When cypress runs it should create screenshots.

Those screenshots should get pushed to S3 in the /vX.Y.Z folder

Those screenshots should be easy to grab from anyone on the team

**Comment by RandallKent** [comment]
@mattkrick Have you considered recording tests to the [Cypress Dashboard](https://on.cypress.io/dashboard-introduction)? It gives you much more than asset aggregation: integrations ([GitHub](https://on.cypress.io/github-integration)/[Slack](https://on.cypress.io/slack-integration)), [parallelization](https://on.cypress.io/parallelization), [analytics](https://on.cypress.io/analytics), and [flaky test management](https://on.cypress.io/flaky-test-management) to help track down some of those race conditions I saw mentioned in #4431.

It's free for Open Source projects and can be set up in minutes by [creating a record key](https://on.cypress.io/projects#Setup) in the Test Runner.

I may be a bit biased as Co-founder though 😬

**Comment by mattkrick** [comment]
hey @RandallKent thanks for stopping by!
[we used to](https://github.com/ParabolInc/parabol/blob/5ffb8c45ce1af3882ef2ab4ba224466c8e235396/packages/cypress/package.json#L19) use the dashboard all the time, it was fantastic! i think i probably just removed the `--record` arg one day to debug locally & forgot to add it back in :sweat_smile:

hope all is well on the cypress front! cheers

**Comment by RandallKent** [comment]
Nice! That was quite a while ago. A lot has changed with the Dashboard, especially around analytics and flaky test management. Would totally suggest adding back in so you can not only close this issue but also track down those race conditions.

**Comment by jordanh** [comment]
Iceboxing
