### ISSUE TITLE
Update meeting lobby illustrations, including new image for Sprint Poker

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3999]
## Issue - Enhancement

In anticipation of Sprint Poker, we've worked on a new illustration for the Meeting Lobby to show this meeting type. At the same time, we took the opportunity to update the existing illustrations to add warmth. New illustrations can be found [here](https://drive.google.com/drive/folders/1_7pTd3_T1PwE2WvRKwY7pyRaG2RLc6MA
). 

### Acceptance Criteria (optional)
Users can:
   - Enjoy the new illustrations in the meeting lobby 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
can someone let me into the drive folder? i don't have access @ackernaut

**Comment by jordanh** [comment]
I got chu
