### ISSUE TITLE
Can't join meeting 

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4000]
## Issue - Bug
[A user](https://app.hubspot.com/contacts/3888472/contact/4940301) 🔒  writes in via support:

> when i join my team's meeting, it gives me error as "An error has occurred! We’ve alerted the developers. Try refreshing the page".
> even when i join with invitation link.
> 
> can you please help me to resolve this?
> Please let me know the updates.

### Acceptance Criteria (optional)
Users can:
   - Cannot do that: join any meetings

**Comment by tianrunhe** [comment]
I can reproduce the issue by impersonating the user. Errors I saw on sentry.io:

| **console** | 
```
SEND TO SENTRY Error: Not invited to the meeting. Cannot subscribe
    at ge (/app/dist/web.js:1:873074)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) undefined
```

 |
| --- | --- |

| **console** | 
```
SEND TO SENTRY Error: Redis took too long to respond
    at Timeout._onTimeout (/app/dist/web.js:1:865363)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) undefined
```

 |
| --- | --- |

| **console** | 
```
SEND TO SENTRY [Error: Cannot return null for non-nullable field RetrospectiveMeeting.(viewerMeetingMember,viewerMeetingMember,viewerMeetingMember,viewerMeetingMember).] undefined
```

 |
| --- | --- |

| **exception** | 
```
Error: Cannot return null for non-nullable field RetrospectiveMeeting.(viewerMeetingMember,viewerMeetingMember,viewerMeetingMember,viewerMeetingMember).
```

 |
| --- | --- |

**Comment by tianrunhe** [comment]
Root cause: the user is not in the team that holds the meetings.

**Comment by tianrunhe** [comment]
The user's `tms` field contains archived team ids. Cleaned it up and got back to the customer.
