### ISSUE TITLE
Jira Webhooks

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4005]
A Jira integration becomes a lot more useful if updates in Jira trigger updates to Parabol.
To do that, we have options:
- we can poll jira (e.g. if a Task is being loaded, we check the last time it was synced. If it has been more than 5 mins, then we re-query the content from Jira)
- we can put a webhook on jira so it alerts us whenever something is changed

The 2nd option means tasks update faster & it's less CPU intensive, so we should prefer that one. Unfortunately, that means the person adding the webhook has to be a jira administrator. We can add polling later for non-admins, if need be. For now, the scope is just webhooks.

AC
- [ ] a `JiraWebhook` DB table exists with `projectKey, teamId, userId, webhookId` etc. the PK is a compound key of projectKey & teamId. In other words, 1 webhook per team per project.
- [ ] `AtlassianManager.tsx` has a method called `getIsGlobalAdmin(cloudId: string)`. If it returns true, we know the viewer can add webhooks. we will use this for our friendly UI.
- [ ] AtlassianManager has an `addWebhooksForProject(cloudId: string, projectKey: string, teamId: string)` it looks in the DB to see if a webhook exists. if it does, it grabs the webhookId & looks that up in jira. if it does not exists in jira, it's removed from our DB. if it does, it looks at the filter & events. if the filter & events do not match what we currently use in the app, delete the exists webhook. else, do nothing, the webhook is already set. If no webhook exists, add a webhook for jira:issue_updated and jira:issue_deleted. Filter for a projectKey. 
- [ ] set the webhook to call our server at `/webhooks/jira`
- [ ] the webhook handler cannot verify the payload. so instead, we grab issueKey from the webhook payload, reach out to jira to fetch the issue, and then update based off of this verified payload. the webhook handler should call `publishWebhookGQL` to access the private schema
- [ ] on the private graphql schema a mutation exists called `jiraUpdateTask` which accepts a partial jira issue e.g. `{id, content, storyPoints}`. that mutation verifies that the authToken is a superUser. it then updates the appropriate fields (eg content) of the Task & then publishes those changes to the Task subscription channel so the update is received by all in real time.
- [ ] `jiraDeleteTask` handles the jira:issue_deleted event. it deletes the task from our system & pushes that change via the Task subscription.

Effort: 25 hours

**Comment by tiffanyhan** [comment]
https://community.developer.atlassian.com/t/how-can-i-register-a-webhook-using-the-rest-api-when-using-3lo-oauth2/30781/4

**Comment by mattkrick** [comment]
for posterity,
I agree polling isn't a viable option. if someone is scoping a poker meeting & changing something in jira, they're likely clicking over to the parabol tab within the next couple seconds. that means to not feel like garbage we'd have to be polling at <5 second intervals. every if we got clever & only polled for teams that are looking are jira issues, that's still a headache.
we might have to do it in the future. but for now, it's easy to just relay the message & not cache anything.
