### ISSUE TITLE
Research Microsoft Teams, Azure Dev Ops integrations

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4009]
## Issue - Enhancement

As a first step on #4008, we want to specifically look at Microsoft Teams and Azure Dev Ops. Our key questions are: 
- Is there a plan to consolidate these tools in the future? What's that timeline? 
- What would integrating with that combo-tool look like? 

Related to #3538 and #3004

**Comment by gcrickman** [comment]
[An account](https://app.hubspot.com/contacts/3888472/deal/2836359974?interaction=email) 🔒  mentioned they would find a 2-way link for tasks between Azure Dev Ops very useful.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
