### ISSUE TITLE
Video UX target scoped

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4014]
### Background
For a while now, we’ve included video in the target UI designs. I want to write down some of the details and organize some of the concepts to serve as a baseline for future discussions (re: decisions, designs, implementations) as we get closer to shipping a first beta.

### Acceptance Criteria
- Concepts gathered illustrating general intent of video UX and its place in the IA
- Notes gathered and shared expressing intent and principles behind
- Async video shared to walk through as a demo

### Estimated Effort
- 6 hours

**Comment by ackernaut** [comment]
See #3642 for older notes

**Comment by jordanh** [comment]
Iceboxing
