### ISSUE TITLE
Meeting history not being ported in by Hubspot/Colab API

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4034]
The Parabol app API into Hubspot frequently doesn't log the meeting activity history - doesn't show last meeting at, meeting count or streak. An example can be found🔐 [here](https://app.hubspot.com/contacts/3888472/company/3173471601)

**Comment by shawneeatparabol** [comment]
Again with [this account](https://app.hubspot.com/contacts/3888472/company/3179291061)
The user count, active users count, active team count, last met at, and meeting count numbers are all off. I am manually updating them so I can send out sequencing that uses these fields but including a screenshot of the inaccurate info here.
Accurate info would read: 70 AU, 183 user count, 9 Active Teams, Last Met 7/28/2020, 175 Meeting Count
![Screen Shot 2020-07-30 at 12 59 44 PM](https://user-images.githubusercontent.com/65249741/88982695-ad0b8f80-d264-11ea-8b6b-be59f319c352.png)

**Comment by shawneeatparabol** [comment]
Here is [another account](https://app.hubspot.com/contacts/3888472/company/3173322524), the active user count is correct but no other data pulled at all

**Comment by jordanh** [comment]
Superceded by #4043
