### ISSUE TITLE
Generalize meeting structure

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4041]
As we move into more meetings, it'd be nice to nail down the special sauce as to why we're so awesome.

- Timebox
- every voice heard
- good UI

Here's how we can replicate this for any subject:
- Diverge/Create. This can be done on an individual level, or in small teams. Inputs include the result of a previous converge stage, whether in meeting or out
  - Reflect on good/bad
  - draw stuff
  - draw on past experiences/expertise
- Converge/Distill. This can be done on a small or large team level. Inputs include the result of a divergence
  - Grouping reflections 
  - Identifying outliers in divergent items/opinions
  - Reaching consent, consensus, or identifying further needs 
- These 2 stages can be repeated until time is reached

My hot take: tiered breakouts. Start with the whole group in the diverge phase. If the group is too large to converge all at once, converge individuals into small teams. optionally diverge again. then converge up again until the the group includes everyone. This will solve the grouping million reflections grouping problem and should also work for any other decision. it's basically a tournament leading to the top.

**Comment by jordanh** [comment]
👏 👏 👏

**Comment by jordanh** [comment]
Iceboxing for now
