### ISSUE TITLE
Triage missing Hubspot prop updates

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4043]
## Issue - Bug

Members of the growth team had been reporting that HubSpot properties on Company records and Contact records was incomplete. I noticed that we hadn't had a new growth lead open in 3 consecutive weeks. I had a look into this today.

Reproduction steps:
  -  Look at the log in `#t_product_prod`, search for meeting completion events
  -  Find an associated Contact or Company record in HubSpot, click on "View property history"
  -  Note absence of some property updates, commonly `Last Met At`, `Meeting Count`, `Monthly Meeting Streak Max`, etc.

I'm not sure if the Segment Functions function is borking or our API is rate-limited or what. Either way, it's borking our ability to sell

### Acceptance Criteria (optional)
Users can:
   - Triage failure
   - Fix if within estimated effort budget or open new issue

**Comment by avivapinchas** [comment]
Not sure if this is the same or a different issue, but adding it here just in case: 
- [User](https://app.hubspot.com/contacts/3888472/contact/17356251)🔒 wrote in to support to say they'd deleted their account but still received email 
- Checking in Hubspot, the `is user removed?` property is blank - so this didn't get updated when/if they deleted their account, and thus didn't trigger them being unsubscribed

**Comment by jordanh** [comment]
@avivapinchas you beat me to the punch. Looking into this, yes–this prop update wasn't happening which meant the user was not un-enrolled from marketing emails. I'll get this prioritized for fix next sprint

**Comment by mattkrick** [comment]
I noticed 2 problems:

1. The code up on segment was an older version. How did an old version of the code wind up back on segment? It could've been me & I just forgot to push the latest a couple months back, or it could've been segment doing a rollback & not letting us know.

2. i wasn't normalized date fields for companies. hubspot only updates something if all the fields are correctly formatted. i'm pretty perplexed as to how this passed testing initially, but it should work now. we'll monitor & see if the number of errors decrease.

**Comment by jordanh** [comment]
I had a look at recent meeting completed events and checked HubSpot—everything looks _great_ so far. Thank you so much, sir!
