### ISSUE TITLE
Contributing guidelines for git strategy.

### ISSUE THREAD

**Issue by debuggerpk** [ParabolInc/parabol#4044]
Gentlemen, in light of my team's (@getbreu) frustrations with over-written history (same commit, different SHA) and merge conflicts, I shot @jordanh an email. he suggested putting it up for a discussion with the community. 

The suggestion put forward by @jordanh is that we should do fast forward only i.e. `git pull --ff-only` for PRs. The added bonus is that we get a very clean git history. (linear IDK). 

My goal is to minimize merge conflicts and optimizing developer's time as the core team of contributors is growing.

// ysf

**Comment by mattkrick** [comment]
--ff-only certainly works. do you have a specific example where this would help with merge conflicts? IMO most IDEs already do a pretty good job with the diffing today, but i'm happy to help if there's something that could be easier

**Comment by debuggerpk** [comment]
I am going to start this conversation with a gripe.

My team spent, mostly @ray-man, spent a little time trying to understand  #3464. The main objective for us was to understand how existing integrations worked and how the overall process flow is architected. We choose the Github integration for our investigation.

After our initial investigation, It was easier for us to leverage @joalmeid work on #3464. The branch was out of sync with current master. The best way for us to do that was to understand what git history looked like when the PR was made. Work @joalmeid did is spanned across 8 commits and the PR was made over two different PRs. The second PR was made to leverage the first one's work and adds one more commit to merge conflict. We spent a little time, cherry-picked each commit at the right moment in time, navigating the merge conflicts very carefully and keeping the history linear. 

At this point, my team thinks that the work already was done for #3464 conforms to how the current codebase is set up and does what it is supposed to do and I am a little sad to see such good work go to waste.

But that doesn't stop us from learning. For me, the takeaways are

- the instructions for `--ff-only` should be clearly documented so we derisk any future occurrences.
- it makes sense to write a dynamic integration layer that should form the basis of each integration. 
- each integration should be like a plugin for us and each integration should be moved out.

The objective is to update contributing guidelines to document this behavior along with having a larger consensus within the community on the direction to take for integration layer.

// ysf

**Comment by mattkrick** [comment]
i hear you, merge conflicts on large PRs are a huge pain.
Unfortunately, I don't think ff-only would do anything to combat the pain of merging in PR that's 8 months old, there's just always going to be conflicts no matter the merge strategy.
that said, if you've got a specific commit example where it'd help, i'd love to learn!

**Comment by jordanh** [comment]
Is this discussion resolved?

**Comment by ray-man** [comment]
Since #4076 ,  #4029 are merged and #3836 is intentionally closed (#4029 covers its changes). I believe it is resolved. Unless someone has a different opinion.

**Comment by jordanh** [comment]
Iceboxing
