### ISSUE TITLE
Make Shared Templates Mobile Friendly

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4045]
AC

- [ ] can [CRUD templates easily on mobile](https://www.figma.com/file/wYDUg5qQMjbEllgxBY37sT/Template-Editor-Dialogs?node-id=591%3A1655)

​

Estimate: 16 hours

**Comment by mattkrick** [comment]
We've let this sit out too long on the backlog. promoting to the top so we can get it done next sprint since the design work is done & we just need to build it

**Comment by mattkrick** [comment]
i feel pretty about out this one going stale again. let's bump it up!

**Comment by jordanh** [comment]
Iceboxing
