### ISSUE TITLE
Add '# of Meetings' user property in Amplitude 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4048]
###  Issue - Enhancement

The number of meetings that a user has completed tells us important information about how engaged they are, how thoroughly they've been onboarded. When trying to understand drop-offs for users early in their lifecycle, it would be useful to be able to filter a funnel to only show users whose meetings counts were 0, 1 or 2. Similarly, when looking to understand inactive users, it would be helpful segment these folks by the number of meetings they held ([example of a user segmentation report that doesn't work currently](https://analytics.amplitude.com/parabol/chart/l2jqaep )).  

### Acceptance Criteria (optional)
Pals can:
   - Filter and segment by a 'number of meetings' user property in Amplitude 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i may be missing something here.
could you add "Performed a Meeting Completed Event <= 2 times" filter to the query to accomplish this?
example here: https://analytics.amplitude.com/parabol/chart/81vw4sg

**Comment by avivapinchas** [comment]
That would specifically tell me how the segment of users who met 2+ times behaved, but not the breakdown of how many meetings inactive vs active users had completed. I could create this same report for each different count, export it, and then aggregate and compare, but it just gets very messy. 

So the question I'm trying to answer is: how many meetings did inactive users previously run? So ideally I need a chart that shows me a breakdown of inactive users by meeting count, rather than different segments.

**Comment by mattkrick** [comment]
i think i get it. you want it broken down by userId?
does this get you what you need? https://analytics.amplitude.com/parabol/chart/t78zxjw

**Comment by avivapinchas** [comment]
Another use case for this: 
- Our Marketing Dash includes an 'activation' section, where we want to see what % of users had 1, 2 meetings, etc. to determine how 'onboarded' our user base is. 
- Ideally, we'd do this via a `user composition` chart in Amplitude. However, in order to do that, the # of meetings needs to be a user property. 
- Today, afaik, there's no way to see a breakdown of users by # of meetings in Amplitude, including folks who had 0 meetings.

**Comment by jordanh** [comment]
Iceboxing for now. Will re-raise down the line, I'm sure
