### ISSUE TITLE
Mobile viewport height and bottom controls

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4049]
Using a mobile-first principle when designing UI views is a good thing. It forces us to work with constraints—what’s the primary activity of the current view? Most importantly we get a mobile-friendly UX for folks who are on their phone and trying the demo, tapping through from the email summary, or actually using the app.

However, it’s tricky to get the viewport size right when pinning controls to the bottom. Sometimes controls might be hidden until the user scrolls the browser chrome away. [This article illustrates the issue](https://chanind.github.io/javascript/2019/09/28/avoid-100vh-on-mobile-web.html) and offers a solution.

That may not be the exact solution we want but I think if we wanted to solve for this issue it would be good to have a single, global method that informs all the UI views of the height.

As an example of the problem, I have seen where the ‘Join’ snackbar component gets clipped off. However, our primary Start Meeting button and the bottom bar of the meeting are both using positioning that seems pretty reliable. So I think we can backlog this one but be aware of it as we start using full-screen dialogs for mobile.

### Acceptance criteria
- Researched and proposed a solution for handling viewport height on mobile browsers

### Estimated effort
- 4 hours

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/19482951) 🔐 noticed, see [verbatim video comment](https://drive.google.com/file/d/1CUZOESAu29y1ILE6Q0TUB0sfF-h13l-h/view?t=7m04s) 🔐

**Comment by jordanh** [comment]
Iceboxing
