### ISSUE TITLE
Finish refactor of custom phase items

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4054]
CustomPhaseItem is now ReflectPrompt.
Now, we can remove the old things without breaking anything.

AC
- [x] Meeting `focusedPhaseItemId` migrated to `focusedPromptId` (OPTIONAL)
- [x] Reflection phaseItem, retroPhaseItemId are removed from graphql schema & DB records
- [x] ReflectionGroup phaseItem, retroPhaseItemId removed, too
- [x] audit graphql `deprecationReason` fields to see if there's anything else we can remove
- [x] remove CustomPhaseItem & the CustomPhaseItemTypeEnum & the constEnum that powers it
-
Estimate: 4 hours

**Comment by jordanh** [comment]
Groomed

**Comment by jordanh** [comment]
Discussed during scrum. We want to keep this one on the backlog. We feel it's a good opportunity to broaden team knowledge. We might parcel this one out to somebody like @tianrunhe to get done.

I'll move this back to "To Prioritize" now to see if we can increase the odds of it getting done before it goes stale again.
