### ISSUE TITLE
Sprint Poker template & scale UI implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4057]
See #4184 for backend implementation

For concepts and notes, see #4015 and [this update in Notion](https://www.notion.so/parabol/Meeting-template-editing-807b69835881449e953708f2d9982a68) (w/ Loom and links to Figma).

#### Templates
- Teams can use or clone a single starting template
- Teams can create a new template
- The template has a single dimension
- The default name of the template and the single dimension is ‘Story Points’
- Folks can edit this value
- Folks can set the level of sharing of team-owned templates: team, org, public
- For mobile, the details view goes back to the list view
#### Scales
- Folks can select a default scale: Fibonacci, T-shirt Sizes, Five Fingers
- Default scales
  - Fibonacci: 0, 1, 2, 3, 5, 8, 13, 21, 34, ?, Pass (see default colors in Figma)
  - T-shirt Sizes: XS, S, M, L, XL, ?, Pass
  - Five Fingers, 1, 2, 3, 4, 5, ?, Pass
- ❓ and 🚫  are included in scales by default:
  - Folks can tap to exclude (boolean toggle)
  - Folks can tap the palette select to change the color of the card. Maybe disable this if the value is toggled off
- Folks can create their own scale
- A scale value option has a value field and a color
- A scale value option can be added, edited, and deleted
- The scale editing view goes back to the template details view
- TBD: can edit or clone existing scales?
#### In the future
- We’ll most likely add multiple dimensions
- We may add numerical value fields for semantic scale values
- We may add a description field for scale values: e.g. Fibonacci `3` means `2-3 days`
- We may add an optional template with a weighted formula for value-based and effort-based dimensions

**Comment by mattkrick** [comment]
@tianrunhe 
On a scale, the `values` property should be an array of objects where each object is: `{color, label, value}`for example, on tshirt sizes, we'd have values = `[{color: 'blue', label: 'S', value: 1}, {color: 'green', label: 'M', value: 2}]`

**Comment by ackernaut** [comment]
>❓ and 🚫  are included in scales by default:
>  - Folks can tap to exclude (boolean toggle)
>  - Folks can tap the palette select to change the color of the card. Maybe disable this if the value is toggled off

I just updated to this. I believe this is where we landed @mattkrick cc @tianrunhe 

Unlike the other values that have a char max of 2, these are simple booleans but folks can change the color

**Comment by mattkrick** [comment]
lgtm!
question card value = 2^31 - 1
pass card value = -1
