### ISSUE TITLE
Architect new User Presence

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4060]
User Presence is a hugely importance piece to our app.
- It's the logic that shows your avatar in the meeting when you're online
- it prevents you from getting a notification that someone created a task for you when you're in the meeting with them
- it's how we know you've been active in the app & we shouldn't put your account on pause

Today, we handle user presence by storing 3 fields on the `User` object in RethinkDB: `connectedSockets, lastSeenAt, lastSeenAtURL`. When a user connects, a socketId is added to the `connectedSockets` array. When they disconnect, that socketId is removed. As a user moves throughout the app, `lastSeenAt, lastSeenAtURL` is updated.

This strategy is bad for the following reasons:
- Storing these fields in RethinkDB means the User object is constantly changing & busting the cache. This is inefficient
- `lastSeenAtURL` is a single value, which means if the user has 2 tabs open, it is last-write-wins. This means if tab A is in the meeting & tab B is on the dashboard, the user will appear to not be in the meeting because tab B set `lastSeenAtURL` to the dashboard
- It doesn't scale horizontally. When we have n servers & we scale down due to a crash or a deployment of a new version, we'll want the connectedSockets array to be updated. For example, when 1 server deploys the newest version, it will have to restart & kick off all connected clients. Those clients will automatically reconnect to a new server, but how do we modify the connectedSockets array?

A good solution will have the following characteristics.

- [ ] When a user has multiple tabs open & 1 is the meeting, it looks like they are in that meeting
- [ ] The `User` document in RethinkDB does not contain lastSeenAtURL or connectedSockets (lastSeenAt is probably still necessary to determine if a user is inactive)
- [ ] An eviction policy is created to guarantee that server downscaling does not leave some users marked as online. 
- [ ] When a user logs in, we can cheaply notify all team members that they are now online

Possible solutions for some inspiration:
- Today, we cache the User object in redis. maybe before each cache we add in these fields?
- Maybe we have a UserPresence key/value lookup in redis that just keeps these fields?
- Maybe redis stores a list of userIds that are connected to a particular node. When that node goes does, we can loop over each userId & remove that socketId from their connectedSockets list?
- Maybe we just use a TTL on a UserPresence record in redis that gets reset every time the client replies to the server ping? (would that be too expensive?)
- Maybe each team has an array of online userIds? See #3259

Acceptance Criteria:
- [ ] A plan with a path forward on what to build & the pros/cons of the choices made

Estimate: 20 hours

**Comment by jordanh** [comment]
Groomed

**Comment by nickoferrall** [comment]
Hey @mattkrick, following on from our chat yesterday, I've written up a plan for user presence: https://www.notion.so/parabol/User-Presence-Plan-06a83b81ff1048ec870179a7f210d9cf

Let me know if there's anything you'd like added / edited

**Comment by mattkrick** [comment]
LGTM!

**Comment by jordanh** [comment]
@nickoferrall love that doc you wrote. I could have commented in it, but I figured I'd comment here so these comments may be (eventually) tied to AC on an issue.

Could you add definitions for the lifecycle events in #3259? What functions would we run on application startup and shutdown and what would they do? Are there other application lifecycle events we need to consider?

**Comment by jordanh** [comment]
@mattkrick how would you like to handle the issue accounting here? I.e. when would we close this issue? Should the AC of #3259 be updated or shall we close this issue and #3259 in favor of a new issue @nickoferrall would write?

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/14411601) 🔒  writes:

> Hi!
> i just want to tell you that, in a meeting, the list of "online people" is not working correctly. it's not showing everybody (but they joined the meeting and could correctly participate)
> 
> Thanks

**Comment by mattkrick** [comment]
This notion doc works for me.
Let's consider this done & implement this work in #4080

**Comment by nickoferrall** [comment]
Thanks @jordanh, I've updated the document following your feedback. If there's anything else you feel could/should be added, just let me know

**Comment by tianrunhe** [comment]
@nickoferrall Hey Nick can I have access to the doc? Thx!

**Comment by nickoferrall** [comment]
@tianrunhe for sure! I shared it in the Product group in Notion but perhaps you haven't been added to that one? I've just sent you an invite to the doc now
