### ISSUE TITLE
Add an anonymous poll after the first completed meeting

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4062]
Once the first meeting with 3+ attendees is complete, we could include an anonymous poll that asks attendees whether they think the meeting went better, worse or the same as their typical meetings. Similar to a twitter poll, once someone has voted, they can see the results from their teammates.

In the vast majority of cases I would expect the feedback to be positive. This would make the person that convinced their team to use Parabol feel good. Attendees that see confirmation that their colleagues also enjoyed the meeting may feel validated in their opinion and may be more likely to refer Parabol.

We could display the poll above the meeting summary.

The stats would also be useful internally. It could be a metric that we could keep track of weekly, as we create more meeting types it would be interesting to compare different feedback scores and, if the results from a poll were negative, it would be well worth interviewing those users.

**Comment by avivapinchas** [comment]
We played with a similar idea at our in-person SPA in Feb - asking a simple question to get a sense of whether folks were truly having better meetings. 

The idea we had was a prompt like "Was that meeting worth the time it took?" with a 👍 👎. We could see trends over time, and teams could get a sense of how their meetings were or weren't working. 

Why are you thinking just after the first meeting?

**Comment by nickoferrall** [comment]
Cool! I like the thumbs up, thumbs down idea. Emojis seem on brand 👌 

I think it's worth asking specifically about how their experience with Parabol went rather than the meeting because they might think Parabol was wonderful but the meeting was awful.

Just after the first meeting feels like the first meaningful opportunity to get feedback from users. 

If we polled users after every meeting, it might annoy them (although the stats would be helpful). But a one-off poll after the first meeting doesn't seem too intrusive, it'd give us helpful stats and users that vote positively and see others vote positively might feel more love for the product than if they don't get that social confirmation.

Also, I enjoy clicking on twitter charts and seeing the results! But that might just be me...

**Comment by avivapinchas** [comment]
> I think it's worth asking specifically about how their experience with Parabol went rather than the meeting because they might think Parabol was wonderful but the meeting was awful.

Asking how their meeting went with Parabol serves _our_ needs, but not really the users - they don't care about Parabol itself, just about getting their work done well. 

Since our purpose is to make meetings worth it, if we ask about the quality of the meeting itself, then it's still telling us whether we're going in the right direction or not, and it's also data that's potentially helpful to the user. 

> If we polled users after every meeting, it might annoy them
Yea I think that's the tricky bit - if we collect data we can then feedback to them, should be done consistently over time, but def agree it could start being ignored

**Comment by jordanh** [comment]
Iceboxing for now
