### ISSUE TITLE
Migrate Pull Panda to Github scheduled reminders

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4063]
Pull Panda has been acquired by Github and the pull reminders we used in Slack channel [#t_product_engineering](https://parabol.slack.com/archives/C095BSMCN) will be shutdown on 10/14/2020. We should migrate to Github in-house [scheduled reminders](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-team).

### Acceptance Criteria

- [ ]  [Scheduled reminders](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-team) is set up in [#t_product_engineering](https://parabol.slack.com/archives/C095BSMCN)

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Groomed

**Comment by tianrunhe** [comment]
Migrated to [here](https://github.com/orgs/ParabolInc/teams/parabol-product/settings/reminders/14508)
