### ISSUE TITLE
Dev server auto reloading

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4064]
## Issue - Enhancement

When devs work on server side code, some changes aren't automatically picked up with the server auto reloading to apply them. The result is you have to constantly manually restart in order to see changes. It would greatly improve productivity and DX if we could fix this.

### Acceptance Criteria (optional)
[ ] Dev can make any server side change and can see their changes automatically applied after saving. No manual reloading necessary.

- **Estimated effort:** 8hrs ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
I'd like to +1 on this, bothered me a lot too. Added to [DX Pain Points](https://www.notion.so/parabol/DX-Pain-Points-wishlist-73f3d25b10cf4a92b35dd8edf35fe7d6)

**Comment by jordanh** [comment]
Groomed

**Comment by tiffanyhan** [comment]
Paired on this today with @mattkrick.

**Current progress:**
This happens bc we "accept" changes on the children. The intended purpose of this is so that when an update occurs in a child which is an error, we can invoke a cb in order to pass over the bad update and use the old version of the module. The unintended consequence of this is that parents of the module in which we "accept" won't be notified of the change. i.e. the changes weren't being bubbled up all the way to the top.

If we comment out the module accept code in `rootSchema` and `gqlExecutor`, server HMR will work as expected. However, bad things will happen again when we save a partially complete change which is an error.

My hypothesis is maybe we move up the accept code to the highest level, so all parents will be notified but we can also swallow saves on errors. Also there is no particular reason we are still on webpack 4. We should look into webpack 5 and see if there is a better API exposed to do this.

**Comment by tiffanyhan** [comment]
Comment on #418 Opt-in to disable page reload when using HMR

**Comment by tiffanyhan** [comment]
hmr will work if we do two things:

1. add `'webpack/hot/poll?1000'` to `gqlExecutor` entry in webpack dev server config.
2. in `packages/server/graphql/rootSchema.ts`, comment out accepting code. we don't need to comment out code block pertaining to the `global.hmrSchema`

the server will restart if we save on a syntax error though. still need to see if it's possible to skip saving on syntax errors, but even his as-is is probably better than what we have now.

https://github.com/ParabolInc/parabol/commit/e5ced999c0a0eb9c0063d372b8293b2597a347bf

**Comment by tiffanyhan** [comment]
> Paired on this today with @mattkrick.
> 
> **Current progress:**
> This happens bc we "accept" changes on the children. The intended purpose of this is so that when an update occurs in a child which is an error, we can invoke a cb in order to pass over the bad update and use the old version of the module. The unintended consequence of this is that parents of the module in which we "accept" won't be notified of the change. i.e. the changes weren't being bubbled up all the way to the top.
> 
> If we comment out the module accept code in `rootSchema` and `gqlExecutor`, server HMR will work as expected. However, bad things will happen again when we save a partially complete change which is an error.
> 
> My hypothesis is maybe we move up the accept code to the highest level, so all parents will be notified but we can also swallow saves on errors. Also there is no particular reason we are still on webpack 4. We should look into webpack 5 and see if there is a better API exposed to do this.
