### ISSUE TITLE
Display timer when meeting has 5 mins left

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4065]
A research interviewee mentioned today that keeping meetings as short and efficient as possible is a top priority for her. Perhaps displaying a timer when there are 5 minutes left in a meeting would help nudge attendees to wrap things up?

When creating a meeting, the facilitator could optionally enter the expected length of the meeting, i.e. 60 minutes. This could be an additional dropdown below the current retro/check-in dropdowns. 

In a similar way to Zoom, when the meeting has 5 minutes left, a timer could be displayed at the top of the screen. However, unlike Zoom, nothing would happen when the timer ends. At most, we could have a dialog pop-up asking the facilitator if they would like to end the meeting or continue. We could add a tooltip to the timer to reassure users that the meeting won't automatically end.

**Comment by debuggerpk** [comment]
I think a [snackbar](https://material.io/components/snackbars#placement) would be a better attendee experience, sorta non-obtrusive.

**Comment by jordanh** [comment]
Theoretically we could do something like this when meeting scheduling is implemented (see: #4639) and we know when and what duration a meeting is supposed to be.

Iceboxing for now
