### ISSUE TITLE
Group title changes allowed during Vote phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4066]
## Issue - Enhancement

Related: #2948, #3701 

### Acceptance Criteria (optional)
Users can:
   - Allowed Group title edits during retrospective Vote phase

- **Estimated effort:** 6 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by nickoferrall** [comment]
Hey @jordanh, it looks like we already have this functionality in place. I've recorded a quick Loom video to repro the functionality just in case I'm misunderstanding anything here: https://www.loom.com/share/851aec207e7c4fbebd2e4738ebc4da05

**Comment by jordanh** [comment]
Oh wow, this really took me by surprise. I had no idea we could already edit the title. I just tried it and showed myself. Sorry for sending you down a wild goose chance, and excellent work showing that in a Loom.

Closing for now.

**Comment by jordanh** [comment]
Have a look at #3701 next, and add your 2¢ 😄
