### ISSUE TITLE
Pinned items removed from agenda

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4068]
## Issue - Bug

[A user](https://app.hubspot.com/contacts/3888472/contact/15990851) 🔒  writes via support: 

> Coming back to the bug, instead of duplicate items all my pinned items have been removed from Team Agenda. Is this a known issue?

Creating an issue to monitor if this is happening for other users. So far we have been unable to reproduce the issue.

**Comment by avivapinchas** [comment]
This happened to me just now. I closed the Persona Research retro, and found there were no more pinned items in the Growth team.

**Comment by jordanh** [comment]
Duplicate of #4352
