### ISSUE TITLE
Add additional retrospective templates - DAKI, lean coffee, starfish, what went well 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4069]
## Issue - Enhancement

We currently offer 5 retrospective templates. Our competitors sometimes offer more templates. Looking at SEO opportunities, users are directly searching for some of these templates. The opportunities look to me like: 

1. DAKI - drop, add, keep, improve
2. Lean Coffee
3. Starfish
4. What went well

### Acceptance Criteria (optional)
Users can:
   - Utilize any of these templates in a retrospective 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11132301) 🔒  mentions:

> We would like the option for a Lean coffee type of retrospective, we do this back in the office and they tend to be very productive.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/17236501/) 🔒  writes:

> Is there an option for 3 or more rounds of reflections?

**Comment by jordanh** [comment]
Removing stale from this, as new retro content is never really stale

**Comment by jordanh** [comment]
Linking issues that would be good to do around the same time: #4704, #4784, and #4703

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/19849851) 🔒  says:

> There's a lot of different methods, you could offer more templates, different techniques so those that aren't experienced have more possibilities.

**Comment by avivapinchas** [comment]
Copy draft for templates ( cc @garethaledavies for a second pair of 👀 )

**Drop Add Keep Improve (DAKI)**
- Drop: What should we no longer do? 
- Add: What should we try or adopt? 
- Keep: What should we continue doing or retain in our practice? 
- Improve: What should we evolve or revise? 

**Lean Coffee ☕  **
@jordanh 🤔 Is it worth offering this format within retros? Lean Coffee is kinda it's own _thing_, but most other retro tools include it in some way. With the linear nature of our app, I'm not sure it _works_, but here are three ways we could approach it: 

Option 1: 
- To Discuss: What should we talk about? 

Option 2: 
- To Discuss: What needs to be discussed but hasn't been talked about? 
- Discussing: What existing conversations should we pick up?

Option 3: 
- To Do: What's up next on your list? 
- Doing: What are you currently working on? 
- Done: What have you finished working on? 

**Starfish ⭐  **
- Keep Doing 🌀: What behaviors are working and adding value? 
- Less of ➖: What are we over-doing or doing too much of? 
- More of ➕: What are we not taking enough advantage of? 
- Stop ⏹️:  What isn't adding value or helping the team? 
- Start ⏯️: What new things should we explore or add to our team? 

**What went well**
- What went well 😄: What good things have happened over the sprint? 
- What didn't go well 😞 : What's happened that didn't go as planned or desired?

**Comment by jordanh** [comment]
I think Lean Coffee is worth adding for completeness, and the description text can be helpful for folks on the intent of the format. Suggesting the following copy:

*Prompt:* To Discuss
*Prompt Description:*
What shall we consider talking about? After folks give input, we'll group related items into topics and vote on them to see what to chat about

**Comment by garethaledavies** [comment]
Looks good to me. Excited about getting Lean Coffee into the product. 

I did a quick edit on the copy. 

Feel free to accept or disregard as you see fit :) 

[Edited copy](https://docs.google.com/document/d/1s2RXY4MZuPyHY73NmAyGrqO0HHo5P8Suc2AL2QTz1Yw/edit?usp=sharing)

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/22796701) 🔒  mentioned:

> As a facilitator and adding new retrospective formats, I would like more retro templates, a really nice one was the Amazon review retrospective.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/16427251) 🔒 says:

> I would like additional retro templates built by your team. We've used all the current ones many times and it would be great to have more options.
