### ISSUE TITLE
denormalized team archive state onto TeamMember

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4070]
a TeamMember object should contain enough information for us to tell if the underlying Team is archived or not.

Options:
- a `isTeamArchived` flag is set on it when the Team gets archived
- we removed everyone from the team by settings `isNotRemoved: false`
- ???

AC
- [ ] the dataLoader `teamMembersByTeamId` and `teamMembersByUserId` filter out team members that belong to archived teams & do it with only 1 DB hit
- [ ] a migration is written to update the TeamMember records 

Estimate: 4 hours

**Comment by jordanh** [comment]
Groomed. Iceboxing.

Going to relate this issue to #4629 in the hopes that it might create finer-grained AC when we move to PG.
