### ISSUE TITLE
Fix integration test DB

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4072]
The [test DB](https://github.com/ParabolInc/parabol/blob/master/packages/cypress/fixtures/rdb_test.tar.gz) we used today has a couple of issues that prevent us from properly running local integration tests:

1. The source DB ``cypress`` was outdated archived with a table ``GQLRequest`` missing. When we tried to reset the ``test`` DB it will error out.
2. Issue 1 can be mitigated today by a manual deletion however we cannot further reset the DB on each single test run 
(which should be done to create a clean state before each test run). For example, one of a recent [migration script](https://github.com/ParabolInc/parabol/blob/master/packages/server/database/migrations/20200715162900-backfillIsActiveForCreatedTeamTimelineEvent.ts) was to backfill the ``isActive`` field in ``TimelineEvent`` table. This backfill has to be run to ensure the [me.ts](https://github.com/ParabolInc/parabol/blob/master/packages/cypress/integration/me.ts) test to succeed as the expected timeline events needed to be ``active`` to be returned. Therefore if any other test resets the DB before its run, it will fail this test as a side effect.

### Acceptance Criteria
- [ ] Fix the integration test DB so that people can just switch to the ``test`` DB and run those tests without any side effects and with less preparation work.

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
See `createFixtures.ts`, we can update the tarball to latest & that should do the trick
