### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by twelvedollar** [ParabolInc/parabol#4077]
## Issue
Pulled latest master branch, redis and rethinkdb started, yarn && yarn db:migrate && yarn dev

**Error no. 1:** yarn db:migrate already throws the following errors:

`ReqlOpFailedError: Index `projectIdUpdatedAt` does not exist on table `actionDevelopment.TaskHistory` in:
r.db("actionDevelopment").table("TaskHistory").indexDrop("projectIdUpdatedAt")`

coming from 20180206135107-renameProjectToTask.js line 13.

**Error no. 2:** yarn dev

`Unknown argument 'parentTemplateId' on field 'addReflectTemplate' of type 'Mutation'.`

**Error no. 3:** yarn dev, relay does not generate graphql files ( '__ generated __' ) and therefore they can't be found, i.e.

`Module not found: Error: Can't resolve '../__generated__/useUpdatedSafeRoute_meeting.graphql'`

- **OS:** macOS Catalina 10.15.3
- **Browser:** not relevant
- **Node version:** 14.7.0
- **NPM version:** 6.14.7
- **RethinkDB version:** 2.4.0 (CLANG 11.0.0 (clang-1100.0.33.16))

Help is much appreciated.

Thank you.

**Comment by jordanh** [comment]
Hey @nickoferrall, @tianrunhe, or @tiffanyhan – if you do a fresh checkout can you reproduce the migration error as given in `Error no 1`?

**Comment by twelvedollar** [comment]
@jordanh: Tried to reproduce Error no.1 on my Windows machine and migration went fine. I'm therefore assuming this has something to do with my macOS machine (Docker, whatever). With the now latest master branch Error no. 2 is also not showing on my Windows machine so I assume this is also fixed. Issue with Relay still valid.

**Comment by nickoferrall** [comment]
For extra verification, I ran Error no.1 on my Mac and didn't get the error message either

**Comment by nickoferrall** [comment]
@jordanh while the dashboard doesn't show any errors for me, after clicking the "New meeting" button I do get an error: `Cannot return null for non-nullable field ReflectTemplate.orgId`

**Comment by tiffanyhan** [comment]
**OS:** macOS Catalina 10.15.3
**Node version:** 13.6.0
**RethinkDB version:** 2.4.0 (CLANG 11.0.3 (clang-1103.0.32.62))
**NPM version:** 6.14.5
**Yarn version:** 1.22.4
**Redis version:** 6.0.6

I can verify a fresh install works for me, but like @nickoferrall I too get the same error when starting a new meeting.

**Comment by tiffanyhan** [comment]
I also used the command `yarn && yarn dev -i`, not `yarn && yarn db:migrate && yarn dev`
