### ISSUE TITLE
Parabol’s public templates have their unique illustration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4079]
### Background
We’ve got nice illustrations for our main templates. Let’s use them!

### Acceptance Criteria
- Each of our public templates has [its unique illustration](https://www.figma.com/file/p5Ap4S9Ob5HuCtjkkLO4cM/Retro-Templates?node-id=46%3A13) (SVG). There’s a local copy of the illustration files for local and private instances, but we could consider putting them on S3.
- Ideally, the exported SVG files only include the edges of the actual art so that we can control whitespace with styles in code. Edit: we can export with a minimal, consistently sized canvas so that the file has as little whitespace as possible but is balanced. We can control whitespace responsively with code.
- New and cloned templates use the ‘custom template’ illustration. This is the illustration we’re using for all templates in the first version of shareable templates.

### Estimated Effort
- 3 hours

### Related
#4069

**Comment by jordanh** [comment]
@avivapinchas could we add this to the Freddie backlog?

**Comment by avivapinchas** [comment]
@jordanh I'm unclear on what needs to be added - we already have an illustration for each of the default public templates, which @ackernaut linked to here. Are there other illustrations that we need/want here? Or is it about the formatting of the files?

**Comment by jordanh** [comment]
j/k – we have everything we need. I'll prioritize

**Comment by ackernaut** [comment]
@mattkrick how should we handle the files? My raw ideas:
- Import the custom illustrations from static in `ReflectTemplateDetails.tsx` and use them if the `teamId = 'aGhostTeam'`
  - Is  there a performance issue for importing those SVG files?
  - We could use static if folks are on a private instance, otherwise use s3
- Or we add an image string property to the MeetingTemplate object, and add an s3 or static string to the default templates, requiring a migration. I’m not sure if that even works for a private instance, could that database have static strings on those objects? New templates get the generic image string.

Do we allow folks to add their own image in the future, whether private or hosted by us? That sounds like a very fuzzy and far-off future.

**Comment by mattkrick** [comment]
just seeing this. how you did it is perfect! use webpack where we can. as we move towards air gapped solutions we'll probably want to start leaning away from the S3 static bucket & just letting webpack do its thing. bigger webpack builds, but less mental overhead
