### ISSUE TITLE
Implement multi-connection User Presence

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4080]
This issue is to implement the work as speced in #4060

AC
- [ ] The architecture designed by #4060 is implemented
- [ ] User can join a meeting, open a 2nd tab on the dashboard & still show up as present in the meeting
- [ ] When a new version launches, the User still appears to be connected to other team members. When they log off shortly after the new version launch, they show up as offline
- [ ] autopausing users still works (lastSeenAt still lives in rethinkdb)

Estimate: 16 hours

**Comment by jordanh** [comment]
Groomed
