### ISSUE TITLE
OrganizationUser audit trail

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4081]
## Issue - Enhancement

One day, it'd be nice to have an `OrganizationUserJournal` table that is updated each time something important happens to an Org User. Today, I think this should be when a user is created, marked active, marked inactive, or removed from an organization.

Today we can create a plot from backend data of the number of active users over time:

![image](https://user-images.githubusercontent.com/103000/90575756-f7e83b00-e170-11ea-8801-e1c0a1dc2ebb.png)

What I really want to be able to do is create analyses for ourselves and our users of how their organization's activity has changed over time. Because we only store the current state, this kind of historical analysis is currently impossible.

### Acceptance Criteria (optional)
   - Migration to add `OrganizationUserAudit` table in POSTGRES
   - Row schema designed that include 'eventDate' timestamp
   - Rows added when a user is created, marked active, marked inactive, or removed from an organization

- **Estimated effort:** X hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Hey @tiffanyhan when you get a moment could you give me a swag on the number of hours you'd think this would take?

**Comment by tiffanyhan** [comment]
Oh I've done something very similar to this before. It shouldn't take long I think, I'd say 8hrs. @jordanh

**Comment by jordanh** [comment]
Will prioritize accordingly, be a good BP for a new backend programmer

**Comment by tiffanyhan** [comment]
when a new user and org is bootstrap or when an existing user creates a new org, `adjustUserCount` is not called. is this a bug? if not, need to insert audit row separately in `packages/server/graphql/mutations/helpers/createNewOrg.ts`

**Comment by tiffanyhan** [comment]
unable to test pausing unpausing. for some reason entering a test stripe cc card no longer works as it used to

**Comment by tiffanyhan** [comment]
added `pg-format` dependency, would like to test this with `pgTyped` tmrw

**Comment by tiffanyhan** [comment]
should a billing leader be able to remove a user whose account was already deleted and so was already removed? maybe need to add a check to avoid misleading audit information

**Comment by tiffanyhan** [comment]
when i delete my account, then either login or sign up with google oauth, my email in my user profile still shows as "deleted" and same thing in the org member list
