### ISSUE TITLE
Build notion integration

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4084]
Stuck on: Notion building an open API 😞 

A user writes:
> I saw that you already have an integration with GitHub which is awesome, so we could try that out and see how it goes.  The only issue is that a lot of the action items that we come up with aren't always engineering related - they're more about team process, so we didn't want to mix up the concerns between GitHub and Notion.
We could also track the progress inside of Parabol, but then that's an extra tool for the team to keep on top of.  My main intent is to use Parabol for retro meetings and then migrate the action items into a Notion board.

AC
- [ ] can integrate against notion, export tasks to a notion board

Estimate: 80 hours

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/17918401) 🔒 writes:

> I saw that you already have an integration with GitHub which is awesome, so we could try that out and see how it goes.  The only issue is that a lot of the action items that we come up with aren't always engineering related - they're more about team process, so we didn't want to mix up the concerns between GitHub and Notion.
>
> We could also track the progress inside of Parabol, but then that's an extra tool for the team to keep on top of.  My main intent is to use Parabol for retro meetings and then migrate the action items into a Notion board.
>
> Do you have plans to work with the Notion API anytime soon?

**Comment by jordanh** [comment]
Related #3554

**Comment by jordanh** [comment]
Still no open API. We did register for access tho. Iceboxing for now

**Comment by charlesmathias** [comment]
[A user](https://app.hubspot.com/live-messages/3888472/inbox/9401987373#email) 🔒 says:
> It would be awesome if you had an integration with Notion that would allow a user to populate meeting details, AI insights, and reports into a Notion database or page for wider visibility and more cohesive organization.
