### ISSUE TITLE
DB cleanup chores

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4091]
AC
- [ ] an audit is performed on the InvoiceItemHook table to ensure that every record's `userId` field points to a valid User
- [ ] an audit is performed on the OrganizationUser table to ensure that 1 user only exists per 1 orgId where removedAt is null

Estimate: 4 hours

**Comment by jordanh** [comment]
Groomed

**Comment by jordanh** [comment]
Iceboxing for now; if something similar in billing bites us again we'll know we made a bad choice
