### ISSUE TITLE
Refine public template sharing

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4099]
managing user generated content is quite possibly the hardest technical problem in the world today.
To manage public template, we have a few options:

1. Wait for a public template to get used 10 times. Only then may it appear on the list. The more often it gets used & the newer it is, the higher it ranks. (This is how it works today)
2. Human moderation. Certain users (e.g. Parabol employees) see all public templates & can approve/reject them
3. Go full blown tik-tok. send a random sampling of 20 templates to all users. let them vote them up/down. templates that get upvoted/used are more likely to appear for more users

I think the gatekeeping of option 1 kinda sucks. a template can be good without it being used 10 times.
Option 2 is just a dumbed down version of Option 3.

So, let's segment users into a couple buckets: early access & standard.
Early access:
- See content as soon as it's released (it could be ugly)
- Can flag content (inappropriate, low quality, etc.)
- Can mark content as viewable for standard

Standard
- See only content that is good
- Can flag content (inappropriate, low quality, etc). Their votes probably count for less

So, when a template gets marked as public:
- look at the publisher. do they have other good stuff? if so, let it go straight to standard. else, it needs to go to just early access
- when content gets flagged by early access, it will never be seen by standard & it appears less to other early access folks. maybe it has to get flagged a couple times.
- when content gets marked viewable (again, maybe a couple times) it'll be visible to standard folks
- when something gets flagged, the approved drops, causing it to be seen less, maybe at all
- if someone approves a template & then it gets flagged, we learn about the approver and the flagger. should this impact their weight?

**Comment by avivapinchas** [comment]
Clarifying questions: 
> Wait for a public template to get used 10 times. Only then may it appear on the list. The more often it gets used & the newer it is, the higher it ranks. (This is how it works today)
This is fully how it's implemented today? I was out last week and saw some discussion about some first few public templates, so assuming this is how it works now after latest fixes? 

>  let's segment users into a couple buckets
How do we determine who is early access and who is standard? 

> look at the publisher. do they have other good stuff?
How do we define 'other good stuff' here?

**Comment by mattkrick** [comment]
> This is fully how it's implemented today? I was out last week and saw some discussion about some first few public templates, so assuming this is how it works now after latest fixes?

correct! there was a bug that didn't filter them out properly

> How do we determine who is early access and who is standard?

to start with, only employees are early access. as we grow our list of superusers/cheerleaders, we can add them, too.

> How do we define 'other good stuff' here?

we come up with a trust score:
- how long has the account been active? 
- how many meetings have the run? 
- how many people have they invited?
- how many of those invitees haven't churned?
- are they paying?
- how many other templates of theirs have we approved?

if their trust score is good enough, we auto-accept their template. otherwise, it gets put in purgatory.

**Comment by avivapinchas** [comment]
This all makes sense to me. 

To avoid things sitting in true purgatory (which I think would feel kinda crappy for users), I'd suggest we work reviewing templates into our processes somehow - whether that's a role or a habit we build. I think we should make that explicit before we roll this out.

**Comment by jordanh** [comment]
I think a good first step would be to pull a list of all the templates folks have defined to see if there are any good ones. If there are some we think should be highlighted, we could do so manually or ask ourselves if some sort of automation is appropriate. I'll add task to raise this sometime in 2021

**Comment by mattkrick** [comment]
this needs some love, either we build forward & implement a way for mods to add templates, or we build back & simply show the ones that we offer (maybe we just keep a JSON updated?) so we don't run expensive queries to look for the gems

**Comment by avivapinchas** [comment]
How many templates have folks shared to `public`? And can we check if any of them are novel, interesting, etc? 

Might be a non-issue if there's nothing really in there

**Comment by mattkrick** [comment]
almost 300 so far, nothing earth shattering though.
i think the big question is how it makes someone feel. does it feel good to find a template by some other team that works for your team? is that validating? or would your team prefer a template made by parabol?

**Comment by jordanh** [comment]
This issue was reviewed during backlog refinement

I wonder if we could scope a smaller test before doing any full-blown design/implementation here. I was struck by this comment:

> think the big question is how it makes someone feel

I think that is the big question! Wouldn't it be grand if we could divide our userbase into two cohorts—those who can see lots of templates from other users and those who can't—and we track any behavioral differences between them? I hypothesize at a minimum we'd see more template customization out of the group who see that others are adding templates, too.

I'm going to icebox this discussion for now, but wanted to record the above thought while I had it. If there is continued tension around this, please reopen this discussion and let's continue until we come up with a clear next step
