### ISSUE TITLE
Guest invites

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4101]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/18084251) 🔒  writes:

> Hi, I am a meetup organizer who is using online retrospectives as part of my events. After trying out parabol's demo, I like it a lot! But each of my events has a random collection of people that only lives for that evening, and asking them to create a parabol account is kind of a downer (extra steps, plus privacy concerns). It would be great if I could provide them with a guest link for the meeting that just lets them type in their name and get started immediately.
 

### Acceptance Criteria (optional)
Users can:
  invite guests to a meeting without having to create an account

**Comment by jordanh** [comment]
This is a common request, not going to fulfill it any time soon. Do keep adding feedback here if you here it, tho.
