### ISSUE TITLE
Segment events to understand template sharing 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4108]
##  Issue - Enhancement

We recently launched template sharing, and would like to understand how it's being used. I propose the following: 
- On `meeting completed` event, add two attributes: `template share type` and `createdby`. This would tell us the breakdown of meetings by public, org-wide or team-private templates, and whether certain users' templates were being used by a large percent of meetings. 
- Add events for: `added template` (clicking the add button), `shared template` (changing sharing settings), `cloned template` (clicking the copy button), `edited template` and `viewed template selector`. 

### Acceptance Criteria (optional)
Parabol Pals can use the above events in Amplitude funnels and segmentation. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing per policy. If there is still tension (e.g. a reason we'd like to have this reprioritized) please reopen with rationale
