### ISSUE TITLE
Segment events to understand starting a meeting 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4109]
##  Issue - Enhancement

We currently believe there's friction in the start meeting UX, but we actually don't collect data on what folks do, so it's hard to see the drop-offs. Additionally, for certain user flows (ex: adding a new template), starting the meeting is a more important next step than completing the meeting. Lastly, adding a `start meeting` event would help us understand how users move through a meeting (is it all linear?), if they abandon meetings (start but never finish) and how long meetings take (which to be fair, can be done with `connect websocket` today). 

One thing that's tricky is there are two start meetings buttons - the first one gets you into the lobby, the second starts the actual meeting. I'm not sure how to name these so it's clear which is which. Suggestions on this welcome :) 

A rough proposal: 
- `Entered meeting lobby` - This would mean clicking the first 'start meeting' button. Properties would include `screen` (ie where were they when they clicked the button). 
- `Changed team in lobby` - This would be changing which team they were starting the meeting for 
- `Changed type in lobby` - This would be flipping through the carousel (related: #4013) 
- `Started meeting` - This would mean actually starting a meeting, either by clicking the second button or joining a meeting. This event should have most of the properties that `meeting completed` has, such as an `is facilitator` attribute (so we could see how folks who clicked vs joined) and `meetingType`. 

### Acceptance Criteria (optional)
Parabol Pals can use these events in Amplitude funnels. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is stale now, and will be iceboxed by policy. @avivapinchas what I suggest doing instead is connecting with @ackernaut to define a new and similar set of events which would allow us to gather data and insights for the meeting scheduling flow. I bet it'll be a superset of the events above
