### ISSUE TITLE
Summary Email styling is off

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4111]
## Issue - Bug

Our summary emails' styling is off: 
<img width="935" alt="Screen Shot 2020-08-27 at 10 47 26 AM" src="https://user-images.githubusercontent.com/11621016/91465162-12967000-e853-11ea-825c-29bdd8648b39.png">

I'm looking at this in Gmail, not sure how it's looking on other email clients. 

This is how it looks no matter how far back I go, so I'm thinking perhaps something changed on Gmail's side that's impacting our emails. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Enjoy well-styled email summaries :)

**Comment by ackernaut** [comment]
We still can’t reproduce. This may be a bug in Gmail. Maybe they fixed it. @avivapinchas are you still seeing this?

**Comment by avivapinchas** [comment]
Thanks for checking! I was yesterday, but am not today 🎉 Closing this out.
