### ISSUE TITLE
Robots.txt file for Parabol subdomain

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#4114]
[robots.txt](https://github.com/ParabolInc/parabol/files/5138262/robots.txt)
## Issue - Bug

The Parabol subdomain action.parabol.co currently has no robots.txt file, which means search engines do not crawl these domains. Our SEO folks have suggested we add a robots.txt file to the subdomain. 

Here's the robots.txt file for the subdomain:

```
User-agent: *
Allow: /
```

Yes, it's that simple. 

Estimated effort: 8 hrs (see CONTRIBUTING.md)

### Acceptance Criteria 

Users can:
   - Discover the sign in page directly from search engines

**Comment by ackernaut** [comment]
We want to disallow crawling invitation tokens (and we’ll look for anything else to disallow). We’re putting 8 hours for the back-and-forth review. This is low value because the robot can only crawl the login page.

**Comment by jordanh** [comment]
The AC for this need to be update a bit to resolve @ackernaut's feedback. Suggest a allow only pattern as documented here: https://stackoverflow.com/questions/7226432/robots-txt-allow-root-only-disallow-everything-else

This should be implemented by updating NGINX's config to serve up a short text string when the robots.txt URL is asked for.

List of routes we want to allow:
1) Login
2) Signup
3) All demo routes

That's it!

**Comment by mattkrick** [comment]
This will live in a `location` block in our nginx config. 
e.g.  
```
location /robots.txt {
  User-agent: *;
  Allow: /;
}
```

**Comment by jordanh** [comment]
It's a little different than 👆 

The NGINX rule should return a status, content type, and string:

```
location = /robots.txt {
   add_header Content-Type text/plain;
   return 200 "User-agent: *\nDisallow: /\n";
}
```

(from: https://stackoverflow.com/questions/7226432/robots-txt-allow-root-only-disallow-everything-else)

Note: the rules in the string need to match the AC, rather than the simple example given above

**Comment by tiffanyhan** [comment]
**Allow paths:**
>/
create-account
signin
retrospective-demo
retrospective-demo/reflect
retrospective-demo/group
retrospective-demo/vote
retrospective-demo/discuss/1
retrospective-demo-summary

[Google reference](https://developers.google.com/search/reference/robots_txt)
[For testing](https://support.google.com/webmasters/answer/6062598?hl=en)
