### ISSUE TITLE
🏁 Release tests v5.16.0

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4118]
## The basics
Run through this list at least once at [staging](https://action-staging.parabol.co):
- [x] Smoke tested the [Demo](https://action-staging.parabol.co/retrospective-demo), unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works (Team > Invite Button > Invite Link, visit URL in an incognito window)
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notifications (use `#t_product_actiontime`)
- [x] Added GitHub, verified issue created (use `ParabolInc/publictestrepo`)
- [x] Added Jira, verified issue created (use `parabol-2`)
- [x] Smoke tested the Retro meeting with 2 players
- [x] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [x] Upgraded to Pro (Credit card number: `4242 4242 4242 4242`, expiration date: any month in the future, CVC: `123`)
- [x] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)

### Added
* Show who is commenting (#4050)
* New integration test DB tarball (#4078)
* Sprint Poker meeting type in new meeting carousel behind a feature flag (#4104)

### Fixed
* Bottom bar cover and floating snackbar (#4036)
* Discussion styling thread with long URL link; Lightened up the grey "ready" checkmark in meeting control bar (#4094)
* A couple of good fixes for invitation workflow (#4082)

**Comment by tianrunhe** [comment]
Demo is breaking in mobile. Reproduction step:

1.  On mobile browser, private mode, go to https://action-staging.parabol.co/retrospective-demo
2.  Click "Start Demo"
3.  Click Next button twice
4.  See the error screen

Sentry sent us the following error:

```
FATAL
TypeError c(packages/client/hooks/useControlBarCovers)
undefined is not an object (evaluating 'o[e].el=null')
Aug. 28, 2020, 9:40:20 p.m. UTC
```

@nickoferrall I think this is yours 😂

**Comment by nickoferrall** [comment]
Ah interesting. Thanks for the repro steps. Just created a PR with a fix here: https://github.com/ParabolInc/parabol/pull/4121

**Comment by tianrunhe** [comment]
Released and closed
