### ISSUE TITLE
Direct links to integrations that we can include in emails 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4122]
##  Issue - Enhancement

As we work on onboarding emails, I'm finding myself sending folks to the marketing site to learn about key features, even after they've already been in Parabol and been running meetings. I'd rather send them directly into the product to engage with those features, but don't have the option to do that for some features. 

This specifically comes up for integrations. If we tell folks about integrations in an email, there's not a direct link we can share to add integrations to their team. 

A few ways this could work: 
- Similar to `new-meeting`, we take you to a general `new-integration` screen where you can see the integrations available to you, then pick the relevant team when you're adding one
- You first hit a page that asks 'which team?' and then go to the integrations page for that team
- Based on your activity (ie which team you're most engaged with), we assume which team you want to add an integration for, and redirect you to the integrations page for that team

### Acceptance Criteria (optional)
Users can:
   - Follow a link from an email to add an integration direct in Parabol 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Integrations are scoped to be front-and-center on the team view. We should try that solution first and then we can have this idea in our back pocket. Marking this as a discussion.

**Comment by jordanh** [comment]
Iceboxing for now
