### ISSUE TITLE
Automatic Team Provisioning via SAML

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4125]
An enterprise user had a really good idea about provisioning teams via SAML so they don't have to send an an invitation to everyone & have them all create an account.

Here's how I imagine it goes:
- In addition to an `email` attribute, the SAML payload includes `teamId` and `orgId` optional attributes. 
- these attributes are IDs that are comma separated (in case someone wants to be on more than 1 team)
- when a SAML user logs in, it checks for the presence of `teamId`. if it's there. it sees if they are a member.  if they are not, it makes them a member. Note that this means if you kick someone off a team, you'll need to also remove that attribute in okta, too (possible footgun). Alternatively, we can ignore these fields unless the user is signing up (vs logging in)
- For security, the billing leader of the teams/organizations must have a matching domain, otherwise e.g. a SAML customer could include the teamId of any random team & force their way on the team.
- if the leader wants them to be part of an org but not on a team, then they can just add `orgId`.

Acceptance Criteria:
- [ ] SAML users can add `teamId` or `orgId` attributes & joining users will get put on those teams.
Estimate: 16 hours

**Comment by mattkrick** [comment]
auto provisioning is probably going to get incorporated into another PR.

**Comment by charlesmathias** [comment]
An Enterprise [user](https://app.hubspot.com/contacts/3888472/contact/144334501/?engagement=38746053709) 🔒 requested SCIM

> SCIM is exactly what we’re after. We actually actively avoid using SaaS products that don’t have SCIM capabilities as we simply don’t have the resource to manually manage accounts.

**Comment by charlesmathias** [comment]
Relevant slack threads ([1](https://parabol.slack.com/archives/C4JAUUZ9P/p1687995473062179?thread_ts=1687969401.849149&cid=C4JAUUZ9P), [2](https://parabol.slack.com/archives/C03LL1JRFH8/p1688039477618859)) 🔒  discussing potential use cases.

**Comment by charlesmathias** [comment]
An [Enterprise System Administrator](https://parabol.slack.com/archives/C029ZTH0EL9/p1722250952099799) 🔒 said:

> They want to be able to mass add users/teams. They asked about auto-provisioning, he said it would very beneficial to the team supporting the users.

**Comment by charlesmathias** [comment]
An Enterprise [user](https://parabol.slack.com/archives/C029ZTH0EL9/p1724403478162199) 🔒 :

> They would like to get SSO set up. He has sen that we don’t have SCIM. He strongly requested that we add this as it allows him to easily manage users and teams through Okta.

**Comment by charlesmathias** [comment]
See https://github.com/ParabolInc/parabol/issues/10012#issuecomment-2304196827 from a new Enterprise account

**Comment by charlesmathias** [comment]
[An Ent user catch-up call](https://parabol.slack.com/archives/C029ZTH0EL9/p1724403478162199) 🔒:
> He has seen that we don’t have SCIM. He strongly requested that we add this as it allows him to easily manage users and teams through Okta.

**Comment by jordanh** [comment]
I wonder how many users would have access to do this? I think most of them would have to open a ticket with their IT group – and that delay would erode the value of this feature (aside from the technical hurdle of understanding team and org ids).

**Comment by charlesmathias** [comment]
[New Enterprise Org Admin wants SCIM](https://app.hubspot.com/contacts/3888472/record/0-1/89336553349)
> This year, we will be focusing on vendors that use up to date authentication and provisioning capabilities in their products.
