### ISSUE TITLE
Do not show task assignee dropdown menu if there are no options

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4129]
## Issue - Enhancement

From #4105:

> If my teammate and I are only on 1 team together, then I can’t reassign their card to another team. We should make that control disabled* unless there are options:
![92017222-0e69c700-ed19-11ea-83a5-7917bbeea98f](https://user-images.githubusercontent.com/1879975/92036129-9f926b00-ed24-11ea-887e-fd5d25b6adb8.gif)

This is the behavior today in production already and it's the same but smaller issue for user assignee (i.e., solo team)

### Acceptance Criteria
When there are no other alternative options for user/team assignee on the task card:
- [ ] The cursor doesn’t change to a pointer
- [ ] The control doesn’t have a hover state or tooltip
- [ ] Clicking does nothing

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Raising this menu causes a fetch. We don't know there aren't teams until the menu is raised. How about we give them a link to a create a new team? Something like, "no teams, go make one?"

**Comment by jordanh** [comment]
The other thing we could do is show a better zero state. Iceboxing as this came up during scrub
