### ISSUE TITLE
Real Video UI design

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4138]
## Issue - Enhancement

The existing mediasoup video implementation UI just uses the tiny avatars as video containers. 

Things I anticipate we need in real video UI v1:
- active speaker is detected and is displayed larger than others
- indication of whether a peer's mic is on or off
- optional ability to mute a peer
- revisiting which video containers to display, how many to display, which ones are overflow and not shown, etc.

### Acceptance Criteria
Deferring to Terry on AC and estimated effort.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I’ll take a card to shape the AC and effort on this one. Marking this as design.

**Comment by jordanh** [comment]
Iceboxing for now
