### ISSUE TITLE
Add Create Jira Issue to Scope Phase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4139]
Per [the scope phase designs](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2696%3A123437), we need a button that lets folks add a Jira Story directly.

AC
- [ ] there's a button that matches the designs in figma to add a new jira story
- [ ] clicking that button scrolls to the top of the list, adds a new item & then focuses it so the user is ready to type. The checkbox is checked by default to be included in the scope.
- [ ] if that story is blurred & no text exists, then the story is removed
- [ ] a mutation called `jiraCreateIssue(content: string, cloudId: string, projectKey: string, teamId: string, meetingId?: string)` is built that is very similar to `createJiraIssue`. the difference is that it does not create a Task in our system, it only creates the Issue in Jira. Instead of returning a `Task` in the payload, it returns a `JiraIssue`
- [ ] `JiraCreateIssueMutation` is built on the frontend to call `jiraCreateIssue` the returned JiraIssue is prepended to the jira issue connection so it stays at the top of the list 
- [ ] after the story is persisted successfully, `UpdatePokerScopeMutation(service: 'jira', taskId: issueKey, action: 'add')` is called to add it to the scope

Estimate: 16 hours

**Comment by ackernaut** [comment]
### Estimated effort
- 8 hours

**Comment by ackernaut** [comment]
@nickoferrall the [main view is seen here](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2696%3A123437) but I should get together the UI states (focused, editing, etc.) for you. These states will be similar to some of [the concepts seen on this page for archived iterations](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/?node-id=2846%3A3). I’ll ping you in Figma when it’s ready.

**Comment by ackernaut** [comment]
>`JiraCreateIssueMutation` is built on the frontend to call `jiraCreateIssue` the returned JiraIssue is prepended to the jira issue connection so it stays at the top of the list 

Is it worth mentioning that the new issue added appears at the top of the list despite what the current query may be? It would be possible to create an issue that doesn’t match the query and it would immediately go away which would probably feel broken. The last detail I remember discussing is that the new issue would remain until the query is updated, then would go away if it doesn’t match.

**Comment by ackernaut** [comment]
@nickoferrall I’ve got a few states here
- [Results set of Jira issues, all unselected](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2696%3A123437)
- [Empty state, no results](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=3272%3A140570)
- [Adding a new issue with placeholder](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=3272%3A141000)
- [Adding a new issue with value being typed](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=3272%3A142035)
