### ISSUE TITLE
mediasoup runs out of memory on circleCI

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4145]
mediasoup uses `nproc` to figure out how many cores it can use to make its binary.
on circleCI, that returns 36.
using 36 cores eats all the memory & the kernel barfs.

Options:
- reduce the number of cores mediasoup can use. this requires a PR & means it'll still like ~5 mins just to build.
- prebuild a binary & use that somehow
- pay circleCI $$$$ for more memory

AC
- [ ] can deploy mediasoup via circleci

Estimate: 8 hours

**Comment by tiffanyhan** [comment]
Found this: https://github.com/versatica/mediasoup/issues/378, which references `MEDIASOUP_WORKER_BIN`.

> If the "MEDIASOUP_WORKER_BIN" environment variable is set, mediasoup will use the it as mediasoup-worker binary:

```bash
$ MEDIASOUP_WORKER_BIN="/home/xxx/src/foo/mediasoup-worker" node myapp.js
```

**Comment by mattkrick** [comment]
that definitely works! we could keep that binary in a github repo & just pull it when needed.
we'll just have to update it when we update mediasoup, node, or the linux architecture.

as a cheap first pass i just set a max cores & surprisingly it built super fast!
https://app.circleci.com/pipelines/github/ParabolInc/parabol/729/workflows/6e6384a6-3c25-44bf-9ff1-d1452df411c3/jobs/9610

**Comment by tiffanyhan** [comment]
ooh sweet, glad i know about `MAX_CORES` now!

**Comment by mattkrick** [comment]
can track here: https://github.com/versatica/mediasoup/pull/462

**Comment by mattkrick** [comment]
closing since this is fixed by using a forked version of mediasoup
