### ISSUE TITLE
Error running on MacOS

### ISSUE THREAD

**Issue by filipeteotonio** [ParabolInc/parabol#4148]
I'm running Parabol locally and everything builds and works just fine except that when opening the browser, I can't see anything due to this error in console: 

`Uncaught SyntaxError: Unexpected token '<'`

OS: MacOS Catalina 10.15.3
Browsers: Brave, Mozilla
Npm: 6.4.1
Yarn: 1.22.5
Node: v13.6.0

**Comment by spyse** [comment]
What was the solution?

**Comment by JimmyLv** [comment]
@filipeteotonio Hi~ could you please help to provide the solution? thanks
