### ISSUE TITLE
Undo button for completed grouping phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4151]
## Issue - Enhancement

This issue defines AC resulting from the discussion #3701, "Allow for regrouping of cards until vote phase completed" addressing the following JTBD:

> When a user has accidentally advanced the meeting, or wishes to add new reflections, or wishes to divide or combine two groups after having advanced to the Vote phase, they want an easy way to Undo the completion state of the Group phase, so that they can adjust the meeting content to their liking

@ackernaut please let me know if this would be blocked be design, or if you think the below AC are sufficient

### Acceptance Criteria (optional)
A design for when users wish to to undo the completion status of the Retro Group phase:
   - The 'Phase Completed' badge of the Group base is updated to read 'Phase Completed Undo' for the Facilitator, where the word Undo is a clickable link
   - Undoing the phase allows the Grouping phase to continue
   - Any non-facilitator users navigated to the Vote phase are navigated backward to the Group phase

Plus:
   - Opened an implementation issue to implement the resulting design

- **Estimated effort:** 12 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
probably design blocked.
in the meantime, i can add the functionality as a cheat code so when people write in at least we can tell them to type `ididntmeanto` and then it'll work.

**Comment by jordanh** [comment]
haaaa. Love a cheat code.

Adding design

**Comment by jordanh** [comment]
Updated AC

**Comment by mattkrick** [comment]
AC for just the cheat code

- [ ] when on the compelted group phase, can type in `ididntmeanto`
- [ ] that cheat code fires a mutation called `resetMeetingToStageId(meetingId, stageId)` where the stageId is the stageId of the group stage
- [ ] on the server, that mutation verifies that the stageId is for group stageId, if not, it sends an error message
- [ ] all discussion items in the meeting are deleted
- [ ] all all discussion stages in the meeting are deleted & a placeholder stage is added (note, if the discussion phase hasn't been reached yet, there may be a placeholder stage. don't delete that). 
- [ ] all votes on all reflection groups are removed
- [ ] the `startedAt, endedAt` fields on the stages after GROUP are reset
- [ ] basically, the `Meeting` object looks identical to how it looked before the meeting was advanced from GROUP to VOTE
- [ ] as a facilitator, the group phase no longer looks completed
- [ ] as a participants, they are transported back to the group phase

@tiffanyhan this should be a fun one to get your feet wet into the inner workings of meetings. Let me know if anything gets tricky!
