### ISSUE TITLE
Update Upgrade Page to include Enterprise

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4153]
###3790 Issue - Enhancement

Right now, the conversion prompt and the upgrade page only direct users to upgrade Pro. This forces them to go onto our website, find contact details, and write in seeking information on Enterprise if they don't feel that Pro is the right option for them. In order to increase enterprise conversion and speed the sales cycle, we should simplify this process for them by having a CTA on the upgrade page that allows them to enter their details and then flows through Hubspot so that the proper rep can respond quickly.

The flow should be:

- The "Upgrade to Pro" CTA from the user avatar should change to "Upgrade Options"
- Once the conversion prompt is changed to 'Upgrade Now' no further changes on the prompt messaging will be needed for this enhancement
- From https://action.parabol.co/me/organizations Upgrade page, users should see a CTA that says 'Upgrade to Enterprise' next to the CTA for 'Upgrade to Pro'
- The CTA for Enterprise should collect their info: name, title, phone number
- Once input, they should receive a message saying "Thanks, we'll be in touch to schedule a call with you soon!"
- Their info should flow through Hubspot so that the Org & User information is connected, and either a new Deal is made and assigned via the current workflows or, if it's an existing Deal, the Deal owner is notified

### Acceptance Criteria (optional)
   - Users can request information about upgrading to Enterprise directly for the https://action.parabol.co/me/organizations Upgrade page
   - Parabol sales is notified about the inbound request and can action on it quickly

**Comment by mariohamann** [comment]
Just a small draft for the main flow:

![upgrade](https://user-images.githubusercontent.com/26542182/94804152-a3c8ab80-03ea-11eb-89e3-642216be39ae.gif)


I tried different icons for the link to upgrade page and am not sure about my final choice.
![image](https://user-images.githubusercontent.com/26542182/94804383-04f07f00-03eb-11eb-976c-4377f892458b.jpeg)

For the "Upgrade" page, I've build a second CTA, rewrote the buttons a bit, and took the quote outside.
- The first blue color of the "enterprise"-CTA is taken from https://www.parabol.co/pricing with a little gradient to the blue of the "Upgrade" link.
- The gradient needs a bit refining, but it could work.
- The quote isn't ideal as well – I decided to align the quote itself centered, but the image and name/position tend to be aligned to the left. But it could work for a first draft. :) (Furthermore the contrasts now aren't that great for a11y...) 

![image](https://user-images.githubusercontent.com/26542182/94804635-6fa1ba80-03eb-11eb-964a-e7397fbd1ff8.jpeg)

You can find all properties in the Figma file: https://www.figma.com/file/HUK40kRWuGgVcPUrmNsyGC/Parabol-Drafts?node-id=5%3A197

**Comment by ackernaut** [comment]
I like the general direction here @mariohamann — would the tier columns stack to a single column for mobile?

**Comment by mattkrick** [comment]
fresh! @mariohamann i really like this, we've been kicking around the idea of getting Enterprise into the app, i think this is a great start

**Comment by mariohamann** [comment]
> would the tier columns stack to a single column for mobile?

Definitely. :)

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.

I am _sure_ we'll get back to this when we turn our focus in the direction to #4251 a little bit down the line
