### ISSUE TITLE
Summary topics out of order

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4157]
## Issue - Bug

[A user](https://app.hubspot.com/contacts/3888472/contact/6576801) 🔒  writes:

> In the summary the topics are no longer sorted in ascending order (the most voted first) but just randomly.

**Comment by ackernaut** [comment]
### AC
- Triage and fix if LTE 3 hours
### EE
- 3 hours

**Comment by jordanh** [comment]
10.5 points

**Comment by jordanh** [comment]
Was fixed in #4206
