### ISSUE TITLE
Display stripe coupons as discount line on in-product invoices

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4161]
## Issue - Enhancement

We occasionally discount annual subscription fees. When we do, we like to apply these discounts as Stripe coupons. However, the current total for the invoice is not displayed correctly, causing customers to freak.

[This customer](url) 🔒  is a good example. We applied a ($3,000) coupon to their account, their total should be total is $600. This is how it shows up under the Billing section:

![image](https://user-images.githubusercontent.com/103000/93143956-cd20d200-f69d-11ea-9010-65bbef1eed6a.png)

Note how the upcoming invoice (for next year) total is correct.

Here's what the invoice looks like when you click through:

![image](https://user-images.githubusercontent.com/103000/93144048-048f7e80-f69e-11ea-97f7-833e0422f2fc.png)

However, when you click through to Stripe, note that the invoice lines are correct:

![image](https://user-images.githubusercontent.com/103000/93144113-26890100-f69e-11ea-9d81-65014dcaca8e.png)

Note how the upcoming invoice is correct:

![image](https://user-images.githubusercontent.com/103000/93144565-23dadb80-f69f-11ea-835c-f946a9d9b475.png)

### Acceptance Criteria (optional)
Users can:
   - see coupon lines are rendered correctly for current invoice, not just upcoming invoices

- **Estimated effort:** 12 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We should fix this one too

**Comment by jordanh** [comment]
Iceboxing

**Comment by nickoferrall** [comment]
Reopening as @drewhousman1010 mentioned another [customer](https://app.hubspot.com/contacts/3888472/contact/19252351) 🔒 requested this. Upgrading to a p3 as pricing inconsistencies feel more urgent than a p4 IMO
