### ISSUE TITLE
Sprint Poker v1 scoping phase implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4166]
See the output of #4016 as [seen in Figma](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2625%3A2)

### Acceptance criteria
- There’s a tab for each integration that can be added. Tapping a button kicks off the Oauth flow for the user
- We start with [a tab for adding Jira](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2625%3A2). Issues can be searched across Jira projects. New issues can be added
- [When an integration tab is added](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2696%3A123437), there’s a more menu on the tab for removing the integration
- There’s a Parabol tab where tasks can be searched, selected, and created
- The last used tab is the first tab in the view

#### Search
- The search icon has a dropdown icon. Tapping the icon set reveals search history. We store the last 5 search queries for that tab. For Jira, it includes any JQL or filters that were set. Tapping an item in the menu loads that query and the results
- The input for Jira can use JQL as the default, or a simple search string
- The input component is of the search type and has an icon control `X` to clear
- The default state uses a broad JQL query like `order by lastViewed DESC` and its results
- The single filter menu exposes the filters that are available:
  - Search and select Jira projects (TBD: all projects are selected by default?)
  - The projects section shows the top 5 projects or more can be searched and loaded
  - Type (e.g. tasks, stories, bug, etc.)
  - Use JQL (selected by default)
- Parabol tasks are scoped to the team. They can be searched using a simple query string. TBD: the filter menu could include status (e.g. active, done, etc.) and maybe a flag for if it has an owner

#### Selecting results & left navigation
- Each item can be selected
- Multiple can be selected
- There’s a ‘select all’ control
- The items are added to the left nav
- They must be removed from the left nav
- They can be sorted in the left nav
- TBD: ‘Add a Story’ in the left nav, it could take the user back to the first tab of scoping, or it could add an item inline assuming the last-used tab, or it could open a dialog for editing the issue (see below)

#### Creating a new issue
- The issue is added to the source of the tab (e.g. a new Jira issue, a new Parabol task, etc.)
- When the new issue is added it is automatically selected to be included in the estimation and it shows in the results regardless of the query that was present when it was added. If they query changes then the new issue may go away if it doesn’t match
- TBD: add the new item inline with the results or in some sort of dialog

**Comment by jordanh** [comment]
@mattkrick could you have a look at this one and link existing issues to make certain all the AC are covered as spec'd?

**Comment by jordanh** [comment]
(and close this if we've got this issue fully covered)

**Comment by mattkrick** [comment]
all accounted for!
