### ISSUE TITLE
Send UTMs with `loaded a page` in Amplitude 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4167]
## Issue - Enhancement

For email campaigns, we want to know how users behave once they come to our site.
- If we send a user an email campaign about a new feature, do they then come and use that feature? 
- If we send a re-engagement campaign, and a user clicks through and comes to our product, do they then run a meeting, check the Timeline, or just disappear? 

### Acceptance Criteria (optional)
Parabol team can:
   - Segment by UTM_source, UTM_medium and UTM_campaign for the `loaded a page` event 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Just scrubbed this one. I don't want to close this one yet without understanding the need.

@avivapinchas clarifying question:

If somebody clicks a link like https://action.parabol.co/some/route?utm_source=email..., how would you like the `Loaded a Page` event structured?

**Comment by avivapinchas** [comment]
This looks to me like it's already happening, actually. IIRC, at some point these weren't coming through or there was some issue, but checking now, this seems to be working correctly. Closing for now, and will log new issues if I encounter them.
