### ISSUE TITLE
Put new users from same company on same organization by default

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4170]
Today, when you join Parabol we give you a new organization.
To help out sales, it may be beneficial to instead put you on the organization that already exists.
This has some security ramifications (ie we'll need to verify your email).
The benefit is it's easier for them to get the big picture of who's on their org

AC
- [ ] New users on existing org by default

Estimate: 8 hours

**Comment by mattkrick** [comment]
I think the current plan is:
- company hits PQL status
- sales manually forces email verification
- as verifications complete, they get moved to a company-wide org

@jordanh

**Comment by jordanh** [comment]
aka – "good things happen when we get together in person"

Yes, this is now the plan. A super, duper elegant solution IMO

**Comment by jordanh** [comment]
^ just scrubbed. Replaced with #4805
