### ISSUE TITLE
Deleted prompts in retro template are still shown after refresh and cannot be deleted again

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4171]
## Issue - Bug

To reproduce:

1.  Start a new meeting
2.  Select retrospective meeting and click the retro template dropdown
3.  Create a new template and see a "New Prompt" is already created
4.  Add another prompt, "New prompt #2"
5.  Delete "New prompt #2" and see it's gone
6.  Now refresh the page
7.  Go to Retro Meeting and click the template dropdown again
8.  See the "New prompt #2" shows up again in the "\* New Template"
9.  Try to delete that prompt again and it won't disappear

![](https://user-images.githubusercontent.com/1879975/93392250-531b5500-f825-11ea-9dbb-e6259d827a0b.gif)

### Acceptance Criteria (optional)

Users can:

*   [ ] create and delete prompt at will

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
I think [this line of code](https://github.com/ParabolInc/parabol/blob/master/packages/server/dataloader/foreignLoaderMakers.ts#L103) is causing the issue. @mattkrick Why did you comment that line?

**Comment by mattkrick** [comment]
reason for comment:
1. hold a meeting
2. delete that template
3. view the completed meeting from the timeline

to keep things simple, we should probably filter at the template list level instead of the dataloader level
