### ISSUE TITLE
Stand up sfu microservice in production

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4174]
## Issue - Enhancement

Currently on local, mediasoup runs in a forked child process. On dev and staging, mediasoup should run in its own container on the same host as the web container. On production, mediasoup should be deployed in its own container in a standalone server. 

- provision a new digital ocean droplet for prod mediasoup use
- update CI so that prod deployment deploys mediasoup to this server; dokku may or may not be used.
- deployment should be zero-downtime.
- on production, client should call out to the microservice host and communicate with it for all media needs
- mediasoup workers should use all cores in machine, and should not overwhelm server resources
- mediasoup instance should be linked and able to be monitored in datadog, sentry, etc.
- create limit constants for video calls e.g. duration of call, no. of users.
- create plan for scaling
- create plan for managing state while scaling. load balancer with consistent hashing based on room id? currently mediasoup server is stateful and we assume all peers in a call will be routed to the same server and worker (sticky session).
  - massive video calls may be out of scope, but `PipeTransport` in mediasoup can be used to link multiple workers (may be across different hosts too) for a single room.

Optional:
- set up a way to load test the mediasoup server in production

### Acceptance Criteria (optional)
Users can:
   - start a video call with 2+ users on production within the Parabol app

- **Estimated effort:** 30 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
