### ISSUE TITLE
Can’t archive meeting of archived team

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4178]
### Steps
- Create a test team
- Run two retros, start to finish
- On the timeline, archive one of the retros, it works
- Archive the test team
- On the timeline, try archiving the other retro, it doesn’t work

### Acceptance criteria
- Users can archive a meeting on the timeline when the team has already been archived

### Estimated effort
- 4 hours

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/18998251) 🔒  was not able to archive meetings on their timeline after archiving a team.

**Comment by jordanh** [comment]
Iceboxing for now. Will reopen if we get another report
