### ISSUE TITLE
Update billing flow to allow us to improve understanding of conversion

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4180]
## Issue - Enhancement

When users want to purchase our software, the flow is: 
1. Go to `/me/organizations`, select 'upgrade to Pro' 
2. Taken to `/me/organizations/[uniqueID]/`, on the billing tab
3. Hit 'upgrade now' 
4. Enter Credit card details, and hit 'upgrade' 

On `/me/organizations/[uniqueID]/` and hits the 'members' tab, then comes back, then the billing tab URL is `/me/organizations/[uniqueID]/billing`

This presents a few challenges: 
- We don't have a way to see how many folks view the billing tab in total - idealy it would have a unique and consistent URL 
- We don't send an event when they click 'upgrade' on `/me/organizations` or `/me/organizations/[uniqueID]/`, so we don't know how many folks saw the modal 

### Acceptance Criteria (optional)
Parabol team can: 
   - Run a funnel in Amplitude showing *Viewed Organizations > Clicked Upgrade > Viewed Billing > Viewed Modal > Upgraded* to understand where drop-offs happen in the conversion funnel and where to optimize 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now. What'd I'd like to do is re-open this one when we implement the manual mutation to require all users for a company domain to verify their email and consolidate into a single org. We'll be in this code area at that time and it'll be great to start getting a baseline for these data when we prioritize organic conversions down the road
