### ISSUE TITLE
Support both per-user and bucketed pricing 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4183]
### Issue - Enhancement

We are considering offering a different pricing model. To do that, our upgrade mechanism needs to support that new model. 

### Acceptance Criteria (optional)
- Users can click through an email to go to `/me/organizations` and see pricing _either_ per user or bucketed (X for Y users, A for B users, Z per user after) based on either a feature flag and/or some parameter on the link clicked
- All users for a given organization see the same pricing model offered 
- After upgrading, users are charged accurately based on the pricing they originally saw
- In Hubspot (Contact or Company property?) and Amplitude (page event, UTM parameter or upgrade event parameter), Parabol team can see what pricing a user was offered to compare results and communicate correctly with users afterwards 
- Users can download accurate invoices that make sense 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
It’d be cool if folks saw a variant of the pricing page for a consistent experience (A - existing pricing, B - new buckets). However, it sounds like a tall order to have a flag follow a user from the first marketing experience through creating an account and upgrading.

**Comment by avivapinchas** [comment]
Agreed on that! Hubspot does let you personalize content on pages based on contact properties, so if we set a Hubspot contact property, I _think_ we should be able to do that.

**Comment by jordanh** [comment]
Iceboxing for now. I bet my shiniest penny this one is going to come back around 😉
