### ISSUE TITLE
Lowercase the domain for SSO Emails

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4191]
AC
- [ ] everything SSO related should normalize the user-defined domain as lowercase
- [ ] can log in with SSO when my domain is HaCkErCaSe.CoM

Estimate: 4 hours

**Comment by jordanh** [comment]
Reported by [this customer](https://app.hubspot.com/contacts/3888472/company/1696726269/) 🔒 . Affect is users who have a habit of typing their email domain with capitalization (Jane.Doe@Compamy.Com) will not be able to log in
