### ISSUE TITLE
Poker: Scope: Parabol: Add Search functionality

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4199]
### AC
- [ ] by default, on the parabol tab the most recent 50 issues with status "active" are listed in descending order by "updatedAt"
- [ ] when scrolling to the bottom, another 50 load
- [ ] if a search input is applied, a list of issues is returned where their contents includes the input query (probably augment the tasks query in the server to accept a searchQuery param)
- [ ] clicking the checkbox next to an issue calls `UpdatePokerScopeMutation`
- [ ] if issue FOO is checked & then another search query is run that returns issue FOO, it still looks checked
### Notes
- Here’s [the most recent Figma board](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2648%3A1335) including WIPs for tabbed list design, editing states, empty states

**Comment by ackernaut** [comment]
Added [a link to Figma](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2648%3A1335)

**Comment by tiffanyhan** [comment]
@mattkrick @ackernaut in reviewing the Figma board, I see differences between what's on the board and what's in the AC for the relevant issues.

Being conscious of v1 vs beyond, is the following in scope for this issue and #4197, or should new issues be written for them?
- [ ] parabol task list item has to its right an "export" button to push it to an integration
- [ ] parabol search bar has a clickable dropdown menu of persisted (server side or client side?) past searches
- [ ] parabol scoping area has to its bottom right hand corner a "new task" button to allow creating a new task
- [ ] JQL-like search syntax is supported for searching parabol tasks

Here's a loom to show the behavior so far from just following the issue AC: https://www.loom.com/share/373ef5d767ec44d995fdc3ca14375fff

**Comment by ackernaut** [comment]
@tiffanyhan nice! I like the status filter menu.

- I don’t think we’re going to support the export to integration in this context just yet. We’ve promoted a primary action of creating a new integrated issue on the Jira tab and I think we learn first. It may become a target, secondary affordance later.
- @mattkrick implemented the persisted search history for Jira. I imagine we’ll do that here, too, maybe just as its own implementation issue?
- Yes, the new Parabol task button is in scope for v1, maybe as a new implementation issue
- For v1, the search is probably a basic text string on top of the status filter you implemented

@mattkrick can check my thinking. And nice work so far! 👏

**Comment by ackernaut** [comment]
I’m writing an issue for adding a new Parabol task. @tiffanyhan if you think the persisted search history menu is out of scope for this issue let me know and I’ll write an issue for that.

**Comment by mattkrick** [comment]
this is just so gosh darn great!
- no export button (for now)
- persisted searches is out of scope, i can't imagine folks have _that_ many parabol cards (i think we can just remove the down arrow next to the search icon for now)
- agreed, "new task" button should land in v1, but not in this PR. #4269
- tbh i hope we never have to invent our own query language. we could do regex, but that opens us up to some nasty security issues (an expensive regex can crash a server) so i say we just do basic search for now

**Comment by tiffanyhan** [comment]
sweet thanks both of you for the clarification!

 fwiw, I think persisted search queries makes more sense if something is in JQL and you don't wanna memorize the syntax. for parabol task searches with plain text... not so much. 

totally agree on not wanting to support our own query language.

i just realized the state with no filters chosen returns "done" tasks too which shouldn't be the case, so i'll fix that before opening a PR today.

**Comment by ackernaut** [comment]
>fwiw, I think persisted search queries makes more sense if something is in JQL and you don't wanna memorize the syntax.

**+1** that was probably the original tension

>i just realized the state with no filters chosen returns "done" tasks too which shouldn't be the case

**+1** good  👁️   for detail
