### ISSUE TITLE
Removing a template doesn't automatically update for teammates

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4202]
If a user removes a retro template that is shared in an organization, their teammates will still see the template until they refresh the page. Retro templates that are shared in a team (and not org wide) automatically update for teammates when they're removed.

### Steps

- Open two windows with two different users in the same organization
- Create two teams in that organization
- User 1 in Team 1 creates a retro template and shares it with the organization
- User 2 in Team 2 can view the retro template under the Organization section
- User 1 removes the template and User 2 will not see an update. When User 2 refreshes the page, they will see that the template is removed from the org

### Acceptance criteria

- [ ] Remove a template that is shared with an org. Teammates should see that the template has been removed without needing to refresh the page

**Comment by jordanh** [comment]
Scrubbed. Likely still broken. Iceboxing for now
