### ISSUE TITLE
Retro template flickering

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4203]
Retro template flickers if User 1 opens the Public section of the retro templates and User 2 creates a new one.

### Steps
- Open two windows with two users 
- User 1 opens the retro template menu and clicks on the Public section
- User 2 starts to create a new meeting template. Both users will now see the flickering/jumping

https://www.loom.com/share/b805d19f4d2d4d6f98d2fa369751f465

### AC

- [ ] User 1 opens the retro template menu and goes to the Public section. User 2 creates a new retro template and without either user experiencing the flickering

**Comment by mariohamann** [comment]
I think I had a similiar or the same bug yesterday.

![Screen Recording 2020-09-30 at 12 12 43](https://user-images.githubusercontent.com/26542182/94799301-336a5c00-03e3-11eb-9e04-d27bd044587b.gif)

**Comment by tianrunhe** [comment]
This has been fixed.
