### ISSUE TITLE
Active Team Count is incorrect in Parabol Hubspot App

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4209]
In connection to Issue #4086   - Bug

Company Active Team count is inaccurate in Hubspot via the Parabol App. This is a known issue, am documenting for future improvement. The issue causes the following inefficiencies on the sales & marketing side:

1. Leads cannot be scored according to whether or not they are over our current threshold and by how much (2 active teams on Personal Plan)

2. Accounts with more than one domain will show a large discrepancy between the App and Colab because the App will display all teams ever created by that domain - not including the related teams under associated domains (see attached screenshots)

3. Automated emails cannot dynamically pull the 'active teams' property into email templates because even when manually updated, the API refreshes it with incorrect data

4. Automated emails from sales & marketing cannot be built to target accounts that are over our Personal Plan thresholds

Potential solutions:
-Rename the field to 'Total Teams' for the time being
-Create a field in Hubspot for 'Active Teams' that is manually entered by the user and can be dynamically pulled into templates and used for reporting
-Have this field at least only pull teams which have actually met, not all ever created (this will get us closer to ascertaining utilization than the current data)

### Acceptance Criteria 
Until Fixed, users can:
   - Manually record an account's active teams in a way that is not automatically updated by the API
 
Once Fixed, users can:
  - Receive leads which are accurately scored according to how far an account is over threshold
  - Build automated email campaigns which incorporate the amount of active teams as a dynamic field
  - Build automated email campaigns and workflows around the amount of active teams an account has

**Comment by shawneeatparabol** [comment]
As you can see in these images, the following data discrepancies exist (🔐[client](https://app.hubspot.com/contacts/3888472/company/943862052) has multiple domains):
-P App reports 11 'Active Teams'
-Colab shows 13 Total Teams, of which only 7 have ever actually met and only 3 of which are 'active'.

<img width="230" alt="Active Team Shot Client 2" src="https://user-images.githubusercontent.com/65249741/94622435-eb660080-024d-11eb-862a-51d4cb122698.png">
<img width="354" alt="Client 2 Parabol App Shot" src="https://user-images.githubusercontent.com/65249741/94622440-ec972d80-024d-11eb-90ad-47b662468b9f.png">

**Comment by jordanh** [comment]
I don't think this is still true. Iceboxing for now
