### ISSUE TITLE
Hubspot Parabol App - Active User discrepancy

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4210]
## Issue - Bug

Related to issue #4209 

Ticket with video showing issue is [here](https://app.hubspot.com/contacts/3888472/ticket/236081505/)

Active User counts in the Parabol App, which are being used to calculate deal score, are showing discrepancies on accounts with more than one domain. This causes deals that should be marked as high value to come through as 0s - 2s. 

This is an issue for sales and marketing because it keeps our reporting from being able to identify to hottest leads. It also keeps us from being able to reference a current account's active use via dynamic fields in email sequences (because, while we can manually edit this field, it repopulates with the incorrect info with each API push).

This data is usually incorrect for single-domain accounts as well but only by a couple of users (I believe it's possible the API just isn't refreshing immediately). Examples included below.

- **Estimated effort: Unknown 

### Acceptance Criteria 
Users can:
   - See the same 'active users' and 'total users' as shown in Colab
   - Use the amount of active users to qualify deals, directly from Hubspot
   - Manually override the API push and enter the correct data in themselves, until fixed

**Comment by shawneeatparabol** [comment]
This is from an🔐[account](https://app.hubspot.com/contacts/3888472/company/1619560736/) with multiple domains

<img width="424" alt="K client active users 2" src="https://user-images.githubusercontent.com/65249741/94625822-67b01200-0255-11eb-87bb-8d3226bb6739.png">
<img width="315" alt="K client active users 1" src="https://user-images.githubusercontent.com/65249741/94625824-68e13f00-0255-11eb-88c6-f02dfdff4189.png">

**Comment by shawneeatparabol** [comment]
This is from an [account](https://app.hubspot.com/contacts/3888472/company/943862052) that came through today with a lead score of 2. You will notice AU discrepancies across all three platforms: Slack, Hubspot and Org & Domain Stats

<img width="594" alt="Screen Shot 2020-09-29 at 1 35 04 PM" src="https://user-images.githubusercontent.com/65249741/94627301-d6db3580-0258-11eb-9ee1-7d2ccb498e79.png">


<img width="348" alt="Screen Shot 2020-09-29 at 1 24 35 PM" src="https://user-images.githubusercontent.com/65249741/94627043-3422b700-0258-11eb-8e5b-c94a64d5d812.png">
<img width="507" alt="Screen Shot 2020-09-29 at 1 31 40 PM" src="https://user-images.githubusercontent.com/65249741/94627046-36851100-0258-11eb-8642-1effee11b833.png">

**Comment by jordanh** [comment]
This might not be a bug, it might relate to how we count AU in domain stats vs. in HubSpot.

@shawneeatparabol if you look at domain stats for the org with this discrepancy, do they...
* ...have more than one org?
* ...have more than one email domain that is common among their users?

**Comment by shawneeatparabol** [comment]
Yes, the discrepancy I'm reporting is primarily on accounts with more than one domain and more than one org (i.e. Enterprise accounts). 

In 🔐[the example above](https://app.hubspot.com/contacts/3888472/company/943862052), all active use is under orgs run by users with the same domain. All users within those orgs are also in the same domain (minus approx 5). Pulling the CSV file, the spreadsheet indicates 23 Active Users for the domain in question (the one listed on the account in Hubspot). So that's a 4th value for Active Users: 25 on Slack, 27 in Hubspot, 47 in Org & Domain Stats, and now 23 AU according to Org & Domain Stats for that specific domain. 

I know that the way our data works today, we can only associate one domain per account. This causes the field to be inaccurate and not one that conclusive reports can be run across. Per Aviva's request, I'm documenting the details of the issue to raise awareness and so that it can be addressed with a manual work-around until we have that capability. 

The discrepancies still occasionally exist on single domain accounts but they are usually only off by a few users and that can probably be explain by data simply not being pushed through the API in real time.

**Comment by jordanh** [comment]
Ok, this is super helpful. Thank you!

**Comment by jordanh** [comment]
One clarification: the HubSpot "Active Users" property _will_ count users where their email domain does not match the HubSpot Company record domain (for example @gmail.com addresses will be counted with @company.com addresses) but _only_ if the @company.com domain emails account for more than 50% of the Parabol Organization. "Domain Stats" does not do this, it counts every user even if only 1 user matches the @company.com domain

I _think_ this discrepancy is working how we designed. I'm particularly interested to see if data isn't being updated or there is a bug in how we're reporting the data. If you see something that looks like that, please tack that info on here

**Comment by jordanh** [comment]
Scrubbed. Making this a discussion to track. No clear acceptance criteria to prioritize yet

**Comment by shawneeatparabol** [comment]
Video in [ticket](https://app.hubspot.com/contacts/3888472/ticket/236128885/) of another🔐 [account](https://app.hubspot.com/contacts/3888472/company/3274086212) with an inexplicable user discrepancy. Hubspot dropped AU down to 39 when in truth it's been over 60.(all same domain, multiple orgs)

**Comment by jordanh** [comment]
This is probably fixed!
