### ISSUE TITLE
Wrong height of (tab) buttons and divs Safari

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4211]
## Bug
- **OS:** macOS
- **Browser:** Safari Version 14.0 (15610.1.28.1.9, 15610)
- **Estimated effort:** 11 points ([see CONTRIBUTING.md]

## Description

There are some wrong heights of (tab) buttons and divs Safari. Maybe it has something to do with providing only `line-height` and not `height`. Or it could have something to do with https://stackoverflow.com/questions/11726442/font-rendering-line-height-issue-on-mac-pc-outside-of-element as well, but as it's the problem in Safari and Chrome, I don't think so. (By the way: Font not installed locally.)

![Screen Shot 2020-09-30 at 10 56 24](https://user-images.githubusercontent.com/26542182/94665787-e451f780-030c-11eb-954a-ddd99a54c362.jpg)

## Edit
Problem could be solved by setting `flex-shrink: 0` to the affected elements.

**Comment by ackernaut** [comment]
Thanks for pointing this out. I’m seeing this in Safari as well. I’ll add it to our backlog.

**Comment by mariohamann** [comment]
@ackernaut – you reopened, did you encounter problems? It works for me with the current master incl. PR https://github.com/ParabolInc/parabol/pull/4254. 

![image](https://user-images.githubusercontent.com/26542182/95822750-cc2aa100-0d2c-11eb-9ec0-7b5893542239.jpeg)

**Comment by ackernaut** [comment]
Oops, I thought it was closed simply because it was mentioned, thanks for fixing, I see the fixes now.
