### ISSUE TITLE
"New meeting": Direction of team selector

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4212]
## Usability Enhancement

It feels a bit strange, that the selector appears above the "button", although the arrow points down. The button looks like a "drop-DOWN" selector, but it isn't. :)

![Screen Shot 2020-09-30 at 10 48 54](https://user-images.githubusercontent.com/26542182/94666777-33e4f300-030e-11eb-85d2-dcabaeb3d675.jpg)

I think the selector should be below the button.

**Estimated effort: 11 points**

**Comment by ackernaut** [comment]
Noted in #4244 — Thanks!
