### ISSUE TITLE
"New Meeting": Labels for selectors/buttons

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4213]
## Usability Enhancement

After creating a "new meeting" for the first time, I would have loved to be guided better, e. g. by labels above the buttons.

![image](https://user-images.githubusercontent.com/26542182/94668533-760f3400-0310-11eb-8e5b-49b0fd6c1234.jpeg)

- **Estimated effort:** 11 points

**Comment by ackernaut** [comment]
Noted in #4244 — Thanks!
