### ISSUE TITLE
"New Meeting": Change icon for Template selector

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4214]
## Usability Enhancement
After the team selector felt a bit strange (see https://github.com/ParabolInc/parabol/issues/4212) I was very surprised, that the template selector has nothing to do with a dropdown – although the chevron usually indicates it. I never expected to get a modal window.

After fiddling around with some icons, i realized that they don't work in combination with the chevron above and it was way too much Icons in the button, as the "chat-icon" is already very consuming.

![image](https://user-images.githubusercontent.com/26542182/94669669-d5217880-0311-11eb-9223-cab3d7aef631.jpeg)

All in all I realized, that I didn't really expect the `question_answer`  to be the selector for `templates` as well.

Therefore I changed the `question_answer` icon to some other icons and :
- `view_list`
- `view_quilt`
- `dashboard`
- `widgets` 
- `view_carousel`

![image](https://user-images.githubusercontent.com/26542182/94670733-39910780-0313-11eb-936c-fee0f747da0a.jpeg)

Those might fit better to "templates". Of course this would profit a lot from https://github.com/ParabolInc/parabol/issues/4213.

I think my favorite is `view_carousel` (being the last icon in the image above).

- **Estimated effort:** 11 points

**Comment by ackernaut** [comment]
Noted in #4244 — Thanks!
