### ISSUE TITLE
"New meeting": Get rid of "Chevron Down"-Icons (in combination with other proposals)

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4215]
## Usability Enhancement

If you use labels (https://github.com/ParabolInc/parabol/issues/4213) I think you could get rid of the Chevrons. Combined with a new icon for the template selector (https://github.com/ParabolInc/parabol/issues/4214) this could look like this – and could solve the problem of https://github.com/ParabolInc/parabol/issues/4212 as well.

![image](https://user-images.githubusercontent.com/26542182/94671097-b58b4f80-0313-11eb-806d-fb38bc2dc169.jpeg)

PS: Maybe it's even better to use the labels "Select Team" and "Select Template"?

**Estimated effort: 12 points**

**Comment by ackernaut** [comment]
Noted in #4244 — Thanks!
