### ISSUE TITLE
"Template selector": Unexpected user flow and doubled "clone & edit template"

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4216]
## Usability Issue

When using the template selector, I was very surprised that the "Floating Action Button" is used to clone the template. After creating a new Meeting I would have definitely expected, that this is the button to select the current template for my meeting, as it is the main action at the moment. In fact, there is no indication that the template is selected – you have to close the modal by clicking in the darker area, realizing that the template already switched.

![image](https://user-images.githubusercontent.com/26542182/94673246-bffb1880-0316-11eb-8696-f958921ec96d.png)

I think it would enhance the usability by having a single FAB which selects the current template. It should match the coloring of the other buttons in the user flow.

![image](https://user-images.githubusercontent.com/26542182/94674051-e79eb080-0317-11eb-96da-bf46da6edcb8.jpeg)

- **Estimated effort:** 13 points

**Comment by ackernaut** [comment]
Agreed, there’s a case for this. Thank you. We’re looking at resolving this with #4128
