### ISSUE TITLE
"Template selector": Add lable to "clone template"

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4217]
## Usability Enhancement

I had no idea what the "duplicate" icon could say. I think it would enhance the usability to add a label to the icon. (Personally, I think it is enough to say "Clone template" instead of "Clone and edit template".

![image](https://user-images.githubusercontent.com/26542182/94674605-bbcffa80-0318-11eb-8941-036da7b6647b.jpeg)

- **Estimated effort:** 11 points

**Comment by ackernaut** [comment]
At some point, we decided that icon-only controls are okay but should have a tooltip unless there’s a good case for not having one. When controls are essential we explore options for making them more prominent. We’re looking at moving this icon see #4218 and we also want this view to better lay out responsively see #4045 (we already have [designs for this](https://www.figma.com/file/wYDUg5qQMjbEllgxBY37sT/Template-Editor-Dialogs?node-id=78%3A5032)). Closing for now, will icebox. Thanks for making the case here.
