### ISSUE TITLE
"Icebreaker": Customize text – indicate edit mode

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4218]
## Usability Enhancement

I clicked on the "customize" icon and expected something like a modal. Your current solution is even better to edit inline – but in fact I only realized that the text is selected. There was no indication that I am in edit mode.

![Screen Recording 2020-09-30 at 12 34 21](https://user-images.githubusercontent.com/26542182/94675154-942d6200-0319-11eb-8a03-fa0c12d21f6e.gif)

I think you could indicate more that you are in "edit" mode now.

![Screen Recording 2020-09-30 at 12 45 16](https://user-images.githubusercontent.com/26542182/94676033-f470d380-031a-11eb-8ff6-ef27073c82e7.gif)

- **Estimated effort:** 13 points

**Comment by mariohamann** [comment]
![Screen Recording 2020-09-30 at 12 57 10](https://user-images.githubusercontent.com/26542182/94677064-9513c300-031c-11eb-954f-dfe97f628b53.gif)

It could be nice to invert the "customize" icon.

**Comment by ackernaut** [comment]
I like the subtle background change to indicate a focused state, but would not use the circled state of the edit icon as I’m not sure we’d use that pattern consistently. I would want the box size to not change, which is simple, the background including box padding would change from transparent to the lighter color (assuming white at some low opacity).
