### ISSUE TITLE
"Icebreaker" – Change icon to edit text

### ISSUE THREAD

**Issue by mariohamann** [ParabolInc/parabol#4219]
## Usability - Enhancement

I think the "Customize" icon is a bit over the top – especially as you only can edit the text. I think a simple pen icon would fit better.

![image](https://user-images.githubusercontent.com/26542182/94676354-8082fb00-031b-11eb-8467-3119a59fdb93.jpeg)

- **Estimated effort:** 11 points

**Comment by ackernaut** [comment]
Agreed, the `edit` icon is more consistent with newer editable fields added in the product.

Would you be able to open a PR that includes this change and the change in background color for the focused state from #4218 ?
