### ISSUE TITLE
Invitation link logic updated

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4224]
### Background

We’ve had a lot of feedback and discussion around the invite links #3954 – folks want them to ‘just work’ so this is a proposed iteration hoping to make them ‘just work’ a little better.

### Acceptance criteria
For an invitation, via the mass-invite link or email link:
- If a user is a member of the team:
  - They tap on an invitation link (expired or not) and are redirected to the ‘**_best space_**’ (our assumptions and heuristics: the meeting with the most active viewers, or the single running meeting, or the team dashboard).
  - Bonus points: the invitation object holds information about what meeting it was generated in and we better know where to send them. If the meeting was ended for some reason, we can fall back to the team view.
- If a user is not a member of the team:
  - If the link is valid they are added to the team and join the best space
  - If the link is expired they are redirected to the best space
    - If they arrive at a meeting or team view and a team member is present, that team member can accept them to the team and let them in via the snackbar control
    - If nobody is present, it says the link is expired, reach out to ‘PreferredName’

Invitation duration:
- The mass-invite link duration doesn’t change. It expires in 24 hours for security reasons
- The email links are extended from 7 days to 30 days to cover folks who may do longer sprints and want to hold a sync retro at the end

Invitation dialog UI:
- We remove the UI copy that says when the links or emails expire.

### Estimated effort
- 24 hours

**Comment by shawneeatparabol** [comment]
🔐 [Customer](https://app.hubspot.com/contacts/3888472/contact/19251301/) writes:
"we have meetings, but someone always ask where the new meeting will be. Not very clear. the UI needs to help us understand. please stop designing to be "minimal" but instead be "focused and helpful"

**Comment by ackernaut** [comment]
Closed in favor of #4322, #4323, #4324, #4325, #4326, #4327
