### ISSUE TITLE
New lines on task cards

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4228]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/19502751) 🔒  describes trying to add notes to a task card with our current UI:

> I thought I couldn't because I wanted to add a comment on a new line and :
> I tried to go to new line by pressing enter (it validates the current text and go out of the task, that's fine)
> So I tried to go to new line by pressing CTRL enter (it validates the current text also)  
> So I tried to go to new line by pressing ALT enter (it validates the current text also)
> Then I gave up...
> In fact the new line is SHIFT + enter in parabol

> So may be my suggestion would be only to accept "CTRL + enter" and "ALT + enter" as "new line"

### Acceptance Criteria (optional)
Users can:
   - use alternate commands to create a new line
   - Task card formatting commands shows commands to create a new line

**Comment by jordanh** [comment]
Making this a discussion issue. Let's spool up some more feedback here before we decide we need to do anything.

I see this as a user education failing, not necessarily a UI or feature failing.

**Comment by jordanh** [comment]
Went stale, didn't get any additional reports. Will close this discussion for now
