### ISSUE TITLE
Demo task assign menu bug

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4229]
### Reproduction
- Advance to the Discuss phase of the demo
- Try changing the owner of a task in the thread. The avatar doesn’t change
- Open the assignment menu again. Notice the options in the menu changed to exclude the person you last assigned. It seems the owner was updated, but not the avatar on the card

### Acceptance criteria
- Changing the owner also updates the avatar on the demo task card

### Estimated effort
- 4 hours

**Comment by jordanh** [comment]
Still a thing (i.e. not fixed). Scrubbed. Going to ice box. Will reopen if there is tension
