### ISSUE TITLE
Task card focus and menu toggles

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4230]
### Background

Today on a task card you can tab to the calendar, integration, and status menu toggles and open those menus by pressing enter if you’re hovering the task card with the mouse. If you’re not hovering the card those toggles aren’t visible and you can’t tab to them. One nuance is that if you’re focused on the description (i.e. ‘_editing_…’) and not hovering the card with the mouse the calendar icon is visible but when you press `shift + tab` to focus on the toggle it goes away.

![2020-10-01 15 19 03](https://user-images.githubusercontent.com/307286/94859151-b72f4300-03f9-11eb-8765-c1813f678111.gif)

### Acceptance criteria
- When focusing on any inner card component all the components are visible regardless of hover state
- This focus state clears when tabbing away from the card or selecting a menu option
- Icebox this in 6 months 🤪 

### Estimated effort
- 4 hours

**Comment by jordanh** [comment]
> Icebox this in 6 months 🤪

ok.
