### ISSUE TITLE
Update link in Check-In Summary email 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4233]
##  Issue - Enhancement

Our Check-in Meeting Summary email includes a link to 'learn more' about the check-in meeting format: 
<img width="551" alt="Screen Shot 2020-10-01 at 8 20 14 PM" src="https://user-images.githubusercontent.com/11621016/94878609-86640380-0423-11eb-92b6-88e9ae8f660d.png">

Currently, this link to the Agile Teaming Beyond Tech post on Medium. As we're migrating evergreen content like this to our own blog, we should update the link to the new home of this post: https://www.parabol.co/blog/agile-management-navigate-uncertainty

### Acceptance Criteria (optional)
Users can:
   - Receive a check-in summary email with a link to the post on our blog 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Thank you @mikennaji
