### ISSUE TITLE
Pushing Story Points to Jira

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4234]
In a poker meeting, when the team agrees upon the story point estimate for an issue, we can update that value in jira a few ways:
- we can update the "story points" field (if they have one set)
- we can add a comment saying "this issue is worth X"
- we can add comment with a link saying "click here to see the story points"
- we can have different messaging for free/paid users
- paid users can customize the comment, or have no comment at all
- we can do nothing

I think this is the right place to start adding friction for free users. If a company pays for jira, they should be paying for us.
Please add your preferences on how to handle these cases here: https://docs.google.com/spreadsheets/d/1Dt7FxgtZ2bzCw3YWoU51gXDzUfMaeY24HJZVI4iLM6U/edit?usp=sharing

@avivapinchas @ackernaut

**Comment by ackernaut** [comment]
I left my 2 cents

**Comment by avivapinchas** [comment]
Same!

**Comment by jordanh** [comment]
We can close this one! We shipped!
