### ISSUE TITLE
poker: flatten dimensions into stages

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4239]
today, a meeting is broken into a series of phases.
each phase has 1 or more stages.
this makes urls predictable across meetings. e.g. /phase/stageIdx will work no matter what meeting you're in

with the poker meeting type, we have a 3rd level: each estimate stage has 1 or many dimensions.
if we treat a dimension as a child of a stage, then we sacrifice dimension-specific URLs, ie going to a specific URL will get you to the first dimension, not necessarily the dimension that the other person is on
this can also have implications for keeping everyone in the meeting at the same place. e.g. clicking "goto facilitator" will take you to the right stage, but not the specific dimension that the facilitator is on.

so, we have options:
- ignore dimension-specific routing, taking a user to the first dimension is good enough
- build support for dimensions into routing. e.g. /estimate/1/3
- flatten the hierarchy so 1 stage is 1 dimension. bringing this to a 2NF means repeated data across stages, but also means a shorter URL (/estimate/4) and no need to build out support for another level of routing. the downside is the stageIdx is going to be N dimensions larger than what users expect. for example, if i have 3 dimensions & i'm on stage 2, then the route stage will be 4, 5, or 6. i think this is probably OK.

tbh, i love flattening data when i can. it's all gonna be kept in the same database row, so there's no performance impact. it should just be easier to access & mutate

**Comment by ackernaut** [comment]
A few questions:

If dimensions are stages, can we seamlessly change views in the UI? E.g. the thread and story card don’t change and I can swipe between dimension columns, the URL changes but the context feels steady

What are our options for the left nav? Can we flatten it somehow? Does it have to be ‘Example issue title is kinda long – Estimated Story Points’ then ‘Example issue title is kinda long – Value’ then ‘Example issue title is kinda long – Effort‘

How does the timer work? What’s the most likely case? E.g. can I turn on a time box for the estimate phase ‘You have until Friday to estimate these stories’? Can I turn on a timer per story across dimensions ‘Take 2 minutes to vote on the dimensions for this story’? Do I have to set a timer per dimension?

**Comment by mattkrick** [comment]
> If dimensions are stages, can we seamlessly change views in the UI? E.g. the thread and story card don’t change and I can swipe between dimension columns, the URL changes but the context feels steady

yep, the sidebar will only show 1 stage per dimensionId. swiping a column will change the URL

> How does the timer work? What’s the most likely case? E.g. can I turn on a time box for the estimate phase ‘You have until Friday to estimate these stories’? Can I turn on a timer per story across dimensions ‘Take 2 minutes to vote on the dimensions for this story’? Do I have to set a timer per dimension?

today, timers live on the stage. i'm not sure if that's the right answer. we probably want a timer per phase or a timer per issue? then again, in a sync meeting, maybe per-dimension feels better? i just don't know & don't have a strong opinion yet. anything is still possible under this new format
