### ISSUE TITLE
Support Annual Pro upgrades in the app

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4251]
##  Issue - Enhancement

We recently [updated our pricing & discounting](https://www.notion.so/parabol/Pricing-Changes-Monthly-Discounts-Annual-Enterprise-Pricing-9ab3e4a7b96149968df46bf7d43fabc3)🔒 to allow for an Annual Pro offering. The main points of this: 
- Buying Pro on an annual basis gives the purchasers a discount over paying monthly
- An annual Pro offering does not include Enterprise features like SSO or on-prem hosting (those would be 'Enterprise' plans)

Ideally, purchasing an Annual Pro subscription would be similar to upgrading to Pro originally - users could self-serve their upgrades within the app itself. 

### Acceptance Criteria (optional)
Users can:
- Upgrade to Pro, pay annually, and enjoy a discount - the annual process would work very similar to how monthly currently works 
- See accurate annual pricing for Pro within the app 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
This may need a light design pass. Are you up to sharing a divergent napkin sketch of the billing view? I imagine two targets could be sketched:

- Next -> Pro monthly or annual
- Later -> Pro (monthly/annual) or Enterprise (contact)

Do we show both prices at the same time? How do folks select annual or monthly?

(This reminds me of #4153)

I’d be happy to make a pass at a visual concept once we can compare ideas. :)

**Comment by avivapinchas** [comment]
Lovely! Def agreed about doing a design pass. 

Looking at the current page, a couple of things stand out to me: 
- Feels weird that 'delete organization' is on the same page where we're asking for an upgrade - we should move that, maybe to the members page 
- The two-tab layout might be constricting over time - probably something for later
- Do we need to ask folks to click to upgrade, and _then_ open the CC form, or could that just be on the page? 
- We don't mention pricing on the page at all 
- We could highlight features more / better 
- We don't take advantage of a headline on this page, to give folks an understanding of the benefit of upgrading 

In terms of the Next & Later bit - agree we should think them about them kinda at the same time. I see two main situations: 
- User is currently free, wants to upgrade their team or a few teams
- User is free or paid, wants to understand Enterprise options 

I have an assumption that in most cases, if folks want to go to Enterprise, they'll come to our site to look at pricing, so I think the _main_ use case here should be getting folks to upgrade to monthly. I also imagine we could make the page more intelligent over time, emphasizing the best plan for them based on the size of the org. 

With all that context, here's what's in my head: 
![Screen Shot 2020-10-09 at 5 06 15 PM](https://user-images.githubusercontent.com/11621016/95636004-a4e58280-0a53-11eb-9ae7-55b09313162c.png)

Made a [quick Figma board ](https://www.figma.com/file/EW46XxO8Ge76W4JzVo6agS/Billing-Page-in-App?node-id=0%3A1) 🔒  to track this, including some inspiration from other SaaS tools. 

> Do we show both prices at the same time?

I think so, highlighting the discount for annual and showing that as the preferred choice. 

Since Enterprise plans are quoted individually, I don't think we should show that here - we want to get folks reaching out to us.

**Comment by ackernaut** [comment]
Thank you, nice concept @avivapinchas !

- If the design needs we can use tabs (that ‘pill tab’ pattern is old, deprecated)
- I like the idea of exploring an inline form as opposed to the dialog
- Yep, I think we could have a tab that is only about billing (including any upgrade state or experiment) and move the delete action somewhere else
- I think the hierarchy here and reasoning behind is solid

**Comment by jordanh** [comment]
Iceboxing for now, when we reprioritize organic conversion
