### ISSUE TITLE
Poker: Estimate: Reveal votes animation

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4258]
https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2838%3A147623

AC
- When the votes are being cast, all the avatars exist on a single row (the question mark card row).
- When the votes are revealed, there will exist multiple rows, 1 for each unique value.
- the avatars from the single row should animate to the row according to their vote (e.g. if Bruce voted for 8, he should be on the 8 row)

Estimate: 16 hours

**Comment by ackernaut** [comment]
I see that an estimate dimension stage is shaped like this:
```graphql
stage {
  isVoting
  scores {
    userId
    value
    label
  }
}
```
So I can use the `scores` to batch users e.g. showing who voted or showing who voted per value row and `isVoting` to swap modes?

Out of scope is how to handle the group of `hoveringUsers` when they have or have not voted? If they haven‘t voted they start peeking in the view when they are hovering? If they have voted but are hovering (movement, as opposed to just resting over the cards) maybe we start to shimmy their avatar to indicate they may be changing their mind?

Am I missing anything @mattkrick ?

**Comment by mattkrick** [comment]
you got it! the hoveringUsers is in my draft PR
