### ISSUE TITLE
Poker: Estimate: Discussion Thread in Right Drawer

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4260]
For the poker meeting, we want to put the discussion thread in a drawer.
this drawer should work exactly the same as the left drawer on the dash or in the meeting (can be swiped & peeked on when on mobile). 

AC
- drawer looks like the figma spec: https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2689%3A118425
- on desktop, there is no hamburger menu to close it, so it's always open
- drawer works the same as the dash or meeting left nav. on mobile, it can be swiped open, longpress to peek, etc.

Note-- we'll probably have to change some physics in `SwipeableDashSidebar` to first detect if the user is attempting to open the left drawer or the right drawer! shouldn't be hard, just detect if the press is on the left or right side.

Estimate: 16 hours

**Comment by ackernaut** [comment]
Does this include wiring up the thread itself or shall that be in another issue?

**Comment by nickoferrall** [comment]
@ackernaut yep, this PR includes wiring up the thread
