### ISSUE TITLE
Poker: Estimate: pokerRevealVotes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4266]
after everyone has voted the facilitator needs to reveal the votes

AC
- [ ] `pokerRevealVotes(meetingId: string, stageId: string)` exists
- [ ] validation makes sure the viewer is the facilitator or defaultFacilitator & that the stageId is valid in the meeting
- [ ] the stage.isVoting boolean is set to false
- [ ] the payload includes a `stage` of type `EstimateStage`
- [ ] a client mutation exists that requests the `stage { isVoting}` in its return payload query

Estimate: 4 hours

**Comment by ackernaut** [comment]
Do we still want to reveal automatically if all the viewers who connected at some point have voted?

**Comment by mattkrick** [comment]
that may get dicey for async meeting.
- i'm the facilitator, i create the scope, then i go through & cast my vote. since i'm the only one who has checked in, my vote makes each one reveal.

we could implement a minimum of 2 votes, but we hit the same problem:
- the facilitator has already voted & then asks me to vote. i log into parabol & cast all my votes. no one else has hit the meeting, so each of my votes triggers a reveal

there's probably a good heuristic that we can use, but i haven't given it enough thought yet

**Comment by ackernaut** [comment]
Good points. I thought it would be good to not gate discussion on how the vote turned out on a facilitator having to reveal. Folks could use the discussion thread. But we’re talking about some behaviors that probably won’t be around for a while in our UX. Well, anybody could take over and reveal the vote if they see the full team has voted.

**Comment by mattkrick** [comment]
bad heuristics:
- trigger auto-reveal from the facilitator if `isAsync` is false. this is bad because someone can have an async meeting without a timebox
- add an auto-reveal checkbox. this is bad because it complicates the UI
- auto-reveal on all stages after the first one if the first one was completed in a synchronous matter. this is bad because it means the app acts differently for no reason. magic isn't fun.
