### ISSUE TITLE
Poker: Scope: Parabol: add new Parabol task

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4269]
### Acceptance criteria
- [ ] folks can tap a primary button ‘Add New Task’
- [ ] a new Parabol task is added to the top of the list with the placeholder
- [ ] the task is selected, updating the ‘select all’ header component
- [ ] if blurring without text, the task goes away and doesn’t persist
- [ ] the task is added to the top of the results set regardless of any current search query. If the search query is updated the task may go away as the results set is updated
- [ ] the task is set to the active status
- [See Figma for a concept](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=3294%3A0)

### Estimated effort
- 8 hours

**Comment by ackernaut** [comment]
Do we need a separate issue to add a Parabol task at the top of the Estimate phase view? @mattkrick @tiffanyhan

**Comment by tiffanyhan** [comment]
Do you mean what's in #4261? Or another button to create a new parabol task on the estimate phase?
