### ISSUE TITLE
Error when ‘\’ typed into search bar

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4271]
## Issue - Bug

1. Raise a dashboard view
2. Focus search bar
3. Type `\`

See:

![Kapture 2020-10-13 at 07 53 08](https://user-images.githubusercontent.com/103000/95877781-53761580-0d29-11eb-86fe-1d61645dcc06.gif)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 4 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Type whichever characters into the search bar they please and not cause a fatal error

**Comment by tianrunhe** [comment]
no longer an issue
