### ISSUE TITLE
Send `active` user properties to Amplitude

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4273]
##  Issue - Enhancement

Related to #4048 and #3943, it would be helpful to have a user property for 'isActive' in Amplitude. This would let us: 
- Pull the 'activation' stats in the Marketing Dash directly from Amplitude
- Better understand how active/inactive users engage with the product

### Acceptance Criteria (optional)
Parabol pals can: 
- Use 'active' user property in funnels and user charts in Amplitude

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
