### ISSUE TITLE
Add Amplitude events for 'reset grouping' 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4276]
## Issue - Enhancement

For the 'reset grouping' feature, we don't have a way of seeing how much that's being used, or when/why. To understand, I suggest two Amplitude events: 
- Event called `Edit Groups clicked`, with properties: meetingID, teamID, orgId. This would trigger when they first click the 'edit groups' button. 
- Event called `Grouping reset` , with properties: previous-phase, meetingId, teamId, orgId. This would trigger after they confirm. 

Having both events will tell us if folks get stopped by the warning, or if that's not an issue. Seeing 'previous phase' will tell us if folks are doing this right after they move to vote, or if they get to discuss and then go back. 

### Acceptance Criteria (optional)
Parabol team can: 
- Run an Amplitude funnel to understand if folks are dropping off before actually resetting Groups
- See how often folks are resetting grouping during a meeting (via Amplitude)
- Understand whether folks are resetting grouping right away, or getting further into the meeting then having to go back

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
