### ISSUE TITLE
Change tier names within the app

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4279]
## Issue - Enhancement

Per [this proposal](https://www.notion.so/parabol/Tier-Names-74c6d2510a704173b67e95ac5a0fbc1a) 🔒 , we've decided to change the names of the tiers we offer: 
- 'Free' should be called 'Team' 
- 'Pro' should be called 'Department' 

These changes need to be made within the app as well. 

### Acceptance Criteria (optional)
Users can:
   - See the new tier names wherever tiers are referred to in the app, ex: billing page (related: #4251), the `pro` badge on an organization in `/organizations` section 
   - See invoices & other billing-related items with the proper tier name 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This proposal wasn't adopted; iceboxing for now

**Comment by avivapinchas** [comment]
@jordanh This proposal *was* adopted:[ in Notion here](https://www.notion.so/parabol/Tier-Names-74c6d2510a704173b67e95ac5a0fbc1a) 🔒 

We haven't bothered to enact it, and I don't feel a lot of tension here, can wait till we look at pricing & packaging more intentionally. But, technically, we did adopt this.

**Comment by jordanh** [comment]
Oh my goodness! My bad.

Noting we did adopt this, but did not make the change. Once you feel the tension, we can re-prioritize
