### ISSUE TITLE
Enable users to change password while logged in

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4280]
#3973  Issue - Enhancement

Users are currently unable to reset their passwords while logged in. The currently workflow requires them to log out of their accounts, hit 'forgot password' and then follow the steps to create a new password. It would. be helpful if the workflow were more intuitive and less time consuming. Ideally, users would have the ability to reset their passwords via their Profile tab.

A user from [a partner](https://app.hubspot.com/contacts/3888472/contact/17027551) reported feeling uneasy about being unable to reset their password while logged:
"Hello,
I'm a Parabol consulting partner and someone I'm using Parabol with expressed a concern regarding their inability to reset their password when authenticated in the tool itself."

### Acceptance Criteria (optional)
Users can:
   - Reset their password directly in Parabol
   - Securely reset their passwords without having to navigate out of the platform (i.e. no verification link sent to inbox)

**Comment by jordanh** [comment]
It's wild how long we've gone on without needing to implement a "change password" inside a product. We didn't get any additional report for this, so iceboxing for now
