### ISSUE TITLE
Squished prompt dots

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4284]
I noticed squished prompts, especially the colored dots. I’m guessing the flex layout should be set to `flex-shrink: 0;` or something similar. Also, the dot should be at the top of the prompt, not centered vertically. It’s meant to be hanging off the first line and centered vertically on the first line. The last prompt in the screenshot looks right since it’s not long.

![Screen Shot 2020-10-19 at 11 18 24](https://user-images.githubusercontent.com/307286/96932358-60f77200-1484-11eb-9537-fe7c4824eb92.png)

### AC
- Fixed the layout

### EE
- LT 1 hr

**Comment by jordanh** [comment]
Stale, but will leave open until next scrub in order to discuss with @ackernaut

**Comment by jordanh** [comment]
Scrubbed, iceboxing
