### ISSUE TITLE
Team Updates feature explored, low-fi version designed 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4286]
## Issue - Enhancement

'Team Updates' is a feature we discussed at SPA 16. This issue is for an initial design. 

Background: 
- [Notes on tensions we're considering](https://www.notion.so/parabol/Team-Updates-698f780358dd4c3b86b03162abc9a66a)
- [Pen-and-ink explorations from the team](https://www.figma.com/file/k6ZPBN2mMN7f72aceG9YFr/Team-Updates?node-id=0%3A1)
- [Proposed initial implementation pen-and-ink ](https://docs.google.com/presentation/d/1WuveNGxT02EASU6FxwAyCKc3PEAcA4f_7Y8_PhiFt6Y/edit#slide=id.p)

### Acceptance Criteria (optional)
Parabol team: 
- Has a defined long-term and first-pass low-fi designs to share with users for feedback 

- **Estimated effort:** 24 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Edited @avivapinchas and added @ackernaut's highly scientific EE

**Comment by jordanh** [comment]
See also: #4107, #4771
