### ISSUE TITLE
Initial Team Updates trial: updates from Parabol team 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4287]
## Issue - Enhancement

Related to #4286, we proposed implementing the option to send out video updates from the Parabol team for key features as a first step towards the Team Updates feature. 

![parabol updates](https://user-images.githubusercontent.com/11621016/97193470-09545180-1777-11eb-8d42-e76d36d4cbde.jpeg)

### Acceptance Criteria (optional)
Users can:
- See video updates from the Parabol team in their Timeline, including latest and a few others 
- Watch the videos in context, within the Timeline 

Parabol team can: 
- Upload new video updates for inclusion in the Timeline event
- See metrics on # folks who started the video, % that got halfway through, % that completed the video - in Amplitude 

- **Estimated effort:** 16 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Edited @avivapinchas's comment. Added EE from @ackernaut

**Comment by jordanh** [comment]
Stories stories everywhere. Iceboxing
