### ISSUE TITLE
Removing the currently selected check-in item kicks the viewer out of the meeting

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4291]
## Issue - Bug

- Removing the agenda item that is currently being discussed causes the viewer to be redirected to the homepage

https://www.loom.com/share/4b3068e23f07450d9ca8a42d08c8618a

### Test

- [ ] Removing the currently active agenda item does not redirect the user to the homepage. The next agenda item / last call phase should display instead

**Comment by jordanh** [comment]
EE
8 hours

**Comment by jordanh** [comment]
Iceboxing, please re-open if you still feel tense around this and think we should bump up in priority
