### ISSUE TITLE
Ability to change email associated with user account

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4297]
### 

## Enhancement: Grant users the ability to change the email address associated with their account

Today, users need to create a new Parabol account if they want to sign-in using a different email address. This causes them to lose their meeting history & task assignments, and they have to be re-invited to their teams. 

Because many of our customer first adopt us without IT review, many users sign-up with their personal email addresses. When they convert to official clients, they then have to start entirely new accounts in order to continue using the platform according to their company's security policy. 

It would be ideal if the client experience was seamless during the conversion process so that upgrading didn't cause any negative ramifications.

### Acceptance Criteria
Users can:
   - Change the email associated with their account via their profile section

**Comment by jordanh** [comment]
We don't want to be in the business of merging user accounts. The naïve thing to do, and the easy thing to do will be to update the email on the `User` record, as long as that email is not used by another `User`.

Marking this as a discussion, looking for more signal before prioritizing

**Comment by mattkrick** [comment]
let's add this to the User Profile wishlist. let them change, add/remove, whatever.

**Comment by jordanh** [comment]
Iceboxing
