### ISSUE TITLE
Improve login page flow

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4301]
## Issue - Enhancement

Expanding from #4299 , we can improve the workflow of our login page. An idea I proposed is to have a email input box on the first page only and then depend on the type of the account (OAuth, SSO, local), we show different pages on the second screen. This way it would only be possible to see the password input box iff the account is a local one. Resetting password link on that page will also make more sense and crypstal clear.

Here’s an example from Quip. I previously signed up with Quip with Google OAuth so they take me there directly. In this example, I wouldn’t even fall into the scenario where I mistakenly thought I had sign up with GMail and a password:

![](https://user-images.githubusercontent.com/1879975/97742847-125c6000-1aa2-11eb-9b08-3a1ef4edd7cc.gif)

If I use an account without OAuth enabled before, they then take me to the normal email/password sign in page:

![](https://user-images.githubusercontent.com/1879975/97742890-2011e580-1aa2-11eb-82f9-5c8bb118d015.gif)

Initial reaction from Matt:

> *   i know i signed up with my password, let me type it all at once, i don’t want to wait for you to load another page
> *   it would solve for the kinda janky SSO login flow
> *   i’d just want to guarantee that typing in my password is just as fast as it is today by hitting the tab key and also avoid dumb people saying “omg, where do i enter my password now? you removed it” without even trying to click login

### Acceptance Criteria (optional)

*   A better user login page solution is proposed

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed, iceboxing
