### ISSUE TITLE
Update default poker template

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4303]
looks like i didn't check the migrations well enough.
The default template should only have a single dimension, because almost all users report only voting on 1 dimension.

AC
- [ ] There is an "Estimated Effort" template that has 1 dimension: story points. It is the default template
- [ ] There is a "weighted shortest job first" template that has 2 dimensions: story points & story value
- [ ] A migration exists that adds these templates & removes the other ones

Effort: 4 hours

**Comment by tianrunhe** [comment]
@mattkrick What do we want to set the default scales for those dimensions?

**Comment by mattkrick** [comment]
fibonacci all the things!
i think we could just copy this & be good: https://github.com/ParabolInc/parabol/blob/clean-uploadables/packages/server/database/migrations/20201014110000-templateScale.ts#L33-L84
