### ISSUE TITLE
Display story point estimates on Task cards, if available

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4305]
Now that folks can vote on different dimensions (e.g. story points, value, etc) we need to assign those estimates to parabol task cards. This is important because they can see this data in jira & we should probably have feature parity of a feature that we design.

The proposed schema is as follows:
```graphql
Task {
  estimates {
    name
    value
    label
  }
}
```

AC
- [ ] given the schema above, design a way to show multiple values. maybe there's a small name & label in the bottom & if there are multiple estimates they can click through them?

Estimate: 16 hours

**Comment by ackernaut** [comment]
@mattkrick in what context will we show a Parabol task card with an estimation on it?

**Comment by mattkrick** [comment]
for v1: whenever the value is present.
for v2: you can edit the value from the card.
for v3: you can add a value to a Task card outside a poker meeting (may never happen)

**Comment by ackernaut** [comment]
Will these cards show on the kanban? Are they assigned to an owner?

**Comment by mattkrick** [comment]
v1: if they have an owner, they'll be on the kanban. I think you & I discussed possibly showing the point value on the `StoryCard` component (the one at the top of the estimate phase) but decided against it.

v2: tasks w/o owners will appear in the kanban

**Comment by ackernaut** [comment]
That sounds right, in the estimation meeting view we wanted the final value to live closer to the activity. I see, it’s possible to include existing Parabol tasks in the meeting and they’d have owners. Okay. I can see a similar meta line to the external link line of integrated tasks. But I’ll put out some iterations. Thanks for clarifying.

**Comment by ackernaut** [comment]
I’ve got [the first set of rough ideas in Figma](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=4102%3A188016). This is a quick iteration to our current task cards.

I don’t think adding meta items after the description is scalable but we can design something better when we have that problem. As of now, it could maybe be a link to GitHub or Jira, and then a pointing score or many. Parabol tasks would just have a pointing score.

If there are multiple we could follow the first dimension with an ellipsis and show all the values on hover. We could use tight formatting with a tooltip or use a menu item if we want to be explicit.

Folks could tap through to the meeting stage where that score was set last.

**Question** for @mattkrick — how do we determine what scores remain on the card? Of course, this seems like an edge case. Say a Parabol task card is given ‘Points: 8’ in meeting 1 and then ‘Value: 8’ and ‘Effort: 5’ in another meeting. Do we override previously set scores from meeting A with the scores now being set by meeting B? Do we aggregate all 3 dimensions ala can’t have the same dimension label twice?

This reminds me of the idea of designing a task card details view that raises like a dialog. We could show extra information in that view. We may still need to indicate that there’s extra meta on the card face.

For mobile, when editing or viewing a card it may be nice to have a focused details view. There’s no room for UI chrome and when editing the keyboard takes half the screen sometimes.

**Comment by mattkrick** [comment]
> Do we aggregate all 3 dimensions ala can’t have the same dimension label twice?
yup, use the label as a key, however many labels + values they wanna throw at a Task, let em

**Comment by ackernaut** [comment]
@mattkrick I’m not sure how much time I need to spend here and only have half-baked ideas at best. Here’s latest. I need a 2nd opinion so we can iterate or decide on first and target versions of this:

https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=4148%3A4496

**Comment by ackernaut** [comment]
Closing in favor of #4511
