### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by spyse** [ParabolInc/parabol#4307]
Hi,

installed parabol like it is described in the readm.me on a oracle linux 8 OS.
Everything build and starts when calling `yarn` but when opening the app in a browser I get the following error:

`Uncaught SyntaxError: Unexpected token '<'`

My `.env` file is the `.env.example` original file. And if I try to change anything in it, like hostname, I'll get this error on `yarn start`:

`InvalidEndpoint: An endpoint must be provided when configuring `s3BucketEndpoint` to true.`

I tried it with the master and with v5.22.0. Same issue.

Node: v14.15.0

**Comment by jordanh** [comment]
@spyse 

A couple of things here, you need to run "yarn build" from the project root to build dependencies. This should fix:

> `Uncaught SyntaxError: Unexpected token '<'`

And secondly, you will need to make sure to unset any `AWS_` vars in `.env` to disable image uploads and get past that fatal error

**Comment by spyse** [comment]
Thanks for the hint, which I saw quite late...
To _unset_ I just erased everything after the ```=``` for ```AWS_```-Properties ?!

Did a ```yarn build && yarn start```

Same behaviour. Still the ```'<'```-Error

I have no external services I want to use right now. Seems like a lot more settings may be unset?

**Comment by aviadavi** [comment]
did you manage to fix it?

**Comment by spyse** [comment]
nope...

**Comment by JimmyLv** [comment]
I met the same issue, but no idea, 👀

**Comment by aviadavi** [comment]
OK, I've managed to workaround the issue by deleting the key_CDN_BASE_URL line from the env-example.config

**Comment by jordanh** [comment]
Closing this!
