### ISSUE TITLE
Re-design failed payment flow to avoid activity dropping 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4319]
### Issue - Enhancement

Right now, when a paid customer has a card fail and doesn't realize it, they're locked out of the product. To get back in, they have to go through the upgrade process again. 

This can lead to some less-than-ideal consequences, as they may be wanting to run a meeting, perhaps don't have the power to update the card info. They get blocked and it leaves a bad taste in their mouth. 

Instead, we should design a process that: 
- Allows users who intended to pay some flexibility, so they don't have this negative experience
- Informs users about potential issues proactively, so they can be resolved before a negative consequence
- Has fall-back or safety mechanisms, so that bad actors who intend to abuse the system aren't able to 

Here's my proposal: 
- When a payment fails, send a proactive email notification to the Billing Leader to update information 
- If payment information is not updated and users go to run a meeting, they're greeted by something similar to the upgrade prompt. They can click out of it and get an email notice to update payment information. They can go on with their meeting before they've updated payment information. 
- Parabol team is notified in some way of the above, and can track when this is resolved or outstanding. 
- As the days tick on, there's some automated flow reminding them to update their payment information. 
- After some grace period, if they have not updated payment, then they are then locked out of the product. 

### Acceptance Criteria (optional)
Users can:
   - Get into a meeting or continue with their work, even if/when a payment fails 
   - Learn about payment failures _before_ they're blocked in the product 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing. Will re-examine when we look into organic upgrades
