### ISSUE TITLE
Invitation links always work for existing team members

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4322]
### Background
Today if a team member goes back to click an expired invitation link to a team or meeting, they get blocked even though they’re already on the team. E.g. maybe it was posted in chat yesterday, they got in once, and they recall getting back via that link. ‘The link should just work, don’t make me think. If I see a link, I click a link.’

### Acceptance criteria
- [ ] The invitation link maintains an expiration feature but there’s logic to check for existing team members and let them in

### Estimated effort
- 8 hrs

### Related
- Invitation link expiration increased with domain verification #4323 
- Invitation email expiration increased to 30 days #4324 
- Expired invitation links trigger the accept snackbar for active team members #4325 
- Accept snackbar can let multiple users in at once #4326 
- Invitation dialog design updated #4327

**Comment by jordanh** [comment]
I am reasonable certain this has been changed to work as above, right @mattkrick and @ackernaut?

If this wasn't addressed when we made the expiry time of links longer, it is a bit less of an issue _except_ for folks who might think to put invite links in to calendar appointments...
