### ISSUE TITLE
Invitation dialog design updated

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4327]
### Background
Today the invite dialog says ‘invite to team’ regardless of the meeting or team context. It has copy that explains the expiration which users shouldn’t have to worry about.

I have a hunch that we give users a single invite path depending on the context. They share a link from the meeting view, the invite via email from the team view. If we make the invite link smarter and increase the duration of the email invitations, users shouldn’t have to worry about that business logic.

If the invite link is only sent from activities it would be nice to know which activity so that we send them to the best place and fall back to the next best place.

### Acceptance criteria
- [ ] Researched metrics on current usage of email vs link
- [ ] Wrote implementation issue for any recommended design changes (single path, best redirect path, copy updates, etc.)

### Estimated effort
- 8 hrs

### Related
- Invitation links always work for existing team members #4322 
- Invitation link expiration increased with domain verification #4323 
- Invitation email expiration increased to 30 days #4324 
- Expired invitation links trigger the accept snackbar for active team members #4325 
- Accept snackbar can let multiple users in #4326

**Comment by jordanh** [comment]
+1 from [this user](https://app.hubspot.com/contacts/3888472/contact/19482951) 🔐  [feedback video](https://drive.google.com/file/d/1CUZOESAu29y1ILE6Q0TUB0sfF-h13l-h/view?t=2m38s) 🔐

**Comment by jordanh** [comment]
Iceboxing for now
