### ISSUE TITLE
Remove deprecated newMeeting mutations

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4330]
In PR #4329, we deprecated the `startNewMeeting` and `endNewMeeting` mutations in favour of meeting specific mutations, e.g. `startCheckIn`.

Once these new mutations have been in production for a month or two, we need to remove the deprecated `startNewMeeting` and `endNewMeeting` mutations and the references to them, e.g. fragments in the subscriptions.

### AC

- [ ] Remove `startNewMeeting` and `endNewMeeting` mutations 
- [ ] Able to start and end all meeting types

**Comment by jordanh** [comment]
EE
4 hours

**Comment by mattkrick** [comment]
this was done awhile ago
