### ISSUE TITLE
New user retro template selection

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4338]
[A user](https://app.hubspot.com/contacts/3888472/contact/19482951) 🔐 shared:

> I wanted to run one of the "Start, Stop, Continue" retros because that is what I had seen in the demo...I'm not sure what the [retro template dropdown] default was, but I'm almost sure it wasn't "Start, Stop, Continue". When I clicked, I think the [template modal] was navigated to [Team] and [had me edit a new template]. I had to click on "Public" and copy "Start, Stop, Continue," and I felt that might be confusing for new users

[See video verbatim here](https://drive.google.com/file/d/1CUZOESAu29y1ILE6Q0TUB0sfF-h13l-h/view?t=0m54s) 🔐

@ackernaut, @tianrunhe, or @mattkrick we should probably look at this more carefully. I could see this being confusing. What is our expected flow today for new users? What is selected in the drop down, zero state? What do they see when they click?

**Comment by jordanh** [comment]
For zero state on a new user/new team, I'm thinking we should:

- Default to whatever we show in the demo (Start, Stop, Continue in the present case)
- When clicked, Navigate the template picker to Public->Start, Stop, Continue
- Make the "copy" CTA much more obvious

**Comment by tianrunhe** [comment]
The default template today is "Working & Stuck" and we can easily change that. I could not reproduce this issue though:

> When I clicked, I think the \[template modal\] was navigated to \[Team\] and \[had me edit a new template\]

![](https://user-images.githubusercontent.com/1879975/99028910-f1761f00-2525-11eb-8fb9-8f38134c4005.gif)

**Comment by ackernaut** [comment]
This is also related to #4128

**Comment by jordanh** [comment]
I believe this is working as designed. I am going to close this for now
