### ISSUE TITLE
Meeting UI: which avatars indicate presence?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4339]
[A user](https://app.hubspot.com/contacts/3888472/contact/19482951) 🔐 said:

> As people were joining the meeting I saw [one avatar] image appear, but all five we already [in the checkin phase item list].

The user wasn't sure which place in the UI indicated presence.

[Verbatim video here](https://drive.google.com/file/d/1CUZOESAu29y1ILE6Q0TUB0sfF-h13l-h/view?t=3m42s) 🔐.

**Comment by jordanh** [comment]
Perhaps connection state should be added to all avatars we display?

**Comment by mattkrick** [comment]
fixed. meeting members are now lazily added as they arrive
