### ISSUE TITLE
Meetings should only include participants

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4351]
​

AC

- [ ] MeetingMember is created lazily when people join

- [ ] summary is still sent to all team members

- [ ] event still gets sent to all team members

​

Estimate: 16 hours

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10453101/) 🔒  says:

> we've made a mistake and did a retro with one team from our tribe within the company. We thought, that the summary would only be mailed to the people that were in the retro (the small team, not the whole tribe). But the email went out to the whole tribe... now I can only hope, that not all are reading the email.

**Comment by shawneeatparabol** [comment]
A🔐[customer](https://app.hubspot.com/contacts/3888472/contact/23239751/) writes in:
"Hi Parabol,
Our whole team doesn’t participate in each Retro. Is there a way to turn off automatic emails?"

**Comment by mattkrick** [comment]
There are a lot of issues here that are tightly coupled. Here's my proposal:
- To enter a meeting (active or finished), you must be invited. 
- By default, all team members (past, present, future) are invited to the meeting
- Each team member can choose to unsubscribe from email meeting summaries

In terms of UI, this should look like the following:
- Each team member has a toggle to turn on/off summary emails for that team
- Each meeting has a visibility setting. Possible options are:
  - ONLY these people - select from a list (post-meeting, we could use this for things like closing it to only folks who attended)
  - Anyone who joins the team before the meeting ends
  - Anyone on the team
  - Anyone in the org
  - Anyone with a parabol account

This PR does the following:
- allows you to enter a meeting even if you're not a meeting member (just a team member)
- once you join a meeting as a team member, it creates a meeting member for you

The scope of this PR is pretty tiny compared to the customer feedback we're getting, so i'm gonna create a new issue for more feedback on meeting permissions.
