### ISSUE TITLE
Pinned items removed on meeting end

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4352]
After ending our Product check-in meeting, the pinned agenda items were removed from the team. During the meeting, we were unable to remove an agenda item (see #4348) - perhaps the bugs are related. 

### AC

- [ ] Able to end a check-in meeting without removing the pinned agenda items

EE: 4 hours

**Comment by ackernaut** [comment]
I saw this today on production. I still can’t reproduce reliably. I tried seeing if the pins would remain on new vs existing teams, and then trying to deduce some regression. No luck.

**Comment by nickoferrall** [comment]
I haven't been able to reproduce this locally or in production and our last couple of Product Check-ins have also worked as expected. Sr Husney mentioned deprioritising this one and I think we should unless it happens again.
