### ISSUE TITLE
Upgrade to latest version of Relay

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4355]
We've got so many Relay GC bugs going on throughout the app that it's really hurting our users.
Our options:
- build our own client cache
- fork relay & write our own caching system for it
- burn the hours triaging the bug & PR relay
- upgrade to the latest version of relay & cross our fingers

Let's start with upgrading, first, and then work our way up the list if that doesn't work.

AC
- [ ] Relay is upgraded to the latest version
- [ ] Relay is forked & our changes are incorporated in our own version (fix for __clientField and the QueryRenderer delays GC for 5 mins after the route is left)

Estimate: 16 hours

**Comment by jordanh** [comment]
@mattkrick what's your sense of urgency around this? i.e. should we tackle this in the next sprint (p1) or before the next S.P.A. (p2)?

**Comment by mattkrick** [comment]
Bumping to P1 because we need this upgrade for ironbank reasons

**Comment by jordanh** [comment]
roger dodger

**Comment by mattkrick** [comment]
Business case:
- our version is insecure & ironbank needs it & that a goal
- this unlocks react's suspense mode for relay.  write cleaner code & have it be asynchronous 
- new directives like `@appendEdge` so new code doesn't have to be so gosh darn imperative & less surface area for bugs
- queryFetcher now have a LRU cache, we can start exploring that & maybe, _maybe_ we can stop forking the silly thing

Plan of attack:
- [ ] read old relay fork to see exactly what we had to fork
- [ ] read all the changelogs since that version (v8?) and pick out notable features
- [ ] write new AC once i know what needs to be done
