### ISSUE TITLE
sort tasks by `createdAt`on kanban board

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4356]
## Issue - Enhancement

If a task is created directly from the kanboard board, it will display on top of the column in which it is created. However, if a task is created from a discussion thread in a meeting, there is no guarantee that it will show at top of the "active" column in the task kanban board. I think this behavior is unintuitive, and the most recently created tasks should always appear on top, no matter where the task is created from. See screenshot below for example of task order and timestamps of first created. To implement, I think we just need to display by `createdAt` then `sortOrder` instead of just `sortOrder`.

### Acceptance Criteria (optional)
Users can:
   - [ ] see most recently created tasks on top of the relevant column in the task kanban board.

- **Estimated effort:** 4 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

## Issue - Enhancement

If a task is created directly from the kanboard board, it will display on top of the column in which it is created. However, if a task is created from a discussion thread in a meeting, there is no guarantee that it will show at top of the "active" column in the task kanban board. I think this behavior is unintuitive, and the most recently created tasks should always appear on top, no matter where the task is created from. See screenshot below for example of task order and timestamps of first created. To implement, I think we just need to display by `createdAt` then `sortOrder` instead of just `sortOrder`.

### Acceptance Criteria (optional)
Users can:
   - [ ] see most recently created tasks on top of the relevant column in the task kanban board.

- **Estimated effort:** 4 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

<img width="1094" alt="Screen Shot 2020-11-18 at 11 38 32 AM" src="https://user-images.githubusercontent.com/11562889/99579137-9f545400-2992-11eb-9814-df12f1f6c8ba.png">

**Comment by avivapinchas** [comment]
Clarifying question: would a user be able to manually sort and moves around the order of the cards in their Active column?

**Comment by tiffanyhan** [comment]
yes if they manually sort, the app would honor that positioning. my idea was only related to the default positioning of created tasks that haven't yet been manually sorted.

**Comment by mattkrick** [comment]
if i understand this clearly, you're proposing 2 sort orders. if i sort by created at & then change the sort order by drag & drop, then my "created at" sort order is no longer true. this could get a little hairy.

i'd propose the following: when a task is created, the server should give that task a sort order that guarantees it is at the top. it can do this by finding the min value for that team for that status & being a little bit smaller than that.

**Comment by tiffanyhan** [comment]
ooh i was mostly proposing desired behavior for discussion, open to implementation.

> i'd propose the following: when a task is created, the server should give that task a sort order that guarantees it is at the top. it can do this by finding the min value for that team for that status & being a little bit smaller than that. that means we only have 1 sort order for the kanban & new things will always wind up on top.

that sounds good to me! i was looking at the code and was surprised it didn't already do this.

**Comment by mattkrick** [comment]
me too! i thought it did that when tasks got created, but perhaps i only had it do that after check-in meetings ended. either way, definitely a strong recommendation for a better UX!

**Comment by jordanh** [comment]
iceboxing
