### ISSUE TITLE
Poker summary v1 designed, 2nd pass

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4363]
### Acceptance criteria
Designed concept iterations that show:
- [ ] The participants
- [ ] A primary CTA
- [ ] Any secondary actions
- [ ] Minimal meta about the meeting
- [ ] A summary of individual items
- [ ] A total and velocity, and any conditions for showing or not
- [ ] A way to give feedback to Parabol
- [ ] Notes on what common summary elements could be updated for the retro, check-in

### Estimated effort
- 8 hours

**Comment by mattkrick** [comment]
the most basic variant is live on master (punted on the feedback & velocity)
i figure that stuff will be easier to build once we look at all meeting summaries & decide which pieces are specific to poker & which ones are shared

**Comment by ackernaut** [comment]
I still like an idea where emails move toward a minimal, notification style (all of which can be managed as preferences) and point to experiences in the app. In this case, a meeting completed notification might look similar in Slack, or on the timeline, or via email, and folks can pick where they want to see it. The notification points to a summary that is dynamic and is part of the meeting UI experience (or part of an insights experience).
