### ISSUE TITLE
Improving build time & stability

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4370]
Doing a bunch of front-end coding lately, I'm really frustrated with the DX. HMR is spotty on both the server & client, relay-compiler will seemingly restart for no reason, etc.

Investing time here in DX will yield huge savings as every developer will be able to code faster, so we should prioritize this.

Thoughts:
- My conclusion is HMR on the server is unreliable. We should get rid of it (for the server). If we are thoughtful, a server restart should be almost as fast as HMR.
- having a co-dependency between server & client packages is wrong. The client should have no dependencies on parabol-server & all shared assets should live in the client.
- We could probably shortcut the GQL Executor in development & just go direct to executeGraphQL
- There should be a way to cache the server bundle & the client bundle independently, although I'm not sure how to do this without some HMR on the server
- We should get those `.graphql` files living on the client compiled & hardcoded so we don't need that babel transformer. in the future, we'll just attach the GH schema to ours & all requests will go through parabol-server
- although it looks like sucrase is faster than swc (https://github.com/alangpierce/sucrase/blob/d8928b27be3d83729bff48fdcb00d9cde5eed3fc/README.md#try-it-out) there are some other tools that we should explore:
  - https://github.com/evanw/esbuild/blob/master/docs/architecture.md
  - https://www.snowpack.dev/ (looks like webpack 5 would be a better call than this)
- we should see if there's a new react HMR tool to improve client HMR

@tianrunhe @tiffanyhan @nickoferrall any input here is welcome! let's get a list of what we want the perfect DX to look like & start building

**Comment by mattkrick** [comment]
i wanna bite this off in chunks:
- upgrade to webpack 5 to reduce build times
- remove all dependencies on parabol-server from parabol-client
- remove HMR on the server & instead use nodemon or similar that watches for changes on the server folder
- work on caching server & client webpack builds

**Comment by ackernaut** [comment]
Can we address the need to restart when changing const enums in some burndown?

**Comment by mattkrick** [comment]
yep! that's a big one.
