### ISSUE TITLE
Refactor color palette

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4372]
We've got way, way too many colors in the palette.
After reading this article (https://refactoringui.com/previews/building-your-color-palette/) i think we should follow suit.
Pick a primary, blue, green, red, gray & get 9 shades, call them 100-900.
as far as naming, i think it should be simple as RED_100, BLUE_500, PURPLE_900, etc. 
i think we have to decouple what they are from how they're used (e.g. replace GRAY_BACKGROUND with GRAY_300). _how_ they're used can live in the comments, but they should only serve as guidelines which can be broken.

AC
- [ ] PALETTE is replaced with PALETTE_V3
- [ ] PALETTE_V3 has a max of 9 shades per color
- [ ] [Burndown](https://github.com/ParabolInc/parabol/issues/4372#issuecomment-789284623)

Stuck on: Branding complete

Estimate: 16 hours

**Comment by ackernaut** [comment]
That’s basically what we used to do. It’ll take some effort to resolve what we get from the branding exercise, as you noted. I’m optimistic if we can get the variants right. Thanks for capturing!

**Comment by ackernaut** [comment]
I think one thing we should consider when refactoring the palette is if we could potentially build a light and dark theme with it. I’m okay kicking a dark theme down the road but I wonder how it might increase attachment with agile engineering teams. Here’s an example of a product from the wild: https://linear.app/

**Comment by mattkrick** [comment]
absolutely we want dark theme.
in a perfect work, we could use e.g. RED_500 on both light & dark, but i fear contrast might not always be enough.
in an almost perfect world, we could create lookup rules a la i18n & say use RED_500 for light and RED_300 for dark. 
in a bad world, we use RED_300 in places, RED_200 in others, and BLUE_300 in others. this is what we want to avoid.

**Comment by ackernaut** [comment]
Inspiration: [https://dribbble.com/search/dark%20mode](https://dribbble.com/search/dark%20mode)

**Comment by ackernaut** [comment]
@mattkrick should we scope a pattern for dark mode in this issue or separate out that work? I could stand to look at how other folks are handling it, but I wonder if we use some sort of theme mapper for only the colors that diverge. Drunken code:

```javascript
export const enum DarkTheme {
  CARD_SURFACE = PALETTE.GRAY_800
}

export const enum LightTheme {
  CARD_SURFACE = PALETTE.LIGHT_100
}
```

We could resolve the theme at some higher context and pass that to the needy components: 

```javascript
const CardWrapper = styled('div')<{theme: Theme}>(({theme}) => ({
  backgroundColor: theme.CARD_SURFACE
}))
```

**Comment by ackernaut** [comment]
Edit:
>Or better yet, what is Theme was a type that required fields to handle each needed color declaration (e.g. cardSurface) and that way we’re checking if a theme has declared all the required colors?

**Comment by mattkrick** [comment]
here's a common pattern: https://emotion.sh/docs/theming#themeprovider-reactcomponenttype

that works if there are no exceptions to the rule.
if there are, it may be easier to pass down a boolean & handle at the component level, e.g. `color: isDark ? black : blue`

**Comment by ackernaut** [comment]
Oh, I think I like the expressiveness and composability of pulling an `isDark` boolean from a global context as needed. You get all the information in the same spot, like how we handle breakpoints.

**Comment by ackernaut** [comment]
I’d amend the following here:
- We have a master set of 9 variants per color in Figma (i.e. documented), but we only include the variants used in the app. E.g. we don’t add RED_900 until we actually use it
- We avoid opacity except when it’s needed e.g. a dialog scrim. In those cases we use a palette color with the alpha parameter added, and maybe uses a const enum like GRAY_700_80 where the second number is the opacity but the first is the palette color
- Gradients are also a special case. We stick to palette variants but name the gradients something appropriate like GRADIENT_RED_500_PINK_500 or something that indicates what values are used

**Comment by ackernaut** [comment]
Also, do we deprecate usage of the current PALETTE but leave it in until we touch those const enum names? And only use PALETTE_V3 moving forward? Or do we touch every file in the refactor? FYI I have a branch where I’ve updated the value of the colors in PALETTE to use the new variants, as an experiment.

**Comment by ackernaut** [comment]
See #4428 in review

**Comment by ackernaut** [comment]
I merged the first pass. I’ll close this issue by scrubbing V2 values and file in a second PR.

**Comment by ackernaut** [comment]
### Burndown
- [ ] Replaced v2 const enums with v3 const enums
- [ ] Scrubbed CSS files like daypicker, globalStyles, email styles, etc.
