### ISSUE TITLE
Architect the video/SFU deployment pipeline

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4375]
As we get closer to deploying video, we need to know what that should look like.
Should it be its own repo? Should a deployment just target that single package?
Maybe this looks like a gitlab pipeline, will leave up to @adaniels-parabol to decide
See https://github.com/ParabolInc/parabol/issues/4174

AC
- [ ] Able to deploy & upgrade the SFU independently of the rest of the app
- [ ] ensure UDP ports are open for business & proxying supports 0-downtime so folks don't lose video when we upgrade
- [ ] Monitoring set up (datadog/sentry)

Estimate: 40 hours

**Comment by jordanh** [comment]
Going to icebox this one for now
