### ISSUE TITLE
Self-provisioning SSO designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4378]
AC proposed concept(s) to gather feedback from team, users

EE 8 hours

**Comment by shawneeatparabol** [comment]
Tiffany and I just did trouble shooting for Azure AD SSO set up for 2 more clients ([here](https://app.hubspot.com/contacts/3888472/deal/2822079768) and [here](https://app.hubspot.com/contacts/3888472/company/2062444578)). We're working on creating better documentation in Notion for the team as have noticed Azure AD users use different terminology and require different information to be gathered/shared. Self-provisioning would be very helpful.

**Comment by ackernaut** [comment]
Iceboxing for now. This will be superseded by the SCIM issue #4833

**Comment by jordanh** [comment]
Related: #4407
