### ISSUE TITLE
Ability to manually import/Export task cards/stories from CSV to Parabol

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4379]
## Issue - Import Feature Enhancement for Sprint Poker

Many large clients use a backlog management system that is not Jira Cloud (either another vendor, proprietary or on-prem). In order for them to get the full value out of Parabol's Sprint Poker feature (which we are banking on) they would either need to invest in a large scale backlog platform transition, be willing to self-host or have team members who are willing to manually transcribe between Parabol and their backlog platform after each meeting.

Clients who do not want to take on the added work of self-maintenance will be hard to convince to select a self-hosted instance, those same clients will also probably not want to spend developer time transposing between the platforms. 

It would be ideal if clients could bulk import stories from CSV in order to accommodate this userbase. One client already asking for this feature is🔐 [here](https://app.hubspot.com/contacts/3888472/deal/2872374739) with 600 potential users.

### Acceptance Criteria (optional)
Users can:
   - Import a CSV spreadhseet of tickets from any backlog platform to Parabol Sprint Poker meeting
   - Bonus: can import/export Action Cards from Kanban as a CSV
   - Export estimation summary into CSV for uploading into their backlog platform

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/deal/2872374739) 🔒 asks:

> Would it be worth it to be able to export to CSV in Jira format, just do an import on a file and we can use this file and then after we can export and we can create the task with the API? (Jira Local)


See discussion from user feedback retro: https://action.parabol.co/meet/VQ0d2FztS/discuss/7

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/27829051) 🔒 writes:

> I tried to test this cool new feature but had to discover that it only works with Jira instances run by Atlassian, not with our self-hosted instance. Do you plan to support different Jira locations in the future?

**Comment by jordanh** [comment]
Likely much of this tension will be reduced by Jira Server and other on-prem integrations under development.

Iceboxing by policy
