### ISSUE TITLE
Improve rate limit reached feedback

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4384]
When a user hits the max number of teams that they can create on the free tier, they see the following error message:

![rate-limit-reached](https://user-images.githubusercontent.com/39854876/100759796-f1609500-33e8-11eb-9595-cc342662d9cf.png)

I think we could provide more clarity here and make it easier for users to upgrade their account. 

We could simply change the feedback text to be: "Free tier limit reached. Upgrade now (hyperlinked to billing page)"

Alternatively, we could immediately display the payment modal with the error message or redirect the user to the billing page but that may feel a bit aggressive.

### AC

- [ ] Update rate limit reached copy

**Comment by ackernaut** [comment]
Closing for now
