### ISSUE TITLE
As a DevSecOps engineer, I want to setup a managed instance of Gitlab via SaaS through Gitlab.com

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#4389]
As a DevSecOps engineer, I want to setup a managed instance of Gitlab via SaaS through Gitlab.com

AC:

- [x] Get approval to procure Gitlab hosted instance at Silver level (cost is $228 per user, annually). Recommend accounts for @jordanh @mattkrick and @adaniels-parabol  to start. Total cost is $684, annually, for the aforementioned users.

- [x] Procure Gitlab hosted instance services per above approval

- [x] Setup project repository with mirroring for Parabol

- [x] Setup security infrastructure as code (IaC) repositories

- [x] Setup Parabol infrastructure as code (IaC) repository to build Parabol application

**Comment by jordanh** [comment]
LGTM!

**Comment by mattkrick** [comment]
Clarifying Q: What does this get us over the free version? why managed instance over using cloud saas?

**Comment by adaniels-parabol** [comment]
@mattkrick

**Why managed instance over using cloud saas?**
The recommendation in this ticket is to use a managed instance of the SaaS, not the self hosted implementation.

**What does this get us over the free version?**
There are automation and management features not in the free version (e.g. k8s agent management, monitoring, ci/cd dashboard, etc) these are in the silver version here's a detailed list https://about.gitlab.com/pricing/gitlab-com/feature-comparison/
