### ISSUE TITLE
Add Hubspot properties per meeting type 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4390]
## Issue - Enhancement

We currently have a field in Hubspot called `Parabol Meetings Completed`. Among other things, we use this to trigger marketing automations after someone's first and second meeting. These introduce them to additional features and remind them to come back. 

Today, we assume the meeting they've run is a retrospective meeting, which is the bulk of meetings run on our platform. With the launch of Sprint Poker, we expect there will be more of a mix. 

I propose we create two additional fields: 
- Retrospective meetings completed
- Sprint Poker meetings completed

This will allow us to trigger automations more specifically and share more relevant content. 

### Acceptance Criteria (optional)
Parabol team can trigger Hubspot workflows based on the number of retrospective meetings, Sprint Poker meetings, total meetings that a user has completed. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
We’re going to icebox this one for now
