### ISSUE TITLE
Migrate db from rethinkdb to postgres

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4398]
## Issue - Enhancement

Let's talk about migrating our db from rethinkdb to postgres. Since rethink is no longer commercially supported, we aren't relying on it for realtime push anymore, plus mysterious performance issues, we'd like to move to postgres.

Since this is a big undertaking, we should break the work into stages.

**1. Choose a light weight "ORM"/tooling for migrations**
- [ ] decide upon tooling for migrating schemas, so we can have source of truth under version control
- [ ] choose a light weight ORM that supports typescript typing of db objects
  - regarding the above, i prefer writing SQL because:
    - it's more interoperable if we should change to some other SQL db
    - it's too easy to write inefficient queries otherwise, and you often end up having to look at the underlying SQL translation anyway
    - SQL is already declarative
    - developers use a generic skill (SQL) that is always going to be more useful and translatable to other things vs knowing the ins and outs of a particular ORM

**2. Get postgres up and running on dev, staging, prod, and cypress environments.**
  - cc. @adaniels-parabol 

**3. Any new tables going forward should be created in SQL**
  - should be easy to do with GraphQL

**4. Migrate rethinkdb tables to postgres**
  - can be broken into further tasks, with low priority tables going first and high priority tables (e.g. User) going last
  - migrating from NoSQL to SQL will not be 1to1
    - consider how to translate nested JSON data fields to SQL
    - may need to rethink (no pun intended) and reorganize our tables
    - migration itself may encounter errors, as we're going from a schema-less db to strict schema enforcing

### Acceptance Criteria (optional)
   - [ ] achieve consensus on the steps above
   - [ ] determine priority and timeline of steps above
   - [ ] opened new set of implementation issues that can be prioritized to further this migration along

- **Estimated effort:** 30 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tiffanyhan** [comment]
Example typescript orm with sql template literals and migration support: https://github.com/Seb-C/kiss-orm

**Comment by adaniels-parabol** [comment]
With regard to DOD efforts for IronBank/DSOP would it make sense to focus less on hardening RethinkDB container image, focus only on Parabol application container image, and await migration to Postgres before trying to harden the database container image in the future once migrated to Postgres. 

Note, there is already a Postgres v9, v10, v11, and v12 harden universal base image (UBI) so we would only need to select what version we would be using post migration. 

@tiffanyhan what version do you foresee us using?

One area of concern might be timing. If Postgres migration is approved, but pushed too far to the right, we could have self hosted Parabol instances by then, thus we would need to also create a easy method of DB migration for users who manage their own instance. Especially, disconnected systems in DOD, so they can maintain existing data.

@jordanh based on our DOD update cycle to the future Ironbank/DSOP container image we may have to version lock certain builds or do multiple release versions on Ironbank/DSOP with both RethinkDB and Postgres.

**Comment by jordanh** [comment]
@adaniels-parabol what would help us a lot here would be helping to size the effort of hardening the rethinkdb container image; that'll help our decision making

**Comment by jordanh** [comment]
Edited @tiffanyhan's comment to peg an EE for the sprint and tweak AC

**Comment by mattkrick** [comment]
closing in favor of #4496 so it's a bit smaller
