### ISSUE TITLE
Infinite loop in useEditorState

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4403]
## Issue - Bug

An infinite loop is being triggered in useEditorState which is causing retro meetings to crash. [Here's](https://sentry.io/organizations/parabol/issues/1641789488/?project=107196)🔒  the bug in Sentry.

This bug is affecting one of our paying users. You can find a log of the emails with the customer [here](https://app.hubspot.com/contacts/3888472/contact/9033151) 🔒 . 

### Acceptance Criteria

- [ ] Resolve infinite loop and prevent retro from crashing

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-3T0](https://sentry.io/organizations/parabol/issues/1641789488/?referrer=github_plugin)

**Comment by mattkrick** [comment]
any possible steps for a reproduction?
will be fixed by #4432
but it'd be great to confirm the fix

**Comment by nickoferrall** [comment]
Unfortunately not, this is the one that we had difficulty reproducing. 

The good news is that it looks like the bug hasn't returned since #4404 was released: https://sentry.io/organizations/parabol/issues/1641789488/?referrer=github_plugin

**Comment by jordanh** [comment]
Closing this for now. We can reopen or reference if we see it again
