### ISSUE TITLE
Group & Vote stage not showing all reflections

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4410]
A paying [user](https://app.hubspot.com/contacts/3888472/contact/9033151) 🔒  reported that their team can only see a few reflection cards on the Group and Vote stage. When they refresh the page, all of the cards appear.
 
The user gave the following repro steps:

> Whenever we create a new team, 
> and create a new meeting in that team, 
> and then I send out the link to my colleagues via chat so they can join.
> I get the "So and so person wants to join the team, 'Accept' / 'Deny'"
> I press "Accept" (maybe my other teammates also do the same.
> The meeting from each of our perspectives only see a few cards. <-- this is the issue
> We have to force refresh our browsers when we reach the voting stage so that we can all see all our cards.
> 
> I'm not sure if this is related or not to the previous bug. But they all seem to revolve around "new people being added to an ongoing meeting".

And gave the following answers to my questions:
> 
> 1. Are you all able to see all of the cards that you've created in the Reflect stage and then see everyone's cards in the Group stage but in the Vote stage, there are only a few cards? Or are there only a few cards in the Group stage too?
> 
> Few cards on Group Stage and Vote Stage. The cards are few until we refresh the page.
> 
> 2. Are the few cards that you see in the Vote stage the cards that you created or are they a mixture of different peoples' cards?
> 
> Hmmm... not 100% sure. could be a mixture, could be just mine.
> 
> 3. Are you able to see all of the cards until clicking "Accept" when someone joins the team? If no one joins the team, do you still only see a few cards?
> 
> When there is no one joining the team, there's usually no issue. we all see all the cards no problem.

**Comment by jordanh** [comment]
See also: #4386

**Comment by jordanh** [comment]
I believe this is now fixed by #4386. Closing this
