### ISSUE TITLE
Mattermost integration designed 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4412]
## Issue - Enhancement

[Mattermost](https://mattermost.com/) is a collaboration platform similar to Slack popular in the regulated market. We're contractually obligated to build a Mattermost integration for the DoD by 2021 Jan 01.

The first step to developing this integration will be to design it.

Related: #3538

### Acceptance Criteria (optional)
Users can:
   - CRUD Mattermost integration on their team
   - Notifications designed, mirroring today's Slack integration (at a minimum)
   - Set of implementation issues created

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
still a thing we are contractually obligated to do :upside_down_face:

**Comment by jordanh** [comment]
I've been doing some research in this area. Here's a design proposal.

# Mattermost Integration Proposal

## Overview

[Mattermost](https://mattermost.com) is a real-time message and collaboration service similar to Slack. 

![image](https://user-images.githubusercontent.com/103000/138159943-040beba9-d9f5-4c32-9f58-b33d32e11617.png)

Where Mattermost differs is it is open-source. It has become popular with institutions where private-hosted or single-tenant software is preferred to multitenant SaaS. As @enriquesanchez noted above, adding a Mattermost integration was the most popularly requested integration. In fact after parsing these same data, @avivapinchas found that Mattermost scored as the most-requested integration among the over 300 survey respondents.

### Adding integrations to Mattermost

Like Slack, Mattermost has a [marketplace](https://mattermost.com/marketplace/). However, unlike Slack many of these integrations need to be written as source-level plugins loaded on the user's system. For services which only require authenticated notifications be sent (like ours), Mattermost provides [additional mechanisms](https://mattermost.com/blog/mattermost-integrations-mattermost-api/) for authenticated incoming messages: [OAuth 2.0](https://developers.mattermost.com/integrate/admin-guide/admin-oauth2/), [personal access tokens](https://developers.mattermost.com/integrate/admin-guide/admin-personal-access-token/), and [incoming webhooks](https://docs.mattermost.com/developer/webhooks-incoming.html). Each of these facilities may be disabled by administrators, and only incoming webhooks are enabled by default.

To support a new generation of interactive, serverless integrations Mattermost is also developing a system they call [Mattermost Apps](https://developers.mattermost.com/integrate/apps/). It is currently in developer preview.

### Message format

Mattermost offers similar (and in many ways, superior) formatting options to Slack. Achieving functional and design parity with our current notification messages will not be an issue.

## Options

   1. `source plugin` – we can create a source-level plugin à la [this GitLab plugin](https://github.com/mattermost/mattermost-plugin-gitlab)
      - **Pros**: marketplace listing and marketing reach, paves road for future interactive functionality, understood by their users
      - **Cons**: another repo/architecture to support, longer to develop
   2. `oauth 2.0` – we could adapt our Slack design for Mattermost, and use a very similar Oauth 2.0 facility
      - **Pros**: straightforward patterns to follow, direct adaptation
      - **Cons**: would need new pattern for specifying which oauth facility to authenticate against (self hosting!); not all Mattermost installations enable the oauth 2.0 service—not everybody could use our integration
   3. `personal access tokens` ("PAT") – each user could add a personal access token to enable the integration
     - **Pros**: by manually adding a PAT we could still support a direct adaptation of the Slack design (i.e. we can get channel listings, send public and direct messages)
     - **Cons**: PATs are disabled by default, not every user could use our integration
   4. `incoming webhooks` – incoming webhooks post messages to a single channel, they are enabled by default
     - **Pros**: simplest to implement, we can send all team notifications with ease
     - **Cons**: too simple? Our Mattermost integration would only be a subset of what our Slack integration supports today
   5. `Mattermost Apps` – we can create a plugin that is as easy to install as `/apps install http http://prbl.app/integrations/mattermost/manifest.json`
     - **Pros**: paves the way for an interactive plugin service in the future, no 3rd-party repo or service to maintain
     - **Cons**: API is very much still in flux, users must install "apps" plugin first, requires Mattermost oauth 2.0 enabled, would require design to get started, and likely some sort of team access token to authenticate requests from Mattermost→Parabol
     
## Proposed direction

I propose we take approach #4: `incoming webhooks`. The two driving factors are:
   * Speed of development and time to market
   * Nearly every Mattermost can use it, out of the box, without making a request of their Mattermost administrator

Should we find a broad and welcoming audience, I propose we consider evaluating option #2 and/or #5 as possible future enhancements. We may find supporting multiple levels of integration advantageous to our users: all could at least use webhooks, while users on permissive enough systems could use the interactive capabilities provide via approach #5.

### Adding integration, configuration, and removal:

I propose the configuration panel looks like:

![image](https://user-images.githubusercontent.com/103000/138163709-e3974f75-c57e-4218-a466-8109343d0c4f.png)

Configuration is team-wide. All users share a single webhook configuration per team.

Removal is simply:

![image](https://user-images.githubusercontent.com/103000/138165039-1b41f6be-15cc-4704-bdb5-8fdc18efbe65.png)

Note: there is no token refreshment as there are no tokens to refresh.

### Notification types

Notifications should resemble what we emit today for Slack:

#### Start meeting

![image](https://user-images.githubusercontent.com/103000/138164457-6cb83e6b-6dc1-478c-98cd-da4228e566df.png)

#### End meeting

![image](https://user-images.githubusercontent.com/103000/138164546-45e958ac-f9ff-4814-a712-dbf84f06b5e2.png)

### Stage timer start

![image](https://user-images.githubusercontent.com/103000/138164708-ee1c5af7-d2b9-495f-a0d1-98c492106cc0.png)

### Stage timer stop

![image](https://user-images.githubusercontent.com/103000/138164801-c3595685-5711-4d8f-82af-12966fd5e749.png)

### Key differences from slack integration today

   - We do without the `SlackNotification` table, per-user configurations, and the ability to send some messages as private/direct messages and some as team public
   - We do without the ability for notifications to be sent to multiple channels (i.e. we do not provide an affordance to add multiple webhooks per team)
