### ISSUE TITLE
GitHub poker integration scoped

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4414]
### Burndown
- [ ] Users can add GitHub in a poker scope tab
- [ ] When users set a final score it’s added as a comment field

### Acceptance criteria
- Break this down into smaller design and implementation tasks

### Estimated effort
- 4 hours

**Comment by ackernaut** [comment]
### Parabol task cards already integrated with GitHub
**Open question**: I wonder what the user expectation is about a Parabol task card that is already integrated with GitHub? Would it show up in both tabs? Will the final task card look the same i.e. a GitHub issue added via poker looks like an integrated task card on the kanban added somewhere not in poker?

**Comment by mattkrick** [comment]
Scoped, going to mark this as complete when we have a "coming soon" frontend

**Comment by mattkrick** [comment]
this shouldn't be here: 
https://github.com/ParabolInc/parabol/blob/423edcdd111491991044b05fa86612ebcc6b6f50/packages/client/components/JiraScopingSelectAllIssues.tsx#L76

**Comment by mattkrick** [comment]
closed as we've got a lot of the jira components cloned & put a "coming soon" chunk in there for github
