### ISSUE TITLE
Integrated Parabol tasks designed for poker

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4415]
### Background

Is there a need to resolve the difference between a task card that is later integrated with Jira or GitHub and a story or issue that is imported via poker?

I asked the same question [re: Jira](https://github.com/ParabolInc/parabol/issues/4369#issuecomment-740883402) and over here [re: GitHub](https://github.com/ParabolInc/parabol/issues/4414#issuecomment-740880488) — I’m opening this to track a possible design decision.

### Acceptance criteria
- Discussed and made a high-level design decision (or close if no tension)

### Estimated effort
- 2 hours

**Comment by jordanh** [comment]
closing in favor of #4417
