### ISSUE TITLE
Designed: poker meetings show a total

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4418]
I’d expect to hear this feedback from folks sooner than later. It actually came up when we got feedback on the early UI concepts.

> When I’m estimating a set of stories for a sprint with my team, I want a total of the points so that I can compare that with our velocity and make sure we’re not taking on too much or too little

We’ve included this in the meeting navigation ([after the list of story stages](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb?node-id=3793:166811#160340330)) and in the summary ([at the top or bottom of the list of stories](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2647%3A3)) in earlier concepts.

### Open questions
- When and where do we display a total of estimated points?
- Do we show a running total while issues are still being estimated?
- How do we handle multiple dimensions? Do we somehow show a total for each? Do we only total the first dimension?
- How do we handle scales that have any non-numerical values? Do we only include a total for dimensions using a numerical scale?
- Should we allow the user to enter their team’s velocity for comparison with the total in the views and artifacts (i.e. summary email, timeline summary card, any summary notification in the future, etc.)?
- If we allow teams to enter their velocity, do we store the last used velocity on the team and auto-populate the next poker meeting? In theory a team could have more than 1 poker session open. Would they all share the same velocity, or once the meeting starts the only way it changes if you edit it? Each edit updates the team velocity? If folks are estimating a subset or milestone, they may not care about velocity. To keep it simple we could make it an optional field per poker session, that is only stored on that meeting, near the places where we show any total.

### Acceptance criteria
- Designed concepts addressing the open questions above. Where do we start?
- Proposed design details as a comment here with links to concepts
- Reviewed with a designer and developer
- Opened a placeholder implementation issue (linking to the outcome here) for a developer to write the acceptance criteria, and for the team to estimate

### Estimated effort
- 8 hours

**Comment by mattkrick** [comment]
we punted on velocity for now as some scales are non-numerical. 
i'm certain this will crop up again soon & we'll be able to mesh this with a 2 way story point sync & analytics of story point estimate vs actual story points

**Comment by ackernaut** [comment]
[This company](https://www.notion.so/parabol/Feedback-from-atsign-com-The-Company-d9faab4e89e7444cb4447b54c325f601) 🔒 would like to see the total and be able to enter their velocity

**Comment by mattkrick** [comment]
let's just tackle this in structured convos when we build out scoring phases
