### ISSUE TITLE
Scale editors show ? and Pass

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4419]
I think it would be a nice-to-have if folks could edit the colors of the ? and Pass cards. I can imagine some options to decide on:

- ? and Pass cards have read-only labels
- ? and Pass cards have the color picker
- They could be reordered?
- They can’t be removed? (it could be a toggle for these 2 since they are special)

My vote is that we pick the order and label. Folks can only pick the color.

Not sure the juice is worth the squeeze but it might help us think about how to enable limited options on templates in general.

### Acceptance criteria
- ? and Pass values show in the scale details view
- They are read-only; they can’t be removed
- They come after all values and can’t be sorted (e.g. 1, 2, 3, ?, Pass where 1, 2, 3 are sortable to a position before ? and Pass)
- Folks can change the color

### Estimated effort
- 12 hours

**Comment by mattkrick** [comment]
i like this. feels a little less magical than hiding them
we should prioritize this for the next sprint
