### ISSUE TITLE
Test ended poker meetings after changed template

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4422]
After a template has changed, we need to make sure that the old poker meeting is still accessible & works as a standalone artifact. Stuck on #4366

AC
- [ ]  change the template after the meeting ended. change the dimension name, delete a dimension. delete a few scale values. change their colors. after each change, check out the ended meeting. it shouldn't bork.

Estimate: 4 hours

**Comment by jordanh** [comment]
Noting that #4366 has been merged, this is not blocked

**Comment by mattkrick** [comment]
it all works...but i still don't love it.

in a perfect world, the dimensions, scales & values for a meeting would persist even after that meeting ended. Changing the value 3 from red to blue should keep it as red for old meetings. changing the dimension name should not change it for previous meetings.

if we wanted to go down this path, there are some options for how we store the data:
- we just store gosh darn everything on the meeting (wasteful)
- every new meeting created a new dimension & scale object (wasteful)
- each dimension & scale object has an `inactiveAt` trait. changing the object just creates a new one & sets the inactiveAt for the old one. (wasteful because it's possible that no meeting is attached to these)
- when a meeting is started, we clone the docs, point to them & make them immutable. if an immutable version already exists, we just use that one. (a little wasteful, minimum 2 docs per template, no edits once meeting begins. bug or feature?)
- if above is a bug, then we do it at the end of meeting. we take the current template, dimensions, and scales & clone them & adjust the meeting.

**Comment by mattkrick** [comment]
stuck on team feedback

**Comment by jordanh** [comment]
I think taking some inspiration from git would be useful. This might be restating what you've suggested, in a different way:

- Templates are like "files" in github, you can mutate them whenever you want
- Meetings are like commits, when you run you "commit" and create a `TemplateRef`
   - If no changes were made to the template between meetings, you refer to the `TemplateRef`, else you make a new one

**Comment by tianrunhe** [comment]
Thinking out loud here: what if we put a version number to those entities (template, dimension, scale) and then a pair of (id, version) uniquely defines a set of entities used in a meeting. When an attribute changes in one of those versioned entities, we increment the version.

**Comment by tiffanyhan** [comment]
```
each dimension & scale object has an inactiveAt trait. changing the object just creates a new one & sets the inactiveAt for the old one. (wasteful because it's possible that no meeting is attached to these)
```

so no meeting is attached to some bc a new template is made each time an object is changed? what if we only create a new one if a meeting is started or ended, and the template is different from the one previously used? singling this suggestion out bc it seems the most intuitive to me

**Comment by mattkrick** [comment]
i love this thread so much. i think we're all saying the same thing in different ways!
- version bumping must occur on meeting start (or meeting end) because if we do it on entity change then we'll be creating versions that aren't ever used.
- we have to have a minimum of 2 versions (the one used for the meeting & the mutable one to be used in the future)

this stuff is probably pretty useful for retrospectives, but i figure poker meetings are new & more complicated so let's try it out there & see how it works.

Start vs. End
- doing this on end gives us the advantage of letting folks change the template mid-meeting. however, that means we have to support in-meeting changes. it also means that the meeting has to support a bivariant template (either a template or templateRef). 
- doing this on start means a meeting can point to a single Instance, but if we do ever want to support in-meeting changes, we'll have to change the template as well as the `TemplateRef` for all currently active meetings.

**Comment by mattkrick** [comment]
stuck on postgres implementation. no sense in creating a new `TemplateRef` table in rethinkdb right now

**Comment by mattkrick** [comment]
- scaleValue = {color, label}
- scale = {scaleValues, name}
- dimension = {name, scale}
- template = {name, dimensions}

AC
- [ ] A TemplateScaleValueRef table exists with 2 cols: color & label
- [ ] A TemplateScaleRef table exists with 
- [ ] A TemplateRef table exists in PG
- [ ]

**Comment by mattkrick** [comment]
Migration checklist:
- jiradimensionfield replace dimensionId with dimensionRefIdx
- for every poker meeting, grab the template & persist it in the DB
- add templateRefId to every poker meeting
