### ISSUE TITLE
Explore replacing cypress with playwright

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4431]
i hate bouncing all over the place with testing, but tbh the current testing solution is bad. it's riddled with race conditions & there isn't a clear path forward for how we should reset the DB.

https://github.com/microsoft/playwright has gotten a lot of attention. we should investigate

**Comment by mattkrick** [comment]
holy shit this is amazing.
the API uses async/await, unlike cypress' strange implicit async method chaining.
it doesn't use electron, which has been proven to be the source of at least some of the race conditions.
it supports chromium, firefox, & webkit across all the 3 OSs (useful for scrollbar testing!)
we can open multiple headless browsers to test subscriptions.
we can intercept/mock network requests for pure front-end testing (not sure if we can do server-side intercepts though)

i'm completely in favor of moving from cypress to this. how to reset the DB between tests, or if we should, is still tbd.

**Comment by mattkrick** [comment]
i think playwright is still the way forward, but we need to prioritize writing some tests for it first

**Comment by mattkrick** [comment]
@Dschoordsch @BartoszJarocki here's an in-memory postgres which might help for testing: https://github.com/oguimbal/pg-mem

**Comment by jordanh** [comment]
We did this. Thank you @blimmer
