### ISSUE TITLE
Agenda Items from previous meeting mysteriously show up in new meeting 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4436]
## Issue - Bug

We run a weekly check-in meeting with our PR team. This week, when we started the meeting, we noticed a bunch of agenda items from the previous week's meeting: 
<img width="804" alt="Screen Shot 2020-12-11 at 10 35 21 AM" src="https://user-images.githubusercontent.com/11621016/101955436-65f2bb00-3bc3-11eb-9f4b-0ef40b38fd53.png">

I took the above screenshot after we'd gone through those items, but they were _not_ initially crossed out. They were at the top of the ageda (we moved some things around) and they were not pinned. 

It also didn't seem like we'd ended up in the old meeting, because we ran through the Icebreaker and Solo Updates phases as normal - no indication that we'd jumped back into a meeting with those phases completed. 

I wanted to see if maybe we hadn't closed the previous week's meeting, so I went to the Timeline. I saw an entry for the previous week's meeting, as expected, but when I clicked on See the Discussion, I got an error: 
<img width="546" alt="Screen Shot 2020-12-11 at 10 35 42 AM" src="https://user-images.githubusercontent.com/11621016/101955572-abaf8380-3bc3-11eb-8666-f3f8e02c718e.png">

### Acceptance Criteria (optional)
Users can:
   - Enjoy a check-in meeting without seeing previous meeting's agenda items

**Comment by jordanh** [comment]
We haven't seen this one for a long while. I'm going to close. We'll reopen if we see it again.
