### ISSUE TITLE
Sprint poker: which events?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4437]
This is a placeholder discussion.

Do we have all the segments events in place we'd like to launch with to understand what's working and what could be better?

**Comment by mattkrick** [comment]
@avivapinchas what segment events would you like to see?

**Comment by avivapinchas** [comment]
This question is my love language 😄 

Thinking about what questions we want to answer here, I think it comes down to: 
- Where (if anywhere) do users get stuck along the way? 
- What features are being used? 

Going through the flow of running a Sprint Poker meeting, here's what I'm thinking, in somewhat stream of consciousness: 
**1. Facilitator starts meeting** 
We don't have a `Started meeting` or `joined meeting` event for other meetings (requested: #4109), which would be nice-to-have. We can use `Loaded a page` includes `meet`, though we can't separate that by meeting type. 
**2. Facilitator chooses a template** 
We have a bunch of events around this: 
![Screen Shot 2020-12-15 at 1 13 51 PM](https://user-images.githubusercontent.com/11621016/102262556-e45b9f80-3ed8-11eb-95d4-f1df156ba248.png)

I _think_ these should be sufficient, but I find them super confusing. Could we write up a definition of what each of these means / points to? 

**3. Facilitator adds stories from Jira or Parabol** 
We already have `Added Integration` - I think we should probably trigger the same event for connecting Jira here. 
We could look at what queries they're running to find and pull in stories, but that feels a bit complex to me - I'm not sure what we would change based on having this info. 

We should add `Added stories`, and include something like `source` to know whether those stories are from Jira or Parabol. This would be for adding them into the scope of the meeting. This feels important. 

**4. Team joins and votes** 
I think for most of these behaviors, we already have ways of seeing if they did the thing: 
- Added comment - exists
- Added task - exists
- Going to this phase - can be done with `loaded a page` where `url` contains `estimate` 

So the missing things would be: 
- `voted` - we could use this across both Sprint Poker and Retros, maybe with some parameters telling us if they used questions or pass. 
- `revoted` - this feels important to know 

**4. Facilitator ends meeting** 
We have the `meeting completed` event for this, which includes meeting type, template, hasIcebreaker, and isFacilitator, so I think we're covered here.

**Comment by tianrunhe** [comment]
@avivapinchas Replies in line:

> **1. Facilitator starts meeting**
> We don't have a `Started meeting` or `joined meeting` event for other meetings (requested: #4109), which would be nice-to-have. We can use `Loaded a page` includes `meet`, though we can't separate that by meeting type.

I think we can add that! Which attributes would you like to see in this event?

> **2. Facilitator chooses a template**
> We have a bunch of parameters around this:
> ![Screen Shot 2020-12-15 at 1 13 51 PM](https://user-images.githubusercontent.com/11621016/102262556-e45b9f80-3ed8-11eb-95d4-f1df156ba248.png)
> 
> I _think_ these should be sufficient, but I find them super confusing. Could we write up a definition of what each of these means / points to?

I suspect those were legacy attributes. We only publish `meetingTemplateName` today.

> **3. Facilitator adds stories from Jira or Parabol**
> We already have `Added Integration` - I think we should probably trigger the same event for connecting Jira here.
> We could look at what queries they're running to find and pull in stories, but that feels a bit complex to me - I'm not sure what we would change based on having this info.
> 
> We should add `Added stories`, and include something like `source` to know whether those stories are from Jira or Parabol. This would be for adding them into the scope of the meeting. This feels important.

Some thoughts here:
1. The word "add" is a little ambiguous here. In the scope phase, user can _create_ a new story or _select_ a story for estimation next (for both Jira and Parabol). I assume we are more interested in latter?
2. Looks like today we are publishing events from _server_ side. Selecting a story to proceed to estimation phase is a _client_ side behavior hence not very easy to track. We can include sth like "number of stories estimated" in the Meeting Completed event though.

> **4. Team joins and votes**
> I think for most of these behaviors, we already have ways of seeing if they did the thing:
> 
> * Added comment - exists
> * Added task - exists
> * Going to this phase - can be done with `loaded a page` where `url` contains `estimate`
> 
> So the missing things would be:
> 
> * `voted` - we could use this across both Sprint Poker and Retros, maybe with some parameters telling us if they used questions or pass.
> * `revoted` - this feels important to know

1. We can publish voting events, no technical difficulty there. However this seems very easy to grow too big:` # of stories/reflection groups * # of team members * # of revotes per user * # of meetings`.
2. In Poker meeting, as an individual you can revote as many times as you want to until all of the votes are revealed. This individual level behavior is tracked in the voting events already if we choose to implement that. There's also a "Team Revotes" link people can click after all the votes are revealed:

<img width="520" alt="Screen Shot 2020-12-16 at 11 24 47 AM" src="https://user-images.githubusercontent.com/1879975/102396952-14b34480-3f92-11eb-924b-d8b481984354.png">

I think that's what we really wanted to track? Because that basically means the previous round of voting does not consent. This single metric is pretty easy to implement.

**Comment by avivapinchas** [comment]
> Which attributes would you like to see in this event?

The useful attributes would be: 
- hasIcebreaker
- meetingType
- meetingTemplateName
- meetingTemplateSharing - this is a new attribute that would also be helpful on `meeting completed`, and the possible values would be team, org, or public. It would be helpful to know how often folks are using default templates, vs org-specific ones, vs things they're making themselves. 
- meetingNumber 
- orgID
- teamID
- wasFacilitator

> I suspect those were legacy attributes. We only publish meetingTemplateName today.

Gotcha, so we should probably clear these out of Amplitude. 

Besides having something like `meetingTemplateSharing` on start and completed events, it would be helpful know when folks are creating and sharing templates. The events I'd imagine are: 
- templateCreated - attributes would be templateType (sprint poker or retrospective), templateName
- templateCloned - attributes would include templateType (sprint poker or retrospective), templateName
- templateShared - attributes would be templateSharing (org or public)
- scaleEdited - I'm not sure if this is quite the right event, but something to tell us if folks are creating custom scales for sprint poker as well as custom templates

> The word "add" is a little ambiguous here. In the scope phase, user can create a new story or select a story for estimation next (for both Jira and Parabol). I assume we are more interested in latter?

Yep, that's true! 

> Looks like today we are publishing events from server side. Selecting a story to proceed to estimation phase is a client side behavior hence not very easy to track. We can include sth like "number of stories estimated" in the Meeting Completed event though.

🤔  What I want to be able to do is create a funnel from started meeting > selected stories > voted > completed, to see if there's a spot where folks are getting stuck along the way. But I suppose I can accomplish that by just seeing if they viewed each of the screens, so this might be fine. 

> We can publish voting events, no technical difficulty there. However this seems very easy to grow too big: # of stories/reflection groups * # of team members * # of revotes per user * # of meetings.

Yea, that's probably not worth it. 

> I think that's what we really wanted to track? Because that basically means the previous round of voting does not consent. This single metric is pretty easy to implement.

Yep! Want to see if they do 'team revotes', meaning wipe and start again. Not as worried about how much individual team members click around before they make their decision.

**Comment by tianrunhe** [comment]
The `wasFacilitator` field for Meeting Started event seems redundant to me: whoever starts the meeting will be the facilitator by default. I think one major difference between a Meeting Started event vs. Meeting Completed, is that the former only publishes once event per meeting whereas the latter publishes as many events as the number of meeting members. I can add a separate Meeting Joined event though. WDYT @avivapinchas ?

**Comment by tianrunhe** [comment]
I'd also like to know how you would use the `templateName` field as:
1. It's not a unique field so not useful for joining in queries
2. Particularly not quite useful in templateCreated and templateCloned events, as the name will always be "* New Template" or "XXXX Copy"

Should we use `templateId` instead?

**Comment by avivapinchas** [comment]
>  I can add a separate Meeting Joined event though. 

Makes sense! 

> I'd also like to know how you would use the templateName field as:

Ah this is a very good point! So for right now, we've used the `templateName` attribute in `meeting completed` for the data in posts like this: https://www.parabol.co/blog/share-custom-retrospective-templates 

What I really want is to be able to browse around and be inspired by template ideas, but maybe this isn't the best way to accomplish that?

**Comment by tianrunhe** [comment]
I see. Here's my $0.02:

For events around template actions (creation/clone/deletion...), it's more about the user who performed the action, so a `userId` and a `templateId` seems good enough to me and by linking the `userId`, you can already get complicated analysis for things like "people who have created a template him/herself have had more meetings than others". 
For template names, they only make sense when the template is used in an actual meeting. I can create a template, rename it, add more prompt questions etc but until it's being used in a meeting, it's incomplete. So I'll keep the template name attribute in the Meeting Completed event. And to address the specific concern of "how many meetings are run by Parabol template vs. custom template", I'll add a boolean attribute `meetingTemplateIsFromParabol` so you can easily slice the events on that and it'd be future proof when we add more Parabol templates.

**Comment by avivapinchas** [comment]
That makes total sense to me! Thanks for talking this through :)
