### ISSUE TITLE
Slack timebox notif includes timezone

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4443]
Our timebox notif is pretty helpful, it gives the team, meeting name, phase. But since we’re all over the place it could use a timezone. I’d be okay with the UTC offset. I can imagine there’s a library that will return something like CST or CDT if we want to get fancy. E.g. currently it only says 12:30 sans timezone info:

>The Reflect Phase for Sprint 70 on Product has begun!
You have until Dec 23 at 12:30 to complete it.
Check it out: [meeting link]

### Acceptance
- [ ] Slack timebox notif includes some type of timezone info, formatting TBD

### Effort
- 3 hours

**Comment by mattkrick** [comment]
that message is customized to the timezone that you have selected in slack :wink:
feel free to re-open if this doesn't solve the tension

**Comment by ackernaut** [comment]
Ah, do you mean it will show the person their local time?

**Comment by mattkrick** [comment]
<img width="468" alt="Screen Shot 2020-12-15 at 10 26 52 AM" src="https://user-images.githubusercontent.com/5514175/102259607-2a5a3880-3ec4-11eb-98dc-aef3e817c370.png">

**Comment by ackernaut** [comment]
@avivapinchas the times are local to the viewer 🎉

**Comment by avivapinchas** [comment]
Oooh that's cool! That's almost too smart for its own good
