### ISSUE TITLE
Timer UX discussion

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4448]
Currently, we’ve excluded the timer from Sprint Poker. We have questions and thoughts around use cases across meetings and around changes to implementation (e.g. timers at the phase level vs stage level).

### Acceptance criteria
- Discussed use cases across meetings
- Discussed implementation details
- Wrote implementation issues (e.g. for Poker behaviors, for refactoring, etc.)

### Estimated effort
- 4 hours

**Comment by ackernaut** [comment]
I’m going to be brief here to revive this discussion which was started in Slack etc. and shoot to my best, latest thinking:

Looking in [Amplitude](https://analytics.amplitude.com/parabol/chart/agp34gr) the timer is used most in reflect followed by discuss, vote, and group phases. Given there’s decent usage in the discuss phase suggests that folks set a timer per topic or some topics (maybe they anticipate topics that need the time constraint).

With that in mind, I could assume a case for folks wanting to limit the time they discuss the score in Sprint Poker so that they can try to reach an agreement if they have a problem on their team of discussing too long. Based on user feedback, I don’t think that’s everybody but it could help the folks who need it. So I could see the case for keeping the timer per stage.

One caveat is that if we add the timer control to the bottom bar we will be up to 4 controls (tips, timer, next, end) as we’ve constrained the bottom bar to have a max of 4 controls per Material Design and mobile-first designs. The controls to reveal votes or reset votes should remain in the dimension column context (this is my opinion anyway). Participants would still have room for a ready control (i.e. ready to finalize a score and move on).

Proposal: adding a timer to the bottom bar for the facilitator in Sprint Poker Estimate is safe to try

**Comment by ackernaut** [comment]
P.S.

One use case I was interested in, but is speculative, is if folks might want to set a timer or timebox across a phase that has many stages. E.g. take 10 minutes to vote on all poker stories, then we’ll discuss — or — you have until Friday to vote async, then we’ll discuss.

There’s almost a hack, the facilitator could set a timer or timebox on the first stage. However, when the facilitator moves to the next stage it ends the timer or timebox on the previous stage. They may move forward to participate for themselves in async. Folks who have navigated elsewhere might become tethered to the sync facilitation again and be taken away from the stage they wanted to view. Solutions to problems create more problems.

I’m not sure we’ve had anybody ask for a timer over a phase of stages yet so we should probably wait for that feedback. In the meantime, adding a timer to the Estimate phase would give us more surface area and data for the UX cases.

**Comment by jordanh** [comment]
> I’m not sure we’ve had anybody ask for a timer over a phase of stages yet so we should probably wait for that feedback. In the meantime, adding a timer to the Estimate phase would give us more surface area and data for the UX cases.

Suggest next steps:
- Open the implementation issue
- Let's defer until we're asked *or* we're reaching for a BP

**Comment by mattkrick** [comment]
yep, next step is to write an issue to migrate the timer from a stage to a phase. then we can add it to the poker meeting

**Comment by ackernaut** [comment]
> yep, next step is to write an issue to migrate the timer from a stage to a phase. then we can add it to the poker meeting

Question: when you say migrate from a stage to a phase, do you mean for all meetings, all phase types?

I was suggesting above that per-stage works for the Estimate phase. In that case, the minimal lift here, if we implement anything, would be to add it to the Estimate phase as it works today. The same logic would apply to the Team Agenda phase, too, but that tension is way lower. The logic is based on the way folks use it during Retro Discuss today.

**Comment by mattkrick** [comment]
i think the question to ask is what is the average number of concurrent discuss stage timers running for a given meeting? my hunch is that folks set the discuss timer 1 at a time, in which case the phase timer would actually be better.

**Comment by ackernaut** [comment]
Yes, that’s all they can do. If they change Discuss stage items it stops the timer for the previous stage. They have to start it per stage.

Having 1 timer that can be used again and again at the phase level handles all cases, I believe (e.g. in Reflect, they could start the timer once for each column if that’s their style).

What we lose is that the timer lingers when switching stages (e.g. Discuss topics) — it was a nice feature. What we gain is that the timebox could be set for a phase of stages to allow folks to do the activity across those stages in async which is unvalidated and not request yet TMK. If we try that today the facilitator would stop the timebox when they move forward to participate async.

Nuance: we would still have an edge case where if anybody goes to estimate in async but the facilitator happens to be there they might get tethered. Bad idea: we could turn off tethering when a timebox is active.

All that being said, the easiest path forward is just to add it as is, per stage, until we know more or hear from folks. The Estimate phase has been the first place where I thought timeboxing across the phase might be reasonable.

**Comment by ackernaut** [comment]
Having the timer lingering across stages shouldn’t be too bad. If they get to 5 minutes and move on they’d have to add minutes or currently start a new one, so it requires an interaction either way.

**Comment by ackernaut** [comment]
@mattkrick one idea occurred to me, if we move to a per-phase model, we could capture the stage ID whenever a timer is set. That way we could still learn about timer behaviors per stage.

**Comment by ackernaut** [comment]
Closed and new implementation issues added #4608 and #4609 — I think we defer until there’s user validation
