### ISSUE TITLE
User replicated 3x

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4459]
[An email](https://app.hubspot.com/contacts/3888472/contact/9033151) 🔒  from a paying customer:

> We have 3 [email redacted] accounts in parabol. The screenshot only shows 2, but there's another same one much lower. When I deactivated one of them (coz I don't want to pay triple for one user), it deactivated all three at the same time.

### AC

- [ ] Triage bug
- [ ] Remove replicated users from paying customer account

**Comment by gcrickman** [comment]
This may be a separate issue but for the same client still occurring:

> We still notice the bug occurs whenever we add a new person to the team in the middle of a meeting. We have a lot of interns (about 20 at any given time) and there’s always someone leaving and someone new joining the company every week. 
> 
> So it’s a regular scenario for someone new to join the meeting as they get sent the meeting link. We see the “Mr. new person is requesting to join the meeting. Accept. Deny” (or something like that) while in the middle of the meeting. When one of us (or many of us) press “Accept”, errors start happening. 
>

**Comment by nickoferrall** [comment]
I've created a PR for this replicated user bug (#4541) but the page freezing is likely a separate issue so I've created a new issue for that (#4542)
