### ISSUE TITLE
Sprint Poker nuances

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4463]
I gave Gareth a demo of Sprint Poker and we noticed a few things:
- The score comments on the Jira item link back to the first stage of the Estimate phase instead of the stage of the story. I suppose this is okay because folks could set a score as a comment and later change the order of stories in the left navigation making the exact URL wrong. If we were to use the exact stage URL in the comment how likely would it be correct? I’d assume folks might add a few stories later, or sort before they start estimating, but not sort much during the Estimate phase.
- Edits to the Parabol task card at the top of the Estimate stage view don’t persist
- The empty stage copy in the thread mentions tasks but only comments are enabled here
- Interrupted navigation when voting independently #4462

**Comment by ackernaut** [comment]
@mattkrick what do you think about the first bullet? It seems like we’d get them to the exact URL most of the time, no?

**Comment by mattkrick** [comment]
definitely a bug. will push a fix direct to staging soon

**Comment by mattkrick** [comment]
fixed!
