### ISSUE TITLE
Automate SAML Upgrades

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4473]
Too much engineering effort is being spent on SAML, so we should automate it.
This builds on the work that @tiffanyhan specced out here: https://github.com/ParabolInc/parabol/pull/4440#issuecomment-747773692

We've got 4 ways to verify a domain:
- cname
- txt record
- upload a file to that domain (e.g. foo.co/parabol-verification.txt)
- manual approval process (ie a human sniff test)

I think we've got to at least support the TXT record & the manual way.

Here's what I propose:
- There is a SAML form in the app. It accepts metadata & a list of domains. If an app is in progress (ie the record already exists, then it just shows the verification token & how to)
- The metadata gets *safely* (it's XML, here there be dragons) parsed & verified on the server. if it looks good, we create a SAML record with 0 domains. we extract the login/loguout urls & the x509 from it. we create a samlSlug from the first domain (e.g. /saml/parabol would be parabol)
- A new row is created for each SAML domain. They each include a token & a verified flag per @tiffanyhan's spec. It also includes the samlSlug in case 2 companies are fighting over the saml domain name
- a mutation exists called `verifyDomain(domain, samlSlug, method)`. if the method is txt, it checks the DNS. if the method is File, it curls the file. if the method is manual & the caller is a superuser, it just accepts it (this will be the first & most popular method i bet). When a domain gets approved, it gets added to the SAML.domains array

@tiffanyhan let me know if this looks good & we can start prioritizing it

AC
- [ ] flow is verified & everything looks sound. good enough for a designer to build out the UI

Estimate: 8 hours

**Comment by tiffanyhan** [comment]
Yup this sounds great!

**Comment by jordanh** [comment]
Scrubbed. Still a goody, will reopen when SAML configuration becomes burdensome again (i.e. too much workload)

**Comment by mattkrick** [comment]
Reviving this because the tension is so high @drewhousman1010 wrote a governance proposal: https://www.notion.so/parabol/Product-Circle-Governance-f1c31fc9915b46e38708d49fc6d1f10d?p=8af18653b8f14399b855048cfb70681b
