### ISSUE TITLE
Security Issue #61

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#4474]
## Issue - Security

See: https://github.com/ParabolInc/action-devops/issues/61

- **Estimated effort:** T.B.D per environment ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
   - See: https://github.com/ParabolInc/action-devops/issues/61

**Comment by jordanh** [comment]
Iceboxing on this backlog (but it will remain open on action-devops)
