### ISSUE TITLE
Profile photo is stored in S3 twice

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#4476]
**Issue**
Profile photo is stored in S3 twice. The issue appears to upload the users profile photo to S3 twice.

**Screenshot**
Screenshot shows the same profile photo with different object names, but uploaded twice. If you download the images and MD5 the file the hash is the same for each file, thus a duplicate. I found this in a few folders I spot checked.

![duplates in s3](https://user-images.githubusercontent.com/71724289/102926429-973c7800-445a-11eb-9a8e-1b6e43e8cc9e.JPG)

**Comment by jordanh** [comment]
Iceboxing for now
