### ISSUE TITLE
Carousel scrolls to different meeting type after changing team 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4484]
## Issue - Bug

In the new meeting carousel, I'll first scroll to the meeting type, and then change the team. _Sometimes_, when I change the team, I'll scroll to a different meeting type. Looks like this might happen when I select Sprint Poker, but I didn't notice what was consistent about this behavior - it happens _sometimes_. 

Here's a video: https://www.loom.com/share/59c7a58380764b02822994f9ea88a731 

### Acceptance Criteria (optional)
Users can:
   - Select a meeting type from the carousel, then change the team, without the selected meeting type changing

**Comment by mattkrick** [comment]
it's not a bug it's a feature 😄 

let's say your product team _only_ runs check-in meetings.
and your growth team _only_ runs retros.
well, when you select your product team, it will think, "hey, last time you ran a check-in meeting, so i'll set it to that".

in a perfect world, the team dropdown should be selected first & then the meeting type. this is done automatically if you click the "start meeting" button from your team dashboard.

we _could_ implement something that says "if they already changed the meeting type, when they change their team, don't change the meeting type". i'm just not sure how many folks bump into that under the assumption that they enter via the team dash 🤷

**Comment by avivapinchas** [comment]
Ooh interesting! So I took a look at this in GA - looking at what the 'previous page' was for any views of pages with 'new meeting' - and here's what I'm seeing: 
![What page came before 'new meeting'_ ](https://user-images.githubusercontent.com/11621016/103691944-aa703d00-4f5c-11eb-8464-ac3982918ac8.png)

Looks like the plurality of views follow that behavior - 44% come from a team page - but the majority do not. 'New meeting' is when someone switches teams on the page (that'll show a new page, with a new unique ID), so that's about 24% of views, and then 18% of views come from the timeline.

**Comment by tianrunhe** [comment]
Here's my proposed solution:
1. When user enters the meeting lobby, it automatically display the last meeting type for that team (i.e., if you comes in from _product_ team dash, you will see the last meeting type for _product_ team)
2. If user changes team in the meeting lobby, the meeting type stays unchanged

What do you guys think?

**Comment by avivapinchas** [comment]
So if I change the meeting type, then change the team, my meeting type won't change? 

If I'm understanding that correctly, that makes sense to me 👍

**Comment by tianrunhe** [comment]
Yes that's correct!

![2021-01-06 11 43 00](https://user-images.githubusercontent.com/1879975/103813235-9a1b9900-5014-11eb-8a62-5a0646ed3926.gif)
