### ISSUE TITLE
CSV export malformed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4489]
## Issue - Bug

[A user](https://app.hubspot.com/contacts/3888472/contact/16890601/) 🔐  (see 🎟️  [#272804875](https://app.hubspot.com/contacts/3888472/ticket/272804875/)) reports an export of their meeting data is corrupt:

> The .csv file I get from Parabol does not seem to be formatted correctly and is not useful for examining meeting summaries in Excel. It appears to be one line (that does load into Excel, but not in a meaningful way). Is this expected?

### Acceptance Criteria (optional)
Users can:
   - Triaged and fixed or,
   - Triaged and new implementation issue opened

**Comment by tianrunhe** [comment]
![tumblr_002d2f70f4414e839c946444d982e897_06c2920c_400](https://user-images.githubusercontent.com/1879975/103687325-f2836580-4f44-11eb-9d6b-3ec48222a608.gif)

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/19816351/) 🔒  writes via support: 

> CSV Export of Meeting Review only displayed in one line
> Message: Hello everyone, When holding retrospective meetings with my teams I usually export the meeting summary as a CSV to be able to easily document it in Confluence. However, when I tried this for the meetings this year all the data was just pasted into one single row.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/3935301) 🔒  says:

> when you export to Excel it comes out as one line and it's difficult to read

**Comment by jordanh** [comment]
@tianrunhe marked this as Done on the sprint board, closing for now
