### ISSUE TITLE
Retro demo crashing on Android

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4490]
It looks like `flatMap` may be causing the demo to crash in the `/reflect` stage of the demo on Android 

https://sentry.io/organizations/parabol/issues/2110046972/?referrer=github_plugin

**Comment by nickoferrall** [comment]
This is likely a webpack issue. The issue surfaced after upgrading to webpack 5 where automatic [polyfills were removed](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed). It [looks like](https://stackoverflow.com/questions/55530690/javascript-flatmap-method-over-array-flatmap-is-not-a-function) the polyfill `core-js/stable` is required for some browsers to be able to use `flatMap`

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-4V9](https://sentry.io/organizations/parabol/issues/2110052718/?referrer=github_plugin)

**Comment by jordanh** [comment]
Discussing with @mattkrick, the root issue is do we want to support old browsers? I don't think we want to add polyfills.

If we don't want to support old browsers, has the time come for us to pop a modal saying, "hey, your browser is too old."

Labelling as discussion and assigning to @nickoferrall to lead this discussion to a resolution.

**Comment by nickoferrall** [comment]
Created a discussion and resolved it with a new issue
