### ISSUE TITLE
Add a dropdown box when the overflow chit is clicked

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4494]
​AC
- [ ] when a user clicks the overflow chit (e.g. +2) in the team member avatar list, it opens up a small modal that has a list of all the team members (or meeting members, depending on context).
- [ ] the avatar is on the left & the name is on the right
- [ ] the list auto-scrolls to the first person who is not visible in the list
- [ ] the list isn't paginated, it just shows all the team members (for now)
- [ ] it includes the administrative options per member item (e.g. remove from team, promote to team lead, etc.)

**Comment by ackernaut** [comment]
We could think about the user menu pattern from #4916

**Comment by ackernaut** [comment]
I believe at least one user wrote in stating they couldn’t access a way to remove a team member. That team member could’ve been in the overflow on the team dash.

**Comment by mattkrick** [comment]
^^^ worth noting that the overflow avatar was only added a couple weeks ago, so it's a rather recent functionality regression. probably good to tackle before too many more sads come in

**Comment by ackernaut** [comment]
I’ll add this as a 20% stretch since I’ll be looking at user-based menus in #4916

**Comment by ackernaut** [comment]
Closing in favor of #5002
