### ISSUE TITLE
Include Postgresql in our bundle

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4496]
AC
- [ ] add postgresql to the dockerfile 
- [ ] add instructions to the readme on how to get postgresql setup as a docker contianer
- [ ] add `pg` to the server package so we can start writing to the postgresql database
- [ ] add a singleton driver similar to the rethinkdb and redis drivers that opens a connection when first called & reuses that connection after that
- [ ] DevOps backlog issue created to add Postgres to our other environments
- [ ] 
Estimate: 16 hours

**Comment by tiffanyhan** [comment]
**API Considerations:**
- SQL even over query builder
  - when query builders translate to SQL, the resulting SQL can be *very* unintuitive and difficult to parse. debugging and optimization will be easier if we work with the SQL we wrote by hand
  - as a developer, i just wanna write SQL or a SQL dialect, not a collection of one-off methods i'll probably never use again outside of this project
- Data Mapper even over Active Record
  - the downside is more boilerplate and complexity, but the upsides are proper separation of concerns
  - data mapper upholds the Single Responsibility Principle, which will make our code more flexible (e.g. should be helpful as we migrate across data stores)
  - active record is simpler and good for MVPs, but I suspect Parabol needs something more sophisticated where each layer is distinct for better scaling
  - active record results in overly fat models that try to do everything in one... this model will prove fragile as the codebase grows
- No automatic implicit eager loading
  - loading relationships should be explicit
  - in my experience working with RoR and Django, eager loading can easily spiral out of control and result in performance nightmares that take a long time to step through and debug
  - in RoR and Django, eager loading is default and can be explicitly requested to turn off. i believe the opposite should be true
- Cascades
  - this is another instance of automatic implicit behavior which can be enticing to use in the beginning, but may bring about frustration later
  - still on the fence about this one, but we may be better off doing away with them and doing everything explicitly

**Comment by mattkrick** [comment]
explicit & expressive are my favorite traits!
my favorite DB APIs are old, boring, and predictable. Surprises at the data layer scare me.
let's stick with `pg` for this first chunk & if we need something more we can adapt from there

**Comment by tiffanyhan** [comment]
https://jawj.github.io/zapatos/#what-does-it-do

**Comment by mattkrick** [comment]
oh that's a fun find! i really like how it's types only, no ORM attached. i've been looking for something like that!
it floors me that it only has a couple hundred stars on GH. i wonder if there is a more popular alternative? i find it so hard to believe that millions of folks who use typescript + postgres don't have a tool like this in their kit

**Comment by tiffanyhan** [comment]
done in #4580
