### ISSUE TITLE
Allow template creators to adjust visibility

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4505]
It feels bad that someone who creates a template can't change the visibility of it.

AC
- [ ] each MeetingTemplate that is created has a `createdBy` which has the userId of the person who created the template
- [ ] a migration exists to populate `createdBy` with the team lead userId
- [ ] a user can change a template's visibility if they are the team lead OR if they created the template

Estimate: 8 hours

**Comment by jordanh** [comment]
Making implications of this clear, quoting @mattkrick from #4757:
> Here's my recommendation:
>
> - Team Member: can create new (including clone)
> - Template creator: all of above + share & delete
> - Team lead: all of above

**Comment by jordanh** [comment]
Related to #5887
