### ISSUE TITLE
Meeting tips remain open until dismissed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4507]
## Issue - Enhancement

A user wrote:

> We didn’t notice the tips until the 2nd or 3rd screen. That level of guidance should be the default your first time through the system. For example, folks when down a rabbit hole on how to vote. I advocated not to change the default. Would have been great to see the tip for this.

### Acceptance Criteria (optional)

   - The tip box is _always_ expanded until they dismiss it, thus instructing them that the tip box exists
      - Dismissing the tip box on a demo meeting does not count

- **Estimated effort:** 8 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Clarifying question: do you mean it always expanded until the first time they dismiss, then after that they’d have to open it again (i.e. it changes back to the current behavior)? That’s how I take it but it could be understood the other way.

**Comment by jordanh** [comment]
> Clarifying question: do you mean it always expanded until the first time they dismiss, then after that they’d have to open it again (i.e. it changes back to the current behavior)? That’s how I take it but it could be understood the other way.

Correct!

**Comment by jordanh** [comment]
Scrubbed and iceboxing
