### ISSUE TITLE
Design "Reflection Inspiration"

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4509]
When a user begins a retrospective, they often can't think of what they accomplished since the last retrospective.
They want to see a short list of the things that they have done in their other systems, be it Jira, GitHub, Figma, etc.

Loose guidelines:
- On initial integration, it shows a list of work items that they have created or edited
- For every retro after that, it shows them only items that have changed
- This whole view probably lives in the right drawer in the reflect phase

### First pass criteria
- A pen-and-ink end-to-end experience is sketched out and validated with the team
- A list of 3-5 users is identified for feedback; prompted conversations
- A next-step issue is written

### Deferred criteria
- [ ] A CTA exists somewhere in the Reflect phase encouraging them to add integrations so they can see what changed
- [ ] A loading state exists while we populate the list
- [ ] An empty state shows what happens if that list is empty (and probably encourages them to integrate something else)
- [ ] A list of possible integrations exists so they can choose which to integrate with
- [ ]  A scrollable, readonly list of work items exists to give them inspiration on what to reflect on
- [ ]  One of the integrations is Parabol itself. They can see items in their active column & items that have been marked as "Done" since their last retro
- [ ] OPTIONAL: somehow they can connect the work item to their reflection (drag n drop, reference ID, ???)

Estimate: 20 hours

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11642401) 🔒  writes:

>  I used to do sometimes  physically a Timechart retro (where we post everthing that happen during the sprint or project and try to find improvements from that). That would be something good to add I think

**Comment by ackernaut** [comment]
From [this person](https://app.hubspot.com/contacts/3888472/contact/23714751/)
>What’s missing from the meeting that would better serve your team? [re: retrospectives]
>Before the discussion, I believe we should discuss about the task still pending or not done during the last Retrospective, elsewhere I have the feeling all actions will pile up.

It’s the whole ‘don’t build the sidewalks yet, wait to see where people form the paths’ - we built a check-in meeting, they should use it in between retros, but they want to be reminded of these tasks at a different moment.

From Matt above:
>One of the integrations is Parabol itself. They can see items in their active column & items that have been marked as "Done" since their last retro

It sounds like we’re closer to solving something like this.

The second bit is how to reference existing things (a GitHub issue, or a Parabol Task) on a reflection card or in a thread. ‘Hey, this didn’t get done [Parabol Task card]’ but hopefully in a friendly, tone and conversation that seeks forward motion.

**Comment by ackernaut** [comment]
>When we are starting a retro is would be great if we could show the tasks from the previous retro, sometimes I need to click out to show the tasks from the previous retro

**Comment by gcrickman** [comment]
> > When we are starting a retro is would be great if we could show the tasks from the previous retro, sometimes I need to click out to show the tasks from the previous retro

This [user](https://app.hubspot.com/contacts/3888472/contact/20421401) 🔒

**Comment by ackernaut** [comment]
We explored some patterns here: https://www.notion.so/parabol/Inspirations-6a259f7b96ce4c498df115af295966e3

I think we break this work down with #4913 to get closer to shipping something and #4771 to look at some fuzzy UX and UI patterns that span the app and agile activities.

**Comment by enriquesanchez** [comment]
A [user writes](https://app.hubspot.com/live-messages/3888472/inbox/3846587137#email) 🔒:

> I was wondering if you have thought about showing the past actions after the “retrospective” part is finished.
> 
> The use case I have, and possibly other teams too, is that we start new retro every week and rarely look back on previous tasks. This leads to coming up with action items but never following up on them. It’s an important step in the retrospection process so perhaps there is a way you could incorporate that in your’s app flow.
