### ISSUE TITLE
Mark paid invoices as paid

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4510]
## Issue - Bug

[A customer](https://app.hubspot.com/contacts/3888472/contact/1430601) 🔒 writes:

> Found them! Thank you. They are labeled as invoices with "Amount Due" in big bold even though they've been paid. Maybe a big Paid stamped on paid invoices? I don't think it'll be a problem, but you never know what accounting is going to flag ¯\_(ツ)_/¯

### Acceptance Criteria (optional)

Invoices which have been paid successfully should be marked as such

- **Estimated effort:** 6 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Perhaps may effect #3955

**Comment by jordanh** [comment]
@ackernaut does this need design? Would we want to do this as a big stamp or some other way?

**Comment by ackernaut** [comment]
It’s been a minute since I’ve seen an invoice. I wonder if we add ‘paid’ and ‘balance’ lines:
```
Amount due           128.00
Amount paid         -128.00
Balance                0.00
```
And then, yeah, maybe a big PAID stamp? How’s that for a bad design idea in a comment?

**Comment by jordanh** [comment]
See also: #3955
