### ISSUE TITLE
Display dimension meta on task cards

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4511]
See #4305 for background and design iterations.

See [this frame in Figma](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=4324%3A193766) for the latest concept.

### Acceptance criteria
When a Parabol task or integrated Parabol task has dimension meta from a Sprint Poker meeting:
- The dimension shows on the same meta line where the external link shows, if applicable
- The link and dimension meta use neutral gray text color. Hovering the link or the dimension meta makes the text dark
- If there are multiple dimensions consider adding an ellipsis on the card label e.g. `Value: 8…`
- Tapping the dimension opens a menu
- Each dimension item’s value can be edited by tapping the pencil icon. Pressing enter updates the value unless the value is now empty. In that case it blurs and shows the original value again. Deletes must be explicit.
- The dimension value can be any valid value for the dimension type following whatever charmax (4 char?) is set regardless of what template scale was used
- Each dimension item can be removed using a delete icon.
- There’s a control to add a new dimension. Tapping it reveals an input inline. Pressing enter returns a new item in the list with an empty value field auto-focused and a placeholder. If left empty the dimension goes away.
- Stretch goal, extra scope: there’s a chat icon that links back to the meeting stage where the dimension was set, if applicable

### Estimated effort
- 20 hours

**Comment by ackernaut** [comment]
Via [this customer](https://app.hubspot.com/contacts/3888472/contact/3645601/)
>After ending the estimation and returning to the team’s dashboard, the ticket estimates are lost on the parabol cards.

**Comment by ackernaut** [comment]
This may be solved by #4649

**Comment by mattkrick** [comment]
love this issue!
all the backend stuff is now complete, nothing blocking us from building the UI.

Thoughts: 
- I ended up calling these `TaskEstimates` where `TaskEstimate.name === dimension.name`
- the name in our system might not equal the name in jira (e.g. we call an estimate `Story Points` but Jira calls it `Story Point Estimate`. That said, we _could_ map one to the other if you want to show both
- If the user updates the value in Jira, it'll update in Parabol automatically (maybe we make that obvious in the UI like a sync icon + jira icon?)

**Comment by jordanh** [comment]
This will be solved by #5063, closing this one as a duplicate now
