### ISSUE TITLE
 User Profile: add feature flags toggles

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4514]
A source of delight for power users is to find hidden settings.
Let's show all the feature flags in the User Profile & let folks turn them on as they please, ie poker.
This  means less work for devs & marketing. we just tell folks where to find it & they have the power.

AC
- [ ] User Profile has a list of toggles. Each toggle represets a feature flag. Some toggles require a password to turn on. We can email them the password via EAP flow, or they could do something like click the input 9 times & then it fills in automatically

Estimate: 8 hours

**Comment by avivapinchas** [comment]
We probably need to differentiate between feature flags that are 'ready for users' and those that aren't. I assume we wouldn't have wanted to let folks try Sprint Poker this way in October, for example.

**Comment by mattkrick** [comment]
Let's use this for our EAP, too

**Comment by jordanh** [comment]
Discussed during PH retro:
- User profile page has feature flag area
- Not all flags are visible, some are like "secret passwords"

EAP can then still cohort folks on. Passwords as disseminated via follow-up emails. If they get out because people are excited. So be it :)

**Comment by jordanh** [comment]
See also: #5632

**Comment by mattkrick** [comment]
scrubbed, another feature for the user settings
