### ISSUE TITLE
Add Postgres to non dev app envs

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4518]
## Issue - Enhancement
Related to #4496. Feel free to edit the AC and EE as required.

### Acceptance Criteria
- [x] postgres 12.5 is added to all Parabol non dev app envs in a secure, documented, and reproducible way.
- [x] create terraform deployment to make the process reproducible (using digital ocean for hosted implementation of postgres)
- [x] integrate terraform deployment with pipeline

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by adaniels-parabol** [comment]
Modified version required to 12.5

**Comment by adaniels-parabol** [comment]
Deployment is located here https://gitlab.com/parabol1/action-devsecops/digitalocean-postgres

Next steps will be to create user accounts and put them in the password manager to share with team.
