### ISSUE TITLE
Meeting summaries not sent

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4520]
## Issue - Bug

Meeting summaries are not being sent by email when a meeting is complete.

A [user](https://app.hubspot.com/contacts/3888472/contact/21299801) 🔒  and their team is having this issue

[Another user](https://app.hubspot.com/contacts/3888472/contact/6610651/) 🔒  is having this issue:

> After the retrospective, usually we've got Email as the summary of our retro- until last year. But yesterday for both team, we don’t get any Email from parabol.

I am also not receiving email summaries 

### Acceptance
- Triage and fix or write an implementation issue if the work is larger than the effort here to commit and review

### Estimated effort
- 4 hours

**Comment by ackernaut** [comment]
I’ve tried both a check-in and a retro with one of my demo teams of 2 users. I didn’t see an email summary for either after completing them. I did get redirected to the summary view when ending the meeting. The meeting event card does show up on my timeline.

**Comment by mattkrick** [comment]
typo that wasn't caught because of an implicit `any` type :disappointed: 
fixed here https://github.com/ParabolInc/parabol/commit/3ef7fceea384351037a7eda3885865afffdff328
