### ISSUE TITLE
Some meetings not ending correctly

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4521]
Today it happened again, 2nd time that I recall. We ended a check-in meeting and

- the done column was not automatically archived and
- the agenda list was not cleared (besides the pinned items)

We are at `v5.30.0`, however it probably happened 2 weeks ago so that could’ve been a minor version or 2 prior (we didn’t ship over the holiday break).

I’ve tried reproducing this on my own demo team in production without success. I wonder if there is something borked about our particular team (i.e. internal Product team).

May or may not be related to:
- Meeting summary not being sent (but I think this is a newer bug) #4520 
- Pinned items from previous meetings getting sticky #4436
- Sometimes pinned items don’t persist #4352

### Acceptance criteria
- Triaged and fixed or implementation issue written if out of time to fix and PR review

### Estimated effort
- 4 hours

**Comment by ackernaut** [comment]
Another data point: we just ended our Product team retrospective. I was facilitator. Instead of landing on the summary view I was redirected to the dashboard and got the ‘Meeting terminated’ snackbar. The timeline event card is there and the summary does look intact. I did get the summary email (I believe that bit was fixed).

**Comment by jordanh** [comment]
@ackernaut have you seen this one recently? If not, perhaps close it?

**Comment by ackernaut** [comment]
It’s been a while. We can close and open a new one if needed for a fresh take on it.

**Comment by jordanh** [comment]
We haven't seen this for quite some time. I'm hoping that our upgrade to the newest version of relay (or something else) fix it. Closing for now...
