### ISSUE TITLE
New team members can't see meeting history

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4527]
## Issue - Enhancement

A [user](https://app.hubspot.com/contacts/3888472/contact/10352351) 🔒  has requested a feature that would allow new team members to view meeting history and summaries.

I imagine this would be a setting as not everyone would want this to be the default.

**Comment by jordanh** [comment]
related to #4540

**Comment by jordanh** [comment]
Closing as duplicate
