### ISSUE TITLE
New users can't see meeting history

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4528]
## Issue - Enhancement

A [user](https://app.hubspot.com/contacts/3888472/contact/10352351) 🔒  has requested a feature that would allow new team members to view meeting history and summaries.

I imagine this would be a setting as not everyone would want this to be the default.

**Comment by mattkrick** [comment]
iceboxing in favor of https://github.com/ParabolInc/parabol/issues/4540
