### ISSUE TITLE
Expanded columns stay expanded when moving from Group to Vote 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4534]
## Issue - Enhancement

With the option to expand columns in Group, I'll set up my screen to maximize the use of space. When we move from Group to Vote, the columns will reset to the smaller size, even though I've expressed my preference for them to be expanded. 

### Acceptance Criteria (optional)
Users move from Group to Vote without columns changing size. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing
