### ISSUE TITLE
Expand columns in Reflect phase

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4535]
## Issue - Enhancement

With the option to expand columns in Group and Vote, my eyes are now open to how much better I can be using the space on my screen! Now that I've tried expanded columns, I want to have the option in the Reflect phase as well. 

Where it's relevant: 
- If I'm adding a lot of reflections in each column, like I might for a large retro covering a long project or when doing UX research grouping
- If I have more horizontal real estate to work with, like my second monitor 

### Acceptance Criteria (optional)
Users can expand columns in the Reflect phase 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Currently in the Reflect phas, you see 1 stack of reflections with the most recent on top. Tapping reveals all but in a single column in a dialog. Is that where you imagine expanding so that you can see more at once?

**Comment by avivapinchas** [comment]
🤔  I didn't have a particular use case in mind, it's more that the columns in the Reflect phase can look 'small' compared to the window size, and now that we can expand columns in later phases, that's more obvious.

**Comment by nickoferrall** [comment]
I thought about adding the expandable logic to the Reflect phase too but it might be tricky to get it looking good.
If the reflection editor is on the left or centre, there's a lot of whitespace. If it's double the width, it's inconsistent. 

When writing reflections, it should probably still only create one reflection stack as it'd be more inconvenient to click on two different stacks. Two stacks wouldn't add much anyway as you can only read the reflection at the top of the stack.

So if the reflection editor remains the same width and there's only one stack, expanding the columns would just add empty space without any extra utility. Maybe it'd still be worth doing though if users enjoy the control. 

![expandable-reflections](https://user-images.githubusercontent.com/39854876/105182786-d74b5500-5b03-11eb-9dee-9af93edef189.png)

**Comment by jordanh** [comment]
Iceboxing
