### ISSUE TITLE
User profile: Allow Team Members to Unsubscribe from Meeting Summary Emails

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4538]
As a team member, I want more power over the emails I get from parabol.
In terms of meeting summaries, I want to be able to turn off meeting summaries for some meetings, or all meetings.

If we put this functionality in the User settings, it has the following benefits: 
- A single toggle for turning off all meeting summary emails (with child toggles for granular control)
- No need for a team member settings page

See customer request: https://github.com/ParabolInc/parabol/issues/4351#issuecomment-760530041

As a rough design, I imagine this:

#### Meeting Summaries ON | OFF
  - Product ON | OFF
  - Growth ON | OFF
#### Task Notifications ON | OFF
  - Task Mentions ON | OFF
  - Task assignments ON | OFF

AC
- [ ] A design in figma that follows the above layout

Estimate: 16 hours

**Comment by ackernaut** [comment]
+1 to being able to opt in or out. I would like the summaries for the meetings I missed to try understand simple things like role changes for the week, but recently we changed it so that only meeting attendees get the summaries.

**Comment by mattkrick** [comment]
we hotfixed this so all team members now get the summary, even if they weren't in the meeting.
making it optional belongs in team settings i think, maybe above the integrations settings.

stuck on new team dash

**Comment by ackernaut** [comment]
Via [this person](https://app.hubspot.com/contacts/3888472/contact/905301/) 🔒 
>‘How can I unsubscribe from all email notifications (Meeting summary, check- ins etc)’

**Comment by gcrickman** [comment]
A **[customer](https://app.hubspot.com/contacts/3888472/contact/11903651)** 🔒 writes:

> As manager of an organization I attend a lot of meetings. When Parabol is used I get a summary mail for every single one. I really do not need these, but I can not turn them off!
> Please provide me with a way to keep this stuff out of my inbox.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/29367951) 🔒  writes:

> I am discovering your tool and so far i really like it.
> The only thing for now that I not like is that every team member seems to get all notifications and information/tips by email. I would like to turn this off. Because I do not want to spam my customers.
> I hope you can tell me how to avoid these emails.
> Thanks a lot.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/24851651) 🔒 writes:

> I've been receiving Summary emails and it seems they can't be disabled, is that correct?
> I would like to disable this feature.
> Thanks.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/36707001) 🔒  writes:

> Hi! There's a way to disable the email sending after ending a meeting? Thanks!

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/49562801?interaction=email) 🔒 writes:

> Hello, is there a way to unsubscribe and not receive any summary emails?
> I checked my profile but I don't see an option for this in my account. I didn't see any option for this when searching the site or looking for help docs.

**Comment by drewhousman1010** [comment]
After receiving an unwanted meeting summary, a [user](https://app.hubspot.com/contacts/3888472/contact/31520701) writes:

> Where’s the unsubscribe button?

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/56132051) 🔒  writes: 

> I noticed that this email is sent to everyone in the team whether they attended the meeting or not. I would like it to be sent to the people who attended that retro. Is there a way to configure this?

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/68195652) 🔒 writes:

> 1) This tool is amazing!
> 2) Is there a way to manage email notifications?

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/live-messages/3888472/inbox/2368093493#email) 🔒 writes:

> How can I turn off email notifications from sending after I end every meeting?

**Comment by gcrickman** [comment]
This [user](https://app.hubspot.com/contacts/3888472/contact/69665201) 🔒 wrote into support asking how to unsubscribe from Parabol summary emails.

**Comment by ackernaut** [comment]
@acressall did you have some early designs here? Mind sharing those. I’m looking across some org and user management design issues for UX themes and UI consistency

**Comment by acressall** [comment]
@ackernaut it's just inspiration and notes at this point, but my next step was going to be some rough sketches. Feel free you add your own notes and comments here if it's useful to you! https://www.figma.com/file/tanOwz8EOLUCfkJlyRviKo/Email-Exploration?node-id=0%3A1

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/67820801) 🔒 writes: 

> I'd like to unsubscribe from these emails, but I can't find a way to do that. Can you please help me?

**Comment by ackernaut** [comment]
Related to #6596

**Comment by avivapinchas** [comment]
**Value: 2**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/21) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: M**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/22) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/50960901) 🔒  writes:

> I doubt most people care about meeting summaries, why is there no unsubscribe link? Thanks :)

**Comment by mattkrick** [comment]
yep!
for the implementation spec, we'll just want the person building it to be aware of what may come in the future so they don't make a boolean like `TeamMember.enableAllEmails = true` and then have to change that when we break them apart by type.

my biggest question is team-specific settings. personally, i only want emails for particular teams. if we support that, does that mean we move this to the team settings instead of the user settings?

**Comment by avivapinchas** [comment]
> my biggest question is team-specific settings. personally, i only want emails for particular teams. if we support that, does that mean we move this to the team settings instead of the user settings?

I realize it's a later concern, but wanted to chime in: I imagine this would be different by role. Some stories: 
- As a team-of-teams lead, I want to see check-in meeting summaries for the teams I lead, so I can keep a sense of what's going on there
- As a squad member, I don't want summaries for squad meetings I attended (because I was there!) but I do want summaries if I was out 
- As a sub-circle member (ex: a Growth team member who isn't part of Exco), I want summaries for the main Circle (in this case Exco) so I can see what leaders at that level are thinking about 

We've got some early evidence that some manager roles behave differently - they'll go in to see meeting notes or tasks, but won't participate in a meeting. I imagine this is a type of user we may need to consider more deeply in future.

**Comment by mattkrick** [comment]
> As a team-of-teams lead, I want to see check-in meeting summaries for the teams I lead, so I can keep a sense of what's going on there

yaaaa! in the past we called this the "subscriber" model. i think it's really good to keep in mind because whatever we build should be able to support that

> As a squad member, I don't want summaries for squad meetings I attended (because I was there!) but I do want summaries if I was out

that's really neat. kinda like a ternary toggle "on/off/on-if-absent"

**Comment by acressall** [comment]
A user requested

> No spam emails anymore

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/72970401) 🔒 writes: 

>  Is there a way to easily cancel/close a meeting that was accidentally made or just needs to be closed? I have one meeting that I cannot open to End the Meeting and two others I don't want to "End the Meeting" because I don't want to send emails for these empty meetings to the team.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/83273851) 🔒 writes:

> Parabol team,
> 
> I can't unsubscribe to the email updates - help!
> 
> Absolutely no way to stop the email updates filling up my inbox.
> 
> Can't find how to unsub!
> 
> Not cool.

**Comment by acressall** [comment]
From a large enterprise customer:

> Where do I go to stop receiving e-mails with the retro summary? I want to remain in the org/team, but just don't want the weekly e-mails.

**Comment by acressall** [comment]
A user writes:
> Hi. How do I unsubscribe from summary emails being sent to me

**Comment by avivapinchas** [comment]
We launched this in September: https://github.com/ParabolInc/parabol/blob/master/CHANGELOG.md#6760-2022-september-28 Closing this out.
