### ISSUE TITLE
updateTask mutation not broadcasting changes

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4545]
## Issue - Bug

Watch 🎞:  : [this Loom reproduction video](https://www.loom.com/share/09334ef7249349969e596e1a2b14f8d3)

Reproduction:
   - User A creates task card during Check-In meeting
   - User A edits and blurs task card, triggering updateTask
   - Other users in meeting do not see task card content update
      -  Other users do see task editing status change, and other broadcast events

Speculation: may be related to edit of check-in question, and not seeing those changes broadcast either

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 16 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Edit task cards and have their changes broadcast to others

**Comment by mattkrick** [comment]
this looks like a regression from code added around here: https://github.com/ParabolInc/parabol/blob/bd5e3d599d280e638f37b75bb1a61c3a5b3a9a67/packages/client/hooks/useEditorState.ts#L30

possible venues may be making sure that the logic there is firing & triaging from there
