### ISSUE TITLE
AMS private instance scoped

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4548]
AC
- [x] ​hosting provider picked
- [x] hosting architecture defined
- [x] next steps captured as issues

EE 6 hours

**Comment by adaniels-parabol** [comment]
@jordanh AWS will be the hosting provider this round. Attached are diagrams of deployment pipeline and expected type.

![AMS Instance - Managed Hosting Architecture](https://user-images.githubusercontent.com/71724289/105547613-42dc2080-5cc4-11eb-904f-c61d85f4ced8.jpg)
![AMS Instance - Deployment Pipeline and Type](https://user-images.githubusercontent.com/71724289/105547616-4374b700-5cc4-11eb-9eac-6b99e2f64579.jpg)

**Comment by adaniels-parabol** [comment]
Next steps captured as issues in following tickets

https://github.com/ParabolInc/parabol/issues/4589
https://github.com/ParabolInc/parabol/issues/4590
https://github.com/ParabolInc/parabol/issues/4591
https://github.com/ParabolInc/parabol/issues/4592
https://github.com/ParabolInc/parabol/issues/4593
