### ISSUE TITLE
Think about how to upgrade to Enterprise a single-tenant cloud where we run a private cloud

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4549]
self, private, hosted

​

AC

- design workflow for cloud, private, self hosting for billings

Effort: 8 hours

**Comment by mattkrick** [comment]
chatted with @adaniels-parabol yesterday about possible solutions for this.
Here's the plan envisioned (please edit this comment directly @adaniels-parabol if it's incorrect).

we create a new env var called `HOSTING_TYPE` with the value of `self, private, cloud`.
for self & private HOSTING_TYPE, we force a single organization (work to be done outisde this issue)

Self hosted:
- We'll kick this can down the road. In the future, we'll probably make a .env for them & send them a script that downloads the repo & runs docker-compose.

Private hosted: 
- As a first step, we'll set up an EC2 for each new region. If we sell another 1 or 2 contracts, we'll probably move towards a k8s solution. Once we do that, we can use that same k8s config file as a self hosted solution
- metrics, analytics, error reporting can be enabled/disabled per user request
- for billing, we'll create a single parabol user & give them su perms
- from the single parabol user, we run `draftEnterpiseInvoice`

Cloud hosted:
- No change for now. If we do move to k8s, the config file can be shared here, too.

**Comment by adaniels-parabol** [comment]
@mattkrick modification to Private hosted (where we manage the infra).

I'm going to use our most recent PO to push forward on K8s vs a single EC2.

**Comment by mattkrick** [comment]
wonderful! @jordanh mind giving this a review?

**Comment by jordanh** [comment]
@mattkrick Clarifying question, with `HOSTING_TYPE` = `private` how would this instance interact with Stripe?

**Comment by mattkrick** [comment]
see last 2 bullet points?
same stripe secret as our cloud offering

**Comment by jordanh** [comment]
I think this is ok. @mattkrick, this means we'd draft and send invoices via this private instance? Safe to try.

@mattkrick I think you can close this one when ready
