### ISSUE TITLE
Reducing In-Product Conversion Friction

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#4555]
Amplitude data shows that we need to do some work to reduce friction around in-product conversion. 

Our recent e-mail experiment regarding conversions showed good engagement but low conversions. This indicates that there was an intent to upgrade but failure to follow-through. Our correspondence with users revealed that many of them questioned the number of active users on their team because they were unable to see the full user-base across their org. 

In this issue I've put together some proposals for how we might improve the organic conversion-flow process in the product, with the goal of:

**1. Reducing confusion about # of teams and team members
2. Enabling a purchasing decision to be made when there are multiple billing leaders for an org sat on different teams**

Here's a drunken-house drawing I did earlier to explain some of my thinking: 

[Conversion Flow Thinking](https://www.figma.com/file/9fO3erdtoTBddLJ8QgxIO8/Conversion-Flow-Thinking)

And a summary here: 

> **1. Reducing confusion about # of teams and team members**

We could reduce confusion by exposing more clearly the number of teams. Parabol is free for 2 teams. But when you look on your Organization you just see a long list of users – not their team affiliation. If we can expose to our users the different teams their org has, who sits in each one, and who is the leader – we can create some clarity. That clarity helps to head off any claims that our data is wrong. 

See in Figma ideas for also including some product stats here to get people visiting the org page more often. 

> **2. Enabling a purchasing decision to be made when there are multiple billing leaders for an org sat on different teams**

Managed sales is very different to organic upgrades, so I wonder if we might need a different approach. Our managed sales process relies on us building relationships and coalitions of users, but I think we'd be hard-pressed to get our users within one org talking to each other about purchasing us from within the app. What if we clearly marked the billing leaders on each team in the view I have sketched but also assigned an explicit 'account owner'. That could be patient 0 or be assigned by a patient 0 to someone else within that org. All our email campaigns would go to that person. They would be the one person that org members could petition to upgrade the account. 

Putting the pressure on one person could be an interesting experiment because it eradicates the decision paralysis that comes with a situation where "there are 4 other teams using Parabol that I don't know – i'm not paying for them out of my team's budget..."

These are very rough sketches – so please be kind!

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.

Tried to see your Figma sketches, sir @garethaledavies, could you check the perms on those and relink them? Would love to look again.
