### ISSUE TITLE
"You already used that name" bug in Group phase

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4558]
Error in the Group phase affecting quite a few users. First discovered in release 5.30.0. I was able to reproduce this in production by ungrouping a reflection group. 

https://sentry.io/organizations/parabol/issues/2135878249/?referrer=github_plugin

```
Error: Objects are not valid as a React child (found: Error: You already used that name). If you meant to render a collection of children, use an array instead.
  at Error: Minified React error #31; visit  (/docs/error-decoder.html)
...
(19 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
https://github.com/ParabolInc/parabol/blob/master/node_modules/parabol-client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx#L168
