### ISSUE TITLE
Limit number of avatars displayed in team dashboard

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4566]
If there are many team members in a team, the team member avatars can scroll on endlessly creating a horizontal scrollbar and all sorts of ugliness.

### AC

- [ ] Limit the number of avatars that can be displayed in the dashboard so that a horizontal scrollbar doesn't appear
- [ ] If there's not enough space to display all avatars, the final avatar on the right says: "+7" with 7 being the number of avatars that are not on display
- [ ] When hovering over the "+7" avatar, a dropdown menu appears with the missing avatars
- **Note**: in Sprint Poker we measured the space available so that the overflow was dynamic; previously in the meeting UI it was a fix number based on breakpoints. Going the dynamic path is an improvement over the fixed number

![many-team-members](https://user-images.githubusercontent.com/39854876/105359743-2f4e8e00-5bce-11eb-8bb1-f9c30dfb7b5b.png)

### EE
- 8 hours

**Comment by jordanh** [comment]
Related to #4493
