### ISSUE TITLE
Sprint Poker: Add delight when consensus is hit

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4570]
https://app.hubspot.com/contacts/3888472/contact/15959651/

> Not sure if you had it, I didn't test that far, but there are platforms who give some cheers when you have consensus so that would be impossible if I'd join the votes with question marks.

This is so much fun. For a quick first pass:

- [ ] consensus is defined as 3+ people voting the same way and no one else voting for any other value except PASS
- [ ] if consensus is achieved let's blast some confetti right in their face (or anything else that seems reasonable)

Estimate: 8 hours

**Comment by jordanh** [comment]
Still a great idea. I would hope we'd get back to this one day (soon!)

Iceboxing for now
