### ISSUE TITLE
Sprint poker: Add a "I don't vote" Option

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4571]
https://app.hubspot.com/contacts/3888472/contact/15959651/

> Having the option to remove voting for some users. I don't normally join the votes as the facilitator and I can't turn it off. 

Sometimes, people are in sprint poker meetings just to observe. we should have a secondary link that turns off their deck & hides their face from the PASS row & the voting totals

AC
- [x] a link exists that says "I don't want to vote". This preference is persisted on the TeamMember (or maybe a list of userIds in the MeetingSettings object, you decide!)
- [x] when that value (`isSpectating`) is true...
- [x] the deck is hidden
- [x] a link exists saying "I want to vote now"
- [x] their face is hidden on the PASS row
- [x] their PASS vote does not contribute to any of the aggregate stats

Estimate: 16 hours

**Comment by jordanh** [comment]
We should find out why pass is insufficient. Keeping this open (obvi) to continue spooling up feedback

**Comment by jordanh** [comment]
Following the link above, we can infer folks want to see consensus. The usage of `PASS` is ambiguous. It could mean "I don't vote" or "I'm not ready" etc.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/8034101) 🔒 writes:

> Create a way to have non-voting participants – our Product Manager and ScrumMaster, and occasionally team members, don’t participate in voting and have to click the Pass card each time

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/21956751) 🔒 writes:

> Subject: Feature Request For Poker Planning
> Message: Hey Parabol Team!
> Just used your sprint poker tool today and LOVED it!
> The one feature I'd love to see is a way for the scrum master or host to not be counted as a voter. The scrum master shouldn't be voting and it looks weird to see my face on the screen every time. Thanks!

**Comment by mattkrick** [comment]
storing this on the team member is probably not the best because that means the aggregate stats could change in the future. we need to store this on the meeting member.

we could store the preference on the team member so in the future they don't have to click the button for every meeting.
is that worth it?
it's probably what the user wants, so let's say yes
