### ISSUE TITLE
Sentry: Ignore resizeobserver error

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4573]
if the resizeobserver can't operate without a single animation frame, it'll throw an error. this is fine. let's stop telling sentry about it.

fix should look like:
```ts
Sentry.init({
   ...
   ignoreErrors: ['ResizeObserver loop limit exceeded'],
 })
```

AC
- [ ] sentry shuts up about above error

Estimate: 1 hour

**Comment by jordanh** [comment]
Mystery solved
