### ISSUE TITLE
Sprint Poker: Design "The Oracle"

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4574]
In sprint poker, we want to know who the good estimators are. We already track their votes & the finalScore, so we can determine how good of a guesser they are. Maybe we put stats like these in the meeting summary? We open it up to leadership in omniview? We give them a badge?

AC
- [ ] Come up with a fun way to celebrate individuals who are good at estimating story points

Estimate: 30 hours

**Comment by jordanh** [comment]
@mattkrick is the idea here that we compare the score to the finalScore (and not to the actual time until the issue got closed?) I think this is a fun idea.

**Comment by jordanh** [comment]
Iceboxing for now
