### ISSUE TITLE
Designed a guided decision thread

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4575]
In the spirit of building things to solve our own problems, how might folks follow a process to arrive at a decision within our software?

Is a decision thread a stand-alone experience or an optional feature of our general discussion thread component? For this exploration either is safe to try

### Acceptance criteria
- Sketched an end-to-end experience where folks can propose a decision, prompt for questions, prompt for reactions, prompt for blockers, and optionally mark a decision as being accepted
- Raised part of the experience to a high-fidelity concept
- Wrote the acceptance criteria for an implementation issue

### Deferred questions
- Where do decisions go? To an integrated space like Docs, Notion, or Confluence?
- Can folks filter team activity in Parabol for decisions? Are these team insights?
- How might other objects in the system be connected to the decision, like the reflections or topic that introduced the tension?

### Estimated effort
- 20 hours

**Comment by jordanh** [comment]
Keeping open for batting practice sake
