### ISSUE TITLE
prod invitation short links not working

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4577]
## Issue - Bug

Customers reporting that invitation short links in prod are not working. I confirmed that the short links are working on staging. The issue is non-code related and seems to be a DNS thing. Invitation short links point to a different domain only on production. The error as seen in the browser is:

`This site can’t be reachedCheck if there is a typo in prbl.in.
DNS_PROBE_FINISHED_NXDOMAIN`

### Acceptance Criteria (optional)
Users can:
   - [ ] access meetings using the generated invitation short links on production

- **Estimated effort:** 4 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed by renewing domain. nice little friday :fire: :firefighter: :fire_engine:
