### ISSUE TITLE
HubSpot Company last met property not updating

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4581]
## Issue - Bug

One of the properties we sync between our app and Hubspot is when users at a particular company last met. This field appears to not be syncing. 

Examples: 
- Company's `lastmet` field in [Hubspot shows Aug 24, 2020 ](https://app.hubspot.com/contacts/3888472/company/2342115427) 🔒 , but in Amplitude, we can see that users with that company's domain [met consistently over the last 90 days](https://analytics.amplitude.com/parabol/chart/1tyvqdl?source=redirect%3A+chart+saved)
- Company's `lastmet` field in [Hubspot shows Sept 8, 2020](https://app.hubspot.com/contacts/3888472/company/791780484) 🔒 , but in Amplitude, we can see that users with that company's domain [met consistently over the last 90 days  ](https://analytics.amplitude.com/parabol/chart/zuyzv5t?source=redirect%3A+chart+saved)

Related issue from June: #3902 

### Acceptance Criteria (optional)
Parabol team can use the `lastmet` field in Hubspot to accurately assess the recency of a company's activities with us.

**Comment by tianrunhe** [comment]
Resolves together with #4578
