### ISSUE TITLE
create a webpack plugin that includes DLL caching

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4583]
today, we handle DLL caching outside of webpack.
we could build this into a plugin & offer it to the community.
there is 1 package that tried to do this, it was built a couple years ago & didn't get much traction. it doesn't work with the latest version of webpack.
@jordanh i'd consider this the kind of package that you're after. one that is an easy lift, but has potential for high visibility

AC
- [ ] the `buildDll.js` logic is moved into a separate package & turned into a webpack plugin
- [ ] the package is open sourced under the parabolinc github and under the parabol in npm
- [ ] instead of referencing the built dll output, the dev config references the dll config & the plugin builds it if the hash changes
- [ ] see https://github.com/clinyong/dll-link-webpack-plugin for inspiration on the API
- [ ] Suggested API: `({vendors: string[]} | {package: string, ignore?: string[]}) & {lockfile?: string}` but it's up to you!

Estimate: 16 hours

**Comment by jordanh** [comment]
@mattkrick this is a _great_ idea

**Comment by mattkrick** [comment]
done by Jimmy
