### ISSUE TITLE
audit every mutation that calls adjustUserCount & maybe use redis lock on them

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4587]
@nickoferrall found a really tricky bug where acceptTeamInvitation could be called in quick succession resulting in an error. 
the flow is like this:
- call acceptTeamInivitation
- check if the user in the org
- if not in the org, add them to the org

the race condition occured at the 2nd step because both calls would return false & then both calls would add the user to the org, resulting in 2 users.

we should make sure that there are no other mutations that could break things if called in quick succession.

AC
- [ ] every function is audited & if we don't want a user to call it multiple times simultaneously, we put a lock on it

Estimate: 24 hours

**Comment by jordanh** [comment]
Scrubbed. We discussed and want to keep this on the backlog. Marking as bug, and will bump up to p3.

**Comment by jordanh** [comment]
Iceboxed
