### ISSUE TITLE
Editable agenda items

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4600]
## Issue - Enhancement

Truly I'm a bit shocked it's taken until now to hear this from a user.

[A user writes ](https://app.hubspot.com/contacts/3888472/contact/10876051)🔒 :
> Discussion Topics are not editable
> It didn’t appear that we could edit a discussion topic when it had been created
> Workaround was to delete and re-write

### Acceptance Criteria (optional)
Users can:
   - have an easy affordance (e.g. does the cursor change to an edit bone?) to edit agenda item names
   - 
Also:
   - internal validation performed
   - implementation issue created

- **Estimated effort:** 6 hours

**Comment by jordanh** [comment]
Going to prioritize this a bit higher. On Exco, we are now tagging items by agenda item type, and not being able to edit these items to retag them is getting in our way

**Comment by jordanh** [comment]
Going to put this one up for grabs on E4E and see if we get any takers

**Comment by shapel** [comment]
I'd like to tackle this one.

**Comment by jordanh** [comment]
@shapel wonderful sir! This one is yours for 8 points. I've updated the Equity for Effort board and assigned you owner. We look forward to the PR!

**Comment by shapel** [comment]
just a follow-up that I still hope to pay attention to it on this week (had to recover from an illness)

**Comment by shapel** [comment]
👋 @jordanh plz help to pick someone to review my PR.

**Comment by jordanh** [comment]
@shapel ok, I will raise as an agenda item during our meeting on Monday. Thank you for raising

**Comment by shapel** [comment]
@jordanh do you have any news about this?

**Comment by jordanh** [comment]
Note: @shapel's PR was never merged (but it got close). This issue is still available for somebody in the community to take, if they wish!
