### ISSUE TITLE
Implemented per-phase timer

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4608]
Today the timer is per-stage. It’s not possible to keep a timer open over a phase of stages if the facilitator navigates past the first stage. It ends the timer. We like the per-stage data. See discussion #4448

**Note**: to my knowledge folks haven’t asked to keep a timer over across stages in a phase, so we can opt to do this when there’s user validation.

### Acceptance criteria
- The timer or time-box runs per phase instead of per stage. that means when a timer is added during the Poker Estimate phase that timer persists for every story being estimated
- When a timer or time-box is started, or time added, or ended, we capture the event including stage ID for metrics

### Estimated effort
- 20 hrs

**Comment by ackernaut** [comment]
#4685 is where we’re discussing the group behavior of working on the estimation async (each participant navigating and voting independently of a facilitator), but while viewing at the same time, or some folks are viewing at the same time.

**Comment by jordanh** [comment]
Iceboxing for now
