### ISSUE TITLE
Added a timer to the Sprint Poker Estimate phase

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4609]
In the Estimate phase, folks might set a timer to limit discussion when looking for some level of agreement. Folks may open up a timer while folks review stories and vote. This needs validation.

**Note**: we can wait until folks ask for this; we can block this if we want to do #4608 first

### Acceptance criteria
- The Sprint Poker Estimate phase has a timer

### Estimated effort
- 8 hrs

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/8034101) 🔒  writes:

> Bring the timer over from the Retro template – that would be incredibly helpful for keeping our Refinement sessions on pace

**Comment by jordanh** [comment]
Still a great idea!

Iceboxing by policy

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/66525451) 🔒 writes: 

> > Hello. First, thanks for the awesome product. Been a user for ~3 years now :) 
> 
> Question: Is it possible to add a timer to Sprint Poker. We try to use it as Grooming (synchronous) and a lot of time end up with very long discussions.
