### ISSUE TITLE
Team member can be null in check-in

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4613]
Bug that has affected 78 users over 9 months. On the 15th Jan, several members from the same team were affected ([see here](https://sentry.io/organizations/parabol/issues/1639628283/tags/user/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d)) so it might be worth digging into that team's data as a starting point.

https://sentry.io/organizations/parabol/issues/1639628283/?referrer=github_plugin

```
TypeError: Cannot destructure property 'picture' of 'r' as it is undefined.
  at None (./packages/client/components/MeetingSidebarTeamMemberStageItems.tsx:59:18)
  at Array.map (<anonymous>)
  at c (./packages/client/components/MeetingSidebarTeamMemberStageItems.tsx:50:29)
  at Set.forEach (<anonymous>)
...
(32 additional frame(s) were not displayed)
```

**Comment by tianrunhe** [comment]
Closes in favor of https://github.com/ParabolInc/parabol/issues/4735 which is in the sprint.
