### ISSUE TITLE
Timeline query returning null

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4615]
There are a few different Sentry issues where the Timeline query returns null or undefined. 

It looks like a low priority bug - this Sentry issue has affected 12 users over 9 months.

https://sentry.io/organizations/parabol/issues/1662768180/?referrer=github_plugin

```
TypeError: Cannot destructure property 'suggestedActions' of 'n' as it is null.
  at c (./packages/client/components/TimelineSuggestedAction.tsx:42:10)
...
(7 additional frame(s) were not displayed)
```

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-4XJ](https://sentry.io/organizations/parabol/issues/2139459833/?referrer=github_plugin)

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-4XK](https://sentry.io/organizations/parabol/issues/2139459835/?referrer=github_plugin)

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-3Y8](https://sentry.io/organizations/parabol/issues/1662768175/?referrer=github_plugin)

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-4XM](https://sentry.io/organizations/parabol/issues/2139459841/?referrer=github_plugin)

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-5K5](https://sentry.io/organizations/parabol/issues/2306416606/?referrer=github_plugin)

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-5K8](https://sentry.io/organizations/parabol/issues/2306416697/?referrer=github_plugin)

**Comment by jordanh** [comment]
Watermark: 31 users affected

**Comment by tiffanyhan** [comment]
All of these timeline issues have had 176 occurrences affecting 168 users. All occur bc they try to read a property off of viewer, which is undefined. Bumping this to p2 as the occurrences are now much more than previously reported.

https://sentry.io/organizations/parabol/issues/2489660517/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

https://sentry.io/organizations/parabol/issues/2489660515/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

https://sentry.io/organizations/parabol/issues/2489660512/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

https://sentry.io/organizations/parabol/issues/2489660511/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-8H6](https://sentry.io/organizations/parabol/issues/2514276491/?referrer=github_plugin)

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-8H7](https://sentry.io/organizations/parabol/issues/2514276530/?referrer=github_plugin)

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-8H8](https://sentry.io/organizations/parabol/issues/2514276539/?referrer=github_plugin)

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-8H9](https://sentry.io/organizations/parabol/issues/2514276583/?referrer=github_plugin)

**Comment by mattkrick** [comment]
All last seen 11 days ago!
I think 6.25.0 might have fixed this
