### ISSUE TITLE
Sprint Poker and new retro templates have their unique illustrations 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4616]
## Issue - Enhancement

We've created illustrations for each 'template' in the product, and we can bring those in to spruce up the experience: 
- [Latest round of retro template illustrations](https://drive.google.com/drive/folders/19g645bIJL6hghTLU9QMm5BhUlJsUVsb_) 🔒 
- [Sprint Poker template illustrations](https://drive.google.com/drive/folders/1MWS3V92yqYvlZgjZ_K5YyIprxz-eSI1E) 🔒 

### Acceptance Criteria (optional)
Users can enjoy all the custom illustrations and feel delighted 😸 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
@tiffanyhan For retro template, you might want to look at [here](https://github.com/ParabolInc/parabol/blob/4efb2ef721e0277a01cc1b241e08e4d88d9d8988/packages/client/modules/meeting/components/ReflectTemplateDetails.tsx#L82-L88) and for sprint poker [here](https://github.com/ParabolInc/parabol/blob/bc966e38d81aa5bd5594973f12866a3d9360f7e9/packages/client/modules/meeting/components/PokerTemplateDetails.tsx#L78).

**Comment by tiffanyhan** [comment]
@tianrunhe perfect thank you!

@avivapinchas can i get access to the google drive files?

**Comment by avivapinchas** [comment]
Access granted! I gave you access to the parent folder that all the illustrations live in, which I _think_ would give you access to the folders within that folder 🤞

**Comment by jordanh** [comment]
I think this shipped, right @tiffanyhan ? Could you close if true...
