### ISSUE TITLE
Discussion thread crashing in Firefox

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4617]
Sentry issue reported in the discussion thread affecting 7 users since release 5.31.1. Only happening on Firefox.

https://sentry.io/organizations/parabol/issues/2164690733/?referrer=github_plugin

```
NS_ERROR_FAILURE: No error message
  at onChange (./packages/client/components/ReflectionEditorWrapper.tsx:139:5)
  at apply (./packages/client/components/ReflectionEditorWrapper.tsx:86:72)
...
(17 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Watermark: 33 users affected

**Comment by jordanh** [comment]
No further incidents in Sentry, closing
