### ISSUE TITLE
Mass invitation link fatal error

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4626]
Team can be null. Fatal bug seen by 13 users over the past two months.

https://sentry.io/organizations/parabol/issues/2085683372/?referrer=github_plugin

```
TypeError: Cannot destructure property 'id' of 'a' as it is null.
  at c (./packages/client/components/MassInvitationTokenLink.tsx:44:14)
...
(7 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Watermark: 6 users, 36 events

**Comment by jordanh** [comment]
No further incidents in Sentry, closing
