### ISSUE TITLE
Replicate Team to PG (Phase 1 of 3)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4629]
After User, Team is next to go to PG. Doing this will allow us to start caching teams, which will let us get rid of tms on the authToken #4071 

let's start to move to postgres. see #4530

AC
- [ ] Every time a Team is created, they are also created in postgres
- [ ] Every time a Team is updated, the update is propagated to postgres
- [ ] a postdeploy hook is written to copy all Team to postgres

Estimate: 16 hours

**Comment by tiffanyhan** [comment]
all update hooks:
- [ ] `terminateSubscription`
- [ ] `draftEnterpriseInvoice`
- [ ] `moveTeamToOrg`
- [ ] `startCheckIn`
- [ ] `startRetrospective`
- [ ] `startSprintPoker`
- [ ] `updateJiraDimensionField`
- [ ] `updateTeamName`
- [ ] `removeTeamMember`
- [ ] `resolveDowngradeToPersonal`
- [ ] `upgradeToPro`
- [ ] `safeArchiveTeam`
- [ ] `ensureJiraDimensionField`

**Comment by tiffanyhan** [comment]
implemented in #4787
