### ISSUE TITLE
Read Team from PG instead of RethinkDB (Phase 2 of 3)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4630]
After #4629 is working is prod, we need to start reading from pg instead of RethinkDB. See #4530 

AC
- [ ] All reads for the `Team` table come from pg, not RethinkDB
- [ ] if you nuke the data in the Team table in rethinkdb, nothing bad happens

Estimate: 16 hours

**Comment by tiffanyhan** [comment]
steps:
- triage all writes to find those that return something, implement the return in pg
- triage and replicate all select statements

**Comment by tiffanyhan** [comment]
could use coalesce to return a subselection of fields, or just return everything by default and drill down in code

**Comment by mattkrick** [comment]
let's return everything, if performance becomes a problem we can cache in redis and/or in memory a la dataloader

**Comment by tiffanyhan** [comment]
added to AC: implement a graphql mutation that takes an equality function to compare tables in rethink and pg

**Comment by mattkrick** [comment]
@tianrunhe could you let us know how to un-stuck this one?

**Comment by tianrunhe** [comment]
> @tianrunhe could you let us know how to un-stuck this one?

None! I just rerun the equality checker and both of the two DBs look identical:

```JSON
{"rethinkRecordsCompared":73948,"foundErrors":0,"missingPgRows":[],"rethinkRowCount":73948,"pgRowCount":73948,"areRowCountsEqual":true}
```

Issue unblocked. I'll start working on this next sprint!
