### ISSUE TITLE
Migrate to PG: Teams: Stop writes to RethinkDB (3 of 3)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4631]
Now that #4630 is complete, we can stop writing to RethinkDB.

AC
- [ ] all writes to RethinkDB are stopped

Estimate: 8 hours

**Comment by shapel** [comment]
Hello @mattkrick I would like you to consider my PR related to this issue. 
I know that it was not marked as "help wanted" but it was so low-hanging fruit that I couldn't resist ;)
