### ISSUE TITLE
pgtyped returns a Json type

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4633]
User.featureFlags should be a better type than just `Json` according to pgtyped.
This might/probably requires custom domains in PG

**Comment by mattkrick** [comment]
@tiffanyhan 

After review, this isn't really a problem with pgtyped, rather a problem with pg. By design, all json in postgres is unstructured.
To fix that, we can add an extension that will validate against a JSON schema (which is probably a good idea in general).
Then we could PR pgtyped to pull from that constraint. See: https://github.com/adelsz/pgtyped/issues/219

I probably won't do work on this until we have a _really_ good reason to use json in our fancy new PG database
Once we have that, here's what we'll do:

AC
- [ ] add json validator extension to PG
- [ ] PR pgtyed to use the constraint definitions, when available

Estimate: 40 hours

**Comment by tiffanyhan** [comment]
sounds good, thanks for looking into this!

**Comment by mattkrick** [comment]
kinda tangential, the battle between composite types & jsonb:
- pg supports composite types. a composite type is kinda like a pseudo table. e.g. we could make a `ScaleValue` type that has `{color, label}`. internally, pg stores this as a tuple. a tuple is gonna be strongly typed & take up less space than jsonb. the jsonb could be strongly typed if we add the json validator extension, but then the type is going to live in the constraint instead of in the data type. marginally harder to get at. 
- neither is gonna get strong types from pgtyped (for now). composite types have to get called with `to_json`, which means even if we PR pgtyped, it won't get strong types.
- neither is great. normalizing data should almost always be preferred & if performance is a problem we should worry about that in redis before we go denorming stuff in pg. one exception i can think of is for ScaleValues for the TemplateScaleRef because the rows will be immutable, guarantee to expand to the full array, store only 2 fields, and rely on the array index. those traits (namely immutability) make it pretty unique. that means we won't have to write headache-inducing queries to mutate the row.

**Comment by jordanh** [comment]
Noting we may have a good use case for this now. The proposed `IntegrationProvider` table contains a [semi-structured JSONB field called providerMetadata](https://github.com/ParabolInc/parabol/blob/ce6979046f17f7d795129256f30e22665ae03f4e/packages/server/postgres/migrations/1635354572171_addIntegrationProviderAndToken.ts#L47). If the provider is an oauth2 provider, for example, the jsonb fields will conform to a schema. It would be nice to be able to use types for these cases.
