### ISSUE TITLE
Meetings view has a team filter

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4634]
Blocked by #4624 

### Acceptance criteria
- [ ] A [team filter is available on the Meetings view](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=74%3A9238) for folks who are on more than 1 team

### Estimated effort
- 6 hours

**Comment by jordanh** [comment]
Still good. Still so right. But iceboxing anyway
