### ISSUE TITLE
New folks get a meeting series per type

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4637]
Output from #4546 also [see this comment](https://github.com/ParabolInc/parabol/issues/4584#issuecomment-772705804)

Blocked by #4624 The alternative idea to this is #4635

### Acceptance criteria
- [See Figma](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=128%3A0)
- When folks first sign up they are redirected to the Meetings view
- There is [a meeting series](https://github.com/ParabolInc/parabol/issues/4584#issuecomment-772705804) for each type: Retro 1, Sprint Poker 1, Check-In 1
- These are real meetings on their first team that is created when they sign up (they just need to see their existing team meetings)
- This doesn’t happen for folks who sign up via invite link or email
- This is probably some scripted use of mutations

### Estimated effort
- 20 hours

**Comment by jordanh** [comment]
Iceboxing
