### ISSUE TITLE
New meeting view: meeting types are easy to see

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4638]
Output from #4547 

While we have 3 meetings we should move away from the carousel:
- Folks easily see the options available
- Folks can choose their type quickly

### Acceptance criteria
- For laptop, [the 3 types are visible, have hover and selected states](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=116%3A1011), design can be iterated
- [For mobile](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=116%3A704) or [small inline views](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=103%3A68819) if that’s ever a thing, there are pills to toggle, design can be iterated

### Estimated effort
- 8 hours

**Comment by jordanh** [comment]
Closing in favor of #5255
