### ISSUE TITLE
Implemented a scheduling control and dialog (draft)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4639]
Output of #4547 and based on #4584

### Acceptance criteria
- The output is a date and time for the current meeting and optionally a recurring pattern for the meeting series
- The date and time uses the date and time selector [like the meeting time box](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=103%3A66856); only future values allowed
- The recurring pattern is like Google Calendar (days, weeks, or months but no year option)
  - Every X days
  - Every X weeks with day multiselect
  - Every X months on X day of the month
- TBD the date added (to the new or open meeting) must follow the recurring pattern or we separate them so that the next meeting can be pushed around outside of the recurring pattern to account for holidays etc.
- If there’s an empty state, the control says ‘Add to calendar’ or ‘Schedule’ and triggers the ‘Add to calendar’ dialog
- The scheduling dialog can be opened from the new meeting view or from the meeting card menu
- Stretch: when folks create a new meeting we automatically add default date, time, and recurring pattern (select today’s date, the closest time to now, and add recurring 1-2 weeks later based on type)
### Deferred
- When we build an integration with Google Calendar, there’s an option to push to calendar. It opens an auth window if folks aren’t integrated. When the date/time is added the first time, or edited on an existing meeting, we add the next/open meeting as an event on their calendar that follows the scheduling meta. **Issue to be written**
- We push 1 event per recurring period. 
### Figma
- From [the New Meeting view](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=67%3A312) (see multiple frames)
- From the Meetings view ([add to calendar](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=120%3A0) or [edit existing](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=105%3A67585))
- Examples of [Google Calendar recurring options UI](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=116%3A2097)
- [Various dialog/menu state options](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=67%3A237)

### Estimated effort
- 30 hours

**Comment by jordanh** [comment]
Iceboxing for now
