### ISSUE TITLE
Update 'Check-In meeting' to 'Standup' 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4646]
## Issue - Enhancement

We offer 3 meetings - retros, sprint poker and check-in meetings. One of these is not like the others, as 'check-in meetings' aren't what these types of meetings are called in agile typically. We should rename 'check-in meetings' to 'standups' to better suit the kinds of meetings our users actually run. 

### Acceptance Criteria (optional)
Users can:
   - See 'standup' meetings in the app 
   - Not see any references to 'check-in meetings' 
    
   
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This work is being carried out starting here: https://github.com/ParabolInc/parabol/issues/5255

Close this issue now that it's stale as a duplicate
