### ISSUE TITLE
Task Context

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4649]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/8883151/) 🔒  writes in:

> One thing I was thinking about that would be super helpful - when following up on tasks created from a retro, we sometimes have older tasks on the board and may have forgotten the exact context from the meeting. I find myself often returning back to retros from months prior & digging around to find the meeting discussion in order to re-familiarize myself with the task.
> 
> It'd be super helpful if there was maybe a small option on the task card itself on the board to quickly jump back to the discussion area where the task was created for more context!

**Comment by ackernaut** [comment]
+1

Thanks for opening this @gcrickman 

I think one key principle in a composable system is identifying links and nodes, i.e. how are 2 objects related. I’ll probably open a larger discussion about a first-class Parabol Task view. I’ll point to this as one concern, for sure.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/12204601) writes 🔒 :
> When tasks are created in the "Discuss" section for retros, they should be linked to the cluster of comments. If they aren't written well, they get divorced of that context in the "tasks" pane on the main page.

**Comment by jordanh** [comment]
@gcrickman contributed on #4169:

[A user](https://app.hubspot.com/contacts/3888472/contact/11377451) 🔒  writes:


>One thing that would help me a bit is if the actions are marked with which sprint (retro meeting) they were from. If you can do that, that would be great!

**Comment by jordanh** [comment]
Closing in favor of work being performed via #5063
