### ISSUE TITLE
Support using local avatar storage.

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4656]
​

AC

- [ ] when the CDN is set to local, the directory should be mounted as a volume in the docker config so upgrading does not wipe out the avatars

​

Estimate: 4 hours

**Comment by adaniels-parabol** [comment]
We should use a docker volume, we can call it `/self-hosted` with a local mount point of `/parabol-dir` (e.g. this is were the docker-compose file might live). This would take `/self-hosted/User/local%7Ctd1_L5y7fl/picture/wyPclFwWW.png` and persist it to a volume on the host system of `/parabol-dir/self-hosted/User/local%7Ctd1_L5y7fl/picture/wyPclFwWW.png` so when the container is destroyed we don't lose any uploaded content e.g. avatars.

Implementation could look like

- add volumes config to https://github.com/ParabolInc/parabol/blob/master/docker-compose.yml#L34
- `volumes:
      - /host/path:/container/path` e.g. /host/docker-compose-dir/self-hosted:/parabol/self-hosted

**Comment by adaniels-parabol** [comment]
Add volumes to https://github.com/ParabolInc/parabol/blob/master/docker-compose.yml#L34

volumes:
 - ./self-hosted:/parabol/self-hosted

We already have a handler called selfHostedHandler for /self-hosted

**Comment by tiffanyhan** [comment]
i couldn't find a good way to conditionally mount the volume depending on an env var. instead, i put the config in a compose override file named `./docker/docker-compose.selfHosted.yml` and documented usage in `./docker/README.md`.

reference: https://github.com/docker/compose/issues/3979
