### ISSUE TITLE
Retro: Divide grouping column by working area and formed groups area

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4662]
Today during group phase in a retro meeting, when user creates a new group, the group sits right in the middle of a bunch of reflection cards. Wouldn't it be great if we have two areas where in one area there are all of the ungrouped reflection cards, and on the other side there are formed groups?

To illustrate, today we have this:
<img width="344" alt="Screen Shot 2021-02-09 at 4 06 29 PM" src="https://user-images.githubusercontent.com/1879975/107445548-866ec100-6af1-11eb-8528-d353de0868c4.png">

I think it'd be easier and cleaner for user to group if we have it look like this:
<img width="348" alt="Screen Shot 2021-02-09 at 4 08 42 PM" src="https://user-images.githubusercontent.com/1879975/107445580-9be3eb00-6af1-11eb-845d-da54d51e46fe.png">

### Acceptance Criteria (optional)
 - [ ] In grouping column, there is a working area with reflections card, divided by a group area with already created groups
 - [ ] Maybe an explicit divider line?
 - [ ] To be less intrusive, we could introduce a button reads sth like "organize the column" and only when user clicks on it we will clean up the column and show the two areas

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This could make a nice batting practice. Adding label

**Comment by mattkrick** [comment]
adding the design tag, as this is probably too broad to start building.
questions:
- how do scroll containers work? do you always have to scroll to the bottom to find a group?
- if we trigger a re-sort locally, are we OK with the order being very different across team members?
- now that we have spotlight, does that suffice?
- we currently have an implicit grouping of putting cards next to each other that we think users will want to group. will this impact that feature?
