### ISSUE TITLE
Sign-in/create account options (SSO, Google Auth, Create Account) - Scope: Parabol managed instances

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#4666]
## Issue - Enhancement

Users accessing Parabol managed instances (e.g. standalone/not part of the public Parabol SaaS) still have the ability to sign-in with SSO, Google Auth, and/or Create an account. When operating in a managed instance it may be beneficial to have sign-in/create account options configurable for selection via ENV variables e.g.

#### MVP: 
- AUTH_SSO_ENABLED (true/false)
- AUTH_GOOGLEAUTH_ENABLED (true/false)
- AUTH_INTERNALAUTH_ENABLED (true/false)

Show/hide sign-in or create account options based on ENV variable.

#### Stretch MVP:
Having these options configurable from an admin section of the Parabol managed instance may also be a viable option. This would put the power back in the hands of the Parabol managed instance owner to configure AUTH options.

### Acceptance Criteria (optional)
- [x] AUTH_INTERNAL_ENABLED set to true, then Internal account workflow is enabled (show Create accounnt sign-up/sign-in), if false hide workflow
- [x] env vars AUTH_SSO_ENABLED, AUTH_GOOGLE_ENABLED, AUTH_INTERNAL_ENABLED created
- [ ] AUTH_SSO_ENABLED set to true, then SSO workflow is enabled (show SSO sign-up/sign-in), if false hide workflow
- [x] AUTH_GOOGLE_ENABLED set to true, then Google workflow is enabled (show Google sign-up/sign-in), if false hide workflow
- [x] `Forgot your password?" would be disabled if only AUTH_INTERNAL_ENABLED is set to false. We can't reset SSO or Google authentication source passwords in app
- [ ] 3 env vars above are added to action-devops enironment files
- [ ] 3 env vars above are added to dev, staging, and production servers
- [x] 3 env vars above are added as build-time variables in the client dev/prod configs & set as global typescript vars on the client (https://github.com/ParabolInc/parabol/blob/0ea032bfa3d57a52212278d47cee0bbe3d1972e2/scripts/webpack/prod.client.config.js#L125)
- [x] if `AUTH_INTERNAL_ENABLED` is disabled, all reset password routes don't exist (redirect to 404)

### Diagram
![image](https://user-images.githubusercontent.com/71724289/109099846-6510f600-76e9-11eb-9996-2214eb0e022c.png)

**Comment by jordanh** [comment]
@adaniels-parabol could you connect with @mattkrick to finalize AC?

**Comment by adaniels-parabol** [comment]
@mattkrick I'm thinking we scratch the Stretch MVP

~~"Having these options configurable from an admin section of the Parabol managed instance may also be a viable option. This would put the power back in the hands of the Parabol managed instance owner to configure AUTH options."~~

And AC would be:

- [ ] env vars AUTH_SSO_ENABLED, AUTH_GOOGLE_ENABLED, AUTH_INTERNAL_ENABLED created
- [ ] AUTH_SSO_ENABLED set to true, then SSO workflow is enabled (show SSO sign-up/sign-in), if false hide workflow
- [ ] AUTH_GOOGLE_ENABLED set to true, then Google workflow is enabled (show Google sign-up/sign-in), if false hide workflow
- [ ] AUTH_INTERNAL_ENABLED set to true, then Internal account workflow is enabled (show Create accounnt sign-up/sign-in), if false hide workflow

A value of false would only be assignable on a private managed instance as public SaaS requires all to be true.

Diagram below to better detail AC.

![image](https://user-images.githubusercontent.com/71724289/108959136-9f22bf00-7639-11eb-81ab-ab6d1461c355.png)

**Comment by adaniels-parabol** [comment]
@mattkrick `Forgot your password?" would be disabled if only AUTH_INTERNAL_ENABLED is set to false. We can't reset SSO or Google authentication source passwords.

**Comment by mattkrick** [comment]
this looks good!
some additional details for the implementer:

AC
- [ ] 3 env vars above are added to action-devops enironment files
- [ ] 3 env vars above are added to dev, staging, and production servers
- [ ] 3 env vars above are added as build-time variables in the client dev/prod configs & set as global typescript vars on the client (https://github.com/ParabolInc/parabol/blob/0ea032bfa3d57a52212278d47cee0bbe3d1972e2/scripts/webpack/prod.client.config.js#L125)
- [ ] if `AUTH_INTERNAL_ENABLED` is disabled, all reset password routes don't exist (redirect to 404)
- [ ] frontend matches Aaron's great pics above

**Comment by adaniels-parabol** [comment]
@jordanh ready to move to To-do

**Comment by jordanh** [comment]
Re-prioritized just now. When new instance(s) are ordered, let's bump this up a bit in priority

**Comment by adaniels-parabol** [comment]
I wonder if we need to look at a redesign of the login form prior to implementation?
