### ISSUE TITLE
Poker: agenda subscription bug?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4670]
## Issue - Bug

During sprint poker meeting, [a user](https://app.hubspot.com/contacts/3888472/contact/2531) 🔒  reports:

> When re-sorting the left nav list, those updates to the sort are not being shown in realtime to other team members. Folks reported that they needed to refresh to see other people's changes. Workable but less than ideal.

- **How serious is the bug?** P3

### Acceptance Criteria (optional)
All users can:
   - See changes to agenda when another users shuffles items around

**Comment by tianrunhe** [comment]
I think it's an updater/optimistic updater related bug:

![Uploading 2021-02-17 20.22.18.gif…]()

**Comment by tianrunhe** [comment]
Fixed in https://github.com/ParabolInc/parabol/pull/4850
