### ISSUE TITLE
Poker: show me who hasn't voted

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4672]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/8034101) 🔒  writes: 
> Show a list of who hasn't voted yet so we can appropriately shame them😂 (or know who hasn’t voted so we don’t have to play process of elimination with the top)
>
> If we can't get who hasn't voted, we'd like to be able to expand the "+1" in the team list at the top so we can do the mental process of elimination

Opening as a discussion. Let's resolve this down into an issue we can take as a next step.

**Comment by tianrunhe** [comment]
<img width="1307" alt="Screen Shot 2021-02-17 at 8 10 37 PM" src="https://user-images.githubusercontent.com/1879975/108304136-354b7680-715c-11eb-9daa-78599600717c.png">

Don't we already show who hasn't voted as a 🚫?

Also it's interesting that the user didn't realize the team list at the top is the attendance list and has nothing to do with the voting.

**Comment by ackernaut** [comment]
Before voting is revealed, there would be a list at the top by the checkmark card. If that overflows there would be a + overflow count as well. I wonder if they’re talking about that row of showing who has voted with overflow? But I do think they are talking about the state before revealing votes.

**Comment by ackernaut** [comment]
This person reported this, but it sounds like a bug. We should be showing a person’s avatar if they’ve chosen the `?` or `Pass` card:

>Hidden Participants

>I found that participants who used the "skip" card don't show up in the list of participants until a "Reveal points". That might also be true for the question mark card. This makes it difficult to determine who I'm waiting for as a facilitator.

**Comment by ackernaut** [comment]
Here are a couple of quick prototypes of one idea:

- [The next/ready control in the bottom bar](https://www.figma.com/proto/1DSwgYv0nRffpvb0Jnuc6G/Meeting-IA?page-id=655%3A7988&node-id=655%3A7989&viewport=219%2C514%2C0.25&scaling=scale-down)
- [The vote button in sprint poker](https://www.figma.com/proto/csERjrh67KZKgnT5VahFSb/Sprint-Poker?page-id=4572%3A196975&node-id=4572%3A196976&viewport=-1026%2C287%2C1&scaling=scale-down)

**Notes**:

- Wherever there’s progress, show a read-only status menu
- The status menu has 2 tabs: the first, default tab shows who hasn’t participated. It shows who’s viewing and who’s not connected
- The 2nd tab shows everybody who’s voted, probably can edit that
- We could probably skip the tabs and just show an avatar row and count for everybody who’s participated. In the case of sprint poker, the row would be redundant
- In the case of the bottom bar ready/next controls, it’s probably too busy to show a status menu on hover, a confirm tooltip on click, and then having to click again. We could test?
- If anything this idea serves to bring out the better ideas
- I’m looking for something small of value to ship to folks, in this case, facilitators

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/64282151) 🔒 writes:

> When estimating, I can't see who hasn't voted. Sometimes people are afk or otherwise distracted and it's frustrating to keep asking who hasn't voted yet. This must be a common problem on many teams. If I could see who hasn't voted yet I can call them out by name.

**Comment by ackernaut** [comment]
See discussion #5461

**Comment by drewhousman1010** [comment]
This came up in [our recent user feedback](https://action.parabol.co/meet/ikFJLIQKdy/discuss/1) retro on December 12th, 2022
