### ISSUE TITLE
Poker: agenda order same as import

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4673]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/2531) writes 🔒 :
> X requests that sorting should initially be the same as it was in the import from Jira, rather than what she described as a “random” order that might be creation date.

Opening as discussion to resolve to an issue with firm next steps.

**Comment by jordanh** [comment]
@mattkrick if items are added to a sprint from the Jira integration, don't the agenda items get created in order?

**Comment by tianrunhe** [comment]
I can verify the sort order for agenda item is the same as import order:

![2021-02-17 20 17 11](https://user-images.githubusercontent.com/1879975/108304650-52cd1000-715d-11eb-9143-41e741eff511.gif)

**Comment by mattkrick** [comment]
yeah, sort order is definitely the same as far as i know. perhaps the user has a repro?
