### ISSUE TITLE
Agenda completed state editing

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4677]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/8034101) 🔒  writes:
> Don't cross out an estimate card if I accidentally click ahead to another ticket – this bit me a couple of times

Ideally I think folks want to be able to "un-complete" a stage. This could be done product-wide.

While were in here, we could also allow folks to edit agenda item titles and such. With the complexities of pinning and such, @ackernaut this might make a good design BP, no?

**Comment by ackernaut** [comment]
From [this person](https://app.hubspot.com/contacts/3888472/contact/25526201/) 🔒 

>Story Sidebar

> Some other feedback from the same colleague:

> ‘I frequently lost my place in the sidebar list — in the list view, the Parabol UI doesn’t make it obvious which stories you’ve already pointed’

>I've felt this way too and I touched on it in earlier feedback. I think it would be useful to have two different "done" states in the sidebar:

>The first: I've submitted an estimate
>The second: A final score has been set by the facilitator.

>I feel like the "crossed-out" appearance should apply only when a final state has been set by the facilitator (final score or skip). The story is essentially "done" for everyone.

>Maybe a checkmark can be applied for the first state to let the current user keep track of which stories they've personally estimated.
