### ISSUE TITLE
Bug: Non-meeting member cannot go back to the meeting thread and make comments

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4688]
User who were not part of the meeting cannot comment to the discussion thread:

![2021-02-18 11 45 06](https://user-images.githubusercontent.com/1879975/108412771-0de9bd80-71df-11eb-89d3-56b9fb3b6e6f.gif)

_Originally posted by @tianrunhe in https://github.com/ParabolInc/parabol/issues/4682#issuecomment-781593367_

**Estimates**: 2 hours

**Comment by jordanh** [comment]
@tianrunhe is this a bug or a feature?

@mattkrick @ackernaut I think the intended behavior is for _nobody_ to be able to make comments after a meeting is closed correct?

i.e. I think the AC for this should clarify what our intent is. Should the comment box state change to disabled after a meeting is completed?

**Comment by jordanh** [comment]
Removing from backlog until AC is specified

**Comment by jordanh** [comment]
See also: #4539, #4540

**Comment by jordanh** [comment]
Setting as discussion until we've got clear AC
