### ISSUE TITLE
HubSpot property 'is user removed'

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4692]
## Issue - Bug

The property HubSpot property 'is user removed' does not update from false to true when someone deletes their Parabol account. I think this might also cause deleted users to still receive marketing emails since the workflow to stop this relies on this property.

Source: API - Property changed by use of a HubSpot API endpoint.

**Estimate**: 1 hour

**Comment by tianrunhe** [comment]
Confirmed that today we only update HubSpot on account creation but not deletion. Code is in this [line](https://github.com/ParabolInc/parabol/blob/master/packages/server/utils/updateHubspot.ts#L384).

**Comment by jordanh** [comment]
EE: 4 hours
AC:
   - [ ] When mutation fires to delete user, sets Contact `is_user_removed` property to `true`

**Comment by jordanh** [comment]
@tianrunhe is this still a thing?

**Comment by jordanh** [comment]
A [former user](https://app.hubspot.com/contacts/3888472/contact/71716401) wrote:

> I’m fairly sure I deleted my account, so I don’t know how or why you still have my email on file.
If my account hasn’t been deleted please action this immediately.

**Comment by jordanh** [comment]
Bumping this up on the backlog
