### ISSUE TITLE
moveTeamToOrg maybe loses BILLING_LEADER role

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4699]
In sales, all teams of an organization were moved to a different organization and back to the original organization. The teams were updated to be `isPaid: false`. However the org user that had the billing role no longer had the billing role when they were moved back. This causes the conversion prompt dialog to break the team view as the billing leader’s `preferredName` is undefined.

See [original chat thread](https://parabol.slack.com/archives/C4JAUUZ9P/p1614178369003700) 🔒  (internal team)

This mutation is used for sales and this behavior blocks their workflow.

### Steps
- Move all teams on an org to a new org
- Move all teams back to the original org
- Maybe see a broken team view
- Maybe see that there’s no longer a billing leader role on the org

### Acceptance criteria
- Triage mutation and check handling of BILLING_ROLE
- Push a fix if possible or update with more details

### Estimated effort
- 2 hours

**Comment by jordanh** [comment]
Will icebox. Will reopen if we see again
