### ISSUE TITLE
🐷🐷🐷 template colors

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4703]
## Issue - Bug

A user 🔒 writes:

![image](https://user-images.githubusercontent.com/103000/109104745-69391580-76e1-11eb-84e6-d6fb928bfc54.png)
> We were thinking that:
> House of Bricks should be green
> House of Straw should be yellow

I agree these colors should change. At least, how can Straw not be yellow??

EE: trivial
AC: 
  - new, more appropriate prompt label colors chosen

**Comment by jordanh** [comment]
Consider "fixing" when addressing #4704

**Comment by jordanh** [comment]
[Another user](https://app.hubspot.com/contacts/3888472/contact/60435351) wrote in to note how confusing the template colors were:

> Hi there!
> The team have been wondering why the colours are the way they are for the categories in the Three Little Pigs retro > template – think a few people found it a bit counterintuitive!

Removing stale and bumping this up the backlog

**Comment by jordanh** [comment]
**Include in next sprint?: y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/5) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by elielytz** [comment]
## Testing summary 
### Environment: local-master
Still observing the old color pattern on my side. In case there are extra steps to observe changes please let me know @tianrunhe . 
![issue#4703](https://user-images.githubusercontent.com/45159239/155675204-d5c13341-5324-4717-a523-22e82cd5ea28.png)

**Comment by elielytz** [comment]
**Story Points: 12**
  [See the discussion](https://action-staging.parabol.co/meet/bfW6S3yHXG/estimate/7) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by tianrunhe** [comment]
> ## Testing summary
> ### Environment: local-master
> Still observing the old color pattern on my side. In case there are extra steps to observe changes please let me know @tianrunhe . ![issue#4703](https://user-images.githubusercontent.com/45159239/155675204-d5c13341-5324-4717-a523-22e82cd5ea28.png)

Thanks for testing! I think you might need to clean your Redis cache

**Comment by elielytz** [comment]
@tianrunhe I have perfectly observed changes in the color arrangement and is as expected.

![Screenshot from 2022-03-02 01-19-20](https://user-images.githubusercontent.com/45159239/156258668-bef05fe3-aa8b-4001-adb0-e8493dd03083.png)

So I tracked down the issue and find that the changes are in _**parabol-feat-4703-pigs_color**_ branch and not in _**master branch**_ yet.

Great !!
