### ISSUE TITLE
New template migration

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4704]
It looks like we haven't been adding new meeting templates as migrations.
This means for folks running private instances, they don't get the templates that folks on the cloud instance get.
We should fix this.

AC
- [ ] a migration exists that adds all the retro & sprint poker templates. if a certain template already exists, it does nothing

Estimate: 4 hours

**Comment by jordanh** [comment]
Will affect majority (i.e. all) private instance folks, so adding p2 label

**Comment by jordanh** [comment]
Still a thing, will affect new private deployments will keep on list

**Comment by jordanh** [comment]
Iceboxing 😢
