### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4708]
https://sentry.io/organizations/parabol/issues/1790265980/?referrer=github_plugin

```
TypeError: Cannot read property 'id' of undefined
  at None (./packages/client/hooks/useSnacksForNewMeetings.ts:22:84)
  at Array.filter (<anonymous>)
  at d (./packages/client/hooks/useSnacksForNewMeetings.ts:17:8)
...
(6 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
@nickoferrall you can't map over a meetingRef, your fragment needs to be `(plural: true)`

**Comment by nickoferrall** [comment]
@mattkrick it looks like there's a [known relay issue](https://github.com/facebook/relay/issues/3041) when using `(plural: true)` with `readInLineData` so I used the solution suggested in that issue. Perhaps I should add a comment in the code explaining why?

**Comment by mattkrick** [comment]
ahh that's a bummer.
just pass in a team instead & then you can access `team { activeMeetings }`

**Comment by nickoferrall** [comment]
Unfortunately, `useSnacksForNewMeetings` is being used in [TopBarMeetings](https://github.com/ParabolInc/parabol/blob/73f281fc23fd30966f67c464108c80e361ad59ea/packages/client/components/TopBarMeetings.tsx#L27) which uses `teams` and [NewMeetingActionsCurrentMeetings](https://github.com/ParabolInc/parabol/blob/60c789134d79a97bcfbb868895c4bec68816d017/packages/client/components/NewMeetingActionsCurrentMeetings.tsx#L46) which uses `team`. If we pass in `teams`, we'll have the same `plural` `readInLineData` issue.

Is the issue with mapping through `meetingRef` aesthetic of functional? The Sentry issue that Tiffany shared here occurred before the mapping through `meetingRef` made it to prod. 

An alternate option could be scrapping `readInLineData` and going back to using a regular Relay query in the components using the hook?

**Comment by jordanh** [comment]
I can no longer find this in Sentry. Closing for now
