### ISSUE TITLE
Sprint Poker: GitHub: Estimate: Push to tag

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4718]
GH doesn't offer a story points field.
Instead, they have labels.
a common pattern seen in large OSS projects is to have a label like `Story points: 5`.
That means we need a way for them to create a label template (e.g. `${dimensionName}: ${points}`)
It's also possible that folks use a weighted shortest job first, where the effort is 5 & user value is 10 so the value would be 2. Should we push to a tag like `Value: 2`?
AC
- [ ] in the push-to-github dropdown, above "as comment" is "as label" that has an edit button
- [ ] clicking the edit button opens up a modal that defaults to `{{dimensionName}}: {{score}}`
- [ ] below the input is a example of what the label will look like, where score is the first value from the scale (e.g. `Story points: 5`)
- [ ] submitting the score will add the label to the issue in GH. if the label doesn't exist, we create it (if we can, if not, a friendly error message says the facilitator is not the owner of the repo)

Estimate: 24 hours

**Comment by jordanh** [comment]
I want to use this for other activities, like triaging bugs. I think this would be cool if it could interact with a label template. So I would have cards 0-5 and the tag I want to push to is `$key $value` like `p$0`

**Comment by jordanh** [comment]
Does this happen in the scale template editor?

**Comment by mattkrick** [comment]
i think it'll happen in the mapper in the estimate stage, same place where you choose which jira field to map to for the atlassian integration.

**Comment by mattkrick** [comment]
@nickoferrall

**Comment by mattkrick** [comment]
![Screenshot from 2021-09-03 12-35-53](https://user-images.githubusercontent.com/5514175/132057633-2bb3fe01-9d28-4379-b115-47ed4b929a9c.png)

**Comment by mattkrick** [comment]
This is tricky because `EstimateStage.serviceField` returns the currently selected option & doesn't remember the labelTemplate if changed from e.g. comment to template.

That means if a team changes from a label template to a comment, they'll lose their previous template. I think that has to be OK.
In a perfect world, we save their `labelTemplate` and we also save a `labelPreference`, but since this is mostly a set-it-and-forget-it setting i'm not too worried.

**Comment by mattkrick** [comment]
also tricky:
- we want `setTaskEstimate` outside the context of a meeting
- without a meeting, we can't determine what color to make the new label
- we have access to their other labels

plan:
- if we have a meetingId, we get the dimension.scale.color
- if not meeting, we could find a previous meeting & get the scale
- if not meeting, we could get the color of all their other labels & just pick one of those or 1 that's far away from those. this seems involved.

**Comment by mattkrick** [comment]
removing labels.
how do we know which label to remove?
- we could add key in the description & only remove labels that have that key (e.g. "Parabol"). This fails if they change the description
- we could look at the label name & see if that matches the label template. This fails if they change the template.

The second feels more professional. It'll be hard matching `Story 1points: 5` or `Value: XS` though because we don't know what part of the string holds the interpolation. I think it's actually technically impossible . We could brute force it by taking substrings & injecting those into their provided labelTemplate & see if we get a match. We could grab a list of possible values & iterate over those, but that's hard, too, because we're not sure what meeting template they used (I mean we're pretty sure, but not 100%). 

Since the easy way is a magic identifier in the description, I'll do that.

**Comment by mattkrick** [comment]
still don't like the description identifier, here are more thoughts:
- we need a way to extract the parabol estimate value from a github issue label. we do this from jira by reading the `storypoint` field. doing that let's us compare the jira value to the parabol value & make changes if necessary.
- trusting that users don't edit a field that belongs to them in github feels brittle
- it's impossible to work backwards from a label to a template. e.g. `sto4ry points4: 4` could be `sto{{#}}ry points{{#}}: {{#}}` or `sto4ry points4: {{#}}`
- we could generate a lookup table like `{'Story Points 4': 4}` to connect the label to the points in our system
- we could also brute force it: given a list of values & a labelTemplate, we could do `labelTemplate(value(i))` until we find a match & then use `value(i)`. 

the last 2 options seem the only viable way. the difference is we either store a list of labels (names and/or IDs) that match with the parabol value, or a list of parabol values + a label template. not too much difference.

where do we store this?? probably on the GitHubDImensionFieldMap, which is where the labelTemplate lives. 
if we do the first option, whenever a new FieldMap is created, we'd iterate through the scale values, generate all possible labels like `[{label: 'P0': value: 0}...]`. that's not great because they can push anything they want to GH, not just the values from the scale.

maybe instead when a score is pushed to github, we grab the parabol value & the github label & then upsert that somewhere. that way we only do work when a label is created.

worth noting that they could rename or delete a label at any time, so any of these values could be wrong.

maybe we store the GitHub label name to the estimate itself.
then when we read GitHub we compare the label to the most recent estimate.
if the estimate.label !== issue.label, then we know the value has changed.
to figure out the new value, we'd have to find an estimate where estimate.label === issue.label & from that we could determine the value.

i don't love keeping GH stuff on the TaskEstimate, but we do that with jira, so we'll keep being denormalized until we refactor.

changes to make:
- [ ] TaskEstimate table has a `GitHubLabelName`
- [ ] setTaskEstimate insert the `GitHubLabelName` 
- [ ] fetching an issue from github includes the labels (maybe OOS?) and the most recent task estimate
- [ ] if the task estimate label is not found in the list of issue labels from github, then we add a new task estimate
- [ ] the new task requires a GitHubLabelName and label. the GHLN is going to be one of the labels attached to the issue. which one?
- [ ] for each issue label, we search the TaskEstimate table for that `WHERE "name" = staleEstimate.name` to rule out other labels for other dimensions. 
- [ ] if there are multiple labels attached to that issue, we pick the most recent one (i think updatedAt is a thing) and remove the others. Else, we just pick a random one

**Comment by mattkrick** [comment]
**Story Points: 21**
  [See the discussion](http://localhost:3000/meet/78WDh4cXU4/estimate/1) in Sprint Poker `#1`

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
