### ISSUE TITLE
Domain change in Google causing problems

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4726]
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/contact/27384701) 🔒 writes:
 

> For a while now, me and my team colleagues have had issues to join meetings on Parabol. Typically we can log in, but then we can't join the meeting proper. It takes us several attempts, trying several ways to reach the meeting, until we finally get there.
> 
> I think this may have started when our employer changed email addresses from `@xxxx.eu` to `@xxxx.com`. We log in through Google as `@xxxx.com`, but when we land in the app our profiles still display as `@xxxx.eu`.
> 
> Another strange effect that I have noticed: sometimes (I think upon login, but not 100% sure), Parabol creates an organization and team for myself, regardless of already existing ones. As a result, right now I am a member of 3 different orgs with name "xxxxx's Org", which are unintended. I have deleted similar ones in the past.

> Can this be fixed so that my team doesn't have such a bad experience trying to get into our retrospectives?

**Comment by tiffanyhan** [comment]
@mattkrick you okay with always generating a random id when creating a new user from google oauth? i don't see the value in the extra conditional logic to either generate a random one *or* use the google id. as discussed in the previous check-in meeting, it seems we don't use the google id for anything internally, and keeping it for tracking these edge cases isn't a good use of time.

**Comment by mattkrick** [comment]
heck yeah, let's just give all new google oauth users a random suffix

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/25290201) 🔒  writes:

> Our company changed all emails domain from @ resultadosdigitais.com.br to @ rdstation.com. Most of us signed up to Parabol with Google. Because of how Parabol integrates with Google Sign In, now we are unable to login back to our original account. Trying to do so, we ended up with new accounts with @ rdstation.com.
> 
> Fortunately, someone was still logged in original account and invited the rest of us to join again the organization. But it only duplicated everyone and we also lost some history.
> 
> We tried some things to fix it for the past few months but every time there is a new difficulty on the way. We are very unsatisfied and starting to lose hope in this.
> 
> Long story short, everything is a mess now. Could you help us to restore our original accounts and change them to use the new email address? Also, could you help us reorganize all those duplicated organizations?
