### ISSUE TITLE
'highestTier' field in Hubspot seems like it's not updating sometimes

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4730]
## Issue - Bug

To send the appropriate communications to users and customers, we include a `highestTier` field on Contact records. It seems like this field isn't getting updated. 

Some example users: 
- User is showing as `personal` in [Hubspot](https://app.hubspot.com/contacts/3888472/contact/5206551) 🔒 , but `'pro` in [Amplitude](https://analytics.amplitude.com/parabol/chart/g32lmvx/edit/yp645n8) 🔒 This user hasn't met since December, and we did launch some update to the Hubspot data sync in December. 
- User is showing as `personal` in [Hubspot](https://app.hubspot.com/contacts/3888472/contact/11018651) 🔒 , but `Pro` in [Amplitude](https://analytics.amplitude.com/parabol/chart/g32lmvx/edit/yp645n8)🔒 They did meet in January. 
- User is showing as `enterprise` in both [Hubspot](https://app.hubspot.com/contacts/3888472/contact/10154751) 🔒  and [Amplitude](https://analytics.amplitude.com/parabol/chart/g32lmvx/edit/yp645n8) 🔒 , and they upgraded recently, and then met recently (Feb). 

### Acceptance Criteria (optional)
Parabol team can utilize Hubspot to send unique comms to customers, based on their highest tier. 

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Comment by tianrunhe** [comment]
This one is the same victim of the issue described in https://github.com/ParabolInc/parabol/issues/4842:

* Both of the first two users had their last meeting completed in the interval when we had HubSpot issue so they did not get chances to update the properties
* The third user had an `Enterprise Invoice Drafted` event on 02/09/2021, i.e., when we already fixed the HubSpot issue, so his `tier` property was properly updated.

Similar to #4842, we will backfill those contacts.

**Comment by tianrunhe** [comment]
There is no easy way to find out whose tiers changed during the HubSpot outage time window so I just took all of the pro and enterprise users from our DB and backfill their tiers on HubSpot.

There could be some users who downgraded during that time but we don't have that tracking information and I assume there weren't many.
