### ISSUE TITLE
facilitators unable to rejoin sprint poker created, team members unable to join as well

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4732]
## Issue - Bug

Someone creates a sprint poker meeting, accidentally closes or navigates away or just refreshes the page, and can't rejoin the meeting. I was able to reproduce while impersonating 
<img width="983" alt="Screen Shot 2021-03-03 at 1 13 40 PM" src="https://user-images.githubusercontent.com/11562889/109874571-236dd700-7c24-11eb-8c7c-30163284efdd.png">

This first happened with (paying user). For this user, I noticed the following weird behaviors: no meeting member was created for her, even though she created the meeting. the meeting showed in the db as ending 38 seconds after it first started. however, it seems the meeting was still showing in the user's home page as active. grayson was able to replicate while impersonating the user, but by the time I tried to do the same, the meeting showed as ended and I was able to view at as the user. the user has the meeting's team id in her `tms` User property. the facilitator of the meeting showed as another team member, so it looks like they took the facilitator role not long before starting the meeting and then ended it

For , i didn't notice any of the above weird behaviors so we can rule them out as root cause. the meeting was not ended, a `MeetingMember` was created for Michael, and the meeting's team id is in michael's `tms` User property. Michael shows as the meeting facilitator in the db.

### Acceptance Criteria (optional)
Users can:
   - as facilitator, rejoin the sprint poker meeting they start
   - as team member, join the sprint poker meeting that the facilitator started

Estimate: 4 hours.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tiffanyhan** [comment]
hypothesis: i think the relay fragment to get the meeting off of the viewer is not returning a meeting in `packages/client/components/MeetingSelector.tsx`

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/13461101) 🔒 writes:

> One time I got all the stories imported and I was able to start the meeting. My teammates joined and we got to the part where they could start pointing. As soon as they selected a card, they would also get locked out of the meeting and were shown the “Invitation Required” message. Then multiple people would “accept” their team members to be able to enter the meeting, but nothing would change for those who were locked out and they would remain locked out. Then, I, the facilitator, was kicked out.
> Now I have multiple active meetings, on multiple teams, that I can’t access or deactivate.

**Comment by tiffanyhan** [comment]
> A [user](https://app.hubspot.com/contacts/3888472/contact/13461101) 🔒 writes:
> 
> > One time I got all the stories imported and I was able to start the meeting. My teammates joined and we got to the part where they could start pointing. As soon as they selected a card, they would also get locked out of the meeting and were shown the “Invitation Required” message. Then multiple people would “accept” their team members to be able to enter the meeting, but nothing would change for those who were locked out and they would remain locked out. Then, I, the facilitator, was kicked out.
> > Now I have multiple active meetings, on multiple teams, that I can’t access or deactivate.

This person wrote in ~15 mins before the fix for the pooled connections went out yesterday. Let's see if the released fix resolves some or all of the reported problems.

**Comment by tiffanyhan** [comment]
Another user experiencing the same issue confirmed today that poker is now working for them. Closing via #4741

**Comment by lwille** [comment]
Experienced the same issue today. Interestingly, when I click the link multiple times, at some point I'll be prompted to confirm my own request. At the same time, when my team confirms my join request, nothing happens. Still seems buggy to me!

![image](https://user-images.githubusercontent.com/175639/145188866-e0653c83-f9db-44de-9027-8591098aa5a8.png)
