### ISSUE TITLE
Sprint Poker problems

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4733]
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/ticket/322230317/) 🔒 writes:

Full ticket [here](https://app.hubspot.com/contacts/3888472/ticket/322230317/)

> My team uses Parabol for team retros and were excited to see the new sprint poker feature (we were using a horrible Slack integration previously).
> 
> However, on our first go using it we've ran into a few issues:
> 
> 1) The biggest issue was every time the points should be revealed, every team member got a crash message:
> 2021-03-03_11-38.png
> I've attached the console log as well from this crash.
> 
> 2)  One of our team members constantly kept not being added to the team even though multiple people clicked accept on the join message.
> 
> 3) Votes seem to be sometimes lost/not recorded? Multiple times team members voted yet when revealed it showed they abstained.
> 
> 4) More of a product issue but every team member found it annoying that one needs to click the circled button to expand the Jira information every time... Would be better if this just didn't collapse or at least the state was saved between issues.
> 2021-03-03_12-28.png
> Thanks, and look forward to seeing the product improve!

AC
- [ ] root caused triaged, fixed or new issue(s) opened

EE 
- 1 hour

**Comment by jordanh** [comment]
@gcrickman I am going to close this issue b/c there are just too any individual points of feedback to address. Could you please:

* Split this into multiple issues and,
* Please make sure to add the screenshot?

Cheers sir!
