### ISSUE TITLE
TypeError: Cannot destructure property 'label' of 'e' as it is undefined.

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4737]
This came up when revealing votes in Sprint Poker. On refresh it cleared up for all users.

### Steps
- Go to a story that hasn’t been voted on with 2 unique viewers (the facilitator and another user in another browser instance)
- Vote with the facilitator, don’t vote with the other user
- Reveal votes (the button may be 1/2 full)
- See the issue
- It clears up on refresh

https://sentry.io/organizations/parabol/issues/2250156406/?referrer=github_plugin

```
TypeError: Cannot destructure property 'label' of 'e' as it is undefined.
  at None (./packages/client/components/PokerDiscussVoting.tsx:76:18)
  at Array.map (<anonymous>)
  at c (./packages/client/components/PokerDiscussVoting.tsx:75:16)
  at apply (./packages/client/hooks/useIsPokerVotingClosing.ts:20:9)
...
(12 additional frame(s) were not displayed)
```

### Acceptance criteria
- Triaged and fixed or updated/created an issue

### Estimated effort
- 1 hour

**Comment by ackernaut** [comment]
I reproduced this again.

![Screen Shot 2021-03-03 at 18 01 32](https://user-images.githubusercontent.com/307286/109889192-85d9ce00-7c4a-11eb-8f1b-d2e73565ad97.png)

**Comment by tianrunhe** [comment]
I cannot reproduce this but this is also the issue in production right now, see #4733

**Comment by ackernaut** [comment]
After another pass of testing on staging (that included more fixes) I didn’t see this bug. I was able to reveal votes. So we can keep an eye here but nothing blocking.

**Comment by ackernaut** [comment]
I know how to reproduce this now.

### Steps
- Go to a story that hasn’t been voted on with 2 unique viewers (the facilitator and another user in another browser instance)
- Vote with the facilitator, don’t vote with the other user
- Reveal votes (the button may be 1/2 full)
- See the issue
- It clears up on refresh

This happens on production. I’m not sure it was a regression in 6.2.0.
