### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4738]
This happened when interacting with the Sprint Poker deck. Also I noticed the thread sidebar had an issue at the same time. I’m not sure that they’re related but I haven’t seen another error for the sidebar yet.

https://sentry.io/organizations/parabol/issues/2250155184/?referrer=github_plugin

```
TypeError: Cannot read property 'slice' of undefined
  at navigateMeetingTeamUpdater (./packages/client/mutations/NavigateMeetingMutation.ts:149:53)
  at updater (./packages/client/mutations/NavigateMeetingMutation.ts:167:7)
  at Set.forEach (<anonymous>)
...
(13 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
We think this has been fixed...
