### ISSUE TITLE
Push to GitHub: $assigneeLogin error

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4740]
### Steps
- On v6.2.0-rc.1 on staging trying pushing a card to GitHub from the kanban or thread
- See this message:
>Variable $assigneeLogin of type String! was provided invalid value

![Screen Shot 2021-03-03 at 16 21 42](https://user-images.githubusercontent.com/307286/109887511-76a55100-7c47-11eb-9417-c06aae36ac4b.png)

### Acceptance criteria
- Triaged the issue

### Estimated effort
- 2 hours

**Comment by tianrunhe** [comment]
I fixed this in [this commit](https://github.com/ParabolInc/parabol/commit/b4769dc94cec9c891fbf66f8f9522edfe74b8bf9). Please verify!

**Comment by ackernaut** [comment]
That worked! Thanks and closing
