### ISSUE TITLE
Sprint Poker: no join snackbar until refresh

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4742]
### Steps
- When starting a Retro or Check-In, other folks see a join snackbar on the dashboard
- Other users don’t see a join snackbar when a Sprint Poker meeting is started

It makes me wonder if we missed some subscriptions in a few places?

### Acceptance criteria
- Triage real-time subscriptions for Sprint Poker meeting events

### Estimated effort
- 2 hours

**Comment by tianrunhe** [comment]
@ackernaut you are right! We are missing a the sprint poker start subscription. I fixed it with [this commit](https://github.com/ParabolInc/parabol/commit/a1b5d40c77cac5a82514d1960079d97590f7e028). Please verify!

**Comment by ackernaut** [comment]
Verified, thanks!
