### ISSUE TITLE
Display ants crawling animation for reflection groups title with word "bugs"

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4753]
AC:

- [ ] when a reflection group title has the word "bugs" in it & it doesn't have more than 5 words, then during the discuss phase you see ants crawl across the header (or empty space at the bottom)

​

Estimate: 16 hours

**Comment by mattkrick** [comment]
this is so good it gives me the ickies https://auz.github.io/Bug/

**Comment by ackernaut** [comment]
> this is so good it gives me the ickies https://auz.github.io/Bug/

+1 I think some might really freak out

**Comment by jordanh** [comment]
> this is so good it gives me the ickies https://auz.github.io/Bug/

Holy crap. We definitely need to get this shipped in time for April Fool's

**Comment by mattkrick** [comment]
i'll punt on the next piece of the GH poker integration & get this in today

**Comment by jordanh** [comment]
With this query:

```js
r.db('actionProduction').table('RetroReflectionGroup')
  .between(r.ISO8601("2021-03-24T12:00:00.000Z"), r.ISO8601("2021-04-07T12:00:00.000Z"), {index: 'createdAt'})
  .filter((row) => row('title').match('(?i).*bug.*'))
  .count()
```

We counted approximately 556 folks who saw bugs while this feature was live. N.B. I temporarily added an index to the table to make this counting possible.
