### ISSUE TITLE
Template copy and delete perms

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4757]
## Issue - Bug

Opening this as a bug and discussion. When this discussion resolves to 1–2 implementation issues, I'll close it.

Let's have a look at the issue(s):

<a href="https://www.loom.com/share/0dfa6d82e3b840ce8bc256351051ec56"> <p>Product | Template Copy & Sharing Perms - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/0dfa6d82e3b840ce8bc256351051ec56-with-play.gif"> </a>

Question 1: should all users always be able to copy/clone a template if they have read permission?

(I think yes)

Question 2: if I am not the team lead, should I be able to delete a template?

This one is trickier to answer. It feels odd to me that sharing is only for the team lead, but deleting isn't. What feels more natural to me is as a team member and non-author of a template:

- I should not be able to share nor delete a template or,
- I should be able to share and delete a template

I think it should be the latter (i.e. more permissive) and let user tensions build if folks want to lock things down.

**Comment by jordanh** [comment]
@mattkrick @ackernaut @tianrunhe what say you?

**Comment by tianrunhe** [comment]
Today, the permissions are:

|                 | Remove | Clone | Share |
|-----------------|--------|-------|-------|
| Team Member     |  √     |       |       |
| Team Lead       | √      |       | √     |
| Non Team Member |        | √     |       |

@mattkrick correct me if I'm wrong, I think the idea is to discourage people from creating multiple clones of the templates in their own team, and encourage people in the same org to use templates from other team?

**Comment by mattkrick** [comment]
yep, that's the goal.
this issue is similar to https://github.com/ParabolInc/parabol/issues/4505

Here's my recommendation:

- Team Member: can create new (including clone)
- Template creator: all of above + share & delete
- Team lead: all of above

**Comment by ackernaut** [comment]
**+1** to @mattkrick ’s recommendation above ⬆️

**Comment by jordanh** [comment]
Closing in favor of #4505
