### ISSUE TITLE
Add Teams control missing when nav has many teams and some level of browser zoom in/out

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4761]
I haven’t confirmed it yet, but I think the Add Teams control is getting pushed out of view when the left navigation has a long list of teams. Reported by [this person](https://app.hubspot.com/contacts/3888472/contact/3595501/) and [this person](https://app.hubspot.com/contacts/3888472/contact/3322301/) 🔒 

Meanwhile folks can still reach this URL to add a new team: https://action.parabol.co/newteam/1 

### Acceptance criteria
- [ ] The layout is fixed saving room for the bottom section of left navigation including the Add Teams control. A long list of teams will fill the vertical space allowed with overflow

### Estimated effort
- 2 hours

**Comment by gcrickman** [comment]
A [customer](https://app.hubspot.com/contacts/3888472/contact/3322301) 🔒  writes: 

> We figured yesterday, if my chrome browser is set to 67% Zoom, it will not show the 'Add Team' option (attached a screenshot). Oddly, selecting any other Zoom setting on the browser (e.g. 50%, 80%, 100%). We reproduced it on my colleagues' browser as well.

**Comment by ackernaut** [comment]
This [customer](https://app.hubspot.com/contacts/3888472/contact/3595501/) 🔒  writes: 
>I was viewing on my 2nd monitor, but moved it to my laptop monitor and now I see the add team option!

**Comment by jordanh** [comment]
@ackernaut – I forget, is this still an issue?

**Comment by ackernaut** [comment]
Yes, this is still an issue.

**Comment by jordanh** [comment]
Not sure if it's still a thing. Iceboxing
