### ISSUE TITLE
Visual highlight on individual update cards (check-in)

### ISSUE THREAD

**Issue by DoriRu** [ParabolInc/parabol#4764]
## Issue - Enhancement

As a new user, I found myself listening to individual updates but not always being able to track which specific card was being referenced by the speaker (e.g. "oh *this* is done", "I'll move *this* over to active"...). 

Some visual indicator of the focus of the conversation would help me track the conversation. Could be:
* a visual highlight on a card on hover or on select (by the currently active presenter)
* a visual highlight on a card when it's moved across columns or statuses

**Comment by jordanh** [comment]
Similar to/see also #2191

**Comment by jordanh** [comment]
Implemented in #5858 !
