### ISSUE TITLE
Next concepts for stand-up meetings created

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4771]
We’re looking to validate a ‘Inspirations’ feature that shows folks what they’ve been working on or talking about in the context of a meeting to help them recall and trigger their input.

We want to validate this pattern in the Reflection Inspiration issue #4509 — we could work on that issue and this one in parallel to inform each other, but validating it in the Retro seems like the quickest way to get rid of the RAT

With stand-ups we want to validate a simple workflow that allows folks to curate (async or sync) a set up updates (a new type of thread/comment object that refers to another work object) and then share their updates in rounds (async or sync).

### Acceptance criteria
- Created sketches, concepts, and/or prototypes to further explore Inspiration patterns in Standups
- Identified 3-5 users to share these with
- Wrote the next-step issue (i.e. more narrowly scoped design task, first thing to validate, etc.)

### Estimated effort
- 8 hours

**Comment by ackernaut** [comment]
This issue was written before we made the concepts for Reflection Inspiration. There will probably be concepts and prototypes in addition to sketches. :)

**Comment by ackernaut** [comment]
Pausing here (back to To Do), gonna take a 2nd pass at #4916 to complete the swing there

**Comment by ackernaut** [comment]
The next step here is to document, organize, and share the latest progress so that we can break this down.

**Comment by jordanh** [comment]
Do you have anything raw to share? I'm curious how what you're thinking about might jive with what I'm thinking about...

**Comment by ackernaut** [comment]
🔒 As we reshuffle our ideas moving forward, we’ll break them down into issues as we validate risks and address first steps. See my latest take here: https://www.notion.so/parabol/Standup-Ideas-394d11e8aa6343b081c88fb281ec75d8
