### ISSUE TITLE
Refactor GraphQL Schema into typedefs & resolvers

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4778]
This has been years in the making. I've been sitting on it because I've wanted the tech to mature before we make the move.

### The problem

Today, our GraphQL schema is created in JS. This is how schemas were made back in 2015. Around 2017 it was possible to write a schema using the Schema Definition Language (SDL). We already had our schema written, so we didn't have a pressing need to make the switch, but there were still problems:

- import statements can cause circular references, since graphql is circular by nature. so, we have to fallback to using `require().default`, which limits DX & our ability to ever move to pure es modules
- We can't do schema stitching. It'd be great to have `teamMember { integrations { github { api { ...THE ENTIRE GITHUB GRAPHQL SCHEMA`
- our resolvers are actually authenticators, validators, and resolvers
- mocking server data! instead of fetching responses from DBs & APIs, we can just have it return mock data. this will be a big win when it comes to things like front-end styling where we don't care about the accuracy of the data, we just want a quick result

The solution:
- Take the schema.graphql & use that as the starting point. from there, we'll need to rip the resolver out of every GraphQL object. This will take a couple days if done manually. a codemod might save us some time, but then again, it might take longer still.

Estimate: 40 hours

**Comment by jordanh** [comment]
Is there any way to do this in pieces? It'd be nice to break this down into several issues.

**Comment by mattkrick** [comment]
mmmm, yeah.
- make a resolvers folder
- go through each object, copy the `resolve` function & move it to a new file in the resolvers folder
- when complete, point to the `resolvers` folder

**Comment by mattkrick** [comment]
Notes from chatting with Ben:
- Ben will use this issue to design a roadmap to get from where we are to where we should be (SDL + typesafe resolvers)
- A good example of what we should target is here https://github.dev/homebound-team/sample-app
