### ISSUE TITLE
Poker: unable to select Jira point field

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4779]
## Issue - Bug

[A user](https://app.hubspot.com/contacts/3888472/contact/2531) reports 🔒 

![image](https://user-images.githubusercontent.com/103000/111526716-559b3080-871c-11eb-8ff0-83833dd4977d.png)

- **How serious is the bug?** P2
- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 2 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Select the JIRA field of their choice during estimate, have it stick, and work or
   - Triage is performed to find the root cause of the bug, timeboxed to ~1 hour.

**Comment by mattkrick** [comment]
Pretty sure this was caused by the updated z-index value on the peeking component, the invisible component sits on top of the dropdown arrow. the fix is in #4791
