### ISSUE TITLE
Jira summary, description missing for non-integrated participant

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4782]
### Steps
- With 2 browser, start a poker meeting with 1 and join with the other
- The facilitator adds Jira issues during the Scope phase
- The 2nd participant isn’t integrated with Jira
- The facilitator advances to the first Jira item in the Estimate phase and sees the summary, description in the top card
- The 2nd participant doesn’t see the summary, description but it’ll appear on refresh
- Note: this doesn’t seem to be a problem if both users have the same Jira site added
- Note: this is happening in production at least as of v6.2.0

### Acceptance Criteria
- A non-integrated participant can see Jira content when advancing from the Scope to the Estimate phase

### Estimated effort
- 4 hours

**Comment by mattkrick** [comment]
wonderful find!
