### ISSUE TITLE
Story can be null in PokerEstimateHeaderCardParabol

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4785]
Affected 48 users in 16 days

https://sentry.io/organizations/parabol/issues/2247547498/?referrer=github_plugin

```
TypeError: Cannot destructure property 'content' of 'l' as it is null.
  at c (./packages/client/components/PokerEstimateHeaderCardParabol.tsx:96:10)
...
(7 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
looking here: https://github.com/ParabolInc/parabol/blob/774c4cf2dfbceaa2d56910583e325080c55deae0/packages/server/graphql/types/EstimateStage.ts#L154

if you create a task, add it to the poker meeting, then go back to the dashboard to delete the task (empty out the contents) then the task gets deleted, thus causing a null story.

i'll let you decide how to solve this :wink:
