### ISSUE TITLE
A short-term icebreaker randomizing solution

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4804]
See this discussion for background #4772 

### Acceptance criteria

- Proposed some ideas

- Sketched some ideas

- Created some lightweight concepts in Figma

- Identified next steps

### Estimated effort

- 4 hours

**Comment by ackernaut** [comment]
We’re gonna check in with Enrique about working on this.

**Comment by enriquesanchez** [comment]
Created implementation issue #4910
