### ISSUE TITLE
Org consolidation & email verification

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4805]
## Issue - Enhancement

When a company company hits PQL status, sales manually forces email verification, as verifications complete, they get moved to a company-wide org

### Acceptance Criteria (optional)
  - TBD

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick let's nail down the AC for this. Something like:

AC
- A mutation that takes either a domain name or list of orgs, plus a target org to consolidate to
- Copy written for the notification email (perhaps linked as a separate issue?)
- Email verification now checks user to see if org migration is pending, if pending moves user to org after successful verification

**Comment by jordanh** [comment]
Note to self: need a follow-on issue to update org view with some stats to make this really effective as a conversion driver

**Comment by jordanh** [comment]
Note to self: #4180 should be done around the same time

**Comment by gcrickman** [comment]
We have been recently auditing Pro accounts and there seem to be a few with teams/orgs outside of the upgraded one. It might be nice to have a way to periodically consolidate these or prevent them from creating orgs outside of the upgraded one's.

**Comment by mattkrick** [comment]
extending the AC
- [ ] a flag exists on managed orgs like `isManagedOrg` that gets flipped when the mutation is called. this tells us that there is a 1:1 relationship between Org & Company
- [ ] on the User object in graphql a flag exists like `isManagedByOrg` that is true if any of the user's OrgUsers are a part of a managed org.
- [ ] created new orgs is disabled on the frontend & backend for users where that flag is true

**Comment by jordanh** [comment]
Related to: #4407
