### ISSUE TITLE
Poker: Votes not recorded

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4808]
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/ticket/322230317/) 🔒  writes:

> Votes seem to be sometimes lost/not recorded? Multiple times team members voted yet when revealed it showed they abstained.

**Comment by jordanh** [comment]
Adding discussion label until we have clear reproduction criteria

**Comment by tianrunhe** [comment]
I think this is the symptom of the pg connection pool issue, which was already fixed in https://github.com/ParabolInc/parabol/pull/4741

**Comment by jordanh** [comment]
We haven't seen this one for awhile; closing
