### ISSUE TITLE
Poker: Jira data visibility

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4809]
## Issue - Enhancement

A [user](https://app.hubspot.com/contacts/3888472/ticket/322230317/) 🔒  writes:

> More of a product issue but every team member found it annoying that one needs to click the circled button to expand the Jira information every time... Would be better if this just didn't collapse or at least the state was saved between issues.
> 2021-03-03_12-28.png
> Thanks, and look forward to seeing the product improve!

Screenshot [here](https://app.hubspot.com/contacts/3888472/ticket/322230317/) 🔒  to maintain anonymity

**Comment by tianrunhe** [comment]
We [added scroll bar](https://github.com/ParabolInc/parabol/pull/4755) to the story card so it should address some of the tension here.

**Comment by jordanh** [comment]
Closing this one for now to see if the shipped changes address the tension
