### ISSUE TITLE
Poker: Can't add team member 

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4810]
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/ticket/322230317/) 🔒  writes:

One of our team members constantly kept not being added to the team even though multiple people clicked accept on the join message.

**Comment by jordanh** [comment]
@gcrickman do you have any reproduction steps for this one? Do you have any details on the team or time of the meeting?

**Comment by gcrickman** [comment]
> @gcrickman do you have any reproduction steps for this one? Do you have any details on the team or time of the meeting?

The user attached the console log when the errors were happening. It's on the ticket [here](https://app.hubspot.com/contacts/3888472/ticket/322230317/) as an attachment from the email.

**Comment by tianrunhe** [comment]
The attached console log is for the https://github.com/ParabolInc/parabol/issues/4807 which was already fixed. I think this particular one is also fixed by @tiffanyhan but I'll let her confirm.

**Comment by jordanh** [comment]
@tiffanyhan May we close this one?
