### ISSUE TITLE
Teammate can kick you out of Poker

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4811]
Steps to reproduce:

- User A and User B go to a Story in the Estimate Phase
- User A goes back to the Scope phase and removes the Story that User B is currently on
- User B will be kicked out of the meeting and won't be able to go back to the meeting unless they change the URL from the Estimate to the Scope phase

### AC

- [ ] If the active Story in the Estimate Phase is removed, users are moved to the previous stage in the Estimate Phase

**Comment by jordanh** [comment]
This is a good one
