### ISSUE TITLE
Improved empty state for discussion thread

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#4813]
## Issue - Enhancement

Follow up of #3901 and #4812. We want to improve the clarity and visuals of the empty/initial state of the discussion and task thread.

This proposal adds an illustration from Parabol's illustrations library and improves the clarity of the message displayed.

### Current vs. proposed

<img width="816" alt="Screen Shot 2021-03-24 at 12 17 05 p m" src="https://user-images.githubusercontent.com/3276087/112363232-e5038f00-8c9a-11eb-8745-e7f863d57800.png">

[Please refer to the Figma file for a more detailed view of the design](https://www.figma.com/file/Ia7SoJcudXUM3nvOYXOldR/comments-and-tasks?node-id=130%3A0).

### Acceptance Criteria
Users can:
   - Easily understand that the component is in an empty/initial state
   - Use the proposed design as a guide for adding a new comment or creating a new task

**Estimated effort:**
- 10 hours.

**Comment by jordanh** [comment]
Brilliant. Adding this to the next sprint, sir
