### ISSUE TITLE
Int cannot represent non-integer value: "Story Points"

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4819]
## Issue - Bug

[Sentry issue](https://sentry.io/organizations/parabol/issues/2238795578/?project=107196&statsPeriod=14d). 1.6K events so far since release 6.1.0.

> Error: Int cannot represent non-integer value: "Story Points"

### Acceptance Criteria (optional)
- [ ] Issue is fixed

Estimate: 1 hour to triage. More if root cause is already identified.

**Comment by tianrunhe** [comment]
Looks like this is related to `[server/graphql/types/JiraDimensionField.ts](https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/types/JiraDimensionField.ts#L19)`: the type for `dimensionName` should be `GraphQLNonNull(GraphQLString)` instead of `GraphQLNonNull(GraphQLInt)`

**Comment by mattkrick** [comment]
1.6k events! shoot, this is probably worth a hotfix. i'll get it into staging
