### ISSUE TITLE
Schedule Slack Notifications in Advance 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4820]
A [user](https://app.hubspot.com/contacts/3888472/contact/26065851) 🔒  writes:

> There are already notifications for when a meeting is created, but my team are in the habit of writing up retro tickets in advance of the meeting so we can get straight down to business. It'd be nice to be able to schedule Slack notifications, say, a day or two in advance of the end of the timer we run in advance.

## Issue - Enhancement

**Comment by ackernaut** [comment]
This is interesting. Today if folks use the time box affordance the notification goes out immediately. It make look something like this:
- A team lead is setting up for the next 2-wk sprint
- They have the habit of opening the retro early to gather comments over the course of the sprint
- They use the time box, saying the Reflect phase will end on Fri 2 weeks from now, and check to send to Slack
- The team gets a notification that they have until then to reflect; they were also probably just notified that the retro meeting was started
- Over the course of 2 weeks I imagine that message is water under the bridge in the Slack channel; if folks have the habit to add comments early maybe they go looking for the board; but most likely they still write all of their cards at the head of synchronous meeting time together on that ‘Friday’ at the end of their sprint

What we could consider:
- A team lead sets up for their sprint, and opens a retro board early (at the head of 2 weeks0
- They schedule a reminder notification to be sent to the team’s channel 2 hours before the meeting. Maybe there’s a notification now (alert the team that the space has been made) and later (remind the team to get some comments in early)

Note:
The ‘Inspirations’ pattern should help with folks remembering what to reflect on. However it depends on what filters and sorting we give them. If they see the latest activity, then it probably matches their memory, and serves as recency bias. If they see the ‘most activity’ whatever that qualifies as, maybe it was important, maybe it was just a big conversation but not that important. If we allow them to sort by least and less activity, maybe they see something that got stuck and cooled and it triggers a topic of why.

I still think prompting folks for pre-work is a good idea, regardless of Inspirations. It allows them to take the time to form their thoughts in writing, and perhaps if the inspirations panel is a thing one day it can inspire them in pre-work too—just maybe we have a great combo that elevates the quality and outcomes of the conversations in a retro.

**Comment by boardfish** [comment]
Baseline and considerations are both accurate to what I'd like to see here. Thank you for considering this in such detail so soon. ✨

I figure you're using Shape Up (given the mention of an affordable), so I understand that this isn't a commitment. Either way, it's cool to see this work being done publicly! Parabol's a great product that's serving our team at @raisedevs nicely, so thanks for the great work.

**Comment by ackernaut** [comment]
@boardfish thanks for the kind note! 🙏

**Comment by jordanh** [comment]
@ackernaut I think confidence is high enough here to create a proper design issue with some AC. Could you either enhance this one or open a new one, link, and close this one? Either way, let's get it added to the backlog

**Comment by jordanh** [comment]
Will be resolved by #4994, closing this discussion
