### ISSUE TITLE
Adds active viewer avatar group to meeting cards

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4835]
A continuation of #4623 

### Acceptance criteria
- Avatars dynamically fill [the space available to the right of the meeting name](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=265%3A72135), with an overflow count.
  - As more folks join, the avatars and/or overflow count update in real time for the current viewer
- In the case of a long meeting name we can:
  - Set the max width of the meeting name to be 100% minus the width of 3 avatars (or 2 avatars and the count badge) plus an 8px margin between the visible avatar footprint and the end of the meeting name (**see Figma**). Truncate the string with ellipsis via styles
- Alternatively, if the layout above is too fussy, we can ([see last examples](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=265%3A72135)):
  - Append the card with a row (right or left-aligned) when there are active viewers (Note: I don’t mind that the card grows when there are active viewers. It’ll draw more attention. The rows can wrap and clear that taller card.
  - (or)
  - Wrap the meeting name to a second line
- Stretch goal: sort the meeting cards by most active viewers. The card with the most active viewers should be first. The sort is on initial load. After that if a bunch of folks join a meeting the card will get avatars in real time.
  - Optionally we could sort by newest first and most folks will probably get the same results. For teams that do open async meetings those would get pushed down.
  
### Estimated effort
- 12 hours

**Comment by mattkrick** [comment]
as a first pass, i'm gonna give the meeting name & the avatar list their own row
- if we put them on the same row we can only get about 3 avatars in. plus, we'd have to constantly monitor the width of the title & number of participants in order to figure out how to optimize the use of space. certainly doable, but just takes more work

**Comment by ackernaut** [comment]
@mattkrick how will it stack up? what’s the order of the rows?

**Comment by ackernaut** [comment]
I could see:
- Meeting name
- Meeting meta
- Avatars

But I wonder on which row we’d stick the more menu if we moved it to the lower section of the card?

**Comment by ackernaut** [comment]
@mattkrick see this for an idea on how to stack things up: https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=332%3A72920
