### ISSUE TITLE
Adds an option menu to the meeting card

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4836]
Continuation of #4623 
### Acceptance criteria
- [See Figma](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=221%3A0)
- A menu appears in the top right
  - A 32px control is inset 4px. The icon is 24px centered. Use `more_vert` icon
  - The hover state may use a transparent white background (`#FFFFFF26` = [15% transparency](https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4)) since we want to play off the illustration background color. (We are avoiding transparency and trying to stick to palette variants only, but I think this is a good case for it)
- The menu item is:
  - (`person_add` icon) Copy invite link
- When the person taps ‘Copy invite link’
  - The menu closes
  - A snackbar appears ‘Meeting link copied!’ with `autoDismiss: 5`
  
### Deferred
Let’s wait until folks ask for a way to remove test meetings from the meetings view.

- The menu item below ‘Copy invite link’ is (`flag` icon) ‘End meeting’
- When the person taps ‘End meeting’
  - The menu closes
  - TBD: they get a dialog that asks them to confirm (or do you have a better idea? e.g. only show this option if the user has a role like facilitator? team lead?)
  - A snackbar appears ‘The meeting has been terminated’ (`popEndMeetingToast.ts`)  

 ### Estimated effort
 - 12 hours

**Comment by mattkrick** [comment]
hey @ackernaut you OK if i remove the click handler from the card image? having a click handler on the options button & a different click handler on the big image right behind it could result in some folks entering the menu accidentally when they just want to open the menu

**Comment by ackernaut** [comment]
@mattkrick I’m okay with that, but I have an idea and a lightly associated thought:
- What if we position a div in the upper right and stick the button in it. We could not allow clicks through that div. Give it plenty of space around the button (maybe the div is like 64 x 64 and the 32x32 button is within the top right 4 pixels)? This way folks could still click most of the card including the illustration to get to the meeting
- Per @enriquesanchez ’s feedback we should make things that go to places a link so that folks can use browser options like open in a new tab. In this case tapping the meeting card would be a link. Are you down with that here? Mind making that change if you’re updating the handler?

**Comment by mattkrick** [comment]
hmmmm, it feels a little unconventional to have a 32px deadzone around the button, it just isn't a pattern i've encountered anywhere else. i guess we could just increase the button's area?

i'm down to make things anchors for accessibility, but we gotta be careful with it. I'd contest that encouraging multiple tabs is a great pattern for websites, but for single page apps like ours, we want to actively discourage that behavior as much as we can

**Comment by ackernaut** [comment]
@mattkrick nah I like the 32x32 button sizing that is flat before hover. I’m okay skipping the deadzone idea. If anything something like an 8px deadzone all the way around would probably be in the spirit of MD recommendations.

Also, we can defer the anchor bit and discuss more.

**Comment by ackernaut** [comment]
https://material.io/design/layout/spacing-methods.html#touch-targets

**Comment by mattkrick** [comment]
if only they had guidance for a touch target that is on top of another touch target!

**Comment by mattkrick** [comment]
i sifted through more material design patterns:
- https://material.io/components/cards#card-collections
- https://material-ui.com/components/cards/

none of the examples have a click handler on top of another click handler, and we don't do this in other parts of the app, so I'm thinking there's gotta be a better way:
- we could put the icon on the 2nd half of the card 
- we could make the meeting name clickable & the 2nd half clickable, but not the big image 
- ???

**Comment by ackernaut** [comment]
Eh we can justify our own pattern above the baseline that is MD. I like that if you hover the card you can tell you can click it. However I’m not sure about the card elevation when you can’t move it.

In Google Keep you can click a card and it expands, or you can tap one of the menu toggles. They’re all on the same surface. I think that’s a close enough example.

**Comment by ackernaut** [comment]
On a Google Keep card, notice that if you click the dead space in between the bottom menu toggles it doesn’t expand the card. So it only expands if you tap on the top part.

We should think about how we give visual feedback on hover if only tapping the bottom content section will go to the meeting. We should change elevation on the whole card?

**Comment by enriquesanchez** [comment]
On the topic of using anchors for things that take you elsewhere, it's important we stick to semantic HTML for many reasons, but mainly for a11y.

Links that are not anchor tags are pretty much non-existent for folks using assistive technology. Tools such as screen readers won't be able to identify these elements as links (because they are not) and thus wont be communicated/presented to the user. We also affect keyboard navigation, by not offering appropriate focus stops and focus states.

While I would argue that it's up to the user if they want to open things in new tabs, it's more important that we present them as links for the reasons stated above.

We lose nothing by sticking to semantic HTML and instead gain a lot in terms of usability and accessibility.
