### ISSUE TITLE
As a DevSecOps engineer, I want to implement a IronBank push pipeline to execute a anchore-scan

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#4838]
As a DevSecOps engineer, I want to implement a IronBank push pipeline to execute an anchor-scan

AC:

- [x] Passes anchore-scan in Ironbank

**Comment by adaniels-parabol** [comment]
Waiting on IB folder to be restored so we can test

**Comment by jordanh** [comment]
@adaniels-parabol may we mark this as Closed?
