### ISSUE TITLE
HubSpot parabolId not set reliably

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4842]
## Issue - Bug

Without the `parabolId` field in HubSpot we can't tell reliably who is, and who is not a user. This may cause us to spam contacts. This is bad.

This affects hundreds (thousands?) of users today. For a full report, see: https://app.hubspot.com/reports-list/3888472/77172779/  🔒  (created by @avivapinchas)

- **How serious is the bug?** P2
- **Estimated effort:** 6 hours

### Acceptance Criteria (optional)
   - When HubSpot integration fires, the parabolId is updated
      - this should handle cases where the contact record exists in HubSpot, but `parabolId` is unset

**Comment by tianrunhe** [comment]
I've made good progress on this today! I've found that users in that report have paused their accounts and then unpaused. @avivapinchas I'd like to know when an account was paused, do we have any automated workflows in HubSpot to delete their records? Because what seemed to happen is that when the account was unpaused, our code base assume that the record in HubSpot still exists, so we only need to update some properties (`userId` is not in the list). But in reality the record was gone so the effect of the code is to create a new record with partial data.

**Comment by tianrunhe** [comment]
Copying my correspondence from Slack:

> now I believe what happened is: during mid December to late January, there was a period of time when we missed adding the HUBSPOT_API_KEY to the server (refresh your memory here), causing all HubSpot calls failed. All new accounts created during that time period will suffer from this problem. Since account creation is the only time we update the parabol id field, if you missed that time window, you won’t have it in the future. However since HubSpot identifies user by email, we can still find the user and update other properties like meeting streak, last met at, etc. That’s how you come to this weird scenario where they don’t have parabol user ids, but they still have other properties available.
Matt & I decided to do backfill for those records. To make it more useful for future, I’m gonna write a generic script which takes some data from our DB, find contacts in HubSpot and update them accordingly.

**Comment by tianrunhe** [comment]
Fix is pushed and will be included in this week. This will allow user Id to be always included and updated on meeting completed events.

In the mean time, I backfilled 4000+ contacts in HubSpot with missing user Ids. There are < 20 orphans left with various reasons from invalid email to not found in our DB so I leave them alone.

**Comment by tianrunhe** [comment]
I checked those 14 people. 3 of them do have user ids so I backfilled them manually. Might be something I missed in my backfill script. The other 11 do not have records in our DB, indicating that their accounts were deleted.

We should monitor the list in case there are sth else I missed to make it grow again.
