### ISSUE TITLE
favor built assets over __STATIC_IMAGES__

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4847]
for our cloud offering, it doesn't really matter if we let webpack control our assets or if we just point to them manually. for airgapped deployments, they may not have access to our S3, so we'll need to let webpack manage those illustrations.

The exception here is emails: if we inline images in emails, then it's possible the message will get clipped or bounced. so, it's probably better to use links for emails, when possible. (little icons should be OK)

**Comment by jordanh** [comment]
During Sprint Planning, @mattkrick suggested:
> Let's elevate the priority of this one before we do another private deployment

cc @adaniels-parabol

**Comment by mattkrick** [comment]
closed in #5701
