### ISSUE TITLE
Incorporating retro summaries into Slack 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4859]
A [user ](https://app.hubspot.com/contacts/3888472/contact/29473451)🔒  writes: 

> I think if I had the ability to collect my reflection by using Slack Integration, It would save my time on remembering what happened during the sprint. Of course I can use a separate list for that, but I would prefer to keep related things closer together. It would be nice to have such a list of reflections in Parabol because we're using it for our retrospectives.

--
**Enhancement**

**Comment by jordanh** [comment]
I'm glad somebody finally asked for this one. Let's keep queuing up feedback and see if more people want this
