### ISSUE TITLE
Retro groups misaligned

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4864]
Mr Husney shared the image below where the retro groups aren't correctly centre aligned.  

![image](https://user-images.githubusercontent.com/39854876/113894273-75f36380-978d-11eb-904c-7e2170cd77e9.png)

It looks like this is happening in a Safari browser. I haven't been able to reproduce it yet on my iPhone X on Chrome or Safari.

**Comment by jordanh** [comment]
This happened to me! Thank you for capturing @nickoferrall
