### ISSUE TITLE
user from org can't access org he created or start a new meeting

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4866]
A [user](https://app.hubspot.com/contacts/3888472/contact/18003701) 🔒  writes:

for my next retrospective I am no longer able to do or see anything. Any advice what to do?

---

I just used my browser’s history as usual to go to my team’s board: https://action.parabol.co/me
Me, as well as the rest of my team, except of one, experiencing the same issue. Screenshot attached. I am using Chrome on Mac. When switching to incognito mode, I at least get to the see the timeline, but when I click on my team in my Org I get an invitation required prompt.
Wonder if permissions for my account somehow changed…

---

No worries, Drew. And no rush. I am a product person too, so totally understand. Just did our retro differently this time around.
I did reset my password, which now gives me the same experience that I had in incognito mode (can now see my timeline, but don’t have access to the org I created, nor start a new meeting).
Here’s my browser information:
Chrome https://www.whatsmybrowser.org/b/UP13A
Safari: https://www.whatsmybrowser.org/b/MRAAY

----
HubSpot ticket: https://app.hubspot.com/contacts/3888472/ticket/365448228/

**Comment by tiffanyhan** [comment]
The user id associated with the email address in HubSpot no longer exists in our db. There is another user account associated with the email address in our db. Some tasks that were created by this user referenced the no longer existing user account. There were some tasks in the team that also referenced nonexistent user accounts. After backfilling the problematic `Task.createdBy` values on staging, (by setting them to reference an existing user), that error no longer got thrown. However, there were a few other errors that need to be resolved as well.

```
2021-04-20T20:31:13.306945177Z app[web.1]: SEND TO SENTRY [Error: Cannot read property 'isLead' of undefined] undefined
2021-04-20T20:31:13.430377122Z app[web.1]: SEND TO SENTRY [Error: Argument "meetingId" of non-null type "ID!" must not be null.] undefined
2021-04-20T20:31:13.543209179Z app[web.1]: SEND TO SENTRY [Error: Cannot read property 'isLead' of undefined] undefined
2021-04-20T20:31:17.054140098Z app[web.1]: SEND TO SENTRY [Error: Cannot return null for non-nullable field Task.createdByUser.] undefined
2021-04-20T20:31:17.147136391Z app[web.1]: SEND TO SENTRY [Error: Argument "meetingId" of non-null type "ID!" must not be null.] undefined
2021-04-20T20:31:17.258997159Z app[web.1]: SEND TO SENTRY [Error: Cannot return null for non-nullable field Task.createdByUser.] undefined
```

https://sentry.io/organizations/parabol/issues/2212688961/?project=107915&query=is%3Aunresolved
https://sentry.io/organizations/parabol/issues/2194641821/?project=107915&query=is%3Aunresolved

it seems these were all thrown server side, and sentry doesn't provide the call stack from server side events??

---

other weird stuff-- there are duplicate OrgUsers which causes one organization to show up twice in the UI when impersonating them on staging. the existing user account associated with this email address has its property`TeamMember.isNotRemoved = false`.

I saw a few other (set to removed) duplicate OrgUser records which had the property `__manualEdit: 'duplicateUser'` on them.

my guess is there was some manual cleanup on the duplicate which put the entire org in a bad state.

**Comment by tiffanyhan** [comment]
we have ~640 teamMember records whose `id`s don't match the `userId`. the userId part of `id` points to a nonexistent user. we need to clone these records and update the id to point to the existing user.

^^ resolves `.isLead` sentry error

**Comment by tiffanyhan** [comment]
triage all tasks with bad `createdBy` value and set them to a good value 

https://www.notion.so/parabol/Manual-DB-Edits-f3424bbb18b646ae903b679af52e8bbb

**Comment by tiffanyhan** [comment]
the meetingId error was a knock on effect of the Task.createdByUser error. solving the latter cleared up the former.

i can navigate to their teams and start a new meeting now on staging. need to do on prod.

they might need to clear their cache or do incognito in order for the fix to work.

**Comment by tiffanyhan** [comment]
i noticed that `Task.userId` also pointed to bad users. this technically didn't break anything, and the field is nullable. but we should probably try to fix that to point to the good corresponding user

**Comment by mattkrick** [comment]
I did a manual edit of Tasks where `createdBy` had a userId field & the User with that userId did not exist on April 5.
Today, there are new cases of this, so whatever bug is causing it is still at large!

Next steps:
- [ ] track down one of these users on hubspot, sentry, or segment & maybe learn more about the possible actions they took

**Comment by tiffanyhan** [comment]
the user in question is in `DupilcateEmails` table.  we should find the total number of affected users and if it corresponds to no. of emails in the table.

**Comment by tiffanyhan** [comment]
the user who wrote in should be able to access their teams now and create a new meeting. there might be other users experiencing similar issues; we haven't done a generic fix yet.
