### ISSUE TITLE
create a way to quickly delete cards 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4871]
A [user](https://app.hubspot.com/contacts/3888472/contact/16498501) 🔒  writes: 

> I would like the ability to quickly delete cards. I understand there is an archive feature, but sometimes cards don't need to be archived and should just be deleted.

**Comment by jordanh** [comment]
Hint: if you select all the text of a card, delete it, and then click off (i.e. de-focus) the card it will delete!

Will make this a discussion to track frequency of feedback
