### ISSUE TITLE
supporting custom issue types for Jira

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4872]
A [user](https://app.hubspot.com/contacts/3888472/contact/29737751) 🔒 writes: 

> We’re using the Jira integration with Parabol. We create action items from our retros and use the Jira integration to create these action items as issues in Jira. However, there doesn’t seem to be a way to control what issue type is created from Parabol. Currently, it creates a ‘task’ ticket type, but we want it to instead create a ‘Retro Action’ (custom issue type) issue instead. How can we do this?

**Comment by jordanh** [comment]
I imagine we'd have to add some options to the Jira publish menu and enhance the integration if we wanted to support this. Next step would be a design issue.

Promoting this issue to be a discussion to track frequency of feedback from the world
