### ISSUE TITLE
Resolve missed user pg writes

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4876]
## Issue - Bug

After running equal checker for User table-- collect, fix, and backfill known missed user writes in pg here:
- [ ] `setUserTierForUserIds` update to `tier` field

### Acceptance Criteria (optional)
Users can:
   - [ ] run pg rethink equality checker for user in prod and confirm equality btwn all records

- **Estimated effort:** 10 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
Notes:

1. `segmentId` is missing from the user insertion statement. Fix in https://github.com/ParabolInc/parabol/pull/4948
2. `tier` property needs to be resolved by Organization table, which is not in PG yet
3. `lastSeenAt` timestamp was different for a few milliseconds between RethinkDB & PG. Only 16 rows. We could loosen the equality constraint on timestamp properties.

**Comment by tiffanyhan** [comment]
> `tier` property needs to be resolved by Organization table, which is not in PG yet

this can be resolved by doing an in-app join. i don't like it, but from the [last convo we had about](https://parabol.slack.com/archives/C836NA350/p1619208292298400) it it seemed like it was better than alternatives.

> lastSeenAt timestamp was different for a few milliseconds between RethinkDB & PG. Only 16 rows. We could loosen the equality constraint on timestamp properties.

that makes sense! if the millisecond difference can't be resolved, this might be a good use case for [bringing back custom equality resolver option](https://github.com/ParabolInc/parabol/blob/8a7de5486c55db74354f3a63dbc6efd9edc9ca24/packages/server/postgres/utils/checkEqBase.ts) in the equality checker.

**Comment by tianrunhe** [comment]
Updates as of 06/23 for sprint planning purpose: we almost achieved equality for User table. Just one tiny edge case for `lastSeenAt` contention issue that needs addressed.
