### ISSUE TITLE
added agenda item updater is not correctly settings isNavigable (and maybe isNavigableByFacilitator)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4884]
​

AC

- [ ] in a check-in meeting that is in the team agenda phase, when you add a new item, you can click that item to navigate to it without refreshing

​

Estimate: 2 hours

**Comment by jordanh** [comment]
Where this occurs: if you add some new agenda items you can't visit them; also, if you delete the last agenda item while navigated to the penultimate item you can't end the check-in meeting

**Comment by jordanh** [comment]
It seems there are other wonky behaviors with the agenda—delete also is not working without refresh. Promoting to p2

**Comment by BartoszJarocki** [comment]
@jordanh I've fixed a lot of issues related to agenda items in: https://github.com/ParabolInc/parabol/pull/5071 including sorting, deleting, and navigation. So whoever gets this task, it's worth checking if the problem still exists.

**Comment by jordanh** [comment]
Oh wonderful! I'm guessing #5071 will resolve these issues. I'll keep this near the top of the backlog and will close if that PR resolves these issues.

Thank you so much for fixing!

**Comment by BartoszJarocki** [comment]
Happy to help! I've checked locally and seems that all the issues are gone. It'd be worth double-checking once it's deployed.
![CleanShot 2021-06-29 at 17 23 36](https://user-images.githubusercontent.com/1017620/123825173-fa720000-d8fe-11eb-80da-bf4fe194b47d.gif)

**Comment by jordanh** [comment]
This fix went out! Closing. Thank you @BartoszJarocki
