### ISSUE TITLE
Adds clarity between comments and task creation

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#4889]
Continuation of #4812 

<details>
<summary>~Old AC~</summary>
### Acceptance criteria

- [See Figma](https://www.figma.com/file/Ia7SoJcudXUM3nvOYXOldR/Adding-comments-and-tasks?node-id=103%3A0) 
- New "action bar":
  - A new "action bar" is displayed above the comment input field. This bar has a `White #FFFFFF` background and is 32px tall and full width. This new bar increases the overall height of `discuss-input-wrapper`.
  - The intended use of the action bar is to group actions and content objects, such as 'Add task', 'Add poll', or 'Schedule event', etc. For now, we will only support the 'Add task' object.
  - 'Add task' should be a blue text button preceded by the `add` MD icon at 18px. It should be centered both vertically and horizontally. I suggest using `flexbox` for alignment. This text button should inherit the same hover and focus styles we already use on other text buttons and links (`Sky 600 #14649E`).
- The comment area will also receive some updates:
  - The 'Add a task' button is removed from `discuss-input-wrapper` (it now lives in the new action bar described above).
  - The comment input field is now followed by a submit icon button. This new button is 32px by 32px, has fully rounded corners and is right aligned. It has a `Slate 200 #F1F0FA` background color when disabled.
  - The icon button uses the MD icon `north` at 18px. The icon is set to `Slate 500 #A7A3C2`.
  - Once text has been entered in the comment field, the new submit button becomes active and will have a background color of `Sky 500 #329AE5` and the MD icon is set to `White #FFFFFF`.
  - On `hover` and `focus` the button's background is set to `Sky 600 #14649E`. The `north` icon stays on `White #FFFFFF`.
  
### Deferred

We will eventually support other content object besides tasks, and we'd want their input buttons to be grouped together inside the new action bar. Once the number of supported objects grows, we might look at moving the action bar to the bottom of  `discuss-input-wrapper`. [See this Figma file for additional explorations](https://www.figma.com/file/D25gVH1t2alUiOdYNs5Owo/Multiple-content-input-types?node-id=0%3A1).
</details>

AC
- [ ] Discussion thread looks like figma: https://www.figma.com/file/D25gVH1t2alUiOdYNs5Owo/Multiple-content-input-types?node-id=56%3A968
- [ ] Send button uses up arrow (not paper airplane)
- [ ] Send button is gray when there is no text in the input
- [ ] Send button has a tooltop that says "Send" when hovered for 200ms
- [ ] Send button turns blue & arrow turns white when text is in the input (color transitions over 100ms)
- [ ] There is a light horizontal rule below the comment input
- [ ] There is a flat "Add a Task" icon & text button that is blue by default (bonus points if it turns gray when the viewer is editing a task)
- [ ] if the discussion thread only supports comments (see prop `allowedThreadables`) then the horizontal rule & "Add a Task" are hidden

@enriquesanchez feel free to edit if I missed anything!
@ackernaut Enrique & I had a little design jam sesh, let me know if this looks good!

### Estimated effort

- 12 hours.

**Comment by mattkrick** [comment]
I'm doing a lot of work on discussions over at https://github.com/ParabolInc/parabol/pull/5016 
so feel free to branch off of that if you start this before it hits master

**Comment by BartoszJarocki** [comment]
@enriquesanchez I have a few questions about the designs and I'd appreciate your input

1. How does the tooltip look like?
2. Is the task only about the input part or the whole Discuss Thread component?
3. If yes, I see the ‘Reply’ button sometimes is on the top-right corner of the comment, sometimes at the bottom. Is that intentional? 
4. What about things like border-radius? I see it’s using 8px and the application is consistent in using 4px, after changing it in only one place it looks a bit weird, should I leave 4px?

**Comment by enriquesanchez** [comment]
Hey @BartoszJarocki! 

>How does the tooltip look like? Is it a standard tooltip we have, like below?

Yes, the standard tooltip with the "Send comment" label is perfect.

>Is the task only about the input part or the whole Discuss Thread component?

Not sure I'm following this question, but let me see if I can clarify: The new 'Add a task' button performs the exact same action we currently have with the 'Add a task' button:

<img width="373" alt="Screen Shot 2021-06-15 at 1 06 37 p m" src="https://user-images.githubusercontent.com/3276087/122101961-8a318d80-cdda-11eb-8a6d-8308cd38caff.png">

Only difference is that is now placed below the comment field and is styled differently. Does that answer your question?

>If yes, I see the ‘Reply’ button sometimes is on the top-right corner of the comment, sometimes at the bottom. Is that intentional?

These design updates do not consider any changes to the 'Reply' button. Can you clarify where are you seeing this change in position?

>What about things like border-radius? I see it’s using 8px and the application is consistent in using 4px, after changing it in only one place it looks a bit weird, should I leave 4px?

Agree we should be consistent. As far as I can tell, none of the updates consider any rounded elements. Where are you seeing the 8px radius? 

>Do we want any on hover states for the send comment button and add task button? Maybe change a font color slightly to add a task button? And change the background color for send comment? 💡

Yes, for the hover states we darken the color we use for the background in the 'Send comment' button, and darken the color of the text for the new 'Add a task' button. We already have a hover color defined that we use in some elements, like the 'Invite to team' button, it's a darker shade of the default blue:

![2021-06-15 1-12-27 p m 2021-06-15 1_12_45 p m](https://user-images.githubusercontent.com/3276087/122102818-78041f00-cddb-11eb-8a05-cb580b91f057.gif)

Here's a screenshot for reference with all the resting, active and hover states:

<img width="1211" alt="Screen Shot 2021-06-15 at 1 22 08 p m" src="https://user-images.githubusercontent.com/3276087/122104001-d41b7300-cddc-11eb-8437-9064cb66cc1e.png">

---

Let me know if something is still not clear or if I can help with anything else.

**Comment by BartoszJarocki** [comment]
@enriquesanchez thank you, it's all clear now! 

Just to clarify, when I asked about border radiuses this is what I had in mind:
![screenshot](https://user-images.githubusercontent.com/1017620/122105719-65103f80-ce19-11eb-8b99-df3351e3bf58.png)
The container on the left has a 4px border radius and the design on the right 8px. Same with the `Reply` button. If you compare these two you'll notice that the design differs from what we currently have.

Right now I know that the task is only about the input part so it's all good 👍 
I'm gonna add hover states, think about graying out the `Add task` button when a new task is being created and it should be good to go.

**Comment by enriquesanchez** [comment]
>Just to clarify, when I asked about border radiuses this is what I had in mind:

@BartoszJarocki  Ah. got it. Yeah, that's not part of this design update. Apologies for the confusion 😃

>I'm gonna add hover states, think about graying out the Add task button when a new task is being created and it should be good to go.

Awesome! Let me know if anything else comes up or if you need help with a review 👍
