### ISSUE TITLE
Typo in `res.writeHeader`

### ISSUE THREAD

**Issue by jbowa** [ParabolInc/parabol#4895]
In `createSSR` should the response header be 'content-type' instead of 'cotent-type'? 

`res.writeHeader('cotent-type', 'text/html; charset=utf-8')`

**Comment by tianrunhe** [comment]
Hey @jbowa , that's a greaaaat find!! I can definitely fix it quick but to finder's pride, we will be thrilled to accept a pull request from you!

**Comment by jbowa** [comment]
Thank you @tianrunhe !
