### ISSUE TITLE
Upgrade to Node v16

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4903]
as a policy, we like to keep up with the latest Node LTS version.
They just released v16, which uses V8 v9.
It's nice using the latest version because that means developers can use the latest language features (if it's valid JS, we should support it!).

Not super pressing, I'd be OK waiting a few weeks in case there is a performance regression.

AC
- [ ] Node uses v16
- [ ] abort-controller package is removed & the native AbortController is used
Estimate: 4 hours

**Comment by jordanh** [comment]
We already done did it!
