### ISSUE TITLE
Adds ability to randomize icebreaker order

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#4910]
This is an implementation issue following the discussion on https://github.com/ParabolInc/parabol/discussions/4772. Also related to https://github.com/ParabolInc/parabol/issues/4804.

### Background
There is [tension around the order of the icebreaker turns](https://github.com/ParabolInc/parabol/discussions/4772#discussion-3276505). The person facilitating the meeting always goes first, and then as members join they are added to the cue.

>As a team lead, I'm usually the one starting the meeting, and I don't want to always answer the icebreaker first. I'd like the option for that lineup to be more random, maybe by hitting a 'randomize!' button or maybe something else.

This proposal is a quick and relatively small solution that introduces a "randomize" button next to the Icebreaker menu item:

<img width="953" alt="Screen_Shot_2021-04-22_at_3 38 05_p m" src="https://user-images.githubusercontent.com/3276087/116122143-033c2080-a687-11eb-85ec-8a3a56ee8c5b.png">

### Acceptance criteria

For the button:

- A new icon `button` is added to the right of the 'Icebreaker' menu item.
- The new icon to use is `refresh` at `18px` from the Material Design icon font.
- The randomize icon button needs an `aria-label` attribute with a value of `Randomize order`.
- The randomize icon button should display a tooltip when hovered or focused that reads `Randomize order`.

For the new functionality:

- When activated, the order of team members should be randomized.
- The randomize action can be activated at any point and as many times as long as there are still members waiting their turn.
- If there are meeting members who have already taken their turn, then they should be left out of the randomize action and stay on top of the list.

<img width="1078" alt="https---s3-us-west-2 amazonaws com-secure notion-static com-aa5e83df-7614-4758-ac1e-c765f1742eaa-Screen_Shot_2021-04-22_at_3 53 21_p m -1" src="https://user-images.githubusercontent.com/3276087/116123557-c07b4800-a688-11eb-82cb-28f984b34596.png">

[See the Figma file for more detail](https://www.figma.com/file/B386ymVFhvopSVKMbrrC99hK/Icebreaker?node-id=172%3A1).

### Estimated effort:
12  hrs

**Comment by mattkrick** [comment]
> If there are meeting members who have already taken their turn, then they should be left out of the randomize action and stay on top of the list.

How does this work for async meetings? For example, we start retro meetings 2 weeks before we meet together. In this scenario, by the time we get into the meeting, the icebreaker phase has already been completed.

If randomizing the order won't do anything, should we hide the button? gray it out?

In our check-in meeting, the `Updates` phase follows the same order as the `icebreaker` stage. Should we update that order to make sure it matches the icebreaker? Or should the 2 diverge?

**Comment by enriquesanchez** [comment]
Thanks for the feedback @mattkrick 🙌

>How does this work for async meetings? For example, we start retro meetings 2 weeks before we meet together. In this scenario, by the time we get into the meeting, the icebreaker phase has already been completed.

As far as I know, the icebreaker is currently the only phase that cannot be completed async and independent of third-party tools, such as Zoom. Am I correct? 

<img width="381" alt="https---s3-us-west-2 amazonaws com-secure notion-static com-939c3357-e604-4d63-a7c2-a3b0db1fffc9-Screen_Shot_2021-04-22_at_4 09 01_p m" src="https://user-images.githubusercontent.com/3276087/116162156-d43fa200-a6ba-11eb-8549-bf1be01c3740.png">

We ask meeting attendees to verbally share their responses with the team. So in order for the icebreaker to work, as it currently stands, everyone has to be present at the same time.

>If randomizing the order won't do anything, should we hide the button? gray it out?

I lean towards graying it out, so facilitators learn to expect that button there.  I also think that the randomize button should **only be available to facilitators**, otherwise it can turn into a random fest if more folks start activating it.

>In our check-in meeting, the Updates phase follows the same order as the icebreaker stage. Should we update that order to make sure it matches the icebreaker? Or should the 2 diverge?

Ah, I had not thought about this, thank you for bringing it up 🙏. I think it'll be a little unexpected if I randomized the order in the icebreaker and it also randomized the order elsewhere, but I can see how a facilitator might also not want to go first in the Updates phase 🤔. 

I think I need to think a little more about this one, because a part of me does not feel right with adding more randomize buttons in other places. It's a short-term solution while we explore a more mature icebreaker phase. Maybe this functionality should live in the facilitator's meeting control bar? 🤔

**Comment by tianrunhe** [comment]
Believe or not, "random/shuffle" is a hard computer science problem! We might not want a true random algorithm here: for example, when there are only 2 members left in the rotation, 50% of the chance you will end up with the same rotation even after a "shuffle". User might get confused whether the feature is working or not.

We might just implement a pseudo-random algo that guarantee the end result will not look like the initial position.

**Comment by jordanh** [comment]
I was looking to prioritize this, and it looks like we don't yet have AC we can implement. Resolving future intent around a potential async icebreaker is a good idea...

Adding `discussion` label and removing from backlog (for now)
