### ISSUE TITLE
Improves context and layout of Slack notifications

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#4911]
This is an implementation issue addressing #3764.

### Background

>Right now, our Slack notifications are pretty plain and not very attractive [...]

Instead, users should:

> - Understand what organization, team and meeting they're being invited to from a Slack notification
> - Join the Slack meeting with one click
> - See Slack notifications for meetings as distinct from other Slack messages

### Acceptance criteria

The goal is to make our notifications more informative, more engaging, and overall friendlier. We also want to display a different format depending on the meeting stage (start, phase initiated, end).

The new notifications should follow the format from [the Slack API](https://api.slack.com/):

- Start with a short message stating one of the following:
  - `Meeting started 👋`
  - `Meeting completed 🎉`
  - `[PHASE NAME] has begun ⏳`
 - Follow with the meeting info: `Team` name and `Meeting` name

If the **meeting is starting**:
- display the shortened `link` for the meeting 
- display a CTA button with the label `Join meeting` in Slack's default green (`#007a5a`)

![](https://user-images.githubusercontent.com/3276087/114430839-77a19a80-9b84-11eb-92b4-c8fa4062f597.png)

If the **meeting has ended**:
- display the summary of the meeting (e.g. `It lasted 54 minutes and generated 13 tasks, 9 agenda items
and 7 comments.`)
- Follow with two actions: `See discussion` and `Review summary`. These two actions should point to the same places as the current meeting summary we show in the users' timeline in Parabol.

![](https://user-images.githubusercontent.com/3276087/114430862-7c664e80-9b84-11eb-961a-151364cea34f.png)

If a **meeting phase has begun**:
- display the phase deadline (e.g. `You have until April 24 at 12:50 PM to complete it.`)
- provide the shortened link for the meeting
- display a green CTA with the label `Open meeting`
- followed by the secondary action `Set reminder`
- `Set reminder` should make use of Slack's own `/remind` feature

![](https://user-images.githubusercontent.com/3276087/114430915-88521080-9b84-11eb-8b66-a851eec67b88.png)

![](https://user-images.githubusercontent.com/3276087/114431513-2f36ac80-9b85-11eb-870d-b4d375674096.png)

### Estimated effort:
12 hrs

**Comment by nickoferrall** [comment]
The [time picker](https://api.slack.com/reference/block-kit/block-elements#timepicker) element is currently in [beta](https://api.slack.com/developer-beta) which unfortunately means that it can't be used in the live app directory.

I suggest that we omit the `Set reminder` button (which uses the time picker) until it comes out of beta. I can create a new issue for this

**Comment by enriquesanchez** [comment]
@nickoferrall Oh, that's unfortunate. But yes, we can revisit once it's out of beta. It's odd, given that the reminder feature has been in Slack for ages 🤷‍♂️

**Comment by nickoferrall** [comment]
@enriquesanchez Slack works in mysterious ways! I've created the issue 👍
