### ISSUE TITLE
Jira server requests

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#4915]
## Issue - Enhancement

We've gotten several requests for a Jira server integration. This issue is to keep track of these requests.

### Acceptance Criteria (optional)
Users can: import Jira issues to Sprint Poker, export dimensions to Jira fields, and create Jira issues from task cards.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/33079101) 🔒  writes:

> Hi, how can you integrate Jira tasks from a company Jira server? We are a big company and running our own customized Jira, many company's do that so how can we integrate our Jira tasks to Parabol?

> Don't want to rewrite all tasks in Parabol without integration. If you would have that feature I think many teams within big companys might wanna buy into Pro plan

> Ok, well is same for us. But can't pitch the tool without testing it fully, so a catch 22 there for me.

**Comment by gcrickman** [comment]
Two other requests for this feature are on #4379

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/20923801) 🔒 writes:

> Hi, I have a question. Does the Jira integration also work with the Jira Server version instead of the cloud version? Thanks in advance!

**Comment by gcrickman** [comment]
Two users from this [account](https://app.hubspot.com/contacts/3888472/company/3254314640) 🔒  mentioned:

> Would be nice to have integration with Jira server, were super excited to use planning poker but we couldn’t use it with Jira server.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/21068751) 🔒  requested:

> Some way of taking the tasks out of Parabol, we are using Jira server but it's managed by a 3rd party.

**Comment by jordanh** [comment]
We had +2 requests for this during this [User Feedback Retro](https://action.parabol.co/new-summary/2AvrebtSAE)

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/39724101) 🔒  writes:

> I see that your platform has the ability to integrate with Jira Cloud.
> 
> I wanted to know if there is support and or development resources that would allow us to integrate with our on-premise Jira instance that we have configured locally in our office? Would we have to setup Parabol on our own instance on premise to make it work or can we integrate the cloud version of Parabol with our on-premise version of Jira?
>

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/49467901) 🔒  writes:

> Does parabol integrate with Jira Server or Jira Cloud only?

**Comment by enriquesanchez** [comment]
A Jira Server Integration was the most requested integration from the [Parabol Customer Feedback Survey](https://parabol.slack.com/archives/C08FL5UE7/p1633422567280700) 🔒.

**Comment by gcrickman** [comment]
This [account](https://app.hubspot.com/contacts/3888472/company/3220410711) 🔒  would also like a Jira server integration

**Comment by WWP-Apalmer** [comment]
Hi - I just signed up with Parabol because it is the only Scrum Poker tool that I have found that allows for voting on multiple aspects of one issue. Our Jira is on-prem and we are about 6 mos to a year away from migrating to Jira cloud - I would love to know what the other options are for uploading issues to Parabol. I see there is also a GitHub integration - I have uploaded my issues here to GitHub as a csv and GitHub can read the file - however - I dont know how to extract them from the file over to issues - and I dont know how to query the file from Parabol - is there any help you can give me on this? We really need this product - but we have a large backlog and adding them one by one into Parabol - while I can do it - seems like an inefficient way of doing this - additionally - the individual add on Parabol doesn't allow me to add all the info I need to have displayed on each issue - please help - thanks!

**Comment by drewhousman1010** [comment]
Hey @WWP-Apalmer here's the response I got from our dev team. I hope we can figure out how to make this work for you! 

> We're about halfway done with the Jira Server integration. Would you like to sign up to be a beta tester for it? If you're curious, you can track our progress here: [https://github.com/ParabolInc/parabol/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated[…]e%3A%22%F0%9F%A5%87+Poker%3A+Initial+Jira+Server+Integration%22](https://github.com/ParabolInc/parabol/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A%22%F0%9F%A5%87+Poker%3A+Initial+Jira+Server+Integration%22)
> 
> If you already imported the issues into a GitHub repository, you can click the GitHub tab in the Parabol Poker Scoping phase, authenticate, and then in the issue list click the filter button, select the repository where you imported the issues & you'll see them all there

**Comment by WWP-Apalmer** [comment]
> Hey @WWP-Apalmer here's the response I got from our dev team. I hope we can figure out how to make this work for you!
> 
> > We're about halfway done with the Jira Server integration. Would you like to sign up to be a beta tester for it? If you're curious, you can track our progress here: [https://github.com/ParabolInc/parabol/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated[…]e%3A%22%F0%9F%A5%87+Poker%3A+Initial+Jira+Server+Integration%22](https://github.com/ParabolInc/parabol/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A%22%F0%9F%A5%87+Poker%3A+Initial+Jira+Server+Integration%22)
> > If you already imported the issues into a GitHub repository, you can click the GitHub tab in the Parabol Poker Scoping phase, authenticate, and then in the issue list click the filter button, select the repository where you imported the issues & you'll see them all there

@drewhousman1010 - I did load them into GitHub - one by one - but at least here I was able to add everything I need to see for each issue - not just the high-level name - and I did integrate GitHub and am able to see them in Parabol - so we will continue to use GitHub until Jira Server integration is completed. I definitely would like to be a beta tester, so let me know how we can participate in that. Thanks so much!

**Comment by drewhousman1010** [comment]
@WWP-Apalmer I'm glad you have a workaround for the time being. I will make a note to reach out to you about beta testing, thanks for volunteering!

**Comment by WWP-Apalmer** [comment]
**Strategic Fit: 3**
  [See the discussion](https://action.parabol.co/meet/bP1HwvJR5K/estimate/2) in Sprint Poker #​​4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**Impact: 5**
  [See the discussion](https://action.parabol.co/meet/bP1HwvJR5K/estimate/3) in Sprint Poker #​​4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**Ease: 3**
  [See the discussion](https://action.parabol.co/meet/bP1HwvJR5K/estimate/4) in Sprint Poker #​​4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/bP1HwvJR5K/estimate/5) in Sprint Poker #​​4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**X-Factor: 3**
  [See the discussion](https://action.parabol.co/meet/bP1HwvJR5K/estimate/6) in Sprint Poker #​​4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**Strategic Fit: 1**
  [See the discussion](https://action.parabol.co/meet/bP2sqe2IQE/estimate/2) in Sprint Poker #​​5

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**Impact: 5**
  [See the discussion](https://action.parabol.co/meet/bP2sqe2IQE/estimate/3) in Sprint Poker #​​5

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**Ease: 2**
  [See the discussion](https://action.parabol.co/meet/bP2sqe2IQE/estimate/4) in Sprint Poker #​​5

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**Urgency: 2**
  [See the discussion](https://action.parabol.co/meet/bP2sqe2IQE/estimate/5) in Sprint Poker #​​5

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by WWP-Apalmer** [comment]
**X-Factor: 2**
  [See the discussion](https://action.parabol.co/meet/bP2sqe2IQE/estimate/6) in Sprint Poker #​​5

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/12216501?interaction=email) 🔒 asks:

> I see you integrate with Jira Cloud. Will you be making a way to connect with Jira server any time?

**Comment by jordanh** [comment]
Now that we have Jira Server support, I am going to close this discussion!
