### ISSUE TITLE
Cannot destructure property 'userId' of 'm' as it is undefined

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4921]
Issue affecting 13 users in the past 14 days. First seen in release 6.7.0

https://sentry.io/organizations/parabol/issues/2340366749/?referrer=github_plugin

```
TypeError: Cannot destructure property 'userId' of 'm' as it is undefined.
  at c (./packages/client/components/NewMeetingCheckIn.tsx:53:10)
  at Set.forEach (<anonymous>)
...
(30 additional frame(s) were not displayed)
```

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-5ZT](https://sentry.io/organizations/parabol/issues/2402579942/?referrer=github_plugin)

**Comment by Dschoordsch** [comment]
Affected 9 users last 11 days

Sentry issue: [ACTION-PRODUCTION-9P6](https://sentry.io/organizations/parabol/issues/2654507844/?referrer=github_plugin)

**Comment by jordanh** [comment]
It looks like this issue no longer happens

**Comment by JimmyLv** [comment]
<img width="331" alt="Google Chrome-TypeError Cannot destructure property 'userId' of 'm' as it is undefined  - parabol - action-production-003588-20220715" src="https://user-images.githubusercontent.com/4997466/179189554-07ae81ac-5764-40fa-9d23-bb842de4ed75.png">

This problem looks to be happening again in https://sentry.io/organizations/parabol/issues/2654507844/?project=107196&query=level%3Afatal+timesSeen%3A%3E5&statsPeriod=14d

**Comment by jordanh** [comment]
This bug appears no longer to occur. Closing and presumed fixed
