### ISSUE TITLE
user can't find meeting 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4926]
A [user](https://app.hubspot.com/contacts/3888472/contact/19021051) 🔒 writes: 

> My colleague and I were preparing for our Retro tomorrow. I started our meeting #24 a couple of weeks ago after finishing #23. I had added several cards and saw that colleagues had added others as well. I used the link in our Slack to get to meeting #24 and saw the screen below. So I logged in to access meeting #24 in another way and found meeting #23 was still open. I also couldn't find meeting #24 in active meetings.

Could you please help? I'm using Google Chrome and am on the most recent version. 

Hubspot ticket: https://app.hubspot.com/contacts/3888472/ticket/395306766/

Slack discussion here: https://parabol.slack.com/archives/C4JAUUZ9P/p1619734116211700

**Comment by jordanh** [comment]
It was found that the user started the meeting from our staging server. This caused us to reopen #2755
