### ISSUE TITLE
meetings have bad templateRefId references

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#4929]
## Issue - Bug

Meetings have bad `templateRefId` references. Need to find what the impact is on the product, when and why it's happening.

Query to get distinct template ref ids in rethink (returns 312+ values):

```
  r.db('actionProduction')
    .table('NewMeeting')
  	.hasFields('templateRefId')
  	.getField('templateRefId')
  	.distinct()
  	.coerceTo('array')
```

Query to get all template ref rows in pg (returns 42+ records):
```
select "id" from "TemplateRef";
```

Example meeting with bad templateRefId reference:

```
"id": "2IBU1yq1Gw",
"templateRefId": "eYu2YXFlgBBQTu6IPqWRAQ==" ,
```

### Acceptance Criteria (optional)
- [ ] assess how this bug affects the user
- [ ] ensure all future meetings that have `templateRefId` value reference an actual row in pg
- [ ] backfill existing bad references

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@tiffanyhan could you suggest a p value for this one?

Values are: https://www.notion.so/parabol/Support-Workflow-d07d2863e5074e79b4beaca769a882b4

**Comment by jordanh** [comment]
Oh! And could you please also add an estimated effort (just a cap on how many hours we'd want to spend on this during a sprint)

**Comment by tianrunhe** [comment]
Hey @tiffanyhan, I saw the same number of TemplateRef rows between Rethink and PG 🤔:

<img width="943" alt="Screen Shot 2021-05-04 at 3 28 11 PM" src="https://user-images.githubusercontent.com/1879975/116973055-8d6f2f00-acee-11eb-9dbd-57e60349f162.png">


<img width="491" alt="Screen Shot 2021-05-04 at 3 36 19 PM" src="https://user-images.githubusercontent.com/1879975/116973024-7cbeb900-acee-11eb-8675-7dab45407ca9.png">

The templateRefId you mentioned was also valid:
<img width="592" alt="Screen Shot 2021-05-04 at 3 55 44 PM" src="https://user-images.githubusercontent.com/1879975/116974784-30c14380-acf1-11eb-99de-8e49afda6522.png">

**Comment by tianrunhe** [comment]
@tiffanyhan Aha! Did you log into our staging pg cluster? I did see 42 rows in TemplateRef for that DB.

42, the "Answer to the Ultimate Question of Life, the Universe, and Everything" 😂

**Comment by tiffanyhan** [comment]
d'oh! i assumed there was some hook that restored prod pg to staging whenever we deployed, but i guess that's not the case yet. *facepalm*

this was keeping me up at night, now i'm so relieved T.T thank you @tianrunhe
