### ISSUE TITLE
Viewing story point difficulties assigned in Jira in Parabol 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4944]
A [user](https://app.hubspot.com/contacts/3888472/contact/9798251) 🔒  asked:

> Once a story has been assigned a story point difficulty in Jira, can you then see that story point in Parabol?

[Slack discussion](https://parabol.slack.com/archives/C4JAUUZ9P/p1620310806232400)

**Comment by jordanh** [comment]
I could have sworn we had a discussion or design issue that was related to displaying other issue metadata such as GitHub labels, but we don't!

Marking this as discussion to spool up more feedback. Adding this thought: I'd like to solve for the general case of displaying and editing issue metadata

**Comment by jordanh** [comment]
Iceboxing for now
