### ISSUE TITLE
session-only impersonation

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4947]
Impersonation could use a better UX.

AC
- [x] can visit `/admin/impersonate/<EMAIL>` to impersonate an email (no userId needed)
- [x] impersonating a user only lasts for the browser session. once the browser is closed, you're logged out. (technically, when the browser is opened, it checks to see if the token is impersonated. if so, it removes it & you have to sign-in again.)
- [x] when impersonating user X, it doesn't tell other team members that user X is online
 
@drewhousman1010 @gcrickman @ackernaut for your consideration

Estimate: 4 hours

**Comment by mattkrick** [comment]
removing BP tag as 4 hours just aint enough time

**Comment by drewhousman1010** [comment]
@mattkrick I'm somehow just seeing this! I can't wait to see this get implemented. Our process for impersonating as it currently stands feels like a stressful, high-wire act and this will make it so much nicer.

**Comment by mattkrick** [comment]
@drewhousman1010 should land next week. How-to video here: https://www.loom.com/share/122527fe02174e63ad6f4c6e81657ff5
