### ISSUE TITLE
As a Facilitator of a Retrospective, I want the ability to see when participants are ready to move to the next phase so that I don't have to keep asking if they are Ready

### ISSUE THREAD

**Issue by hayyhink** [ParabolInc/parabol#4951]
## Issue - Enhancement

During a Retrospective today, I kept having to ask the participants if they were ready to move to the next phase. According to them, they click a Ready button when they are Ready. I as a facilitator have no way of seeing when they are. If would be super helpful if I can get an indication or notification when everyone is ready to move on.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/16427351) 🔒  says:

> The ready button is really confusing, people don't know if they have hit ready or not. We just want to see the ready button get fixed as soon as possible.

**Comment by mattkrick** [comment]
@enriquesanchez if you're on the hunt for some a11y stuff, mind double checking the contrast between our gray & green on the ready checkmark? want to be sure that they are different enough for folks to see that it turns green when they click it

**Comment by enriquesanchez** [comment]
@mattkrick The green on our color palette does not pass WCAG color contrast guidelines. Against a white background, we get a 2.29:1 ratio, when at least 3:1 is needed for visual elements (icons, images, graphics, etc.).

That said, I get a feeling that the root cause of the issue here is not the color contrast of the Ready icon, but may be more about the visibility of the progress circle around the check.

>I as a facilitator have no way of seeing when they are. If would be super helpful if I can get an indication or notification when everyone is ready to move on.

It's such a small surface that is easy to miss. Maybe in addition to the progress circle in the meeting bottom bar, we can show a notification on top as well? This is a super quick mockup, and I'm sure we can improve the copy, but something like this:

<img width="1288" alt="Screen Shot 2021-05-13 at 11 40 45 a m" src="https://user-images.githubusercontent.com/3276087/118157441-2e8d7200-b3e0-11eb-8ca1-fb5ecbb5d3f6.png">

**Comment by enriquesanchez** [comment]
Or if we prefer to keep things related to meeting facilitation contained to the bottom bar, maybe we can draw more attention to the Ready button:

<img width="463" alt="Screen Shot 2021-05-13 at 12 02 09 p m" src="https://user-images.githubusercontent.com/3276087/118160013-5b8f5400-b3e3-11eb-9ad6-371149c36304.png">

**Comment by mattkrick** [comment]
2 good options! it's a tight rope to walk between a UI that quietly gets out of the way & 1 that is in your face making sure you do what it wants. let's gather some more user feedback to see how many other folks face this problem.

**Comment by jordanh** [comment]
Scrubbed. Marking discussion until this issue resolves down to defined acceptance criteria

**Comment by ackernaut** [comment]
@enriquesanchez and I will be looking at these meeting participation concerns soon. @mattkrick suggests needing more signal (i.e. more folks writing in)

**Comment by jordanh** [comment]
Related to #5166

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/42641801) 🔒 writes:

> The only thing I've consistently found is that people forget to click the "ready" button. It might benefit from being more prominent, but I also think it's a non-issue.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/13408051) 🔒  writes:
> One small suggestion, regarding the next button on the UI, sometimes it was confusing to know if we are waiting for the input of someone or our input to move forward to the next step.
I would suggest adding a clear text/sign that all the other participants are done so that we jump with confidence to the next step.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/45262751) 🔒  writes:

> Subject: Feedback: Improve contrast of "Ready" button action state
> Message: Right now I feel like it's tricky to tell if I have clicked the "Ready" button or not. The difference between the 2 states is very small. Perhaps when the "Ready" button is active it's background area could be highlighted green.

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/20229501) 🔒  says:

> I would like a better way of knowing who has and hasn't hit "next" to make it easier for me to know when to move on to the next phase

**Comment by jordanh** [comment]
See other related issues which will improve this feature. Removing this from our backlog to reduce duplicity.
