### ISSUE TITLE
As a DevSecOps engineer, I want to create a Ironbank hardening manifest for security pipeline

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#4960]
As a DevSecOps engineer, I want to create a Ironbank hardening manifest for security pipeline

AC:

Manifest should include

- [x] All security artifacts to be scanned
- [x] Meet the Ironbank security pipeline manifest guidelines
- [x] Contain all meta data about our container
- [x] Pass the hardening manifest check within Ironbank

**Comment by jordanh** [comment]
May we also mark this as done now?
