### ISSUE TITLE
NS_ERROR_FAILURE: No error message (Reflection issue during Group phase in Firefox)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4968]
https://sentry.io/organizations/parabol/issues/2380241664/?referrer=github_plugin

This has affected 8 users in the last 10 days (as of Fri May 14). So far it’s only happening in Firefox. It’s happening in the Retro Group phase.

```
NS_ERROR_FAILURE: No error message
  at onChange (./packages/client/components/ReflectionEditorWrapper.tsx:139:5)
  at apply (./packages/client/components/ReflectionEditorWrapper.tsx:86:72)
...
(18 additional frame(s) were not displayed)
```

### Acceptance criteria
- Triage and fix, or open a new issue with root cause to be fixed

### Estimated effort
- 4 hours

**Comment by jordanh** [comment]
No more instances in Sentry, closing
