### ISSUE TITLE
Add reminder to Slack timer notifications

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4984]
At the time of writing this issue (May 2021), Slack's [time picker](https://api.slack.com/reference/block-kit/block-elements#timepicker) element is in beta which means it can't be submitted to the app directory.

When the element makes its way out of beta, we should add a "Set reminder" button to the Slack notifications triggered when a user sets a timer (as outlined in issue #4911). 

![image](https://user-images.githubusercontent.com/39854876/118896732-83dcee00-b8ce-11eb-9283-bb434c344b34.png)

![image](https://user-images.githubusercontent.com/39854876/118896738-86d7de80-b8ce-11eb-89fd-5d77fedca14b.png)

Note: this may require adding an additional [reminder](https://api.slack.com/methods/reminders.add) scope which means resubmitting the Slack app.

### AC:

- [ ] Add "Set reminder" as a secondary action button 
- [ ] "Set reminder" should make use of Slack's own /remind feature
- [ ] The user receives a reminder notification at the time & date they choose in the reminder pop-up

### Estimated
- 12 hours

**Comment by jordanh** [comment]
@nickoferrall this is still a real good idea; feel free to re-open and add to a sprint poker meeting if you'd like to see us do it
