### ISSUE TITLE
Data in Companies with multiple domains seems funky 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4985]
## Issue - Bug

We score and prioritize Deals based in part on the number of Active Users associated with a company. Sometimes, that data isn't correct. 

As an example, [this company](https://app.hubspot.com/contacts/3888472/company/2395210447)🔒  shows Active Users bouncing between 2 and 50 on one day: 
![Screen Shot 2021-05-20 at 12 08 53 PM](https://user-images.githubusercontent.com/11621016/119052407-2b6b2680-b98a-11eb-82d9-1180393bfc20.png)

To see the above screenshot, go to the Company then look at the Active Users property, and click `Property History`. 

I'm not sure why this is happening, but one hypothesis is that it's related to having multiple domains. The example company has the email domains `@company.com` and `@company.de`. In Hubspot, a Company is a collection of users with the same email domain. In cases when we see a set of users with a .com domain and another with a .de domain, and we know these operate as one company, we'll merge those companies in Hubspot. Hubspot also provides some intelligence to do so. 

My hypothesis is that, in this case, two Companies - one with the .de domain, the other with the .com domain - were merged, and now when data is updated, it's sometimes reflecting users with .de and sometimes users with .com. 

In cases like this, the ideal state would be that a merged/combined record like this reflects users with either domain. If that's not possible, then it would be helpful to see the larger number of Active Users. 

### Acceptance Criteria (optional)
Parabol team can rely on Active Users field in Hubspot to accurately determine the extent of usage in Companies with multiple domains. 

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
that's weird! to test the hypothesis we could call
```
mutation {
  setOrganizationDomain(orgId:"foo", domain:"foo.com") 
}
```

on those domains in question where the .com are only winning by a narrow margin. once an orgnaization is pinned to a domain it won't change as members join/leave

**Comment by tianrunhe** [comment]
Aviva's hypothesis is correct:

<img width="742" alt="Screen Shot 2021-05-21 at 3 42 47 PM" src="https://user-images.githubusercontent.com/1879975/119101261-5e292380-ba4b-11eb-858a-54f6772e1af3.png">

<img width="655" alt="Screen Shot 2021-05-21 at 3 42 30 PM" src="https://user-images.githubusercontent.com/1879975/119101292-65e8c800-ba4b-11eb-98b5-24dbb5eb1a93.png">

We can merge those users in tui.de to tui.com for this particular case for sure but I feel like a long term solution is to update the company in HubSpot by its id over the domain. WDYT @mattkrick ?

**Comment by tianrunhe** [comment]
Oh NVM I saw we did use companyId to update the record in HubSpot.

**Comment by mattkrick** [comment]
@tianrunhe it'd be cool if we could grab the domain from the hubspot company & set it in our own app. that'd be a lot nicer than our very naive approach.
