### ISSUE TITLE
selecting "next 50 issues" in poker updates all tickets to 0 story points 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4992]
A [user](https://app.hubspot.com/contacts/3888472/contact/8748451) 🔒 writes:

>  selecting a Jira issue had the effect of immediately updating the selected Jira ticket to have 0 Story Points. I accidentally clicked “Select next 50 issues” and, even though I de-selected them right away, Parabol updated all of the tickets to have 0 story points with MY name attributed to it in Jira … quite a serious issue!

Hubspot ticket: https://app.hubspot.com/contacts/3888472/ticket/425678212

**Comment by jordanh** [comment]
Hmm.  I presume that this is no longer an issue because it is so old. Closing for now.

@drewhousman1010 could you reach back out to the user and find out if this is still and issue? If so, I'll have some one look into it more deeply

**Comment by drewhousman1010** [comment]
@jordanh I reached out to this user and I'll report back if it's still happening.
