### ISSUE TITLE
Adds a Manage Team side sheet to Team view

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5002]
Solving #4494 

This updates the avatar group for team members and membership management on the team dashboard.

**Note**: we can probably use the updated avatar group component as long as it’s upgraded to handle new details and behaviors.

See [background and design notes](https://www.notion.so/parabol/Avatar-group-improvements-a841c58603e5474782c02a92db3a0ee7) in Notion 🔒 

#### Team view top bar
- [See Figma](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=1%3A1490)
- [ ] The right side of the team dashboard top bar has Manage Team, Invite, and Agenda components
  - The Manage Team control shows member avatars and toggles the Manage Team side sheet
  - The Invite control toggles the Invite dialog
  - The Agenda control toggles the Agenda side sheet
- [ ] The avatars overlap. The avatar is 24px plus 2px border that matches the background to create the visual separation. This means that the total box is 24+2+2 = 28. It is not a 24 box with 2 + 2 pixel of border on the inside, this would make the actual avatar visual footprint be 20 which is not desired per design. The overlap is 6 pixels (4px of avatar + 2px border)
- [ ] Offline folks are now at 35% opacity. Remove the circular badge as this is an old design pattern. We need a solid background behind each avatar that matches the team dash (`SLATE_200`) so that they overlapping avatars don’t show opacity over each other
- [ ] There’s an overflow badge when applicable
- [ ] Responsive layout and overflow ([See Figma](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=1%3A1960)):
  - [ ] At smaller breakpoints the manage team, invite, and avatar controls can wrap to a second row
  - [ ] We can limit the width of the avatar group to cause overflow based on how much space is available in the viewport
  - [ ] At any breakpoint, set a max width so that 10 avatars show or 9 avatars + overflow badge
- [ ] Hovering an avatar [shows the name](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=2%3A194); in the future we could show [the last time they connected](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=2%3A133) on a second line
- [ ] Tapping an avatar opens a Manage Team side sheet and scrolls to that user if they are scrolled out of view
- [ ] Tapping the overflow badge opens the menu and scrolls to the first user in the overflow state
- [ ] [Layout, type, color etc.](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=1%3A1514) — the top bar is 72px with 40px tall components and 16px vertical gutter above and below. Icons use the 24px MD variants. The links and labels are 12px font size, 600 weight. Labels use `Slate_700`. Blue components are `Sky_500`

#### Manage team side sheet
- [See Figma](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=1%3A2010)
- [ ] Each item shows a team member with a 24px avatar and their name
- [ ] The team lead has a secondary meta line ‘Team Lead’ (option: use a badge)
- [ ] If the user can take action on that item there’s a `more_vert` menu toggle
- [ ] Team leads sees a menu for all other members with the options: 1) ‘Promote NAME to Team Lead’ 2) ‘Remove NAME from Team’
- [ ] A team member sees a menu toggle on their user menu item with the option to ‘Leave Team’
- [ ] Only 1 side sheet can be open at a time, either the Agenda or the Manage Team sheet
- [ ] When a side sheet is open the toggles are still visible. They can be used to close and or swap out the content of the side sheet
- [ ] The side sheet can be closed with an X control in the upper right.
- [ ] Mobile uses [a modal side sheet](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=1%3A2259) that appears over the content with a scrim. At the `SIDEBAR_LEFT` breakpoint, it uses a standard side sheet that pushes in on the right side of the content. For more see [the MD docs for side sheets](https://material.io/components/sheets-side#usage)
- [ ] Note: when a side sheet pushes into the layout (i.e. not mobile, where it overlaps with a scrim) it should push the control bars and floating action buttons, too. The Add Meeting button should be in the bottom right of the main view when any side sheet is open, not over the side sheet ([see example](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=1%3A2010))

**Comment by ackernaut** [comment]
Before implementation, I need to work through our TBD of where to stick this…

**Comment by ackernaut** [comment]
I’ve made an update here. The AC are edited above. Here’s [a fresh Figma file](https://www.figma.com/file/aFpTjk6wGGfHeYKcUXfdqn/Team-member-management?node-id=1%3A1490) outlining the view states. Moving this to the backlog for implementation.

**Comment by nickoferrall** [comment]
Rough plan:

- build the Team view top bar before the Manage team side sheet
- borrow from the agenda items right sidebar in the Team view. Make it as wide as the left sidebar
- consider borrowing from the org members view for the `more_vert` menu toggle
- build out the mobile view once desktop is ready

**Comment by nickoferrall** [comment]
Hey @ackernaut, thanks for the detailed AC here! One question - you mentioned: "The Add Meeting button should be in the bottom right of the main view when any side sheet is open, not over the side sheet"

The Add Meeting fab currently sits on top of the agenda items right sidebar. To keep things consistent with the Manage Team side sheet, do you think we should move that one too?

![fab](https://user-images.githubusercontent.com/39854876/130157485-f79025b8-8cab-4645-93be-56a6ba95e163.png)

I quite like how it looks in the agenda item sidebar with the content sitting above the fab. There's less space for the content but I'm used to it fab floating above all content and not moving when changing views.

**Comment by ackernaut** [comment]
@nickoferrall Thanks for the question here. My opinion is that leaving the floating action button in place, over the side sheet, is not in the spirit of Material Design, but an ad hoc solution that we get away with in this context.

If I were to normalize the pattern I would assert that the floating action button is positioned over the main view, and that for larger viewports, the standard side sheet pushes in, not over, the main view. The main view is now narrower as a result. In addition, the mobile side sheet would push in over the view, and obscure any floating action view or content in the main view.

There are probably some places in the app where columns scroll under the side sheet and I would consider this a pattern of overflow in the main view, although it has the same effect as the side sheet pushing over instead of in. I’m okay with the overflow in certain contexts. However I think treating the floating action button in the current way is probably not a good idea in many contexts.

In this case a meeting button is over a meeting agenda. But when a team member list is in the side sheet, now a meeting button is ‘out of place’ over the member management context.

To my knowledge there’s not a specific example of how to treat a floating action button when a standard side sheet pushes in. This is my recommendation.

Here are the specs for reference:

https://material.io/components/sheets-side
https://material.io/components/buttons-floating-action-button

I don’t want to stop the show. Move forward in the way you see fit. If the change is easy I’d say go for it. If not I consider it UI design debt.

**Comment by nickoferrall** [comment]
Makes sense! Thanks for the explanation and links. I'll work on adding it to the main view and making the agenda item sidebar consistent 👍
