### ISSUE TITLE
pull everyone into a meeting automatically if they are on their team page and a meeting has begun 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5008]
A [user ](https://app.hubspot.com/contacts/3888472/contact/3935301) 🔒 says:

> it'd be nice if everyone who was on team page when a meeting was started got dragged right in to the meeting automatically

**Comment by jordanh** [comment]
I don't think we want to do this, it's not really in our principles to force navigate folks. However, I think there is room to integrate this feedback to change our team view to make it easier to find where to go.

@mattkrick would want to know, "what today about our snackbar, [the little message that pops up], doesn't work?"

**Comment by jordanh** [comment]
Related: #3458

**Comment by jordanh** [comment]
Closing.

Please re-open if we get similar feedback.
