### ISSUE TITLE
give the facilitator a sound board to add delight 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5010]
A [user ](https://app.hubspot.com/contacts/3888472/contact/13165151) 🔒 says:

> I like to have a sound board open during Parabol meetings. When I move a Jira ticket to done during a retro I will make a ka-ching sound or a super mario coin sound. this keeps things a little more interesting. Maybe you could add something like this into the app. 

related to [issue 4570](https://github.com/ParabolInc/parabol/issues/4570)

**Comment by jordanh** [comment]
Making discussion to see if we hear this feedback more often
