### ISSUE TITLE
Support recording video message in discussion thread

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5014]
## Issue - Enhancement

Loom just published their [recordSDK](https://www.loom.com/sdk-beta). We can now support injecting a video message in our meeting discussion thread.

Note: [design for 'action bar'](https://github.com/ParabolInc/parabol/issues/4889) might be a pre-requisite. 

### Acceptance Criteria
   - Users can click the record button in action bar under discussion thread to start recording
   - When recording is done, an embedded Loom video is inserted into the discussion thread
   - User can play back the video
   - User can delete the video

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Making a design issue to draw some protos as a next step, should we choose to prioritize this
