### ISSUE TITLE
password reset token expiring too quickly

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5018]
A [user](https://app.hubspot.com/contacts/3888472/contact/32838051) 🔒  writes:

> When I click on the reset password link, it takes a long time to receive it on my corporate email account.
> 
> By the time I get the reset password email, and try to reset the password by entering a new one in the text box, I always get “Reset token expired”
> 
> Cannot login anymore, cannot use parabol

[Hubspot ticket ](https://app.hubspot.com/contacts/3888472/ticket/437958976/)🔒

**Comment by tiffanyhan** [comment]
This person has three reset password requests in the db, all of them invalid. Every time a person makes a password reset request, we invalidate all previous requests. 

In [mailgun](https://app.mailgun.com/app/sending/domains/mail.parabol.co/logs?date_from=2021-05-28T00%3A00%3A00.000Z&date_to=2021-06-03T23%3A59%3A59.999Z&search=vbanda%40expediagroup.com&sort=datetime%3Aasc&recipient=vbanda%40expediagroup.com&tags=type%3AresetPassword&page=0), I can see that all three password reset requests were accepted and queued by mailgun immediately. The first email got sent out 4 mins after queued. The second and third emails went out 4 mins after that, and the third 5 mins after that. 4 mins seems like a pretty long wait time, so we might want to look into mailgun load and possible priority configurations (is it possible batch marketing messages were being sent out during that time?).

The first two password reset requests were invalidated bc of subsequent reset requests. I'm guessing the third one was invalidated bc it was used, and then the user tried to use it again or tried to use previous reset requests again. This isn't a bug on our part, but a possible performance issue with mailgun.

Engineering next steps:
- [ ] investigate mailgun load and priority configurations. does mailgun use priority queue under the hood, and are we currently utilizing that?

Support next steps:
- [ ] @drewhousman1010 can tell the person we're looking into performance issues with our 3rd party email provider, that they've hit the password reset limit and please try again in 24 hours. if they urgently need to get to parabol today, i can make manual changes in the db but prefer not to.

**Comment by tiffanyhan** [comment]
I opened up a [support ticket](https://app.mailgun.com/app/support/view/1679099) with mailgun to see if they have any explanations and/or advice.

**Comment by tianrunhe** [comment]
Mailgun had [an incident on 2021-06-03](https://status.mailgun.com/incidents/fc1wfjhbg4nm) that delays the delivery of emails. It was reported at 05:56 PDT and it was resolved at 09:06 PDT. The customer contacted us at 08:10 PDT so he/she is definitely impacted by this incident.

Anything else we need to do from our side? @tiffanyhan

**Comment by mattkrick** [comment]
this is great. i think we can correctly say that this is the fault of mailgun & it is pretty rare (incident from 6 months ago). 
Reprioritized to p4 since there are work arounds & it doesn't affect many folks.

Closing for now, we can re-open if this crops up again
