### ISSUE TITLE
'highestTier' not always updated in Hubspot, Amplitude

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#5019]
## Issue - Bug

In the course of going to review some of our Pro accounts (thread [here](https://parabol.slack.com/archives/C9519N85P/p1622746014068300) and [here](https://parabol.slack.com/archives/C9519N85P/p1622751502078400) 🔒 ), we found that some members of Pro orgs were showing `highestTier` as `personal' in both Amplitude and Hubspot. 

Examples: 
- This [user](https://parabol.slack.com/archives/C9519N85P/p1622751502078400) 🔒 is in a Pro org, but showing as personal in both Hubspot and [Amplitude](https://analytics.amplitude.com/parabol/chart/7xxr9dc?source=redirect%3A+chart+saved) 
- This [user](https://app.hubspot.com/contacts/3888472/contact/11499351) 🔒  is also in a Pro org, but showing as personal in both Hubspot and [Amplitude](https://analytics.amplitude.com/parabol/chart/7xxr9dc?source=redirect%3A+chart+saved)  

We fixed as similar issue recently: #4730 but that was due to a Hubspot-specific issue, so may not be directly related. 

### Acceptance Criteria (optional)
HightestTier data is correct in Hubspot and Amplitude, and matches what's in Parabol. 

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tianrunhe** [comment]
Quick update: both of the users are marked as `personal` in our DB, i.e., HubSpot & Amplitude is in sync with our source of truth.

Therefore we should investigate why they are marked as `personal` in our DB in the first place. Maybe there is a bug in the logic of calculating the highest tier.

**Comment by jordanh** [comment]
Iceboxing
