### ISSUE TITLE
create ability to compare estimates vs time spent in poker 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5021]
A [user](https://app.hubspot.com/contacts/3888472/contact/30460701) 🔒  says:

> Can you do Sprint review > where it pick the jira ticket and then see the realestimation compare to the sprint poker?
Just an idea :wink:

@BartoszJarocki interpreted this to mean the following: I think he wants another type of meeting ‘sprint review’ where he’d be able to select the Jira tickets (as in sprint poker) and then compare the original estimates vs real time spent

**Comment by mattkrick** [comment]
not every task integration will store a history of estimates. 
even if they do, not every team will use the 2 fields as they should be used.
I think the _right_ way to do this is to keep a history of story point estimates.
Then, as the value changes in jira, we can create a new record in our system.
For reporting, we can compare the last record to a previous one.
