### ISSUE TITLE
Add 'domain' property to events sent to Amplitude 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#5023]
## Issue - Enhancement

Right now, when we see a trend in our data, it's difficult to know which accounts or companies account for that change. For example: 
- If we saw that [fewer teams met this week versus last week](https://analytics.amplitude.com/parabol/chart/6nvw77b)🔒, and wanted to know if that was true across many accounts, or if the change was in a few larger accounts, we couldn't see that. It seems that at some point we sent 'OrgID', but that's [coming up empty now](https://analytics.amplitude.com/parabol/chart/m6pjcyv?source=redirect%3A+chart+saved)🔒. Something like 'company name', 'org Name' or 'domain' would be more useful, as we could easily link the data to accounts we're familiar with. 
- If we wanted to know which accounts were expanding, we can't see `account created` by domain or org. We _could_ group by an email property, and then export, but it's ultimately fussy. 
- We can't easily see which accounts upgraded to Pro. To figure this out, I usually look at `upgraded to Pro`, and then group by email, and from the email address, I figure out the company. So this one is doable, but not great. 

### Acceptance Criteria (optional)
Key events include a property indicating which company or account they're related to. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
#5502 makes this request ready to implement.
