### ISSUE TITLE
Everyone can add emojis to cards/groups before discuss phase

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5027]
## Issue - Enhancement

A user says:

> So I typically like to follow an ORID pattern when I run retros. Once all of the cards are laid out, i want to give my team a chance to use emojis to reflect how the observations made them feel before we actually discuss and reflect.

**Comment by jordanh** [comment]
While I've wanted this too, we didn't collect additional feedback where. Iceboxing for now
