### ISSUE TITLE
Remove localStage/localPhase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5030]
Keeping local objects as shortcuts turned out to be a bad idea.
Primarily because we have to duplicate the graphql fragment in the request that goes to the server
e.g.
```gql
      localStage {
        ...EstimatePhaseDiscussionDrawerEstimateStage @relay(mask: false)
      }
      phases {
        stages {
          ...EstimatePhaseDiscussionDrawerEstimateStage @relay(mask: false)
        }
      }
```

this is a sharp edge for new developers because it's easy to forget that you have query for the server-side piece.

instead, we should get rid of the localStage/localPhase & just have a helper method like findStageById

AC
- [ ] localStage & localPhase is removed across the app & replaced with a helper function that takes in `phases, stageId` or similar

Estimate: 8 hours

**Comment by mattkrick** [comment]
still a thing, but i guess not high priority

**Comment by mattkrick** [comment]
Reopening because this is the root cause of #6247.
We should kill this pattern via a refactor to remove the possibility of this happening in other meetings

**Comment by jordanh** [comment]
@mattkrick this went stale again. At-mentioning you as a courtesy. Please re-open if you feel so moved. If you do re-open it, let's add it to the All-Product team check-in so we can take a next-action
