### ISSUE TITLE
Send `highestTier` property on `Meeting Completed` events

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#5032]
## Issue - Enhancement

We have a `highestTier` property for Companies in Hubspot. For most companies on the Pro or Enterprise tiers, this property in Hubspot is still showing 'unknown'. That seems to be because we only update it when companies upgrade or downgrade.[Discussion on Slack here. ](https://parabol.slack.com/archives/C9519N85P/p1623178139127800)

Suggestion for fixing this from @tianrunhe on Slack: update this property on Meeting Completed events as well. 

### Acceptance Criteria (optional)
Hubspot property for `highestTier` matches the current plan for the company. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by avivapinchas** [comment]
This may also apply to Contacts - the [vast majority (90%) of Contacts created this year do _not_ have highestTier set ](https://app.hubspot.com/reports-list/3888472/79340138/)🔒, which I'd assume is because that property is only updated when a contact upgrades or downgrades as well.

**Comment by jordanh** [comment]
I'm going to remove this from the backlog and request the @tianrunhe and/or @tghanken add it to theirs...
