### ISSUE TITLE
Consolidate user records in PG

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5057]
## Issue - Enhancement

We have finally achieved equality between RethinkDB & Postgres for `User` table. We just need to enforce the unique email constraint in PG before we can read from it (#4867 ). Today there are 15 emails in PG that have more than 1 records associate with it.

### Acceptance Criteria
- [ ] For each of the email, determine the unique user record, consolidate the data if necessary
- [ ] Remove the duplicate user records from RethinkDB
- [ ] Remove data from other tables in RethinkDB for the duplicate users (see #5035 )
- [ ] Remove the duplicate user records from PG
- [ ] Add unique constraint back to User email field
- [ ] Run equality checker again to verify two DBs are in-sync after above operations

**Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tiffanyhan** [comment]
sounds nice! we'll also need to write a unique email string when deleting a user.

https://github.com/ParabolInc/parabol/blob/a680ff179f4a77040ef16ee3ba93e700a15fa140/packages/server/graphql/mutations/deleteUser.ts#L77-L87

There's already a helper fn for that here:

https://github.com/ParabolInc/parabol/blob/c099c2438239eb2ec6f4c515c4d53d2c00b07571/packages/server/utils/getDeletedEmail.ts#L1-L2

**Comment by tianrunhe** [comment]
> sounds nice! we'll also need to write a unique email string when deleting a user.
> 
> https://github.com/ParabolInc/parabol/blob/a680ff179f4a77040ef16ee3ba93e700a15fa140/packages/server/graphql/mutations/deleteUser.ts#L77-L87
> 
> There's already a helper fn for that here:
> 
> https://github.com/ParabolInc/parabol/blob/c099c2438239eb2ec6f4c515c4d53d2c00b07571/packages/server/utils/getDeletedEmail.ts#L1-L2

I think in this case we will do a hard delete. Like, nuke them💣

**Comment by tiffanyhan** [comment]
> I think in this case we will do a hard delete. Like, nuke them💣

oh i see, even better!
