### ISSUE TITLE
Discussion: refactor Segment events to cut event count

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5059]
## Issue - Enhancement

Our current agreement with Segment is ~$1.3k/mo; event overages from our current tier cost us on average about $400/mo on top of this. It'd be nice to avoid this cost.

We generate approximately 2.5M events/mo. Auditing our event counts, we can save about half of these events.

The #1 event is `Loaded a Page` (~1.2M/mo). We should keep these events as is. We use them _all_ over the place. `Connect Websocket` and `Disconnect Websocket` account for ~600k/mo each (~1.2M/mo) in total. These latter events are the ones to refactor.

`Connect Websocket` and `Disconnect Websocket` are used within Amplitude to calculate accurate MAU and WAU stats. We _certainly_ could calculate these another way.

### Proposed design

I'd like to:

- [ ] Use connection stats on each `User` record to calculate metrics
- [ ] Create a private GraphQL query that allows us to query these statistics:
   - [ ] by day, week, month, year
   - [ ] starting on datetime
   - [ ] returning a number of n groups (e.g. "7 days", "3 months", or "1 year")

Optionally:

- [ ] Emit an event called `Hourly Connection Statistics` every 0th minute of every hour with the following properties:
   - [ ] `connections` the number of websocket connections
   - [ ] `disconnections` the number of websocket disconnections
   - [ ] `connections_unique` the number of websocket connections unique to each `User`
   - [ ] `disconnections_unique` the number of websocket disconnections unique to each `User`

Having this event in the Segment stream would allow downstream GUI tools (e.g. Amplitude) to still display WAU/MAU on dashboards.

### Next steps

Making this a discussion issue to explore alternatives before settling on A/C

**Comment by jordanh** [comment]
@mattkrick penny for your thoughts

cc @avivapinchas

**Comment by avivapinchas** [comment]
@jordanh I'm confused about how this would then be available in Hubspot. Can you explain that part?

**Comment by mattkrick** [comment]
i _really_ like the private query.

for the API, i propose something like 

```gql
query {
  stats {
    wau(announce: true): number
    mau(announce: true): number
  }
} 
```

if announce is true, we publish that data to our data stores.
@jordanh

**Comment by tianrunhe** [comment]
> I'm confused about how this would then be available in Hubspot. Can you explain that part?

@avivapinchas My understanding is that HubSpot will not be affected at all with this proposed change as we are not looking at it for WAU/MAU data. 

Amplitude, on the other hand, will be affected a little bit.
Today how we emits data is like this:
```
User A connects at 06/22/2021 00:01:00
User A disconnects at 06/22/2021 00:11:00
User A connects at 06/22/2021 00:21:00
User A disconnects at 06/22/2021 00:31:00
User A connects at 06/22/2021 00:41:00
User A disconnects at 06/22/2021 00:51:00
```
i.e., 6 distinct events.
With this proposed change, we will aggregate these events into a single one:
```
User A connects 3 times during 06/22/2021 hour 0 and disconnect 3 times during 06/22/2021 hour 0
```

**Comment by avivapinchas** [comment]
@tianrunhe Ah I meant Amplitude - working too fast! Yes, that makes sense to me for Amplitude- so we'd still see the connect/disconnect, but instead of 3 events, we'd see 1 event. 👍

**Comment by ackernaut** [comment]
In backlog refinement, we decided we should keep this on our radar. @tianrunhe can you write acceptance criteria and give a first estimated effort

**Comment by jordanh** [comment]
I thought of this issue this morning and about how I think it could make a good BP.

**Comment by jordanh** [comment]
We discussed internally. Here is the outcome:

This issue will remain designated as a _Batting Practice_ with the following Acceptance Criteria:

- [ ] Architecture proposed for how to resolve this issue as new GitHub issue (closing this issue)

Estimated Effort: 8 hours

We'd intent a PR for an implementation for this issue to also be included in a _Batting Practice_

**Comment by jordanh** [comment]
We're electing to be billed by tracked user, so this won't help our bill. Iceboxing
