### ISSUE TITLE
Designed persistent story context in poker meetings to not lose estimations

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5060]
### Acceptance criteria
- Designed and proposed an end-to-end experience solving for #4992 supported by sketches, a prototype, design notes, etc.
- Validated with core Parabol teams and the reporting user if they’re willing to give feedback
- Drafted 1 or many implementation issues for the validated design

### Estimated effort
- 16 hours

**Comment by mattkrick** [comment]
Closing in favor of #5162. tasks will hold the estimates so we don't lose any data :tada:
