### ISSUE TITLE
UI implementation details for the ‘work activity’ side sheet

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5061]
This defines the UI components and behavior for the output of #4913

It does not specify implementing separate integrations including the content of the results for that integration.

Here’s [the clickable prototype](https://www.figma.com/proto/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?page-id=435%3A34605&node-id=435%3A34606&viewport=1096%2C460%2C0.25&scaling=scale-down) and here are [frames for the various states](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/?node-id=739%3A41421) for both laptop+ and mobile viewports.

### Viewing the work activity side sheet
- The work activity side sheet is open by default. If a user closes the side sheet we store that user preference using local storage in the browser
- A toggle in the upper right opens the side sheet. It’s only visible when the side sheet is closed. It uses the `insights` icon and has a tooltip ‘See work activity‘
- For clarity we change the ‘Tips’ icon in the bottom bar from `help_outline` to `lightbulb`
- Mobile uses a modal side sheet that appears over the content with a scrim ([see Figma](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=741%3A47400)). At the `SIDEBAR_LEFT` breakpoint, it uses a standard side sheet that pushes in on the right side of the content. For more see [the MD docs for side sheets](https://material.io/components/sheets-side#usage)
- The side sheet has 1 tab per integration: GitHub, Jira, Parabol — tapping the tab animates to the view for that tab
- The side sheet has an icon control `close` in the upper right. Tapping this closes the side sheet and reveals the ‘See work activity’ toggle
### Adding an integration
- [This view](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=741%3A46367) has an image, some copy, and a button. It’s visible if the integration hasn’t been added by this user for this team. Tapping the button adds the integration, using an authorization workflow in a small window if necessary
### Viewing work activity items
- Each item has a title line and a meta line. They are read-only. Tapping the title opens the item in a new tab
- There’s [a loading state](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=741%3A46368) when first loading work activity items or changing filters
- If there are no results, we have an empty view. It uses an image and some copy with a tip on how to see results ([see Figma](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=741%3A47399))
### Filtering
- There’s a ‘since date’ filter. A control `date_range` ‘Since [month day]’ is the toggle. It uses a calendar menu component. This sets the filter to only show work activity items since the date specified. By default we set it to the last time the team had a retro or 2 weeks ([see Figma](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=741%3A46370))
- There’s a sort control. It lists a set of options for sorting e.g. ‘Most recent activity’ vs ‘Least recent activity’ — how this works is TBD based on the API of the integration ([see Figma](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=739%3A41421))
### Future considerations
- Maybe one day items are separate and use an elevation 0 border. They could be dragged into the view and included as an inline reference ([see variants in Figma](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=248%3A0))
- Maybe one day if you hover a work item you see a preview. The intent is to show more details so that folks don’t have to tap through to a new tab as often ([see Figma](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=252%3A380))

**Comment by ackernaut** [comment]
An update here: I made a first pass writing down the details of the UI and behaviors to support a first version of a ‘work activity’ side sheet (aka Reflection Inspiration).

This doesn’t represent the implementation issue for each specific integration, but could be included in the acceptance criteria, as each should follow the overall UI pattern. I suppose we’ll start with GitHub so much of the UI work will be done then and others can follow suit.

It also doesn’t cover what work activity the API for each integration supports, or what sorting options might be available.

**Comment by ackernaut** [comment]
@mattkrick I imagine you are most keen to review this? I can stub out separate issues for building out each integration tab.

**Comment by mattkrick** [comment]
looks good to me!
only thing wrt implementation is i'd say we leave out the sort for a v1.
i'm still building the github integration, so maybe we have a dev build out the sidebar and just have a functioning parabol tab? for the other 2 we can put in a dumb "coming soon" and cute logo

**Comment by ackernaut** [comment]
> looks good to me!
> only thing wrt implementation is i'd say we leave out the sort for a v1.
> i'm still building the github integration, so maybe we have a dev build out the sidebar and just have a functioning parabol tab? for the other 2 we can put in a dumb "coming soon" and cute logo

I’m okay deferring the ability to sort. I’m good with your plan to chip away at it. Perhaps this issue can be referenced for the bits that get built out incrementally? Do you want me to write out a first-step issue?

**Comment by mattkrick** [comment]
sure! i'd recommend a first pass as something with just the UI elements & no data connected & a flag that hides the button

**Comment by ackernaut** [comment]
I opened #5076 and #5075

**Comment by ackernaut** [comment]
Closing this, but it’s linked in the next issues as a reference for the UI details
