### ISSUE TITLE
Task context designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5063]
## Issue - Enhancement

See user requests/notes in #4649

### Acceptance Criteria (optional)

A lo-fidelity design that:
   - Allows users to discover when a Task card has context (i.e. came from a Meeting)
   - Can see details of that context (i.e. via hover or click), such as:
      - Agenda item name
      - Related Reflections (if Retrospective)
      - Related Tasks (i.e. Tasks in created in same Discussion thread) or integrated Stories, if Sprint Poker)
      - Related Comments (i.e. from same Discussion thread)
   - Can navigate to specific context (i.e. the meeting discussion from whence the task came)

**Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@enriquesanchez I thought this might be something you'd be interested in designing during a sprint in the near future

**Comment by enriquesanchez** [comment]
Oh, definitely! Adding it to my task list @jordanh 🙌

**Comment by enriquesanchez** [comment]
Designs are ready:

![image](https://user-images.githubusercontent.com/3276087/132251749-71c68b03-1789-47ec-bb04-b505ec4c11ea.png)

I've broken the UI work down into several issues:

1. #5366
2. #5367
3. #5368
4. #5369
5. #5370
6. #5371

**Comment by avivapinchas** [comment]
Re-opening, as this came up during a sales call with this [contact](https://app.hubspot.com/contacts/3888472/contact/54829251) 🔒

**Comment by charlesmathias** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/56490051) 🔒  says:

> I would love to have task context: eg a link to the discussion point if a task came from a meeting. This helps to understand the full context of a task without having to leave your task list and go through all of your old meetings.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/67465801) 🔒 asks if task cards could link back to the discussion for context.

**Comment by enriquesanchez** [comment]
During [a demo call](https://www.notion.so/parabol/Alicia-Collymore-3b64e18ceed5437694f0e08ffc12d2da?pvs=4) 🔒 a user shared how they wish Tasks had context of where they came from:

>My biggest annoyance is that there’s no context of where the task came from. I have to search in my email to find the meeting summary where the task came from and then open that retro. I have to do this for most of my tasks”
