### ISSUE TITLE
Move cards across columns during grouping phase without having to form groups 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5066]
A [user](https://app.hubspot.com/contacts/3888472/contact/11903651) 🔒  says:

If you want to move a card from one column to another during the grouping phase you need to put it with another card. It can't live on its own. Makes it harder to put cards where you want, this was frustrating.

**Comment by mattkrick** [comment]
if you get a chance to hear about use case for this one, i'd love to learn more!
if we let folks drop cards between other cards, then there's a chance that they'll accidentally move a card instead of grouping it, which is a bummer.
how we run retros, i don't know why you'd want to mix & match, but i'm probably missing something

**Comment by jordanh** [comment]
There was some elaboration in Slack, will mirror the jist here for the record.

This particular set of users was using the retro for brainstorming things they could do, and their cum prompts were different efforts "1 day," "1 sprint," etc. Moving items between columns was used to change the effort for a brainstormed task

**Comment by jordanh** [comment]
Marking as discussion until we receive more feedback/coalesce to a defined list of acceptance criteria

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/20229501) 🔒  says:

> > 
> I want to be able to move a card from one column to the other, e.g. we put a card in the "stop" column but actually, after discussion, we decide we would rather it live in the "continue" column. The discussion can make you change your mind about what should actually be in each column. 
>

**Comment by jordanh** [comment]
Iceboxing
