### ISSUE TITLE
Adds a functional Parabol tab in the work activity side sheet

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5075]
This is the first part of the ‘Inspiration’ side sheet.

### Acceptance criteria
- The UI components follow the criteria from #5061 
- The tab for Parabol is functional
  - We show the **_most recent to least recent_** Parabol tasks that were **_created, edited, or moved to [status]_** on the team. If the mixed criteria is high-effort we can start with **_created_**
  - Each task has:
    - A title line that ends in ellipsis if the text is long
    - A meta line that shows when created, edited, or moved to [status] (whichever was latest). We can start with ‘created’ if this high-effort
    - TBD: Tapping expands the task inline, revealing full text and more meta? ([see an example in Figma](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=754%3A2268))
  - We add a ‘time since’ filter with a calendar menu (see #5061 for more details)
  - Deferred: we build a sorting affordance later

### Estimated effort
- 24 hours

**Comment by ackernaut** [comment]
@mattkrick here’s an issue for building the Parabol tab. What do you think about:

>TBD: Tapping expands the task inline, revealing full text and more meta?

Maybe it’s okay to handle Parabol inline since we don’t have a single task view, but integration items can open in a new tab?

**Comment by ackernaut** [comment]
Here’s a look at [Parabol tasks as dense list items & a way to expand inline](https://www.figma.com/file/JBkyDJcOO9AtxTb2Z81URS/Inspirations-Retros-and-Standups?node-id=754%3A2268)

**Comment by mattkrick** [comment]
yeah, either expand or an outlink to the Tasks page with userId & teamId set so it's guaranteed to show up

I'd probably filter tasks so that `userId === viewerId || createdBy === viewerId` to make them more relevant to the viewer

**Comment by ackernaut** [comment]
It’s interesting to think about what outstanding work on the team raises a tension for an individual. The simple answer from a bottom-up UX is to start by showing the viewer’s tasks. Maybe there’s a way to change it to see across the team. Maybe a lead is looking for items that were stuck or didn‘t get attention, etc.

**Comment by jordanh** [comment]
We're going to do this...one day
