### ISSUE TITLE
Stubs out the work activity side sheet

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5076]
Here we build out the UI containers but hide it behind a feature flag until at least 1 integration tab is functional, maybe Parabol #5075 or GitHub first?

### Acceptance criteria
- Follows the general details of #5061 
- Each integration tab is empty
- The toggle is hidden behind a feature flag
- The side sheet is not open by default; there’s no local user preference

### Estimated effort
- 24 hours

**Comment by jordanh** [comment]
Keeping open

**Comment by jordanh** [comment]
Oh dang! I have a feeling this one will come around again soon
