### ISSUE TITLE
TypeError: n is null

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5081]
Affecting 5 users in the last 1-4 weeks. First seen in 6.12.0

https://sentry.io/organizations/parabol/issues/2419715521/?referrer=github_plugin

```
TypeError: n is null
  at c (./packages/client/components/MeetingSelector.tsx:30:34)
...
(29 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
No longer seeing this in Sentry. Closing
