### ISSUE TITLE
get a heads up that the existing poker notes and estimates will be wiped in certain Sprint Poker situations

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5087]
A [user](https://app.hubspot.com/contacts/3888472/contact/13344751) 🔒  writes:

> > 
> Hi, we love the new Sprint Poker tool. Some feedback: when I'm running a Sprint Poker meeting using Jira tickets as the scope and I backtrack from an estimate to update the Jira filter used as the scope, it would be helpful to get a heads up that the existing poker notes and estimates will be wiped (which is probably foreseeable, but it can be a nasty surprise if you're blindly multitasking).

**Comment by mattkrick** [comment]
not sure what they mean about existing poker notes.
valid point about overwriting estimates though. maybe we pop a warning if we find an existing value

**Comment by drewhousman1010** [comment]
> not sure what they mean about existing poker notes.
> valid point about overwriting estimates though. maybe we pop a warning if we find an existing value

from the OP: 

> Thank you! By "existing poker notes", I mean the comments that can be saved for each issue.

**Comment by mattkrick** [comment]
oh! well that shouldn't be, we only add comments, we never remove any. if we can reproduce that that'd be a good bug to fix

**Comment by mattkrick** [comment]
this will be fixed in #5171

**Comment by jordanh** [comment]
I expect not to prioritize this issue directly, but rather address with #5171
