### ISSUE TITLE
Multiple retro phases of divergence and convergence

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5090]
# Prompting Tension

[A user](https://app.hubspot.com/contacts/3888472/contact/3519751) 🔐 writes:

> I'm new to Parabol, but it seems to be very prescriptive in exactly what steps you must perform, and in what order.
> Or is there a way to customize one's retro in Parabol?

After asking for clarification:

> There's a retro format (and variants) that involves brief creative writing, then iterating on that. I doubt I'm the first to use it, but I can't recall my inspiration for it.
> 
> My example from today (literally right before I emailed you) was:
> 1. First column. Write a very brief fairy tale for Sprint [x] where the participant is the main character in the kingdom of [Project Name]. Try to include an obstacle, an achievement, and/or hope for the sequel (next Sprint). This is two or three sentences, sometimes a little longer.
> 2. Second column. From the first column, find Common Themes. Then we group and vote on this column only.
> 3. Then discuss the Common Themes to find Action Items like usual.
> 
> Other variations I do is making column 1 an "Amazon Review" of the Sprint, or a "Wedding Toast" to the Sprint. Regardless, we read these together, then build the next column.
> 
> So basically my customization wish would be reviewing, grouping, and voting on columns separately before the Discussion step.

# Solution(s) Conjecture

Parabol is certainly proscriptive today, and accommodating this sort of format would be difficult.

One option would be to allow Retro prompts to be configurable non-anonymous (showing content and perhaps even authorship, see also: #2806)

Another option would be to allow for multiple cycles of divergence and convergence: Allowing for multiple Reflect, Group, or Vote stages the output of one being an input to the next. Have two Reflect stages next to each other? Perhaps you see all the input as "Inspirations", etc.

# Next Steps

Going to keep this issue open as a discussion to see if we collect similar feedback.

**Comment by jordanh** [comment]
Ah ha! Signal on exactly this.

[A user](https://app.hubspot.com/contacts/3888472/contact/25028601) writes 🔒 :
> I checked what was possible to do with custom templates, but I could not find a way to fit my needs.
>I would like to add a grouping & voting step in a retrospective:
> 1. Reflect (what we can customize with templates)
> 2. Group
> 3. Vote
> 4. Reflect again to make propositions, or at least do it together while someone is adding cards
> 5. Group (optional)
> 6. Vote
> 7. Create TODO cards with the most voted
>
> I currently need to do the 2nd vote manually, but if I create a new template, I will need to do the 1st vote manually instead, which is not what I'd like to do.

**Comment by jordanh** [comment]
Another user writes 🔒 :

> The session was designed around several topics: Current Reality, Vision, Action Planning. I had to do these in different meetings. It would be great if Parabol had the flexibility to create several rounds within a single meeting (Reflect, Group, Vote, Discuss) and if everything remained editable and accessible even as you moved on. This would make it easier for people to refer back to earlier conversations and would make the documentation more discoverable. I wrestled with ~tool X~ for two days because of this, but gave up. Parabol is so much easier to use. If it had more flexibility it could be used for many other use cases.

**Comment by jordanh** [comment]
@ackernaut interesting signal on multiple rounds came in just this week

**Comment by ackernaut** [comment]
@jordanh I saw. This will come in handy as we think of a composable meeting system. I imagine the end result is far in the future, if ever, but we can continue to improve our conceptual model underneath our designs. I like the idea of [conceptual integrity](https://en.wikipedia.org/wiki/The_Mythical_Man-Month#Conceptual_integrity) (Brooks) and lately have been trying to see our system through that quality.

**Comment by jordanh** [comment]
Iceboxing
