### ISSUE TITLE
Remove SuggestedIntegration in favor of GitHubRepo and JiraProject

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5094]
The SuggestedIntegration graphql type is basically the same thing as a github repo or jira project.
let's remove it & replace it with a interface that resolves to those things to make it a little easier to understand.

AC
- [ ] SuggestedIntegration and all subtypes are removed
- [ ] a new interface type is created that resolves to a _xGitHubRepo or JiraRemoteProject, perhaps `IntegratedRepo` or `RepoIntegration`?
- [ ] projectKey is no longer required to keep on the Task.integration for Jira tasks (today it is used to determine which project to recommend)
- [ ] list of suggestions are checked to be valid (ie WAMP is not available in the dropdown for jira because the project no longer exists)

Estimate: 8 hours

**Comment by mattkrick** [comment]
> We want to remove the SuggestedIntegration type and replace it with a interface, but it looks like SuggestedIntegration is already an interface (see here)?

Yep, let's replace this with `TaskIntegration`.
TaskIntegration is an interface of _xGitHubRepo & JiraRemoteProject (and more to come later)
To determine if it is a _xGitHubRepo or JiraRemoteProject, today we use `isTypeOf`& that should probably be good enough.

The solution can be 1 or the other:
- Either we add `isTypeOf` to the _xGitHubRepo here https://github.com/ParabolInc/parabol/blob/33c3478b8699f0a61e092b533c36e4e6ac03c704/packages/server/graphql/rootSchema.ts#L32
- Or we could always fallback resolveType on the TaskInterface type
- e.g. `  isTypeOf: (value) => value.service === 'jira',`

> projectKey is no longer required to keep on the Task.integration for Jira tasks

see https://github.com/ParabolInc/parabol/blob/fa276fb44fff283b51e242221a1129610fd43045/packages/client/shared/gqlIds/JiraProjectKeyId.ts if you need projectKey, but the work should be done already

> What does WAMP mean in this context?

WAMP is just the name of an archived project on jira. Suggestions probably shouldn't come from most commonly integrated tasks. If we can get rid of this https://github.com/ParabolInc/parabol/blob/8729ec5e362606172b51eba7af1814bac71b3cc9/packages/server/graphql/queries/helpers/suggestedIntegrationHelpers.ts#L46, then SUPER!

**Comment by nickoferrall** [comment]
Hey @mattkrick, you mentioned in the AC that we should create `a new interface type that resolves to a _xGitHubRepo or JiraRemoteProject, perhaps IntegratedRepo or RepoIntegration`. In the comment above you mentioned that we should replace `SuggestedIntegration` with `TaskIntegration`, which interfaces `_xGitHubRepo` and `JiraRemoteProject`. 

I just wanted to check whether you're thinking we should replace `SuggestedIntegration` with `RepoIntegration` and keep `TaskIntegration`, or just replace `SuggestedIntegration` with `TaskIntegration` and forget `RepoIntegration`?

Currently, I'm working on the later approach, and I'm replacing all instances of `SuggestedIntegrationJira` & GH with `JiraRemoteProject` & `_xGitHubRepo`. 

However, `JiraIssue` interfaces `TaskIntegration` and contains the field `JiraRemoteProject`. If I add the `TaskIntegration` interface type to `JiraRemoteProject` too, I get a `Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization` error, but without it, `"JiraRemoteProject" is not a possible type for "TaskIntegration"`. I'm looking this now.
