### ISSUE TITLE
Basecamp integration

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5096]
A [user](https://app.hubspot.com/contacts/3888472/contact/40476451) 🔒 writes:

> My office recently started using parabol. I noticed you have other apps that can be linked to the meetings. We use Basecamp which unfortunately isn't one of the applications but I think it would be a great one to incorporate.

**Comment by jordanh** [comment]
Iceboxing this issue. Will create discussion if we hear again
