### ISSUE TITLE
Proxy jira images through parabol

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5100]
Discussion in #5098
Jira gives us image URLs that we can't put in img tags because they need an Authorization header. 

To get around this, we'll replace their URLs with a parabol URL that will retrieve an image stored in redis.
For ultimate security, we'd give the client a UUID that expires in an hour & then the server trades that UUID for a filename. then, to keep from saving the same image twice, it trades that filename for a file.
we can get away replacing the UUID with something deterministic as long as it's signed with a server secret.

AC
- [ ] request for a JiraIssue returns a `descriptionHTML` that looks through all img tags & replaces the `src` with `/jira-attachment/filename.ext`. it uses cheerio to do this. see https://github.com/ParabolInc/parabol/blob/a6f7d3153947b4f5cd70ef48912bbdf00b60bb94/packages/server/email/inlineImages.ts#L42-L50 for inspiration
- [ ] filename is the original src hashed with our server secret (e.g. ` crypto
    .createHmac(algo, SERVER_SECRET)
    .update(url)
    .digest('base64')`)
- [ ] the server writes a sentinel value to redis like `{[filename]: 'X'}` to signify that an image will be there soon
- [ ] the server fetches all images from jira, but does not await the result (ie `descriptionHTML returns before jira responds to the image fetches)
- [ ] when the result comes back, the server writes the image as a buffer to redis `{[fileame]: <Buffer>}`
- [ ] an http endpoint exists like `/jira-attachment/filename.ext`
- [ ] the endpoint handler grabs the buffer from redis
- [ ] if it has the sentinel value ('X') then it wait 500ms and tries again.
- [ ] if it still has the sentinel value, it times out & sends a default sad panda image (@ackernaut do you have an image that we could use as a "image failed to load" message?)
- [ ] if it has the image, then it returns that image
- [ ] the image has a ttl of 2 hours in redis (if you want to do a multi-set, here's some inspiration: https://github.com/ParabolInc/parabol/blob/c64e145ab51465a0c8487460c3c76f9c98186cb2/packages/server/dataloader/RedisCache.ts)

Estimate: 8 hours

**Comment by mattkrick** [comment]
@ackernaut @enriquesanchez do we have an image to show when an image fails to load? maybe a sad panda?

**Comment by enriquesanchez** [comment]
@mattkrick I'm not aware of us having anything already designed, but I can come up with something. Do you know the approximate dimensions we need?

**Comment by mattkrick** [comment]
@enriquesanchez  we'll be putting that image in a task card so maybe ~300px wide & 2-300px tall?

**Comment by enriquesanchez** [comment]
@mattkrick Is this similar to what you had in mind? These are PNG but if any of these feel like the one, I can send you the SVG.

![image](https://user-images.githubusercontent.com/3276087/127225495-924eef18-72fc-445a-803d-8dcb4778a027.png)

![image](https://user-images.githubusercontent.com/3276087/127225510-d7e0fbe7-54c5-4d57-84d1-5ff7603905a5.png)

**Comment by ackernaut** [comment]
@enriquesanchez thanks for taking this!
