### ISSUE TITLE
Poor man's jira webhook to keep tasks fresh without refresh

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5101]
Jira doesn't do webhooks.
That means if someone changes a task in jira & then comes back to parabol, the task in our system will be stale until they hit refresh. hitting refresh is gross :stuck_out_tongue_closed_eyes: 

So I've got this idea...
Today, on the task card we have a link to get to the issue in jira.
What if we just watch that tab & see when it closes?
Once it closes (or our tab regains focus) we send a `checkJiraForUpdate(issueKey, currentValueHash)` mutation that fetches the issue, hashes it, and sees if that hash is different from the client-provided hash.
if it's different, we push the change via subscription.

this isn't too crazy, we do something similar with OAuth popups (https://github.com/ParabolInc/parabol/blob/8c68bf771a350b31c7948e6bd11c5c110e30c977/packages/client/utils/getTokenFromSSO.ts)

AC
- [ ] a `checkProviderForUpdate` mutation exists that includes `service: TaskServiceEnum, key: string, currentValueHash: string` for args
- [ ] For Jira, the key is the `JiraIssueId` which includes the cloudId, issueKey, projectKey
- [ ] the `currentValueHash` is the hash of the content from the provider
- [ ] If the service variable is `Jira` then we fetch the issue from jira, hash the content & compare it to the client-provided currentValueHash
- [ ] If the value is different, then we update the issue in redis & send down the updated value in the response (the response payload should probably have a `task` field)

Estimate: 8 hours

**Comment by Dschoordsch** [comment]
@mattkrick it seems to me Jira does webhooks: https://developer.atlassian.com/cloud/jira/platform/webhooks/#registering-a-webhook-using-the-rest-api--for-connect-and-oauth-2-0-apps-

**Comment by mattkrick** [comment]
🎉 Closing this in favor of webhooks https://github.com/ParabolInc/parabol/issues/5101
