### ISSUE TITLE
TypeError: Cannot read property 'newMeeting' of null

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5103]
Since 14 hours ago, affected 7 users in 7 events.

https://sentry.io/organizations/parabol/issues/2488690956/?referrer=github_plugin

```
TypeError: Cannot read property 'newMeeting' of null
  at c (./packages/client/modules/summary/components/NewMeetingSummary.tsx:22:14)
  at Array.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
...
(35 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
@BartoszJarocki thinks that when folks click a summary from the timeline, the meeting referenced may not exist
