### ISSUE TITLE
refactor discussionTopicType to only be task (for now)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5104]
things like `taskServiceToDiscussionTopicType` should all point to type of `task`. doing that will keep us sane as we bring in more discussion topics & integrations

AC
- [ ] discussionTopicType has jiraIssue & githubIssue removed from it

Estimate: 4 hours

**Comment by jordanh** [comment]
@mattkrick says:
> We will feel this pain when we move the Discussion table over to postgres
