### ISSUE TITLE
Spotlight: UI Skeleton 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5106]
To get moving on spotlight, we'll build the UI first. See #5105 for the full list of UI specs

AC
- [ ] in the reflection card component, there is a static variable `const showSpotlight = true`
- [ ] if `showSpotlight` is true, then the the search icon appears
- [ ] On desktop, the search icon is hidden until hovered
- [ ] Hovering the icon shows a tooltip that says "Find similar" (or whatever copy you like)
- [ ] Clicking the icon opens up the "Spotlight Modal", which is a large modal that takes up the entire meeting area (excluding left nav & right drawer)
- [ ] At the top of the spotlight modal is the card that the user clicked (it will animated into place, just like expanded groups do today)
- [ ] below the card is an autoFocused search input field with the search icon on the left
- [ ] instead of search results, it just shows the following
![124508014-a3ec4200-dd94-11eb-9295-d89df0c228d6](https://user-images.githubusercontent.com/5514175/124647704-2c2d1e80-de4b-11eb-8185-346b3a3fbfca.png)

Estimate: 24 hours

**Comment by nickoferrall** [comment]
Hey @mattkrick & @enriquesanchez, the AC mentions that the modal should take up `the entire meeting area (excluding left nav & right drawer)`. Enrique mentioned in the Loom that we want to use as much space as we can while letting the user know that they're still in the Group phase.

A few questions:

1. We only show the right drawer in the Poker meeting so I assume we just want to account for the left sidebar?
2. Typically, we add opacity to the app around the modal to focus the user's attention on the modal. Do we want to do that here too? The designs in #5105 don't add the background opacity
3. If we want to add opacity around the modal, should we still leave space for the left sidebar? The second image shows what that would roughly look like. If we don't want to add opacity, I think it makes sense to leave space for the left sidebar as the modal feels like it just fits in place. If we do want to add opacity, I think we should leave space for the group title at the top but we probably don't need to leave space for the left sidebar as the user can't click the sidebar, it takes up real estate and it fits more naturally in the center imo. 

![image](https://user-images.githubusercontent.com/39854876/126240651-c2bdaaf0-51e5-4290-8013-0479fca1affa.png)

![right](https://user-images.githubusercontent.com/39854876/126240761-48acb326-3631-42eb-8ef8-d4db57953694.png)

![center](https://user-images.githubusercontent.com/39854876/126240622-431dc03c-a68f-461c-adbb-2c567c526e3e.png)

**Comment by mattkrick** [comment]
IMO i like scrim + extra real estate, that's how it works in macOS & ubuntu when you trigger a spotlight search.
i view spotlight as kinda like a checkout function in ecommerce-- you want to minimize distractions once they hit this point.
I'd be curious to see what Enrique thinks, too

**Comment by enriquesanchez** [comment]
Thanks for raising these issues, @nickoferrall 🙌

>1. We only show the right drawer in the Poker meeting so I assume we just want to account for the left sidebar?

You're right. No need to worry about a right side in the Group phase.

>2. Typically, we add opacity to the app around the modal to focus the user's attention on the modal. Do we want to do that here too? 

I did not think about adding a scrim but I like it now that I'm seeing it, and considering that nothing else around and behind the spotlight modal can be interacted with, it makes sense for the modal to cover the sidebar as well.

>I think we should leave space for the group title at the top but we probably don't need to leave space for the left sidebar as the user can't click the sidebar, it takes up real estate and it fits more naturally in the center imo.

This is a good idea. I'm now wondering if we should also cover the meeting controls bar. It also can't be interacted with while the modal is open. What do you think?

I think we'd still want to define a max-width and max-height for the modal, to keep the proportions and empty white space well balanced, specially when the browser's viewport is big. This will be easier to fine tune once we have something to try and test.

**Comment by nickoferrall** [comment]
> I'm now wondering if we should also cover the meeting controls bar. It also can't be interacted with while the modal is open. What do you think?

Agreed! I think something like ~80/90 viewport width and height would work well. It'll still be clear that they're on the same page but we'll use as much space as possible. 

I'll start with this approach and then, once I have a PR ready to share, we can tinker with the height & width once you have something to play with

**Comment by nickoferrall** [comment]
@enriquesanchez do we have an image asset for those lovely-looking purple lines in the empty state design? I clicked on [this Figma](https://www.figma.com/file/u5bdWUn9hxkdvS2YOYDnXU/Spotlight?node-id=144%3A538) file but it says that `Either this file doesn’t exist or you don’t have permission to view it`. If not, I'm sure I can create them using CSS

**Comment by enriquesanchez** [comment]
`<svg width="24" height="28" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17.07 19.769l-9.695 1.95.583 2.897 9.695-1.95-.582-2.897zm-1.1-8.004l-12.339-.856-.204 2.948 12.339.856.204-2.948zM9.935.895l-1.27 2.669 9.19 4.369 1.268-2.67L9.935.896z" fill="#A06BD6"/></svg>`

That's the SVG file of the purple lines. That's the "left side" in the mockup, we can flip it for the other side.
