### ISSUE TITLE
Long meeting names throw off meetings view layout

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5107]
If the meeting name or the org name is relatively long, there isn't enough space between the meeting cards. 

![meetings-view](https://user-images.githubusercontent.com/39854876/124682797-48ec4500-de91-11eb-8bf2-418634cdef42.png)

This is because the meeting cards are positioned absolutely and their top is calculated with a fixed [meeting card height](https://github.com/ParabolInc/parabol/blob/c8d057bc6861eaa9d102e8a53966fb79e55a3272/packages/client/components/MeetingsDash.tsx#L98).

Possible solutions are:

1. Pass a ref to each meeting card and use the client height to calculate the top
2. Use the meeting and org name to calculate the height of the card, e.g. if the meeting name > 22 characters, we know it's 2 lines, 44 characters = 3 lines.
3. Make each meeting card in each row the same height as the tallest card. This will be the easiest to calculate, ensures consistency but means that some cards could have a lot of whitespace. If one card on the row has a meeting name that's 3 lines long, a team name that's 2 lines long and has connected users in the `AvatarList`, there'll be 80px of whitespace

I'm working on solution 1 at the moment.

**Comment by enriquesanchez** [comment]
A few more instances of this I noticed today:

<img width="1258" alt="Screen Shot 2021-07-07 at 11 01 03 a m" src="https://user-images.githubusercontent.com/3276087/124810167-9ebefc80-df26-11eb-929c-5cde92dd025e.png">
<img width="1256" alt="Screen Shot 2021-07-07 at 11 01 29 a m" src="https://user-images.githubusercontent.com/3276087/124810171-a088c000-df26-11eb-84c4-0ea26c69a9ef.png">

**Comment by enriquesanchez** [comment]
Would it be a good idea to use CSS Grid for this view?

**Comment by mattkrick** [comment]
i don't think grids animate too well (https://blog.bitsrc.io/animating-css-grid-rows-and-columns-4b3b0997d06a), which is a huge bummer because if they did this would be a LOT easier

**Comment by mattkrick** [comment]
maybe we could absolutely position all the cards in the corner to measure them, then create a grid layout using their sizes, & then absolutely position them on top of their pseudo elements? my gut tells me there'd be a flicker between measurement & animation, but i haven't tested it

**Comment by nickoferrall** [comment]
At the moment, I'm creating several meeting card refs in `MeetingDash` and passing them to the `MeetingCard` child. Then we can calculate the height of each row and adjust their absolute position that way. 

There'll be space between the cards, which is how things were previously working, but I think it's preferable to the unevenness of a grid as it draws more attention to the active meetings. Here's a screenshot of one of the larger differences you'd see:

![using-refs](https://user-images.githubusercontent.com/39854876/124813043-0460b800-df2a-11eb-8ea9-3b76d05ca6da.png)

What do you think?

**Comment by mattkrick** [comment]
that works!

an alternative is
```ts
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap'
```

but maybe there's too much data loss if we truncate to 1 line? 
i'm cool with either solution, whatever you feel is best!

**Comment by enriquesanchez** [comment]
I'm on the fence about truncating the meeting title to one line. Visually it'll make the grid more even and pleasant, but we lose clarity.

In a similar vein, we also have the issue of some cards being taller because some have avatars and some don't. One way we can address this is by having a placeholder text when no one has joined, something like this:

<img width="1208" alt="Screen Shot 2021-07-07 at 4 17 58 p m" src="https://user-images.githubusercontent.com/3276087/124829975-e8b3dc80-df3e-11eb-9da2-be7cacbdef3f.png">

This placeholder elements should have the same height that otherwise the avatars would occupy.

**Comment by nickoferrall** [comment]
Agreed - truncating the title, perhaps combined with slightly reducing the size of the font, would certainly be the easiest thing from a dev perspective & it'd help with consistency but lose clarity. 

I like the placeholder idea although I think the cards will still end up having different heights as the title can take up 1-3 lines and the meeting team name can take up 1-2 lines
