### ISSUE TITLE
offer users the option to apply a JIRA label in Parabol when a point value is assigned

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5110]
A [user](https://app.hubspot.com/contacts/3888472/contact/28003151) 🔒 says:

> If tickets are already estimated it doesn't reflect that in Parabol. We filter those out of the query. It would be great to pull them in but still know they are pointed.

**Comment by jordanh** [comment]
More context on this bit of user feedback:

Developers on the user's team sometimes assign a point value when they create the issue and sometimes not. They have a workflow where a label is applied to mark as issue as "groomed"—i.e. that the point value has been validated by the group during Sprint Poker. When Parabol Sprint Poker completes, we don't touch the labels, so they have to manually go back in Jira and mark the issues as "Groomed"

One solution would be to provide an automation to automatically apply one or more label values if an issue receives a point value. However, a better first step would probably be to let folks do it manually via #5111 

I am going to close this one for now, and re-open if #5111 doesn't address the tension

**Comment by mattkrick** [comment]
https://github.com/ParabolInc/parabol/pull/5095 gives us the affordance to persist that kind of data within our system.
we could add story points that come from jira to the Task card in parabol. IIRC Terry already has designs for this
