### ISSUE TITLE
Poker: in-line label editing designed

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5111]
A [user](https://app.hubspot.com/contacts/3888472/contact/32435201) 🔒 says:

> There are times when I bring a whole epic in and estimate it, but if we're doing it by the sprint I want to figure out if I've done everything in the epic, too.

**Comment by jordanh** [comment]
Note this issue used to be titled:
> Jira: updating the epic label from within Sprint Poker

## AC:

A design that:
- [ ] a user can configure which integrated object (e.g. Jira ticket) labels they'd like to be able to update from within Sprint Poker
   - [ ] can read a list of all labels
   - [ ] can filter the list of labels
   - [ ] can select one or more labels to include
   - [ ] can remove previously selected labels
- during the Scope phase, a user can:
    - [ ] read the current label
    - [ ] update the label value

There probably are corner cases galore, but let's start here...

**Comment by mattkrick** [comment]
i don't want this to go stale, as i think it's a pretty great feature.
From the sounds of it, the user would like to see if the Story already has an estimate attached to it during the scoping phase.

There are plenty of edge cases here, so we'll start with something simple.

- For every jira project, we look at the fields that they have pushed to previously
- for each field, we fetch that & display it in the Scoping Search Results (in the subtitle? design TBD)
- The issue card at the top of the Estimate stage shows the current value in the integration for that dimension

**Comment by jordanh** [comment]
This is going to come back, for sure. Iceboxing for now
