### ISSUE TITLE
make it easier to find meetings that have ended

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5113]
A [user ](https://app.hubspot.com/contacts/3888472/contact/28003151) 🔒 says: 

> it's hard to find meetings that have ended 

global search or filtering on the timeline could help

**Comment by jordanh** [comment]
Scrubbed. Making this a discussion in order to collect more feedback

**Comment by mattkrick** [comment]
timeline should have a filter by team feature. we designed it, just haven't implemented
