### ISSUE TITLE
Reflect phase consistently crashing for paying user

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5119]
A paying user [emailed in](https://app.hubspot.com/contacts/3888472/contact/9033151) saying that they consistently hit a fatal bug during retros with 30-60 participants.

![bug](https://user-images.githubusercontent.com/39854876/125000960-2dab4200-e017-11eb-8784-3fe5ee614834.png)

The user mentions that they think it first occurred on June 29th and said: 

> We refresh and it goes back to that error screen again. We continuously refresh and get back to that error screen again and again. It lasts for about 10mins

I've checked Sentry and LogRocket and haven't found a relevant issue for this one yet.

**Comment by nickoferrall** [comment]
Spent more time digging into Sentry, LogRocket and trying to reproduce but I haven't found the root cause yet. I've added the user's email address to a watchlist here (#5127) so that we record all of their sessions which should help us debug

**Comment by nickoferrall** [comment]
Progress update in Slack: https://parabol.slack.com/archives/C836NA350/p1626390166174000

Main update is this watchlist PR https://github.com/ParabolInc/parabol/pull/5127 which will let us record the user's sessions in LogRocket

**Comment by jordanh** [comment]
elevating to p1

**Comment by mattkrick** [comment]
@adaniels-parabol we should call `backupOrganization` to pull all their data from the cloud so we can move them over to a private instance.

then, we may we able to do the same thing when we move them back to the cloud later.

**Comment by nickoferrall** [comment]
The user reported that they didn't have any issues in their most recent meeting following Aaron's update 🎉 

Perhaps we should keep this issue open for another week and if there are no further bug reports from the user, we close the issue? I also suggest that we change this from a p1 to a p2

**Comment by jordanh** [comment]
All is quiet on the eastern front. Closing this one
