### ISSUE TITLE
last met date not appearing accurately in Hubspot 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5121]
This [user](https://app.hubspot.com/contacts/3888472/contact/34678001) 🔒  shows a last met date in Hubspot of June 8th. 

But Domain Stats shows a last met date of June 29th. 

[Amplitude ](https://analytics.amplitude.com/login/parabol?next=%2Fparabol%2Fchart%2Fnew%2F6udzp94)agrees with Domain Stats.

**Comment by tianrunhe** [comment]
aha, this is an interesting one. I did some digging and it looks like the team started the meeting on June 8th but did not end the meeting until June 29th. We should discuss which date should be used to determine the last met date.

**Comment by jordanh** [comment]
I agree, let's discuss!

The name `lastMet` suggests to me the date that the meeting ended. However, the sales team wants to know the last time the user/account undertook a significant activity. They would want to know when the meeting was started.

Is this really an enhancement? Should we introduced a new property, `lastMeetingStarted`?

**Comment by avivapinchas** [comment]
I think `lastMet` suggests: when did they last engage in a meeting? 

To account for sync *and* sync behaviors, and for folks forgetting to 'end' a meeting, I think it should be either - the field should update when they start a meeting, and when the meeting ends. 

What we're looking for is recency, imo.

**Comment by jordanh** [comment]
Iceboxing. Suggest taking this up with the data team now!
