### ISSUE TITLE
story mapping capabilities within the Parabol app 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5124]
A [user](https://app.hubspot.com/contacts/3888472/contact/21686551) 🔒  says:

> A story mapping tool built in, to create little flows and diagrams like Vizio or Lucidchart, would be amazing

I linked to sales call videos where he goes into more details in his Hubspot contact card

**Comment by jordanh** [comment]
Scrubbed. Making discussion in order to spool up more feedback
