### ISSUE TITLE
Sprint Poker extra dimensions

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5126]
## Issue - Bug

This [user](https://app.hubspot.com/contacts/3888472/contact/8626801) 🔒 reports new custom dimensions showing up during sprint poker and they did not create them.

> We are facing a bug with the new dimensions feature in Poker Estimation.
> Even though we haven't added any custom dimensions, we have 2 additional dimensions showing up while estimating.
> 
> It's splitting people's focus.

Meeting ID's: https://action.parabol.co/meet/4ZhShbt8SA/estimate/1
                        https://action.parabol.co/meet/510mhTr9Zu/estimate/1

HS ticket: https://app.hubspot.com/contacts/3888472/ticket/477043763

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tiffanyhan** [comment]
i can reproduce this bug locally. in the db, the extra template dimensions all have `removedAt` timestamp. however, the dataloader `templateDimensionsByTemplateId` does not exclude removed dimensions. fix should be trivial.
