### ISSUE TITLE
add audio cue when timer runs out 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5130]
A [user](https://app.hubspot.com/contacts/3888472/contact/17542651) 🔒  writes:

> When the timer stops it doesn't do anything. An audio cue would be nice.

This is related to [issue 5010](https://github.com/ParabolInc/parabol/issues/5010)

**Comment by jordanh** [comment]
AC
- [ ] design exploration for adding sound when time expires

EE
- [ ] 16 hours

**Comment by mattkrick** [comment]
my vote is for this sound: https://vm.tiktok.com/ZMd7Guy9Y/
