### ISSUE TITLE
Add tooltip to long agenda item names

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5131]
If the agenda item name is too long to show the entire name, display a tooltip on hover so that users can still read the agenda item.

![tooltip](https://user-images.githubusercontent.com/39854876/125484320-9e2af5f3-67f6-4944-9960-e3bbe0696532.png)

### AC:

- [ ] If the agenda item name requires an ellipsis, show a tooltip when hovering over the text of the name

**Comment by jordanh** [comment]
Would love to tackle this one the same time we do #4600
