### ISSUE TITLE
GitHub Action: Guarantee base branch's migration files are all less than branch

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5142]
Now that we have > 1 backend engineer, it's important that our migrations stay linear.
I think the easiest way to do this is a github action that does the following:

AC
- [ ] checkout the base branch
- [ ] goto packages/server/postgres/migrations & pick the last file in the directory. extract the timestamp & call it BASE_TIMESTAMP
- [ ] checkout the PR branch
- [ ] pick the last file in the directory again. extract the timestamp PR_TIMESTAMP
- [ ] assert(BASE_TIMESTAMP <= PR_TIMESTAMP)
- [ ] this re-runs whenever something gets pushed to master
- [ ] this causes a check to fail in the pending PR

Let's first see if something like this already exists in the npm/yarnpkg ecosystem.

I think this probably looks like a single-file script that gets called by npm scripts. Once working, we can extract it into its own package & publish it free for the world.

@tianrunhe i think you may have bumped into this when deploying today. Do you think this would solve the problem?

Estimate: 8 hours

**Comment by tianrunhe** [comment]
I was thinking even more automated way. Rather than a GitHub action that detects the discrepancy and then prompt dev to fix it themselves, how about a git hook that just fix the issue for you upon commit or push? Logic follows all the steps you described but if the assertion fails, we rename the migration file in PR branch to `[BASE_TIMESTAMP+1]-migrationName.ts`. What do you think? Autopilot scares you?😂

**Comment by jordanh** [comment]
@BartoszJarocki curious for your thoughts. I'll look to have consent on AC before prioritizing

**Comment by mattkrick** [comment]
i would LOVE to auto rename.
the only reason i'd opt against it is that means your local DB will be borked & you won't be able down-migrate because the migration tool doesn't recognize the name of the renamed migration. if you can solve that case i'm in!

**Comment by tianrunhe** [comment]
Oh I see... yeah that makes sense!

**Comment by mattkrick** [comment]
looks like `20210629164700-task-hash.ts` didn't run in prod, which was probably a side effect of this. thankfully nothing broke! just a little scary :grimacing:
