### ISSUE TITLE
Polls implementation: [Frontend] Adding a poll

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5145]
This issue is part of **Polls implementation: EPIC #5147**

The new polls feature allows users to create a multiple choice question in a discussion thread, and lets meeting attendees vote. 

- [Please watch this Loom for a quick overview](https://www.loom.com/share/3ed5d71323494b24bb850ca55d4ebdcc?sharedAppSource=team_library).
- [The Figma source file can be found here](https://www.figma.com/file/D25gVH1t2alUiOdYNs5Owo/Multiple-content-input-types?node-id=518%3A19375).

Feel free to ping me for questions or comments.

# The 'Add a poll' action

<img width="848" alt="Screen Shot 2021-07-15 at 4 47 51 p m" src="https://user-images.githubusercontent.com/3276087/125862228-8a95e3ec-8bb5-4bf0-9da1-0a71195500b7.png">

- [ ] A new 'Add a poll' option is added to the 'action bar' below the comment field in a discussion thread.
- [ ] Both actions are evenly spaced and centered in their container.
- [ ] 'Add a poll' has the same styles that its sibling 'Add a task'.
- [ ] 'Add a poll' uses `poll` (outlined) from the Material Design icon library.

**Comment by BartoszJarocki** [comment]
# Adding a poll

## Backend
### SQL 
To insert and fetch polls we need 2 queries
1. `upsertPollQuery` - inserts, on conflict, updates the `Poll` table
2. `getPollWithOptionsByDiscussionIdQuery` - will return joined `Poll` and `PollOptions` tables

### Mutations
1. `CreatePollMutation` 

	Data model
	```
	const PollOptionInput = new GraphQLInputObjectType({
	  name: 'PollOptionInput',
	  fields: () => ({
		title: {
		  type: GraphQLNonNull(GraphQLString),
		  description: 'Poll option title'
		}
	  })
	})

	const CreatePollInput = new GraphQLInputObjectType({
	  name: 'CreatePollInput',
	  fields: () => ({
		title: {
		  type: new GraphQLNonNull(GraphQLString)
		},
		meetingId: {
		  type: new GraphQLNonNull(GraphQLID),
		  description: 'foreign key for the meeting this was created in'
		},
		discussionId: {
		  type: new GraphQLNonNull(GraphQLID),
		  description: 'foreign key for the discussion this was created in'
		},
		pollOptions: {
		  type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(PollOptionInput)))
		}
	  })
	})
	```

### Queries
1. Modify `resolveThreadableConnection` to include polls as well
2. Modify `Threadable` type to include the poll type
```
const Threadable = new GraphQLInterfaceType({
  name: 'Threadable',
  description: 'An item that can be put in a thread',
  fields: threadableFields,
  resolveType: ({status}) => {
    return status ? Task : Comment //TODO: add poll handling
  }
})
```

## Frontend 
1. Adding `poll` as a new `threadable` type
	 `DiscussionThreadables = 'task' | 'comment' | 'poll'`
 
2. Adding a `Create a poll` button
	Similarly to the `Create a task` button, the `Create a poll` button will live in `DiscussionThreadInput`

	```
        {isActionContainerVisible && (
          <ActionsContainer>
            {allowTasks && (
               <AddTaskButton dataCy={`${dataCy}-task`} onClick={addTask} disabled={!canCreateTask} />
            )}
            {allowPolls && (
               <AddPollButton dataCy={`${dataCy}-poll`} onClick={addPoll} disabled={!canCreateTask} />
            )}
          </ActionsContainer>
          )}

	```

3. Adding `Poll` component
	I think it'd be best to design `Poll` as a compound component. From a high-level perspective, `Poll` is very similar to the native `select` element, let's take a look.
	Normal select looks the following way
	```
	<select>
	  <option value="value1">key1</option>
	  <option value="value2">key2</option>
	  <option value="value3">key3</option>
	</select>
	```
	`Poll` is pretty much the same from this perspective. There's a parent `Poll`, there is a list  `PollOption` that users can select. I imagine `Poll` as something like that

	```
		<Poll>
		  <PollOptions>
			{pollOptions.map((option) => <PollOption key={...} title={option.title} isSelected={...} />)}
		  </PollOptions>
		  {!isStarted && 
			<CreatePollButton>
				Start
			</CreatePollButton>
		  }
		</Poll>
	```

	Polls will have to be fetched along with other `threadables` and displayed in `DisucssionThreadList`. In `ThreadedItem` we will have another type `__Poll` and a component responsible for displaying a poll, `ThreadedPollBase` where the `Poll` component will be used. 

4. Showing `X is creating a poll...`
	There are 2 possible solutions 
	1. Modify edit commenting - it'd need to be more generic ie. EditDiscussion(...) which would take a param indicating if it's a poll being created or a comment

		Pros
		- easier to implement

		Cons
		- would be a messy solution if we ever decide to show a poll placeholder instead of just `X is creating a poll`



	2. Implement the same flow as for tasks ie. add a poll immediately (without any data) and then keep updating the poll when the user starts adding titles and options. 

		Pros
		- seems to be the correct solution, it's only related to the poll itself
		- we don't touch any other implementations

		Cons
		- way more cases to handle, for example, someone starts adding a poll, and then the browser crashes
		- poll has can have multiple inputs so it's not an option to remove the poll when it loses the focus (maybe I'm wrong?), and we _don't_ have any option to delete the poll if I see correctly (is that a missing piece on the designs?)

   I'd personally go with the second one but I'm not 100% sure, any thoughts @mattkrick? 🙏 

@mattkrick I'd really appreciate it if you could check how does it look to you, thank you!

**Comment by mattkrick** [comment]
Whoa, looks great! 

> upsertPollQuery

if you're still considering using an auto-generated sequence as an ID you'll need to break this apart into insert and update queries
 
>  CreatePollInput

- remove `meetingId`, that is a foreign key of the Discussion, ie given a discussionId we can determine the meetingId (if any)
- add `threadSortOrder` so we know where deterministically to insert the poll in the thread, similar to addComment

> Showing X is creating a poll...
-  IMO, the first seems cleaner. Keep the poll & poll options saved locally until they hit submit. You're correct, we do have a little weirdness in our data schema. should the "commenting" prop live on the discussion or should it live on the threadable? For comments, it can't live on the threadable because that hasn't been created yet. for tasks, it can live on the object because an empty Task is created immediately even before you hit submit. I'd argue that Polls should function more like Comments because the way Tasks is very error prone, especially if someone tries to delete an empty one. My advice is change `editCommenting` to `editDiscussion(isEditing: boolean, discussionId: string, threadableType: 'task' | 'comment' | 'poll')`

**Comment by BartoszJarocki** [comment]
@mattkrick thank you! 

> if you're still considering using an auto-generated sequence as an ID you'll need to break this apart into insert and update queries

Hmmm, let's make sure we're on the same page. There are 2 ways of using the generated sequence:
`column_name type GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY[ ( sequence_option ) ]` 
If I understand correctly, using `GENERATED ALWAYS` is a problem when updating as postgres will throw an error
```
The GENERATED ALWAYS instructs PostgreSQL to always generate a value for the identity column. If you attempt to insert (or update) values into the GENERATED ALWAYS AS IDENTITY column, PostgreSQL will issue an error.
```
Another way is using `GENERATED BY DEFAULT` which _should_ work just fine when updating the existing row
```
The GENERATED BY DEFAULT also instructs PostgreSQL to generate a value for the identity column. However, if you supply a value for insert or update, PostgreSQL will use that value to insert into the identity column instead of using the system-generated value.
```
So I planned to use `GENERATED BY DEFAULT`. I hope I'm not missing anything here so I'd appreciate your input @mattkrick  😅 Thank you!


> remove meetingId, that is a foreign key of the Discussion, ie given a discussionId we can determine the meetingId (if any)

makes sense! btw, is there any case where `meetingId` could be null? 

> add threadSortOrder so we know where deterministically to insert the poll in the thread, similar to addComment

will do that, thank you! 

> IMO, the first seems cleaner. Keep the poll & poll options saved locally until they hit submit. You're correct, we do have a little weirdness in our data schema. should the "commenting" prop live on the discussion or should it live on the threadable? For comments, it can't live on the threadable because that hasn't been created yet. for tasks, it can live on the object because an empty Task is created immediately even before you hit submit. I'd argue that Polls should function more like Comments because the way Tasks is very error prone, especially if someone tries to delete an empty one. My advice is change editCommenting to editDiscussion(isEditing: boolean, discussionId: string, threadableType: 'task' | 'comment' | 'poll')

oh yeah, the second option is definitely more complex and error-prone. Will move forward with a suggested solution. I appreciate the input!

**Comment by mattkrick** [comment]
> GENERATED BY DEFAULT

This means we _could_ pass in a unique int as an ID, but how would we know which int to pass in? if we have 3 node instances all trying to guess which int come next, then some will fail because they'll pick an ID that already exists, so it's best to let the DB pick the ID. The reason why we use `BY DEFAULT` is so we can perform backups/restores easily when the ID is deterministic. 
If you let the DB pick the ID, then you can't use that primary key to determine `ON CONFLICT` 

> is there any case where meetingId could be null?
 
Today meetingId is guaranteed nonnull: https://github.com/ParabolInc/parabol/blob/eea39f8b904fbd9fe077f04325fab72656425244/packages/server/graphql/types/Discussion.ts#L29. In the future, this logic may change, but we can worry about that later

**Comment by BartoszJarocki** [comment]
@enriquesanchez I'd remove two acceptance criteria:
- [ ] Pressing 'Add a poll' creates a new poll object in the discussion thread.
- [ ] Focus moves to the new poll object
 as they're related to creating the poll object itself which is related to: https://github.com/ParabolInc/parabol/issues/5146

This task would be then by simply adding a button 🙏

**Comment by enriquesanchez** [comment]
@BartoszJarocki Sounds good! Thanks for pointing it out 🙌
