### ISSUE TITLE
Polls implementation: EPIC

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5147]
This is an implementation issue for #4990.

![image](https://user-images.githubusercontent.com/3276087/125862136-2e02a9ff-a5b0-4629-a2d9-251ce2b99d9d.png)

The new polls feature allows users to create a multiple choice question in a discussion thread, and lets meeting attendees vote. 

- [Please watch this Loom for a quick overview](https://www.loom.com/share/3ed5d71323494b24bb850ca55d4ebdcc?sharedAppSource=team_library).
- [The Figma source file can be found here](https://www.figma.com/file/D25gVH1t2alUiOdYNs5Owo/Multiple-content-input-types?node-id=518%3A19375).

Feel free to ping me for questions or comments.

# Sub-issues
- [x] #5203
- [x] #5145 
- [x] #5315 
- [x] #5146
- [x] #5441 
- [x] #5148
- [x] #5442
- [x] #5149
- [x] #5443 
- [x] #5150
- [x] #5444 
- [x] #5151
- [x] #5152
- [x] #5153
- [x] #5478

# Additional, related tasks
- [x] #5440  

# Disucssions
 - #5411

**Comment by BartoszJarocki** [comment]
Open questions
1. How to delete a poll that is currently being created?

**Comment by enriquesanchez** [comment]
>How to delete a poll that is currently being created?

@BartoszJarocki I think we should mimic the same behavior we currently have for tasks.

While it's being created:
- If I just pressed 'Add a task' and I haven't typed anythig, pressing <kbd>ESC</kbd> removes the task object.
- If I have already entered some text, then I have to go to the `...` menu and remove it from there ('Set as archived'). In the case of polls, we could say instead 'Delete poll'.

**Comment by BartoszJarocki** [comment]
@enriquesanchez thank you! That makes sense. The reason I'm asking is, there's no '...' on the designs when you're creating a poll so I assume, it should be there all the time, am I right? Also, the difference between poll and task is poll is much harder to remove when losing focus (it has many inputs, for example, we can't remove poll if someone uses a tab to move focus to the 'Start poll' button so I think there are too many edge cases to handle it that way). To summarize, can we do the following?
1. Show `...` button all the time so user can remove the poll anytime
2. If there's nothing added in the poll, hitting ESC will remove the poll
3. We don't remove the poll when a poll is losing focus (it has too many focusable elements to handle that without any hiccups)

Also, one more thing about poll options itself, how can I remove the empty poll option while adding a poll?

@enriquesanchez I'd appreciate it if you could take a look 🙏

**Comment by enriquesanchez** [comment]
>there's no '...' on the designs when you're creating a poll so I assume, it should be there all the time, am I right?

@BartoszJarocki Yep. Here's a mockup with the `...` menu shown:

<img width="486" alt="Screen Shot 2021-09-29 at 4 12 15 p m" src="https://user-images.githubusercontent.com/3276087/135349240-dcbe1a74-5e35-470b-a416-bca2ed3677c7.png">

I like your 3 suggestions, I think they all make sense.

>how can I remove the empty poll option while adding a poll?

Can you expand a little more on this question?

**Comment by enriquesanchez** [comment]
>Of course, I'm open to any solutions, just wanted to lay down some possible downsides. Let me know what do you think 

@BartoszJarocki  Ah, these are great points. I agree it'll be best to show it all the time 👍

>There's an empty, third poll option added. How can I remove it? 

Ah, I see what you mean now. My idea was that because only choices 1 and 2 are required for a poll to be created, choices 3 and 4 are optional and thus it's OK if they are left empty. You can get an idea of how this feels if you try creating a poll on Twitter. 

We can make this a bit more obvious if we change the label/placeholder text of the choices 3 and 4 to also say that they are optional: "Add choice 3 (optional)..."

**Comment by BartoszJarocki** [comment]
@enriquesanchez thank you, it's all clear now! I'll create some tickets to align with this behavior. 👌

**Comment by jordanh** [comment]
Iceboxing
