### ISSUE TITLE
Ability to check off icebreakers

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5155]
## Issue - Enhancement

This [user](https://app.hubspot.com/contacts/3888472/contact/21953851) 🔒  would like a way to check off icebreakers with separate teams to keep the same ones from coming up again. The icebreaker is an important part of their retro's and it's difficult to keep track of which ones have been done recently especially across multiple teams.

The way I see this working is once an icebreaker comes up for a team it doesn't come up again until all of the other questions have been cycled through. If a team doesn't like a particular icebreaker there could also be an option to check "don't show me this again"

**Comment by mattkrick** [comment]
How i see working is every team has an icebreaker "pool" with 100 questions. each time we show them an icebreaker we remove it from the pool until there are none left and we just refill the pool. not too challenging & probably worth the effort

**Comment by ackernaut** [comment]
This could be a potential designer BP
