### ISSUE TITLE
Error: Redis took too long to respond

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5157]
Sentry error first appeared on the scene a month ago and has affected 864 users at the time of creating this issue (16th July).

It's not a fatal error but we do have a paying customer reporting that the reflect phase of their retro initially stops submitting reflections and then stops working entirely (https://github.com/ParabolInc/parabol/issues/5119). 

If you change the `MAX_TIMEOUT` to a smaller value, you can reproduce similar behaviour where the reflections are disappearing and the page can crash with a <100ms timeout limit (https://github.com/ParabolInc/parabol/blob/bfed594b1f8f053ea628a3c541502ddd9b47b374/packages/server/utils/PubSubPromise.ts#L5). 

https://sentry.io/organizations/parabol/issues/2436528767/?referrer=github_plugin

```
Error: Redis took too long to respond
  File "./packages/server/utils/PubSubPromise.ts", line 45, in Timeout._onTimeout
    reject(new Error('Redis took too long to respond'))
```

**Comment by nickoferrall** [comment]
After discussing with Matt, this is most likely an issue with the GraphQL executor rather than Redis. Redis is just the messenger saying that it's taken 10+ seconds to receive a response from the GraphQL executor

**Comment by jordanh** [comment]
I recall @tiffanyhan investigated and fixed the the Gql Exector's ability to report to sentry. Is it working? Are we seeing errors from this service?

**Comment by tiffanyhan** [comment]
sentry reports errors but not necessarily timeouts i don't think.

i recall that's what the graphql performancetracer that bruce was working on was supposed to expose-- https://github.com/ParabolInc/parabol/pull/4843 but that one ran into some unforeseen blockers didn't it?

**Comment by tianrunhe** [comment]
We can do some testing in staging by:
1. reducing the timeout to a small number so we can easily reproduce the Redis timeout
2. enabling app tracing by setting ``DD_TRACE_ENABLED='true'`` to see which set of GraphQL queries are taking long to execute

**Comment by mattkrick** [comment]
this can cause a page crash??
that is absolutely wonderful! let's come up with a way to gracefully handle these errors on the client (if that requires adjusting the payload sent from the server that's fine too). 
Let's treat this issue as the triage & call it complete.

I'll create a new issue to handle that case better
