### ISSUE TITLE
When timer expires, prompt for readiness

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5166]
A [former user](https://app.hubspot.com/contacts/3888472/contact/38441701) 🔐 found our ready button a bit too opaque and prefers the explicit prompting of [Lean Coffee Table](https://www.leancoffeetable.com/):
> When I hit Ready on the participant side, absolutely nothing happens on the facilitator screen. 
>
> I need to see a working copy to be sure, but I'm not sure if it'll work as well as active prompting. LCT's approach to this needs no explanation, people react instinctively when they get a BIG prompt with thumbs up, down and sideways - I just need to get them to LCT. This is significant for new faces at the meeting. With this approach I have to explicitly remind everyone to press the button when they are ready to move on to the next topic.

The suggestion from this user is to have the expiring timer prompt of folks need more time. If they say no, then they are marked as ready

Opening this as a discussion to spool more feedback

**Comment by mattkrick** [comment]
That's kinda fun.
Maybe after 50% of participants have marked "ready" then the button becomes "I need more time" and it counts down so if you don't hit it it checks ready for you.
