### ISSUE TITLE
Retro: free-form add topics

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5168]
[A user](https://app.hubspot.com/contacts/3888472/contact/38441701) 🔒 writes:

> I think my biggest blocker is that it is not possible to go back and add votes and topics. This comes up a lot because we frequently have late-joiners on longer meetings, or things come up that we want to split to a new topic in order not to derail the discussion. 

I think the idea here would be to make the Discuss agenda work similarly to the Check-In agenda and simply add an input field at the end. I'l validate this

**Comment by jordanh** [comment]
Same user replied:
> Ahh.. Sure, that would be fine. I don't think lack of voting is a deal breaker.

**Comment by mattkrick** [comment]
i'd like to avoid this if possible as it removes a guard rail for having a great meeting. reflections = buy-in & if someone creates a new topic they're essentially saying let's talk about my thing even though no one, including myself, mentioned it.
