### ISSUE TITLE
Bug: fix sort order

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5169]
## Issue - Bug

Here's a simple one. When I want to assign a user to a task, I'd like the usernames to be in sorted alphabetical order (without regard to case), so that I can quickly find the person to assign the task to

Today, you'll note 'matt' is sorted after all of us upper-case letter users:

![image](https://user-images.githubusercontent.com/103000/126084368-ef737638-142f-4155-a414-2a30c9e6371e.png)

### Acceptance Criteria (optional)
   - task assignment sort updated to ignore case

**Estimated effort:** 1 hour

**Comment by tianrunhe** [comment]
~I think @mattkrick should rename himself to match with his team members~

**Comment by mattkrick** [comment]
fun fact-- the reason i'm lower case with an emoji is to test for this and proper utf-8 to unicode support :nerd_face: 
and y'all just thought i was lazy with the shift key :wink:
