### ISSUE TITLE
DB Migration: Notifications: Phase 1: Create table

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5172]
The first step to migrate notifications to postgres is to create a table in postgres.

AC
- [ ] a postgres migration exists that creates a Notification table that has all the same fields & indexes as the rethinkdb one
- [ ] all foreign keys that have primary keys that exist in postgres are treated as references (ie userId and teamId are treated as refs because User & Team exist in PG, whereas orgId is just a string because Organization doesn't exist in pg yet)

Estimate: 6 hours

**Comment by jordanh** [comment]
Keeping open
