### ISSUE TITLE
DB Migration: Notifications: Phase 1: Write to PG table

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5173]
Predecessors: #5172

Now that we have a Notification table in postgres, we need to start writing to it.

AC
- [ ] each call to write to the rethinkdb Notification table is updated to additionally write to the postgres notification table 
- [ ] the writes are wrapped in a try/catch because any updates will likely fail because the row doesn't exist yet

Estimate: 8 hours

**Comment by jordanh** [comment]
Keeping open
