### ISSUE TITLE
DB Migration: Notifications: Phase 1: Migrate rethinkdb data to pg

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5174]
Predecessors #5173

Now that a pg table exists and we're writing new records to it, we can copy all the existing rethinkdb data over to it.

AC
- [ ] A postgres migration exists that fetches rethinkdb data from the Notification table in batches of 3000 rows. it then writes that data to postgres IIF the data does not already exist. if it doesn, it does nothing.

Estimate: 6 hours

**Comment by jordanh** [comment]
Keeping open
