### ISSUE TITLE
DB Migration: Notifications: Phase 1: Resolve inequalities

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5176]
Predecessors: #5175 

Now that we have a way to check deltas between the 2 DBs, we should fix those deltas.
This issue exists to create extra issues.

AC
- [ ] When a delta is discovered, a new issue is created to triage & fix the delta.
- [ ] The first part of the new issue describes the delta (fields affected, possible causes, etc)
- [ ] The second part of the new issue discusses a proposed plan of attack and includes an estimate of no greater than 8 hours
- [ ] Help to triage is requested if a PR to resolve the delta is not submitted within 8 hours of discovering the delta

Estimate: 2 hours to check the equality & create a new issue

**Comment by jordanh** [comment]
Keeping open
