### ISSUE TITLE
DB Migration: Notifications: Phase 3: Stop rethinkdb reads/writes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5179]
Predecessors: #5178

Now that data is being written to both rethinkdb & postgres & reads are coming from postgres, we can safely remove writes to rethinkdb

AC
- [ ] writes to rethinkdb Notification table are removed
- [ ] the Notification type is removed from `RethinkSchema` in rethinkDriver.ts

Estimate: 8 hours

**Comment by jordanh** [comment]
Going to keep this one open, cause, you know, we do have to do this
