### ISSUE TITLE
Spotlight: Support drag & drop for source to result

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5185]
Predecessor: #5182

Now that the results are populated, we should allow the viewer to drag the source reflection at the top onto a group.
See https://github.com/ParabolInc/parabol/issues/5105 for more info

AC
- [ ] can drag the source reflection onto any group in the results space
- [ ] after dropping on a group, it animates being dropped
- [ ] after the animation, the modal animates closed

Estimate: 4 hours

**Comment by mattkrick** [comment]
**Story Points: 5**
  [See the discussion](http://localhost:3000/meet/7fE8wObWGA/estimate/1) in Sprint Poker `#2`

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by mattkrick** [comment]
**Story Points: 8**
  [See the discussion](http://localhost:3000/meet/7fE8wObWGA/estimate/1) in “Sprint Poker `#2`”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by jordanh** [comment]
**Story Points: 34**
  [See the discussion](https://action.parabol.co/meet/7By0K1Cj6w/estimate/14) in “Sprint `#89` Scoping”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
