### ISSUE TITLE
allow unlimited teams in a single org on personal plan 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5188]
Currently, we have a limit of 10 teams in one org on our personal plan. 

 It makes billing a lot simpler if we can merge teams before an upgrade to Pro. See [this notion doc](https://www.notion.so/parabol/How-to-Merge-Teams-into-One-Org-Upgrade-to-Pro-cb0b75a961b9421bbbd5d98b321d2a08). 🔒  

Usually, prospects have more than 10 teams to merge, so it would be great if we could take off the ten team limit. There have not been many problems caused by companies having more than 10 teams in one org.

**Comment by mattkrick** [comment]
this limit should only occur when users add an 11th team themselves, not when we use our super powers to merge orgs. that said, i don't see much harm in removing the limit anyways

**Comment by drewhousman1010** [comment]
You are right that it's different when we use our super powers, but it still causes teams that login after the merge to see a big alert that says they have an unpaid invoice.

**Comment by jordanh** [comment]
This needs clear acceptance criteria and estimated effort before we may proceed to get any work added to the backlog
