### ISSUE TITLE
Meeting summary not showing reflections if meeting was finished before discussion phase

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5191]
## Issue - Bug

Meeting summary will not show reflections if the meeting was finished before going to discuss phase.
Related discussion: https://github.com/ParabolInc/parabol/pull/5137#issuecomment-881440603

### Acceptance Criteria (optional)
- [ ] Meeting summary correctly shows all the reflections even if the meeting has finished before the discussion phase

**Comment by acressall** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/13750301) has run into this issue when trying to export to CSV. When clicking the "export to CSV" button, nothing occurs. Even though the retro had 58 reflections and 34 topics, nothing is displayed in the meeting summary.
