### ISSUE TITLE
"Load more" button doesn't work on billing tab

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5195]
## Issue - Bug

A [customer](https://app.hubspot.com/contacts/3888472/deal/424446033) 🔒  reports the load more button on the billing page does not work. I was able to reproduce this issue in production on the Parabol org. This is the button I'm referring to:

<img width="646" alt="Screen Shot 2021-07-20 at 1 56 17 PM" src="https://user-images.githubusercontent.com/60167404/126372457-4988086f-df17-4ae7-974b-894fa0e791e2.png">

This prevents customers from being able to access past invoices beyond the 2 most recent and the upcoming one.

**Comment by jordanh** [comment]
Thank you for opening this one. Assigning p2 to get fixed sooner rather than later

**Comment by jordanh** [comment]
I bet we'll come back to this when we refactor our admin section...
