### ISSUE TITLE
When a task changes teams, make sure there's no conflicting integrationHash

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5200]
We want to guarantee a single source of truth for integrated tasks, or at least get close.
This isn't possible because multiple teams could refer to the same jira issue.

So, what if team A & team B both import jira issue C onto their respective teams to estimate story points on?
I think this should be permitted.
What if a user moves that issue from team b onto team a & now there's a dupe? what if it's archived there? or private?

i think we keep it simple.

AC
- [ ] Allow to change teams for integration tasks
- [ ] if issue B is moved to to team A & they refer to the same jira issue, then issue A gets deleted
- [ ] after A is deleted, then we continue to move B over
 
that will solve the case for dupes, archived, and private

Estimate: 4 hours

**Comment by mattkrick** [comment]
nice find! i forgot switching teams was already locked down for integrated tasks. that makes me less worried about this issue.
i'll leave it up to you, we can either de-prioritize this issue & tackle it later or if you've already made progress on it you can enable switching teams for integrated tasks in the UI.

in the future we'll show both the team & the user assignment on the task card, we just haven't designed that yet.

**Comment by Dschoordsch** [comment]
I only spent little time figuring out how this situation could be triggered. I think we should de-scope this and tackle it later.

**Comment by jordanh** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/7By0K1Cj6w/estimate/2) in “Sprint `#89` Scoping”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
If a task B is private and moved from team B to team A, it will be private in team A regardless of whether or not the task A referring to the same integration task C was private, i.e. the visibility is reduced afterwards.

**Comment by Dschoordsch** [comment]
There is a different issue when moving an integration task to another team: What do we do when the owner does not have set up the integration for the target team?
I will add a dialog: "You did not set up GitHub for Team B yet, would you like to do so now? Yes - No" which starts normal flow to add the integration.
