### ISSUE TITLE
User tier is not re-computed after leaving a team

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5202]
## Issue - Bug

While investigating https://github.com/ParabolInc/parabol/issues/5193, I've found this bug:

To reproduce:
1. User A is in a personal tier org/team. User B is in a pro tier org/team
2. User B invites User A to join his/her team
3. Now User A's tier is correctly updated to `pro`
4. User B kicks User A out from his/her team
5. Now Use A is only in his/her own personal tier team so his/her tier should be `personal`. However, his/her tier remains at `pro`.

### Acceptance Criteria (optional)
- [ ] When user left a team/org, his/her tier should be re-computed.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
Good edge case!

**Comment by jordanh** [comment]
@mattkrick notes that this should only happen if a person leaves an org
