### ISSUE TITLE
Designed: poker shows existing estimations when scoping items to estimate

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5208]
Here’s the [background in Slack](https://parabol.slack.com/archives/C0161UFBM6W/p1627055443180100?thread_ts=1627054678.178400&cid=C0161UFBM6W) 🔒 

> what do you think about showing story points in the scoping area search results?

> i'm not sure all the use cases, but i saw that feedback crop up a couple times. like maybe they did a first pass in jira & they want to get the team in on it for a do over? or they only want to see the issues that don't have points?

> i think it'll need its own pass at UI to make it look right. we gotta have the UI say "hey, here's the search results straight outta jira. here's the points that live in jira. but we'll fix those soon, don't you worry"

### Acceptance criteria
- Designed concepts (sketch / Figma) that show when items may or may not have an existing estimation; but it’s clear that these items can be included for new estimations in the Poker Scoping activity, to be reviewed by the Product team
- Drafted an implementation issue to be reviewed for the backlog that reflects the design we’re going with

### Estimated effort
- 12 hours

**Comment by mattkrick** [comment]
:tada: 
- we'll probably only be able to do this if we know which field they're exporting to (e.g. Story Points, Story Point Estimate, something else?) that is to say, the points might not show up for their very first meeting if they use a custom field
- if the issue already exists in parabol, we can use the estimate from the previous meeting, else we can grab the estimate from jira itself

**Comment by jordanh** [comment]
This is pretty damned interesting. I bet this one will come back. Maybe, even for our own team
