### ISSUE TITLE
addMissingJiraField refactor args

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5212]
As estimates become a first-class entity in our system, it's possible that we change jira fields outside of a meeting.
To do that, we need estimate-based mutations to work outside of a meeting context.

AC
- [ ] addMissingJiraField accepts `taskId, dimensionName` instead of `meetingId, stageId`

Estimate: 3 hours

**Comment by jordanh** [comment]
iceboxing for real this time
