### ISSUE TITLE
bundle rethink & pg -- restore

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5218]
Separated from #4989

## Issue - Enhancement
  - [x] restore job added to the postgres pipeline in gitlab (currently in progress by Aaron)
  - [x] trigger added in gitlab to invoke postgres restore job programmatically via API (see if we can trigger just a job instead of a whole pipeline)
  - [x] `pg-restore.sh` added, which triggers postgres restore job
 
Additionally:
  - [ ] we should trigger production pg backup on production deploy, as we already do this for rethink
  - [ ] update release playbook

**Estimated effort:** 5 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tiffanyhan** [comment]
gitlab job: https://gitlab.com/parabol1/action-devsecops/digitalocean-postgres/-/merge_requests/10

**Comment by adaniels-parabol** [comment]
@tiffanyhan great job!

**Comment by adaniels-parabol** [comment]
@tiffanyhan feel free to merge over in Gitlab. I'm moving this issue to done.

**Comment by tiffanyhan** [comment]
thanks y'all for reviewing!

**Comment by tiffanyhan** [comment]
@adaniels-parabol were you able to take a look at https://github.com/ParabolInc/action-devops/pull/74 as well? just wanted to double check since the work was in more than one place
