### ISSUE TITLE
Meeting phase reminders: Phase deadline notification

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5222]
This is a sub-issue for #4994. 

- [Figma file for reference.](https://www.figma.com/file/13hfEQOWIsaWc1pqfhoEnd/Schedule-phase-reminders?node-id=125%3A527)

# Phase deadline notification

![image](https://user-images.githubusercontent.com/3276087/127064487-3820985c-dd8f-4d43-964d-73c5d6118974.png)

AC:

- [ ] When a time limit has been set, we display a notification at the top of the phase area where we also display the timer count down. This notification should indicate the deadline: `Deadline for this phase is May 5 at 3:00PM`.

EE: 4 hrs

**Comment by jordanh** [comment]
@enriquesanchez will this become an implementation issue or a further design issue? Either way could you add EE and AC please?

**Comment by enriquesanchez** [comment]
@jordanh This is an implementation issue, part of #4994. Forgot to add the AC label and the EE. Just fixed that here and in the sibling issues as well 👍

**Comment by mattkrick** [comment]
At what width do we show this? I'm not sure this will work for mobile

**Comment by enriquesanchez** [comment]
> At what width do we show this? I'm not sure this will work for mobile

@mattkrick This was [brought up before here.](https://www.figma.com/file/13hfEQOWIsaWc1pqfhoEnd/Schedule-phase-reminders?node-id=92%3A0). The last iteration of the message does fit nicely on mobile.

**Comment by jordanh** [comment]
This is going to come back. Mark my words
