### ISSUE TITLE
Unpaid invoice modal randomly shows on Enterprise account

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5245]
## Issue - Bug

This [account](https://app.hubspot.com/contacts/3888472/deal/2827746686) 🔒 is an Enterprise tier customer. They had an invoice that went unpaid since January, I switched the billing contact in Stripe at their request and they paid the outstanding invoice. Somehow the unpaid invoice modal was activated on their account (I didn't do this manually) and they couldn't access any of their teams even after paying the invoice. I'm afraid this could happen to other customers without us knowing.

Is there something wrong with how Stripe and Parabol are communicating related to Enterprise invoicing?

**Comment by jordanh** [comment]
I believe if an invoice is unpaid for some number of days we'll lock the account. If the invoice _was_ paid and the lock out occurred, this would certainly be a bug. Marking as p1 to prioritize dicussing/triaging

**Comment by jordanh** [comment]
AC
- Triage and fix or,
- Triage and open new

EE
- 6 hours

**Comment by tianrunhe** [comment]
I noticed the `stripeSubscriptionId` is null for this organization so there's definitely something out of order between Parabol & Stripe.

**Comment by tianrunhe** [comment]
Theory now: customer had a few failed payment which triggers our mutation to set `isPaid` to `false`. They then paid off in Stripe but looks like it's not through a ordinary workflow? The invoice in Stripe reads "Invoice was marked as paid outside of Stripe" so I suspect our app did not get notified for this payment, hence never reset the `isPaid` property.  
  
Next step is to dig into how they paid and if that's an edge case we didn't catch.

**Comment by mattkrick** [comment]
Here are some things that make this case unique:
- The user is on the enterprise tier
- Their invoice start date was Jan 14, but they paid on July 28
- There is no billing leader email
- stripeFailPayment got called on an enterprise invoice (this has never happened before & we don't currently support this flow)

Proposed new flow:
- in stripeSucceedPayment, before updating the invoice, update the org so org.stripeSubscriptionId = invoice.subscription

Estimate: 2 hours
