### ISSUE TITLE
Image scaling in task description 

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5247]
## Issue - Bug

Images in task descriptions are not scaled correctly, see the screenshot below

### Acceptance Criteria (optional)
- [ ] Images are displayed correctly in the tasks descriptions

**Estimated effort:** 8 hours

![action parabol co_me_tasks](https://user-images.githubusercontent.com/1017620/128222305-f2dcd2a4-ca02-4f0c-b661-5665465b5b77.png)

**Comment by mattkrick** [comment]
fixed in #5758
