### ISSUE TITLE
Jira integration - 'Fix it for me' doesn't work

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5251]
## Issue - Bug

When using the 'fix it for me' functionality the `submitScore` isn't called. It results in not updating the estimate once the field is successfully added.

### Acceptance Criteria (optional)
- [ ] error message is cleared correctly
- [ ] submit score is called, estimate is update

**Estimated effort:** 8 hours

**Comment by mattkrick** [comment]
bumping to p2, feels bad that we have a "fix it for me" button that doesn't fix it.
if we wanted to make it a p1 i'd be all for it.

**Comment by BartoszJarocki** [comment]
@mattkrick I'm happy to jump in and fix it. I think it looks really bad so I'd love to have that working.

**Comment by mattkrick** [comment]
sounds good! should be a pretty quick fix, regression tests will be rough. this is probably a great area to intro unit tests in the future
