### ISSUE TITLE
iOS no zoom in on input touch

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5253]
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone#6394497

on iOS when you tap an input field (eg reflection card) it zooms in slightly. when it zooms it, moving around the meeting gets really clunky. we want to avoid clunky movements

**Comment by jordanh** [comment]
AC
 - Implement: https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone#6394497

EE
- 4 hours
