### ISSUE TITLE
New Meeting view UX improvements

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5255]
Our New Meeting view could use a refresh. There are some known frictions and some known areas where we’re exploring system design. Namely, we want to provide a greater set of activities and make it easy and clear how to start and set those up. For this iteration it should be clear how to start any agile meeting (Retro, Poker, Stand-up), but be a step toward adjacent activity stacks.

### Known frictions
- Sometimes folks start a meeting on the wrong team
- Sometimes folks start the wrong meeting type
- Sometimes folks aren’t aware of other meeting types

### Open concerns
- How can we make activity type and template options more clear?
- How might we set up a recurring meeting or activity like a daily stand-up? How could we do it with or without a calendar integration?
- How might we set up a packaged set of activities using templates like Agile Sprint (aka cadence designer)?

### Previous work
We’ve got some early ideas and concepts [Enrique’s exploration](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=0%3A1), the [Meetings view](https://www.figma.com/file/dfTQxhoKzohkCpxlztBbhS/Meetings-view?node-id=67%3A312), thinking about [Team Activities](https://www.figma.com/file/f2224pwzQgNcRmY19LSgr1/New-Team-Activity?node-id=0%3A1) and [the iterations on the current view](https://www.figma.com/file/2CdDxgchV8PHXT8YfWfGpw/?node-id=230%3A1796)

## Acceptance criteria
- Primarily goal: designed recommendations for 1) improving the visual hierarchy so that folks understand what is selected and what their options are and 2) improving the flow for making changes and getting started
- We had a responsive layout for the template dialog that still hasn’t been implemented via #4045 — any new layout changes should be mobile-first, including if there are ways to drill down into templates outside of a dialog
- Secondary goal: explored the open concerns of recurring activities and activity sets (cadence designer). Recommendation: time box this exploration and maybe limit to sketching in order to think about where we may be headed in the future
  - Note: we will explore more deeply recurring meetings and sets of activities (cadences) in separate issues

## Estimated effort
- 18 hours

**Comment by enriquesanchez** [comment]
Implementation issue for an MVP → #5589
