### ISSUE TITLE
Remove sfu and cypress pacakges from the monorepo

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5261]
Now that we have ironbank stuff to contend with, it helps to keep package dependencies to a minimum.
since we're moving to playwright & not running any cypress tests, that should be safe to remove 
https://github.com/ParabolInc/parabol/issues/4431

since we're not longer focused on sync video, we should remove that too.

I suggest we keep those 2 in a long-lived git branch so when we decide to energize those areas we can pull from them easily

AC
- [ ] a new branch is created that is called sfu-cypress-checkpoint & that branch is pushed to github
- [ ] sfu and cypress are removed from the repo (except for the branch above)

Estimate: 4 hours

**Comment by BartoszJarocki** [comment]
Branch for the future reference: https://github.com/ParabolInc/parabol/tree/sfu-cypress-checkpoint
