### ISSUE TITLE
Can't view check-in children when there are many discussion items

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5262]
In master, if there are many items in the discuss, estimate or agenda items phases, it's not possible to view the meeting members in the check-in phase:

![check-in-bug](https://user-images.githubusercontent.com/39854876/129109827-f8fd19ce-643f-4858-9dc1-854fcfa88925.gif)

This PR should fix this issue: https://github.com/ParabolInc/parabol/pull/5240

### Test

- [ ] Create a retro, add 5 reflections, proceed to the Discuss phase, click on the Icebreaker title in the sidebar and see that the sidebar displays the meeting member children
- [ ] Create a retro, add 50 reflections, proceed to the Discuss phase, click on the Icebreaker title in the sidebar and see that the sidebar displays the meeting member children
- [ ] Adding a large number of agenda items to the check-in meeting or tasks to the poker meeting doesn't prevent the user from seeing the children in the check-in phase

**Comment by nickoferrall** [comment]
This issue will be resolved when https://github.com/ParabolInc/parabol/pull/5240 is merged

**Comment by mattkrick** [comment]
fixed in #5240
