### ISSUE TITLE
Check Team.isPaid before starting a meeting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5267]
We have something that people want so badly they're willing to get around our silly modals :tada: 
@gcrickman 

AC
- [ ] in every startMeeting server mutation, check the `isPaid` boolean and `lockMessageHTML`
- [ ] if `lockMessageHTML` is present, then they're naughty hackers & the error message should say something cheeky
- [ ] if lockMessageHTML is not present & isPaid is false, then they should get a boring error message

Estimate: 4 hours

**Comment by mattkrick** [comment]
> "Wow, you're determined to use Parabol! That's awesome! Do you want to keep sneaking over the gate, or walk through the door with our Sales team?"

**Comment by treyparabol** [comment]
+1 here. Users are still able to run Parabol meetings from their Task Board, Timeline, and Meetings Hub. The example user [https://app.hubspot.com/contacts/3888472/contact/10624101/](url) 🔒  referenced in the screenshot below can be found here.
<img width="1233" alt="Screen Shot 2021-12-20 at 12 37 20 PM" src="https://user-images.githubusercontent.com/88459947/146810226-c1387f9d-d3c4-4297-bc82-4b014d6e1f41.png">

**Comment by gcrickman** [comment]
At least 9 accounts that have been locked are still meeting on Parabol. [Here's the list](https://www.notion.so/parabol/Locked-Accounts-ffbc2106ad584c308e70596aedf5dcb4) we have in Notion 🔒

**Comment by jordanh** [comment]
## AC
- Can still lock a team, but allow for it to be circumvented
- Can further "strengthen" the lock to apply to the server-side, preventing meetings from starting
