### ISSUE TITLE
Moving meeting membership to the sidebar

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5274]
This is a proposal for moving and displaying the full list of meeting members in the same area where we currently show the meeting facilitator. ([See original proposal here](https://www.notion.so/parabol/User-presence-activity-status-5599fa99e8e643ff9c1f0bb53e000f39) 🔒)

![image](https://user-images.githubusercontent.com/3276087/129637772-6ff26338-253e-493e-8011-6b00a9381154.png)

### Why? 

Because as it stands right now, there is no way in a Parabol meeting to accurately know the total number of members in a meeting, how many are currently present, and how many are offline.

This proposal aims to let anyone in a meeting, but mainly the facilitators, answer the following questions without much friction:

1. How many members are in this meeting?
2. How many are currently online?
3. How many are offline?

![image](https://user-images.githubusercontent.com/3276087/129638233-17c5e0a8-d423-4d8b-b21d-18a996a56ff4.png)

With the new design, we can still indicate who is the meeting facilitator by placing a visible badge on top of their avatar, and placing this avatar at the start of the list. This list of avatars will also help us communicate who is online and who's not, by way of making the avatars of the disconnected users transparent, like the last four members in the image above.

There's also a clear and prominent 'Invite' button below the list, making it obvious how to add more folks to the meeting. This way, everything that is member-related is contained in this component. No need to look or click elsewhere to figure this out.

#### Member info

Focusing or hovering on an avatar will show a little member popup, revealing member-specific information and actions.

![image](https://user-images.githubusercontent.com/3276087/129638508-782ef2b6-abcc-4bcb-b331-c0092d31e9f7.png)

When I hover the facilitator's avatar, the popup tells me their name, that they are the facilitator, and I can access the 'Take the facilitator role' control. Something similar is shown when hovering the avatar of a regular member:

![image](https://user-images.githubusercontent.com/3276087/129638533-5cbee1df-faa5-4a04-993d-5e6d5ed1c810.png)

The popup shows me their name, and in the case of a disconnected user, when was the last time they were connected. I can also see the phases they have completed, revealing that this user has been active in the meeting. I also have access, as a facilitator, to a 'Remove from meeting' control. 

For those members who have not engaged with the meeting at all, we can display a message along the lines of "Has not joined the meeting":

![image](https://user-images.githubusercontent.com/3276087/129638546-bb637f4b-1a84-4bc7-9185-f347f20b07f9.png)

As our membership features grow. the popup can also scale to include more actions, for example:

![image](https://user-images.githubusercontent.com/3276087/129638599-3338e79f-1c78-45a2-b34b-858506e2a9b4.png)

###  Handling large meetings

Let's say a meeting has 56 members. We obviously don't want to display them all at once since it'll be a lot of avatars. We can define a threshold at which we hide the rest of the avatars, say our threshold is 20, and what we do then is show a link below the group of avatars that lets you expand to see more:

![2021-08-16 5-50-28 p m 2021-08-16 5_51_22 p m](https://user-images.githubusercontent.com/3276087/129638895-a93ae954-5180-4cb8-bfbf-b4eddc388986.gif)

This allows the facilitator, and anyone else on the meeting, to view the complete list of members and interact with all of the avatars. 

Going back to the 3 questions a facilitator should be able to answer, I think this design helps answer all three of them:

1. How many members are in this meeting? ✅
2. How many are currently online? ✅
3. How many are offline? ✅

### Unlocking phase-level activity

Completion of this proposal will also allow us to explore new ways to display phase-level activity, helping facilitators understand the engagement and ready status of the meeting phases. See #5275 for a detailed proposal.

For more detail, [check out the Figma file here](https://www.figma.com/file/yqqEVeeMNGVaRT0Z0O852W/User-presence-and-activity?node-id=93%3A0).

**Comment by jordanh** [comment]
@enriquesanchez can you please work with a developer teammate to add EE to this?

**Comment by enriquesanchez** [comment]
@jordanh @mattkrick @ackernaut Opening this for discussion. [You've probably seen this before over here 🔒](https://www.notion.so/parabol/User-presence-activity-status-5599fa99e8e643ff9c1f0bb53e000f39). This is a more condensed version of that.

**Comment by mattkrick** [comment]
for large meetings i think a list view might be a more appropriate component. not everyone has an avatar, not every avatar looks unique, it'll get a little frustrating trying to find the person i'm looking for in a grid. 

big picture i think left drawer should be for navigation & right drawer could have members. 
i know there were a few designs awhile back about have a zoom-esque right drawer that has a "Participants" tab. I imagine avatar on the left, name on the right & in the future we can add a menu to each list item for extra actions
