### ISSUE TITLE
New phase-level presence and activity status

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5275]
This is a proposal for displaying phase-level user activity in a Parabol meeting. It is unblocked by completion of #5274 . ([See original proposal here](https://www.notion.so/parabol/User-presence-activity-status-5599fa99e8e643ff9c1f0bb53e000f39) 🔒)

![image](https://user-images.githubusercontent.com/3276087/129639936-fc8490e4-4bff-48a2-93b6-a7c546e3440c.png)

### Why?

Facilitators require to know when its time to move on to the next phase or stage of a meeting. In order for this to happen, they need to know who has engaged with the current phase and who is still pending. While we have the 'Ready' button to give us an idea of phase completion, it's signal can be unreliable it's a small surface area in the overall meeting UI that can be missed by some users.

This can produce uncertainty for facilitators, particularly when it comes to deciding when it's time to advance to the next phase or stage in a meeting (see #4340, #4951, #4672).

### New phase-level presence and activity status

Requiring that first we move meeting membership to the sidebar (see #5274), we are left with new available space in the top-right corner of the phase area:

![image](https://user-images.githubusercontent.com/3276087/129775480-6e77cfeb-fbe3-4c0b-9ce0-458151750cdd.png)

I think this is the ideal space to explore displaying phase-level user activity for the simple reasons that is within the phase area and is also a very visible surface. This will make it easier for facilitators to be aware of phase completion. I think it can look something like this:

![image](https://user-images.githubusercontent.com/3276087/129775535-959e1c80-3363-4eee-b678-da19037f6964.png)

As users start to engage with and complete a phase, everyone, including the facilitator, will start to see the avatars animate and appear in this space. This should provide the necessary signal for facilitators to understand the engagement level of a particular phase. 

![image](https://user-images.githubusercontent.com/3276087/129775579-15272537-3373-4e47-aac0-63e4b6031227.png)

For more detail, [check out the Figma file here](https://www.figma.com/file/yqqEVeeMNGVaRT0Z0O852W/User-presence-and-activity?node-id=93%3A0).

**Comment by jordanh** [comment]
@enriquesanchez could you work with a developer pal to add EE?

**Comment by enriquesanchez** [comment]
@jordanh @mattkrick @ackernaut Opening this for discussion. [You've probably seen this before over here 🔒](https://www.notion.so/parabol/User-presence-activity-status-5599fa99e8e643ff9c1f0bb53e000f39). This is a more condensed version of that.

**Comment by mattkrick** [comment]
is there any concern over anonymity here?
Scenario 1:everyone has finished except me so now i feel bad & have to hurry up.
Scenario 2: I'm done quickly but i don't want to be the first to finish so i don't hit the ready button because then my manager will think i didn't take it seriously because i finished in 1 minute.

**Comment by jordanh** [comment]
I think this is still a good idea, especially safe to try for a meeting type such as Sprint Poker.

This issue went stale, but I have a feeling the tension behind this (and the associated design work) will come back up.

Iceboxing for now
