### ISSUE TITLE
Failing migration - addUserEmailUniqueConstraint

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5281]
## Issue - Bug

https://app.circleci.com/pipelines/github/ParabolInc/parabol/2874/workflows/e37cc867-555b-455b-9d91-9282b6524886/jobs/11729/parallel-runs/0/steps/0-110
`addUserEmailUniqueConstraint` fails the following error

```
### MIGRATION 1625124096757_addUserEmailUniqueConstraint (UP) ###        
remote:        Error executing:        
remote:        CREATE UNIQUE INDEX "User_email_index" ON "User" ("email");        
remote:        error: could not create unique index "User_email_index"        
```

### Acceptance Criteria (optional)
- [ ] migration runs successfully 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
stuck on restoring the prod postgres DB to staging
@adaniels-parabol @tiffanyhan any scripts already exist to do this?

**Comment by mattkrick** [comment]
no scripts exist, so we just do a restore via pgadmin.
how-to here: https://www.notion.so/parabol/Release-Playbook-c3d1b146ea7c4f2fbf9501ae578ced25#7db3e583ee89474aa6718e9b09c06900
