### ISSUE TITLE
Sprint poker - final score isn't automatically updated for all meeting participants when set by the facilitator 

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5283]
## Issue - Bug

The final score isn't automatically updated for all meeting participants when set by the facilitator. It still shows an empty field even though it was already set. 

Reproduction steps
1. Start sprint poker meeting
2. Invite other people 
3. Estimate a card
4. Reveal the votes
5. Set the final score
6. Final score isn't visible for everybody except for the facilitator 

### Acceptance Criteria (optional)
- [ ] - final score is visible to all participants

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
fixed in #5285
