### ISSUE TITLE
Batch archive tasks in Done column

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5286]
## Issue - Enhancement

For customers who use our Kanban board but not run check-in meetings, there are no ways to automatically archive the done tasks. As a result, they will see tasks piled up in the done column. This might also affect performance.

We could provide a button near the done column to archive all the tasks in this column.

### Acceptance Criteria (optional)
Users can:
   - [ ] batch archive tasks in done column 

**Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@tianrunhe @ackernaut @enriquesanchez does this need `design`?

**Comment by ackernaut** [comment]
Yeah, I’d say this would be a light design task. We could shoot for a quick prototype that shows a few steps to archive the column.

**Comment by jordanh** [comment]
Iceboxing
