### ISSUE TITLE
Cannot read property 'newMeeting' of null, NewMeetingSummary

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5288]
## Issue - Bug

159 events affecting 155 users in the past month. 

https://sentry.io/organizations/parabol/issues/2515932506/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tiffanyhan** [comment]
Sentry issue: [ACTION-PRODUCTION-8HQ](https://sentry.io/organizations/parabol/issues/2514500905/?referrer=github_plugin)

**Comment by mattkrick** [comment]
Hasn't been seen since 6.24.0, 7 days ago!
I think 6.25.0 might have fixed it. Gonna optimistically close
