### ISSUE TITLE
Remove remaining refs to withAtmosphere

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5293]
There are only 37 places where we use `withAtmosphere` instead of `useAtmosphere`.
We should get rid of these to make adopting the codebase cleaner & reduce the double context that we have to keep for it, which is pretty confusing when it comes to reading the code.

AC
- [ ] `withAtmosphere` is refactored to `useAtmosphere`
- [ ] AtmosphereContext is removed

Estimate: 4 hours

**Comment by jordanh** [comment]
Opted not to icebox

**Comment by Dschoordsch** [comment]
@treyparabol this looks like a DX issue, do you want to take it to squad 2?
