### ISSUE TITLE
Remove waterfall data fetches

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5305]
We currently use an old version of react-router where routers are nothing more than switch statements nested in arbitrarily deep render trees. This leads to waterfall loading. 

For example, take a Dashboard component:
- Dashboard loads its own query
- When it comes back, it can load either the tasks or the timeline view
- if it loads the tasks view, it can load either archived or current tasks

Instead, it'd be great to know the full route & perform the necessary data fetches for it all up front. This is what Relay's `useQueryLoader` lets us do.

A good example of a basic router that does that for us is: https://github.com/relayjs/relay-examples/blob/main/issue-tracker/src/routing/createRouter.js

AC
- [ ] Every route loads every necessary query all up front
- [ ] Create a basic router that maps out all our queries based on the route
- [ ] Put this router at the top of our app, match the route & have it call `useQueryLoader` for all necessary queries
- [ ] have the router pass down the queryRefs as necessary

Estimate: 8 hours

**Comment by jordanh** [comment]
Added mid-sprint for @JimmyLv to get his feet wet

**Comment by ackernaut** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/9) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
**Include?: Y**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/10) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by JimmyLv** [comment]
The good news is that [React Router v6.3](https://github.com/remix-run/react-router/releases/tag/v6.3.0) was released 8 days ago, with a backward-compatible API ([Official v5 to v6 Migration Guide](https://github.com/remix-run/react-router/discussions/8753)), but still hasn't finished the Router's `preload` API, so we can prepare to upgrade React Router to v6, but it's best to wait for the `preload` API to come out. At the same time, I would like to implement the `preload` and `prepare` logic based on: https://github.com/relayjs/relay-examples/blob/main/issue-tracker/src/routing/createRouter.js

**Comment by JimmyLv** [comment]
Pause to do this enhancement and marked the PR as a draft, do something more important at this point.

some notes below 👇

Relay ✖️ React Router

- Waiting for React Router v6's experimental `preload` API https://github.com/remix-run/react-router/discussions/8009
- Chose another option? https://github.com/relay-tools/found-relay

To optimize route redundant code by EntryPoint pattern?

- [Entry points docs · Issue #1 · relay-tools/typescript-relayjs-examples](https://github.com/relay-tools/typescript-relayjs-examples/issues/1)
- EntryPoint examples
  - [https://github.com/relay-tools/typescript-relayjs-examples/blob/master/relay-entrypoints/src/Repository.entrypoint.ts](https://github.com/relay-tools/typescript-relayjs-examples/blob/master/relay-entrypoints/src/Repository.entrypoint.ts)
  - [https://github.com/sorenhoyer/react-relay-typescript-boilerplate/blob/0ae1d519f5/client/src/routing/createRouter.ts#L38](https://github.com/sorenhoyer/react-relay-typescript-boilerplate/blob/0ae1d519f5/client/src/routing/createRouter.ts#L38)

**Comment by mattkrick** [comment]
looks like this has gone over on the time estimate, so moving this to the backlog & we can revisit
