### ISSUE TITLE
TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5309]
Why can props not be destructured? affected 10 users in 10 events, first seen in release 6.24.0.

https://sentry.io/organizations/parabol/issues/2588850934/?referrer=github_plugin

```
TypeError: Right side of assignment cannot be destructured
  at invariant (./packages/client/components/MeetingSelector.tsx:29:10)
  at su ([native code])
  at None (./packages/client/components/Action/Action.tsx:39:21)
  at replace (None:18:27)
  at forEach ([native code])
...
(30 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
whoa! My guess is safari has an off-by-one on their stack trace & it's in fact the viewer that  cannot be destructured.
Either way, not seen in 6.25.0. Let's assume it's fixed!
