### ISSUE TITLE
Add noImplicitAny to server tsconfig (Part 1 of 8)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5314]
When we migrated to typescript from javascript, it was too expensive to turn on `noImplicitAny` because it was hard enough just making the switch.

Today, having `noImplicitAny` could catch a lot of errors that I'm seeing in code reviews.
The problem is that there are 1600 errors!
This is too many for any one person to do in a sprint.
However, the benefit of having this turned on for new code is pretty great.

So, I propose we share the love & chip away at it:
- [ ] turn on `noImplicitAny` in the server tsconfig file
- [ ] fix ~200 errors
- [ ] turn it off again in the tsconfig file & submit the PR
- [ ] we'll merge it blindly
- [ ] create a copy of this issue named Part (2 of 8) so we can re-prioritize for the next person. We'll keep doing this until it's done

AC
- [ ] 200+ `noImplicitAny` errors are fixed in the server package

Estimate: 4 hours

**Comment by tiffanyhan** [comment]
> we'll merge it blindly

@mattkrick does it mean we won't do code review for these PRs?

**Comment by mattkrick** [comment]
ahhh that's a good question.
perhaps a _very_ light review? I'll take a look later today
