### ISSUE TITLE
TypeError: ServiceWorker script at https://action.parabol.co/sw.js for scope https://action.parabol.co/ enco...

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5323]
https://sentry.io/organizations/parabol/issues/2502161931/?referrer=github_plugin

Affected 109 users, happened 1.6k times in the last 30 days. Unhandled. 

```
TypeError: ServiceWorker script at https://action.parabol.co/sw.js for scope https://action.parabol.co/ encountered an error during installation.
```

**Comment by mattkrick** [comment]
This seems to be a firefox bug: https://github.com/mozilla/serviceworker-cookbook/issues/291#issuecomment-369373962

Funny that it's been a thing for 3+ years: https://stackoverflow.com/questions/48295748/firefox-typeerror-serviceworker-script-encountered-an-error-during-installation

Next step is to reproduce locally:

- yarn build
- yarn start
- open firefox
- if that works, open a different firefox (dev/beta/nightly) using the same profile
- open it with a different profile, see if that works
- throw a try/catch or 10 into the sw.js and see where it fails
- if it truly is a fatal error, make a workaround. else, just swallow the error in the catch with a comment about firefox


AC
- [ ] workaround or fix implemented

Estimate: 4 hours

**Comment by jordanh** [comment]
Looked in Sentry, still a thing: affected 74 users, ~4.7k events

**Comment by jordanh** [comment]
Checked to p3 for non-fatality
