### ISSUE TITLE
Error: No payload received

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5326]
https://sentry.io/organizations/parabol/issues/2399285612/?referrer=github_plugin

It's not fatal but it's an indication that a user can't do much in our app, ie. I was getting this during the login, signup when API was down. 

```
Error: No payload received
  at Object.fetch (./node_modules/@mattkrick/graphql-trebuchet-client/lib/GQLHTTPClient.js:17:23)
```

**Comment by mattkrick** [comment]
still a problem in 6.25.0

AC
- [ ] catch this error & log it with the name of the query, variables, & the auth token

Estimate: 4 hours

**Comment by mattkrick** [comment]
we hit this in our check-in meeting! https://sentry.io/organizations/parabol/issues/2399285612/?environment=client&project=107196&query=is%3Aunresolved

bumping to p1

**Comment by tiffanyhan** [comment]
the error originates from `node_modules/@mattkrick/graphql-trebuchet-client/lib/GQLHTTPClient.js`, where the error is passed to `sink.error` method. When `QueryRenderer` does its thing, the error is thrown and then caught by `ErrorBoundary` where it's sent to sentry.

i think to capture more info, such as query and variables, we should `console.info` right before the error is thrown and then caught in `node_modules/@mattkrick/graphql-trebuchet-client/lib/GQLHTTPClient.js`. i don't think it's preferable to make the change in lib code, but it doesn't seem like there's a way to "catch" the error in app code and then log verbose details on the query and variables.

@mattkrick what do you think?

**Comment by tiffanyhan** [comment]
As an aside, when looking through user feedback on sentry: https://sentry.io/organizations/parabol/issues/2399285612/feedback/?project=107196&referrer=github_plugin , it looks like the error occurs randomly. i.e. users reporting it happened when trying to load timeline, adding a card, logging in, adding a comment, etc.

i'm thinking logging the specific query and variables might not help us much, since the error doesn't occur deterministically from one or even a few actions. it seems like looking at server stats and metrics with times correlating to the error events might be a more promising route.

cc. @mattkrick @adaniels-parabol any thoughts?

**Comment by tiffanyhan** [comment]
i looked at the server logs and tried to see what happened when the spike of this error happened today sep 2, 6:00-7:00 utc time. i found lots of `SEND TO SENTRY Error: GQL executor took too long to respond` and `SEND TO SENTRY Error: TIMEOUT` logs. i then looked again at the sentry page for the above error: https://sentry.io/organizations/parabol/issues/1666567181/?project=107196&query=&sort=freq&statsPeriod=14d

it looks like the time distribution of events is the same as the distribution of events of this "No payload received error". E.g. both errors spiked at sep 2, 6:00-7:00; aug 26-27; aug 19-20. I then looked at exact time of events for today Sep 2 and found 1:1 correlation. E.g. events for both errors happened on Sep 2, 6:12-6:13.

bc of the above, I think this error is just the client manifestation or knock-on effect of the persistent "GQL executor took too long to respond" error we've been seeing the past few months. we need to take another look at how we're going to approach pinpointing the cause of the "GQL executor" problem.

<img width="1322" alt="Screen Shot 2021-09-02 at 2 56 23 PM" src="https://user-images.githubusercontent.com/11562889/131921554-773b2aed-806a-437b-ab33-5097135021a0.png">

**Comment by tiffanyhan** [comment]
Related: https://github.com/ParabolInc/parabol/issues/5189

**Comment by mattkrick** [comment]
Yep, so `no payload received` means the server sent `{data: null, errors: any}`.
this happens when the request takes too long.
 
we'll need to handle this more gracefully in the advent of null data
