### ISSUE TITLE
Datadog RUM for Parabol frontend

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5331]
This ticket is a request to enhance logging abilities of our frontend components to Parabol. This ticket would implement Datadog Real User Monitoring (RUM). We currently use Datadog today for other capabilities and implementing RUM would expand those capabilities to help with logging.

Benefits:
- We use Datadog today in order to capture backend/rethinkdb log data. Being able to correlate that data with RUM adds a layer of logging that increases are awareness and observability
- Detect user issues real time and better correlate with backend errors
- Track how releases impact or change performance over time
- More analytics e.g. who is using Parabol (country, device, OS), monitor individual users journeys, and analyze how users interact with Parabol (most common page visited, clicks, interactions, feature usage, etc)

Note: I have already tested RUM on local builds and impact seems to be not noticeable. This ticket would implement on all environments. 

AC
- [ ] RUM setup for staging
- [ ] RUM setup for production

Estimate: 2 hours

**Comment by mattkrick** [comment]
Love this.
Additional benefits:
- connects front end errors to backend errors
- could replace sentry + logrocket (1 tool to rule them all)

**Comment by adaniels-parabol** [comment]
@mattkrick that would be the ultimate goal for sure
