### ISSUE TITLE
Add filter by me option to dashboard

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5337]
## Issue - Enhancement

As a user I want to check if my tasks are up to date. Right now I have to search in the filter list labelled 'All team members' for my name. It would be nice to have the first two entries be:
* All team members
* Me
* ...

### Acceptance Criteria (optional)
Users can:
  [] filter tasks for themselves by selecting the "Me" menu entry

**Estimated effort:**

**Comment by tianrunhe** [comment]
The [Tasks subpage](https://action.parabol.co/me/tasks) will serve your needs, no?

**Comment by Dschoordsch** [comment]
Partially, the tasks subpage will show all my tasks and not just the ones in that team. I also didn't figure out at the time of writing that this would work.

**Comment by jordanh** [comment]
Re-adding the discussion label as I have a question and some thoughts (but first the question):

@Dschoordsch are you referring to the task dashboard appearing on the /team/:teamId route?
