### ISSUE TITLE
Allow filtering tasks in team view by pressing on avatar

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5338]
## Issue - Enhancement

As a user when I see the team dashboard for the first time and want to filter tasks by person, the most intuitive place is their avatar. At the moment it seems there is only their connection status visible, I wish there would also be a button labelled "Show only their tasks".

### Acceptance Criteria (optional)
Users can:
  - [ ] Filter tasks in team dashboard by clicking on avatar and then "Show only their tasks"

**Estimated effort:**

**Comment by jordanh** [comment]
Iceboxing
