### ISSUE TITLE
Create primary/foreign key loaders pattern for postgres

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5340]
Now that we're using pg, we need to create some good patterns for dataloaders.

AC
- [ ] there's a new file called pgLoaders that works like customLoaders except it doesn't take this.dataLoaderoptions, it's just the `batchFn`
- [ ] there's a pgPrimaryLoader that takes in a pgLoader
- [ ] there's a pgForeignLoaders file that works like fkLoader that
- [ ] a pgLoader can be a foreign key loader, too. it can optionally take in primary key loader which will clear & prime the optional primary key loader 

Estimate: 4 hours

**Comment by jordanh** [comment]
@mattkrick If this is still a thing, does the above AC need to change at all given recent changes?

**Comment by Dschoordsch** [comment]
@mattkrick what's the goal of this task? Do we want to be able to have loader makers like
```
export const users = pgPrimaryLoaderMaker(getUsersByIdsQuery)
```
and
```
export const usersByEmails = pgForeignLoaderMaker('users', 'emails', getUsersByEmailsQuery)
```
?
