### ISSUE TITLE
Request to join Team toast invitation is always in the way

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5354]
If a request to join team toast is never acknowledged with accept or deny it stays at the bottom of the screen. The toast is somewhat in the way when no one accepts/denies. This could lead to someone getting accepted, that shouldn't be accepted, just to get the toast to go away.

I'm wondering if we should have a queue off to the side after X seconds or have the toast message collapse after X seconds

Below is a screenshot of the toast message in question. I've blurred any sensitive information in the screenshot.

![image](https://user-images.githubusercontent.com/71724289/131819488-d229b31d-7663-4f47-bd0a-6b08ade47882.png)

**Comment by mattkrick** [comment]
if you click any part of it besides accept/deny then it'll go away :slightly_smiling_face: 
should probably make that more obvious!

**Comment by jordanh** [comment]
Superseded by: #6218
