### ISSUE TITLE
Marketing site - cookie policy, banner and GDPR

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5357]
## Issue - Enhancement
Let's make sure our marketing site is GDPR compliant and shows the cookie banner with correct options

### Acceptance Criteria (optional)
- Folks from the EU see the cookie banner on their first visit
- Cookie banner has all the required options
- All the cookie banner options are handled correctly
- Cookie policy exists and it's linked in the cookie banner

**Comment by jordanh** [comment]
Hey @BartoszJarocki – our marketing site already does this automatically. If the IP is located within the GDPR zone, we'll pop a banner asking for cookie consent. It's a feature of HubSpot
