### ISSUE TITLE
Application - cookie policy, banner and GDPR

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5358]
## Issue - Enhancement
From what I see we don't use *any* cookies but let's make sure it's always the case.

### Acceptance Criteria (optional)
- Make sure we don't use cookies *or* make sure we have a proper cookie policy and cookie banner showing
- Make sure our app is GDPR compliant

**Comment by jordanh** [comment]
This is a thing we do for the marketing website. Not for the app yet. If you still have tension, re-open
