### ISSUE TITLE
Integration Discovery Assistance 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5359]
I've talked to quite a few users who don't know about our integrations. This is a place to capture that feedback. 

From my call notes yesterday with [this user](https://app.hubspot.com/contacts/3888472/contact/9913651) 🔒 :

> I asked if they had suggestions for how we can improve the product. They talked about how much time they spend interfacing between Jira and Parabol. They were happy to learn we offer a Jira integration!

**Comment by thaywood83** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/47883751) 🔒  said: 

> 
The one thing I think it'd be awesome is if for sprint planning there was an option of just adding tasks not integrated with Jira or Github, and separate from the Parabol Backlog; something like an ephemeral backlog where we just add titles of the tasks to estimate.

**Comment by jordanh** [comment]
@thaywood83, I moved your user feedback [here](https://github.com/ParabolInc/parabol/discussions/5389) as it is a distinct idea from the issue @drewhousman1010 captured.

**Comment by ackernaut** [comment]
There’s a [discussion issue #5515](https://github.com/ParabolInc/parabol/discussions/5515
)

**Comment by jordanh** [comment]
Closing in favor of #5515
