### ISSUE TITLE
Improve scrolling in check-in

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5377]
When moving phases, the first child doesn't always scroll perfectly into view if there are many children. It does work some of the time but not always. 

Often, when going from Icebreaker to Solo Updates it initially scrolls to the correct position but if the viewer goes back to the Icebreaker and returns to the Solo Updates, it doesn't scroll to the exact position of the first team member.

![scroll-bug](https://user-images.githubusercontent.com/39854876/132512229-2b6142c3-b9ce-4579-98ed-003ea2c5ede0.gif)

**Comment by jordanh** [comment]
Iceboxing
