### ISSUE TITLE
Allow someone to set up a retro board and then assign the facilitator role to another team member

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5378]
A [user](https://app.hubspot.com/contacts/3888472/contact/20229501) 🔒  says:

> Can I assign a different facilitator after setting up a retro board? For example, I would like to manually give the facilitator role to someone else when I go on holiday

**Comment by tianrunhe** [comment]
Anyone can go to an active meeting and take the facilitator role themselves. There's no need for the creator to "give the role to someone else".

![](https://user-images.githubusercontent.com/1879975/132801174-f6194f13-d61d-478e-ace2-b839d7d18a89.png)

**Comment by drewhousman1010** [comment]
For sure, I understand that, thanks! But just so we're clear on that this user wants, they are asking for the option to assign the role to a teammate as opposed to asking someone to take it. This would remove the step of having to explain to someone how to take the role, or asking around to see who wants it.

**Comment by tianrunhe** [comment]
Ohhh got it! Thanks for the clarification!

**Comment by jordanh** [comment]
Iceboxing

**Comment by emilyhebner** [comment]
I asked if it were possible to assign Jordan to be the facilitator of the Remotely Agile retro bc the only option I see is to “randomize” the facilitator. It would be great to be able to assign a facilitator esp as we'll be doing more Remotely Agile events and as the person coordinating, I will always be the one opening the retro and Jordan will always be the facilitator.
