### ISSUE TITLE
allow facilitator to opt-out of voting during retros 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5379]
A [user ](https://app.hubspot.com/contacts/3888472/contact/20229501) 🔒  says:

> I don't vote with my team. So when voting ends, my votes are always left over. I'd like the option to remove myself from the voting and the vote count altogether.

This user is an agile coach. When she runs retros with other agile coaches, she participates in voting. When she runs retros with developers, she does not vote.

**Comment by jordanh** [comment]
Iceboxing!
