### ISSUE TITLE
Hubspot: Active Teams should only count teams who met

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5387]
## Issue - Enhancement

Today the `Active Teams` property in Hubspot counts all Teams associated with a Company, not the number of teams who are actually active on the product. This sometime gives us a false positive when deciding how to prioritize deals.

### Acceptance Criteria (optional)
   - `Active Teams` is counted as: the number of teams who have completed any meeting in the last 30 days who are associated with the given Company domain

**Estimated effort:** 12 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I'm going to remove this from the backlog and request the @tianrunhe and/or @tghanken add it to theirs...

**Comment by tghanken** [comment]
Closing this as we now populate HubSpot from data-sanctum.
