### ISSUE TITLE
Designed: how to provide recurring stand-ups

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5394]
I have some questions and assumptions about holding a daily stand-up in our software:

### Questions
- **Do we allow folks to give updates on their work without an open activity, or do we require an activity for the input?** Today we have an example of both cases: folks can work on their Parabol tasks independent of a Check-In meeting, but they can’t add reflections without a Retro meeting. If answering this question by itself, and quickly, I’d say being able to add updates about work outside of a meeting feels flexible, bottom-up, and async-first. But, I’m not sure what’ll drive the behavior. Having an explicit, open activity may cause folks to feel accountable for giving updates for their team. It also provides a nice hook for setting up notifications and reminders
- **How do we allow folks to change or pick templates for activities when they are automatically opened?** Do we require somebody to pick a template, blocking input for the meeting? Do we allow changes until somebody has responded, otherwise the template change takes affect for the next meeting?
- Stretch: how might this interact with a calendar integration?
- Stretch: how might this work with notifications and reminders?

### Assumptions (as user job stories)
- When holding a stand-up with my distributed team everyday I want them to be able to answer their questions any time so that I can see what folks are working on regardless of timezone or a sync meeting
- When holding a sync stand-up meeting I want folks to join and talk about updates (that they prepared in advance) so that we feel more connected as a team and have a quick meeting so that everybody can get back to their work
  - Alt: when holding a sync stand-up daily, I want folks to be reminded in advance so that they can be prepared to give their update before the meeting
- When holding a stand-up with my team daily I want a meeting to automatically exist so that I don’t have to create the same meeting over and over

### Acceptance criteria
- Designed concepts showing…
  - the experience of of setting up recurring activities
  - the experience of choosing and changing templates
  - the experience of holding meetings just in time on top of async data
  - a quick look (sketches?) at how calendar and chat integrations may help
- Shared a summary of the work as a comment here
- Defined next steps (scoped more design work? drafted implementation issue(s)?)

### Estimated effort

- 20 hours

**Comment by mattkrick** [comment]
closing in favor of #5635

**Comment by ackernaut** [comment]
And once we suss out recurring logic, we can also start on #5638 sooner than later
