### ISSUE TITLE
Sprint Poker: Edit tasks in task selector

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5399]
## Issue - Enhancement

This is [user](https://app.hubspot.com/contacts/3888472/contact/39724101) 🔒  would like the ability to edit Jira task names when adding tasks before a sprint poker meeting.

> when creating tasks for a Sprint Poker Meeting – why can you not edit the task name within the window before the meeting in case you make a mistake? I am also the facilitator, and I understand I can make edits once I start the estimation on the next screen but how come not here?

**Comment by jordanh** [comment]
Iceboxing
