### ISSUE TITLE
Check-in meeting navigation can't rejoin or click left nav item sometimes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5400]
We experience this ourselves during our check-in meetings.
Here's the meeting object that is borked: https://github.com/ParabolInc/action-devops/issues/73

## How to reproduce
Start a check-in meeting with 2 participants, the facilitator Fritz and Paula the participant. Add two agenda items, when on the first one Paula starts to write a comment and Fritz moves the meeting forward to the next item.
Paula stays on the first item and can finish their comment

## Expected behaviour
Paula can rejoin the meeting by either
1) pressing the "rejoin" button
2) selecting the active agenda item on the left

## Actual behaviour
Paula cannot move to another agenda item, neither by selecting it directly, nor by pressing "rejoin". Only refreshing the page works.

AC
- [ ] can navigate to items that i should be able to

Estimate: 4 hours

**Comment by elielytz** [comment]
## Testing results
Tested this on **_staging environment_** and the described actual behavior still persists.
Participant cannot move to another agenda item, neither by selecting it directly nor by pressing "rejoin".
Only refreshing the page works.

**Comment by BartoszJarocki** [comment]
@elielytz the fix isn't on staging yet, so this will need to be retested once merged.

**Comment by elielytz** [comment]
Thanks for the update Bartosz, I have marked it for re-testing once merged.
