### ISSUE TITLE
Sprint Poker: GitLab: Scope: Oauth2 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5404]
The next integration we'd like to add to sprint poker is GitLab :tada:.

To do that, we need the following:
- A UI
- A DB Table to store GitLab credentials
- A mutation to add credentials to the DB

### Acceptance Criteria
- [ ] When the user creates a new poker meeting, a GitLab tab is visible with the same functionality as the GitHub tab. It should look pretty similar to https://github.com/ParabolInc/parabol/blob/091037bf777be5d7e5d138e111b474e56e948f27/packages/client/components/ScopePhaseAreaAddGitHub.tsx. Note: we use Relay v11 now, so it's encouraged to use hooks e.g. `useFragment` instead of HOCs like `createFragmentContainer`. Pro tip: refactor the GitHub component to use hooks, copy the file, do a search & replace to change `Hub` to `Lab`.

![Screenshot from 2021-09-15 13-13-23](https://user-images.githubusercontent.com/5514175/133502865-e6583371-7f3f-4b12-914f-bec8f0793aed.png)

#### Frontend
- [ ] Clicking "Import stories from GitLab" opens an oauth2 flow
- [ ] Completing the oauth2 flow should create a new record in the `GitLabAuth` table and the component showing should just say "Integrated!" 

#### Backend
- [ ] A postgres migration exists that creates a new table called `GitLabAuth`. The columns are about the same as the columns in `GitHubAuth`. To create a migration, call `yarn pg:migrate create gitlabAuth`. To explore postgres use pgadmin at localhost:5050
- [ ] A mutation to support adding gitlab auth to the database is created. Use `yarn newMutation addGitLabAuth` and it will create all the necessary files 

Estimate: 16 hours

**Comment by Dschoordsch** [comment]
## AC
* [ ] add migration to insert a row into IntegrationProvider for gitlab.com (maybe post-deploy)
* [ ] make sure `GitLabProviderRow` is shown in team integrations
* [ ] make sure add GitLab is shown in sprint poker

**Comment by Dschoordsch** [comment]
You can add the row manually for testing by running the mutation
```
mutation {
  addIntegrationProvider(input: {
    teamId: "aq9zXJNmHn"
    service: gitlab
    authStrategy: oauth2
    scope:org
    oAuth2ProviderMetadataInput: {
      serverBaseUrl: "https://gitlab.com"
[...]
    }
  }) {
    __typename
    ... on AddIntegrationProviderSuccess {
      provider {
        id
        isActive
        teamId
        ... on IntegrationProviderOAuth1 {
          id
          serverBaseUrl
        }
      }
    }
  }
}
```
