### ISSUE TITLE
Dropping remote reflection loses position when opening the Spotlight

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5415]
To reproduce:

- Go to the grouping stage in a retro
- Open a second browser and drag and drop a reflection
- On the first browser, click the open spotlight icon before the remote reflection has completely dropped
- Note that it either loses its position or moves into the Spotlight

### AC

- [ ] The dropping remote reflection position doesn't change when opening the Spotlight

**Comment by nickoferrall** [comment]
@BartoszJarocki oh well that's good news! Which branch are you using? I just tested it on my most recent branch, and I'm still seeing the issue. I'll test it on the one you're using

**Comment by BartoszJarocki** [comment]
@nickoferrall you're right, sorry! yesterday wasn't my best day! 🤕

**Comment by jordanh** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/7By0K1Cj6w/estimate/7) in “Sprint `#89` Scoping”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
