### ISSUE TITLE
Retro: JIT Reflect template editing

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5417]
​

Folks often want to add a lane for "questions" or "kudos" after they have started a meeting

​

Likely, we'd provide affordances for this that would create a copy of the current template automatically if edits are applied

​

AC

   - [ ] Lo-fi design to create a lane in situ

   - [ ] supports adds/removal of lanes

**Comment by mattkrick** [comment]
Predecessor: (No issue yet) create immutable retrospective templates (similar to what we do for poker templates)
