### ISSUE TITLE
Bundle static images stored in S3 into the Parabol git repo

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5421]
This ticket is a request to bundle static images stored in S3 into the Parabol git repo so that we have a centralized location for static image content (e.g. static images stored in S3 buckets at action-files.parabol.co/production/static). Images will still be in S3 for hosting as well.

AC
- [ ] All static image content committed to git repo ( Files from https://s3.console.aws.amazon.com/s3/buckets/action-files.parabol.co?region=us-east-1&prefix=static/ need to be pulled into https://github.com/ParabolInc/parabol/tree/master/static)
- [ ] All static image content synced to S3 bucket via deployment pipeline

Estimate: 2 hours

**Comment by adaniels-parabol** [comment]
@adaniels-parabol I think this is something @jchandler-parabol could work on as well

**Comment by adaniels-parabol** [comment]
Since this ticket was created, it looks like all of the content has been migrated away from the static s3 folder (https://s3.console.aws.amazon.com/s3/buckets/action-files.parabol.co?region=us-east-1&prefix=static/) to the webpack bundles. @mattkrick with exceptions of AVATAR_BUCKET (https://${process.env.AWS_S3_BUCKET}/static/avatars`) it looks like we don't really use /static much any longer. @mattkrick would you concur we don't need this any longer?

**Comment by mattkrick** [comment]
yep, this work was done in https://github.com/ParabolInc/parabol/pull/5701.
i think we can close this issue

AVATAR_BUCKET is where we keep all the default avatars (AA, AB, AC, AD....ZZ). Keeping that in the git repo feels bad since there's so many of em & they'll never change. we could move the avatars to another dir if that makes things clearer

**Comment by adaniels-parabol** [comment]
Thanks, I think we can close this. I don't feel a tension to move default avatars into repo. I don't foresee those changing.
