### ISSUE TITLE
Gracefully handle poker meeting fail when un-integrated

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5424]
From [slack](https://parabol.slack.com/archives/C4JAUUZ9P/p1632321853060100):

>Hi,
 We use the Sprint poker planning in parabol but we have some issues with old meetings. We can’t join them even if we have created these meetings. We have a message telling that there is an invitation required.
 We use these meeting as continuous meetings for poker planning without ending them, that’s probably why they don’t work anymore (they are old).
Meeting ids

similar to #4732

AC
- [ ] no error on screen

Estimate: 8 hours

**Comment by tianrunhe** [comment]
![](https://user-images.githubusercontent.com/1879975/134398327-f5fc1004-d127-4b39-a867-f58df7f00348.png)

The response from MeetingRootQuery is attached above. Looks like the user has turned off Atlassian integration. We should handle this edge case better, maybe a view indicating that they should re-integrate.

**Comment by jordanh** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/7By0K1Cj6w/estimate/6) in “Sprint `#89` Scoping”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
