### ISSUE TITLE
Design the Steve Jobs version of Team Dash Standups

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5425]
Channeling my inner arrogant a-hole, I think I know what the market needs for a standup tool & need to turn that idea in something visual.

Figma: https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=275%3A9688

AC
- [ ] iterate on current designs to bring them to high fidelity. The goal is a series of views that could be handed off to the dev team to build
- [ ] Break the work into 2-3 phases
- [ ]  Phase 1 is an MVP that we aren't ashamed to use internally. It should take no more than 400 developer hours (1 developer, 3 months with no other assignments except meetings)

Estimate: 25 hours

**Comment by jordanh** [comment]
I believe we are settled on another direction. Please re-open if I'm wrong
