### ISSUE TITLE
GitHub Estimates: Update when querying GitHub

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5433]
Similar to what we do with Jira, when we query an issue from jira, we should compare its story points to the story points in our system. If they are different, we should update our system.

AC
- [ ] fetching an issue from github includes the labels and the most recent task estimate
- [ ] if the task estimate label is not found in the list of issue labels from github, then we add a new task estimate
- [ ] the new task requires a GitHubLabelName and label. the GHLN is going to be one of the labels attached to the issue. which one?
- [ ] for each issue label, we search the TaskEstimate table for that `WHERE "name" = staleEstimate.name` to rule out other labels for other dimensions. 
- [ ] if there are multiple labels attached to that issue, we pick the most recent one (i think updatedAt is a thing) and remove the others. Else, we just pick a random one

Estimate: 4 hours

**Comment by jordanh** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/7By0K1Cj6w/estimate/22) in “Sprint `#89` Scoping”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by igorlesnenko** [comment]
It seems that I need to store a pattern like `Story Value: {{#}}` in `TaskEstimate` table .
Otherwise no good unversal algorithm to determine that 2 labels are belong to same dimension.
Dimension name could be `Story Points` but the acual pattern could be anything.

**Comment by mattkrick** [comment]
See #5522. When this issue is fixed, it should be obvious what is causing the error in #5522
