### ISSUE TITLE
Reply by creating task UI bug

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5434]
when you reply to something in a discussion by creating a task an extra comment input appears beneath the task input. 

https://www.loom.com/share/572ad42e48324d7581ba7c4f2e6796ff

### Acceptance Criteria (optional)
Users can:
   - Reply in a discussion by creating a task w/o an extra distracting input appearing beneath

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
Iceboxing
