### ISSUE TITLE
Error dispatch(@mattkrick/graphql-trebuchet-client/lib/GQLTrebuchetClient)

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5438]
Affected 18 users in the last 11 days. Looks similar to #5381, looks like from 6.28.0 we changed the error handling of this.

https://sentry.io/organizations/parabol/issues/2654611644/?referrer=github_plugin

```
Error: Server error
  at dispatch (./node_modules/@mattkrick/graphql-trebuchet-client/lib/GQLTrebuchetClient.js:44:28)
  at call (./node_modules/@mattkrick/graphql-trebuchet-client/lib/GQLTrebuchetClient.js:9:18)
  at emit (./node_modules/eventemitter3/index.js:202:33)
  at WebSocket.<anonymous> (./node_modules/@mattkrick/trebuchet-client/lib/SocketTrebuchet.js:113:26)
```

**Comment by mattkrick** [comment]
this makes sense, i assume these are errors where no `data` field is received from the gql executor due to a server timeout.
related https://github.com/ParabolInc/parabol/issues/5406

**Comment by mattkrick** [comment]
AC
- [ ] the server should ALWAYS send an `{errors, data}` response in the event of a timeout.

**Comment by igorlesnenko** [comment]
As far as I see `Server error` is not a timeout error

It is returned here:

[https://github.com/ParabolInc/parabol/blob/9e1b280bc2246d90426fa892b9be8d38e38ed881/packages/server/graphql/handleGraphQLTrebuchetRequest.ts#L55](https://github.com/ParabolInc/parabol/blob/9e1b280bc2246d90426fa892b9be8d38e38ed881/packages/server/graphql/handleGraphQLTrebuchetRequest.ts#L55)

While timeout is handled separately here:

[https://github.com/ParabolInc/parabol/blob/9e1b280bc2246d90426fa892b9be8d38e38ed881/packages/server/graphql/handleGraphQLTrebuchetRequest.ts#L60](https://github.com/ParabolInc/parabol/blob/9e1b280bc2246d90426fa892b9be8d38e38ed881/packages/server/graphql/handleGraphQLTrebuchetRequest.ts#L60)

For timeout, the message would be `The request took too long`

In `sanitizeGraphQLErrors` we hide the real error message and replace it with `Server error`

So I checked the exact same error timings in Datadog, and it is most likely the following error:

```
SEND TO SENTRY [Error: Cannot return null for non-nullable field Task.plaintextContent.] undefined
```

Checking how is that possible

**Comment by mattkrick** [comment]
> Checking how is that possible

Super interesting! Looks like the seed card (the one that is created when a new user signs up) is the culprit, but I just did a spot check. there could be others.

perhaps the next step is a migration on the task table to generate plaintextContent from the rich content & see if the problem comes back? I wouldn't worry too much about it because when the Task table is moved to PG we'll be able to force non-null & write a little pre-update hook.

**Comment by igorlesnenko** [comment]
@mattkrick I have already managed to make the migration: #5869
I found about 2500 tasks in the rethinkdb that were missing the `plaintextContent`. Yes, looks like all of them are seed cards. The last card was created at `Wed Dec 09 2020 21:48:46 GMT+00:00` So the bug that caused this should not exist anymore.

**Comment by mattkrick** [comment]
fantastic! reviewed the PR. not sure if 2500 will crash our system or not, but willing to find out
