### ISSUE TITLE
Refactor EditCommenting mutation to support comments, tasks and polls

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5440]
Context: https://github.com/ParabolInc/parabol/issues/5145#issuecomment-899889116 

The idea is to have a common mechanism to notify other users about different events in the discussion threads. Currently, tasks are handled differently than comments and the mechanism is error prone.

Instead of having different mechanisms, let's create a standard way of handling that by refactoring a `EditCommentingMutation` into something like the following
```
editDiscussion(isEditing: boolean, discussionId: string, threadableType: 'task' | 'comment' | 'poll')
```

AC:
- [ ] refactor the way we display `X is creating a Task...` to use the new mechanism
- [ ] refactor the way we display `X is creating a Comment...` to use the new mechanism 
- [ ] get rid of any old functionality leftovers 

EE: 16h

**Comment by jordanh** [comment]
Scrubbing backlog today.

@BartoszJarocki when you have a moment could you add AC and EE then add this to the Sprint Board? thx!

**Comment by BartoszJarocki** [comment]
@jordanh added. Should I leave it in the `To Prioritize` column or move to the backlog?
