### ISSUE TITLE
DevOps: Jira Server instance set up

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5446]
## Issue - Enhancement

In order for us to develop against Jira Server, we'll need to set up a test instance. We have a license. Let's go!

### Acceptance Criteria (optional)
Parabol developers can:
   - Access Jira Server instance

**Estimated effort:** 12 hours

**Comment by adaniels-parabol** [comment]
@jordanh JIRA has been setup and I posted details in slack.
