### ISSUE TITLE
Proposed our stand-up direction and first steps

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5460]
### Acceptance criteria
- Reviewed the optional candidates (in Notion) that we’ve explored; added any additional information, links to screenshots, etc.
- Synced with Matt on bottom-up ideas
- Started the stand-up experiment (Jell or Geekbot); started competitor notes, etc.
- Made a proposal by end of sprint for our stand-up direction; consent-based
  - What future do we want to live in?
  - What’s the smallest step toward that future which we can ship by end of Q1 2022?

### Estimated effort
- 25 hours

**Comment by jordanh** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/7By0K1Cj6w/estimate/12) in “Sprint `#89` Scoping”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
The proposal [is in Notion](https://www.notion.so/parabol/Stand-up-Proposal-98d513d6593b4b64ad797580869484c3).

Next steps: we’ve gathered feedback internally, and now we’re scoping a milestone for the work
