### ISSUE TITLE
Build a .env getter

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5466]
builds should be .env agnostic. they are for the client, but we need to do that for the server, too. this means we won't have to do 3 separate builds for ironbank. also helps out for PPMI.

AC
- [ ] on the client, the server should send all .env vars as it currently does here: https://github.com/ParabolInc/parabol/blob/e35ac6c6a7c9004300c7d52280a20fda49f9af85/packages/server/createSSR.ts#L11-L19
- [ ] on the server, we need a getter that reads from a `.env` file that is not part of the build. so instead of `process.env.FOO` we have something like `getEnvVar('FOO')` which reads the .env from disk, caches it, & then returns that.
   
Estimate: 8 hours

**Comment by jordanh** [comment]
Lora is taking this one for her BP

**Comment by mattkrick** [comment]
Reviewed this with Lora & @adaniels-parabol today & realized that it's no longer an issue, our server webpack build already grabs vars from the environment & they are not hardcoded into the build.
