### ISSUE TITLE
Getting `ERROR:  must be owner of extension citext` when restoring PG backup

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5473]
## Issue - Bug
When I was deploying today, I couldn't restore the DB from backup in PG admin. 
The error I got: `pg_restore: error: could not execute query: ERROR:  must be owner of extension citext`
The only option I've used was `Clean before restore`

It'd be nice to investigate if there are any specific options needed to perform the restore or do the backup.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
should be harmless, but perhaps we should dump as SU? https://dba.stackexchange.com/a/247313

**Comment by jordanh** [comment]
@BartoszJarocki clarifying question, did the restore abort (i.e. was it fatal to the restore process) or was this just an error message that was emitted?

**Comment by BartoszJarocki** [comment]
I'm sorry @jordanh I somehow missed your question, Github notifications are the worst. I'm closing this as it's no longer relevant. We have nice scripts now!
