### ISSUE TITLE
Add noImplicitAny to server tsconfig (Part 2 of 8)

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5476]
When we migrated to typescript from javascript, it was too expensive to turn on `noImplicitAny` because it was hard enough just making the switch.

Today, having `noImplicitAny` could catch a lot of errors that I'm seeing in code reviews.
The problem is that there are 1600 errors!
This is too many for any one person to do in a sprint.
However, the benefit of having this turned on for new code is pretty great.

So, I propose we share the love & chip away at it:
- [x] turn on `noImplicitAny` in the server tsconfig file
- [x] fix ~200 errors
- [x] turn it off again in the tsconfig file & submit the PR
- [x] we'll merge it blindly
- [ ] create a copy of this issue named Part (3 of 8) so we can re-prioritize for the next person. We'll keep doing this until it's done

AC
- [ ] 200+ `noImplicitAny` errors are fixed in the server package

Estimate: 4 hours

**Comment by Dschoordsch** [comment]
Turning it on on master right now:
```
Found 1411 errors.
```

**Comment by Dschoordsch** [comment]
On fix/5476/fix-some-no-implicit-any
```
Found 957 errors.
```
