### ISSUE TITLE
Polls implementation: Show the overflow menu all the time

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5478]
This issue is part of **Polls implementation: EPIC #5147**

Context: https://github.com/ParabolInc/parabol/issues/5147#issuecomment-930549496 
We should be showing the `...` all the time. 

When a poll is being created the menu should contain only one option - `Delete`. 
When poll is already created but not ended - `Delete`, `Edit`
When poll is already ended - `Delete`

**Comment by jordanh** [comment]
Iceboxing
