### ISSUE TITLE
Stop writing User to rethink

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5483]
Requires: #5384, #4867 and #5507

When all reads for `User` come from PG we should stop writing to rethink

### Acceptance criteria
* [ ] `db.write` and `db.writeTable` are removed
* [ ] database/types/User.ts type is removed

**Comment by mattkrick** [comment]
@Dschoordsch by all means feel free to throw away the `db.write` pattern & go directly to the database or a dataloader!

the `db.write` pattern of caching the User object was primarily because I wanted to see if I could remove some pressure from RethinkDB. Postgres can certainly handle the additional queries so we don't need to cache so aggressively.

**Comment by jordanh** [comment]
@Dschoordsch before we stop writing to rethink, I'd very much like to have hired our Data Architect and coordinate this making this change We have a bunch of queries in https://github.com/ParabolInc/parabol-data-notebooks we use to keep tabs on various low level metrics. It'd be great to:

1. Get `User` moved over to a data warehouse or, failing that,
2. Update these notebooks to query from Postgres instead

**Comment by mattkrick** [comment]
scrubbed, still a thing

**Comment by Dschoordsch** [comment]
@tghanken can we stop writing to `User` in Rethink from your perspective?

**Comment by tghanken** [comment]
> @tghanken can we stop writing to `User` in Rethink from your perspective?

Yes, there's nothing on our end stopping this at this point.

**Comment by Dschoordsch** [comment]
@jordanh I still see this single `User` read in the mentioned notebooks https://github.com/ParabolInc/parabol-data-notebooks/blob/44152c7e57bf4c4952b959f958ac818838be3d36/Marketing/Users%20Last%20Seen.ipynb Is this used?

**Comment by tghanken** [comment]
I don't believe anyone is using those notebooks anymore.  Everyone should now be reading from BigQuery instead.  If necessary, I can submit a fix on that notebook code to move the read to Postgres, but I don't think it should stop us from moving forward with this issue.

**Comment by mattkrick** [comment]
fixed in #8116
