### ISSUE TITLE
Meeting Type illustrations updated

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#5484]
## Issue - Enhancement

We've created new Meeting Type illustrations in an updated style. We should updated the ones used in the app: 
- Do = Check-in 
- Learn = Retrospective
- Plan = Sprint Poker 

[Illustrations are saved here. ](https://drive.google.com/drive/folders/1NOByxTSgu46Ir_nEw-SBZyHqNhaQyIyP)

### Acceptance Criteria (optional)
Users can enjoy the lovely new illustrations. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by avivapinchas** [comment]
**Effort: 🍉**
  [See the discussion](https://action.parabol.co/meet/7rgp0tOoWk/estimate/2) in “Sprint Poker `#13`”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Confidence: 🐘**
  [See the discussion](https://action.parabol.co/meet/7rgHmNgnte/estimate/1) in “Sprint Poker `#14`”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Confidence: 🐘**
  [See the discussion](https://action.parabol.co/meet/7rh7m4YDza/estimate/1) in “Sprint Poker `#15`”

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by mattkrick** [comment]
:rofl: :skull:

**Comment by Dschoordsch** [comment]
@avivapinchas Does this include both the new meeting dialog and the meetings dash?
![Screenshot from 2021-12-13 14-31-45](https://user-images.githubusercontent.com/7331043/145821678-8cc82eab-5ff5-4d55-a359-2cccc0e04186.png)
![Screenshot from 2021-12-13 14-31-11](https://user-images.githubusercontent.com/7331043/145821681-1bdcddf4-3012-4fbd-9945-72a00a6b084b.png)

**Comment by Dschoordsch** [comment]
@avivapinchas Going with the same size as before, the new images have no background, so applying the same colour as before we get
![Screenshot from 2021-12-14 11-54-59](https://user-images.githubusercontent.com/7331043/145985638-26cc9932-b000-4b2a-b026-a5aa99294947.png)
I'm a bit unsure about the blue and the haircolour, but compared to all the same colour
![Screenshot from 2021-12-14 11-55-29](https://user-images.githubusercontent.com/7331043/145985707-e94581e1-6560-4644-93f5-bac4449706c2.png)
I think it looks better. What do you think?

Keeping the colours also makes it easier for existing costumers.

**Comment by enriquesanchez** [comment]
@avivapinchas @Dschoordsch 

I'm going to try these new illustrations on both the meetings view and the new meeting dialog to find what background colors work best.

I will update here once I have some direction for these.

**Comment by acressall** [comment]
@Dschoordsch here are the updated illustrations to use:
[meeting-illustrations.zip](https://github.com/ParabolInc/parabol/files/7737359/meeting-illustrations.zip)

Background colours:

- Sprint Poker: `#FD7F77` (tomato400)
- Check-In: `#55C0CF` (aqua400)
- Retro: `#A06BD6` (grape500)

Designs for reference: https://www.figma.com/file/cKIkD2c3fgoO8QigBDuGiS/Meeting-Cards?node-id=1%3A1892

**Comment by Dschoordsch** [comment]
@acressall I updated the colours, the bottom line is not aligned in the images, basing the offset on the overlapping octopus I get this
![Screenshot from 2021-12-20 10-45-15](https://user-images.githubusercontent.com/7331043/146751158-9839c331-c85e-48ec-8777-7955ad2347a7.png)

I also updated the new meeting dialog, but did not adjust all the offsets to match Figma since it's going to be replaced
![Screenshot from 2021-12-20 11-09-19](https://user-images.githubusercontent.com/7331043/146751273-ab3d6577-d730-49da-b6e6-56f96ab6de94.png)

What about the mobile view? Right now it has no background and I think that's fine?
![Screenshot from 2021-12-20 11-09-27](https://user-images.githubusercontent.com/7331043/146751356-319cd6cf-0126-4b6e-84a8-da8eefb3c47b.png)

**Comment by acressall** [comment]
This looks great! The mobile view is fine with no background, since it's full-width. Thanks @Dschoordsch!

**Comment by mattkrick** [comment]
@acressall @enriquesanchez is it possible to get these in vector vs raster? the vectors will be a little higher quality & more flexible (plus they're a little smaller!)

**Comment by enriquesanchez** [comment]
@mattkrick Oh, I had assumed we were using SVG for these! Yeah, totally agree we should use vector instead.

Looking at what is in the shared drive, we only have PSD and PNG for these. @acressall I don't have Photoshop so I can't check if these can be exported as vector. Do you know if we have vector versions or if these can be exported as vector?

**Comment by acressall** [comment]
@enriquesanchez @mattkrick these have been created as rasters, to allow for some of the texture and hand-drawn feel

**Comment by Dschoordsch** [comment]
@acressall can we modify the pictures so that the bottom edge is consistent? There doesn't need to be a line, but when the kraken is supposed to overlap the background, the bottom line should have the same distance for all images.

**Comment by acressall** [comment]
[meeting-illustrations.zip](https://github.com/ParabolInc/parabol/files/7802836/meeting-illustrations.zip)

Updated @Dschoordsch – I also made them larger for better resolution, but there's lots of room for you to compress them if you need to!

**Comment by Dschoordsch** [comment]
I resized them down to the previous 600px height since the largest we show them is 300px, that should be plenty.
