### ISSUE TITLE
MyDashboardTimelineQuery failing for some users

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5492]
Affected 7 users in the past 16 days.

https://sentry.io/organizations/parabol/issues/2661484738/?referrer=github_plugin

```
RelayNetwork: No data returned for operation `MyDashboardTimelineQuery`, got error(s):
Server error

See the error `source` property for more information.
  at createError (./node_modules/relay-runtime/lib/util/RelayError.js:25:13)
  at create (./node_modules/relay-runtime/lib/util/RelayError.js:52:24)
  at forEach (./node_modules/relay-runtime/lib/store/OperationExecutor.js:374:32)
  at _handleErrorResponse (./node_modules/relay-runtime/lib/store/OperationExecutor.js:362:15)
  at _handleNext (./node_modules/relay-runtime/lib/store/OperationExecutor.js:439:34)
...
(20 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
I get this error when trying to open our sprint poker https://action-staging.parabol.co/meet/aGjmYpJBIs raising priority.
Tested on staging, seems to be a `Taskintegration` issue with `Bad credentials` error, maybe wrong/expired GitHub token is used [[DD]](https://app.datadoghq.com/logs?cols=host%2Cservice&context_event=AQAAAX8d6hN-x6eIBQAAAABBWDhkNmhPZUFBQkJvTzVFYTMxRVBnQUE&event=&from_ts=1645474334422&index=%2A&live=false&messageDisplay=inline&query=host%3Aaction-staging-web-nyc1-02+service%3Aweb+container_id%3A1307347a7fdeb26c4d84d24b262e614666f8a1730102a423fcb143b3b033ab4f&saved_view&stream_sort=desc&to_event=AQAAAX8d6hN-x6eIDwAAAABBWDhkNmhPZUFBQkJvTzVFYTMxRVNBQUE&to_ts=1645474354047&viz=)

**Comment by Dschoordsch** [comment]
Might be related to #5439

**Comment by jordanh** [comment]
Affected 36 users in the last 60 days, happening 154 times. Going to keep this one open

**Comment by jmtaber129** [comment]
Closing, as this particular issue was last seen two months ago on Jan 5, 2023.
