### ISSUE TITLE
UTM parameters added to meeting and team invite links

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#5494]
## Issue - Enhancement

Right now, invitation links (either for a team or meeting) do not include UTM parameters. This means that in our various data tools (Amplitude, Google Analytics, Hubspot), it's hard to separate traffic that came from an invitation link from other traffic. 

Discussion with @mattkrick on implementation on Slack: 
>  we use a short URL to make the link easy to share & then we have a DNS record that just says "hey, when you see prbl.in/FOO goto action.parabol.co/invitation-link/FOO
> so we'd need to update that record to say hey goto action.parabol.co/invitation-link/FOO?utm_source=invite%20link&utm_medium=product&utm_campaign=invitations

Per our [UTM guidelines 🔒 ](https://www.notion.so/parabol/UTM-Parameters-Guidelines-f2e1ada7e80042ff90a304d6511d9e27), we should add: 
- For meeting invite links, utm_source=`meeting invite link` 
- For team invite links, utm_source=`team invite link`

For both, utm_medium=`product`, and utm_campaign=`invitations`. 

### Acceptance Criteria (optional)
Parabol team can see which traffic came from invitation links. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
since the UTM parameters are constant given the `/invitation-link` route, then inside the app we could just redirect to the same route with those UTM params. that won't get us an accurate utm source though. TBH i'm not sure if we store that utm source anywhere.

as a cheap no-code alternative, couldn't we just check traffic to /invitation-link?

@Dschoordsch: do we have 2 different invite links? maybe we put a prefix on the token itself?

**Comment by avivapinchas** [comment]
> as a cheap no-code alternative, couldn't we just check traffic to /invitation-link?

I think that's a Q for me, but lmk if I misunderstood. 

The challenge isn't understanding traffic, it's understanding users and conversions. 

I'll give you two use cases: 
**1. Google Analytics: sign-ups by source**
Today, if I wanted to see where our sign-ups come from, to separate folks coming through from the invite link, I'd need to pull a report with landing page and source, export it, edit the spreadsheet, and then I have an answer. If I wanted to see any other data comparing sign-ups, I'd need to do it again. 

**2. Amplitude: user behavior by source**
"Landing Page" isn't a concept in Amplitude. I could see folks who loaded that page, and create behavior funnels based on that event, but I'd have to manually add different sources as user segment to compare them - I couldn't compare based on source.

**Comment by jordanh** [comment]
I'm going to remove this from the backlog and request the @tianrunhe and/or @tghanken add it to theirs...
