### ISSUE TITLE
Implement menu bar ARIA pattern for the dashboard's side navigation

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5497]
## Issue - Enhancement

Screen-reader and keyboard navigation would be greatly improved if we implemented the [ARIA menu bar pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) on the dashboard's sidebar navigation.

<img width="260" alt="Screen Shot 2021-10-06 at 6 29 42 p m" src="https://user-images.githubusercontent.com/3276087/136297358-d263f1b2-3620-4ef7-b6d1-a23c8d16927f.png">

The menu bar ARIA pattern will make the nav component a single tab stop, making screen-reader and keyboard navigation more efficient. Once users land on the menu bar element, navigating the list of options is done with the up/down keys. Pressing the TAB key again navigates the user to the next component of the page.

[See the implementation example here](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html).

### Acceptance Criteria

Screen reader and keyboard users can:
   - Navigate to the sidebar nav with <kbd>TAB</kbd>
   - Use <kbd>Up</kbd>/<kbd>Down</kbd> to move between the list of items in the sidebar nav
   - Navigate out of the sidebar nav with <kbd>TAB</kbd>

**Comment by enriquesanchez** [comment]
Maybe this issue is like wine, and instead of going stale, it gets better with age 😄

**Comment by jordanh** [comment]
@enriquesanchez, iceboxing. Let me know if you'd like me to reopen
