### ISSUE TITLE
Migrate data-notebooks to a data warehouse reading from postgres

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5507]
Before we stop writing to rethink, I'd very much like to have hired our Data Architect and coordinate this making this change We have a bunch of queries in https://github.com/ParabolInc/parabol-data-notebooks we use to keep tabs on various low level metrics. It'd be great to:

1. Get `User` moved over to a data warehouse or, failing that,
2. Update these notebooks to query from Postgres instead

_Originally posted by @jordanh in https://github.com/ParabolInc/parabol/issues/5483#issuecomment-940608697_

**Comment by tghanken** [comment]
Added.  Do we want this issue to continue to live here, or move to our data repo?

**Comment by Dschoordsch** [comment]
@tghanken is this still a thing? Can this issue be closed?

**Comment by tghanken** [comment]
Are people still actively using the data notebooks today?

We should fully migrate all queries to the data warehouse rather than direct PG/Rethink reads.  I'm in favor of closing this issue and tracking on https://github.com/ParabolInc/parabol-data-sanctum/issues/374 instead.
