### ISSUE TITLE
Improve link UI in Poker description

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5509]
In Sprint Poker, the description imported from GitHub or Jira can contain links. In Parabol, the link doesn't have a text-decoration underline. It does act as a link in every way other than the underline, i.e. the cursor becomes a pointer on hover and clicking the link takes the user to the page.

The link doesn't necessarily look like a link which may be why it doesn't have the underline. For example, in the description in the image below, I'd expect `parabol/packages/server/utils/PubSubPromise.ts` to be underlined. Screenshot comes from the following issue: https://github.com/ParabolInc/parabol/issues/5189

![Screenshot 2021-10-12 at 09 30 07](https://user-images.githubusercontent.com/39854876/136976227-019360e6-7d8b-4760-8db9-50b9db1537af.png)

**Comment by jordanh** [comment]
Iceboxing
