### ISSUE TITLE
Sprint poker Jira issue field shows fields from all task types

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5519]
## Prerequisite:
* Create Jira project(s) with different task types
* Start Sprint poker
* Import multiple different task types
* Start voting

## Expected
The story point drop-down shows only fields which are applicable to the task at hand.
(It might also offer to create fields once #5134 is fixed)

## Actual
It shows a union of all task type fields (+some more)
![Screenshot from 2021-10-14 10-33-31](https://user-images.githubusercontent.com/7331043/137282460-3f2c6318-6f0b-4ef3-82c7-4d51787a4bf6.png)
Picture shows 2 issue types, Task with "Exclusive Task Points" and Bug with "Bug legs", both showing up at once, also "Story Points" and "Story Points Estimates" which is not part of any of them.

**Comment by mattkrick** [comment]
let's do this when we do #5211 to better the filters
