### ISSUE TITLE
Team management side sheet includes email information

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5526]
There may be many use cases for displaying a user’s email information in the manage team side sheet. Here’s one:

>When looking to manage my team in the side sheet, I want to see emails so that I can remove duplicates of folks using both a work email and their personal email (or communicate about it with that person, first).

### Acceptance criteria
- Designed 1 or many quick concepts showing options for how and when to display email information (e.g. on hover, as a second line, etc.) with any related notes
- Drafted an implementation issue pointing to the chosen concept

### Estimated effort
- 5 hours

**Comment by avivapinchas** [comment]
**Value: 2**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/19) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: SM**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/20) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: XS**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/20) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
