### ISSUE TITLE
TypeError c(packages/client/components/Dashboard) Cannot read properties of undefined (reading 'flatMap')

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5529]
See [Sentry.io](https://sentry.io/organizations/parabol/issues/2716536744/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d):

TypeError
Cannot read properties of undefined (reading 'flatMap')

./packages/client/components/Dashboard.tsx in c at line 88:32

```
    queryRef,
    {UNSTABLE_renderPolicy: 'full'}
  )
  const {viewer} = data
  const {teams} = viewer
-->  const activeMeetings = teams.flatMap((team) => team.activeMeetings).filter(Boolean)
  const {isOpen, toggle, handleMenuClick} = useSidebar()
  const isDesktop = useBreakpoint(Breakpoint.SIDEBAR_LEFT)
  const overLimitCopy = _optionalChain([viewer, 'optionalAccess', _ => _.overLimitCopy])
  const meetingsDashRef = useRef(null)
  useSnackNag(overLimitCopy)
```

Affecting 97 users since release of 6.32.0

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
No longer happening
