### ISSUE TITLE
Better integration visibility

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5533]
## Issue - Enhancement

After integrating a service the only way to see it is to go to settings. It always gives me the impression it is team-related.
It'd be nice to have a more clear way of showing active integrations and making sure users know it's personal.
Related conversation: https://parabol.slack.com/archives/C836NA350/p1634140455441800 

### Acceptance Criteria (optional)

- [ ] Integrations have better visibility and it's clear they're personal, not a team related

### Estimated effort
- 8 hrs for design exploration

**Comment by jordanh** [comment]
See also: #5534

**Comment by enriquesanchez** [comment]
> It always gives me the impression it is team-related.

#5875 might help with this

**Comment by enriquesanchez** [comment]
I think what's proposed in #5875 partially solves this, but I'll keep this one open because there's more to address here.

**Comment by jordanh** [comment]
Closing in favor of #5939
