### ISSUE TITLE
Suggest integration after pasting GitHub / Jira link

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5534]
## Issue - Enhancement

To increase integration usage, suggest integration when the user pastes a GitHub / Jira link in a Parabol task
Related conversation: https://parabol.slack.com/archives/C836NA350/p1634140455441800 

### Acceptance Criteria (optional)

- [ ] When GitHub / Jira link is detected a suggestion to integrate is displayed

### Estimated Effort
- 6 hrs for design exploration

**Comment by mattkrick** [comment]
We might want to move to tiptap before we invest more in draftjs see #5431

**Comment by enriquesanchez** [comment]
We also need to think about what is the added value the integration brings when pasting a link. 

Are we going to show richer content, such as previews and embeds, that update live?

**Comment by enriquesanchez** [comment]
When we detect that a link to an integration that we support has been added to a task, reflection, or comment thread, we can display a little popup on the top right corner of the window that prompts the user to connect to said integration:

![image](https://user-images.githubusercontent.com/3276087/148846628-f02390e5-6207-403d-ab95-6b559745cd6a.png)

I suggest the top right corner for two reasons:

1. It's generally easier to see UI elements when they appear on the upper part of the window. Anything on the bottom side is more obscure and easier to miss.
2. We already have the 'Start meeting' CTA on the bottom right, and I didn't want to cover it.

The language of the popup can vary, and **would love to hear if you have any suggestions for improving it**, but for now I'm proposing something like:

```
That looks like a  GitLab link.
Connect to GitLab for a more streamlined experience. Learn more.
```
Replace GitLab with any other integration we support.

![image](https://user-images.githubusercontent.com/3276087/148847482-6d3ee604-04b1-4e6b-b6f8-343914eb4b5f.png)

The popup should comply with the following **acceptance criteria**:

- [ ] The popup should be easily dismissable (close button)
- [ ] The popup should be smart and only appear if the integration has not be added yet, or if the popups has not been previously dismissed.
- [ ] The popup should include a 'Learn more' link to a support article, for example `https://www.parabol.co/integrations/jira`
- [ ] Clicking 'Connect' should let you connect the integration without leaving the current view. We can show a popup window or modal in place. See #5567 for more detail.

How should we deal with cloud vs. self-hosted integrations? When supporting both, how do we know which one the user would prefer?

We don't, and I think we should ask first. #5567 has some [design solutions that should also work here](https://github.com/ParabolInc/parabol/issues/5567#issuecomment-967700027).

**Comment by enriquesanchez** [comment]
I mentioned this in a previous comment, but I think we are going to have to follow up with clarifying what added value brings connecting an integration, particularly in these scenarios where it's only a link being pasted or added.

- Should we show richer embeds?
- Should these update live?

**Comment by jordanh** [comment]
@enriquesanchez, I'm not sure how to trigger it, but our Task cards have an error state where we can show a message when something fails. I wonder instead of the modal, we put this message on the task card itself? Something like:

|--------|
| Task card content with GitHub link |
|--------|
| *That looks like a GitHub link.* Connect Parabol to GitHub for a more streamlined experience. |

**Comment by enriquesanchez** [comment]
@jordanh This is great, thank you! I was not aware we had a pattern like this. Your suggestion prompted me to explore a little more and I came up with the following alternative:

Considering that we adopt the pattern proposed in https://github.com/ParabolInc/parabol/issues/5535#issuecomment-1016963149, we can have the following flow:

When a user pastes a link from an integration or 3rd party service that we support, we:

**1. Allow the action of pasting a text link to happen, but at the same time we prompt the user to make a choice:**
  
<img width="347" alt="Captura de Pantalla 2022-01-21 a la(s) 3 31 59 p m" src="https://user-images.githubusercontent.com/3276087/150602873-5a8f4be0-766b-47ff-83cf-fd6734ad9ca3.png">

a) If I continue to type or press `ESC`, the popup goes away.
b) If I select `Paste as link` the popup goes away and I continue with my text editing.
c) If I select `Paste as attachment` the link goes away, I get a link embed instead and I can continue with my text editing.

(Maybe we add a 3rd option `Ignore and don't ask me again` 🤔)

**2. Once a choice has been made in the previous step, then we suggest the integration:**

a) If I chose to paste the link as regular text

<img width="330" alt="Captura de Pantalla 2022-01-21 a la(s) 3 37 10 p m" src="https://user-images.githubusercontent.com/3276087/150603655-2bfbebfa-183c-402b-bb48-4f81712c48ae.png">

b) If I chose to paste the link as an attachment:

<img width="323" alt="Captura de Pantalla 2022-01-21 a la(s) 3 44 44 p m" src="https://user-images.githubusercontent.com/3276087/150604247-84e48bdc-89ba-43a9-a938-8ed6579430b7.png">


**3. From here, I can either go through with connecting the integration, or dismiss the little banner.**

If I go through and connect the integration, I now see richer content.

a) If I pasted as link:

<img width="322" alt="Captura de Pantalla 2022-01-21 a la(s) 3 42 36 p m" src="https://user-images.githubusercontent.com/3276087/150604004-190d5ee7-1b4f-428c-a106-71a52af57559.png">

b) If I pasted as attachment:

<img width="326" alt="Captura de Pantalla 2022-01-21 a la(s) 3 46 23 p m" src="https://user-images.githubusercontent.com/3276087/150604428-8d9f8901-8af8-4b35-abd0-d69443ddd70c.png">

If instead I chose to dismiss the banner, we remember that choice and don't prompt the user again.
