### ISSUE TITLE
Investigate Atlassian GraphQL API

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5539]
Atlassian now offers a GraphQL API: https://developer.atlassian.com/platform/atlassian-graphql-api/graphql/#authentication

We should see if we can use this. It would make life SO much easier as we grow our atlassian integration.

AC
- [ ] investigate the API, see if it is worthwhile to replace our current integration pattern
- [ ] if it's worthwhile, create a handful of issues to migrate our AtlassianManager to using GraphQL

Estimate: 8 hours

**Comment by jordanh** [comment]
@Dschoordsch I think your work with #5563 concludes that the GraphQL is insufficient/does not exist for Jira Server, so we may close this one. Yes?

**Comment by Dschoordsch** [comment]
@jordanh you're correct, there is no GraphQL API for Jira Server. REST API for Atlassian Cloud and Jira Server is different anyway, so we could still migrate Atlassian Cloud to GraphQL.
