### ISSUE TITLE
Spotlight UI: matched results in one column if there are only a few

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5544]
## Issue - Enhancement

Predecessor: https://github.com/ParabolInc/parabol/issues/5390

From https://github.com/ParabolInc/parabol/pull/5469#discussion_r731346707:

> In [Enrique's Loom](https://www.loom.com/share/4e8f8b4e12e8417b8675e994b06d3cec) which he linked here #5105, he suggested that we return the results in one column if only a few are returned

i.e., These results should be in one column rather than 3:
![Screen Shot 2021-10-19 at 3 00 19 PM](https://user-images.githubusercontent.com/1879975/137996747-2eee0a68-7c4a-4c02-a157-df4f1c65077a.png)

### Acceptance Criteria (optional)
- [ ] If there are a few matched reflection cards returned, they should be in one column

**Comment by nickoferrall** [comment]
This issue was fixed by https://github.com/ParabolInc/parabol/pull/5402. Closing now
