### ISSUE TITLE
Spotlight UI: matching keyword should be highlighted

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5545]
## Issue - Enhancement

Predecessor: #5469 

In search query case, the returned matched reflection groups should highlight the matching keyword, like:

![Screen Shot 2021-10-19 at 3 07 30 PM](https://user-images.githubusercontent.com/1879975/137997484-ed7c432a-8d5f-4da2-97dc-c116d856cb9e.png)

See [Figma](https://www.figma.com/file/u5bdWUn9hxkdvS2YOYDnXU/Spotlight?node-id=56%3A0) for more detail

### Acceptance Criteria (optional)

- [ ] When a user searches a keyword in Spotlight, the returned reflection cards should highlight the matching keyword.
- [ ] If the matched reflection card is deep inside a reflection group, that card should pop up on the top at the stack. 
	> If the user searches "kitten" and there's a group with two reflections, one with "cat" at the top of the group stack and "kitten" underneath, the "cat" group shows up even though we can't see the word "kitten".

**Comment by nickoferrall** [comment]
We want to highlight a reflection that matches the query even if it’s not at the top of the stack. An alternate approach to popping-up the reflection to the top of the stack (see the 2nd checkbox in the AC) could be changing the opacity of the reflections that are on top of the reflection that matches the search query. That way, the user is still aware that the reflection is nested within the group, but they can also see that it matches the query.

**Comment by igorlesnenko** [comment]
For now implemented the approach with card popping-up to the top of the stack. See video here: #5716

I also tried to I tried to experiment with changing opacity:

**Opacity: 0.2**

![image](https://user-images.githubusercontent.com/466991/142882603-4ec82b7f-6039-453c-bc5f-ddd4be6cc000.png)


**Opacity: 0.09**
![image](https://user-images.githubusercontent.com/466991/142882464-8c3822c5-90f1-46d0-ad89-8d8d51f2e34c.png)


**Opacity: 0.05**

![image](https://user-images.githubusercontent.com/466991/142882152-cc8d8521-85ed-41c3-8639-0babe0421d6d.png)
