### ISSUE TITLE
Deployment Reliability: Disable refetch queries on new version bump

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5548]
Today when a disconnect occurs, the frontend will refetch all queries to make sure the data is still fresh.
This is the right thing to do if they were disconnected for a handful of seconds, e.g. a mobile device going through a tunnel.
This is the wrong thing to do when we push a new version out, because the time disconnected is likely < 1 second.

AC
- [ ] Determine if we should disable refetches based on a version bump or a disconnected duration. Pick a side & fight me
- [ ] Implement the refetch logic to first check the disconnect duration (or version bump). Only trigger a refetch if necessary. If it is necessary, consider adding a long jitter

Estimate: 8 hours

**Comment by Dschoordsch** [comment]
6.36.0 release deployment resulted in 5min outage, we should prioritize this issue.

**Comment by igorlesnenko** [comment]
@mattkrick I would prefer the version bump approach.

If we go with measuring disconnect time, I'm not sure if it is possible to select that `REFETCH_AFTER` variable correctly:

- If `REFETCH_AFTER = 1 second`, there is no guarantee that the next deploy will not take `1.1 seconds`
- If `REFETCH_AFTER` would be big enough, we might miss a case of `mobile device going through a tunnel`

Checking the version would guarantee that we always handle only a particular redeploy-disconnect case.

Another question is: do we care about theoretical desynchronisation that might occur in this short period of time (<1 second)? 

As soon as we figure out that we don't want to refetch, we can show some snackbar with the text "You’re offline, refresh"?
Or alternatively, we can show it if redeploy-disconnect took some big time.

What do you think?

**Comment by igorlesnenko** [comment]
@mattkrick I created a PR with a version bump approach for now #5749: Left some comments in self-review there.
What do you think?

**Comment by mattkrick** [comment]
> Another question is: do we care about theoretical desynchronization that might occur in this short period of time (<1 second)?

Nope! With the socket heartbeat we can catch anything over 15s, which is probably OK.

> As soon as we figure out that we don't want to refetch, we can show some snackbar with the text "You’re offline, refresh"?
Or alternatively, we can show it if redeploy-disconnect took some big time.

I think the magic all revolves around this line: https://github.com/ParabolInc/parabol/blob/2b26b54a11ecab8569149274978c48dae3123de1/packages/client/hooks/useTrebuchetEvents.ts#L58

Maybe we do something as simple as
```ts
if (oldVersion == newVersion) {
  atmosphere.retries.forEach((retry) => retry())
}
```

TBH I'm not sure if you can read directly from __APP_VERSION__ or if you'll need to wait for the `onData` callback to fire with `obj.version`. To test we'll need to run `yarn build` so the serviceworker kicks in, which will change how __APP_VERSION__ updates

**Comment by igorlesnenko** [comment]
@mattkrick `__APP_VERSION__` only changes if the user reloads the page. The only way to know if the backend is now having a different version is to check `obj.version` in `onData`: #5749

**Comment by igorlesnenko** [comment]
#5749

**Comment by jordanh** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/8Kr615RAwE/estimate/11) in Sprint Poker #​​9

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
