### ISSUE TITLE
GitLab Architectural Spec Written

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5564]
Adding support for GitLab is [a commonly requested feature](https://github.com/ParabolInc/parabol/discussions/5456) and one we're contractually obligated to deliver. We're currently unsure what it would take to implement it. Let's remove this ambiguity.

N.B: @adaniels-parabol can grant the person who takes this issue access to our Gitlab instance

### AC
   - Spec written in GitHub with high-level proposal on how implementation proceed, [see this as an example](https://github.com/ParabolInc/parabol/issues/4412#issuecomment-948003051)
   - After spec reviewed by Review & Maintainer, Epic created and Issues created (including design and implementation issues) and added to Epic
   - Things to consider:
       - Do we only support the cloud-hosted version of GitLab first or both self-hosted and cloud (see: #5567)?
       - Which authentication modes do we support (Oauth, personal, or project tokens? see: #5567)
       - Which API do we use, REST or GraphQL? If GraphQL, can we nest the schema as we do with GitHub?
       - How might our database and GraphQL schemas need to change?
       - What are the impacts to Sprint Poker, to Task pushing?
    - Close #3971 along with this issue

### EE
   - 21 hours

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/10) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by nickoferrall** [comment]
@jordanh I'd be happy to volunteer for this one

**Comment by mattkrick** [comment]
From #5567 
There's a good image of how self-hosted should look
![foo](https://user-images.githubusercontent.com/3276087/141006244-ea217e48-9124-44a3-a0ae-8a6f7afa3880.png)

We may need an additional dropdown at the bottom for them to select an already-existing self-hosted solution that exists within their org, but aside from that it'd be a good jumping off point

**Comment by mattkrick** [comment]
Closing in favor of #6058
