### ISSUE TITLE
Design: supporting self-hosted services

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5567]
## Overview

Extending Parabol to support self-hosted integrations in addition to the multi-tenant SaaS integrations we already support takes careful consideration. There are some useful patterns from other tools we can look at. There are also some interesting questions raised by envisioning the user's journey when using our app. Let's start by illustrating this journey.

### User journey

Imagine an agile Team Leader working at a security-sensitive organization. Many of their team's tools are self hosted: They use Mattermost (see: #4412) for short messaging and GitLab (see: #5564) for backlog management and CI/CD. Our Team Leader wants to use Parabol to help facilitate their agile meetings and workflow, and wants to begin by running a Sprint Poker meeting with their team. When they run a test Sprint Poker meeting, they see GitLab is supported, they want to add the GitLab integration so that they can import their GitLab Issues for scoping.

### Present state

When an integration is added by a user today, they may navigate to the Team→Settings→Integrations area _or_ they may add the integration via an in-line affordance—such as during the Sprint Poker Scope phase. Adding an integration, such as GitHub, will trigger an oauth authentication to fetch a token that can be used on behalf of the user/team to access the service provided by the integration. In all cases, Parabol will raise a popup browser window to begin the authenticate with the integration provider's service.

However, how will our journey change to support selecting a self-hosted oauth provider?

### More questions

Where will users go to add additional oauth providers (i.e. self-hosted services)? Which users can add these additional providers?

Will we support multiple self-hosted servers per team for the same integration (i.e. two Jira Server instances on the same team)? How will users select which oauth provider to use?

How will users choose between a canonical public SaaS service (i.e. Jira Cloud) and a self-hosted service (i.e. Jira Server)?

Not all self-hosted servers have oauth enabled by default, most (all?) also provide the ability to manually generate a personal acces token ([GitLab's personal access token ](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) ("PAT"); Jira Server and Mattermost also have the same affordances), should we support adding services via an access token? If we do, should we support adding services via oauth _and_ access tokens?

## Options

| option | nickname | oauth config location | token types |
| :-----: | :----- | :-----: | :-----: |
| 1 | `the full monty` | per team | both |
| 2 | `PAT overrides central oauth` | per org | both |
| 3 | `access token only` | n/a | personal access token |
| 4 | `centralized oauth` | per org | oauth |

1. `the full monty` – each team can add any number oauth services or personal access tokens. 
**Pros:** able to serve the most complex teams, particularly those who have multiple backlogs on multiple servers
**Cons:** longer time time to market; most complicated; no data that this solution is needed

2. `PAT overrides central oauth` – teams inherit oauth configs from their Org, supports PAT to get going without admin intervention
**Pros:** nearly as flexible as (1); only loses users where PATs have been disabled and admins won't add oauth config
**Cons:** the same cons as (1)

3. `access token only` – each user adds their PAT to their team
**Pros:** users may add project or user-level access tokens, compared to (4) requires no admin setup (more bottom-up)
**Cons:** will require UX/UI design before implementing; users may specify incorrect scopes when creating their own tokens; some tools (e.g. Mattermost) disable PATs by default

4. `centralized oauth` – Org admin must add oauth service, use it by default if set
**Pros:** creates a compelling reason to upgrade to Enterprise if we make adding custom oauth servers an Enterprise feature; can use similar integration additional flow today (i.e. pop oauth window); does not prevent us from pursuing options (2) or (1) down the road
**Cons:** some tools disable oauth by default (e.g. Mattermost & self-hosted Gitlab)

### Additional considerations

For each option above, additional functionality must be chosen:

* Are cloud and self-serve integrations listed and configured separately (i.e. Jira Cloud and Jira Server)?
* Are multiple self-hosted servers supported per Org or Team?

## Proposal

Given the options above, I suggest we:

* Elect **option 4, `centralized oauth`** plus:
   * List cloud and self-hosted integrations separately—i.e. one entry for Jira Cloud and another Jira Server
   * Initially disallow for adding multiple oauth services per Org

For the below user journeys, we'll use Jira Server as an example.

### Primary journey

1. When a user wishes to add Jira Server, they'll navigate to either the Team→Settings→Integrations area or click on a button to add the integration from the Scope Phase
2. If an oauth connection does not exist on the Team's Org, a modal appears asking for the user to set the server url, client id, and secret. If the oauth connection does exist on the Team's Org, the modal does not appear and the user proceeds directly to the Jira Server oauth popup
3. If the user was the first on the Org to add the Jira Server oauth application configuration, they receive the role of `Integration Admin` at the Org level (note: all `Billing Leaders` also have the permissions necessary to create/read/update/delete oauth service configurations)

Why a modal in step (2), above? Because this component can be reused in both Team→Settings→Integrations or in-band during a meeting

### Future journey considerations

Should we wish to support multiple oauth services per org or add PATs, rather than pop an oauth model right away we can pop a modal to specify for additional information. This modal would ask:

1. does the user wish to use oauth or PATs?
2. does the configuration already exist, or does a new configuration need to be added?

### AC

A set of UX/UI designs that:
- Illustrate the Primary journey, above in high fidelity
- Extend the Organization menu to CRUD oauth configurations under Organization→Integrations  for users carrying the `Billing Leader` or `Integration Admin` roles
- Extend the Organization→Members menu for `Billing Leader` or `Integration Admin` to add/remove the `Integration Admin` role

### EE
* 13 hours

**Comment by enriquesanchez** [comment]
@mattkrick Pinging you because Jordan is currently not available and I'm a little confused by this part on the user journey described above:

>If an oauth connection does not exist on the Team's Org [...]

Why would an ouath connection exist if they haven't added the integration? Where is this done?

**Comment by enriquesanchez** [comment]
### Designs for primary journey


>1. When a user wishes to add Jira Server, they'll navigate to either the Team→Settings→Integrations area [...]

![imagen](https://user-images.githubusercontent.com/3276087/141004950-3ddd7950-64b2-4416-a0fb-3ef2f07bd456.png)


>2. If an oauth connection does not exist on the Team's Org, a modal appears asking for the user to set the server url, client id, and secret

![imagen](https://user-images.githubusercontent.com/3276087/141006244-ea217e48-9124-44a3-a0ae-8a6f7afa3880.png)


**Note:** Each field has a `?` button next to the label. Hovering/tapping it should show a tooltip with info on how to obtain the requested info.
**Note:** If there's a support article available, there is a `Need help?` link at the bottom-left corner that should point to it for additional information.


> 2. [...] If the oauth connection does exist on the Team's Org, the modal does not appear and the user proceeds directly to the Jira Server oauth popup

![imagen](https://user-images.githubusercontent.com/3276087/141006120-3848821b-10de-44a2-b952-f6f28a8f581c.png)

**Note:** The actual Jira Server oauth  popup might look a little different.

>3. If the user was the first on the Org to add the Jira Server oauth application configuration, they receive the role of Integration Admin at the Org level (note: all Billing Leaders also have the permissions necessary to create/read/update/delete oauth service configurations)

![imagen](https://user-images.githubusercontent.com/3276087/141007739-1c806c7b-f148-4502-8401-be80da3b759e.png)

----

### Some nice to haves

For clarity it'd be nice to separate the `active` from the `non-active` integrations on the Integrations page. Something like this:

![imagen](https://user-images.githubusercontent.com/3276087/141010002-e5cd1a5a-5126-44de-bd14-e53c4e1d2c77.png)

----

### Next steps:

- [ ] Review proposed designs
- [ ] Flush out implementation issues based on technical and design specs

**Comment by enriquesanchez** [comment]
Moving to review. @ackernaut Would appreciate a second pair of eyes here 🙏

**Comment by mattkrick** [comment]
> When a user wishes to add Jira Server, they'll navigate to either the Team→Settings→Integrations area [...]

>> For service providers that support both a self-hosted and cloud option (like Jira Server and Jira Cloud) we only present a single integration list (or a single tab under something like the Sprint Poker Scope phase)—initially we only allow folks to enable the self-hosted or SaaS integration for their team

I think it's worthwhile seeing a design that shows "Jira Server" next to the existing "Atlassian" because the 2 look so similar. We need a way to disambiguate the 2 as much as possible so folks don't get confused & accidentally click the self-hosted version when they want the cloud version. The same will be true for "GitLab" and "GitLab Enterprise".

I think having 2 separate rows (1 for self-hosted, 1 for cloud) is the right call because otherwise you integrating with the cloud would prevent me from integrating with a self-hosted version, and that gets confusing.

grouping by active/available is the right call.

>> [...] If the oauth connection does exist on the Team's Org, the modal does not appear and the user proceeds directly to the Jira Server oauth popup

Jordan & I discussed & we agreed we should keep the "Organization" out of this. We'll keep integrations specific to the team but we might share self-hosted configs across teams in the same org. that'll be down the road

**Comment by jordanh** [comment]
When @mattkrick and I spoke, we discussed only allowing one or the other: public or private. I think this could make sense as a starting place.

When we get home from the hospital, I will have some work to show we can kick around

**Comment by enriquesanchez** [comment]
In the meantime, to get a feel for how things might look like, here are a few variations:

**1. If we want to show a row for both self-hosted and cloud integrations:**

![imagen](https://user-images.githubusercontent.com/3276087/141199926-9791ba36-112f-46aa-8cc2-aa1c1f466f0b.png)

**2. Or maybe we use a grid layout for the integrations that have both options:**

![imagen](https://user-images.githubusercontent.com/3276087/141200005-b2085f22-3c8e-4636-929a-ea1e4f32d12d.png)

**3. Or maybe everything is on a grid:**

![imagen](https://user-images.githubusercontent.com/3276087/141200071-b6cd63f2-2788-49e2-9eea-e3df3f7019b6.png)

**4. Or if we prefer a cleaner layout, we can show two buttons for those integrations with both options:**

![imagen](https://user-images.githubusercontent.com/3276087/141200192-21c1c07f-275f-498e-aba2-4998b448afe8.png)

**Comment by enriquesanchez** [comment]
What it could look like from the Scope phase of a Poker meeting:

![imagen](https://user-images.githubusercontent.com/3276087/141210636-1da8c5a8-d495-4168-a11b-759ed5c25204.png)

or maybe a little more visual:

![imagen](https://user-images.githubusercontent.com/3276087/141210652-bf685604-a830-48dc-89bc-67ed125e9fe1.png)

**Comment by ackernaut** [comment]
@enriquesanchez I like these iterations.

Let’s say folks can only connect cloud or self-hosted.

For the integrations list view, if we have a separate card for both, then the other would need to go away or be disabled? If we have 2 ways to connect on the same card, then that state will go away and they will have an active connection or configuration. It should be clear that they can remove or change it. We may need to see what the settings state looks like. Today there’s a little avatar and a more menu with 2 options: refresh token or remove [integration]

For the poker tab, I think it works either way, because they can’t get back to an initial state (with the 2 options) unless they remove the integration in the team settings view?

**Comment by enriquesanchez** [comment]
>Could you show what this looks like when pushing a task card to Jira for the first time?

A couple of explorations of the dropdown when pushing a task:

<img width="1494" alt="Screen Shot 2021-11-12 at 1 25 05 p m" src="https://user-images.githubusercontent.com/3276087/141523536-abcf33cb-d3f8-4c6c-bec0-375ad40ea57c.png">

The first one has a little description below the title pointing folks to where they can manage their integrations. Second one hides the description behind a `?` hover button.

**Comment by ackernaut** [comment]
Re: [A couple of explorations of the dropdown when pushing a task](https://github.com/ParabolInc/parabol/issues/5567#issuecomment-967379314)

I like this approach. I’d vote for the description being revealed. Today they only see this the first time they integrate with one of these on a team. The next time they see options on the integration they selected. Maybe we use the second header variant (Integrations (?)) when they’ve integrated once. They can use their integrations below the divider or be reminded of how to set up more with the little (?).

I think we can get away with duplicate providers for a while. GitHub has self-hosted, too. The next improvement I would think of is maybe 1 item per provider. Tapping it opens a dialog to choose cloud or self-hosted. Then they authenticate. Then they’re ready to roll in the same place they left off.

**Comment by enriquesanchez** [comment]
>For the integrations list view, if we have a separate card for both, then the other would need to go away or be disabled? If we have 2 ways to connect on the same card, then that state will go away and they will have an active connection or configuration. It should be clear that they can remove or change it. We may need to see what the settings state looks like. 

I think a single card for both types would be best, since we are only going to allow connecting to one. The connected state can specify the type (server/enterprise/self-hosted or cloud).

![imagen](https://user-images.githubusercontent.com/3276087/141540973-746bf91a-8dd3-421b-83de-1da6b1d29495.png)

**Comment by enriquesanchez** [comment]
>The next improvement I would think of is maybe 1 item per provider. Tapping it opens a dialog to choose cloud or self-hosted.

Seeing that the list of integrations will be short for the time being, I think we can save users a click by displaying all in the list. 

That said, if we decide to go with the dialog, we could reuse the pattern for the scoping phase:

![imagen](https://user-images.githubusercontent.com/3276087/141544235-ffd687b1-742b-4ecd-a8bd-2515b84aad58.png)

**Comment by ackernaut** [comment]
Re [this comment](https://github.com/ParabolInc/parabol/issues/5567#issuecomment-967693836) about integration settings and [this comment](https://github.com/ParabolInc/parabol/issues/5567#issuecomment-967700027) about integrating from cards…I think this is the right direction! LGTM, nice work 🙌

**Comment by jordanh** [comment]
👀  **Watch the demo & overview 👇 **

[![image](https://user-images.githubusercontent.com/103000/141662110-5caa5dce-f65f-4c2b-bdd7-eaaa9aa16240.png)](https://www.loom.com/share/22037d51a1404fa5aab5d6ba10c98778)

See: https://github.com/ParabolInc/parabol/pull/5594#issuecomment-968176433

**Comment by enriquesanchez** [comment]
Closing as this seems to have the needed design direction. Feel free to reopen if more design work is needed.

**Comment by mattkrick** [comment]
@enriquesanchez what are you thoughts on how to only allow for 1 integration type (cloud vs. enterprise) per team?

For example, let's say I add GitHub. That integration is specific to my TeamMember.
Then, you would like to add GitHub Enterprise. That integration is specific to your TeamMember.

Doing this, I'd be integrated with GitHub & you'd be integrated with GitHub Enterprise, which means the team would have both.

If the UI disabled you from integrating against GitHub Enterprise because I already added a Cloud integration, that means you'd have to know the integration status of every other team member & you'd have to ask every other team member to remove their integration before you could add yours, which feels a little clunky.

IMO the only elegant solution is to allow folks to add whatever they want. We could limit a single team member from integrating against 2 different types, but I'm not sure if that'd be confusing or not?

**Comment by enriquesanchez** [comment]
@mattkrick Yeah, I like that solution. A team member can add on or the other, but not both at the same time. The UI should offer both as an option when available, and reflect which one is active.

[The mockup on this comment above](https://github.com/ParabolInc/parabol/issues/5567#issuecomment-967693836) shows these scenarios. When both options are available, we have the two buttons to choose. Once one has been connected, we show "Connected to Server" or "Connected to Cloud".

**Comment by mattkrick** [comment]
There are 3 options:
- only 1 type per team. this means my integrations are codependent on yours. this ain't good
- only 1 type per team member. this means i can add cloud & you can add enterprise
- many types per team member. this means i can add up to 1 cloud & 1 enterprise. today a user can't add 2 accounts across 2 clouds, so we're not really taking much functionality away if we don't allow this.

specific to atlassian:
- jira server & confluence server use different auth BUT jira cloud & confluence cloud use the same. that means we might hit some sadness if we combine atlassian [cloud] with jira server, but we can cross that bridge later.
 
after a sync chat with @enriquesanchez i think the 2nd option is best & we can move forward with that 🎉
