### ISSUE TITLE
PPMI for customer-staging.parabol.co

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5579]
This ticket is a request to implement a public test instance of Parabol for customers to test against (e.g. test a SAML integration prior to the change on public SaaS)

AC
- [x] PPMI for customer-staging.parabol.co
- [x] Datadog configuration (monitor)

Estimate: 2 hours

**Comment by jordanh** [comment]
@adaniels-parabol is this done? Could you close it if so?

**Comment by adaniels-parabol** [comment]
This has been completed.
