### ISSUE TITLE
Read-only instance for the production Postgres instance

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5581]
This ticket is a request to implement a read-only instance for the production Postgres instance

AC
- [x] Create IaC to deploy read-only copy production postgres instance
- [ ] Test IaC in staging
- [ ] Deploy IaC to production

Estimate: 5 hours

**Comment by adaniels-parabol** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/8Kr615RAwE/estimate/7) in Sprint Poker #​​9

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by adaniels-parabol** [comment]
@jordanh as @jchandler-parabol worked this in his batting practice and implemented on staging, I'd love to hand this over.

**Comment by jordanh** [comment]
@adaniels-parabol what was the reason for the read-only instance?

In any event, iceboxing now per policy
