### ISSUE TITLE
New meeting flow UX: the MVP

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5589]
This issue follows #5255 and lays out the implementation of the new meeting view UX. Starting by what an MVP will look like and then addressing follow up improvements.

Links to relevant pieces of the [the Figma file](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=673%3A6442) are found in the AC below.

## MVP

![image](https://user-images.githubusercontent.com/3276087/139140259-e553cfe9-55f1-48e4-8021-0eb19424aac3.png)

The MVP addresses the following [current frictions](https://github.com/ParabolInc/parabol/issues/5255):

> - Sometimes folks start a meeting on the wrong team
> - Sometimes folks start the wrong meeting type
> - Sometimes folks aren’t aware of other meeting types

### Acceptance Criteria

- Starting a new meeting now displays a centered dialog (800px wide on desktop).
  - The dialog should inherit the background view from where it was invoked. If I'm on the team view and I select the `+ Add meeting` button, I should stay within that same view.
  - On the other hand, if the new meeting is being created by an URL endpoint, we can default instead to have the meetings view in the background.
  
**Meeting type**  
- The 3 meeting types currently offered by Parabol are all displayed on the top row of the dialog's main content area. There will always be one option selected, and [each meeting type has its own distinctive illustration and color](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=683%3A8501).
-  We can continue to have the most recent meeting type the team had selected by default.
- Selection of a meeting type should have an ease animation.
- Selection of a meeting type should update the value for the template field, same as today.
- When a meeting type is selected, we display an "information" icon next to the type label. For the MVP this icon should link to our support pages where we detail each meeting type. This link should open on a new tab/window.
  - https://www.parabol.co/resources/retrospective-meetings
  - https://www.parabol.co/resources/planning-poker-guide
  - https://www.parabol.co/resources/check-in-meetings

**Team select**
- Below the meeting types is the team selector. It displays a grid of 2x2 avatars of team members (ideally these would be randomly picked from the full group of team members) and the team name.
  - If a team has less than 4 members, [here's how to handle the grid of avatars](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=685%3A11301).
- Selecting the team dropdown [displays a list of available teams](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=685%3A11301), same as we do today.

**Template select**
- To keep things small, [we are going to reuse the same UI we currently have for selecting a template](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=685%3A11302). Only change is how we get there and how the template selection UI behaves with the new dialog/modal pattern.
- When selecting the template field, the template selection UI should slide in from right to left and take up all the space on the dialog.
- Everything should remain the same, with the exception of the addition of a back arrow preceding the title.
- Clicking on the back arrow should slide the template selection UI out of view within the modal, and return to the main new meeting view.

**Icebreaker**
- The icebreaker checkbox should behave the same way it currently does.

**Bottom row**
- The bottom section of the new meeting dialog [contains a space for error or active meeting notification](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=690%3A13920), and the Cancel and Start meeting buttons. No new functionality is added.

**Mobile**
- [Here's how to adapt the layout to smaller screens](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=691%3A15332). 
- To keep things simple for this MVP, the meeting types can overflow and scroll horizontally. We can look at carousel-type patterns later.
- The current template selector view does not work well on mobile and we'll need to adopt a [list-based navigation pattern](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=691%3A15332).

## Implementation steps
* [x] #5602
* [x] #5603
* [x] #5604
* [x] #5605
* [x] #5608

## Follow ups

Follow up issues will be linked once available. These are not required for the MVP and instead address improvements or enhancements for future iterations.

- [x] #5591
- [x] #5596
- [ ] Meeting type info sub-view
- [ ] Meeting type carousel 

### Estimated effort:
??

**Comment by avivapinchas** [comment]
Just adding some signal to this: on the Growth team, we're engaging users in 'public' retros as a way to build relationships with them. Folks get added to a `remotely agile` team to participate in those, and then they [start accidentally starting meetings on that team](https://parabol.slack.com/archives/C4JAUUZ9P/p1650396221465579) 🔒  😬 😭

**Comment by Dschoordsch** [comment]
Done.

**Comment by enriquesanchez** [comment]
Just noting that https://github.com/ParabolInc/parabol/issues/5591 and https://github.com/ParabolInc/parabol/issues/5596 are still pening

**Comment by Dschoordsch** [comment]
> Just noting that #5591 and #5596 are still pending

They were categorized as follow-ups. You could create a new milestone to track those further improvements if you think they get lost otherwise.
