### ISSUE TITLE
Error: QuotaExceededError: The quota has been exceeded.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5592]
https://sentry.io/organizations/parabol/issues/2663153523/?referrer=github_plugin

```
Error: QuotaExceededError: The quota has been exceeded.

QuotaExceededError: The quota has been exceeded.
```
This error occurred after participating in meetings and performing multiple options.

Happened to 21 users in a month.

**Timeboxed 1h to estimate**

**Comment by jchandler-parabol** [comment]
One possibility 👇 

https://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

TL;DR when user tries to use the app when in private browsing mode local storage is not available at all.

**Comment by jordanh** [comment]
No occurrences in the past 30 days
