### ISSUE TITLE
Can’t swap to pinned agenda item on mobile device (Android 11, Chrome, Pixel 4)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5595]
When somebody joins a check-in meeting on an Android 11 device (using Chrome, Pixel 4), they should be able to click on both pinned and unpinned agenda items

AC
- Folks on Android can tap on and navigate to pinned agenda items

EE
- 5 hours

**Comment by mattkrick** [comment]
@ackernaut can you please add AC/Estimate?
