### ISSUE TITLE
Update all atlassian refresh tokens for a given user 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5601]
@Dschoordsch pointed this out during our 1:1 & we should fix it this sprint.

The latest jira changes mean a userId can only have 1 valid refresh token for a given app. that means whenever we update the refresh token for 1 team member, we need to also update it for all other team members.

AC
- [ ] when the refresh token is updated for a team member, it updates the refresh token across all teams
- [ ] if a parabol user has 2 separate jira integrations, the refresh token doesn't apply across both (ie you can't just apply the update across all integrations for the given userId.  it'll have to be for the jira user id.

Estimate: 4 hours

**Comment by BartoszJarocki** [comment]
Also, just making sure, by `jira user id` do you mean `accountId` from `AtlassianAuth` table?

**Comment by mattkrick** [comment]
Yep, you're understanding of the problem is correct!
Let's update `accessToken, refreshToken, updatedAt` for all applicable rows where an applicable row is an AtlassianAuth that has the same `accountId`.

I'd suggest using `userId` as the index and then filtering that result by matching `accountId`.

Reasons:
- 95% of the time the index won't overfetch (ie most users don't have 2 separate jira accounts)
- In Jordan's proposal #5567 accountId will likely fall into the `attributes`, which is JSONB. I'd like to avoid indexing on unstructured JSONB data if I can help it
