### ISSUE TITLE
Updated new meeting dialog and route

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5602]
See #5589 for context
![new dialog](https://user-images.githubusercontent.com/7331043/140178594-08abed09-35bd-44f3-85c9-463ed80bf0e9.png)

## Acceptance criteria
* [ ] existing new meeting page stays functional, new dialog is only accessible when entering route directly
* [ ] existing new meeting page copied and convert it into a dialog
* [ ] dialog has it's own "modal route" which can be accessed by `meetings/new-meeting` or `team/${teamId}/new-meeting` depending on where it is opened
  Inspiration can be gotten from https://github.com/davidmfoley/react-router-modal
* [ ] Bottom row with 'Create', 'Cancel' and existing meeting status is added
* [ ] Title and X buttons are added
* [ ] Existing template select is copied and adapted with new behaviour, **no** design or functional changes
  * [ ] When selecting the template field, the template selection UI should slide in from right to left and take up all the space on the dialog.
  * [ ] Everything should remain the same, with the exception of the addition of a back arrow preceding the title.
  * [ ] Clicking on the back arrow should slide the template selection UI out of view within the modal, and return to the main new meeting view.

## **Not** part of AC
* Carousel and meeting selector
* Pointing 'Add meeting' buttons to new route

**Comment by Dschoordsch** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/8dpiOGSY5G/estimate/2) in New meeting dialog estimates

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/8dpiOGSY5G/estimate/2) in New meeting dialog estimates

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
@enriquesanchez I have a question about the button types. At the moment we're using raised buttons for "Start Meeting" and "Active Meetings". From the design it looks like these are more flat buttons?

### Title with flat X
![Peek 2022-07-07 13-20](https://user-images.githubusercontent.com/7331043/177761880-28cdb17a-e079-42f4-8887-c7afd39d7e8d.gif)


### Actions with raised "Active Meetins", flat "Cancel" and primary raised "Start Meeting"
![Peek 2022-07-07 13-20-1](https://user-images.githubusercontent.com/7331043/177761890-920055fd-3c06-49a7-b3d1-79f6b9537ca0.gif)

Which type should we choose? Should the "Start Meeting" button be more flat when not hovered to match the rest of the design?

**Comment by enriquesanchez** [comment]
Thanks for the ping @Dschoordsch!

>From the design it looks like these are more flat buttons?

Yes, I've been using buttons without drop shadows in recent mockups. My intention is for us to start moving away from over using drop shadows. 

>Which type should we choose? Should the "Start Meeting" button be more flat when not hovered to match the rest of the design?

If it's possible, then yes, let's remove the drop shadow from these buttons (Active meetings, Cancel, and Start meeting) in the new meeting dialog. I would only recommend adding a small drop shadow for the hover state of the Start meeting button.

----

The recent experiment of the new start meeting button on the top bar is another place where I recommend removing the drop shadow:

<img width="404" alt="Captura de Pantalla 2022-07-07 a la(s) 10 39 21 a m" src="https://user-images.githubusercontent.com/3276087/177814938-41d8adac-6646-4254-acd5-c73c4335f461.png">

**Comment by Dschoordsch** [comment]
> If it's possible, then yes, let's remove the drop shadow from these buttons (Active meetings, Cancel, and Start meeting) in the new meeting dialog. I would only recommend adding a small drop shadow for the hover state of the Start meeting button.
> 
Should we keep the grey highlight for `Cancel` and `X` or choose a shadow like for `Active Meetings`? Should `Active Meetings` be made gray instead? Right now it feels a bit chaotic.

> The recent experiment of the new start meeting button on the top bar is another place where I recommend removing the drop shadow:
> 
> <img alt="Captura de Pantalla 2022-07-07 a la(s) 10 39 21 a m" width="404" src="https://user-images.githubusercontent.com/3276087/177814938-41d8adac-6646-4254-acd5-c73c4335f461.png">

I missed that. I will remove the drop shadow there as well.

**Comment by Dschoordsch** [comment]
I made the "Start Meeting" button completely flat as well
![Peek 2022-07-08 17-48](https://user-images.githubusercontent.com/7331043/178030931-089eca14-93fc-4c9a-8aba-872e93f0df41.gif)

**Comment by enriquesanchez** [comment]
@Dschoordsch I like it! 🙌
