### ISSUE TITLE
New meeting type carousel

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5605]
See #5589 for context

## Acceptance criteria
* [ ] The 3 meeting types currently offered by Parabol are all displayed on the top row of the dialog's main content area. There will always be one option selected, and [each meeting type has its own distinctive illustration and color](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=683%3A8501).
* [ ]  We can continue to have the most recent meeting type the team had selected by default.
* [ ] Selection of a meeting type should have an ease animation.
* [ ] Selection of a meeting type should update the value for the template field, same as today.
* [ ] When a meeting type is selected, we display an "information" icon next to the type label. For the MVP this icon should link to our support pages where we detail each meeting type. This link should open on a new tab/window.
  - https://www.parabol.co/resources/retrospective-meetings
  - https://www.parabol.co/resources/planning-poker-guide
  - https://www.parabol.co/resources/check-in-meetings

**Comment by Dschoordsch** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/8dpiOGSY5G/estimate/4) in New meeting dialog estimates

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by enriquesanchez** [comment]
Small update to the meeting type carousel, [see this Slack convo (🔒) for context](https://parabol.slack.com/archives/C836NA350/p1641405825026100).

We are going to add a line of text to each meeting type stating the meeting's primary benefit:

**Check-in:** Sync up, unblock each other
**Retrospective:** Improve how you work
**Sprint Poker:** Estimate effort, de-risk execution

The update will look like this:

![149837534-753bcadb-6b41-48d3-86c4-2818dfd96294](https://user-images.githubusercontent.com/3276087/149837739-a26cbb45-5aab-4e7f-81c0-255b926afb2c.png)

When a meeting type is selected in the carousel, the line of text will be shown just below the type title.

**Comment by acressall** [comment]
A user writes:

> Currently you can't edit the meeting name until after you have started the meeting.  It would be nice to edit the name of the meeting before it has started.

**Comment by igorlesnenko** [comment]
@enriquesanchez a couple of questions:

- On a screenshot I see 3 cards and no carousel controls. Now we also have async standup meeting type. How would it look like? Should we add some carousel controls?

- "It would be nice to edit the name of the meeting before it has started." Can we add this field somewhere?

**Comment by enriquesanchez** [comment]
Hey @igorlesnenko 👋 

>On a screenshot I see 3 cards and no carousel controls. Now we also have async standup meeting type. How would it look like? Should we add some carousel controls?

You are correct. The row of meeting types acts as a side scrolling area, with no carousel controls.

https://user-images.githubusercontent.com/3276087/179564053-ff2cdc04-17f0-4bcd-a07e-4fbd7a46f909.mp4

[Here's the Figma file](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=733%3A10005)

>"It would be nice to edit the name of the meeting before it has started." Can we add this field somewhere?

This was initially planed but later scrapped in favor of a more lean MVP. But [here's an example of how that functionality should behave.](https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=707%3A9143) 

https://www.figma.com/file/5ouU5EQOZ0ELcBA0xWZGdQ/Start-a-new-meeting?node-id=707%3A9143

It's basically the same behavior as editing the meeting title in a meeting. Let me know if you need clarification on anything.

**Comment by igorlesnenko** [comment]
@enriquesanchez I have some concern about **active** card style. If I just zoom the whole card relative to its center, it eats the paddings.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/466991/180480261-4be1ce0b-4c74-4be5-a8af-a9534a139961.png">

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/466991/180480335-535f62ab-a1af-41f9-ab55-2dd13307f91e.png">

Here is the loom.

https://www.loom.com/share/ccefbb4537ca42989ecbcf28c2a4a2f3

What do you think?

Also if I understand correctly, I don't add (i) icon to the description but use primary benefit text from here https://github.com/ParabolInc/parabol/issues/5605#issuecomment-1014890945 ?

**Comment by enriquesanchez** [comment]
Hey @igorlesnenko! Thank you so much for the update! This is coming along super nicely 🙌 

I don't have issues with the change in padding for the selected meeting type. It feels similar to how other UIs do it. A good example of this is the Apple TV:

![appletv2017event-12l-660290845](https://user-images.githubusercontent.com/3276087/180494780-febc0576-8ac1-4de9-8526-323f80b0e394.jpg)

Notice how the "Movies" option is bigger and breaks away from the padding the other items have?

What do you think?

Also, I LOVE the kinetic effect you added to the row of meeting types! It looks really cool!
