### ISSUE TITLE
Switch 'New meeting' button to new meeting modal route

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5608]
Requires rest of #5589 to be done

## Acceptance criteria
* [ ] Switch 'New meeting' buttons to new meeting modal route defined in #5602 
* [ ] Delete old new meeting page and unused components

**Comment by Dschoordsch** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/8dpiOGSY5G/estimate/3) in New meeting dialog estimates

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
If #6866 gets merged as is, we don't need this because the new dialog would be live straight away.

**Comment by acressall** [comment]
@igorlesnenko can we close this issue?

**Comment by igorlesnenko** [comment]
@acressall yeah, I think it already works correctly
cc @Dschoordsch 

Closing this
