### ISSUE TITLE
Search in integration dropdown does not work

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5612]
## Issue - Bug

See Loom: https://www.loom.com/share/85c7a11754324cc882d4fb1f5a677257

### Acceptance Criteria (optional)
Users can:

- [ ] Search properly in task integration dropdown menu

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by agarg21** [comment]
Hi @tianrunhe! I recently learned about Parabol and really like the idea :) I'm curious if it's ok for me to try to debug this task?

**Comment by agarg21** [comment]
I'm curious what's a good way to test Github integration on dev, do we create a dev Github app to get Github credentials?
https://github.com/ParabolInc/parabol/blob/1980e0bb40dc8f23a5c08110df0ddcdbca3235db/.env.example#L15

**Comment by tianrunhe** [comment]
Hey @agarg21, thanks for helping!  
  
Yes, feel free to create a dev GitHub app yourself to get the client Id and client secret.

**Comment by mattkrick** [comment]
related to: https://github.com/ParabolInc/parabol/issues/5094

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/17746551) 🔒  writes:

> I have recently set up an integration between Parabol and Jira to push action items from retrospective meetings into a dedicated process improvements project.
> 
> However, it does not work as expected because I cannot push tasks to the required project. I see only the first 10 projects available in the dropdown menu (sorted alphabetically) and when I try searching for the project I need, I get the 'No integrations found!' message. I tried the full name of the project and a partial search as well, none of it helps.
> I have access to the required project and admin rights there.
> Can you help me with this?
