### ISSUE TITLE
Code review to verify if all the singleton implementations for Redis connections are needed

### ISSUE THREAD

**Issue by mariogruizdiaz** [ParabolInc/parabol#5614]
## Enhancement

Verify if the singletons are working as expected. In [Phase I](https://www.notion.so/Site-Reliability-Roadmap-a7c303f9f89d47f395e7b8b3950b7ee5#2ff121023e1f471fa816a41387ddd4c8) of the [Site-Reliability-Roadmap proposal](https://www.notion.so/Site-Reliability-Roadmap-a7c303f9f89d47f395e7b8b3950b7ee5) is shown some examples about duplicated connections to Redis which are launched with the same singleton code.

### Acceptance Criteria (optional)
   

- [ ] Review every singleton implementation and document why and for what they are needed. If some of them can be merged, please create an enhancement issue to request it.
- [ ] Clarify of duplicated Redis connections based on the same singleton code is expected. If they are not, create appropriate bug issues to fix the problem

**Estimated effort:** 12 points

**Comment by mattkrick** [comment]
root cause: there are 2 services (gql executor & webserver) that both use a singleton created by the same function, so there is 1 singleton per instance
