### ISSUE TITLE
Add metadata to every Redis connection

### ISSUE THREAD

**Issue by mariogruizdiaz** [ParabolInc/parabol#5615]
## Enhancement

In order to do granular monitoring about each Redis connection, we will need to have named them.
Please define the connectionName at Redis instantiation step:

`new Redis(REDIS_URL, {connectionName: '[SOME_REPRESENTATIVE_NAME]'})`

### Acceptance Criteria

- [ ] Set the connectionName to every Redis singleton connection
- [ ] Verify the names are shown in the terminal by using redis-cli commands connected to the Redis instance when the app is running

**Estimated effort:** 11 points

**Comment by mattkrick** [comment]
fixed in #5617
