### ISSUE TITLE
Only show GitHub repos that have issues enabled

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5633]
If it's not possible to add an issue to a GitHub repo, we shouldn't show that repo in our task integration.

While testing the GitHub integration, I selected a repo to integrate the task with and saw an error message. I assumed there was a bug until I noticed that the repo I selected had issues disabled.

A user might go through the same experience if they want to test the integration before using it in a "real" repo.

It looks like we can use the `has_issues` field [here](https://docs.github.com/en/rest/reference/repos) to check if issues are enabled. 

### AC

- [ ] In the GitHub task integration, don't show repos that have issues disabled

**Comment by mattkrick** [comment]
closing in favor of #5094 to be fixed in the pr #5883
