### ISSUE TITLE
Template Illustrations updated

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#5636]
## Issue - Enhancement
We've created new Template illustrations in our updated style, for both retro templates and estimation templates. We should updated the ones used in the app. 

[Illustrations saved on GDrive here. 🔒 ](https://drive.google.com/drive/folders/1A8Cmdr1oFbYk6gKolAg922pNR4Mw6b7Z?usp=sharing)

Related issue: #5484 for updating Meeting Type illustrations

## Acceptance Criteria (optional)
Users can enjoy the lovely new illustrations.

**Estimated effort:** X points (see CONTRIBUTING.md)

**Comment by Dschoordsch** [comment]
@avivapinchas Right now we only have 2 poker templates: Estimated Effort and Weighted Shortest Job First.
![Screenshot from 2021-12-13 15-59-35](https://user-images.githubusercontent.com/7331043/145836090-e59441fc-5c6e-4581-ae02-15f3c8411a96.png)
When creating a custom template, the user can chose from the other 4 versions as well
![Screenshot from 2021-12-13 15-59-59](https://user-images.githubusercontent.com/7331043/145836163-9a3993f5-26bf-44f2-ab00-783064b88833.png)
but there are no icons.

How should we proceed here? Do we want to show all 6 templates when creating a new poker meeting? Is there a reason only 2 are shown?

**Comment by avivapinchas** [comment]
@Dschoordsch I would say update the illustrations for Estimated Effort and Weighted Shortest Job First and the retro templates. If there isn't an illustration to update, don't think we need to create a spot for an illustration.
