### ISSUE TITLE
GitLab integration provider row(s) designed

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5639]
See #3971 and #5564 for context.

----

![imagen](https://user-images.githubusercontent.com/3276087/141019609-4196778a-27b1-4d97-8c2b-6296cc39b296.png)

With the previous design work we've done for the GitHub integration and [self-hosted services](https://github.com/ParabolInc/parabol/issues/5567#issuecomment-964577411), we now have enough patterns that we can reuse for the **GitLab integration.**

Let's use this issue to track any new or additional design work that we might need to do.

**Comment by jordanh** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/9SaEuq8iJO/estimate/1) in Sprint Poker for Sprint #​​94

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by enriquesanchez** [comment]
Closing as there has not been any movement here. Feel free to open if any new design work is needed 👍
