### ISSUE TITLE
Type mismatch GraphQL - Typescript

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5644]
While working on #5476 I found a couple of places where the usage in Typescript did not match the GraphQL definition, i.e. arguments were optional in GraphQL but not treated as such in code.

## Acceptance criteria

*   [ ] Add types back at the following files and adapt type usage or GraphQL definition to match
    *   [ ] https://github.com/ParabolInc/parabol/blob/33c3478b8699f0a61e092b533c36e4e6ac03c704/packages/server/graphql/mutations/addTeam.ts#L35
    *   [ ] https://github.com/ParabolInc/parabol/blob/33c3478b8699f0a61e092b533c36e4e6ac03c704/packages/server/graphql/mutations/createReflection.ts#L32
    *   [ ] https://github.com/ParabolInc/parabol/blob/33c3478b8699f0a61e092b533c36e4e6ac03c704/packages/server/graphql/mutations/updateTaskDueDate.ts#L28
    *   [ ] https://github.com/ParabolInc/parabol/blob/33c3478b8699f0a61e092b533c36e4e6ac03c704/packages/server/graphql/mutations/updateTeamName.ts#L24

**Estimated effort:** 4 hours

**Comment by jordanh** [comment]
**Include in next sprint?: y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/28) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by blimmer** [comment]
This is likely out of scope for this bug, but it might be nice to use something like [GraphQL Codegen](https://www.graphql-code-generator.com/) to automatically produce the GQL types for your schema. That way, types are always in-sync.
