### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5648]
There was a period of time where parabol client couldn't get a response from parabol server when making a graphql request. Affected 7 users at the same time that we deployed v.6.36.0: https://app.circleci.com/pipelines/github/ParabolInc/parabol/3560/workflows/902621cd-bbdf-4655-8739-7b084a341af0/jobs/12387

https://sentry.io/organizations/parabol/issues/2781730644/?referrer=github_plugin

```
TypeError: Failed to fetch
  at None (<anonymous>:1:876)
  at fetchData (./packages/client/Atmosphere.ts:147:23)
  at handleFetchPromise (./packages/client/Atmosphere.ts:276:22)
  at source (./packages/client/Atmosphere.ts:289:12)
  at h (./packages/client/hooks/useQueryLoaderNow.tsx:20:5)
...
(26 additional frame(s) were not displayed)
```

**Comment by tianrunhe** [comment]
Sentry issue: [ACTION-PRODUCTION-AG0](https://sentry.io/organizations/parabol/issues/3004782556/?referrer=github_plugin)

**Comment by jordanh** [comment]
Marked as ignored in Sentry. I am going to ignore it here. Please don't hesistate to reopen if you, dear future reader, should feel differently
