### ISSUE TITLE
Incorrect position for remote reflection 

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5657]
If the viewer scrolls down in a column and then a reflection near the top of the column is remotely dragged, the position of the remote reflection is above the column:

![remote-reflection-scroll-bug](https://user-images.githubusercontent.com/39854876/141827086-a2dc622c-a69e-45e3-b5bd-afb8d9109ee5.gif)

I thought that this might be related to the Spotlight feature, but I could reproduce the bug in v6.25.0, which was before any Spotlight logic was pushed to prod.

### AC:

- [ ] Remote reflection drags always start and end from a position in the kanban column

**Comment by jordanh** [comment]
Iceboxing
