### ISSUE TITLE
Designed a fully-featured account members/seats UI

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5664]
## Background
Folks want the ability to better review and manage their list of organization members (all seats on the account).

This was bulleted here in #5661

>bulk administer users: filter a list by search criteria bulk select to pause or remove them
search criteria: email, preferred name, create/last active dates, optional: team name

[Mentioned here](https://github.com/ParabolInc/parabol/discussions/5661#discussioncomment-1653903)
>Is it possible to see the member list alphabetically so it’s easier to search?

And mentioned [in this Loom](https://www.loom.com/share/242b2fab85da4d0e90055e253c0c4a91) sometime after 27:14 .

We could write these as a few user job stories:

>When managing licensed seats on my enterprise account, I want the ability to find inactive users, or users who are not part of my organization (by email), so that I can free up active seats and manage license consumption

>When reviewing members on my account, I want to search and filter so that I can identify folks who are inactive so that I can remove old accounts
  
### Today
![Screen Shot 2021-11-16 at 16 14 30](https://user-images.githubusercontent.com/307286/142075208-5c1df58a-18e8-4c1a-95fb-5676ad41d3f1.png)
![Screen Shot 2021-11-16 at 16 14 19](https://user-images.githubusercontent.com/307286/142075240-9c080722-7377-4d67-9206-6c998b72b8ec.png)
### From the Oct 2021 prototype
![Members scrollable](https://user-images.githubusercontent.com/307286/142075406-4330bc1f-80c9-472a-83f9-3fdbc5202bb6.png)
- Here’s [the prototype](https://www.figma.com/proto/u4JmGghyoLS2gHcFtmrPQG/Admin-Prototype?page-id=0%3A1&node-id=22%3A3130&viewport=501%2C48%2C0.15&scaling=scale-down&starting-point-node-id=28%3A1187)
- Here’s [the view in Figma](https://www.figma.com/file/u4JmGghyoLS2gHcFtmrPQG/Admin-Prototype?node-id=22%3A3130)
- [Feel free to comb through these transcripts for verbatim comments](https://www.loom.com/team-videos/Design/Admin%20prototype%20feedback)
- Some of [these comments](https://action.parabol.co/meet/8eGK7ZCOkw/discuss/4) were about the user table. Others were about [the most active members table](https://www.figma.com/file/u4JmGghyoLS2gHcFtmrPQG?node-id=0:1#125326710).

## Acceptance criteria
- Proposed a members ‘rich table’ interface concept addressing these concerns:
  - This UI component can fit in a regular page layout regardless of final navigation or IA concerns of the admin area
    - How might this adapt for mobile?
  - Admins can perform fuzzy search; maybe even using specific search queries in the future
  - What data fields do we present per member? The UI component has table headers with labels for the fields that are presented. A little discovery work may be necessary here, but a minimal we can find a good place to start
    - Admins can [sort by table headers](https://action.parabol.co/meet/8eGK7ZCOkw/discuss/5) where logical and reasonable
    - Consider if the table header is sticky (it doesn’t scroll out of view) so that folks remember what the fields are
  - Admins can use filters, especially filters like active, inactive
    - Stretch goal: folks can filter which members have or do not have the top level email domain (e.g. find users with or without @parabol.co)
  - How do we load a lot of members on a large account? Lazy loading?
  - Can admins export user data? Which fields? What’s the control look like? What’s the workflow like? See #5665 
  - What other admin actions can be performed? How are they performed? Today members can leave an account. Today billing leaders can promote or remove the billing leader role, and remove members

## Estimated effort
- 21 hours

**Comment by avivapinchas** [comment]
**Value: 3**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/15) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: L**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/16) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by gcrickman** [comment]
An [Enterprise customer](https://app.hubspot.com/contacts/3888472/contact/71976001) 🔒 asks:

> Are there any plans for Parabol to build functionality to manage teams centrally through the organization at some point?  ie be able to list them, add users to them or remove folks from a team by a super admin?

**Comment by jordanh** [comment]
Likely we'll reopen this as it is a perennial need and we even have a SBIR proposal going out that would continue the design/implementation work here. That notwithstanding, iceboxing for now
