### ISSUE TITLE
Admins can export member data

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5665]
Short of building out #5664 this is an opportunity to do something small for customers.

[This user](https://www.loom.com/share/242b2fab85da4d0e90055e253c0c4a91) 🔒  stated (sometime after 27:14) that it would be helpful if he could export member data to review, search, etc. since our UI is limited.

Note: to my knowledge this is the first person to ask for this, but it seems like a meaningful step toward a theme of giving folks better access to their data

### User job story
>When managing my account members with limited UI (including looking for external members by email, etc. and removing inactive members, etc.), I want to export a list of users, so that I can search and sort the data on my own

### Open questions
- Is it worthwhile to build this before building #5664 ? Assuming we build #5664, is the effort low enough and value high enough? Will implementing new admin designs take long enough?
- What fields should we include?

### Acceptance criteria
- Adds a icon and label control to the upper right of the panel ([see design below](https://github.com/ParabolInc/parabol/issues/5665#issuecomment-1106730040))
- Clicking downloads a CSV with: name, email, inactive (Y/N), billing lead (Y/N)

### Estimated effort
- 8 hours

**Comment by ackernaut** [comment]
@jordanh @avivapinchas - hey team leads

Do you see value in this as a ‘help wanted’ task? @atannus may volunteer, if so.

What I imagine here is an ‘Export to CSV’ link or button at the upper right of the Organization > Members view. This produces a CSV with:
- name
- email
- inactive Y/N
- billing lead Y/N

Folks could use this to comb through a long list of users (e.g. they’re worried about their licensed seats), as we don’t provide a search or filter experience yet.

Later, if we offered search and filters, they may still find this export function to be useful.

![export users to csv button](https://user-images.githubusercontent.com/307286/164766639-10d8ef5b-ac2a-4ed2-a181-a3f8ef3df038.png)

**Comment by avivapinchas** [comment]
I defer to @jordanh. I imagine this would have value, but the key challenge is that folks today can't see across team/org boundaries, so this wouldn't solve the bigger problem, but might alleviate some things.

**Comment by ackernaut** [comment]
What say ye @jordanh (PM)?

**Comment by avivapinchas** [comment]
**Value: 2**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/13) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
