### ISSUE TITLE
t_product_stats logins & sign-ups are sorted alphabetically

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5668]
In the `t_product_stats` Slack channel, we share the top sign-ups and top logins of the day. Companies are currently sorted alphabetically by name rather than by number of logins or sign-ups.

### AC

- [ ] `dailyPulse` metrics are sorted by daily login & sign-up count

**Comment by tianrunhe** [comment]
Duplicate of #5606 . Sorry @nickoferrall, I'm way ahead of you 😆
