### ISSUE TITLE
Admin IA and navigation designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5669]
## Background
**Note**: see the background from discussion #5661 and [the design sprint notes in Notion](https://www.notion.so/parabol/Administrative-IA-and-features-8443fdec91994bc2ac15d893190f6607)

As we expand the functionality of our account administration section and views, we need an IA and corresponding navigation that helps a user stay oriented while quickly getting to the features they need. An attempt at a high-level user job story:

## User job story
>When managing my Parabol account, I want clearly organized information and navigation, so that I can quickly find what I’m looking for and complete the tasks I need to do without guesswork

Needless to say there are probably a dozen user job stories ranging from managing users (e.g. #5664), to managing SSO/SAML (e.g. #5512) etc. We need to provide good IA and navigation in order to support folks doing these jobs.

## Open questions
- How might we organize around the broad range of concerns from #5661 ?
- Is there a way we can build this out iteratively? Could we only add the navigation items that we can support today, and stick existing views in them, to start (e.g. put our Members view under that nav item, but our Billing components under that nav item, don’t display a Support nav item until we build it)
- Is there a point in which we over-optimize? We’ve managed to survive years with limited account views, how can we find the right, small scope that will help us for the foreseeable future?
https://www.figma.com/file/u4JmGghyoLS2gHcFtmrPQG?node-id=184:1448#125632422
- How much do we divide team management and insights under a team view versus a global account view?
- How might the navigation patterns we develop give us flexibility to improve IA? I.e. if we have left nav we realize we may need to combine two sections into 1 nav item, or break 1 nav item out, etc.
- How might we show conditional content? E.g. if we turn on domain stats for a set of accounts where might that go? Is it a new nav or sub-nav item? Is it at the top of an existing page?
- What is the entry point? Today folks access the account views form their top-left user menu, or from the organization name link under the team view header. Is this its own area of the product with its proper left nav? How do folks get back to their primary product experience?

## Concept
This came out of the design sprint. Let it me a source of inspiration, if anything.

![Insights scrollable](https://user-images.githubusercontent.com/307286/142249263-91f1949b-e356-4604-b3f2-3dcff941034d.png)

### Insights
This section is for helping me understand how well my teams are doing. Are they keeping a healthy cadence? What activity types are they running more? What are the trends from their activity that provide insights around team and company wide challenges?
### Members & Teams
The members section should be more about managing users (see #5664). The team section seems to be more about usage, health, and insights. Should this be here or under the team? Is this simply a view to see all the teams? Does an admin role have the ability to see any team from this view (as a launching point) but navigate to those team views without being a member? If we stick more management and insights under the team, then the team members and lead will have access to the same information without us having to build it in 2 places. See #5671
### Plan & Billing
It should be clear what plan they are on. They should have access to their invoices. They should be able to manage emails that receive invoices (see #3955). In the future they should probably have some optionality about downgrading and upgrading.
### Advanced Settings
How might we provide advanced support for SSO/SAML across 1 or many domains? (e.g. see #4833) What are the needs of private instances? Are the good user job stories for managing integrations at the account (company wide) level? Could we tease the features for free accounts by showing them disabled?
### Support
Here we could have a search field that opens up to external support content. We could have some top-level FAQs inline. The idea is to provide something quick, just the right scope, but a place to get them started on getting help. [See this inspiration](https://www.figma.com/file/u4JmGghyoLS2gHcFtmrPQG/Admin-Prototype?node-id=184%3A1452)

## Acceptance criteria
- Designed a concept to demonstrate:
  - the overall IA and navigation, including sub-navigation
  - ways that views may have sections in tabs or expanding sections
- Proposed a small way to start
  - What nav items could we ship with first using existing views?
- Stretch: wired up a quick prototype with conceptual page content (just fake it so that it matches the IA) so that we can test with 5 customers (can be deferred as a second issue)
- Stretch: (after creating a prototype) drafted implementation issues for creating the navigation components, views, routes, and how to move existing sections to their new homes

## Estimated effort
- 21 hours

**Comment by jordanh** [comment]
Discussed during user feedback retro: https://action.parabol.co/meet/aG72wCHz5S/discuss/2

**Comment by jordanh** [comment]
Related, and something we may consider doing as a follow on: #4805

**Comment by drewhousman1010** [comment]
An enterprise [user ](https://app.hubspot.com/contacts/3888472/contact/28098151)🔒 writes:

> My boss left the company, so I should now be the default admin for Parabol. I can see that I am the billing leader, but I can't see all the teams that exist in Parabol. Is there a way to make me the main admin for all teams at my company?
> 
> This came up because someone asked me to add them to a team they are not on (and that I am not on) and I thought I would be able to see everything with that role.

**Comment by ackernaut** [comment]
> A [customer](https://app.hubspot.com/contacts/3888472/deal/1874650176) 🔒 was having some trouble because users couldn't access the Enterprise organization. They probably joined Parabol without getting an invite to a team that was in the Enterprise organization which resulted in them creating new teams in a new organization. Right now the solution would be to merge the teams into the right organization. It would be nice for new users to have the option to join the upgraded organization if they have the same email domain.

+1 to being able to identify a domain and request access cc @gcrickman

**Comment by avivapinchas** [comment]
**Value: 3**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/9) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: XL**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/10) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by drewhousman1010** [comment]
An enterprise [user ](https://app.hubspot.com/contacts/3888472/contact/20491151) 🔒 writes:

> We got a request to add users to a team that I’m not personally on, and we’re not sure who the administrator is for that team. Is there any level of admin control that would allow me to see all teams?

**Comment by ackernaut** [comment]
@drewhousman1010 that’s a good use case, thanks for capturing.

**Comment by mattkrick** [comment]
@ackernaut any designs we can start building against?

**Comment by ackernaut** [comment]
@mattkrick I’m a little behind on addressing needs for individual design issues, but I can bring this into my queue for my squad time. I should have a starting point for us if we’re ready to work on it, but I need time sort it with some other squad design needs.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/53157801) 🔒 writes:

> I'm curious if there is some kind of administrator or global read-only role that could be granted to myself and ___ in order to answer any questions from our internal users before we need to send them over to yourself? As it stands we will only see the projects/teams that we are directly added to. At least during our pilot phase it would be good to have visibility on the usage.

**Comment by jordanh** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/61271051) 🔒 writes:

> As a Senior EM with several teams, I try to use parabol's digest feature rather than using it to run meetings directly. Having a multi-team dashboard to review past datapoints would be very helpful for myself and others in the Director-ish sphere at [Company X].
>
> It’d be nice to see attendance (who attends meetings how often) as well as engagement per person.
> While it’s hard to quantify “engagement” in a deterministic way, understanding of someone went to the meeting and contributed at least one card would say a lot about the value various teams are getting out of each meeting.

**Comment by jordanh** [comment]
Related issue: #8055

**Comment by jordanh** [comment]
Assigning this to Squad Self-Serve, but feel free to close in favor of different/more granular work

**Comment by avivapinchas** [comment]
Reviewed this issue a while ago (Loom here) and broke it down into 3 smaller issues on Notion: [Access Admin role](https://www.notion.so/parabol/Admin-Access-Role-c097dc055f13424bbc4f39408a9936d0) (backlogged),[ automatic re-assign team lead](https://www.notion.so/parabol/Automatically-assign-new-team-lead-when-team-lead-leaves-1f995d39dd3b402f9f9b80141c4397aa), and '[did you mean to join X org?' prompt](https://www.notion.so/parabol/Did-you-want-to-join-X-Org-Prompt-0d2ed2665034493f96da98abf0c4f711) (final implementation). 

Closing this issue in favor of those.
