### ISSUE TITLE
Empty meeting summary emails sent on staging

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#5720]
## Issue - Bug

**Steps to reproduce**

- Create any meeting on staging
- Finish meeting
- See empty summary email received

![image](https://user-images.githubusercontent.com/466991/143872895-3ee65cdc-cdf4-48c0-bf17-58e37212fb17.png)

Release tests issue: #5715

**Comment by igorlesnenko** [comment]
The issue is not appearing on production after the release. So it's something to do with staging only.

Though, it make sense to investigate this at some point, as otherwise, we can't test emails on staging, and it might be an indicator of some other potential issues.

**Comment by mattkrick** [comment]
AC
- [ ] find the root cause. if easy to fix, do it. otherwise open another issue

**Comment by ackernaut** [comment]
I got an empty summary email for our design check-in meeting today.

**Comment by igorlesnenko** [comment]
So the issue was already fixed by removing these lines of code:

https://github.com/ParabolInc/parabol/commit/9d5a8548994d4982d8a5e57d3c0f7917cdb968fd#diff-684344d1b071bd71a363c34ae791895edb616d76dec74a9a4420268398ee2bc5L60-L64

It was not reproducible on `localhost` and `production` because `DD_TRACE_ENABLED` was not set to `true` there.

Deleted part of the code returns the response as:
```
{
  data: [Object: null prototype] {
    viewer: [Object: null prototype] {
      newMeeting: [Object: null prototype],
      id: 'local|7RocnjZ768'
    }
  }
}
```

While fixed part of the code returns:
```
{ data: { viewer: { newMeeting: [Object], id: 'local|7RocnjZ768' } } }
```

`JSON.stringify` for both responses gives identical results. 

The issue was caused by `null prototype`. Because of this `QueryRenderer` was failing with an error `TypeError: data.hasOwnProperty is not a function`

@mattkrick I would suggest closing this issue.

@ackernaut as far as I see, the current issue didn't exist on production. If you saw an empty email on production, can you please provide a screenshot and some additional information about the meeting, so I can find it in the database? 

I would suggest opening a separate issue for this. As it is most likely it is unrelated to this staging issue.
It could be something like new env variables were set before deploying new code, but not sure, need to look.

**Comment by ackernaut** [comment]
@igorlesnenko here’s the new issue: https://github.com/ParabolInc/parabol/issues/5808

Let me know if you need more details

**Comment by igorlesnenko** [comment]
Closing this as staging issue was fixed. Will check: #5808
