### ISSUE TITLE
Invitation required screen right after creating a new team

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#5721]
## Issue - Bug

**How to reproduce**

- Create a new team in existing organisation
- See the new team board is opened
- Refresh a page
- See "Invitation required" screen
- See you are no longer able to access the team

![image](https://user-images.githubusercontent.com/466991/143874779-fae3ffa5-106d-4fdc-954d-85e1d3f09a02.png)

**Another way to reproduce:**

- Create a new organisation, specify team name
- Refresh the page, see organisation disappeared from the sidebar
- Refresh the page again — it appeared in the sidebar
- Refresh again — disappeared, etc.
- Wait for several minutes
- Refresh the page — see invitation required screen
- Try to click on it in the sidebar — invitation required screen, you are no longer able to access the organisation

https://user-images.githubusercontent.com/466991/143608984-d331a1e3-0045-476a-a7cf-385fb245fb62.mov

**Comment by igorlesnenko** [comment]
Found an additional issue that exists both on staging and production.

- Create a new user.
- Quickly after creation click on add meeting button at bottom right corner of the screen

See `an error has occurred` message

![image](https://user-images.githubusercontent.com/466991/143930990-0dc60513-6d19-469d-ad6c-80a3f1719b33.png)

**Comment by tiffanyhan** [comment]
Only happens on prod and staging, I was unable to reproduce it locally

**Comment by mattkrick** [comment]
root cause found, gonna submit a PR fix soon
