### ISSUE TITLE
Updating GitHub estimates breaks integration in case of switching from comment to label

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#5722]
## Issue - Bug

**How to reproduce**

- Add GitHub integration
- Start a poker meeting
- Add a fresh GitHub issue with no estimation and no labels to the scope
- Pick any value, select `As a comment` and click update
- See comment appeared on GitHub
- Select `As a label` option, keep value the same, click update again
- Refresh a page
- See GitHub integration down error
- See GitHub label is added on GitHub correctly

The error from sentry

```
Error: There can only be one variable named "repoName"
  File "app:///gqlExecutor.js", line 1, in null.<anonymous>
    '{snip} pointContext:t,batchRef:n}),{data:s,errors:d}=o;return[s,d?new Error(d[0].message):null]}}},4311:(e,n,t)=>{"use strict";t.d(n,{Z:()=>i});con {snip}
  ?, in runMicrotasks
  ?, in async Promise.all
  File "app:///gqlExecutor.js", line 1, in async resolve
    '{snip}            }`,b=(0,a.Z)(d,o,{accessToken:u}),[[v,A],[R,S]]=await Promise.all([b(y),m.length>0?b("query getIssueLabels($repoName: String!, $r {snip}
```

**Comment by tianrunhe** [comment]
Closed together with #5908
