### ISSUE TITLE
Add noUncheckedIndexedAccess to tsconfig.base (Part 3 of 4) 

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5746]
see #5313 for context

AC
- [ ] add `noUncheckedIndexedAccess` to tsconfig.base
- [ ] fix ~100 typescript errors
- [ ] remove `noUncheckedIndexedAcces` from tsconfig.base
- [ ] submit PR

Estimate: 4 hours

**Comment by Dschoordsch** [comment]
For reference, on master there are at the moment:
parabol-server: Found 150 errors.
parabol-client: Found 98 errors.

**Comment by Dschoordsch** [comment]
I fixed all parabol-client issues in #5837 and enabled the config there. I will create a new ticket for the remaining
```
parabol-server: Found 98 errors.
```
issues.
