### ISSUE TITLE
Need to refresh after integrating Jira or GitHub

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5756]
Predecessor: #5755 

To reproduce:

- Integrate Jira or GitHub
- Open the dropdown menu on a task and start searching
- See that the Jira or GitHub issues do not show up
- Refresh the page and now see that they do
- Remove the Jira or GitHub integration, search again, and see the issues still show up unless you refresh the page

### AC

- [ ] After adding or removing a Jira or GitHub integration, the user does not need to refresh the page to see the change when searching in the task dropdown

**Comment by agarg21** [comment]
Hi, I'm trying to work on some bugs to familiarize myself with the codebase.

What's a good way to test this on Dev? I created a test Github app - what should I put in the field "callback url"? 
https://docs.github.com/en/developers/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps#2-users-are-redirected-back-to-your-site-by-github

Is there some other documentation I can follow to test integrations on Dev? 

Thanks,
Apoorva

**Comment by Dschoordsch** [comment]
Callback URL should be `http://localhost:3000/auth/github`. It must forward to https://github.com/ParabolInc/parabol/blob/master/packages/client/components/AuthProvider.tsx which is bound to that address https://github.com/ParabolInc/parabol/blob/master/packages/client/components/Action/Action.tsx#L59

**Comment by jordanh** [comment]
Iceboxing
