### ISSUE TITLE
Cannot destructure property 'name' of 'k' as it is undefined.

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5765]
## Issue - Bug

[Sentry](https://sentry.io/organizations/parabol/issues/2663127037/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d)

```
TypeError c(packages/client/components/EstimateDimensionColumn)
Cannot destructure property 'name' of 'k' as it is undefined.
```

Affects 30 users in last 30 days.

### Acceptance Criteria (optional)
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
294 users affected. Going to keep this one open and bump a bit in priority
