### ISSUE TITLE
Cannot read properties of undefined (reading 'lastSeenAtURLs')

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5766]
## Issue - Bug

[Sentry](https://sentry.io/organizations/parabol/issues/2418189861/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d)

Affects 14 users in last 30 days.

### Acceptance Criteria (optional)
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tianrunhe** [comment]
Sentry issue: [ACTION-PRODUCTION-6RJ](https://sentry.io/organizations/parabol/issues/2418189861/?referrer=github_plugin)

**Comment by jordanh** [comment]
Now 24 users affected. Ice-boxing per policy
