### ISSUE TITLE
Dashboard filter controls enhanced to incl. search

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5777]
## Enhancement

Today, when a task card is pushed to an integration we have a wonderful control that looks like this:

![image](https://user-images.githubusercontent.com/103000/146066679-9131e4d4-a9ec-4242-817a-acbfa1dba5d2.png)

When team's have many, many projects they can narrow the list by typing in a filter string.

Other drop downs, like these filter controls on https://action.parabol.co/me/tasks look like this:

![image](https://user-images.githubusercontent.com/103000/146066849-6a11ed7a-6577-41ed-b699-26b7d51d15e3.png)

They could really benefit from the same filter-string pattern.

### Acceptance Criteria

- Filter controls on the following routes updated to use a control with a filter string
   - https://action.parabol.co/me/tasks
   - https://action.parabol.co/team/:teamId

### Estimated effort

- 13 hours

**Comment by elielytz** [comment]
## Test Results

### Task card integration filter check:
Status: Passed

- Case sensitive: Checked
- Filter using single/double letters : Chaecked
- Feedback if not searching results: available

https://user-images.githubusercontent.com/45159239/151502592-d651515a-5cad-4a59-b15d-4c15618c6d28.mp4

### Team member filter dropdown
Status: It seems is not in the staging environment yet, I am testing it on local environment
