### ISSUE TITLE
‘5 whys activity’ end-to-end UX explored

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5778]
## Background

I’m pulling some feedback from [a customer](https://app.hubspot.com/contacts/3888472/contact/19191201) 🔒  in an email thread. This is the beginning of the useful context:

>Let me take the chance of this direct connection with you and let you know about one more thing that would turn Parabol into our favorite agile tool: **5-whys template for post-mortems**. We love post-mortems and we're doing it regularly for incidents to learn our lessons. We tried using Confluence, spreadsheets, Miro, Draw.io and something else. We were looking forward to moving this activity to Parabol after reading [this article](https://www.parabol.co/blog/howto-run-successful-incident-postmortems) but it turned out, the described template cannot be created (we tried and also contacted your colleagues some months ago).

Long story short, (my interpretation) they were not happy with the current Retro template abilities because it doesn’t allow for folks to have open phases or cycles of progressive inquiry:

>There can't be any voting and action points can come at any level of discussion…can you provide us something like [this](https://www.mindtools.com/pages/article/newTMC_5W.htm)?

The customer shared this image.

![image](https://user-images.githubusercontent.com/307286/146064525-a6467008-2520-4155-bba0-33cccd563819.png)

They shared:

>For example we have a lot of discussions like below. All it b/w are whys(discussion) and in green are action items. And we would like to push to Jira action items identified and have some reference outside of it to get the context if needed. 

And another image:

![image](https://user-images.githubusercontent.com/307286/146065074-b921e7fb-2548-43a4-8fbb-a4a5b3dbbf51.png)

Jordan replied:

>We'd like to add 5 Whys to as a feature to any Discussion item, so that you could drill into the root cause of an issue or behavior. I think I want what you want. Just to make sure we understand each other: it's not about having a new meeting template, but rather a feature that would allow you to start a "5 Whys" during a discussion, right?

They replied:

>From my side it's about a new meeting template. We sometimes(often) gather to do a "5 whys" on some topic(incident). Usually it's a separate discussion, not a retrospective of the latest sprint or something. We need a meeting to dig into the root cause of the problem urgently and identify action items to be done to avoid issues in future. 

And a bit more they shared:

>I'd like to give you even more context on how we conduct post-mortems. I was a bit inspired by [this article](https://www.atlassian.com/incident-management/handbook/postmortems#what-is-post-mortem).
Preconditions:
We had an incident and want either to prevent it happen in the future or make the impact less forceful
One of the team members fills in the form which describes what happened, how we discovered it and the incident timeline(who did what and when). This part is important as team needs the full picture of what happened and who was involved.
Meeting:
as we have an incident summary we start asking first 'why' to it. For example "Service A ran out of memory on prod"
we can have several answers on 'why' question and choose what branch to dig in first
when all branches are covered, we identify action items and link it to respective answers. it's important to have them linked as later it gives context in case we forget where the action item came from. action item always has an assignee
After meeting activities and some thoughts:
I create Jira tickets in Process project and assign them to assignees defined previously. Sometimes it's a pain :(  
as we usually are very limited in time we write answers and action items in russian but Jira is english only tool. So I need(nice to have) to be able to update action items after meeting before pushing them to Jira(when you fix issue with pushing cards to Jira)
it will be helpful to have a link to meeting results page in pushed Jira ticket to be able to jump to it at any time

### User interview
I spent some time with the customer talking about 5 Whys, [see the Loom](https://www.loom.com/share/0461e2dffed940408270755632c1eb35) 🔒 

## User job story

One possible job story to provoke thought:

>When looking to understand the causes of an incident with a product/service (e.g. an outage), customers want an activity that supports rounds of open discussion (that could support a 5 whys format), so that they can get to the underlying causes and create clear takeaway items with the option of integrating those tasks in other destinations (e.g. Jira backlog)

## Current roadmap notes and ideas

These are opportunities to expand on our existing thinking and roadmap:

**Idea 1**) We’re introducing an async team prompt tool that supports a single open question in its first version. One idea for building on top of this experience was to allow for multiple rounds of prompts ([see this Loom starting at ~24:00 mins](https://www.loom.com/share/449bb7e2934541d190635e602c1444c6)). Each prompt could trigger new responses, threads, and action items. Perhaps they could format the prompts ahead of time (i.e. 5 literal “why” prompts as an async prompt template) or just press ‘add another prompt’ organically at different points in the discussion (some response card opens up another prompt phase from the thread (add a task, add a prompt) with its inputs from the team and respective threads). The template approach would make this reusable for other formats like governance, where each phase of questions is predetermined, whereas the ‘add another prompt’ would be neat for rounds of divergence and convergence, where you could add another cycle.

**Idea 2**) This could be a stand-alone activity ,or be kicked off at any time during a discussion topic in a thread, or scheduled for later as an action item?

## Acceptance criteria

- Produced a series of sketches showing the end-to-end experience of starting, holding, and concluding a 5 whys discussion addressing any open questions. Form an opinion and add your open questions)

### Open questions
- How and when is this activity started?
- How can we make use of existing experiences like the basic async prompt activity?
  - Or the reverse, how could we reuse the components of this experience to power other experiences that need predetermined or on-the-fly rounds of questioning? 
- What is a useful format for a summary?
- What data, research, or inspiration could help here?

- Suggested actionable next steps, some ideas:
  - Created a scrappy prototype (testing biggest ideas and risks, even over optimization and refinement)
  - Followed up with the customer for feedback
  - Drafted next design issues to refine UX and UI (a la breaking down the work)
  - Identified next steps (add your own here)

## Estimated effort
- 21 hours

**Comment by gcrickman** [comment]
A [customer](https://app.hubspot.com/contacts/3888472/contact/3322301) 🔒 writes:

> Any thoughts on introducing a 5 Whys retro template? That's something we would like to use Parabol for but can't quite figure out the optimal way to set it up

**Comment by ackernaut** [comment]
**Priority? Must/Should/Could/Won’t Have: C**
  [See the discussion](https://action.parabol.co/meet/rTgzJqOZoc/estimate/2) in Sprint Poker #​​12

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
