### ISSUE TITLE
Created a team prompt activity data type

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5788]
Adding placeholders for now, any member can contribute to these details…
## Background
(add background here)
See useful outputs of #5787 
## Open questions
(add open questions here)
## Additional notes
(add notes here)
## Acceptance criteria
- Created a team prompt activity data type that we can build with
## Estimated effort
- 13 hours

**Comment by BartoszJarocki** [comment]
Closing in favor of: https://github.com/ParabolInc/parabol/issues/5916
