### ISSUE TITLE
Created a start and end mutation for team prompt activity

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5789]
Adding placeholders for now, any member can contribute to these details…
## Background
(add background here)
See useful outputs of #5787 
## Open questions
(add open questions here)
## Additional notes
(add notes here)
## Acceptance criteria
- Created a mutation that starts and end a team prompt activity
## Estimated effort
- 13 hours

**Comment by BartoszJarocki** [comment]
Closing in favor of: https://github.com/ParabolInc/parabol/issues/5930 and https://github.com/ParabolInc/parabol/issues/5936
