### ISSUE TITLE
Adds team prompt activity option to existing start meeting view

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5790]
Look for designs from #5888

## Acceptance criteria
- Behind the feature flag, beta users can see the team prompt activity option in the start new meeting carousel
- For there first pass, the only option is to select which team to start the activity
- Tapping start creates an new meeting, even if we haven’t built out the UI for that meeting yet
## Estimated effort
- 8 hours

**Comment by ackernaut** [comment]
My current thinking is that we add an un-styled carousel option to start the team prompt activity from the existing ‘start meeting’ view. Once we get closer we can see where we are with the new start meeting dialog. If the first version has shipped, then we can add to it. Otherwise we can dress up this view for production

**Comment by BartoszJarocki** [comment]
@ackernaut I've created the standup issues grouped by the feature. There's some overlap so I'll close some of them and reuse the rest. I hope you don't mind! 

Closing this in favor of: https://github.com/ParabolInc/parabol/issues/5918

**Comment by ackernaut** [comment]
That works @BartoszJarocki
