### ISSUE TITLE
Adds a team prompt activity card to meetings view behind feature flag

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5791]
Look for designs from #5925 

## Acceptance criteria
- Behind the feature flag, a meeting card appears for the async stand-up when one is started
- It goes away when the meeting is closed
- There’s a menu item to invite to the meeting

## Estimated effort
- 8 hours

**Comment by BartoszJarocki** [comment]
Closing this in favor of https://github.com/ParabolInc/parabol/issues/5931 and https://github.com/ParabolInc/parabol/issues/5937 (handling on the start/end meeting mutation and as a result, showing/removing meeting card)
