### ISSUE TITLE
Refined UI for team prompt activity card

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5793]
Adding placeholders for now, any member can contribute to these details…
## Background
(add background here)
## Open questions
(add open questions here)
## Additional notes
(add notes here)
## Acceptance criteria
- Implements the missing details and styles for #5791 as defined by #5792 
- The card is generally ready for production
## Estimated effort
- 13 hours

**Comment by BartoszJarocki** [comment]
Closing in favor of https://github.com/ParabolInc/parabol/issues/5931
