### ISSUE TITLE
Standup UI - Response thread

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5796]
Design - https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1247%3A80368 

Design task - https://github.com/ParabolInc/parabol/issues/5966 

AC
- [ ] UI matches the design
- [ ] Responses can have their own thread object
- [ ] Users can add comments or tasks in the thread

**Comment by BartoszJarocki** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/7) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by BartoszJarocki** [comment]
**Include?: Y**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/8) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
