### ISSUE TITLE
Standups: Recurrence built for team prompt activities

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5798]
## Recurrence
**Goal**: beta users can specify recurrence; open activities update automatically to reflect the pattern
- [ ] Discussed, decided, and documented architecture for recurrence function
- [ ] Data types updated to support recurring patterns
- [ ] Mutations created to support recurring selections
- [ ] Lo-fi placeholder recurrence controls added to the start meeting view
- [ ] Refined UI of recurrence settings controls based on current designs (this is in flight); controls can be reused in the start activity dialog
## Acceptance criteria
- Created the next stand-up milestone including new issues representing the above or whatever we learned we really needed
## Estimated effort
- 3 hours

**Comment by BartoszJarocki** [comment]
earlier discussion reference: https://github.com/ParabolInc/parabol/issues/5916

**Comment by BartoszJarocki** [comment]
Closing in favor of https://github.com/ParabolInc/parabol/milestone/141
