### ISSUE TITLE
 Jira Server: sprint poker vote to comment

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5811]
Needs:
* #6096 

## Acceptance criteria
* [ ] Add Jira Server as part of `setTaskEstimate` mutation
* [ ] add logic to write score to comment (adding comment logic is already part of the manager #5810)

**Comment by jordanh** [comment]
**Include in next sprint?: N**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/3) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
