### ISSUE TITLE
Make createJiraTaskIntegration/createGitHubTaskIntegration generic

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5819]
Both mutations are virtually identical and are just different in the IntegrationManage used. Since we also need a mutation like this for Jira Server and GitLab it is sensible to make it generic first

## Acceptance criteria
* [ ] replace `createJiraTaskIntegration` and `createGitHubTaskIntegration` with one `createTaskIntegration` mutation
  * [ ] arguments `integration` of type `IntegrationProviderTypeEnum`, `taskId` and `projectId`
* [ ] all integration specific actions are performed in their respective IntegrationManager

**Comment by Dschoordsch** [comment]
The idea is to have 2 arguments: `taskId` is our id, `projectId` is integration specific and interpreted by the integration manager. For Jira the `projectId` would be in the format [`JiraProjectId`](https://github.com/ParabolInc/parabol/blob/2708b9553cc212d6da9be951c6b486e46f57b68d/packages/client/shared/gqlIds/JiraProjectId.ts) which already includes the `cloudId` and `projectKey`, for GitHub the `projectId` would be in the format `nameWithOwner` which is just GitHubs format for a project id.

**Comment by elielytz** [comment]
## Testing results

This works like a charm 💯 .
