### ISSUE TITLE
Jira Server: poker read back votes

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5821]
## Acceptance criteria
* [ ] Read votes from Jira server and show on task in Poker

**Comment by jordanh** [comment]
**Include in next sprint?: N**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/1) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
**Story points: 13**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/17) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
**Include in next sprint?: N**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/18) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
