### ISSUE TITLE
add eslint rule: disable `!=`

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5823]
we like things strict. let's make `!=` an error to force `!==`

AC
- [ ] eslint rule added & all offenders fixed

Estimate: 2 hours

**Comment by tiffanyhan** [comment]
@tianrunhe can you take a look at this one please?

**Comment by tiffanyhan** [comment]
@igorlesnenko as this is my last day, may i pass this issue to you, or you can reassign it if your plate is full? 🙏
