### ISSUE TITLE
Fixed retro demo integrated task creation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5826]
## Issue - Bug

Integration task creation is currently broken. When you hit the publish button, an empty menu is displayed:

![image](https://user-images.githubusercontent.com/103000/147511837-4db6b42d-37e1-4ff0-868e-8771c872aba1.png)

Reproduction:

1. Advance https://parabol.co/retro-demo to Discussion phase
2. Create task
3. Press publish button
4. Observe bug

### Acceptance Criteria (optional)
Users can:
   - Create integrated tasks during the demo

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by agarg21** [comment]
Hello! I have been trying to learn more about Parabol, was trying to find a bug to work on.

I tried to debug this bug, I think we are returning here:
https://github.com/ParabolInc/parabol/blob/1766b647c835e7ac4ce1bda2bf0a8844441c01c3/packages/client/components/TaskFooterIntegrateMenu.tsx#L72

I'm still trying to understand why `assigneeTeamMember` and `viewerTeamMember` are undefined for demo user.

**Comment by Dschoordsch** [comment]
@agarg21 thank you for looking into this!

**Comment by nickoferrall** [comment]
Fixed by https://github.com/ParabolInc/parabol/pull/5827
