### ISSUE TITLE
Implement Create abstract NotificationManager class

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5828]
Implement #5748

## Acceptance criteria
* [ ] Refactor Slack and Mattermost notifications to resemble following structure
```
interface NotificationManagerAuths {
  slack: SlackAuth | null,
  mattermost: MattermostAuth | null
}
type NotificationManagerType = keyof NotificationManagerAuths

class IntegratedServicesNotifier {
  managers: {[key in NotificationManagerType]?: NotificationIntegrationManager} = {}

  constructor(auths: NotificationManagerAuths) {
    // init this.managers based on auths
    if (auths.slack) {
      this.managers.slack = new SlackNotificationIntegrationManager(auths.slack)
    }
...
  }

  // returning void because otherwise errors would need to be picked apart per integration and this manager should deal with retries
  // preferences should be limited to enable/disable an integration for a certain action, we don't want to support sending different events to different channels for example
  startMeeting(meeting: NewMeeting, team: Team, preferences: NotificationManagerType[]): Promise<void>
  endMeeting(meeting, team, preferences): Promise<void>
  startTimeLimit(meeting, team, preferences): Promise<void>
  endTimeLimit(meeting, team, preferences): Promise<void>
}

type NotifyResponse = 'success' | {
  error: Error
  recoverable: boolean
}

export interface NotificationIntegrationManager {
  startMeeting(meeting: NewMeeting, team: Team): Promise<NotifyResponse>
  endMeeting(meeting, team): Promise<NotifyResponse>
  startTimeLimit(meeting, team): Promise<NotifyResponse>
  endTimeLimit(meeting, team): Promise<NotifyResponse>
}

// new dataloaders to load all available notification auths
const auths: NotificationManagerAuths = await dataLoader.get('notificationManagerAuths').load({teamId, userId})
const manager = new IntegratedServicesNotifier(auths)

const preferences = await dataLoader.get('notificationPreferences')
manager.startMeeting(meeting, team, preferences.startMeeting
```

**Comment by jordanh** [comment]
Could you move this issue to the Reviewer Review column and tag some folks (like @Dschoordsch or @BartoszJarocki) to look at this? Once this API has been reviewed, I'll prioritize this for implementation

**Comment by tiffanyhan** [comment]
@Dschoordsch mind reviewing the API in the issue description for this issue?

**Comment by Dschoordsch** [comment]
* I would remove `NotifyResponseEnum` and change the return type in `NotificationIntegrationServerManager` to `Promise<void | Error>`. I think the only reason for `NO_OP` would be if the integration was not added and then we shouldn't be able to create a `NotificationIntegrationServerManager` for it in the first place.
* In `IntegratedServicesNotifier` the `managers` field depends on the `teamId`, so I would restructure it to be initialized with `teamId` and `dataLoader` and then it can have `startMeeting(meetingId): Promise<void>` etc. `managers` field can be private.
* `startTimeLimit` also needs `scheduledEndTime: Date` argument

@tiffanyhan What do you think?

**Comment by tiffanyhan** [comment]
> startTimeLimit also needs scheduledEndTime: Date argument

yeah that makes sense!

> - I would remove NotifyResponseEnum and change the return type in NotificationIntegrationServerManager to Promise<void | Error>. I think the only reason for NO_OP would be if the integration was not added and then we shouldn't be able to create a NotificationIntegrationServerManager for it in the first place.
> - In IntegratedServicesNotifier the managers field depends on the teamId, so I would restructure it to be initialized with teamId and dataLoader and then it can have startMeeting(meetingId): Promise<void> etc. managers field can be private.

that's interesting. i was actually envisioning these classes to be singletons, sorry if that wasn't clear in the spec. we could go a non-singleton route, but imo it seems a bit unnecessary to instantiate multiple times for different use cases. what do you think the pros and cons would be of singleton vs non-singleton? @Dschoordsch

**Comment by Dschoordsch** [comment]
@tiffanyhan I think a singleton is fine here, just wasn't clear. The biggest drawback of singletons is bad testability, but that's really not an issue here. I would then change `NotifyResponseEnum` to be a string union though, because that's used mostly now.
Could you please update the description to clarify these points?
* [ ] singleton `IntegratedServicesNotifier`, maybe just define the instance or getter
* [ ] add the argument to `startMeeting`
* [ ]  change `NotifyResponseEnum` to string union

**Comment by tiffanyhan** [comment]
> @tiffanyhan I think a singleton is fine here, just wasn't clear. The biggest drawback of singletons is bad testability, but that's really not an issue here. I would then change `NotifyResponseEnum` to be a string union though, because that's used mostly now. Could you please update the description to clarify these points?
> 
> * [x]  singleton `IntegratedServicesNotifier`, maybe just define the instance or getter
> * [x]  add the argument to `startMeeting`
> * [x]   change `NotifyResponseEnum` to string union

@Dschoordsch I clarified details for the spec and updated some naming to be more clear. please review and lmk if any follow up questions or comments.

**Comment by Dschoordsch** [comment]
@tiffanyhan I don't think there is any benefit in making the implementations of `NotificationIntegrationServerManager` singletons since these should not be accessed directly but always through `NotificationIntegrationServerManager`. It could also make testing of those more difficult in the future, so I would just leave them as normal classes.

**Comment by tiffanyhan** [comment]
@Dschoordsch are you saying that we only need a singleton getter for `IntegratedServicesNotifier` and not for any of the `NotificationIntegrationServerManager`s since they'll only be instantiated through `IntegratedServicesNotifier`? I.e. they'll be singletons in fact already because of this, without us needing to do any additional work to make it so. If so, I totally agree. I just wanted to make the classification explicit rather than implicit in the spec.

**Comment by mattkrick** [comment]
- I don't believe we can use singletons here. For example, `startMeeting` will need to use a user-specific token that possibly expires before we use it again. I'd say we just create it when we need it & let it go after the call. the fresh token will be saved in the dataloader so subsequent creations won't be expensive
- I think the method calls may need to include a userId (by default the viewerId) to pick the best token
- I'd suggest `NotifyResponse` be replaced with the object that comes directly from the service. That way we don't lose data for debugging, etc. e.g. `SlackNotificationManager = NotificationManager<TSuccess>`

**Comment by tiffanyhan** [comment]
> * I don't believe we can use singletons here. For example, `startMeeting` will need to use a user-specific token that possibly expires before we use it again. I'd say we just create it when we need it & let it go after the call. the fresh token will be saved in the dataloader so subsequent creations won't be expensive

ah you mean that we need a user-specific api auth token to hit the integrated service api? In the spec, `NotificationIntegrationServerManager`s would be separate from e.g. `SlackServerManager` and `MattermostServerManager`. The latter would handle generic api auth and communication, while the former would encapsulate parabol specific notification logic. since those two are separate, i think `NotificationIntegrationServerManager`s can be singletons, unless i am missing something. `SlackServerManager` and `MattermostServerManager`s can be instantiated ad hoc and as needed.

it's possible to simplify and combine the two into one class, but i think it's better to decouple generic api communications from parabol-specific app logic.

> * I think the method calls may need to include a userId (by default the viewerId) to pick the best token

looking at the code, it looks like we've been pretty consistent in using `meeting.facilitatorUserId`. do you think we should continue this pattern, or explicitly pass in the viewerId as you said above?

> * I'd suggest `NotifyResponse` be replaced with the object that comes directly from the service. That way we don't lose data for debugging, etc. e.g. `SlackNotificationManager = NotificationManager<TSuccess>`

That sounds like a good idea. Since we won't always have a response from the service, either in case of no-op or of some errors (e.g. network errors), perhaps instead of replacing we can just add it as an optional second argument to the return type.

**Comment by tiffanyhan** [comment]
@Dschoordsch or maybe @BartoszJarocki since today is my last day, may i ask you to take over this work? i feel like i've pretty much documented all my current thinking on this one, so i think it's in a good state to pass on. feel free to make whatever changes you think needed to the api spec.

**Comment by Dschoordsch** [comment]
* Right now we're using the meeting `facilitatorUserId` for the `auth`, which effectively is the `viewerId`. We also fallback to any team members `auth` inside the dataloader if the user themselves don't have the integration, which is fine. Thus we don't need to pass the `userId` separately.
* At the moment we just fire and forget to both slack and mattermost. We also only call one notification method per mutation. There is no response from the methods.
* One thing we might want to pull out of the individual Slack/MattermostNotificationManagers is how multiple channels are handled. Right now it is up to the integrations themselves, but this should be common for all notification managers. This is out of scope of this change, but should be considered for the design.

With these considerations, I would only make minor adjustments to the design proposed by @tiffanyhan:
```ts
NotifyResponse = 'SENT_SUCCESSFULLY' | 'NO_OP'

class IntegratedServicesNotifier
  managers: NotificationIntegrationServerManager[]

  constructor(meetingId, teamId, dataloader) {
    // init applicable notifiers, which in the first step would be 1 mattermost and 1 slack
    // in the future, we can expand this to take settings into account here
    // TBD we can also have 1 notifier instance per auth/team member in the future to move the decision which channels to notify here
  }

  public startMeeting(): Promise<void>
  public endMeeting(): Promise<void>
  public startTimeLimit(): Promise<void>
  public endTimeLimit(): Promise<void>
}

interface NotificationIntegrationServerManager {
  new(meetingId, teamId, dataloader): NotificationIntegrationServerManager
  public startMeeting(): Promise<NotifyResponse | Error>
  public endMeeting(): Promise<NotifyResponse | Error>
  public startTimeLimit(): Promise<NotifyResponse | Error>
  public endTimeLimit(): Promise<NotifyResponse | Error>
}
```

**Comment by BartoszJarocki** [comment]
@Dschoordsch looks good. I have a couple of questions, though:
1. Is there any reason to pass the data loader (and what data loader?) in the constructor? I'd rather pass data that's needed explicitly. If someone can fetch data that's not really needed there, it'd make it easier to overuse the class and implement functionalities that weren't supposed to be there. 
2. What about singletons? It seems to me we can't really (or at least shouldn't) use singletons here; I imagine `IntegratedServicesNotifier` should have all the services for a given user (or team).

**Comment by Dschoordsch** [comment]
@BartoszJarocki
1. The reason for passing the `dataLoader: DataLoaderWorker` is that loading the authentication is quite different per notifiction service. Also the notification services load `NewMeeting` and `Team` in order to construct the appropriate messages. We could split this up: `IntegratedServicesNotifier` still gets the `dataLoader` loads the auth for different services (which involves auth specific knowledge) and also `NewMeeting` and `Team` to only pass relevant information to Slack/Mattermost notification service. The advantage would be pulling out the dataLoader of the services. However this is a bit deceiving as there is some DB access still in the service to update rows on errors for example. That would need to be moved out as well. That's a bigger step right now and not necessary in the first step I think.
2. There are no singletons anymore in my last proposal.

**Comment by BartoszJarocki** [comment]
Thank you for clarification, everything looks good to me.

**Comment by mattkrick** [comment]
> RE: dataloader argument

+1 Today, dataloaders use IntegrationManagers to [talk to services](https://github.com/ParabolInc/parabol/blob/d60fad0527c699ad7ea9498840b42734f6dece30/packages/server/dataloader/atlassianLoaders.ts#L235-L239) and managers never use dataloaders. This unidirectional dataflow (GraphQL Resolver > Dataloader(s) > Service) keeps things simple (IMO it's why React beat Angular as the preferred framework back in the day). If down the road notification managers are used to query things from services (vs. mutate), would we cache those results in a dataloader? would a dataloader -> manager -> dataloader pattern be confusing or set us up for more stale cache reads?

An alternative might be:

```ts
const auths = await dataLoader.get('notificationManagerAuths').load({teamId, userId})
const manager = new IntegratedServicesNotifier(auths)

const preferences = await dataLoader.get('notificationPreferences') // e.g. call slack on start & mattermost on meeting end
manager.startMeeting(meetingId, preferences)
```

It's nice keeping everything self-contained in a manager. It's also nice having a unidirectional flow. There's no easy answer here, I've got a slight preference to keep them separated, but I could go either way.

> meetingId arg

+1 it's possible that we build notifications that occur outside a meeting (e.g. TaskAssigned). In that case, we'd want `meetingId` to be part of the `startMeeting` method & not in the constructor.

safe to move forward!

**Comment by mattkrick** [comment]
As this is a discussion issue, I'll leave it to @Dschoordsch to close when ready & open a new implementation issue (can just copy over your AC from here)

**Comment by jordanh** [comment]
A note on priority: if/when @ParabolInc/microsoft-codewith decides they'd like to join us in co-developing a Teams integration, we'll want to implement this. Probably best to shape the implementation issue within the next sprint or so

**Comment by Dschoordsch** [comment]
@mattkrick Your version fits the current architecture the best, so here is a refined proposal:
```ts

interface NotificationManagerAuths {
  slack: SlackAuth | null,
  mattermost: MattermostAuth | null
}
type NotificationManagerType = keyof NotificationManagerAuths

class IntegratedServicesNotifier {
  managers: {[key in NotificationManagerType]?: NotificationIntegrationManager} = {}

  constructor(auths: NotificationManagerAuths) {
    // init this.managers based on auths
    if (auths.slack) {
      this.managers.slack = new SlackNotificationIntegrationManager(auths.slack)
    }
...
  }

  // returning void because otherwise errors would need to be picked apart per integration and this manager should deal with retries
  // preferences should be limited to enable/disable an integration for a certain action, we don't want to support sending different events to different channels for example
  startMeeting(meeting: NewMeeting, team: Team, preferences: NotificationManagerType[]): Promise<void>
  endMeeting(meeting, team, preferences): Promise<void>
  startTimeLimit(meeting, team, preferences): Promise<void>
  endTimeLimit(meeting, team, preferences): Promise<void>
}

type NotifyResponse = 'success' | {
  error: Error
  recoverable: boolean
}

export interface NotificationIntegrationManager {
  startMeeting(meeting: NewMeeting, team: Team): Promise<NotifyResponse>
  endMeeting(meeting, team): Promise<NotifyResponse>
  startTimeLimit(meeting, team): Promise<NotifyResponse>
  endTimeLimit(meeting, team): Promise<NotifyResponse>
}

// new dataloaders to load all available notification auths
const auths: NotificationManagerAuths = await dataLoader.get('notificationManagerAuths').load({teamId, userId})
const manager = new IntegratedServicesNotifier(auths)

const preferences = await dataLoader.get('notificationPreferences')
manager.startMeeting(meeting, team, preferences.startMeeting)
```
