### ISSUE TITLE
Unable to toggle users active/inactive on Pro orgs

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5832]
## Issue - Bug

A [customer](https://app.hubspot.com/contacts/3888472/contact/19554351) 🔒  writes: From some time - week, maybe a little longer - when I am trying to deactivate user (the toggle button on their right side - see screenshot) in my organization the deactivation button automatically comes back to active state (and I can see that it is coming back to active state just after I clicked it).

I was able to reproduce this with the Parabol Pro org - Grayson

**Comment by jordanh** [comment]
AC
 - Triage or fix
 
EE
- 1 hour
