### ISSUE TITLE
JIra - getProjectAvatar refactored to cached images in redis

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5833]
Datadog APM tells us that getting project avatars is a [pretty expensive thing to resolve.](https://app.datadoghq.com/apm/resource/gqlexecutor_01/graphql/f5c522ac77a9e943?query=env%3Aproduction%20service%3Agqlexecutor_01%20operation_name%3Agraphql%20resource_name%3A%22query%20JiraScopingSearchFilterMenuRootQuery%22&env=production&event=AgAAAX4mB-LpRtIq0gAAAAAAAAAYAAAAAEFYNG1CLWZrQUFCMHdvZTBJUGQzWWVzSAAAACQAAAAAMDE3ZTI2MDgtODBhOS00OWQ0LThkYjUtMGY2ZjcxNjdkMTgx&index=apm-search&spanID=570770132399154101&timeHint=1641315558121&topGraphs=latency%3Alatency%2Cerrors%3Aversion_count%2Chits%3Aversion_count&traceID=570770132399154101&start=1641313883530&end=1641317483530&paused=false) 

We've already fixed this for jira images in issues. We just cache those images in redis & then send down a URL instead of sending a base64 encoded image. We should do that here, too.

AC
- [ ] AtlassianManager.getProjectAvatar uses the same image strategy as images in JiraIssues

Effort: 8 hours

**Comment by elielytz** [comment]
Hi @mattkrick , can I get steps to reproduce and test this issue?

**Comment by elielytz** [comment]
I have managed to find out the steps and reproduce this.

## Test results
Passed
