### ISSUE TITLE
Polls cannot be submitted

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5839]
## How to reproduce
Start a retro and advance to the discussion phase. Create a poll. Select an answer and try to submit.

## Expected behaviour
Answer is selected and submitted. Then the result is shown.

## Actual behaviour
Answer does not appear selected, but submit button appears.
Submit button appears to do nothing on click

![Peek 2022-01-05 11-14](https://user-images.githubusercontent.com/7331043/148201437-eb462c0c-123d-41f5-8d00-11b11b040eda.gif)

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by BartoszJarocki** [comment]
@Dschoordsch this feature wasn't finished as it wasn't a priority. See the progress here: https://github.com/ParabolInc/parabol/issues/5147

**Comment by Dschoordsch** [comment]
@BartoszJarocki sorry, my fault. Also just found the TODO.
