### ISSUE TITLE
When installing PWA, "refreshing the app" isn't straightforward as it is in the browser

### ISSUE THREAD

**Issue by MidasLamb** [ParabolInc/parabol#5844]
When installing the PWA from the chrome browser, and something has gone wrong, users can get to see the following screen:
![image](https://user-images.githubusercontent.com/14802865/148512205-50aa3093-aaf5-4a3f-a3cb-8883bc043eba.png)
However, in contrast to a browser, there is no button to refresh on screen (f5 works but not everyone knows f5).

Potentially add a refresh button besides the report feedback button, to allow refreshing even when the button is not visible in the web app?

**Comment by mattkrick** [comment]
What a great find! We'll add a link to refresh the page.
Thanks for the bug report!

Acceptance criteria:
- [ ] `Try refreshing the page` is a hyperlink that calls window.reload() or similar

Estimate: 2 hours
