### ISSUE TITLE
Jira - poker meeting does not suggest to fix a field when clicking on a mini estimation card

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#5846]
## Issue - Bug

* Create a poker meeting
* Add some Jira issue
* Select an estimation field that does not exist on this type of the issue
* Vote and reveal votes
* Click on mini estimation card
* See nothing happens
* Try to edit estimation field manually and click update
* See Fix field dialog appeared

https://user-images.githubusercontent.com/466991/148576855-1cf5c3f8-5c7a-432a-865d-adc43529d6ec.mov
 
### Acceptance Criteria (optional)

- [ ] Clicking on mini estimation card in the case above should show an error and fix field dialog

Related issue: #5705

Estimate: 8h

**Comment by elielytz** [comment]
Hi @igorlesnenko i have reproduce this and test it.

## Testing results
### Passed
I have test this and it works as expected.

**Comment by mattkrick** [comment]
related: https://github.com/ParabolInc/parabol/issues/5894
