### ISSUE TITLE
Suggest adding an integration when another team member has added it

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5849]
This issue is a child of #5939.

## Enhancement

When we detect that a team member has added an integration, we can suggest it to other team members who have not added it yet. 

## Example

When a team member has added an integration, we can prompt other team members who have not done so, to connect it as well.

<img width="1287" alt="Captura de Pantalla 2022-01-24 a la(s) 5 50 12 p m" src="https://user-images.githubusercontent.com/3276087/150884629-7180d9ba-0cda-4e7b-a48b-a0becdc71ee4.png">

## Scope

- Because integrations are team level, let's start by only showing this popup on the team page. We can figure out later on how to deal with views that support multi-team content, such as the Tasks view.

## Acceptance criteria

- [ ] When a team member has added an integration, and the user has not added it themselves, and the user has not previously dismissed the popup, we display a popup on the top right corner of the Team page that prompts the user to add said integration.
- [ ] The popup can be easily dismissed (`X` button), and we remember that choice to avoid annoying the user again
- [ ] The popup should include a 'Learn more' link to a support article, for example `https://www.parabol.co/integrations/jira`
- [ ] Clicking 'Connect' starts the connect integration flow in place, meaning that the popup window appears on top and the user stays in the same view.

### Estimated effort:
- 20 hrs

**Comment by enriquesanchez** [comment]
Similarly to #5534, we can display a little popup on the top right corner of the window when the following is true:

- [ ] A team member has added an integration, and
- [ ] the user has not added it themselves, and
- [ ] the users has not previously dismissed the popup.

<img width="1182" alt="Screen Shot 2022-01-10 at 4 49 57 p m" src="https://user-images.githubusercontent.com/3276087/148852167-45c9904f-32d7-4794-8a6f-edd17d01f408.png">

This is the same UI component from #5534, so we can recycle most of it. It should also follow #5534's acceptance criteria:

- [ ] The popup should be easily dismissable (close button)
- [ ] The popup should be smart and only appear if the integration has not be added yet, or if the popups has not been previously dismissed.
- [ ] The popup should include a 'Learn more' link to a support article, for example `https://www.parabol.co/integrations/jira`
- [ ] Clicking 'Connect' should let you connect the integration without leaving the current view. We can show a popup window or modal in place. See #5567 for more detail.

**Comment by ackernaut** [comment]
@enriquesanchez
- This seems safe to try
- I made a comment on #5875 about showing team members usage meta, but this is definitely more direct. I think it would be great to track how many folks upgrade through this dialog. One day it’d be nice to turn things on like this for a subset of our users and see the difference
- If there are any reservations about using a dialog, maybe we could stick it as a banner element near the team name where the settings and integration links lives. In a future version of the team dash I could see us showing more clear meta as to what integrations are active on the team and how to drill down and configure more

**Comment by Dschoordsch** [comment]
@enriquesanchez Where do we remember the choice of the popup? Is it per `User`, `TeamMember` or local per browser? I would put it per `TeamMember` as it seems to be a good middle ground between nudging the user and not being too annoying.

**Comment by enriquesanchez** [comment]
@Dschoordsch Yes, I think `TeamMember` makes total sense 👍
