### ISSUE TITLE
Spotlight bug: another user's spotlight floating card should keep its height

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5856]
Repro:
- There are 5 cards in a column, all with 4+ lines
- User A opens a spotlight on card 3
- User B sees card 4 move up & under where card 3 is, making it hard to read card 4

AC
- [ ] When another user opens spotlight, it floats but maintains it's height within the column

Estimate: 8 hours

**Comment by jordanh** [comment]
adjusting to p3

**Comment by mattkrick** [comment]
still a thing, iceboxing
