### ISSUE TITLE
Highlight hovered cards in check-in meeting updates

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5858]
As a user in check-in meetings I intuitively point on a card and then proceed "This one is in review" without giving any context. If the remote participants could see which card I'm hovering above, it would be easier for them to follow.

![Peek 2022-01-11 22-39](https://user-images.githubusercontent.com/7331043/149026145-70dcefcd-d51d-43b2-ab42-c4ffc98ef129.gif)

### Acceptance Criteria (optional)
In check-in meetings in solo-updates phase
* [ ] check with a designer if this is ok
* [ ] when in right phase an task is hovered, mutation `setTaskHighlight` is triggered with `meetingId`, `taskId` and `isHighlighted`
* [ ] `SetTaskHighlightPayload` is added to `MeetingSubscription`
* [ ] `Task` is extended on client side with `isHighlighted` and `OutcomeCard` highlighted accordingly
* [ ] Only send the highlight when the highlighter is the author
* [ ] Clear all highlights when moving to next stage

**Comment by ackernaut** [comment]
@Dschoordsch do you mind adding an initial estimation? Otherwise waiting for a poker session is fine, thanks

**Comment by jordanh** [comment]
See also: #3430 and #2191

I would _love_ to make this a BP, so I will :)

**Comment by jordanh** [comment]
Removing BP now that I see there is a PR :)

**Comment by Dschoordsch** [comment]
@jordanh I took a look at my PR and I think it should be solved differently. The highlight belongs on the stage, not the task itself, so there is enough meat left to make it a BP. I would like to implement it, but it's not my top priority, so I could ditch it.

**Comment by elielytz** [comment]
@Dschoordsch is this functionality ready to be tested meanwhile?

**Comment by Dschoordsch** [comment]
@elielytz Matt had requested major refactoring, only after that testing makes sense.

**Comment by elielytz** [comment]
okay great
