### ISSUE TITLE
Remove aggregate fields from Jira Issue Field dropdown in Sprint Poker

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5864]
## Issue - Bug
To make setting estimates in sprint poker more reliable we need to remove fields that are set by the system. 
The documentation isn't clear about which fields can be set/updated, which can't, unfortunately. I've spent some time and went through the Jira community posts and [I found all the fields that are aggregates can not be touched via REST API. ](https://community.atlassian.com/t5/Jira-questions/Update-timespent-and-status-in-jira-using-python/qaq-p/800510 )

```
  {
    id: 'aggregatetimespent',
    key: 'aggregatetimespent',
    name: 'Σ Time Spent',
    custom: false,
    orderable: false,
    navigable: true,
    searchable: false,
    clauseNames: [],
    schema: { type: 'number', system: 'aggregatetimespent' }
  },
```

```
  {
    id: 'aggregatetimeoriginalestimate',
    key: 'aggregatetimeoriginalestimate',
    name: 'Σ Original Estimate',
    custom: false,
    orderable: false,
    navigable: true,
    searchable: false,
    clauseNames: [],
    schema: { type: 'number', system: 'aggregatetimeoriginalestimate' }
  },
```

```
  {
    id: 'aggregatetimeestimate',
    key: 'aggregatetimeestimate',
    name: 'Σ Remaining Estimate',
    custom: false,
    orderable: false,
    navigable: true,
    searchable: false,
    clauseNames: [],
    schema: { type: 'number', system: 'aggregatetimeestimate' }
  },
```

```
  {
    id: 'aggregateprogress',
    key: 'aggregateprogress',
    name: 'Σ Progress',
    custom: false,
    orderable: false,
    navigable: true,
    searchable: false,
    clauseNames: [],
    schema: { type: 'progress', system: 'aggregateprogress' }
  },
```

An attempt to update any of the fields listed above will result in an error. It'd be best to avoid this situation, by not showing these fields at all. 

### Acceptance Criteria (optional)
- [ ] Aggregate fields are not showing  in the Jira Issue Field dropdown
![Screenshot 2022-01-12 at 15 45 13](https://user-images.githubusercontent.com/1017620/149164606-07300df3-162f-499c-b49e-83c1636635bf.png)

**Estimated effort:** 8h

**Comment by Dschoordsch** [comment]
Maybe we can assume sane naming conventions and skip all `id: aggregate.*` fields?

**Comment by BartoszJarocki** [comment]
I think it's safe to assume that 👍🏻

**Comment by igorlesnenko** [comment]
Did some changes of how fields fetched here #5825

**Comment by enriquesanchez** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/3) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by elielytz** [comment]
@BartoszJarocki how this can be tested?

**Comment by BartoszJarocki** [comment]
If you open Jira Issue Field dropdown, there should be no items starting with `Σ`
