### ISSUE TITLE
Improve automatically adding missing fields in Jira during Sprint Poker

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5868]
## Issue - Bug
We offer a brute-force mechanism that aims to automatically add the missing field to the Jira issue screen configuration.
As it turns out, some fields like  `timeoriginalestimate ` and `timeestimate ` depend on other fields being added to the screen, in this case, `timetracking`. Similarly [to this situation](https://github.com/ParabolInc/parabol/pull/5865/), we need to add a special treat for that case, and if the user tries to fix the missing Jira field issue using Parabol for fields `timeoriginalestimate` or `timeestimate` we need to add `timetracking` first. 

It's very unfortunate, but even if the field `timeoriginalestimate` is added the issue, but there's no `timetracking` added, updating `timeoriginalestimate` via Jira REST API will fail (even though, the user will be able to update this field manually, directly in Jira). This looks like a Parabol bug, where in reality it's just a Jira API quirk, so let's try to fix that.

### Acceptance Criteria (optional)
- [ ] if user uses 'Fix it for me' mechanism for `timeoriginalestimate`, make sure to add both fields `timetracking` and `timeoriginalestimate`
- [ ] if user uses 'Fix it for me' mechanism for `timeestimate`, make sure to add both fields `timetracking` and `timeestimate`
- [ ] Check if there are other field dependencies, if there are, handle them as well
- [ ] Implemented solution does not time out

**Estimated effort:** 16h

**Comment by Dschoordsch** [comment]
Will be handled when doing #6887
