### ISSUE TITLE
No timer notifications are send via slack and mattermost

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5870]
## How to reproduce
Add mattermost or slack integration to a team.
![Screenshot from 2022-01-13 12-38-28](https://user-images.githubusercontent.com/7331043/149323932-ec1adfaf-595a-4498-a570-bdd2216e1c41.png)
Start a retro meeting and set the timer to a date+time, keep "[x] notify via slack" checked. Wait until the timer runs out.

## Expected
There is a notification for timer start and timer end.

## Actual
No notifications related to the timer

## Acceptance Criteria
* [ ] notifications are sent aligned with the integration settings

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/79268751) 🔒  writes:

> Hey guys. We've set up our first meeting, butt can't get Parabol to post timer updates to the designated channel in Slack.

**Comment by gcrickman** [comment]
This [user](https://app.hubspot.com/contacts/3888472/contact/112525951) 🔒 is experiencing the same problem, no Slack notifications for the timers.

**Comment by igorlesnenko** [comment]
This looks fixed to me, tested for both mastermost and slack. 

End timer notification didn't work for slack on Parabol-stagin app, fixed it.
