### ISSUE TITLE
Meeting summary page is not responsive

### ISSUE THREAD

**Issue by elielytz** [ParabolInc/parabol#5879]
## Summary:

The meeting summary page is not responsive on mobile devices (device screen resolution 760x1600)

<img src="https://user-images.githubusercontent.com/45159239/149885360-dc98e526-3232-475a-8c95-fddd41a13485.jpg" width=35% height=35%>

## **HOW TO REPRODUCE**

- Start a Retro meet
- Go through meeting steps (Icebreaker, Reflect, group, vote & Discuss) 
- Advance to the end of the meeting 
- End the meeting.

### **Environment**

- Infinix Smart4, Android 09, XOS v5.5.2
- Device screen resolution 760x1600

### **Expected behavior**
Load meeting summary page and fit depend on device dimensions.

### **Actual behavior**
The meeting summary page is not responsive

**Comment by ackernaut** [comment]
I don’t think we’ll ever make this version of the summary responsive due to the nature of reusing the email HTML which is not responsive and probably not very feasible. We’ll probably update email and summary design before we get here, so iceboxing for now
