### ISSUE TITLE
Choose an approach to support a change of email domain

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#5885]
## Issue - Enhancement

A user wants to seamlessly change the domain for his team emails

A user writes:

> We are going to change the primary domain in our Google suite and we would like to keep all the user history of all the chats and so on.
> We tested with a couple of accounts and a lot of times there is a new profile created and we want to keep the old profile, so all history is preserved.

If the user just changes his domain and tries to login with google, a new parabol account is created. (See: #4860 where similar problem discussed)

Possible solutions:
- Update email based on existing google id in our database when a user tries to login: (https://github.com/ParabolInc/parabol/issues/4860#issuecomment-832120625)
- Have the ability to add an additional email to a user profile
- Have the ability to just change the email in a user profile

### Acceptance Criteria (optional)
- [ ] Propose, discuss and select the approach. What is the best practice for this? Any security risks?
- [ ] Create additional implementation issues 

**Estimation**: 4h

**Comment by ackernaut** [comment]
@igorlesnenko do you mind adding an initial estimation? Feel free to wait until poker if otherwise

**Comment by jordanh** [comment]
Closing this in favor of #5921
