### ISSUE TITLE
Designed new meeting view for stand-up

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5888]
Supports #5790

Edit: we’re planning to use the existing meeting view in the MVP when removing the feature flag as we may not have the new meeting dialog ready — adding and updating AC!

### Acceptance criteria
- Designed visual concepts to answer the questions:
  - What illustration do we use?
  - What’s the activity called? What is each meeting named?
  - What does the new meeting view look like with or without an editable prompt or editable recurrence?
  - How do you edit the prompt once it’s in? I expect we’ll write a specific design task to fully design the prompt editing views and interactions
  - How do you edit recurrence once it’s in? I expect we’ll write a specific design task to fully design editing recurrence

### Estimated effort
- 3 hours

**Comment by ackernaut** [comment]
### Here’s what I’m proposing for review:
- Here are [the Figma concepts](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1088%3A71115)
- The activity is called Async Standup
- The meeting name is fixed and increments, e.g. Async Standup 1, Async Standup 2, Async Standup 3 for the team that starts them. Later we’ll address the ability to rename them.
- We use the illustration with green background as a placeholder until we have an illustration specifically meant for standups
- The how-to copy is a first draft, safe to try
- Initially the MVP doesn’t support changing the prompt or recurrence. Users can only select a team
- If we get to the point of editing prompts or recurrence and are still using this view instead of the new start meeting dialog, I’m suggesting we use the dialog views being designed for that dialog UX to support the UX for these controls. The purpose of this design issue is not to design those dialog views but to simply show how we may add more controls and dialogs to the existing start meeting view as we enhance the Async Standup UX
- The existing Start Meeting view is mobile, so no concerns there. The dialogs can be full-width, or 2 columns can collapse to one, so no concerns there
### Next steps
- I would like @enriquesanchez (Senior Designer) and 1 developer to review this. We will write the implementation criteria together on an existing issue or a new one if needed
- I’ll add this view to a new prototype representing the initial end-to-end flow of the Async Standup MVP

**Comment by nickoferrall** [comment]
This looks great, @ackernaut! It definitely feels like the smallest first step we can take.

My questions and reactions:

1. What URL should we use for the "Learn more" hyperlink? Until we have a blog ready, perhaps we use https://www.parabol.co/features and add a `TODO` that it needs to be changed?
2. You mentioned that we might not have the new meeting dialog view ready, so we'll start by using the existing one. That makes sense. Do you know whether we'll work on the new meeting dialog alongside standups? I'm slightly concerned about re-doing the work here, but I don't think it matters too much as the main custom logic is the recurrence dialog, which we should be able to copy over to the new view. 
3. Where can we get that placeholder image? Does that already exist in the repo or can we use any image as a placeholder? 
4. The first draft copy says: "Share what you're working on as a team". Perhaps we could change this to "Share what you're working on" as users will be reflecting on what they have individually been working on? Plus it's shorter. 

It's safe to try for me!

**Comment by ackernaut** [comment]
@nickoferrall thanks for the feedback!
1. Yes, I think a todo on the backlog, and commented in the code is fine. We may have a link by the time we want to remove the feature flag
2. I think you’re right. If we reuse the new settings dialogs for prompt and recurrence in the new start dialog view, we haven’t lost much new work. Using the existing design in the meantime is very low effort. It would be cool to start working on this in parallel at some point, see #5589 
3. The image in Figma should be fine. I’d have to see how these are exported for the codebase; I believe the background color is specified with CSS
4. I’ll use your copy suggestion. I wanted to keep it in the imperative. You’re right, individuals are sharing. What I meant when using the team phrase is that everybody on the team should share.
5. Technically I think stand-up is probably more correct. However the name should be normalized in our agile-specific product and we can drop the dash. So my vote is Async Standup or Async Standups therefore `standup` or `standups`

**Comment by enriquesanchez** [comment]
This looks good to me. I understand we might create a new illustration for standups, but this one being used here feels pretty decent to me.

+1 to the copy suggestions from @nickoferrall  👍

>I’d have to see how these are exported for the codebase; I believe the background color is specified with CSS

@ackernaut The illustration needs to be a PNG with transparent background, 1066px x 600 and you can run them through tinypng.com to have them reduced in size.

**Comment by enriquesanchez** [comment]
The new illustration for the stand-up meeting type/activity [can be found here 🔒](https://drive.google.com/file/d/1D_Q8mBxL2nHb27YlEcZXM_pzT_IqWpSH/view?usp=sharing).
