### ISSUE TITLE
Search in integration dropdown does not work for GitHub

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#5889]
## Issue - Bug

* Create a **new** team
* Add GitHub integration
* Try to push any issue to GitHub by opening "push to integration" dropdown
* See no repositories are displayed (make sure you have some on GitHub)
* Refresh the page, see that it still doesn't work

![image](https://user-images.githubusercontent.com/466991/150121965-1700bb37-cac8-4c84-9f3d-5ae4d7d1a9bc.png)

Works for Jira

- **How serious is the bug?** P2

### Acceptance Criteria
- User sees his Github repos in the dropdown

**Estimated effort:** 4h

See also previous PR: #5755

**Comment by jordanh** [comment]
Going to keep this one open

**Comment by nickoferrall** [comment]
I just tried to reproduce this bug, but I was able to see my GitHub repos in the task footer menu after creating a new team. 

@igorlesnenko are you still able to repro this bug? Do you see GitHub repos in the task footer menu normally, but not when you create a new team?

**Comment by JimmyLv** [comment]
I haven't reproduced the bug either, but it's in a new team (newly add the GitHub Integration).

<img width="503" alt="Google Chrome-Team Dashboard  TOFU Squad-000428-20220926" src="https://user-images.githubusercontent.com/4997466/192240542-3805f459-ad40-4c22-9b43-3cbf2041acdc.png">

**Comment by nickoferrall** [comment]
Hey @igorlesnenko, just checking whether this one is safe to close?

**Comment by jordanh** [comment]
I also tried to reproduce this one, and was not able to. I am going to close it for now.

@igorlesnenko please reopen if you see it again!
