### ISSUE TITLE
Release Test v6.44.0

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5900]
- The basic checklist is required
- Adding tests from merged PRs is optional

## The basics
Run through this list at least once at [staging](https://action-staging.parabol.co):
- [ ] Smoke tested the [Demo](https://action-staging.parabol.co/retrospective-demo), unauthenticated
- [ ] Created an account
- [ ] Verified invite via mass link works (Team > Invite Button > Invite Link, visit URL in an incognito window)
- [ ] Verified invite via email works
- [ ] Added Slack, verified meeting notifications (use `#t_product_actiontime`)
- [ ] Added Mattermost, verified meeting notifications (check the test webhook in [Parabol Mattermost](https://mattermost.parabol.co/product/integrations/incoming_webhooks))
- [ ] Added GitHub, verified issue created (use `ParabolInc/publictestrepo`)
- [ ] Added Jira, verified issue created (use `parabol-2`)
- [ ] Smoke tested the Retro meeting with 2 players
- [ ] Smoke tested the Sprint Poker meeting with 2 players
- [ ] Smoke tested the Action meeting with 2 players
- [ ] Smoke tested cards on the dashboard
- [ ] Created a 2nd team
- [ ] Created a 2nd organization
- [ ] Upgraded to Pro (Credit card number: `4242 4242 4242 4242`, expiration date: any month in the future, CVC: `123`)
- [ ] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)

### Added

- Add GitLab (#5829)
- Customise release snackbar #5743
- Add migration to fill missing plaintextContent for tasks #5869
- add undefined to wrappedQuery vars #5898

### Changed

- enforce server side lock (#5840)
- SECURITY: bump react-refresh-webpack-plugin #5896
- Security/bump graphql jit #5897
-

### Fixed

- Fix Original Estimate field can not be updated in Sprint Poker (#5865)
- Fix isSpectating toggle & Reveal Votes count #5782
- No implicit any fixes #5830
- Fix alignment of Add task button in discussions #5876
- Fix all noUncheckedIndexedAccess for parabol-client #5837

**Comment by elielytz** [comment]
## Testing Summary
Most of the test cases passed except the following have **_passed with some errors_** or _**failed**_.

### Demo test
Passed with some errors: Most of the features are working except,
When the End Timer option is clicked in the timer button, **_"You found a bug"_** notification is popped.
After that, you can hardly use the timer feature until you refresh the page or advance to the next step.

<img src="https://user-images.githubusercontent.com/45159239/150486520-3347ec6b-8ce9-49d2-9305-5568c1ccaae0.png" width=65% height=65%>

### Creating Account
Passed with email & google sign_up option except for SSO option.
I need more clarification on how SSO sign-up & sign-in works.

### Email invite
Failed: Am getting _**"server error notification"**_

<img src="https://user-images.githubusercontent.com/45159239/150486841-d7f601c4-dc7d-4ffd-b819-b57d5dffdd76.png" width=65% height=65%>

### Adding Mattamost & Slack, verifying meeting notifications
Only starting and ending meeting notifications appear.
Timer notification still not working 

- [ ] #5870 

### Mobile (In progress)
