### ISSUE TITLE
Sprint Poker meeting corrupted state

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5908]
## Issue - Bug

When I left a Sprint Poker meeting and rejoined, all of my scoped integrated tasks showed the default/error state. Corrupt meeting [is open here](https://action.parabol.co/meet/9SaEuq8iJO)

Loom recording is here: https://www.loom.com/share/3c57b3e67eb640fc81da73171a2effc1

- **How serious is the bug?** P1
- **OS:** macOS
- **Browser:** Chrome

### Acceptance Criteria (optional)
   - Triage and fix or,
   - Triage and open issue to fix in a subsequent sprint

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tianrunhe** [comment]
#5722 might be the the same issue as this one

**Comment by tianrunhe** [comment]
It’s Matt’s `nest-graphql-endpoint` to be blamed 😅. [Fix](https://github.com/ParabolInc/nest-graphql-endpoint/commit/62dc182a4357bf31b45b617524e280cd4a54e826) is pretty simple.
