### ISSUE TITLE
Staging: Email Invite: server error warning

### ISSUE THREAD

**Issue by elielytz** [ParabolInc/parabol#5912]
## Environment
Staging

## Issue - Bug

I am getting a server error warning on sending mass email invitations.

### How to reproduce

- Click the invite team button in team's dashboard at the top right corner
- Paste/write emails you want to invite separated by a comma
- Click Send invitation button.

<img src="https://user-images.githubusercontent.com/45159239/150486841-d7f601c4-dc7d-4ffd-b819-b57d5dffdd76.png" width=65% height=65%>

### Acceptance Criteria (optional)
Users can:
   - [ ] Send invitation links directly to recipients emails.

**Comment by Dschoordsch** [comment]
@elielytz did you use different email addresses for the account and the invite? Tip: gmail allows to add suffixes with + to your email address and it still reaches you. So 'example@gmail.com' and 'example+release-test@gmail.com' go to the same inbox.

**Comment by elielytz** [comment]
Yes @Dschoordsch. I used different email addresses for the account and the invite, in the previous release test v6.43 it worked like a charm. Also, I have tested out to add suffixes but am still getting the same error output. How is the output from your side?

**Comment by Dschoordsch** [comment]
@elielytz thanks for clarifying. I hadn't tested it before. I get the same error.

**Comment by nickoferrall** [comment]
Fixed by https://github.com/ParabolInc/parabol/pull/5913
