### ISSUE TITLE
Burndown - Async Standup v1

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5914]
The goal of this issue is to group all the issues related to the first iteration of a standup feature. 
Milestone: https://github.com/ParabolInc/parabol/milestone/122 

## Resources
1. loom video about what we're trying to achieve https://www.loom.com/share/6e6ebcfb35604d74a7b8b9c0b7f1ccc1
2. plan outline https://www.notion.so/parabol/Stand-up-MVP-27ebad512e754eb0ae740cdb7326a080
3. design: https://www.figma.com/proto/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?page-id=653%3A23925

---

### Design
- [x] #5964 
- [x] #5966
- [x] #5925 
- [x] #5926
- [x] #6069 
- [x] #5965
- [x] #6076  

#### Starting a standup meeting
- [x] #5916
- [x] #5917
- [x] #5918 

#### Joining a standup meeting
- [x] #5930
- [x] #5931
- [x] #5932
- [x] #5933

##### User is able to write prompt response in an editor (but not in a standup meeting yet) and the response is stored in DB
- [x] #6203
- [x] #5948
- [x] #5950
##### User is able to see the top bar when entering standup and they can go back to meeting page
- [x] #6196
- [x] #6197
- [x] #6198
- [x] #6199
- [x] #6200
##### User is able to see the response grids and interact with them (probably need more breakdown later)
- [x] #6201 
- [x] #6202
- [x] #5796
- [x] #6261 
- [x] #6372
- [x] #6393
- [x] #6395
- [x] #6422

#### Ending a standup meeting
- [x] #5936
- [x] #5937

**Comment by jordanh** [comment]
Marking as discussion to remove from my grooming queries

**Comment by BartoszJarocki** [comment]
it's done!
