### ISSUE TITLE
Add a new meeting type to a start new meeting screen

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5918]
Update the existing `start meeting` screen with a new meeting type.
![Screenshot 2022-01-21 at 16 29 09](https://user-images.githubusercontent.com/1017620/150553981-234b18d3-9dfc-4276-af0c-c2204764127a.png)

AC:
- [ ] new meeting type is not visible if a `standups` feature flag is disabled for a user
- [ ] new meeting type is visible otherwise
- [ ] the only option visible is  `select team`

Design task: https://github.com/ParabolInc/parabol/issues/5888

**Comment by ackernaut** [comment]
[Here are the design details](https://github.com/ParabolInc/parabol/issues/5888#issuecomment-1022407717). I’ve asked @enriquesanchez (Senior Designer) and @nickoferrall (Senior Developer) to review if this gets us what we need to implement in this issue.

**Comment by BartoszJarocki** [comment]
**Include in next sprint?: N**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/32) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by BartoszJarocki** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/17) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by enriquesanchez** [comment]
The new illustration for the stand-up meeting type/activity [can be found here 🔒](https://drive.google.com/file/d/1D_Q8mBxL2nHb27YlEcZXM_pzT_IqWpSH/view?usp=sharing).
