### ISSUE TITLE
Support email domain & oauth2 changes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5921]
User story 1
> An organization changes their domain, e.g. `parabol.co` to `parabol.com` or `parabol-team.co`. All users with the old domain should have their email updated to the new domain.

User story 2
> An organization drops google as an email provider. OAuth2 logins no longer work. They should be able to login using an email + password.

After seeing both of these issues, even though they're related to logging in, I don't think there's 1 solution that would fix them both.

Proposed solution for 1
> private mutation accessible by the sales team:

```gql
mutation {
  changeEmailDomain(oldDomain: "parabol.co", newDomain: "parabol-team.co") {
    users {
      email
    }
  }
}
```

Proposed solution for 2
> Remove Google AuthIdentity from User object
> Add a local AuthIdentity if one doesn't exist with a bogus hashed password
> instruct each user to click "forgot password", which will send them into the reset password flow. We could send this automatically from the mutation for each identity removed.

this would be another private mutation like
```gql
mutation {
  removeAuthIdentity(domain: "parabol.co", identityType: "GOOGLE", addLocal: true) {
    users {
      email
    }
  }
}
```

@gcrickman Would these solutions work?

**Comment by gcrickman** [comment]
Ya, I think that would work!

**Comment by gcrickman** [comment]
This [customer](https://app.hubspot.com/contacts/3888472/company/5353593883) 🔒  also reported a domain change with their Google Suite

**Comment by Dschoordsch** [comment]
@mattkrick @gcrickman 
How often does user story 2 occur? Would it make sense to offer them the possibility to do it themselves? Something like:
* When a user enters a Google AuthIdentity email in forgot password show a popup "You're signed up with google, do you want to switch to username + password?"
* Only when they follow the reset link in their email and they set the new password, we convert it to local account.

Alternatively we could also just modify the email in this case to mention that this would convert their Google ID account to email + password.

**Comment by jordanh** [comment]
Prioritized to backlog. Will increase priority as we hear this more often

**Comment by jordanh** [comment]
@mattkrick could you give me a rough burn down / EE for this? I'd like to weigh this against some other things when we get to focusing on admin feature

**Comment by ackernaut** [comment]
Mentioned today in [a user feedback retro](https://action.parabol.co/meet/aG72wCHz5S/discuss/1)

**Comment by mattkrick** [comment]
> When a user enters a Google AuthIdentity email in forgot password show a popup "You're signed up with google, do you want to switch to username + password?"

this has only happened 1 or 2 times IIRC.
that definitely works! I think building something on the frontend + a backend flow for the emailing might be longer than a quick mutation, but i don't see harm in either implementation


EE is 8 hours, work to complete is the 2 proposed solutions above (or any other solution that can be done in a day)

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/44653151) 🔒  writes:

> My company was recently acquired, and we will be losing access to our Google accounts soon. Our email accounts will still work. I would like to decouple my Parabol account from my Google account, which I previously used to sign in, and I would like to sign in with a password going forward. Can you help me unlink the account from Google?

**Comment by avivapinchas** [comment]
**Value: 3**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/11) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: M**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/12) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by nickoferrall** [comment]
Tables with an email address or domain that need to be updated in RethinkDB:

- Organization
- User
- TeamMember
- SAML
- Invoice, update the billingLeaderEmails field

In Postgres:

- OrganizationApprovedDomain
- User

Tables that contain an email address or domain that I don't think we should update:

- PasswordResetRequest. It's more secure to make the user request their password reset again. 
- EmailVerification. It's more secure to make the user sign-up with the new email and get the email verification email again.
- FailedAuthRequest. This tracks failed login attempts, so the data should contain the email address that failed. 
- SecureDomain. [This comment](https://github.com/ParabolInc/parabol/pull/6487#discussion_r866235207) suggests the table can now be removed. 

Current plan cc @mattkrick:

- Create a changeEmailDomain private mutation
- Update the email address and/or domain in the relevant tables
- Test that this works by logging in with `nick@test.co`, change the domain to `test.com`, and see that my email address in my profile has been updated to `nick@test.com`. If I log out, I should not be able to sign in with `nick@test.co`, but I should be able to sign in with `nick@test.com`
- For gmail users, it's possible that their company has changed their domain in Google or they've added a new domain to their Google account and given users a fresh email address. The fresh email address will have a different Google id to the id we store in the User table. That should be OK - as long as the email address changes in the User table, they can log in with their new gmail account and still see all of their data.
- Should we store the old domain & old email anywhere? Probably not. This might help us debug an issue if a mistake was made, but it would require additional db storage. If a mistake were made, we could just look at the `updatedAt` timestamp to see which domains & emails were changed. 
- Create a separate issue for user story 2 to keep this as small as possible

**Comment by mattkrick** [comment]
- User table in RethinkDB is deprecated & can be removed

other than that it looks great!
