### ISSUE TITLE
Designed meeting card for async stand-ups

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5925]
Supports #5791

### Acceptance criteria
Designed a concept that answers the questions:
- What illustration?
- What’s it called? What meta do we include?
- Does it show avatars when folks are viewing?
- What menu items are there? To invite to the meeting? To close the meeting?
### Estimated effort
- 3 hours

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/11) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
For the initial version of the meeting card for Async Standups:
- [See Figma](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1140%3A72999)
- Let’s use the same placeholder illustration and background color from #5888 
- The meeting name is on the card (Async Standup ##) which is autogenerated for the team
- The meta is just the team name for now
- The control to invite is on the card, no change
- If folks are actively viewing the meeting we can use the same avatar group pattern from the existing meeting cards. We can defer implementing this for the MVP if it takes too much time.

What’s not addressed in this design:

- Maybe in the future we show some participation stats here; if I see that there are new responses and conversations maybe I’ll jump back in
- For now I want to push all the options to edit and update this type of activity in to the activity view itself. The reason why is that I want folks to see what’s going on in the activity first before changing settings. From the card they might miss the context or update the wrong meeting because they didn’t see the team name etc. However, maybe in the future there are more options than copying the invite link on the meeting card.

**Comment by ackernaut** [comment]
My preference is that we drop the pound sign and stick with the number, so ‘Async Standup 123’ — I suppose we would go back and change that for other meetings. For now if the other meetings use the pound # then we should follow suit to keep this to the minimal MVP effort.
