### ISSUE TITLE
Designed top bar and overall layout for standup MVP

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5926]
This design issue clarifies what’s in the top bar and overall meeting layout for the MVP. This should serve our needs until we add recurrence. Later we can decide on how to edit settings in this view, or how a day navigator might work.

### Acceptance criteria
Iterated on design concepts to answer the following questions:
- Can I end the activity from this main activity view? (yes, in a simple settings menu)
- Do we use the existing meeting member avatars and invite control? (yes)
- Do we defer on the day navigator? (yes)
- Can we edit the meeting name? (no)
- Where do we put the team name and link? (under the meeting name)
- What does this look like on mobile? (TBD)
- Is there an explicit facilitator for these meetings?

### Estimated effort
- 3 hours

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/13) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
I’m proposing this (WIP) for the layout and first swath of functionality:
- The meeting name is autogenerated and not editable yet
  - ‘Async Standup 1’ (the count goes up)
  - It’s in the upper left at any breakpoint
- There’s a back arrow that takes the user to the Meetings view AMA
- At the larger breakpoint (actual breakpoint TBD but probably ~tablet/laptop and up) there’s a blue link with the team name
- There’s a static prompt in the center at the top of the main view. It’s not editable yet
- We can defer adding the avatar group and invite control, but when we do we reuse the styles we have today. In the future I want to push for design changes in this user hub area.
- For now the way to end the meeting is using the bottom bar control. This only shows for the facilitator.
- For these meetings I propose we maintain an explicit facilitator. For this first version (Beta!!) we will not show who it is or how to change it. We will address this in future design and build.

**Comment by enriquesanchez** [comment]
@ackernaut This looks good 🙌

> There’s a back arrow that takes the user to the Meetings view

Do we use this pattern elsewhere? On the other meeting types, the only way to go back to the meetings view is by clicking on the Parabol logo at the bottom of the meeting sidebar. I prefer the back arrow as it is more obvious, but a part of me misses the presence of our logo. 

> At the far upper left there is a simple options menu

Should this say "upper right" instead?

> For these meetings I propose we maintain an explicit facilitator

I had not thought about this. Does a async stand-up need a facilitator? I assumed it to be an "unguided" activity.

**Comment by tianrunhe** [comment]
Looking good! I like the simplicity but also the familiarity. A couple of questions:

*   Who do we show in the avatar group? Team members who has joined this activity? Or team members who are also viewing this page at the same time as the viewer?
*   Is the flag icon for "End this activity" intended in the design? If so, the flag seems weird to me.
*   Is the design for the prompt finalized? I think it could be a little more visible than the meeting name? Bold & large font size? Not sure though. Not a big deal atm.

**Comment by ackernaut** [comment]
Thanks for taking a look, and the questions and comments:
- Re: back arrow, I’m really keen on having this activity feel lightweight. I jump in and participate, and then I back out to the ‘meetings’ view where maybe I’ll see something else at a state where I can jump in there too. I like the ‘meetings’ view to be a place where I clearly see how I can participate in any open activity. We can do a better job at showing state and prompting folks to their next action for that activity
- Re: a facilitator, I think we take a bottom-up approach to facilitation. We enable any team member to kick off a process. I like how our developers today have kicked off their own Sprint Poker meeting. However I think it’s good to be explicit who has started a thing and who to talk to about the activity. E.g. I think we should keep focus days on Wednesday and remove Wednesday from our stand-ups. I can do that but who started this thing? I think anybody can take over facilitation and then edit activities, but they may want to ask first. The intent is more to show activity (who started or is running it), not domain (who owns it).
- Re: flag for ending, we use it on the bottom bar so I thought we could keep using it. I like the weird symbol, because we’re never really ‘there’ as a team, we just made it to the next hill and put a flag down
- Re: avatar group, for starters I think it shows who is viewing. In the future maybe we show who has viewed with transparency to show participation (kinda like Notion)
- Re: prompt design. In the future I think folks will edit their prompts. They could be longer or shower, maybe having formatting, maybe attach to an external integration (e.g. a governance prompt that links to a Notion page or GitHub MD). As is we can tweak the typography. I don’t want to go too big to safe room for the grid.
