### ISSUE TITLE
Designed timeline summary card for async stand-ups

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5927]
When the async standup ends, what do we show on the timeline? This issue should address only the needful for the MVP.

### Acceptance criteria
Designed a concept of a summary card on the timeline that addresses these questions:
- This shows once the meeting is closed?
- Does this link to the closed activity?
- What other meta might we show?
- What might we show in the future? (This can be a high-level, stretch goal)
- What might be the difference between a one-time activity and a recurring activity? (This can be a high-level, stretch goal)

### Estimated effort
- 3 hours

**Comment by ackernaut** [comment]
Here’s what I propose:
- [See the Figma concept](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1193%3A74353)
- We use the `group_work` icon. If we have a better idea this is easy enough to change later
- We largely follow the formatting of other summary cards for now
- We emphasize responses on the first line, and thread activity on the second line
- The link takes the user to the activity view. That is the way to follow up with the threads e.g. you had a question or reaction to what I shared etc.
- Important: I propose that all responses and threads remain alive and editable after the activity has ended. This probably has an impact implementation and there’s not consensus on this UX. I think it’s safe to try at any rate.

In the future, not part of this design:
- I think we will use in-app and chat notifications to ping folks when there are new responses and comments, bringing them back to the meeting
- In the future I think the summary card may be a little richer, maybe showing some avatars, maybe showing if there are conversations that are still going, etc.

**Comment by ackernaut** [comment]
Marking this as done, to be implemented in #5800 (AC and EE to be determined) unless there’s a better issue cc @BartoszJarocki

**Comment by jmtaber129** [comment]
> I propose that all responses and threads remain alive and editable after the activity has ended.

@ackernaut should the summary card be updated when responses and comments are added after the meeting ends?  E.g. if 2 responses and 6 comments were added before the meeting is ended, and then a straggler adds their response and 2 comments later, should the summary card show 2 responses + 6 comments or 3 responses + 8 comments?

**Comment by ackernaut** [comment]
@jmtaber129 I think a snapshot of static meta when the meeting ends is a fine place to start. Later we may find some use case for having dynamic meta. We can revisit it when we think about recurring meetings.

**Comment by Dschoordsch** [comment]
> @jmtaber129 I think a snapshot of static meta when the meeting ends is a fine place to start. Later we may find some use case for having dynamic meta. We can revisit it when we think about recurring meetings.

@ackernaut I wonder what was the reason behind this? Was it for the user experience as it would be confusing if it changes or did you think it is easier to implement?

**Comment by ackernaut** [comment]
It’s been a minute. I think I assumed it was easier to implement. I think dynamic meta is probably best in general.
