### ISSUE TITLE
Implement a start standup mutation

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5930]
In similar fashion to `startCheckIn` or `startSprintPoker` mutations, we need `startStandup` mutation.

AC:
- [ ] evaluate if we can have a single, generic `startTeamPrompt` mutation or do we need `startStandup`, discuss with the maintainer
- [ ] implement the solution

**Comment by Dschoordsch** [comment]
I assume the DB schema is out of scope because it will be done already when we're starting this issue?

**Comment by BartoszJarocki** [comment]
correct. the first story to handle is: https://github.com/ParabolInc/parabol/issues/5915
