### ISSUE TITLE
Add a meeting card menu item to handle the new end standup mutation

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5937]
Until we have more advanced control over team prompts meetings, we need a manual way of ending the meeting.

AC:
- [ ] Add a new meeting menu item `End meeting` to the `MeetingCard` component
- [ ] When clicked, handle the new mutation added in #5936 
- [ ] Meeting card disappears when mutation completes

**Comment by Dschoordsch** [comment]
Would this finish a meeting and send out a summary or abort the meeting?

**Comment by BartoszJarocki** [comment]
this particular issue is frontend-only and it's about sending/handling the mutation and making sure there's no meeting card after that. 

this is a good question regarding #5936 and for the start, I think it'd be sufficient just to set `endedAt`. everything else will depend on how the data structure looks like and if there's anything else to finalize. summary cards have [their own tasks](https://github.com/ParabolInc/parabol/issues/5800) (which probably will need to be revised) and they're out of scope of initial MVP.
