### ISSUE TITLE
Integrations awareness

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5939]
This is a parent issue that lays out a plan for approaching all the various design and implementation work around integrations awareness. 

## Context

It stems from #5843, in which we explored different ideas to improve our users' awareness of the integrations that we support, and how these relate to their teams.

### 1.

We'll start by improving the clarity of the integrations settings page:

- [x]  #5875

### 2.

With that out of the way, we can continue to improve the user experience by suggesting adding an integration when a related link is pasted. To keep the scope manageable, I suggest we start with GitHub only:

- [ ] #5940
- [x] #5941

### 3.

As more and more users start to become more aware of integrations, and as a result they start adding integrations, we can spread the awareness to team members as well:

- [x] #5849

### 4. 

At this point we can look at ways to extend the functionality of integrations, and while not exclusive to integrations, attachments are a great way to improve our tasks feature. It so happens that integrations are the ideal candidate to start with attachments. 

Starting with integrations should keep the scope focused, and lay the groundwork for a more robust attachments feature later on.

- [ ] #5942

### 5.

Another area where we can increase awareness of integrations in Parabol is during user onboarding. User onboarding is a whole topic on its own, and there's more than plenty we could do here. But one quick win we have available right now is to add a task card next to the initial task every user gets when opening Parabol for the first time:

- [x]  #5943

**Comment by mattkrick** [comment]
idea that we had floating around for awhile:
- the "push to integration" icon in the Task Card Footer could be foreign to many folks. We could try replacing that icon with the jira icon since that seems more familiar. Since they recognize the jira icon, they might be more inclined to click it. If they integrate with e.g. GitHub, then we change the icon to the Octocat.

**Comment by ackernaut** [comment]
@enriquesanchez I really like how you worked up a list of enhancements here. Especially, where you’ve identified low effort that could have good impact. I think integration awareness follows the pattern ‘find what you love or love what you find’ — some folks are looking for integration settings and would benefit from e.g. #5875 whereas some folks would discover the ability and have a good chance at liking what they find e.g. #5940 . Nice work capturing both kinds of opportunities. 🙌 

💭  I’ve said this elsewhere but I think there are a few key moments where discovering integrations is the most helpful to the UX. One is scoping for Sprint Poker, it helps to have some issues. The other is the takeaways tasks in the discussion thread. The context is primed via the discussion, and there’s a real need to consistently kick out tasks to an integrated destination. These may be 2 other places to focus.

⭐  Another place that is lower effort but may have impact is the Start Meeting view. Currently in that view, we don’t hint at integrations very well. This is the how-to copy: ‘Select stories from your backlog’ or ‘Export final score to your tracker’ or ‘Create takeaway tasks to make improvements’. I think in the existing view it would be low effort to sprinkle in some icons and some more direct language like ‘Sync and estimate tasks from Jira, GitHub, etc.’. I also suspect this would be a good improvement to the new Start Meeting dialog designs.

**Comment by nickoferrall** [comment]
This looks great! Hopefully, we'll see a nice bump in user integrations once these are implemented.

Two additional ideas:

1. `Settings & Integrations` hyperlink takes the user to the Team page and they need to do an additional click to get to the Integrations page. Instead, we could call it `Integrations & Settings` and initially show the `Integrations` page, saving the user a click.
2. As we want to promote integrations as much as possible, perhaps they deserve some real estate in the left sidebar, under Tasks, for example? The `Settings & Integrations` hyperlink feels a bit hidden away.

**Comment by jordanh** [comment]
@enriquesanchez love this plan! I agree with starting with the item at the top of your list. I will look at its priority now.

For https://github.com/ParabolInc/parabol/issues/5875, what could we measure here to know if this design update had any effect?

Similarly, for https://github.com/ParabolInc/parabol/issues/5940 what segment events should we emit so we can make some hypotheses and measure?

**Comment by enriquesanchez** [comment]
Thanks @jordanh 🙌

>For https://github.com/ParabolInc/parabol/issues/5875, what could we measure here to know if this design update had any effect?

In general the goal of #5875 is to reduce confusion about how integrations work with regards to member and team. The most obvious change I would expect is reduced support inquires. Users still have to find their way to the Integration settings page, so I'm not sure if we'll see any meaningful movement in our metrics. 

> Similarly, for https://github.com/ParabolInc/parabol/issues/5940 what segment events should we emit so we can make some hypotheses and measure?

I feel this one is easier to measure. My hypothesis being that we'll see an increase in integrations set up by users.

**Comment by enriquesanchez** [comment]
Thank you @nickoferrall 🎉

> Instead, we could call it Integrations & Settings and initially show the Integrations page, saving the user a click.

> As we want to promote integrations as much as possible, perhaps they deserve some real estate in the left sidebar, under Tasks, for example? The Settings & Integrations hyperlink feels a bit hidden away.

These are great ideas. Another thought I had was to add `Integrations` to the user menu in the top bar in the dashboard. Something like:

- `Profile`
- `Integrations`
- `Organization`
- `Sign out`
