### ISSUE TITLE
Attach integration links to task cards

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5942]
This is a child issue of #5939. It requires completion of #5941.

## Enhancement

When pasting a link of an integration that we support, we ask the user if they want to paste as an inline embed or as an attachment.

## Example

<img width="332" alt="Captura de Pantalla 2022-01-24 a la(s) 6 21 25 p m" src="https://user-images.githubusercontent.com/3276087/150887176-199914ac-f09a-4e96-8520-cca26f352e45.png">

- If I press `esc`, the popup goes away and we default to inline embed
- If I select `Paste as inline embed` the popup goes away and we convert the link to an inline embed
- If I select `Paste as attachment` the link goes away and the attachment is added to the bottom of the task card. I can continue adding text to the card.

<img width="332" alt="Captura de Pantalla 2022-01-24 a la(s) 6 26 15 p m" src="https://user-images.githubusercontent.com/3276087/150887678-4fed576e-2d44-4004-99d7-b707361fcf58.png">

Attachments by nature show richer content than inline embeds. In the case of a GitHub link, we can display more details about the issue or PR. Shown in the example above are:

- title (truncated if long)
- assignee if available, and logo 
- status icon
- issue/pr number
- date of creation

Attachments behave like links, meaning that they can receive focus and hover states. They can also be easily removed via a `X` button that appears when focused or hovered:

<img width="332" alt="Captura de Pantalla 2022-01-24 a la(s) 6 34 59 p m" src="https://user-images.githubusercontent.com/3276087/150888460-2d14dd82-0ee7-4dc8-ad81-7c8de5f7388e.png">

A task card can also contain multiple attachments, and when dealing with more than a couple, we can hide and expand them via a toggle link:

<img width="664" alt="Captura de Pantalla 2022-01-24 a la(s) 6 40 07 p m" src="https://user-images.githubusercontent.com/3276087/150888952-3647f606-50d8-4753-a6a0-d5a6d319f1fb.png">

## Scope

- Let's start with integrations only, and specifically with GitHub. We can extend to other types of attachments in the near future once the feature is out in the wild. To give you a taste of what kinds of attachments we could support in the near future, here are some ideas:

<img width="1093" alt="Captura de Pantalla 2022-01-24 a la(s) 6 42 49 p m" src="https://user-images.githubusercontent.com/3276087/150889192-d8b10a61-b06f-42f8-bbc1-4a5b929646da.png">

## Acceptance criteria

- [ ] When pasting a link of an integration that we support, we show a popup asking the user if they want to paste as an inline embed or as an attachment
- [ ] If the user presses `esc`, the popup goes away and we default to inline embed
- [ ] If the user selects `Paste as inline embed` the popup goes away and we convert the link to an inline embed
- [ ] If the user selects `Paste as attachment` the link goes away and the attachment is added to the bottom of the task card
- [ ] For integration attachments, the attachment shows
  - [ ] title
  - [ ] assignee if available
  - [ ] logo 
  - [ ] status icon
  - [ ] issue/pr number
  - [ ] date of creation
- [ ] Attachments behave like links, meaning that they can receive focus and hover states
- [ ] Attachments can be easily removed via a `X` button that appears when focused or hovered
- [ ] A task card can contain multiple attachments
- [ ] Users can toggle to view all or less attachment via a link

### Estimated effort:
- 48 hrs

**Comment by ackernaut** [comment]
@enriquesanchez 
- Wow, this is 🔥 
- What happens if I add a link to text using command K? Nothing? Do we ask if they also want to attach? Is that too intrusive?
- I made a comment on #5941 about dragging and dropping synced work items from the Inspiration panel onto a reflection, or prompt response, or a task card, etc. The attachment version of this is what I initially had in mind would show on the card.
- I really like how you dug into the details on showing meta, hover state, different apps & sources — solid!

**Comment by enriquesanchez** [comment]
Thank you @ackernaut 🙏

> What happens if I add a link to text using command K? Nothing? Do we ask if they also want to attach? Is that too intrusive?

I think it feels intrusive, the user intention is a bit different in this scenario. They are creating a hyperlink. (See also https://github.com/ParabolInc/parabol/issues/5940#issuecomment-1022697993).

**Comment by jordanh** [comment]
I ❤️  this. I am going to add this to our product roadmap and prioritize this for further architecture and implementation. I think it'll be useful throughout the product, in all our experiences

**Comment by jordanh** [comment]
Related: Task details – Integrations #5371 

My intuition tells me that we'd tackle this issue (#5942) before #5371, and implement the latter when we feel the need to mention our own Tasks in our Task cards. Our tasks would need a unique identifier and a URL to make this happen. Waiting for a user to express this tension via implementing #5942 first feels like the right order of operations...

Does that jive with you @enriquesanchez and @ackernaut?

**Comment by enriquesanchez** [comment]
@jordanh Yeah, working on this one first sounds right to me 👍

**Comment by jordanh** [comment]
I still like this one. I have no idea how often users do this behavior, but I love it.
