### ISSUE TITLE
Implement mutation to handle adding responses

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5948]
- [ ] When user starts a team prompt meeting, empty responses were created
- [ ] A mutation exists to update the content of a response. It takes prompt id and stringnified content as arguments

**Comment by tianrunhe** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/19) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by tianrunhe** [comment]
**Include?: Y**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/20) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
