### ISSUE TITLE
Sprint poker GitHub integration got corrupted

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5954]
## How to reproduce
Start sprint poker, add GitHub issues, advance through the meeting and vote on some tasks

## Expected
The summary shows the correct titles and all tasks are archived

## Actual
One task was not archived, the others show placeholder text

![Screenshot from 2022-01-25 20-33-44](https://user-images.githubusercontent.com/7331043/151047283-c88e5058-93a8-46a4-bf6e-00358a6068f7.png)
When following the link for the broken issue it shows
![Screenshot from 2022-01-25 20-37-19](https://user-images.githubusercontent.com/7331043/151047281-b704cc12-f01d-4033-bd21-5f8f206c9578.png)

Link to the summary: https://action.parabol.co/new-summary/aqXH2xvWx2

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tianrunhe** [comment]
Same issue as #5908. Closing.
