### ISSUE TITLE
Sprint poker issue results, no indication there’s more to load

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5955]
- When searching for issues in the Scope phase of Sprint Poker, we only load the first 25 when there may be more.
- The select all control says ‘Select all 25’. There’s no indication that there are more that can be loaded.
- Users have to scroll to load more, maybe multiple times. Then the select all control updates e.g. ‘Select all 45’
- When loading more than 50, it says ‘Select the next 50’ because we only allow users to select up to 50

![Screen Shot 2022-01-25 at 13 44 30](https://user-images.githubusercontent.com/307286/151048363-ebaf69ad-e9d5-45e9-9178-6af6070ca89b.png)
![Screen Shot 2022-01-25 at 13 44 35](https://user-images.githubusercontent.com/307286/151048367-91a9932b-c503-4b7c-a6f0-7369745d0dbc.png)
![Screen Shot 2022-01-25 at 13 44 40](https://user-images.githubusercontent.com/307286/151048370-5b6b408c-1775-490c-aab9-c03a70218c0a.png)

### Questions for developers:
- Can we know there are more issues than what initially loaded?

### Acceptance criteria
Designed a concept that answers these questions:
- How can we show there are more issues than what loaded?
- Should we nudge folks to scroll? How?
- Do we display only meta that is non-interactive (e.g. loaded 25 of 100), or is there an action you can take besides scrolling to load more? E.g. tap the meta to load more, or an explicit button or link to load more

### Estimated effort
- 5 hours

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/21) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
Here are a few ideas:
- [We could have results meta at the top](https://www.figma.com/file/C1bw7pYGiF2qzUb1QpXZA0/Poker-scoping%2C-loading-more-issues?node-id=2%3A318) that say how many have loaded, how many results match the query in total, and hint at scrolling to load more
- [We could put an explicit scroll hint at the bottom](https://www.figma.com/file/C1bw7pYGiF2qzUb1QpXZA0/Poker-scoping%2C-loading-more-issues?node-id=2%3A333) when there are more that can be loaded
- We change the word ‘all’ to ‘next’ as ‘all’ might be misleading. We already do this when we get to 50 ‘Select next 50’ — So we’d go from ‘Select all 25’ to ‘Select next 25’ — Maybe we use ‘all’ when all are loaded and the total results is 50 or less.

For feedback purposes:
- What is possible to know in the initial query? Can we know the total that match the query? Can we know if there are more to load?
- Any question or reactions about these proposed solutions? Anything not safe to try?

**Comment by enriquesanchez** [comment]
These are great improvements, the meta at the top and the scroll hint at the bottom can work very well together. 🙌

I feel that saying "select the next 25 issues" is still a little confusing: the next in relation to what? does this mean there are previous issues?

I think that, if we are looking at the first 25 issues in the list, then say "Select the first 25 issues". We can then change the action to "The next..." knowing that the first batch has already been selected. Does that make sense?

**Comment by ackernaut** [comment]
Yeah, that makes sense. Initially I thought we should say ‘Select the top 25 issues’ and if more load ‘Select the top 50 issues’ etc.

**Comment by ackernaut** [comment]
@tianrunhe do you have questions or thoughts here? Does this seem feasible with how it works today, or are there any upcoming changes to how we are loading. I would like to validate this design and then for us to create an implementation issue on the backlog.

**Comment by tianrunhe** [comment]
@ackernaut Questions:

1.  What does the 'Select next X issues' actually do? Say I load first batch of 25 but do not pick any of them. I see the bottom prompt so I scroll, now 25 more loaded and the text changes to "Select next 25 issues'? So clicking that checkbox will select issue 26-50?
2.  If there are in total 40 issues. First load, boom, 25 show up. I scroll to the bottom, 15 more are loaded. Does the text change to "Select next 15" or "Select all 40"?
3.  Would the designed behavior change in any way when a few tasks are selected in the first load?

**Comment by ackernaut** [comment]
@tianrunhe good questions. I’d say give it a try on a test team. In the original comment above I posted the screenshots. If you do not select the number goes up to 50. (Each screenshot above is an updated state of the previous screenshot.) But you raise a good point. I’m gonna take a look at what happens if you select partial. I think basically the same states will be true, we just need to tweak the existing labels. And consider the new hint text and load more

**Comment by tianrunhe** [comment]
@ackernaut oh I was as posing the question to check if the behavior today would change with the new labels.

**Comment by ackernaut** [comment]
I’ll take a closer look at the behaviors and share any new thoughts

**Comment by jordanh** [comment]
@ackernaut if we had final designs for this, it might make a nice front-end BP

**Comment by jordanh** [comment]
Iceboxing
