### ISSUE TITLE
Designed response card for async stand-ups

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5964]
Supports #5949

### Acceptance Criteria
Designed a concept that answers the questions:

- Plain text? Supports formatting like a task card (i.e. bold, italic, command K links, etc.)? No integrated links for now?
- Will response cards support emoji? How many emoji? How do they wrap?
- How many reply avatars can we show? Will we truncate avatars when they don't fit?
- Only author can edit their card? How to edit versus open the thread?
- What does this look like on mobile?

**Estimated effort:**
4 hrs.

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/15) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
@enriquesanchez such nice work! Thanks for taking the time to list and demo the various states.
- How soon should we build rich editing on cards opposed to plain text? I wonder if the developers want to reuse our existing rich editing libraries or move to something better before using more of the same. Is starting with plain text fine, and deferring rich editing to an enhancement issue later?
- My only small point of feedback is I’d consider only showing up to 3 avatars, not 5, so there is less wrapping there, but I leave that to you!
- This is ready from my perspective 👏

**Comment by enriquesanchez** [comment]
> such nice work! 

@ackernaut All credit goes to you, I just grabbed some mockups you had previously done from here and there 😄 

> How soon should we build rich editing on cards opposed to plain text?

This is a good point. I figured that since we already have the functionality in task cards it'd be a no-brainer to have it here as well. I'd let a developer make the call here.

> My only small point of feedback is I’d consider only showing up to 3 avatars, not 5

Sounds reasonable. I think it'll help us have less wrapping to new rows 👍

> This is ready from my perspective 👏

🙌

**Comment by nickoferrall** [comment]
> I wonder if the developers want to reuse our existing rich editing libraries or move to something better before using more of the same.

I'm keen to try alternatives to DraftJS (our current rich text editor library), but I suggest that we migrate away from DraftJS in a separate issue(s). Using our existing rich text editor components for stand-ups should help us build it faster, and it shouldn't result in much more refactoring if we move away from DraftJS.

Other questions & reactions:

- The Figma designs look beautiful, and it's great to see that we're reusing a lot of our existing logic!
- The emojis in the design can currently wrap to two lines. Is there a limit to how many lines they could take up?
- How many lines of text could there be in a response card? Will it be 4, like in a regular task?
- If someone edits a card, will the timestamp under their name be taken from when they created the card or when they edited it?
- As emojis are added, the position of the "Reply" button will shift. I might go to click "Reply", but if someone adds an emoji beforehand, I'll accidentally click the emoji. Do you think this could be a problem? If so, maybe putting the "Reply" button in a fixed position at the bottom right of the card would help?

**Comment by enriquesanchez** [comment]
Thanks @nickoferrall 

> The emojis in the design can currently wrap to two lines. Is there a limit to how many lines they could take up?

Yes, we currently limit emojis in reflections to a maximum of 12 and we fit 6 per row. So we only allow for a max of two rows. I think we should do the same for response cards.

> How many lines of text could there be in a response card? Will it be 4, like in a regular task?

Great question! Yes, I suggest we mimic what we are already doing with other card types. We also limit lines of text to 4 1/2 in reflection cards as well.

> If someone edits a card, will the timestamp under their name be taken from when they created the card or when they edited it?

The timestamp should reflect the creation date. 

>  Do you think this could be a problem? If so, maybe putting the "Reply" button in a fixed position at the bottom right of the card would help?

Oh, good point! I have never run into this issue in other places where we follow a similar pattern. Have you? I'm inclined to  put this one aside as a future tension.

**Comment by nickoferrall** [comment]
That all makes sense to me!

> Oh, good point! I have never run into this issue in other places where we follow a similar pattern. Have you?

Nope, I haven't run into this on the comments or reflections where we can add emojis. The "Reply" button is distinct from the emojis so I wonder how it'll feel when its position wraps because emojis have been added, but leaving this as a future tension sounds good to me 👍

**Comment by enriquesanchez** [comment]
Great suggestions @ackernaut  🙌
 
I'm on the fence whether we should truncate stand-up responses or not. I think we can make a more informed decision once we start to play with a live version.

**Comment by ackernaut** [comment]
I think at some point if we consider working out a masonry grid (may not be the best choice responsively, and probably not where we start) then I wonder if we just let the cards take full height. Short of that, we probably need to keep a simpler grid logic tighter by truncating long cards. Just another thought.
