### ISSUE TITLE
Designed default task destination

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5969]
There’s an idea I’ve been kicking around in the back of my head too long. I think it helps us solve for 2 use cases:

1) Folks aren’t aware of our integrations (see #5515 and #5939). I think we can boost awareness in the 2 moments in the UX where integrations are the most helpful. One is for adding issues to Sprint Poker. The other is for adding synced tasks in a discussion thread during a meeting. This issue focuses on adding synced tasks.

2) Some folks have commented in user interviews that they’d like to set it and forget, meaning they want to select where new tasks are created and synced and not have to integrate each task card they write. E.g I pick that tasks go to Jira Project X and that’s where additional cards go

Open questions:
- How can I send tasks to different sources? E.g. one is for the Parabol board, one is a GitHub issue?
- How can I see what options are available to me?
- Can I change the default destination for tasks?
- Do we still have an icon on task cards to upgrade when starting from basic Parabol tasks?
- Can we do this on the task board, too? I.e. set the default, or pick task destinations?
- Can I add additional integrations later, inline?
- If the task is created for an integration, can I then edit the task and everything sync?

Here’s a drunken drawing:

![CamScanner 01-26-2022 12 39](https://user-images.githubusercontent.com/307286/151226184-25b4358f-ea76-4ceb-9ebc-b47446a42167.jpg)

1) When using the discussion thread for the first time on a team (since integrations are scoped to the team), and I haven’t chosen a default destination for tasks yet for this team, I see a button ‘Add Takeaway Task’
2) The first time I have to pick a destination (1) Add to Parabol 2) Add to GitHub 3) Add to Jira 4) More expands future integrations?)
3) Once I’ve authenticated and picked a destination (e.g. GitHub / Repo ABC ) the button has a new state. Tapping the main part of the button adds a task in the default destination. I think this implies that integrated tasks can be edited and sync.  Tapping the arrow gives me more options. There you can choose a different destination, like a Parabol task. You can probably see what your default is. You can probably see a way to add more.

I think that since integrations are specific to the team member and team, each team member would have a default task destination on their team member object.

### Acceptance criteria
- Discussed the feasibility of this with a developer
- Designed concepts addressing the open questions and idea within the context of the discussion thread
  - Note: any of the suggested ideas above are candidates for the garbage can if there’s a better way
- Stretch goal: explored and captured any thoughts around using similar patterns on the task board, later. This may be another design issue if this idea has legs
- If there’s an minimal viable design that seems to work, work with a developer to review the details and write a first implementation issue

### Estimated effort
- 13 hours

**Comment by ackernaut** [comment]
cc @enriquesanchez @mattkrick what do you think about this issue? I imagine there are some hurdles to overcome with task syncing and editing if we went this route.

**Comment by ackernaut** [comment]
This may make a decent Batting Practice, but it’s a little low on discovery since it’s a solution idea.

**Comment by mattkrick** [comment]
1 challenging piece that you mention is that they can't just click "Jira" they have to click "Jira - Project X", and that dropdown will likely need a search bar at the top to find the right project.

We also want to show other users that a card is being created, which means we'll have to create a parabol card when they click new task. Then, while they're writing, we'll need to hide the integration button on that card if the card was created within a thread & is destined for an integration, which feels a little odd.

To solve for the "set it and forget it" problem, even if we have a default, we'll need to provide an affordance to set that default & update it. I think the best thing we can do is show their favorite repo in the integrations button on the task card.

For the discoverability, we could update the button, put some tooltips or icons on it without requiring them to set the integration + repo, which might be a little cleaner

**Comment by ackernaut** [comment]
@mattkrick do you have any ideas on how to solve for users having to click to integrate every card they write? There are those who have a practice of pushing all their takeaways to Jira. They find it clunky to have to make the same choice over and over. Tap to add task, write a card, open a menu, tap the repo, repeat 4 steps for subsequent tasks. I realize entry of tasks is probably not high frequency. Other times folks forget to integrate the task they write. Later they don’t find it in Jira and wonder what happened. At some point we may need to revisit the base pattern at play here.

**Comment by enriquesanchez** [comment]
We had previously explored having more than one action besides `Add task`. I wonder if we could have a different one for creating an issue in Jira/GitHub/etc. This way I just have to initially decide if I want a Parabol task, or a Jira issue, and just select that option.

We can still show in the thread that an issue was created and pushed. Maybe it's a card that looks a bit different than the regular Parabol task?

**Comment by ackernaut** [comment]
@mattkrick @enriquesanchez Enrique and I like the idea of improving the integration button on task cards. Enrique is going to backlog a design issue to explore what we can do there.

**Comment by ackernaut** [comment]
Here’s a low-effort design issue getting at the same problem: #5980

**Comment by ackernaut** [comment]
We probably won’t revisit this anytime soon, iceboxing
