### ISSUE TITLE
Designed Search and Tag function for template selector

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#5972]
As more templates get added to the product, it will be harder for users to find the specific template they are looking for. 

This issue is motivated by discussions that took place in issue #5890 [here](https://github.com/ParabolInc/parabol/issues/5890#issuecomment-1018422782).

Currently, a user can scroll up and down to select a template. Soon there will be >35 templates for retrospective meetings. To make it easier for users to find what they're looking for and effectively browse templates I propose the following enhancement:

1. **Search**: In the template picker view, we can include a search bar that allows users to find templates they are looking for and directly select them. 

1. **Tags**: In the template picker view, users can filter retrospective templates by tag. For now, tags might look like _retrospective_, _futurespective_, _pre-mortem_, _activity_, and _feedback_, for example. As we add more templates in future, we can broaden the tags we might need to use.

I've drafted up two initial ideas of what this functionality _could_ look like, based on the latest designs. Please consider these drunken house drawings. 

![Template Picker 1](https://user-images.githubusercontent.com/15236825/151392601-5ef284a3-ee00-40b7-939a-ff6032874ff6.png)

![Template Picker 2](https://user-images.githubusercontent.com/15236825/151392607-9bab3b22-b1bd-4e77-a9bb-4196b47de809.png)

[Figma file](https://www.figma.com/file/LQCyBrUdKGLgNPxwAy6rBi/Search-and-tag-function-in-template-selector?node-id=0%3A1).

I'd appreciate any help to work this up into a design that could make it easier for users to select the template they want.

### Acceptance Criteria (optional)
Users can:
- [ ] Search for specific templates and select them in the template picker
- [ ] Filter templates based on tags

**Comment by ackernaut** [comment]
I like this design issue! There are a few more opinions and ideas in #6249 — we can close that once we pick up here.

**Comment by jordanh** [comment]
Closing by process, but I'd like to see this done one day. This is issue is very well crafted.

Let us not hesitate to reopen if we hear feedback relating to difficulty of searching of our templates in our existing UI
