### ISSUE TITLE
Task card integration button improvements

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5982]
As part of the efforts to increase awareness of the integrations supported by Parabol, we've been wondering if there's anything we can do to make the `Push to integration` button more clear.

## Acceptance criteria

Designed concepts to address open questions and ideas:

- How is the current `Push to integration` failing users?
- How can we improve its clarity?
- Can we use a more obvious icon?

### Estimated effort
- Suggested: time box to 5 hrs including review

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/78285451) 🔒 recently told me on a call they had no idea the task cards had integrations.
