### ISSUE TITLE
`Opened Spotlight` segment event does not set `teamId` prop 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5987]
## Issue - Bug

When querying the `Opened Spotlight` event via Amplitude, I noticed that `teamId` was never set. This makes it impossible to calculate answer the question, in how what percentage of meetings is spotlight used by any participant?

### Acceptance Criteria (optional)
  - teamId is set when generating `Opened Spotlight` event 
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by nickoferrall** [comment]
Hey @jordanh, we include the `meetingId` in the `Closed Spotlight` event, so I think we can calculate the % of meetings using Spotlight like so: https://analytics.amplitude.com/parabol/chart/durywx6

**Comment by jordanh** [comment]
Good catch and good work around! I created a new analysis here that tweaks a few things : https://analytics.amplitude.com/parabol/chart/65rczbw

While technically still an issue, I will close as there is no urgency to fix any longer
