### ISSUE TITLE
Jira Server: show integrated task

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5994]
Requires:
* #5810 
* #5993 

## Acceptance criteria
* [ ] call `createTaskIntegration` from the `TaskIntegrationMenu` for Jira Server
* [ ] add Jira Server to [`integration`](https://github.com/ParabolInc/parabol/blob/6893c722d92f4a3b0daed839c0b0e9aa977f2f4d/packages/server/graphql/types/Task.ts#L78) field on `Task`
* [ ] adapt UI to show integrated task

**Comment by Dschoordsch** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/37) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by mattkrick** [comment]
closing in favor of #6059
