### ISSUE TITLE
Poker: Dragging Scoped items in Estimate agenda unexpected behavior

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5997]
## Issue - Bug

See this video: https://www.loom.com/share/8fd2cc36a9eb4cec946d6eb94f8a1b8d

Repro steps:

1. Scope at a few issues (repro'd with ~10)
2. Drag an issue from the middle of the list upward in the list, note duplication
3. Drag issue down, note duplicate issue _may_ go away

- **How serious is the bug?** P2

### Acceptance Criteria (optional)
Users can:
   - Reprioritize issues without duplication

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
Duplicated issues are collapsed when they are adjacent
![Adjacent duplicate tasks are collapsed](https://user-images.githubusercontent.com/7331043/152769966-c8df724e-d109-4f65-9bd7-11b93e9704c5.gif)

**Comment by mattkrick** [comment]
ohhhhh that's a good learning!
my guess is dragging the item only drags the first dimension & doesn't drag any subsequent stages along with it. i don't think i ever tested drag & drop with multiple dimensions

**Comment by Dschoordsch** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/40) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
