### ISSUE TITLE
Poker: dimension order non-deterministic

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5998]
## Issue - Bug

When estimating with multiple dimensions, the ordering of the dimensions can be non-deterministic.

See: https://www.loom.com/share/bc05e5cf7aa04a388d71361f41582572

- **How serious is the bug?** P3

### Acceptance Criteria (optional)
Users can:
   - browse the Estimate agenda and have the dimensions always display in the template's order

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
fixed in #6028

**Comment by tianrunhe** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/11) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
