### ISSUE TITLE
Poker: Scope: Sort selected items to appear on top of list 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6003]
If there are 10 items in the scope, those 10 items should appear on the top of the search results.

Please fight me on the AC if you disagree

AC
- [ ] when the search query is null (or default), the selected items appear on the top of the list
- [ ] when the search query is non-null, the results are sorted by selected & then salience
- [ ] In the case of paginated results, e.g. if 2 items from the first page are selected & 3 from the second page, then 2 results would be on the top at first, when page 2 loads, then 5 items would be on the top

Estimate: 4 hours

**Comment by ackernaut** [comment]
Any UX play with this issue? https://github.com/ParabolInc/parabol/issues/5955
