### ISSUE TITLE
Jira: getAllProjects maxResults?

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6006]
The Jira API has maxResults as an int32. Does that mean we can request more than 50 at once? If so, we should do that to avoid having to paginate.

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-search-get

AC
- [ ] test how many projects we can return from jira by setting the maxResults param & report back

Estimate: 1 hour

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/21) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
