### ISSUE TITLE
Slack integration not finding correct channels 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6008]
A [user](https://app.hubspot.com/contacts/3888472/contact/63108301) 🔒  writes:

> I am able to add the Parabol app to the channel where I want notification to go but when I go to the settings screen you snapshotted, my channel is not in the list of available channels. In fact the list is populated with a seemingly random subset of channels from our Slack instance.

More info in this [slack thread](https://parabol.slack.com/archives/C4JAUUZ9P/p1643404924356909) 🔒

**Comment by jordanh** [comment]
Maybe there are too many channels or we are not paginating?

Will assign `p2`. Will bump up the stack if we hear this again
