### ISSUE TITLE
Cannot restore from production pg_dump

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6017]
To dump a slice of our production database (ie data that only pertains to our team) we do the following:
- query all the data we want
- create a new database called orgBackup
- inject that data subset into orgBackup
- export the orgBackup data
- rename schema orgBackup to public
- export the orgBackup schema

this has worked well for us in the past because to restore, we just restore the schema, then restore the data on top of that schema.

However, that all changed once we started using generated columns.

Now we get the following error:

```sh
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 4149; 0 39593 TABLE DATA User pgparaboladmin
pg_restore: error: could not execute query: ERROR:  column "domain" is a generated column
DETAIL:  Generated columns cannot be used in COPY.
Command was: COPY "orgBackup"."User" (id, email, "createdAt", "updatedAt", inactive, "lastSeenAt", "preferredName", tier, picture, tms, "featureFlags", identities, "lastSeenAtURLs", "segmentId", "newFeatureId", "overLimitCopy", "isRemoved", "reasonRemoved", rol, "payLaterClickCount", "isWatched", domain) FROM stdin;
```

that copy command shouldn't include `domain`, but it does. 

PS
pgRestore should use the docker image to restore:
```ts
  const containerId = '$(docker ps -aqf "ancestor=docker_postgres")'
  const dockerExec = `docker exec -i ${containerId}`
```

AC
- [ ] figure out how to restore the output from `backupOrganization` for postgres

Estimate: 16 hours

**Comment by igorlesnenko** [comment]
Using pg_dump/restore v14, I was able to manually dump and restore on a fresh db

```
pg_dump --file="/Users/igor/{data_source}-{timestamp}-dump.sql" --format=t --create --no-owner --role=pgparaboladmin
```

```
/usr/local/Cellar/libpq/14.1/bin/pg_restore --dbname=database_name --format=t --username=pgparaboladmin --host=localhost --port=5432 /Users/igor/parabol_STAGE-2022_02_09_01_32_24-dump.sql
```

**Comment by jordanh** [comment]
**Include in next sprint?: N**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/7) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
