### ISSUE TITLE
Add first-class unit testing support (backend)

### ISSUE THREAD

**Issue by blimmer** [ParabolInc/parabol#6018]
## Issue - Enhancement

Today, the backend test suite only contains [a few tests](https://github.com/ParabolInc/parabol/tree/d681cf1e283f4bc497d456d96bcdedc393e1a49a/packages/server/__tests__). This makes it challenging to write tests for new features and against bugs as they're fixed.

There are currently a few missing infrastructural components that make adding additional tests more challenging:

1. Tests that rely on the database have side-effects. The database should be truncated after each test runs.
2. Rate limiter can cause test suites to fail.

### Database Truncation

For Postgres I've seen a pattern that uses the excellent [`pg-structure`](https://www.pg-structure.com/) NPM package to build a database function for truncating all tables. Then `beforeEach()` test, you call the function within the test database to ensure tests do not leak state between each other.

I'm not super familiar with RethinkDB but, because there's active work to migrate over to Postgres, perhaps we could hard-code some reset logic for the data stored in Rethink?

### Rate Limiter

It looks like the Rate Limiter is currently using an in-memory store since the app isn't horizontally scaled. For the short-term, I think we should be able to find a way to reset the store `beforeEach()` test, similar to the database.

Speaking more long-term, it might be nice to introduce a `Context` object that wraps up "tools" used throughout the server. For instance:

```ts
interface Context {
  rateLimiter: RateLimiter
  mailer: Mailgun
  logger: Pino
  stripe: Stripe
}
```

Then, in `test` you can inject test-versions of the services in the `Context` to reduce the need to mock the third-party services.

### Acceptance Criteria
Developers can:
  - Be sure that the data stores are reset between each test that talks with the database
  - Not be rate limited when calling the same endpoint multiple times

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes)). This is just an estimate. I mostly wanted to open this up for discussion for now. I think the outcome of this ticket would be a few smaller tickets that would be easier to scope and point.

**Comment by mattkrick** [comment]
Notes from chatting with Ben:
- This is really good & probably the pattern that we want to move towards
- Before we do this, we'll want to complete #4778. Getting that extra type safety will provide the biggest bang for the buck & then moving things like DB drivers into the context can come next
- RethinkDB is a big thorn in our side. We should focus on migrating away from that before implementing graphql resolver tests so we can use only pg-structure instead of building tooling for a legacy DB that we're moving away from
