### ISSUE TITLE
Add first-class unit testing support (frontend)

### ISSUE THREAD

**Issue by blimmer** [ParabolInc/parabol#6019]
## Issue - Enhancement

Today, the front end application does not have a working unit test suite. It would be nice to be able to:

- Mount a component
- Mock out resolved network responses
- Make assertions using a library like [react testing library](https://testing-library.com/docs/react-testing-library/intro/).

Compared to the corresponding backend ticket (#6018), I'm less familiar with what it will take to get this implemented for the frontend, because of the use of websocket subscriptions and relay.

That said, it looks like Relay has some testing documentation that would be worthwhile to further investigate: https://relay.dev/docs/guides/testing-relay-components/. Based on a quick review of that page, it looks like they support generating fixture data out-of-the-box, which would help ease the burden of writing tests.

### Acceptance Criteria (optional)
Users can:
   - Easily simulate a network response to provide Prop data to their component
   - Mount a component for testing
   - Make assertions on the rendered result of the mounted component

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes)). For now, I'm going to open this up for discussion. I think I'd need to do some more investigation to provide a more accurate estimate.

**Comment by BartoszJarocki** [comment]
There's definitely a lot of value to gain from testing. Although, unit tests aren't usually very useful on the front end unless we're talking about testing utility functions and stuff like that. Also, to be specific by unit test I mean, a test that mocks all the dependencies of a given component/function and validates the output of it. In the component world, this gets tricky. 
There's an article that I agree with: https://kentcdodds.com/blog/write-tests. The TLDR is, unit tests in the component world bring very little value and give a lot of maintenance overhead. On the other hand, _integration tests_ are great! 

An example of frontend integration tests in our case could be:
1. Discussion thread tests ie. mock network responses only and renders all the component tree of the discussion thread, then, for example, add a comment, check if comment appeared in the thread; add a task, check if the task appeared in the. thread
2. Meeting phases tests
3. Adding a new team
and so on. 

In this solution, there'll be fewer tests and they _should_ be easier to maintain while providing more confidence than unit testing of each of the components. 

Now, the problems with that
1. What should be tested and how big of the scope of the test could be? This is more art than science and could lead to more confusion about where and how to write tests (after all, we could render the whole `<App />` and try to click through it). 
2. While Relay is great, mocking the network/data layer isn't _easy_, especially in our case where the app is very subscription/data-heavy 

That said, I still think it'd be great to head in that direction. TLDR: I personally don't like `snapshot` testing components, and tests that check if `Button` renders a `Button`, as the value they give is very low compared to the overhead they need. Integration testing would be great, though.

**Comment by mattkrick** [comment]
After chatting with Ben:
- Finishing up the demo tests will provide the biggest value right now
- After that, exploring tests that prove our subscriptions work will be great, so long as we don't hit too many problems with RethinkDB. See #5961
