### ISSUE TITLE
Add Open-AI Summary to top of Discussion Thread

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6027]
AC
- [ ] In a retro, at the top of the discussion thread, we should show a digest summary
- [ ] The input of that digest summary is all the cards in that group
- [ ] The output is a summary of what the cards are about

Out of scope: caching

Estimate: 8 hours

**Comment by jordanh** [comment]
May I suggest we hack this in and put it behind a feature flag? It'd be great to see what kind of content the API generates for ourselves. I bet that would generate future ideas.

**Comment by jordanh** [comment]
Good fodder for a hack week
