### ISSUE TITLE
Bug: dropping agenda item/estimated tasks to original position causes error

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6029]
In Sprint Poker, when dropping an estimate issue in its original position, there's an error in `PokerSidebarEstimateSection`: `Cannot read properties of null (reading 'index')`

![poker-sidebar-bug](https://user-images.githubusercontent.com/39854876/153407548-5fcf88fa-a444-41fc-a6ee-b0f815bd487f.gif)

I can't reproduce this in production, but I can in master.

### AC

- [ ] Users can drag and drop estimate issues in their original position in the sidebar

**Comment by tianrunhe** [comment]
EDIT: changed the title to indicate that this also happen for agenda items

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/19) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by elielytz** [comment]
## Testing summary 
Environment: local-master
No error is caused on vertical drag (along Y-Axis), but there is an error caused when the card is dropped along the X-axis

https://user-images.githubusercontent.com/45159239/155671907-864263b4-46ef-4c33-96b5-11118e7a3eda.mp4

.
