### ISSUE TITLE
Jira webhook API spec'd

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6031]
At the moment we read Jira issues only when they're loaded and don't live update these. The quality of the integration would be better if we would implement live updates.
Jira supports webhooks for OAuth2 apps [docs](https://developer.atlassian.com/cloud/jira/platform/webhooks/#registering-a-webhook-using-the-rest-api--for-connect-and-oauth-2-0-apps-)

## Acceptance criteria
* [ ] webhook designed to update Jira issues
* [ ] defined how we manage registering/unregistering webhooks so we don't over/under-subscribe
* [ ] defined how this can be made generic for future integration webhooks (Jira Server, GitHub, Gitlab)
* [ ] issues created for the implementation

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/14760601) 🔒 writes:

We're using the Sprint Poker Meeting tool and link our issues via Jira. One thing we miss is: if a story's description is being updated in Jira, there is no option to reload/update the linked issue in the ongoing Sprint Poker Meeting. Would love to see that option available in the future.

**Comment by mattkrick** [comment]
For the Batting Practice

Acceptance Criteria 
- [ ] When a user has parabol open & they're looking at a Task that is integrated with Jira, when they update that issue on the jira website, the task in parabol gets updated without them having to refresh

**Comment by jordanh** [comment]
Closing #6153 until we decided to re-prioritize. Keeping this issue, the original tension, open for prioritization

Make sure to review #6153 when we decide to carry this through to completion, there are many good thoughts in there

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/55646451) 🔒 mentioned during a feedback session:

When you import Jira tasks and are in the first round of estimation, we want the description to update, currently, we have to be on both Parabol and on Jira at the same time.

We want real-time updates from info in Jira to Parabol without having to refresh. The description doesn't update unless you re-import it.

**Comment by acressall** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/57109001) wrote in:

> As a improvement that I think it would be great to have is to be able to refresh the description of the cards. For example, sometimes I add some information to the Jira tasks, but I can't see those changes in the Parabol cards. The way I do it now is to deselect and select again the task in Scope. But that action deleted all the comments that my team had written :(
