### ISSUE TITLE
Sprint Poker: GitLab: Display issues

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6034]
Successor: #6088 

### AC:

- [ ] Query the GitLab issues that the viewer is a member of
- [ ] Display the GitLab issues in the list

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/31) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by nickoferrall** [comment]
@jordanh issue updated. I've removed some of the AC in this issue and moved it to this new issue: https://github.com/ParabolInc/parabol/issues/6088
