### ISSUE TITLE
Retro: Spotlight: Disable spotlight if someone is editing the card

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6036]
AC

- [ ] If someone creates a new card during the group phase, another user should NOT see the spotlight icon.

Estimate: 3 hours

**Comment by 87prashant** [comment]
Do you mean the search icon here?

![Screenshot 2022-07-25 122420](https://user-images.githubusercontent.com/106697681/180716235-d7e9a26e-80e5-4f7b-abf0-71a4676256a7.png)

**Comment by 87prashant** [comment]
Also, can one not edit the reflections made by others in the `group` phase?
Is this intended?

**Comment by 87prashant** [comment]
I was checking with `isEditing`, but it is only limited to local changes
It does not show remote editing of the reflection card.

I think `isEditing` should also update on remote editing.

**Comment by jordanh** [comment]
Still a good one, but iceboxing for now

**Comment by Dschoordsch** [comment]
@87prashant `isEditing` should update on the remote side. It's set by the `EditTaskPayload` of the `editTask` mutation. Maybe we're missing the correct subscription in the group phase so it's not properly updated.

**Comment by 87prashant** [comment]
@Dschoordsch, can I work on this in future

**Comment by Dschoordsch** [comment]
Sure, that would be nice!
