### ISSUE TITLE
Poker: updatePokerScope should not reach out to the integration

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6043]
While debugging #6015 I noticed that every time an item is added or removed from the scope, all selected items are fetched from the integration! This is not necessary. I assume the mutation payload includes a fragment that is like `{task { integration {...} } }` and it shouldn't have that. This causes our app to feel slow while selecting items.

AC
- [ ] updating the poker scope for integrated items does not reach out to jira or github

Estimate: 4 hours

**Comment by tianrunhe** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/13) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
