### ISSUE TITLE
Sprint Poker: GitLab v1: Search issues

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6045]
Predecessor: #6088 
Successor: https://github.com/ParabolInc/parabol/issues/6046

Like the Poker integration with Parabol tasks, the user can type into the search field. This will filter issues whose title & description don't match the search query. 

Unlike Jira or GitHub, for v1, the user cannot save search queries or add more complicated searches such as filtering by labels.

AC: 

- Create a UI that’s similar to the Parabol tasks search bar
- There’s a placeholder that says “Search issues in GitLab”
- Typing into the search field filters the issues by their title & description

**Comment by jordanh** [comment]
**Include in next sprint?: N**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/33) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
