### ISSUE TITLE
Sprint Poker: GitLab v1: Project filter menu

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6046]
Predecessor: https://github.com/ParabolInc/parabol/issues/6045
Successor: https://github.com/ParabolInc/parabol/issues/6138

### AC:

- [ ] There's a filter button on the right-hand side of the search input, just like GitHub, Jira, and Parabol tasks
- [ ] Clicking the filter button opens a dropdown menu that contains all of the projects that the user has access to
- [ ] It is sorted in a sensible, deterministic fashion. `lastActivityAt` could be a good field to sort by
- [ ] Selecting a project in the menu filters the issues displayed in the card
- [ ] If there’s more than 10 projects, include a search box just like Jira & GitHub
- [ ] As the user types, the projects displayed in the menu are filtered

**Comment by nickoferrall** [comment]
**Story points: 13**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/13) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by nickoferrall** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/14) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by mattkrick** [comment]
fixed in #6323
