### ISSUE TITLE
GitLab v3: Self-Hosted Architectural Spec Written

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6051]
Now that we've integrated Parabol with GitLab cloud, let's create an architectural spec for the self-hosted integration.  

### AC

- [ ] Spec is written in GitHub with a high-level proposal on how implementation will work. [See example here](https://github.com/ParabolInc/parabol/issues/4412#issuecomment-948003051).
- [ ] After spec is reviewed by Reviewer & Maintainer, the Epic and Issues are created (including design and implementation issues).

**Comment by acressall** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/94183751) has requested this integration:

> Hi, is there any way to integrate with Self-hosted Gitlab and Parabol ?

**Comment by enriquesanchez** [comment]
[Another user](https://app.hubspot.com/live-messages/3888472/inbox/4057812496#email) 🔒 has also inquired about the self-hosted version:

>My team host gitlab on our own server so it's it differ url then the main gitlab. Can I still integrate parabol with my team's gitlab?

**Comment by jordanh** [comment]
Removing stale as a user asked about this last week. Keeping open for now to collect more signal

**Comment by jordanh** [comment]
(chances are we'll do this for one of our DoD folks)

**Comment by jordanh** [comment]
Taking this out of the icebox

**Comment by Dschoordsch** [comment]
We're going to support only 1 GitLab integration per team member. This is already possible with the current architecture.
