### ISSUE TITLE
Track down the root of a reflectionGroup not having reflections

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6055]
https://github.com/ParabolInc/parabol/pull/6010 logs the error & keeps things from breaking, but it doesn't get to the root cause.

Sometimes, a reflectionGroup has `null` reflections. This should not be. Technically, it shouldn't even be an empty array. A reflection group should also have at least 1 reflection in it after the updater has run.

AC
- [ ] devise a way to determine what is causing the bug. I suggest first determining if this is caused by an optimistic updater. If so, then we just need to triage that bit of code.
- [ ] If it's not caused by an optimistic updater, we need to figure out if it affects all members in the meeting (via subscription) or just the person triggering the mutation

Estimate: 8 hours

**Comment by jordanh** [comment]
Assigning `p3`, will bump if we suspect this is related to other badnesses
