### ISSUE TITLE
Designed initial editable prompt view for standups

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6069]
Initially we want to test stand-ups with a static prompt. Later we want to add the ability to edit this prompt.

### Questions
- How might we design a dialog view that can open up from both the existing start meeting view and the newer start meeting dialog design?
- Is the default prompt the same any time a new meeting is started? Probably so, as we would wait to store and reuse prompts when we add templating?
- How much formatting does the prompt provide. Do we start with plain text? Do we start with full formatting like task cards (bold, italics, command + K linking, etc.)?
- For the MVP there’s not recurring, however can I edit the prompt once the meeting has started? Once recurring is built, where can I edit the prompt? The top bar design #5926 suggests that updating the meeting happens from an upper-left options menu. Do we open the prompt dialog from a menu item? Some other way? Do we just reuse the prompt editor dialog view?
- What are the states of a prompt editor?

### Acceptance criteria
- Proposed concepts that answers questions like the ones above, including any variant states and workflow contexts
- Wrote down general criteria that can be used in an implementation issue and reviewed with a designer and developer

### Estimated effort
- 8 hours

**Comment by ackernaut** [comment]
cc @enriquesanchez does this design issue make sense? Do I need to clarify anything? Did I miss anything? Feel free to add to the list of questions above. Thank you!

**Comment by enriquesanchez** [comment]
@ackernaut 

> How much formatting does the prompt provide?

What did you have in mind when thinking about formatting prompts?

> What are the states of a prompt editor?

Are you referring to states such as empty, edited, etc?

**Comment by ackernaut** [comment]
@enriquesanchez 

Re: formatting prompts; do we allow for bold, italics, links, emoji, integration attachments, etc.

E.g. Here’s the proposal (attached link to Notion) Clarifying questions? 👂 

Re: states; yes, any error, empty, etc. [anything from this list](https://www.figma.com/file/TApZCU6WOLaA7xN79N8nIB/UI-State-Checklist?node-id=2%3A151) that applies in this context

**Comment by jordanh** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/aOko8PmZr2/estimate/41) in Planning for Sprint #​​97

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
@enriquesanchez I suggest this is your mission, should you choose to accept 📩

**Comment by enriquesanchez** [comment]
![image](https://user-images.githubusercontent.com/3276087/155623325-6eca7c82-973c-4e88-9da5-6a99235029fb.png)



[Here's the design proposal (Figma)](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1315%3A85138).

- [From the current start new meeting view](https://github.com/ParabolInc/parabol/issues/5888), clicking on the prompt field will open a UI modal similar in size and behavior as the current templates modal.
- The prompt modal contains a text field with the text for the default prompt.
- The prompt can be edited and supports markdown styling (links, bold, italics).
- We should probably limit how many characters a prompt can have. **Open to suggestions here**.
- Below the prompt text field we show some suggestions (5) for common or recommended prompts the facilitator can use. **Open to suggestions here**.
- There is a `Save prompt` button (similar to the `Use template` button) on the bottom right corner of the modal.
- We can use the same modal for the current and [the upcoming new meeting view](https://github.com/ParabolInc/parabol/issues/5589).
- Once a standup activity has started, the facilitator can edit the prompt by clicking on the `Edit` icon found next to the prompt. Only the facilitator can edit the prompt.

**Comment by tianrunhe** [comment]
Oooo looks good! I have a lot of questions on this one:

1.  The text field:
    1.  Is it just one-liner? Can you expand?
    2.  I agree we should set a limit on max number of characters, but also on min number, to encourage good behavior. What would the error state look like when we exceed that limit?
    3.  Maybe we should default the prompt to the last used one? Like today the behavior for default chosen template.
2.  The suggestions:
    1.  Are the suggestions created & maintained by us? Like public templates in retro & poker meeting today?
    2.  Are the suggestions just plain text? I wish I could just click on one of them and it automatically populate the text field, maybe in the next version
3.  The FAB & the modal:
    1.  I feel like since in this early version you can't create/edit/delete/share the prompts yet, it's more "Use prompt" to me. WDYT?
    2.  If you change the prompt text, instead of clicking the FAB you close the modal by hitting the x, does the text preserve?
    3.  Does clicking outside the modal automatically close the modal too?
4.  The title: I feel like having both "Prompt" and "Standup prompt" are redundant. WDYT?

**Comment by ackernaut** [comment]
@enriquesanchez thanks for pushing forward here 🙌  :
- Do you think we need formatting on prompts in the first pass? I suppose a developer could help us decide if we do that
  - In the future, I really like the idea of being able to link to a supporting doc, and maybe one day, using integrated links for supporting docs
- Why might we need a min or max limit of characters?
- I like the prompt suggestions, here are more ideas:
  - What did you learn today?
  - What’s got your attention today?
  - What’s one thing outside of work you’re looking forward to today?
- I agree that ‘Save prompt’ may feel a little like there’s some templating feature that’s not there, yet
- I have no problem with the suggestion to edit the prompt inline. I am curious about what you think about how we develop the IA of this activity (and similar affordances for new activity types). In that sense I wonder if we should move away from that pattern here. It’s a pattern that we’ve used in the current UX and I think it stands improvement:
  - What if we add a little friction to changing the prompt by moving it [more toward a settings view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=845%3A77557)? The first thing that comes to mind is that I want the UX of these views to be very focused. Sometimes I’m concerned secondary buttons and actions tend to get added instead of taken away. Interfaces can feel clunky in my opinion. Maybe the razor is that anything useful for the primary UX (participation in the activity) makes it in (i.e. can be inline, more obvious, more useful in the workflow moment, etc.), any meta work (like activity settings, etc.) gets put in the options or a menu of options? I suppose we’d have to think about where some facilitator actions fall (is it part of the activity (e.g. starting a timer) or part of the work supporting the activity (e.g. we haven’t updated the recurring prompt in weeks, but now I want to). If that last case were a case then why always have the noise of a pencil there?)
  - That said (previous bullet), [what do you think about this IA](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1138%3A72617)?
 - What does mobile look like? Is it a full-screen dialog? It’s obviously single column 100% width in a sense, but do type and margins stay the same?
 - In the future: I think what may be in our future is starting to think of a targeting template library system:
   - What type of activity or composable phases are there? Can they be added? Are there template options at the activity level? At the phase level?
   - What do we learn from our existing template system?
   - I can we select a list of random prompts? How can we clone or create those lists to make them our own?
   - I think the driving mechanism in any cases I can think of is: this activity or phase has a prompt (e.g. recurring social prompt) or a sequence of steps (e.g. sequence of governance prompts). How do I select what drives that prompt or sequence? What template options might we have for how folks engage? (E.g. responses are anon/public, can have 1 or many responses? Are responses revealed immediately? Are threads open on comments at this phase? A real rabbit hole that needs to be driven by use cases of structured comms!)
   - My reason for writing this ‘future’ bit is just to have a think about it. It may inform your MVP designs. In your role, you may develop an opinion and really drive target designs and iterations later, if we get to a point, and privilege, where we’re designing a larger system of activities including the structured conversations.

**Comment by enriquesanchez** [comment]
Thanks for the thoughtful feedback and questions, @tianrunhe and @ackernaut 🙌

> The text field: Is it just one-liner? Can you expand?

My idea is that you can expand. I don't want to both limit how much text the user might feel they can add by having a small text field, but also don't wan't to have a big text area that encourages longer prompts. A two-line text field feels like a good balance, and of course, it should expand if the users types a longer string of text.

> What would the error state look like when we exceed that limit?

Oh, great question! I obviously did not include this and I will update the mockups to show error states 👍

> Maybe we should default the prompt to the last used one?

I like this idea 👍

> Are the suggestions created & maintained by us?

For now, yes. Eventually, if/when we introduce some kind of templating features for stand-ups then this will change.

> Are the suggestions just plain text? I wish I could just click on one of them and it automatically populate the text field, maybe in the next version

Yes! We also had the same idea of clicking to populate the field. I'm not sure how to make this action obvious without any additional affordances. Would love yo hear if you have any ideas here. On the other hand, having them as plain text (that you can select, copy and paste) would make for a decent first version.

> I feel like since in this early version you can't create/edit/delete/share the prompts yet, it's more "Use prompt" to me. WDYT?

You are totally right 👍

> If you change the prompt text, instead of clicking the FAB you close the modal by hitting the x, does the text preserve?

I'm honestly undecided about this. On the one hand a user might want to cancel the action, how would they do that right now? By closing the prompt. On the other, we are growing more and more used to click-to-edit interfaces, where there is no explicit `Save` or `Edit` actions. The latter feels more consistent to how Parabol currently works (task cards, reflections, etc), so it feels like the most obvious approach. What do you think?

> Does clicking outside the modal automatically close the modal too?

Yep!

> The title: I feel like having both "Prompt" and "Standup prompt" are redundant. WDYT?

I know! I struggled with this one. The modal should have a title, but I also want the text field to have a label (for accessibility and clarity), and I couldn't come up with a better label. Maybe `title = Standup` and `label = Prompt`?


> Do you think we need formatting on prompts in the first pass? 

I think so, yes. I mentioned in the design details above that the text field supports markdown styling (links, bold, italics). This should be identical to how we handle text styling in task cards and thread comments. I wouldn't go as far as allowing quote blocks, tables, etc.

> Why might we need a min or max limit of characters?

The idea is to avoid something like this from happening:

![image](https://user-images.githubusercontent.com/3276087/156457701-bb117b1f-021c-48a4-ba24-6de18e20d449.png)

I see it as a way for the software to encourage good meeting hygiene. 

> I like the prompt suggestions, here are more ideas: 

I love these! I will add them to the mockups 🙌

> What if we add a little friction to changing the prompt by moving it [more toward a settings view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=845%3A77557)?

Your suggestion feels much better. I agree we should keep the UI simple and focused 👍 
Deferring these explorations for #6076 then.

> What does mobile look like?

Oh wow, I missed adding these mockups! I will update the Figma file. Thanks for the reminder.

**Comment by ackernaut** [comment]
Ha! I like that you showed the long prompt. In the future, I think we should account for longer prompts, maybe we do something like expanding and collapsing as seen in Sprint Poker issues during the Estimate phase. But encouraging linking out for the background and supporting doc is probably the better practice.

Whatever we do here I suggest it be the minimal next version. Eg.
- We start with a static prompt
- You can edit a prompt (but we don’t save the last one or tap to add from the ones below, etc.)
- We move on to template ideas
- Etc.

Your ‘copy and paste’ from the suggestions below is a good example of how to reach for a lesser version first.

I think we can capture those ideas, but avoid scope creep in the next version.

Thanks for all the attention to detail here!

**Comment by tianrunhe** [comment]
@enriquesanchez Thanks for answering these questions!

*   I think having a plain text suggested prompts as the first version makes sense
*   click-to-edit also makes sense to me. I noticed today our template editor modals do not even have the closing button
*   regarding the modal title and text field label, I'm really bad at naming stuff so... no much tension there

**Comment by enriquesanchez** [comment]
[Placeholder implementation issue is here](https://github.com/ParabolInc/parabol/issues/6216).
