### ISSUE TITLE
Refined recurring UX (part 2 of 2, the UI)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6073]
Based on the output of #6072 

### Questions
- How can we build a dialog view that can be used in both the existing and new start meeting views?
- What are the states of the view? What are the controls in the view?
- Where do we update recurring configuration. #5926 suggests we do it from the upper-right options menu of the activity view. What does that look like? Do we open the same dialog view from a menu option? Something else?
- What are the various states, tips, error messages etc.

### Acceptance criteria
- Updated and created concepts to use the latest recurring UX logic and criteria
- Concepts have all styles and states needed for implementation
- Proposed written criteria for implementation
- Reviewed with a developer and a designer

### Estimated effort
- 8 hours

**Comment by ackernaut** [comment]
cc @enriquesanchez how does this issue look? Questions? Anything missing?

**Comment by enriquesanchez** [comment]
LGTM! 👍

Exploring this one is going to be fun 🎉

**Comment by ackernaut** [comment]
@enriquesanchez I’m going to continue the work here. I like the work you did for setting up recurrence in the new dialog views, so I’ll probably borrow that. When I get to a stopping point, mind if I ask for a review?

**Comment by enriquesanchez** [comment]
@ackernaut Sounds good! 🙌 

> When I get to a stopping point, mind if I ask for a review?

Absoultely! Happy to help 👍

**Comment by ackernaut** [comment]
Updates:
- These updates support setting up and editing a recurring meeting series based on [where we left off in this doc](https://www.notion.so/parabol/Recurring-logic-v1-4ee17110f78b471e80f4d58c6ad3c03f) which is the output of #6072 . I won’t get into the details on how chat notifications work at this time, just that they are decoupled from the time that a recurring instance ends
- For configuring recurrence there is a dialog that can be used in 2 states: one for [initially setting up recurrence](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1417%3A87594), and another for [editing recurrence](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1657%3A90030). Setting up happens in the [new meeting dialog](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1315%3A85140). Editing is an option in [the settings menu of the activity view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1417%3A90591).
  - There is a field for ‘Each instance ends at’ where folks can select a time. We give them 30 min increments. It’s based on the viewer’s local time. Alternatively, we could remove this field and just end ‘Monday’ or whatever day at the latest possible time globally, i.e. 11:59 PM UTC+14. Later we may learn something from users about inputing more exact times or specifying timezones
- The name and prompt can be edited from [a dialog view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1657%3A90770) similar [to the initial prompt dialog view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1315%3A85239)
  - When editing the ‘activity name’ folks are editing a name field on the meeting series object. Updating this changes it everywhere, including previous summary cards. A summary card will have the series name, the instance date, and the team name. ‘Async Stand • Wed Apr 6 • Crash Test Dummies’
  - Here’s [an example of a summary card](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1657%3A90746) if we use the meeting series name, end-at day, and team name
- A meeting series, once started, can be ended from [the settings menu of the activity view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1417%3A90591). A meeting series can’t be changed to a ‘one-time’ activity
- The [menu for editing and ending the activity](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1417%3A90591) could alternatively hang off of the meeting card instead but I think we should decide for one place over the other. I think given the constraints of our dashboard, we should have folks edit the meeting closer to the context of the meeting (i.e. they see the activity view and have a better idea of what’s going on). I could see it being very easy to accidentally edit or end the wrong meeting from our existing dialog view. Also I don’t want to try to solve all meeting configuration in the future (especially the prospect of building your own meeting) from our meeting cards, but rather closer to the activity itself. I also don’t want to try to edit everything inline with pencil icons. I don’t think that pattern will scale well in the future. See [my comment here](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV?node-id=1315:85379#176193202)

**Comment by ackernaut** [comment]
@enriquesanchez @BartoszJarocki @mattkrick any questions or feedback for [the comment above](https://github.com/ParabolInc/parabol/issues/6073#issuecomment-1090835107)?

Consider the recommendations above next steps or future target; future target meaning there may be a smaller step toward what is above, which I’m okay with identifying.

**Comment by ackernaut** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/15) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by mattkrick** [comment]
> Alternatively, we could remove this field and just end ‘Monday’ or whatever day at the latest possible time globally, i.e. 11:59 PM UTC+14. 

Timezones are hard. REALLY hard. I promise if you keep everything in a single timezone defaulted to the local time everything will work out. When folks try to get fancy with timezones it only leads to heartache

> The name and prompt can be edited from [a dialog view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1657%3A90770) similar [to the initial prompt dialog view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1315%3A85239)

I'd love to avoid multi-field forms if we can help it. In other meetings, you can edit the meeting name by clicking on it. That's great because the action is colocated with the field, i know exactly where to go, I don't have to worry about clicking a save button, it just feels very lightweight.

Similarly in the check-in meetings, you can edit the prompt by clicking on it & editing inline. I like the suggested prompts. We could add those to a dropdown box that acts kinda like a typeahead (think github when you hit the `#` sign and start typing).

> A meeting series, once started, can be ended from [the settings menu of the activity view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1417%3A90591). A meeting series can’t be changed to a ‘one-time’ activity

This menu feels strange in the meeting. We're inside an _instance_ yet we're controlling a _series_. Children shouldn't control their parents 🙂 . These settings should live in the _series_ menu (e.g. the 3 vert dots on the series card in /meetings).

> I also don’t want to try to edit everything inline with pencil icons. I don’t think that pattern will scale well in the future.

I _really_ like inline editing. Don't make me hunt for the setting i want to change! On desktop we can show pencils on hover like we do with templates today. On mobile we can hide the pencil & facilitators will just tap to edit.

**Comment by ackernaut** [comment]
Here’s an updated WIP proposal (links to Figma to come):

- **Meeting series name**: the facilitator can edit the meeting series name inline from the activity view. Changes to the meeting series name affect past, present, and future artifacts (e.g. like the team name as seen on summary cards; if you change the team name the change will be reflected on an old summary card). The activity view uses the meeting series name meta in the upper left
- **Meeting instance name**: the meeting name is the day the currently open instance closes; in this format, e.g. Fri Apr 8. This is not designed to be editable. It can be used to distinguish past instances from one another: Series Name • Day Month Date. This information is immutable for historical artifacts
- **Meeting series prompt**: the facilitator can edit the meeting series prompt inline from the activity view. They can only do it from within the instance that is currently open, not from past instances. (Folks may get to past instances from summary cards or a future date picker.) Changes to the prompt only affect the current and future meetings. The meeting series prompt is stored as an immutable prompt field on the meeting instance object once that instance closes
- **Editing recurrence**: any member (?) can open and edit recurrence from a menu item on the meeting card for the series. They simply open the dialog view in the editing state
- **Ending a series**: any member (?) can end it from the meeting card
- **Choosing time for ending each instance**: for ‘ends at’ time selection we provide options for 30 min increments in the user’s local time without any timezone information. Optionally, we could add one more option at the end for 11:59 PM (which breaks the 30 min increment pattern)

**Comment by enriquesanchez** [comment]
Sounds good and reasonable 👍

**Comment by ackernaut** [comment]
@BartoszJarocki [the comment above](https://github.com/ParabolInc/parabol/issues/6073#issuecomment-1092172386) goes a long way at answering how the UI supports editing the meeting meta, especially if it’s a recurring meeting (just FYI)
