### ISSUE TITLE
Designed team prompt activity settings

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6076]
See potential output from #6069 #6073

How can I edit the settings of an open team prompt activity?

### Questions
- Can I update the meeting name? Where? How?
- Can I update the recurring settings?
- Can I update the prompt?
- Can I cancel the activity?
- Is anything else editable? In the future, can we choose another template? Can we update a templated, randomized list or pick another list to drive the meeting? Or do folks have to set up a new actiity?

### Acceptance criteria
- Designed concepts to show how to edit team prompt activities
- Proposed written criteria and reviewed with a designer and developer

### Estimated effort
- 5 hours

**Comment by ackernaut** [comment]
cc @enriquesanchez yet another design issue. Questions? Anything missing?

**Comment by enriquesanchez** [comment]
LGTM 👍

**Comment by ackernaut** [comment]
Turns out I got ahead and did this work in https://github.com/ParabolInc/parabol/issues/6073#issuecomment-1092172386
