### ISSUE TITLE
Sprint Poker: score updates should use facilitator's access token

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6085]
## Issue - Bug

Today the score updates from Parabol to GitHub (maybe Jira too, haven't checked yet) are using the access token from the user who initially added that issue to estimation scope, which results in unexpected audit history. For example, I imported #5927 to our poker meeting last sprint but it was actually Jordan who aggregated the votes and set the final score. It seems weird to see the activity I didn't perform:
<img width="647" alt="Screen Shot 2022-02-18 at 3 58 13 PM" src="https://user-images.githubusercontent.com/1879975/154776239-e524cc66-3d23-40e4-9c4a-0f35dc749695.png">

To repro:
1. Logged in as userA, start a poker meeting, add one GitHub issue to the meeting
2. Switch to userB and logged back to the meeting
3. As userB, set a final score for the GitHub issue
4. Go to GitHub and observe that it would show "userA added the Story Points: XXX"

### Acceptance Criteria (optional)
- [ ] When pushing final scores to integrated services, we should use the access token from the user who actually sets the final score, fallback to the person who scoped the issue on permissions error

**Comment by jordanh** [comment]
Groomed, updated AC

**Comment by Dschoordsch** [comment]
I moved this to backlog as it did not have a squad assigned
