### ISSUE TITLE
Enhancement: Task card dates have the same color labels in the "done" column.

### ISSUE THREAD

**Issue by lorena-cure** [ParabolInc/parabol#6093]
## Issue - Enhancement

After I've completed my tasks in Parabol, the date still shows red as if I haven't completed that task.
Maybe we could change the date color after they're moved to the completed column?

<img width="339" alt="Screenshot 2022-02-22 at 10 03 11" src="https://user-images.githubusercontent.com/97244811/155159889-fc3b7566-0382-46fb-b59f-b175422c291c.png">

**Comment by jordanh** [comment]
EE
- Assert that task styling color by some variant of grey from the Parabol palette when a task is moved to the Done column

AC
- 2 points

**Comment by Shivanshu-09** [comment]
Hi @jordanh @igorlesnenko , Can you assign this to me. 
To resolve this, I am sending one more "prop" to "Toggle" interface, which is "status" of task. 
If the task status is "done" and it is "pastDue" then we will
<img width="1680" alt="Screenshot 2023-05-05 at 1 46 31 AM" src="https://user-images.githubusercontent.com/61676272/236319572-cdd177c0-cf11-4c53-9942-c1896c1ead9d.png">
 show the variant of grey, else we will show red. 
I have tested it locally. If solution seems fine, let me know, will create a PR for review.

**Comment by igorlesnenko** [comment]
@Shivanshu-09 I think you can include `status` directly in the fragment `fragment DueDateToggle_task on Task {` without sending it trough prop.
Also feel free to create a PR with a suggested solution at any time
