### ISSUE TITLE
 Jira Server: List issues in Sprint Poker

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6096]
Needs:
* #5810 
* #5993 
* #5994

## Acceptance criteria
* [ ] Add tab to sprint poker for Jira Server
* [ ] List tasks the user has access to (no pagination, just first 25 results, no user editable search)

**Comment by igorlesnenko** [comment]
Extracted `Allow adding tasks to scope` to a separate task #6158. As does not look straightforward for this integration.
