### ISSUE TITLE
Learning "hub" experience designed

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6099]
[Previous Work:](https://www.notion.so/parabol/In-product-learning-hub-design-b5de909c9c35459dadfe310d1cc80162)

## Issue - Enhancement
To encourage users to run a meeting, looking specifically at:
- How to help them feel safe to click the "start an activity" button
- Promote awareness of integrations with the goal of increasing stickiness
- Create awareness of new features to create stickiness through adoption

### Acceptance Criteria (optional)
Users can:
   - understand what will happen when they click "start an activity" before click it
   - feel comfortable (safe!) with the scary task of facilitating their first meeting in Parabol

**Estimated effort:** 13 points

**Comment by jordanh** [comment]
@acressall any tension putting this on the main Sprint Board? Putting this on its own board makes it difficult for us to groom our issues (unless we update our grooming queries)

**Comment by acressall** [comment]
No tension @jordanh!
