### ISSUE TITLE
Develop IaC to deploy Datadog testing for PPMI instances

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#6102]
As a DevSecOps architect, I want to develop IaC to deploy Datadog testing for PPMI instances

A/C

- [ ] IaC developed to deploy a synthetic UI test to Datadog for PPMI
- [ ] Pipeline created to automated deployment of synthetic UI test
- [ ] Pipeline tested to validate deployment of synthetic UI tests on Customer Staging PPMI

Development constraints

- [ ] Must be developed in Terraform
- [ ] Must be deploy via Gitlab runner
- [ ] Needs to be reusable with vars

Useful information/starting point

- This repo for your development workspace https://gitlab.com/parabol1/parabol-iac/iac-playground/datadog-synthetic-test-iac
- This TF provider https://registry.terraform.io/providers/DataDog/datadog/latest/docs
- Here's the TF example for synthetic tests https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test
- Test endpoint will be <fqdn>/intranet-graphql
- Will need to post present request body `{"query":"query {\n  pingActionTick\n}","variables":null,"isPrivate":true}` with body type application/json
- Will need request header `content-type` of `application/json`
- Will need request header `X-Application-Authorization` of `Bearer {TOKEN}`
- Here is a currently configured test in datadog https://app.datadoghq.com/synthetics/details/4bd-8ap-qbx?live=1h
- Example test in TF https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#example-usage

**Comment by adaniels-parabol** [comment]
Tossing this one over to @jchandler-parabol to knock out.

**Comment by adaniels-parabol** [comment]
**Story points: 13**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/7) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by adaniels-parabol** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/8) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by jordanh** [comment]
@adaniels-parabol I am iceboxing this one — but noting that it seems to be a good idea if we keep popping up PPMIs. Please reopen if you are so moved
