### ISSUE TITLE
Unable to integrate task with GitHub

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6120]
When trying to integrate a task with GitHub, I get the following error in prod & master: `There can only be one variable named "assigneeLogin"`

I can still successfully integrate a task with Jira.

![task-gh-bug](https://user-images.githubusercontent.com/39854876/155332171-0ecd64e0-7c5d-4b14-9c0a-78c24af346fa.png)

### AC

- [ ] Able to integrate a Parabol task with GitHub

**Comment by nickoferrall** [comment]
I can reproduce this bug when using v0.4.0 and beyond of `nest-graphql-endpoint`. v0.3.3 works for me. 
@mattkrick perhaps you recognise the issue (could be [this commit](https://github.com/ParabolInc/nest-graphql-endpoint/commit/6718618c0104013b6c8cc388d529536cad3264c2))? I'd be happy to dig into the package in more detail.

**Comment by mattkrick** [comment]
on prod i can get an error, but not that error. can you give some more detailed steps to reproduce or a loom?

**Comment by nickoferrall** [comment]
@mattkrick here's a Loom where I can reproduce the error: https://www.loom.com/share/34d2a4b67dd24b93b84cd0435618d98f

Interestingly, I was able to integrate with the Parabol repo and create an issue ([this one](https://github.com/ParabolInc/parabol/issues/6123)), but I run into the bug whenever I try to integrate with public repos that belong to me.

**Comment by mattkrick** [comment]
perfect! can reproduce, will push a fix soon

**Comment by jordanh** [comment]
Fixed!
