### ISSUE TITLE
Azure DevOps: integration provider 

### ISSUE THREAD

**Issue by bobjac** [ParabolInc/parabol#6124]
Azure DevOps Services supports both OAuth 2.0 and Personal access tokens (PAT) to make authenticated calls to their REST Api.  Azure DevOps Server is hosted on-premises and supports personal access tokens, but does not support OAuth 2.0.    Choosing OAuth 2.0 or a PAT toke has its own pros and cons affecting the user experience of both the Parabol user and the Azure DevOps administrator.  The choice of authentication mechanism also determines the preferred client libraries which abstract away the authentication protocol.  Detailed guidance on choosing the right authentication mechanism can be found [here](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops).

#### Pros

- Supported with both Azure DevOps Services and Azure DevOps Server
- Slightly simpler setup for Azure DevOps administrator
- Supports fine-grained scopes in support of least prilege
- Eliminates need to Parabol end-user login and consent

#### Cons

- User-level RBAC for Azure AD user's are not honored. The PAT token connects to Azure DevOps as a third-party service/application as opposed to an organization user, i.e. "A Parabol user is calling a REST Api" as opposed to "bob@myorg.com is calling a REST Api".
- PAT tokens must be managed and secured like passwords
- PAT tokens expired / refresh process must be implemented

#### Pros

- Typically preferred by Organizations that use Azure Active Directory as it supposed RBAC at the user level
- Credentials aren't distributed and expiration/refresh do not need to be accounted for

#### Cons

- Additional configuration steps required on Azure DevOps and Azure Active Directory side
- User login and consent required before accessing REST API
- Multiple versions of REST API and client libraries - documentation can be confusing

## Acceptance Criteria

- [x] Confirm authentication with @[Dschoordsch](https://github.com/Dschoordsch) mechanism best suited for version 1 of Azure DevOps integration
- [x] Add adoServer to `IntegrationProviderServiceEnum`
- [x] Add `oauth2` and `pat` to `IntegrationProviderAuthStrategyEnum`

**Comment by Dschoordsch** [comment]
I have a few questions
> ### PAT
> [...]
> * Supported with both Azure DevOps Services and Azure DevOps Server

Does that mean OAuth 2.0 is not supported by DevOps Services?
> [...] 
> * Eliminates need to Parabol end-user login and consent

Do you imagine that the team lead adds the integration with his PAT and it is reused by all team members?

> ### OAuth 2.0
> [...]
> * Multiple versions of REST API and client libraries - documentation can be confusing

Do you mean with both options OAuth 2.0 and PAT it is more confusing?

I propose going with the option mainly used by your cloud offering customers. I assume that would be OAuth 2.0 but you probably have better data on that.

I also took the freedom to update the type names as these were probably just outdated in the other issues.

**Comment by bobjac** [comment]
> I have a few questions
> 
> > ### PAT
> > [...]
> > 
> > * Supported with both Azure DevOps Services and Azure DevOps Server
> 
> Does that mean OAuth 2.0 is not supported by DevOps Services?
> 
> > [...]
> > 
> > * Eliminates need to Parabol end-user login and consent
> 
> Do you imagine that the team lead adds the integration with his PAT and it is reused by all team members?
> 
> > ### OAuth 2.0
> > [...]
> > 
> > * Multiple versions of REST API and client libraries - documentation can be confusing
> 
> Do you mean with both options OAuth 2.0 and PAT it is more confusing?
> 
> I propose going with the option mainly used by your cloud offering customers. I assume that would be OAuth 2.0 but you probably have better data on that.
> 
> I also took the freedom to update the type names as these were probably just outdated in the other issues.

OAuth 2.0 is supported by the cloud-hosted Azure DevOps Services.  It is not supported in Azure DevOps Server, which is the on-premise hosted version.  You can see the note called out at https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops.

In our experience, Azure DevOps Services is more commonly used and OAuth 2.0 is the preferred approach taken for user impersonation.  PAT tokens are normally used for automated daemon processes or build pipelines.

**Comment by bobjac** [comment]
@Dschoordsch - We are implementing the OAuth2.0 for the cloud service.  That implementation is part of the PR, but I am not marking any tasks as complete until they are merged into the master branch.  I just wanted to confirm this is how you wish we proceed.

**Comment by Dschoordsch** [comment]
@bobjac Yes, that's how we're doing it here. When you think you're done implementing and ready for review, the task move along the board to reviewer review.

**Comment by bobjac** [comment]
These was implemented and pushed to the master branch.
