### ISSUE TITLE
Jira Server: implement `stateToJiraServerFormat`

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6130]
Predecessor: #6059

Jira Server uses its own format for the issue description.
It is something like a mix of markdown and wiki format: https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all

Here is the example:

```
*bold text*

{color:#de350b}red text{color}

_Italic text_

[link title|http://example.com/]
 * list 1
 * list 2
 * list3

h2. Heading
{quote}quote paragraph

quote line 2

quote line 3
{quote}
 

{{preformatted}}

-strike-

~subscript~
```

We need to implement a converter from DraftJS format to Jira Server format.
We can support the most common formatting for now.

### Acceptance Criteria (optional)

- [ ] Implement `stateToJiraServerFormat` and use it to preserve the text style, when pushing an issue to Jira Server
- [ ] Support only links, bold, italic, blockquote

**Estimated effort:** 8h

**Comment by jordanh** [comment]
Groomed!
