### ISSUE TITLE
Error on updating final score value of Jira issue

### ISSUE THREAD

**Issue by elielytz** [ParabolInc/parabol#6132]
## Testing summary
In a sprint poker meeting after the participants completed voting on Jira issue, and the facilitator decides to edit the final score value of Jira issue. There is error notification popped followed by field configuration assistance. 

**"you do not have this field configured in Jira"** notification persists even after following integration assistance instructions.

https://user-images.githubusercontent.com/45159239/155720262-be52d0c6-094c-4c80-b54b-9d4f2f9f4729.mp4

### How to reproduce
(I simulated this with 2 participants)
- Start Sprint Poker Meeting
- Scope section: Here you can select few issues
- Estimate section: Vote for the issue, and as facilitator reveal and edit story value score
- Change Jira issue field

**Comment by Dschoordsch** [comment]
I think this is an issue if the user does not have enough permissions in Jira, needs retesting as an admin or similar.
Slightly related to: #5508

**Comment by jordanh** [comment]
AC
- When user has insufficient permissions to fix field configuration, display a more helpful message than "insufficient permissions"
   - i.e. tell them what action to do instead
   - optional (and perhaps an example of a Jira admin they should contact)

EE
  - 3 hours

**Comment by elielytz** [comment]
thanks, @Dschoordsch for the suggestion I am working on it. In case there will be any clarification on permission issues I will reach out
