### ISSUE TITLE
Sprint Poker: what to do when a user wants to use Jira fields we don't support

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6133]
A [user](https://app.hubspot.com/contacts/3888472/contact/65666201) 🔒 writes:

> I set up a single-select field (T-shirt estimate) with values of S,M,L,XL in Jira to capture Parabol estimates. It didn't show up in the field list in parabol. I created a copy of this field, but as a text field, and that field showed up in the list. How do I get the single-select field to show up in the available fields list? I'd like to constrain the types of t-shirt sizes people can select in Jira by using a dropdown/single select rather than an open text field.

**Comment by igorlesnenko** [comment]
Probably, a single select field has a type other than string and number that we support
https://github.com/ParabolInc/parabol/blob/872f802fb6407ba681593e9058fae33e7c89cf76/packages/server/utils/atlassian/jiraFields.ts#L1

**Comment by jordanh** [comment]
To tackle this issue:

1. Set up a single-select field (T-shirt estimate) with values of S,M,L,XL in Jira to capture Parabol estimates
2. Setup up a template in Parabol that will use a dimension with cards S,M,L,XL
3. Create test issues
4. Try to update this field via Sprint Poker, observe error

AC
-  Investigate error from above, generate new issue to implement enhancement
- Or, implement enhancement directly if trivial

EE

- 5 hours

**Comment by jordanh** [comment]
@drewhousman1010 we'll need to enhance the product to support this field type. I will prioritize on our backlog

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/65744451/) 🔒 says: 

> We have required fields in Jira that Parabol doesn't support

**Comment by jordanh** [comment]
This is going to come back again. I can feel it
