### ISSUE TITLE
Remove LogRocket

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6135]
Now that we're using DataDog's session replays, we no longer need LogRocket. We've already stopped paying for LogRocket, so let's remove the relevant code.

### AC

- [ ] Remove LogRocket from the codebase

**Comment by jordanh** [comment]
@nickoferrall if you haven't already, you might want to add this to the Planning meeting

**Comment by nickoferrall** [comment]
Sure thing, added!

**Comment by Dschoordsch** [comment]
I'm not going to remove `isWatched` now as this could also be used with DataDog going forward.

**Comment by mattkrick** [comment]
fixed in #6266
