### ISSUE TITLE
Azure DevOps: Azure DevOps PAT Token Flow

### ISSUE THREAD

**Issue by bobjac** [ParabolInc/parabol#6136]
Azure DevOps has two ways of authenticating the use of their REST Api's:

- Personal Access Token (PAT)
- OAuth 2.0

OAuth is the preferred authentication method, but it is only supported by the cloud-hosted Azure DevOps Services.  For the on-premise hosted Azure DevOps Server, the only option will be to support the Personal Access Token (PAT) flow.

A personal access token is a simple alternative to OAuth 2.0.  Detailed instructions on creating and using a personal access token can be found at https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Linux.

## Flow 

- integration row must be added when the org/team is provider set up
- personal access token configured in integration provider
- personal access token must and Azure DevOps Tenant information must be configured in Parabol server
- for personal access tokens, no popup authentication is required

### Acceptance Criteria 

- [ ] new query `getPersonalAccessToken`
- [ ] modify mutation `addIntegrationToken` to support Personal Access Token
- [ ] Azure DevOps integration row added if team/org has integration provider
- [ ] Azure DevOps client manager which handles PAT flow

**Comment by jordanh** [comment]
Groomed!
