### ISSUE TITLE
Azure DevOps: Rest Manager

### ISSUE THREAD

**Issue by bobjac** [ParabolInc/parabol#6137]
## Acceptance Criteria

- [x] create `AzureDevOpsRestManager`
- [ ] create new `AzureDevOpsTaskIntegrationManager` and add to `TaskIntegrationManagerFactory`
- [ ] create `AzureDevOpsIssueId` and store on the `Task`
`integrationHash: JiraServerIssueId.join(providerId, projectId, issueKey)
integration: {
  accessUserId
  service
  providerId
}`

**Comment by Dschoordsch** [comment]
You mean you need to send it as 'application/x-www-form-urlencoded'? In that case I would just make a different helper, there is probably not enough code in common to justify abstracting the function to have two entry points, one for json and one for urlencoded. If it's just the response, then fixing the 'Accept' header and parsing the response depending on content type would be the way to go.

**Comment by bobjac** [comment]
Correct.  It needs to be sent as 'application/x-www-form-urlencoded.  I slightly modified the authorizeOAuth2 function to remove the hardcoding of Content-Type of 'application/json'.  Instead I check the incoming headers for "Content-Type" and use whatever is passed.  If nothing is passed, I set it to application/json to remain backwards compatible.  

The rest of the functionality, is in different ServerManager classes and isolated from what is currently in the codebase.  

You can see the changes in the feature/6125/ado-integration branch.  

If you have any suggestions for change/refactor, please let me know.  Would be happy to get on a pair programming session to work through it.

**Comment by bobjac** [comment]
This was merged to the master branch.
