### ISSUE TITLE
Sprint Poker: GitLab v1: New Search Input UI

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6138]
Predecessor: https://github.com/ParabolInc/parabol/issues/6046

In Jira and GitLab, the only way to see the project filters is to open the project filter menu:

![image](https://user-images.githubusercontent.com/39854876/156038846-7ba18b5e-5026-4a73-ae9a-12ebf363c5aa.png)

Instead, let's show the current project filters under the search input. While we're here, we can improve the UI by adding a border to the search input and making the filter button blue to draw more attention to it:

![image](https://user-images.githubusercontent.com/39854876/156039138-4a631d7c-1348-4a33-a5b2-f1110da6fcfe.png)

Note: we don't need to add the current filters in the GitHub integration as the search query already includes the repos we're filtering by. See discussion here: https://github.com/ParabolInc/parabol/issues/6088

### AC

- [ ] In all Sprint Poker integrations, the search input has a border and the filter menu has a blue background like the image above
- [ ] In Jira & GitLab integrations, list the current filters below the search input
- [ ] If there are many filters and there's not enough space to list them all, show `... and 9 more` at the end of the line
- [ ] The GitHub integration does not include the "current filters" text as users can see the selected repos in the search query

**Comment by mattkrick** [comment]
https://user-images.githubusercontent.com/5514175/156233871-1dc1a6f1-6cd0-4fc2-947b-986915d84161.mov

**Comment by nickoferrall** [comment]
^ that screen recording is the functionality that I suggest we tackle in this issue: https://github.com/ParabolInc/parabol/issues/6047

**Comment by nickoferrall** [comment]
**Story points: 13**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/11) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by nickoferrall** [comment]
**Include in next sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/12) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
