### ISSUE TITLE
Hover over avatar to see names not working for some users

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6139]
A [user](https://app.hubspot.com/contacts/3888472/contact/64282151) 🔒 wrote in saying they couldn't see names when hovering over avatars in a poker meeting. 

> I can't see who has joined the meeting. All I see in the upper right corner are initials and when I hover over I can't see their names. I've asked the team to put up profile photos for now which helps.

@tianrunhe [said he was having issues seeing avatar names in retros too. ](https://github.com/ParabolInc/parabol/discussions/6110#discussioncomment-2238520)

**Comment by 87prashant** [comment]
![Screenshot 2022-08-03 171841](https://user-images.githubusercontent.com/106697681/182600609-4f30000c-5b82-4f33-ab87-d98c063a8467.png)

Are you talking about here? The below one is working for me though.
Btw, I am not able to see any name on hover in any meeting.
