### ISSUE TITLE
Retrospective voting: indicate when every active participant voted

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6141]
As a facilitator of a retrospective it is difficult to judge when everybody had voted on an issue, especially when the meeting was opened for asynchronous participation before. There are currently 2 indicators for the facilitator to see if everyone voted:
* "Team Votes" counter
* progress circle on "Next" button

As a participant if I don't want to use all votes I press the "Ready" button to indicate I'm done.
If I used all votes I may or may not press the "Ready" button.
I might have added reflections but I'm not in the meeting right now.

In this case the facilitator will see a partial progress circle on the "Next" button and remaining votes, both showing voting is not ready yet.

## Acceptance criteria
* [ ] If a user presses ready, their remaining votes are subtracted from team votes
* [ ] If a user used all their votes, we mark them as ready
  * [ ] some different animation may be used to notify them that we changed the state for them
* [ ] Offline users' votes are subtracted from "Team Votes" and not considered in progress circle on "Next"
* [ ] Total votes including offline users and non-voters are shown grayed out in parenthesis with tooltip so async voting can still be performed sensibly

**Comment by JimmyLv** [comment]
>  some different animation may be used to notify them that we changed the state for them

This animation should have been implemented in #6815.

> Offline users' votes are subtracted from "Team Votes" and not considered in progress circle on "Next"

The idea of excluding Offline users' votes is awesome, I didn't even think of it before.
