### ISSUE TITLE
Bug: billing leader NOT reassigned if the current one's account is deleted

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6144]
## Issue - Bug

If the user is the billing leader for an org and his/her account is deleted, the org will have no billing leaders and no one else in the org can claim that. 

We should fix it.

### Acceptance Criteria (optional)
- [ ] When a billing leader's account is deleted, reassigning the role to someone else in the org

**Comment by jordanh** [comment]
Keeping this one open
