### ISSUE TITLE
Updated design of empty state for threads

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6147]
Today we use an older illustration in the empty state of the thread. Our illustrator has [a new one following the updated visual direction](https://parabol.slack.com/archives/C01BFF6J36H/p1645105507753909) and it’s pretty 🔥 IMO. In addition to the illustration there’s some copy and an arrow. Open questions:

- Do we keep the same copy? Do we style it differently? (note the difference; in Sprint Poker we don’t have tasks enabled, in Retros we do)
- Do we keep the arrow? Does it match the style of the illustration>?
- Do we do something different?

### Acceptance criteria
- Proposed a new empty state design that handles both Sprint Poker (without the ability to add tasks) and Retro/Check-In use cases (with the ability to add tasks)
- Wrote design criteria as a comment on this issue and reviewed with a designer
- Optional: asked a developer to write an implementation issue
  - Note: this is a good candidate for a ‘UI enhancement issue’ and a designer could write it and do it using their front-end dev hat)

### Estimated effort
- 3 hours

![image](https://user-images.githubusercontent.com/307286/156262307-7703f31a-2a86-4e8d-9368-af53e40606f7.png)
<img width="369" alt="Screen Shot 2022-03-01 at 16 43 32" src="https://user-images.githubusercontent.com/307286/156262285-82e5f925-8979-483f-8f29-67daf71f7eae.png">
<img width="396" alt="Screen Shot 2022-03-01 at 16 44 02" src="https://user-images.githubusercontent.com/307286/156262287-42d3fdc6-71f8-4244-a899-31f3c82418ec.png">

**Comment by acressall** [comment]
Related implementation task #6177

**Comment by avivapinchas** [comment]
Is there a plan to move forward on this or prioritize it? This issue and illustration have been done for ~6 weeks. Unless we have currently active work to make changes here, I would like to get this illustration out there

**Comment by ackernaut** [comment]
I’ll add it to sprint poker and see where it falls

**Comment by ackernaut** [comment]
@enriquesanchez this is up for grabs for either squad. If you don’t want it, I can take it

**Comment by enriquesanchez** [comment]
I'll take this one 👍

**Comment by enriquesanchez** [comment]
This is the direction I'm exploring on #6423. I've decided to remove the tangled arrow since the style is a bit different, and with the new illustration being a little more visually complex, I didn't want the empty state to feel heavy.


<img width="387" alt="Captura de Pantalla 2022-04-19 a la(s) 5 15 41 p m" src="https://user-images.githubusercontent.com/3276087/164113909-1575cc71-f22e-4322-ac6a-87eb5798470f.png">

**Comment by ackernaut** [comment]
LGTM!

**Comment by enriquesanchez** [comment]
Closed by #6423
