### ISSUE TITLE
Refactor AnalyticsPage

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6149]
AnalyticsPage has gotten a little messy by adding extra services here & there.
It'd be nice to refactor & get things looking clean, but it's a tricky mess because we need to make sure we send the _exact_ same messages with the same metadata to segment as we do currently. 
Work has been started here but that PR was deprioritized so we could focus on sprint work: #5991

AC
- [ ] guarantee that segment page & identify events (seen in devtools XHR as p & i, respectively) are sent is the same order as they were previously. Below are a few example scenarios
- [ ] be logged out, goto /, then log in, make sure segment events are in the same order with the same payload as before
- [ ]  be logged in, goto a meeting, check for the same
- [ ] accept an invite while logged out, check for the same
- [ ] accept an invite while logged in, check for the same

Estimate: 8 hours

**Comment by jordanh** [comment]
@mattkrick any sense of priority for when you'd like to get this done?

**Comment by mattkrick** [comment]
low priority for sure. it's currently working, so until we have a reason to go in there & add something new it causes no tension
