### ISSUE TITLE
kkkkkk

### ISSUE THREAD

**Issue by lehoangquan88** [ParabolInc/parabol#6156]
### Pre-submission instructions (remove me before creating an issue)

- [ ] Decide is this is a bug or an enhancement request (if you can't decide, join the chat in [slack](http://slackin.parabol.co/) and ask in `#general`)
- [ ] I've checked open (and closed!) issues and made sure that the feature request doesn't already exist.
- [ ] I've completed the Enhancement section below
- [ ] I've deleted this checklist section before I hit submit

## Issue - Enhancement

[Describe why the feature is AWESOME and would make Action SUPER AWESOME]

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
Closing as it has no content.
