### ISSUE TITLE
Consider hierarchical dataloaders to provide better types

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6165]
There's a piece of code that makes a little sad:

```ts
const provider = await parent.get('integrationProviders').loadNonNull(token.providerId)

        const manager = new JiraServerRestManager(
          provider.serverBaseUrl!,
          provider.consumerKey!,
          provider.consumerSecret!,
          token.accessToken!,
          token.accessTokenSecret!
        )
```

we shouldn't have to do non-null coercion on all those keys because we know that the provider is a IntegrationProviderJiraServer.

I propose the following:

1. create a loader for each of the types:

```ts
  | IntegrationProviderMattermost
  | IntegrationProviderGitLabOAuth2
  | IntegrationProviderGitLabPAT
  | IntegrationProviderJiraServer
```

2. each of those dataloaders then calls the existing `integrationProviders` loader internally
3. before returning, those loaders validate that provider.service is what it says it is. it returns null if it's not.
4. `integrationProviders` is either not available directly (treated like a private dataloader) OR when it fetches rows, it primes the specific dataloaders with the data

curious what you think @Dschoordsch

**Comment by Dschoordsch** [comment]
Yes, that bit of code is not ideal, but it's out of context
```ts
  const auth = await dataLoader
          .get('teamMemberIntegrationAuths')
          .load({service: 'jiraServer', teamId, userId})
  if (!auth) return
    const provider = await dataLoader.get('integrationProviders').loadNonNull(auth.providerId)
    const manager = new JiraServerRestManager(
          provider.serverBaseUrl!,
          provider.consumerKey!,
          provider.consumerSecret!,
          auth.accessToken!,
          auth.accessTokenSecret!
        )
```
So instead of having a hierarchical loader for the provider, we should have a loader for 'teamMemberJiraServerAuths' which also returns the provider with the correct type. We almost always need the provider when loading the auth itself.
