### ISSUE TITLE
Button hover styling mismatched on the /me/profile page

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#6169]
## Issue - Bug

- **How serious is the bug?** P4
- **OS:** macOS
- **Browser:** Chrome

https://user-images.githubusercontent.com/4997466/156768067-8cf7c549-0a70-412c-9bd6-ec667e089437.mp4

### Acceptance Criteria
Users can:
   - see the full button shadow effect with the correct padding when hovering (`/me/profile` page)
   - see UI consistent with other buttons on all pages

Root cause: The current button on the profile page does not have enough padding when hovering, so the shadow effect is obscured.

![correct button padding when hover](https://user-images.githubusercontent.com/4997466/156767234-75d630f1-50d5-4f1a-867a-3b39a29b6d24.gif)

**Estimated effort:** <1 hour

**Comment by jordanh** [comment]
This is a real, real old section of the product—that's why. Keen eye for catching this sir!

Going to prioritize toward the end of the backlog, but since it is so trivial if you feel like fixing just do it whenever the mood strikes you
