### ISSUE TITLE
Sprint Poker, scope issue search only shows 1 GitHub repo

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6175]
### Reproduction steps
- Create a new team on a new test organization
- Open a Sprint Poker session
- Add GitHub
- Open the filter menu in the upper right
- Try searching for some other repository. I can only see the one
- Note: when integrating a task card I see a lot of repositories (see below)

![2022-03-04 14 03 09](https://user-images.githubusercontent.com/307286/156834500-1b4579d6-7ef2-4d07-aceb-f4676e66c23c.gif)

![2022-03-04 14 13 37](https://user-images.githubusercontent.com/307286/156835143-e7299e90-9936-46ce-a85a-19803c76f922.gif)

### Acceptance criteria
- Triaged this issue (is it just me?)

### Estimated effort
- 1 hour

**Comment by jordanh** [comment]
^ All these label changes were me testing a new workflow
