### ISSUE TITLE
Illustration update: empty discussions thread

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6177]
## Issue - Enhancement

We've got a new illustration for the discussion thread empty state! 🎉  [Saved here.](https://drive.google.com/drive/folders/1Cp6E8FXzamwdEkcfXt-hEyQ5hYYf3Vhs) 

### Acceptance Criteria (optional)
Users can enjoy the new illustration ✨ 

fyi @acressall 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by acressall** [comment]
Dependent on #6147

**Comment by enriquesanchez** [comment]
Closed by #6423
