### ISSUE TITLE
Facilitator can visit a stage without moving team members to that stage

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6179]
Currently, if a facilitator would like to visit a Check-In stage, Discuss stage, or Estimate stage, the rest of the team will be taken to that stage. 

If the facilitator wants to take a sneak peek at a stage, it would be nice if they had the option of not dragging the rest of the team with them. 

When the viewer is not the facilitator, there is an icon next to the facilitator's name:

<img width="257" alt="Screenshot 2022-03-07 at 17 26 19" src="https://user-images.githubusercontent.com/39854876/157086230-08129302-9981-4374-bf9e-36d34db1468d.png">

Perhaps we could add the same icon when the viewer is the facilitator? They could open a menu that gives them the option to visit a stage without changing the active stage of other meeting members.

### AC:

- [ ] Design created for the above functionality

**Comment by Dschoordsch** [comment]
Maybe you can drop the facilitator role without assigning a new one. This might make sense in async scenarios?
