### ISSUE TITLE
Replace Deprecated Scopes in Jira Integration

### ISSUE THREAD

**Issue by lora-reames** [ParabolInc/parabol#6180]
https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-517
> ## Deprecation Notice Scopes for Forge and OAuth 2.0 (3LO) apps
> The original OAuth scopes for Forge and OAuth 2.0 (3LO) apps on Confluence Cloud, Jira Cloud platform, and Jira Service Management Cloud are deprecated.
> 
> All Forge and OAuth 2.0 (3LO) **apps must use the new scopes by 23 August 2022 PDT / 24 August 2022 AEST**. After this date, only apps using the new scopes will function as expected, as the original scopes will have been removed.

Parabol currently uses the following [deprecated scopes](https://developer.atlassian.com/cloud/jira/platform/scopes-for-oauth-2-3LO-and-forge-apps/#deprecated-scopes):
- 'read:jira-user'
- 'read:jira-work'
- 'write:jira-work'
- 'manage:jira-project'

**Comment by lora-reames** [comment]
found this while working on https://github.com/ParabolInc/parabol/issues/6153

**Comment by Dschoordsch** [comment]
@igorlesnenko you mentioned you've read the deadline moved? Could you update the description?

**Comment by igorlesnenko** [comment]
Yeah, they paused this change
https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-603

> On 22 February, we announced the [availability of new scopes for Forge and OAuth 2.0 (3LO) apps](https://community.developer.atlassian.com/t/action-required-update-scopes-for-forge-and-oauth-2-0-3lo-apps/53299). Following concerns raised by our developer community, we have now paused the deprecation of classic scopes and removed the requirement to transition your app to new scopes by 23 August 2022.

> There is no action for you to take regarding your app scopes at this stage. Apps using either classic or new scopes can continue to do so. For those that haven’t adopted new scopes yet, please continue using classic scopes – we’ll let you know when you can start transitioning.

**Comment by jordanh** [comment]
Good to know! It is still coming up, but we can safely kick the can down the road just a little while longer...
