### ISSUE TITLE
REST architecture for inbound integrations spec'd

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6185]
From our [SPA 18 discussion](https://www.notion.so/parabol/Day-2-Flow-of-Consciousness-brainstorming-24999cdf8d474cbdbf3c3395d1e15cfd)

## Use cases
* Create cards from github actions
   - Create either integrated or Parabol card
* Add a label and the task comes to your board
* some issues for current potential use-cases
  - https://github.com/ParabolInc/parabol/issues/6113
  - https://github.com/ParabolInc/parabol/issues/6114
  - https://github.com/ParabolInc/parabol/issues/6081

## REST vs. public GraphQL
While GraphQL would fit into the current architecture better, it would make it much more difficult to use it for above mentioned integrations. REST would make that much easier.

## Authentication
Since one of the main use cases is automation which often doesn't support OAuth we should go with PAT.
A user should be able to create and name multiple PATs so it is possible to revoke these per application.

### Authorization
Authorization is handled by loading the user from the DB each time. Unlike the JWT we use for user authorization today, the PAT cannot be regenerated each time the user changes teams etc. Thus we need to load the user from DB. This is not a big bottleneck since we need to load the PAT as well to verify it.

### PAT table
- id
- name
- tokenHash
- valid ← tokenHash IS NOT NULL
- userId
- createdAt
- expirationDate
- lastUsed

### User actions
User can
* create and name a token which is visible once (only hash is stored)
* refresh a token which replaces the existing one with a new one which is visible once
* delete a token which marks it as invalid by setting tokenHash to NULL
* when a user is deleted we mark their token as invalid
* Maybe in the future make PATs reassignable?
  - do not reassign automatically because this might assign blame to someone

## Potential tensions
- PAT is shared and therefore a card could be created with your PAT that is offensive in some nature or malicious e.g. something you wouldn’t normally create a card about
- Should only certain level users billing leader/team leads have ability to create tokens?
- Should we possible restrict it to enterprise users?

## Traceability
Actions done via user's integration should be distinguishable from actions done by the user directly because the token might be used in automation which is shared for more people.
We don't need to add more tracing than we have right now. If we store currently that an action was done by a user (e.g. `createdBy` field in `Task`) then this should be associated with the integration (i.e. `patId`). There are two possibilities:
1) Adding a Bot-User per PAT which is associated with its creator
  * *Pro*: It can be easily linked to the actions taken
  * *Con*: It might break all user related code like listing team members, billing etc.
2) Adding an extra field where we currently store the user
  * *Pro*:
    * low risk of breaking existing code
    * easier to understand
    * can be done one by one while adding REST endpoints
  * *Con*
     * needs to be done for all associated fields
     * can be forgotten

Winner is **2**

### First REST endpoints
* creating `Task`
  * add field to `Task`: createdViaIntegration → PAT table
* viewing, listing, deleting, updating `Task`
  * the rights should be the same as right now, i.e. all team members can delete tasks
* creating meetings
  * needs possibility to list templates as well

### TODO
* How to use existing resolvers
* Which technology to use? Swagger/OpenAPI?
* How do the REST endpoints look exactly?

**Comment by mattkrick** [comment]
I see 2 issues:
- data transport (REST vs GraphQL)
- Becoming an identity provider (allowing other apps to use parabol on behalf of a user)

For the first issue, I see there's some pain with using GraphQL. I'd like to better understand why GraphQL is causing this pain.

> Create cards from github actions

GitHub tutorials encourage the usage of their GraphQL endpoints instead of using REST. 
https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects

For the second issue, it's just a really, really big thing. it'd take 3+ months to become an identity provider. I'd suggest we just use OAuth2 to improve the UX so the app's users don't have to go into parabol & copy & paste keys, which is no fun, especially on mobile. I'm not opposed to it, but it's just a massive undertaking.

**Comment by adaniels-parabol** [comment]
Without using some sort of token based authentication, how would you handle more command line access to Parabol to make cards, like pipeline?
