### ISSUE TITLE
Standup UI - Top Bar - Meeting title

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6198]
Design - https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1138%3A72617

AC
- [ ] The meeting name is autogenerated and not editable yet - ‘Async Standup 1’ the count goes up
- [ ] It’s in the upper left at any breakpoint

**Comment by mattkrick** [comment]
fixed in #6336
