### ISSUE TITLE
Migrate GitHub Integration to a GitHub App

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6208]
GitHub offers 2 ways to integrate: GitHub App & OAuth.
Today, we use OAuth because it's cheap & light.

A GitHub App allows for fine-grained controls over which repo they want to let parabol look at. That's good.
Plus, it means GitHub (the company) could use us 🎉 

AC
- [ ] Create a GitHub App & get it working locally
- [ ] Find out what changes we'll have to make & write issues to make sure it works
- [ ] Write a migrations issue (it may just nuke all existing GitHub integrations)

Estimate: 8 hours

**Comment by mattkrick** [comment]
Removing stale flag since this unlocks more usage with our github integration. We'll probably want to do this before we invest anything else into the github integration

**Comment by jordanh** [comment]
Scrubbed again, going to icebox for now
