### ISSUE TITLE
Retrospective: Voting: Show Votes left + Ready for present people

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6210]
This tension hits every meeting we're in, but i wasn't sure how to solve it.

For example, a retro has 10 people, but only 3 present. It shows 85 votes left.

I think it'd be best to show something like "85 Team Votes (0 from Users present)"
Similarly, the green ring show be present folks, but we have a second ring that shows present + offline.

AC
- [ ] Designs created to show both connected & total for votes & ready button

Estimate: 8 hours

**Comment by Dschoordsch** [comment]
Similar to #6141 , we should only do one of those

**Comment by ackernaut** [comment]
There are [a few ideas here](https://github.com/ParabolInc/parabol/issues/4672#issuecomment-827694157) around clarifying who has voted, who’s not around, etc.

@enriquesanchez had explored updated patterns around this as well. See #5275 and #5274

**Comment by jordanh** [comment]
Iceboxing this by policy. We've also already iceboxed all related issues.

My hope is as we continue to enhance the product for more async use-cases, that we implement a general pattern that can be back-ported to our previous activity types...
