### ISSUE TITLE
Unable to select all issues in Poker

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6213]
When selecting all issues in Poker, only one is added to the Estimate phase and one "Unknown Story" is added. See gif:

![buggy-select-all](https://user-images.githubusercontent.com/39854876/158602047-b74abbfa-e55a-44a7-a6e2-decc75818363.gif)

If I refresh the page, the issues are visible in the Estimate phase, so there might be a problem with the `UpdatePokerScopeMutation` updater.

The same behaviour happens for GitHub issues, Jira issues, and Parabol tasks. 

### AC

- [ ] Clicking "Select All" successfully adds all issues to the Estimate Phase, and their titles are visible in the sidebar

**Comment by JimmyLv** [comment]
I think this is the same issue as https://github.com/ParabolInc/parabol/issues/6384?

**Comment by nickoferrall** [comment]
Yep, that's right. I'll close #6384
