### ISSUE TITLE
Placeholder: Implement initial editable prompt view for standups

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6216]
**This issue is currently in placeholder state. Needs implementation input from a developer**.

Follows design proposal from https://github.com/ParabolInc/parabol/issues/6069

# Initial editable prompt view for standups

![imagen](https://user-images.githubusercontent.com/3276087/158704968-294fc452-9867-4a54-8d3f-cc8becc9d964.png)

**Goal:** Users can access a view where they can edit the initial prompt for standups

### Estimated effort

**Comment by jmtaber129** [comment]
Closing in favor of https://github.com/ParabolInc/parabol/issues/6584 and https://github.com/ParabolInc/parabol/issues/6585
