### ISSUE TITLE
Add dismiss button to snackbar messages

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6218]
Currently, our snackbar messages look like this:

<img width="434" alt="Screenshot 2022-03-15 at 08 24 49" src="https://user-images.githubusercontent.com/3276087/158708397-ace52180-a4c6-4a5c-87c6-2c247571dcf2.png">

While the message and CTA are pretty clear, I find that there is no obvious way to dismiss them. We currently support clicking anywhere on the snackbar to remove them, but there are two issues with this approach:

1. Not everyone knows this (I didn't!), since there is no visible affordance that indicates it. 
2. Because focus cannot be placed on the snackbar itself, they can only be dismissed if you are using a mouse or touch input device. Keyboard-only users have not much of a choice.

Snackbars are also intended to [disappear automatically](https://material.io/components/snackbars#behavior):

> Snackbars appear without warning, and don't require user interaction. They automatically disappear from the screen after a minimum of four seconds, and a maximum of ten seconds.

But in our case, it stays in view until clicked on.

I don't mind having them stay in view, it makes sense given the type of messages we are using them for. But I think **we can improve the interaction if we add a close/dismiss button to them**.

This is similar to what GMail is doing:

<img width="363" alt="Captura de Pantalla 2022-03-16 a la(s) 10 45 26 a m" src="https://user-images.githubusercontent.com/3276087/158709360-0e7e5b95-dc85-41b7-a6be-ee997deca6b9.png">

For us, it could look like this:

<img width="600" alt="Captura de Pantalla 2022-03-16 a la(s) 10 45 26 a m" src="https://user-images.githubusercontent.com/3276087/158710712-8742bd14-0726-46fd-bc34-20506bf871dc.png">

- The puzzle piece emoji (or any emoji we may use in the future) is relocated to the start of the text. This anchors the eyes, but also brings visual balance to the whole component.
- The `Learn more` button maintains its primary CTA status by visually standing out more than anything else.
- The close button is visible, but does not steal any attention from the message nor the primary CTA.

### Acceptance criteria
- Users can dismiss a snackbar via a visible affordance (dimiss button)

### Estimated effort
(Needs input from a developer)

**Comment by enriquesanchez** [comment]
One thing I havent'd made up my mind about is if we keep the current behavior for dismiss the snackbar (clicking anywhere), or do we only allow dismissal via the new `x`button.

Would love to hear what others think.

**Comment by DrASK** [comment]
Clicking anywhere to dismiss the snackbar seems surprising from the POLA perspective. And it's also: click anywhere **not** near the _Learn More_ text.  I would abandon the current behavior.

**Comment by enriquesanchez** [comment]
>Since the buttons don't have a clear outline, I wonder if folks would click one or the other by accident?

This is a good point and you make great suggestions, thank you @avivapinchas 🙌

Here's a mockup adding a background color to the `Learn more` button. It makes the boundaries more distinct, and also raises the visual prominence. I like it!

![imagen](https://user-images.githubusercontent.com/3276087/159560902-d8a1e1ac-08d4-459e-836c-d9f6e7c745db.png)

**Comment by 87prashant** [comment]
Hi everyone, Anyone working on this?
Can I work on this?

**Comment by enriquesanchez** [comment]
@87prashant Hi! And yes, looks like you can work on this! Thank you 🙏

**Comment by 87prashant** [comment]
Thanks @enriquesanchez, I just wanted to confirm a few things:

Do we need a close button for all snackbar messages?
e.g.
![Screenshot 2022-06-21 000922](https://user-images.githubusercontent.com/106697681/174735028-f010e3b1-9ee1-4e8b-9f1f-369e534fa77a.png)

Also, is there any svg/png files directory for the "cross" icon?

**Comment by enriquesanchez** [comment]
> Do we need a close button for all snackbar messages?

Ideally yes. The user should always be in control of these types of components. The only case where I think it would be OK to NOT have a dismiss button is if the snackbar goes away automatically after a few seconds. But even in that case, having a dismiss button does not hurt and instead gives the user more control.

Does that make sense?

>Also, is there any svg/png files directory for the "cross" icon?

I believe we use the` Material Icons` icon font in our repo. Are you able to find it?

**Comment by ackernaut** [comment]
We have a few snack bars that show to billing leaders when their account requires attention. If I recall correctly, they go away with user interaction but will come back on the next load, or after 3 minutes. This is because we require their attention to the matter. If there were to be a closing X on the control, I think the requirement would remain they same. The snack bar will appear constantly until appropriate actions are taken.

I share this use case because it ties in to our business logic. I vote that if we develop a pattern to add the X control it should be optional per use case, and may need to be flexible enough to not prevent snack bars from reappearing if some logic requires that they show again later.

If the snack bar goes away within a timely manner I think we can forgo adding yet another button. I would not recommend touching every existing snack bar in the code base as a refactor. I think if this pattern is available to us we can add it in as the need arises (e.g. adding new workflows that include snackbars, or addressing user feedback on existing snackbars).

**Comment by 87prashant** [comment]
@ackernaut what I get is that we should not use the close button on the snackbars that go away without interaction
Is that right?

**Comment by 87prashant** [comment]
Ok 
I don't think I changed the logic (in PR) of snackbars for reappearing.
If it was working previously then it should work now as well.
