### ISSUE TITLE
Jira task integration menu is not showing all projects first time

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6220]
## How to reproduce
Janin is integrated with Jira and GitHub, goes to the task dashboard and refreshes Parabol.

### Expected behaviour
Janin can push tasks to Jira straight away

### Actual behaviour
First time the menu is opened, it does not show the Jira repositories
![Jira repo not shown first time](https://user-images.githubusercontent.com/7331043/158763875-5a915d6c-21ea-42b1-83b8-852c8b6f0d90.gif)

**Comment by Dschoordsch** [comment]
Root cause was the same as #6221

**Comment by Dschoordsch** [comment]
I was wrong, I can still reproduce it on master. Both GitHub and Jira integrations seem to be needed to reproduce this.

**Comment by jordanh** [comment]
Duplicate of #5756, I believe

**Comment by jordanh** [comment]
@Dschoordsch could we close this and #5756 now. Were these fixed by #6221?

**Comment by MindEvo** [comment]
@Dschoordsch Tested this on prod. Jira repos would show on first menu click. Unable to reproduce the bug.
