### ISSUE TITLE
Standups: Improve copy in team prompt how-to-steps 

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6224]
+1 having the verb be "share" for both of these feels weird.
Feel free to wordsmith a little

CC @ackernaut

_Originally posted by @mattkrick in https://github.com/ParabolInc/parabol/pull/6082#discussion_r828505333_

**Comment by enriquesanchez** [comment]
Closing since the "old" meeting lobby is now being replaced by the new one, where we don't include how-to steps.
