### ISSUE TITLE
HubSpot properties: active teams instead of registered teams

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#6225]
Our Growth team relies upon a property called `active_team_count` – it appears as though we are actually setting this value to the number of registered teams

On the Growth team today they know this, and treat it like like registered teams. Well, they almost all know this: new folks and candidates don't and it leads to some pretty awful interactions with prospective customers. ("we do _not_ have 18 active teams!)

AC
   - when HubSpot properties are updated, `active_team_count` should be set to the number of teams who have held a meeting in the past 30 days

**Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
moving back to Backlog as it has no squad assigned

**Comment by Dschoordsch** [comment]
@tianrunhe are you working on this now outside of the sprint?

**Comment by tianrunhe** [comment]
@Dschoordsch Yes I'm working on it. I don't know the best way to track it though. I have a PR requesting @nickoferrall to review so I guess I could put it in squad 1's board so you guys can see? I'm happy to work in whatever way that suits better for you!

**Comment by Dschoordsch** [comment]
I think going forward you will work on more issues. Maybe you just invent a label "analytics" or similar so we can filter those out? We can then also remove the issues from the sprint boards until they are in review. Unless you're churning out dozens of PRs a week, I think that would be good enough. You don't need to assign a squad since tickets without one are visible to both.

**Comment by nickoferrall** [comment]
@tianrunhe sorry, I've had a bunch of review requests lately and this one slipped through the cracks. I've added [this bookmark](https://github.com/ParabolInc/parabol/pulls?q=is%3Apr+is%3Aopen+user-review-requested%3A%40me) to my browser so I have a list of PRs awaiting my review. 

I should get to it tomorrow!
