### ISSUE TITLE
Jira Poker cannot change field when using others integration

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6229]
## How to reproduce
Jasmin has Jira integration and Fridolin is the facilitator in a Sprint Poker meeting. Jasmin adds a task and both vote on it. Fridolin tries to select a field to push the score.

### Expected behaviour
The facilitator can change the field even if he did not add the integration

### Actual behaviour
Changing field is not possible
![Poker vote cannot change field Jira](https://user-images.githubusercontent.com/7331043/158986111-df184fc4-0486-4b1a-a796-1eac807f8986.gif)

**Comment by tianrunhe** [comment]
Are Jasmin and Fridolin characters  from somewhere? Sounds much more fun than Alice and Bob
