### ISSUE TITLE
Sprint Poker - Updated Final Score *cleared/removed/deleted/overwritten* from DL of CSV

### ISSUE THREAD

**Issue by WWP-Apalmer** [ParabolInc/parabol#6241]
I found a glitch with Sprint Poker - when I went to download the results - it wasn't storing the updated final scores - does show count of votes - it seems this happens if I use any feature beyond just voting and updating the total score per dimension. So if I chose to 'revote' on a dimension - all the dimensions voted on prior to that one were overwritten or deleted even though a final score was chosen and update was clicked - csv files attached.

- **OS:** Windows 10
- **Browser:** Chrome
[ParabolPoker_WWP CRM Coordinating Council_2022-3-18 (3).csv](https://github.com/ParabolInc/parabol/files/8306600/ParabolPoker_WWP.CRM.Coordinating.Council_2022-3-18.3.csv)
[ParabolPoker_WWP CRM Coordinating Council_2022-3-18 (2).csv](https://github.com/ParabolInc/parabol/files/8306601/ParabolPoker_WWP.CRM.Coordinating.Council_2022-3-18.2.csv)
[ParabolPoker_WWP CRM Coordinating Council_2022-3-18 (1).csv](https://github.com/ParabolInc/parabol/files/8306602/ParabolPoker_WWP.CRM.Coordinating.Council_2022-3-18.1.csv)
[ParabolPoker_WWP CRM Coordinating Council_2022-3-18.csv](https://github.com/ParabolInc/parabol/files/8306603/ParabolPoker_WWP.CRM.Coordinating.Council_2022-3-18.csv)

**Comment by jordanh** [comment]
Steps to try and reproduce this:

1. Start a Poker meeting that uses multiple dimensions
2. Add items to scope phase
3. Vote on an item and each dimension to different scale values
4. Revote on the final dimension
5. End the meeting
6. Download CSV file

Check: Did the final revote overwrite the values of the other dimensions?

**Comment by jordanh** [comment]
Going to keep this one open to see if we can reproduce, otherwise we will close it.

@WWP-Apalmer sorry this has taken us so long to get to!

**Comment by jordanh** [comment]
Closing this one as we haven't reproduced it. @WWP-Apalmer please let us know if this is still occurring for you and we'll reopen it and look more deeply at it
