### ISSUE TITLE
Jira Server advertisement for manual setup added to team integrations route

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#6269]
## Issue - Enhancement

When Jira Server v1 ships, we won't have a mechanism for folks to add Jira Server themselves, they'll have to contact us so we can add the provider for them.

We should make this job story as easy as possible:

>  When want to see if Parabol supports Jira Server, I want to see it in the list and have a clear means to add it, so that I can try it out and get going

I suggest we add a ProviderRow to the Integrations page with a CTA that take folks to our contact page with a pre-written subject line to add Jira Server. From there, we can build a relationship with folks and perhaps ask them to sign a trial agreement

### Acceptance Criteria (optional)
Users can:
   - Discover we have Jira Server on the Integrations page
   - Click a button to navigate to a place they can contact us, such as: https://www.parabol.co/contact/?subject=[Jira%20Server]%20Add%20Request

**Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@Dschoordsch this is something @igorlesnenko and I spoke about during our 1:1. Do you think this makes sense to add to our v1 epic?

**Comment by Dschoordsch** [comment]
**Story points: 13**
  [See the discussion](https://action.parabol.co/meet/chrwZ1fHoc/estimate/1) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
Yes, I think it does.
