### ISSUE TITLE
TypeError: _ is undefined

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6277]
99 events, 84 users

https://sentry.io/organizations/parabol/issues/2608089376/?referrer=github_plugin

```
TypeError: _ is undefined
  at c (./packages/client/components/PokerCardDeck.tsx:57:19)
...
(8 additional frame(s) were not displayed)
```

> Cannot destructure property 'scale' of '_' as it is undefined.

```
const isVoting = localStage.isVoting
const {scale} = dimensionRef
const {values: cards} = scale
const totalCards = cards.length
```

**Comment by jordanh** [comment]
Possible related to #6278 ?

**Comment by jordanh** [comment]
AC
   - Triage in time allotted & fix, else open a new issue

EE 1 hour

**Comment by mattkrick** [comment]
closing in favor of #6247. It's the same bug, just a different message depending on the browser (this message only occurs on firefox &  edge it seems)
