### ISSUE TITLE
GitHub Poker: Show "Powered by Parabol" when creating a new issue

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6281]
After voting on an issue in Sprint Poker, we add a comment that says "Powered by Parabol". When creating an issue from Parabol, I see an empty comment. This could be a bug or perhaps we haven't added this functionality. See below:

![powered](https://user-images.githubusercontent.com/39854876/160107729-84612f1a-ff0c-4262-9b84-3bab824428d7.png)

When users create a new GitHub issue from Parabol, we should add "Powered by Parabol" in the description to spread the good word. 

It looks like we don't add a "Powered by Parabol" comment to Jira issues, so perhaps this functionality isn't possible yet. I suggest starting with GitHub and GitLab.

### AC

- [ ] When a user creates a new GitHub issue from Parabol, "Powered by Parabol" is included in the description
- [ ] When a user creates a new GitLab issue from Parabol, "Powered by Parabol" is included in the description

**Comment by Dschoordsch** [comment]
@nickoferrall we have commenting capabilities for Jira, maybe it only appears when voting to a comment? We add a comment for example if an issue was pushed using someone else's credentials. I put it in a comment in this case as I felt it's not part of the ticket content. You may disagree, but at least we should have it somewhat unified.

Do we add a comment right now when voting to a label?

When we put it in the description, it will appear also back in Parabol when reading out the issue. So we might want to filter it.

**Comment by nickoferrall** [comment]
> Do we add a comment right now when voting to a label?

Yeah, in GitHub, when we finish voting, we add that comment in the screenshot in the description. 

In Jira, I was expecting to see a comment in the issue at the end of this gif:

![Untitled_ Mar 25, 2022 1_12 PM](https://user-images.githubusercontent.com/39854876/160127458-010d1516-20f3-44c3-9050-527b74a7969c.gif)

If you agree with the UX, I can create an issue to add "Powered by Parabol" as a comment to the Jira issue after voting?

> When we put it in the description, it will appear also back in Parabol when reading out the issue. So we might want to filter it.

True! Could add that as an optional AC? As a user, I'd prefer the description to exactly match what we see in GitHub, but I can see why you'd prefer to only see relevant content.

**Comment by jordanh** [comment]
@nickoferrall I hope you don't mind that I added this to the GitLab v1 milestone?

**Comment by jordanh** [comment]
Related: #6287
