### ISSUE TITLE
Replace `createFragmentContainer` with `useFragment`

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6283]
`createFragmentContainer` is deprecated and should be replaced with `useFragment`.
See [Partial data](https://www.parabol.co/blog/upgrade-react-to-graphql-relay-hooks/) for details.

Use the codeshift automation described in the [migration doc](https://www.notion.so/parabol/How-to-Migrate-createFragmentContainer-useFragment-with-codeshift-d534e7d0b8674089a2075f2835544558) to update most of the instances to the hook.

## Acceptance criteria
* [ ] find all occurances of `createFragmentContainer` and replace them with `useFragment`
  * [ ] move `fragment FooBar ...` from `createFragmentContainer` into `useFragment`
  * [ ] replace parameter of type `FooBar` with `FooBar$key` and pass to `useFragment`
  * Example: https://github.com/ParabolInc/parabol/commit/0cb19afc1043501a55a990e3a838c1792840e1bb
* [ ] remove occurances of `UNSTABLE_renderPolicy: 'full'`

**Comment by jordanh** [comment]
Could we divide this into smaller issues? Perhaps re-write the AC to 1) discover all the places to refactor 2) open issues to break this refactoring into chunks?

**Comment by jmtaber129** [comment]
My 2¢ as I'm currently doing a similar (but at a much smaller scale and with less complexity) HOC->hook migration for `withAtmosphere` - there's currently **276 occurrences** of `createFragmentContainer(`, so ~226 components need to be migrated.  **This is a _lot_ to change manually** (it took me the better part of an hour to manually migrate 20(!) React class components to function components - a supposedly trivial migration in most cases), **so I would _strongly_ recommend automating this via something like jscodeshift**.  Even if we decide to approach this primarily through "in the neighborhood" refactoring, we should try to automate most of this to **reduce the friction associated with changing one of these components** - I don't want an engineer to have to take the time to read a doc on this to figure out how to manually perform the migration.  I'd rather engineers just be told "**run this script if you're changing a component with `createFragmentContainer`**, then go do whatever changes you want on that component".

**Comment by jmtaber129** [comment]
FWIW I have some interest in picking this up (it's been a while since I've [played with Babel+ASTs](https://heap.io/blog/how-we-leveraged-asts-and-babel-to-capture-everything-on-react-native-apps) [shameless plug] and I've been meaning to check out jscodeshift), though I may not have capacity for a few sprints.

**Comment by jordanh** [comment]
@jmtaber129 I think building some AST jscodeshift chops could be real, real nice. Discuss on your squad or pick up during a slack week!

**Comment by jmtaber129** [comment]
(reopening since the closing PR only added automation to assist this effort; the AC still needs to be executed)

**Comment by jordanh** [comment]
Was about to icebox, but I think we've done most of the work here to automate this migration. Will keep open a bit longer.

@jmtaber129 please let me know if you'd like to add anything to this Issue so that we prioritize it or decide to close it

**Comment by jmtaber129** [comment]
Yea, all the automation is implemented, we just need to actually apply it.

I'll probably run a few batch migrations in the next few weeks, so let's keep it out of the icebox
