### ISSUE TITLE
inject gifs based off certain keywords in the reflection text entities e.g. "teamwork"

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6284]
drop a list of gifs with their keywords in the comments below.

e.g.
teamwork: https://media.giphy.com/media/1MayKbFuSKE1O/giphy.gif

i suggest both gify & tenor as platforms to search for SFW content

**Comment by jordanh** [comment]
If you don't get the joke, we should explain it if your culture doesn't understand April fools

**Comment by jordanh** [comment]
"Happy April Fools"

**Comment by enriquesanchez** [comment]
https://en.wikipedia.org/wiki/April_Fools%27_Day

**Comment by jordanh** [comment]
Closing as the day has passed. Next year?
