### ISSUE TITLE
Show warning when switching away from a branch with a migration

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6286]
When switching development branches with migrations, it is easy to forget to run the down migration before checking out another branch, which can mess up the local database.

## Acceptance criteria
* [ ] if local branch has migration not present on target branch, alert the user
* [ ] (optional) stop the checkout until the user confirms the previous warning "Your current branch has additional migrations which you might want to run down, do you want to continue with the checkout?"​

**Comment by jordanh** [comment]
@Dschoordsch and I discussed. He wants to keep it open. He says, with confidence, "I will do it during slack week." 😉
