### ISSUE TITLE
Upgrading to Pro no longer shoots confetti

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6297]
Upgrading to Pro used to show the upgrade success modal & shoot off a confetti cannon.
This positive user feedback is important to our overall feel (plus the success modal means yes, it did it fact work when you put in your CC number)

AC
- [ ] after upgrading to pro (CC 4242424242424242) the confetti cannon shoots off & the success modal is shown

Estimate: 2 hours

**Comment by Dschoordsch** [comment]
Worked last release

**Comment by mattkrick** [comment]
🤔 perhaps there's a race condition? i noticed the mutation took around 6 seconds, perhaps a timeout somewhere?

**Comment by mattkrick** [comment]
creating a stripe customer: 1 second
creating a stripe subscription: 3 seconds
every other async call is < 50ms, so i'm not sure we can speed this up any
