### ISSUE TITLE
Unsupported unicode characters

### ISSUE THREAD

**Issue by borisyordanov** [ParabolInc/parabol#6302]
## Issue - Bug

- **How serious is the bug?** P4
- **OS:** Windows 10
- **Browser:** Chrome 99

### Acceptance Criteria (optional)
Windows users:
   - Do not see "LSEP" characters
   
It appears this issue is scoped to the WordPress instance on parabol.co. It's a common problem that has several solutions:
- https://stackoverflow.com/questions/39603446/why-is-this-lsep-symbol-showing-up-on-chrome-and-not-firefox-or-edge
- https://stackoverflow.com/questions/41555397/strange-symbol-shows-up-on-website-l-sep

![chrome_lBjTotFfY0](https://user-images.githubusercontent.com/12392666/160620064-fc8da2bd-22e7-4726-b045-4972a045e7ba.png)

**Comment by jordanh** [comment]
Thank you for the bug report. We re-opened this on our internal marketing website backlog. We'll hope to fix it soon!
