### ISSUE TITLE
Unable to create a new Jira issue in Poker

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6320]
When creating a new Jira issue in Poker in prod, I can enter the title but the new issue doesn't submit when pressing enter or clicking outside of the input. I can see in the network requests that the mutation hasn't been executed. 

It does work in GitHub and Parabol.

![create-jira-issue](https://user-images.githubusercontent.com/39854876/161032714-298d684e-e4c1-4ad8-adde-d37141658ba0.gif)

### AC

- [ ] Can create a new Jira issue in Poker

**Comment by jordanh** [comment]
Hey @MindEvo could you please try and reproduce this one to see if it is still an issue? If so, I will prioritize it a bit higher

**Comment by MindEvo** [comment]
During my attempts to reproduce this bug I discovered that I was able to make it appear after making and creating a/the 5th Jira push (see video) during the Sprint Poker scoping. I tested this on both Brave, Chrome and Firefox however the latter would show the bug on the 3rd push.

Loading the Atlassian Project board and viewing the issues appeared to reset everything. After viewing I could push new issues before one random push would show the bug again.

https://www.loom.com/share/1a85de2e4a054a6c945ad52de4377ab7

**Comment by jordanh** [comment]
I wonder if there is some kind of API metering? Perhaps related to #7896?

**Comment by jordanh** [comment]
This issue came up during a scrub. I see it hasn't been prioritized yet – if this is a p2, we should get this in the next sprint. @avivapinchas, @nickoferrall, could you please consider prioritizing this one?

**Comment by jordanh** [comment]
Scrubbed again. @avivapinchas would you be able to prioritize this one for your next sprint?

**Comment by avivapinchas** [comment]
We have [4 P2 bugs in process currently in this sprint](https://github.com/orgs/ParabolInc/projects/13/views/6). I don't believe we should have more than ~3-4 bugs that we're taking on per sprint, so we can focus on feature work as well. 

If all or most of these bugs are closed, then we can take this one into the next sprint, but I'd like to keep it at a limit of ~2 new bugs we're pulling in and no more than ~4 total in the sprint.
