### ISSUE TITLE
Sprint Poker: GitLab v1: Can vote on an issue

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6322]
### AC

- [ ] In the Estimate phase of a Poker meeting, a user can successfully vote on a GitLab issue

**Comment by Dschoordsch** [comment]
@nickoferrall can you please add your estimate until we can vote in a poker meeting?

**Comment by nickoferrall** [comment]
@Dschoordsch sure, as in add my estimate as a label to this issue?

**Comment by nickoferrall** [comment]
**Story Points: 8**
  [See the discussion](http://localhost:3000/meet/curomvzm0g/estimate/4) in Sprint Poker #​​32

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by nickoferrall** [comment]
**Story Points: 8**
  [See the discussion](http://localhost:3000/meet/curomvzm0g/estimate/4) in Sprint Poker #​​32

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
