### ISSUE TITLE
feat(DX): rewrite newMutation yarn script to support new pattern

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6324]
Even with the new SDL-driven architecture, there's still a lot of boilerplate.
We should automate as much of that as we can.

AC
- [ ] calling `yarn newMutation` creates a typeDef file, a resolver, a permissions entry, and does all the client stuff it does today.

Estimate: 5 hours

**Comment by ackernaut** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/13) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
**Include?: Y**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/14) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
@ackernaut I don't mind you claiming this one, but technically "Refactor GraphQL SDL" ended up in Squad: 1

**Comment by mattkrick** [comment]
ah, that's my bad. i'd call it more DX instead of SDL.
