### ISSUE TITLE
Sprint Poker: GitLab v2: Refactor nested issues query

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6325]
In Poker, we want to show users their GitLab issues. However, the GitLab API offers a `projects` query but not an `issues` one. So, we're currently querying their most recently updated projects and getting the issues in those projects.

One problem with this is when the user scrolls down, we want to render more issues. As we can't have nested connections, we have to increase the number of projects being loaded which isn't what the user necessarily wants. 

See the discussion issue here for more context: https://github.com/ParabolInc/parabol/issues/6272

### AC

- [ ] For the initial fetch, use the projects API with a set number of issues & projects. it can't be increased. if gitlab returns an error, we tell the user to pick a project from the dropdown menu. Scrolling to the bottom does nothing.
- [ ] When the user has at least 1 selected project, we call the project(id) API instead, since that returns a single object. we map over the fitleredProjectIds and trigger a new query for each. Put a @connection on the issues field in this refetchable query
- [ ] When the user scrolls to the bottom, we call loadMore(20) to load 20 more issues on each. This will be a noop if all the issues have already been fetched for a given project since hasNextPage will be false
- [ ] The results from each of the queries is flatmapped together, just like today

**Comment by jordanh** [comment]
Out of curiosity, could this perhaps be broken down into smaller issues?

**Comment by nickoferrall** [comment]
> Out of curiosity, could this perhaps be broken down into smaller issues?

Yes, I have an idea on how I could break this into two PRs. My current approach:

We need to loop through the selected project id filters and execute multiple `project` queries. From the returned project queries, we need to flatMap the issues within those projects. As a lot of data manipulation is required, I think we should add a field called `projectIssues` to `GitLabIntegration` so that the server does this rather than the client each time. On the client, we would also have to loop through an array and call a Relay hook query, which would break the rules of hooks.

`projectIssues` will be a connection data type so that we can add a refetchable argument to the query. This will allow us to increase the `first` argument as the user scolls down the page, meaning that more issues will render as they scroll.

While it would be preferable to query the GitLab API directly from our frontend, as there's no `issues` endpoint, I think this is the best bet. 

One way that I could potentially break this down into smaller PRs is to implement `projectIssues` on the server in one PR. In a second PR, I could add the logic where a user scrolls and new issues render.
