### ISSUE TITLE
feat(sdl): fix args implicit any in sdl resolvers

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6327]
For a reason I'm not 100% sure of, when `files: {}` is included in the tsconfig, then `args` in sdl resolvers is implicitly of type any instead of what they should be. 😕

Now that eslint configs have been sorted out, we should be able to safely tackle this one. 

AC
- [ ] refactor enableSAML to have optional args. Typescript throws warnings that the args are optional

Estimate: 8 hours

**Comment by ackernaut** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/11) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
**Include?: Y**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/12) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by Dschoordsch** [comment]
@ackernaut I don't mind you claiming this one, but technically "Refactor GraphQL SDL" ended up in Squad: 1

**Comment by ackernaut** [comment]
@Dschoordsch do you still want to move this to squad 1? do you want to include it in sprint 100?

**Comment by Dschoordsch** [comment]
@ackernaut if you have open capacity feel free to keep it in squad 2

**Comment by ackernaut** [comment]
Okay, I understand it to be a DX related issue, so should be fine
