### ISSUE TITLE
`Minified exception occurred` error in poker meeting

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6334]
Some users see the following error during their poker meetings with the Jira integrations:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/466991/161308188-611f7c93-262b-4778-9db0-5da5142a423a.png">

See sentry for additional information:

https://sentry.io/organizations/parabol/issues/?environment=server&environment=client&project=107196&query=minified&statsPeriod=14d

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/466991/161308805-6b4d7f2e-1ef7-423c-9223-66d1bc58ebbe.png">

### Acceptance Criteria (optional)
- [ ] Triage is performed to find the root cause of the bug
- [ ] The error is fixed and does not prevent user to add Jira issues to the poker scope 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by nickoferrall** [comment]
I think this issue might be fixed by https://github.com/ParabolInc/parabol/pull/6439/files

@Dschoordsch perhaps we can put this issue back on the backlog and check it again when #6439 is in prod? If you agree, I'll take a task to check this issue once my PR is merged

**Comment by Dschoordsch** [comment]
I could reproduce `RelayRecordProxy#setLinkedRecord(): Expected a record, got `undefined`.` prior #6439

**Comment by Dschoordsch** [comment]
I can still reproduce it on master by adding/removing issues or all issues to sprint poker. It is preceded by the warning
```
Warning: A store update was detected within another store update. Please make sure new store updates aren't being executed within an updater function for a different update.
```
on the console
