### ISSUE TITLE
Fresh new quotes in the Upgrade now page

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6345]
When folks are about to upgrade, we show a random quote from a customer.
This is our little way of saying, "it's OK to give us your money, you can trust us" .
We haven't updated the quotes in a LOOONG time.
Let's get some quotes, avatars, and permission from some of our great users.

Here's what it looks like today
![Screen Shot 2022-04-05 at 8 08 17 AM](https://user-images.githubusercontent.com/5514175/161785992-354bc53d-f157-44f5-88eb-c847e56731cd.png)

AC
- [ ] A notion doc with a handful of new quotes including name, avatar, company name, and quote

Estimate: 4 hours

**Comment by avivapinchas** [comment]
Latest quotes are on the homepage: https://www.parabol.co/ No need to create another doc. 

I'll say here what I said on Slack: F I don't think it's worth the work to update this in the app. Very few folks even look for, let alone find the upgrade flow, and I'm not sure how motivating the quotes are. I'd rather redesign that flow when we decide to prioritize organic upgrades.

**Comment by jordanh** [comment]
I think this will get "fixed" as Squad 2 does its work this trimester
