### ISSUE TITLE
Update Relay to v13

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6347]
## Issue - Enhancement
There's a new version of Relay that we should upgrade to: https://github.com/facebook/relay/releases/tag/v13.2.0 

Packages to update: `relay-runtime`, `react-relay`, `babel-plugin-relay`. In addition, check if we still need `@types/relay-runtime` and `@types/react-relay`

### Acceptance Criteria (optional)
- [ ] relay compiler still works
- [ ] application still works 

**Estimated effort:**
8h

**Comment by ackernaut** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/17) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
**Include?: Y**
  [See the discussion](https://action.parabol.co/meet/chorM4RmGA/estimate/18) in PS2 Poker 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by JimmyLv** [comment]
Just revisited this issue and Relay v14 has been released, https://github.com/facebook/relay/releases

**Comment by jordanh** [comment]
What do you know? We did this! We just didn't close this issue :)
