### ISSUE TITLE
Poker: Estimate: Links in header cards don't open in new tab 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6351]
Links in an issue should open in a new tab when they're clicked.
To do this, I think we'll have to intercept the HTML coming in from github/jira & attach a `_blank` to the anchor tag, but that's just a suggestion. How you decide to do it is up to you.

AC
- [ ] when I click a link in an Estimate Header card for a github or jira issue, it opens in a new tab

Estimate: 4 hours

**Comment by Dschoordsch** [comment]
Duplicate of #6194
