### ISSUE TITLE
Burndown - Async Standup v2

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6369]
TODO: figure out the scope of v2 milestone

**Comment by ackernaut** [comment]
- **Editing name**: for our current meetings, a user can’t edit the activity name until after the meeting is started. So what we could do first is decide if folks are editing the series name, or each meeting name, and then add the UI where it makes sense (maybe from the meeting card, or inline in the UI — these are the latest contenders). We have to decide if editing the name affects all meetings retroactively or just the meetings moving forward.
- **Editing prompt**: there’s a push to be able to do this inline. I think we just need to agree on if editing the prompt affects the whole series and how, retroactively or just moving forward?
- **Basic chat notifications**: at this point I’d say we could include the ability to opt in to basic start and stop chat notifications only for one-time activities. Later if folks choose to repeat they could opt in to a reminder and summary chat notification
- **Summary card**: I think this is simple enough, we can include one when a one-time activity is closed. We need to figure out how to end the one-time meeting, from the meeting card, or the activity view

If I could only pick one I’d go for the editable prompt. If we wanted a smaller milestone I’d say we could defer the chat notifications and only do editable name, prompt, and the ability to end the meeting and see a summary card

**Comment by ackernaut** [comment]
[See my latest work here](https://github.com/ParabolInc/parabol/issues/6073#issuecomment-1092172386), which might give an idea of where we’re headed with designs

**Comment by BartoszJarocki** [comment]
> Editing name: for our current meetings, a user can’t edit the activity name until after the meeting is started. So what we could do first is decide if folks are editing the series name, or each meeting name, and then add the UI where it makes sense (maybe from the meeting card, or inline in the UI — these are the latest contenders). We have to decide if editing the name affects all meetings retroactively or just the meetings moving forward.

here I think the real question is how we think about the meeting series. i personally think it's more an implementation detail and the user should not be concerned about having 'multiple' meetings. from that perspective, it's a single meeting so IMO it's ok to assume that editing the name would edit the _series_ name. 

 > Editing prompt: there’s a push to be able to do this inline. I think we just need to agree on if editing the prompt affects the whole series and how, retroactively or just moving forward?

my take here is, the prompt should be editable _per meeting_. i imagine this could be useful for the following situation. you create a standup meeting for the whole month/year and it'd be nice to be able to ask different question sometimes. 

> Basic chat notifications: at this point I’d say we could include the ability to opt in to basic start and stop chat notifications only for one-time activities. Later if folks choose to repeat they could opt in to a reminder and summary chat notification

sounds good!

> Summary card: I think this is simple enough, we can include one when a one-time activity is closed. We need to figure out how to end the one-time meeting, from the meeting card, or the activity view

we already can end it, see the overflow menu of the `Async Standup` card. we did it so we won't have many meetings just bloating the dash

![CleanShot 2022-04-08 at 08 37 09](https://user-images.githubusercontent.com/1017620/162378648-f06a2573-b1c0-4a26-a0c3-779dfbe6afbb.gif)
board while we test it.

regarding the scope, as this is a milestone i think we need more than one. all 4 sound good to me!

**Comment by ackernaut** [comment]
@BartoszJarocki the output of this design issue ([see comment](https://github.com/ParabolInc/parabol/issues/6073#issuecomment-1092172386)) can inform the parts that make the next milestone, but also some things are deferred. My latest on this:
- We defer editing the meeting series name until we develop the meeting series object that supports recurring instances
- We include editing the prompt in this milestone (this could be deferred, but I’m not sure what we’re getting beyond v2)
- We make sure threads are at parity and have the content at the top (it seems most of threads were included in milestone 1, yes?)
- Anybody can end the meeting from the meeting card (which is already done; I see this behind the feature flag)

So I’m not sure what we’re scoping this to, just an editable prompt and response cards?

In general I think scoping down milestones is great, but it’s helpful to articulate a goal. For this next milestone is the goal that anybody behind the feature flag could have an end to end experience, even if the components are fully featured? I.e. I can open an async standup, folks can add cards and thread, folks can end the meeting.

When do we add the summary cards on the timeline? Is this done?

**Comment by ackernaut** [comment]
@BartoszJarocki I think we should propose the milestone. Do we want to make a proper GH milestone that includes a burndown issue? We can check with squad 2 and product manager for questions, comments, and objections. Let me know if you want more attention from me. I can sync on it, too! Happy to pair work, I think you’re doing a good job tracking this.

**Comment by BartoszJarocki** [comment]
@ackernaut I think it's a good idea to have some sync time. regarding milestones, I've already created the next two, so we have a place for moving things around. 

V2 - https://github.com/ParabolInc/parabol/milestone/129
V3 - https://github.com/ParabolInc/parabol/milestone/130 

My idea with this issue was to scope V2, move everything else to V3 (and then, do the same with V3, move everything else to V4...). I'll propose things I think makes sense, considering all the data from this thread and the current progress, so we can discuss.

**Comment by jordanh** [comment]
Grooming. Marking this as `discussion` to not come up on my query

**Comment by BartoszJarocki** [comment]
Closing as we don't really use it anymore
