### ISSUE TITLE
Use single GraphQL type for all task integrations

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6374]
Following up on the discussion here: https://github.com/ParabolInc/parabol/pull/6214#discussion_r840881317

Currently, our API exposes separate types for different issue integrations, with a different set of fields. 

**Example:**

```
 ... on JiraServerIssue {
  __typename
  issueKey
  summary
  descriptionHTML
  jiraUrl: url
}
... on _xGitHubIssue {
  __typename
  number
  title
  bodyHTML
  url
}
```

However, the UI for all integrations looks identical and requires the same set of data.

**This leads to the following issues:**

- More additional work to add a new integration. 
- Every time we need to edit many places to spread `...NewIntegrationType` and write logic that would map integration fields to component props 
- Fragments will grow endlessly as we add new integrations

**Example:**

https://github.com/ParabolInc/parabol/blob/75eb07960df21901961f2c7d6a25e61a88651698/packages/client/components/PokerEstimateHeaderCard.tsx#L25-L54

This seems like redundant work.

**How I imagine It could work in an ideal world:**

- Adding a new task integration type requires only exposing new data on the API
- We only edit frontend to add a new visual appearance based on `type` field: `'jira' | 'github'`

**Possible solutions:**

**1)** Create additional unified fields that would be aliases for existing fields. For example have a common `summary` field for all integration types, that resolves to different fields.

Does not work well because of the issue discussed here: https://github.com/ParabolInc/parabol/pull/6214#discussion_r840881317

> No way to tell the client that the 2 fields were the same.

So we always need to maintain 2 fields of different names on a frontend to make cache and updater work correctly.

**2)** As suggested here https://github.com/ParabolInc/parabol/pull/6214#discussion_r840881317:

> I think the right way to do it is by adding that field on the client, not the server, via a clientSchema extension. Then, you can have a client resolver that resolves 1 value to the other. If this sounds interesting to you, you can experiment with it, the details on how to do it are here: https://relay.dev/docs/guided-tour/reusing-cached-data/filling-in-missing-data/

My common concerns here: 

* It feels like it would be easier if the backend just exposes "ready to use" fields. Imagine we created a native iOS app, it will require reimplementing the same mappings again. 
* We still need to write many fragments
* If we allow access to both alias and original field, it feels that now we have 2 source of thruth. Is there a reason to have both? Could it be confusing?

**3)** Have a single `TaskIntegration` type that exposes the same set of fields for all integrations. 
- Use `type: 'jira' | 'github'` on a frontend for selecting the correct styling.
- Expose as much as possible from API, for example, we can expose "name: 'GitHub'" to automatically build link titles.
- Try to unify fields as much as possible. For edge cases, we can expose something like `TaskIntegration.remoteTask` that will resolve to a specific type, e.g. `JiraServerIssue`.

**Comment by Dschoordsch** [comment]
If we go with 3), couldn't we just move more fields from `JiraServerIssue`, `JiraIssue` etc. into the interface? So we have all the commonly used fields in the interface with unified naming and we can still query the exact types for extra information if necessary?
