### ISSUE TITLE
Standups: Analytics

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6385]
## Issue - Enhancement
TODO

### Acceptance Criteria (optional)
TODO

**Estimated effort:** 4h

**Comment by BartoszJarocki** [comment]
@ackernaut @enriquesanchez currently we don't track pretty much anything standups related, are there any particular events you guys would like to see handled?

**Comment by enriquesanchez** [comment]
Oh, this is great @BartoszJarocki 🙌

I'm going to mention all that come to my head right now, so a few of these might be too much and you can totally ignore me. Would also love to hear @ackernaut's ideas.

1. Number of standups created
2. Number of team members in a standup
3. Number of responses added to a standup
4. How often do standups repeat (recurrence settings, what are the most common days when teams hold standups)
5. Number of responses with comment threads
6. Number of responses with reactions
7. How much content is added to standups (to learn how small or big responses are, maybe we can measure this by number of lines of text? characters?)
8. How many responses include links (this can give us insights into adding attachments later on)
9. Most common times when teams add their responses

**Comment by ackernaut** [comment]
Closing in favor of #6535
