### ISSUE TITLE
Standups: Masonry layout implementation

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6389]
## Issue - Enhancement
Implementation details should be provided here once we agree what's the best way to create the masonry layout in React

**Estimated effort:** 4h to discuss

**Comment by enriquesanchez** [comment]
[This article over at CSS Tricks](https://css-tricks.com/piecing-together-approaches-for-a-css-masonry-layout/) goes over a few options (some pure CSS, and some requiring also a some JS). A few of these look like they could _almost_ get us what we need.

**Comment by BartoszJarocki** [comment]
@mattkrick's comment about how we can do it: https://parabol.slack.com/archives/C836NA350/p1649863598765079?thread_ts=1649775671.616269&cid=C836NA350

**Comment by jordanh** [comment]
Iceboxing by policy
