### ISSUE TITLE
Standup UI - Activities from other team members get real-time updates

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6395]
AC:
- [ ] updating team response content mutation payload is added to the meeting subscription
- [ ] verify: When Bob joins the team, Alice sees a new response card show up on her screen, with Bob's avatar

Estimate: 5 hours

**Comment by mattkrick** [comment]
since we're using tiptap, we could use this opportunity to introduce collaborative editing so instead of seeing "X is typing..." it looks like a google doc where the cursor just pops up on the document
