### ISSUE TITLE
Sprint Poker: GitLab v2: Push a weight to an issue

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6396]
Premium GitLab users can add a weight to an issue: https://docs.gitlab.com/ee/user/project/issues/issue_weight.html

A weight is a non-negative integer and is used to estimate the difficulty of an issue.

This feature is only available for premium users. If they have a premium account, after voting on a GitLab issue in Parabol, they should be able to push the score to their GitLab issue as a weight.

Two ways that we could potentially implement this:

1. Always show an "As a weight" label. If a user selects this option but does not have a premium GitLab account, we could show a pop-up saying that they need to upgrade their GitLab account.
2. Check whether they have a GitLab account and only show "As a weight" if they do.

I'd say the second solution would be a better UX. 

### AC

- [ ] A user can select "As a weight" option as a GitLab label
- [ ] If "As a weight" is selected, the selected score in Parabol is added as a weight in GitLab
- [ ] Only show the "As a weight" option if the user has a premium GitLab account

**Comment by nickoferrall** [comment]
Signal from [this customer](https://app.hubspot.com/contacts/3888472/contact/81826201) 🔒  that they would like this functionality

**Comment by jordanh** [comment]
Taking this out of the ice box
