### ISSUE TITLE
The new Activity view

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6399]
![image](https://user-images.githubusercontent.com/3276087/165395723-74a26e0a-6ae0-451c-904b-f396c284874d.png)

<img width="1211" alt="Captura de Pantalla 2022-04-27 a la(s) 3 39 12 p m" src="https://user-images.githubusercontent.com/3276087/165627259-7530dadd-ee8c-45db-9c0f-02e55d8567ea.png">

This issue follows design explorations from #6070. You can [view all the design explorations and final concepts in Figma](https://www.figma.com/file/3ol7LnhfgLX2080DrlXrs4/Notifications?node-id=0%3A1).

## Summary

The new Activity view combines our current `Notifications` menu with the `Timeline` view. Both come together in a single view now called `Activity`.

🍿 [Here's a 6 min. Loom with an overview](https://www.loom.com/share/dab8113b9b7e4224966dcb1ae1cb7338).

### Laying the ground work

- #6458
- #6449
- #6450
- #6451
- #6457
- #6453
- #6464

### New functionality

- #6454
- #6455
- #6456
- #6459

### Updating styles

- #6463
- #6461
- #6462
- #6470 

### Extras

- #6471

### Measuring use

-  #6472

## What's in v2?

- Adding new activity event types
  - Add `comments` event type
  - Add `replies` event type
  - Add `mentions in threads` event type
  - Add `meeting phases` event type
- Group related event types

**Comment by Dschoordsch** [comment]
Just to clarify, the data shown will be the same that was shown in `Notifications` and `Timeline` but just combined? How will pagination work?
If we're adding new event types in v2 we should consider already combining the two underlying rethinkdb tables and move the data into one postgres table. This will simplify pagination and search and is easier to expand for v2.

**Comment by ackernaut** [comment]
I like the general direction here. I think you have a great start to breaking it down.

As you listed, we can start out by combining what we have today.

I agree adding filters is the next logical step. We thought they’d be useful as more teams and activity types are at play, and we’re starting to hear it!

I’m looking forward to supporting how folks reengage with async threads, especially stand-up and poker threads, in this view.

I recommend sitting down with a developer and see if there’s any more ‘better now than later’ groundwork to be laid (Georg brought up good points), and start breaking down the first bits into issues.

Also, you mentioned refining some of the design to support building bits and pieces of it. That sounds like a good idea, it’ll be helpful to gauge how much more design work you would do and then support during implementation.

**Comment by enriquesanchez** [comment]
> the data shown will be the same that was shown in Notifications and Timeline but just combined? 

@Dschoordsch Correct, it will be a combination of what is currently Notifications and Timeline.

> How will pagination work?

Oh, great question! I will work on mockups for this scenario. I was imagining that we will have a `Load more` button at the bottom of a certain amount of activity items. How does that sound to you?

> If we're adding new event types in v2 we should consider already combining the two underlying rethinkdb tables and move the data into one postgres table. This will simplify pagination and search and is easier to expand for v2.

This is the kind of dev input I was looking for, thank you!  Where in the plan do you think this step should go?

**Comment by Dschoordsch** [comment]
> > If we're adding new event types in v2 we should consider already combining the two underlying rethinkdb tables and move the data into one postgres table. This will simplify pagination and search and is easier to expand for v2.
> 
> This is the kind of dev input I was looking for, thank you! Where in the plan do you think this step should go?

This should go into **laying the groundwork**

**Comment by nickoferrall** [comment]
This looks great! Things that I particularly like:

- The pink dot next to "activity". This gets my attention more than the notification bell because my eyes are drawn to this section of the app more frequently.
- That it's interactive! Users don't need to click away to edit a task or accept an invitation.
- Merging notifications and timeline turns two kinda useful features into one truly useful feature.
- That your Looms are always ~6 mins in length! You seem to work hard to make them concise. 

What I think could be changed:

- I'd like to see which filters have been selected. The filter button doesn't take up much space, so perhaps the names of the filters could be included below or on the side, similar to the new Poker scope search UI?
- I think the "What's new in Parabol", Filters button, and Search Activity could have a different background colour to help them stand out.
- Currently, the timeline has cards that create a visual separation for each event. Do we need a visual separation for activities such as a faint horizontal line?

**Comment by enriquesanchez** [comment]
Thanks for the feedback @nickoferrall 🙌

> The filter button doesn't take up much space, so perhaps the names of the filters could be included below or on the side, similar to the new Poker scope search UI?

You're right, I'm going to try this on my next iteration 👍

> I think the "What's new in Parabol", Filters button, and Search Activity could have a different background colour to help them stand out.

@ackernaut had made a similar observation, but refering to the background of the activity items. Here's what I came up with:

![image](https://user-images.githubusercontent.com/3276087/164551654-c6356813-574c-4a5f-b4b8-98921160ab77.png)

I'm adding a white background to the filters button, and given that the most important piece of content here are the activity events, I added the backgroubd to that section as well. I think I like it. What do you think?

> Currently, the timeline has cards that create a visual separation for each event. Do we need a visual separation for activities such as a faint horizontal line?

I had divider lines on my initial iterations but thought that the avatar/meeting icons, plus enough white space in-between was enough to anchor the eye. But I need to spend more time looking at it to have a final decision. Fortunately it is something that would be very simple to add.

**Comment by enriquesanchez** [comment]
>How will pagination work?

@Dschoordsch this is what I had in mind:

<img width="1027" alt="Captura de Pantalla 2022-04-21 a la(s) 4 31 13 p m" src="https://user-images.githubusercontent.com/3276087/164555614-9bd0822a-0ab1-45d2-8724-43919ba1cf57.png">

We load X number of activity events by default, and once the user has reached the bottom we have the option to `Load more...` via this button. 

Instead, if they've reached the end of all activity events, we show a message like this one:

<img width="893" alt="Captura de Pantalla 2022-04-21 a la(s) 4 43 59 p m" src="https://user-images.githubusercontent.com/3276087/164557004-356671d8-599f-49c9-ba55-ca5c44bee95d.png">


And for a brand new account, the initial state of the Activity view could look something like this:

![image](https://user-images.githubusercontent.com/3276087/164557168-62d49fcf-61b7-43d8-9f38-7a528d36252a.png)

**Comment by igorlesnenko** [comment]
Looks great! I like the white background. Though I have a feeling that notifications could be visually separated more.

Just a thought, maybe have an icon near the avatars that shows what type of event occurred. This is to quickly understand what the notification is about and how important it is, without reading the whole text.

**Comment by jordanh** [comment]
+1 to what other's said:
   * I'd like to see filter states a la @nickoferrall 
   * I'd also like to see an exploration of styling what kind of activity an activity entry is, perhaps an icon as @igorlesnenko is a good direction
 
Future stuff:
   * How would sharing work from this activity view? For example, how could we make it easier to share Parabol summaries with non-team members? Could we just have a share button to email a summary to an address?
   
 Questions:
  * Let's assume this page gets more eyeball time than /me does today: how could sales use this real-estate to get in touch with our users/take some action?
  * In the filter view, I have like 20 teams: how would overflow be handled? 3 dots and a filterable input (similar to what we have today?)
  * How about filter by date ranges?

**Comment by ackernaut** [comment]
I still wonder what kind of gaps exist between the Meetings view and this view. The last place folks saw their meeting was on the Meetings view, then when the meeting ends they wonder where it went. I only have raw ideas on how to leave any breadcrumbs connecting the flow.

We’re becoming more aware of how folks get lost signing into our app for the first time. I wonder what a first-time state or activity might look like for this view? I wonder how we may iterate on the CTAs of the current timeline (try the demo, invite your team, start a meeting). I wonder what first-time state may make sense on the Meetings view vs this view. In either view, do we try a single action and see if folks bite, or do we try a ‘choose your own adventure’ set of actions and track what gets chosen the most?
