### ISSUE TITLE
security(ad-hoc): Remove externals from parabol org

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6403]
We have about 300 folks in the parabol org that we need to remove.

The list of users is found like this in the rethinkdb admin panel:

```ts
r.db('actionProduction').table('OrganizationUser').getAll(PARABOL_ORG_ID, {index: 'orgId'})
  .filter((row) => row('joinedAt').gt(new Date(Date.now() - 1000 * 60 * 60 * 24 * 30)))('userId')
```

Once this list is determined, create a for loop to to call the following on the /intranet-schema

```gql
    removeOrgUser(userId: $userId, orgId: $orgId) {
      error {
        message
      }
```

for that call to succeed, please first promote yourself to billing_leader in the parabol org (you can do this manually via a DB update)

AC
- [ ] the parabol org only has parabol-approved folks in it

Estimate: 3 hours

**Comment by Dschoordsch** [comment]
After moving the team to the public org, 279 users without a team in the parabol org were removed.
