### ISSUE TITLE
GraphQL schema is broken in /admin/grapqhl

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6409]
## Issue - Bug

<img width="1212" alt="Screen Shot 2022-04-15 at 3 51 44 PM" src="https://user-images.githubusercontent.com/1879975/163586640-930c5ea1-79a4-4cde-90c8-197a58a5c09a.png">
<img width="971" alt="Screen Shot 2022-04-15 at 3 54 56 PM" src="https://user-images.githubusercontent.com/1879975/163586644-43ce334c-297c-424c-aaf9-7b0be0cc1733.png">

This causes running GraphQL queries really hard in `/admin/graphql` with no auto-suggestions etc. If you manage to get the queries correct they run fine though.

### Acceptance Criteria (optional)
Users can:
   - [ ] Run GraphQL queries in `admin/graphql` with auto-suggestions

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
I see there is a branch with a fix on it (in history above). I'll add this to the project, but I expect it to close "on its own". I'll assign @mattkrick so he can make sure to close this
