### ISSUE TITLE
Illustration update: invite modal in meetings

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6417]
Issue - Enhancement
We've got a new illustration for the invite modal (when folks click 'invite' during meetings). 🎉 [Saved here.](https://drive.google.com/drive/folders/1KG9lgDz2ZV3iGnrT6IOLn1yStvnwGnub)

Acceptance Criteria (optional)
Users can enjoy the new illustration ✨

fyi @acressall

Estimated effort: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by acressall** [comment]
The orientation of the image prompted a look at updating the design of the modal slightly. Note: this change does not impact mobile, where no illustration is shown. CC @ackernaut @enriquesanchez for any feedback
https://www.figma.com/file/G0dEQ
![invite-desktop](https://user-images.githubusercontent.com/18582225/163919550-76717aa1-cf9b-451f-8133-94a0d9959120.png)
BKK9j5zGHDZsL3Lcp/Invite-Dialog?node-id=325%3A274

**Comment by ackernaut** [comment]
@acressall I like the illustration. Would it look better if the dialog header was aligned with the content (just hang the image on the left)? That visual flow is weird for me. If the dialog title was above ‘share this link’ the character would be pointing to it which might work well

**Comment by enriquesanchez** [comment]
+1 to @ackernaut's suggestion. It will also create a nice situation where the hand is pointing at the header 😃

**Comment by acressall** [comment]
Thanks both! I've updated and it flows a lot better 😄 
![invite-desktop (1)](https://user-images.githubusercontent.com/18582225/164357189-b3634339-ef4a-4e56-bf1b-652e730e4862.png)
