### ISSUE TITLE
Check-In: Create agenda items without advancing the meeting

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6418]
As a meeting facilitator I want to be able to add certain agenda items already before the meeting started. At the moment I need to advance the meeting at least past icebreakers to be able to add agenda items. When the sync meeting happens, all icebreaker participants are already crossed out.

## Possible solutions
1) allow facilitator to move to different stages without advancing the meeting #6179 and also opening the agenda items from the start
2) reset meeting/ reset stage button to mark all stages as non-complete for check-ins (could also work for poker, but not retrospectives)

**Comment by enriquesanchez** [comment]
>As a meeting facilitator I want to be able to add certain agenda items already before the meeting started

While this can be done before the meeting starts in the Team view, I know it's not easily discoverable and does not solve the case when you want to add them once the meeting has started.

I wonder if we can enable the ' Add agenda item' button for facilitators during the Icebreaker and Solo Updates phases?

@ackernaut Would you have some background on why this wouldn't be safe to try?

**Comment by ackernaut** [comment]
We only turned off the ‘add agenda item’ for the Icebreaker phase. We assumed nobody wanted to see folks adding agenda items if they were talking (we were thinking a lot about the sync UX of icebreakers at the time, since you can only really take turns and speak over video etc.). During the solo updates phase, I believe you can add to the agenda.

I don’t think it would harmful to allow it during the icebreaker, too.

**Comment by Dschoordsch** [comment]
We could still blur all of these, but everyone could add more

**Comment by enriquesanchez** [comment]
Thanks @ackernaut 

> I don’t think it would be harmful to allow it during the icebreaker, too.

That's my perspective as well.

> We could still blur all of these, but everyone could add more

What would be the harm of not blurring them? In general it's good meeting hygiene to have everyone know the meeting agenda beforehand.
