### ISSUE TITLE
Standup UI - Support editing a response while another team member joins (TEST-ONLY)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6422]
If someone joins the meeting or team while I'm typing out my update, I want to make sure that my card doesn't move & the focus isn't lost.

AC
- [ ] on device 1, type out half your response
- [ ] on device 2, join the team & meeting
- [ ] on device 1, my card is still in the first spot & the focus did not change

Test-only Estimate: 3 hours (should already be working, just want to verify it's working as intended)

**Comment by jmtaber129** [comment]
@BartoszJarocki this is effectively blocked on https://github.com/ParabolInc/parabol/issues/6395, right?

**Comment by jmtaber129** [comment]
Confirmed that this does **not** work as intended currently.  Opened https://github.com/ParabolInc/parabol/issues/6553 to actually fix
