### ISSUE TITLE
Jira Server v2: Implement OAuth2

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6442]
It seems OAuth2 is possible, check https://confluence.atlassian.com/adminjiraserver/jira-oauth-2-0-provider-api-1115659070.html if we can simplify adding Jira Server for the team lead.

## Acceptance criteria
* [ ] Implement OAuth2 variant for Jira Server of `addIntegrationProvider`
* [ ] Enable OAuth2 flow in `JiraServerClientManager`
* [ ] Distinguish between OAuth1 and OAuth2 clients in `JiraServerRestManager`

**Comment by Dschoordsch** [comment]
It's available from Jira Server 8.22 which was released in Februar https://jira.atlassian.com/browse/JRASERVER-43171
We should start supporting it, but not get rid of OAuth1 just yet since we don't know how fast the upgrade cycle of our clients is.

**Comment by jordanh** [comment]
@Dschoordsch why do this now, vs. wait to see if we get signal from users?
