### ISSUE TITLE
Jira Server: oauth window disappears as soon as you open it

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6444]
## Issue - Bug

Jira Server oauth window disappears as soon as you open it.

I noticed this behavior at least in Chrome `Version 100.0.4896.127 (Official Build) (x86_64)` and Safari `Version 14.1.2 (16611.3.10.1.6)`

Does not work with paused AdBlock too. On Safari I have no plugins installed.

https://user-images.githubusercontent.com/466991/165166106-fe700ab6-a790-460f-b601-7a78c73fa02c.mov

### Acceptance Criteria (optional)
Users can:
   - open auth popup with no issues 

**Estimated effort:** 4h

**Comment by Dschoordsch** [comment]
I cannot reproduce it with Google Chrome `Version 101.0.4951.64 (Official Build) (64-bit)` nor with Firefox `100.0 (64-bit)`

**Comment by igorlesnenko** [comment]
Now I can only reproduce this problem in chrome. Safari and Firefox work fine for me.

Issue with chrome fixed by disabling metamask plugin.

Conclusion — the problem is not a bug on our side. No action required right now.

I'm closing this issue.
