### ISSUE TITLE
Jira Server: some projects are visible even when they are not accessible

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6446]
Looks like some projects are still visible even after they were removed from Jira Server

Maybe some isArchived filter is missing or something.

How to reproduce:
- Setup our `parabol` Jira Server integration
- Create any task and try to push it to `Georgs test` project
- See `project not found error` returned

<img width="321" alt="image" src="https://user-images.githubusercontent.com/466991/165167988-a020b1b8-8309-477e-94b4-3bd5dcf7a014.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/466991/165168113-380d9e7c-f009-45c5-a9ff-a5e30b767aae.png">

### Acceptance Criteria
- User see only available projects in push to integration menu and scope filter menu

**Estimated effort:** 2h

**Comment by Dschoordsch** [comment]
@igorlesnenko the project is not deleted, but access to it is restricted so it should not appear in the list for you.

**Comment by Dschoordsch** [comment]
@igorlesnenko When you login directly to Jira, could you check if the project shows up there for you?

**Comment by igorlesnenko** [comment]
@Dschoordsch I undable to see it on Jira 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/466991/165256573-fbd54e2d-05e1-4069-9da7-5d079c076956.png">

**Comment by Dschoordsch** [comment]
Ok, then it should not appear in the REST request either. Just for reference, I created 1 user who has access who can still see the project
![Screenshot from 2022-04-25 22-25-57](https://user-images.githubusercontent.com/7331043/165257141-841d9bb5-cb57-421f-b997-71222dc7888a.png)
s

**Comment by igorlesnenko** [comment]
@Dschoordsch for some reason it is still appearing for me, here is the rest response

```
{
  expand: 'description,lead,url,projectKeys',
  self: 'https://jira.parabol.co/rest/api/2/project/10100',
  id: '10100',
  key: 'GT',
  name: 'Georgs test',
  avatarUrls: {
    '48x48': 'https://jira.parabol.co/secure/projectavatar?pid=10100&avatarId=10601',
    '24x24': 'https://jira.parabol.co/secure/projectavatar?size=small&pid=10100&avatarId=10601',
    '16x16': 'https://jira.parabol.co/secure/projectavatar?size=xsmall&pid=10100&avatarId=10601',
    '32x32': 'https://jira.parabol.co/secure/projectavatar?size=medium&pid=10100&avatarId=10601'
  },
  projectTypeKey: 'software',
  archived: false
},
```
