### ISSUE TITLE
Activity view: Add `Filter` menu to `Activity` view

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6455]
This issue is part of #6399 

Adds filtering option to the new Activity view via a new `Filter` menu dropdown.

<img width="1447" alt="Captura de Pantalla 2022-04-26 a la(s) 5 20 16 p m" src="https://user-images.githubusercontent.com/3276087/165402176-ee6c1a23-97d0-4c33-97f5-bbf6da697340.png">

🎨 [Figma file for reference](https://www.figma.com/file/3ol7LnhfgLX2080DrlXrs4/Notifications?node-id=320%3A4453)

### Acceptance Criteria
- A new `Filters` menu dropdown is available in the new `Activity` view
- The new `Filters` dropdown can receive focus and displays proper focus styles when focused
- When activating the `Filters` dropdown:
  -  The `expand_more` icon changes to `expand_less`
  - The filters dropdown is displayed and [includes the options as seen in the Figma file](https://www.figma.com/file/3ol7LnhfgLX2080DrlXrs4/Notifications?node-id=339%3A5109)
- When clicking on the Filters toggle again:  
  -  The filtering options are hidden
  -  The `expand_less` icon changes to `expand_more`
  
We will be tackling the actual filtering functionality on a subsequent issue (#6456).  

### Estimated effort
(Needs EE)

**Comment by jordanh** [comment]
I don't want to icebox this one. I really don't. I hope we re-open it in the near future
