### ISSUE TITLE
Activity view: Add `What's new` section to `Activity` view 

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6471]
This issue is part of #6399.

<img width="600" alt="Captura de Pantalla 2022-04-27 a la(s) 3 49 30 p m" src="https://user-images.githubusercontent.com/3276087/165628464-f3232e47-8263-4d10-813e-98a1b3958668.png">

🎨 [See Figma for reference](https://www.figma.com/file/3ol7LnhfgLX2080DrlXrs4/Activity-view?node-id=320%3A4453).

### Acceptance Criteria
- The new `Activity` view includes a `What's new' section
- The `What's new` section **replaces the current snackbar** pattern for announcing new features
- The `What's new` section is only available on large viewport sizes, and **hidden on mobile** 
- The `What's new` section **can be dismissed** via the `X` button
  - This setting is remembered (per user) until a new what's new message is broadcasted
  - When a new message is broadcasted, and if the section was previously hidden, we display it again
- Each `What's new message` can include an emoji/icon, a short text, and a link to `Learn more`

### Estimated effort
(needs EE from a developer)

**Comment by enriquesanchez** [comment]
@nickoferrall Since you worked on the current snackbar pattern for "what's new" messages, does this issue make sense to you? Am I missing something? Is there anything else we would need to do in order to transition from snackbars to this new pattern?

And while I have you attention, could help me out with a rough EE for this issue?

**Comment by nickoferrall** [comment]
> The What's new section is only available on large viewport sizes, and hidden on mobile

On a laptop, would the "What's new" section be visible?

**Comment by enriquesanchez** [comment]
> On a laptop, would the "What's new" section be visible?

I'd stick to the same breakpoint of 920px we currently have, so on regular laptop the what's new section would still be visible, unless the browser is set at a smaller window size
