### ISSUE TITLE
Notify via Slack?

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6474]
Today when setting a time limit in a Parabol meeting, every user regardless of what chat integration they have set will see a `Notify via Slack` option:

<img width="273" alt="Captura de Pantalla 2022-04-27 a la(s) 4 37 13 p m" src="https://user-images.githubusercontent.com/3276087/165635537-89e09727-27fd-4210-ac34-e5ed0dac9a7e.png">

If I haven't set up the Slack integration, activating that option will open the oauth window. If instead I had already setup Slack, then this acts as a regular option I can turn on,  or off.

On the other hand, if I have Mattermost setup instead, I see this:

<img width="263" alt="Captura de Pantalla 2022-04-27 a la(s) 4 36 15 p m" src="https://user-images.githubusercontent.com/3276087/165635765-142b4595-6f03-4fd9-a7bc-65308f2cfa0c.png">

I don't get an option to "Notify via Mattermost", I'm just told that the action will happen.

Now that the MSTeams integrations is almost ready, [the question came up](https://parabol.slack.com/archives/C03ADGTTS2D/p1651072949062849?thread_ts=1651015856.785999&cid=C03ADGTTS2D) 🔒 about **following the default Slack pattern, or the Mattermost pattern?**

While an edge case, this also led to wonder what will happen if a team has **more than one chat integration** enabled, **how do they decide to which one to send the notification to?** Should we add a select dropdown? Should we default to either one?

We currently do this:

<img width="268" alt="Captura de Pantalla 2022-04-27 a la(s) 4 46 08 p m" src="https://user-images.githubusercontent.com/3276087/165636532-5f1359ac-41a0-4a4d-9d27-8bcf9bcb22ce.png">

...which is a bit confusing, because it seems that I can decide to notify Slack or not, but I have no option for Mattermost.

**Should we explore a new pattern?**

-------

### Acceptance criteria
- Explored and designed a solution that resolves the confusion stated above

### Estimated effort
- 4 hrs

**Comment by enriquesanchez** [comment]
@Dschoordsch @mattkrick @ackernaut Would love to hear your thoughts here.

**Comment by Dschoordsch** [comment]
I think we should keep things simple and not allow individual settings per integration. I propose having a
"Add integration to notify team" if they're not integrated and a checkbox "Notify team via <list of added integration icons>". Maybe also in the first case add the icons so the user knows directly what's available.

**Comment by ackernaut** [comment]
> I think we should keep things simple and not allow individual settings per integration. I propose having a "Add integration to notify team" if they're not integrated and a checkbox "Notify team via ". Maybe also in the first case add the icons so the user knows directly what's available.

I like this!

> ✅  Notify via chat (**slack** icon)(**teams** icon)(**mattermost** icon)

I do think we should consistently use the word ‘chat’ e.g. ‘integrate with chat’ ‘notify via chat’ ‘manage chat notifications’ etc. as it’s clear language and leaves us open to them picking their chat of choice. I suppose we could use conditional language when it makes sense ‘Manage Mattermost notifications’ when they are integrated with 1 particular chat

What does it show when the select it? Do they first select which chat via dialog and then we kick off the oauth for that particular integration?

Another pattern could be a dropdown:

Option 1: No chat notifications (default selection)
Option 2: Notify via Slack
Option 2: Notify via Mattermost

When the select a chat they can authenticate.

Then the menu can have ‘Notify via Mattermost’ selected or whatever

**Comment by jordanh** [comment]
@enriquesanchez iceboxing by policy. I hope we reopen this one with tension
