### ISSUE TITLE
bug: invoice missing on Organization page but indeed charged in Stripe

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#6477]
## Issue - Bug

One 🔐[user](https://app.hubspot.com/contacts/3888472/contact/24634251):
> I've noticed that we were charged for April for $66.45 yet I cannot find an invoice for it on my Organization page. Could you please help clarify that? Thanks.

### Acceptance Criteria
Users can:
   - see all charged invoices on Org page

**Estimated effort:** 3 hours to triage.

The initial finding is that the returned data seems to be partly missing, see [Slack](https://parabol.slack.com/archives/C4JAUUZ9P/p1651128386842309?thread_ts=1651069532.878569&cid=C4JAUUZ9P)

The invoices list of this org is found like this in the RethinkDB admin panel:

```js
r.db('actionProduction').table('Invoice').between(['3xAXbSQBhK', r.minval], ['3xAXbSQBhK', r.maxval], {index: 'orgIdStartAt', leftBound: 'open', rightBound: 'closed'}).filter((invoice) => invoice('status').ne('UPCOMING').and(invoice('total').ne(0))).orderBy(r.desc('startAt'), r.desc('createdAt')).limit(4)
```

**Comment by mattkrick** [comment]
The construction guys cut my internet (again) so I couldn't record a video on how I fixed this.
Here are the steps:

- login to stripe
- type in the orgId in the search
- notice the April invoice didn't show up
- click the customer
- click the April invoice
- notice that there is no metadata attached to the invoice
- copy the invoiceId
- goto /admin/graphql run `stripeCreateInvoice(invoiceId: ID)`
- see that the invoice was created

still not sure WHY this happened. we need to fix https://github.com/ParabolInc/parabol/issues/4935 to get more visibility (OK webhooks are removed after 15 days)

**Comment by JimmyLv** [comment]
Awesome! As my understanding, according to https://github.com/ParabolInc/parabol/issues/4935, so this issue is probably because Stripe's Webhook broke before it succeeded (when it was sent to Parabol), and Parabol should have waited for the data to be successfully saved into the database before replying success, right?
