### ISSUE TITLE
bug: undefined Label after revealing votes for tasks added via Parabol (Sprint Poker)

### ISSUE THREAD

**Issue by MindEvo** [ParabolInc/parabol#6483]
Steps to Reproduce:

1. Open a Sprint Poker meeting
2. Add a task 'x' via Parabol and select it
3. Click next and vote on 'x'
4. Click reveal votes
5. Bug is visible in the edit score div.

See video:

https://user-images.githubusercontent.com/35351786/165997376-8d845ef1-97bd-4acd-aac2-d48150b5aaf1.mp4

**Comment by jordanh** [comment]
This is a good find!

**Comment by jordanh** [comment]
Also: If the label is updated on a Parabol task, how would a user ever see it?

**Comment by raj360** [comment]
Hi @jordanh, what should be the expected result on here. cc @Dschoordsch, @MindEvo.

**Comment by Dschoordsch** [comment]
The undefined label was fixed in the meantime. We don't show these estimates anywhere yet. If you feel like it, you can come up with a design and propose it in a new issue.

I will close this bug since it was fixed.
