### ISSUE TITLE
Check for vulnerabilities in PRs github workflow

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6489]
Run `yarn audit` for PR builds. This will block commits if moderate or above vulnerabilities found. This will aid in keeping moderate and above (high, critical) out of our code base. This also has the benefit of reducing security findings during Ironbank vulnerability scan as yarn audit is one security feed used for vulnerability findings.

> IMO I'd run this as a github workflow so it'd throw up a red flag before merging to master vs. on every local commit.
> Maybe put it here? https://github.com/ParabolInc/parabol/blob/7be22aa9856e85e5c284fa06c5bad88253e31822/.github/workflows/typecheck.yml

_Originally posted by @mattkrick in https://github.com/ParabolInc/parabol/issues/6030#issuecomment-1049203884_

## Acceptance criteria
* [ ] `yarn audit` is run for PRs and build fails if there are moderate or above vulnerabilities found

**Comment by jordanh** [comment]
This was a good one. Just noting for @rafaelromcar-parabol and @adaniels-parabol if they'd like to reopen some day in the future
