### ISSUE TITLE
can't see ended meeting on timeline view 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6492]
A [user ](https://app.hubspot.com/contacts/3888472/contact/65877651) 🔒 ended a meeting but can't see it in their timeline. 

Slack discussion with @JimmyLv [here](https://parabol.slack.com/archives/C4JAUUZ9P/p1651077080259489)

**Comment by jordanh** [comment]
We caught no further occurrences of this issue. Iceboxing
