### ISSUE TITLE
Standups: Include stage/discussion metadata in URL when discussion is open

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#6495]
We'd like to include some stage metadata in the URL when a standup discussion is open, so users can share links to standup discussion threads.  However, our current model of local meeting state doesn't provide an easy way to conditionally include a stage index in the URL, since `localPhase` and `localStage` are non-null, and existing URL utils only exclude the stage index if the [phase type is hard-coded as a single-stage phase](https://github.com/ParabolInc/parabol/blob/584cb1d210b8f05dd5b2cd0f2886fa84e7f1afd1/packages/client/utils/meetings/fromStageIdToUrl.ts#L12-L24).

We need a way to conditionally show the stage ID in the URL.

See discussion in https://github.com/ParabolInc/parabol/pull/6370#discussion_r852514465.

AC:
- [ ] URL includes stage ID when discussion thread is open
- [ ] Navigating to URL with stage ID opens the corresponding discussion thread
- [ ] URL does not include stage ID when the discussion thread is closed
- [ ] Opening the discussion thread by swiping the scrim from the edge updates the URL and shows the discussion

**Comment by jordanh** [comment]
@jmtaber129 iceboxing this by policy
