### ISSUE TITLE
Standups: Dataloaders usage when querying standups related data

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6496]
## Issue - Enhancement

There might be a few places where gql types use PG queries directly instead of using data loaders. Introduce new data loaders if needed and make sure there's no direct use of PG queries.

One known place: https://github.com/ParabolInc/parabol/pull/6388/files/6754119ee3bb3ada9dc1ac53d8e673c78bf38976#diff-eda5c477ef57e1cbe2c683f1899923c8fb472c3c57d69173ae01d330fd736e04 

### Acceptance Criteria (optional)
- [ ] no direct queries are executed in standups related gql types

**Estimated effort:** 8h

**Comment by jordanh** [comment]
@BartoszJarocki iceboxing this by policy
