### ISSUE TITLE
Sprint Poker sporadically clears Jira point values 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6499]
A [user ](https://app.hubspot.com/contacts/3888472/contact/17005951) 🔒 writes: 

> 
> Over the past few weeks myself and the Product Owner for my team have been using the Planning Poker tool in combination with Jira Cloud.
> 
> In doing so we've encountered a bug. Sporadically when using Parabol Planning Poker it somehow clears the point values on seemingly random unrelated tickets. Tickets that you aren’t looking at in Parabol scope, or even from the same project.
> 
> I've had it happen with my account, and the PO has had it happen as well. We aren't even aware of it having happened until someone comes along asking why we removed points from their tickets. In Jira it just looks like our user deleted points from the ticket.

**Comment by Dschoordsch** [comment]
I created #6506 to investigate and fix the bug.

**Comment by jordanh** [comment]
We'll get to this one very soon

**Comment by jordanh** [comment]
Closing this in favor of #6506
