### ISSUE TITLE
Team Invite email updated to include Poker

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6501]
## Issue - Enhancement

The content in our 'you've been invited to a team!' email is outdated.
![Screen Shot 2022-05-04 at 10 48 24 AM](https://user-images.githubusercontent.com/11621016/166821349-daff0adf-4df7-4d87-ab37-2e39652b2d62.png)

We need to make the following changes: 
- Update the graphic to show our newer video (below) 
- Link to the 101 page: https://www.parabol.co/resources/retrospective-meetings/#video 
- Add 'Estimating issue: Sprint Poker 101', which should link to https://www.parabol.co/resources/sprint-poker-meetings/ 

![Screen Shot 2022-05-04 at 3 33 21 PM](https://user-images.githubusercontent.com/11621016/166821400-313df534-b1b4-4b97-b849-0a046b365ee4.png)

And while you're there: #6498

### Acceptance Criteria (optional)
Users can see our updated video in the email, find a link about Sprint Poker. 

**Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by 87prashant** [comment]
We need to upload above image to the database to use it.
Any help on how to do it?

**Comment by jordanh** [comment]
Scrubbed, but it is so trivial I am going to try and keep it open and ask if somebody can get this done

**Comment by Dschoordsch** [comment]
@nickoferrall did you figure out where to upload those assets? (like the favicon?)

**Comment by nickoferrall** [comment]
Yeah, Aaron said we can upload them here: https://s3.console.aws.amazon.com/s3/buckets/action-files.parabol.co?region=us-east-1&prefix=static/

Slack thread [here](https://parabol.slack.com/archives/C608QL4RH/p1670496627105919)
