### ISSUE TITLE
Promote 'practice round' to users who are practicing 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6502]
## Issue - Enhancement

In [watching session replays 🔒 ](https://www.notion.so/parabol/Session-replay-churned-e40b12411b354fb0987aa2cac7753865), we've found that some users will run test meetings (1-person meetings, where all the reflections are 'test' or the issues to scope are 'test'). Since Parabol's value comes out primarily when you're interacting with folks, they're not getting to see the true value! 

We should consider highlighting the demo to these folks, as a way to test the product better. 

Ideas: 
- Copy can read something like: "Parabol is best played with pals. If you're not ready to bring in your team, [Try a practice round with some friendly robots]" 
- We could highlight this on the Meeting view, maybe in the Meeting Lobby? And maybe somehow once they've started a meeting. 

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@tianrunhe could you perhaps add some AC here to match the exploration work that you did and anything that you might consider you or somebody else do before this would be safe to try in prod?

**Comment by avivapinchas** [comment]
Bringing this into the conversation: would love to include [the Learning Hub exploration](https://parabol.slack.com/archives/C9519N85P/p1652070017649999?thread_ts=1651876062.782999&cid=C9519N85P ) in our efforts here, either in the MVP or in a fast-follow.

**Comment by tianrunhe** [comment]
I reviewed @acressall 's awesome work on leaning hub and I think this particular issue is more aligned with the 'practice round' card in the meeting view. The introduction video from Jordan piece needs a separate issue (and maybe later picked up by the growth team dev). My question to @acressall: what do you think if we launch the first version with the demo card? Per my understanding you initially wanted the intro video to be the MVP.

**Comment by acressall** [comment]
Note: this is being done in https://github.com/ParabolInc/parabol/issues/6649
