### ISSUE TITLE
Help new users who try to use the left nav to find their way 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6503]
## Issue - Enhancement

[Some users](https://www.notion.so/parabol/Session-replay-churned-e40b12411b354fb0987aa2cac7753865) 🔒  try to navigate to the next meeting phase by clicking the phase names in the left-hand sidebar. When they do, they get no feedback, and aren't sure what to do next. 

We should help them find their way! Some ideas: 
- They're allowed to use the sidebar for navigation 😄  The phase names behave just like the 'next' button for the facilitator 
- If they click the sidebar, they get some message that points out the 'next' button, so they know where to go. 

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@avivapinchas any acceptance criteria you might have to suggest on what the output would look like? Is it a time-bounded exploration? Some prototypes to test with ourselves or users? Something else?

Tension is good and I'd love to get this to a place where it can be prioritized

**Comment by avivapinchas** [comment]
@jordanh I think the output could either be: 
- 1-2 prototypes shared with users for feedback <- I think we'll get lower-quality feedback here, as folks often have a hard time predicting their behaviors, but it may be helpful for some quick feedback
- Changes launched to subset of users behind feature flag, results analyzed 

I think it depends how significant the changes are, and I would err towards smaller and faster-to-feedback.

**Comment by acressall** [comment]
Moving this to the backlog in favour of #6673

**Comment by jordanh** [comment]
Related to (and closing in favor of) https://github.com/ParabolInc/parabol/issues/8056
