### ISSUE TITLE
Standups: Show 'X is adding a response...' when team member is adding a response

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6524]
## Issue - Enhancement

It'd be good to show and real-time indicator about other folks adding a response, just like w do with comments and tasks.
It's worth noting  [`EditCommentingMutation`](https://github.com/ParabolInc/parabol/blob/master/packages/client/mutations/EditCommentingMutation.ts) can't be directly used as it's tied to `discussionId`. We either have to refactor or create a similar mechanism for standups. It might be worth breaking down the issue into smaller chunks after starting the development. It'd be also best to discuss the potential solution with the maintainer before the implementation.

### Acceptance Criteria
- [ ] `X is adding a response...` is visible when team member is adding a response
- [ ] `X is adding a response...` is replaced with real content when team member response is submitted 

**Estimated effort:** 21h

**Comment by jordanh** [comment]
@BartoszJarocki iceboxing by policy. Please reopen if you'd like to re-prioritize
