### ISSUE TITLE
Allow anonymous users to contribute to retros without creating an account 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6528]
A [user](https://app.hubspot.com/contacts/3888472/contact/46679151) 🔒 writes:

> How do I enable anonymous access to a retrospective board? Anonymous submissions is a standard of trust we have built and I could not ask 10-200 people to go create an account. This is an easy retro feature. I can allow anonymous access and anyone with the link can post.

**Comment by acressall** [comment]
@ackernaut and I discussed this recently re: public retros! Here are our rapid fire thoughts from a 5min discussion:
    - We’re wanting to do it (Remotely Agile, public user feedback), why not let users do it too?
    - Paid feature?
    - not tied to a team or org
    - doesn’t introduce vulnerabilities to their account or org
    - does a team own a public retro?
    - doesn’t have integrations because doesn’t need it
    - only facilitator can have tasks?
    - doesn’t connect back to a team dash; it’s output only
    - will folks try to gamify? pay for an org of 1 and hold public retros with their teams

**Comment by ackernaut** [comment]
>This is an easy retro feature. I can allow anonymous access and anyone with the link can post.

Sounds like they have what the need 🤪 or do they want the affordances of Parabol without 10-200 users haha?

**Comment by ackernaut** [comment]
A few more ideas:
- Free:
  - 1 public retro can be managed a month (can open, close, re-open, reset) etc.
  - It’s a sandbox activity; you can still create teams, have private activities on those teams, etc.
  - The retro automatically closes after a timeframe, on Pro you can keep it open longer
  - When you look back on a public retro for contributions, you only have access to it so long. On Pro you have unlimited history of public retro summaries.

**Comment by jordanh** [comment]
Removing stale from this. Reviewing this now is a good prompt to add some recent feedback.

We recently met with a software factory within the U.S. Space Force. One of their software development process practice leads told us that the primary inhibitor from using Parabol was that we required authenticated access to run an activity. Especially for involving contractors, they'd like a way to open up particular activities (or even phases within activities) to public participation.

We will gather more information from them

**Comment by igorlesnenko** [comment]
Linking some old prototype: #7164
