### ISSUE TITLE
Fix GitLab query complexity bug

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6540]
To reproduce:

- Select 50 issues in the GitLab Poker Scope phase
- Refresh the page a few times
- See that the sidebar doesn't show the titles of the issues and the console says that the complexity of the query exceeds the limit of 250

Originally discovered by Matt here: https://github.com/ParabolInc/parabol/issues/6511#issue-1227046122

### AC

- [ ] Can add 50 GitLab issues, refresh the page, and still see all the issues in the sidebar

**Comment by igorlesnenko** [comment]
@nickoferrall is it same issue here #6386 ?

**Comment by nickoferrall** [comment]
@igorlesnenko it is! I didn't see that one. I'll close it now
