### ISSUE TITLE
TypeError: i is undefined in c(packages/client/components/ScopePhaseArea)

### ISSUE THREAD

**Issue by jchandler-parabol** [ParabolInc/parabol#6545]
https://sentry.io/organizations/parabol/issues/3214259012/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d

![Image](https://user-images.githubusercontent.com/99220260/167865568-9c665550-9b69-4613-bc40-eb1036360db8.png)

**Comment by jchandler-parabol** [comment]
![image](https://user-images.githubusercontent.com/99220260/167866584-40486319-a0d9-43a0-a826-ce56d2ae9fec.png)

**Comment by jordanh** [comment]
Related to #5707?

**Comment by jordanh** [comment]
### AC
- 1 hour to triage and fix or
- triage and open new issue

### EE: 1 point

**Comment by jordanh** [comment]
No longer occurring in Sentry. Presuming fixed
