### ISSUE TITLE
Core Metrics users by tier accuracy issue

### ISSUE THREAD

**Issue by tghanken** [ParabolInc/parabol#6558]
## Issue - Bug

There currently appear to be significant inconsistencies between the `OrganizationUser` and `User` tables that are impacting our Core Metrics.

Today, Core Metrics users by tier appears to be calculated like (SQL pseudo code):
```
select tier, count(*)
from User
where not inactive and not isRemoved
group by tier
```

Across most of our analytics, we instead use the `OrganizationUser` table as the source of truth (SQL pseudo code):
```
select tier, count(*)
from (
  select userId, max(tier) as tier
  from OrganizationUser
  where not inactive and removedAt is null
  group by userId
)
group by tier
```

These two approaches result in significantly different (~25% at the enterprise tier!) counts of users at each of our tiers.  After looking into it more, I was able to get counts for three buckets of issues:

Active in Users not OrgUsers | Active in OrgUsers not Users | User tier <> OrgUser tier
-- | -- | --
685 | 317 | 1304

Overall, I think there are some issues in how we're syncing data between these two tables that we need to address.

### Acceptance Criteria (optional)
- [ ] Which table should be the source of truth for Analytics?
- [ ] Determine where we are introducing sync issues in the product
- [ ] Clean up historical data

**Estimated effort:** 1 hour to triage.

**Comment by jordanh** [comment]
Holy buckets. I guess the next level would be to compare against Stripe subscription counts and see if we've also been under-billing in cases...

**Comment by tianrunhe** [comment]
One of the issue is that when a user is removed from an org, his/her tier is not updated. See #7319

**Comment by tianrunhe** [comment]
For analytics purpose, we should look at `OrganizationUser` table over `User` table

**Comment by tianrunhe** [comment]
Found one more issue tracked in https://github.com/ParabolInc/parabol/issues/7624
