### ISSUE TITLE
Standups: Order response cards

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#6561]
We should sort response cards such that they're consistent between page loads and viewers.  Specifically, the order should be:
* Viewer's cards (regardless of whether it's completed)
* Non-empty cards
  * Ordered by response's `createdAt` time
* Empty cards
  * Ordered by when the team member's stage was created
  * For team members who joined the meeting by being a part of the team, the ordering should be consistent within a meeting, but the sort key is unimportant.

Suggestion: do the non-viewer card sorting on the server to ensure consistency.

### Acceptance Criteria
- [ ] Viewer's card is first
- [ ] Non-empty cards appear immediately after viewer's card
- [ ] Empty cards appear after non-empty cards
- [ ] When a response transitions from empty to non-empty, the card moves to between the last non-empty card and the first empty card
- [ ] When a team member joins, their empty card appears at the end of the card list
- [ ] When a response transitions from non-empty to empty (i.e. team member cleared their response), the card moves to the empty cards (exact placement isn't important)

**Comment by ackernaut** [comment]
Overall, this makes sense to me. I do have a question about this detail:

>Non-empty cards Ordered by response's createdAt time

Could we stick the newest cards first in the sort order? This would favor fresh content, putting it at the top. The thinking is if I looked at the view I’d see new responses. That assumption was based on an async flow.

I suppose the layout changes could get busy if a bunch of folks were adding responses at the same time. If they were holding a sync meeting this may be annoying if I’m trying to read other cards. The reason this may be okay is that my card will always be top left, so I can edit without having my card move around.

If there are doubts, I think adding non-empty responses to the grid (oldest first, newest appended) is a safe starting point to have less layout change. The goal is to ship good over perfect.

**Comment by jmtaber129** [comment]
I have a medium preference towards optimizing for less layout changes, at least for non-empty cards, since the impact of things moving around while you're trying to read responses is pretty negative IMO.  E.g. If I'm trying to read through my teammates' responses, and suddenly they all shift while I'm reading because someone just submitted their first response, that would be a pretty significant interrupt, and would make it difficult to get through reading all the responses.

Maybe there's a more targeted enhancement of surfacing unread cards that we could do as a later milestone.  Perhaps a highlight or a little red dot in the corner of cards that were updated since last view?

**Comment by ackernaut** [comment]
Okay, we can start with less layout change. I like deferring ideas around showing what’s new. I think once we and others use it for a while we can revisit.
