### ISSUE TITLE
Postgres: make "providerId" field a foreign key

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6564]
"providerId" field in the "...DimensionFieldMap" tables in Postgres should be a foreign key to the "integrationProvider" table.

_Originally posted by @igorlesnenko in https://github.com/ParabolInc/parabol/pull/6437#discussion_r874619140_

## Acceptance criteria
* [ ] make the field a foreign key in all "...DimensionFieldMap" tables (i.e. AzureDevOps, GitHub, JiraServer...)
* [ ] ensure providerId is a foreign key in "TeamMemberIntegrationAuth"
* [ ] add delete cascade to the integration provider

**Comment by Dschoordsch** [comment]
Let's still do this to set a good example for the future.

**Comment by jordanh** [comment]
Still the right thing to do
