### ISSUE TITLE
Designed v1 Domain Stats with CTA

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6568]
### Discussed in https://github.com/ParabolInc/parabol/discussions/5666

<div type='discussions-op-text'>

<sup>Originally posted by **ackernaut** November 16, 2021</sup>
Short of building out the full enterprise usage report as admin views (which can be scoped as a broader design exploration) we could tease folks in their admin view with domain stats and a CTA to upgrade.

## User job story

>When I learn that our company has many accounts and many teams, that we are over usage, and I want to continue using Parabol with my teams, I want access to **_easy to understand_** data that doesn’t expose the content of my meetings and a clear set of options for what’s required of me, so that I can initiate the purchase process with my company.

## Open questions
- How might we start small, sharing a subset of the enterprise report in the admin view today? Do we tease with limited information? Should we show them more information if they take action?
- How could we test what stats are safe to share across accounts?
- What might we learn in order to build out more of the domain stats in the admin views?
- How can we use the current account language (‘organization’ instead of ‘workspace’, ‘member’ or ‘user’ instead of ‘seat’ in a way that is easy to understand? (We can update language later)
- What’s the primary action we are looking from folks? Are there any secondary actions? Contact sales to share feedback? Upgrade to Pro? Something else?
- What do folks get if they take the action? Extended usage? Access to more data i.e. ‘the full report’? If we progressively share domain data, what would they see next?
- How do admins turn this on for organizations? Is it an admin mutation?
- How will folks know about the stats without having to point them to the stats?

## Concepts

Here’s a rough concept from the prototype:

![Domain stats CTA](https://user-images.githubusercontent.com/307286/142079053-a9475b3f-8a69-4b12-a23c-8a36b6a484f1.png)

We could hack this into the billing CTA to be scrappy:

### Before

![Billing upgrade CTA before](https://user-images.githubusercontent.com/307286/142079785-cd00ca7a-1be5-4d34-b529-35aade7c51f2.png)

### After

![Billing upgrade CTA after domain stats is turned on for org](https://user-images.githubusercontent.com/307286/142079806-6398574b-874c-4744-b7ea-448be583ec09.png)

## Acceptance criteria
- Discussed CTA options with Growth, Sales
- Discussed technical options with Squad Developers
- Designed concepts for initial, limited stats view
- Designed concepts for expanded stats view
- Designed workflow for CTA (what UI do they see? confirmation? how do we flag a sales person? do they get a follow-up email?)
- Worked with a developer to write implementation issues, including any needed admin mutation
- If there are unanswered open questions or more design work needs be done, make smaller issues at the end of this sprint e.g. need to work on the CTA workflow some more, or need to review stats views

## Estimated effort
- 16 hours - 1 two-week sprint for concepts, feedback & review, and new step issues written

**Comment by ackernaut** [comment]
@adaniels-parabol thanks! I added your question around which data source to our discussion tomorrow

**Comment by avivapinchas** [comment]
**Value: 5**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/1) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: L**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/2) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: M**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/2) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
Here’s [my initial proposal](https://www.notion.so/parabol/Domain-Stats-MVP-09c3c57236ce4ebf89bb4775f533c719#ab2ce34bf1e6436590aacb55b511f170) 🔒  for review (and the doc has a complete next pass in terms of an exploration)

**Comment by mattkrick** [comment]
LGTM!
Implementation issue: #6661

**Comment by ackernaut** [comment]
[Here’s an updated direction for this based on review and feedback](https://www.notion.so/parabol/Domain-Stats-MVP-09c3c57236ce4ebf89bb4775f533c719#88e057d809a948b9973d1ad01202912e
)
