### ISSUE TITLE
Invoice email copy and design

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6571]
If we send an invoice email, what does it look like? What’s the copy?

### Acceptance criteria
- Decided to use or update the simple email template (logo and copy), or do we need a different template, like a plain text template?
- Worked with Growth to develop copy

### Estimated effort
- 5 hours

### Related
- See burn-down issue #6574

**Comment by jordanh** [comment]
Customer requirements from #6825:

>Name and address of your company (service provider)
Our company name and address (being billed as customer / service consumer / customer)
Your company (service providers) tax number
Date of issuing of the invoice
Invoice number (unique / sequentially)
Quantity / Amount and of delivered goods or service
Date of (service) delivery, if not equal to Date of invoice
Price, including discounts (if not included in pricing), if applicable separated by different tax rates
included taxes (rate and amount included), or notice about tax exemption
VAT Number

**Comment by jordanh** [comment]
This is going to happen. It's going to happen this year I bet. But for now, it's going in the ice box
