### ISSUE TITLE
End meeting options

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6572]
We've heard a few times from customers that they want end a meeting without it sending a summary to the rest of the team. Some have even reached out to ask how to delete a meeting altogether.

This may be because they changed their mind on how the meeting is set up or maybe because they accidentally started the meeting in the wrong team.

I want to explore and discuss what would it look like if users had the option to delete a meeting after selecting `End Meeting` from the facilitator's meeting controls. The goal is to solve for the tension described above.

## Current behavior

Currently, when the facilitator selects `End meeting` from the facilitator's meeting controls, they are prompted to click again to confirm:

https://user-images.githubusercontent.com/3276087/168908728-146c3ae9-8820-4913-b302-0d4e28108385.mp4

Asking them to click `End meeting` again serves as a safety measure to avoid accidentally ending a meeting.

## My proposal

What if instead of the second click, we displayed a popup like this:

<img width="848" alt="Captura de Pantalla 2022-05-17 a la(s) 4 00 05 p m" src="https://user-images.githubusercontent.com/3276087/168909317-566b1798-5311-4d24-87b0-cad6f1b70986.png">

Effectively ending a meeting is still a two-click process, so we are not making it more cumbersome. However, we can now offer additional options for those cases where the facilitator wants more control for ending (or deleting) a meeting.

In the regular flow, the facilitator would just click the `End meeting` button and be done. However, in this proposal, they can un-select the option to email all team members before ending it, and even clicking the `delete meeting` text button below.

If they chose to delete the meeting, then we can present a new dialog to confirm the destructive action that is about to happen:

<img width="837" alt="Captura de Pantalla 2022-05-17 a la(s) 4 04 12 p m" src="https://user-images.githubusercontent.com/3276087/168909945-bbd370f7-bb62-4f20-8baf-d9a46c5889f0.png">

The facilitator will also have the option to choose `Cancel` in case they backtrack. Selecting `Cancel` closes the popup.

---

## How does this idea feel to you?

**Would this be unsafe to try?**
**Are there any other options worth considering for this end meeting popup?**
**How could we improve the wording here to make it super super obvious and clear?**

**Comment by avivapinchas** [comment]
I like the clarity! 🤔  I wonder if folks would want the 'send summary' setting on a per-meeting basis or just persistent across a team or meeting. I suppose we can start here and go from there. 

Does 'deleting' create a hard delete, or is it an archive (ie they can't see it, but the underlying data isn't actually destroyed)?

**Comment by enriquesanchez** [comment]
Thank you, @avivapinchas!

> I wonder if folks would want the 'send summary' setting on a per-meeting basis or just persistent across a team or meeting

That's a great question, and agree this feels like a good starting place. I lean for keeping the email summary as a default, as I feel is in line with the product's transparency value. But now that we have a setting or it, we can learn how much and how users tick it off, and make a more informed decision then.

>Does 'deleting' create a hard delete, or is it an archive (ie they can't see it, but the underlying data isn't actually destroyed)?

My expectation is that it should be a hard delete. Nothing should be kept or stored. Do you have a different idea?

**Comment by avivapinchas** [comment]
> Do you have a different idea?
That makes sense to me. The only times I can imagine folks wanting a delete, though, is: 
- They started the meeting by accident, so they want to clean it up 
- They have some kind of privacy concern and want data removed 

In the first case, I think an archive should be sufficient, and would be more reversible. In the second case, I'd imagine that they probably want to delete more things, so not sure if having that at the 'end meeting' button is that helpful.

**Comment by tianrunhe** [comment]
From data perspective, would "delete meeting" count as 1 meeting completed event?

**Comment by enriquesanchez** [comment]
>would "delete meeting" count as 1 meeting completed event?

@tianrunhe What would you expect? I personally think that if you delete a meeting I shouldn't get a meeting completed event.

**Comment by tianrunhe** [comment]
> > would "delete meeting" count as 1 meeting completed event?
> 
> @tianrunhe What would you expect? I personally think that if you delete a meeting I shouldn't get a meeting completed event.

Yeah that makes sense

**Comment by tianrunhe** [comment]
Another small thing to think about... today we have an "archive meeting" option in timeline (history: it was my BP project!)

<img width="609" alt="Screen Shot 2022-05-20 at 10 43 06 AM" src="https://user-images.githubusercontent.com/1879975/169583397-85c0daaf-ebe5-44a3-ad95-80006fd4f89f.png">

Almost nobody knows this feature 😂. In the backend it won't actually delete the meeting data, it's just used to hide that from the timeline.
I think it has some overlap with the awesome feature you designed here. Maybe we can consolidate a little bit here?

**Comment by jordanh** [comment]
Removing from backlog until this is resolved to AC and EE. Should this be a `design` issue?

**Comment by acressall** [comment]
@enriquesanchez I think there is _potential_ to propose this as a squad 2 experiment. If you think it's ready, can you put together an implementation issue?

**Comment by enriquesanchez** [comment]
>allowing the facilitator to set a global preference AND a team-member specific preference adds a little too much confusion

I don't see the confusion, but I may be missing something. The way I see it, if the facilitator decides that no email summaries should be sent for that particular meeting, then that's it. I doesn't matter what I have set as my personal notifications preferences because an email summary will simply won't be sent.

On the other hand, if the facilitator leaves the email summary on, then my personal notification preferences come in and those dictate what happens next. 

@mattkrick Would that not be the case? Is there more context I'm missing?

>since it's more like meeting management, could we move it to the actions menu of the meeting card on the /meetings route?

How would that flow look like? Would the facilitator have to exit the meeting (clicking on the Parabol mark or opening a new tab?) and find the corresponding meeting card?

I think this can turn dangerous if I make the mistake of selecting the wrong meeting card. We always say how hard it is sometimes to find the right meeting in /meetings. This is mostly due to the cards looking the same and having similar naming conventions. I think the same confusion can happen here when deleting one.

Being _in the meeting_ is the best way to know if that's the one I want to delete.

>offering an option to delete a meeting in the same modal as finish meeting feels dangerous

I personally don't think it's dangerous considering that the `Delete meeting` option is small and lower in the visual hierarchy, _and then_ we have a confirmation step with a big red button. 

But I am obviously biased here, what makes you feel that these are not enough to make it safe?

We don't have a `Settings menu` inside meetings (standups may have one though), but if we did, then that's where I would look at for a placement alternative for a delete meeting option.

**Comment by mattkrick** [comment]
> On the other hand, if the facilitator leaves the email summary on, then my personal notification preferences come in and those dictate what happens next.

you got it! the scenario that might confuse users is a meeting participant saying "hey parabol, we just finished a meeting & i didn't get a summary. why not? my settings say i get summaries after the meeting". that participant has no visibility into the option that the facilitator checked. emotionally, it takes agency away from the user. it's saying "you have a choice, as long as your choice is the same choice as the facilitator". 

> I think this can turn dangerous if I make the mistake of selecting the wrong meeting card. We always say how hard it is sometimes to find the right meeting in /meetings. This is mostly due to the cards looking the same and having similar naming conventions. I think the same confusion can happen here when deleting one.

if we can't trust users to click the right meeting, that's the root problem! Our UI should make it easy to click the right meeting without thinking. We should fix it instead of designing around it because we're gonna add more menu items to those cards & we want to be sure folks are clicking the right one with confidence. 

> But I am obviously biased here, what makes you feel that these are not enough to make it safe?

emotionally, it sends the wrong signal. imagine you just ran a meeting with your team. it was a great meeting! You're ready to end it & parabol is giving you the chance to delete it? Deleting a meeting is an antipattern that we actively want to discourage. we want you to have a long history of meetings that make you feel connected with your team & the product. if you're thinking about leaving parabol for a competitor, you should think twice because of your meeting history that you have with parabol. If we provide that as a secondary option, we're saying, "this is the 2nd most common action to take on a completed meeting". Heck no! We want you to end it successfully, share it with colleagues, tweet about how awesome it was, give us feedback about it, seek feedback from the participants... anything but delete it!

there is a good user story for deleting a meeting! maybe it was abandoned for 3 months & you don't want the participants to get the summary. In that case, I imagine the tension is that you have too many meeting cards, so you'd probably want to make the card go away.

I'm probably missing some other user stories! Let's share some more user feedback & see where their tensions are

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/72904151) 🔒 chatted in:

> how can I delete meetings?

**Comment by mattkrick** [comment]
that first comment is good! create a wrong meeting on the wrong team? you want to delete an empty meeting without emailing all the team members.

not sure about the 2nd. is archiving it good enough? if not, why not?
without knowing any more about the use cases, i'd say on /meetings on a meeting card we'd add an "Archive Meeting" option in the 3-dots menu. that's the same place it lives after the meeting is complete in a timeline event. if a meeting gets archived before it's complete, we just end it silently (no emails, no timeline events).

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/86385301) 🔒 writes:

> Hi! How can I delete meetings. I created some to test the features and I do not find any way to delete them.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/78683451) 🔒 writes

> Recently, my team had a retrospective meeting and at the end the summary was sent to everyone that is in that team. This is highly upsetting for a few reasons: 1) Never does it tell the user who is getting the summary before sending, 2) retros should be a safe space and we should not have to worry about anyone seeing what the team is saying, 3) it was sent to people that shouldn't have seen the retro conversations, 4) it makes no sense that the people in the meeting wouldn't be the only ones to get the summary.
> 
> This has affected our relationship with our client. There should be at LEAST a way to view who is going to get the report and remove people as needed prior to sending.

**Comment by malak-coforma** [comment]
Hi there! I'm not the above user, but I was in that retro and experienced the negative repercussions of how Parabol handled the retro summary. If I may, I'd like to add some extra feedback to the proposed modal in the original post here:

Instead of the single checkbox, it would be great if it allowed for "Send email summary to retro participants" versus "Send email summary to all team members".

**Comment by 87prashant** [comment]
> 1) Never does it tell the user who is getting the summary before sending

> There should be at LEAST a way to view who is going to get the report and remove people as needed prior to sending.

I feel that the users want to get full control over who is getting the email.
Apart from the default checkbox "send email summary to all team members"
We can add an option "or, Select here" or something like that.

Moreover, if a user participated in the meeting and expected the summary email (although it may be tricky to identify who is expecting the email and who is not) we can notify them with an alternative email that the meeting ended but the facilitator choose not to send a summary. 

What do others think about that? or is it too soon to judge?

**Comment by acressall** [comment]
@87prashant I think we'll want to give the control to each individual user to decide which emails they do and don't want to receive, which will be addressed in #4538 

> I feel that the users want to get full control over who is getting the email.

This makes sense when you think about sending an email directly -- you always decide who is going to get it. But by giving users the ability to decide what they see for themselves, we're creating transparency by default.

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/56279051) 🔒 writes:

> I schedule a lot of retros of different teams, and sometimes I need to cancel them (kill them with fire) but I dont know a graceful way to do this without just clicking next, which winds up sending an email to everyone. 
> 
> Could a cancel button be added, with a confirmation dialogue popping up, so I can kill unwanted meetings without spamming people?

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/67465801) 🔒 asked if there was a way to delete open meetings without sending the summary email to everyone.

**Comment by enriquesanchez** [comment]
A [user](https://app.hubspot.com/live-messages/3888472/inbox/4072665990#email) 🔒 writes:

> I accidentally ended a Poker meeting after all our team members had voted, without revealing any of the votes. It was shocking, and though I could go back to the meeting, it was already locked up in a read-only state, and nothing happens when I click the "Reveal Votes" button. There was no way to undo the End Meeting action and re-start the meeting.
> 
> I think, if the End Meeting action is one-way and cannot be undone, then it warrants a proper modal dialog confirmation dead-center in the screen, rather than just "Click again to confirm" on the same button. The confirmation must warn that "The meeting will be locked and placed in a read-only state. You will no longer be able to reveal any hidden votes or make any further changes to the meeting." or something like that.
> 
> This was an anxiety-inducing experience for me, hurting my mental health, as I couldn't make use of the votes my team had already given, and I had to bother them again to open a new meeting with the same set of issues and have them vote all over again. So I hope you can understand the gravity of my feedback.

**Comment by charlesmathias** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/31659701) 🔒 shared the following suggestion on where to include a "delete meeting" option:
![image001](https://github.com/ParabolInc/parabol/assets/101657889/2f133468-598a-4950-90a2-3ec989f8f309)

**Comment by charlesmathias** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/31659701) 🔒 suggested including a delete meeting option (where no email summaries are sent) in the 3-dot menu on the Meetings page.

**Comment by enriquesanchez** [comment]
Came up again during [User feedback retro #24](https://action.parabol.co/meet/qTPICRO3Li/discuss/4) 🔒
