### ISSUE TITLE
Cards appear in different orders for different users in Grouping stage

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#6582]
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/contact/69825751) 🔒 says:
> We noticed that the “grouping” step shows the cards in different orders depending on the user, which makes it difficult to go over each card and explain it (according to our process above).

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
We need to add a tiebreaker here: https://github.com/ParabolInc/parabol/blob/84aacf71d583f407468307d7f9a39fbfcc2f60be/packages/server/graphql/mutations/helpers/handleCompletedStage.ts#L46

`createdAt` would be a good one
