### ISSUE TITLE
Standups: Edit prompt when creating meeting

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#6585]
Meeting creator can edit the prompt when creating the meeting.

Designs - https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=1087%3A71021

Design issue - https://github.com/ParabolInc/parabol/issues/6069

Suggested backend approach:
* When updating the prompt from the new meeting view, persist the prompt to `MeetingSettings` for the team's `teamPrompt` meetings via a new mutation
* In `startTeamPrompt` mutation, initialize the prompt to the prompt in the team settings
* In `createTeamAndLeader`, initialize the meeting settings for `TeamPromptMeetings`
* Write a migration to add team prompt meeting settings to existing teams (see `packages/server/database/migrations/20200824105351-pokerTemplate.ts`).  This should initialize meeting settings the same as in `createTeamAndLeader`

AC
- [ ] New team prompt view shows an option for the prompt matching the designs
- [ ] Clicking the prompt option opens the modal implemented in https://github.com/ParabolInc/parabol/issues/6584
- [ ] Clicking "use prompt" updates the team settings for team prompt meetings, such that the prompt option is prepopulated with the new prompt when creating new team prompt meetings
- [ ] After creating the meeting, the edited prompt is shown instead of the default
- [ ] If the Parabol team chooses to change the default prompt for new teams, existing teams' default prompt does not change.

**Comment by jordanh** [comment]
@jmtaber129 iceboxing by policy, please re-open if this tension still remains
