### ISSUE TITLE
Profile & settings

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6596]
We have received enough signal from users that there is a need for a dedicated section in the app to manage preferences and settings.

Whether that's a need to change their password (see #5631, #6301, and #5632) or email (see #5630 and #5632), there is a common expectation for these types of settings to be available in any modern web app.

As our feature set grows, we are also discovering new opportunities to streamline the user's experience by offering preference and settings they can tweak to get a better use out of Parabol, such as notification preferences (see #6075).

The intention of this issue is to start a discussion and start exploring concepts and ideas so that we can give shape to this feature.

I started looking at the problem and came up with some mockups that should help us with that first step.

## Profile & settings

<img width="428" alt="Captura de Pantalla 2022-05-19 a la(s) 5 05 13 p m" src="https://user-images.githubusercontent.com/3276087/169412300-7e34dc99-cfda-4f47-af81-ed02f54a20c4.png">

Instead of simply having a `Profile` option under the user menu, maybe now we  have one called `Profile & settings` that takes you to a view that could look like this:

![image](https://user-images.githubusercontent.com/3276087/169412717-57c25859-e53a-4dac-acd0-8a90db5695f0.png)

...and it could contain subsections such as:

- Profile
- Notification preferences
- Account
- etc..

For example, we have been working on a color-blind friendly mode for template prompt colors, and we are not sure where a setting like this could currently live in the app. So maybe an `Appearance` sub-section for settings such at that one could work here. Or maybe we have a more general sub-section to house these and other one-off settings. The gist is that we now have a place for these settings.

### Notification preferences

One important piece of this feature is `Notification preferences`. This will be a much needed feature to have now that we are looking at [notifications for recurring activities](https://github.com/ParabolInc/parabol/issues/6075).

![image](https://user-images.githubusercontent.com/3276087/169413314-51bb8aef-7530-4889-9551-98fa4b3a3c72.png)

## Thoughts?

What are your thoughts on this? 
Should we be looking at different patterns?
Are there any other options that you think we should consider?

**Comment by jordanh** [comment]
Removing from Sprint Board until this is resolved to AC or EE (perhaps a new design issue is needed?)

cc @ackernaut, as this look roughly in bounds for Squad 3

**Comment by ackernaut** [comment]
I’ll throw it in the milestone for now as we decide what’s in, out, and rank where to start

**Comment by ackernaut** [comment]
Re: notification options

I like the idea of consistent notifications. You might see:

- Sections of notification types at the user level
- A row per notification in that section
- A column with a check per channel: in app / chat / email

You might see:
| Notification  | In App | Chat | Email |
| - | - | - | - |
| Lemonade stand new order  | ✅ | ✅ | ✅ |

The message may look like: “_The lemonade stand just received an order_. [See the order](www.parabol.co)” whether it was in the in-app activity view, an email, or a chat notif.

My open questions are:

- **How much of this is set up at the team settings level**? How do we handle that? Do we have a section with a link to all the settings view per team? I may like the notif for team A but not team B. I may have chat integrated for team B but not team A? It gets complex. I imagine many folks are on a single team so maybe we could simplify a la ‘don’t make me think’. Then maybe it’s progressively enhanced for a user on many teams, and maybe many orgs?
- **Do all notifs line up across the channels**? For example, I think there should be a simple **_meeting completed_** notif that could be sent to any of the 3 channels. It links to the meeting summary artifact in app. The email is no longer a summary but just a notif that links to the summary. How to share? I think that’s a different user job story. How should we share summaries, digests, etc. in the future? How do we make those interesting? I think the artifacts should be engaging to those interested and should have permalinks with some level of permissions (team, org, public? read-only? other actions?)

**Comment by jordanh** [comment]
I am sure this one is going to come back around :)
