### ISSUE TITLE
Standups: Discussion UX for long responses

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#6624]
## Issue - Enhancement
Discussion threads currently scroll in their own box below the response within the drawer, which is bad for responses that take up a large portion of the drawer height.  See https://www.loom.com/share/e6d0fc0ac7be45119744b25b9c9678c0

### Acceptance Criteria (optional)
- [ ] Users can easily scroll through the discussion on large responses

**Comment by jmtaber129** [comment]
@ackernaut curious to your thoughts on how we should fix this.  E.g. make the entire drawer scrollable, only pin the header and let the response scroll with the discussion, something else, etc.

**Comment by enriquesanchez** [comment]
>I think scrolling the whole thing makes sense

Plus one to this. I still think we should keep the thread heading sticky, so it's easier to identify what thread you are on, or who you are responding to. Something like this:


<img width="624" alt="Captura de Pantalla 2022-06-06 a la(s) 12 59 39 p m" src="https://user-images.githubusercontent.com/3276087/172218579-6a9bad66-58c6-4dbb-a173-77f3917ce45a.png">

So as I scroll down, the original response comments moves up out of view along with the rest of the comments, but the thread heading remains sticky in place. 

@jmtaber129 @BartoszJarocki thoughts?
