### ISSUE TITLE
Standups: Handle links in response cards 

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6630]
## Issue - Enhancement

Currently, we don't really handle links at all in our new tip tap editor. There's an extension for that: https://tiptap.dev/api/marks/link

### Acceptance Criteria (optional)
- [ ] User can paste link 
- [ ] User can format links manually 
- [ ] Links have the same style as in other parts of the application (discussion threads, tasks)

**Comment by ackernaut** [comment]
What does the UI look like for this? Do we use the same text and URL editing dialog? Do we use the same `cmd/ctrl + k` shortcut? Does this extension allow for a custom UI? Something else?

**Comment by BartoszJarocki** [comment]
@ackernaut good questions!

> What does the UI look like for this?

there's no default UI, we can build one - more info in general about having menus in tip tap - https://tiptap.dev/guide/menus 

> Do we use the same text and URL editing dialog?

For this task I'd like to get some low hanging fruits, ie. handling links at all (currently, you can't even open a link when you click it), maybe auto-linking text on pasting, etc

> Do we use the same cmd/ctrl + k shortcut

there's no default shortcut - https://tiptap.dev/api/marks/link#keyboard-shortcuts but I'm pretty sure we can implement it 

> Does this extension allow for a custom UI?

yes, we can build styling menus, not only for links and I think it'd be very beneficial - https://tiptap.dev/guide/menus 
I honestly still struggle with how things work in our current editor in tasks and discussion threads. I'd love to have something more explicit and obvious

**Comment by ackernaut** [comment]
@BartoszJarocki I like your instinct around low-hanging fruit. I like the idea of automatically applying links when pasted. A separate idea, maybe if a link is typed we could set the link and then a backspace would undo? I also wonder how we may explore quickly finding integrated items and referencing them inline (kinda like you can press # here in GitHub)

Re: more explicit, yeah this one is tricky. On one extreme I’d hate to see an editor toolbar anywhere you can edit. I wonder if we can drop hints in more places as to how to edit things including links.

**Comment by BartoszJarocki** [comment]
> @BartoszJarocki I like your instinct around low-hanging fruit. I like the idea of automatically applying links when pasted. A separate idea, maybe if a link is typed we could set the link and then a backspace would undo? I also wonder how we may explore quickly finding integrated items and referencing them inline (kinda like you can press # here in GitHub)

This would work similarly to autocorrection on Android, it might be interesting but it's IMO still very implicit

> Re: more explicit, yeah this one is tricky. On one extreme I’d hate to see an editor toolbar anywhere you can edit. I wonder if we can drop hints in more places as to how to edit things including links. In the meantime, it could be confusing to have different ways to create links in the app.

No, definitely seeing menus all the time is the worst. On the other hand, showing nice UI when user selects some fragment of text would be nice IMO, see the example below (UI would be up to us)
![CleanShot 2022-05-27 at 15 26 19](https://user-images.githubusercontent.com/1017620/170708986-e9d335ac-3160-4ebe-8aa1-6e3865903023.gif)

and yes, it'd be confusing to have different ways of formatting content in the app. Eventually, we'd need to migrate all editors to tiptap so I think it's a good time to think about what we like and what we could improve

**Comment by ackernaut** [comment]
@BartoszJarocki that minimal set of actions appearing on highlight is very interesting!

Ideas:
- we show the link action explicitly (on highlight), and a second button opens a dialog to learn all options & shortcuts
- we show a few basic formatting options, and a second button opens a dialog to learn all options & shortcuts
- we only show a button that opens a dialog to learn shortcuts

I wonder if we’ll develop a pattern for quickly referencing integrations inline or attaching to a card (like Jira or GitHub issues)

This also reminds me of Notions pattern for showing a pop-up when you past a GH link:

![2022-05-27 08 38 43](https://user-images.githubusercontent.com/307286/170710910-810a2b92-b5b1-4ab8-8977-33f64f7c159b.gif)

**Comment by BartoszJarocki** [comment]
@ackernaut I'd personally love to have all the basic options (most commonly used) appearing when I select a text. as long as it sounds bad, I really like when the app I'm using doesn't require me to think about how to do stuff. that kind of menu is very obvious and I think could work well. having an additional button to learn all the options and shortcuts is a wonderful idea! 

> I wonder if we’ll develop a pattern for quickly referencing integrations inline or attaching to a card (like Jira or GitHub issues)

I think doing this when way presented on GIF you've attached would be great and very future-proof. We could use it not only for existing Parabol integrations but for embedding loom, youtube, and stuff like that. 

CC @jmtaber129 this is a nice discussion, it'd be great to hear your thoughts too

**Comment by ackernaut** [comment]
I wonder how often folks discover the linking ability on task cards and thread comments? I wonder how many tasks and comments include a link that wasn’t pasted? It may be that we have an underused feature and we don’t realize it

**Comment by BartoszJarocki** [comment]
I'm not gonna lie, it took me a while to realize how our editor works. I also didn't know we have a shortcuts instructions page so I checked the code to understand how it works.

**Comment by ackernaut** [comment]
Here’s Notion’s toolbar that appears when highlighting text:
![2022-05-27 09 20 32](https://user-images.githubusercontent.com/307286/170718413-a1a5841e-15e5-4fae-8429-350d09deb701.gif)

**Comment by BartoszJarocki** [comment]
yeah, I like it. having a simplified version of that would be great, imo

**Comment by BartoszJarocki** [comment]
@jmtaber129 agreed, what's more, each of the actions could be a separate deliverable too. I'll start another task to kick off the discussion about the floating menu.

**Comment by enriquesanchez** [comment]
>I think doing this the way presented on GIF you've attached would be great and very future-proof. We could use it not only for existing Parabol integrations but for embedding loom, youtube, and stuff like that.

@BartoszJarocki  [We have a design proposal over here with a very similar pattern](https://github.com/ParabolInc/parabol/issues/5942), only the exploration was more focused on integrations links. I do look at other types of links further down on that issue's description, under Scope.

![image](https://user-images.githubusercontent.com/3276087/172226245-15594e61-3e72-4dd5-808e-0b5e666ec643.png)

I second @jmtaber129 suggestion of keeping the scope small for now. At the very least we should aim to have parity with how links work in other areas of the app. That means, I should be able to paste a URL and have it automatically turn into a link, or select some text and have the option to convert it into a link. 

For consistency and parity sake, I think we should start with the current method of using cmd + k. I also agree it's pretty hard to discover, but it's what we have for now.
