### ISSUE TITLE
Give users feedback that they need to vote in Vote phase

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6631]
In the Reflect phase, if the user doesn't add any reflections and tries to proceed to the Group phase, we give them feedback by preventing them from clicking "Next" in the control bar. "Next" is greyed out and there's a no entry icon on hover:
![control-bar](https://user-images.githubusercontent.com/39854876/170283821-fa843428-aa13-44e0-9d2c-02964be4547e.png)

In the Voting phase, if you don't vote on a group, you can't proceed to the Discuss phase, but the control bar doesn't give them any indication that that's the case.

![control-bar-two](https://user-images.githubusercontent.com/39854876/170284522-41c4405a-3843-4065-a0d2-ad34a0ff8608.png)

### AC

- [ ] If the user hasn't voted in the Vote phase, grey out the "Next" button and show a no entry icon on hover

**Comment by avivapinchas** [comment]
Suggestion: can we add some kind of tool tip or thingy that tells them what they need to do? Do we have any existing pattern for that?

**Comment by nickoferrall** [comment]
I don't think we're currently doing that in the meeting control bar but we could add it! I agree that a tooltip that pops up when the user hovers over the disabled "Next" button would be helpful
