### ISSUE TITLE
Showcase support, resources in the app, without having to recreate content

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6633]
Showcase support, resources in the app, without having to recreate content

### Purpose 
We have a variety of educational resources on our website [here](https://www.parabol.co/support/) and [here](https://www.parabol.co/resources/).  We want to help first-time users more easily navigate the challenges they may run into by showcasing some of this content in the app ([early design of this here](https://www.figma.com/file/XnPJgiNEA65oCI2MZXGzQN/Learning-Hub?node-id=705%3A1118)). 
We would want to show different content based on user attributes, like whether they’re a team lead, whether they were invited to the account or not, the number of meetings they’ve participated in and the types of meetings they’ve run. Propose a way to accomplish this, knowing that marketers primarily engage with WP as their single-source for managing content.

#### Open Questions
- How will we get content from WordPress? WordPress has an API built-in, but there is also a [WP GraphQL plugin](https://www.wpgraphql.com/). Which approach is best in the app environment?
- What user criteria is available to use for filtering content? Ex. amount of meetings participated in, amount of meetings run, which meetings run / participated in, size of team, number of teams, integrations activated
- What is the best way to structure the data? Should we add categories to posts so they are filtered, or create a custom post type referencing chosen pieces? Meaning, do we get _all_ the content and filter it, or get one category and then all the content associated with it?
- What impact will this have on performance / how can we mitigate the impact?

#### How this _could_ work in WordPress
- Our [Support](https://www.parabol.co/support/) and [Resource](https://www.parabol.co/resources/) content can have custom fields for editors to select (something along the lines of "display in product"
- Editors will then be able to select filters or categories that this applies to, which will be mapped to the filters in the product (ie. for users who have participated in >3 meetings)

## Acceptance Criteria
- We can successfully access WordPress content within the app
- We can filter the content based on user properties

_Not required for this project_
- Building out the WordPress architecture (we can create a test, or just pull existing Support or Resources posts)

**Comment by jordanh** [comment]
One other bit of AC to consider adding: what do we do if Parabol is deployed as a private instance, with no access to the internet?

In my opinion, it would be ok to omit the content but the app should not break

**Comment by jordanh** [comment]
This is still a great BP. Going to keep this one open
