### ISSUE TITLE
Bug: active meetings menu with standups

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6634]
### Reproduction
- Open a standup meeting
- Go to the new meeting view
- Open the active meetings menu
- Note the error if the team has an open standup meeting
- Teams with active meetings other than a standup don’t see the error

![Screen Shot 2022-05-25 at 14 05 35](https://user-images.githubusercontent.com/307286/170348960-3274fa4c-c39b-4061-98b3-7122a19da23c.png)

**Comment by ackernaut** [comment]
cc @BartoszJarocki @jmtaber129

**Comment by BartoszJarocki** [comment]
@ackernaut this has been fixed: https://github.com/ParabolInc/parabol/pull/6611. it was released today, I double-checked, and we're good!

**Comment by ackernaut** [comment]
Wow! Good deal!
