### ISSUE TITLE
Jira: automatic fix for `original` and `remaining` estimate field does not work for simplified projects 

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6638]
Following up the issue here #6589
Previous issue: #6637

Our current approach for adding missing Jira fields does not work for `simplified` projects.

To be able to set Original and remaining estimates fields 2 settings must be enabled:

1) Estimation feature must be enabled. See here #6637
2) `Time tracking` field should be added to the specific issue type

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/466991/170709022-3730aa5f-3000-4bda-9a85-f0ce7dbc53aa.png">

It looks like, estimation feature is not possible to enable using API: #6637

### Acceptance Criteria

- Check if it is possible to add `Time tracking` field using API
- If not possible show an error with suggested actions — "Enable estimation feature, add time tracking field"
- If possible:
- In `addMissingJiraField` try to add `Time tracking` to a specific issue type or maybe better to all available types if make sense
- If does not work, estimation feature is probably not enabled. Return an error with suggested action — "Enable estimation feature"

**Estimated effort:** 8h

**Comment by mattkrick** [comment]
agreed, perhaps we start tracking these new errors & if enough users encounter them we can build a more graceful solution then
