### ISSUE TITLE
In-app domain stats technical exploration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6639]
>When looking at my account I want a clear picture of usage so that I can make informed decisions about managing it, including upgrading.

To solve for this user job story we’ve manually shared Domain Stats. How might we make it easier to share these stats from within the app? We have more questions than we have answers around providing this.

### Open questions
- What information do we share today? How do we get it?
- What information do we need for a v1? Subsequent versions?
- Where would we get the data to provide these stats in the app?
- How would we connect the data source and the app?
- Do we start by requiring a Parabol admin to enable this on an account by account basis?
- How would Parabol admins enable it for a ‘domain of organizations’? Would they use a mutation in the existing admin interface? Something else? See #6646 
- Do we allow for different amounts of information to be shared? Do we initially share limited information to encourage them to reach out for the full data? If the users talk with sales, maybe they can turn on full stats then?
- How might we start small to learn what we truly need to support technically?

Some of these may be informed by UX design issues like #6568 and any smaller design issues we may break out from that issue.

### Acceptance criteria

- Create a list of issues necessary to build the following (will require a bunch of questions for @ackernaut & @gcrickman:
![image](https://user-images.githubusercontent.com/5514175/171257265-e7726e04-38a1-4902-ba01-8631fd771c31.png)

  
### Estimated effort
- 16 hours

**Comment by mattkrick** [comment]
All issues have been created & added to milestone https://github.com/ParabolInc/parabol/milestone/136

**Comment by avivapinchas** [comment]
**Effort: L**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/4) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by avivapinchas** [comment]
**Effort: M**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/4) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
