### ISSUE TITLE
User still able to use product after being removed from organization

### ISSUE THREAD

**Issue by tghanken** [ParabolInc/parabol#6641]
While trying to create a new team today, I noticed that Parabol doesn't think I'm in any organizations (userId = `google-oauth2|81Pbv6EBJ6`).

<img width="783" alt="image" src="https://user-images.githubusercontent.com/51011434/170799480-58db333f-41c5-4665-b6b3-db63141f2814.png">

After poking around on the backend, it looks like my OrganizationUser record was marked as removed on April 14th (I believe when we were removing users due to the "Remotely Agile" team).  This leads to a few questions:
- How have I been able to use the product since April if I've been removed from the organization?
- When viewing the Parabol organization through one of the teams I'm already on, why do I show as Active?
<img width="671" alt="image" src="https://user-images.githubusercontent.com/51011434/170799719-ebb93be4-f6ea-4de3-bd2b-a9fcdee42194.png">
- Is this happening to other users who have been removed from organizations, and are they still able to see their teams?

### Acceptance Criteria
- Confirm that this is not affecting more users, and that they cannot see information from organizations that they have been removed from.
- Identify if this happened due to manual data manipulation, or is a systemic issue.
- Cleanup my user record and any other affected Parabol users.
- Open a new issue with details if a systemic issue

**Estimated effort:** 1 hour to triage.

**Comment by nickoferrall** [comment]
Hey @tghanken, just wanted to double-check that you're still able to reproduce this?

I impersonated your account, and went to create a new team, but I could see that you're a member of the Parabol org:

![create-team](https://user-images.githubusercontent.com/39854876/195329751-3d42585a-ea75-47bf-a9dd-4560e3a598f3.png)

**Comment by tghanken** [comment]
I'm no longer able to reproduce this.  It may have been cleaned up automatically as I got invited to other teams in the Parabol org?

**Comment by nickoferrall** [comment]
Yeah, I think that's probably it. I can't see any other users affected, so I'll close this issue for now 👍
