### ISSUE TITLE
Unify the use of the global unique id for PostgreSQL objects

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6642]
GraphQL specification requires objects to have global unique id across the whole app: https://graphql.org/learn/global-object-identification/

Currently, we are creating individual global id generator function for every object type, for example:

https://github.com/ParabolInc/parabol/blob/7c60878ee1740fd9b60a1d62c10b584d04802d11/packages/client/shared/gqlIds/IntegrationProviderId.ts#L1-L4

For obejcts stored in postgresql, I suggest to do the following:

- Use `fromGlobalId` and `toGlobalId` functions from https://github.com/graphql/graphql-relay-js package
- Always use `string` type for `id` column in postgresql tables (Use `uuid_generate_v4()` for generating unique id)
- Always have an `id` column

### Acceptance Criteria
   - Change type of existing `id` columns (use `uuid_generate_v4()` to generate unique id)
   - Replace individual functions with `fromGlobalId` and `toGlobalId` where possible
   - Edit PR review guide to include above convention

**Estimated effort:** 21h

**Comment by Dschoordsch** [comment]
I think we could replace the id resolver instead with [`globalIdField`](https://github.com/graphql/graphql-relay-js/blob/d4c533fa0ebe866abe655262bf01999a1e2c984c/src/node/node.ts#L114).

**Comment by Dschoordsch** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/dNtK0rjNFS/estimate/4) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by tghanken** [comment]
Could whoever picks this up tag me once implementation begins?  I want to ensure there's no impact to our downstream data pipelines (although there shouldn't be as currently outlined).
