### ISSUE TITLE
Sprint Poker: GitLab v2: Push estimate to an issue

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6645]
GitLab supports an estimate field which can be pushed by a comment shortcut like `/estimate 4h`.

## Acceptance criteria
* [ ] added field voting option "Time estimate"
* [ ] persist choosen voting option
* [ ] vote is send to correct field

**Comment by jordanh** [comment]
Taking this out of the icebox

**Comment by charlesmathias** [comment]
[Team plan user](https://parabol.slack.com/archives/C4JAUUZ9P/p1733235277495949) 🔒  testing Self managed GitLab integration and considering upgrading to Enterprise:
> I’d love to have a sync option with Gitlab to have the Sizing appearing as a label on an issue.

**Comment by charlesmathias** [comment]
Thanks @Dschoordsch !
