### ISSUE TITLE
Parabol admins can require email verification

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6646]
This is #4805 Jr.

We want to experiment with ways to support accounts, like e.g. turning on domain stats for a user. We want to make sure these users are legitimate.

### Open questions
- Do we want to create a single mutation that both turns on domain stats and requires verification for 1 or many emails, or an email domain? If the mutation turns this on, will it immediately sign out those users, or will they be able to see the domain stats while they are logged on?
- Can we sign folks out immediately?

### Acceptance criteria
- Parabol admins can use a mutation to require email verification:
  - The mutation can accept 1 or many emails, or an entire domain (e.g. *@parabol.co)
- These users get a simple email (template and copy design issue TBD)
  - They click a button and/or link that takes them to their `/me/profile` view
  - There’s a confirmation message (to be designed)
- There’s a way to query and see that a user’s email is verified
### Estimated effort
- TBD in Sprint Poker

**Comment by ackernaut** [comment]
cc @gcrickman @mattkrick thoughts?

**Comment by mattkrick** [comment]
related #6095 (which is almost complete).
TBH i can't remember if i incorporated this functionality in that PR or not

**Comment by ackernaut** [comment]
**Value: 3**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/5) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
**Effort: M**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/6) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by mattkrick** [comment]
We actually have this functionality today called "SecureDomains". it's how we prevent people from creating "help@parabol.co" and then pretending to be us. 

how we do that has been refactored in: https://github.com/ParabolInc/parabol/pull/6487/files

closing in favor of https://github.com/ParabolInc/parabol/issues/6663
