### ISSUE TITLE
visiting root poker meeting URL redirects to /meetings

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6647]
we've got a problem with poker meetings.
meetingId: `dHOSUUpFO8`
when visiting the root url it redirects to /meetings.
when visiting a route inside the meeting like /estimates/24 it works, but the other phases are "no-click"

AC
- [ ] triage root cause

Estimate: 2 hours

**Comment by Dschoordsch** [comment]
Duplicate of #6674?

**Comment by mattkrick** [comment]
i believe so, yes. will close
