### ISSUE TITLE
Onboarding: Create an onboarding team with onboarding tasks

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6651]
Create an onboarding team which is filled with some tasks like:
* run the demo
* create a team
* invite new members
etc.

**Comment by JimmyLv** [comment]
Hi @Dschoordsch , what is the definition of an onboarding team here, and is it the same as the first team created by default with the 'user name' as the team name?

**Comment by JimmyLv** [comment]
Could I treat the other issue https://github.com/ParabolInc/parabol/issues/6719 as the third point of this task? Or is this task just a discussion and will be broken up into more smaller tasks?

**Comment by acressall** [comment]
I left a draft of the tasks and related copy [in Notion](https://www.notion.so/parabol/Onboarding-Create-an-onboarding-team-with-onboarding-tasks-c6fa6ab6a1924757b5f11b3853158418), and asked [in Slack](https://parabol.slack.com/archives/C2790TSTT/p1655926853618719) for a copy review.

**Comment by acressall** [comment]
Moving this back due to feedback in #6719 that user's complained about new tasks! I'll bring this back to design and see if there's another way to promote these actions

**Comment by jordanh** [comment]
@acressall may I recommend opening a design issue you could sprint on to explore alternatives to #6719? I'd like to close this issue if the next steps are murky...

**Comment by acressall** [comment]
Yes, let's close this one!
