### ISSUE TITLE
Questionnaire for early dropped off users

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6653]

**Comment by acressall** [comment]
I've put together a few designs for placement of a questionnaire. I'm thinking in all cases we can link out to the questionnaire (Typeform, Maze, or a form on the website). 
https://www.figma.com/file/F7fujE4V5GhGcloomQvtuU/Feedback-Survey---Early-dropoff?node-id=0%3A1

**Comment by acressall** [comment]
Option 1: adding a new card to the timeline view. I _suspect_ this view isn't visited often, and those that go there are more likely to have already become an "active" user, but that might mean they're more likely to spend the time giving feedback 🤷 


![Image](https://user-images.githubusercontent.com/18582225/171488700-855cc694-51d7-4144-abc6-eb695bd4c848.png)

**Comment by acressall** [comment]
Option 2: Adding a button to the summary. 
Both a positive and a negative is the user won't see this until they've already run their meeting. 


![Image](https://user-images.githubusercontent.com/18582225/171488851-ccb3b001-5cde-4819-b85a-8c8575cebc54.png)

**Comment by acressall** [comment]
I like this idea! I think we should backlog it though -- right now we have the "add a meeting" button in that location, and I think it would be good to run the test on the placement of that before we put something different there. 

I like the idea of the stars for rating directly, but do you think that info would be helpful? I don't think a _good_ rating would actually tell us anything, and if it's a bad rating I would want to know _why_. 
Maybe if they give it a low rating, a textbox appears asking them to add more detail?

**Comment by avivapinchas** [comment]
> I like the idea of the stars for rating directly, but do you think that info would be helpful?
> ["How likely is it that you would recommend Parabol to a friend or colleague?"](https://tyrrellaccountants.com/2022/01/23/how-likely-customers-recommend/)

FWIW, NPS (the 'how likely are you to recommend') is not that helpful ([some data on this)](https://hbr.org/2019/10/where-net-promoter-score-goes-wrong), but we've talked about a Q that aligns more to our mission: 
"Was that meeting worth the time?" 

We asked a [similar Q in the onboarding flow](https://www.notion.so/parabol/How-was-it-Q-in-Onboarding-Email-flow-EPIC-d50e61937ea14a7e90ba276a619a06f3), and what we found was: 
- No one clicks the 'no' or 'bad' button - I'd guess they don't find it useful to give us feedback if they had a bad time
- Lots of folks click yes or average - I think 'average' is probably where some of the interesting info lies, as it's folks who were willing to reply but weren't wowed.

**Comment by acressall** [comment]
I think for the sake of simplicity and seeing what info we get, we should stick to linking out to a form -- and if we find we get engagement, we can look into doing something in the app later. 

@Dschoordsch I'd like to propose we go with Option 2 (meeting summary) as a really quick option, and potentially adding option 3 (help menu) and we can see which location does better. WDYT?

**Comment by Dschoordsch** [comment]
Going with options 2 and 3 is the easiest right now. Let's see how it performs. I have some concerns that the interesting users may either not get to the meeting end view or not see the button, but let's try it anyways.

**Comment by acressall** [comment]
Agreed! I had another idea from this... people might be more like to _ask a question_ rather than give feedback. There have been discussions around adding the chat window from the website into the product and I wonder if we should explore that too. 

For now, I'll make an implementation issue for the survey to stick in the backlog, and a design issue for the chat placement

**Comment by acressall** [comment]
Updated proposal: https://parabol.slack.com/archives/C03GZQJ27MG/p1654718453484139

Using the chatbot feature in HubSpot means we can write, update, and turn on the "script" in HubSpot without needed to update anything in the code

**Comment by acressall** [comment]
Implementation issue: #6718

**Comment by Dschoordsch** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/e4unKJcXHW/estimate/1) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
