### ISSUE TITLE
Decrease demo drop off

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6654]
We have quite a big demo drop off from first to second step [45%](https://analytics.amplitude.com/parabol/chart/z69dbio?source=space) and also from last step to the meeting summary 53%.

The first drop off could happen because
* users entered the demo without knowing what to expect
* users did not understand how to proceed

**Comment by Dschoordsch** [comment]
Looking at session replays it appears as if users are a bit lost. No reflections are added and it appears as if it's not clear what's happening. I propose adding a video overlay/split view which shows one of us explaining sth. along the lines of:
"We're running the Demo Retrospective adding reflections. Our Intern Isabel and Operations Oscar are already typing and adding some reflections. Please press next once you're ready to move to the next stage."

**Comment by acressall** [comment]
This is an interesting concept @Dschoordsch! I really like the idea of combining video and interactivity
