### ISSUE TITLE
Domain Stats: Aggregate Insights Panel Frontend 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6661]
Designs to implement here: https://www.figma.com/file/454u4uRYZlZMtmUtgQAQ3G/Domain-Stats-v1?node-id=139%3A9513

AC
- [ ] When you click your avatar on the dash, you see a link to "Usage" if the insights feature flag is turned on. It goes to /usage route
- [x] a "paid domain" is defined as a domain with at least 1 organization at the pro or enterprise tier.
- [x] if domain is unpaid, `suggestedTier` is set to the first non-null `OrganizationUser.suggestedInsightsTier` within the domain   
- [x] for every domain that includes at least one `OrganizationUser.suggestedInsightsTier` is not null, usage stats panel is shown
- [x] if the domain is paid, no nag panel is shown
- [x] if `suggestedTier === 'pro'`, Upgrade CTA is shown
- [x] if `suggestedTier === 'enterprise'`, Contact Us CTA is shown

Estimate: 16 hours

**Comment by avivapinchas** [comment]
@mattkrick This AC needs an update - it doesn't match what @ackernaut proposed

**Comment by ackernaut** [comment]
LGTM!! 👍

**Comment by avivapinchas** [comment]
This LGTM! 

I'd also like an event sent for when the snackbar is viewed, that way we can understand how effective the snackbar is at drawing the users' attention.

**Comment by mattkrick** [comment]
> when the snackbar is viewed

how would you like to count a "view"? once per session, once per appearance (assuming they dismiss it)?

**Comment by avivapinchas** [comment]
I think once per session, but honestly whichever is easier. Amplitude lets us look at uniques (essentially meaning users) and totals, so I'll probably look at unique to click conversion rate.
