### ISSUE TITLE
Domain Stats: Backend mutation to flag PQLs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6662]
<details>
<summary> Thought process</summary>
Today, a user's company is calculated from their email domain.
That means if we turn on `User.featureFlags.insights`, they'll only see insights for the domain.
That means consultants wouldn't be able to see those insights since they wouldn't have the same domain.

So we've got a problem. Today, 1 user has many orgs, and each org could have a different company. ergo, 1 user has many companies. We can either force 1 user to 1 company, or we can show multiple insights, 1 for each org that they're in.

```gql
viewer {
  organizations {
    company {
      id
    }
  }
}
```

today, 1 company = 1 domain. we need to fix this. 
we kinda handle this in the SAML table. a SAML id is like a company, which then has multiple domains.
what if we break that link out into its own table?
Company table has:
- id
- name
- domains (array?)
- contacts/leads (array?)

in 3NF we'd need 3 tables:
Company table:
- id
- name
CompanyDomain table:
- domain
- companyId
CompanyContact table:
- companyId
- email/userId

not sure what to do about leads, stick them in the OrgUser? the challenge today is that domain & company are synonymous. we need to separate them out like we do in the SAML table.
We get that with the first 2 tables, but the company contacts is tough. this is a trait for a user set by a salesperson. i'd like to build this to support 1 user belonging to multiple companies because it's cheap to build it that way now, but it'll be expensive if we need that later.
so, 1 user has many orgUsers, 1 orgUser has 1 organizations, 1 organization has 1 company (which is currently calculated by activeDomain). So, since 1 org has 1 company, we can put it on the OrgUser document.

then again, hubspot already does a good job of extracting the Primary company from the user.
what if we just use hubspot as the single source of truth? or at least as a good default value.
</details>

v1: Insights for invitees 
- `insights` is added as a feature flag, when true, the insights link appears in the dash
- `allowInsights` is put on the OrganizationUser. that way we don't have to force 1 User to be attached to 1 Company.

v2: Insights for all (waaay out of scope, maybe we never do this)
- Everyone sees the insights link
- in addition to `allowInsights`, if your email address is verified, you can see the insights for the domain attached to your email.

AC

- there is an `insights` featureFlag
- there is a `toggleInsightsContact(value: Boolean!, domain: String!, emails: [String!])` mutation on the private schema. Calling it will set `isInsightsContact` to true for every OrganizationUser that is apart of an Organization where `Organization.activeDomain === domain`. If `value === false`, then that field is unset for everyone in the emails arg. if emails arg is empty, then it turns it false for everyone in every org. if `value === true`, then emails is non-null (because setting it for everyone at once is risky).

Estimate: 16 hours

**Comment by Dschoordsch** [comment]
I don't know what PQL means and a quick google just shows "process query language", so could we name it something clearer?

**Comment by mattkrick** [comment]
that's good feedback, it's a sales term "product qualified lead". 
i should dig a little deeper into all the stats that we use for the sales team, perhaps this would make a better enum

**Comment by jordanh** [comment]
Let's talk about naming such a table.

Not all Organizations are Companies (e.g. the US Airforce, NGOs, Non-profits, heck even departments within Companies. Some possible options:

- OrganizationDomains (or OrgDomains)
- OrganizationGroup (or OrgGroup)

Personally, I think `OrganizationGroup` is most clear...

What are your thoughts?

**Comment by mattkrick** [comment]
Yeah, Company isn't great, we can change the name in this milestone, but it already existed for hubspot reasons (that's where the name came from...).

I think I found a way to avoid new tables, at least for now...
Today, 1 company = 1 domain, which isn't 100% accurate.
If we need 1 company to support multiple domains, then we'll need to do that work now.

**Comment by avivapinchas** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/e4WY6u2dfq/estimate/2) in Sprint Poker #​​2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
