### ISSUE TITLE
Domain Stats: Force email verification for members of PQLAccepted domains

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6663]
Predecessors: #6662 #6487

AC

- [ ] If a user signed up via email/password & they're a part of an org that is a part of a company that is `PQLAccepted`, then their email must be verified the next time they try to login
- [ ] We can piggyback on some of that logic already used here (https://github.com/ParabolInc/parabol/blob/6c1103a3fa81b754db4f271528b762ae61d96434/packages/server/graphql/mutations/signUpWithPassword.ts#L77)
- [ ] if they're already logged in, before issuing a fresh JWT we perform this check as well & invalidate the JWT if it fails the test

Estimate: 8 hours

**Comment by mattkrick** [comment]
>  I wonder whether we should add user friction just as the company is deciding whether to upgrade?

Totally valid point. If not now, when?
We could get away with using unverified emails in the aggregated metrics.
However, the next question in the sales process would be "who else is using this?". At that point, we'll need to show them email address. If we show an unverified email address (e.g. poopoohackerface@enterprise.co) it'll make us look bad. conversely, if our aggregated metrics say "100 users" and we only show 10 emails, then that can look fishy, too.

if there's another time to force verification, i'm all for it!

**Comment by avivapinchas** [comment]
> If we show an unverified email address (e.g. [poopoohackerface@enterprise.co](mailto:poopoohackerface@enterprise.co)) it'll make us look bad.

Meaning: if the email address doesn't really belong to the company / isn't real, right? Because an unverified but valid email address wouldn't look bad, I think 

> conversely, if our aggregated metrics say "100 users" and we only show 10 emails, then that can look fishy, too.

Couldn't we be explicit at that stage, and say "this is the list of *verified* addresses - for privacy reasons, these are the only ones we can show" or something like that?

**Comment by mattkrick** [comment]
> Couldn't we be explicit at that stage, and say "this is the list of verified addresses - for privacy reasons, these are the only ones we can show" or something like that?

absolutely! but our aggregated metrics are using unverified emails, so the scenario i'd like to avoid is if we told someone that their company had 100 users & when they said "show me" & we could only show them 10

**Comment by mattkrick** [comment]
Closing because showing a list of email addresses is no longer in scope.
With the updated business logic, only enterprise PQLs will see into orgs that they aren't a part of. If there is a bogus person on a standalone org that gets added to the total that's probably OK for now since the stats will just be aggregates.
