### ISSUE TITLE
Design: "step-by-step" user guidance for the first time Parabol users

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#6673]
## Issue - Enhancement

As we talked in [Slack](https://parabol.slack.com/archives/C03GZQJ27MG/p1654134670310269?thread_ts=1654092809.253259&cid=C03GZQJ27MG), we would like to try to add "step-by-step" user guidance for the first time Parabol users, when the meeting only has one attendee + that attendee is the facilitator.

There are some out-of-the-box technical implementations: Tourist Guide demo: https://reactour.js.org/

and more: https://www.npmtrends.com/react-joyride-vs-react-user-tour-vs-reactour-vs-intro.js-react

![step-by-step  user guidance-Meetings  Parabol-002959-20220603](https://user-images.githubusercontent.com/4997466/186732678-0d33fc44-f202-4df4-a63f-bb04937b96c4.gif)

This issue is meant to be a demonstration technically, and to follow up we need to define more about 1. where each step is to be displayed 2. and what the hints are.

### Acceptance Criteria (optional)
Users can:
   - follow the "step-by-step" user guidance
   - to finish the Retrospective meeting steps
   - can select to the next "step"

**Estimated effort:** 3 hours

**Comment by jordanh** [comment]
As I Icebox this, I have a few notes to add: as PM, I _hate_ step-by-step instructions for users. Needing them, to me, makes me feel like our design has failed. Our design should be clear enough on its own not to necessitate this kind of onboarding experience.

That said, I realize I can't speak for all user's preferences. Should we ever decide to design/implement such a user journey I'd recommend it be optional (i.e. not the default), e.g. "show me step by step"
