### ISSUE TITLE
Standups: Show bubble menu when selecting a text fragment

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6678]
## Issue - Enhancement

Implement a floating menu that pops up when selecting a text fragment in the editor, here's the [context](https://github.com/ParabolInc/parabol/issues/6630#issuecomment-1139623028). 

The menu should have all the most commonly used options available - bold, italic, strike, and link. possibly a link to learn more shortcuts. The reason I'd like to have an explicit way of setting most basic styles is that it took a long time for me to discover the shortcuts we currently have. Before this task can be implemented, the designs are needed. Note this will probably affect all the editors we have, including tasks and comments so the discussion is needed if this is an appropriate solution.

### Acceptance Criteria (optional)
- [ ] A bubble menu shows up when user selects the text
- [ ] bold action is available
- [ ] italic action is available
- [ ] strike action is available
- [ ] link action is available 
- [ ] all the above works for selected text

**Comment by enriquesanchez** [comment]
This is such a great idea. I really like how it's a "there when you need it" type of UI. Only appears when some text is selected. It also doesn't have to be complicated, something super lightweight and simple would be more than enough:

<img width="983" alt="Captura de Pantalla 2022-06-06 a la(s) 5 24 32 p m" src="https://user-images.githubusercontent.com/3276087/172259271-e910274e-79fb-4e82-82b7-53748478207c.png">
