### ISSUE TITLE
Standups: Do not show inactive users in the responses grid

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6679]
## Issue - Enhancement

In bigger teams, there are team members that are not active. I'd say we shouldn't show response cards for users who were not seen in the last 30 days. That kind of user would get his response card when joining the meeting. Otherwise, their cards only take space for little to no use. 

I can see a couple of ways to accomplish it

Client-side
1. when building an array of responses, check `teamMember.user.lastSeenAt` and filter users who were not seen for X days
2. it could be useful to add `lastSeenAt` to the `TeamMember` gql type to prevent deep nesting; `TeamMember` gql type already has a bunch of properties denormalized from `User` type so doing that should be ok. one way or another, it shouldn't be a problem. 

Server-side
1. When creating the `TeamPromptResponseStage` for each team member when async standup is being created, do not create the stage for the user that wasn't active for X days. 
2. if the previously inactive user joins the meeting, create a `TeamPromptResponseStage` for him in `joinMeeting` mutation; it's a similar case for when a new user joins the team _after_ the async standup has been already started

### Acceptance Criteria (optional)
- [ ] Inactive user isn't showing on responses list
- [ ] When an inactive user joins, his response card is shown correctly

**Comment by BartoszJarocki** [comment]
I'd personally head towards the client-side solution. The server-side causes de-sync between team members and `TeamPromptResponseStage` (ie. some users won't have the object).  The client-side solution has different issues, over fetching data, client-side filtering always adds some complexity.  Before starting the implementation it'd be best to talk to @Dschoordsch or @mattkrick

**Comment by Dschoordsch** [comment]
Interesting, I would have leaned towards filtering server side. To me this seems like less complexity. The `joinMeeting` logic could be reused and I don't see the problem of not having a stage for each user. But as soon as a user joins, they would get their stage and all clients would be notified. Seems way less work to me and fewer chances of messing things up.

**Comment by mattkrick** [comment]
well now you got me thinking...

TODAY
- when a meeting is started every team member is added as a meeting member
- if someone joins the team, they're added as a meeting member

CLIENT-SIDE
- when a meeting is started every team member is added as a meeting member
-  in active meetings, the client checks the `user.inactive` prop and filters out inactive ones that do not have a response

SERVER-SIDE
- when a meeting is started every **_ACTIVE_** team member is added as a meeting member
- when someone reactivates, nothing happens
- when someone joins the meeting, they're added as a meeting member

The only edge case I can see is what if someone goes inactivate while a meeting is in progress? If client-side, they'll be hidden. If server-side, they'll still be visible. Maybe we do both server & client side? 😆  kidding...,either is fine by me!

**Comment by jordanh** [comment]
@BartoszJarocki iceboxing this one by policy. Please reopen if if the tension still remains/you'd like to prioritize it
