### ISSUE TITLE
Analytics for new Domain Stats implementation

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6681]
## Issue - Enhancement

Starting a list of events we'll need to measure the effectiveness of this effort. I see a need for tracking: \
- Viewing the snackbar
- Clicking on the snackbar CTA
- Viewing the stats page (they may find it without clicking the banner) 
- Clicking the CTA, including what type of CTA it is (`contact us` or `upgrade now`) 

### Acceptance Criteria (optional)
- [ ] there is a nagging snackbar with a "See Usage" CTA. If dismissed, it reappears in 3 minutes. It is visible on every route (including meeting routes) except /usage
- [ ] above 4 events are sent to segment

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by avivapinchas** [comment]
> just wondering what banner this refers to? I don't see a banner in the [figma designs](https://www.figma.com/file/454u4uRYZlZMtmUtgQAQ3G/Usage-Stats-v1).

Ah sorry - should be snackbar, updated above 

> is it safe to remove it from the Growth Sprint?

Yep, removed

>  the nagging snackbar could be implemented in a separate issue to keep PRs as small as possible if that works for you?

No pref on my end :)

**Comment by nickoferrall** [comment]
Cool, thanks! I've created a PR https://github.com/ParabolInc/parabol/pull/6764 to track when users visit the `/usage` page and when they click the CTA. 

At the moment, I'm sending the `domain` to Segment and the CTA type when they click the CTA. If there's any more data that you'd like recorded, just let me know!
