### ISSUE TITLE
"X has asked to be invited to team" snackbar changed to queue

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6686]
## Issue - Enhancement

Today, when users try to get access to a team that they don't yet have access to, we'll pop up a snackbar for team members who are online at the same time. These snackbars can be easy to miss, or hard-to-manage if a bunch of folks make the request at the same time. When a team member logs in later, you may see a snackbar notification and be unsure when it was requested or if it's been resolved. 

If a member isn't granted access immediately or if there's a bunch of requests at once, we should create a queue of some kind, rather than a snackbar. 

Possibly related: #6399

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by enriquesanchez** [comment]
>I wonder if your activity view helps to solve this?

@acressall I think the Activity view is the perfect spot for these.

Having more space to work with should also help us solve for the tensions described above:

>you may see a snackbar notification and be unsure when it was requested or if it's been resolved.

The activity view entry could offer this information as well, since they can be "live" items. Something like `Access granted by Aviva on June 13 at 13:35`

**Comment by jordanh** [comment]
This is still a good issue, but iceboxing. Reopen if this causes tension
