### ISSUE TITLE
Standups: Improve UX when submitting standup responses

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6688]
Currently when submitting a standup response, there is no clear action to submit a response. Of the common ways for submitting a text input, none are present:

1. Pressing <kbd>Enter</kbd>: this does not work how we would expect based on the behavior of reflection cards, instead it creates a new text paragraph inside the response.
2. Submit button: there is no button to submit the response, opposite of how submitting a comment in a thread works.

[This has already come up in user feedback sessions](https://www.loom.com/share/d958ddc72d4a4dfa928a06244069e9b2#), where folks are confused by the lack of a clear action, and instead think the `Reply` button is the action for submitting.

The only way for users to "leave" editing mode of a response card is to click elsewhere.

In addition to a lack of clear submit action, the presence of both the `Reply` and reacti buttons can cause additional confusion, particularly because at the moment, there is nothing to reply or react to. 

<img width="300" alt="Captura de Pantalla 2022-06-07 a la(s) 4 34 37 p m" src="https://user-images.githubusercontent.com/3276087/172489745-42d1124f-7dec-4dd3-ba76-195c42d33b55.png">

## Proposal

Let's add a `Submit` button and show the reply and reacti button only once a response has been submitted:

### When it's empty:

<img width="400" alt="Captura de Pantalla 2022-06-07 a la(s) 4 57 45 p m" src="https://user-images.githubusercontent.com/3276087/172489875-f900c0eb-771c-4693-8aed-a76f600368d1.png">

The response card shows the placeholder text and a disabled `Submit` button.

### When a response is entered

<img width="400" alt="Captura de Pantalla 2022-06-07 a la(s) 4 58 34 p m" src="https://user-images.githubusercontent.com/3276087/172489998-da24b069-1897-4947-9d5d-74c94df643cc.png">

The `Submit` button becomes active and the user can click it now.

### When a response has been submitted

<img width="400" alt="Captura de Pantalla 2022-06-07 a la(s) 4 59 09 p m" src="https://user-images.githubusercontent.com/3276087/172490083-5c9ae924-7a66-4f2a-8391-0f0263905905.png">

The `Submit` button goes away, and now we can display the `Reply` and reacti buttons.

### Replies and reactions

<img width="400" alt="Captura de Pantalla 2022-06-07 a la(s) 4 59 54 p m" src="https://user-images.githubusercontent.com/3276087/172490219-d86b411e-fe91-416b-bc11-0f068ce09d30.png">

Replies and reactions can continue behave the way they currently do. 

### When editing a response

<img width="400" alt="Captura de Pantalla 2022-06-07 a la(s) 5 00 46 p m" src="https://user-images.githubusercontent.com/3276087/172490294-236e4eee-9cd4-49e6-81c7-7b102050f352.png">

Only authors can edit their own responses, and so if they click anywhere inside the text area (similar to how task cards work), they can edit the reponse and a `Update` button appears so they can submit the edits.

-------

[**Figma file**](https://www.figma.com/file/fw5gj7qRbKSh5XQbnh0PUr/Standups-tweaks?node-id=4%3A2871)

------

# Acceptance Criteria
[ ] Users have a clear action for submitting a standup response card
[ ] When a response card is empty, waiting to be filled out, there are no other actions that can cause confusion on how to submit a response

**Comment by jmtaber129** [comment]
LGTM! Excited for this

**Comment by jmtaber129** [comment]
@enriquesanchez a couple clarifying questions:
1. If someone edits their response to be entirely cleared after initially submitting a response (i.e. submit, edit, then delete the entire response), should we:
a) Do the same thing as if they were simply editing their response
b) Keep the update button enabled, but change the copy to "delete"
c) Disable the update button
d) something else?

2. What should we do if someone starts editing their response, but decides they no longer want to edit their response?  E.g. slack includes a secondary "cancel" button when editing messages - I think this is probably the way we want to go

**Comment by enriquesanchez** [comment]
>If someone edits their response to be entirely cleared after initially submitting a response

I feel this should count as "deleted" and maybe we return to the initial empty state? Which means that the `Update` button returns to read `Submit`?

>What should we do if someone starts editing their response, but decides they no longer want to edit their response? 

Oh yeah, that's a good point. We can have a `Cancel` text button next to `Update`:

<img width="484" alt="Captura de Pantalla 2022-06-16 a la(s) 12 06 23 p m" src="https://user-images.githubusercontent.com/3276087/174127076-a5d6d6f7-3700-40b4-b833-0375af81a471.png">


>Should the Update button appear only after the user starts editing, or as soon as the text input has focus?

🤔 If I only focus text input on the card, then nothing has really changed, right? In that case, there is yet nothing to update. So maybe only once a change has been registered?

What do you think?

**Comment by jmtaber129** [comment]
For (1), I mean specifically the point in which the user has removed the text from their response, but the response hasn't been submitted yet.  E.g. I submit my response, then go to edit my response and clear the whole thing out - when I go to hit submit after deleting all the text in the box, what does the "update" button look like?

Yea, I think we should only show the update button after the text has changed.

**Comment by enriquesanchez** [comment]
>when I go to hit submit after deleting all the text in the box, what does the "update" button look like?

Got it, thanks for clarifying! 

I think c) is right then. The `Update` button should be disabled, and they should also see a `Cancel` action to undo everything and go back to how it was before.
