### ISSUE TITLE
Poker: undefined Label when estimating Parabol issues

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6710]
* Add a parabol issue to poker meeting scope
* Estimate
* See undefined Label

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/466991/172855504-a8c0c3e6-3eb2-46a1-986d-5e343e303a5c.png">

https://www.loom.com/share/39125cf4d55b4e749d0b27b327d22de1

AC:

* Can successfully estimate parabol issues

Estimation: 4h

**Comment by Dschoordsch** [comment]
Surprisingly many folks use Sprint Poker with Parabol tasks.
