### ISSUE TITLE
Password reset problems

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#6712]
I'm turning a discussion we had into an issue and we'll continue to record when users have password reset problems here. There seems to have been an unusual amount of requests coming into support in the last 2 weeks.

Here's the original discussion https://github.com/ParabolInc/parabol/discussions/6301

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/74598901) 🔒 writes:

> I have created a parabol account using my mail id, but I am not able to login to my account and also I tried resetting the password. I am not able to do that also.
> 
> Please do what is necessary so that I can access my parabol a

ccount.

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/80936701) 🔒 writes:

> I’m having issues logging into my account in Parabol using the email _____. I was able to receive one password reset email, but it said my token has expired. I have since tried to request new password reset emails, but with no luck. I didn’t see any additional pw reset emails in my junk, spam, etc. Can you please assist me with getting back into my account?

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/54036051) 🔒 writes:

> Good morning,
> I’m hoping you can help me. I am attempting to access my account however the login page doesn’t appear to be accepting my username and password. I have subsequently tried to reset my password but I get a message stating something went wrong

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/66255801) 🔒  writes: 

> Hi,
> When I try to get forgot password, I am getting an error

**Comment by drewhousman1010** [comment]
A u[ser](https://app.hubspot.com/contacts/3888472/contact/58620701) 🔒  writes:

> I still have problems resetting my password

**Comment by mattkrick** [comment]
Assumed AC:
- [ ] get the userId for every user above
- [ ] determine if the cause is on our end or if it's user error for each
- [ ] if there is a fix we can implement, create an issue with the AC of fixing the cause

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/12753501) 🔒 sent an email to support with the subject "forgot password error" and a screenshot of our forgot password prompt that says "oh no, something went wrong"

**Comment by mattkrick** [comment]
> whenever we send it manually, they get it

**Comment by jordanh** [comment]
Removing Discussion, @mattkrick's AC are good

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/16627501) 🔒  writes: 

> Can you please send me the password reset link as your link within the website isn’t working

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/58620701) 🔒  writes

> I forgot my password. Can you provide a new one?

**Comment by mattkrick** [comment]
Working as intended-- unfortunately we only keep mail logs for 15 days so I could look up many. 

I did find 1 interesting message: `We reject all .co domains`.
So that's on them if their company wants to put up stupid firewalls.

Next time a message like this comes in, before generating a password reset for them:
- go here: https://app.mailgun.com/app/sending/domains/mail.parabol.co/
- paste in their email
- see if there are any errors in the logs

**Comment by mattkrick** [comment]
Found it!
The daily password reset limit was set to lifetime, so users who have requested their password a lot from the same IP address over the months/years were getting denied.
