### ISSUE TITLE
Unable to see prompts in retro

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6714]
In this retro (https://action.parabol.co/meet/dObw9p39Be/reflect), we're unable to see the prompts in the Reflect stage. We see the following blank screen:

![image](https://user-images.githubusercontent.com/39854876/172917628-cca052a6-5bb3-4cc3-9d1e-5c932004c2c4.png)

All other meetings are working for me and I am able to see prompts when creating a new meeting.

### Acceptance Criteria:

- [ ] Discovered the root cause of the issue
- [ ] Fixed if it's easy, create a new issue if it's not

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
This may have been caused by the release because we changed the ids of some prompts :fearful:

**Comment by Dschoordsch** [comment]
This seems to have wider consequences, I also cannot join some retrospectives anymore.
