### ISSUE TITLE
Start with a Template

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6720]
Adding some content to the meeting view, a simple list of templates could create awareness about templates and also allow for a "quick start" option.

Miro example:
<img width="1664" alt="Screen Shot 2022-04-11 at 4 36 52 PM" src="https://user-images.githubusercontent.com/18582225/173091528-7bc86b32-de3d-4313-a7a0-774b33ca73fa.png">

Quick concept:
https://www.figma.com/file/XnPJgiNEA65oCI2MZXGzQN/Learning-Hub?node-id=909%3A3069

Note: the design will likely be impacted by the results of this experiemtn #6649

**Comment by jordanh** [comment]
Instead of iceboxing, I am going to mark this one as Closed and resolved by _Retros In Disguise's_ new activity user journey
