### ISSUE TITLE
RelayNetwork: No data returned for operation `DashboardQuery`

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6728]
20 users are affected, happened 135 times.

https://sentry.io/organizations/parabol/issues/2666077545/?referrer=github_plugin

```
RelayNetwork: No data returned for operation `DashboardQuery`, got error(s):
Server error

See the error `source` property for more information.
  at Array.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
...
(23 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Watermark 172 events, 10 users affected in the last 30 days. I am going to keep this one open. When I look at one of the stack traces I see that it is happening just after a new user signed up. That's not great

**Comment by jordanh** [comment]
![image](https://github.com/ParabolInc/parabol/assets/103000/55a20222-5f2b-43a6-9cbc-1ac9dfff4519)
