### ISSUE TITLE
End meeting options: Team member setting for sending meeting summary

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6737]
Part of the implementation for:
* #6572

As a facilitator I want to have the option to not send a summary email after the meeting ended. I also don't want to set this each time, so the setting should be persisted.

## Acceptance criteria
* [ ] add setting `sendMeetingSummary` to `TeamMember`, `true` by default
  * [ ] add to DB
  * [ ] add to graphql type
* [ ] create mutation `setSendMeetingSummary` with boolean `sendMeetingSummary` and `teamMemberId`
* [ ] modify `endSprintPoker`, `endCheckIn`, `endRetrospective` mutations to only send the summary email, if the setting for the facilitator is `true`

**Comment by mattkrick** [comment]
related #4538
