### ISSUE TITLE
End meeting options: end meeting dialog

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6738]
Part of the implementation for
* #6572

Needs:
* #6737 

As a facilitator I want to see the summary email option right at the time when I end a meeting.

## Acceptance criteria
* [ ] change behaviour of `EndMeetingButton`
  * [ ] click opens dialog from #6572 (without the delete option)
  * [ ] we keep clicking twice as shortcut for users who don't want to change anything
  * [ ] clicking "End meeting" in the dialog calls same end meeting function as clicking twice on the end button
* [ ] "Send meeting summary" checkbox value is read from `TeamMember`
* [ ] (un-)checking "Send meeting summary" calls `setSendMeetingSummary` mutation
* [ ] still redirect to meeting summary page

**Comment by mattkrick** [comment]
As our company grows, the features we say "no" to are MORE important than the ones we build.
As a product team, we need to aggressively fight against features that can complicate the UI/UX for the new user. 
Our design ethos has always followed "Don't make me think".
That manifests itself by only putting common actions in common workflows.
Ending a meeting is a common workflow. Every facilitator will do it!
Deleting a meeting isn't common. That doesn't mean we can't include the feature! But it should be tucked away in a place so as to not encourage the behavior. A new user shouldn't have to stop & think "well, maybe I do want to delete it?".

Similarly, putting 2 gates in front of sending a summary email (the facilitator can send, the team member can choose not to receive via settings) can lead to confusion. Let's opt for having this be a team-member preference. if a meeting gets killed (archived before it is ended) we can opt to not send a summary.
