### ISSUE TITLE
End meeting options: delete meeting dialog

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6740]
Implementation for:
* #6572 

Needs:
* #6739
* #6738 

As a facilitator I want to be able to delete a meeting

## Acceptance criteria
* [ ] Add "delete meeting" option to the end meeting dialog from #6738 according to the design in #6572
* [ ] Add confirmation dialog
* [ ] On confirmation, call `deleteMeeting` mutation from #6739 and redirect to team dash (same where you would go after meeting summary)

**Comment by mattkrick** [comment]
Closing, see https://github.com/ParabolInc/parabol/issues/6738#issuecomment-1164638309 for details
