### ISSUE TITLE
Design to prompt user to drag cards in group phase

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6741]
[User feedback:](https://parabol.slack.com/archives/C029ZTH0EL9/p1655132122585119)

>  It took two meetings to figure out that he had to drag to group - it wasn't obvious at the start.

Design an animation or prompt to indicate to the user that they can drag and drop cards to group them

### Acceptance Criteria
Users can:
   - See a prompt to start grouping
   - Not see the prompt _after_ they have begun grouping
   - Make the prompt go away
   - do not show this for users who've run >3 retros

**Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by acressall** [comment]
I have two ideas for helping users see that they can drag and drop in the grouping phase of a retro. 

The animation should only start when the user:
1. is present
2. has not done anything for >=1 minute (too short?)
3. has not participated and/or facilitated more than 2 retrospectives

The animation should only show up once per phase and stop as soon as the user takes _any_ action

**Comment by acressall** [comment]
Option 1: hinting at drag and droppable cards. This animation will repeat once and will occur on the first card that is not in a group


https://user-images.githubusercontent.com/18582225/174649708-21f216d9-d0bd-494a-b376-6669455b8473.mov

**Comment by acressall** [comment]
Option 2: highlighting the tips. This animation prompts the user to view the tips for more information about what to do. It could potentially be used in more than just the group phase


https://user-images.githubusercontent.com/18582225/174649814-4d5df6f5-0d64-45f2-bac6-7cf77e322468.mov

**Comment by Dschoordsch** [comment]
I'd like to use the option 2 style hint for highlighting the next or end meeting depending on context.

**Comment by acressall** [comment]
New issues added to reflect these #6815, #6814

**Comment by 87prashant** [comment]
> Option 2: highlighting the tips. This animation prompts the user to view the tips for more information about what to do. It could potentially be used in more than just the group phase

A small observation: 
What I notice is that it is hard to notice the animation, white element against the white background (maybe that's the case only with me).
- We can change/add the color at the time of the animation (though we are changing color already, but it is not significant)

What do others think?

**Comment by JimmyLv** [comment]
I agree that it is hard to notice the animation, but since it is flashing repeatedly, maybe the user will notice after staying for a while? 
> We can change/add the color at the time of the animation
I like the idea of adding color to it though

**Comment by acressall** [comment]
Hmm it might get rather annoying if it is _endless_. Let's put a cap on it of 10s or ~3 repetitions?

Here's an updated animation addressing the contrast issue

https://user-images.githubusercontent.com/18582225/179829476-db5f76d3-5156-4d33-b545-2dda65be2775.mov
