### ISSUE TITLE
MS Teams: Add Parabol to the MS Teams store

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6743]
MS Teams users should be able to easily add Parabol app to their MS Teams.

**Comment by Dschoordsch** [comment]
The standard way would be to create an [Office 365 connector](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating#integrate-the-configuration-experience).

There might be some other options according to @MicrosoftCSA, will wait for a reply on that.

**Comment by Dschoordsch** [comment]
Feedback was that the Office 365 connector is the only way to get our app into the MS Teams store.

**Comment by nickoferrall** [comment]
Hey @Dschoordsch, just checking if this issue is still In Progress and should be in Squad 2?

**Comment by jordanh** [comment]
Implementing this would require that we upgrade our Teams integration to a full integration where we allow users to authenticate with O365. We may do this later this year as MS is keep to promote us
