### ISSUE TITLE
Enable tasks in Sprint Poker threads?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6748]
Sprint Poker can be used to look at any list of ideas, projects, work, issues, etc.

Sometimes there’s a next step smaller than the listed body of work.

We already have Parabol tasks; we turned them off in poker threads to bring greater focus.

Should we enable them?

### Open questions

- Is it as easy as removing a conditional?
  - Do poker threads support tasks?
  - Are there any missing mutations, types, subscriptions etc?

### Acceptance criteria
- Discussed async
- If we decide no, close this
- If we decide yes
  - Do it in 1-2 hours if it’s easy
  - Write an implementation issue if the effort is greater

### Estimated effort
- 2 hours

**Comment by ackernaut** [comment]
I vote yes. I wanted this today. I think the affordance is easy enough to ignore if a team doesn’t use them.

**Comment by jordanh** [comment]
I also vote yes!

**Comment by jordanh** [comment]
I have a feeling this one will come around again...
