### ISSUE TITLE
Drag-and-drop upload images onto OutcomeCards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#675]
## Issue - Enhancement

Don't you love that you can just drag-an-drop and image into a github issue, and it magically uploads to their CDN and injects the proper markdown? _Us too!_

Let's add the same functionality to our Project and Action cards.

### Acceptance criteria:

It should:

- [ ] allow an image to be dropped to a specific position within an `OutcomeCard` component
- [ ] insert placeholder markdown while...
- [ ] ...the image is securely uploaded from the client directly to S3
- [ ] and call the component back with its final URL upon upload completion

- **Estimated effort:** 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
👾

**Comment by ndey96** [comment]
ooo this sounds like fun! I shall begin at 1️⃣ce

**Comment by jordanh** [comment]
You sir, you sir are our hero. This will make a BIG difference.

**Comment by ndey96** [comment]
@jordanh Still sounds fun but I'm going to put this one on the back-burner for now

**Comment by jordanh** [comment]
@ndey96 ok, no worries mate.

**To our community:** this one is still up for grabs. If you want to help work on it under our [Equity for Effort](https://github.com/ParabolInc/action/projects) program, just leave a comment here.

**Comment by paceaux** [comment]
I'm willing to take this on. 

I've done some DnD work in the past. Estimate seems accurate.

**Comment by ackernaut** [comment]
👋 

Good deal @paceaux —the issue is yours! Feel free to ping us with questions as you make your way around the stack. Here or in Slack is a fine place to do so.

**Comment by jordanh** [comment]
Scrubbed today. Will leave open for E4E.

**Comment by jordanh** [comment]
Scrubbed again. Leaving open for E4E.

**Comment by jordanh** [comment]
Feedback from a user at this company:

> "I was poking around this software a little bit and one thing I was kind of disappointed to realize was that there doesn't seem to be a way to add in images, which I find to be a great way to make retros more fun and engaging."

**Comment by NikAiyer** [comment]
I'll take a shot at this one

**Comment by jordanh** [comment]
As time goes on, some things have changed with the underlying technologies Parabol's relies on. I assert that rather than implement this functionality on top of the DraftJS editor, we move the Reflect cards to Tiptap before taking this on

**Comment by jordanh** [comment]
Going to close this one for now...
