### ISSUE TITLE
Redesigned Retro voting icons

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#6750]
## Issue - Enhancement

We consistently get feedback the thumbs up/thumbs down icons we've implemented for the Retro Vote phase are confusing. For example, this is what [this user ](https://app.hubspot.com/contacts/3888472/contact/54665901)🔒 had to say:

> One piece of feedback I would give you is that the thumbs up/thumbs down we found a little confusing. It looks like you are trying to downvote a card VS remove a like.

### Acceptance Criteria (optional)
   - Designs that explore multiple options for replacing thumbs up/thumbs down to spend/remove votes
   - Internal feedback collected to narrow options to a subset
   - External feedback collected with at least one user
   - Implementation issue created

**Estimated effort:** 8 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by treyparabol** [comment]
A[ user](https://app.hubspot.com/contacts/3888472/contact/52617851) 🔒  wrote into Support:

> Hi,
> 
> Small thing we've noticed on our team is that when in the vote stage, clicking a thumbs up or thumbs down highlights the opposite vote. I've had a handful of times where I've voted, gone to click ready, and then done a double take cause it looks like I've downvoted a handful of cards when I haven't.
> 
> Super small change, just thought I'd call some attention to it.

**Comment by Dschoordsch** [comment]
How about just replacing those with +/-?
![Peek 2022-06-22 10-17](https://user-images.githubusercontent.com/7331043/174979858-69b80bc6-ea7b-42d6-ad54-89684ad0a322.gif)

**Comment by ackernaut** [comment]
@Dschoordsch I like that direction. The feedback in the center is nice, maintaining the thumbs-up and a count even if you’re going back down. This reminds me of our voting settings:

![Screen Shot 2022-06-22 at 14 40 55](https://user-images.githubusercontent.com/307286/175122429-97d13e25-f609-4d48-a703-00b3a38364b9.png)

The bare minus and plus icons feel a little too light. I think they need a little more weight. Does a circular variant of the icons work to add a little more weight and surface area?
- `remove_circle_outline` or `remove_circle`
- `add_circle` or `add_circle_outline`

**Comment by Dschoordsch** [comment]
@ackernaut thanks for the feedback, I have 3 options to choose:
1. plus_circle
![plus_circle](https://user-images.githubusercontent.com/7331043/175240085-634590e5-5840-482d-af6d-571585154ce8.gif)
![Screenshot from 2022-06-23 09-26-55](https://user-images.githubusercontent.com/7331043/175241243-7181e166-381a-4bd3-a476-a2872682dad2.png)

2. border + shadow (same as in Vote Settings)
![raised border](https://user-images.githubusercontent.com/7331043/175240110-e47d302a-b8a5-4a11-8b77-f6d75e6895cd.gif)
![Screenshot from 2022-06-23 09-27-40](https://user-images.githubusercontent.com/7331043/175241276-7747971f-a145-459f-82bf-39aa26abbe29.png)

3. border + shadow + SLATE_100 background
![raised border and SLATE_100 background](https://user-images.githubusercontent.com/7331043/175240124-25eb0145-25fe-4f5a-a7f8-d73956d16ee0.gif)
![Screenshot from 2022-06-23 09-25-56](https://user-images.githubusercontent.com/7331043/175241312-12fd53ad-d9af-4a3a-b55b-b856f0a079af.png)

4. Bonus: FlatButton
![FlatButton](https://user-images.githubusercontent.com/7331043/175243438-c820acfe-2bb9-4289-8831-b0a8a68f7e9a.gif)
![Screenshot from 2022-06-23 09-37-31](https://user-images.githubusercontent.com/7331043/175243387-dec5e51e-0e58-4952-93f0-857bb5c1876b.png)

**Comment by Dschoordsch** [comment]
In isolation I preferred version 3. but with multiple cards it looks cluttered. 1. and 4. look nicely for multiple cards, but only 4 seems consistent with the rest of the app, what do you think?

**Comment by ackernaut** [comment]
I agree. 4 seems most consistent and less busy with many cards which is the
typical case. Nice work!
