### ISSUE TITLE
Can't vote in sprint poker - estimate phase is already completed

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6755]
## Issue - Bug

Meeting ID: e17R70AOPu 

![CleanShot 2022-06-14 at 18 34 41](https://user-images.githubusercontent.com/1017620/173755780-5a6123fb-c2db-45e4-9ae8-13ef9a92a9c3.gif)

I was a facilitator, the meeting was still open and I wasn't able to vote on anything, or reveal any existing votes. When the meeting was closed, the UI didn't update until refreshed (the meeting card was still on the meeting dashboard, people who were in the meeting still were able to see the normal state) 

### Acceptance Criteria (optional)
- [ ] find a root cause

Triage is performed to find the root cause of the bug, timeboxed to ~4 hours.

**Comment by 87prashant** [comment]
@BartoszJarocki is there any way to reproduce the bug?

**Comment by 87prashant** [comment]
@jmtaber129 
I think this issue is also fixed and can be closed.
