### ISSUE TITLE
Add a cancel option for pro users

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6760]
## Issue - Enhancement

Context [🔒 here](https://parabol.slack.com/archives/C836NA350/p1655300185796309).
Once we focus more on pro users' experience it'd be nice to allow them to cancel their subscription on their own. 

### Acceptance Criteria
- [ ] a design where pro users can cancel subscription on their own 
- [ ] when users move to cancel their subscription, they can select multiple reasons to tell us why
- [ ] there is an optional text input box to tell us more
- [ ] a written implementation issue added to the backlog

**Comment by jordanh** [comment]
Making this a design issue and going to edit your AC directly above. There are a few things we'll want to consider before we implement

**Comment by acressall** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/hwEj48juqk/estimate/1) in Sprint Poker #​​3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
