### ISSUE TITLE
Implement domain stats snackbar

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6762]
As mentioned in https://github.com/ParabolInc/parabol/issues/6681, we want to emit a nagging snackbar to ask relevant users to visit the `/usage` page. 

### AC

- [ ] Store a `hasSeenUsage` boolean field on the User object
- [ ] In `MeetingSelector`, `NewMeeting`, and `DashboardRoot`, add a `useSnackbar` hook that works in a similar way to (or modifies) [useSnackNag](https://github.com/ParabolInc/parabol/blob/8c68bf771a350b31c7948e6bd11c5c110e30c977/packages/client/hooks/useSnackNag.ts)
- [ ] If the `insights` featureFlag is true, `hasSeenUsage` is false, and is not `/usage` page, the snackbar is emitted
- [ ] When the user visit the `/usage` page, a mutation is executed that updates `hasSeenUsage` to true
- [ ] When the snackbar is emitted or dismissed send an event to Segment
- [ ] If the snackbar is dismissed, it nags the user every 3 minutes until they visit the `/usage` page

**EE**: 5 hours

**Comment by mattkrick** [comment]
>  Store a hasSeenUsage boolean field on the User object

what functionality is dependent on this variable?

**Comment by nickoferrall** [comment]
> what functionality is dependent on this variable?

Whether we should the snackbar. `hasSeenUsage` is false until the user visits `/usage`, when it's updated to true. If `hasSeenUsage` is false, we show the nagging snackbar. If it's true, we don't.

**Comment by mattkrick** [comment]
ahhhhh so if they goto /usage once, they never see the snackbar again?

**Comment by nickoferrall** [comment]
Yep, exactly!

**Comment by mattkrick** [comment]
gotcha! i was thinking about nagging em even more 🤣 

there's a few places we could store `hasSeenUsage`, ranging from most naggy to least naggy

- never store hasSeenUsage, they can only escape the snackbar by clicking dismiss every 3 minutes. this is what we currently use for the useSnackNag.
- store it in the client schema (ie per-session)
- store it in local storage (ie per-device)
- store it on the User object (ie per-user)

my .02 is to not keep it on the user object since that involves the server & a DB migration, but i'll let you & @ackernaut  @avivapinchas decide

**Comment by nickoferrall** [comment]
😄  another option could be storing it in Redis with a TTL of say one week? If they've visited the `/usage` page but haven't upgraded to Pro / Enterprise after one week, we'd nag them with the snack again. 

Never storing it might be annoying for billing leaders that are waiting for permission from their boss to upgrade. Storing it per session or device feels a bit random to me. Storing it on the User object means they might not be nagged enough. So, the Redis option is probably my favourite. 

However, I don't think we should nag them every 3 minutes during a meeting. I think they're fair game in the dashboard and meeting selector, but if I was focusing on an hour-long meeting and kept getting pestered every 3 minutes by a snackbar, I'd find it too aggressive.

**Comment by avivapinchas** [comment]
> every 3 minutes

My pref: I think it should be persistent on the screens where it shows up, until they dismiss (comes back in X time) or upgrade. 

> I think they're fair game in the dashboard and meeting selector

What about: timeline, /meetings, tasks?

**Comment by nickoferrall** [comment]
>  My pref: I think it should be persistent on the screens where it shows up until they dismiss (comes back in X time) or upgrade.

If the user dismisses the snackbar during a meeting, do you think it should come back every 3 minutes? I think that works well everywhere else in the app but would feel annoying during a meeting. Still, if you and Matt prefer that, it would be easier for me to build. We could always change it if customers complain. 

> What about: timeline, /meetings, tasks?

Yep, it'll show up there too. The `Dashboard` component in the codebase includes all of these pages.

Once the user visits the `/usage` page, how quickly afterwards do you think we should show the snackbar? I think we should show it one week or maybe one day later, just as long as we're not showing it to them every 3 minutes after they've visited `/usage`.

**Comment by avivapinchas** [comment]
> during a meeting, do you think it should come back every 3 minutes? 

🤔 I kind of don't think it should show up during meetings - folks are doing something else, they're pretty unlikely to engage with it then, imo. 

> Once the user visits the /usage page, how quickly afterwards do you think we should show the snackbar? I think we should show it one week or maybe one day later, just as long as we're not showing it to them every 3 minutes after they've visited /usage.

I think it should be essentially persistent

**Comment by nickoferrall** [comment]
Cool, I'll go with that 👍
