### ISSUE TITLE
Refactor SendClientSegmentEventMutation to ensure type safety 

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6765]
Currently, we're not getting any type safety from the `SendClientSegmentEventMutation` mutation. Git blame tells me the mutation is 5 years old! 🧓 

### AC

- [ ] Refactored `segmentEventTrack` to SDL pattern 
- [ ] Refactored `SendClientSegmentEventMutation` so that we get type safety when calling the mutation from the client 

**EE**: 3 points

**Comment by jordanh** [comment]
Pretty good find on @nickoferrall's part. Please reopen if you disagree with the decision to icebox
