### ISSUE TITLE
Designed better awareness of Retro reflection search (code name spotlight)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6766]
Terry says: Spotlight is our internal nickname for our Retro reflection search tool. Once folks find it, it’s pretty powerful offering suggested groups and the ability to group in the dialog. However the initial control is relatively minimal on the bottom right of reflection cards in the Group phase. This too, is not a bad thing, as we don’t want the interface to get too busy or clunky. There are many micro interactions for authoring cards and managing groups and we have to manage the use cases including discoverability.

### Discussed in https://github.com/ParabolInc/parabol/discussions/6257

<div type='discussions-op-text'>

<sup>Originally posted by **drewhousman1010** March 22, 2022</sup>
Spotlight is awesome and I want to make sure our users know about it. This is a place to collect signal when we hear from users that they couldn't find spotlight or didn't understand they could use it to solve a problem. 

E.g. this [user](https://app.hubspot.com/contacts/3888472/contact/40915851) 🔒 writes: 

> Subject: Grouping doesn't work w/ long list
> Message: Please let me drag a card up beyond the currently visible scroll area in the Grouping phase. This is always extremely frustrating and wastes a lot of time in meetings, would be a lifesaver bug fix. Thanks!

When the support person responded that Spotlight could help with that, they said: 

> Interesting! I'll try it next time. I've never noticed it before.
</div>

### Open questions
- What are the user job stories where spotlight helps?
- How often do folks have retros with lots of cards?
- How can we boost awareness without the interface feeling clunky or heavy?

### Acceptance criteria
- **Early and often**: shared progress and gathered feedback from the team
- Identified additional open questions, if any
- Gathered additional user insights, if any
- Sketched lo-fi solutions
- Designed concepts and/or prototypes
- Outlined a plan for gathering feedback from users
- Documented design details with a developer for implementation

### Estimated effort
- 21 hours

**Comment by jordanh** [comment]
I _really_ want this to happen. As it is marked as `Batting Practice` I will keep open
