### ISSUE TITLE
Designed better voting status for Retros

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6767]
Today it’s not apparent who hasn’t voted yet in a Retro. There’s only a single count of votes remaining for any participants who have viewed the meeting.

Sometimes folks are viewing and have votes remaining. Sometimes folks have joined the meeting async and were given votes, but are not on during a sync call.

Here’s a quote from #5461 

>In our retro meetings we often are waiting around for team votes to get to 0. It would be great to see how many votes each team member has remaining. Would save a lot of time saying "who didn't vote?"

### Open questions
- Will folks feel ‘on the spot’ if it shows remaining votes per person?
- Are there any patterns that may also be useful in Sprint Poker? See #6768 
- How do we distinguish who is online or offline?

### Acceptance criteria
- **Early and often**: shared progress and gathered feedback from the team
- Identified additional open questions, if any
- Gathered additional user insights, if any
- Sketched lo-fi solutions
- Designed concepts and/or prototypes
- Outlined a plan for gathering feedback from users
- Documented design details with a developer for implementation

### Estimated effort
- 21 hours

**Comment by enriquesanchez** [comment]
This came up during [User feedback retro 🔒](https://action.parabol.co/meet/oDZQWB3EVq/discuss/2):

>it would be nice to see who has votes remaining specifically in case I need to nudge them.
