### ISSUE TITLE
Designed better voting status for Sprint Poker

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6768]
While voting in Sprint Poker, an avatar group appears for those who have voted. It’s not apparent who hasn’t voted yet for the item currently being estimated.

Sometimes folks are online and viewing. Sometimes folks have joined the meeting async but haven’t voted, and they’re not on the view now.

Here’s a quote from #4672

>When estimating, I can't see who hasn't voted. Sometimes people are afk or otherwise distracted and it's frustrating to keep asking who hasn't voted yet. This must be a common problem on many teams. If I could see who hasn't voted yet I can call them out by name.

### Open questions
- Will folks feel ‘on the spot’ if it shows remaining votes per person?
- Are there any patterns that may also be useful in Retros? See #6767 
- How do we distinguish who is online or offline?

### Acceptance criteria
- **Early and often**: shared progress and gathered feedback from the team
- Identified additional open questions, if any
- Gathered additional user insights, if any
- Sketched lo-fi solutions
- Designed concepts and/or prototypes
- Outlined a plan for gathering feedback from users
- Documented design details with a developer for implementation

### Estimated effort
- 21 hours

**Comment by enriquesanchez** [comment]
[A user writes](https://app.hubspot.com/live-messages/3888472/inbox/3474057512#email) 🔒:

>We use your Estimate meetings and it works very well for us. We only have one problem: Due to the fact that we do estimations with a rather big team, it is difficult to impossible to tell which two or three people are missing in the voting.

It'd be great to have a list of all people that want to vote and haven't yet.
