### ISSUE TITLE
Choose your own [product design] adventure

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6769]
This issue is evergreen for product design candidates who are working on a trial project with us.

### Acceptance criteria
- Spend time exploring the Parabol product UX end to end
- Peruse our issues and discussions for user feedback
- Make a list of the top 3-5 UX pains, in your opinion
- Write a design issue to solve for 1 of the top pains. The issue should include:
  1) **Background** — describe the problem context in brief
  2) **Open questions** — what are the riskiest assumptions?
  3) **Acceptance criteria** — what does done look like?
  4) **Estimated effort** — aim for ~21 hours, including the time spent choosing your adventure
- Propose the design issue to the team for questions and feedback
- Once the team gives the green light, proceed with the design issue
- Make meaningful progress on the design issue for the remainder of the trial project

### Estimated effort
- 21 hours

**Comment by jordanh** [comment]
This one can be kept open as it is evergreen
