### ISSUE TITLE
Jira: `addMissingJiraField` function does not work with custom screen names

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6771]
Our `addMissingField` function searches the required screen by matching its name with project key.

```
 if (screen.name.startsWith(nameProjectPrefix) && screen.name.includes('Default')) return 1
```

However, if user uses custom screen names it would be impossible to match the screen like this.

We can iterate all the screens and try to add the field to every screen, but in case of 100+ screens our function will fail with timeout

**I suggest the following solution:**

1. Request additional oauth scope when Fix field button clicked: `manage:jira-configuration`
2. Get the projectId by projectKey
3. Run the following API query, by putting necessary `projectId` `https://api.atlassian.com/ex/jira/b8999f88-721c-49c7-aa0e-d60eeffc1eb6/rest/api/3/issuetypescreenscheme/project?projectId=10019`

The result would be:
```
{
    "maxResults": 50,
    "startAt": 0,
    "total": 1,
    "isLast": true,
    "values": [
        {
            "issueTypeScreenScheme": {
                "id": "10027",
                "name": "New custom schema",
                "description": "",
                "projects": {
                    "maxResults": 0,
                    "startAt": 0,
                    "total": 0,
                    "isLast": true,
                    "values": []
                }
            },
            "projectIds": [
                "10019"
            ]
        }
    ]
}
```

We need `issueTypeScreenScheme.id`

4. Now run `https://api.atlassian.com/ex/jira/b8999f88-721c-49c7-aa0e-d60eeffc1eb6/rest/api/3/screenscheme?expand=issueTypeScreenSchemes&maxResults=100`
Using pagination fetch all screen schemes, similar to what we currently do with screens

5. In the response we need to find the item where `issueTypeScreenSchemes.values` includes previously found `issueTypeScreenScheme.id`:

```
        {
            "id": 10079,
            "name": "CT1: Kanban Default Screen Scheme",
            "description": "",
            "screens": {
                "default": 10079
            },
            "issueTypeScreenSchemes": {
                "maxResults": 2,
                "startAt": 0,
                "total": 2,
                "isLast": true,
                "values": [
                    {
                        "id": "10025",
                        "name": "CT1: Kanban Issue Type Screen Scheme",
                        "description": ""
                    },
                    {
                        "id": "10027",
                        "name": "New custom schema",
                        "description": ""
                    }
                ]
            }
        },
```

6. Now pick the default screen id `screens.default`, fetch tabs, try to update like we currently do

AC:
- [ ] New algorithm implemented and works with custom Jira configuration

**Comment by Dschoordsch** [comment]
#7206 removed this functionality
