### ISSUE TITLE
feat(usage): Usage Charts

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6777]
We need to show folks that their usage is growing. Here's some ways we display that today
![Screen Shot 2022-06-16 at 2 52 34 PM](https://user-images.githubusercontent.com/5514175/174172271-9f891ad3-e30a-4492-837c-b54374487591.png)
![Screen Shot 2022-06-16 at 2 52 39 PM](https://user-images.githubusercontent.com/5514175/174172276-cbabc292-3b4b-4c99-bf4f-bcff7647ec05.png)
![Screen Shot 2022-06-16 at 2 53 29 PM](https://user-images.githubusercontent.com/5514175/174172280-c82b6d8a-e22c-438f-8d40-2694bd7abab2.png)
![Screen Shot 2022-06-16 at 2 50 24 PM](https://user-images.githubusercontent.com/5514175/174171857-a0400f37-120d-44a4-b731-77fa8741b6b2.png)

I think we're _real_ close to a final product! Here's what I'd propose to start the discussion:

### Chart 1 - # of Meetings by type 

- NOT cumulative
- stacked area chart
- each dataset is a meeting type

### Chart 2 - # of Teams

- Cumulative
- Shows all teams 
- bar chart

### Chart 3 - # of Users

- Cumulative
- Shows all users
- line chart

**Comment by nickoferrall** [comment]
For the meetings chart, it might be useful to use the Stacked Bar Chart and show the breakdown of the meeting type:

![stacked-bar-chart](https://user-images.githubusercontent.com/39854876/174254962-5ba2bd4a-3783-4645-a32f-a5170e91e34b.png)

Also, if there's space, it'd be cool to see the average/median meeting length. A user might see that there are several meetings but wonder how many of them are dummy meetings that were created and immediately ended. Average/median meeting length would also indicate whether meetings are taking too long.

**Comment by mattkrick** [comment]
permissions problems:
- meetings live on teams
- you can't see a meeting if you're not on that team
- to get a count of the number of meetings, you need to see teams that you're not apart of

options:
- create a new `meetingMetadata` object that lives on the organization `{meetingType, createdAt}`. I don't like creating partials for the sake of permissions. it gets messy & bloats the api.
- let anyone in the org see a team. i don't like this because it takes down another line of defense (ie if a hacker is in the org, your data is theirs)
- let anyone in the org see at least a part of a team. i don't like this because a Team has certain non-null fields & if they request those fields, we'd have to feed default values.
- add an arg to teams like `Organization { teams(all: true) { id } }` same problem as above, but at least it's expressive 🤷 
- contextual allowance. if the request starts with `company { organizations {teams } }` then we allow then to access a partial. i don't like the implicit nature of this allowance
- we can put meetingMetadata on the Team object instead of the Organization, but the same problem as above occurs since we only want to expose meetingMetadata, nothing more.

fundamentally, you shouldn't have access to a team you're not apart of, so the simplest thing is to not grant access to the team.
that means the first choice is the only option. i hate it because it's so single purpose, but after exploring all other options, it's really all we can do.

moving forward:
```gql
company {
  organizations {
    meetingStats {
      meetingType
      createdAt
    }
  }
}
```

next challenge is how to get access to an organization that they user is not apart of.
probably have to allow access if they have manual perfmission

**Comment by mattkrick** [comment]
Permissions:
- [ ] if you are a super user, you have access to all organizations under a given domain
- [ ] if your suggestedTier === enterprise, you have access to all organizations under a given domain. Even if you are not apart of that org!
- [ ] else, you have access to organizations that you are apart of

**Comment by ackernaut** [comment]
@mattkrick how does one become a super user? when we target them with multi-org domain stats? When you say they have access what do you mean? They can see those orgs in their orgs list? And they are not listed as a member on that org?

**Comment by mattkrick** [comment]
- superuser is parabol employees
- when we declare that they should be an enterprise client, they have permission to view all organizations under that domain, even if they are not a member. UI doesn't change, it's just permissions
