### ISSUE TITLE
feat(usage): Automation exploration

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6781]
### Problem
We group orgs by domain so we can show that 1 company has 2 departments both using parabol separately.
Grouping organizations by domain is imperfect. How do we know the domain they share isn't freemail?
Today, we filter out the common ones like gmail.
We could instead ask hubspot if the domain is freemail, they have an OK (but not perfect!) association.

The problem is that we are sharing information across organizations. That's OK if the 2 organizations should, in fact, be 1! But that's impossible to know without a human touch involved.

Here's the following scenario:

- I use my protonmail.ch email address along with 100 other people.
- According to parabol, that is a company domain (wrong!)
- According to hubspot, that is a company domain (wrong!)
- I go to `/usage` & I can see how many meetings have been run by everyone with that same domain
- I get crafty & instead of asking for the meeting start date (which is necessary for the charts) I ask for the meeting contents, the emails of the participants, or anything else... locking this down will be _very_ hard to do & is ripe for 1 mistake that could give up PII.

If a human touch is involved, e.g. a sales person talks to both departments & verifies that they are in fact under the same org, this risk seems manageable. Full automation is just too unsafe though.

### Proposal
As a workaround, we know full automation is the goal for Pro upgrades.
We also know the majority of Pro users have a single org.
So, my suggestion is to use "organization stats" for automated results, which will work well for Pro leads.
We use "domain stats" for high-touch enterprise leads.

**Comment by ackernaut** [comment]
In short, I agree. It’s a good place to start and we will learn in the meantime. Safe to try 👍

**Comment by avivapinchas** [comment]
I agree as well - we can exclude Pro-Qual Domains with more than one org from our conversion efforts.

**Comment by nickoferrall** [comment]
I agree too. Company-wide stats/insights could be another advantage added to the enterprise pricing comparison table

**Comment by avivapinchas** [comment]
I like that thinking @nickoferrall!

**Comment by mattkrick** [comment]
love it!
business logic here: https://github.com/ParabolInc/parabol/issues/6777#issuecomment-1162477814
