### ISSUE TITLE
Retrospective: Add more prominent enter-hint for reflection phase

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6792]
We observed many times that new users don't read the placeholder and thus miss pressing enter after they've added their reflection. We don't want to show any additional buttons to not clutter the interface too much, but we could show a hint if they stop editing without submitting the reflection.

![Peek 2022-06-21 10-03](https://user-images.githubusercontent.com/7331043/174748510-4de66b9e-ec83-4ed7-be6c-0dc8498a0c25.gif)

## Acceptance criteria
* [ ] show a hint if `!isEditing && content.hasText()` in `PhaseItemEditor`
* [ ] add nice transition

**Comment by acressall** [comment]
I like this idea a lot. Do we have the ability to adjust how long before it shows up if I still have the card in focus? For example, if I pause to think about what I'm writing I wouldn't want it to show up all the time.

Design notes:
- I'd love a bit of extra padding on the bottom of the text. Maybe 4px?
- Would you like me to design a transition?

Copy note:
What do you think of `Press enter or click here to add` ?
