### ISSUE TITLE
A/B testing mutation

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6796]
Relates-To:
* #7130

Add a mutation which adds feature flags to users based on a normal distribution. We want to be able to
* assign flags to existing users based on the distribution
* have organization affinity
* store metadata about the experiments in the database
  * needed for data warehouse
  * needed for assigning flags to new users
* assign flags to newly created users

## Database
The experiment database 
```sql
CREATE TABLE IF NOT EXISTS "Experiment" (
  "id" SERIAL UNIQUE PRIMARY KEY,
  "name" VARCHAR(120) NOT NULL,
  "group" VARCHAR(120) NOT NULL,
  "percentage" INTEGER NOT NULL,
  UNIQUE(name, group)
);

% add field "experimentFlag" to "User"
```
Experiment flags are constructed by concatenating `${experiment.name}_${experiment.group}`.

## Mutation
* [ ] add mutation `setupNewExperiment`
```graphql
input ExperimentInput {
  group: String!
  percentage: Int
}
mutation setupNewExperiment(experiment: [ExperimentInput!]!): Boolean
```
* [ ] check all but 1 percentage need to be defined (last one can be calculated)
* [ ] check sum(ExperimentInput.percentage) <= 100
* [ ] assign each user a group based on their biggest organization
  * could be done by using (Experiment.randomSeed + orgId) as seed for a random number generator and then check in which group the result falls
* [ ] if a user joins an organization (also on signup) assign the experiment group from their largest org

## Acceptance criteria
* [ ] implement database changes
* [ ] implement `setupNewExperiment` mutation
* [ ] implement assignment for new users
* [ ] add `experimentFlags` to graphql `User`
* [ ] add `experimentFlags` to Amplitude identify call
  * [ ] format must be parseable by limited Amplitude matching functions even when a User has multiple groups assigned

**Comment by mattkrick** [comment]
this is gonna be fun!

thoughts
- a `_A` suffix is gonna be a little weird for true/false tests (e.g. does JiraServer_A mean I can access JiraServer? What's the difference between JiraServer_B and nothing at all?). Might be nice to supply a name for these groups so it's easier to run analytics on when we forget what A/B stand for
- our feature flags are denormalized JSON today, perhaps now is the right time to take it to 3NF & give them their own table?
- we'll need to restructure our GraphQL schema. Probably get rid of `UserFeatureFlags` and instead just return a string array (or a bitset if you want to watch the world burn :stuck_out_tongue: )
- I'm not sure I understand how the `assignToNewUsersOnly` flag. It seems like that would work against domain/org affinity?

**Comment by Dschoordsch** [comment]
I simplified it based on your comments, thank you!

**Comment by jordanh** [comment]
How does the data get into amplitude/the data sanctum?

For Amplitude: do we depend on emitting an identify() call to update the Segment user properties with the actively running experiment or feature flag(s)? Could you update your spec with what the data shape might look like?

For the Data Sanctum, I imagine we just inject the new data table/flag fields, is that right?

**Comment by Dschoordsch** [comment]
> How does the data get into amplitude/the data sanctum?

Experiment groups will be in the User table, thus available in data sanctum

> For Amplitude: do we depend on emitting an identify() call to update the Segment user properties with the actively running experiment or feature flag(s)?

Yes

> For the Data Sanctum, I imagine we just inject the new data table/flag fields, is that right?

Yes

**Comment by tianrunhe** [comment]
We might prefer [`group()`](https://segment.com/docs/connections/spec/group/) over `identify()` for Segment/Amplitude.
