### ISSUE TITLE
Standups: Design Activity summary

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6801]
Design the activity summary users get when the standup has ended. This should be closely similar to the summaries we already show for other types of meetings.

### Acceptance Criteria (optional)
Users can:
   - View a summary of their standup instance
   - The summary can be viewed both on email and on the browser

**Estimated effort:** 
5 hrs

**Comment by enriquesanchez** [comment]
@lorena-cure @BartoszJarocki @jmtaber129 

Here's a first pass for the standups summary. This is what folks will see both on email and web. 

You'll notice it's very similar to the other meeting summaries, and that's intentional. I don't think we should deviate much here. But I can be convinced otherwise if you have a strong argument, just raise your tension.

![image](https://user-images.githubusercontent.com/3276087/177652007-3497b13f-88bd-4200-8d9a-148a074481a0.png)

The summary shows the responses, given this is the most important piece of content generated during a summary, and what teammates would be most interested in seeing. I don't think we should also show any created tasks here, since that is secondary info and could potentially make these summaries very long. But do let me know if you think otherwise 👍 

**Questions:**

- Should we call these "Meeting summary"?

**Comment by jmtaber129** [comment]
LGTM!  Only thing I'd suggest changing is changing "replies" to "comments" or similar to avoid the "response"/"reply" ambiguity.

**Comment by jmtaber129** [comment]
@enriquesanchez one Q about this - what should "participants" reflect?  Total response cards (empty and non-empty), members who responded or added a discussion comment? Something else?

**Comment by enriquesanchez** [comment]
@jmtaber129 Ah, good question. I lean for only including those who added a response. On other summary types, like retros, we include a section for teammates who don't created new tasks:

<img width="649" alt="Captura de Pantalla 2022-07-13 a la(s) 3 39 17 p m" src="https://user-images.githubusercontent.com/3276087/178830259-5e762c1c-5826-444f-a29a-3579f8a1bb30.png">

...but I don't think that's useful info, and in our case could only be useful to call out those who did not respond. How do you feel about it?

**Comment by jmtaber129** [comment]
@enriquesanchez I was mostly thinking about the "participants" stat at the top.

We _could_ include a list of people who have an empty response card, but that seems low importance for now

**Comment by jmtaber129** [comment]
The main issue is that if participants is the number of people who added a response, that number will always be the same as the "responses" stat.

**Comment by jmtaber129** [comment]
@enriquesanchez another issue I'm noticing as I'm getting into more styling - the existing generic summary email gives the white container 600px of width, while the Figma designs show this container as 680px.

I'd rather not expand the width without full context on why it's this specific width in the first place (I assume for email sizing), so I'm going to move forward by shrinking certain components a proportional amount, but let me know if you'd rather update the Figma designs.

**Comment by enriquesanchez** [comment]
>so I'm going to move forward by shrinking certain components a proportional amount, but let me know if you'd rather update the Figma designs.

I agree. I can quickly update the Figma mockup so you don't have to worry about this.

**Comment by enriquesanchez** [comment]
@jmtaber129 [Here's an updated mockup](https://www.figma.com/file/fw5gj7qRbKSh5XQbnh0PUr/Standups-tweaks?node-id=143%3A16635)

![image](https://user-images.githubusercontent.com/3276087/178845102-88e18c1d-482d-43e8-8a9e-d3adc21971b2.png)
