### ISSUE TITLE
Add "See how it works" link to the description of each integration 

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6805]
Add a See how it works link to the description of each integration that links to a support/help document that highlights how to use it.

![image](https://user-images.githubusercontent.com/466991/178793354-5c33c93e-e05a-4e7f-9184-dcc98f3c7fe5.png)

AC:
- Show `how it works` link in the description of each integration
- How it works URL leads to a support page, not landing page
- Use the new `seeHowItWorksUrl` prop added in #6804

**Comment by acressall** [comment]
I've created a [Notion task](https://www.notion.so/parabol/New-Integrations-landing-pages-c3260e301be146798ba3ee41f7b345e4) for @lorena-cure to tackle this (let us know if you need a hand). 
@igorlesnenko are those links going to be live soon? Do they go anywhere currently?

**Comment by igorlesnenko** [comment]
@acressall currently, ms teams and azure devlops are still under the feature flag.
However, Jira Server link will be available, possibly, on the next release.
It will look like this:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/466991/175297037-649714d8-6701-4eca-9800-91643fef3e2e.png">
Link goes to: https://www.parabol.co/integrations/jira-server/

**Comment by igorlesnenko** [comment]
Updated the AC. Looks like we need separate support pages, not link to landing pages. So we need to update URLs later, or do not merge the current PR before we get the correct URLs

**Comment by jordanh** [comment]
Labeling this a discussion as the word doesn't _really_ belong on our backlog. @igorlesnenko, let me know if you disagree

**Comment by jordanh** [comment]
Thank you @igorlesnenko !
