### ISSUE TITLE
Upgrade to Segment Analytics 2.0

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6806]
Segment upgraded our analytics [automatically to v2](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/#automatic-migration) which caused the following error:

https://sentry.io/organizations/parabol/issues/2373218413/?referrer=github_plugin

```
TypeError: window.analytics.page is not a function
  at apply (./packages/client/components/AnalyticsPage.tsx:139:24)
```

Right now we [manually switched back to v1](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/#revert-to-analyticsjs-classic) in the settings, but we might want to upgrade to profit from the smaller size etc.

**Comment by jmtaber129** [comment]
@Dschoordsch this was a Segment client upgrade, right?  I.e. not Amplitude?

**Comment by Dschoordsch** [comment]
@jmtaber129 You're right, I fixed the description.

**Comment by tghanken** [comment]
v1 will be sunset on August 31, 2022.  The data team will help implement and validate the upgrade before then.

**Comment by tianrunhe** [comment]
I quietly turned on analytics 2.0 and let it run for a while. It seems whatever issue we faced last time was auto fixed.

<img width="1142" alt="Screenshot 2022-11-18 at 11 04 41 AM" src="https://user-images.githubusercontent.com/1879975/202783022-2ecd6abf-c608-49f2-a830-c7b8db62a6f6.png">

**Comment by Dschoordsch** [comment]
Awesome!
