### ISSUE TITLE
Explore how other SaaS products automate SAML

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6811]
Background: https://github.com/ParabolInc/parabol/issues/4473

We want to automate enabling SAML as much as possible. 
This is not a unique problem to us, so we should see how other folks do it.

AC
 - [ ] check out how other apps let users turn on SAML (e.g. notion, figma, you name it)
 - [ ] take some screenshots of the forms & write up the flow. loom optional
 - [ ] discuss pros/cons of each approach
 - [ ] arrive at a decision on the cleanest approach
 - [ ] create a series of issues, including a design issue for the forms & necessary implementation issues

**Comment by nickoferrall** [comment]
Sharing some initial notes here. I'll add to this later with more consideration around pros/cons, suggested approach, plus ideally going through a whole SAML sign-up form:

The current flow (as I understand it from [this doc](https://www.notion.so/parabol/SSO-SAML-Data-Requirements-Checklist-3ba63c2fd33e41958d1ac7df9e3472d6)) is a company upgrades to Enterprise, a sales member from Parabol gets the `name`, `domains`, and `metadata` from the company, and then runs `enableSAMLForDomain` in GraphiQL. We provide the client with an ACS URL, entity ID, and start URL. This is a manual process, so we want to automate it to save us & customers time while reducing the possibility of errors.

Notion:

<details>

You need to be an Enterprise user to access the SAML form, but they have screenshots on their [website](https://www.notion.so/help/saml-sso-configuration). 

Enterprise users can add their domains, SSO URL, and IdP metadata URL/XML. After they add a domain, there are instructions on how to verify the domain with Notion. This involves navigating to the DNS records section and creating a new TXT record. 

After verifying the domain, you can remove the TXT record from the domain. Once the domain is verified, you'll receive a message letting you know.

There's then a guide on how to configure SAML with IdPs. 

![image](https://user-images.githubusercontent.com/39854876/177977093-9b73f92c-753c-40d4-aece-8b12759ae9b7.png)


</details>


Figma:

<details>

You also need to be an Enterprise customer to access Figma's SAML form, and [their guide](https://help.figma.com/hc/en-us/articles/360040532333-Guide-to-SAML-SSO) doesn't offer much detail about the process on their end. However, they do tell admins that they need to decide whether users can login via email & password or only SAML SSO. They recommend letting users login with both options which surprises me as it's less secure. 

I think it's good to give users the option of choosing either one, but it'd be best to recommend the more secure method. 

</details>


Atlassian:

<details>

Flow:

![domain](https://user-images.githubusercontent.com/39854876/178001526-cd6921e1-66b1-4cc1-af72-e137ee91bd96.png)

![verify-domain](https://user-images.githubusercontent.com/39854876/178001543-a2817bd2-5462-447f-9b8d-07d1220ee53b.png)

![https](https://user-images.githubusercontent.com/39854876/178001553-cbbdb629-8323-4a5d-86f5-73590856e853.png)

![goog](https://user-images.githubusercontent.com/39854876/178001560-644aa571-fb43-48d4-b201-25c1277476b1.png)

![pop-up](https://user-images.githubusercontent.com/39854876/178001576-379ac250-c32c-421e-afc0-443cee5afe76.png)

I couldn't verify the domain as I'd need to copy the TXT record to the DNS host.

</details>

Linear:

<details>

[Guide here](https://linear.app/docs/saml-and-access-control#2-update-your-identity-provider).

- send an email to users that includes SAML instructions
- user updates their Entity ID / Audience URL, Issuer ID, and Single Sign-On URL
- after the user adds Linear to their identity provider, they share their endpoint, signing algorithm, and signing certificate
- users can update the domains, binding, and signing algorithm type
- Linear reaches out to the customer once they've configured SAML. Unclear whether that step is automated

</details>

**Comment by mattkrick** [comment]
- i like notion & asana a lot!
- i don't know why notion has a UUID for the SSO url. using something human readable like what asana does seems better, that's how we do it today
- asana only asks for the URL & x509, they don't ask for the full metadata like notion. that means asana can't populate certain fields like a name or email using `md:NameIDFormat`. i think notion got this right. IMO, we should ask them to paste the metadata & if we detect that they pasted a link to the metadata, we fetch it. 
- i agree with you, SSO that ins't enforced defeats the purpose. that's how we have it set up today & i'd argue we should keep doing that until we get a customer who says otherwise
- a DNS TXT record is probably fine for v2, no need for multiple options like jira
- since we won't support DNS TXT record lookups in V1, we'll want to add `verifyDomain` as defined here: https://github.com/ParabolInc/parabol/issues/4473#issue-772507821

rough idea:
- a sales person calls `verifyDomain(domain: parabol.co, slug: parabol, method: manual)` in lieu of a TXT record lookup
- the user can go to their Org Settings & sees a link to open a SAML modal config, even if they aren't enterprise
- that modal shows all the verified email domains (ie the ones the sales person added), it has a text area for the metadata, and offers a SSO page link for them to copy (action.parabol.co/saml/<SLUG>). If not set up yet, the slug is just their email without the tld

really great job on digging into this! feel free to add any thoughts you have to help the designers build something & we can open the design issue

**Comment by ackernaut** [comment]
We can close this once we create a design issue. I have a task for that.

**Comment by ackernaut** [comment]
Closing in favor of next step, design issue #6951
