### ISSUE TITLE
Prompt user to go to next phase or end meeting

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6815]
Design from #6741 

https://user-images.githubusercontent.com/18582225/175158956-4dea61a6-048c-4ff1-afa3-a9933e3c4af5.mov

After [length?] of inactivity, the user will see the "next" item in the toolbar do a wiggle animation to hint at the next step. 
This will only appear for the facilitator.
We can test this in the demo. 

**Reflect phase:**
when there are no reflections in progress (other users) and none in focus (facilitator)?

**Group phase:**
when nothing has moved after 30s?

**Vote phase:**
When the remaining votes is at zero for 30s or has not changed for 30s

**Discuss phase:**
this is a tricky one since a lot could be happening sync in a call. Maybe we hint after 5 minutes?

Caveat: if the ready button is "full" before these conditions are met, the animation should start after 5s

**Comment by Dschoordsch** [comment]
I think we can also animate the ready button with similar criteria.

**Comment by acressall** [comment]
> I think we can also animate the ready button with similar criteria.

I like this idea. We get a lot of feedback about the ready button so it would be interesting to see if prominence is the issue and then figure out what else we want to do from there

**Comment by JimmyLv** [comment]
Hey @acressall sorry, I don't quite understand what you mean by " if prominence is the issue", do you mean the circle that is only 3/4 of the ready button?

<img width="29" alt="ParabolIncparabol-003579-20220715" src="https://user-images.githubusercontent.com/4997466/179155691-23c14490-9745-47bd-9190-ad4ce152e805.png">

I see that the current ⭕️ has only two states (no circle and full circle), so I'm curious if your latest design is trying to use the percentage of the circle to represent the current stage of the meeting? 😁

![Google Chrome-Retro Meeting  Demo Team-003580-20220715](https://user-images.githubusercontent.com/4997466/179155939-9ccb718e-8dd2-429a-bd93-378ad1e1801a.gif)

**Comment by acressall** [comment]
>  if prominence is the issue

I would like to understand if users are complaining because they don't notice it (which this experiment could solve) or if it's not intuitive enough. For example, our team often forgets to use the ready button even though we know it's there. So is the issue that people don't see it or that there needs to be more of a habit and benefit to doing it? Don't worry about the design here, it's more a question for the feedback we get after this is live

> I see that the current ⭕️ has only two states (no circle and full circle), so I'm curious if your latest design is trying to use the percentage of the circle to represent the current stage of the meeting?

Is this right? When there are multiple participants, I think the facilitator sees a percentage of how many participants have clicked "ready"

> Q1: but after all participants click on "Ready", the "Next" button on the facilitator's side becomes a "full" circle?
Q2: that means that when every participant is ready, the facilitator should start the next step immediately (within 5s), otherwise it will prompt an animation after 5s, right?

Yep, correct on both points here! 
1. When it is "full" only the facilitator will see the wiggle. The facilitator should only see it when the circle is full / everyone is ready (sorry for the design confusion here, it's not technically accurate)
2. If the participant has already clicked ready, they won't see it
3. If the participant has _not_ clicked ready, they will see it
_2 and 3 can be done later if you like, and we can just start with the facilitator view for now_


### Animation details:

- Delay: 2s
- Duration: 1000ms
- Iteration count: 3
- Transition timing: ease-in-back

Design file: https://www.figma.com/file/KJfNn58ksFO9c9oXhu2EQO/Grouping-prompt?node-id=10%3A1934
