### ISSUE TITLE
Improved Pro upgrade / checkout experience

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6816]
## Issue - Enhancement

Right now, to upgrade to Pro, a user needs to go to the Organizations page > click upgrade > modal opens > enter details. 

The limitations are: 
-  We can’t drop users right into the purchase flow
-  If we could just send a user to the modal, it would be unclear what they’re paying for.
-  We also can’t track the drop-offs along that process because of how it’s setup so it’s unclear how much of a problem it is. 

### Acceptance Criteria (optional)
New flow designed for upgrading an organization to Pro that allows for: 
* [ ] Tracking the key steps to analyze for drop-offs
* [ ] Having a dedicated URL that makes it clear what they're purchasing and allows them to make that purchase
* [ ] Design created for a billing page that includes the credit card info inputs & price
* [ ] a design where pro users can cancel subscription on their own 
* [ ] when users move to cancel their subscription, they can select multiple reasons to tell us why
* [ ] there is an optional text input box to tell us more

**Estimated effort:** 13 points

**Comment by jordanh** [comment]
Note: needs EE

**Comment by acressall** [comment]
UX Flow proposal: https://www.loom.com/share/6c7bbd844a1746d69362198c8dc71e0b

Figma: https://www.loom.com/share/6c7bbd844a1746d69362198c8dc71e0b
