### ISSUE TITLE
Invoice requirements

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#6825]
See this discussion for more https://github.com/ParabolInc/parabol/discussions/6569

Minimum requirements for [this](https://app.hubspot.com/contacts/3888472/contact/11132901) 🔒 client:

Name and address of your company (service provider)
Our company name and address (being billed as customer / service consumer / customer)
Your company (service providers) tax number
Date of issuing of the invoice
Invoice number (unique / sequentially)
Quantity / Amount and of delivered goods or service
Date of (service) delivery, if not equal to Date of invoice
Price, including discounts (if not included in pricing), if applicable separated by different tax rates
included taxes (rate and amount included), or notice about tax exemption
VAT Number

**Comment by jordanh** [comment]
Closing this issue in favor of design issue #6571. I moved these requirements there. Thank you for writing this up
