### ISSUE TITLE
feat(usage): Charts changes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6829]
This is a catch-all issue for discussing changes that we may want to make to domain stats.
My .02: ship it, we can edit if we hear bad things from customers.

@avivapinchas @ackernaut @nickoferrall 

Tensions:
- Meeting char: Legend should hide meting types if # of meetings = 0 for that type
- Meeting chart: Cumulative vs. monthly vs. add a toggle to change between the 2
- Address discrepancies between active users show in aggregate table vs. total users show in chart (is this OK, do we make it visually more pronounced? or do we change the data to match?)
- Address discrepancy between meeting count of all teams in aggregate table vs. meeting count of non-archived teams in chart
- [Add your own here]

AC
- [ ] A decision made about each item
- [ ] Implementation issue(s) created for each change order

**Comment by avivapinchas** [comment]
These feel like design questions, so assigning @ackernaut so someone is keeping an eye on this moving forward

**Comment by jordanh** [comment]
@mattkrick could this issue be closed now?
