### ISSUE TITLE
Standups: Highlight link text while link changer is open

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#6832]
When the link changer modal is open, we don't currently keep the link text highlighted within the editor.

### Acceptance Criteria (optional)
- [ ] Users can see the selected text when the link changer modal is open

**Comment by jordanh** [comment]
HELL YES! I just left a comment on the latest retro to suggest exactly this. Thank you for catching it before me

**Comment by BartoszJarocki** [comment]
@jmtaber129 I'm not sure exactly what this issue is about, could you please share a screenshot or something with the problem? thank you!
