### ISSUE TITLE
Improve `Invitation Link Expired` View

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6838]
Noticed in a few session replays that there are users who end up on the `invitation link expired` view. This view doesn't give the user an option to do anything except leave. We can add a few options:

1. Notify the team lead (we already tell them who it is, so I imagine it wouldn't be a _huge_ lift to send that person an email)
2. Sign up anyway _or_ go to their meetings dashboard, depending on whether or not they already have an account

Screenshot of the current view:

![Image](https://user-images.githubusercontent.com/18582225/176207754-e7b2903b-2d18-4ea6-9017-b989d24e108c.png)

## Acceptance criteria
* [ ] add a link to the expired dialog "Reach out to `Inviter name` to invite you again"
* [ ] the inviter gets a notification that someone wants to join

**Comment by jordanh** [comment]
Good idea!

**Comment by igorlesnenko** [comment]
Proposed solution:

Authenticated user:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/466991/188492118-065da2fb-b81e-4c20-aaed-a0ee7118176a.png">

Non-authenticated user:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/466991/188491993-a631f74d-970e-4429-8f2e-a691702b8b66.png">

I also have some concerns about sending notification email. If we send it automatically:

- User might get spammed, as every link opening will cause email to be sent.
- User accessing invite link might not have a Parabol account yet, so we will only sent a notification in some cases.

Would just displaying the team lead email solve the problem?

@acressall what do you think?

**Comment by acressall** [comment]
@igorlesnenko I think this is a good first step, and I like the button options for a next step too. I'm trying to think if there would be any reason someone would get upset with their email being exposed, but can't come up with a _good_ reason. WDYT?

**Comment by igorlesnenko** [comment]
@acressall if user send invite by email his email is exposed too. When invited user joins organization, he will see emails of the whole team too. So it feels safe for me

**Comment by enriquesanchez** [comment]
@acressall @igorlesnenko 

re: exposing the team lead's email: what if the invite link is not shared by email, for example I copy it and paste it in Slack?

Of if we used the recent experiment we did for the Remotely Agile event as another example, I imagine that the team lead's name and email would have been exposed to a much larger group of folks. Do you see any concerns there?

**Comment by igorlesnenko** [comment]
@enriquesanchez Just one note, I think currently not really team lead email but email of the person who created the link. 

I think if there are doubts about displaying data, it is easier to delete the email. Most likely the person will have the contact of the person who gave the link

Should we only keep buttons?

**Comment by enriquesanchez** [comment]
@igorlesnenko @acressall  My recommendation will be to say "Reach out to the team's lead to request a new one" instead. 

How does that sound?

**Comment by Dschoordsch** [comment]
We expose the email address of the invitee already in the invite email, so it feels safe. Although for mass invitation it might not be seen before.

I still would like to have a CTA to send an in-app notification to request an invite.

**Comment by enriquesanchez** [comment]
>I still would like to have a CTA to send an in-app notification to request an invite.

This sound like a good middle ground 👍

**Comment by igorlesnenko** [comment]
@Dschoordsch @enriquesanchez I'm not sure how `Request invite` button will work when anonymous user is trying to join using the link? He don't have any account

**Comment by enriquesanchez** [comment]
>I'm not sure how Request invite button will work when anonymous user is trying to join using the link? He don't have any account

@igorlesnenko Is it possible to have them sign in and then re-request the invite?

>Also what should we show after Request invite clicked? Just some snackbar with Invite requested message?

Yes, we should show a success or confirmation message. I think a snackbar is the right component for this 👍

**Comment by igorlesnenko** [comment]
> @igorlesnenko Is it possible to have them sign in and then re-request the invite?
@enriquesanchez we can show sign in button for them, after sign in (or sign up if no account at all) if they access the screen again they will be able to request invite.

**Comment by igorlesnenko** [comment]
@enriquesanchez or maybe better we can redirect them to sign up form anyway regardless fo link expiration. This is what we do for anonymous user if link is not expired

**Comment by enriquesanchez** [comment]
>or maybe better we can redirect them to sign up form anyway regardless fo link expiration

@igorlesnenko So they would see the signup/login form instead of the expired link message? And then how would they figure out that the link has expired?

**Comment by igorlesnenko** [comment]
@enriquesanchez in this case, they will figure it out only after sign up or login and will be able to request an invite.

What if we still show expired link window for them, but add a text that says "login or sign up to request invite again?"

**Comment by enriquesanchez** [comment]
>what if we still show expired link window for them, but add a text that says "login or sign up to request invite again?"

I like this!

**Comment by igorlesnenko** [comment]
@enriquesanchez made some updates

Authorized user:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/466991/192460677-85fe9e62-7280-43ee-9cf7-0f1a7e9aaa43.png">
Anonymous user:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/466991/192378399-7184101a-3819-46c5-8030-e96a0d9a72b8.png">


What do you think?

**Comment by enriquesanchez** [comment]
@igorlesnenko Much better 🙌 

I have some suggestions on the copy: 

**For the first one** we are saying "Reach out to Igor Lesnenko to request a new one", and then show them a button that says "Request invite". I think it is a bit confusing: do I reach out to Igor or do I click the button that says request invite?

My suggestion:

```
The invitation to New team 2 has expired.
Request a new invitation or reach out to the team administrator.

[Request Invite] [Go to Dashboard]
```


For the anonymous option:

```
The invitation to New team 2 has expired.
Sign in to request a new invitation or reach out to the team administrator.

[Sign in]
```

How does that feel to you? Is it more clear?
Also, @acressall would love your input here!

**Comment by igorlesnenko** [comment]
@enriquesanchez updated:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/466991/192752308-b7882b0f-eefe-4061-ae5f-289e478f010d.png">

<img width="641" alt="image" src="https://user-images.githubusercontent.com/466991/192752379-5e00d593-5129-4124-afc7-ca8b675e4c2c.png">

**Comment by enriquesanchez** [comment]
@igorlesnenko Much better!

How do you feel about using "team administrator" instead of the real name?

**Comment by igorlesnenko** [comment]
@enriquesanchez I think it is good, because on expired link there might be non relevant name.

**Comment by nickoferrall** [comment]
Hey @igorlesnenko, just checking if this issue is still In Progress and should be in Squad 2?

**Comment by igorlesnenko** [comment]
@nickoferrall It is still in progress. I pushed a PR #7153, but noticed that the requested fix is not very easy to do. I plan to return to this issue and finish.

**Comment by jordanh** [comment]
@igorlesnenko hi there! This issue is getting a bit stale. Would you like to carry it over the line or shall I close it?

**Comment by igorlesnenko** [comment]
Hi @jordanh! I'm closing this issue as we merged some improvement here
