### ISSUE TITLE
Remember WIP Reflections

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6839]
## Issue - Enhancement
A user writes:

> When you writing a really long retro note and the host clicks next and you lose what you wrote. Yeah, that's annoying.  

Questions to consider:
- Where would the in-progress reflection go in the group phase?
- Would the in-progress reflection be only visible to the author? 
- Would it technically still be "in progress" or do we save it as done?

**Comment by Dschoordsch** [comment]
What if we would handle it similar to discussions, if you're writing, you
stay at the reflect phase and have to rejoin?
We would only allow to finish the current one and then you could rejoin to
the group phase. I think this would be the least disruptive.

**Comment by jordanh** [comment]
Personally I'd like to see us just leave the text in the Reflection field so that the user could go back a phase and hit submit if they'd like.

This issue came up during a scrub. I am going to icebox it for now. Please feel free to reopen it if the tension should arise again.
