### ISSUE TITLE
Standups: The default title should have a date instead of a sequence number

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6850]
The sequence number that we have right now does not make too much sense. Standup, by default, is tied to a given day so let's use a more human-readable format. Suggested format - `Async standup - Oct 14, 1983`. 

AC
- [ ] When starting the meeting, the standup title is by default `Async standup - Oct 14, 1983` (with today's date).

**Comment by BartoszJarocki** [comment]
@enriquesanchez is the date format ok? or do you have any other suggestions?

**Comment by BartoszJarocki** [comment]
I guess we should get rid of the year, it's too long
![action parabol co_meetings (1)](https://user-images.githubusercontent.com/1017620/177476778-cee9aaf1-0907-460b-b9c7-734d27d45a4a.png)

**Comment by BartoszJarocki** [comment]
![localhost_3000_meetings](https://user-images.githubusercontent.com/1017620/177588845-24002035-9db1-4645-a8e4-bf050b3d58fd.png)

I think this looks ok, @enriquesanchez please let me know what do you think, thanks!

**Comment by BartoszJarocki** [comment]
@enriquesanchez IMO it looks a bit cleaner with a hyphen but I don't have strong preferences here

**Comment by enriquesanchez** [comment]
@BartoszJarocki No strong preference here either, so if you think with the hyphen is better then go for it 👍
