### ISSUE TITLE
Standups: Fix showing active standups as 'completed' on the meeting dashboard

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6851]
Currently, even after starting the meeting we show `Complete` in the standup meeting card.
![action parabol co_meetings](https://user-images.githubusercontent.com/1017620/177472386-8d3b1d79-d9b5-4cb0-993d-a510a38b986b.png)

The reason it happens is there's no label in the lookup object for the responses phase
```
export const phaseLabelLookup = {
  checkin: 'Icebreaker',
  reflect: 'Reflect',
  group: 'Group',
  vote: 'Vote',
  discuss: 'Discuss',
  updates: 'Solo Updates',
  firstcall: 'First Call',
  agendaitems: 'Team Agenda',
  lastcall: 'Last Call',
  SUMMARY: 'Summary',
  SCOPE: 'Scope',
  ESTIMATE: 'Estimate'
} as Record<NewMeetingPhaseTypeEnum, string>
```

AC
- [ ] there's no `Complete` label displayed on the meeting card for standups

**Comment by BartoszJarocki** [comment]
@enriquesanchez do you think we should just hide it or display something else here? would appreciate your thoughts, thank you!

**Comment by enriquesanchez** [comment]
@BartoszJarocki I think we should do the same that we do on other meeting types, which is to show the status of the meeting. Now, we don't have phases for standups, and in simple terms, a standup can either be open or closed, right?

So the first option that comes to mind is `Open`.  Meaning the standup is open and the user can add their response.
On the other hand, I don't love `Closed`. It gives the feeling that the standup can't be accessed anymore? I wonder if there's another word to describe that it has ended but folks can still open it and reply to responses?

`Started` and `Ended` maybe?

**Comment by BartoszJarocki** [comment]
@enriquesanchez yeah, it's tricky! `Started` sounds good to me. We won't have `Ended` as when we close the meeting, it disappears from the meeting dashboard. it'll be just `Started`, otherwise meeting card won't be visible.
