### ISSUE TITLE
Standups: Design 'Beta' notice

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6855]
Design a notice to let users know that the Async Standups feature us in "beta" stage.

## Acceptance criteria
- Design concepts, mockups and user flows for the early access notice and form
- Gather feedback and iterate as necessary
- Create implementation issue once the designs have been green-lighted

### Estimated effort
4 hrs

**Comment by enriquesanchez** [comment]
![image](https://user-images.githubusercontent.com/3276087/178372332-0b8dbd22-2d74-4047-950d-b2eb3c0deea8.png)

We can add a `Beta` badge to the standup illustration. Both color and position should work together to make it stand out enough to be noticed.

**Comment by BartoszJarocki** [comment]
@enriquesanchez it looks good! the only question I have is, how does it suppose to look on mobile?
![localhost_3000_new-meeting_dXGo9DDk2t(iPhone SE)](https://user-images.githubusercontent.com/1017620/178553531-44aa9c8c-d800-40a6-aba3-9b0658dc1aab.png)

**Comment by jordanh** [comment]
Should anything appear in the meeting view itself to let participants know this is a beta experience?

**Comment by enriquesanchez** [comment]
@BartoszJarocki Yep, you are correct

**Comment by enriquesanchez** [comment]
Reopening to address the new meeting lobby designs:

Desktop:
![imagen](https://user-images.githubusercontent.com/3276087/181385975-2921fd0f-a943-4404-9eb6-483d770ec190.png)

...and mobike:
![imagen](https://user-images.githubusercontent.com/3276087/181386521-5e9b6b3d-25de-469c-a1ba-74be0cd42d1f.png)

There's an `8px` offset top and right on the Beta badge.

**Comment by ackernaut** [comment]
This isn’t feedback on the design, but, what’s the goal of the beta? When do we know we are no longer in beta?

**Comment by enriquesanchez** [comment]
And here's the Beta badge on the un-selected state:

![imagen](https://user-images.githubusercontent.com/3276087/181613655-b9872487-cc9b-4330-8a74-6d1bb4c54a61.png)

**Comment by enriquesanchez** [comment]
>what’s the goal of the beta? When do we know we are no longer in beta?

@ackernaut Main goal is engaging customers to give us feedback. By signaling that the feature is "in progress", we not only set expectations, but also open the door for customers to help us make it better.

**Comment by enriquesanchez** [comment]
Implementation happening here: https://github.com/ParabolInc/parabol/pull/6961
