### ISSUE TITLE
Poker: Discussion drawer is not accessible (or troublesome) on mobile devices

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#6858]
## Issue - Bug
Tested on Chrome and Firefox on Android:
#### Chrome
Weird behavior due to URL bar when scrolling:

https://user-images.githubusercontent.com/106697681/177599519-9f05f8c1-218f-4ffb-84e6-1b56df5b27e6.mp4

#### Firefox
Similar to Chrome

https://user-images.githubusercontent.com/106697681/177599448-a76b47ee-721f-4d41-be24-d72d6e19b15a.mp4

Moreover, we could implement similar to this:

https://user-images.githubusercontent.com/106697681/177599493-bcc84f4f-e96a-4931-813d-13860c24836e.mp4

**Comment by jordanh** [comment]
Thank you @87prashant for your report. Going to prioritize this as a p4. If we get other independent reports that this is bugging our users (or we see an uptick Android usage) we will reprioritize higher

**Comment by 87prashant** [comment]
`dvh` now supported on chrome android.
