### ISSUE TITLE
Check-in: Task assignee menu is missing entries

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6862]
## How to reproduce
* Start check-in meeting with 3 participants
* Try reassigning a task in Solo updates
* Try reassigning a task in Agenda item discussion

## Expected behaviour
Assignee menu shows all team members.

## Actual behaviour
Assignee menu shows different subset of members depending on stage.
![Screenshot from 2022-07-07 13-37-03](https://user-images.githubusercontent.com/7331043/177777002-134b523d-d8a4-4813-81f3-566bdf408a09.png)
![Screenshot from 2022-07-07 13-34-34](https://user-images.githubusercontent.com/7331043/177777045-a9b16466-b126-4cf9-a613-1e92f714b024.png)

**Comment by jmtaber129** [comment]
@Dschoordsch what's the desired behavior here when the current assignee is selected from the list of team members? No-op, make task unassigned, something else?

**Comment by Dschoordsch** [comment]
> @Dschoordsch what's the desired behavior here when the current assignee is selected from the list of team members? No-op, make task unassigned, something else?

We don't have unassigned tasks, so a no-op would be fine. We could also filter out the author, but then the list is different for each tasks and if you assign multiple tasks it could be annoying. I would prefer to show all members but disable the entry for the current assignee.

**Comment by jmtaber129** [comment]
@Dschoordsch I tried to repro this on master to compare master to https://github.com/ParabolInc/parabol/pull/7160, but I'm not actually able to repro unless I'm the only one on the team.

Can you provide a bit more detail about how to repro?

**Comment by Dschoordsch** [comment]
@jmtaber129 I don't have more reproduction information, we noticed this when running a check-in as release smoke test with 3 participants.

**Comment by jmtaber129** [comment]
Closing this as we don't have a repro
