### ISSUE TITLE
Standups: Design feedback method in-meeting

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6864]
Design a method for early access customers of the standups tool to provide optional feedback to us. [Also look into including the `BETA` badge.](https://github.com/ParabolInc/parabol/issues/6855#issuecomment-1182110186)

## Acceptance criteria

- Design concepts, mockups and user flows for the feedback method
- Gather feedback and iterate as necessary
- Create implementation issue once the designs have been green-lighted

### Estimated effort
4 hrs

**Comment by enriquesanchez** [comment]
Here's an update on my progress:

![image](https://user-images.githubusercontent.com/3276087/179120048-e35be9a0-1b7d-4b8f-847b-fa24fa6dd3a0.png)

I propose we add a `Beta` badge to the meeting view as well, but the one in the meeting will also act as a button that brings up a little modal where we can add the questions we want folks to respond to. The button uses the same purple color we use in the create meeting view, this along with the icon, helps it stand out enough to encourage folks to click it. The placement is also in a spot where it will be hard to miss. 

As for the questions, I'd love to hear from @lorena-cure @BartoszJarocki @jmtaber129  if you have any suggestions. At this point I don't think there's anything super specific that we want to find out from our users, so I've started by suggesting:

> - What’s one thing you _like_ about our standups tool?
> - What’s one thing you _don't like_ about our standups tool?

Whatever we ask, we should encourage thoughtful feedback and avoid questions that can lead to generic responses that we can't do much with. Things such as _"I hate it"_ or _"It sucks"_ don't give us much to work with, which is why I think we should avoid open ended questions. **Do let me know if you have different or better ideas!**

@BartoszJarocki @jmtaber129 I'd love your input on the technical side of this. Where should responses go to and how do we set that up? Can we use a 3rd party service to collect responses? Should we do a custom thing instead?

**Comment by Dschoordsch** [comment]
> As I proposed in the product check-in, I think a simpler & faster way is to put a HubSpot chat bot here. We already have the architecture setup for meeting summary page so it costs a little to set it up here. We will get feedback flowing into HubSpot & Slack channel and all the goodies there.

We don't need any changes in the app, the HubSpot chat bot can be set up completely in HubSpot.

**Comment by enriquesanchez** [comment]
@tianrunhe @Dschoordsch Thank you! This will definitely make it easier for us.

I'm going to close this issue and create a new one to track the task of setting of the Hubspot chat bot.

cc @BartoszJarocki
