### ISSUE TITLE
Implement Stripe Climate

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6868]
With Stripe Climate, we could direct 1% (or whatever % we choose) of our Pro subscription revenue to remove carbon from the atmosphere. Read more about how it works [here](https://stripe.com/docs/climate/faqs) and [here](https://stripe.com/en-gb-us/climate). 

This would be an effective way for us to have a positive impact on the environment, which is something that we've been discussing internally. 

Reducing our Pro revenue by 1% over the long run will likely be costly. However, our [current conversion rate](https://analytics.amplitude.com/parabol/chart/yx2yxq0/edit/se7kpsy) for users that open the credit card modal is low. If this helps to boost that, it would be a good business decision too.

![image](https://user-images.githubusercontent.com/39854876/178240711-d36d106f-0e85-4a9f-a2f8-089125392eea.png)

I suggest that we only do this with Pro upgrades to start with, not Enterprise invoices. If we get feedback from users that they were happy to see this contribution, we could consider adding it to Enterprise invoices too.

### AC

- [ ] Enable Stripe Climate in Stripe's dashboard 
- [ ] Update the modal UI to include the message that 1% of the subscription will remove CO₂ from the atmosphere
- [ ] Let Growth know once it's been implemented as it could be worth tweeting about

### EE: 3 

Note: my Stripe permissions would need to be upgraded to Admin to be able to implement this.

**Comment by jordanh** [comment]
It's a nice idea, let me run the business model impact analysis with @avivapinchas before we prioritize—but I am in favor

**Comment by nickoferrall** [comment]
Slack thread related to this issue: https://parabol.slack.com/archives/C836NA350/p1665067839935699

The financial model will be reviewed in an Exco meeting soon and we'll hopefully be able to implement this

**Comment by Dschoordsch** [comment]
This should be put on ice for now, see Slack.
