### ISSUE TITLE
Standups: Navigating away from a standup with an in-progress response causes the response to be lost - should be persisted in localstorage

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6871]
See [miniRFC​](https://www.notion.so/parabol/miniRFC-Persist-draft-standup-responses-ee2d82b79055447992aea5e3601c4c90) 🔒

**Comment by Dschoordsch** [comment]
Should we store it on the server instead? I don't want to submit a response on blur but saving a draft should be fine
