### ISSUE TITLE
Standups: Autofocus the input in the discussion drawer when opened

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6873]
​

**Comment by Dschoordsch** [comment]
Fix was reverted as it conflicted with the follow facilitator logic:
* the cursor would go into the discussion drawer
* when the facilitator goes to the next stage, the user would remain on the current stage and see the "Rejoin" button

I think it would be safe to modify the logic to leave the viewer behind only if their input is non-empty and not based on the focus being in the discussion drawer.
