### ISSUE TITLE
Disable integrations globally for an org 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6882]
An [enterprise prospect](https://app.hubspot.com/contacts/3888472/deal/5362696559/) 🔒 asked if we could remove the Github integration from our integrations menu so that no one would be tempted to use it. 

Let's collect more signal here to see if this is something we should build into the new admin dashboard.

**Comment by treyparabol** [comment]
An enterprise prospect [https://app.hubspot.com/contacts/3888472/company/5749228585](url) 🔒 asked of we could block the integration on their account due to a potential infosec issue.

**Comment by jordanh** [comment]
Iceboxing per policy.

Should this come up again, this is the kind of policy I would expect Enterprises to pay for. Draconian as I find it.
