### ISSUE TITLE
Sprint Poker returns incorrect data, resulting in an undefined error for getting value or deconstructing

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#6889]
## Issue - Bug

<img width="1087" alt="Google Chrome-Issues - parabol - Sentry-003586-20220715" src="https://user-images.githubusercontent.com/4997466/179184986-824e70b5-f11e-472c-b548-afde7ed4fe33.png">

```js
TypeError ?(packages/client/components/EstimateDimensionColumn)
Right side of assignment cannot be destructured

TypeError ?(packages/client/components/PokerCardDeck)
Right side of assignment cannot be destructured

TypeError ?(packages/client/components/ParabolScopingSelectAllTasks)
Cannot read properties of undefined (reading 'node')

TypeError c(packages/client/components/GitHubScopingSearchResults)
Cannot destructure property 'integrations' of 'g' as it is null.

TypeError c(packages/client/components/ParabolScopingSearchResultItem)
Cannot destructure property 'id' of 'n' as it is undefined.
```

Not sure what kind of use case would cause these errors on [Sentry](https://sentry.io/organizations/parabol/issues/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d), or maybe separate data errors are triggered?

Sentry Issues:

- [TypeError: Cannot destructure property 'id' of 'n' as it is undefined. - parabol - action-production](https://sentry.io/organizations/parabol/issues/3393847750/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d)
- [TypeError: Cannot destructure property 'integrations' of 'g' as it is null. - parabol - action-production](https://sentry.io/organizations/parabol/issues/3410062671/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d)
- [TypeError: Cannot read properties of undefined (reading 'node') - parabol - action-production](https://sentry.io/organizations/parabol/issues/2699461488/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d)
- [TypeError: Right side of assignment cannot be destructured - parabol - action-production](https://sentry.io/organizations/parabol/issues/3416470299/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d)
- [TypeError: Right side of assignment cannot be destructured - parabol - action-production](https://sentry.io/organizations/parabol/issues/3416470300/?project=107196&query=level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned+is%3Aunresolved&statsPeriod=14d)

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by JimmyLv** [comment]
Hey @nickoferrall, have you touched any of the code related to Sprint Poker recently? could you please take a look at this issue?

**Comment by jordanh** [comment]
Only one issue is still occurring: https://parabol.sentry.io/issues/2699461488/?project=107196&query=level:fatal+timesSeen:%3E5+is:unassigned+is:unresolved&statsPeriod=14d

Going to icebox for low-ish frequency.

Watermark: 37 events, 4 users affected
