### ISSUE TITLE
Poker meeting says it's ended when it hasn't, no one can vote 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6890]
Here's a poker meeting mystery from [this user](https://app.hubspot.com/contacts/3888472/contact/53007401) 🔒 

They originally wrote in asking:

> Hello. Our grooming meeting closed before our meeting. Do meetings have a time limit?

Then:

> When people attempt to vote, including myself as the facilitator, it says the Estimate phase is already complete. The meeting had no prior votes, never been closed (as the option to end the meeting is still there), and there are no options available to reset or reopen. Trying to prevent this in the future but to do that I need to understand why we get this error. Could you please help?

[This is the meeting in question](https://action.parabol.co/meet/eAmAkBUyTm/estimate/1) 🔒 

I impersonated them and confirmed that it won't allow votes, as shown in the gif I made. When I try to look at the meeting from their timeline view (where I assume it should be if it's closed?) I get an error.

@nickoferrall tried to repro this in prod, but wasn’t able to

**Comment by jordanh** [comment]
Will elevate in priority if we get another, similar report

**Comment by 87prashant** [comment]
@jmtaber129 
I think this issue is also fixed and can be closed.
