### ISSUE TITLE
Design more visible integrations link

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6894]
As discussed in https://github.com/ParabolInc/parabol/issues/5939, we want to increase the awareness of our integrations. The current flow to find integrations is:

- Click on Team
- Click on `Settings & Integrations` font size 12 hyperlink
- Click on Integrations

We want to make Integrations link more visible and easily accessible.

I also noticed that if you are not owner of an organisation, team settings looks empty, which might be confusing

<img width="829" alt="image" src="https://user-images.githubusercontent.com/466991/179497233-74b197e3-4a0f-4da4-bab0-2f5d14d6cd0a.png">

It would be nice if we can link directly to integrations.

See previous discussion here #6556 and here #6867

**Comment by acressall** [comment]
Early concepts! This has two parts:
### Team settings screen
Right now if you are not a team lead you see an empty team tab. Let's swap the tabs so you see integrations first.
**Possible side benefit:** For team leads who are gaming the pricing by removing team members each month, we're adding a bit more friction for them to do that. 
**Hypothesis:** by reducing the time to get to integrations by 1 click, we might have more people try them out. 
![Settings](https://user-images.githubusercontent.com/18582225/181578578-292ad7c0-a113-4e30-853f-ffafa3939d0a.png)

### Team Dashboard
Three possible concepts here.

1. Increase the text size of the "settings & integrations" link
**Hypothesis:** The link will be easier to see so more users will click on it to see what's there
**Caveat:** The hierarchy isn't great when we make it larger. It might compete with the left nav
![Team view - Larger text](https://user-images.githubusercontent.com/18582225/181579078-07c1f6e1-f198-4f73-b930-d3a99fc1a8a8.png)

2. Settings icon
**Rationale**: The top right is a common place to find settings, so it might be a place users look more. It doesn't specifically call out integrations though, so it is imperfect
![Team view - Settings icon](https://user-images.githubusercontent.com/18582225/181579401-20a72aeb-dd45-4951-98ec-a90f9d980209.png)

3. Team dropdown nav
Rationale: this pattern is taken from Google Drive. Airtable also has something similar. The nice thing is there's room to add more options here, for example, maybe users can edit the team name inline if we add an option here, or if we have a "team health check" type feature it could fit here. It is a larger break from existing patterns though, so we might not want to do it at this stage.
![Team view - Dropdown](https://user-images.githubusercontent.com/18582225/181580167-dd8baca2-edb2-4d8a-9b2a-901203f70f9c.png)
![Team view - Dropdown open](https://user-images.githubusercontent.com/18582225/181580165-2546fb83-ef2f-4897-97f0-bb0ab9e5dbbb.png)

**Comment by jordanh** [comment]
@acressall could you please add a swag of AC?
