### ISSUE TITLE
Standups: Implement Hubspot chat bot

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#6898]
See #6864 for more context.

We need to implement the Hubspot chat bot inside the standup meeting in order to give customers a way to submit feedback.

### Acceptance Criteria (optional)
Users can:
   - Submit feedback to us via a Hubspot chat bot

**Estimated effort:** 
  - TBD

**Comment by enriquesanchez** [comment]
@tianrunhe For the EE, would you have an idea of how much time it will take a dev to implement the chat bot?

**Comment by tianrunhe** [comment]
> @tianrunhe For the EE, would you have an idea of how much time it will take a dev to implement the chat bot?

@acressall should have a good idea on this!

**Comment by BartoszJarocki** [comment]
if I understand @Dschoordsch correctly, there's no dev time needed 
https://github.com/ParabolInc/parabol/issues/6864#issuecomment-1189015582 
can we enable it per URL or how does it work?

**Comment by enriquesanchez** [comment]
>there's no dev time needed

I got the same impression as well, but I still want to track the task here 👍

**Comment by acressall** [comment]
Yes, it's very easy to do! As long as there is a standard URL structure, but in this case it looks like we don't have anything specific to standups after `meet`. This might make the chatbot appear for all meeting types.

Once we know _where_ it's going, we can easily set up the chat in HubSpot. You can choose to have an open question, like we had in `#t_product_feedback` in slack, or it can be a chatbot where users go through a selection of choices. 
Here's a how-to for creating a chatbot: https://www.notion.so/parabol/How-to-Create-a-chatbot-4f6e2f297da54e1083af22777af0d6bf

**Comment by acressall** [comment]
We can also target referral URLs if that's helpful

**Comment by BartoszJarocki** [comment]
@acressall do you have any ideas on how we can make chatbot available only for one meeting type? for now, standups URL ends with `/responses` that's the only phase we have, would that work?

**Comment by BartoszJarocki** [comment]
that's awesome. it would be even better if there's `ends with` instead of `contains` but both should work!

**Comment by acressall** [comment]
Agreed! We have a `begins with` option, but no ends, unfortunately 😞
