### ISSUE TITLE
Standups: user behavior events added

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6902]
## Issue - Enhancement
In order to understand how user interacts with Standup, we need more events than `Meeting Started` and `Meeting Completed`. For V1 I propose:

- Response Added
- Response Updated
- Comment Added (we have this today but we need a `meetingType` attribute to distinguish among different types of meetings)
- Reactji Added

### Acceptance Criteria (optional)
- [ ] When user adds a response in a stand up meeting, a `Response Added` event is emitted to Segment
- [ ] When user updates a response in a stand up meeting, a `Response Updated` event is emitted to Segment
- [ ] When user add a comment to a response in a stand up meeting, the `Comment Added` event is emitted to Segment, with a new attributed `meetingType`
- [ ] When user add a reactji in a stand up meeting, a `Reactji Added` event is emitted to Segment

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
@BartoszJarocki just a heads-up on this issue. I'll probably do it later.

@avivapinchas any other metrics you'd like to see here? Make a wish list and we will _partially_ fulfill it 😜

**Comment by avivapinchas** [comment]
This LGTM! Thanks for giving me a chance to think about this 😄
