### ISSUE TITLE
TypeError: Cannot destructure property 'id' of 'i' as it is undefined.

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#6913]
https://sentry.io/organizations/parabol/issues/3429643481/?referrer=github_plugin

**Affected users in the last 24h:** 3 users
**First seen:** 13 days ago

```
TypeError: Cannot destructure property 'id' of 'i' as it is undefined.
  at c (./packages/client/modules/meeting/components/ReflectTemplateItem.tsx:63:14)
...
(10 additional frame(s) were not displayed)
```

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-BX4](https://sentry.io/organizations/parabol/issues/3543368654/?referrer=github_plugin)

**Comment by jordanh** [comment]
Issue no longer in Sentry. Presumed fixed.
