### ISSUE TITLE
Recurrence MVP: `stopRecurrence` mutation

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#6918]
Backend spec: https://github.com/ParabolInc/parabol/issues/6888

Blocked on https://github.com/ParabolInc/parabol/issues/6916

Implement the `stopRecurrence` mutation, which ends recurrence for the meeting series associated with the provided meeting ID.

### Acceptance Criteria (optional)
- [ ] When `stopRecurrence` is executed:
  - [ ] The meeting series' `cancelledAt` is set to `now`
  - [ ] The `scheduledEndTime`s of any open meetings in the series are set to null
- [ ] Errors are returned if 
  - [ ] The meeting doesn't exist
  - [ ] The meeting is not associated with a meeting series

**Comment by BartoszJarocki** [comment]
@jmtaber129 what do you think about having `meetingSeriesId` as a parameter instead of `meetingId`? imo it'd be more future proof and make sense
