### ISSUE TITLE
Recurrence MVP: Restart recurrence in `startRecurrence` mutation

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#6921]
Backend spec: https://github.com/ParabolInc/parabol/issues/6888

Blocked on https://github.com/ParabolInc/parabol/issues/6916

Add support for restarting recurrence via the `startRecurrence` mutation.

### Acceptance Criteria (optional)
- [ ]  When `startRecurrence` is executed on a meeting with an inactive meeting series
  - [ ] The series `cancelled_at` is set to null
  - [ ] The `scheduledEndTime` of the current meeting (and any other open meetings in the series) are set to a reasonable time in the future
  - [ ] The next `processRecurrence` run doesn't create or end any meetings in this series

**Comment by BartoszJarocki** [comment]
@jmtaber129 do you foresee any case where we'd have many meetings opened in the meeting series? I just wonder if it's good behavior. Maybe for the MVP we should assume there's only one meeting open? it'd simplify this task by not requiring to update `scheduledEndTime` for any meeting, except for the one that was used to call `startRecurrence`. I think we'd need to put some effort to think about how we want to handle all the cases with multiple meetings opened at the same time, not sure if it's worth it right now
