### ISSUE TITLE
Cannot find module './generated/getUsersByIdsQuery'"

### ISSUE THREAD

**Issue by vvp1983** [ParabolInc/parabol#6926]
After **yarn && yarn build && yarn start**  get error
branch master
```
yarn run v1.22.19
$ node scripts/prod.js
🙏🙏🙏      Building Production Server      🙏🙏🙏
webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:7
Object(function webpackMissingModule() { var e = new Error("Cannot find module './generated/getUsersByIdsQuery'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
                                                 ^

Error: Cannot find module './generated/getUsersByIdsQuery'
    at webpackMissingModule (webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:7:50)
    at eval (webpack://parabol-action/./packages/server/postgres/queries/getUsersByIds.ts?:7:155)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:171:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:9267:41)
    at eval (webpack://parabol-action/./packages/server/utils/segmentIo.ts?:7:89)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:426:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:9267:41)
    at eval (webpack://parabol-action/./packages/server/graphql/mutations/addAgendaItem.ts?:14:74)
    at Array.<anonymous> (/opt/parabol/scripts/toolbox/updateSchema.js:293:1)
    at __webpack_require__ (/opt/parabol/scripts/toolbox/updateSchema.js:9267:41) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 87prashant** [comment]
I think it will run after successful `yarn db:start`

**Comment by vvp1983** [comment]
> yarn db:start
it will be first build and after build start.
```
yarn db:start
yarn run v1.22.19
$ docker-compose -f docker/dev.yml up -d
Creating network "docker_parabol-network" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-362f42cdc492 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Dschoordsch** [comment]
Could you please try again after upgrading docker and using `docker compose`? See #6925

**Comment by vvp1983** [comment]
> Could you please try again after upgrading docker and using `docker compose`? See #6925
Official version.
docker --version
Docker version 20.10.17, build 100c701

```
dnf list | grep docker
containerd.io.x86_64                                              1.6.6-3.1.el8                                             @docker-ce-stable
docker-ce.x86_64                                                  3:20.10.17-3.el8                                          @docker-ce-stable
docker-ce-cli.x86_64                                              1:20.10.17-3.el8     
```
How **var e = new Error("Cannot find module './generated/getUsersByIdsQuery'"** relates with docker compose?

**Comment by Dschoordsch** [comment]
> How **var e = new Error("Cannot find module './generated/getUsersByIdsQuery'"** relates with docker compose?

Your last `yarn db:start` message showed some error which might be related to docker compose.
The file file mentioned (and others) are generated on the first run of `yarn dev` from SQL definitions. Generation of the queries requires the Postgres database to be running and all migrations to be run so that it can query types from the DB. If your `yarn db:start` failed, then this will not work.

For development we run `yarn db:start` and then `yarn dev`. The second command will monitor file changes, rebuild and reload affected parts. It may show some errors at first startup as all services are started in parallel and thus there are some race conditions, but it should settle and there shouldn't be any on a second `yarn dev` run.

**Comment by nyabut-id** [comment]
For me, when I ran `yarn db:start` after seeing the "Cannot find module" error, the problem was that the server I am using runs on ARM64 and the platform is specified to be x86_64 in docker/dev.yml.

**Comment by Dschoordsch** [comment]
@nyabut-id I'm not sure how this is solved, but others run it this way successfully @BartoszJarocki @igorlesnenko

**Comment by BartoszJarocki** [comment]
I'm building the app on an m1 mac without any issues. 

To be clear, @vvp1983, do you want to build and run the prod version? Our prod version is built by circle ci, and there, before running `yarn build` and `yarn start`, we run this: https://github.com/ParabolInc/parabol/blob/4bdb32b83208b7092d7311a60713dd5f1f91dc1c/.circleci/config.yml#L68 

It means that if you want to build a prod version locally, you need to prepare the DB and generated DB queries by running `yarn install && yarn db:start && yarn db:migrate && yarn db:migrate up && yarn pg:build`. After preparing the db and generated queries, you can run `yarn build && yarn start`. 

If you want to run a dev version, all you need to do is `yarn install && yarn db:start && yarn dev`

**Comment by jordanh** [comment]
@kastyle please re-open if still an issue

**Comment by Norazan** [comment]
Hi, I get this issue even after trying the various suggestions in the thread. I tried creating a docker container with `docker compose` as well as manually running `yarn && yarn db:start && yarn build`, both resulting in the same MODULE_NOT_FOUND error. The manual attempt was on a Windows x64 system. I can provide any more info if required.
