### ISSUE TITLE
Usage: should we show active Teams & Members, rather than Total? 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6936]
## Issue - Enhancement

Opening an issue to collect feedback on whether having "meetings" be cumulative is misleading. This issue is just meant to collect signal and feedback from users.

### Acceptance Criteria (optional)
Parabol team is clear on whether users expect to see active teams and members in the charts. A design or implementation issue has been created, if we intend to make a change.

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by nickoferrall** [comment]
Discussed during our check-in: Closing as there hasn't been any user tension
