### ISSUE TITLE
Add Upgrade button to meeting summary

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#6939]
In the Growth retreat [pricing discussion doc](https://www.notion.so/parabol/Pricing-Plan-Discussions-5c34fda167684d828b827a7914ba1a03#127218d14bab4fc39d369cdd84bd0f94), one idea was to add an upgrade button to the meeting summary. 

Perhaps we could replace the "Go to Team Dashboard" button with an "Upgrade" button? Or we could make the "Go to Team Dashboard" a secondary button and "Upgrade" a primary button. 

![Screenshot 2022-07-26 at 13 06 41](https://user-images.githubusercontent.com/39854876/181001963-11f1151a-2ec4-4120-95e6-fd1a65802e08.png)

### AC

- [ ] Design created that includes an Upgrade button in the meeting summary

**Comment by mattkrick** [comment]
IMO, I don't think anyone is gonna upgrade from a meeting summary & i'd rather invest the time in something else

**Comment by nickoferrall** [comment]
Makes sense 👍
