### ISSUE TITLE
Usage: Active Teams definition refined 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#6948]
## Issue - Bug

There's a discrepancy between the 'active teams' in our Domain Stats report and what we're seeing in the Usage Stats report in-app. We should figure out this discrepancy and resolve it. 

### Acceptance Criteria (optional)
Domain Stats and Usage Stats show the same number for Active Teams across ~5 domains we check, including parabol.co. 

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
Current definition

> teams with at least 2 team members who have logged in within the last 30 days & within an active organization that has had a meeting that has an updatedAt newer than 30 days ago


Discussion

I think my ideal "Active Team" definition would be:
A team with >1 member, that had a meetingStart, meetingEnd, or meeting updatedAt timestamp within the last 30 days.
An "Onboarded Active Team" would be the same criteria, with an added >2 lifetime meetings.

Matt
  10 minutes ago
archived teams count? do the 2+ users have to be active?


Taylor
  5 minutes ago
Archived teams don't count.  We treat them as fully removed everywhere on our end.  Today, we look at 2+ lifetime users, not active users.  Interested to hear if 
@Aviva
 would prefer active users there.


Matt
  4 minutes ago
gotcha. i think we have the same definition then! updatedAt will always be >= createdAt, and it gets set to endedAt when the meeting ends

**Comment by aviva** [comment]
Hello. I have no idea who your people are, lol. 
You have the wrong Aviva

**Comment by avivapinchas** [comment]
@mattkrick Thanks for pasting in that context! If I'm following, we now have an understanding of what `active teams` should be, and will make changes in Usage Stats accordingly, is that right?

**Comment by mattkrick** [comment]
My understanding is that the current definition in usage stats is correct & that @tghanken will be matching that definition in domain stats: https://github.com/ParabolInc/parabol-data-sanctum/issues/323

**Comment by aviva** [comment]
I don’t know how I got included in these emails, You have the wrong email address. I have no idea what this is or who you people are. Can you please remove me?


Aviva Lazar
cfprogrammer.ca 
{ Sent from my data pad 🖖🏻}

**Comment by avivapinchas** [comment]
@aviva Unfortunately, we can't remove you from the thread, but you can unsubscribe - it's in the right-hand sidebar: 
![Screen Shot 2022-08-12 at 8 50 53 AM](https://user-images.githubusercontent.com/11621016/184367529-fcb351d6-64b3-434b-94df-0a4160094236.png)

**Comment by avivapinchas** [comment]
@mattkrick Per our discussion in Slack: sounds like we need to either fix `updatedAt` and/or change this definition to use `max(meeting.createdAt, meeting.endedAt),`. You said you have what you need, so I'll move this back to in-progress. 

This is, afaik, the last issue blocking us from using this feature, so I'm really eager to see it resolved!

**Comment by avivapinchas** [comment]
Related: #7054

**Comment by mattkrick** [comment]
fixed by #7060
