### ISSUE TITLE
Designed a form where customers can set up SAML

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#6951]
Output of #6811 (see comments from Matt and Nick)

### Acceptance criteria
- Designed the end-to-end flow for users finding and configuring SAML in a form, probably from an admin view
- Stretch goal: clarified IA of where users do this, otherwise opened a part 2 just to focus on account management IA

### Estimated effort
- 13 hours

**Comment by ackernaut** [comment]
@nickoferrall @mattkrick I kept the AC concise. I read through your comments on #6811 and will pick up with those suggestions. Sound good as a place to start here?

**Comment by mattkrick** [comment]
LGTM

**Comment by ackernaut** [comment]
@nickoferrall @mattkrick I made a rough first pass, [I have questions in Figma](https://www.figma.com/file/veEiStrSPlBvKgLNVgRNQg/Org-Settings?node-id=2%3A220)

**Comment by ackernaut** [comment]
Hello @enriquesanchez and @mattkrick would y’all mind reviewing this?

Here’s [the proposal including my doubts and specific feedback needs](https://www.notion.so/e91ea187f0ea4b48a35a95799a0609b3)

- Do you have any questions about this design?
- Developer reviewer: are there any details missing that you need for implementation?
- Are there any details to the design that aren’t safe to try?

**Comment by enriquesanchez** [comment]
@ackernaut left some comments in the Figma file 👍

**Comment by drewhousman1010** [comment]
I'm excited to see this progress, awesome stuff :) 

I just want to note that we had a [customer](https://app.hubspot.com/live-messages/3888472/inbox/3381603148#email) 🔒 write in asking if we had SSO setup instructions. Good signal. 

> I see with Enterprise licensing, we’re able to configure SSO and integrate with Jira. I don’t see any options for me to setup SSO. Are you able to provided documentation on how to do this? I’m assuming there should be a place for me to upload our Azure certificate.
