### ISSUE TITLE
Refactor User properties in Segment

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6952]
User Properties in Segment are basically dimensions we can slice our analysis on:
<img width="780" alt="Screen Shot 2022-07-26 at 4 27 05 PM" src="https://user-images.githubusercontent.com/1879975/181129143-d69a081d-b2e2-4b0d-b62e-d7b7de9f9eae.png">

For example, if we build a M1>M2 funnel analysis, we could see the differences by, say, invited vs. non-invited, patient 0 vs. others, enterprise tier vs. personal tier etc.

What do we have for user properties today?

1. `avatar`: I don't know why we needed this here... completely waste. We should remove it?
2. ~`createdAt`: seems useful except in Segment you can't do any date parsing functions so not quite useful either~ (we can use [derived properties](https://help.amplitude.com/hc/en-us/articles/360058731292#date-time-functions)). We can keep this though.
3. `email` & `id`: for identity purpose we should keep them
4. ~`name`: seems useless. I can't think of any use cases where we would do analysis based on users' preferred names. Might just remove it.~ (could be useful when we look up users in Amplitude)
5. `highestTier`: probably the only useful attribute for analysis.

I think what would be quite useful & easy to add are:
1. `isPatient0`
2. `isActive`: this could be a little bit confusing if added as it might change time by time but I think it'd be helpful
3. `isBillingLead`
4. `isTeamLead`

### Acceptance Criteria (optional)
- [ ] `avatar` and `name` are removed from Segment identify call
- [ ] `isPatient0`, `isActive` and `isRemoved` are added to Segment identify call

**Comment by tianrunhe** [comment]
@avivapinchas thought you might dig this and again please make your wish list! 😃

**Comment by avivapinchas** [comment]
Thanks for tagging! I'm so excited for `isActive` - I [asked for this in October 2020](https://github.com/ParabolInc/parabol/issues/4273) 🙈 

If you're asking for a wishlist, I'd also like: 
- `isBillingLead` and `isTeamLead` - I think these kind of roles will be important for understanding how leaders on a team behave differently from members
- 'maxOrgTeamCount' from #4051 - I'm open to other ways of implementing this one, if it's particularly hard, but I'd like to be able to segment charts based on the size of the account that users are part of 
- `numberMeetings` from #4048 - The more meetings a user has completed, the more 'onboarded' they are. While we can create segments based on doing an event, these are all time-bound, which is limiting. 

I debated having something like `hasFacilitated`, but I created a custom event in Amplitude ([example of it in use here](https://analytics.amplitude.com/parabol/chart/tgnuzet) 🔒 ) which I think should suffice. The time-based nature feels more appropriate here.

**Comment by jmtaber129** [comment]
I don't know what Segment plan we're on, but FWIW a lot of this would be pretty easy to do in a robust way if we had [Personas](https://segment.com/docs/personas/), e.g. `numberOfMeetings` can be defined as a [Computed Trait](https://segment.com/docs/personas/computed-traits/) and `isActive` can be defined as an [Audience](https://segment.com/docs/personas/audiences/).

**Comment by tianrunhe** [comment]
@jmtaber129 Wooo I like that! Looks like we are in the business plan that can enable this. I'll play with it. Thank you!

**Comment by Dschoordsch** [comment]
As you brought up yourself, we should also track feature flags if we don't do it already.

**Comment by tianrunhe** [comment]
There are additional costs to turn on Segment Personas so I think right now it's just cheaper to add a few properties ourselves. We could definitely revisit this if we need more & deeper analysis.

**Comment by tianrunhe** [comment]
@avivapinchas sorry to disappoint you... after some investigation, I feel like `isActive` and `featureFlags` are the easiest two to add for now.
All of the other properties you suggested, I need to think about a better & cheaper way to **backfill** existing users. For example, `isTeamLead`, it's pretty easy to identify a user as team lead upon promotion event. So this would work smoothly for **new** team leads. However, for existing team leads, there seems to be no good place to "identify" them. Login is a good place to cover majority of the active users but It seems pretty expensive to calculate if a user is a team lead for any of the teams he/she belongs to. We can do this for `isActive` and `featureFlags` because we have the infomation right there from reading the user data from DB.
