### ISSUE TITLE
All `prbl.in` links are broken in the notifications

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6968]
All links we're using in notifications are only masked with `prbl.in` short link. the real link is longer and uses the standard `parabol.co` domain. As a result, clicking the link works, but copying it does not. 

We either need to configure some other short URL to work with meeting URLs, or just use the long version. The second solution isn't perfect as the link has some UTM parameters and will look bad.

_Originally posted by @mattkrick in https://github.com/ParabolInc/parabol/pull/6879#discussion_r927904008_

**Comment by mattkrick** [comment]
my vote is to remove the URL & just rely on the button.
if an integration doesn't support a button, then we make the link label whatever the button would say.
e.g. [Join Meeting](https://action.parabol.co/FWOOOPPAKLJAJ)

**Comment by jordanh** [comment]
Was this fixed in #6879 or is this still an issue?

**Comment by BartoszJarocki** [comment]
still an issue. this task was created to prevent the scope creep of #6879
