### ISSUE TITLE
Azure DevOps: Implement task integration

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6970]
Pushing a task to ADO does not work since no project is found in the TaskFooter menu

![ADO No project found](https://user-images.githubusercontent.com/7331043/181737796-9925f8da-4bb1-433e-b827-d3380fd951d8.gif)

**Comment by Dschoordsch** [comment]
@nickoferrall you probably know best where this breaks, maybe you could add some more information?

**Comment by nickoferrall** [comment]
@igorlesnenko @Dschoordsch do you know if the Azure task integration was built? I can see this issue https://github.com/ParabolInc/parabol/issues/6172 without a linked PR mentioning `getProjects` and "push task menu", but I don't see anything in the code relating to this.

**Comment by igorlesnenko** [comment]
@nickoferrall I don't see Azure added to `TaskIntegrationManagerFactory`
https://github.com/ParabolInc/parabol/blob/42eb41fda6faed80754a4c77ddbd5577f71f250f/packages/server/graphql/mutations/createTaskIntegration.ts#L73

**Comment by nickoferrall** [comment]
Thanks 👍  I'm working on building this out now

**Comment by nickoferrall** [comment]
The Azure task integration needed to be implemented so I've updated the name of the issue
