### ISSUE TITLE
Update location of "add meeting" to left sidebar

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6974]
Design: #6941 
Experiment details: https://www.notion.so/parabol/Squad-2-Notes-515904adde5441febd81750e4c7a1e65?p=b6b35077e9e4492e9c0d631d2f964a90&pm=s

### AC:
**Mobile**: stays the same as it is currently

**Desktop**: 

- Button is placed at the top of the left sidebar nav
- The icon and text are aligned with the navitems below
- Drop shadow is removed
- When the nav is closed the button remains, with the icon only
- Button is on top (z direction) of the menu and when closing the side menu minimizes to the + version

Open nav
![Image](https://user-images.githubusercontent.com/18582225/181785231-bfd0d06d-2952-46e3-bed0-5459ab062bbb.png)

Closed nav
![Image](https://user-images.githubusercontent.com/18582225/181785204-eae0e09d-f50f-43df-8907-97b593ac7ba8.png)

**Comment by Dschoordsch** [comment]
I think we should also do the minimize animation straight away, I.e. the Add Meeting button doesn't close with the menu but stays on top and just minimizes to the + when closing.

**Comment by acressall** [comment]
Agreed! Here's an animation

https://user-images.githubusercontent.com/18582225/181787284-79529271-2085-4eba-8944-1af30a46536b.mov

**Comment by 87prashant** [comment]
Hi @acressall
Can I work on this?
