### ISSUE TITLE
A/B testing: add random number to each user

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6976]
Relates to:
#6796

We want to A/B test users while also having domain and organization affinity, meaning users with the same domain/organization should get the same experience. Around 65% of users are only in 1 org, 25% in 2, thus it should be possible to fulfil domain affinity in most cases.
In order to not calculate organization affinity for each experiment, we should determine this once for each user

For simplicity we ignore users joining other orgs for now.

## Acceptance criteria
* add a field `randomSeed` to "User"
* assign each user a value in the migration
  * if someone with the same domain has a value -> choose that
  * if someone of their largest org has already a value -> choose that
  * else give random number
* when a user joins assign a number with the same logic

**Comment by mattkrick** [comment]
questions
- how do you handle freemail domains? will every gmail user have the same seed? how do we determine if their email is freemail?
- is there a rebalance? what if i created my account, got my seed, then joined  my org? (this is a common flow for new users for some reason...)
- how do we handle consultants, contractors, etc who share the same domain, but have different orgs?

reactions. here's what i'd do if i were building it. not saying you have to!
- ignore domain, create a seed by hashing their biggest orgId whenever a new experiment is created & assign it to the user then. that way it rebalances every time you call `setupNewExperiment`
- we might not always want org affinity. i see a table like `{userId, experimentId, testGroup}` & then we can use different strategies (org affinity, per-user, geographic, pre-existing heavy usage of feature X). Basically that table would replace adding the `randomSeed` column on the user. Maybe we save this for v2 though.

**Comment by Dschoordsch** [comment]
Sounds easier, let's close this then.
