### ISSUE TITLE
Make new meeting dialog full screen on mobile

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#6977]
Make new meeting dialog full screen on mobile.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/466991/181806358-978b0190-70d5-4979-a741-1c994e1e8db6.png">

AC: 
- full screen on mobile
- keep modal on desktop

**Comment by Dschoordsch** [comment]
It should still act like a modal on mobile with the X at the top, just not waste space.
Not sure about back button behaviour, check other apps how they handle it to make it consistent.
