### ISSUE TITLE
Icons displaying as text for some users

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6985]
## Issue - Bug
[This user](https://app.hubspot.com/contacts/3888472/contact/79961501) is not seeing the icons displayed. It might be related to #6927 
![image (1)](https://user-images.githubusercontent.com/18582225/182386460-cf78c804-43ec-43d9-81b3-343882a52829.png)

- **How serious is the bug?** P0 - P4
- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`

### Acceptance Criteria (optional)
Users can:
   - View icons rather than text
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by 87prashant** [comment]
@acressall I wanted to know : 
Does the above behavior show when the user opens the site (i.e. for a fraction of a second) and the then font is replaced with icons? 
or does the site remains the same afterward?

It is also related to #6062

**Comment by maser** [comment]
@87prashant I reported this. The icons never show up. Also, I'm happy to support you with additional information (including from dev tools).

I can basically not properly participate in retros right now as I can't even vote without the voting icons.

**Comment by Dschoordsch** [comment]
@maser thanks for your report.
The issue could happen if the "Material Icons" font is not available, so it will be fixed by #6062. I would suspect this is either
* a build issue and we're not publishing the font properly
* loading of the font is blocked for some reason

**Comment by Dschoordsch** [comment]
#6062 was closed and will be released this week.
