### ISSUE TITLE
Improve the navigation on the meeting type selection

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#6986]
## Issue - Enhancement

Add arrows or a bar to ease the meeting type selection.

It would allow users to actually see all the available meeting types and choose between them without clicking on the last one to see the ones that aren't on screen.

Currently, it looks like in the below screenshot. The first option cannot be identified and there is no other way to see if there is the only other option there of if there are more.
![Screenshot from 2022-08-02 15-47-48](https://user-images.githubusercontent.com/101704572/182404923-7e246ff3-6886-4836-b489-7bef9e90447f.png)

### Acceptance Criteria (optional)
Users can:
   - See all the meeting types without needing to change the selected one.

**Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by enriquesanchez** [comment]
Thanks for raising this issue @rafaelromcar-parabol!

>It would allow users to actually see all the available meeting types and choose between them without clicking on the last one to see the ones that aren't on screen.

Currently you can scroll or drag the row of meeting types to browse them. We might need to make the affordance more clear to avoid any confusion, as you report.

**Comment by rafaelromcar-parabol** [comment]
True. I didn't notice. At least it can be done :) but it's not enough clear, I imagine I'm not the only one that didn't notice. Thanks! I'll let you either close it or add it to the backlog

**Comment by enriquesanchez** [comment]
Since we are just launching this updated design, I will keep it open to track any feedback around this.

**Comment by jordanh** [comment]
@ackernaut since you are working this area now, just hitting you with a mention to incorporate reducing this friction, if possible.

Iceboxing this issue now per policy
