### ISSUE TITLE
DX: Typescript fails to throw an error for not awaiting a promise

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6990]
Repro:
- open this file: https://github.com/ParabolInc/parabol/blob/d170ac8aa54b9ea47319f57645712c59ff2e6ced/packages/server/graphql/mutations/helpers/getCCFromCustomer.ts
- remove `await`
- see typescript doesn't throw an error, even though you're trying to put a promise in the DB! wtf

Estimate: 4 hours

**Comment by jordanh** [comment]
@mattkrick was this fixed in #6895 ? Could you please close if so
