### ISSUE TITLE
Not able to run Sprint Poker

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#6993]
## Issue - Bug

https://user-images.githubusercontent.com/106697681/182590984-e74fcf60-2908-4b35-af90-204c429bd4cc.mp4

When advancing to the `scope` phase it says "An error has occurred! We’ve alerted the developers. Try refreshing the page". I also tried a different browser and mobile device too.
- **OS:** Windows
- **Browser:** Chrome / Firefox

**Comment by 87prashant** [comment]
I think it is account-related problem as the other account is working fine.

**Comment by BartoszJarocki** [comment]
@87prashant do you have any integrations set up?

**Comment by 87prashant** [comment]
Yes
![Screenshot 2022-08-03 173219](https://user-images.githubusercontent.com/106697681/182603021-636389e2-d25f-4285-8f4f-42636a2d1e6b.png)

**Comment by 87prashant** [comment]
Not sure how but it started working now automatically

I don't know if it is related: the only thing I did is set the team member account's integrations (my other account) that was not set earlier. But removing it is not recreating the issue.

**Comment by 87prashant** [comment]
I will update if it happens again.

**Comment by BartoszJarocki** [comment]
thank you! it'd be great if you can find out the steps to reproduce. I don't see any spikes in sentry so for now, I'll assume it's not something common.

**Comment by jordanh** [comment]
Closing for now. Please re-open if this happens again
