### ISSUE TITLE
Add a link to support page when Jira update error occurs

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7005]
## Issue - Enhancement
Multiple users have had issues where sending story points to Jira results in an error. We have [documentation in Notion](https://www.notion.so/parabol/How-to-Fix-a-field-in-Jira-manually-328f413f3d6444d29ca623ceb56c90dc) that should resolve this for most cases. We should add this to our support page and link to it when the error occurs.

![Screen Shot 2022-08-03 at 3 33 25 PM](https://user-images.githubusercontent.com/18582225/183087600-f1a38432-4859-49e9-accf-f2fcac7c6ad2.png)
![Screen Shot 2022-08-03 at 3 33 36 PM](https://user-images.githubusercontent.com/18582225/183087602-d41208d0-6be6-4618-b5be-2af6ddbf7a52.png)

### Acceptance Criteria (optional)
Users can:
   - Find a link to get more help when our automatic fix fails

**Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Added AC and EE

**Comment by Dschoordsch** [comment]
#7206 removed this functionality
