### ISSUE TITLE
Azure integration doesn't automatically refresh

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7006]
If I integrate with Azure and leave the app for a day, I need to reintegrate to have access to my Azure integration.

### AC

- [ ] Azure integration automatically refreshes the token

**Comment by mattkrick** [comment]
I'd suggest that all azure queries are fetched from dataloaders & they all first use a dataloader to fetch a fresh access token.
Pattern: https://github.com/ParabolInc/parabol/blob/072cdfcbe5cf1a5eed3a9c72ec1da51756d2b9fe/packages/server/dataloader/atlassianLoaders.ts#L45
