### ISSUE TITLE
Front page of Parabol.co website doesn't show logged in state

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7013]
I think this is a bug because it doesn't ask me to sign in; it just signs me in.

This is what I experience on Chrome, Mac OS.

![2022-08-07 at 12 47](https://user-images.githubusercontent.com/253067/183289077-53e8a1a6-8dd2-4f93-b28d-b2b8c6903bb6.gif)

What I expected to see would be that my logged-in status would be reflected on the front if I am being remembered. As far as a serious level, this feels pretty flow-breaking to me as a customer if I expect to be remembered and welcomed.

**Comment by jordanh** [comment]
Working as designed!
