### ISSUE TITLE
Sorting in groups during meeting is difficult on smaller screens when scrolling up

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7014]
I saw this when I was in a meeting and tried to sort by dragging up a card from the bottom. It was using a MacBook pro 14, which meant the screen was a little smaller. What I found was it was pretty impossible using the trackpad to do this to get it into the group. This felt like a problem and made me think about easier ways of adding to groups.

There probably are two things to solve here:

1. The bug of dragging up in a column when the screen also needs to move up. This was using Chrome.
2. The issue of adding to a group without having to just drag. Could you perhaps somehow select a group easier using dropdowns/tagging?

As far as serious level, this is more annoyance and I would say it falls into 'bug' for the first point, but there is an enhancement here too.

**Comment by jordanh** [comment]
I agree with this. I wish this were better

**Comment by jordanh** [comment]
EE
- Solutions to grouping an item "below the scroll" with an item "above the scroll" explored
- Decision on direction made

AC
- 13 hours
