### ISSUE TITLE
Expand the sandbox area to not just be a walkthrough

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7015]
The sandbox is amazing but it feels very 'clickthrough' right now. It would be great to truly feel like you can safely explore without issues. Maybe have a time delay or something and even pre-filling with data is a bonus, but removing the feeling of a walkthrough empowers more.

I know this likely has been talked about and please close or merge if this falls into another issue. I think that what is there now though is a little too close to a wizard and will therefore not truly show the power from the start of the experience. It doesn't also give the empowerment of exploring.

![2022-08-07 at 13 03](https://user-images.githubusercontent.com/253067/183289607-a36d61fa-e96b-4290-af27-72e216b8e876.jpg)

Screens like this one are too 'default' and whilst they do lead to things they also will need to be removed by a customer which is a step for someone to make. If there was a sandbox area, you could even consider removing these cards and not needing removal. What if the sandbox was the first state, and you could confirm to move out of it? Of course, you easily could just skip it then.

**Comment by jordanh** [comment]
I am sure this is going to come up again and likely more holistically as an investigation into our overall onboarding flow. I am going to close for now

**Comment by Dschoordsch** [comment]
Will be explored in #6945.
