### ISSUE TITLE
Icon looks clickable in timeline

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7016]
The timeline avatar icon choice is the expected one for clicking and adding an icon which makes this expected to be clickable. I would recommend that this should either be made clickable or swapped out. Probably swapping out makes more sense for an easier catch.

![2022-08-07 at 13 05](https://user-images.githubusercontent.com/253067/183289716-557861d9-4b1b-4ab9-8a21-df803b2df28f.jpg)

As far as the level of bug, this feels like a low-hanging fix. It could be an annoying hitch to experience for someone if they did feel they should click and it wasn't clickable, but I have no data for how often that happens.

**Comment by jordanh** [comment]
AC
- Icon should perform the same action as the CTA

EE
- 1 hours
