### ISSUE TITLE
Filtering is still able to be done when only one state is available

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7018]
This probably is a bit of a stress case to work to so might be a low priority. You can currently filter by one team meet when you only have one, which feels 'odd'.

![2022-08-07 at 13 13](https://user-images.githubusercontent.com/253067/183290027-bf91ad08-4aca-4ede-a5bb-295505e554cb.jpg)

I would recommend when you only have a single state possible, filtering just doesn't show. This feels a more expected interface behaviour.

**Comment by jordanh** [comment]
AC
- Do not display filtering controls if filtering not possible

EE
- 1 hour
