### ISSUE TITLE
Multiple primary buttons are a little confusing

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7019]
There are several screens on the website and also in the application where multiple primary buttons are confusing to find the path forward for someone.

![2022-08-07 at 13 15](https://user-images.githubusercontent.com/253067/183290123-7db8dae0-a48c-474a-a35c-38b427d00c97.jpg)

![2022-08-07 at 13 16](https://user-images.githubusercontent.com/253067/183290129-bb1f5020-5070-4e79-81eb-a7ac4601de6e.jpg)

My recommendation would be only to have one primary per page and think about secondary, even tertiary actions if needed. It will help clarify paths for people and avoid those strong buttons creating visual traps. They are great to catch the eye but when you have more than one they cause some considerable flow issues.

**Comment by jordanh** [comment]
N.B. this issue only relates to the product, not our marketing site (we have no jurisdiction there 😉)

AC
- List made of areas in product where there are multiple conflicting primary CTAs
- Design issue created to resolve this competition for attention (do we re-style one or the other dynamically?)

EE
- 5 hours

**Comment by jordanh** [comment]
We resolved this on the homepage, but not in all places in our product. Iceboxing this as per policy
