### ISSUE TITLE
Timer countdown can be difficult to understand for new users

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7020]
If a board closes in days, the countdown being so verbose can be hard to read. I would recommend changing this clearly to days. You absolutely can keep the counter too, but clearly saying 'closes in 2 days' for example, would bring that level of human clearness that would be really useful.

This is what currently is seen:

![2022-08-07 at 13 21](https://user-images.githubusercontent.com/253067/183290316-87481da2-1131-4c58-91f1-3521811da5e3.jpg)

It's not a critical bug by any means. This certainly is a useful, quality of life enhancement if anything.

**Comment by jordanh** [comment]
Thank you for this! Adding to the backlog

**Comment by jordanh** [comment]
AC
- Alternate timer displays designed and next steps decided

EE 
- 5 hours

**Comment by jordanh** [comment]
Iceboxing
