### ISSUE TITLE
Consider adding upcoming filter to timeline

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7021]
Unless I am missing something, the timeline doesn't have a way to see upcoming things. I found myself really wanting to see this in using Parabol. I am also not totally sure it needs to be in the timeline, but why I recommend, there is having 'one place' to see everything. It feels sensible to have a place you can see everything you have and are going to do.

**Comment by jordanh** [comment]
We've integrated this feedback into some future designs
