### ISSUE TITLE
Show time sensitivity on meeting card

### ISSUE THREAD

**Issue by karmatosed** [ParabolInc/parabol#7022]
The meeting cards don't indicate times or status. This was something I found myself wanting to see. I would go to the meetings area, and seeing what time those were would have stopped me from going to the calendar. Now, this might be conscious, but I note this was a behaviour I found myself wanting a few times.

![2022-08-07 at 13 24](https://user-images.githubusercontent.com/253067/183290472-1f27f8f1-f473-4974-9982-93ca9d83b0bb.jpg)

The ask:

- If a meeting has a scheduled time, show it on the card.
- You could even link to the meeting if it's using zoom/other forms, but that doesn't feel as much of a need (cautious this isn't a calendar replacement).

**Comment by mwermuth** [comment]
Looked at during backlog grooming. Going to icebox it.
