### ISSUE TITLE
Task footer menu can crash if Azure & Jira Server are integrated

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7031]
See the discussion here for further details: https://github.com/ParabolInc/parabol/pull/7007#issuecomment-1208108516

### AC

- [ ] After integrating with Jira Server & Azure DevOps, the user can open the task footer menu without any issues
- [ ] Can push a task to both Azure 
- [ ] Can push a task to Jira Server

**Comment by jordanh** [comment]
It's a rare case for both of these integrations to be added to the same team, for sure, but I am going to bump to p2 just in case...
