### ISSUE TITLE
Standups: Ended meeting view

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7033]
https://user-images.githubusercontent.com/1017620/183697407-2941274e-6d03-46c9-9466-14dae0d2ebbf.mp4

## Issue - Bug

Right now, there's no way to see if the standup has ended. What's more, if it has ended, all the buttons for adding/updating the response are active. When the user actually tries to update the response, it shows as updated but after refreshing, the update is gone.

### Acceptance Criteria (optional)
- [ ] figure out what to show on ended standups view
- [ ] handle add/update response mutation errors correctly

**Comment by enriquesanchez** [comment]
For reference, on retros if you browse back to the meeting view from the summary, you can browse through the phases but cannot edit or update anything (except reactions).

**Comment by enriquesanchez** [comment]
@BartoszJarocki @jmtaber129 

Curious to hear your thoughts: if the activity has ended, do we still want to allow for team members to be able to reply to responses? How about react to a response?

**Comment by jmtaber129** [comment]
@enriquesanchez I think yes.  IIRC there was a discussion at some point about that, but I'm not sure where it is.  @ackernaut might have thoughts.

**Comment by ackernaut** [comment]
My 2 cents: threads should stay alive. I should be able to edit my response. We risk making too many assumptions about lag time across timezones and when folks are away. If you pinged me yesterday in a thread e.g. cc @ackernaut and I was out, if I come back to it today my hands are tied if the activity is closed and that means the conversation is closed. I’ll have to ping you on Slack (chat) and make some sort of reference to what you asked me about. I think we can still indicate in a clear way that the activity is completed and a day in the past without making the conversation rigid.

**Comment by enriquesanchez** [comment]
Thanks for the input @jmtaber129 and @ackernaut!

To summarize, when a standup has ended we continue to allow folks to:

- Reply to responses (comments in threads)
- React to responses
- Edit their response

...and then we also indicate the ended status of a standup. The easiest method is to use a snackbar component, which we already support in the app:

![image](https://user-images.githubusercontent.com/3276087/186233452-f5f33d2f-2b1a-4bfa-a561-2370e3cb3287.png)

I suggest this should be the way to go.

_THAT SAID_, if we ever implement the time-left indicator, like this one:

<img width="565" alt="Captura de Pantalla 2022-08-23 a la(s) 1 09 21 p m" src="https://user-images.githubusercontent.com/3276087/186233313-f693e85b-3f12-420d-99aa-5fb784a1f2d1.png">

That little component would be ideal for this type of message:

![image](https://user-images.githubusercontent.com/3276087/186233383-e754ed3f-05a2-41ae-a9a4-7e381b740e3c.png)

...but that's for a future time.

--- 

@BartoszJarocki @jmtaber129 I'd like to hear your feedback on this one and if there are any concerns you may have whit this solution. If there are none, I think we can go ahead and create an implementation issue 👍

**Comment by jmtaber129** [comment]
@enriquesanchez 
The ⛔ emoji makes me feel discouraged from participating in the activity after it's ended. I'd suggest removing it or replacing it with something that feels more informational than instructive.

I'd also suggest ignoring which components we do/don't have implemented - any method of showing that a meeting has ended will probably be pretty low-effort on the technical side

**Comment by enriquesanchez** [comment]
>The ⛔ emoji makes me feel discouraged from participating in the activity after it's ended.

That's a good point @jmtaber129 

How about a time-related one?

![image](https://user-images.githubusercontent.com/3276087/186270593-afab1ade-d725-4a2a-9e28-f67e70933716.png)

[I experimented with few more here](https://www.figma.com/file/fw5gj7qRbKSh5XQbnh0PUr/Standups-tweaks?node-id=275%3A31363).

**Comment by jmtaber129** [comment]
@enriquesanchez Hmm time-related emojis feel more like "this is timed and there's time remaining" than "this is timed and the time's up".  I think my preference is towards 👀 or ℹ️. Might be worth getting input from others in the org though

**Comment by Dschoordsch** [comment]
I propose ✅ since it's done and you achieved something, so give it a nice spin. Maybe 🏁 as this might be more associated with being done but still is positive?

**Comment by enriquesanchez** [comment]
Thanks for chiming in @Dschoordsch 🙌 , I think I like you suggestion of using the ✅! Here's an iteration taking @jmtaber129 and @ackernaut feedback into account:

![image](https://user-images.githubusercontent.com/3276087/186462020-c39b3e2e-9d59-4ff5-b761-ef6d29856046.png)

**Comment by mwermuth** [comment]
@endtwist what is the status of this? Are we going to fix this bug with the above design?

**Comment by enriquesanchez** [comment]
@mwermuth I think you meant to ping me here instead. Thank you for the reminder!

This one is ready for implementation and I think it can be included as part of Squad 1's priorities. What do you think @BartoszJarocki ?

**Comment by jmtaber129** [comment]
@enriquesanchez looking back through the conversation here - are you recommending a snackbar because we already have that component, or because it's the better design before we have a time-left indicator?

**Comment by enriquesanchez** [comment]
@jmtaber129 I was recommending it because we already have it, but your suggestion above

>I'd also suggest ignoring which components we do/don't have implemented - any method of showing that a meeting has ended will probably be pretty low-effort on the technical side

...nudged me to go back to the original idea. I prefer the indicator on top, which does not obscure any content behind it and it's in a more visible area of the page.

**Comment by BartoszJarocki** [comment]
I think it'll play nicely with showing the timer as designed here: https://github.com/ParabolInc/parabol/issues/7098, good stuff!

**Comment by BartoszJarocki** [comment]
@enriquesanchez, one last question, where would you put this on mobile view?
