### ISSUE TITLE
User settings minimal next wins

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#7035]
Combining some needs of #4538 and #5632 to get some quick wins out​

### AC
- Designed user settings views that help with managing email auth/password and email preferences
- Stretch: think about IA of integration settings across user vs team etc.

### EE
- 13 hours

**Comment by ackernaut** [comment]
**Included in next Sprint?: Y**
  [See the discussion](https://action.parabol.co/meet/fuuBJrLzj2/estimate/8) in Sprint Poker #​​4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ackernaut** [comment]
@nickoferrall @acressall requesting your review if you are available:

Here are [the notes on recommended next steps](https://www.notion.so/parabol/Settings-Admin-IA-7d6e7e8fecf84a72a15d4ef7c7dab555#9b95dca458a74cab923597a6820c2cf1).

- Do you have any questions about this design?
- Developer reviewer: are there any details missing that you need for implementation?
- Are there any details to the design that aren’t safe to try?

**Comment by acressall** [comment]
Added a few comments and questions in Figma. My main request is that we make sure to add a link to unsubscribe in the summary emails too! 
I think it's safe to try!

**Comment by nickoferrall** [comment]
Happy to check it out! @ackernaut or @acressall do you have a link to the Figma file? The Figma link in the doc [here](https://www.notion.so/parabol/Settings-Admin-IA-7d6e7e8fecf84a72a15d4ef7c7dab555#9b95dca458a74cab923597a6820c2cf1) doesn't link to Figma

**Comment by acressall** [comment]
I assumed it was the same figma file listed elsewhere in the doc! https://www.figma.com/file/2Nj1y1KUfE2swHZuDY5Zxn/My-User-Account-Management

**Comment by nickoferrall** [comment]
Looks good to me! I've added a comment to Notion & Figma
