### ISSUE TITLE
Usage Stats: Clarity Improvements

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7037]
## Issue - Enhancement

Changes: 
- Change 'Meetings' to 'Total Meetings' in Table and Chart
- Add Tooltips on all terms 
  - Organizations: organizations with at least 1 unarchived team on it, which has at least 2 team members who have logged in within the last 30 days
  - Active Teams: teams with at least 2 team members who have logged in within the last 30 days & within an active organization that has had a meeting that has an updatedAt newer than 30 days ago
  - Active Members: number of users on an active organization that has logged in within the last 30 days
  - Total Meetings: number of meetings created by unarchived teams on organizations assigned to the domain
  - Total Members: number of users on organizations assigned to the domain
  - Total Teams: unarchived teams on organizations assigned to the domain 
- Remove "Usage" title and add "Usage" after the domain heading, so `parabol.co Usage`
- Bonus points: add toggle for 'Cumulative' vs 'By Month' in Total Meetings Chart

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I made [a quick iteration](https://www.figma.com/file/454u4uRYZlZMtmUtgQAQ3G?node-id=311:9258#243768804) on having an info icon that opens a tooltip or read-only menu

**Comment by mattkrick** [comment]
@avivapinchas tooltip definitions added, feel free to edit inline

**Comment by jmtaber129** [comment]
Re: Total Meetings - this should also be changed from a stacked bar chart to some form of line chart (stacked or multi - dealer's choice), since a bar chart implies that the meeting count reflects each individual month, rather than all meetings up to and including that month (changing "Meetings" to "Total Meetings" helps a bit, but a "total meetings" label on a bar chart still implies "total meetings in each individual month")

**Comment by avivapinchas** [comment]
> this should also be changed from a stacked bar chart to some form of line chart

@jmtaber129 Thanks for your feedback. The existing description captures the changes we've agreed to implement at this point. That said, if it's a simple change, I think it's fine to do. If it's non-trivial, I prefer to start with the changes we've already identified. I defer to @mattkrick on making a call around the level of effort here. 


> tooltip definition

Edits: 

- Organizations: Organizations associated with this domain and with at least 2 active members.
- Active Teams: Teams that met within the last 30 days and have at least 2 active members. 
- Active Members: Users who have logged in within the last 30 days.
- Total Meetings: Total number of meetings by teams in associated organizations. 
- Total Members: Total users in associated organizations.
- Total Teams: Total teams in associated organizations.
