### ISSUE TITLE
webpack: bundle deployment scripts

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#7039]
yarn scripts we need:
- pg:migrate
- db:migrate
- postdeploy

ideally make this 1 command (db, pg, pd)

AC
- [ ] write a script & add it to the server config when isDeploy is true

Estimate: 2 hours

**Comment by adaniels-parabol** [comment]
@mattkrick will isDeploy also trigger S3 push or will that be ignored if "local" is set for FILE_STORE_PROVIDER

**Comment by mattkrick** [comment]
getting rid of node_modules has proven to be pretty difficult when deploying in circleCI.
I think we'll want to wait until we change our CI so we have more room to build, then once we have that done we can come back to finishing this
