### ISSUE TITLE
Azure DevOps timeout error

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7047]
If there are dozens of Azure DevOps results, after a few refreshes, no results are returned and the server returns the following error: `Error: Azure DevOps is down`.

### AC

- Render dozens of Azure work items in the Scope stage, refresh the page a few times, add and remove work items, and see the expected work items
- It looks like the `workItems` query is failing, most probably rate limited by Azure. See if we can make this query more efficient, e.g. making using of the first argument here https://github.com/ParabolInc/parabol/blob/7938dd78615230f2a6501594813a43722004e06c/packages/server/graphql/types/AzureDevOpsIntegration.ts#L109-L111

**Comment by mattkrick** [comment]
I'd suggest caching work items in redis & use a cache-and-network strategy to return the result from our redis cache if it exists & then when the result comes back from azure, we can push that value to redis & send the update to the client if there's a delta.

https://github.com/ParabolInc/parabol/blob/072cdfcbe5cf1a5eed3a9c72ec1da51756d2b9fe/packages/server/utils/atlassian/jiraIssues.ts
