### ISSUE TITLE
Missing meeting summaries

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7050]
## Issue - Bug

- Two separate users of different companies have reported not receiving meeting summaries, for both retrospectives and sprint poker. They are able to see the summaries in the timeline, it is the email send that is not working. 
- In Mailgun, I have not been able to see a meeting summary sent after August 4 (which could line up with the last release)

- **How serious is the bug?** P2

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jmtaber129** [comment]
It would seem so. Aug 11 is when the hotfix went out

**Comment by acressall** [comment]
Yes, confirming it is the same!

**Comment by Dschoordsch** [comment]
Thank you both for confirming! In this case there is nothing more to do here.
