### ISSUE TITLE
Bug: Mass invitation link stays the same from Team page or Meeting Page

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#7057]
## Issue - Bug
Reproduce:
1. Go to team page, try to invite someone, take a note down of the mass invitation link
2. Go to a meeting this team holds, try to invite someone too
3. See the mass invitation link stays the same

The invitation token encrypt the information of `teamId` and/or `meetingId`. When a user accepts the invitation, it won't be possible to see [where this user is accepted to](https://github.com/ParabolInc/parabol/blob/d54ca5ba8879fd994f34a708414ec5ebddfebbce/packages/server/graphql/public/mutations/acceptTeamInvitation.ts#L53), if the link is the same.

### Acceptance Criteria (optional)
- [ ] when a mass invitation link is generated, in addition to check if there's already one from the same inviter and same team, also check the location where the link is generated. If the new one has different location, generate a new token, otherwise use the old one.

**Comment by jordanh** [comment]
Clarifying questions:
- Is this so you can tell where invitations are happening from?
- If so, why embed this information in the encrypted link? Why not add a URL parameter?

**Comment by tianrunhe** [comment]
> Is this so you can tell where invitations are happening from?

Yes, but mostly inside a meeting or outside a meeting

> If so, why embed this information in the encrypted link? Why not add a URL parameter?

Today we infer if the invitation happens inside a meeting from the encrypted `meetingId` inside the token. I feel like generating a new token is easier than adding a URL parameter?
