### ISSUE TITLE
Highlight the card the facilitator is hovering over in the Group phase

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7074]
In a retro, the facilitator usually walks through each reflection reading each card out along the way. Sometimes, when the facilitator has expanded the kanban column and the viewer has not, it can be difficult to follow along as the cards appear in a different order.

To help, we could highlight the card that the facilitator is hovering over, just like we do in Check-ins (see https://github.com/ParabolInc/parabol/issues/5858).

### AC

- [ ] Highlight the card that the facilitator is hovering over in the same way we highlight cards in Check-ins

**Comment by 87prashant** [comment]
@nickoferrall 
I would like to work on this one if that's OK

**Comment by nickoferrall** [comment]
Sure thing, @87prashant!

**Comment by 87prashant** [comment]
I am not currently working on this, if anyone would like to work then go ahead.
