### ISSUE TITLE
Able to removeAuthIdentity for specified emails

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7086]
Currently, we can only remove the auth identity for a domain: https://github.com/ParabolInc/parabol/blob/5e914de403f00c300d85adc5d9cd93726c9d16ba/packages/server/graphql/private/mutations/removeAuthIdentity.ts

However, [this user](https://app.hubspot.com/contacts/3888472/contact/70527551) 🔒 has asked us to remove the auth identity for their individual account.

### AC

- [ ] `removeAuthIdentity` can accept a `domain` or `emails[]` arg
- [ ] Able to remove the auth identity for specified user emails without affecting other users with that domain

**Comment by raj360** [comment]
Hi @nickoferrall, what  other requirements and full context to hack on this?
