### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7087]
https://sentry.io/organizations/parabol/issues/3472578519/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'map')
  at a (./packages/client/hooks/useMeetingMemberAvatars.ts:31:8)
  at useMeetingMemberAvatars (./packages/client/hooks/useMeetingMemberAvatars.ts:29:35)
  at c (./packages/client/components/MeetingCard.tsx:159:26)
...
(14 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
affects 4 users in last 30 days

**Comment by jordanh** [comment]
Was about to icebox this, then saw 159 events, affecting 43 users. Going to bump up the priority on the bug board. If we git 100 users, I will bump to p2

**Comment by jordanh** [comment]
![image](https://github.com/ParabolInc/parabol/assets/103000/e76b75db-760a-4b49-80f9-c4549e7241f6)

**Comment by Dschoordsch** [comment]
Last seen 22 days ago in 6.124.0, closing
