### ISSUE TITLE
Retro: Text without spaces breaks the UI in discussion `DiscussionThreadInput`

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7090]
## Issue - Bug
If there are no spaces in the text then it breaks the UI
![Screenshot 2022-08-18 174854](https://user-images.githubusercontent.com/106697681/185434977-3cc0b72e-fdd7-41ed-859f-c02404060ed7.png)

### Acceptance Criteria (optional)
UI should not break in above situation

**Comment by 87prashant** [comment]
@enriquesanchez any way to tackle this, though in the above the user can also use the `ctrl+k` to make the links
should we truncate or wrap?

**Comment by enriquesanchez** [comment]
@87prashant Hi!

I think this can be handled with CSS, take a look at this help doc https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text#breaking_long_words

**Comment by Dschoordsch** [comment]
@enriquesanchez does that mean we should wrap long words?

**Comment by enriquesanchez** [comment]
>does that mean we should wrap long words?

@Dschoordsch I think so, otherwise the word can't be read, right? How would you approach this?

**Comment by jordanh** [comment]
How Slack handles this:
![image](https://user-images.githubusercontent.com/103000/187511597-87c876ac-a351-4df3-b9a7-9ede1aa44fd3.png)

**Comment by 87prashant** [comment]
Thanks @enriquesanchez
