### ISSUE TITLE
Sprint Poker: number of stories in summary stats is one less than actual stories

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7092]
## Issue - Bug

When a Sprint Poker meeting has ended, the number of stories in the summary stats is one less than the actual number of stories that were estimated.

<img width="708" alt="Captura de Pantalla 2022-08-18 a la(s) 3 36 51 p m" src="https://user-images.githubusercontent.com/3276087/185491327-16a4e4b5-5f7a-4b67-b2e2-ec9857a75086.png">

Note that the stats at the top says `8` but the list of stories estimated below totals `9`.

- **How serious is the bug?** P4
- **OS:** Unspecified
- **Browser:** Unspecified

### Acceptance Criteria (optional)
- Number of stories in the summary stats is equal to the number of stories estimated

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by enriquesanchez** [comment]
[A user writes](https://app.hubspot.com/live-messages/3888472/inbox/3044835194#email) (🔒):

>Whenever we get our meeting summary the amount of stories is incorrect at the top in the summary area. For example, today we had 9 stories and all of them are listed in the summary but the top only says 8 stories. Can you let me know if i'm missing something or not doing it correctly that it is always 1 off?

**Comment by 87prashant** [comment]
These are not total stories, these are completed stories
In this case, the last story is not considered completed when we click `End meeting`
- Either we can change the name above "stories" => "completed stories"
- Or change the value to show the total stories

@enriquesanchez WDYT?

**Comment by sophiaenax** [comment]
I looked at this issue and noticed that only stories with votes get counted. So if there are 10 stories with no votes, the count is 0 stories. Don't know if that was the idea.

**Comment by enriquesanchez** [comment]
>In this case, the last story is not considered completed when we click End meeting

Oh, interesting. How did you arrive to that conclusion, @87prashant ?

**Comment by enriquesanchez** [comment]
Just tested this again, on a Sprint Poker meeting where I estimated 5 issues, and I got a total of 4 reported in the stats.

<img width="697" alt="Captura de Pantalla 2022-09-01 a la(s) 4 35 42 p m" src="https://user-images.githubusercontent.com/3276087/188017432-4ce53bdb-ec1a-4595-bc11-3d594cf0ffcb.png">

**Comment by 87prashant** [comment]
@enriquesanchez 

https://user-images.githubusercontent.com/106697681/188045902-aafdaa00-8087-4678-8590-bbda920c49a4.mp4

**Comment by 87prashant** [comment]
I think to make it total stories we can do this:

![Screenshot 2022-09-02 081036](https://user-images.githubusercontent.com/106697681/188047909-f2d68cf8-c364-4b85-89c3-17b7f68cd483.png)

**Comment by enriquesanchez** [comment]
@Dschoordsch would you mind taking a look and advise how to proceed with this bug?

**Comment by Dschoordsch** [comment]
Thanks @87prashant, you're right. I think there are 2 issues here:
1) we only count completed stages, this was done by @nickoferrall [here](https://github.com/ParabolInc/parabol/commit/9bc11623b9276ea1aaf990c3c761117a891f8f06), sadly without any additional information. So this seems intended but might be a bit confusing for users when it's just named "stories"
2) not all voted stories marked as completed reliably

**Comment by nickoferrall** [comment]
@mattkrick you mentioned https://github.com/ParabolInc/parabol/pull/5062#pullrequestreview-691232842 that we should count the completed stories. Not sure if you have any strong feels on this? 

We could change the "Stories" title to "Completed Stories". I also have no tension counting all stories, rather than completed stories.

**Comment by mattkrick** [comment]
I've got a slight preference to keep it to completed stories because I've seen cases where folks add like 50 & then complete as many as they can get to, which makes for less visual noise.

The big question for me is why are stories not marked as completed? when end meeting is called it should mark the stages started as completed. if we solve that i think we fix the issue!

**Comment by 87prashant** [comment]
> when end meeting is called it should mark the stages started as completed

All stages?

Just confirming, are we choosing completed stories or all stories?
