### ISSUE TITLE
Standups: time-left indicator

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7098]
For the use case of async standups, knowing how much time there is left before the instance ends can be useful for everyone involved.

We can solve for this need by adding a time-left indicator. Some initial explorations:

![image](https://user-images.githubusercontent.com/3276087/186237541-40570e43-f594-4473-8dc0-d1bbca34caa2.png)

We can also add more relevant information there, like the number of submitted responses:

![image](https://user-images.githubusercontent.com/3276087/186237699-83ce0d38-2e48-4e5d-9300-e456adfee011.png)

One **potential issue** with this pattern is that for those teams that are doing **sync** standups, this indicator will be confusing and annoying. For this reason **this idea needs more research and exploration** to validate usefulness and value.

**Comment by jmtaber129** [comment]
When it comes to recurrence, I think it's fine to continue building primarily for async.  If we're worried about sync teams getting confused when they see "N hours" even though their calendar meeting is over in half an hour, we could add a tooltip on hover that says something like "this activity will automatically close at <timestamp>"

**Comment by jordanh** [comment]
Related: #7020

**Comment by BartoszJarocki** [comment]
@enriquesanchez this is done, right?

**Comment by enriquesanchez** [comment]
@BartoszJarocki Oh yeah, thanks for the reminder!
