### ISSUE TITLE
One can comment with empty message (with only whitespaces)

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7120]
## Issue - Bug

![Screenshot 2022-08-29 001817](https://user-images.githubusercontent.com/106697681/187090639-69bf65fd-25d8-48d3-93c9-a34cc9bd21ff.png)

### Acceptance Criteria (optional)
If only whitespaces are present comments should not be submitted

Estimated effort: 1 hour

**Comment by jordanh** [comment]
Added estimated effort
