### ISSUE TITLE
There is no tag for edited comments

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7121]
## Issue - Bug
Before Edit:
![Screenshot 2022-08-29 003536](https://user-images.githubusercontent.com/106697681/187090893-c21c38bb-98c8-43e2-ada9-a558d6fa96ef.png)

After Edit:
![Screenshot 2022-08-29 004826](https://user-images.githubusercontent.com/106697681/187090890-86032bbc-5ce8-496b-ae97-15e3bfdf4899.png)

Though there is time that can inform about that but edited label or something would be better
### Acceptance Criteria (optional)
There should be a label at least that the comment is edited

**Comment by mekzy-o** [comment]
Hi, @87prashant  is this a feature or bug?

**Comment by 87prashant** [comment]
I think we could use `(edited)` after the comment that is edited.
For example in the above scenario:
```
sdfsfsf (edited)
```
we can make `(edited)` bold to stand out

**Comment by jordanh** [comment]
Unmarking as bug, changing to enhancement

**Comment by 87prashant** [comment]
@Dschoordsch @enriquesanchez  WDYT?

![Screenshot 2022-10-05 235239](https://user-images.githubusercontent.com/106697681/194133952-520d4161-9746-4533-963f-f45d63439bea.png)

As time can take the next line and it does not look very crowded in my opinion, I propose a solution:

-  "'updated time'/'created time'" and on hover, it should show "'Updated/Created"
    ex: 2 minutes ago/1 hour ago. On hover => Updated/Created
- We could also use "•" in place "/"

If it feels too crowded another option could be:

> I think we could use `(edited)` after the comment that is edited. For example in the above scenario:
> 
> ```
> sdfsfsf (edited)
> ```
> 
> we can make `(edited)` bold to stand out

But I am not sure to the user how much useful this information is.
