### ISSUE TITLE
Use static extraction tools to automatically find and export translatable texts

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#7122]
Split from #7103 

options: [i18next-scanner](http://i18next.github.io/i18next-scanner), [i18next-parser](https://github.com/i18next/i18next-parser) and [babel-plugin-i18next-extract](https://github.com/gilbsgilbs/babel-plugin-i18next-extract) can read through code files to automatically find and export translation keys. [^1]
[^1]: https://www.i18next.com/how-to/extracting-translations

ACs:
- write suitable config file for i18next-scanner CLI
- scan Parabol's codebase, extract translation keys/values
- merge them into i18n resource files.
- _optional?_ automates this process of maintaining the translation catalog. https://github.com/ph1p/i18next-scanner-webpack

**Estimated effort:** 5 points

**Comment by jordanh** [comment]
Marking discussion to keep off the backlog. Please either add AC or EE or close when you have concluded your hack, sir!

**Comment by JimmyLv** [comment]
Of course, I've added the ACs, and I'll close the issue after I finish the research. 😁

**Comment by Dschoordsch** [comment]
False positive:
* https://github.com/ParabolInc/parabol/pull/7089#issuecomment-1229535920

**Comment by JimmyLv** [comment]
@Dschoordsch are you supposed to be referring to the sonar bot here? #7123, I found that sonar's default rules didn't help us much and I think it's time to disable it, sorry for the disruption. 
I was logged into sonarcloud with my GitHub account and found that @jordanh had previously set up Parabol's sonar project [^1], thus it (before I even decided) automatically started GitHub Action. 

[^1]: https://sonarcloud.io/organizations/parabolinc/projects

At the moment, since I don't have Admin access on either GitHub or SonarCloud, could you please help to turn it off?
on GitHub configuration: https://github.com/apps/sonarcloud/installations/28666016

![Google Chrome-Update SonarCloud's repository access-000072-20220831](https://user-images.githubusercontent.com/4997466/187612980-b7edc362-73e8-411f-b6cb-b59fa5bde7d4.png)
