### ISSUE TITLE
Automated review in Self-Review stage, e.g. Sonar GitHub Action

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#7123]
We now have a self-review phase of PR review, at which point we can use automated bots (GitHub Action) to see some issues with our code in advance _from another perspective_: maybe it's some obvious bad smell, help us to improve the quality of our code in time.
Of course, this is optional and will not make the build fail.

https://github.com/SonarSource/sonarcloud-github-action

Other options:
https://github.com/reviewdog/action-eslint
https://github.com/EPMatt/reviewdog-action-tsc

**Comment by jordanh** [comment]
@JimmyLv  I like the experimentation here. I am going to mark this as a Discussion to keep it from tripping my backlog grooming rules.

If you'd like this to become part of a sprint could you please add some acceptance criteria and estimated effort? Otherwise, please close this when you feel you have next steps

**Comment by JimmyLv** [comment]
@jordanh After the experiment, I found that sonar's default rules didn't help us much and I think it's time to disable it, sorry for the disruption.

At the moment, since I don't have Admin access on either GitHub or SonarCloud, could you please help to turn it off?
👉 on GitHub configuration: https://github.com/apps/sonarcloud/installations/28666016

![Google Chrome-Update SonarCloud's repository access-000072-20220831](https://user-images.githubusercontent.com/4997466/187613377-7817b8c7-c9cd-42d3-960f-14ff3051e9c5.png)

**Comment by JimmyLv** [comment]
Yeah, sonarcloud's comments can be disabled, but I think the problem here is that sonar's detection rules can be `false positives` (as you mentioned https://github.com/ParabolInc/parabol/issues/7122#issuecomment-1232514525).
So I am concerned that there are no comments, but the sonar check for PR will still be there, and thus the check task will still run.

https://github.com/ParabolInc/parabol/pull/7089/checks?check_run_id=8059992206

**Comment by Dschoordsch** [comment]
It's a false positive in this particular case. It complains about a possible DOS attack on a regex. This might be possible depending on the library, but doesn't matter at all if the code is run on the client like in this case.
I wanted to collect some data and hope that we may have valid finds at some point to justify the tool.

**Comment by JimmyLv** [comment]
> I wanted to collect some data and hope that we may have valid finds at some point to justify the tool.

good point! 

collect another case here: [6.2% Code Duplication](https://sonarcloud.io/component_measures?id=ParabolInc_parabol&pullRequest=7076&metric=new_duplicated_lines_density&view=list) at https://github.com/ParabolInc/parabol/pull/7076#issuecomment-1234291609

**Comment by JimmyLv** [comment]
I checked and found that the default sonar code duplication setting is `≤ 3%`, but I can't change the configuration as I don't have admin access to sonarcloud, @jordanh can you please help add me or @Dschoordsch as admin?
👉 here: https://sonarcloud.io/organizations/parabolinc/members

![Google Chrome-parabol - Parabol-000084-20220902](https://user-images.githubusercontent.com/4997466/188061435-1e86fc95-6511-4cd4-a848-473c1e6094bc.png)

![Google Chrome-Members - Parabol-000086-20220902](https://user-images.githubusercontent.com/4997466/188062127-53358e67-471e-494e-81ca-101973de7960.png)

**Comment by JimmyLv** [comment]
see related discussion, https://parabol.slack.com/archives/C836NA350/p1664188208786099?thread_ts=1664182887.626359&cid=C836NA350

_**machine checks**_ are never friendly enough. :robot_face:
