### ISSUE TITLE
Retrospective demo canonical link

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#7125]
Ahrefs continuously flags a small error where our product signup and demo pages are confused as the same link. There is currently no canonical link set. 

We purposefully index a couple of these URLs:

1. https://action.parabol.co/ so people can log into the product via Google search
2. https://action.parabol.co/retrospective-demo so people can discover the product demo via Google search

However, the following URLs are flagged as duplicate content and we should set https://action.parabol.co/retrospective-demo as the canonical link for them.

1. https://action.parabol.co/retrospective-demo/reflect 
2. https://action.parabol.co/retrospective-demo/vote 
3. https://action.parabol.co/retrospective-demo/group 

See screenshot for the errors in Ahrefs:

<img width="822" alt="Screenshot 2022-08-29 at 14 45 12" src="https://user-images.githubusercontent.com/15236825/187204063-7c74de2a-567b-4043-bbf9-594a6472861e.png">

## Acceptance criteria
* [ ] server writes a canonical link header for demo routes

**Comment by Dschoordsch** [comment]
Search engines don't evaluate JavaScript, only the html file we serve. With a SPA it's the same file for all 'action.parabol.co`. This means we need to inject the canonical link when serving the page. The simplest solution would be to write a canonical link header[^1] if the demo URL is accessed here https://github.com/ParabolInc/parabol/blob/4e2fd5dd5431c9df023fcead896d604d0a6bd5ec/packages/server/createSSR.ts#L71

[^1]: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-header-method

**Comment by raj360** [comment]
Hello, @Dschoordsch What is the most effective way to test changes made to [parabol/packages/server/createSSR.ts](https://github.com/ParabolInc/parabol/blob/4e2fd5dd5431c9df023fcead896d604d0a6bd5ec/packages/server/createSSR.ts)? Obviously, I've tried building and testing locally; but, I can't test for changes.

**Comment by gitstart-parabol** [comment]
Hello, @Dschoordsch What is the most effective way to test changes made to [parabol/packages/server/createSSR.ts](https://github.com/ParabolInc/parabol/blob/4e2fd5dd5431c9df023fcead896d604d0a6bd5ec/packages/server/createSSR.ts)? Obviously, I've tried building and testing locally; but, I can't test for changes.

**Comment by Dschoordsch** [comment]
You can `yarn build && yarn start` and then go to the reflect page with the chrome inspector (or any other debug tool) and check the response headers.
![Screenshot from 2022-12-01 09-54-52](https://user-images.githubusercontent.com/7331043/205009365-83dfdd95-7144-46a6-85e7-cee448ed9ce7.png)

Be aware that running production server will install a service worker which might conflict with `yarn dev` so it's best to remove it afterwards.

**Comment by gitstart-parabol** [comment]
@Dschoordsch, do you have any ideas on how to fix the issue I keep getting running  the production server?
<img width="1431" alt="Screenshot 2022-12-01 at 1 53 16 PM" src="https://user-images.githubusercontent.com/116144318/205036270-57f02b15-c2d4-487d-a11b-94dbfd0173ad.png">

<img width="1431" alt="Screenshot 2022-12-01 at 1 53 03 PM" src="https://user-images.githubusercontent.com/116144318/205036434-ad15f8e7-9085-45d0-9c50-c199472a8897.png">

**Comment by Dschoordsch** [comment]
I think you're missing an environment variable, but I don't know which one. Finding the exact place of the error in the HTML should help. I suggest skip minifying the code in the `createSSR` function and then you should find the origin of the error easier.

**Comment by gitstart-parabol** [comment]
Hello, @Dschoordsch . Despite testing the suggestions, we have not been able to identify the root cause of this error; however, we have submitted a draft PR [here](https://github.com/ParabolInc/parabol/pull/7516/files) that you can reference and help test out these changes from your end.

below is the unmagnified html for reference 
![Screenshot 2022-12-02 at 3 38 41 PM](https://user-images.githubusercontent.com/116144318/205306577-4af43002-fd15-49d4-8190-ec1df20d13e9.png)
