### ISSUE TITLE
Edit copy of /create-account Page

### ISSUE THREAD

**Issue by lorena-cure** [ParabolInc/parabol#7126]
Of the total amount of people who lands on the /create-account page, ~40% of them create an account. 

We would like to start optimizing this page by changing this copy first.

**Copy to replace the current one:**
92% of users agreed that Parabol improves the efficiency of their meetings.

<img width="1440" alt="Screenshot 2022-08-29 at 16 45 14" src="https://user-images.githubusercontent.com/97244811/187245312-c1007025-7b47-4108-b58e-61c0d3737ed8.png">

**Comment by mwermuth** [comment]
Hey @lorena-cure I have this running locally. Will create a PR and hopefully merge it for the release tomorrow 🙌 

<img width="925" alt="CleanShot 2022-08-30 at 14 22 53@2x" src="https://user-images.githubusercontent.com/1415538/187435556-4457704a-1b5d-42ae-87d0-15e1fc1efcf5.png">

**Comment by mwermuth** [comment]
PR waiting for Review: https://github.com/ParabolInc/parabol/pull/7132
