### ISSUE TITLE
Improving Jira search function

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7127]
A [user](https://app.hubspot.com/contacts/3888472/contact/87728551) 🔒 said: 

> Your Jira search function within Poker can be better. 
> 
> - If you type in just part of the name of a Jira card or ticket number, it doesn't come up as an option. You need to type in the entire string. 
> - Can the search function search labels in Jira?
> - Can you allow us to filter the search?
>

**Comment by tianrunhe** [comment]
Does the customer know we support [JQL](https://www.atlassian.com/blog/jira-software/jql-the-most-flexible-way-to-search-jira-14)?

**Comment by jordanh** [comment]
JQL is the preferred solution here! I am going to close this for now...

**Comment by drewhousman1010** [comment]
Re-opening this. I had two user calls recently where people said poker search problems (including using JQL) were bad enough that they had to stop using Poker. 

[This user](https://app.hubspot.com/contacts/3888472/contact/60438151) 🔒  loves Parabol but is having all kinds of search issues, namely around the inability to find the proper story in Jira despite entering what should be the right keywords. 

[Link to a slack discussion](https://parabol.slack.com/archives/C03LL1JRFH8/p1682088036908239) 🔒 , which has a gif where the user shares his screen and shows the problem.
