### ISSUE TITLE
Allow multiple team leads per team

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7134]
At this time, we only allow one team lead per team. We heard from a customer that they'd like to have more than one team lead per team. 

A [user](https://app.hubspot.com/contacts/3888472/contact/15220701) 🔒 recently said: 

> 
> I was wondering if teams could have multiple managers. For instance, I'm under the "Team X" in our company. I'd like to manage members together w/ my teammate.
> Is that possible?
> 

**Related:** 

- https://github.com/ParabolInc/parabol/discussions/6105
- https://github.com/ParabolInc/parabol/discussions/5655

**Comment by jordanh** [comment]
@drewhousman1010 correctly pointed out that this isn't a true duplicate, as the linked item is a discussion. Reopening. Doh!
