### ISSUE TITLE
DS tool and Usage Stats active teams don't match

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#7139]
## Issue - Bug

This [company](https://app.hubspot.com/contacts/3888472/deal/9767205783/) is an example of the discrepancy. They show 40 active teams on usage stats and 25 teams with lastMetAt date within the last 30 days when using our domain stats tool.
![Screen Shot 2022-08-31 at 12 32 18 PM](https://user-images.githubusercontent.com/60167404/187732756-44a47d39-5b55-4340-8ff4-57e04c94cb24.png)
![Screen Shot 2022-08-31 at 12 40 50 PM](https://user-images.githubusercontent.com/60167404/187732878-8cba65b4-91f4-40f3-99e5-5c4c80df53c3.png)

**Comment by mattkrick** [comment]
@tghanken this one kinda stumps me because active teams is greater than the count of `lastMetAt`s. 
Where does `Team.lastMetAt` come from in domain stats?

**Comment by tghanken** [comment]
We were still using `max(updatedAt)` in Domain Stats, and I just merged a fix for this today.  However, we're still seeing some discrepancies.  It appears that the Usage Stats list of orgs is different than the Domain Stats list of orgs.  Let me through together a PR on this that we can use to finalize and align on the definitions.

**Comment by jordanh** [comment]
@tghanken @mattkrick is this issue still a thing?

**Comment by tghanken** [comment]
@jordanh Yes, I have a partially written fix locally that I need to wrap up.  It is currently only affecting a small number of orgs that we activated Usage Stats on.

**Comment by mwermuth** [comment]
As @tghanken is part of Squad 2, and this likely falls into that area of responsibility. I'll mark this as Squad 2.

cc @nickoferrall @avivapinchas

**Comment by tghanken** [comment]
This should be resolved by #7937, will validate after merged.
