### ISSUE TITLE
Meetings: improve top bar layout on mobile

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7143]
## Issue - Bug

The layout of the top bar (meeting title, team members) can be improved on small screens, particularly when the meeting title is long:

<img width="448" alt="Captura de Pantalla 2022-08-31 a la(s) 5 54 25 p m" src="https://user-images.githubusercontent.com/3276087/187800023-bae0d246-d59f-4389-aa94-6ce2441d38f4.png">

In addition to this, there is no indication when the user reaches the limit of number of characters allowed in the title. Users are left to wonder what is happening as they type and see that nothing is happening.

### Acceptance Criteria

Design a solution that:
- [ ] Improves the mobile layout when the meeting title is long
- [ ] Improves the UX when editing the title and reaching the max number of characters
- [ ] Made sure fix applies to all meeting types (check-in, retro, sprint poker, and standups)

## Estimated effort:
- 4 hrs

**Comment by jordanh** [comment]
Noting related issue: #7167
