### ISSUE TITLE
Optionally run build for external PRs

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7144]
Currently build/test phase is not run for external PRs ([example](https://github.com/ParabolInc/parabol/pull/6959)). It would be good if
* we show a warning that it wasn't run
* allow parabol members to run the build (after they checked it's safe to run)

## Acceptance criteria
* [ ] investigate options available in GitHub
* [ ] implement appropriate change or create follow up issue with implementation if too time intensive

EE: 2h

**Comment by JimmyLv** [comment]
After a quick look at the options available on GitHub, it's set to "Require approval for first-time contributors" [^1], so only first-time contributors to Parabol need to be approved, is that suitable?

![image](https://user-images.githubusercontent.com/4997466/190335025-310f47a7-2061-42d0-adc9-989541d5be24.png)

[^1]: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories
