### ISSUE TITLE
There is no check for valid emails when inviting the team members

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7149]
### Discussed in https://github.com/ParabolInc/parabol/discussions/6992

<div type='discussions-op-text'>

<sup>Originally posted by **87prashant** August  3, 2022</sup>

https://user-images.githubusercontent.com/106697681/182586373-57142fef-b502-4ff9-b15c-453891959a46.mp4

Is there any way to check for valid emails? 
One issue I feel like if there is a typo in the email during sending the invite then it will show the invitation has been sent and the actual user will not get the email.

What do others think about this?</div>

**Comment by Dschoordsch** [comment]
The email you used looked like a valid (slightly unusual) email address. There is no way for us to know whether or not there is a typo since you might want to invite a new user to use parabol, closing this issue.

Please comment if you disagree.
