### ISSUE TITLE
Error: NotFoundError: The object can not be found here.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7151]
https://sentry.io/organizations/parabol/issues/3016693054/?referrer=github_plugin

```
Error: NotFoundError: The object can not be found here.

NotFoundError: The object can not be found here.
```

Happened 9 times in last 10 days, mostly to demo users.

**Comment by jordanh** [comment]
Watermark: 5 times in past 30, 9 total users affected

Going to icebox
