### ISSUE TITLE
Snackbar messages are not bottom centered during standups

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7158]
## Issue - Bug
![Screenshot 2022-09-07 125238](https://user-images.githubusercontent.com/106697681/188818615-6d4b3edb-ee4b-4f50-9154-18a023c19972.png)

- **How serious is the bug:**  P4
- **Tested on:**  Windows
- **Browser:** Chrome / firefox

### Acceptance Criteria (optional)
Snackbar messages should be bottom centered

**Comment by coachlivinglegend** [comment]
Hi @87prashant, just wondering what action in particular triggers this snackbar shown in the screenshot?

**Comment by 87prashant** [comment]
Hi @coachlivinglegend
Starting a meeting after starting another meeting (I think before the particular duration).
