### ISSUE TITLE
Send button is disabled in retro discussion on mobile 

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7165]
## Issue - Bug
Send button is disabled on mobile. However, we can send using the keyboard arrow/next-line button. I think it should be similar to the desktop version and the next-line button should work as next line button 

Apart from that clicking on the send button also closes the keyboard which is also annoying. 

#### Desktop
![Screenshot 2022-09-09 224844](https://user-images.githubusercontent.com/106697681/189408438-c5951f6f-ef82-4a1c-9c33-4fdff5ee9cc2.png)

#### Mobile
https://user-images.githubusercontent.com/106697681/189408259-3ed76f93-08f0-47df-9ce0-306b0c3027e1.mp4

- **How serious is the bug?** P4
- **OS:**  Android
- **Browser:** Chrome 

### Acceptance Criteria (optional)
- User can send the comment using the send button
- Clicking the send button should not close the keyboard
- Next-line button should change the line (instead of sending comment) as there is no other way on mobile to change the line.

**Comment by 87prashant** [comment]
Same behavior also present in `Poker` and `Check-In`

**Comment by jordanh** [comment]
Wow. That's very odd! Good find
