### ISSUE TITLE
Check-in: improve top bar layout on mobile

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7167]
## Issue - Bug
![Screenshot 2022-09-10 212851](https://user-images.githubusercontent.com/106697681/189491598-d0a8b757-45cc-4d40-8631-6498f26ae1eb.png)

Similar to #7143

**Comment by usmailaabdoul** [comment]
Hi @87prashant, how do we get to this page

**Comment by victorgbaye** [comment]
@87prashant are you referring ing to the alignment of the top bar? and is there a proposed design to follow?

**Comment by 87prashant** [comment]
Hi @victorgbaye 
> are you referring ing to the alignment of the top bar?

Yes
> and is there a proposed design to follow?

Not currently

**Comment by jordanh** [comment]
Note: going close this as a duplicate of #7143 after adjusting this former issue's title and acceptance criteria
