### ISSUE TITLE
Sprint Poker: "Estimate phase is already complete" error message

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7191]
This message appears when the estimate phase is completed. We consider it completed when all stages are completed. We mark a stage completed when the facilitator moves to the next stage after it.
Since this cannot happen for the last stage in a Sprint Poker meeting, to reach this state you have to either
* navigate through all issues and then remove the last non-completed issue
* move a completed issue to the last position and move through the others

This way all stages can be completed without also ending the Poker meeting.
I don't think this logic is correct given the async use case and at the moment we don't have any phases after estimate, so there is no reason to check for `isPhaseCompleted` in this case.

The error came up in a support case [[slack thread](https://parabol.slack.com/archives/C4JAUUZ9P/p1663250944275279)]

## Acceptance criteria
* [ ] voting in Sprint Poker is possible even when all stages are completed, i.e. don't check for `isPhaseCompleted('Estimate'...)`

**Comment by 87prashant** [comment]
Similar issues:
#6755
#6890

**Comment by jordanh** [comment]
I know this is still a thing, but I'm going to icebox it as it went stale again. If it gets reopened, let's really fix it.
