### ISSUE TITLE
Automatically drafts next release notes as pull requests are merged into master

### ISSUE THREAD

**Issue by JimmyLv** [ParabolInc/parabol#7196]
As a release owner, currently we have to manually create Release Changelog in [Release Playbook](https://www.notion.so/parabol/Release-Playbook-c3d1b146ea7c4f2fbf9501ae578ced25). 
Also, being an open-source project, we don't integrate/use GitHub's [Release](https://github.com/ParabolInc/parabol/releases) and right now using the [Markdown format `CHANGELOG.md`](https://github.com/ParabolInc/parabol/blob/master/CHANGELOG.md) could not able to associate issue numbers and committers (at least not yet).

let's use the [Release Please](https://github.com/googleapis/release-please) GitHub bot to have a try, automates CHANGELOG generation, the creation of GitHub releases, and version bumps for our project.
![image](https://user-images.githubusercontent.com/4997466/191206346-4ede85f0-64d3-471b-b41a-84f65abdd658.png)

## ACs

- [ ] Add https://github.com/google-github-actions/release-please-action
- [ ] Update the [configuration](https://github.com/google-github-actions/release-please-action#configuration)
- [ ] Update the [Release Playbook](https://www.notion.so/parabol/Release-Playbook-c3d1b146ea7c4f2fbf9501ae578ced25)
- [ ] changelog entries do not have `fix`, `chore` prefix etc.
- [ ] category/component of prefix is added in bold, i.e. `chore(DX): add release draft notes` is converted to `**DX**: add release draft notes`

_edited_: replace the [Release-Drafter](https://github.com/apps/release-drafter) with [Google Release Please](https://github.com/googleapis/release-please)

**Comment by rafaelromcar-parabol** [comment]
Why using [Release-Drafter](https://github.com/apps/release-drafter) over [Google Release Please](https://github.com/googleapis/release-please)? Release please also has a proposed [Github action](https://github.com/google-github-actions/release-please-action).

**Comment by Dschoordsch** [comment]
Added AC to not continue adding the conventional commit prefixes to the changelog

**Comment by JimmyLv** [comment]
@rafaelromcar-parabol Quick answer, I think that's why it's called `Draft`, because my initial intention was just to generate the latest changes from the last release Tag 🤣
But thanks for introducing [Google Release Please](https://github.com/googleapis/release-please), I thought if we could do it in one step, it would be straightforward to do.

**Comment by rafaelromcar-parabol** [comment]
Yeah, Release Please looks great. I've been planning on testing it and I'll do it probably this week for one Terraform module, just to test it. 

As it is suppose to do more than the Release-Drafter, would you like to test that with me and then decide which one to implement? Or you prefer me to enable Release-Drafter here anyway?

**Comment by JimmyLv** [comment]
After testing Release Please with Rafa at https://github.com/ParabolInc/terraform-module-parabol-gcp, it works really well and does a lot more. 
Unlike the Release-Drafter, it generates a PR with the release branch to automatically update the version number, which completely replaces the version changes we were doing manually in the `staging` branch. 
Next I will try to test the Node.js project for our main Parabol repository, especially for the monorepo typo, to see if it works equally well.
