### ISSUE TITLE
Bug: Auto Group titles should not erase manually input title

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#7207]
## Issue - Bug

[A user](https://app.hubspot.com/contacts/3888472/contact/77510551) 🔒 reports:
> There was one particular thing that's annoying, when grouping cards, it's trying to be smart and auto-suggest the name of the group, but that also overrides the "custom" name that was given, this was the most annoying thing we noticed as we often try to incrementally group things and each time adding a new card to the group made us lose the name.

I quickly test this on our demo team and was unable to reproduce it single player. I wonder if this only happens in multiplayer (e.g. if the Viewer isn't the one to set the title)?

I suggest the first step with the bug is testing it multiplayer and seeing if it can be reproduced... This would be very annoying indeed!

### Acceptance Criteria (optional)

Performed triage to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
@MindEvo could you test this issue and add reproduction steps if you could reproduce it?

**Comment by MindEvo** [comment]
Steps to Reproduce:
1) Create some cards.
2) Give a title to a single card group.
![image](https://user-images.githubusercontent.com/35351786/191378584-ef8ca299-33af-4be2-bff9-ff119eff59fb.png)
3) Drag that card to another card to create a group.
![image](https://user-images.githubusercontent.com/35351786/191378658-2e52435e-a06f-4780-9bb6-23725e9d846a.png)
4) Observe the bug.


Note: I have a video of this but there's a 10mb size limit here. I can send it through slack if needed.

**Comment by jordanh** [comment]
Thank you @MindEvo!
