### ISSUE TITLE
ability export all tasks to CSV from dashboard 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7213]
A [user ](https://app.hubspot.com/contacts/3888472/contact/68389701) 🔒 asks:

> Can I export all of my active tasks to CSV? I don't want to do it meeting by meeting. Just all of the current and active tasks

**Comment by jordanh** [comment]
This is a nice one

**Comment by drewhousman1010** [comment]
> Good morning, I would like to know how can export all my tickets history to a CSV.

From this [user](https://app.hubspot.com/contacts/3888472/contact/1291151) 🔒

**Comment by enriquesanchez** [comment]
A [customer](https://app.hubspot.com/live-messages/3888472/inbox/3495602538#live-chat) 🔒 wrote in:

>Are there ways to export tasks to Excel or text file?

**Comment by lilicaruso** [comment]
A [customer](https://app.hubspot.com/live-messages/3888472/inbox/4001973095#live-chat) wrote in to support: 

> How do I import tasks from a csv file to parabol?

**Comment by mwermuth** [comment]
Looked at during backlog grooming. Going to icebox it.
