### ISSUE TITLE
Awkward Scrolling Experience in Retros with Expanded Screens

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7222]
A [user ](https://app.hubspot.com/contacts/3888472/contact/56279051) 🔒 writes:

>  I have to expand my screen on retros so that its legible in remote meetings. This makes the bigger templates side scroll (horizontal) during voting, but the z-axis of the little control panel thingy at the bottom of the screen sits on top of the horizontal scroll bar, making it a little awkward to scroll.

**Comment by jordanh** [comment]
Interesting feedback! So the tension here is that our facilitator panel makes it difficult for them to horizontally across? Is that right?
