### ISSUE TITLE
Auto focus on new template title

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7240]
[This chart](https://analytics.amplitude.com/parabol/chart/inrjy9s?source=search) in amplitude suggests that users may not know how to edit some template titles.

There are several templates that are being regularly used with the word "Copy" at the end, e.g. `Start, Stop, Continue Copy`.

The title `*New Template` is being used by almost 20 users each week in total across dozens of teams, [see chart](https://analytics.amplitude.com/parabol/chart/z4jdghx?source=redirect%3A%20chart%20saved).

I suggest that we auto-focus on the title after clicking "Create custom template" or copying a template. See Loom for further info: https://www.loom.com/share/a315a07f09b94fcf9ba373b7c80d52ab

### AC

- [ ] After clicking "Create New Template" or clone & copy a template, the title is auto-focused and the text is empty
- [ ] The `Please enter a template name` error message doesn't show up initially on auto-focus, but if the user doesn't enter a title and they click away, it does show-up onBlur

**Comment by jordanh** [comment]
Way to use data!
