### ISSUE TITLE
Editing: Strike through is not working

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7244]
The keyboard input dialog shows strike through options, none of these appear to work.

## How to reproduce
1) create a task and add some text, select it and press <ctrl>+<shift>+x
2) insert text wrapped in `~` or `~~` and press enter
3) do the same in discussion input

## Expected
Text will be stricken through as explained in the help dialog
![Screenshot from 2022-10-04 12-44-27](https://user-images.githubusercontent.com/7331043/193804976-00062cfd-d214-42ed-acd7-b5dc4e3ab2f1.png)

## Actual
Text appears normal, `~~` and `~` stay in the text.
![Screenshot from 2022-10-04 13-15-20](https://user-images.githubusercontent.com/7331043/193805110-ce1da310-924b-4762-a284-551d9e9dc5c6.png)
![Screenshot from 2022-10-04 13-14-57](https://user-images.githubusercontent.com/7331043/193805112-7b313e63-fb42-4df1-9f8b-a0782419fc1f.png)

**Comment by 87prashant** [comment]
I think the below are also not working: 

![Screenshot 2022-10-04 171004](https://user-images.githubusercontent.com/106697681/193810630-640b4d53-836c-448c-8721-752f56d44ea4.png)

**Comment by 87prashant** [comment]
@Dschoordsch 
Markdown for strikethrough is working but I have to:
- give space after 
- use only a single word at a time. 

But the keyboard shortcut is not working for the same.

**Comment by Dschoordsch** [comment]
@87prashant thanks for checking!

**Comment by jordanh** [comment]
Going to icebox this one. We can re-address when we move from DraftJS to TipTap throughout the product
