### ISSUE TITLE
`Keyboard Shortcuts` header name should be more general

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7245]
## Issue - Bug

Keyboard Shortcuts are applicable almost everywhere. So I think header should be more general.

![Screenshot 2022-10-04 190406](https://user-images.githubusercontent.com/106697681/193833370-5b906360-6990-4b3b-af89-1a5551fc7b48.png)

**Comment by jordanh** [comment]
We'd gladly take a PR with this header renamed to "Formatting Text"

**Comment by byasi** [comment]
Hi there, I am interested in fixing this bug but not sure how to navigate to this page. Kindly requesting on how to display this modal

**Comment by Dschoordsch** [comment]
On the top right on the dashboard "?" -> "Keyboard shortcuts"
![Screenshot from 2022-10-14 09-05-02](https://user-images.githubusercontent.com/7331043/195783859-d12f476a-3ada-4897-9a63-f6136ed01061.png)
