### ISSUE TITLE
Users might not aware of `comment anonymously` feature

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7246]
## Feature
In my opinion, as a user, it is not obvious to click on the avatar. Though placeholder may help in this by `comment publicly`

If there could be a way to make it obvious for new users? Maybe animations to give hint about this.

![Screenshot 2022-10-04 191055](https://user-images.githubusercontent.com/106697681/193835330-3cac5d12-f34e-4355-871b-da599d66e5e4.png)

**Comment by Dschoordsch** [comment]
I agree it's not an easy to find feature. It is also not a very important feature for users, especially at the beginning when they're still learning. I think having an animation once when focusing the input field might work.

I don't agree that this is a but though.

**Comment by Dschoordsch** [comment]
A design proposal would be very much appreciated!
