### ISSUE TITLE
Profile name length should have the upper limit 

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7252]
## Issue - Bug

It causes UI issues:

![Screenshot 2022-10-05 232211](https://user-images.githubusercontent.com/106697681/194129339-0b5a7459-18d6-4313-b2f3-e835e7e179ac.png)

![Screenshot 2022-10-05 232334](https://user-images.githubusercontent.com/106697681/194129335-01162e3f-35a3-4c30-ab89-a740fe186c92.png)

**Comment by raj360** [comment]
Hi @87prashant, for purposes of user experience I would suggest appending an error message to the input once the upper limit is reached, just to add awareness to whoever if updating the username. whats your take on this? cc @jordanh @Dschoordsch

**Comment by Dschoordsch** [comment]
`preferredName` has an upper limit in the database because it is defined as `VARCHAR(100)`. I would shy away from adding additional verification on the client side. However, it would be good if we'd enforce word wrap if they choose a name that is too long to fit into one line and has no spaces.
