### ISSUE TITLE
"team check-in" meeting shows agenda of previous meeting

### ISSUE THREAD

**Issue by VaheHayrapetyanIM** [ParabolInc/parabol#7256]
- [ ] Decide is this is a bug or an enhancement request (if you can't decide, join the chat in [slack](http://slackin.parabol.co/) and ask in `#general`)
- [x] I've checked open (and closed!) issues and made sure that the issue doesn't already exist.
- [x] I've completed the Bug section below
- [ ] I've deleted this checklist section before I hit submit

## Issue - Bug

- **How serious is the bug?** P2
- **Browser:** Chrome

We created a "team check-in" meeting, and went through all of the team agenda items. Then in our next "team check-in" meeting, the same agenda items reappeared, so we have deleted them. Then when i went to review discussion from the first "team check-in," the discussion was gone, presumably because the agenda items were deleted.

**Comment by jordanh** [comment]
Reopened #4521. Closing this one in favor of #4521.

Thank you for the report!
