### ISSUE TITLE
Improve readability of Azure task integration

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7274]
After pushing a task to an Azure project, we see the id in the link:

![Screenshot 2022-10-12 at 10 35 40](https://user-images.githubusercontent.com/39854876/195307528-07b23294-accd-4d7f-bbe3-7415acaad5b1.png)

### AC

- [ ] Show something human readable in the link that is consistent with the other integrations, such as the name of the project

**Comment by jordanh** [comment]
It's not _really_ a bug. Relabeling
