### ISSUE TITLE
Remove @types/ioredis

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7280]
@igorlesnenko [noticed](https://github.com/ParabolInc/parabol/pull/7234#discussion_r993460521) that we can remove @types/ioredis once we've upgraded to Redis v5: https://github.com/luin/ioredis/wiki/Upgrading-from-v4-to-v5

### AC

- [ ] Removed @types/ioredis package without breaking anything

**Comment by BartoszJarocki** [comment]
@nickoferrall is it about removing `@types/ioredis`?

**Comment by nickoferrall** [comment]
Sure thing, I've updated the title

**Comment by Dschoordsch** [comment]
While I appreciate keeping PRs small, creating a PR with this one line fix would have been easier and faster than creating this issue.

**Comment by nickoferrall** [comment]
True - I was thinking it was like a regular package that requires updates elsewhere in the app, but of course it's just removing the types now Redis provides this out of the box 🤦
