### ISSUE TITLE
Need to refresh the page to see new integration in task menu

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7283]
After adding or removing an integration, the user needs to refresh the page to see the new/removed integration in the task footer menu.

The user might look at the menu and think that their newly added/removed integration hasn't been added/removed.

### AC

- [ ] After adding/removing an integration, the user can open the task footer menu and see the update without refreshing the page

**Comment by jordanh** [comment]
Under the rationale that the user doesn't care if we never implemented the subscription or not, I will classify this one as a bug
