### ISSUE TITLE
Notifications: Batch notification email improvements

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#7284]
Make batch notification summary emails more useful, actionable, and frequent.

Product Brief: https://www.notion.so/parabol/Product-Brief-Batch-Notification-Email-Improvements-e4e3ca2e203b4864bc8de0bb950298e9
Spec: https://www.notion.so/parabol/Spec-Batch-Notification-Email-Enhancements-f5a99dd9509a4aff93b6ec6568a969ae

**Comment by BartoszJarocki** [comment]
@jmtaber129 at this point this could be closed, right?
