### ISSUE TITLE
Research sign-up flows of other SAAS tools

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7288]

**Comment by JimmyLv** [comment]
I added a signup use case from ProductHunt, showing a popup to signup with Google account. https://www.notion.so/parabol/Ideas-References-6039a0c5319641fab858e1b3f74aae19#854a60402d144efc91ae4016e59d4aeb

![Google Chrome-Product Hunt – The best new products in tech -000641-20221018](https://user-images.githubusercontent.com/4997466/196455432-59b23edb-7bb3-4a40-822a-b0f62b85908f.png)
