### ISSUE TITLE
Design proposal that places a sign-up field in the homepage

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7289]
Experiment: Remove friction by placing the sign-up email field in parabol.co’s homepage

**Comment by enriquesanchez** [comment]
Here's the design direction we are going to go with for our initial experiment:

![imagen](https://user-images.githubusercontent.com/3276087/198094528-ad28bd9a-3499-468e-9236-1eeab12a6dd4.png)

The goal is to test if an email signup field in the homepage yields an increase in signups. For that reason, we are introducing as little change as possible and only adding the email field while moving the `Try a practice round` button below and reducing its visual hierarchy by making it a link instead.

@JimmyLv @lorena-cure Please add any questions or comments to this issue.

**Comment by enriquesanchez** [comment]
Also cc. @acressall in case you have any insights.

**Comment by enriquesanchez** [comment]
@JimmyLv From a technical stand point, here's how I think this should work:

- When a user enters their email and submits the form, they are taken to `action.parabol.co/create-account`. 
  - How do you feel about keeping form validation on `/create-account`? Meaning that if the email they entered is invalid, we don't show the error message in the homepage and instead show it on `/create-account`. How does that sound to you?
- The email field in `/create-account` should already show the email they just entered previously in the homepage.

**Comment by acressall** [comment]
This looks good and the functionality seems simple enough on the website side.
@JimmyLv we'll need to create a new block in WordPress for this. Would you feel comfortable trying that or will you like me to do that part?

@lorena-cure from a content editor perspective, I think this would be a new component with the input field and button text hard-coded for now, since we'll need to do some fancy stuff on the button click. Is that ok for you?

**Comment by JimmyLv** [comment]
@acressall I've previously figured out how to add an HTML block (yeah, there will be a hard-coded logic) to a WordPress site, so I'd like to try adding a button to https://develop.parabol.co, and will get your help for the Review. 
This is an unknown area for me and I will probably encounter problems. 😂 But I'm happy to learn and see.

**Comment by JimmyLv** [comment]
> The email field in /create-account should already show the email they just entered previously in the homepage.

@enriquesanchez The `/create-account` now already has the logic to do this, just append `?email=xxx@gmail.com` to the end of the URL, which automatically fills in the corresponding email address. So let's keep it simple and let the email validation happen in the [action.parabol.co](https://action.parabol.co).

https://user-images.githubusercontent.com/4997466/200570409-8acb4637-0570-4f06-bf1d-a9767ba0c940.mp4

**Comment by acressall** [comment]
@JimmyLv do you want to set up a time for us to chat about the website setup? I'm not sure what the impact would be on the performance if we used an HTML block. The alternative is we could create an entirely _new_ block locally. I think we should chat about it to decide which way will make the most sense

**Comment by JimmyLv** [comment]
@acressall cool, thanks let me know that we can create the block **locally**! 
aha, when you reply to me here. I just asked you a question on [slack](https://parabol.slack.com/archives/C043AHXNB32/p1667917647751579) and I think that's the answer I was looking for. 😁
Of course, exactly how to develop a local block, I guess we could set a time to demonstrate that, thanks!

**Comment by enriquesanchez** [comment]
Design is ready. Closing in favor of the implementation issue #7290
