### ISSUE TITLE
Implement homepage sign-up field and filling email address in `/create-account` page

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7290]
See design: https://github.com/ParabolInc/parabol/issues/7289#issuecomment-1292373770

![Image](https://user-images.githubusercontent.com/4997466/200559750-af10db59-7c19-4c01-898e-aa22f6b23fc6.png)

Figma: https://www.figma.com/file/UVwOvQbjKsaN9tkXTILKEW/Sign-up-from-homepage?node-id=55%3A494

**Comment by JimmyLv** [comment]
I've just changed the title of this issue, to identify this is our first initial experiment to reduce sign-up friction #7287 

The whole sign-up process experiment will be in 3 stages, the 2nd and 3rd are out of scope.

1. place a sign-up field on the home page, after the user filling in the email, redirect to the /create-account page and populate the email number (initial experiment) 
2. place a Google sign-in button next to the sign-up field on the home page, allowing the user to sign in with a single click 
3. on all parabol.co content pages, add the top right corner of the Google auto-login popup, ref: https://github.com/ParabolInc/parabol/issues/7288#issuecomment-1282468344

## Acceptance Criteria

- user can see the sign-up field and type the email address
- click the 'Get Parabol for Free' button 
- redirect the user to `/create-account` page
- `/create-account` should show the email
- user adds password and finish the sign-up process

## References:

[Setup  |  Authentication  |  Google Developers](https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid)

**Comment by JimmyLv** [comment]
Using the native WordPress HTML Block would enable the functionality, as the form code is below. 
But since the HTML Block could not insert inside the existing Hero Layout on the home page, we currently need to create a whole new hero locally. ref: https://www.loom.com/share/2edb89a37d1844e6a60582c466ee50f9

cc @acressall 

```html

<div class="sign-up-html-block">
  <form action="https://action-staging.parabol.co/create-account" method="get" target="_blank" class="sign-up-form">
    <div class="form-item-input-email">
      <input type="email" name="email" placeholder="Your email address" id="email" required />
    </div>
    <div class="primary shadow text-16 leading-24 font-weight-500  mb-16 md:mb-0 md:mr-16 lg:mr-32">
      <input class="sign-up-form-button" type="submit" value="Get Parabol for Free" />
    </div>
  </form>
  <a class="sign-up-demo" href="https://action.parabol.co/retrospective-demo/reflect" target="_blank">Try a Practice Round</a>
</div>

<style>
  .sign-up-html-block {
    background: #7b54aa;
  }
  .sign-up-form {
    display:flex;
    align-items:center;
    justify-content:center;
  }
  .sign-up-form-button {
    background: transparent;
  }
  a.sign-up-demo {
    margin-top: 10px;
    font-size: 16px;
    font-weight: 400;
    line-height: 24px;
    display: flex;
    align-items: center;
    justify-content: center;
    text-decoration-line: underline;
    color: #FFFFFF;
  }
</style>
```

**Comment by BartoszJarocki** [comment]
@acressall correct me if I'm wrong, but this is done, right? 🙏

**Comment by acressall** [comment]
Yes, this is done! We have a fix for the CTA on the parabol-dot-co repo https://github.com/ParabolInc/parabol-dot-co/issues/89
