### ISSUE TITLE
Reflection card visually disappears when you try to drag it from an expanded group of cards

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7297]
First seen in 6.77.0, since then it occurred > 900 times. 

https://sentry.io/organizations/parabol/issues/3649823309/?referrer=github_plugin

```
TypeError: Cannot read properties of null (reading 'cloneNode')
  at cloneReflection (./packages/client/utils/retroGroup/cloneReflection.ts:13:25)
  at current (./packages/client/hooks/useDraggableReflectionCard.tsx:335:20)
  at apply (./packages/client/hooks/useEventCallback.ts:14:16)
```

**Comment by igorlesnenko** [comment]
Looks like happens when you try to drag a card from an expanded group of cards:

https://user-images.githubusercontent.com/466991/196685027-acc04743-8689-4ee2-adc0-9387834f72a7.mov

**Comment by Dschoordsch** [comment]
Might be related to #6910 `packages/client/hooks/useDraggableReflectionCard.tsx`
