### ISSUE TITLE
Standups: Implement ended meeting view

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7298]
Implement the design from #7033

**Comment by BartoszJarocki** [comment]
@enriquesanchez as I'm working on this, I think it'd be good to replace placeholders when the meeting has already ended, as it's not possible to update the response then.

Do you think this looks good or should we use something different than just `No response`? 
![localhost_3000_meet_hI1fhGaN3i_responses](https://user-images.githubusercontent.com/1017620/197538907-29be1c23-e79f-4ac7-a60f-6c7ae986907e.png)

**Comment by enriquesanchez** [comment]
@BartoszJarocki `No response` looks good! 

Would you still be able to update/add a response?

**Comment by BartoszJarocki** [comment]
I can't find it right now but I'm pretty sure the agreement was to _not_ be able to update the/add the response but still allow folks to talk in discussion threads

**Comment by enriquesanchez** [comment]
Yes, I remember that as well 👍
