### ISSUE TITLE
Add retro template graphics into selector

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#7306]
**Tension**

I noticed that our latest template graphics aren't showing up in the product interface. 

**Resolution**

We should add the new template graphics to the template picker modal. The following templates are affected:

- [ ] Christmas retrospective
- [ ] Always be learning
- [ ] Diwali retrospective
- [ ] Hands on deck activity
- [ ] Halloween retrospective
- [ ] Hero's journey retrospective
- [ ] Hopes and fears retrospective
- [ ] Superhero retrospective
- [ ] Hot air balloon
- [ ] Keep problem try
- [ ] Six thinking hats
- [ ] Highlights and lowlights
- [ ] Questions comments concerns
- [ ] SaMoLo
- [ ] Marie Kondo retrospective
- [ ] New year retrospective
- [ ] Original 4
- [ ] SWOT analysis
- [ ] Rose Thorn Bud
- [ ] WRAP
- [ ] Speed car
- [ ] Team retreat planning
- [ ] Thanksgiving retro
- [ ] Surprised worried inspired

All the template images can be found [here](https://drive.google.com/drive/u/0/folders/123srLIG0ZoXiF8m7OkTNi9JcaEqcoqTx)

**Comment by garethaledavies** [comment]
Can someone coach me on how to add these graphics? I would be happy to implement the change myself (as I did with icebreakers) if someone can tell me how to engage with the code.

**Comment by Dschoordsch** [comment]
The illustrations are not stored in the database, but are static content on the client side.
* put the graphic into [static/images/illustrations](https://github.com/ParabolInc/parabol/tree/master/static/images/illustrations)
* add the [import](https://github.com/ParabolInc/parabol/blob/22a0d9030d4323b415739eee8de019fbdf1c6573/packages/client/modules/meeting/components/ReflectTemplateDetails.tsx#L17)
* add the [mapping to the template id](https://github.com/ParabolInc/parabol/blob/22a0d9030d4323b415739eee8de019fbdf1c6573/packages/client/modules/meeting/components/ReflectTemplateDetails.tsx#L130)

Here is a list of all template ids so you can look for the correct ones:
```
"ikeEgKtMlO"
"diwaliRetrospectiveTemplate"
"halloweenRetrospectiveTemplate"
"alwaysBeLearningRetrospectiveTemplate"
"g1e8AwyTvO"
"aChristmasCarolRetrospectiveTemplate"
"energyLevelsTemplate"
"dropAddKeepImproveDAKITemplate"
"marieKondoRetrospectiveTemplate"
"dreamTeamRetrospectiveTemplate"
"herosJourneyTemplate"
"gladSadMadTemplate"
"g1n26U6j0A"
"fWD4szKkJa"
"fourLsTemplate"
"mountainClimberTemplate"
"original4Template"
"estimatedEffortTemplate"
"hotAirBalloonTemplate"
"ikeJimDpD2"
"surprisedWorriedInspiredTemplate"
"g1n2DTxMju"
"highlightsLowlightsTemplate"
"questionsCommentsConcernsTemplate"
"sWOTAnalysisTemplate"
"ikj2SdPiCc"
"ilFnClCBjO"
"ikfgDllOow"
"handsOnDeckActivityTemplate"
"newYearRetrospectiveTemplate"
"starfishTemplate"
"roseThornBudTemplate"
"sailboatTemplate"
"keepProblemTryTemplate"
"startStopContinueTemplate"
"hopesAndFearsTemplate"
"speedCarTemplate"
"teamCharterTemplate"
"teamRetreatPlanningTemplate"
"sixThinkingHatsTemplate"
"workingStuckTemplate"
"superheroRetrospectiveTemplate"
"leanCoffeeTemplate"
"thanksgivingRetrospectiveTemplate"
"wsjfTemplate"
"whatWentWellTemplate"
"saMoLoTemplate"
"scrumValuesRetrospectiveTemplate"
"threeLittlePigsTemplate"
"wRAPTemplate"
"winningStreakTemplate"
```
