### ISSUE TITLE
Limit Meeting History to X months for free plan

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7307]
## Issue - Enhancement

Meeting history may not be important to an individual team member, but would matter more to a lead looking to understand their team's behavior over time. We should limit the history we provide on the personal plan and include features around context, history and trends over time in our paid plans instead. 

Some considerations: 
- What should the limitation be? How many months? 
- How do users learn about the limitation? 
- How are users directed to solve their problem if they want more history? 
- How do we evaluate if this was effective? <- could be qual or quant 

[Slack discussion 🔒 ](https://parabol.slack.com/archives/C042E8PGPD4/p1666088173461069), [Notion card 🔒 ](https://www.notion.so/parabol/Limit-Meeting-History-to-X-months-for-free-plan-59967cdd58f9407db29b3aaa6f579566)

### Acceptance Criteria (optional)
Users on the free plan can only see limited meeting history, and understand they need to upgrade to see more. 

**Estimated effort:** [13 points](https://action.parabol.co/new-summary/hwEj48juqk) 🔒 
​

**Comment by Dschoordsch** [comment]
Progress is tracked in #7375
