### ISSUE TITLE
Remove pro-rated billing [exploration]

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7308]
## Issue - Enhancement

Users today are charged based on how much they were active within a month, not whether or not they were active in a month. This leads to confusing invoices and hard-to-understand bills, for both customers and the Parabol team. 

Instead, we should charge accounts based on the number of users who are active at the time of billing. 

[Background](https://www.notion.so/parabol/How-should-billing-work-8b2573b8fae6486a922b903cf836e83d) 🔒, [Notion card](https://www.notion.so/parabol/Remove-pro-rated-billing-e453e80025aa48168b3ecd44bb6f6776) 🔒 

### Acceptance Criteria (optional)
Parabol team understand complexity of switching to billing based on active users at time of bill, rather than pro-rated based on usage within the month. 

**Estimated effort:** [8 points](https://action.parabol.co/new-summary/hwEj48juqk)
​

**Comment by Dschoordsch** [comment]
See #7409
