### ISSUE TITLE
Design custom template upgrade modal

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7330]
When a free tier user clicks "Create New Template" in the retro template picker, we want to open a modal that informs the user that creating custom templates isn't possible on the free tier.

The modal also includes a CTA button that takes them to the Billing page where they can upgrade.

See [Notion doc](https://www.notion.so/parabol/Template-limits-on-starter-plan-limited-number-and-or-limit-sharing-customization-e5231a1dcfa5450a99b2dc5c09480a0a) 🔒 for further context.

### AC

- [ ] Design created for a modal that contains text explaining that custom templates aren't available on the free/starter plan
- [ ] Modal design includes a CTA button that takes the user to the Billing page
- [ ] We should give the user feedback that the `Create New Template` button isn't possible on the free/starter plan. Perhaps a lock emoji next to it as Georg suggests [below](https://github.com/ParabolInc/parabol/issues/7330#issuecomment-1290462401)?

**Comment by Dschoordsch** [comment]
I personally don't like teasing with a feature that's not obvious that it's not available. I would prefer to either
* change the button to "Upgrade to Create New Templates" or
* add a lock symbol next to it, similar as it's planned for the templates

**Comment by nickoferrall** [comment]
Yeah, I completely agree! I'd be in favour of a lock symbol next to it, but it's up to the designer. I'll update the description to mention this

**Comment by nickoferrall** [comment]
Add a lock emoji to the custom templates button letting the user know that it's a premium feature:

![locked](https://user-images.githubusercontent.com/39854876/199538173-fbc2316d-c55b-457e-8c63-c3b181e1da52.png)

When the user clicks the "Create New Template" button, a modal opens up:

![modal](https://user-images.githubusercontent.com/39854876/199538180-92dc620f-b572-498b-a810-2571785afdd5.png)

The "Upgrade Now" CTA takes the user to the billing page

**Comment by acressall** [comment]
@nickoferrall I'm struggling a bit with having a modal within a modal here. I really like the "Premium template" text you have for [this solution](https://github.com/ParabolInc/parabol/issues/7332#issuecomment-1300890923) and wonder if we can keep it more consistent. Could we put the content that you currently have in the modal in the right side of the existing modal instead?

**Comment by nickoferrall** [comment]
> I'm struggling a bit with having a modal within a modal here

Yeah, I do think modals within modals isn't ideal! Although the template picker modal does exist within the meeting picker modal, so there is precedent 

> Could we put the content that you currently have in the modal in the right side of the existing modal instead?

Here's an quick image showing what that might look like (button would be a different colour, font a different size and position, different img):

![error-msg](https://user-images.githubusercontent.com/39854876/199804478-e472d7eb-6cc5-4e7f-a0ce-bb06db67c158.png)

Personally, I feel that the right-hand side shows content related to the template item that's selected. It makes sense that this updates when we click "Create New Template" because it reflects the new template UI. But I'm not sure I'd expect an error/upgrade message to show there when my eyes are focused on the top left of the modal.

It would also be a bit easier to build the modal vs updating the right side of the template picker, but if you feel that we shouldn't go near the modal inception, then I'm happy to update the right side of the template picker! 

Here's a rambling Loom with my thoughts if that's unclear at all: https://www.loom.com/share/692f1d69655c4bdabcc2e329ff3e13a6

**Comment by nickoferrall** [comment]
Makes sense! Thanks for the feedback and suggestions.

@ackernaut & @avivapinchas it’d be great to get your thoughts on this one 🙏  At the moment, a user opens the new meeting modal and then opens the template picker modal. From here, if a user on a free team clicks “Create New Template”, I’d like to open another modal that lets them know that it’s a premium feature and they’ll need to upgrade.

It’s not ideal to have modals within modals, but it would be very quick to build (basically copy & pasting an existing modal) and feels safe to try to me. We could always go with this approach to start with and then update it once a designer has the chance to work in it? Any objections?

**Comment by ackernaut** [comment]
We have 2 concerns here. One is trying this limitation within our current UI. The other is using the best UI patterns we can. At the end of the day I think both are safe in terms of we need to learn, and we could undo it or iterate on the pattern.

It is a poor pattern and we are already have 1 item of UI debt in this case. When Enrique designed the meeting selector, the idea was that any sub view would take over the dialog (not open another dialog). So if they tapped to select a template, you would be 1 level deep (perhaps the template view slides in) with a back button to the top view of the dialog. We skipped that level of complexity. Using another dialog is once again skipping complexity, increasing UI debt. At some point I question when users will perceive lower quality in our UI, but that is a future tension. However, I’m not sure we can adapt to the perception in time other than go back and fix stuff and hope that new folks will find that our UI is of higher quality.

I think the use of the right panel to communicate the limitation when tapping create new template is clever. It makes me question how can we use the UI that exists to communicate inline. How long would it take to create that conditional details view for the tier message instead of a template editing view?

**Comment by nickoferrall** [comment]
> Using another dialog is once again skipping complexity, increasing UI debt. At some point I question if and when users will perceive lower quality in our UI

That makes sense!

> How long would it take to create that conditional details view for the tier message instead of a template editing view?

It'd probably turn a very small PR into a moderate one. The components are located quite far from one another so there'd be a fair bit of prop passing plus some UI to implement, but nothing crazy.

How would you @ackernaut & @acressall feel about the design proposal here:

![upgrade-now](https://user-images.githubusercontent.com/39854876/200559696-b846dfae-5ea3-41b7-8452-67845a118a41.png)

After clicking "Create New Template", the right-hand side would change to this. I'm thinking the "Questions, Comments, and Concerns" item wouldn't be highlighted, the center alignment between the title & text would be better, and the image would be something different.

**Comment by acressall** [comment]
LGTM! I think the image could stay the same! This is actually the custom template image, but we're also using it as a default right now. I'm pretty sure Gareth has an issue created for updating the template images
