### ISSUE TITLE
Design for the team & org page of template picker

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7331]
Now that custom templates will be a paid-for feature, we need to update the Team & Organization page text if the user is on the free tier:

![team-template](https://user-images.githubusercontent.com/39854876/197518079-d911a82f-48bf-41d2-9167-49111847256b.png)

### AC

- [ ] Design created that replaces "Your custom templates will..." text with text explaining that it's a premium feature
- [ ] There should be a link that takes the free user to the Billing page where they upgrade. Perhaps we should copy the existing format of hyperlinking text, i.e. replace `Public Template` with `Upgrade Now`, or perhaps we should have a CTA button?

**Comment by nickoferrall** [comment]
Suggested copy

![Screenshot 2022-11-02 at 13 57 45](https://user-images.githubusercontent.com/39854876/199508350-b6a818e5-3a3a-4c84-84dc-f7fe4d5d7879.png)

I suggest making `Upgrade to Pro` a hyperlink that takes the user to the Billing page

**Comment by acressall** [comment]
@nickoferrall I like the copy! Do you think we should also keep the bit that says "Your custom templates will show up here" at the beginning?

What would happen if I clicked on "Create New Template" here?

**Comment by nickoferrall** [comment]
> Do you think we should also keep the bit that says "Your custom templates will show up here" at the beginning?

Hmm maybe "Upgrade to Pro to create custom templates for your team. They'll show up here!"? If we start with "Your custom templates will show up here", I think we'd need to follow it with something like "if you upgrade to Pro!" which might sound sassy 😄 Personally, I like to keep the text as concise as possible to make it more likely users will read it

> What would happen if I clicked on "Create New Template" here?

This issue goes through this in more detail https://github.com/ParabolInc/parabol/issues/7330, but if they click "Create New Template" either an upgrade modal will pop up or we'll update the right-hand side of the template picker

**Comment by acressall** [comment]
>  I like to keep the text as concise as possible to make it more likely users will read it

Yep, that's fair. Let's just give Aviva and/or marketing a pass at it before we implement, but I agree with you here!

Once we have #7330 sorted this will be good to go

**Comment by nickoferrall** [comment]
Sounds good! @avivapinchas are you happy with the copy "Upgrade to Pro to create custom templates for your team [change "team" to "organization" on org page]"?
