### ISSUE TITLE
Add isFree to MeetingTemplate

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7334]
We want to make 7 public templates accessible to all users, while the remaining templates are available to only pro & enterprise users.

To do this, we should add an `isFree` field to the `MeetingTemplate` object. If `isFree` is not true, we know it's a premium template.

### AC

- [ ] Implement a migration that adds an `isFree` boolean to the `MeetingTemplate` object
- [ ] The [following 7 templates](https://www.notion.so/parabol/Template-limits-on-starter-plan-limited-number-and-or-limit-sharing-customization-e5231a1dcfa5450a99b2dc5c09480a0a#09585fd0b0c54ba08d5820adceb8741c) should have `isFree: true`

**Comment by tianrunhe** [comment]
Please remember to also update the [metrics](https://github.com/ParabolInc/parabol/blob/master/packages/server/utils/analytics/helpers.ts#L25)

**Comment by nickoferrall** [comment]
@tianrunhe I'm thinking we'll add `meetingTemplateIsPremium: template?.isPremium` to that object. How does that sound?
