### ISSUE TITLE
Add accessiblePremiumTemplateIds to RetrospectiveMeetingSettings

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7336]
We're limiting some public templates to Pro & Enterprise teams, but we don't want to take away templates that free teams have already used.

It would be a bad experience for a team to discover that they need to upgrade to access a template that they've been using for a while.

I suggest that we implement a migration that finds all the `MeetingTemplate`s that free teams have previously used (i.e. if the `lastUsedAt` is non-null) and add those ids to a new `accessiblePremiumTemplateIds` field that exists in `RetrospectiveMeetingSettings`.

The `isPremium` resolver in `MeetingTemplate` can then check whether the template id exists in `accessiblePremiumTemplateIds`. If it does, `isPremium` is false, and the user can continue to access the template.

### AC

- [ ] Add `accessiblePremiumTemplateIds` to the `RetrospectiveMeetingSettings` db & gql object
- [ ] Implement a migration that adds the template ids that free teams have previously used to the `accessiblePremiumTemplateIds` field

**Comment by Dschoordsch** [comment]
Do we also add custom template ids to `accessiblePremiumTemplateIds`?

**Comment by nickoferrall** [comment]
I don't think we need to as teams on the personal tier that have previously created custom templates will still be able to access them. We'd continue to get all the team templates [here](https://github.com/ParabolInc/parabol/blob/1b07e58347e807df76009f12b2cd32113eae033a/packages/server/graphql/types/RetrospectiveMeetingSettings.ts#L64-L66). If there are no team templates and the team is on the personal tier, the UI would show text explaining that custom templates are a premium feature (see https://github.com/ParabolInc/parabol/issues/7343)

**Comment by nickoferrall** [comment]
Hey @Dschoordsch, one problem I'm running into is checking whether a team has previously used a `MeetingTemplate`. Previously, I thought that I could filter by `teamId` & `orgId` in `MeetingTemplate`, but these are only relevant for custom templates. For public templates, we have `aGhostOrg` and `aGhostTeam` as the ids.

I don't want to get the previously used public `templateIds` by searching through all free teams' meeting history as it'd be too expensive.

So, I'm thinking that I could implement a migration that simply copies the `selectedTemplateId` to an `accessiblePremiumTemplateId` field.

Free users wouldn't have access to all of the premium templates that they've previously used, but they would always have access to the currently selected template id, which is the template they used in their previous meeting.

What do you think?

**Comment by nickoferrall** [comment]
I love that idea! By using that Redis query in the `isFree` resolver, we no longer need the `accessiblePremiumTemplateIds` field, can avoid the migration, and we can gradually remove premium templates from free users without (hopefully) upsetting them. Thanks!

**Comment by nickoferrall** [comment]
Decided to keep things simple and give the same experience to all free users, regardless of whether they've used a premium template before. We can build this is any users request it after we've shipped template limits.

See Slack thread for further context: https://parabol.slack.com/archives/C042E8PGPD4/p1667388355109689
