### ISSUE TITLE
Meeting scheduling within Parabol

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#7340]
**Tension**

There's currently no way for a team lead to schedule meetings easily. It's a manual process of setting up a Parabol meeting on the spot during the team's meeting time, or setting up a meeting and pasting the link into the calendar invitation. 

If a team runs retrospectives every 2 weeks, a team lead must go into the platform and set up another meeting manually. There's a lot of friction in that process.

**Potential solution**

I noticed that Google Meet has this nice little modal that pops up when you try to start a meeting. Could we design something similar for Parabol? 

![image](https://user-images.githubusercontent.com/15236825/197752728-49072723-46c3-45dc-9111-97d469cbde72.png)

In an ideal world, when clicking "schedule for later" a team lead would be able to:

- Set a date when their meeting takes place
- Then set recurrence (as a first step)
- Be prompted to integrate Parabol with their GCal or Outlook calendar to set up a recurring meeting with meeting links there (as a second step)

Most people organise their meetings through their calendar. That's the cultural norm in our societies.

Parabol is a meeting tool, but we don't integrate with any calendar tools. 

I believe setting recurrence for meetings and building them into peoples' calendars (where their meeting schedule lives) would make Parabol more user-friendly and more sticky. 

It would certainly reduce a lot of the busy work of calendar management for Scrum Masters, which is a tangible benefit we can speak to.

Note: There is already a Gcal integration issue here: #3345

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/84521201) 🔒 writes:

> I want to run our retros completely async (due to time zones) and I'd like to set up the meeting in advance.
> For example, I want to configure the meeting to run monthly on the first week of the month. I'd like to be able to set the
> following in advance (and recurring if possible)
>    - Start date and time
>    - Due date/time for icebreakers and reflections
>    - Due date/time for reflections (perhaps use AI to do this for me, or allow the meeting host to do this step to save time?)
>    - Due date/time for voting
>    - Due date/time for discussion 
>       - For this, it might be nice to have Phase 1 and Phase 2.
>       - Phase 1 is to write your initial thoughts, and phase 2 is to respond to what others have written.

**Comment by jordanh** [comment]
Now that recurrence is implemented for Stand-Ups, this should be a bit lower lift for us to implement if demand is high enough
