### ISSUE TITLE
Implement setIsFreeMeetingTemplate private mutation

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7341]
Predecessor: https://github.com/ParabolInc/parabol/issues/7334

Create a private mutation so that Growth team members can update the `isFree` field on templates. This will make templates accessible to all users or restrict them to paying users.

### AC

- [ ] Create a private mutation that updates `isFree` on `MeetingTemplate`
- [ ] The mutation could take the `templateId` as an argument and/or the template `name`

**Comment by Dschoordsch** [comment]
I think we shouldn't normalize any names and instead only check if these match exactly.
Instead of `togglePremiumTemplate` I would prefer `setPremiumTemplate` with an additional `isPremium: Boolean!` so the result doesn't change if the mutation is run multiple times.
