### ISSUE TITLE
Implement restrictions on public templates

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7344]
Predecessors https://github.com/ParabolInc/parabol/issues/7332 & https://github.com/ParabolInc/parabol/issues/7341 & https://github.com/ParabolInc/parabol/issues/7336

### AC

- [ ] Implement the design that comes out of https://github.com/ParabolInc/parabol/issues/7332
- [ ] If `MeetingTemplate.isPremium === true && tier === 'personal'`, the template shows the restricted UI
- [ ] If  `MeetingTemplate.isPremium === false`, show the free, publically accessible template UI
- [ ] If `MeetingTemplate.isPremium === true && tier !== 'personal'`, show the unlocked UI
- [ ] If a user clicks on the "Upgrade Now" CTA in the template picker, track the event in Segment
- [ ] Update the [selectTemplate](https://github.com/ParabolInc/parabol/blob/209eb714c484f074cedc92dddc3cb2fcb2960823/packages/server/graphql/mutations/selectTemplate.ts) mutation to check whether the user should have access to the template
- [ ] update the template ordering to take accessibility into account https://github.com/ParabolInc/parabol/blob/3545d153c1d0260f836646ce5c6a7beec79d7292/packages/server/graphql/queries/helpers/getPublicScoredTemplates.ts#L4

**Comment by Dschoordsch** [comment]
I came across the `isStarter` property in the templates and found it's only used for sorting. We should modify the sorting to punish locked templates, I added an AC.
