### ISSUE TITLE
Running health check retros 

### ISSUE THREAD

**Issue by ayo-yemi** [ParabolInc/parabol#7348]
## Issue - Enhancement

A[ user](https://app.hubspot.com/contacts/3888472/contact/49900201) 🔒 said: 
> Running health check retro: We are running quarterly health check retros following the Spotify model (https://engineering.atspotify.com/2014/09/squad-health-check-model/). We are currently using tools like Miro or Figjam for this. That would be great if we could have all the retro in one place and use Parabol.

Until we have acceptance criteria and estimated effort, we will keep this issue open and collect more feedback.

@jordanh @mwermuth

**Comment by mwermuth** [comment]
Looked at during backlog grooming. Going to icebox it.
