### ISSUE TITLE
Unable to import issues from Jira for Sprint Poker

### ISSUE THREAD

**Issue by dherman-eb** [ParabolInc/parabol#7353]
## Issue - Bug

- **How serious is the bug?** P0
- **OS:** All
- **Browser:** Chrome / Firefox / all others - latest

### Acceptance Criteria (optional)
Users can:
   - Do this: Import Jira issues into the scope - fails
   - After selecting Jira project, issues do not display (see screenshot)
   - Cannot do that: Actually, use the sprint poker since issues don't load
  
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** TBD

![image](https://user-images.githubusercontent.com/111456128/198145328-391eef7a-fb66-4b32-b702-1b39dd076a8c.png)

**Comment by Dschoordsch** [comment]
@dherman-eb I'm sorry you're having this issue. I tested it before with my account and it worked, so I tried reproducing it with a new one and I couldn't reproduce this issue: https://www.loom.com/share/8360017b7c3b4db6aceff4b8fcfad650

Could you help me with some more steps to reproduce this issue?
* Did you create a new meeting or opened an existing one?
* Did you add the Jira integration or was it one of your team mates?

**Comment by dherman-eb** [comment]
Hi Georg,

I created a new meeting and ran into the issue. I tried creating another
meeting and still had the same problem. I also tried disconnecting and
reconnecting to Jira, but that didn't work. I set up the Jira integration
with my cloud account.

Best,

Daniel

**Comment by acressall** [comment]
Additional users with this issue who have wrote in to support over the last 4 days
- [User 1](https://app.hubspot.com/contacts/3888472/contact/94976802) 🔒
- [User 2](https://app.hubspot.com/contacts/3888472/contact/77978051) 🔒
- [User 3](https://app.hubspot.com/contacts/3888472/contact/88575401) 🔒

**Comment by dherman-eb** [comment]
Thank you for the fix! Confirming the Jira integration is working as expected.
