### ISSUE TITLE
Recurrence: Enable recurrence when creating a new meeting

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7412]
Part of [#7410](https://github.com/ParabolInc/parabol/issues/7410)

→ [Figma explorations](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=0%3A1)

**Comment by enriquesanchez** [comment]
![imagen](https://user-images.githubusercontent.com/3276087/202780649-9226a69e-797a-48ba-8b26-97e8f0ca525b.png)
![imagen](https://user-images.githubusercontent.com/3276087/202781796-4ad9984d-d865-4ead-93de-06b7cbdf49b1.png)
![imagen](https://user-images.githubusercontent.com/3276087/202780494-d7cb37d9-d6df-4595-b641-256698b57a23.png)


→ [Figma source](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=162%3A16749&t=9oIuB2J89JlHnQQ9-4)


# Acceptance criteria

- Users can enable and configure recurrence from the meeting lobby. This includes:
  -  enabling recurrence
  - setting repeating schedule (Every X weeks/months)
  - setting days of week (M, T, W, T, F, S, S)
  - setting a start time (set to user's local timezone)
- Users are made aware via natural language of the settings:
  - Your standup meeting will repeat on Mondays, Wednesday and Fridays
    - On weekdays (Monday to Friday)
    - Every day (Monday through Sunday)
    - On Fridays every other week  
    - etc.
- The change is reflected in the dropdown label

**Comment by enriquesanchez** [comment]
@BartoszJarocki Let me know how this looks. 

One thing I'm wondering is if we need to define the natural language version of the schedule for every possible combination ("On Fridays every other week"), or if whatever library or framework we may use will handle this?

**Comment by BartoszJarocki** [comment]
@enriquesanchez looks good! and yes, we can have a human-readable version of recurrence rules for example:
```
every 5 weeks on Monday, Friday until January 31, 2013
```

last question, how does the select/input for `Each instance starts at` work? is it just an input or dropdown with predefined set of values?

**Comment by enriquesanchez** [comment]
>how does the select/input for Each instance starts at work? is it just an input or dropdown with predefined set of values?
 
That's the idea, yes. It's similar to how you pick a time in gCal:

<img width="200" alt="Captura de pantalla 2022-11-22 a la(s) 1 26 53 p m" src="https://user-images.githubusercontent.com/3276087/203404061-669a7fd6-a460-4477-a82d-8c26a3914961.png">

The pre-defined values can be 30-mins apart (9:00, 9:30, 10:00, 10:30, etc...).

How does that sounds to you @BartoszJarocki ?

**Comment by enriquesanchez** [comment]
@BartoszJarocki Let me know if this one feels ready for implementation

**Comment by BartoszJarocki** [comment]
Yes, I may have some questions about the input, but I'll leave that for later, looks good!
