### ISSUE TITLE
Remove templateLimit feature flag

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7413]
Before releasing the template limit restriction, we'll need to remove the feature flag. This will involve removing several viewer queries as we no longer need to check `featureFlags` in `makeTemplateDescription`, added in https://github.com/ParabolInc/parabol/pull/7405

### AC

- [ ] Remove template limit feature flag
- [ ] Remove viewer queries related to `makeTemplateDescription`

**Comment by jordanh** [comment]
@nickoferrall this one just went stale but it felt wrong just to icebox it as it seems like a decision needed to be made. Mentioning you here (and on Slack) so you can decide what to do

**Comment by nickoferrall** [comment]
Thanks! We're still testing this with a subset of users to assess its impact on usage. The test is almost complete, and the results are looking good so far, so once the test is done, I'll implement this issue
