### ISSUE TITLE
Recurrence: Update recurrence settings from inside the meeting

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7417]
Part of [#7410](https://github.com/ParabolInc/parabol/issues/7410)

→ [Figma explorations](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=0%3A1)

**Comment by enriquesanchez** [comment]
![imagen](https://user-images.githubusercontent.com/3276087/202810557-1d9a5d57-08d1-483c-b051-08f4dea2e1e7.png)
![imagen](https://user-images.githubusercontent.com/3276087/202811157-8c327c42-3b16-4481-9d75-2216a44f74a1.png)


→ [Figma source](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=164%3A16986&t=9oIuB2J89JlHnQQ9-4)


# Acceptance criteria
- Users can access a new menu option under the standup's more menu
  - If recurrence has not been set, the label will read "Enable recurrence"
  - If recurrence has already been set, the label will ready "Edit recurrence settings"
- If the option is selected, the same recurrence settings component used in the meeting lobby will be shown, but as a centered modal with a darkened background covering the rest of the page
- The modal will have a confirmation button, that can read "Save" or "Update", depending on the situation.

**Comment by enriquesanchez** [comment]
@BartoszJarocki Let me know how this one looks 👍

**Comment by BartoszJarocki** [comment]
Looks great! what about mobile view @enriquesanchez ?

**Comment by enriquesanchez** [comment]
>what about mobile view?

Thanks! On mobile the modal fits nicely in the center of the sceen, similar to how we handle the mobile view on #7412

![image](https://user-images.githubusercontent.com/3276087/204637224-9562ce60-97bc-487d-b2e2-3fb7360e810a.png)
