### ISSUE TITLE
Recurrence: See a confirmation after enabling recurrence from the meeting view

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7418]
Part of https://github.com/ParabolInc/parabol/issues/7410

→ [Figma explorations](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=0%3A1)

**Comment by enriquesanchez** [comment]
![imagen](https://user-images.githubusercontent.com/3276087/202811361-09e0dd74-5ae8-486a-8a3d-4e5e9afb000c.png)

→ [Figma source](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=164%3A26161&t=9oIuB2J89JlHnQQ9-4)

# Acceptance criteria:

- When recurrence is enabled, users will see a text label under the meeting title that described the current recurrence settings set for the activityy ("Recurs Monday, Wednesday and Friday")

**Comment by enriquesanchez** [comment]
@BartoszJarocki This one is also ready for you review

**Comment by enriquesanchez** [comment]
@BartoszJarocki also ready for your review

**Comment by BartoszJarocki** [comment]
👌
