### ISSUE TITLE
Recurrence: See information when the new meeting starts in the meeting view

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7420]
Part of https://github.com/ParabolInc/parabol/issues/7410

→ [Figma explorations](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=0%3A1)

**Comment by enriquesanchez** [comment]
![imagen](https://user-images.githubusercontent.com/3276087/202812134-5ad3b05d-7f67-40ae-be6e-7b7a7aa01d72.png)
![imagen](https://user-images.githubusercontent.com/3276087/202812317-3eaa5594-771d-481b-8bd3-be0d09c763a6.png)
![imagen](https://user-images.githubusercontent.com/3276087/202812329-8770a4aa-a36d-40af-b7f8-128b732ef31f.png)


→ [Figma source](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=164%3A30795&t=9oIuB2J89JlHnQQ9-4)

# Acceptance criteria

- Every recurring standup will have a time-left indicator at the top of the meeting view
  - This pill-shaped indicator will show how much time there is left before the activity ends (49 hours, 3 hours, 10 minutes, etc)
  - This time-left value also serves as an indicator of when the new instance starts

**Comment by enriquesanchez** [comment]
@BartoszJarocki I'm still a little unsure if this design covers all the cases you had in mind around start and end times. The way I see it, if I see that the standup has 3 hours left, that means the new one starts in 3 hours. I'm however not sure for activities that are not daily (for example a fridayhip) if the next instance starts right after the current one ends, or if there will be some gap time in between instances?

If that's the case, we can point that out:

![imagen](https://user-images.githubusercontent.com/3276087/202813548-d5109f65-25c3-45f6-85ed-166b810ad588.png)


Another edge case is if I happen to open a standup that already ended (or say I left my browser tab open and the standup expired before I look back at it again), we should point users to the current one, I think we could do it like this:

![imagen](https://user-images.githubusercontent.com/3276087/202813204-5456f629-20b1-4406-a08f-a02f356a2ec2.png)

**Comment by enriquesanchez** [comment]
![imagen](https://user-images.githubusercontent.com/3276087/202813548-d5109f65-25c3-45f6-85ed-166b810ad588.png)

→ [Figma source](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=165%3A40323&t=9oIuB2J89JlHnQQ9-4)

# Acceptance criteria

- If users open a standup activity that has already ended or expoired, and the next one is yet to start (for example, standups that are not daily, like a fridayship), they will see when the next activity starts next to the ended meeting notice

**Comment by BartoszJarocki** [comment]
👌
