### ISSUE TITLE
Implement usage stats for organizations without domain

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7422]
Currently, Usage Stats are shown only per each of the existing domains.

If a user has a gmail account and has created an organization, it is not possible to enable Usage Stats for the organization. 
Just nothing will be shown, as we iterating domains and show stats for the whole domain, [see here](https://github.com/ParabolInc/parabol/blob/f49d713260b7297a8f74dd79978cf3f58430d3e4/packages/client/components/Insights.tsx#L30)

<img width="727" alt="image" src="https://user-images.githubusercontent.com/466991/201229242-dcba32c4-8aea-4b17-b70f-d63afe77859d.png">

Ideally, it should be possible to view usage stats for organizations without active domain.

Possible solution is to include organization without domains in usage stats like:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/466991/201230128-7626b9b5-ffc7-4122-b5c9-e53c9ddc2b1c.png">

**Comment by jordanh** [comment]
Iceboxing!
