### ISSUE TITLE
JIRA Cloud auth seems broken

### ISSUE THREAD

**Issue by mwermuth** [ParabolInc/parabol#7430]
It seems like JIRA auth is broken and we can't add credentials to it.

For context: https://parabol.slack.com/archives/C4JAUUZ9P/p1668470700946019

**Comment by BartoszJarocki** [comment]
the error I'm getting locally and on production is the following
```
{
  "id": "12",
  "type": "complete",
  "payload": {
    "data": {
      "addAtlassianAuth": {
        "error": {
          "message": "Tenant is restricted: suspended-payment"
        },
        "teamMember": null
      }
    }
  }
}
```

**Comment by mwermuth** [comment]
Looks like this was only related to billing issues to our Jira project. We have to renew the subscription.
