### ISSUE TITLE
Add seasonal retrospective templates to the product

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#7434]
I've got a few more templates I'd like to add into the product:

---

**Holi retrospective**

**Colors**
_What color represents our recent work? Why?_

**Music** 
_Are we all dancing to the same rhythm? Where were we in sync? When did we fall out of sync?_

**Dance** 
_What big wins make us want to dance? What moves or actions should we try next?_

**Sweets** 
_Who deserves something sweet, kudos, or a word of thanks?_

---

**Easter retrospective**

**Easter eggs** 
_What was hidden from sight or caught you by surprise? What did you learn or find out?_

**Seeds** 
_What new processes would we like to cultivate? Is there something that faded away that we should bring back?_

**Hope** 
_What did you hope for? What are you hoping for next?_

**Chocolate**
_Who deserves some kudos or a word of thanks?_

---

**Midsummer retrospective**

**Wreaths** 
_What processes and practices are binding us together and making us stronger?_

**Schnapps**
_What’s been hard to swallow, admit, or realize about our work?_

**Longest day**
_What feels like it took too long or was never-ending?_

**Strawberry cake**
_Who deserves some kudos or a word of thanks?_

---

**Lunar new year retrospective**

**🧧 Hongbao** 
_Who deserves a red envelope with kudos and some words of appreciation?_ 

**🎊 Couplets** 
_What important messages should we remember for guidance?_

**🧨 Firecracker** 
_What caught us by surprise or gave us a fright?_

I would love to get @tianrunhe's feedback on the lunar new year retro before we put these into the product!

**Comment by tianrunhe** [comment]
Wooo I love a lunar new year theme template! My thoughts:
1. We stick with English translations for broader audience, so I'll replace "Hongbao" with "Red Envelope"
2. Lanterns are more of culture symbols for [Lantern Festival](https://en.wikipedia.org/wiki/Lantern_Festival) over Lunar new year. A more Lunar NY themed symbol would be [couplets](https://en.wikipedia.org/wiki/Antithetical_couplet). The prompt could be sth like "What should we hang up on our door as our guidance?". I'm not a good writer 😂 @garethaledavies come up with sth better than mine please

**Comment by garethaledavies** [comment]
> We stick with English translations for broader audience, so I'll replace "Hongbao" with "Red Envelope"

On this one I've decided to leave "Hongbao" because I think it encourages people to Google it. Like with the international languages in the check-in round, I think it helps people learn more about another culture. I added the words "red envelope" into the prompt text to clarify.

> A more Lunar NY themed symbol would be [couplets](https://en.wikipedia.org/wiki/Antithetical_couplet)

Brilliant, thank you! I've added this in. There wasn't a great emoji for this. If you have a better emoji option, please let me know! Otherwise I'll stick with the confetti streams.

Thank you for looking at this!

**Comment by garethaledavies** [comment]
Hi folks! I'm currently working with a writer to get template pages made for these 4 ideas. 

What can I do to help get these into the product before they get published in a couple of weeks?

**Comment by garethaledavies** [comment]
@nickoferrall Would you be able to help me get these added to the product? We're publishing online content about these currently and I'd love for the inside of the product to match what we talk about on the website!

**Comment by nickoferrall** [comment]
Sure thing @garethaledavies. Should these be premium templates for the users that are in our template A/B test?

**Comment by garethaledavies** [comment]
Yes, I think they should be premium templates :) Thank you for helping with
this.
