### ISSUE TITLE
Teams limit: Exclude organizations and domains with active deal in progress

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7436]
We need to exclude deals we're actively working from getting the time-bound trigger.

This information is available in HubSpot.

There are 2 possible approaches that I see:

1) Dynamically query HubSpot API to check if the organization or domain should be excluded.
2) Setup HubSpot webhook that will update some flag on organization accordingly, for example (`has_active_deal`)

Second option  seems to be better in terms of architecture, but I would suggest to pick something that would be faster to implement for now.

AC:
- [ ] Determine which approach for excluding organizations is better
- [ ] Do not trigger limit flow for organizations that are WIP by sales
- [ ] Do not trigger limit flow for organizations that are under a domain that is WIP by sales

**Comment by tghanken** [comment]
I wrote up a [guide](https://www.notion.so/parabol/How-to-identify-in-progress-deals-in-HubSpot-via-API-9563a8994dce44eda7ae0c691d376a5c) 🔒 for querying the HubSpot API to determine if a specific domain should be excluded.
