### ISSUE TITLE
Tier names changed to 'starter' and 'team' 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7437]
## Issue - Enhancement

We[ adopted a proposal](https://www.notion.so/parabol/Tier-Names-65ae94996c214b80992cde6c240db737) to change the names of our tiers: 
- `personal` will now be known as `starter` 
- `pro` will now be known as `team` 

### Acceptance Criteria (optional)
Users see the correct tier names everywhere in the interface. Including: 
- In the dropdown menu from the profile icon - `upgrade to pro` should change to `upgrade`
- In the `Organizations` screen, the `pro` label should change to `team`, and the `upgrade to pro` button should change to `upgrade` 
- The `pro` badge on invoices should change to `team` 
- On the `billing` pages, `upgrade to pro` in headlines should change to `upgrade` <- it may make sense to not do this, and instead wait till #6816, depending on level of effort 
- On the new template limits: when clicking 'create template', the right-hand prompt says 'upgrade to pro' prompt - should change to just 'upgrade'. 

<img width="697" alt="Screen Shot 2022-11-16 at 3 17 50 PM" src="https://user-images.githubusercontent.com/11621016/202286334-b0ef19e4-f687-4b77-ad21-17fff38aea82.png">

<img width="189" alt="Screen Shot 2022-11-16 at 3 17 21 PM" src="https://user-images.githubusercontent.com/11621016/202286321-cca3fcbb-a1f5-4ea0-afdd-e48d85aabd80.png">

<img width="596" alt="Screen Shot 2022-11-16 at 3 18 25 PM" src="https://user-images.githubusercontent.com/11621016/202286310-c225ff36-828e-4b58-bdf4-74035143235f.png">

<img width="292" alt="Screen Shot 2022-11-16 at 3 18 47 PM" src="https://user-images.githubusercontent.com/11621016/202286300-e59c01a7-2921-46e2-a5c4-abd052ad6dc0.png">

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
Please tag the data team for this so we can update our data warehouse too

**Comment by nickoferrall** [comment]
A few other places that we can update:

Pro badge in billing:
![pro](https://user-images.githubusercontent.com/39854876/202455347-9b554676-1434-4f36-a6c9-e5700b6aa1ec.png)

Pro badge in the org dropdown menu:
![org-badge](https://user-images.githubusercontent.com/39854876/202455407-2d8797a3-67b4-4658-b607-ee6e13f378c9.png)

Upgrade to Pro in the template restrictions:
![image](https://user-images.githubusercontent.com/39854876/202455621-273f546f-cbfa-40b4-aac6-10380200904e.png)

**Comment by jordanh** [comment]
Will Segment events be updated too, or will we continue using the legacy names?

**Comment by tianrunhe** [comment]
> Will Segment events be updated too, or will we continue using the legacy names?

Segment should be updated. I can collaborate with whoever pick up this issue. Although there might be a long migration period when both of the legacy & new names will be present.

**Comment by nickoferrall** [comment]
Hey @tianrunhe, how can I help with the segment events?

**Comment by tianrunhe** [comment]
> Hey @tianrunhe, how can I help with the segment events?

Your WIP PR looks pretty exhaustive and already covers a couple of places I was thinking. Tag me when it's ready!
