### ISSUE TITLE
Experiment started for Template Limits (WIP) 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7443]
## Issue - Enhancement

We want to understand whether template limits will encourage upgrades. 

### Acceptance Criteria (optional)
Experiment started: 
- Running over 6 weeks
- Approx. 500 teams should see the variation. 

We're assuming this timeframe will allow teams to see the prompt approx. 3 times on average. A risk is timing: we know the last 2 weeks of December and first week of January have significantly lower activity. We should monitor this to see how much folks did see the limit and adjust timing as appropriate. 

[Discussion here](https://parabol.slack.com/archives/C042E8PGPD4/p1668793266121179?thread_ts=1668715400.969029&cid=C042E8PGPD4) 🔒 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scubbed. Noting needs completed AC and EE

**Comment by avivapinchas** [comment]
@tghanken added deets from our convo - anything else you need from me here?

**Comment by tghanken** [comment]
@nickoferrall can you confirm `templateLimit` is the correct feature flag for this?  If so, I think we're good to go!

**Comment by nickoferrall** [comment]
@tghanken yep, `templateLimit` is the correct feature flag!

> I think we're good to go!

🥳 🥳 🥳

**Comment by tghanken** [comment]
Experiment launched, cohorts stored in `99_temp_squad_2_bofu.template_limit_cohorts`
