### ISSUE TITLE
Recurrence: Find your way to the current activity if the one you are looking at has expired

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7457]
Part of https://github.com/ParabolInc/parabol/issues/7410

→ [Figma explorations](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Recurrence?node-id=0%3A1)

**Comment by enriquesanchez** [comment]
This might be an edge case, but if I happen to open a standup that already ended (or say I left my browser tab open and the standup expired before I look back at it again), we should point users to the current one:

![imagen](https://user-images.githubusercontent.com/3276087/202813204-5456f629-20b1-4406-a08f-a02f356a2ec2.png)

# Acceptance criteria
- If a user opens an expired standup, and a new one is currently active, they should see a notice that the activity has ended and a link to the current standup

**Comment by enriquesanchez** [comment]
@BartoszJarocki also ready for your review 👍

**Comment by enriquesanchez** [comment]
@BartoszJarocki Let me know if this one feels read y for implementation

**Comment by BartoszJarocki** [comment]
yes looks good! not sure how I missed that, sorry!
