### ISSUE TITLE
Automatically calculate average value in Sprint Poker

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#7459]
Some users would like the average value automatically calculated in the estimate phase as the suggested value. I know I've heard this at least once before and another request came in recently from this [user](https://app.hubspot.com/contacts/3888472/contact/115996451) 🔒 : 

For our team, the mean value is very exciting. We have very experienced programmers and beginners. The average (in our experience) reflects a very real value, and it would be fantastic if we didn't have to calculate it.
Would it be possible to put this request on your parabol backlog list?

**Comment by jordanh** [comment]
I'd like something similar...rather than the average I'd like the mode. I'd personally like this to save from having to reach for the keyboard if we are _almost_ at consensus.
