### ISSUE TITLE
Error: NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is ...

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7463]
Error https://action.parabol.co/retrospective-demo/group

https://sentry.io/organizations/parabol/issues/1245488138/?referrer=github_plugin

```
Error: NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

140 events 14 users

**Comment by jordanh** [comment]
Looks Chrome Mobile-related, perhaps. First instance 3 years ago

**Comment by jordanh** [comment]
![image](https://github.com/ParabolInc/parabol/assets/103000/4db1e760-da06-49d3-afed-75136697da04)
