### ISSUE TITLE
TypeError: Load failed

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7464]
TypeError: https://action.parabol.co/meet/{...}/discuss/13

https://sentry.io/organizations/parabol/issues/2752872031/?referrer=github_plugin

```
TypeError: Load failed
```

69 events 18 users

**Comment by jordanh** [comment]
![image](https://github.com/ParabolInc/parabol/assets/103000/8a7eb7c2-2750-46f0-9866-b0caac11279a)

**Comment by jordanh** [comment]
Going to keep this one open

**Comment by mwermuth** [comment]
Still there, but only 4 times in the past 30 days. Going to close this for now.
