### ISSUE TITLE
Missing prompts on Starfish Retrospective

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#7466]
The Starfish retrospective template is missing prompts. I know this has happened before for SaMoLo and perhaps some others. It would be great to get a fix for this, but also to understand how/why this keeps happening.

Here's the template with missing prompts:

<img width="903" alt="Screenshot 2022-11-22 at 14 50 14" src="https://user-images.githubusercontent.com/15236825/203330807-09b46d0b-c7e8-4586-81fd-7aaf791b1efe.png">

Here are the prompts to add:

Keep Doing 🌀: What behaviors are working and adding value?
Less of ➖: What are we over-doing or doing too much of?
More of ➕: What are we not taking enough advantage of?
Stop ⏹️: What isn't adding value or helping the team?
Start ⏯️: What new things should we explore or add to our team?

**Comment by jordanh** [comment]
Wow. Super interesting. I agree with p2 label here. Let's figure this out
