### ISSUE TITLE
AI Summary: track relevant events

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7467]
To understand whether the AI summary feature has been used and is useful, we'll want to track relevant events. 

Speak with the data team to find out which events should be tracked and update the AC below.

### Proposed AC

- [ ] Track when the meeting summary has been viewed

**Comment by nickoferrall** [comment]
Hey @tghanken, are there any events that we should start tracking now for this feature?

**Comment by tghanken** [comment]
I'd like to track both views and engagement:

### Views
- Event: `Viewed AI Summary`
  - Property `source`: either `Meeting Summary` or `Discussion`
  - Property `tier`: user's tier, so we can track if the trial works
  - Property `meetingId`
 
### Engagement
I'm a little less certain of what we can/should track here.  Do we have any finalized designs yet?  I think at the bare minimum, we can track reactjis in the discussion, but maybe we could have a "learn more" CTA or other way for them to interact?  Regardless, we can use our existing tracking to see if this drives conversions, it'll just be hard to see if people find the actual feature useful without some kind of non-paid conversion action.
