### ISSUE TITLE
AI Summary: design: discussion thread includes summary of reflections

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7469]
In a retrospective meeting, the discussion thread includes a summary of the reflections added to that topic.

If Parabol is running on an air-gapped network, we won't reach out to the GPT-3 API. In that case, we won't show a summary in the discussion thread - we'll show the empty state that we currently have in production. 

### AC

- [ ] Design approved of a comment in the discussion thread that summarises the reflections in the topic

**Comment by jordanh** [comment]
Pls make sure design AC includes what happens when Parabol is running as a private instance, on an air-gapped network without access to GPT-3

**Comment by nickoferrall** [comment]
@jordanh issue description updated 👍

**Comment by nickoferrall** [comment]
Hey @acressall, how do you feel about this design as the GPT-3 generated summary in the discussion thread? When the user proceeds to a Discuss stage of a retro, they would see the summary of the reflections in that topic:

![ai-summary](https://user-images.githubusercontent.com/39854876/203626894-db41fdbe-9328-4ce8-a13c-57372d5d86e2.png)

The one thing I'd change from the image above is the user name would be `Parabol AI` instead of `Parabol`

**Comment by acressall** [comment]
Clarifying questions:

1. Is this shown automatically, or do I need to make it happen? What would that look like?
2. Should there be some kind of feedback option for free users? ie. "Was this helpful? Yes/No"
3. How many are the "first few retros"?
4. Can I see a discussion summary here too? Or only at the end/in the meeting summary?

**Comment by nickoferrall** [comment]
> Is this shown automatically, or do I need to make it happen? What would that look like?

It would happen automatically as the user proceeds to the DIscuss phase. They would arrive at the top votes Discussion topic and see the GPT-3 generated summary in the discussion thread

> Should there be some kind of feedback option for free users? ie. "Was this helpful? Yes/No"

Yep, completely agree - we've got this issue open to get live feedback: https://github.com/ParabolInc/parabol/issues/7474

> How many are the "first few retros"?

To be decided. We could run a couple of different tests, see Notion thread [here](https://www.notion.so/AI-summary-0db139fbccbe4a45a25c9b51437e4bda?d=b2d0b764f6bd4f2ab729a6cdad2dd85b#3d8837e325604e78913040b4c67b46a1)

> Can I see a discussion summary here too? Or only at the end/in the meeting summary?

You can only see the topic summary in the discussion thread as the discussion summary is the summary of the comments in the discussion thread. In the meeting summary at the end, you can see the whole meeting summary (all reflections + all comments), the topic summary (reflections in that topic), and the discussion summary (comments in the discussion thread for that topic).

**Comment by nickoferrall** [comment]
Hey @acressall, I've implemented this design, so I'll close the issue, but please let me know if there's anything you'd like me to change about the implementation. You can see the Loom demo here: https://www.loom.com/share/18ee9056101944d0b3affb9c9e6d1fd0
