### ISSUE TITLE
AI Summary: implement summary of discuss stage reflections in discussion thread

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7472]
Predecessor: https://github.com/ParabolInc/parabol/issues/7471

### AC

- [ ] In each Discuss stage of a retro, include the `topicSummary` as a comment from Parabol
- [ ] The comment should look like the design in https://github.com/ParabolInc/parabol/issues/7469
- [ ] Make the GPT-3 API keys an optional environment variable. If the key doesn't exist, don't show the `topicSummary` and show the discussion thread empty state instead. This way, if Parabol is running on an air-gapped network, we will not reach out to the GPT-3 API

**Comment by jordanh** [comment]
Please update AC to account for what happens when Parabol is running without access to Open AI/AI model provider. We must gracefully degrade

**Comment by nickoferrall** [comment]
@jordanh issue description updated 👍
