### ISSUE TITLE
AI Summary: invert feature flag

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7478]
If the A/B test (https://github.com/ParabolInc/parabol/issues/7475) has been successful, remove the feature flag.

### AC

- [ ] AI Summary feature flag has been removed
- [ ] Add feature flag to users who have opted out

**Comment by nickoferrall** [comment]
Hey @tghanken, where can I find a list of the users who have opted out? How do you think we should add them to the flag?

Perhaps the release owner would update the feature flags just after releasing to production?

**Comment by nickoferrall** [comment]
@tghanken I'm getting this error on that link:

![Screenshot 2023-03-30 at 19 40 35](https://user-images.githubusercontent.com/39854876/228933311-9785f05e-4fa2-48c6-9b3e-f85b1d0d6f3d.png)

**Comment by tghanken** [comment]
Can you try again? I tweaked IAM settings.
