### ISSUE TITLE
Recurrence stable link: display meeting series on the meeting dashboard

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7481]
Part of #7450 

>As a user, I want to see the meeting series card on the dashboard instead of a single meeting card (meetings tied to a meeting series should not be displayed separately on the dashboard)

**Comment by enriquesanchez** [comment]
![image](https://user-images.githubusercontent.com/3276087/206803774-f3af2573-aa7a-4597-8eb6-f1ec71948a16.png)

[Figma link](https://www.figma.com/file/azeQHaPX6yVsTHCq1aFPvK/Standups-Stable-Link?node-id=22%3A18896&t=UGVvGHEsxk0AplGE-4)

We are introducing collapsible sections in the meeting dashboard, to distinguish between recurring and non-recurring meetings: 
- The toggleable section should only appear when there are open meetings of its type (recurring and non-recurring)
- If there aren't any meeting for either section, then no collapsible sections are shown.

-----

<img width="1211" alt="Captura de pantalla 2022-12-09 a la(s) 4 12 17 p m" src="https://user-images.githubusercontent.com/3276087/206804047-76bc6dc1-f258-47d9-9c69-b435af5a9c5e.png">

- The meeting card for a recurring meeting will be shown as a stack of cards, showing a depth of 3 levels each rotated slightly to create the stacked effect.
- In addition to that, the label `Recurring` will appear next to the meeting type, in this case "Standups"

----

When collapsed, the number of meetings under each section will be shown in a badge next to the section toggle:

<img width="775" alt="Captura de pantalla 2022-12-09 a la(s) 4 16 11 p m" src="https://user-images.githubusercontent.com/3276087/206804584-019992ec-221c-470c-8af6-979724001ea7.png">

----

@BartoszJarocki @ackernaut requesting your review:
- Do you have any questions about this design?
- What aspects of this design do you like?
- Developer reviewer: are there any details missing that you need for implementation?
- Are there any details to the design that aren’t safe to try?

**Comment by ackernaut** [comment]
I like it. I left a couple of questions about the stack style and the recurring meta label in Figma.

**Comment by enriquesanchez** [comment]
Here's an updated version:

![image](https://user-images.githubusercontent.com/3276087/207719841-178354a2-1f08-4c8d-a255-64e827015ae4.png)
