### ISSUE TITLE
Recurrence stable link: navigate to other meetings in the series (and return to current instance)

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7482]
Part of #7450

> As a user, I want to be able to navigate to the previous meeting in the series.
> As a user, after navigating back to one of the past meeting in the series, I want to be able to go back to the next meeting in the series easily
> As a user, after navigating back to one of the past meeting in the series, I want to be able to go back to the current meeting easily

**Comment by enriquesanchez** [comment]
![image](https://user-images.githubusercontent.com/3276087/206805406-4d9020d1-ff96-4cad-8a07-bbe19b3a6811.png)

[Figma link](https://www.figma.com/file/azeQHaPX6yVsTHCq1aFPvK/Standups-Stable-Link?node-id=94%3A15793&t=UGVvGHEsxk0AplGE-4)

We are introducing a new component to navigate between meeting instances of a recurring meeting. This component is made up of 3 elements:

- a calendar icon that opens a calendar widget
- a back button to navigate back to the previous instance (if any)
- a forward button to navigate forward to the next instance (if any)

Some considerations:

- the calendar should display in bold the dates of the days where an instance exist. Days with no instance in them should appear disabled
- The back and forward arrows should only appear active if there are instance to go back or forward to. If there aren't any, then the buttons should appear disabled

In addition, when navigating back to a past instance, the meeting status pill should show a link to easily get back to the current instance:

<img width="459" alt="Captura de pantalla 2022-12-09 a la(s) 4 28 27 p m" src="https://user-images.githubusercontent.com/3276087/206805926-8d846da6-3404-4012-b8cc-bbaf131c53eb.png">



----

@BartoszJarocki @ackernaut requesting your review:
- Do you have any questions about this design?
- What aspects of this design do you like?
- Developer reviewer: are there any details missing that you need for implementation?
- Are there any details to the design that aren’t safe to try?

**Comment by ackernaut** [comment]
I think you got to a very elegant solution here. No questions or comments!
