### ISSUE TITLE
Recurrence stable link: see ended meeting series

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7483]
Part of #7450

> As a user, I want to see an ended meeting series

**Comment by enriquesanchez** [comment]
![image](https://user-images.githubusercontent.com/3276087/206806273-529955ef-4968-417a-9869-67aeb9897b9c.png)


[Figma link](https://www.figma.com/file/azeQHaPX6yVsTHCq1aFPvK/Standups-Stable-Link?node-id=22%3A19879&t=UGVvGHEsxk0AplGE-4)

When a meeting series has ended, we specify this status both under the meeting title and on the status pill.

- users are still able to browse and review the contents of the meetings, and interact with comment threads and reactions
- users are still able to navigate back and forward to the various instances of the series, via the calendar and arrows component
- Invitations should not be available for a series that has ended (note the lack of the invite button on the top-right corner)


----

@BartoszJarocki @ackernaut requesting your review:

- Do you have any questions about this design?
- What aspects of this design do you like?
- Developer reviewer: are there any details missing that you need for implementation?
- Are there any details to the design that aren’t safe to try?

**Comment by ackernaut** [comment]
Dropped a question in Figma!
