### ISSUE TITLE
Recurrence stable link: see a no active meetings view if the meeting series is active, but there are no active meetings

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7484]
Part of #7450 

> As a user, I want to see a no active meetings view if the meeting series is active, but there are no active meetings (could happen when the user ends the meeting manually and the new meeting wasn't yet created by Parabol)

**Comment by enriquesanchez** [comment]
![image](https://user-images.githubusercontent.com/3276087/206807144-dfeafd2c-b014-4239-8701-77c2ff7ee571.png)


[Figma link](https://www.figma.com/file/azeQHaPX6yVsTHCq1aFPvK/Standups-Stable-Link?node-id=61%3A12812&t=UGVvGHEsxk0AplGE-4)

When users open a meeting with no current active meetings, we show an "empty state" that describes this status and helps the user understand what is going on:

- The description text should include information of when the next meeting restarts, and a link to the previous instance
- In addition they have the option to browse instances with the calendar and arrows component

----

@BartoszJarocki @ackernaut requesting your review:

- Do you have any questions about this design?
- What aspects of this design do you like?
- Developer reviewer: are there any details missing that you need for implementation?
- Are there any details to the design that aren’t safe to try?

**Comment by ackernaut** [comment]
Left questions and comments in Figma!

**Comment by enriquesanchez** [comment]
Adjusted for mobile views:

![image](https://user-images.githubusercontent.com/3276087/207664701-1585da1d-e754-40ba-8cad-df642bd5bdfe.png)
