### ISSUE TITLE
Staggered roll-out for Meeting History Limit

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7502]
## Issue - Enhancement

Epic here: #7375

Since this is a new limit, we want to test this feature to determine if we see an impact, and hear concerns early before full release. 

[Discussion here](https://parabol.slack.com/archives/C042E8PGPD4/p1668540172077129) 🔒 

### Acceptance Criteria (optional)
Roll-out should be: 
- First release: 50% of users should see the varition. If there's no meaningful negative feedback within 2 weeks (accounting for seasonal factors), then we release to 100% of users. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tghanken** [comment]
No negative results from the feature test.  Rolling out globally this week.

**Comment by Dschoordsch** [comment]
@tghanken this is done, isn't it?
