### ISSUE TITLE
Jira integration broken when ip whitelisting is enabled

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#7503]
## Issue - Bug
When a user is trying to integrate with Jira where IP whitelisting is enabled, the integration flow continues through as designed, but doesn't showed "Connected". When this happens if you go to a card in the task list, and click the integration arrow, click integrate with Jira here and follow the process, you get a warning about the IP whitelist.

![image](https://user-images.githubusercontent.com/71724289/204664599-80dfdbfb-b753-4ba4-bcd4-5e744478f869.png)

We need to bubble this error at the integration page vs just showing the connect button. There is no indication there is a problem with IP whitelist except for this portion of the app integration.

- **How serious is the bug?** P3
- **OS:** All OS
- **Browser:**All browsers

**Comment by adaniels-parabol** [comment]
We should also include in the request, the server IP they need to add.

**Comment by adaniels-parabol** [comment]
Sentry log shows ```
SEND TO SENTRY Error: The IP address has been rejected because it is not on the allowedlist. See your admin for more information.
    at Object.resolve [as MutationaddAtlassianAuthResolver] (/parabol/dist/gqlExecutor.js:1:229435)
```

**Comment by mattkrick** [comment]
what version was this? it might be fixed by https://github.com/ParabolInc/parabol/pull/7432

**Comment by adaniels-parabol** [comment]
Parabol version is 6.82.0. We added the IP to https://admin.atlassian.com/ > Security > IP Whitelist of the requesting server to solve the issue, but we just didn't get a good error on the integrations page only on the card itself is where we got the error.

**Comment by adaniels-parabol** [comment]
TL/DR: friendly error when doing the integration from a card, but on the integration page, no error.

**Comment by mattkrick** [comment]
fixed in 6.83.0
