### ISSUE TITLE
Private instance user cannot push story points to Jira 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7512]
On a setup call with a [PPMI user](https://app.hubspot.com/contacts/3888472/company/7164993656) 🔒 and @adaniels-parabol, a customer could not get story points in Poker to show up as story points in Jira. They only showed as comments. I know we fixed a similar issue for our public SaaS users, I wonder if this is just a PPMI issue? 

Here is the similar issue we solved for public SaaS users: https://github.com/ParabolInc/parabol/issues/6589#issuecomment-1290628807

**Comment by adaniels-parabol** [comment]
@drewhousman1010 I believe it's because they haven't followed this guide that it ended up in the comments

https://www.parabol.co/support/estimation-in-jira-company/
https://www.parabol.co/support/estimation-in-jira-team/

**Comment by drewhousman1010** [comment]
Ah okay, thanks @adaniels-parabol. So is it enough for me to send those links to the user? is there anything else I need to do? If I all need to do is send those then we can close this issue :)

**Comment by jordanh** [comment]
I am going to label this is a customer support issue vs. a bug until it has been verified that something is broken on our side. Please make sure to correspond with the CS Lead to get the help you need in resolving this. Let @mwermuth know if you run into any headwinds

**Comment by jordanh** [comment]
@drewhousman1010 has this one been resolved?
