### ISSUE TITLE
Teams limit: send warning email when the limit is exceeded

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7518]
Prev issue: #7379

Designs TBD

AC:
- [ ] Send a warning email to all organization billing leaders, saying that the tier limit was exceeded and account will be blocked in 30 days

**Comment by igorlesnenko** [comment]
Worth checking notification preview functionality: https://github.com/ParabolInc/parabol/pull/7563#pullrequestreview-1218409335 
Maybe it could be used for this email notification

**Comment by acressall** [comment]
@avivapinchas can you proofread the copy for these emails? @igorlesnenko I have three emails here -- are we missing any use cases? https://docs.google.com/document/d/1XUGU2Ozhdapc4dSA2raNbi6gA0FexxUJRw2xlQQcxNM/edit?usp=sharing

**Comment by avivapinchas** [comment]
I've made some non-trivial edits here. I wanted to: 
- Share more info, if possible, to make the scenarios more clear - @igorlesnenko lmk if we aren't able to pull in Org name and Number of teams 
- Make the emails more different from one another, increase the urgency with each email, and focus on loss aversion (don't lose something you're used to) as the main persuasive tool 

LMK if this isn't what you had in mind!
