### ISSUE TITLE
Standups: multiple hyperlinks in the same update point to one URL

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7524]
If there are several hyperlinks in one standup update and you click them in quick succession, they can all direct you to one URL rather than several different URLs.

See Loom demo: https://www.loom.com/share/393d3263ae554e10ab5bf0f8bbc8ccb5

### AC

- [ ] Hyperlinks open to the URL that the author intended

**Comment by jmtaber129** [comment]
This is a bug with the tiptap library - when the tiptap editor's selection is one link and the user clicks on a different link, tiptap will handle the click by opening the selected link instead of the link the user clicked on.

I'll look into PR-ing a fix into the TipTap lib
