### ISSUE TITLE
Checkout Flow: credit card UI

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7530]
Figma designs [here](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?t=p3f7trldNdOyScXZ-0)

<img width="623" alt="credit-card-ui" src="https://user-images.githubusercontent.com/39854876/215596345-59e7d328-8497-4f6a-9c7b-4729cf05607b.png">

### AC

- [ ] Implement the UI for the credit card section of the checkout flow
- [ ] The billing section text is hardcoded. We'll make it dynamic here: https://github.com/ParabolInc/parabol/issues/7693

**Comment by nickoferrall** [comment]
Hey @acressall, are you thinking the heading "Your first payment..." would only show for new users, and then everyone else would just see "Your next payment is due on..."? 

I lean towards just saying, "Your next payment is due on..." for all users to keep things simple and consistent. WDYT?

Also, do you have any designs for an error state? If the user enters incorrect card details, where would we should "Invalid CVC" text, for example?

**Comment by acressall** [comment]
I'm ok with the consistent language you proposed! [Here's the error state design](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=474%3A4319&t=f1ZxoeQjHE2AkLLA-4). Do we have content from the existing form we can use, or do we need some?

**Comment by nickoferrall** [comment]
> [Here's the error state design](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=474%3A4319&t=f1ZxoeQjHE2AkLLA-4).

Thanks!

> Do we have content from the existing form we can use, or do we need some?

Yeah, atm, in the credit card model we have errors that say "invalid CVV" or "invalid credit card". 

![Screenshot 2023-02-23 at 12 44 17](https://user-images.githubusercontent.com/39854876/220909452-0fd38eaa-29d3-4f7b-8768-1ee7814ff8b4.png)

I guess I could make the error state look like your design and replace the "Woops! Something looks off" with "Invalid CVV"? Or maybe "Woops! That's an invalid CVV"

**Comment by acressall** [comment]
> I guess I could make the error state look like your design and replace the "Woops! Something looks off" with "Invalid CVV"?

Yes, that's good! I just threw in some dummy copy, so don't worry about pulling in any of that

**Comment by nickoferrall** [comment]
One more question @acressall: do we need the credit card name input? In production, we're not requesting the card name. I'm wondering if we want to collect it to improve our credit card acceptance rate?

If not, perhaps we can remove it to save users time and keep it as concise as possible?

**Comment by nickoferrall** [comment]
@acressall as I start work on the credit card functionality, I realise that the heading saying, "Your first payment...", is only visible in the UI where the user hasn't entered their card info, so Starter tier users.

This means they don't have a first or next payment date. I think the first payment date is always the date that they enter their card details anyway?

![heading](https://user-images.githubusercontent.com/39854876/221151793-84e1c402-f434-4671-9b3b-7b8d3faae35f.png)


For users that have upgraded, we show them the credit card details, but we don't say "Your first payment...":

![Screenshot 2023-02-24 at 10 11 02](https://user-images.githubusercontent.com/39854876/221152242-2eeee8b0-93f5-46e5-9ff2-ed00871289d4.png)


Perhaps we can remove the heading "Your first payment..."?

**Comment by acressall** [comment]
> do we need the credit card name input? In production, we're not requesting the card name. I'm wondering if we want to collect it to improve our credit card acceptance rate?
If not, perhaps we can remove it to save users time and keep it as concise as possible?

I'm ok with leaving it out! If it's not required, let's skip it

>  I realise that the heading saying, "Your first payment...", is only visible in the UI where the user hasn't entered their card info, so Starter tier users.
This means they don't have a first or next payment date. I think the first payment date is always the date that they enter their card details anyway?

Yes, that's right. I do like giving an expectation for when they will be paying. Right now, we don't have any confirmation or sense of when things happen. If you're ok with including it for the upgraded users as well, I think that would be ideal.

**Comment by nickoferrall** [comment]
> Yes, that's right. I do like giving an expectation for when they will be paying. Right now, we don't have any confirmation or sense of when things happen. If you're ok with including it for the upgraded users as well, I think that would be ideal.

Ah I was suggesting we remove it for Starter users, if that works for you?

For Team & Enterprise users, I'm happy to include it, but I'm wondering where to add that sentence? Perhaps in the Invoices panel?

![Screenshot 2023-02-24 at 17 47 29](https://user-images.githubusercontent.com/39854876/221252029-d41eb1bd-e973-48ff-8dd7-d0f2571df141.png)

**Comment by acressall** [comment]
Ahh ok. Thanks for the screenshot -- I forgot we essentially include it in the upcoming "estimate" on the invoices panel. 

> Ah I was suggesting we remove it for Starter users, if that works for you?

Would it be ok to keep it for starter users, as it is in the design? We don't send them a confirmation email on payment, so there's no indication that they've been charged _immediately_.

**Comment by nickoferrall** [comment]
> Would it be ok to keep it for starter users, as it is in the design? We don't send them a confirmation email on payment, so there's no indication that they've been charged immediately.

@acressall sure thing. So would you like it to say: "Your first payment will be ${todaysDate}"? 

IMO, as a user, I'd always assume the payment is immediate so the message would seem redundant. Perhaps the better UX would be adding a payment confirmation email? 

We could send the Stripe confirmation email rather than designing and building a custom email?

The email would look like this:

![Screenshot 2023-02-27 at 18 46 55](https://user-images.githubusercontent.com/39854876/221655059-45554ba9-1074-46cb-a410-79e2502c09c9.png)

**Comment by acressall** [comment]
Oooh I didn't know we could do this! Yes, if it's easy enough to send this email this is definitely the ideal. 

> So would you like it to say: "Your first payment will be ${todaysDate}"?

If we're able to send the confirmation email, let's make the text "Your next payment will be on [one month from today]."

FYI @avivapinchas 👆 payment confirmation emails!!

**Comment by nickoferrall** [comment]
> Oooh I didn't know we could do this! Yes, if it's easy enough to send this email this is definitely the ideal.

Sounds good! I'll create an issue. I don't know how hard it'll be, but I suspect not _that_ hard

> "Your next payment will be on [one month from today]."

I'm talking about the Starter view, so their next payment would be today, as they haven't yet completed the credit card form. Would it be OK to remove that sentence if we're able to add a confirmation email? 

![image](https://user-images.githubusercontent.com/39854876/222458595-9143796c-430f-4546-8b80-3f43847a0157.png)

**Comment by acressall** [comment]
Ahhh okay, I see what you mean. Yes, let's remove it from the initial view

**Comment by nickoferrall** [comment]
Sounds good 👍 

I've created an issue here: https://github.com/ParabolInc/parabol/issues/7851

I moved it (and one other issues) to a separate v2 Checkout Flow milestone so the original milestone accurately indicates when we can ship the feature to all users

**Comment by avivapinchas** [comment]
Very excited about sending that confirmation email!
