### ISSUE TITLE
Add ability to turn on feature flag for multiple domains at once

### ISSUE THREAD

**Issue by tghanken** [ParabolInc/parabol#7539]
## Issue - Enhancement

Right now, the `addFeatureFlag` [mutation](https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/public/typeDefs/addFeatureFlag.graphql#L33:L49) accepts either a list of emails or a single domain.  As we are starting to use more feature flags for testing and staggered rollouts, it would be a time saver if we could also submit a list of domains.

### Possible solutions
- Add a new query (ie. getUsersByDomains) to support getting users for multiple domains and add it to the `addFeatureFlag` mutation.  This would allow `getUsersByDomain` to strictly guarantee returning users for a single domain.
- Change the existing [getUsersByDomain](https://github.com/ParabolInc/parabol/blob/master/packages/server/postgres/queries/getUsersByDomain.ts) query to support a domain list parameter.  I prefer this approach even though it touches more locations, unless we need the single domain guarantee elsewhere in the codebase.

### Acceptance Criteria (optional)
Users can:
   - Submit a list of domains to enable a feature flag

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
@tghanken Is this something you're working on?

**Comment by mwermuth** [comment]
Looked at during backlog grooming. Going to icebox it.
