### ISSUE TITLE
Staggered roll-out for teams limit

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7550]
**Issue - Enhancement**
Epic here: https://github.com/ParabolInc/parabol/issues/7370

This is an enforcement of an existing limit, and we are committed to continuing down this path. We need to see if there are any significant negative impacts, and intent to evolve the enforcement rather than revert the changes. 

**Acceptance Criteria (optional)**

Roll-out should be:

- Roll out to 50% of qualified users, for at least 45 days. Then: we decide if enough folks have seen the prompts to make a decision on a broader release. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by nickoferrall** [comment]
This has happened 🎉  closing the issue
