### ISSUE TITLE
Organization Nav Design

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7553]
Designed the new navigation for the organization view. 

AC:

- [ ] Views for all tabs
- [ ] Collapsed/mobile view
- [ ] Breadcrumbs

**Comment by acressall** [comment]
First pass at nav UI & breadrumbs https://www.loom.com/share/9cc313c2ab504409853ce9d6285d9f90

**Comment by acressall** [comment]
@nickoferrall could you review the nav design and let me know if you have any questions about functionality?

@ackernaut the nav format is largely taken from your previous work, so I'm hoping all will be good on that front. Could you focus the review on the tab views? My main question: is there any objection or concern about starting with just existing content for these views, even if that means they might be a little sparse?

Navigation & views for existing tabs:

![Image](https://user-images.githubusercontent.com/18582225/207361696-8a47d290-213c-4f04-be4d-6472ac109bd0.png)
![Image](https://user-images.githubusercontent.com/18582225/207361697-00271fab-c157-4a2c-90cf-48357b15b52e.png)
![Image](https://user-images.githubusercontent.com/18582225/207361695-63a283f0-af88-45c0-affa-fbe4355f146a.png)
![Image](https://user-images.githubusercontent.com/18582225/207361698-8bbdaeda-312d-4bf4-bb57-32cccaf2d126.png)
![Image](https://user-images.githubusercontent.com/18582225/207361700-6aa0e372-d198-4521-bc2a-b19b19d5d466.png)
![Image](https://user-images.githubusercontent.com/18582225/207361699-a8ca007a-5df2-4010-81d6-535cb11098b4.png)

Mobile nav:

![Image](https://user-images.githubusercontent.com/18582225/207361818-484e807d-5cdf-45c3-96b8-2999ee8539bc.png)
![Image](https://user-images.githubusercontent.com/18582225/207361817-bb9e27b3-410b-4ec3-8ec8-8e34ba7ded10.png)
![Image](https://user-images.githubusercontent.com/18582225/207361819-7444c21c-7343-4577-b66c-05506bc3c8ae.png)

Mobile nav prototype: https://www.figma.com/proto/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=165%3A4221&scaling=scale-down&page-id=161%3A1713&starting-point-node-id=165%3A4221

Figma: https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=161%3A1713

**Comment by ackernaut** [comment]
@acressall nice work! I left a few small questions, details — nothing big. Ready for you to move forward!

**Comment by nickoferrall** [comment]
The functionality looks good to me! Added two comments to the Figma file
