### ISSUE TITLE
Show the version in the boot message of all commands

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#7557]
## Issue - Enhancement

Today the boot message for the Web Server and the GraphQL Executor are:
- Web Server: 🔥🔥🔥 Server ID: ID. Ready for Sockets: Port PORT 🔥🔥🔥
- GraphQL Executor: 💧💧💧 Server ID: ID. Ready for GraphQL Execution 💧💧💧 

The version should be also printed there. Proposed:
- Web Server: 🔥🔥🔥 Parabol version: VERSION. Server ID: ID. Ready for Sockets: Port PORT 🔥🔥🔥
- GraphQL Executor: 💧💧💧Parabol version: VERSION.  Server ID: ID. Ready for GraphQL Execution 💧💧💧 

It will show that you are running Parabol, the server ID and which type of component it is. The version should also be added to any command running the application (migrations, post-deploy...)

### Acceptance Criteria 

- [ ] Web Server shows the version.
- [ ] GraphQL Executor shows the version.
- [ ] Database migrations shows the version.
- [ ] Post Deploy shows the version.
- [ ] The rest of the components show the version.

**Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
Could we also include the commit hash?

**Comment by rafaelromcar-parabol** [comment]
@Dschoordsch We could, but at least having the version would already be great. I would implement a version first showing the version and then iterate to add anything else.

How would you pass the commit hash to the application? I understand that the application is aware of its own version, but the commit hash isn't stored into any application code or configuration file.

**Comment by mattkrick** [comment]
This would've been very useful for debugging a recent problem with KR. 
I added the version + git hash to the predeploy script only.
That way if we can't see the version number in the customer's logs, we can assume that they didn't run predeploy 🙃 .
