### ISSUE TITLE
Redis connection using in-transit encryption

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#7564]
## Issue - Enhancement

The application should be able to connect to Redis using in-transit encryption.

### Acceptance Criteria (optional)

- [ ] Web Server can use in-transit encryption to communicate with Redis.
- [ ] GraphQL Executor can use in-transit encryption to communicate with Redis.
- [ ] Database migrations can use in-transit encryption to communicate with Redis.
- [ ] Any other component/command can use in-transit encryption to communicate with Redis.
- [ ] Documentation: there is a howto configure and use in-transit encryption to communicate with Redis.

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
Does this issue include the DNS issue, i.e. names are not resolved again before attempting to reconnect?

**Comment by rafaelromcar-parabol** [comment]
@Dschoordsch it did, but as we talked on Slack, I agree that those are two different issues.

This issue requires, if we want to deploy the application, secured, in GCP using Memorystore the backoff retry feature. But we should create another issue for that.

**Comment by rafaelromcar-parabol** [comment]
The issue [Re-connection to databases: retry and DNS refresh](https://github.com/ParabolInc/parabol/issues/7570) is a requirement for this to work correctly, as certificates are rotated quite often in [GCP Memorystore Redis](https://cloud.google.com/memorystore/docs/redis/about-in-transit-encryption).

**Comment by rafaelromcar-parabol** [comment]
[ioredis library allows to connect using TLS](https://github.com/luin/ioredis#tls-options). Do you think this would be an easy issue to do @mattkrick @Dschoordsch ?

This isn't a blocker, but it is clearly a good practice to connect through TLS to our databases. We already have it for PostgreSQL and we would like to use it in all of our databases when we migrate to GCP.
