### ISSUE TITLE
Unable to share a template in an org

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7566]
@jordanh shared in [Slack](https://parabol.slack.com/archives/C4JAUUZ9P/p1670874591652199) 🔒  that he wasn't able to share a Team template in his org.

It looks like this was a one-off incident as I am able to share templates publically, so it may be related to that template specifically.

@tianrunhe [noted](https://parabol.slack.com/archives/C4JAUUZ9P/p1670952512731189?thread_ts=1670874591.652199&cid=C4JAUUZ9P) that `isActive` is false for that template.

### AC

- [ ] Find out why the template (`templateId` included in Slack thread) was not able to be shared with the org

**Comment by jmtaber129** [comment]
Bumping this down to P3 because this seems to be limited in the cases when templates can't be shared - you can still generally share templates, and it seems like no one's successfully reproduced the issue demonstrated in the loom.
