### ISSUE TITLE
Arrow icons not showing up on task calendar

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7586]
@rafaelromcar-parabol shared in [Slack](https://parabol.slack.com/archives/C4JAUUZ9P/p1671186349709149) that the arrows to change the due date of a task aren't showing up

### AC

- [ ] Arrows and text show up as expected

**Comment by rafaelromcar-parabol** [comment]
In some cases there is a text shown, that you can click to change the date:
![Screenshot from 2022-12-16 10-25-07](https://user-images.githubusercontent.com/101704572/208086858-efeaa374-5d1c-4718-81d1-d0c360a7ee17.png)

In others, there is no text at all and you cannot modify the date:
![Screenshot from 2022-12-16 10-27-40](https://user-images.githubusercontent.com/101704572/208086863-ab84f526-fa21-4c6a-92ea-4485d326cb10.png)

**Comment by nickoferrall** [comment]
Fixed here https://github.com/ParabolInc/parabol/pull/7521
