### ISSUE TITLE
A/B Testing: Create a mutation to remove a feature flag

### ISSUE THREAD

**Issue by tghanken** [ParabolInc/parabol#7590]
## Issue - Enhancement

Currently, there is only an `addFeatureFlag` mutation that we expose in GraphQL.  With our move towards using feature flags more frequently in product testing, we should add a `removeFeatureFlag` mutation that allows us to easily remove user feature flags without needing to make direct db changes.

### Acceptance Criteria (optional)
Superusers can:
   - Use the private `removeFeatureFlag` mutation to remove users
   - Provide either a list of users or a list of domains to remove the feature flag for
   - Specify which feature flag is being removed

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
We now have `updateFeatureFlag(..., addFlag: false)` which will remove a feature flag.
