### ISSUE TITLE
Sprint poker not revealing votes

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7602]
A non-paying [user](https://app.hubspot.com/contacts/3888472/contact/13344751) 🔒  writes:

> I've noticed a couple of times over the last month or two that sometimes the "Reveal Votes" button in Sprint Poker doesn't seem to take any action when clicked. It hasn't happened consistently, but it started around early November and the last time this happened for us was on Dec. 14 from 11:00 AM-12:00 PM ET. Clearing cache and relaunching the experience doesn't seem to help. Is there anything else I can try when this happens?

**Comment by wochinge** [comment]
Same for us 🙌🏻

**Comment by jordanh** [comment]
We should most definitely look into this. @wochinge and @mathislucka, are you able to reproduce this issue reliably? When next it happens for you, would you be willing to write a comment here sharing a link to the Poker activity where it occured?

**Comment by jordanh** [comment]
We haven't heard more instances of this. Perhaps our relay update fixed this? Unclear. Will close for now and reopen if we hear of another instance of this behavior

**Comment by wochinge** [comment]
yeah, sorry, we weren't able to reproduce this anymore . Thanks for your help 🙌🏻
