### ISSUE TITLE
User tier discrepancy between User table & OrgUser table

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#7624]
The issue seems to only happen between starter/personal and enterprise. No pro/team tiers are found with issues at time of writing. I'm seeing a couple of hundreds of this kind of discrepancies.

Examples:

`google-oauth2|dGEA9unISQ`: tier is `starter` in User table. However the user is actively in an `enterprise` org:

<img width="611" alt="Screenshot 2023-01-05 at 2 12 04 PM" src="https://user-images.githubusercontent.com/1879975/210890166-98d4347b-b636-444c-81d8-77442eb29303.png">

`sso|iTAv6Q7SSc`: tier is `enterprise` in User table. However the user is only actively in an `starter` org:

<img width="612" alt="Screenshot 2023-01-05 at 2 14 45 PM" src="https://user-images.githubusercontent.com/1879975/210890505-cb576c51-e934-4d8a-9763-26d662e21101.png">

### Acceptance Criteria (optional)
- [ ] Figure out if there's any edge cases when users are upgraded/downgraded, tiers are not updated correctly
- [ ] Backfill the `tier` column in User table with correctly computed value from OrgUser table

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tianrunhe** [comment]
Stil an issue

**Comment by jordanh** [comment]
We should figure this out before (or as we) migrate to PG

**Comment by rafaelromcar-parabol** [comment]
@mattkrick this is probably important for you to know for the next RethinkDB to Postgres migrations

**Comment by Dschoordsch** [comment]
Superseeded by #9932
