### ISSUE TITLE
SAML UI: Allow enterprise customers to self setup SAML

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7641]
Previous work :
* #6811
* #6951

Until now SAML can only be set up manually by us and often requires a lot of back and forth with the customer. To solve this they should be able to set up SAML themselves. Because SAML is associated with an email domain, the customer needs to verify the domain is under their control. For the beginning, this will be done manually by us. So instead of `enableSAMLForDomain` we will need to call `verifyDomain` for the customer to be able to do the rest of the setup on their own.

Steps:
* [x] #7642 
* [x] #7643 
* [x] #7661 
* [x] #7662
* [ ] #7744 (parabol team)

**Comment by mattkrick** [comment]
Context:
- old slack convo: https://parabol.slack.com/archives/C836NA350/p1683886365822119

Mind if i start working on this one? Adding this feature could save devops & sales a bunch of time so I think it'd be a good one to get done soon

**Comment by mattkrick** [comment]
Verifying SAML metadata
- When the viewer clicks "Update metadata" we need to guarantee that the metadata is correct
- To do this, we need to make sure that their IdP is set up correctly
- So, we'll need to go through the whole SAML flow

The flow as I imagine it:
- Click "update metadata"
- Send the metadata to our server to (safely) parse the XML & extract the signon URL
- If can't parse metadata, throw error there
- Their IdP auth window pops up. they log in. IdP posts to /saml/:domain
- Our server accepts their post and redirects the popup window to /saml-redirect, which forwards the result to the opener
- The opener shows any error message or a success if it all works

**Comment by Dschoordsch** [comment]
I'm not sure if we do this atm., but we should also keep the local account from the admin setting up SAML so they can still log in and fix it, if it breaks.

**Comment by mattkrick** [comment]
💯 we don't persist `metadata` to the DB until we know it works!
