### ISSUE TITLE
SAML UI: Create a `verifyDomain` mutation

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7642]
An organization has an associated domain which we derive from their email address. If a user wants to setup SAML we need to verify that the domain really belongs to them as all users under that domain will be affected. For starters we want to be able to do this manually with a custom domain.

## Acceptance criteria
* [ ] add a new optional field `orgId` to the SAML table
* [ ] create a new private mutation `verifyDomain(orgId: ID!, domains: [String!]!, slug: ID!)` [^1] which inserts a new SAML value with `domain`, `slug` and `orgId` set; `url` and `metadata` will be `null`
* [ ] ensure the current code can handle `url` and `metadata` set to `null`

[^1]: the idea https://github.com/ParabolInc/parabol/issues/6811#issuecomment-1180913613 also mentions a `method` field, but we don't need it because it will always be "manual" atm.

**Comment by gitstart-parabol** [comment]
@Dschoordsch , Can you provide more information on how we will determine the correct `orgId` for users who belong to multiple `organizations` when sourcing the `OrganizationUser` table? Specifically, what criteria will be used to select the `orgId` for a specific `user`, such as current `organization`, last accessed `organization` or something else?

**Comment by Dschoordsch** [comment]
* for existing entries in the `SAML` table just set `orgId=null`
* for `verifyDomain` add `orgId` as argument (I've updated the AC accordingly)

**Comment by gitstart-parabol** [comment]
@Dschoordsch,  Currently trying to test GraphQL mutations in the codebase, but when I hit the endpoint `http://localhost:3000/admin/graphql`, I am being redirected to `http://localhost:3000/meetings`. Can you provide any insight into why this is happening and how I can properly test mutations in the codebase?

**Comment by Dschoordsch** [comment]
You need to give your user the `su` role: https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/private/README.md

**Comment by gitstart-parabol** [comment]
> * for existing entries in the `SAML` table just set `orgId=null`
> * for `verifyDomain` add `orgId` as argument (I've updated the AC accordingly)

@Dschoordsch, Can you please confirm that for existing entries in the `SAML` table, I should set `orgId` to `null`?

**Comment by Dschoordsch** [comment]
@gitstart-parabol Yes, we need to manually verify the `orgId` for existing entries, so the default value should be `null`. This would apply for the migration to add the column as well as the existing mutation `enableSAMLForDomain`.
