### ISSUE TITLE
SAML UI: Create `updateSAML` mutation

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7643]
Needs:
* #7642 

Updating SAML for a domain should be possible by billing leaders of an organization for themselves.

## Acceptance criteria

* [ ] Create `updateSAML` mutation similar to [`enableSAMLForDomain`](https://github.com/ParabolInc/parabol/blob/d75533910d56f4358a08f7477fa3df3a72013522/packages/server/graphql/private/mutations/enableSAMLForDomain.ts#L70)
* [ ] arguments: `orgId`, `metadata`
* [ ] `metadata` can be `null` for disabling SAML again (should also update `url` in the `SAML` table)
* [ ] only callable by a `billingLeader` on an `enterprise` organization
* [ ] requires an existing `SAML` entry, otherwise fails

**Comment by gitstart-parabol** [comment]
@Dschoordsch, we suggest including `slug` or `name` as part of the mutation arguments to facilitate querying the `SAML` table, as the `orgId` field may potentially be `null`.

**Comment by Dschoordsch** [comment]
@gitstart-parabol This mutation should only be callable by a billing leader of an organization with a verified domain. That means there must be a SAML entry with the `orgId` set, otherwise they should not have access to this feature.

Modifying existing entries without an `orgId` via `domain` and `slug` can only be done by us using the existing, private `enableSAMLForDomain` mutation.
