### ISSUE TITLE
Change ‘Timeline’ to ‘History’

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#7667]
Many, many users over the years are unaware of where to find Meeting History. Recently we received direct feedback that they did not expect to find meeting history under ’Timeline’.

We began to track [this request on our on own internal Problems, Ideas, and Opportunities 🔒 board](https://www.notion.so/parabol/Change-Timeline-to-History-1ce0910aa235406995fff8d34c1c7e8f). There is a lot of internal support. Let's just do it and see what happens. It's a trivial change.

### Acceptance Criteria (optional)
   - Replaced word ‘Timeline’ with ‘History’ on side navbar
   - Search and replace for other mentions in the product
   - Notified #t_growth when change has been made so that they have the opportunity to update any screenshots that they may or may not deem to be important to update

**Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by enriquesanchez** [comment]
<img width="1292" alt="Captura de pantalla 2023-01-17 a la(s) 5 22 49 p m" src="https://user-images.githubusercontent.com/3276087/213033946-d1fbe8e7-a421-4e09-ad1d-6e08539b46dd.png">

@Dschoordsch I started working on this, and while changing the label and icon was trivial, I'm left wondering about all the timeline-related objects in the code, such as `callTimelineEvent`, archiveTimelineEvent`, `TimelineEventCheckinComplete`, etc... do those names also have to be changed to `history`? 😬

**Comment by Dschoordsch** [comment]
@enriquesanchez Let's only change the copy for now. If we get annoyed by it, we can rename it in the code later.
