### ISSUE TITLE
AI Summary: Staggered Roll-Out

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7668]
## Issue - Enhancement
Epic here: https://github.com/ParabolInc/parabol/issues/7480 

We are rolling out a new feature, and need to gauge response to it. 

## Acceptance Criteria (optional)

Roll-out should be: 
- 25% of users for 2 weeks. Since this goes out to all users, that ought to be plenty of views. 

We should assess if we're getting enough clear feedback during this phase, and if we want to add more mechanisms for judging effectiveness (like a feedback form, or an explicit up/down vote or similar) *and* where in our plans we want this feature to land.  

## Estimated effort: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))****

**Comment by tghanken** [comment]
User cohort stored in `data-sanctum.99_temp_squad_2_bofu.ai_summary_cohorts`.

**Comment by tghanken** [comment]
Rollout started on 2/13.

**Comment by nickoferrall** [comment]
The staggered roll out has begun so I'll close this issue
