### ISSUE TITLE
Checkout Flow: Make credit card info dynamic

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7693]
Predecessor: https://github.com/ParabolInc/parabol/issues/7530

### AC

- [ ] Next payment text and credit card info is dynamic, i.e. it's calculated using the org data
- [ ] After submitting credit card info and clicking Upgrade, the confetti animation happens
- [ ] The org is upgraded to the Team plan
- [ ] Handle error states as discussed [here](https://github.com/ParabolInc/parabol/issues/7530#issuecomment-1441707327)

**Comment by nickoferrall** [comment]
Pausing work on this issue until I know whether we'd like to use Stripe Elements - see comment [here](https://github.com/ParabolInc/parabol/pull/7812#discussion_r1119261639)

**Comment by nickoferrall** [comment]
Hey @acressall, when using Stripe Elements, the billing address is required. This adds one/two extra fields depending on the country:

![Screenshot 2023-04-05 at 15 16 29](https://user-images.githubusercontent.com/39854876/230108939-8eb57e26-57a1-49ec-a32e-766b8a2128d2.png)

![Screenshot 2023-04-05 at 15 16 37](https://user-images.githubusercontent.com/39854876/230108949-33eb70e4-2532-4e33-b5d4-0f6738523ddf.png)

I wanted to check if that works for you? Perhaps I should add extra spacing to the Team Plan Pricing so that it fills more of the height of the panel?

Also, Stripe expects to send the user to a payment completion page once they've entered their card details. Perhaps this would be a good idea as it would make it clearer that they've upgraded vs just seeing the confetti animation and the right drawer opening?

Here's a Loom with how it's currently looking: https://www.loom.com/share/8ae42db6610147f6946d06ecfc31e7b1

**Comment by acressall** [comment]
> I wanted to check if that works for you? Perhaps I should add extra spacing to the Team Plan Pricing so that it fills more of the height of the panel?

I have no issue with the extra field! As for the pricing side, I don't mind terribly if the upgrade btn is hanging, but I trust your judgement here.

> Also, Stripe expects to send the user to a payment completion page once they've entered their card details. Perhaps this would be a good idea as it would make it clearer that they've upgraded vs just seeing the confetti animation and the right drawer opening?

Does Stripe expect us to send them to a _Stripe confirmation_ page? Or just any page? I left some comments in the Loom, but want to make sure I understand. Do they want a new URL? Or is a change of state enough?

**Comment by nickoferrall** [comment]
> Does Stripe expect us to send them to a Stripe confirmation page? Or just any page? I left some comments in the Loom, but want to make sure I understand. Do they want a new URL? Or is a change of state enough?

Stripe has a redirect URL as the default behaviour, but I've disabled this, so we don't have to do that. Seeing that that's their default made me think it could be a good idea.

I'll paste your Loom comment here so it's all in one place:

> After the confetti animation is done, can we show a few elements of the billing view? 1. the collapsed CC field, and the invoice panel, which would probably show their first invoice? Not sure if we can do that right away?

Yep, I'll look at collapsing the CC field and showing their first invoice! Once I've built that, I'll share another Loom so you can see how it looks and decide whether or not we should have a confirmation page. Adding a confirmation page would probably be a v2 issue anyway.

**Comment by nickoferrall** [comment]
Hey @acressall, just letting you know that I've created a PR with the credit card functionality: https://github.com/ParabolInc/parabol/pull/8005 You can find a Loom demo in the PR description.

It isn't updating the UI after the upgrade happens yet - I'll handle that in https://github.com/ParabolInc/parabol/issues/8006 and keep you posted!
