### ISSUE TITLE
Checkout Flow: Add billing leader functionality 

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7694]
Predecessor: https://github.com/ParabolInc/parabol/issues/7531

<img width="221" alt="dropdown" src="https://user-images.githubusercontent.com/39854876/215598704-e7629db3-705c-459c-9588-1c56947b1437.png">

![Screenshot 2023-04-26 at 12 30 35](https://user-images.githubusercontent.com/39854876/234562096-1d81300a-2516-462a-be73-9ed1957b31bf.png)

### AC

- [ ] Clicking the icon on the right of the billing leader lets the user remove the billing leader or remove them from the org
- [ ] The user can press "Add Billing Leader", search through users in the org, and add them as a billing leader

**Comment by lilicaruso** [comment]
This 🔒 [user](https://app.hubspot.com/live-messages/3888472/inbox/4528535192#live-chat) requested this. I will let him know when complete.
