### ISSUE TITLE
Checkout Flow: add left sidebar

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7695]
Navigating to the org page (`me/organizations/${orgId}`) results in the left sidebar being replaced with the left sidebar in the designs [here](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=209%3A3221&t=89Ho501858UU34wG-0).

<img width="274" alt="left-sidebar" src="https://user-images.githubusercontent.com/39854876/215601735-fef04efa-c73e-41d2-89ad-67b3f1922d71.png">

### AC

- [ ] Org page shows the left sidebar that looks like the designs
- [ ] Only shows the Members, Plans & Billing, and Usage items (and only shows Usage if this is enabled)
- [ ] Clicking the Members menu item takes the user to the Members page, `/members`
- [ ] Clicking Plans & Billing takes the user to the new Checkout Flow, which has the same URL `/billing`
- [ ] Clicking Usage takes them to the same `/usage` page that exists in our current app
- [ ] Clicking the back Organizations button takes them back to the `/me/organizations` page

**Comment by acressall** [comment]
@nickoferrall a few notes on the first iteration:

- We'll exclude "Teams" for now. When/if we decide to introduce public & private teams, we can bring in this view
- Do you think we should move usage stats here at some point? Rather than going somewhere else for it? 

[here is the design](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=161%3A2088&t=gwfEUONL7iNnfmn6-4) for the organization details view.
![Desktop - org details](https://user-images.githubusercontent.com/18582225/215784344-44782ead-83dd-40c9-9952-e8bdbc9fd55b.png)


Also, [here's](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=165%3A4221&t=gwfEUONL7iNnfmn6-4) how it will look on mobile. Clicking the hamburger in the main nav will open/close the sidebar. 
![Mobile - billing - nav open](https://user-images.githubusercontent.com/18582225/215785324-82141e9e-84fb-4164-ac5e-0cbd41a76bc9.png)

**Comment by nickoferrall** [comment]
> We'll exclude "Teams" for now

Yeah, in the AC I suggested that we only show: `the Members, Plans & Billing, and Usage items`. Does that sound right?

> Do you think we should move usage stats here at some point? Rather than going somewhere else for it?

Yeah, I think that makes sense!

**Comment by acressall** [comment]
Sounds good!

**Comment by nickoferrall** [comment]
Hey @acressall, here's what I have so far:

![checkout-flow-sidebar](https://user-images.githubusercontent.com/39854876/217513678-4d37b980-a7f4-4b4c-bad2-049ded14ff83.png)

The problem is Usage is tied to the domain rather than an org, so I'm running into the following problem:

- The company Parabol has a Growth Org and a Product Org
- A user clicks Members or Plans & Billing. The URL is `/me/organizations/${orgId}/members`, so we can get the org name Product Org using the `orgId` in the URL
- The user clicks Usage, which has the URL `/usage`. We could store the org name in state, so when the user goes to `/usage`, the org title remains Product Org, but if the user refreshes the page, what org do we show? One option would be finding the first org in the `parabol.co` domain, which would be Growth Org. Refreshing the page and seeing a different org title isn't a great UX.


A couple of options that I see:

1. We don't show Usage in the left sidebar
2. We refactor how Usage Stats works so that the URL can be `/usage` or `/me/organization/${orgId}/usage`. The former would show Usage Stats for all orgs within the domain, whereas the latter would show Usage Stats for only that one org.

The second option would require a fair amount of refactoring, so I lean towards option 1. What do you think?

Also, in the design, the back button says "Organization", but as the user is on the Organization page, I think it should just say "Back"? I'll change the nav item icons before creating a PR.

**Comment by nickoferrall** [comment]
> Let's remove usage for now

@acressall sounds good 👍 

> I think it was supposed to be plural? Organization_s_? Do you think that's too confusing?

I shared a Loom in the linked PR here that touches on it: https://github.com/ParabolInc/parabol/pull/7733

The Organizations button currently exists in the app, but I think it's confusing:
![Screenshot 2023-02-08 at 18 56 04](https://user-images.githubusercontent.com/39854876/217625589-15d544da-014c-4679-90d2-5a5e35cbf005.png)

The user will go from the home page, click on their Team, and then click on the org. They then see the "Back to Organizations" button, and if they click it, they see a list of all of their orgs. It's confusing to me that it says "Back to" because, most of the time, that's not where the user previously was.

So, in the new flow, I'm thinking it should just say "Back" and take the user to the homepage. Organizations are already show in the left sidebar, so I'm not sure that page is necessary?

**Comment by acressall** [comment]
I'm ok with the btn saying "back" as long as it goes back to the last page the user was on. They could be coming from the team view, but there's also the "organizations" view that's accessible via the top nav, so if they come from there I would expect the back btn to go back there too.
