### ISSUE TITLE
Checkout Flow: add downgrade logic

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7697]
<img width="582" alt="Screenshot 2023-01-30 at 15 56 35" src="https://user-images.githubusercontent.com/39854876/215604325-8a03a574-03e3-4a9d-9ca0-1758419f0459.png">

### AC

- [ ] Clicking the "Downgrade" button (as outlined [here](https://github.com/ParabolInc/parabol/issues/7529)) opens a dialog with the Downgrade text specified in the [designs](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=209%3A3221&t=89Ho501858UU34wG-0)
- [ ] Pressing "Keep my Plan" closes the dialog
- [ ] Pressing "Yes, downgrade" downgrades the org from Team to Starter and shows them the second dialog screen asking why they're leaving
- [ ] The user can select several of the available options and click submit, which closes the dialog and causes the Plans UI to update. Their answer is tracked in Segment

**Comment by tghanken** [comment]
I'd like to follow a similar pattern to our Upgrade flow for Segment downgrade events:
- Start with a `Downgrade Clicked` event when the billing leader starts the downgrade.  Include a `downgradeLocation` property
- For menus in the middle of the flow, we can use a `Downgrade Continue Clicked` event with the name of the menu as a property.
- Finally, when the downgrade is finalized, we should use the existing `Organization Downgraded` event.

In practice, I see this as one `Downgrade Clicked` event emitted on the plans UI when the downgrade option is selected, then a `Downgrade Continue Clicked` event emitted when the "Yes, Downgrade" button is clicked on the attached design.  Finally, `Organization Downgraded` would be submitted when "Submit" is clicked, and we'd add the list of feedback as a new property.
