### ISSUE TITLE
why do you use RethinkDB

### ISSUE THREAD

**Issue by MaryLilian** [ParabolInc/parabol#7699]
Hi, I am reading your project and I love this project
I have a question, why do you choose RethinkDB in your project instead of other NoSQL like Redis, Cassandra , are there any special features that others dont have it. Can you share me it. I am wondering when I should choose RethinkDB instead of your project instead of other NoSQL like Redis, Cassandra

**Comment by Dschoordsch** [comment]
Hi @MaryLilian, I appreciate your interest. For questions like this you might want to join our [developer community slack](https://slackin.parabol.co/).
I wasn't with this project when rethink was introduced, but I think the main reason for a NoSQL was speed of development. We use Redis as cache and communication layer, but it's not great for persisting data. Cassandra is a whole different beast and is best suited for a more distributed service which does not suite our current architecture well.
FYI we are slowly moving away from Rethink and migrating data to Postgres, mostly for performance reasons.
