### ISSUE TITLE
Recurrence stable link: copy stable link from meeting

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#7701]
As a user, when I'm in a recurring meeting, I want to copy the stable link for the corresponding meeting series so I can share it with others.

**Comment by jmtaber129** [comment]
@enriquesanchez Button placement LGTM, but I'm not sure our users would make the connection that the "meeting series link" would always go to the active/most recent meeting. Maybe we use the term "permalink" instead of "link"? To me, that would more adequately imply the stable nature of the link. Changing "meeting series" to "active meeting" might also help.

**Comment by enriquesanchez** [comment]
@jmtaber129 Oh, I like "permalink", makes much more sense! 

Also, the more I read "meeting series" the less I feel it's obvious, since we don't use that term anywhere in the app. 

How about "**Copy recurring meeting permalink**"?

**Comment by enriquesanchez** [comment]
Got some more feedback during Design Share to reduce the label, we can try: `Copy meeting permalink`

![imagen](https://user-images.githubusercontent.com/3276087/217962526-ac5895d7-e5b6-440f-bb09-855c3c5c638b.png)

![imagen](https://user-images.githubusercontent.com/3276087/217962644-b2f575cb-e127-4b0d-9527-8c04d250270c.png)

**Comment by BartoszJarocki** [comment]
looks good to me! the only concern I have it's the fact it's a little bit hidden, but let's try it
