### ISSUE TITLE
Teams limit: handle inactive domains

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7723]
Currently, if an org doesn't have an active domain, which can happen if they use a free domain such as gmail.com, we don't send them the teams limit warning.

This is because we can't show Usage Stats to free domains as everyone that signs up with gmail.com would see all other user data from gmail.com.

We do have one Team tier company that is using a free domain (see [message](https://parabol.slack.com/archives/C042E8PGPD4/p1675267220136159?thread_ts=1675266998.778289&cid=C042E8PGPD4)).

So, in teams limit, we need to either:

1. Find a way to show Usage Stats to orgs that are using a free domain
2. If the org is using a free domain, don't send them to Usage Stats. Show them a different notification that let's them know they're over the limit. 

See discussion thread here: https://github.com/ParabolInc/parabol/pull/7637#discussion_r1097038026

### AC

- [ ] Orgs with inactive domains receive teams limit warning notifications and emails

**Comment by igorlesnenko** [comment]
To enable this we also need to have a way to check for an active deal on `HubSpot` for orgs without a domain. Or we need to decide that it is safe to skip the check in this case.

**Comment by nickoferrall** [comment]
In Sprint Planning, we said that as this is part of an experiment, we should wait until the experiment is successful before implementing it. If it's unsuccessful, we'll remove all the code and won't need to build this. 

Keeping the issue, but moving it out of this Sprint
