### ISSUE TITLE
Browser refresh required to see a member has been removed from an org

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7724]
An [enterprise customer ](https://app.hubspot.com/contacts/3888472/contact/28098151) 🔒 writes: 

>  I have been removing inactive members from my organization and noticed that when I hit the confirm button it sometimes loads and works correctly and other times I click the button and nothing happens (confirmation modal stays open) but then if I refresh the person is gone. Not a big deal, but wanted to share!

I was able to reproduce this with one of my demo accounts, as you can see in this gif 
![2023-02-07 12 23 54](https://user-images.githubusercontent.com/80418360/217318765-fd995aa1-a1f7-449e-a9e6-9b136928e3e4.gif)

**Comment by jordanh** [comment]
I've asked Squad 2 if they'd be willing to take this on

**Comment by BartoszJarocki** [comment]
@jordanh there's a PR that's fixing a bunch of related things: https://github.com/ParabolInc/parabol/pull/7772 let's revisit this one, once it's merged

**Comment by Dschoordsch** [comment]
Could be related to #7717
