### ISSUE TITLE
Prompt to join org

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7726]
Brief: https://www.notion.so/parabol/Did-you-want-to-join-X-Org-Prompt-104a6a8bbb2b4addbb5fed632b53a3c6

**Epic draft:**

**Version 1**: 
- https://github.com/ParabolInc/parabol/issues/7789
- https://github.com/ParabolInc/parabol/issues/7792
- https://github.com/ParabolInc/parabol/issues/7796
- https://github.com/ParabolInc/parabol/issues/7797
- https://github.com/ParabolInc/parabol/issues/7802
- https://github.com/ParabolInc/parabol/issues/7803

**What is not included in V1**:

- Update generic domains list. As we use a feature flag to manually select orgs with specific domains it is safe to not update it right now
- Email notificatons. We use pinned snackbars + notifications that we expect to be visible enough
- Pending approval status in the sidebar. I suggest to not include it in v1 because it does not affect the result — how many users send requests and how many billing leaders accepted it
<img width="454" alt="image" src="https://user-images.githubusercontent.com/466991/220299902-e74c0bb0-026f-47b4-824f-658f814cb419.png">

- Requesting access status on a billing leader side in organizations members list. Notification should be visible enough for now. Snackbar stays until closed and delivered even if user was offline. And even if it was closed by mistake, notification is still available in the notification center where user can click accept or deny again.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/466991/220300930-c44748a1-73ab-495e-a389-b1d4844699f8.png">

**Comment by igorlesnenko** [comment]
I updated the issue description with proposed epic

**Comment by acressall** [comment]
Exclusions to v1 are 🔥 . Big fan of the narrowed scope

**Comment by acressall** [comment]
@igorlesnenko designs are approved and we're ready to start implementing! Let me know if there are any outstanding questions

**Comment by nickoferrall** [comment]
Closing this as Squad 🧁 decided we'd track feature progress exclusively in Milestones instead of Milestones & Epic issues
