### ISSUE TITLE
Finance Role

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7727]
Brief: https://www.notion.so/parabol/Separate-Finance-Payments-Role-a6cc61807d834b59b66a45a3fea3a9ad
Designs: https://www.figma.com/file/i3kHOHbj4hoIrK3uVlEgZb/Finance-Role?node-id=25-750

## Issues

- [x] #7729

**Comment by nickoferrall** [comment]
Closing this as Squad 🧁 decided we'd track feature progress exclusively in Milestones instead of Milestones & Epic issues
