### ISSUE TITLE
Design settings space for finance role

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7729]
In creating a new role, we will need a place to add/remove members to the role. The role should exist at the organization level

[Brief](https://www.notion.so/parabol/Separate-Finance-Payments-Role-a6cc61807d834b59b66a45a3fea3a9ad?pvs=4)

AC

- [x] Billing leaders can add a new user to the finance role
- [x] Billing leaders can assign an existing member to the role
- [x] Billing leaders can remove users from the role

**Comment by acressall** [comment]
Implementation is pending confirmation of the name for this role. Current proposal is to rename the finance role `Billing Lead` and change the current billing lead to `Admin` or something similar. 

Version 1 would allow admins to select a "billing lead" on the billing screen. They can only select someone who is already a user in their org. 

- [Prototype](https://www.figma.com/proto/i3kHOHbj4hoIrK3uVlEgZb/Finance-Role?node-id=25-1105&scaling=min-zoom&page-id=25%3A750)
- [Figma](https://www.figma.com/file/i3kHOHbj4hoIrK3uVlEgZb/Finance-Role?node-id=25-750)

Version 2 allows admins to either select an existing user or invite someone to the role by email. This would be pending the work on public teams, so an invited user doesn't need to be assigned to a team. 
They can also be given the role from the `/members` tab

- [Figma](https://www.figma.com/file/i3kHOHbj4hoIrK3uVlEgZb/Finance-Role?node-id=25-751)

**Comment by enriquesanchez** [comment]
@acressall Love seeing this come into shape! I left some comments in the Figma file 🙌

**Comment by nickoferrall** [comment]
> are you ok if we use the existing designs from the checkout flow for assigning this role?

Sounds good!

**Comment by acressall** [comment]
I'm going to skip maintainer review for this one, since the design patterns existed in the checkout flow which was reviewed previously
