### ISSUE TITLE
RFC: RethinkDB Migration Strategy

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#7731]
Currently, we're considering doing a 3-phase approach for each DB table:
- Phase 1 creates the table in PG, writes queries to both RethinkDB and PG
- Phase 2 migrates all existing RethinkDB data over to PG & then checks the equality to make sure the tables are consistent
- Phase 3 removes the writes to RethinkDB & deletes the table in RethinkDB

This approach works great for our use case where writes are happening in real time, but it is extra work.

An alternative approach is to make a DB table readonly while we perform a single migration.
This allows us to perform a single migration, but our DB writes are not transactional. It's possible that writes to 1 table succeed and writes to the migrating table fail, which could leave orphans & break referential integrity.

To solve this, we could make the whole DB readonly. There's still a risk of becoming out of sync with an external DB (e.g. jira, github) but that's pretty minimal because we don't issue writes to an external entity & our internal DB in parallel.

The downside of using this approach is that our site will be down during the migration. We could solve for this by running it at times of low volume (e.g. 10PM PST). So, the question is: would we rather do more work during working hours, or less work during less opportune hours?

**Comment by rafaelromcar-parabol** [comment]
IMHO, for small tables, I would go with the real time and slow migration.

For bigs tables like RetroReflection, RetroReflectionGroup, NewMeeting, TimeLineEvent, Task, Task History, Comment and MeetingMember  I would do a one-shot migration. I would take the site down or stop writes to RDB during a Saturday afternoon or night, informing our clients with at least a 2-week notice.

**Comment by mwermuth** [comment]
Looked at during backlog grooming. @mattkrick can we close this? It came up as stale, but I know you are doing some work around this. We can potentially close this RFC, right?
