### ISSUE TITLE
Teams limit release test

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7732]
Once all teams limit PRs are merged and shipped to staging. Do the following tests on staging:

**Prerequisites:**

- Currently, team limits only work if an organization has an `activeDomain`
- You need to have a custom domain on your email (not Gmail), for example: `myaccount@customdomain.com` This should be a **real email**, so you can receive and test emails.
- It is better to not have any other organization that is already paid, you shouldn’t have usage stats enabled.
- It is recommended to record the whole testing process on **loom**. Due to complexity and a lot of steps, later it will be easier to understand if something went wrong.

**Case 1: Check if the limit is triggered correctly**

- Create a new organization, copy ID
- Add a feature flag **to the org**:

[https://action-staging.parabol.co/admin/graphql](https://action-staging.parabol.co/admin/graphql)

```
mutation {
 addFeatureFlagToOrg(orgIds: ["PUT_ORG_ID_HERE"], flag: teamsLimit) {
  ... on AddFeatureFlagToOrgSuccess {
    updatedOrganizations {
      id
    }
  }
}
}
```

- Create **3 teams** in total
- Add at least **1** more member to every team
- Add at least **1 additional billing leader** to the org
- Create 4th team, don’t do anything with it, let it stay empty
- For every team start running meetings, every meeting **must** have at least **2 attendees**
- You will need to run at least **3 meetings** for every team. it is recommended to run **various** types of meetings.
- When you finish **3rd meeting** on the **3rd team (And only in this case)**, **check** that that **all** billing leaders (and only billing leaders) are received:
    - Email saying that the limit of teams on organization is exceeded
    - Snackbar notification with “Your account is on roll!” text and usage stats button
    - Same text notification in the notification center in the header (bell icon)
    - Usage stats are enabled, and shows a warning with the correct lock date
    - If you close the snackbar notification and refresh the page, usage snackbar will not appear again.
- 
- If you now open any meeting (except standup) you would see an upgrade CTA in the sidebar.
- Delete an empty team (4th team), with no meetings, check that you still able to see upgrade CTA
- Delete one of the team with 3 meetings, upgrade CTA in the sidebar should gone
- Manually trigger `runScheduledJobs` Make sure you don’t receive any warning emails or notifications, organization is not locked:

[https://action-staging.parabol.co/admin/graphql](https://action-staging.parabol.co/admin/graphql)

```
mutation {
 runScheduledJobs(seconds: 5000) 
}
```

- Create the team again, run 3 meetings with 2 attendees, see the limit was triggered again
- Upgrade, see CTA in the sidebar CTA is gone
- Just like last time trigger `runScheduledJobs`, see no notifications or locks triggered
- Create one more team with 3 meetings with 2 attendees. See that no limit is triggered again, because the account is already paid.

**Case 2: Check that we exclude active deals on HubSpot**

We exclude organizations that have a domain with an active deal in progress on HubSpot. To test that:

- Downgrade the previous org to a free tier (cancel subscription): [https://www.notion.so/parabol/How-to-downgrade-an-account-from-Pro-or-Enterprise-6363156eaff14508bc2aeeec26cbc60a](https://www.notion.so/6363156eaff14508bc2aeeec26cbc60a)
- Copy your `orgId`
- Ask a developer to find an active deal on HubSpot
- Ask a developer to **temporary** update your organization in staging database with the active deal domain:

```
r.db('actionDevelopment').table('Organization')
  .getAll(r.args(['PUT_ORG_ID_HERE']), {index: 'id'})  
  .update({
    activeDomain: 'PUT_ACTIVE_DOMAIN_HERE'
});
```

- Run a meeting to trigger teams limit again. See that no limit was triggered (no warnings, no CTA etc.)
- Ask a developer to return a previous `activeDomain` value (your email domain)

**Case 3: Warnings and locks**

We have a warning 7 days before lock. We lock an org after 30 days

- Run a meeting to trigger the limit again. See it successfully triggered
- Connect to staging rethinkdb, see that 2 jobs were created successfully for that org - LOCK_ORGANIZATION, WARN_ORGANIZATION
- See that `runAt` has a correct value
- Update WARN_ORGANIZATION job to `new Date()`
```
r.db('actionProduction').table('ScheduledJob').get('PUT_JOB_ID_HERE').update({runAt: new Date()})
```
- Run `runScheduledJobs`

```
mutation {
 runScheduledJobs(seconds: 5000) 
}
```

- See that all billing leaders received a warning email
- See that all billing leaders received a warning snackbar and notification (check bell icon in header)
- Update LOCK_ORGANIZATION job to `new Date()`
- Run `runScheduledJobs`

```
mutation {
 runScheduledJobs(seconds: 5000) 
}
```

- See that all billing leaders received an email saying their orgs were locked
- See that all teams are locked now.
- Upgrade the org, see that the lock is gone

**Comment by MindEvo** [comment]
I triggered the usage stats page and noticed a couple of items on the usage stats page:

- The header says `abc.com Usage` as opposed to `customdomain.com Usage`. I used a custom domain for both billing leaders however the other 3 members of the org used abc.com domains. Not sure why it chose that over the billing leader's domain.
![image](https://user-images.githubusercontent.com/35351786/220551323-0931e894-7614-4f74-a726-727bf2475096.png)
- The total meetings chart is blank and the y-axis labels should probably be whole numbers that scale up with respect to the total meetings count. The x-axis needs to be changed to maybe a weekly scale?
![image](https://user-images.githubusercontent.com/35351786/220551144-972fe0c6-5ea9-46a2-a17e-9e1cd71acb89.png)
- Axis labels for the total members and total teams charts could also be updated (whole numbers on the y-axis). X-axis on total teams has the same problem as on total meetings above.
![image](https://user-images.githubusercontent.com/35351786/220552161-55732d33-ca98-4ae8-a7de-e0b940491ab9.png)

**Comment by igorlesnenko** [comment]
> Not sure why it chose that over the billing leader's domain.

@MindEvo At the moment this is expected behaviour, instead of showing usage stats for all domains user have, we pick the [biggest org](https://github.com/ParabolInc/parabol/pull/7587#issuecomment-1361835788).  

However, as it cause some confusion again, we might wont to change this in future when we refactor usage stats, which I think we want to do.

cc @nickoferrall

**Comment by igorlesnenko** [comment]
> - The total meetings chart is blank and the y-axis labels should probably be whole numbers that scale up with respect to the total meetings count. The x-axis needs to be changed to maybe a weekly scale?
> Axis labels for the total members and total teams charts could also be updated (whole numbers on the y-axis). X-axis on total teams has the same problem as on total meetings above.

@MindEvo thanks! I created an issue about this #7817
This should mostly happen on a test data, where we run everything within a short period of time. So I consider this is safe to roll-out to the real orgs.
