### ISSUE TITLE
Allow assigning of tasks without needing text in the body of the task first

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7741]
A [user](https://app.hubspot.com/contacts/3888472/contact/115220351) 🔒  on a sales call said: 

> I assign a lot of tasks to my teammates during retros. In order to change the default owner of the task, I have to write out text first. I would like to assign the task to a person, then write what I want it to say.

Right now, if you click your face to reassign before typing something the task disappears. 

![2023-02-08 17 17 46](https://user-images.githubusercontent.com/80418360/217663958-d9b8498a-5cc8-4190-8db0-5bd9538ad0fc.gif)

**Comment by jordanh** [comment]
This is a nice one.

@Dschoordsch says, "I think the same thing happens when you select a Due Date."

**Comment by jordanh** [comment]
AC:
- Change event to delete task for when focus leaves the card (i.e. it is blurred)
