### ISSUE TITLE
SAML UI: Add SAML/Enterprise SSO info page

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7744]
In #7661 we add the new SAML setup page which also has an info link "Learn more about this feature". We need a page where this points to. The only info I found, was a paragraph on https://www.parabol.co/enterprise/

## Acceptance criteria
* [ ] create a dedicated page for SAML/Enterprise SSO on parabol.co
* [ ] (share the link and assign to a dev)
* [ ] add the link to "(i) Learn more about this feature"

**Comment by Dschoordsch** [comment]
@avivapinchas Assigning to you so you can coordinate with growth how we can add this page.

**Comment by avivapinchas** [comment]
@Dschoordsch I need more context here 😄 Why do we need a dedicated page? Who is directed to this page? What is this page supposed to clarify or do?

**Comment by Dschoordsch** [comment]
I think the design was done by @ackernaut. We're adding a UI for enterprise customers to self-setup SAML (see screenshot it #7661). I think to explain what they're getting, the get more information link was added. To be honest, most enterprise users will know if they have a SAML provider or not. We could list a couple of big ones we support: Okta, Azure ActiveDirectory, DUO (these just come from our internal setup guide https://www.notion.so/parabol/SSO-SAML-Data-Requirements-Checklist-3ba63c2fd33e41958d1ac7df9e3472d6#d6c719a15eae4a59abddb89c6f598176)

As @tianrunhe pointed out that @igorlesnenko pointed out (this seems like a big collaboration :partying_face: ), we could create a page similar to https://www.parabol.co/integrations/jira-server/ which not only gives more information for the user, but also has a contact field to request us to enable it for them (we currently have to manually verify their domain).

**Comment by avivapinchas** [comment]
>  I think to explain what they're getting, the "get more information" link was added. To be honest, most enterprise users will know if they have a SAML provider or not.

Yes, that's part of the purchase process - they can buy Enterprise with or without SSO. 

So is this page needed? 

> We could list a couple of big ones we support: Okta, Azure ActiveDirectory, DUO
If this is the only content for the page, can this info live directly on the screen within the app? 

> we could create a page similar to https://www.parabol.co/integrations/jira-server/ which not only gives more information for the user, but also has a contact field to request us to enable it for them 
Would it be possible for a form like this to live on the screen within the app as well? It feels weird to me to direct folks to the site for the request, once they're already here. Also, I don't want to have a public page about this if it's only relevant once you've made an Enterprise purchase. 

> (we currently have to manually verify their domain).
Do you mean you need to verify after they make the request?

**Comment by Dschoordsch** [comment]
It's about a single link in the design, @ackernaut, where does [this link](https://www.figma.com/file/veEiStrSPlBvKgLNVgRNQg?node-id=21:2336#372304075) lead?

**Comment by mwermuth** [comment]
Looked at during backlog grooming. Going to icebox it.
