### ISSUE TITLE
Insights teaser

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7755]
We want to get a sense of demand for the Insights feature and get user feedback on what we intend to build.

To do that, we could:

1. Send users an email letting them know that we're building an Insights feature, provide them with a short description, and see if they'd like early access. If they do, we could include a form in the email that asks for more info and/or schedule a call with them. We'd probably want to send the email to a subset of users and keep sending it to more users until we feel we've had a good number of calls, e.g. 10 calls.
2. Share a teaser in the product. A subset of users can go to an `/insights` page, perhaps from the Profile menu, and see a dialog with info about the feature. The dialog contains a CTA that adds them to a beta list. We could add a calendly integration so that they can schedule a call after clicking the CTA. We could send a notification to a subset of users that directs them to the Insights page. Below is a rough idea of how it could look (the background would have a chart, though, and be more blurry).

![p-insights](https://user-images.githubusercontent.com/39854876/218123897-e7989788-1560-4cf8-ab02-6d4bbfcb894c.png)

3. Do both of the above

Further context in this [Slack thread](https://parabol.slack.com/archives/C042E8PGPD4/p1675370108197249) 🔒 

I lean towards option one as we wouldn't need to build anything in the product, so it would be the fastest. 

This is a discussion issue, so please let me know what you think. If you don't like any of the ideas or you have a completely different idea, please do tell!

### AC

- [ ] Reach a decision on next steps and close this issue

**Comment by acressall** [comment]
I lean to option 1 as a starting point. I'm not sure how much visibility the /insights url would get, but if we update the nav slightly we might get more eyeballs over there later. 
So I think we do option 1 now to start getting signal early, and then option 2 later (where we might be able to have a few things like this and gauge which gets the most signal)

**Comment by avivapinchas** [comment]
I vote we do both

For the email: I don't believe there's any blocker to starting that work. Someone would need to scope out that research, incl what we'd ask on the call. Depending what we want to know, we could do that either immediately (for more general exploration research) or when we have a designed prototype (for more specific feedback). 

For the in-product mention: I think we should treat that as part of our development process. Once we have a design we want to build against, we can first build that path or navigation and have it lead to a form. That way, as we're building out the actual feature, we're starting to get signal already.

**Comment by nickoferrall** [comment]
Here's an example of what we could email users and what we could ask them during the call 🔒 : https://www.notion.so/parabol/Proposed-Research-Call-Info-8f55629ca2764d8a94d29831abc87ffd

**Comment by avivapinchas** [comment]
Recruiting for this research is underway, tracking in Notion. Closing this issue for now. We may re-open an issue for a teaser when we start work on implementation.
