### ISSUE TITLE
Bug: Jira Integration - grayed out "Authorize" button

### ISSUE THREAD

**Issue by treyparabol** [ParabolInc/parabol#7756]
A [customer](https://app.hubspot.com/contacts/3888472/contact/98419001) 🔒 emailed Support:
<img width="484" alt="Screenshot 2023-02-02 at 11 00 46 PM" src="https://user-images.githubusercontent.com/88459947/218267548-246df4b6-365e-4dac-bf4f-4a3fa81f6f65.png">

Another [customer](https://app.hubspot.com/contacts/3888472/contact/80280951) reported the same issue in the same week:
<img width="491" alt="Screenshot 2023-02-02 at 11 03 06 PM" src="https://user-images.githubusercontent.com/88459947/218267572-1e21f8d5-bac8-42a1-8866-f76e2af21f1e.png">

Escalating this issue to p1 per the recommendation of @nickoferrall, as the first customer noted is on a paid plan.

**Comment by jordanh** [comment]
@nickoferrall curious if there was any triage resolution to this one, sir? Could you please add here.

**Comment by nickoferrall** [comment]
@jordanh I don't think anyone has taken this issue yet, so there hasn't been a triage. Would you like our Squad to add it to the Sprint?

**Comment by Dschoordsch** [comment]
I have a hunch that this is related to project settings and role restrictions. Needs a paid account to test.

**Comment by Dschoordsch** [comment]
No success with IP restriction either, while direct access to Jira Software does not work, the integration auth dialog works just fine, so does scoping in Sprint Poker.
![Screenshot from 2023-06-07 13-11-59](https://github.com/ParabolInc/parabol/assets/7331043/92add2ee-75e7-41a1-8359-faaf7589b3bf)

**Comment by Dschoordsch** [comment]
@drewhousman1010 could you contact the customer and check if the dialog looked anything like my last screenshot? Maybe ask them to make a screenshot themselves, as it may contain information which could help us.

**Comment by Dschoordsch** [comment]
The original error contained the message "Parabol cannot send data to any location".
From my testing and the documentation about [data residency](https://support.atlassian.com/security-and-access-policies/docs/understand-data-residency/) I conclude it's not that. It should not restrict access for 3rd party apps

The only related info I've found was this: https://community.atlassian.com/t5/Jira-Software-questions/quot-Jira-Cloud-for-Spreadsheets-cannot-send-data-to-any/qaq-p/2252502 which only has a vague answer which also points to the setting of "Allow user installed apps". While my error message was different, the resulting grayed out "Authorize" button matches. Thus I think it is a Atlassian Cloud configuration issue.

@drewhousman1010 could you confirm with the customer if users are allowed to install apps?

**Comment by jordanh** [comment]
@Dschoordsch I agree with you. I believe this is a configuration issue with security policies on the user's Jira Cloud instance. I've seen this one before.

Since this is recurring, we could consider "fixing" this one by adding a link like "Unable to connect?" to the Jira Integration setup section that links to some documentation that helps the user take some sort of action with their IT staff

What do you think?
