### ISSUE TITLE
Unable to end retro meeting

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7763]
Clicking "end meeting" didn't end our Squad retro meeting: https://action.parabol.co/meet/kBkIIO2Wv6/discuss/4

I can reproduce this locally. I get the following error message: 

```
SEND TO SENTRY Error: Cannot return null for non-nullable field EndRetrospectiveSuccess.isKill.
```

**Comment by Dschoordsch** [comment]
Assigning myself because I've ran into this locally and have a stash with changes for it already.

**Comment by Dschoordsch** [comment]
Sentry issue: [ACTION-PRODUCTION-AWN](https://parabol.sentry.io/issues/3192650181/?referrer=github_plugin)

**Comment by Dschoordsch** [comment]
Sentry issue: [ACTION-PRODUCTION-9ZR](https://parabol.sentry.io/issues/2783345256/?referrer=github_plugin)

**Comment by Dschoordsch** [comment]
Sentry issue: [ACTION-PRODUCTION-DHF](https://parabol.sentry.io/issues/3928359368/?referrer=github_plugin)

**Comment by Dschoordsch** [comment]
Releasing as hotfix to production since it happened 4k times in the last 30days, 1.6k times in the last 24h alone
