### ISSUE TITLE
Dataloader for `lastSeenAtUrl`

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7770]
We've seen some big chunk of the `TeamSubscription` time to be spend on resolving [`lastSeenAtUrl`](https://github.com/ParabolInc/parabol/blob/a57c546f43cd4e0573deba9f5b1417fae8365ccb/packages/server/graphql/types/User.ts#L295). The query is simple but means a roundtrip to redis for every team member for every team member (n²). Having a dataloader should reduce the roundtrips to 1.

## Acceptance criteria
* [ ] add a `lastSeenAtUrl` custom dataLoader
* [ ] use it also for `isConnected`

**Comment by mwermuth** [comment]
Looked at during backlog grooming. Going to icebox it.
