### ISSUE TITLE
Error: The loader.load() function must be called with a value,but got: undefined.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7771]
https://parabol.sentry.io/issues/1697059572/?referrer=github_plugin

```
Error: The loader.load() function must be called with a value,but got: undefined.
```

Reproduction:
* create a new team
* create an invite link from the team dashboard
* follow the invite link with a different user

**Comment by Dschoordsch** [comment]
I was tempted to put this as p1 because it affects a user joining a team which happens early in the user journey and thus sets the tone for how they perceive Parabol. However a simple reload fixes the issue for them and they will be a member of the new team.

**Comment by igorlesnenko** [comment]
This might be related #7776 but I was unable to get the exact same error locally

**Comment by igorlesnenko** [comment]
Merged a fix for at least one `.load()` issue. Not closing this for now, lets see if my fix solve the issue?

**Comment by igorlesnenko** [comment]
I see that the number of errors has decreased. It was 1.5k and now it's 200. So we fixed most of cases, but there is still some.
