### ISSUE TITLE
RCA: Downtime 2022-02-13 7:40-8:02UTC

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#7773]
We had a downtime incident yesterday that I still can't figure out.

- RethinkDB did not show elevated levels of CPU or Memory usage. Load seemed average
- PG also did not show elevated CPU or memeory usage. It had a few long-running queries, which is often does even when the site isn't down. I'm regarding that as a separate issue with a support ticket [here](https://www.digitalocean.com/community/questions/what-does-duration-mean-for-logs-queries-of-a-managed-postgres-database)
- The application server is using >80% of it's secondary memory, mostly from old docker images. This isn't wonderful, but I don't think this is the root cause because it's been this way for a long time. If we were choking the pagefile we'd see a spike in memory usage, which we do not. We may also see an increase in Garbage collection, which again we don't really see. 
- There are some large Disk I/O spikes. 1 from an hour before the incident & another a few hours before. Due to the timing of these spikes, even though their cause is unknown, makes me think this isn't it.
- Redis seems absolutely fine
- That leads me to to app itself. console logs in DD don't show anything happening right before the GQL executor fails to respond in time.

**Comment by jordanh** [comment]
Shall we close this one as `won't fix` and instead hope that the additional tracing we've added to APM will help us narrow this down if/when it happens again?

**Comment by mattkrick** [comment]
We've got a healthy chunk of non-trivial changes coming in the next hours/days.
- Brand new droplet
- Ubuntu 18.04 to 22.04
- Bump dokku
- Bump docker
- Bump NodeJS to v18
- Bump uWebSockets.js

These may impact site reliability. If not, we're fixing tracing, too:
- Adding redis, pg, fetch to dd-trace
- Adding variables to dd-trace graphql plugin

Closing this issue, we'll revisit if it crops up again
