### ISSUE TITLE
Standups: Add meeting series name to recurrence settings

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7783]
We are adding a title field to the settings of recurring meetings. This is to allow users to edit the series name if they ever want something different than the default "Standup".

[See Slack for full discussion.](https://parabol.slack.com/archives/C03THUWKVQ8/p1676562099316839) 🔒

In order to differentiate one instance from the other, we will append the date (in short form) for each instance. Example: "Standup - Feb 15".

## Acceptance criteria

Users can edit the name of a recurring meeting series from the recurrence settings modal (when a meeting is created and also when a meeting is already active).

![image](https://user-images.githubusercontent.com/3276087/221047184-b4a10a12-975d-4366-97ee-a80691a604a9.png)

[Figma link](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Standups-Recurrence?node-id=401%3A23963&t=OLVKaNXRDflQW0hG-4)

Please note the minor but important layout changes introduced in this iteration.

**Comment by enriquesanchez** [comment]
@BartoszJarocki 

Note: I updated the mockup in the description above to include some feedback we got today during Design Share.

The change is around the Stop and Update buttons at the bottom, the pairing of Stop recurrence and Update next to each other made it look like it was an either one or the other option (like when you have a Save and Cancel).
