### ISSUE TITLE
Checkout flow: Plans functionality

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7791]
Predecessor https://github.com/ParabolInc/parabol/issues/7529

### AC

- [ ] Show the Active Teams, Active Members, and Total Meetings stats for the org
- [ ] For users on the Starter tier, The Team plan is currently selected, Starter plan button is disabled, and clicking the Contact button opens a new email tab with `love@parabol.co` as the recipient 
- [ ] For users on the Team tier, the Team button says `Current Plan` and is disabled, while the Starter button now reads `Downgrade`. Downgrade logic will be handled here: https://github.com/ParabolInc/parabol/issues/7697
- [ ] For users on the Enterprise tier, the Team and Starter CTA buttons says "Contact" and open an email addressed to `love@parabol.co`
- [ ] Don't include the teams limit warning message - this will be added here: https://github.com/ParabolInc/parabol/issues/7692

**Comment by acressall** [comment]
I agree with you @nickoferrall ! Option 3 is best
