### ISSUE TITLE
Prompt to join org: Implement “Would you like to join X org” notification and a snackbar

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7792]
Show a "Would you like to join X org" prompt to a user once he signed up. Use his email to check if there are other organizations on his domain.

**AC:**

When user successfully signed up:

- Check if he doesn't have a generic email domain (see `isCompanyDomain`) 
- Check if his email is verified: `isEmailVerified`
- Check if there are at least one organization with this domain that matches the following criteria:
  - Has feature flag enabled (#7789) 
  - Has more than 1 user
  - Is not enterprise
 - If above is true, send a notification and a snackbar to the user
- Design:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/466991/221518148-f614d108-101c-4684-a6f0-9543d628d9d8.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/466991/221518041-4a0a027b-5fa6-4ff7-846d-9b08f60647c9.png">

- Hardcode all variable values in the notification object (consider notification as a text message)
- Add segment events

 
**What is not included**:

- Do not update list of generic domains for now
- No need to create request to join mutation in this PR

**Comment by acressall** [comment]
Here's the notification design
![Notification](https://user-images.githubusercontent.com/18582225/223234525-58eec8be-5b17-4697-9bd8-3d1188aa9d58.png)

**Comment by Dschoordsch** [comment]
@igorlesnenko @acressall Right now we're not verifying emails by default and we also don't want to have that by default as it adds additional friction. I think in this case we might need to add additional steps to the flow, like:
user creates new account without invite -> we recognize the domain and want them to join -> show a modal: "Your domain already has an organization on parabol, verify your email to join" -> start email verification flow

I think the "needs email verification" setting could be a good addition to the admin panel in general and organizations which set this to true would benefit from bigger security and also simplified onboarding.

**Comment by igorlesnenko** [comment]
@Dschoordsch @acressall User can still sign up using google with a custom domain, in this case email is verified. Do you think this could be enough for testing v1?

Alternative approach I can suggest: 

If we see that all conditions for showing "would you like to join org" are met, we just require verification from user from the beginning as if it was enabled on the domain

What do you think?

**Comment by igorlesnenko** [comment]
Another approach: Keep everything as is. But when user clicks 'Request to join', instead of showing "success" we show a snackbar saying "request will be send after verification, check your inbox"

And we send it automatically after verification.

**Comment by Dschoordsch** [comment]
I like the last approach.
We could start with only google signups and limit the testing to those for v1.
This would give us a skewed result though, as we would need to add additional friction for username+password signups.
That would be fine for me, so we could implement this additional step last, even after the first rollout.

**Comment by acressall** [comment]
Good catch! I think starting with google signups and then the last approach @igorlesnenko suggested sounds like a great way to move forward. Having this in place will also help with any security concerns on the part of the existing domain

**Comment by igorlesnenko** [comment]
@acressall I just noticed one thing:

> At least 1 active team
> More than 1 active user

Should we follow usage stats (teams limit) definition for active team and active user?

Asking because the query is quite complex and we would need to run it on every sign up. So probably I need to do some refactoring to simplify this query in this case.

**Comment by acressall** [comment]
Do you mean we'd wait until there are the same amount of active teams, or just the way "active" is defined is the same? I think the same definition of active would be ideal!

**Comment by igorlesnenko** [comment]
@acressall I mean that when we decide if we need to show "Would you like to join org" snackbar, we are checking that the org we want to join has at least 1 active team.

If we follow teams (usage stats) limit definition, "active" here is: Active team is the team that completed 3 meetings with more than 1 attendee and have had at least 1 meeting in the last 30 days

And active user is the user who have logged in within last 30 days.

**Comment by igorlesnenko** [comment]
@acressall My concern is that would be tricky to achieve:

- Currently, we have a very expensive query to check the number of active teams in organization 
- For "Prompt to join org" It will become even more complex, as we need to check it for several orgs on the domain, not only a single org like in teams limit.
- We also would have to run the query on every user sign up, and when user clicks on "Request to Join".

I would like to avoid this to avoid performance issues.

One solution is to make refactoring and store some calculations in DB: https://github.com/ParabolInc/parabol/issues/7975.
But this work might take some time.

So I wonder, If it is possible to simplify criteria for matching orgs?

For example:

1. Org has more than 1 any kind of member
2. Org has at least one meeting started in last 30 days

**Comment by acressall** [comment]
Ok, thanks for explaining the concern! I think this simplification makes a lot of sense for an experiment. When analyzing the test we can look at which orgs users were added to, to determine how well this criteria works and if we need to refine it at all

**Comment by igorlesnenko** [comment]
@acressall maybe in this case I can avoid checking "Org has at least one meeting started in last 30 days" too? If org has  > 1 member at least it is not default org that is created on sign up

**Comment by acressall** [comment]
haha yeah, that crossed my mind as well! we might get more early adopters this way too, so let's try it!

**Comment by igorlesnenko** [comment]
I excluded people that joining using invite links. I'm assuming that it's likely that they are already joining the right organization. There may be other organizations here, but it is easier to code at least for v1.

I also excluded people joining using SSO, as I think we don't want to touch enterprise users

@acressall what do you think? is it fine?

**Comment by acressall** [comment]
Yes, let's exclude enterprise for v1! Excluding invites sounds like the right call. Thanks for refining the criteria! Can we document what we've decided on in the brief once the PR goes through?
