### ISSUE TITLE
Checkout flow: Plans mobile UI

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7794]
Predecessor: https://github.com/ParabolInc/parabol/issues/7529

### AC

- [ ] Make the plans UI look good on mobile

**Comment by acressall** [comment]
@nickoferrall do you have any reservations about making the plans cards a slider? This is what we do on the website, but IIRC we're only doing this is the current new meeting modal. 
Figma: https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Checkout-concepts?node-id=529%3A4310&t=YQbiW05aeuuVPbjZ-4


![Image](https://user-images.githubusercontent.com/18582225/222810650-b4d5582d-2ffa-4257-a8f3-e601118b3d8c.png)

**Comment by nickoferrall** [comment]
@acressall I think that'd work! 

Carousels can be a bit fiddly though. I see [Linear](https://linear.app/pricing) stack the tiers which might be another option?

![Screenshot 2023-03-06 at 12 18 27](https://user-images.githubusercontent.com/39854876/223108930-37028a27-f7eb-45b5-a1bd-499dfd37cd63.png)


![Screenshot 2023-03-06 at 12 18 17](https://user-images.githubusercontent.com/39854876/223108919-7df5da85-f9c7-4d5d-a07d-cec7dd5edf5a.png)

**Comment by acressall** [comment]
I had to test how it would look stacked for us 😬 in my head I was thinking the cards would be too tall, but we can fit ~2 in view, so I think it will work fine! I've updated the designs
<img width="412" alt="Screen Shot 2023-03-06 at 10 16 40 AM" src="https://user-images.githubusercontent.com/18582225/223152002-081c5897-1232-4e57-b133-620fc74fc679.png">

**Comment by nickoferrall** [comment]
Oh nice, that looks great! Thanks for the design 🙌
