### ISSUE TITLE
Prompt to join org: Request to join domain mutation

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7796]
Implement a mutation that creates a join request for the domain

**AC:**

- Mutation does not accept any parameters
- Mutation checks if the viewer has a custom domain
- Mutation checks if the custom domain has at least one other organization which meets the following criteria:
  - Has a feature flag added 
  - More than 1 user
  - Is not enterprise
- Create a new postgres table to store the request.
- Request is attached to the whole domain (discussion for the context: https://github.com/ParabolInc/parabol/issues/7728#issuecomment-1456097607)

```
id
createdBy
domain
createdAt
expiresAt
```
- Set expiration date
- Do not create a duplicate request if already exists, even if expired
- Attach the mutation to the UI here #7792 

**What is not included:**
- Notifications
- UI changes

**Comment by Dschoordsch** [comment]
@igorlesnenko Why does it need to be a mutation? Can't we check on signup already and trigger this logic?

**Comment by igorlesnenko** [comment]
@Dschoordsch with the current flow, on sigup we only send a snackbar and notification, and then a user decide if he wants to click "Request to join" and run this mutation
