### ISSUE TITLE
Prompt to join org: Deny mutation

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7801]
Clicking deny button should mark all requests as denied (see #7797)

**AC:**

- Create deny mutation
- Mutation accepts array of request Ids (Take them from the notification, one notification might be attached to several requests)
- Mutation should mark all given requests as denied (see #7796)
- Ignore the request if already denied or accepted
- Modify UI from #7797 to attach this mutation to the `Deny` button
- Deny button should close the snackbar (notification will be marked as clicked automatically in this case)
- Update notification object, mark it as denied just to hide buttons (see #7781):
Design (TBD) cc @acressall 

<img width="485" alt="image" src="https://user-images.githubusercontent.com/466991/220540168-c9046d45-9289-4f44-bfbb-9963289db8b2.png">

- Update notifications of other billing leaders only if they have equal array of requestIds (as they may have different set of join requests attached to their notifications)

**Comment by acressall** [comment]
Design: 
![Notification](https://user-images.githubusercontent.com/18582225/223234651-ec0916f6-3aa3-4125-a015-52248de4b015.png)

**Comment by igorlesnenko** [comment]
Closing this issue, due to changes in architecture. Deny button will not only close the notification and mark it as clicked
