### ISSUE TITLE
Prompt to join org: Add teammate UI

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7802]
Clicking Review request button should open a dialog that allows to add a user to specific teams on the domain

Designs

![image](https://user-images.githubusercontent.com/466991/224244947-32e70695-1b6d-42c9-ba75-370bbd9a4e75.png)

- Blue check -> when user has added (active)
- Slate 600 outline -> available, unchecked
- Slate 600 check -> disabled, user has already been added to team

**AC:**

- Implement add teammate dialog
- Dialog should appear when the Review button is clicked on the notification or snackbar or notification (#7797)
- "Cancel" button should close the dialog
- Dialog shows **all** teams under the domain where the user is a team lead
- Enterprise organizations are excluded

**Not included:**

- Add to teams mutation

**Comment by acressall** [comment]
@igorlesnenko here's the updated modal. 

- Blue check -> when user has added (active)
- Slate 600 outline -> available, unchecked
- Slate 600 check -> disabled, user has already been added to team

![confirm modal (2)](https://user-images.githubusercontent.com/18582225/223234276-3c881a14-54e0-4adb-97fb-4162c7fb8952.png)
