### ISSUE TITLE
Clear out notifications from staging on backup-restore

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7818]
We need to clear out notifications from staging on backup-restore

While testing scheduled jobs on the staging, you can accidentally send notifications that were transferred from the production

**Comment by jordanh** [comment]
This is a good one!

**Comment by jordanh** [comment]
@mattkrick @rafaelromcar-parabol raising visibility. Shall we do this before standing up new prod infra?

**Comment by mattkrick** [comment]
This is a good one, I think it's independent to the prod migration though, I assume this has been a longstanding problem for awhile?

**Comment by rafaelromcar-parabol** [comment]
@jordanh "new prod infra" you mean the future Kubernetes or today's operation?

In any case, this is independent. This is problematic for our weekly backup, restore and test on Staging. A script should be developed and instructions to run it added to the Release Playbook, so we execute it after every restore on Staging.

@mattkrick We have had problems with Staging notifications being sent to clients for a while I think. This is related with the fact that action-chronos is disabled on Staging.

**Comment by jordanh** [comment]
>  "new prod infra" you mean the future Kubernetes or today's operation?

@rafaelromcar-parabol, starting with today's dokku-based solution

**Comment by rafaelromcar-parabol** [comment]
Discussed with @mattkrick today in some sync time we had.

We will be tackling that in the future (August/September), at least defining a solution that can go in the following direction:
- Decoupling migrations tests from application tests: we would have a pipeline that would clean-up databases, restore **production** data, run the migrations, extract all useful data for us (how long it took, monitoring metrics and stuff) and then cleans-up again the databases and restores **staging** data. Then, in Staging we would have our own generated data (or we might have only data from Parabol org in Staging) so we can mess around without any trouble. No worries about notifications, no worries about security issues or anything.

**Comment by rafaelromcar-parabol** [comment]
Why did you close this @mwermuth ? this isn't really fixed afaik 🤔 the temporary fix was to disable Chronos and set the e-mail provider to debug, so we wouldn't send e-mails to anyone. But the root problem is still there!

Or maybe I'm missing something 🤔

**Comment by Dschoordsch** [comment]
@rafaelromcar-parabol we iceboxed the issue because it got stale, feel free to re-open if you feel we should still prioritize it.
