### ISSUE TITLE
Publish landing pages for "Lessons Learned", "Post-Mortem", and "Pre-Mortem"

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#7823]
​

**Comment by jordanh** [comment]
Created by Jordan for Gareth
  See the dashboard of [Squad 3: Land & Expand](https://action.parabol.co/team/h0ZGQYp0Y0)

  *Powered by [Parabol](https://www.parabol.co/integrations/github)*

**Comment by garethaledavies** [comment]
I imagine these can be based off the existing Retrospective product landing pages, with minor edits to the text. The goal is simply to attract qualified users to new product pages.

Things to do:

- [ ] Draft pages
- [ ] Select target SEO keyword
- [ ] Check Clearscope rating
- [ ] Check CTA leads to correct URL
- [ ] Update top navigation
- [ ] Publish
- [ ] Add internal links from other pages where we mention the keyword
- [ ] Verify page is crawled on Google Search Console

**Comment by mwermuth** [comment]
Came up during backlog grooming. Moving to icebok.
