### ISSUE TITLE
Draft and write-up in-product templates for "Lessons Learned", "Post-Mortem", and "Pre-Mortem"

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#7826]
- [ ] Research potential templates that exist already
- [ ] Create a first draft of in-product templates
- [ ] Get feedback on in-product templates
- [ ] Refine ideas
- [ ] Write them up properly to be added to the product

Follow on task: #7829

**Comment by garethaledavies** [comment]
Drafted here: [https://www.notion.so/parabol/Retros-in-Disguise-V1-in-prod-templates-6f1d904e95704875a77b41cbb849c566?pvs=4](https://www.notion.so/parabol/Retros-in-Disguise-V1-in-prod-templates-6f1d904e95704875a77b41cbb849c566?pvs=4)

**Comment by mwermuth** [comment]
Came up during backlog grooming. Moving to icebok.
