### ISSUE TITLE
Send payment confirmation email

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7851]
Once a user has upgraded to the Team tier, we should send them a payment confirmation email.

The email can be the default Stripe confirmation email, see here: https://github.com/ParabolInc/parabol/issues/7530#issuecomment-1446871057

### AC

- [ ] Send users a payment confirmation email after they upgrade to the Team Tier

**Comment by acressall** [comment]
Noting, it would be ideal if this issue can include sending ongoing invoices / notifications of invoices by email as well. Is this within scope @nickoferrall ?

**Comment by nickoferrall** [comment]
@acressall agreed that that would be ideal, but it would be out of scope for this issue

**Comment by acressall** [comment]
Ok, I'll create another issue for it!
