### ISSUE TITLE
Standups: Response text in a discussion thread cannot be selected

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7866]
## Issue - Bug

When opening a discussion thread in a Standup meeting, the response text cannot be selected. Please note that comments can be selected.

<img width="1064" alt="Captura de pantalla 2023-03-06 a la(s) 11 25 37 a m" src="https://user-images.githubusercontent.com/3276087/223185309-7c7c7284-7ce4-4548-87fe-5b6c040f4e4c.png">

## Acceptance Criteria:
Users can:
   - Select (and copy) the Standup response text in a discussion thread
   
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by enriquesanchez** [comment]
@BartoszJarocki fyi

**Comment by Dschoordsch** [comment]
Our drawers react to sliding in/out. This might be related as I also noticed this an a new drawer we're just adding: https://github.com/ParabolInc/parabol/pull/8004
