### ISSUE TITLE
EditableText uses wrong font on some machines

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7867]
`EditableText` uses a monospace font when editing icebreakers on Android or editing the Standup title or prompt on Chromium on Linux
![Screenshot_20230302-165522](https://user-images.githubusercontent.com/7331043/222482411-9a2e1a76-07ff-4197-bf76-0f42fe11b219.png)

See comment in https://github.com/ParabolInc/parabol/pull/7431#pullrequestreview-1322123112_

**Comment by BartoszJarocki** [comment]
@Dschoordsch is it still happening? I fixed the styles a while ago and I want to confirm, thanks!

**Comment by Dschoordsch** [comment]
Thanks for the ping, it's fixed now
