### ISSUE TITLE
Add a sound when a message is added to the discussion thread

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7868]
Inspired by https://github.com/ParabolInc/parabol/pull/7858, I'd love to be notified when someone has added a comment or task to the discussion thread.

When I'm on a smaller screen, I've been in several retros where I'm looking at the Zoom call and have missed a comment in the discussion thread.

We could use the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to detect if a user is currently focusing on Parabol. Only if they're not looking at Parabol should we play the sound.

It's possible that some users wouldn't want any sound, so if we want to build this, we should probably add a mute button, perhaps next to the avatars at the top right of the screen?

### AC

- [ ] Design made with a mute button

**Comment by mwermuth** [comment]
Looked at during backlog grooming.
