### ISSUE TITLE
Exploration: Standups — AI summaries

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7872]
Implement AI summaries similarly to what we have in retro meetings

To investigate
1. Standup responses are fairly long and usually cover many topics. Check how Open AI API is handling that kind of data

[Slack Message](https://parabol.slack.com/archives/C03THUWKVQ8/p1677864191059149?thread_ts=1677864191.059149&cid=C03THUWKVQ8)

AC
- [ ] Explore meeting summary contains an AI summary of all the responses submitted

**Comment by mwermuth** [comment]
Solved in #8568
