### ISSUE TITLE
Deselect All in Poker

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7881]
Design: #7575 
Prototype: https://www.figma.com/proto/ZJKPCmYNHVaGsZQbQhq3vg/Poker%3A-Deselect-Clarity?node-id=1-349&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A349

## Scope phase
![Image](https://user-images.githubusercontent.com/18582225/223580853-d790cd3a-adc4-4a6f-99cf-d5e0d7690a02.png)

- Users can add and remove issues as usual
- Users can see issues that have existing Parabol activity (disabled)
- Users _cannot_ remove issues that have existing Parabol activity (disabled)
- If a user hits "deselect all" the disabled issues will not be removed from scope

## Estimate phase

- Users can remove an issue from scope by hovering over the issue in the sidebar and click the trash icon
- If the user clicks the trash icon on an issue that has Parabol activity (votes, comments), they will be prompted to confirm
- The user can remove an issue that has a decided vote, but will be prompted to confirm

![Image](https://user-images.githubusercontent.com/18582225/223581130-d8a4beef-b201-4223-ab72-950ee7a3b118.png)

![Image](https://user-images.githubusercontent.com/18582225/223581169-893444b8-cdd3-4603-86b5-ca855b9112fc.png)

**Comment by nickoferrall** [comment]
Closing this as Squad 🧁 decided we'd track feature progress exclusively in Milestones instead of Milestones & Epic issues
