### ISSUE TITLE
client error when tab opens from sleep

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#7883]
### Reproduction criteria
_Note: this reproduction criteria is sporadic_

1. Allow/put laptop to sleep (1-hour or more seems to work well on my side)
2. Click on Parabol tab
3. Note client side error

### Acceptance Criteria (optional)
   - Root cause identified
   - Fixed or new backlog issue(s) opened

**Estimated effort:** 2 hours to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
@jordanh Because I think your description and reproduction steps don't match this Sentry issue, I created #7898 to fix the Sentry issue and left this one because I assume you could reproduce the sleep issue.
