### ISSUE TITLE
Standups: Add meeting ended notifications

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7885]
AC
- [ ] when meeting ends send a meeting ended notification just like     for other meeting types (slack, mattermost etc)

[:lock: Slack Message](https://parabol.slack.com/archives/C03THUWKVQ8/p1678245670827799)

**Comment by gcrickman** [comment]
A [customer](https://app.hubspot.com/contacts/3888472/company/7348403968) 🔒 writes:

> It wasn't clear that everyone on the team would need to connect to slack via the team view --> integrations link. We are piloting async standup via Parabol with this small 5 person team. Now that they've done that and I've removed the recurrences for the previous meetings and started a new one. They get a notification via the Parabol app in slack when meetings start but haven't gotten anything when a meeting ends. Given we spin up teams and dismantle them frequently based on project lifespans it's a bit more overhead than we were hoping for to make everyone have to do that every time we create a team in Parabol. Given that's required, it seems, it would be rad if they only had to do that once at their account level and then any team they were allocated to, they'd then get notifications via slack.
> 
> Why do we choose a channel to have Parabol post to if nothing is posted to the channel? We were hopeful that the async standup summaries would post to the designated channel to make it easy on the production team folks managing the teams. We used to use another tool called Status Hero that did this and were stoked to see this
