### ISSUE TITLE
Standups: clarify distinction between "End meeting" and "Stop recurrence"

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#7889]
[Background and context 🔒](https://parabol.slack.com/archives/C03THUWKVQ8/p1678200490239829)

## Issue - Enhancement

Some users are getting confused by the option to "End meeting" thinking that at the same time it will stop recurrence. Let's explore solutions to clarify the distinction between these two actions.

## Acceptance Criteria
Users can:
   - easily understand the different between ending a meeting instance, ending the meeting series, and stopping recurrence.

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by enriquesanchez** [comment]
Here's the result of feedback and iteration:

When a user selects the option to end a recurring standup meeting, either from inside a Standup or from the meetings view, we pop a dialogue asking for confirmation of intent:

```
- End this meeting (will restart in {time})
- End this meeting and don’t restart
```

`{time}` being the time left before the next instance starts

![image](https://user-images.githubusercontent.com/3276087/224392790-a9b02699-8263-4dde-a45f-7e38e931d8ad.png)

The flow would work something like this:

https://user-images.githubusercontent.com/3276087/224395149-4096bdc7-cdea-4851-95c9-dfce582cdad9.mp4

https://user-images.githubusercontent.com/3276087/224395172-2d296c48-78f0-4c47-a950-734ff77c3044.mp4

--- 

Note that **this dialogue should only appear if the standup is set to recur**. For single-instance standups we do not need to show it.

@BartoszJarocki @jmtaber129 Would like one final check from you before calling this one done.

**Comment by jmtaber129** [comment]
@enriquesanchez LGTM!

**Comment by enriquesanchez** [comment]
@jmtaber129 Thanks for the review 🙌
