### ISSUE TITLE
TypeError: socket.getUserData is not a function

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7898]
https://parabol.sentry.io/issues/3965814612/?referrer=github_plugin

```
TypeError: socket.getUserData is not a function
  File "./packages/server/socketHelpers/sendEncodedMessage.ts", line 27, in sendEncodedMessage
    if (socket.getUserData().done) return
  File "./packages/server/sse/SSEConnectionHandler.ts", line 49, in SSEConnectionHandler
    _sendEncodedMessage.sendEncodedMessage.call(void 0, connectionContext, {version: APP_VERSION, authToken: nextAuthToken})
```

Most likely happens because the uWebsockets library cannot acquire a socket and thus returns an invalid object. This first happened after switching to new infrastructure.

**Comment by rafaelromcar-parabol** [comment]
This is fixed thanks to [7903](https://github.com/ParabolInc/parabol/pull/7903)

**Comment by jmtaber129** [comment]
Closing per the above message
