### ISSUE TITLE
Usage stats shows incorrect count of active teams

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7916]
Based on data reported [here](https://parabol.slack.com/archives/C042E8PGPD4/p1678718317634859), we have one organization that has only 3 active teams, while the usage stats shows 8 active teams

AC:

- Determine the root cause
- Show the correct number of active teams

**Comment by tianrunhe** [comment]
Another report for [target.com](https://parabol.slack.com/archives/C03C3J42WDU/p1680532305226219)

**Comment by tianrunhe** [comment]
👆 That was a wrong PR to reference but I can't remove it...
