### ISSUE TITLE
Team health check

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7938]
As a manager I want a quick check in round where the team can vote how they're doing. Seeing the current results can help spark discussions.

To get feedback as fast as possible this feature should be kept minimal in v1
* additional optional phase in retros after the icebreaker before the reflect phase
* 3 options depicted by emojis and a single fixed question
* once voted, users can switch vote but not take it back
* once votes are revealed, the number of votes for each option will be displayed
* the same result is also part of the summary

---
Work breakdown
* [ ] #7939 
* [ ] #7940
* [ ] #7941

---
See also [previous discussions](https://github.com/ParabolInc/parabol/discussions/6311)

**Comment by Dschoordsch** [comment]
@ackernaut I played around with the designs a bit and would like to get some feedback
Overview, new phase with logo:
![Screenshot from 2023-03-27 08-22-52](https://user-images.githubusercontent.com/7331043/227857723-cd193861-bc81-4f31-9bc3-55cacc274d84.png)
Selecting an answer:
![Peek 2023-03-27 08-23](https://user-images.githubusercontent.com/7331043/227857801-7a5e5769-9b39-4202-9e6a-c5b3e25d8ac0.gif)

**Comment by acressall** [comment]
Some clarifying questions:

- Is this only for retros to start? Would we expect this to influence the reflections or what a manager might want to discuss? If it's only for retros to start, why retros over another meeting type?
- How was "how are you" decided as the prompt? Do we expect people to answer honestly if they aren't doing well? (Considering when we are asked this question in person, we often say we are doing fine even when we're not)
- Are there any background materials? I'm assuming this came from the retreat, so I might be missing a lot of context

**Comment by Dschoordsch** [comment]
Thanks for your feedback
> * Is this only for retros to start? Would we expect this to influence the reflections or what a manager might want to discuss? If it's only for retros to start, why retros over another meeting type?

It's meant to check in with team health and may be tracked over time in the future. Eventually it could be added to other meeting types and/or in other positions as well. Retros were just chosen as the first one to try it and get some feedback on how it's used.

> * How was "how are you" decided as the prompt? Do we expect people to answer honestly if they aren't doing well? (Considering when we are asked this question in person, we often say we are doing fine even when we're not)

The prompt is not finally decided. In the future it should be editable. My notes say: "How do you feel?", maybe that would be less ambiguous?
> * Is there any reasoning for happy/sad emoji as opposed to red/yellow/green (traffic light) format?

Mostly colour blindness as red/green is the most common one.

> * Are there any background materials? I'm assuming this came from the retreat, so I might be missing a lot of context

There are a couple of motivations behind this first iterations which we discussed
* start as simple as possible
* make it generic enough so it works also in the future
  * with different question
  * maybe also with different response options
  * as a building block in other meeting types
  * at the start/end of the meeting
* we most likely want to track it over time in insights

**Comment by Dschoordsch** [comment]
@ackernaut thanks for your review. The current implementation plan is:
* Team Health is a meeting phase which could be added to Sprint Poker, Retros or Check-Ins, but we start with just retros
* It can have multiple stages, each with their own question and answer options, but we start with one predefined question and answer set
* Currently the selected state is the biggest emoji, it's more obvious if you're in control of the mouse rather than watching a gif
* I had planned to put a reveal button underneath for the facilitator and then move to a view where the answers are revealed. I'll post an update once I get to it.

I think this architecture is quite future proof and would allow for your mentioned future expansions: multiple question stages, different answer possibilities. In that case we might want to introduce a separate results stage to see all results at once, but for now this would be overkill.

**Comment by ackernaut** [comment]
@Dschoordsch could the multiple questions/stages be presented in the same view, like X number of retro prompts are for the Reflect phase? Could we also consider updating the revealed stage in the same view, like revealing a Sprint Poker?

**Comment by Dschoordsch** [comment]
@ackernaut That's a good question, I haven't thought about putting all questions on the same screen, but I think it makes sense. I'll think about it and propose something.

**Comment by acressall** [comment]
@Dschoordsch LMK if you want to spend some time workshopping this together!

**Comment by nickoferrall** [comment]
Closing this as Squad 🧁 decided we'd track feature progress exclusively in Milestones instead of Milestones & Epic issues. We can always reopen this issue and add it to the milestone if anyone would like to continue the discussion
