### ISSUE TITLE
Design Topic Sharing

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7945]
- [Brief](https://www.notion.so/parabol/Shared-Summaries-ac446ff9604c43afb5c82edc951aba4d?pvs=4)
- Goal: How might we create more touch points with Parabol to increase awareness within a company?

This is an iteration of work done on the growth retreat, designs by @lorena-cure 🎉 

AC:
As a user, I can:
- [ ] see how to share a retro topic from the meeting summary
- [ ] select where to share the topic
- [ ] have confirmation that the reflections were shared to my selected channel

**Comment by acressall** [comment]
- [Figma](https://www.figma.com/file/hQRaJxKfSgOQO6KXyclK0Y/Share-Summary-Topics?node-id=282%3A300&t=7flpYN8sRoltp7Xi-1)
- [Prototype](https://www.figma.com/proto/hQRaJxKfSgOQO6KXyclK0Y/Share-Summary-Topics?node-id=282-362&scaling=min-zoom&page-id=282%3A300&starting-point-node-id=282%3A362)
- [Loom](https://www.loom.com/share/4ecb702c79b745139523dee5e80805ce)

**Comment by enriquesanchez** [comment]
@acressall This is a really cool idea. Added my comments to the Figma fike 👍

**Comment by acressall** [comment]
@ackernaut this is ready for maintainer review. A summary of the new elements:

- share button added to retro summary
- Modal + confirmation snackbar added to summary page
- If a user clicks the share button from the _email_ summary, they will be taken to the product summary page with share modal open
- New Slack message to include topic reflections, and AI summary if available

**Comment by ackernaut** [comment]
Hey, nice work iterating on this idea! I left a few minor comments in Figma. I’m curious to see usage metrics for this feature, do y’all plan on tracking an event for ‘summary topic shared’ or similar?

**Comment by acressall** [comment]
Thanks Terry! Yes, we'll definitely be tracking what's shared, where it's shared, and I'd love to dig into what kinds of teams share and if those teams grow at all after sharing.
