### ISSUE TITLE
Human readable & user friendly default team names

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#7947]
## Issue - Enhancement

Inspired by @lilicaruso 's [request](https://parabol.slack.com/archives/C03C3J42WDU/p1678974775652259): 
Today when a new user signs up, we create a team for her and name it "XXX's team", where `XXX` is parsed from user's email. 

I think we can add a little bit fun to this by changing it to some pre-defined "fun" nouns. The concept is kinda like our ice breakers. So maybe we have a list of fun team names, e.g., "bug writers", "long meeting lovers", "work procrastinators" etc and when a new team is created, we just randomly pick one from the list. I think this would:
1. Make our product more fun
2. Give our user a little nudge to change it therefore getting a little bit closed with us
3. ~~To change the team name you need to find the team setting page, where you could discover the integration settings 😜~~

### Acceptance Criteria (optional)
Users can:
   - [ ] get a fun and meaningful default team names when signing up

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
That was implemented, just tested with a new user and got "Team Comfy Socks 🧦"
