### ISSUE TITLE
Use user's timezone when creating a standup meeting

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7952]
When creating a standup meeting we use `UTC` when creating a title ie. `Standup - Thu 28`. This could lead to meeting having a wrong date as user timezone can vary. 

To solve this we'd need to use user's timezone. 

AC
- [ ] propose a solution for sending user timezone to a server
- [ ] use user timezone when creating a standup meeting title

One of the solutions could be sending the timezone via custom http header, similarly to how Vercel is doing that: https://vercel.com/docs/concepts/edge-network/headers#x-vercel-ip-timezone. Then, once we have that, use GQL context to make it available in all the resolvers.
 

_Originally posted by @jmtaber129 in https://github.com/ParabolInc/parabol/pull/7850#discussion_r1128134522_

**Comment by jordanh** [comment]
Related to #7953?

**Comment by BartoszJarocki** [comment]
@jordanh no, for the recurrence we have a timezone picker, and we use the correct timezone. this is just for creating a single meeting and figuring out the correct date in the title

**Comment by jordanh** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/npWgyd21Py/estimate/1) in Sprint Poker #​​7

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
