### ISSUE TITLE
Defined UX flow for selecting a different team on a team-scoped template

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#7955]
Currently in the activity library concept we have the idea that a user can see any templated activity available to them via their team membership. What happens when they select an activity but then select a different team for a template scoped to a single team?

### Acceptance Criteria
Delivered a UX flow showing
- How users can change to a different team on an activity/template scoped to the currently selected team
- This will inform UI design and implementation

### Estimated Effort
- 3 hours

**Comment by ackernaut** [comment]
Does this look good for this sprint @enriquesanchez ?

**Comment by ackernaut** [comment]
I can take first steps on this and pass it on if I need to.

**Comment by ackernaut** [comment]
[Jotting down note here](https://www.notion.so/parabol/UX-for-selecting-a-different-team-for-an-activity-scoped-to-a-single-team-e428dc2538de411c94a34b81adfe9f88)

**Comment by enriquesanchez** [comment]
>I can take first steps on this and pass it on if I need to.

@ackernaut Yeah, if you already have some initial thoughts on how to handle this, then I'd prefer if you take first steps and then pass on.
