### ISSUE TITLE
Public teams: Add a team setting to make it private

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7981]
As all teams are public by default, as a team lead, I want to be able to mark a team as private if it contains sensitive information. This feature is only available on non-starter plans.

## Acceptance criteria
* [ ] private teams are not visible to non-members (check with #7979 where we made them visible)
* [ ] team can be marked private on creation
* [ ] team private setting can be modified in the team settings

**Comment by mwermuth** [comment]
Came up during backlog grooming.
