### ISSUE TITLE
Team Limits: Active Teams visible to Billing Lead (aka Super Admin) 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#7983]
## Issue - Enhancement

In our team limits test, we've gotten 2 pieces of feedback that leads didn't know what the active teams were and 4 pieces of feedback that they wanted to remove teams to stay under the free limit. 

To solve this tension, we should help Billing Leads understand what teams are active across their Orgs. 

We've previously designed two versions of this: 
<img width="628" alt="Screenshot 2023-03-29 at 11 35 05 AM" src="https://user-images.githubusercontent.com/11621016/228619759-d1df0f67-676e-4c7f-80cc-0704f5d0109c.png">

<img width="318" alt="Screenshot 2023-03-29 at 12 28 55 PM" src="https://user-images.githubusercontent.com/11621016/228619973-729dbe45-4688-4561-951d-220a0ebae20f.png">

### Acceptance Criteria (optional)
Billing Leads can see what teams are active within their orgs, the team leads associated with those teams, and whether the team is active or not. They can see the option to archive a  team, but cannot archive teams that they are not leading. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by gcrickman** [comment]
A [customer](https://app.hubspot.com/contacts/3888472/company/791351286) 🔒 asks:

> will it be possible for the billing leader to select and update Team Leads of a team?

This feature request seems like it would fit under a super admin role. This customer has had several problems with Team Leads leaving the company and they are unable to assign new one's without Parabol support.

**Comment by gcrickman** [comment]
A [customer](https://app.hubspot.com/contacts/3888472/company/791565527) 🔒 asks:

> We were wondering if there's an option in Parabol to manage the Teams within our organization. 
> For now, as Billing Leader, I do not see any team that has been created in the organization and I know there are several of those. Is it possible for us to see them and manage them? Would it require any role change?

**Comment by treyparabol** [comment]
[A customer](https://app.hubspot.com/live-messages/3888472/inbox/4322036321#email) 🔒 requested assistance. Echoing the above, this fits a super admin role:
> Hi, I am the billing leader for my organization. I am not able to remove the team "Outcomes Summit" from the "Paladin" organization. The usual button to remove the team is not rendered. A prior member added this team, but is not inactive and removed from the org. How do I remove this team?

**Comment by avivapinchas** [comment]
User requested [this in Insights research call](https://www.notion.so/parabol/Pablo-Martinez-c1ad747b72504ab6a17a818493746df4) 🔒

**Comment by avivapinchas** [comment]
Raised by a user and [shared in User Feedback Retro in June '23.](https://action.parabol.co/meet/n1i5vziUh2/discuss/1) 🔒

**Comment by acressall** [comment]
Designs: https://www.figma.com/file/bjpKrqtAf3zO2UMe6QoA17/View---Org-%3E-Teams?type=design&node-id=18-632&mode=design&t=mHQWlPT1EvuRWk8b-0



![Image](https://github.com/ParabolInc/parabol/assets/18582225/aeab2954-2fbd-4885-830a-51607ccb5e79)
