### ISSUE TITLE
AI Summary: emojis limited to 👍 and 👎 

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#7991]
## Issue - Enhancement

To help us better understand how user like or dislike the AI summary, I think instead of providing the full emoji picker for the comment, we limit it to only 👍 and 👎. Furthermore, we put them along the header, sth like this:

<img width="346" alt="Screenshot 2023-04-03 at 17 01 57" src="https://user-images.githubusercontent.com/1879975/229652833-99946470-3ab5-4eec-a0a8-38ae998ff091.png">

In the backend, we could still use the `Reactji Interacted` metric and simply just record `+1` or `-1`.

This way it's much more streamline and easier to do analysis and would enable us to iterate our GPT models (e.g., A/B testing for different models).

### Acceptance Criteria (optional)
   - [ ] User can vote 👍🏻 or 👎🏻 for AI comment
   - [ ] When a vote is cast, `Reactji Interacted` metric is sent to Segment, with value `+1` or `-1` respectively

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by nickoferrall** [comment]
Restricting emojis to only 👍 or 👎 would give us a slightly better understanding of whether users like the summaries, but it makes the UI a bit more busy/cluttered IMO. If we had our own custom model that we were training with user feedback, I think it would be worth doing. 

But for gauging whether users want the summaries, I think we should focus on whether they toggle off the feature. We have a design issue (https://github.com/ParabolInc/parabol/issues/7882) that's being worked on to add that functionality.

**Comment by jordanh** [comment]
I'd love to see the AC for this expanded slightly (or perhaps better or a follow-on issue added) that adds the option for the user to say why 👎 was pressed. I think it will help us optimize the engineering of these prompts better.

I think we got lucky when a user wrote in to support with bug #8491 ... it would be nice to catch other such cases more reliably

**Comment by tianrunhe** [comment]
I still want to do this, so removing the stale label. Might get to it as a side project some time.

**Comment by jordanh** [comment]
Iceboxing for now as I believe we need to focus on other things. @tianrunhe if you feel otherwise, please reopen
