### ISSUE TITLE
Watchdog for GraphQL executor

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8002]
We had an incident with invalid data causing an endless loop when calculating dates from an rrule. This caused our app to grind to a halt. We should have a timeout for this which worst case kills the server if it doesn't finish in time.
In this particular case this would have been the only solution because it was stuck in a synchronous function.

## AC
* [ ] kill server if it does not finish resolve call in 30s

**Comment by mattkrick** [comment]
since this'll have to live outside of the node process could we treat this as a devops problem?
e.g. if CPU/memory is too high, or we try pinging a particular server & it doesn't respond to 2 pings, then we kill that server?

it's possible that a server doesn't resolve in 30 seconds, e.g. we do a long-running query from GraphiQL like `checkEquality`. Even though that process isn't blocking the main thread, it could still take a long time.

**Comment by Dschoordsch** [comment]
Yes, it is partially an infrastructure problem. It could be as simple as increasing the ping frequency and killing the server if it does not reply.
It requires some thought from a developer which interface to use and how to avoid killing the server while it's legitimately busy vs. just stuck.

**Comment by rafaelromcar-parabol** [comment]
I missed this issue, sorry.

In Kubernetes, which is the future infra and I'm concentrating on that, we have Liveness and Readiness Probes. If the readiness probe does not respond X times, the pod is automatically killed and replaced by a new instance of it. A pod is like an instance of a component (a web server, a grapql executor). We must define these Probes for all our components and I need you guys for that. I will request help for that soon. We only defined, months ago, the [Readiness Probe for the Web Server](https://github.com/ParabolInc/helm-charts/blob/main/charts/parabol/values.yaml#L221) which controls only whether that pod is ready or not to receive requests, but it doesn't kill the pod.

There are also memory and CPU limits that can be configured. Memory limits are a best practice and will be in place. If the app arrives to Y MBs/GBs, the pod will be killed and replaced by a new one. Same logic as with the Liveness Probes. For CPU the case is different. You don't want to limit the CPU usage of a component, as you could block a component while you still have CPU available on the underlying system. I'm against it, but we will setup CPU requests (reservations). That means that every pod of the Web Server will have, for example, 2 CPUs assigned, reserved. No other pod can use those CPUs if that Web Server needs them. But any non reserved CPU will be available for everyone to use. This is the regular best practice in Kubernetes (memory requests and limits + cpu requests). Then we will have alerts in case our applications is not behaving as expected and act in that case only. You can see an example of how CPU and Memory are configured for pods [here](https://github.com/ParabolInc/helm-charts/blob/main/examples/full-example/parabol-values.yaml#L65).
