### ISSUE TITLE
User loses access to usage stats if they leave the organization

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8011]
When we enable usage stats, we enable it for organization users and set a feature flag for them.

If a user leaves the organization, they still have the feature flag enabled, but he are is to access usage stats anymore.

They will be able to open usage stats but will see an error:

![image](https://user-images.githubusercontent.com/466991/230605125-4d656813-d7b5-4661-9b7c-4cdf18581aa0.png)

This might be especially confusing for the user because we always show usage stats under the domain name, not under the specific organization name.

The user might still be a member of other organizations under the domain, but access to usage stats is lost now.

**Possible solution:**

Don't show the usage stats link if there are no organizations with usage stats enabled that the user can access. However, this might be confusing too, as usage stats in this case would just disappear.

**Alternative solution:** 

Enable usage stats not per OrganizationUser but per User. Or, in some way, just allow users to see their stats.

**Comment by jordanh** [comment]
Going to close this one to choose not to prioritize it. Will re-open if we hear something from our user base
