### ISSUE TITLE
RiD: Team selection on team-scoped templates

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#8026]
Design issue - https://github.com/ParabolInc/parabol/issues/7955

Team-scoped templates can only be used to create activities on the owner team, so we want a special case for the team selection dropdown when the template is team-scoped explaining the issue + prompting the user to share to the org.

As part of this, we should allow all team members (not just team lead) to change template visibility

[Figma](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?node-id=915%3A26502&t=7C8RKY6hckMOKINM-1)

AC:
- [ ] When a template is team-scoped, clicking the team dropdown shows a popover instead of the normal team selection menu
- [ ] The popover includes the desired copy + a button prompting the user to change the scope to "ORGANIZATION"
- [ ] Clicking the button updates the template scope

**Comment by mattkrick** [comment]
Convo doc: https://www.notion.so/parabol/UX-for-changing-sharing-scope-of-templates-e428dc2538de411c94a34b81adfe9f88
