### ISSUE TITLE
Monthly invoice emails

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#8039]

**Comment by charlesmathias** [comment]
This [customer](https://app.hubspot.com/contacts/3888472/contact/17933951) 🔒 wants to select which email address receives monthly invoices

**Comment by acressall** [comment]
Broke this feedback down into three cards on the Problems, Ideas, and Opportunities Notion:

- [Receipts](https://www.notion.so/parabol/Automated-notification-of-payment-receipts-07c026203c0247278dd218ccbb024eee?pvs=4)
- [Invoices](https://www.notion.so/parabol/Send-Team-customers-invoices-via-email-ba54669aef034c3ea9630b204e7b52f2?pvs=4)
[- Send invoices to specific email
](https://www.notion.so/parabol/Send-invoices-to-specific-email-b6070e89f8a84279ac9e3c7048dd62e3?pvs=4)

**Comment by nickoferrall** [comment]
Relevant Slack thread [here](https://parabol.slack.com/archives/C042E8PGPD4/p1687279937712259) 🔒

**Comment by avivapinchas** [comment]
With this issue now closed https://github.com/ParabolInc/parabol/issues/8480, I suggest we change the AC here to focus on just sending an email notification when a new invoice is available.
