### ISSUE TITLE
Activity library: bookmark or save activities

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8048]
This issue covers design iterations to allow users to bookmark or favorite activities in the Activity Library. Please refer to #8187 for a full list of all related design issues. 

<img width="1387" alt="Captura de pantalla 2023-05-22 a la(s) 11 30 06 a m" src="https://github.com/ParabolInc/parabol/assets/3276087/4d6020ac-55fe-4d71-8d77-e64bb99d387c">

This update includes refinements to:

- Adding UI to support the favorite feature
  - Category
  - Action within the detail view 
- Empty state of the "Favorites" category

| 👉 [Here's the Figma file for full detail.](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1583-39418&t=r5B9rd3ZAJHqmKSO-4)  👈 |
| ------------- |

**Comment by enriquesanchez** [comment]
@ackernaut Pinging for design review 🙌

**Comment by ackernaut** [comment]
I like the iteration here, and left a few comments 🙌
