### ISSUE TITLE
Reflection cant save the data

### ISSUE THREAD

**Issue by kemalgoekhan** [ParabolInc/parabol#8050]
Hello all, 

I try to deploy self hosted parabol on my instance which runs on docker completely. 

![image](https://user-images.githubusercontent.com/110381245/232010422-f83c2e9c-0e72-41b2-830c-4140ba42ff21.png)

The problem is the submitted data on web browser is disapperaring and there is no log on app server which runs node.

https://user-images.githubusercontent.com/110381245/231188858-e92dfeb8-fc7c-406a-bf0b-183ae0c4b17a.png

https://im5.ezgif.com/tmp/ezgif-5-5969388b5e.gif

Logs:

![image](https://user-images.githubusercontent.com/110381245/232011572-df43355e-268f-4e0e-9589-5e5cad609d79.png)

**Comment by Dschoordsch** [comment]
It looks like a problem with the `GoogleLanguageManager`. We should return `null` here:
https://github.com/ParabolInc/parabol/blob/74fb3b89140d7cc944161d32a9098cf7222fe448/packages/server/getGoogleLanguageManager.ts#L11
and then do
```ts
if (!manager) return []
```
after this line: https://github.com/ParabolInc/parabol/blob/7ee3eca865ba5496ef0dc04bcc57c993dd4feb25/packages/server/graphql/mutations/helpers/getReflectionEntities.ts#L8

If you can make the change and do some testing, a PR would be greatly appreciated.

**Comment by jordanh** [comment]
@kemalgoekhan just scrubbing our backlog, have you been able to work through this issue? If not, please add a comment and we'll re-open this Issue
