### ISSUE TITLE
Poker: support custom text fields

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#8051]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/27787301) 🔒 writes:
> We use a custom field for acceptance criteria similar to how it is suggested here https://community.atlassian.com/t5/Jira-questions/How-to-Add-Acceptance-Criteria-to-User-Story/qaq-p/1053304. 
> We use this field to define the done state for the ticket. That is the bit that is missing for us when poker planning using parabol that makes it difficult for us to understand the scope. We use the description field to provide context of the ticket only.

Indeed, it would be great to design an enhancement to Sprint Poker that, if configured, would allow for users to display (and eventually edit) an additional text field. Perhaps, this second field would be located directly below the current area used to display the Description.

### Acceptance Criteria (optional)
Users can:
   - Configure which Jira projects to display secondary fields
   - See the secondary fields when participating in Sprint Poker

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by charlesmathias** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/139911301) 🔒 says:

> Our Jira server has custom fields that are important to our development process. Having only the description show on the item for planning poker means that the facilitator has to swap to the Jira issue to present the issue, which is annoying.

> Our descriptions are also very long due to pictures, it would be nice to be able to expand or change the size of the description for the item being estimated

**Comment by charlesmathias** [comment]
The same [user](https://app.hubspot.com/contacts/3888472/contact/139911301) 🔒 added:

> If a story already has points in Jira when it is imported, it would be nice to see that somewhere.
