### ISSUE TITLE
Admin: Org-level configuration for Self-hosted Integrations

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#8055]
## Issue - Enhancement

[An Enterprise customer](https://app.hubspot.com/contacts/3888472/contact/40608001) 🔒  gave the following feedback:

> Target would like for the Jira Server integration to be at the organization level (currently it’s at the team level). Target has thousands (per Matt Perron) of teams (only a few hundred would use Parabol). Having to setup an integration for each team through a mutation result in a lot of manual steps on our end (e.g. running mutation [How to: Create Jira Server integration provider (notion.so)](https://www.notion.so/How-to-Create-Jira-Server-integration-provider-fda32e577ab74611b062bf19626a22c7) and doesn’t automatically assign new teams the integration when a team is created. They don’t want to move forward with using the Jira Server integration until an organization level integration option is available.

### Acceptance Criteria (optional)
As an Enterprise IT administrator, when I want to allow the teams I support to use self-hosted integration, I want a design that:
   - Allows Billing Leaders (or some other role?) to create, update, and delete Integration Providers for all users in the Org

For the first design iteration, it's assumed that any Integration Provider added to the Org could be used by any Team belonging to the Org. In the future (and in out of scope for this design issue) we could provide permissions associated with each Integration Provider such that only specific teams (i.e. whitelisting) are able to discover and use the Integration Provider

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
@jordanh for this particular use case, wouldn't setting `scope: org` when creating the provider solve their immediate issue?
```
mutation AddJiraToOrg {
  addIntegrationProvider(input: {
    teamId: "",
    service: jiraServer,
    authStrategy: oauth1,
    scope: org,
    oAuth1ProviderMetadataInput: {
      serverBaseUrl: "",
      consumerKey: "",
      consumerSecret: "",
    }
  }) {
    __typename
    ...on ErrorPayload {
      error {
        title
        message
      }
    }
    ...on AddIntegrationProviderSuccess {
      provider {
        id
      }
    }
  }
}
```
