### ISSUE TITLE
Multiples charges incurred on Team subscription when customer failed payments

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8061]
## Issue - Bug

We have seen issues when customer failed their payments and then got duplicate charges on future invoices (e.g., [this one](https://parabol.slack.com/archives/C029ZTH0EL9/p1681386083144879)). Today we we receive payment_fail event, we delete the subscription but somehow we are leaving a balance on that customer account.

### Acceptance Criteria (optional)
- [ ] User won't be extra charged on failed payments

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by tghanken** [comment]
We should also confirm there are no other recent upgrades this applies to.
