### ISSUE TITLE
Updating a problematic icebreaker question

### ISSUE THREAD

**Issue by emilyhebner** [ParabolInc/parabol#8065]
In monitoring Parabol’s twitter, a user tagged us about the following question. The sentiment is that it's uncomfortable and not inclusive:

"If you could live i another historical period, would you? If so, which one?

Could we edit this question to read:

"If you could live anywhere in the world for 3 months where would it be?"

![IMG_4746](https://user-images.githubusercontent.com/100224920/232844846-ae33217a-9310-4006-96c7-2300c7a8b547.png)

**Comment by jordanh** [comment]
I'm closing this one
