### ISSUE TITLE
activeDomain is replaced when a new user joins an org

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8076]
If a user joins an organization with an email domain that differs from the organization's `activeDomain`, then the `activeDomain` is updated to match the new user's email domain."

We relying on activeDomain in multiple places, changing it could lead to unexpected behaviour, example here: https://github.com/ParabolInc/parabol/pull/8040#pullrequestreview-1393756196

**Steps to reproduce:**

- Create an org with an `activeDomain` (Use non-gmail account to do that, e.g. parabol.co)
- See that `activeDomain` is set as `parabol.co`
- Invite a user with an email on another custom domain (e.g. someanotherdomain.com)
- See that after user joined, `activeDomain` of the original org is replaced with `someanotherdomain.com`

**AC:**

- Existing `activeDomain` should never be replaced when new user joins an org

**Comment by igorlesnenko** [comment]
This could be expected behaviour. When a new user with custom domain joins we calculate `activeDomain` again based on most used domain: https://github.com/ParabolInc/parabol/blob/6367a1d3c898a0ab6f0f27619f9d00345cc6a4bb/packages/server/billing/helpers/adjustUserCount.ts#L31

**Comment by tianrunhe** [comment]
That's right, this is the expected behavior. We have examples of this before. As you discovered, the logic is to calculate the "dominant" domain but we don't take "common email providers" (e.g., gmail.com, hotmail.com) into consideration.

**Comment by igorlesnenko** [comment]
Thanks @tianrunhe! In this case I'll check if sudden change of `activeDomain` might affect our teams limit functionality, and will close this issue.

**Comment by jordanh** [comment]
Just a note that I had a look at this one as PM. @igorlesnenko I'll await what next action you think is appropriate

**Comment by igorlesnenko** [comment]
Teams limit should be fine. `We use activeDomain` to check if there are active deals on the hubspot. After teams limit is triggered we don't use `activeDomain` anymore.
