### ISSUE TITLE
Non-facilitators can proceed to the Reflect phase

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8077]
As a facilitator, on two occasions, I've created a retro and shared a link, but non-facilitators haven't been able to add reflections because it's still on the Icebreaker.

I think that non-facilitators should be able to skip ahead to the Reflect phase even when the active phase is the Icebreaker. It would work in the same way non-facilitators can skip to the Agenda Item phase during Solo Updates in a Check-In.

### AC

- [ ] Non-facilitators can proceed to the Reflect phase even if the Icebreaker is the active phase

**Comment by avivapinchas** [comment]
With the Team Health feedback process, 2 users requested this, saying: 
> Our team can't add tickets to the retro because the health phase blocks them 

> Would be helpful if members could do the team health check and then advance to adding reflections instead of having to wait to get to the team reflections until the facilitator moves the board
