### ISSUE TITLE
TypeError: Cannot destructure property 'isConnected' of 't' as it is undefined.

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8084]
https://parabol.sentry.io/issues/3921990898/?referrer=github_plugin

```
TypeError: Cannot destructure property 'isConnected' of 't' as it is undefined.
  at <anonymous> (./packages/client/components/DashboardAvatars/DashboardAvatars.tsx:109:14)
  at Array.forEach (<anonymous>)
  at sortedAvatars (./packages/client/components/DashboardAvatars/DashboardAvatars.tsx:107:17)
  at j (./packages/client/components/DashboardAvatars/DashboardAvatars.tsx:104:25)
  at Set.forEach (<anonymous>)
...
(45 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
1k users, 1k events.

**Comment by avivapinchas** [comment]
Closed in favor of https://github.com/ParabolInc/parabol/issues/8088

**Comment by Dschoordsch** [comment]
While they're very similar and might be worked on in conjunction, the symptoms differ. Here the user is nullish while in #8088 the user appears valid and the team member is nullish.

**Comment by igorlesnenko** [comment]
There were 13 events for the last 24 hours, I'll set it as P2 so we can look a bit later.

**Comment by igorlesnenko** [comment]
Now only 3 errors for the last 30 days, closing, unassigning in sentry, if it will appear again then it will be reported by error reporter again
