### ISSUE TITLE
Propose approach for adding new users to the RiD feature flag

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#8093]
We'd like new users who sign up through an RiD landing page to be automatically added to the feature flag and redirected to the correct template.

Propose a solution, with a focus on technically derisking the solution.

AC:
- [ ] RFC written in Notion proposing the flow for adding new users to the feature flag + redirecting to the correct template, including notable technical details

**Comment by jordanh** [comment]
There are two use cases I can think of that we might want to consider for the RFC:

   * A new user signs up and we want them to get the feature flag 100% of the time
   * A new user signs up and we want them to get the feature flag less than 100% of the time

I think the former case is obvious: a potential new user lands on one of our shiny new landing pages and signs up. We're going to want them to get the new feature flag all the time.

The latter case is less obvious. Let's say we forecast 3,000 signups each week. Perhaps we want 1 in 100 to get the new feature flag. It might be nice to have a parameter that probabilistically assigns the flag, too.
