### ISSUE TITLE
Move Pushing client build to S3 out of webpack & into syncToCDN

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8101]
Today, we push the client build to our CDN as part of our webpack build.
In a future where we build once and deploy to multiple PPMIs, we'll need to push the client build to multiple CDNs.
That requires decoupling the push from the build. 

We already do something similar with meetingTemplate images in #8071.  We can build off that.
We could special case our own cloud build, but it'd probably be cleaner to not have special cases & call syncToCDN for every predeployment we run. 

AC
- [x] chat with @rafaelromcar-parabol to figure out how best to do this (are client assets kept in the docker image)
- [x] syncToCDN does what the webpack S3Plugin does today: It pushes the entire build directory to the CDN listed in the .env
- [x] S3Plugin is removed from webpack & the app
- [x] favicon uses the runtime CDN, it is not hardcoded
- [x] initial JS/CSS in index.html point to the CDN
- [x] webpack's `publicPath` is not determined at build time. it is determined by the server at runtime using the webpack var or 'auto'
- [x] sourcemaps are available
- [x] local filestore finds the build files at /static
- [x] cdn filesstore finds the build files at /build/vX.Y.Z
- [ ] verify `jiraPlaceholderBuffer` is correct 
- [ ] pushing sourcemaps to sentry should occur in pushToCDN, not during the circleCI script
- [ ] serveStatic should only serve client assets
- [ ] only 1 reference to action.parabol.co being hardcoded
- [ ] no references to action-files.parabol.co hardcoded
- [ ] remove protocol relative uses of the CDN_BASE_URL
- [x] css link needs crossorigin in initial index.html
- [x] manifest to build dir
- [x] empty the build dir before writing to it
- [ ] dynamic fetches, like extra CSS, have a dynamic publicPath

Estimate: 8 hours

**Comment by mattkrick** [comment]
@rafaelromcar-parabol 

Questions:
- We've got 2 servers (GQLExecutor, Web), a couple scripts (migrate, postDeploy) and the client bundle (/build). Are we putting all of these in a docker image?
-My goal is during pre-deploy, after the migrations run, we call `pushToCDN`, which pushes all the client assets to the CDN defined in the .env. Would this work for you?

**Comment by rafaelromcar-parabol** [comment]
> We've got 2 servers (GQLExecutor, Web), a couple scripts (migrate, postDeploy) and the client bundle (/build). Are we putting all of these in a docker image?

Everything produced by the current `yarn build` is going into the Docker image. If we use the --no-deps flag, only `dist` folder is.

> My goal is during pre-deploy, after the migrations run, we call pushToCDN, which pushes all the client assets to the CDN defined in the .env. Would this work for you?

It should work for my but =>

Could you define pre-deploy? Could you draw a flow diagram clearly showing the process and the steps? From your comments, if I understand it correctly, the process would be the following:
- Pre-deploy
  - database-migrations
  - push-to-cdn (only after database-migrations have ended successfully)
- Rolling application: both the Web Server `node ./dist/web.js` and the GQL Executor `node ./dist/gqlExecutor.js` are deployed in parallel.
- Post-deploy: the post-deploy script `node ./dist/postDeploy.js` is executed after the Web Server and the GQL Executor is running. Additional question => do we need the to wait until all new Web Servers and GQL Executors are up and running to run the post-deploy, or it can run without them?

**Comment by mattkrick** [comment]
> Everything produced by the current yarn build is going into the Docker image. If we use the --no-deps flag, only dist folder is.

what would you like to happen to the client assets in `/build`? I think we need an environment that includes vars like `CDN_BASE_URL` so we can push that directory to their CDN, right?

> do we need the to wait until all new Web Servers and GQL Executors are up and running to run the post-deploy, or it can run without them?

With the change implemented last week, this no longer has to happen in post deploy. we can do this in predeploy, too! Everything else you said is correct

**Comment by rafaelromcar-parabol** [comment]
> what would you like to happen to the client assets in /build? I think we need an environment that includes vars like CDN_BASE_URL so we can push that directory to their CDN, right?
Yes, I think we should have a variable to tell the app, I imagine the script push-to-cdn, where to push the assets. This might be an URL or the name of a GCP GCS or AWS S3 bucket so the app knows where to push.

Ideally static assets wouldn't be included into the Docker images, but I think it isn't a problem today and we shouldn't spend time on this for now.

If I'm getting things correctly, we have three use cases (for now):
- Local storage
- AWS S3
- GCP GCS

The common variables for all of them are:
- FILE_STORE_PROVIDER: [local | s3 | gcp-gcs]
- CDN_BASE_URL: if I'm not mistaking, this is the URL base of the URL where clients will request the assets. It is then independent of the provider.

Then we should have particular variables for each provider. For AWS S3 and for GCP GCS we would need the bucket [GCP_GCS_BUCKET | AWS_S3_BUCKET] and for local storage we would need a local path or nothing at all?

It would be great to have a documentation on the three providers with the common vars and their possible values and also the specific values per provider.

@mattkrick

**Comment by mattkrick** [comment]
that all sounds right! I haven't done any work on moving to GCS so i've got no clue what kinda stuff they require. I assume it looks pretty similar to S3

**Comment by rafaelromcar-parabol** [comment]
Great!

GCP GCS should be similar, but we need to check the auth part of that integration as we could do it without any secret if we are deployed in GCP GKE. We should work together on that during the summer.

**Comment by mattkrick** [comment]
you're talking about Google's ADC?

IMO, I think API keys would be a little easier:
- we already use API keys for Google OAuth & Language service, we may even be able to reuse the same keys!
- devs wouldn't need to install gcloud CLI on every machine they work with. This is really the big one. It's more involved than copying & pasting keys: https://cloud.google.com/docs/authentication/provide-credentials-adc#local-dev 
- make it simpler for customers. The customers we have today that manage their own instances can struggle with getting parabol set up. If we remove additional complexity, it will save us all a bunch of time!

**Comment by rafaelromcar-parabol** [comment]
Developers will need to install gcloud on their machine as they will need it to: 
- List and download docker images produced by our pipelines.
- Connect to our Kubernetes clusters, even in read-only mode, as they do today with Staging and Production.
- Connect to any database in our system.

gcloud and kubectl are regular tools used by developers in cloud environments, with the correct permissions set (read-only in the 99,99% of the cases). Also, it is a security risk to provide GCP Service Accounts keys to our developers in order to connect to any of our resources. In the documentation you share they even put a note about that there `Creating a service account key is a security risk that should be avoided if possible. If you must create a service account key, make sure you keep it secure.` A developer that leaves the company has everything they need to continue using our systems. There is an alternative to it and we should use it. I'm not saying we should do it right now, but we should clearly do it in the future (Q4 this year probably) when our focus goes to security.

That said, we should be able to provide both options: auth providing the GCP SA email and key and at the same time supporting workload identity for our GKE clusters. Same goes for AWS S3. I have done that multiple times, it shouldn't be a problem 😄

**Comment by mattkrick** [comment]
Basically, this work draws a line between "Build" and "Predeploy"

Build:
- Compile the server & client assets
- Push sourcemaps to sentry/datadog (this could be in predeploy, but we only want to do it once per version 🤔 )

Predeploy:
- Migrate DBs
- Push meeting templates to CDN
- Push client assets to CDN
- Apply env vars to built assets
  - This is tricky because built assets must include paths to the host/CDN. Things like the built index.html and sw.js must get rewritten
  - We could also perform this at runtime if that works better

**Comment by rafaelromcar-parabol** [comment]
Pushing to Sentry and Datadog is something related only with our environment and our tools and particular way of deploying. I wouldn't put that into pre-deploy.

**Comment by mattkrick** [comment]
agreed, yeah i think it belongs in build.

As I've gone through this, I think I've over-engineered it. It all works, but having to overwrite build assets in preDeploy to account for different CDNs is more complex than necessary. webpack assets will also have to rewrite their publicPath at runtime. It's all just a bit more complex than I'd like.

In the name of simplicity, I think the better approach is to have all assets come from `/static`. If our server performance is an issue, then we can have our reverse proxy redirect `/static` to our CDN. This does a few things:
- The app is completely unaware of a CDN, which is an infra problem IMO
- the predeploy step is MUCH SIMPLER. It does not rebuild manifest, sw.js, built assets, index.html, etc. It's the same code & URLs for every deployment
- no CORS issues! This is the big one. All assets are coming from SAMEORIGIN
- more asset caching between versions! /v1.0.0/foo.js and /v1.1.0/foo.js are the same, but they're not treated the same because their path is different. if we do away with build versions in the path then we can cache between versions, which means parts of our app

The risk with this is higher latency because requests will go through our server & get redirected to the CDN.  Today, requests already go through cloudflare to get to our server & our CDN. I don't know if cloudflare -> proxy -> CDN is going to be any slower than cloudflare -> CDN!
Proposal:
- all static assets are found in /static
- /static/build keeps all built assets for ALL builds. no
