### ISSUE TITLE
Bug: App auto updating subscription quantity in Stripe

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8104]
## Issue - Bug

Subscriptions in Stripe are being auto updated based on active user count, causing customer invoices to show the wrong tier and dollar amount.  

[Slack discussion here. ](https://parabol.slack.com/archives/C03C3J42WDU/p1682453340586379) 🔒 

A customer this just happened to [here. ](https://dashboard.stripe.com/customers/cus_HLqtiZmjTSHhNm) 🔒 

### Acceptance Criteria (optional)
- [ ] When an enterprise subscription is created, the app should not update its subscription quantity

**Comment by tghanken** [comment]
This has happened to 7 more customers since #8105 was merged.  Re-opening this bug, and will work on a fix.
