### ISSUE TITLE
UI: Create generic `Dialog` component 

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8107]
Currently all our modals dialogs are different. 

For example new meeting and start recurrence have different close button implementations:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/466991/234565706-55253e6b-500f-40ed-869f-b84b5fbc8b8e.png">

<img width="428" alt="image" src="https://user-images.githubusercontent.com/466991/234565801-5b4f65d3-f7f2-4fff-b789-a6c15591d01a.png">

We also recreating some basic parts every time:

https://github.com/ParabolInc/parabol/blob/183f543b74b49f40d19eb1829b79e0c8d2a119a2/packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx#L40-L44

https://github.com/ParabolInc/parabol/blob/afa812a1fc18e6e8b12b8fde877b7f9c3ed1b2e3/packages/client/components/ReviewRequestToJoinOrgModal.tsx#L104-L110

Would be good to have a generic, responsive dialog component using `tailwind` and for example `radix-ui`.

**Comment by igorlesnenko** [comment]
Tagging @BartoszJarocki just in case

**Comment by BartoszJarocki** [comment]
@igorlesnenko maybe we should create a separate label just so it's easy to see all the design system related tasks?

**Comment by igorlesnenko** [comment]
@BartoszJarocki I just created a milestone like this https://github.com/ParabolInc/parabol/milestone/168
Feel free to delete it/select better solution to track these
