### ISSUE TITLE
Fix memory leak on server

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8109]
We've got a memory leak on our server. It's been that way for about a year, so it's not urgent.
Fixing memory leaks is a great skill to have, so if you'd like some help in tackling it reach out or stop by my office hours. Most of the tooling is already in place!

![App-Host Memory breakdown](https://user-images.githubusercontent.com/5514175/234643536-19b554ab-b0f3-4307-849b-b8e8ff9cb0f3.png)

**Comment by mattkrick** [comment]
Promoting to P1 as this is causing downtime now

**Comment by mwermuth** [comment]
Hey @mattkrick do you have any update on this? I think you had a look into this right?

**Comment by mattkrick** [comment]
Yep, 1 leak down, 2ish to go

**Comment by mattkrick** [comment]
We have 3 memory leaks left.

The biggest offender is dd-trace. I'm upgrading it & hoping that fixes it. I don't think it will. Their lib is FULL of memory leaks: https://github.com/DataDog/dd-trace-js/issues?q=is%3Aissue+is%3Aopen+memory+leak

The 2nd biggest is draft-js. We're moving away from it, so I'm not gonna spend the time fixing it.

The 3rd biggest is relay, it's hanging onto the ServerEnvironment that we set up. There was a PR to fix this, but the relay team never merged it, so if we want to stay on main, then we'll need to just destroy the objects ourselves. E.g. instead of 100k objects full of other objects, it's 100k empty objects. Not a perfect fix, but it means we don't have to battle Meta to get a PR across the line.

**Comment by jordanh** [comment]
@mattkrick just scrubbed this. After checking on the `dd-trace` leak and deciding which action you'd like to take could you please close this issue and re-open issues for the other two so they may be prioritized separately? ¡Muchas gracias senior!

**Comment by mattkrick** [comment]
- Bumping dd-trace in #8389
- Fixing the relay mem leak in #8389
- Created #8414 as prereq to further troubleshooting dd-trace
- Ignoring DraftJS mem leak. We need to get rid of it for security reasons, too.
