### ISSUE TITLE
Azure DevOps: imported tasks in poker meeting are stop working after some time

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8139]
A user reported a problem:

After integrating azure devops, importing tasks in poker meeting, after some time all tasks become unavailable (see the screenshot):

<img width="845" alt="image" src="https://user-images.githubusercontent.com/466991/235925635-b20937b8-0643-450c-b9db-d2360d577a12.png">

At the same time the integration seems to be working because user can still see the issues in the scope tab.

**AC:**

- Identify what cause poker meeting to break
- Fix the bug

**Comment by Dschoordsch** [comment]
Related: https://github.com/ParabolInc/parabol/issues/7114

**Comment by Dschoordsch** [comment]
I suppose there are at least 2 issues at play: we're using the wrong auth token which expires too fast and we're not properly refreshing it in time.

**Comment by lilicaruso** [comment]
Lili let 🔒 [user](https://app.hubspot.com/live-messages/3888472/inbox/4468736649#email) know when this is fixed.

**Comment by igorlesnenko** [comment]
I was able to reproduce this on prod, the meeting I created 2 days ago with azure became broken after 24 hours or more. Looks like token issue

**Comment by jordanh** [comment]
@igorlesnenko this is indeed correct. Shortly after shipping this to beta it was discovered that we hadn't implemented the correct means of refreshing the server token. In order to resolve that bug, this enhancement will need to be made

**Comment by jordanh** [comment]
Found the issue! (h/t @mwermuth https://github.com/ParabolInc/parabol/issues/7006

@nickoferrall can share more

**Comment by jordanh** [comment]
(just adding a note for record keeping that this came up during scrub)

**Comment by jordanh** [comment]
Scrubbed again. Going to explicitly recommend prioritizing this one until all other p2's are closed

**Comment by mwermuth** [comment]
Came up during backlog grooming and @Dschoordsch mentioned that this is prioritized but it is currently taking a moment to get through all their prioritized issues.
