### ISSUE TITLE
Redis Memory Leak

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8176]
It's clear we have a redis memory leak.
Looks like it started sometime between April 15 - April 23.
To fix, use something like redis commander or similar to find the list of keys & determine which ones aren't being flushed.

<img width="1513" alt="Screenshot 2023-05-10 at 10 08 23 AM" src="https://github.com/ParabolInc/parabol/assets/5514175/18a0ca63-4906-462f-bdaf-684c15c729d1">

AC
- [ ] root cause identified
- [ ] patch written in the code
- [ ] manual flush of offending keys triggered

**Comment by mattkrick** [comment]
Root cause:
- the `presence:` and `team:` keys are growing unbounded
- this was caused by https://github.com/ParabolInc/parabol/pull/7208
- that PR changed the way we manage presence. instead of flushing it whenever a server came online, it would store the serverID on the presence object & then when a server goes down, it would flush all presence for those users connected to that server

It works locally, so the question is-- why doesn't it work in prod? Since `SERVER_ID` isn't unique, perhaps the name gets re-used & so it looks like the server doesn't go down?

**Comment by Dschoordsch** [comment]
If a server comes up, should it just clean all the keys that belong to its current `SERVER_ID`? That way it wouldn't matter if it's reused.

**Comment by rafaelromcar-parabol** [comment]
@mattkrick set Redis policy to `allkeys-lru` while this is fixed. That cleaned up quite many keys.

**Comment by mattkrick** [comment]
@Dschoordsch that could work! the only tricky part is queueing all connections until the server is done purging its records from redis. Otherwise, it's possible that a person connects to the server before the purge happens & their new presence gets removed with the old ones. That's why I only call it in the `onKill` handler after a server is no longer accepting new connections.

Digging into it more, I looked at my own record in prod:

```
LRANGE presence:google-oauth2|X 0 -1
1) "{\"lastSeenAtURL\":null,\"serverId\":\"0\",\"socketId\":\"ws_mpktv3YTD2\"}"
2) "{\"lastSeenAtURL\":null,\"serverId\":\"01\",\"socketId\":\"ws_mpktwHjH44\"}"
3) "{\"lastSeenAtURL\":null,\"socketServerId\":\"0\",\"socketId\":\"ws_n4fJP7O3rG\"}"
```

The first 2 records use `serverId` instead of `socketServerId`, which is the old name. 
This makes sense-- my PR changed the interface of the presence record AND removed flushing presence from the `postdeploy` script 😞 . I should have  waited 1 release to remove `postdeploy` because the old records never got flushed.

That doesn't explain the whole story, but it should fix part...

**Comment by mattkrick** [comment]
Looks like the memory leak is still there, but not as easy to see. We'll give it a couple more week before we do more investigating...

**Comment by igorlesnenko** [comment]
I found this error which might be related

```
ERR wrong number of arguments for 'hdel' command
```

https://parabol.sentry.io/issues/3024781886/?query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=22
