### ISSUE TITLE
Standups: remove CSV export

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8184]
### Issue - Bug

Currently the option to export to CSV from a Standup summary does not work. Clicking the option does nothing. 

<img width="736" alt="Captura de pantalla 2023-05-11 a la(s) 4 14 00 p m" src="https://github.com/ParabolInc/parabol/assets/3276087/3b27f868-e622-43f1-8a9f-a635ccd3abf4">

Kudos to @acressall for reporting it 🙌 

- **How serious is the bug?** P2
- **OS:** All platform
- **Browser:** All browsers

### Acceptance Criteria (optional)
Users can:
   - Click on "Export to CSV" and get their file

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by ackernaut** [comment]
What would be included in the export? The responses? The thread comments?

As we discussed, if there’s not a good use case for exporting we could simply remove it for the standup summary.

**Comment by jmtaber129** [comment]
Let's just remove the button for now and add back if it's requested

**Comment by jordanh** [comment]
Let's remove it until we get feedback that folks want CSV export. I will update issue description now
