### ISSUE TITLE
Activity library: refinements to detail view

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8185]
This issue covers design iterations and refinements to the Activity detail view. Please refer to #8187 for a full list of all related design issues. 

<img width="1289" alt="Captura de pantalla 2023-05-19 a la(s) 4 06 01 p m" src="https://github.com/ParabolInc/parabol/assets/3276087/e30c82c7-4140-4519-9c14-d3d8562342e2">

This update includes refinements to:

- Layout and info display
- Updates styles for reflect #8220
- Layout of Edit mode

| 👉 [Here's the Figma file for full detail.](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1463-33137&t=r5B9rd3ZAJHqmKSO-4)  👈 |
| ------------- |

**Comment by enriquesanchez** [comment]
@ackernaut Pinging for design review 🙌

**Comment by ackernaut** [comment]
Nice work, here. I left a few comments. I’m mostly interested in seeing a little less movement of components between read-only and editing views. E.g. the edit button is upper right of the content, but the done button jumps up to the upper right of the header. Just some thoughts to consider!
