### ISSUE TITLE
`yarn build --no-deps` requires queryMap & yarn.lock

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8202]
AC
-  [ ] queryMap & yarn.lock get compiled into the build
-  [ ] queryMap should be able to get imported
-  [ ] yarn.lock is probably used to determine the project root. we can instead re-use the `__PROJECT_ROOT__` webpack var.
-  [ ] In fact, let's completely remove `getProjectRoot` in favor of a webpack var

NOTE: government clients still need to scan yarn.lock so we might need to leave that in here, but we should _not_ depend on it

**Comment by rafaelromcar-parabol** [comment]
This PR must include changes on the pipeline.dockerfile, removing the COPY commands that copy both queryMap.json and yarn.lock to the Docker image.

Just leaving here a note to avoid forgetting about it 😸

**Comment by jordanh** [comment]
I'm going to randomly pick a backlog owner for this one

**Comment by mattkrick** [comment]
while trying to troubleshoot a memory leak we got an error & this was the root cause. gonna put it on my plate for this sprint

**Comment by mattkrick** [comment]
- queryMap.json is removed
- we can't use the build-time __PROJECT_ROOT__ during predeploy because the directory where the app is built will not be the same as the one where predeploy is called. 
- we can't remove yarn.lock for security testing
