### ISSUE TITLE
Sprint Poker: Azure DevOps cannot vote to custom issue types

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8219]
Custom issue types do not appear in the search (for example "Product Backlog Issue" as compared to built in "Feature", "Bug" etc.). If they're added via WIQL query, the user cannot vote to any field but only to comments.

**Comment by charlesmathias** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/141998051) 🔒  says:

> I'm trying out the new Azure DevOps Beta but struggling to get anything back in results other than "Features". We currently use custom-named user items - which differs from the Azure DevOps default of type "User Story" which might be why nothing is coming back for me.
