### ISSUE TITLE
Activity library: new UX

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8220]
This issue covers design iterations and refinements to the general layout of the Activity Library. Please refer to #8187 for a full list of all design issues.

<img width="1075" alt="Captura de pantalla 2023-06-08 a la(s) 5 26 07 p m" src="https://github.com/ParabolInc/parabol/assets/3276087/84858fd8-2569-49f2-a5f3-62661e659106">

This update includes refinements to:
- Responsive layout
- Header, category navigation, and seach
- Activity grid and sections
- Placement of the Create custom activity button

| 👉 [Here's the Figma file for full detail.](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1402-34308&t=CwIWnJxU58KnyxgR-4)  👈 |
| ------------- |

**Note:** Please refer to #8190 for specifics on Activity cards.

**Comment by enriquesanchez** [comment]
@ackernaut Pinging for design review 🙌

**Comment by ackernaut** [comment]
Hey @enriquesanchez I left comments! Nice work here! The direction for the header area is good, I had some thoughts on search position. The grid work is 💯 🔥 and will nicely support testing groupings of activities.
