### ISSUE TITLE
Activity library: preview on hover

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8254]
Allow users to preview the activity without needing to open the activity detail view.

<img width="1518" alt="Captura de pantalla 2023-06-12 a la(s) 3 06 32 p m" src="https://github.com/ParabolInc/parabol/assets/3276087/3880be01-17df-4ed2-8c0d-6fbe84cf1920">

[👉  Figma explorations](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1722%3A37753&t=N33eRFCBQUtTuofW-1)

**Comment by enriquesanchez** [comment]
From this Slack comment:

>Before we had a menu where we could see [...] the columns it would have if created and its description. Now, [...] **_I need to click on it to see what's inside_**.

**Comment by BartoszJarocki** [comment]
How will it work on mobile?

**Comment by enriquesanchez** [comment]
@BartoszJarocki Since there's no way to replicate the hover action in mobile, I think we can defer this interaction to the platform's native "peek and pop" (aka 3D touch), where you long press a link and it opens a small preview of the page the link directs to. Both iOS and Android support it.

**Comment by BartoszJarocki** [comment]
@enriquesanchez how are we suppose to handle the scenario where the prompt does not fit one line and the whole prompt list is needs more space than it's available in the card? 
1. Use current behavior, let the card grow higher (other cards will follow and grow too)
2. Change the current grid behavior and make the cards fixed height and allow card to scroll when there's not enough space

I personally feel like, using something like [Hover Card – Radix UI](https://www.radix-ui.com/docs/primitives/components/hover-card) would handle this scenario without constraints of card height and width. Also, I'm not sure if fixing all the edge cases of putting this within a card would be faster, than just implementing a hover card. If we gonna go with showing content within a card, we'd need to have designs that'd cover concerns I described above.

**Comment by enriquesanchez** [comment]
@BartoszJarocki 

>Change the current grid behavior and make the cards fixed height and allow card to scroll when there's not enough space

This is what we had thought. I prefer scrolling than making the cards taller 👍 

>I personally feel like, using something like [Hover Card – Radix UI](https://www.radix-ui.com/docs/primitives/components/hover-card) would handle this scenario without constraints of card height and width

I agree this solution is not 100% ideal, but it gets us closer. [We had some concerns](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi?node-id=1722:38104#466806202) around the hover popup being annoying (as it happens on every single card), so I think we need a little more time to find a better alternative.

**Comment by BartoszJarocki** [comment]
<img width="204" alt="Screenshot 2023-06-16 at 14 38 18" src="https://github.com/ParabolInc/parabol/assets/1017620/226ae2a2-f323-43af-a283-995a1baba8c9">
@enriquesanchez If card isn't wide enough and there's no space to show this in one line, how should we wrap the text in this case?

**Comment by enriquesanchez** [comment]
@BartoszJarocki 

> If card isn't wide enough and there's no space to show this in one line, how should we wrap the text in this case?

Thanks for raising this point. [I've updated the mockup to reflect this case](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1865-40796&t=ojv4J7TM1uy6T6LI-4). I think keeping everything in one like is a safe choice. 

>what do we show for normal meetings when hovering? ie. standups, check in etc?

We have [a couple of examples here](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1793-44315&t=ojv4J7TM1uy6T6LI-4), for both standups and check-ins. It is the same pattern we are using in the other cards: icon + text

**Comment by enriquesanchez** [comment]
Closing as it looks like everything has been addressed 👍
