### ISSUE TITLE
Using Jira sub-tasks as sub-tasks in Parabol

### ISSUE THREAD

**Issue by hichamine** [ParabolInc/parabol#8260]
A [user](https://app.hubspot.com/contacts/3888472/record/0-1/137704401) 🔒 said that when taking Jira tasks to their Parabol meetings, they found it really hard to find sub-tasks of the main Jira tasks in their Parabol meeting, and that it'd save them a lot of them if they could be able to find sub-tasks of the main Jira task when integrating with Parabol,

**Comment by jordanh** [comment]
I think they may be able to do this with a JQL search... let me check
