### ISSUE TITLE
refactor ActivityDetails to decrease overfetch

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8262]
`ActivityDetails` has a graphql fragment that has a few extra fragments & fields than it uses. This can be problematic in reading & refactoring the code because it's difficult to know which fields can be removed.

AC
- [ ] in the gql fragment, every field requested in ActivityDetails is used by Activity details
- [ ] the fragment spreads included are for components that are direct children of the ActivityDetails
- [ ] sort order of templates deprioritizes older templates

Estimate: 2 hours

**Comment by mwermuth** [comment]
Hey @mattkrick will you still have time to close this in this sprint, although you are part of DevOps now? Or do you want to hand this off?

**Comment by mattkrick** [comment]
it's all complete in #8293, just waiting for review
