### ISSUE TITLE
Checkout flow: Upcoming invoice only visible for Team tier

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#8268]
## Issue - Enhancement

On the billing view, showing the upcoming invoice / invoice estimate creates confusion for enterprise customers and makes negotiating renewals more complicated. [See discussion for context](https://parabol.slack.com/archives/C03C3J42WDU/p1680602215633269). 

### Acceptance Criteria (optional)
Users can:
   - see an estimate when on the team tier
   - only view paid invoices when on the enterprise tier

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by nickoferrall** [comment]
Hey @acressall, once this PR (https://github.com/ParabolInc/parabol/pull/8474) has been merged, this will be fixed. It should be fixed for users after either this week's release or next
