### ISSUE TITLE
UI: Change `Checkbox` component to add size and color props

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8273]
See #8257
Currently, we have to style `Checkbox` using styled components like this:

```
const StyledCheckbox = styled(Checkbox)({
  '&&': {
    width: 24,
    height: 24,
    marginRight: 8,
    color: PALETTE.SKY_500
  }
})
```

AC: 
- Allow to specify `size` and `color` props

**Comment by BartoszJarocki** [comment]
This is something to think about more. Depending on how many colors we need to support the solution may differ. I'll be working on the design system for the frontend so I'm happy to handle this as well.

**Comment by jordanh** [comment]
Scrubbed – I'd like to add this to a squad's backlog but based @BartoszJarocki's reply I'm not sure where to put it. @BartoszJarocki should I give this to us on Land & Expand or does @igorlesnenko feel so strongly about that he'd like to forge ahead with the refactor and take advice from you @BartoszJarocki?

**Comment by BartoszJarocki** [comment]
happy to take it and discuss it with @igorlesnenko. if @igorlesnenko wants to take it and discuss it, that works too :)

**Comment by igorlesnenko** [comment]
@BartoszJarocki feel free to take it, I'm ok with any option

**Comment by jordanh** [comment]
Scrubbed again & assigned
