### ISSUE TITLE
5% of Agile Users on Marketing Site Get RiD Feature Flag

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#8291]
Along [our plan](https://www.notion.so/parabol/Structured-Conversations-Product-Requirements-Phase-1a-Retros-in-Disguise-1bfb914e97f643f9be419106d609f073?pvs=4#f4c9168448224423ab4566878ca0ec39)​ 🔒 , we're looking to observe the behavior of up to 500 new users who sign up using our "Agile" (i.e. "Classic") landing pages (e.g. parabol.co, https://www.parabol.co/resources/how-to-run-an-online-sprint-retrospective/, etc.)

### Acceptance Criteria
- [ ] Gathered a list of all "Agile" pages, added appropriate parameters to signup link on these pages to probabilistically assign new signups to RiD feature flag at a rate of 5%

**Comment by jmtaber129** [comment]
Closing as this is done with https://github.com/ParabolInc/parabol/pull/8337
