### ISSUE TITLE
Activity library: when starting an activity we default to the first team on the list instead of last used or route context

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8312]
>  if you are on a team page and start a meeting there, the old meeting selector will set the team accordingly but the activity library seems to always choose the 1st team sorted alphabetically? ([from Slack](https://parabol.slack.com/archives/C042HTVBH8D/p1685636102060229) 🔒 )

IIRC we also used to default to the last team used, and now we always default to the 1st team on the list

### AC:
- Previous behavior for team selection when starting a new meeting is restored

**Comment by jordanh** [comment]
Looked at this during scrub. It would be great to add to our next sprint.
