### ISSUE TITLE
Checkout Flow: improve responsiveness

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8317]
This PR made the Plans section responsive: https://github.com/ParabolInc/parabol/pull/8075

We still need to get the other sections of the checkout flow looking good on mobile and tablet.

### AC

- [ ] The checkout flow is fully responsive

**Comment by nickoferrall** [comment]
Hey @acressall, I was taking a look at the checkout flow on mobile, and I think things are already looking good. Perhaps the other sections followed the responsive UI you built for the Plans Section.

Would you mind taking a look at this Loom to see whether you agree?

**Comment by acressall** [comment]
Thanks for the Loom @nickoferrall! I actually did all the panels in the one PR before 😉 Good to confirm it works in the "paid" state too. I think we're safe to close this!

**Comment by nickoferrall** [comment]
Amazing, this is a lovely surprise 😄 !
