### ISSUE TITLE
Team Health: Add metrics

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8324]
### Acceptance Criteria (optional)
- [ ] `Meeting Started/Joined/Completed` events should contains a new boolean property `healthCheckEnabled`, just like `disableAnonymity`

<img width="644" alt="Screenshot 2023-06-05 at 14 59 33" src="https://github.com/ParabolInc/parabol/assets/1879975/eed43df8-b620-4a93-bbe7-b466bb17e2fa">

- [ ] `Meeting Settings Changed` events should contain the same `healthCheckEnabled` property. See [here](https://github.com/ParabolInc/parabol/blob/935d5bf131146cfb64a015716c0058f6cf26c148/packages/server/utils/analytics/analytics.ts#L52).

- [ ] Do we have metrics on what user voted? 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
I had missed a couple of places, but this was fixed in #8396
