### ISSUE TITLE
Rename postDeploy to predeploy

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8334]
AC
- [ ] rename postDeploy to preDeploy
- [ ] run preDeploy in predeploy for in app.json
- [ ] add README.md for all predeploy scripts

will CC @rafaelromcar-parabol in PR review

**Comment by rafaelromcar-parabol** [comment]
Hey @mattkrick do you have an ETA for this issue? I would like to have this done and merge before we start using the GCP Staging, so the hooks are already configured as they should.

**Comment by mattkrick** [comment]
end of week
