### ISSUE TITLE
Notification Subscription Payload received without field: AddPokerTemplatePayload/RemovePokerTemplatePayload

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#8338]
[Logs | DataDog](https://app.datadoghq.com/rum/sessions?query=*activity*/library*%20@session.has_replay:true%20@type:session&cols=&event=AgAAAYiSPJhq9VdZowAAAAAAAAAYAAAAAEFZaVNQTFVpQUFEYlpLb1lIbkp0dEFBQQAAACQAAAAAMDE4ODkyNDAtM2U5MC00YTZkLTkyNWUtYzQ3N2NiZmJhYzMz&p_tab=issues&saved-view-id=1861304&sort_by=time&sort_order=desc&viz=stream&from_ts=1685947772092&to_ts=1686120572092&live=true)

[Logs | DataDog](https://app.datadoghq.com/rum/sessions?query=*activity*/library*%20@session.has_replay:true%20@type:session&cols=&event=AgAAAYiSPvTeTx5ZpAAAAAAAAAAYAAAAAEFZaVNQeC1CQUFCamZSSGJSSndKYlFBQgAAACQAAAAAMDE4ODkyNDAtM2U5MC00YTZkLTkyNWUtYzQ3N2NiZmJhYzMz&p_tab=issues&saved-view-id=1861304&sort_by=time&sort_order=desc&viz=stream&from_ts=1685947772092&to_ts=1686120572092&live=true)

### Acceptance Criteria (optional)
- [ ] AddPokerTemplatePayload added to notification subscription
- [ ] RemovePokerTemplatePayload added to notification subscription

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
I saw from DataDog that the user was @jmtaber129 (my clue was that the user was coming from Bolivia). Marking this a p3 and assigning to the Land Expand squad.
