### ISSUE TITLE
Billing: Don't lock the org immediately if payment fails

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8341]
Currently, if payment fails we lock the org immediately.

I suggest:

- If payment fails, send `Card rejected` notification and give `30 days` for completing the payment.
- Show persistent UI warning everywhere in the app.
- If it is the first payment that fails (subscription is `incomplete`), do not lock the org at all, downgrade org back to the `team tier`, send a notification.
- After 30 days lock the org, cancel the subscription to stop generating new invoices

We can use lock org mechanism from teams limit for that.

- Is 30 days too long?
- If they decide to resume their subscription later, should we charge them for 30 days additionally?

**Comment by tghanken** [comment]
It would be nice to surface these orgs in HubSpot so the sales team can manage communications.

**Comment by tghanken** [comment]
Acceptance Criteria:
- (APP): Don't cancel the Subscription after a failed payment occurs
- (APP): Don't lock the org if the payment fails
- (DATA): Add property to HubSpot indicating there's a current failed payment on the company
- (DATA): Work with sales to confirm communication strategy.
