### ISSUE TITLE
Activity Library: add sections for recommendations

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8349]
In order to guide users and help them find the right activity in Parabol, we can introduce sections under categories that highlight and group activities under specific themes. These are similar to what you'll find in streaming services and app stores where there's a need to dissect large amounts of contents and where recommendations play a big role in the user experience.

As the AL grows we'll find more places where these recommendations will come in handy, but currently the spot that needs this feature the most is the Retrospectives category, where we have the largest amount of activities.

![image](https://github.com/ParabolInc/parabol/assets/3276087/2091b222-12ff-48eb-a42c-34ebedab669a)

- What are some basic recommendations we can start with?
- Besides retros, is there another category where this will be useful right now?
- How do we categorize the "Create custom activity" card that appears first on the list?

👉  [Design explorations in Figma](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1721-37460&t=N33eRFCBQUtTuofW-4)

Please note that #8356 is required to unblock this issue

**Comment by enriquesanchez** [comment]
@garethaledavies Would love to hear if you have any thoughts on what sections we could start experimenting with 🙌

**Comment by ackernaut** [comment]
cc @enriquesanchez @garethaledavies 

I think once we get a pattern for sections in place we will experiment with sections based on goals like expansion, or adopting new activities. What do we start with?
- You ran these recently?
- Other teams on your org run these?
- Folks who run what you have run also run these?
- These go well with integrations
@avivapinchas had [some good use cases here](https://parabol.slack.com/archives/C03NGEJUKCN/p1686603185523349)

**Comment by jmtaber129** [comment]
@enriquesanchez does this change quick start at all? Or does this only apply to categories?

Should this be applied to _all_ categories, including low-cardinality categories like standups or strategy, or should this only be applied to categories with more than N activities? It seems weird to have subsections when there are only two activities in the entire category.

Right now, I'd suggest the following categories for simplicity - we can iterate on these + additional categories in the future:
* "Popular activities" / "Must-try activities"
* "You used these recently" - Activities the user has started (first) and participated in (second)
* "Others in your org are using"
* "Try these activities" - activities the user hasn't tried before. Would start as some random sample of activities the user hasn't tried before, with future iterations using more complex recommendation algorithm(s)
* "Other activities" - anything that doesn't fall under one of the above subsections

**Comment by enriquesanchez** [comment]
>does this change quick start at all? Or does this only apply to categories?

>It seems weird to have subsections when there are only two activities in the entire category.


@jmtaber129 Agreed! Given how few activities we have on Quick Start and other categories, I propose we only start with Retros. That said, I think we can run a few tests on Quick Start if we wanted to promote certain activities, etc.

Ideally this can be implemented in a way that if we ever want or need to add sections to other categories, it'll be relatively easy to do so.

>Right now, I'd suggest the following categories for simplicity 

I really like these 👍
