### ISSUE TITLE
Activity Library: update header

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8356]
## Design issue

![image](https://github.com/ParabolInc/parabol/assets/3276087/53cdddb7-639e-4427-9d96-0f31019ac3d1)

This issue covers updates to the Activity library's header that accomplishes the folowing:

- Refines the visual hierarchy in order to improve findability of search
- Removes the "Create custom activity" card from the grid and places instead a "Create custom activity" button with higher visibility and hierarchy, which also unblocks #8349
- Tightens up the layout to keep the information contained to the center, to aid with eye browsability

👉 [See Figma for details](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1758-40953&t=I0b5WFqjb4B1klXZ-4)

### Design checklist

- [x] Is the end-to-end flow complete?
- [x] Have you considered all possible states and scenarios? ([See our UI State Checklist](https://www.notion.so/parabol/UI-State-Checklist-a90cc393612f4a0588144f897dee848a?pvs=4))
- [x] Have you confirmed that the interactive components in your work have all the necessary states designed? (focus, hover, disabled, etc)
- [x] Have you considered all the breakpoints required for a responsive interface? (S, M, L)
- [x] Have you had a design peer or maintainer review your work?
- [ ] Have you had a developer review your work?

**Comment by BartoszJarocki** [comment]
@enriquesanchez looks good! here's a few questions
1. Is search related only to a single, currently selected category? if not, we should not show the categories buttons when showing the search results (this is what I'd recommend, I think it wouldn't be to obvious it's only within a category)
2. The desktop layout is a little bit asymmetric as there's no back button (it's only close button in the top right corner). 
3. In general, the situation with back and close buttons is a little bit confusing. we have 3 variants
  a. desktop - no back button, only close
  b. tablet - no back, no close buttons
  c. mobile - back button, no close button 
Is that intentional? Is the behavior of close and back button the same?

**Comment by enriquesanchez** [comment]
@BartoszJarocki Great questions! Thank you! 

>Is search related only to a single, currently selected category? if not, we should not show the categories buttons when showing the search results

[Matt and I discussed this here](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi?node-id=1392:33452#435195096), and we agreed to keep them visible but also unselected. How does this sound to you?

>In general, the situation with back and close buttons is a little bit confusing.

You are absolutely right! This is an oversight on my part. The close button is trickier to place on mobile, and I like how the back button integrates much more nicely with the header. I'll update the mockups and only keeping the back button.

**Comment by BartoszJarocki** [comment]
> Matt and I discussed this here, and we agreed to keep them visible but also unselected. How does this sound to you?

@enriquesanchez So, if I understand it correctly, clicking category when in search, resets the search and just shows the selected category?

> You are absolutely right! This is an oversight on my part. The close button is trickier to place on mobile, and I like how the back button integrates much more nicely with the header. I've update the mockups and only keeping the back button. How does that look to you?

looks good!

**Comment by enriquesanchez** [comment]
>So, if I understand it correctly, clicking category when in search, resets the search and just shows the selected category?

@BartoszJarocki Correct 👍
