### ISSUE TITLE
gracefully handle SERVER_SECRET rotations

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8384]
When we change the server secret, users could get kicked out of their meetings since their token is now invalidated.
To fix this, we'll want to support the old server secret momentarily. 
I'm not sure how long we should accept the old token. For the life of the access token? I.e. if they give us a token signed with the old secret that hasn't expired, we give them a new one signing with the new value. Unfortunately, if we do that, then anyone who has a token that shouldn't would still have their token, so it doesn't work great for that attack vector.

Basically, all we want is everyone in a meeting to stay in their meeting. If they hit refresh in their meeting, they should still stay in their meeting. However, we want to force them to re-authenticate at their own convenience.  Perhaps within the next 2 hours (most meetings conclude < 2 hours).

I think this means we have a grace period for the old token.
Putting that grace period in an ENV_VAR is tricky because the time depends on when the app gets deployed.
We can have a  SERVER_SECRET_VALID_AT, but that's tricky, too.
We can compare SERVER_SECRET and SERVER_SECRET_OLD and if there is a delta then start the clock, but that'll require us changing the SERVER_SECRET_OLD on next deploy.
We can conditionally tell the client to flush the old token on browser exit. That won't handle refreshes. 
To make it handle refreshes, we can set a `tryFlushingTokenAt`. on unload. on load, if that timestamp is older than a minute, then we wipe the token. To be clear, this isn't a security issue, it's a UX issue, so doing this client side isn't off limits. We have similar logic for token expiration. Essentially, we're just adding a second expiration.
To simplify, we can just issue a new token using the old secret that expires in 2 hours.

AC
- [ ] a new env var SERVER_SECRET_OLD is introduced
- [ ] a rotation is defined as moving SERVER_SECRET to SERVER_SECRET_OLD and generating a new SERVER_SECRET
- [ ] When users connect, we authenticate their token. if the secret is bad but the token is not expired, we check it with SERVER_SECRET_OLD. If it's valid with the old secret & it's set to expire in > 2 hours, we issue them a new token with the old secret set to expire in 2 hours. That gives them time to finish their meeting
- [ ] Users cannot exchange an old token for one signed with the new secret. they must re-authenticate.

**Comment by jordanh** [comment]
Scrubbed. Noting that this needs to be added to a DevOps project board when it exists

**Comment by rafaelromcar-parabol** [comment]
This is 100% done thanks to [this](https://github.com/ParabolInc/parabol/pull/9360) isn't it @mattkrick ? if it is the case, just close this issue please 😸
