### ISSUE TITLE
DX: Remove LocalCache, RedisCache 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8414]
The `LocalCache, RedisCache` managers were put in place to take some load off RethinkDB. Namely for meeting templates, the User table, etc.

These tools have served their purpose & we've since moved to PG.
We can now safely get rid of them & keep our simpler API.
In addition to simplifying our datafetching APIs, it will reduce our retained memory. While researching our memory leaks, many datadog contexts were retained due to these helpers. I'm not sure why! It's possible they are part of the problem. By removing them, we can perform another snapshot & see if our dd-trace memory leak problem improves.

**Comment by Dschoordsch** [comment]
@mattkrick do we still have memory leaks which you suspect could be associated with this? Otherwise I think this should not be a bug but routine DX work.

**Comment by mattkrick** [comment]
We're still leaky (2GB/week), but the leak is much smaller so i haven't spent the time to investigate.
![App-Host Memory breakdown (3)](https://github.com/ParabolInc/parabol/assets/5514175/885ddcc5-49ff-4fcb-83b4-67c8f21bc1dc)

Happy to downgrade this to DX work since it's not as critical now.
