### ISSUE TITLE
Activity Library: Fatal error when clicking template from a team that viewer does not belong to

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8415]
Steps to reproduce:
- Team A, Team B are both a part of Org X
- User Annie is a part of Team A, but not Team B
- Team B has custom Template T that they share with all of Org X
- User Annie tries to start a meeting using Template T, sees that no teams are available & an error is reached

**Comment by jmtaber129** [comment]
@mattkrick I'm not able to repro - could you add some additional details or record a loom? Here's what I've done:
* Team X and Y are in Org Z
* Create a template T on team X
* User A is on Team Y
* User A tries to start a meeting with template T
* All teams User A is on in Org Z are shown in the dropdown.
