### ISSUE TITLE
Enterprise users getting unpaid invoice error, can't use Parabol 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#8422]
A [user ](https://app.hubspot.com/contacts/3888472/record/0-1/17950801) 🔒 wrote: 

> Hi Drew,
> 
> We're having a number of reports from our teams that Parabol isn't available to them due to an unpaid invoice.
> I've followed up with my finance team and they haven't received any invoices from you and believe everything to be paid to date.
> 
> Could you please do a quick check on your side to see what the issue is?
> If it is an invoice then if you could forward me on any unpaid i'll get our team on it as a priority.
> 

We determined their invoice is not an issue. 

I asked for the emails of some users that have been affected. They each belong to the same two Parabol teams. The affected teams have parabol IDs:

`jEPUgOtUCR`
`n1Y656VNQJ`

I wonder if something has gone wrong with their SSO setup?

**Comment by drewhousman1010** [comment]
One user from the company that reported this issue is able to login without problems anymore. 

> Thanks for the account reset. I got the Parabol e-mail. Tried to host a retro again, and it worked perfectly.

I am not sure what they are referring to with the "account reset" though. Maybe running the unlock mutation cleared it up for them? Did we do something else on our end?

**Comment by mwermuth** [comment]
Scrubbed and demoted to P2. 
Thanks for the update @drewhousman1010 I'll assign this to a squad and see if someone can look at this.

**Comment by drewhousman1010** [comment]
I heard this from the customer, so I am going to close this and re-open if we hear it again 

> No issue my end. I’ve asked the team to get in touch if there are any issues.
