### ISSUE TITLE
UI: Implement `Button` component

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#8432]
## Issue - Enhancement

Add an `Button` component that renders either a `button` or a specified child. 

### Acceptance Criteria - work in progress

- [ ] Button component supports the following variants 
  - primary - pinky gradient color
  - secondary - blue button
  - outline
  - ghost
  - danger

- [ ] Button component supports the following shapes 
  - pill 
  - circle
  - rounded

**Comment by b4s36t4** [comment]
@BartoszJarocki any design file for this component? would love to work.!

**Comment by mwermuth** [comment]
Thanks for the interest @b4s36t4.

We are going to icebox this stale issue as per our policy, but if you are still interested to work on it let me know :)
