### ISSUE TITLE
Warning Banner for Specific Email Domains

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#8457]
**Description:**

As a security measure, we need to implement a feature that will present specific warnings and directives to users based on their email domain.

**Acceptance Criteria:**

- [ ] Implement a check for the domain of the user's email during the sign-up and sign-in process. If the email ends in .mil or .gov or if the email's domain is part of a known contract (e.g. xyzcontractor.com)
- [ ] If the first condition is met, display a banner with the following message: "You are using the Parabol commercial SaaS. This environment is for public information only. Do not enter CUI//SP-CTI or higher classification data into this system. Please contact [pubsec@parabol.co](mailto:pubsec@parabol.co) for information on how to obtain a Parabol environment that meets your data classification needs".
- [ ] The banner should include a 'Dismiss' button. Upon clicking this button, the banner should change to display the following message: "For public information only. Do not enter CUI//SP-CTI or higher classification data.", along with a button for more information that displays "Please contact [pubsec@parabol.co](mailto:pubsec@parabol.co) for information on how to obtain a Parabol environment that meets your data classification needs". Selection of dismiss should be remembered.
- [ ] The list of email endings and known domains should be stored in a config table in the database for easy updating by DevSecOps. The config table should also include the banner text values and color for modification in different environments e.g. Public, NIPR, etc
- [ ] Banner should be prominently displayed at the top of the screen.

**Comment by adaniels-parabol** [comment]
We can icebox this for now. It is going to be handled a different route with a similar outcome via hubspot.

**Comment by mwermuth** [comment]
Ah ok good to know!
