### ISSUE TITLE
ENV var to make all users/teams/orgs enterprise

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#8458]
**Description:**

Our non-saas customers e.g. PPMI, DOD, GOV, etc need a way to keep all resources enterprise and hide upgrade UI/UX components. The solution in the issue proposes we create a ENV var called IS_ENTERPRISE that can be set to true. See A/C below for specifics.

Priority: Right after migration off RethinkDB

**Acceptance Criteria:**

- [ ] if true: all users, teams, orgs should be enterprise by default.
- [ ] if true: all UI/UX for upgrade should be disabled e.g. don't show invoices, screens to enter cc data, etc
- [ ] a migration that checks for DEFAULT_TIER=enterprise & if that's true, then it upgrades everyone

**Comment by mwermuth** [comment]
@adaniels-parabol same here. Is this something the product team needs to do, or is this something you can handle? Would be good to classify those issues so we know.

**Comment by adaniels-parabol** [comment]
This is something the product team could handle or @mattkrick may want to pickup. I created the ticket in hopes it would get picked up by someone when backlog grooming was done.

**Comment by nickoferrall** [comment]
@adaniels-parabol just wanted to clarify the tension: is the problem that enterprise customers have users sign-up and create Starter tier organizations. Those users see the upgrade flow and find that confusing?

**Comment by adaniels-parabol** [comment]
@nickoferrall the tensions
- Enterprise and DOD/self-hosted users are prompted to upgrade, it's confusing
- Would like all users/teams/orgs to be enterprise if set for DOD/self-hosted

**Comment by avivapinchas** [comment]
I'm not inclined to prioritize this on our squad for a few reasons: 
- We don't have any pro-active pushes to get folks to upgrade, so I can't imagine there's much they're really running into, and [I don't see this logged on the PIO board as something we've gotten much feedback around ](https://www.notion.so/parabol/Problems-Ideas-Opportunities-faf6d63750274a8f9dff62dbe9787c81) 🔒 
- Our squad is focusing on the Team-tier, so this would be outside of our priorities
- We don't have many PPMI customers and are not currently selling it, so again limited impact

We are currently testing a 'prompt to join Org' flow ([FAQ and details here](https://www.notion.so/parabol/FAQ-Prompt-to-Join-Org-0a0e284049da49f197c71233891c8363)) 🔒. We could implement it as a best practice to add any Enterprise Orgs to this feature flag to help users help themselves.

**Comment by mattkrick** [comment]
Additional AC

- [ ] turn off anti-spam mechanisms when on a PPMI & not using our cloud saas email. This came up with KR

**Comment by mattkrick** [comment]
IS_ENTERPRISE now exists
