### ISSUE TITLE
Insights: Feature flag and skeleton

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8464]
Add the feature flag and minimal UI. The UI should always be shown when Insights are available.

## Acceptance criteria
* add insights organization feature flag
* add the feature flag to parabol.co domain after the release
* add nullable `TeamInsights` graphql type to Team
  * return `null` if the org feature flag is not set
  * show the insights on client side only if not null
* `TeamInsights` PG table with `id`, `teamId` and `updatedAt`
* split Team dashboard into 2 parts, "Open meetings" and "Insights", "Insights" is only shown if not null

**Comment by acressall** [comment]
@Dschoordsch does "minimal UI" here refer to the new tabbing structure of the team dashboard? Or should that be a separate issue?

**Comment by Dschoordsch** [comment]
@acressall I missed that completely. I thought we'd need to only split the view horizontally, but there are also tabs :facepalm: Will add a new issue.
