### ISSUE TITLE
Empty standup summary

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#8470]
## Issue - Bug

I couldn't reproduce that locally, but seems like some of our fridayships email summaries are empty. See the [Slack thread 🔒 ](https://parabol.slack.com/archives/C4JAUUZ9P/p1687792572799769)

### Acceptance Criteria (optional)
- Standups email summaries are correctly sent

**Comment by mwermuth** [comment]
Came up in grooming. Feels relevant to fix in the near future.

**Comment by BartoszJarocki** [comment]
Main reason - facilitator of the meeting is no longer in a given team, as a result null is returned from `newMeeting` query used in `MeetingSummaryEmailRootSSRQuery`. 

potential fix:
1. while removing team member, check if given team member is a facilitator of any active standup meeting; if yes, update it and default to team lead
2. manually update `facilitatorUserId` for already affected meetings

**Comment by BartoszJarocki** [comment]
@mwermuth I updated the `facilitatorUserId` to an existing user so we should start receiving not empty emails moving forward. Regarding the fix, I'd suggest to create a separate task to fix this in the code, brainstorm the correct solution and implement the fix. it shouldn't be a priority, so I think that's the best solution, wdyt?

**Comment by mwermuth** [comment]
Created a new issue #8602 to track this work.
