### ISSUE TITLE
Include customer billing info in the invoices

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8480]
## Issue - Enhancement

Today the invoices (e.g., [this one](https://action.parabol.co/invoice/in_1NMagjFLaFINmHnBcqd9FfZd)) we generated in the app only include billing leaders' email address. We have a bunch of customer requests to include the billing information in the invoices. I think to the simplest starting point, we can just mimic the invoices generated by Stripe in the app (we had to self-generate and customize the invoice because we used to do proration - now we don't need that anymore)

### Acceptance Criteria (optional)
- [ ] `Team` tier billing leaders can see their invoices in the app that include billing information like address, phone numbers, tax ids etc.

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by avivapinchas** [comment]
[Discussed in user feedback retro](https://action.parabol.co/meet/nJIAHfOafS/discuss/6). 

The ideal scenario would allow users to: 
- Have custom information included on the invoice 
- Download the invoice as PDF (vs printing it from a web view) 
- Be notified when a new invoice is available 

We should first investigate how much of these needs can be covered by this shift to using Stripe invoices, then log issue for any remaining bits not covered here.

**Comment by nickoferrall** [comment]
- It looks like Stripe has the following field on the `invoice` object: `invoice.hosted_invoice_url`
- If you click on that, you get taken to a page where you can download the invoice. Below I've included screenshots of what that page and the downloaded invoice look like:

![Screenshot 2023-07-12 at 08 42 23](https://github.com/ParabolInc/parabol/assets/39854876/19feffeb-b44c-47c6-97cc-0bcd5c8bb45b)
<img width="738" alt="Screenshot 2023-07-12 at 08 42 39" src="https://github.com/ParabolInc/parabol/assets/39854876/cf97460d-d7f8-4ab7-bdcd-03a3e9663281">


After clicking on the invoice in Parabol (see below), we could take the user to the `invoice.hosted_invoice_url` and show them this Stripe page. 

![Screenshot 2023-07-12 at 08 46 01](https://github.com/ParabolInc/parabol/assets/39854876/4b301501-3864-4f3f-a6d8-12fd5eb56308)


@avivapinchas you mentioned that ideally we'd have `custom information included on the invoice`. Is there anything not included in the screenshots above that you think we need to include?

**Comment by avivapinchas** [comment]
@nickoferrall The scenario that happens is that some European customers need specific details on their invoice, which aren't part of the standard invoice. The sales team is able to add those in Stripe, but those changes aren't then pulled through to the invoice. 

I think @tianrunhe could speak to where they show up in Stripe, and @gcrickman or @drewhousman1010 can clarify what those specifics are (since they're having to regularly edit and send these).

**Comment by Dschoordsch** [comment]
@nickoferrall if we customize the invoice information in stripe, it would show up on each generated invoice, right?

**Comment by tianrunhe** [comment]
I like @nickoferrall 's approach. It also solves the PDF download issue customer long wanted.

And as @Dschoordsch speculated (and I tested), if sales manually update the customer data (e.g., adding tax id, changing billing address), those changes will show up on the Stripe generated invoices.
