### ISSUE TITLE
Bug: unnecessary vertical scrolling bar, insufficient bottom padding for the last menu item

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8500]
Looks like we have a few UI issues on the current `Menu` and/or `MenuItem` implementation across the board:

To reproduce, create 5 teams in an org and open the team filter in team dash or user dash, you will see the unnecessary vertical scrolling bar (screenshot is not for team filter but the issue stays the same):
![250608439-e69f6b51-4ab0-4844-ad54-20b7615d282e](https://github.com/ParabolInc/parabol/assets/1879975/111ac4d1-6b40-442b-8265-cf9d0a077f98)

Also insufficient padding for the last menu item (compared to the first menu item):
![250608532-2197f671-753e-4ff9-a8cc-fe02551ee156](https://github.com/ParabolInc/parabol/assets/1879975/d184ef95-7e71-41f7-b75a-fe232736702c)

_Originally posted by @tianrunhe in https://github.com/ParabolInc/parabol/pull/8397#discussion_r1257349012_

**Comment by mwermuth** [comment]
Came up in the backlog scrub. Put it as a P3.
