### ISSUE TITLE
Pre-Deploy script does not fail if one of its functions fails on execution and exits with code 0

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#8523]
## Issue - Bug

- **How serious is the bug?** P1 (or even P0 as it is a blocker for the GCP migration)
- **OS:** using our produced Docker images and running them in GCP Kubernetes environment, but should be easy to reproduce anywhere.
- **Browser:** it does not apply
- **Node version:** app version 6.112.0
- **NPM version:** app version 6.112.0
- **RethinkDB version:** 2.4.2

Testing our latest 6.112.0 in our GKE environment I ran the pre-deploy script and got the following log:

```
### MIGRATION 1686226640890_addTeamHealthToAllMeetingSettingsRetrospective (UP) ###
### MIGRATION 1686226641890_fixed-activities (UP) ###
### MIGRATION 1687822236394_activity-illustrations (UP) ###
### MIGRATION 1689031398651_del-team-meetingTemplate (UP) ###
🐘 Postgres Migraiton Complete
🔗 QueryMap Persistence Started
⛓️ Prime Integrationgs Started
⛅️ Push to CDN Started
Post deploy error Error: Env Vars PROTO and HOST must be set if FILE_STORE_PROVIDER=local
    at new l (/home/node/parabol/dist/preDeploy.js:1:754681)
    at t.default (/home/node/parabol/dist/preDeploy.js:1:756946)
    at s (/home/node/parabol/dist/preDeploy.js:1:906627)
    at /home/node/parabol/dist/preDeploy.js:1:905182
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

But I detected that because I went checking it out of curiosity. Even though it failed and didn't run the post-deploy, it exited with code 0! And the job was marked as completed (which mean exited successfully with code 0).

```
State:          Terminated
Reason:       Completed
Exit Code:    0
Started:      Mon, 17 Jul 2023 10:57:37 +0100
Finished:     Mon, 17 Jul 2023 10:57:57 +0100
```

We must throw a non-zero exit code if any of our scripts or components doesn't work as expected, so we can detect the error in Kubernetes and act. Helm charts will continue with the deployment of the web-server, gql-executor and chronos only when the pre-deploy script works correctly, and we shouldn't continue a release if anything fails in our pre-deploy script.

- Could you change the pre-deploy script so it really fails if one script does not work?
- Could you verify that behavior is also applied to all other scripts? (Chronos, Web Server and GQL Executor)

### Acceptance Criteria
The pre-deploy script fails and throws a non-zero exit code when one of the internal scripts do not end correctly.

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by rafaelromcar-parabol** [comment]
BTW there are some typos in 
```
🐘 Postgres **Migraiton** Complete
🔗 QueryMap Persistence Started
⛓️ Prime **Integrationgs** Started
⛅️ Push to CDN Started
```

They should be
```
🐘 Postgres **Migration** Complete
🔗 QueryMap Persistence Started
⛓️ Prime **Integrations** Started
⛅️ Push to CDN Started
```

**Comment by mattkrick** [comment]
Fixed. Tested by adding the following:

```ts
process.on('exit', function (code) {
  console.log('About to exit with code:', code)
})
```

This resulted in the following:


```
About to exit with code: 1
/Users/matt/code/parabol/dist/preDeploy.js:11710
      throw new Error('Env Vars PROTO and HOST must be set if FILE_STORE_PROVIDER=local')
            ^

Error: Env Vars PROTO and HOST must be set if FILE_STORE_PROVIDER=local
    at new LocalFileSystemManager (/Users/matt/code/parabol/dist/preDeploy.js:11710:13)
    at getFileStoreManager (/Users/matt/code/parabol/dist/preDeploy.js:11838:24)
    at pushToCDN (/Users/matt/code/parabol/dist/preDeploy.js:18406:58)
    at preDeploy (/Users/matt/code/parabol/dist/preDeploy.js:18313:111)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```
