### ISSUE TITLE
ReqlDriverError: The connection was closed before the query could be completed

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#8526]
## Issue - Bug

- **How serious is the bug?** P3.
- **OS:** application running in a Docker container in a Kubernetes cluster.
- **Browser:** -
- **Node version:** `node --version` any version of the application.
- **NPM version:** `npm --version` any version of the application.
- **RethinkDB version:** `rethinkdb --version` 2.4.0 and 2.4.2 at least.

When executing the old `migrate` and the new `preDeploy` scripts, we can see the following error message:
```
ReqlDriverError: The connection was closed before the query could be completed
``` 
Example with preDeploy:
```
https://HOST/self-hosted/Organization/aGhostOrg/template/workingStuckTemplate.png
https://HOST/self-hosted/Organization/aGhostOrg/template/wsjfTemplate.png
⛅️ Push to CDN Complete: 53 files pushed
ReqlDriverError: The connection was closed before the query could be completed
🔗 QueryMap Persistence Complete: 0 records added
```

### Acceptance Criteria
The application closes the connection with RethinkDB only after all queries were completed.

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mwermuth** [comment]
@rafaelromcar-parabol do you think this is something for the DevOps circle or for the devs to fix up?

**Comment by rafaelromcar-parabol** [comment]
@mwermuth this is nothing related with features of the application, so I think that it could be under the DevOps Circle.

**Comment by mwermuth** [comment]
Closing this one, because it came up as stale.
