### ISSUE TITLE
Remove action.parabol.co hardcoded in app

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8549]
Our app is deployed to many hosts.
It's here, but also other places: https://github.com/ParabolInc/parabol/blob/b656e7d44061aabd78abadfb05e79d61de9bd181/packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/LogoFooter.tsx

AC
- [ ] use process.env.HOST instead

**Comment by mattkrick** [comment]
https://github.com/ParabolInc/parabol/pull/8557#pullrequestreview-1565456466

**Comment by BartoszJarocki** [comment]
@mattkrick should we remove this from our squad board then?

**Comment by mattkrick** [comment]
sure, i'll take this one. still not sure what to do with those static assets that aren't directly tied to a build, but we'll figure something out!

**Comment by mattkrick** [comment]
Plan of attack:
- put EVERYTHING in the build
- push all assets to the same bucket, do not use a versioned subdirectory (already done in #8557)
- optional: check if exists before pushing to speed up pushes
- when webpack touches images, keep their file name or maybe filename + a content hash.
