### ISSUE TITLE
One on one: add 1:1 check-in activity

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8559]
![image](https://github.com/ParabolInc/parabol/assets/466991/279334d8-41cb-41ae-b627-4a1f1c644c43)

**AC:**

- Create 1:1 category in activity library
- Add check-in meeting there 
- Add check-in meeting to the quick start page
- The check-in has a new `one on one` name, new hover description, new page description (see designs)
- Use a feature flag
- _Think if we need to explicitly mark the meeting as one-on-one. Because on the meeting page we need to show different controls,  or for example in future we want to select all one-on-one check-in meetings_

**Metrics:** 

- one-on-one meeting page seen event
- Modify `Meeting Started` event or create additional event to see that it was not check-in that started but 1:1 meeting

cc @tianrunhe @tghanken 

**[Designs](https://www.figma.com/file/Vc09AD3hxef2ypriihfK0T/Flow---one-on-one?type=design&node-id=0-1&mode=design&t=n98vvQK9920rLKnB-0)**

**Comment by tianrunhe** [comment]
Page view is automatically tracked so no need to explicitly log that. The meeting related events will depend on how you implement it: a new meeting type? or check-in in disguise? Tag us when you have a PR!
