### ISSUE TITLE
Invitations moved to Sidebar, Default to Open for New Teams

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#8567]
## Issue - Enhancement

After a user creates a new team, they are dropped into the empty task view. Their next step is to invite team members, but they need to spot the `Invite` button in the upper right in order to do so. 

We should remove this friction and make it slightly easier to know what to do next by working with the pattern we have for 'agenda' items: 
- Move the 'invite' modal content to a right-hand drawer, similar to the behavior of the Agenda button that's next to it
- When a user visits this page for a new team, have that drawer open by default, so they don't need to go looking for it. 

Here's a terrible sketch of what I mean: 
![Screenshot 2023-07-25 at 6 16 30 PM](https://github.com/ParabolInc/parabol/assets/11621016/693b5e58-ab79-4351-b513-783782a1d8d6)

### Acceptance Criteria (optional)
Users can:
   - See how to invite new team members without needing to click a button to show the option 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by acressall** [comment]
Some context and conversation: https://parabol.slack.com/archives/C042E8PGPD4/p1691180398136479

Designs: https://www.figma.com/file/WOdLvetCvDA7ZUSGjj9JyD/view---New-team-dashboard?type=design&node-id=1-1535&mode=design&t=FB3naWxCSYtfjsK6-4

@ackernaut another one ready for maintainer review!

**Comment by ackernaut** [comment]
Hello! I left a few questions in Figma.

**Comment by acressall** [comment]
Designs complete and ready for implementation

![Image](https://github.com/ParabolInc/parabol/assets/18582225/646a0c8b-723f-443b-811b-4d3544f81aac)
