### ISSUE TITLE
Ad-hoc teams design

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#8576]
[Brief](https://www.notion.so/parabol/Ad-hoc-teams-2f2ec0b6dc6d4e56b8072a6626d01e3d?pvs=4)

A user picker that allows to pick multiple existing users or enter any number of custom emails.

**Comment by acressall** [comment]
@ackernaut these designs are ready to review https://www.figma.com/file/Vc09AD3hxef2ypriihfK0T/Flow---ad-hoc-teams?type=design&node-id=61-3659&mode=design&t=kti28Szv29av8w5M-4

I recommend reviewing in combination with 1:1s #8593 
Loom: https://www.loom.com/share/42406e0b7964458a9461f1b5cf69f0eb?sid=541575c1-4d13-4359-a774-9b10a9873c4d

**Comment by ackernaut** [comment]
Okay, I’ll take a card to give any feedback!

**Comment by ackernaut** [comment]
@acressall I looked at this along with the 1:1 selector work. Nice work all around!
