### ISSUE TITLE
Improving Category query in the new Activity Library

### ISSUE THREAD

**Issue by mwermuth** [ParabolInc/parabol#8581]
Improve `ActivityLibraryQuery ` to prevent lag and RethinkDB taking too many hits.

For Context:
https://parabol.slack.com/archives/C042HTVBH8D/p1690389143937259

**Comment by mattkrick** [comment]
Sure thing, just tag me in when needed

**Comment by mattkrick** [comment]
Sure thing, so Team:MeetingTemplate is a M:N relationship, so I'd say we just create a junction table like `TeamMeetingTemplate` (the internet says it's sometimes nice to put an `XRef` suffix on junction tables... i think this is our first one, so we could do that, I don't have a strong preference). It has 3 columns: `teamId, activityId, lastUsedAt`. If we want to change the business logic so it shows the activities most recently used by a specific _user_, we'd make UserMeetingTemplate. IMO, this is a little nicer, but totally up to you!

**Comment by mattkrick** [comment]
I'll take a first stab at this & open a PR in a little bit
