### ISSUE TITLE
Default team tab is `Task` but the content shows meeting cards

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8582]
## Issue - Bug
To reproduce:
1. Create a new account
2. Go to the default team created automatically
3. See the active tab is on Task but the content is the empty state for meetings

![2023-07-27 10 17 04](https://github.com/ParabolInc/parabol/assets/1879975/dc08ed7c-d26f-4643-a5ae-abb0b70086e2)

Seems also happen when there are no active meetings and/or no tasks?

![2023-07-27 10 14 56](https://github.com/ParabolInc/parabol/assets/1879975/ee111952-1609-4367-b68a-48ead1d165f4)

### Acceptance Criteria (optional)
Users can:
- [ ] when goes to the team page, the activity tab is displayed by default
- [ ] when on the task tab, tasks are displayed
- [ ] when on the meetings tab, meetings are displayed

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mwermuth** [comment]
I think this if fixed according to the PR from @Dschoordsch above. Thank you!
