### ISSUE TITLE
1:1 designs

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#8593]
[Brief](https://www.notion.so/parabol/One-on-One-Meeting-type-778d17abb9ea4ea4b1c18b6c6be9690f?pvs=4)

Reuse the check-in meeting type as 1:1s, adjusting the selected team picker to allow for selecting a single user

**Comment by acressall** [comment]
@ackernaut these designs are ready for review https://www.figma.com/file/Vc09AD3hxef2ypriihfK0T/Flow---ad-hoc-teams?type=design&node-id=1-735&mode=design&t=kti28Szv29av8w5M-4

I recommend reviewing with #8576 
Loom: https://www.loom.com/share/42406e0b7964458a9461f1b5cf69f0eb?sid=541575c1-4d13-4359-a774-9b10a9873c4d

**Comment by ackernaut** [comment]
Okay, I’ll hope to get feedback to you soon.

**Comment by ackernaut** [comment]
@acressall this is looking sharp! Nice work showing all the states and use cases
