### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/app/dist/action-files.parabol.co/production/build/v6.11...

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8597]
Looks like the Jira "Not Found" image is broken. This is probably a mismatch between the server public path & the prefix we use to fetch it. It should be fetched locally from the server & cached in redis.

https://parabol.sentry.io/issues/3749078033/?referrer=github_plugin

```
Error: ENOENT: no such file or directory, open '/app/dist/action-files.parabol.co/production/build/v6.114.0/server/dist/1aeded0fccef1148dab6f1df28b9f1af.png'
```

**Comment by rafaelromcar-parabol** [comment]
Is this really DevOps related and not just a regular bug? IMHO we should remove the label devops and remove the issue from the DevOps project
