### ISSUE TITLE
User uploaded picture/document accessible by any user even after deletion / account deletion

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#8616]
## Issue - Bug

Vulnerability Name - User uploaded picture/document accessible by any user even after deletion / account deletion

Steps:
1 - Log in as a user
2 - Go to profile
3 - Upload profile picture or any document
4 - Right click on the picture and click on view image, the link will be

Example LINK - https://action-files.parabol.co/production/store/User/local%7CoyrAx657Gw/picture/oyrSEWyFby.jpeg

5 - When the user deletes the account/profile picture, the link/ picture is still accessible.

Impact - The attacker can steal sensitive information such as document , picture , etc through the link

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mwermuth** [comment]
Looked at during backlog grooming.
