### ISSUE TITLE
TipTap: Links are opened twice

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#8624]
When a user clicks an open-able link in a tiptap field (i.e. standups), their browser will actually open the link twice, though some browsers will block one of these as a pop-up. This seems to be because the browser is opening the link as a normal anchor tag, and TipTap is opening the link via onclick listener.

Setting `openOnClick` to `false` instead of `isReadOnly` seems to fix this, though we should investigate a bit more and confirm that this change won't have any adverse impacts.

See https://parabol.slack.com/archives/C042HTVBH8D/p1691164500225379

AC:
- [ ] Confirm whether `openOnClick: false` won't have any unintended side-effects
- [ ] Issue fixed by changing to `openOnClick: false` iff the above is true.

**Comment by BartoszJarocki** [comment]
@jmtaber129 I haven't found any regression when setting `openOnClick: false` so I'd suggest to move forward with that solution. PR #8658
