### ISSUE TITLE
Checkout Flow: Add visual cues to upgrade flow to prevent confusion

### ISSUE THREAD

**Issue by tghanken** [ParabolInc/parabol#8628]
We're seeing some users experience [frustration](https://parabol.slack.com/archives/C042E8PGPD4/p1691445086645969?thread_ts=1691132968.111179&cid=C042E8PGPD4) 🔒  with the new checkout flow that is causing them to abandon their upgrade attempt.

When clicking on the `Team` tier, nothing interactive happens within the interface and the `Starter` plan remains highlighted, causing users to believe the checkout flow is broken, even though they can upgrade using the credit card details section.

![no_upgrage_interactivity](https://github.com/ParabolInc/parabol/assets/51011434/db9331fb-9cbd-4576-9042-a77f0f2e2225)

### Possible Solutions
- Hide credit card module until user selects the `Team` plan
- Highlight the `Enterprise` or `Team` plans while the user remains on the billing page if clicked, reset to true organization tier after leaving the page and revisiting.

### Acceptance Criteria
Users can:
   - Get visual feedback while moving through the checkout flow

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by acressall** [comment]
[This](https://www.figma.com/file/SyJdkzumWsUJo58cmBGgus/Flow---Checkout?type=design&node-id=216-4562&mode=design&t=pxXJIo1ca61GKUqr-4) is what it's meant to look like after click
![plans](https://github.com/ParabolInc/parabol/assets/18582225/a9a8e215-a72a-4bf4-99da-fcc09b52fe81)
