### ISSUE TITLE
Batch archive tasks in the done column

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8634]
## Issue - Enhancement
Today there are only two ways to archive tasks:
1. Manually set a single task as #archived by clicking the three dot icon on the top right bottom of a task card
2. Run a check-in meeting and at the end of the meeting, all DONE tasks for that team will be automatically archived

Hence, if a user does not run any check-in meetings, they don't have a good way to batch archive DONE tasks. As a result, they have many tasks cluttered at their DONE column, like this:
<img width="363" alt="Screenshot 2023-08-08 at 15 48 47" src="https://github.com/ParabolInc/parabol/assets/1879975/308a2dda-f287-44b4-bd09-b59489f17a39">

### Acceptance Criteria (optional)
Users can:
- [ ] have a way to archive all the tasks in the done column

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by enriquesanchez** [comment]
👉 [Design explorations in Figma](https://www.figma.com/file/HIw7Xg3uNmUS90K75uoEJD/Archive-all-Done-tasks?type=design&node-id=0-53&mode=design&t=ZjNkGlcIvgF15oXn-4)

**Comment by tianrunhe** [comment]
WIP:

![2023-09-02 12 03 12](https://github.com/ParabolInc/parabol/assets/1879975/424bfac8-a749-41d3-84cc-654acefd5ed3)

**Comment by enriquesanchez** [comment]
@tianrunhe let me know when I can review this 👍

**Comment by mwermuth** [comment]
@tianrunhe this is done right? At least I remember you showing it at the Demo Day 😅

**Comment by tianrunhe** [comment]
@mwermuth Not yet! I was demoing my local version. Still in PR review phase. As it's a side project, I didn't prioritize
