### ISSUE TITLE
Empty Meeting View: promote Standups

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#8640]
### Design issue

In the empty meetings view, we highlight retros & sprint poker, but not standups. We should include standups so folks are aware of that offering. 

[Background here.](https://parabol.slack.com/archives/C03DSA15H9C/p1691593977162249) 🔒 

## Design checklist

- [ ] Is the end-to-end flow complete?
- [ ] Have you considered all possible states and scenarios? ([See our UI State Checklist](https://www.notion.so/parabol/UI-State-Checklist-a90cc393612f4a0588144f897dee848a?pvs=4))
- [ ] Have you confirmed that the interactive components in your work have all the necessary states designed? (focus, hover, disabled, etc)
- [ ] Have you considered all the breakpoints required for a responsive interface? (S, M, L)
- [ ] Have you had a design peer or maintainer review your work?
- [ ] Have you had a developer review your work?

**Comment by acressall** [comment]
Two concepts: the first is just adding a video like we have for poker (pending video). The second is for when the activity library has been fully released
[Figma](https://www.figma.com/file/ZlKeZYgtx640CL6HbB7UJp/view---empty-meeting-dashboard?type=design&node-id=0-1&mode=design&t=d1ldi7GVnRETV8oM-0)


![Image](https://github.com/ParabolInc/parabol/assets/18582225/bd4c927c-99fd-4672-a5f9-d2c9f28ccd37)
![Image](https://github.com/ParabolInc/parabol/assets/18582225/9e8d87e5-7aab-477a-b7a9-67fac9a8b816)

**Comment by acressall** [comment]
@ackernaut ready for maintainer review! this is to add standups to the empty meeting view. Emily has made a demo, so it will open in a modal the same as the sprint poker demo. 

In future, when the AL is fully rolled out, I'd like to take time to make this smarter, adjusting for where a user is in their journey (ie. power users don't need to see demos) and maybe suggesting based on team type and previous activity

**Comment by acressall** [comment]
Closing this because the other squad already did it 🎉  https://github.com/ParabolInc/parabol/pull/8862
