### ISSUE TITLE
Do not send segment events from client when segment is not installed

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8649]
### Pre-submission instructions (remove me before creating an issue)

This is to clean up error logs seen in PPMIs

AC
- [ ] When a PPMI does not have segment installed, we should not send segment events to the client via gql.

**Comment by mwermuth** [comment]
Looked at during backlog grooming.

@Dschoordsch mentioned that @tghanken might have worked on this already and removed it in a recent PR. Is that true? _Added it to the "Migrate to Amplitude Analytics" milestone._

**Comment by mattkrick** [comment]
yep, this was fixed in #8682, I think we may be getting rid of segment on the client, too, but i haven't heard the full story there
