### ISSUE TITLE
phaseTypes can be undefined in meeting sidebars

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8654]
Affected 112 users in 4 days

https://parabol.sentry.io/issues/4378994691/?referrer=github_plugin

```
TypeError: Cannot destructure property 'phaseTypes' of 'E' as it is undefined.
  at z (./packages/client/components/RetroMeetingSidebar.tsx:81:10)
...
(14 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
Last seen 3 days ago
in release [6.87.1](https://parabol.sentry.io/releases/6.87.1/?project=107196). The [version distribution](https://parabol.sentry.io/issues/4378994691/tags/release/?referrer=tag-distribution-meter) shows the newest where it appeared was 6.114.1. Checking the diff of [6.114.1 to 6.115.0](https://github.com/ParabolInc/parabol/compare/v6.114.1...v6.115.0#diff-d64184079df3bc63d07be56c82bf532344138ed47653d0eb58645c541b7c901f) shows that the failing code line was removed back in August.
