### ISSUE TITLE
New ready status should not be displayed on all phases

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8672]
## Issue - Bug

Not all phases require a ready status to be shown in the facilitator's meeting controls. It can actually be confusing or distracting in cases such as the Icebreaker phase, or Solo Updates, where requirement of input from all attendees is not expected:

<img width="929" alt="Captura de pantalla 2023-08-15 a la(s) 12 08 08 p m" src="https://github.com/ParabolInc/parabol/assets/3276087/5b199167-bc37-428e-bbf0-bd271d64fcba">

### Acceptance Criteria (optional)
  - Consider adding logic to this feature so it's only shown on multiplayer phases

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mwermuth** [comment]
Looked at during backlog grooming.
