### ISSUE TITLE
Upon first load the Activity tab in the team dashboard is missing selection state

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8673]
## Issue - Bug

<img width="691" alt="Captura de pantalla 2023-08-15 a la(s) 12 04 42 p m" src="https://github.com/ParabolInc/parabol/assets/3276087/83af41ea-77a2-44e4-ab83-b0186afb0e51">

When opening a team dashboard the Activity tab is missing the selected underline state. Clicking on any of the tab options displays it correctly.

### Acceptance Criteria (optional)
- The underlined selected state is shown on first load.

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mwermuth** [comment]
Looked at during backlog grooming.
