### ISSUE TITLE
Resolve questions around invitation behavior 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#8701]
After this [analysis](https://www.notion.so/parabol/Invitations-Scope-Size-of-Challenges-01986222d49c4e3d9c2860e7fd53295a#b6fd9558772848f4b28913e498222b6a), we have some remaining questions on the invitation issue: 
- Have users moved from emails to invite links? Does factoring in link behaviors tells us anything new? 
- After receiving an email invitation, to what degree are users are still creating an account (even if they aren’t clicking the accept button)? 
- Has invite option on new team creation increased overall % of users inviting others? 
- Have efforts to block spammers caused fewer legitimate users to be able to invite others? 
- When looking at Account Created > Invite sent by Feature Flag, have any features impacted this behavior?

**Comment by tghanken** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/pNxT3KzvMY/estimate/19) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
