### ISSUE TITLE
Not possible to return to pinned agenda items if you go directly to the new once

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8704]
See the loom

https://www.loom.com/share/0fc5c8aee18f42ec986edffc4c932301

**Comment by mwermuth** [comment]
Looked at during backlog grooming.

**Comment by mattkrick** [comment]
your call!
the reason for setting it to `false` is to encourage meetings to have a linear flow-- going from updates -> agenda item -> updates feels like the meeting isn't moving forward. that said, you might say that's a little overly prescriptive & if the facilitator wants to hop all over & give their participants whiplash, we should let em.
i don't have a strong opinion. if i had to pick, i'd say make the bottom ones as restrictive as the top ones, but i could go either way.
