### ISSUE TITLE
Your work: designs for adding integrations

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8733]
## Design issue

Users need a way to add available integration to the "Your work" drawer.

### Acceptance Criteria
- User can add one or more integrations right from the Your Work drawer

### Design checklist

- [x] Is the end-to-end flow complete?
- [x] Have you considered all possible states and scenarios? ([See our UI State Checklist](https://www.notion.so/parabol/UI-State-Checklist-a90cc393612f4a0588144f897dee848a?pvs=4))
- [x] Have you confirmed that the interactive components in your work have all the necessary states designed? (focus, hover, disabled, etc)
- [x] Have you considered all the breakpoints required for a responsive interface? (S, M, L)
- [x] Have you had a design peer or maintainer review your work?
- [x] Have you had a developer review your work?

**Comment by enriquesanchez** [comment]
[Figma can be found here](https://www.figma.com/file/mR6vYT8fUDRv9tBGb8OPCL/Standups-iterations?type=design&node-id=1527-26435&mode=design&t=3ye4HL0tjWJOo6fI-4).



![Image](https://github.com/ParabolInc/parabol/assets/3276087/7d6408b9-9fbb-4a18-8c60-81bb83d7b589)

**Comment by enriquesanchez** [comment]
@jmtaber129 this one is ready for a dev review 👍

**Comment by jmtaber129** [comment]
Left comments in the Figma

**Comment by mwermuth** [comment]
@enriquesanchez can we call this done? Or are you still going to work on that?
