### ISSUE TITLE
Potential AI feature related issues crashed the meeting

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8737]
## Issue - Bug

The land & expand squad had a [retro meeting](https://action.parabol.co/meet/pXqx8fEKGI/discuss/1). After the group phase entering into voting, the facilitator saw a blank page while others saw an error page. Hard refresh did fix it. However we found some of the AI features were missing in the discussion groups: e.g., [this topic](https://action.parabol.co/meet/pXqx8fEKGI/discuss/1) has the AI summary but not the prompt question; [this one](https://action.parabol.co/meet/pXqx8fEKGI/discuss/3) has the question but not the summary so it looks like we hit some time out -ish stuff with OpenAI or sth like that.

Notice we tried the auto group button and then reset, in case that's relevant.

We should investigate & fix this before the roll out

### Acceptance Criteria (optional)
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mwermuth** [comment]
Looked at during backlog grooming.

@tianrunhe would you be able to take a look, as you worked on discussion topics?

**Comment by tianrunhe** [comment]
I think this [Sentry error ](https://parabol.sentry.io/issues/4410735306/?query=is%3Aunresolved+OpenAI&referrer=issue-stream&statsPeriod=14d&stream_index=0) could be related. Assigning to self-serve squad for @nickoferrall to investigate.

**Comment by nickoferrall** [comment]
@avivapinchas [mentioned](https://parabol.slack.com/archives/C836NA350/p1694192601993789) that the recent Exco retro didn't have any AI features. Could be related
