### ISSUE TITLE
investigate redis mem leak

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8741]
​

**Comment by mwermuth** [comment]
Hey @mattkrick this came up during backlog grooming. Is this a new leak? There are no labels and descriptions on it 😅

**Comment by mattkrick** [comment]
yep, new leak, still gotta triage

**Comment by rafaelromcar-parabol** [comment]
Is this still a valid issue @mattkrick ? I think you said that there is no Redis mem leak finally 😸

**Comment by mattkrick** [comment]
correct! leak free (for now 😓 )
