### ISSUE TITLE
Meeting from summary: add sidebar to summary

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8749]
![image](https://github.com/ParabolInc/parabol/assets/39854876/b0883eb3-eaf3-4b32-97e4-05d979ce2b25)

We want to let users start a meeting from the summary, but we don't want to have too many CTAs. Showing the left sidebar should let users add a meeting quickly without cluttering the summary.

**AC:**

- Show sidebar next to the meeting summary in the web app
- Don't show the sidebar in the email 

Designs: https://www.figma.com/file/HQkcXyUtEIhDH27GdchRxr/view---Meeting-domino?type=design&mode=design&t=h4Y4Ob4p6QlexnvP-0

**Comment by nickoferrall** [comment]
Hey @acressall, just wanted to check if you still want to work on this issue after we changed the AC?

**Comment by acressall** [comment]
I have actually tried to add the navigation here before and couldn't figure it out, so it's probably best if someone else takes it!
