### ISSUE TITLE
Meeting inception: add "add an activity" button

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8750]
<img width="247" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/13b1dc38-d60c-44cd-8fc0-8c02ebdc1ce3">

AC: 
- Add org level feature flag
- Add "Add an activity button" to the discussion panel 
- Button should simply redirect to the activity library for now

**Comment by igorlesnenko** [comment]
@acressall currently we have polls disabled on the production, but if they will be enabled someday and on localhost it will look like this

<img width="382" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/2270a725-0c0e-4174-a100-e2338976f075">

What should we do? increase panel width?

**Comment by acressall** [comment]
This is just a first version, so we'll keep it as-is for now. Some devs will have all 3 in their local environments, but everyone else will just have task and activity. 

The goal here is to see if people want to create activities from within a meeting. Down the road, I'd like to move towards having apps and activities in separate sections -- [here's](https://www.figma.com/file/0VNZh252EhtXerwguGc9xL/meeting-inception?type=design&node-id=16-6088&mode=design&t=x7X8poVCnNpUyxFY-4) a concept of how that could look. 

As far as I know, we're not bringing back polls any time soon, so I think we'll have time to learn from this experiment and can adjust when we have more actions to include
<img width="366" alt="Example Retro Discuss thread (3)" src="https://github.com/ParabolInc/parabol/assets/18582225/6a7f6c78-45da-4d0f-83a6-b1c3b7e4234f">

**Comment by igorlesnenko** [comment]
Removed "retro meeting condition" from the AC, I think it could be added anywhere and I don't see in original document this restriction

> - Add "Add an activity button" to the discussion panel of a **retro meeting**
