### ISSUE TITLE
Meeting inception: post meeting card to the discussion

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8751]
<img width="250" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/aaf982ff-d3a7-475e-a01a-a5556e4c87c3">

**AC:** 
- `Add an activity button` should redirect to the activity library (in a new tab) and provide an additional param, probably `discussionId`
- After the new meeting is created, it should be posted to the discussion thread (see screenshot)
- Validate that the meeting is not ended and access control

**Questions:**

- Should we support all meeting types here? cc @acressall 
- Probably we need to somehow additionally track meetings created like this in the segment. How? Store `sourceMeetingId`? cc @tghanken

**Comment by tghanken** [comment]
>Probably we need to somehow additionally track meetings created like this in the segment. How? Store sourceMeetingId? cc @tghanken

Yest, that makes sense to me.  If we add that to the Meeting Started event, it should be enough for us to track this!

**Comment by igorlesnenko** [comment]
Now I'm thinking we can show activity-library in a popup window, not a new tab. Probably this way it will be more obvious that something will happen if you add an activity. And if we implement 'user is adding activity' placeholder, you will able to see it this way.
And use some existing method of communication between windows. Maybe `postMessage`? Need to check

**Comment by acressall** [comment]
The concern with showing it in a modal was that we'd have to adjust the activity library from it's fullscreen form. Not the end of the world, but a bit more work. LMK if you'd like me to whip up what the design adjustments would be.

Alternatively, we could show the _old_ meeting picker to start and do the activity library later.
