### ISSUE TITLE
Invite from manage team sidebar

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8753]
![image](https://github.com/ParabolInc/parabol/assets/466991/0da91322-7b2b-49e6-bf84-f6f905833902)

**AC:**

- Manage team sidebar is opened by default for new teams
- Invite link block is added to the bottom of the sidebar
- Make sure it works with very long users list correctly

**Questions:**

- I'm not sure about feature flag on this. Should it be a feature flag that randomly added to the new users? cc @tghanken

**Comment by tghanken** [comment]
I'd recommend setting this up under a feature flag so we can do a phased roll-out to ensure nothing breaks, but I don't think we need to limit this to just new users.
