### ISSUE TITLE
Active teams definition on Usage Stats is different to the definition on Domain Stats

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#8762]
Users with the [insights (Usage Stats) feature flag](https://www.notion.so/parabol/insights-46faf37e7e5d4d6f93e602df1d5dce1f) 🔒 turned on see a different definition of active teams compared with what appears on internal tools like DomainStats and HubSpot.

Example [org](https://app.hubspot.com/contacts/3888472/record/0-2/7683623068) 🔒 with example [user](https://app.hubspot.com/contacts/3888472/record/0-1/61447901) 🔒 

Here's our internal tooling:

![Image](https://user-images.githubusercontent.com/101657889/264607373-b0afaf98-5dcb-4f99-815b-2fe34ee84067.png)

And then here's Usage Stats:

![Image](https://user-images.githubusercontent.com/101657889/264607403-6c38cbd4-4d33-41e1-a7b9-a9718d7f970f.png)

**Comment by charlesmathias** [comment]
[Relevant Slack thread](https://parabol.slack.com/archives/C03C3J42WDU/p1689950627830559) 🔒

**Comment by jordanh** [comment]
Going to keep this one open a bit longer. We may revisit this feature as part of leadership value

**Comment by charlesmathias** [comment]
If usage stats has been removed, can we close this issue? @nickoferrall

**Comment by nickoferrall** [comment]
Yep! I'll close it now 👍
