### ISSUE TITLE
Your work: Allow users to see their assigned open/closed issues from Jira.

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8782]
### Design issue

Allow users to see their assigned open/closed issues from Jira.

## Design checklist

- [x] Is the end-to-end flow complete?
- [x] Have you considered all possible states and scenarios? ([See our UI State Checklist](https://www.notion.so/parabol/UI-State-Checklist-a90cc393612f4a0588144f897dee848a?pvs=4))
- [x] Have you confirmed that the interactive components in your work have all the necessary states designed? (focus, hover, disabled, etc)
- [x] Have you considered all the breakpoints required for a responsive interface? (S, M, L)
- [x] Have you had a design peer or maintainer review your work?
- [ ] Have you had a developer review your work?

**Comment by enriquesanchez** [comment]
[Figma can be found here](https://www.figma.com/file/mR6vYT8fUDRv9tBGb8OPCL/Standups-iterations?type=design&node-id=1499-19380&mode=design&t=3ye4HL0tjWJOo6fI-4).



![Image](https://github.com/ParabolInc/parabol/assets/3276087/2c5d34ea-11f8-4873-943b-31d89191756b)

**Comment by enriquesanchez** [comment]
@jmtaber129 ready for a dev review 👍, Jira issues follow the same design/layout and behavior we have for GitHub issues.

**Comment by jmtaber129** [comment]
LGTM!
