### ISSUE TITLE
Some `page_view` events are missing after migrating to GA4

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8787]
## Issue - Bug
We noticed `page_view` GA4 event counts dropped from 03/10/2023:
<img width="252" alt="Screenshot 2023-09-05 at 16 20 42" src="https://github.com/ParabolInc/parabol/assets/1879975/85b6c5ea-49c2-4d3d-857d-f2836fddfda4">

On 03/09 we released v6.95.0 and it looks this [PR](https://github.com/ParabolInc/parabol/pull/7848/files) might be the culprit. I did a quick test: if I went to `localhost:3000/invitation-link/abcded` no `page_view` events are emitted to GA4. It's only after the user signs in/up, we start to send `page_view` events. I wonder if the bug is that only `page_view` events with `userId` are sent?

### Acceptance Criteria (optional)
- [ ] `page_view` events for not-logged in traffic (`/invitation-link`, `/team-invitation`, etc) are properly sent to GA4

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mwermuth** [comment]
Looked at it in the backlog grooming.

**Comment by mwermuth** [comment]
@tianrunhe are you actively working on this as you are assigned to it?

**Comment by tianrunhe** [comment]
This is no longer an issue! 🎉
