### ISSUE TITLE
Node v20.6.0 Upgrade - Remove dotenv

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#8788]
Node v20.6 adds native support for `.env` files. This should make our DX a bit cleaner.
https://philna.sh/blog/2023/09/05/nodejs-supports-dotenv/

AC
- [ ] dotenv package is gone

**Comment by rafaelromcar-parabol** [comment]
Should we keep this on the DevOps project? IMHO we should remove that project and add the labels Dx and p2 or p3. Up to you!
