### ISSUE TITLE
Track button clicks in the summary

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8803]
We'd like to know which buttons are useful so we can remove any buttons that aren't providing value.

See [Slack thread](https://parabol.slack.com/archives/C042E8PGPD4/p1694118181865609?thread_ts=1694030189.809269&cid=C042E8PGPD4) for more context.

### AC

- [ ] Track "go to team dashboard"
- [ ] Track "export to csv"
- [ ] Track "download to pdf"
- [ ] Track clicking the team name to take you to the dash (once this is built!)
- [ ] Track any other relevant buttons in the meeting summary that aren't being tracked

**Comment by tianrunhe** [comment]
We already have some of them: `click` events are automatically tracked by GA4! I'll be out soon but you can work with @tghanken to pull some metrics pretty quick.

Here's a starter query:
```SQL
SELECT
  *
FROM
  `data-sanctum`.`analytics_320682165`.`events_202309*`
WHERE
  event_name = 'click'
  AND CONTAINS_SUBSTR( (
    SELECT
      value.string_value
    FROM
      UNNEST(event_params)
    WHERE
      KEY = 'page_location'), 'action.parabol.co/new-summary')
LIMIT
  10
```
