### ISSUE TITLE
Dashboard search disappears

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#8809]
### Steps
- Go to the Tasks view and see that the dashboard search in the top bar is working
- Go to a Team view. You should see the Activity tab and the search is still present. It doesn’t noticeably work to filter anything on that view to my knowledge.
- Switch to the Tasks tab. The search goes away. Going back to Activity it still is missing.

Note: if you had an active query in the search box while at the Task view e.g. ‘feedback’ (I have task cards about this) and switch to the Tasks tab on a team, the query is still filtering the tasks although you don’t see the search box. Should we clear the query when switching from Tasks to a Team view?

### Effort
- 1 hour triage the team view state. Update here

**Comment by mwermuth** [comment]
Looked at during backlog grooming.

**Comment by Dschoordsch** [comment]
This should be a really easy fix, we're most likely not matching with the new subpaths added when splitting the dash into path/activity tabs.
