### ISSUE TITLE
Stand-up response side sheet, emoji tooltip info is wrong

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#8810]
### Repro steps
- Go to a Standup meeting
- Open the response side sheet thread by tapping on Reply
- Hover over the first emoji, see what it says
- Then tap Reply on another card to swap out the side sheet response and thread
- Hover over the first emoji, at some point after swapping responses by tapping reply on response cares in the grid view (main area left of the side sheet), this emoji in the side sheet will have what seems like tooltip info from the emoji of the previous response that was in the side sheet view

E.g. here the 2 hearts on 1 response in side sheet is showing the tooltip for 3 sparkles that was left on another response (as seen in the response grid card)

![Screen Shot 2023-09-08 at 14 52 25](https://github.com/ParabolInc/parabol/assets/307286/e621c73a-6ace-46d6-be1a-aaed59b34243)
![Screen Shot 2023-09-08 at 14 52 46](https://github.com/ParabolInc/parabol/assets/307286/69ba4350-cc50-4712-8fbe-993d5d370d40)

### Effort
- 1 hour to triage query update on side sheet view and emoji or similar. Update here

**Comment by mwermuth** [comment]
Looked at during backlog grooming.
