### ISSUE TITLE
PreDeploy script continues running after error

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#8812]
## Issue - Bug

- **How serious is the bug?** P1
Running on the Docker image produced from the tag v6.118.0

I executed the pre-deploy script against a database that was actually already in v6.119.0 and this was the result:

```
ServerID 642
🚀 Predeploy Started v6.118.0 sha:0880bae3cea63bfcf621879a35c05d5a15ccef82
👴 RethinkDB Migraiton Started
[migrate-rethinkdb]  ↑  up  ↑  20160715095300 initialize
[migrate-rethinkdb] Migration failed: initialize
s [ReqlOpFailedError]: Table `actionProduction.User` already exists in:
r.db("actionProduction").tableCreate("User")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at l.handleErrors (/home/node/parabol/dist/preDeploy.js:18:1712062)
    at l.resolve (/home/node/parabol/dist/preDeploy.js:18:1710687)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.run (/home/node/parabol/dist/preDeploy.js:18:1701780)
    at async Promise.all (index 0)
    at async t.up (/home/node/parabol/dist/preDeploy.js:2:594486)
    at async t.up (/home/node/parabol/dist/preDeploy.js:18:16975)
    at async /home/node/parabol/dist/preDeploy.js:18:19058
    at async u (/home/node/parabol/dist/preDeploy.js:18:18734)
    at async Promise.all (index 0) {
  msg: 'Table `actionProduction.User` already exists.',
  type: 17,
  cause: undefined,
  term: [ 60, [ [Array], 'User' ] ]
}
ReqlOpFailedError: Table `actionProduction.User` already exists in:
r.db("actionProduction").tableCreate("User")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at l.handleErrors (/home/node/parabol/dist/preDeploy.js:18:1712062)
    at l.resolve (/home/node/parabol/dist/preDeploy.js:18:1710687)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.run (/home/node/parabol/dist/preDeploy.js:18:1701780)
    at async Promise.all (index 0)
    at async t.up (/home/node/parabol/dist/preDeploy.js:2:594486)
    at async t.up (/home/node/parabol/dist/preDeploy.js:18:16975)
    at async /home/node/parabol/dist/preDeploy.js:18:19058
    at async u (/home/node/parabol/dist/preDeploy.js:18:18734)
    at async Promise.all (index 0)
👴 RethinkDB Migraiton Complete
🐘 Postgres Migration Started
PostgreSQL - No migrations to run!
🐘 Postgres Migration Complete
🔗 QueryMap Persistence Started
⛓️ Prime Integrationgs Started
⛅️ Push to CDN Started
⛓️ Prime Integrations Complete
/home/node/parabol/dist/preDeploy.js:2
```

The script failed at the end, but IMHO it shouldn't have started the Postgres migrations, not even arrived to the `RethinkDB Migraiton Complete` as RethinkDB migrations failed before.

I consider this important as it might have executed Postgres migrations even after errors on the RethinkDB migrations. IMHO if one script fails, pre-deploy should stop and exit there, not continuing with the rest.

### Acceptance Criteria (optional)
Pre-Deploy script exists as soon as one of the scripts fails at any point.

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by rafaelromcar-parabol** [comment]
It failed due to other reasons. I had `CDN_BASE_URL='NO_CDN'` and it then didn't fail when I changed it to `CDN_BASE_URL=''`. It means it wouldn't fail for an error on the migration phase. 

Changing this to P1

**Comment by mattkrick** [comment]
i'm pretty perplexed how you got to this state! did you perhaps restore every table except the `_migrations` table in RethinkDB?

2 conditions must be true in order to get here:
- The `User` table exists
- the `initialize` migration was already run, but does not exist in the `_migraitons` table

I could be wrong, but it seems like this does not affect new deploys or existing deploys, only deploys that have 1 DB that got caught in a partial state. For the sake of time, rather than debug more, I'd just ignore this since it seems to be quite an edge case. Let me know if you agree!

**Comment by mwermuth** [comment]
Looked at this during backlog grooming. @mattkrick and @rafaelromcar-parabol do you still think that is a P1? If not please feel free to change the label. Otherwise that would mean you'd only focus on this one right now. Probably more a P2 as one person is digging into this and not you all, right?

**Comment by rafaelromcar-parabol** [comment]
I saw it again right now in the GCP Dokku VM while migrating from DO. [Here](https://circleci.com/api/v1.1/project/github/ParabolInc/parabol/19394/output/110/0?file=true&allocation-id=65003a593f5bb30f8ca63701-0-build%2FABCDEFGH) is the log.

It failed during the RethinkDB migration due to some problem with the PSQL SSL certificates and the script didn't stop right away. It only stops once it gets to the Postgres migration, and there is no clear message about why then. The only error message is multiple lines above, when running the migration `[migrate-rethinkdb]  ↑  up  ↑  20160923154400 project ` which fails, and then it continues with `[migrate-rethinkdb]  ↑  up  ↑  20161013161900 project`. Then it executes well the rest of RethinkDB migrations and that part ends with `RethinkDB Migraiton Complete`. It then starts Postgres `Postgres Migration Started` and stops, without any kind of error.

IMHO this should be P1 as it might lead to data corruption or the application being unavailable.

**Comment by rafaelromcar-parabol** [comment]
I think this is 100% fixed, isn't it @mattkrick ?

**Comment by mattkrick** [comment]
yessir
