### ISSUE TITLE
Users are unable to group cards smoothly

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#8817]
A [user](https://app.hubspot.com/contacts/3888472/record/0-1/149660351) 🔒 shared [two videos](https://parabol.slack.com/archives/C4JAUUZ9P/p1694432144589349) 🔒 of their meeting, specifically during the Group phase.

There's seems to be issues with lagging, jumping, dragging and mistaken dropping - all while moving reflections in the Group phase.

**Comment by Dschoordsch** [comment]
Happened to me as well on Safari with many columns and horizontal scrollbar and many reflections and vertical srollbar. Not sure which part is important.

**Comment by acressall** [comment]
We removed this from the current sprint due to only hearing of it once and difficulty to reproduce.
Now that @Dschoordsch has seen it in the wild, it could be easier to troubleshoot. Will keep an eye on it for now

**Comment by jordanh** [comment]
Will reopen if we hear of it again
