### ISSUE TITLE
Activity library: Cannot search/list templates that pre-existed Activity Library

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8821]
## Issue - Bug

Might need some investigation. [See this Slack message for full context](https://parabol.slack.com/archives/C053J59PQLT/p1694535095514869).

### Acceptance Criteria (optional)
Users can:
   - search all templates even those created before the AL release
   
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by BartoszJarocki** [comment]
@jordanh I did some investigation and here's what I'm not sure I understand

* template `Trimester Planning` belongs to the team with id `rkJF5kA0-` 
* team from the above is a part of the organization with id `Skc7syWwNox` called `Parabol`

now, when you look at the `MeetingTemplate` table, this template has the `cwxuOXroJy` org id set, which is `PARABOL PUBLIC`. Does it look right? ie. template owned by a team, that's not a part of org that's set for this template?

**Comment by mwermuth** [comment]
@BartoszJarocki have you checked if this might be related to a filter in the search regarding the creation date? @Dschoordsch mentioned something like that in our backlog scrub. Going to mark this as a P3 for now.

**Comment by Dschoordsch** [comment]
I checked a couple of things that could have affected this, but based on @BartoszJarocki comment I think it was a data error and I will close this.
