### ISSUE TITLE
Activity library: Template sharing is not working as expected

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#8822]
## Issue - Bug

Might need some investigation. [See this Slack message for full context](https://parabol.slack.com/archives/C053J59PQLT/p1694535095514869). This might be a consequence of #8821

### Acceptance Criteria (optional)
Users can:
   - share templates as expected
   
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
I could not reproduce an issue here.
