### ISSUE TITLE
Stories in estimate phase say "integration is down"

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#8832]
## Issue - Bug

- **How serious is the bug?** P2 -> note: I can't replicate the issue and don't know how many users it is impacting, suggest to increase priority if determined it is impacting majority of users
- **OS:** macOS
- **Browser:** Chrome 116.0.5845.179

### Acceptance Criteria (optional)
Users can:
   - add a Jira issue in the scope phase
   - see issue details in estimate phase
   - estimate issue and send to Jira
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

Context, including video from users: https://parabol.slack.com/archives/C4JAUUZ9P/p1694651544057339

**Comment by jordanh** [comment]
No longer happening? Iceboxing
