### ISSUE TITLE
Remove AI Summary from discussion thread

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8858]
Since upgrading to 3.5 turbo, the AI Summaries have become longer. Now that we have the prompt suggestions in the discussion thread (and they're good!), we should remove the AI Summary and just have the discussion prompt so that there's less text in the thread.

We will need to have released discussion prompts to all users before removing the AI Summary. 

### AC

- [ ] Remove AI Summary from discussion thread once discussion prompts have been rolled out

**Comment by jordanh** [comment]
Just saw this. I'll tie this one to the AI Discussion thread issue, too
