### ISSUE TITLE
Trial mutation 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#8863]
## Issue - Enhancement

With more paid features, the sales team wants to be able to give prospective users access to try out these features during the sales process. Today, this would require running several mutations, both to start the trial period and to end it. 

Challenges brought up so far: 
- How do we handle org-level vs user-level flags? [My opinion: I'd like to know what options we have here. We could limit this to just org-level features, if that would simplify implementation, or ask for a set of user IDs for user-level flags, or something else that someone else suggests] 
- @tghanken suggested that the mutation could accept a set of flags (to cover the early access case) 
-  @igorlesnenko suggested 2 parts: temporary upgrade to paid, and then remove feature flags
- @tghanken raised: how does this impact our reporting? [My opinion: these types of accounts should be flagged as 'trial' in some way, then upgraded/downgraded as appropriate] 

[Background in Notion. 
](https://www.notion.so/parabol/Trial-Mutation-for-Sales-312a0f7426c7492e99c126b54c450b73)

## Acceptance Criteria 

The ideal solution would allow: 
- Sales team members can run a single mutation per account to give that account access to all paid features 
- [Bonus] Sales team members can optionally include early access features in the trial 
- When a trial is over, sales team members can run 1 mutation to again remove access, if appropriate
- If an account upgrades, feature flags are appropriately cleaned up 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
I think the cleanest solution would be to introduce a new tier in the code `trial` which is handled like the `team` or `enterprise` tier in code. This way they would get exactly what they'd get when upgrading, without any feature flag messing around. We would need to decide which one, or introduce 2 different trial levels.

Stopping the trial requires cleaning up some paid features:
* email verification
* SAML information
* ?

**Comment by igorlesnenko** [comment]
Stripe has built-in trial functionality, worth checking if it make sense to use it

https://github.com/ParabolInc/parabol/blob/6e03ccfda34d63d59a0f6b48650477924c26a948/packages/server/utils/stripe/StripeManager.ts#L129
