### ISSUE TITLE
Loading CSS chunk 520 Error

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8868]
Affected 210 users over the past month since release v6.116.

https://parabol.sentry.io/issues/4411877910/?referrer=github_plugin

```
ChunkLoadError: Loading chunk 4953 failed.
(error: https://action-files.parabol.co/production/build/RetroVotePhase_588c05856a54e2557204.js)
  at (error:  (/production/build/RetroVotePhase_588c05856a54e2557204.js))
  at Array.reduce (<anonymous>)
  at phaseLookup.vote (./packages/client/components/RetroMeeting.tsx:34:27)
  at Set.forEach (<anonymous>)
  at sink.next (./packages/client/Atmosphere.ts:220:9)
...
(36 additional frame(s) were not displayed)
```

**Comment by mwermuth** [comment]
Came up during Backlog grooming. Moved it to a p1 to be safe.

**Comment by mattkrick** [comment]
yep, p1 sounds right. since the CSS is cross-origin we can't measure content-length when it's inside the cache. somehow we'll need to make sure that we don't cache 0-length assets. perhaps we can measure it after it's fetched but before it's cached?

**Comment by acressall** [comment]
In case it's helpful context, I think this is happening for me. [Here's how it's showing up in the app](https://parabol.slack.com/archives/C4JAUUZ9P/p1695852584541069). 

I noticed it only happens in Chrome; Safari and Firefox are fine. I'm using Chrome Version 116.0.5845.187

**Comment by Dschoordsch** [comment]
Testing locally I got
```
The FetchEvent for "http://action-files.parabol.co/development/build/0cf1f647c5c101cb1641.css" resulted in a network error response: an "opaque" response was used for a request whose type is not no-cors
Promise.then (async)
(anonymous) @ sw.js:81
```
