### ISSUE TITLE
Meeting timer sometime adds X min, 2 secs

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8876]
<img width="301" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/daf61034-a180-4562-b8d0-b56e486842e1">

See loom: https://www.loom.com/share/cce8d4eabb49406cb081f9652342913e

AC: 
- Timer always adds an even number of minutes without extra seconds

**Comment by mwermuth** [comment]
Came up during backlog grooming. After a chat with @Dschoordsch we decided to close this as priority for this is fairly low, and the reason probably being that clocks on devices + server are out of sync.
