### ISSUE TITLE
ENV to change base URL?

### ISSUE THREAD

**Issue by chrism417** [ParabolInc/parabol#8911]
When deploying parabol via docker, is there a way to change the base path? I don't see the ENV for it.

 For example:

instead of http://localhost I want it to be http://localhost/parabol

**Comment by Dschoordsch** [comment]
[Here](https://github.com/ParabolInc/parabol/blob/master/docker/parabol-ubi/docker-build/README.md#run-the-application-using-a-docker-image) you can see examples of how to run some of the services. The [README](https://github.com/ParabolInc/parabol/tree/master/docker/parabol-ubi/docker-host-st) points to the `.env.example` file. The important variables for this setting are [`HOST`](https://github.com/ParabolInc/parabol/blob/10b3cb990b563ef5c4830efcdef00ff31eff664a/.env.example#L39), [`PROTO`](https://github.com/ParabolInc/parabol/blob/10b3cb990b563ef5c4830efcdef00ff31eff664a/.env.example#L68) and [`PORT`](https://github.com/ParabolInc/parabol/blob/10b3cb990b563ef5c4830efcdef00ff31eff664a/.env.example#L59)

**Comment by Dschoordsch** [comment]
Closing this now, but please feel free to comment or open another issue if it's not completely answered.

**Comment by chrism417** [comment]
@Dschoordsch thanks for the response. If I change HOST to http://localhost/parabol, I get 404 trying to visit http://localhost/parabol. The website is still only available at http://localhost.

**Comment by Dschoordsch** [comment]
Sorry, missed that part before. The app and it's server are not a general purpose webservers. If you want to serve it on a domain or subdirectory, you need to configure a reverse proxy (nginx for example) to do that.
You would still need to modify the environment files mentioned above so the apps links and connections work correctly in all cases.
