### ISSUE TITLE
Your Work: Add analytics

### ISSUE THREAD

**Issue by jmtaber129** [ParabolInc/parabol#8924]
Add analytics tracking for the Your Work drawer.

AC:
Instrumented the following:
- [ ] Opened your work drawer (either click or impression)
- [ ] Integration panel impressions (i.e. viewed Parabol, GitHub, etc.)
- [ ] Connect integration from panel
- [ ] Integration card interactions
  - [ ] Clicked link
  - [ ] Copied link/title
- [ ] Drawer closed
- [ ] Repo/Project filtered

**Comment by tghanken** [comment]
The only thing I'd add is closing the work drawer, so we can figure out if users are viewing but not getting value out of the feature.

**Comment by jmtaber129** [comment]
@tghanken should tracking for closing the work drawer be for _explicitly_ closing the drawer, or just anytime the drawer closes? For example, if the work drawer closes because the user opened a discussion drawer, should we track that as the user closing the drawer even though the user didn't explicitly close the work drawer?

**Comment by tghanken** [comment]
I only think we need to track explicit closes.  We're looking to gauge engagement with the new feature, and I think explicit closes are going to be a much stronger signal for what we're looking for.
