### ISSUE TITLE
Add License Count Endpoint with ENABLE_LICENSE_COUNT_ENDPOINT env variable

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#8935]
**Description:** To ensure accurate licensing counts for DOD customers, we need to develop an endpoint that counts the number of users in the Enterprise tier. The endpoint should only be enabled when the ENABLE_LICENSE_COUNT_ENDPOINT environment variable is set to true.

**Background (slack thread notes):**
- License counts should primarily consider Enterprise tier users since charges are based on Enterprise features.
- The goal is to count all users in a deployed instance under a single organization.
- In the absence of a single org deployment: Count all unique email addresses and retrieve the date of last activity for each user.
- This approach should apply to all users, regardless of their organization, as long as they derive value from a private instance.
- The suUserCount currently only counts users within the organizations the querying user belongs to. This process might need modification to capture all users, even those outside the querying user’s organization.
- The only option is a direct database query, but doesn't suffice to retrieve all users not belonging to the querying user's organization.

**Objective:**
- Develop an endpoint to count tiers of users
- This endpoint should only be active when ENABLE_LICENSE_COUNT_ENDPOINT is set to true.
- Implement a mechanism counting all unique email addresses, retrieving their last activity date.

**Comment by mwermuth** [comment]
@adaniels-parabol how time sensitive is this work? How quickly do we need this?

**Comment by adaniels-parabol** [comment]
> @adaniels-parabol how time sensitive is this work? How quickly do we need this?
> 
> Maybe we can even reformat this request a bit, and make it more usable in general. Like a "All users under one domain" or something similar.

I think that is a great idea as well, would make it easy to find users of a specific domain without needing to be a part of the domain where the users reside to get an accurate license count. I still believe we need a way to count every user on the instance, no matter the domain e.g. DOD users may have mixed domains e.g. af.mil, army.mil. navy.mil on a single instance, especially in instances where the instance is procured by a joint-command (e.g. multi branch).

**Comment by adaniels-parabol** [comment]
@mwermuth I feel it would be useful in accurately accounting for users on instances where we rely on non-Parabol staff to take count of users (e.g. off-net or DOD customers). IMO I don't think it has to be highest priority, but it would be useful for sure.

**Comment by adaniels-parabol** [comment]
This is certainly not the highest priority.

**Comment by jordanh** [comment]
Going to icebox this one for now. I'm sure that it'll come back soon with a slightly different set of AC. My guess is, we can create an endpoint for su rol users that won't depend on an env var
