### ISSUE TITLE
Update sign up destination

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#8941]
Design #8639 

AC

- On signup: user lands on team dashboard with "manage team" panel open
- On subsequent signup: user lands on `/meetings` view

**Comment by acressall** [comment]
@tghanken do you want a separate issue for the rollout of this? It only impacts new sign ups, so I'm thinking we test quickly, with 50/50 and keep an eye on:

1. Invitations
2. Meetings started
3. Returning users
4. MAU of users signed up in test period

**Comment by tghanken** [comment]
A rollout issue would be great.  I agree with your thinking on how we can handle it!

**Comment by acressall** [comment]
Issue created for rollout https://github.com/ParabolInc/parabol/issues/9030

I've added both these issues to the onboarding milestone https://github.com/ParabolInc/parabol/milestone/185

**Comment by Dschoordsch** [comment]
@acressall what's the intention about the subsequent logins ending on `/meetings`?

**Comment by acressall** [comment]
@Dschoordsch it was a concern over multiple teams and not knowing which to send them to. I'm fine with having them land here if there's only one team
