### ISSUE TITLE
Application files should not be served from action.parabol.co

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8948]
All files in the `parabol-static` cache are served from the webserver directly instead of the CDN.
<img width="771" alt="Screenshot 2023-10-09 at 11 17 27" src="https://github.com/ParabolInc/parabol/assets/7331043/62e4c746-2f0d-42f3-881a-ab361035a9da">
The 300 files amount to around 1.6 MB

**Comment by mattkrick** [comment]
this is so weird because those URLs are invalid. if you look at the preview you'll see each one returns our HTML, not even the assets 🤔 . tbh not even sure how the app is working in its current state

**Comment by Dschoordsch** [comment]
Looking at the static and dynamic cache we have:
static: `/TeamFilterMenu_d462eccfa23818e42d74.js`
dynamic: `/production/build/TeamFilterMenu_d462eccfa23818e42d74.js`
So we're just fetching everything into the dynamic cache, the static one seems to be fully ignored

**Comment by rafaelromcar-parabol** [comment]
Ignored but downloaded at least once, isn't it? 🤔 I mean, that can still be a problem on releases with a lot of clients connecting at the same time. We should fix it anyway, or get rid or the static cache if that make sense
