### ISSUE TITLE
Show who is inviting you to Parabol

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8949]
@garethaledavies suggested [here](https://parabol.slack.com/archives/C03NGEJUKCN/p1696672232145009) that we should show who is inviting you to Parabol in the subject line. 

At the moment, it says, "You've been invited to Parabol", which one might think it spam.
![](https://files.slack.com/files-pri/T08FL6336-F05V5PM8GH5/img_1861.jpg)

### AC

- [ ] Email subject line says who has invited you to Parabol

**Comment by jordanh** [comment]
This is a nice, simple issue. Going to elevate this on up the backlog

**Comment by Mohd-Muneeb** [comment]
Hey @jordanh, I've sent fix for the issue in the linked PR, do look into it and merge if it LGTM!
