### ISSUE TITLE
Template Limits v2: increase the number of free public templates

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8974]
We currently have seven free public templates. This may feel overly restrictive for new users when they see a long list of premium templates that they can't use.

### AC

- [ ] Increase the number of free templates

**Comment by nickoferrall** [comment]
@garethaledavies or @tghanken do you have any thoughts on how many free templates we should add and which ones?

**Comment by tghanken** [comment]
I think we should try to structure it around the activity library, and ensure that each tab has a meaningful (3+?) number of free templates.  Other than that, I don't have any real thoughts on which specific templates should be included.  Do we want some of our more popular ones locked? Or free?

**Comment by nickoferrall** [comment]
Makes sense. I'm thinking we should make some of our more popular templates free to prioritise usage. If we notice a big drop-off in template conversions, we could make some of them premium again (ideally, we don't change free/premium templates too much, of course). 

I'm thinking we can increase the number of free templates from 7 to 12, adding the 5 most popular premium templates from this list: https://app.amplitude.com/analytics/parabol/chart/inrjy9s

**Comment by garethaledavies** [comment]
[Here are the stats](https://docs.google.com/spreadsheets/d/1FuSTy5EM3YWsNlva_T9UtLVRsTuwIlkgAwpealfNBCY/edit?usp=sharing) for the template pages that converted best over the past 12 months:

Based on that I’d say we should open up:

**Holiday-related templates:**
- Halloween
- Diwali
- Easter
- Christmas
- New Year

**Other top converting templates:**

- SWOT
- Mountain Climber
- What Went Well
- Energy Levels
- Keep Problem Try
- Three Little Pigs

An alternative that I’m sure the squad already considered, but wanted to throw out there, would be to give everyone “team tier” Parabol for 2 weeks, or 1 month, and then downgrade afterwards to encourage team tier conversion. That would mean all our templates can successfully pull people into the product + activate them. If that hasn’t been discussed yet, I’d be happy to add a GitHub issue for it.
