### ISSUE TITLE
Repository filter not working first time, needs refresh

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8991]
## Issue - Bug

It looks like the repo filter in Your Work drawer does not work the first time it opens? A refresh fixes it though. This is the same logic used as in Sprint Poker so there could be an issue there too. See 🔒[Slack discussion](https://parabol.slack.com/archives/C042HTVBH8D/p1697755507837629)

![2023-10-19 15 43 27](https://github.com/ParabolInc/parabol/assets/1879975/df10ccfe-519e-4bac-9791-683c2f17acc2)

### Acceptance Criteria (optional)
Users can:
   - [ ] see their repositories on first open the Your Work drawer 

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
Iceboxed during scrub
