### ISSUE TITLE
Investigate how can we use Tailwind CSS in emails

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#9022]
To use Tailwind CSS in emails we need an additional step of translating Tailwind CSS classes to either inline styles or stylesheet included in email. The next step after solution outlined in this task is accepted would be to create implementation issues.

AC:

- [ ] solution proposed on how can we use tailwind css in server rendered emails

**Comment by mwermuth** [comment]
Hey @BartoszJarocki I moved this main issue into our squad. I guess this will be updated once other issues are moving forward.
