### ISSUE TITLE
UI overlap on mobile meeting start activity screen

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#9061]
When viewing the meeting start activity screen, there is significant UI overlap causing display and clicking issues.

![image](https://github.com/ParabolInc/parabol/assets/71724289/2c9dce58-5a4f-4f3c-831b-f4f4810019b2)

**Comment by acressall** [comment]
It looks like the mobile view was never built, but @enriquesanchez did design it. Enrique, is [this](https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1614-34837&mode=design&t=RQ9pF7GteP4dDtl9-4) the correct design?

**Comment by enriquesanchez** [comment]
Hi! 

@acressall @nickoferrall Yes, those are the correct designs. I don't know why these were not implemented 😞

**Comment by nickoferrall** [comment]
Great! Thanks for sharing. I'll remove the design label and work on implementing this 👍

**Comment by nickoferrall** [comment]
Just wanted to check what you think about this design @enriquesanchez or/and @acressall?

![Screenshot 2023-11-30 at 19 00 53](https://github.com/ParabolInc/parabol/assets/39854876/d8989f3d-16bf-4ddc-aba1-cc44dd3e92ae)

Clicking the downward arrow icon on the right of the settings would minimise the settings, only showing the two CTA buttons (and the button that shows any active meetings).

Then just the settings title with an upward icon would show up, letting the user expand the settings.

My thinking is:

1. It's simpler to build the above screenshot 
2. When clicking on a settings icon (as in the design below), I expect to be taken to another page, but this would expand the settings.

What I don't like in my suggestion is the downward arrow icon in the Team selection clashes with the icon above it. That's not ideal, but not too bad IMO. 

![Screenshot 2023-11-30 at 19 05 35](https://github.com/ParabolInc/parabol/assets/39854876/2b57286f-3817-41dc-b8d8-9c556e5068c6)


Curious to get your thoughts 🙏

**Comment by enriquesanchez** [comment]
+1 to Alicia's comments.

@nickoferrall I do want to see how this looks collapsed. We want to avoid users missing the settings and starting an activity on the wrong team :)
