### ISSUE TITLE
YouTube video link for all caught up message is broken

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#9063]
## Issue - Bug

![2023-10-26 10 07 56](https://github.com/ParabolInc/parabol/assets/1879975/41195f56-8e01-4777-b496-e5e7a9946ebe)

### Acceptance Criteria (optional)
Users can:
   - [ ] link to a working video or that CTA is removed?
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
What should be done instead? Remove the link? Find something else to link to? Depending on external assets is rough
