### ISSUE TITLE
Bug: Cannot login with Google on Android Chrome

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9069]
Trying to login with Google on Android Chrome 117.0.5938.153, Android 11 results in "Error logging in".
The issue is caused by [`window.opener`](https://github.com/ParabolInc/parabol/blob/a826bb74feb89390b8585561e78254c4a6b0fd98/packages/client/components/AuthProvider.tsx#L12) being `null`.
I have multiple Google accounts on that phone.

From the dev tools it looks like the account selection is not opened in the same tab as the redirect, so we end up with 3 windows: main app, google account selection, oauth redirect.

**Comment by Dschoordsch** [comment]
For now classifying it as P2 as I could not see evidence for customers experiencing this, but that might change.

**Comment by Dschoordsch** [comment]
I can log in with the same phone on staging 🤔

**Comment by mattkrick** [comment]
staging uses a different (non-public) OAUTH2 app. I bet google is more secure for public apps.
I'm not sure how to solve this! auth0 uses the same logic, but i haven't combed through their issues yet. maybe someone attempted a PR to fix?

https://github.com/auth0/auth0-spa-js/blob/e272225a2b6c0489ab5e7d94cc6dd91987e23087/src/utils.ts#L104-L111

**Comment by rafaelromcar-parabol** [comment]
FYI, I just tried with my Android Chrome and I could log in production without any trouble. Could you try and close this bug issue if it's fixed?

Chrome 131.0.6778.81
Android 13

**Comment by Dschoordsch** [comment]
Works for me now.
Chrome 131.0.6778.81
Android 13

Closing as we don't have any user reports and cannot reproduce the issue.
