### ISSUE TITLE
Jira project not showing when trying to export task cards

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#9074]
## Issue - Bug

A [user](https://app.hubspot.com/contacts/3888472/record/0-1/89516001) is unable to find the Jira project he wants using the search box when pushing a task to Jira.

> I'm trying to have Parabol integrated with Jira Cloud so that me and my team can export into our Jira board the action points we set up for ourselves after our recurring retrospectives.
> The issue I have is that, once the integration is enabled, I do not see our project among the options showed when I click to export an action point.
> I only get presented with some entries and I am wondering which kinds of settings do I need to enable on the Jira Cloud part

> Thanks for reaching out. Do you see any projects in the dropdown menu during the scope phase? Could you try:
> Refreshing the token for the Jira integration on your team inegrations page
> Running a JQL query that includes text which filters to the project you're looking for
> If neither of those work, could you please provide us with a screenshot of what you're seeing so we can further troubleshoot.

> I did refresh the token but I believe it not to be the issue here
> Running a JQL query did not seem to have any effect, since when I click on the integration it seems to have a search bar based on project names, so I am not sure what would a JQL query do in there
> Here is the screenshot of what I see, which are some projects that I assume are in our company's Jira instance.
> As you see I succeeded in sending an item to Jira, although to the wrong project, and I could see that in the board fro that project, so I believe it is only a matter of making our project appear in the list and then the integration should work.
> Unfortunately I have been searching for it but it does not seem to be showing up

[Link to Slack thread with screenshot](https://parabol.slack.com/archives/C4JAUUZ9P/p1697791793512289)

> Is there a specific setting or other thing I should look in Jira for to enable the project/board to be seen by the integration?
> If I go into my Jira - Projects list I see the first ones listed there are the same as the first one appearing in Parabol (screenshot I sent previously) but then if I filter in Jira for my project I see it, whereas in Parabol not
> Could it be that the integration fetches only a limited amount of projects?
> I see we have 23 pages of projects in Jira but when I try to search in your integration I see that the filtering works well for projects in the first 4 pages, whereas if I try to search for the first project I see in our 5th page in Jira the integration does not find it
>

**Comment by jordanh** [comment]
@gcrickman just doing some spring cleaning – if this is still an issue happy to reopen
