### ISSUE TITLE
Can't push task to Jira Server integration

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#9078]
## Issue - Bug

After integrating Jira Server I can't push any tasks to a project. Server returns empty string as an error so investigation is needed to find more information.

### Acceptance Criteria (optional)

- [ ] user can push a task to Jira Server project

**Comment by Dschoordsch** [comment]
@BartoszJarocki which Jira project did you test with? I intentionally broke one of the test projects.
