### ISSUE TITLE
Implement switching templates during a retro UI

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9087]
See design issue here: https://github.com/ParabolInc/parabol/issues/9047

Figma designs here: https://www.figma.com/file/3mCDNSuJeByj3jiMeGm7yb/Change-retro-template-within-meeting?type=design&node-id=1-1006&mode=design&t=vXi8NP08RgHAYSX4-0

### AC

- [ ] Show options button in retro meeting, just like Standups
- [ ] A dropdown menu opens with "Change template"
- [ ] If a reflection has been added to the meeting, "Change template" is disabled. A tooltip pops-up when hovering over it explaining that you can only change the template before a reflection has been added
- [ ] Clicking "Change template" opens a right drawer with the templates
- [ ] Clicking a template does nothing. The logic will be handled in a subsequent issue.
- [ ] The options button only shows up in the reflect phase as you can't change the template in other phases. This can be changed when we add recurring retros.

**Comment by jordanh** [comment]
Going to icebox this for now

**Comment by Dschoordsch** [comment]
I un-iceboxed the issue. We figured this might be an important part of recurring retros, so the user still has the option to change the template. It should be mostly done, just needs merging of the PR.
