### ISSUE TITLE
Notify to Slack when master actions fail

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#9103]
## Issue - Enhancement

Notify to Slack channel `engineering` when:
- [ ] Github Action Build fails on master 
- [ ] Github Action Test fails on master

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))​

**Comment by mattkrick** [comment]
this should be obviated by our new gitops pattern!
- a push to master MUST come from a PR, no direct pushes
- a PR must first merge master (this is new! this is what saves us)
- a PR should pass tests before it can get merged to master

**Comment by rafaelromcar-parabol** [comment]
We just had two cases where @jmtaber129 merged [two commits](https://github.com/ParabolInc/parabol/commits/master) ([this](https://github.com/ParabolInc/parabol/commit/a147fa34af958a74facde516347d9a8b91e6aa72) and [this](https://github.com/ParabolInc/parabol/commit/0fdef2d8371be3f65326e28af4a585bc500f0ed3)) to master and they are marked as failed because the tests were canceled. IMHO that should send a notification.

**Comment by rafaelromcar-parabol** [comment]
It happened again. Master was broken because tests were failing and nobody noticed till I said something on Slack 😸 Let's hope we can tackle this during the next month.

**Comment by rafaelromcar-parabol** [comment]
And it happened again, so I'm opening a branch and a PR to add some notification system to our Slack
