### ISSUE TITLE
Activity Library: Force name of new custom templates

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#9107]
## Issue - Enhancement

Some users struggle to create new custom templates. They think our product is broken:

> Since new UI was implemented, I have issues creating and finding templates. Is there any way to see and edit all the templates created by our organization? at this point I can’t create a new template because “you already have new template created, try renaming that one first” and I can’t find how to edit existing templates can you guide us a bit? thanks!

I share this tension. For me, it shows up where we’ve got a growing number of `*New Template` templates in our Activity Library. It makes a few things difficult:
   - When I try to create a new custom activity on a Team, often it tells me there is already a *New Template , to find that one, and customize it
   - There is no way to filter the Activity Library by team, so I can’t find the particular *New Template to delete it
   - When I demo Parabol with a screenshare, the Activity Library looks messy and I’m also unable to demo the new custom activity feature

We held [a brainstorm here ](https://parabol.slack.com/archives/C836NA350/p1698337168517479)🔒. @Dschoordsch suggest the change that resulted in the below Acceptance Criteria.

### Acceptance Criteria (optional)
   - When a user creates a new custom template, the template name is focused first and the validation forces them to create a template name of at least 3 characters
   - Optional: we generate a unique name for the template ("Slinky Snake Activity", "Fantastic Fox", etc.), but select the text when the field is focused such that it is easily overridden

**Estimated effort:** 8 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by Dschoordsch** [comment]
As a quick fix we could also just append a number to the `*New Template #12`

**Comment by jordanh** [comment]
This has been implemented
