### ISSUE TITLE
Accessing jira-attachments will result in a 5xx 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#9111]
From Slack:
https://parabol.slack.com/archives/C4JAUUZ9P/p1698966704621919?thread_ts=1698858093.998069&cid=C4JAUUZ9P

> response_sent_by_backend: mostly [action.parabol.co/jira-attachements/HASHES](http://action.parabol.co/jira-attachements/HASHES) urls. 1087 entries, see GCP logs [here](https://console.cloud.google.com/logs/query;query=resource.type%3D%22http_load_balancer%22%20AND%20http_request.status%3E%3D500%0AjsonPayload.statusDetails%3D%22response_sent_by_backend%22;summaryFields=jsonPayload%252FstatusDetails:false:32:beginning;cursorTimestamp=2023-10-31T15:49:42.262323Z;duration=P7D?project=parabol-saas-production). Something must be not working with Jira. This status response_sent_by_backend means that the application is answering with 5XX and the LB is just passing the answer through. We should probably fix how we manage errors coming from JIRA to stop answering with 5XX here.
Latency for the jira-attachements isn't that high, most of them less than 200ms and some almost 1s
Also some POST calls to [action.parabol.co/graphql](http://action.parabol.co/graphql), which have higher latency (over 10s).

AC
- [ ] audit the [handler](https://github.com/ParabolInc/parabol/blob/7c60878ee1740fd9b60a1d62c10b584d04802d11/packages/server/jiraImagesHandler.ts) and see why we don't always return a 200
- [ ] if it's still unclear, gather some recent logs & see if we can repeat the request for a given hash

**Comment by rafaelromcar-parabol** [comment]
This is a P2 but very important for us DevOps as it adds noise in our metrics and logs. It would be great to have it fixed asap.

**Comment by mwermuth** [comment]
Hey @mattkrick I saw you added this to the DevOps board. Will you be able to fix this?

**Comment by mattkrick** [comment]
yep

**Comment by mattkrick** [comment]
Now that we have a healthy number of images imported from the server, I think we can standardize how they should be imported.

We have 3 images:
- our logo, used in mattermost messages. what we want here is a URL that points to the instance's CDN so when the client opens up their mattermost, it loads from their CDN, which they have whitelisted
- anonymous avatar, used in emails. needs to be a raster (another issue), but also needs to be available in the email (base64 inlining is another option, but our emails can get so big they get truncated)
- jira image not found. we keep this on the webserver as a buffer. it'd be great to keep it local, but a one-time fetch is worth the simplicity vs. special casing it!

in dev mode, these 3 should end up in the `/dev` directory, which should get fetched from /static)

**Comment by mattkrick** [comment]
done back in Dec
