### ISSUE TITLE
Add SSO to new checkout flow

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9123]
The SSO feature only exists in the old checkout flow at the moment. It should probably be a new tab in the organisation sidebar. 

### AC

- [ ] Add SSO feature to new checkout flow

**Comment by Dschoordsch** [comment]
Please ping @mwermuth once it's done

**Comment by charlesmathias** [comment]
Recent example of an Enterprise org not being able to activate their SSO after purchase due to this missing feature:
- [Enterprise org](https://parabol.slack.com/archives/C4JAUUZ9P/p1699051754489979) 🔒
