### ISSUE TITLE
Error: Template already created

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9167]
When I tried to create a custom template, I clicked the CTA and didn't get any feedback. I could see in the terminal the error message below. I've tried to reproduce it again on Loom, but wasn't able to - now I do get an error message. I'll update this issue if I come across it again.

When I get the error message, it says: `You already have a new template. Try renaming that one first.`. But it's very hard to find the custom template that I created.

It's happened 20 times in the past 8 days.

https://parabol.sentry.io/issues/4594669108/?referrer=github_plugin

```
Error: Template already created
  File "app:///gqlExecutor.js", line 96408, in resolve
  File "app:///gqlExecutor.js", line 130595, in Object.MutationaddReflectTemplateResolver
```

**Comment by jordanh** [comment]
I think this has been fixed... reopen if not true
