### ISSUE TITLE
Replace GA_TRACKING_ID by GOOGLE_ANALYTICS_TRACKING_ID

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#9177]
​Make the variable consistent with the rest of the `GOOGLE_` variables. It is found only in:
- `scripts/toolboxSrc/applyEnvVarsToClientAssets.ts`: `googleAnalytics: process.env.GA_TRACKING_ID`
- `scripts/webpack/dev.client.config.js`:  googleAnalytics: `process.env.GA_TRACKING_ID`

How-to do this replacement:
- [ ] Validate this can be done with the Data team and Developers
- [ ] Add the new variable `GOOGLE_ANALYTICS_TRACKING_ID` in:
  - [ ] Staging environment
  - [ ] Production environment
  - [ ] All the environment files in action-devops
- [ ] Merge the PR created for this issue
- [ ] Release the new version using the new variables
- [ ] Remove the old variable `GA_TRACKING_ID` from:
  - [ ] Staging environment
  - [ ] Production environment
  - [ ] All the environment files in action-devops

**Comment by rafaelromcar-parabol** [comment]
@tianrunhe @tghanken can this be easily done? if yes, I'm probably doing it this week

**Comment by rafaelromcar-parabol** [comment]
Adding also @mattkrick and @Dschoordsch to get their POV

**Comment by Dschoordsch** [comment]
There is no point in making it consistent with other Google services as it's independent of those. GA_TRACKING_ID seems to be a common name for this variable and googling it shows the correct result what to fill in. Searching for google analytics tracking id also works, so I'm indifferent about renaming.
Only downside in renaming could be that someone might think it is in any relation to the other `GOOGLE_` parameters.

**Comment by rafaelromcar-parabol** [comment]
> There is no point in making it consistent with other Google services as it's independent of those

The same could be said about:
```
GOOGLE_CLOUD_CLIENT_EMAIL='key_GOOGLE_CLOUD_CLIENT_EMAIL'
GOOGLE_CLOUD_PRIVATE_KEY='key_GOOGLE_CLOUD_PRIVATE_KEY'
GOOGLE_CLOUD_PRIVATE_KEY_ID='key_GOOGLE_CLOUD_PRIVATE_KEY_ID'
```

And
```
GOOGLE_OAUTH_CLIENT_ID=''
GOOGLE_OAUTH_CLIENT_SECRET=''
```

Both are for Google things that do not relate, but both are GOOGLE and their name are easy to relate their functionality for anyone reading our `.env.example`. In this case, `GA_TRACKING_ID` isn't clear at all for a self-hosted client or anyone reading the `.env.example`. 

That said, I'm also ok with adding a comment above the variable explaining what it is!

**Comment by mattkrick** [comment]
IMO we should keep the token as it is & use a comment. GA libraries likely look for this token by name. While we are no longer doing GA on the server anymore (at least I don't think we are?) it's helpful for folks who are new to the project because it's the generally accepted name

**Comment by tianrunhe** [comment]
I don't have strong preference over any of the two.

**Comment by rafaelromcar-parabol** [comment]
For now, what I have done is to add a comment on the [new version](https://github.com/ParabolInc/parabol/pull/9104/files) of the `.env.example`.
