### ISSUE TITLE
Anonymous reactions are not anonymous

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#9196]
## Issue - Bug

- **How serious is the bug?** P2 or P3. I would say P2 as this is related with privacy.
- **OS:** Linux - but it isn't OS related
- **Browser:** Chrome version 119.0.6045.123 (Official Build) (64-bit)
- **Parabol version:** v7.7.0

https://www.loom.com/share/d6c0d45abab54cc08e656459fff9b1dc?sid=a47ee328-9082-40ea-89fc-e2bfccd52019

### Acceptance Criteria (optional)
Users can:
   - React anonymously and their reactions are anonymous.

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
Came up in backlog scrubbing: Do we want the discussion anonymity toggle also toggle the anonymity for reactions on reflections or do we need a new design for it?

**Comment by rafaelromcar-parabol** [comment]
I assume that if I decided being anonymous, I'm anonymous for everything. 

So same design but toggling anonymity for everything at the same time

**Comment by Dschoordsch** [comment]
> I assume that if I decided being anonymous, I'm anonymous for everything.
> 
> So same design but toggling anonymity for everything at the same time

Sure, I agree. It just seems a bit odd to have the toggle in the discussion panel.

**Comment by rafaelromcar-parabol** [comment]
> Sure, I agree. It just seems a bit odd to have the toggle in the discussion panel.

You are 100% right. I didn't think about that design 😸 it would be _better_ to have the toggle somewhere else, but I would first make sure that right now people are anonymous when they think they are anonymous.

Then, I would do a design change to make that clearer and move the toggle.

**Comment by jordanh** [comment]
I'm going to Icebox this for now; if we get user signal on this I'l reopen and reprioritize

**Comment by rafaelromcar-parabol** [comment]
Wasn't this fixed? IMHO this is important. Anonymity, when offered, should be real anonymity.
