### ISSUE TITLE
Activity Library v2: Handle hover & focus states

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9200]
Designs: https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1581-36866&mode=design&t=j8Z33M8twVhJVMMa-0

### AC

- [ ] Hover and focus states look like the designs above

**Comment by jordanh** [comment]
Those are nice. I'll add them to the Ready queue as the lift is low and we want to get the AL out to everybody
