### ISSUE TITLE
Service worker requesting all assets on every new version

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#9204]
As we release more, we want the impact of a new release to decrease. I noticed that the service worker is downloading all 295 assets when a version gets bumped, even though only a handful of files changed. We need to fix this!

AC
- [x] new versions only trigger a fetch of the changed files
- [x] reduction in opaque requests (add crossorigin to requests, etc. i'll do as many of these before i run out of time)
- [x] skeleton.html is removed from the sw manifest
- [x] License files are removed from webpack build (these are in source maps, which we ship. we're also open source!)
- [x] GraphiQL assets are not included in the sw manifest (we exclude GraphQLContainer, but that's not working because the dependencies are still included. not sure why...)

css doesn't support modifiers to url fetches, e.g. `background-image: url(/foo.png) crossorigin=''`. That means any fetches that originate from css can't have CORS added to them. I wonder if I can intercept this fetch request in the service worker & add CORS to the request 🤔

**Comment by mwermuth** [comment]
@mattkrick similar to the other issue. Is this something you are working on as part of the DevOps team? Also it looks like this is in progress, would be helpful if we had someone assigned to it.

**Comment by mattkrick** [comment]
good call! assigned myself
