### ISSUE TITLE
Email verification whitelisting should support globs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#9226]
We should add support for globs to handle subdomains in OrgApprovals.
In the future we can add this support for SAML, too, but for now just OrgApprovals is necessary.

AC
- [ ] adding `*.parabol.co` to the OrgApproval list will require email verification from `mail.parabol.co`

**Comment by mwermuth** [comment]
As we have quite a few p2's and both squads are pretty packed with tasks and bugs, would it be possible for the devops team, a.k.a @mattkrick on the application side to fix this?

**Comment by mattkrick** [comment]
sounds great!
