### ISSUE TITLE
Org showing up multiple times after auto join

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9229]
@acressall shared the bug here: https://parabol.slack.com/archives/C042E8PGPD4/p1700530049859259

### AC

- [ ] Org only shows up once after auto joining multiple teams in the same org

**Comment by Dschoordsch** [comment]
`acceptTeamInvitation` must not be run in parallel because `adjustUserCount` creates a new `OrganizationUser` if they're not present. This results in duplicate `OrganizationUser` objects and thus the org and teams showing up multiple times.

**Comment by Dschoordsch** [comment]
It's unclear why we always create a new `OrganizationUser`. Until that's answered, this is stuck.
