### ISSUE TITLE
Kudos: send kudos in text in standups

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#9230]
Currently, it is only possible to send kudos by setting emoji reaction. You can't send an arbitrary kudos to someone.

I suggest we recognize kudos emoji in any text and send kudos based on it. For example, a comment 'Kudos to Alicia ❤️' would send kudos, because kudos-emoji is used after the mention.

**AC:**

- Define an algorithm for how we determine what in a text is kudos and to whom it is addressed
- Handle it in standup responses
- If we have to send a mention notification, replace mention notification text with kudos text, for example:`You received kudos...`. Keep in mind slack integration

**Suggested algorithm:**

1. We divide the text by paragraphs. 
2. If there are mentions in one paragraph and kudos emoji anywhere in the same paragraph, everyone who is mentioned gets kudos

**Comment by Dschoordsch** [comment]
Instead of adding a field `isAnonymous` we should make it really anonymous in the database by setting the sender `null`.

**Comment by igorlesnenko** [comment]
@Dschoordsch I see a couple of issues with setting sender as null.
- If we then make a user's dashboard, we can show all the kudos he sent, even his anonymous kudos 
- Kudos wouldn't be really anonymous anyway, because kudos are still bound to either a reflection or a comment for which we store `userId`

**Comment by igorlesnenko** [comment]
@acressall If I only keep kudos notification and remove mention notification it might be not clear that user was also mentioned, because we can also send kudos by reaction.
<img width="443" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/e595ebce-ca8e-4980-a08c-9898144fd329">

What do you think we can do here? Keep both notifications? Modify mention notification text so it will say that it is not only mention but also kudos?

**Comment by igorlesnenko** [comment]
<img width="414" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/1973f6f4-0fb8-4874-8406-f3995a82e07f">

**Comment by acressall** [comment]
Sorry I didn't get to this yet! I think your recommendation is good and we can always update later after trying it out ourselves
