### ISSUE TITLE
Fix active meetings menu position on mobile/tablet

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9272]
![Screenshot 2023-12-06 at 10 30 49](https://github.com/ParabolInc/parabol/assets/39854876/7cc11f98-c873-4e61-abeb-74bcded6d9b9)

### AC

- [ ] The active meetings menu opens in the position where the button is

**Comment by jordanh** [comment]
Related to #9272? Elevating the priority of this one as I know we want to get the AL out to everybody
