### ISSUE TITLE
Refactor NewMeetingTeamPicker menu to Radix

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9274]
The `NewMeetingTeamPicker` currently has a meeting prop called `positionOverride`, which feels a bit hacky. 

We need to update the `positionOverride` if it's on mobile. Its position can be unreliable and needs a refresh - see Loom: https://www.loom.com/share/26a4e81d4d2041ca8d4eaff014dd8e0d

Hopefully, refactoring this `useMenu` to the Radix menu can make it more reliable and enable us to remove the `positionOverride` prop.

### AC

- [ ] Refactor `NewMeetingTeamPicker` `useMenu` to the Radix `Menu` component

**Comment by jordanh** [comment]
Going to elevate the priority of this one as this cycle is focusing on getting the AL out to everybody
