### ISSUE TITLE
Pararbol seems to crash with uWS on node v20 when no authorization header is received.

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#9289]
Pararbol seems to crash with uWS on node v20 when no authorization header is received.

![image](https://github.com/ParabolInc/parabol/assets/71724289/2b185723-f7ff-407a-b678-202eea817c7b)

This was happening on a system where istio was the ingress. I was able to mock it by setting up a local nginx proxy and stripping the headers.

**Comment by mattkrick** [comment]
this is a good one. the lack of headers should've caused an error to go sentry, but it hit another error on its way. fixed in #9292
