### ISSUE TITLE
Bug: duplicate OrganizationUser objects are created in some cases

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9302]
A newly added test to check that we're not creating duplicated `OrganizationUser` objects is failing randomly. It appears there are still duplicates created in certain cases.

> @Dschoordsch it looks like this produced a flaky test result for me-- failed first test, passed on second try. 
>
> https://github.com/ParabolInc/parabol/actions/runs/7278378730/job/19832437203. Should I make an issue for this?
>
>edit: happened again, so likely not a fluke: https://github.com/ParabolInc/parabol/actions/runs/7278798261/attempts/1?pr=9295

_Originally posted by @mattkrick in https://github.com/ParabolInc/parabol/issues/9290#issuecomment-1864849230_

**Comment by Dschoordsch** [comment]
The chance of duplicate org users increases with the number of autoJoin teams.

**Comment by mattkrick** [comment]
you know, we should just put a unique constraint on `userId, orgId, removedAt nulls not distinct`. That'd solve it 😛

**Comment by Dschoordsch** [comment]
Yes, we should. Instead of creating duplicate organization users it will throw an exception, so the code bug is easier to find.

**Comment by Dschoordsch** [comment]
We have around 3600 duplicates. I'll check how to best clean those up and then add a constraint.

**Comment by Dschoordsch** [comment]
We also log duplicate OrganizationUserAudit entries. I'm not going to mess with these.
The duplicates are not consistent in themselves, some are removed, some have multiple active ones. My plan is to keep only the latest active one.
