### ISSUE TITLE
Bug: selected category tags become 100% transparent

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#9338]
## Issue - Bug

1. Go to [Activity Library](https://action.parabol.co/activity-library/category/recommended)
2. Notice the 'Quick Start' tag is selected/highlighted by default
3. Select any other category, e.g., 'Retrospective'
4. Notice the selected tag becomes 100% transparent

<img width="1289" alt="Screenshot 2024-01-15 at 13 48 50" src="https://github.com/ParabolInc/parabol/assets/1879975/ab7abf27-b269-4eef-b051-adb3d4a17a81">

### Acceptance Criteria (optional)
Users can:
   - see the category tag they selected gets highlighted

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
Is already fixed by #9277, just needs to be released properly
