### ISSUE TITLE
New teams in trial org do not have premium features

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#9425]
- enable trial, see you have premium features
 - create a new team, see it does not have premium features

**Comment by Dschoordsch** [comment]
It's not very severe, but because it's on the path to conversion, I'm labelling it P2.

**Comment by jordanh** [comment]
Moving this to a `p3` as there is a work around

**Comment by tianrunhe** [comment]
I couldn't reproduce this issue anymore: after running the mutation for an org, I can see all of the existing teams and newly create teams get access to premium features like health check and AI summaries.

@charlesmathias would you verify?

**Comment by charlesmathias** [comment]
I tried to replicate the bug and had the same experience as you: existing and new teams get premium features.

**Comment by charlesmathias** [comment]
Can we mark this as closed? @tianrunhe
