### ISSUE TITLE
embedder: k8s deployment of embedder service

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#9438]
## Issue - Enhancement

Adding the embedder service will require modifications to our deployment charts. Decisions will need to be made about which model(s) to use and how many resources to mobilize.

Initially, I believe we should target:

   - A single instance of the embedder service that utilizes a CPU-based embedding model (such as llmrails/ember-v1) and Open AI for summarization (depends on: #9436)
   - Enabling the embedder service and recommended discussions only for the Parabol Org Id via a feature flag

### Acceptance Criteria (optional)
We can:
   - Deploy the embedder service and its configuration
   - Deploy a CPU-based embedding model
   - Run the embedder service in order to generate historical embedding artifacts

**Estimated effort:** 13 points

**Comment by rafaelromcar-parabol** [comment]
- Embedder already added to our Helm chart.
- Embedder tested, alongside Text Embeddings Inference, in our on-demand-envs without real data.
- Text-Embeddings-Inference deployed on Staging.
- Waiting for the last step: deploy the Embedder on Staging and observe the result with meaningful data.

**Comment by rafaelromcar-parabol** [comment]
Deployed to Staging.

We agreed on waiting for Production until I'm back (Monday 15th) to give some time to Matt and the team to find and fix anything we might see.

**Comment by rafaelromcar-parabol** [comment]
Embedder is already in production
