### ISSUE TITLE
embedder: created high-watermark table, refactor

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#9451]
## Issue - Enhancement

Background: https://github.com/ParabolInc/parabol/pull/9417/files/5ac2b541fbfcb0cf8232adc4de2168f2ef050fdf#r1488739626

Today the embedder has no way to distinguish how far along it is when adding historical items to the `EmbeddingsMetadata` table from when the application might add an item itself to the `EmbeddingsMetadata` table. If an item by our application before the embedder has indexed all of the history, the unprocessed history will never be embedded.

We need a mechanism to store the high water mark of history. Suggesting we add a table such as `EmbeddingsWatermark`

```
id                  PRIMARY KEY
objectType          EmbeddingsObjectTypeEnum
newest              TIMESTAMP
```

While refactoring, @mattkrick has also suggested the following pattern:

```typescript
// redis CLI
PUBLISH buildObjects "{start: '1970-01-01', end: '2024-02-22', objectType: 'discussionTopic'}"

// embedder.ts
const subscriber = new RedistInstance('sub')
subscriber.subscribe('buildObjects')
subscriber.on('message', _channel, message) => {
    addMetadata(JSON.parse(message))
}

const addMetadata = async ({start: Date, end?: Date, objectType?: ObjectType}) => {
  if (objectType === 'discussionTopic') {
    addMetaDataForDiscussions(start, end)
  }
}

const addMetadataForDiscussions(start: Date, end?: Date) {
  let curStart = start
  for (i = 0; i <1e6; i++) {
    const items = r.table('NewMeeting').between(curStart, end, {index: 'endedAt'}).limit(100)
    const failedToInsertDueToUniqueConstraintViolation = await processItems(items)
    if (items.length < 100 || failedToInsertDueToUniqueConstraintViolation) break
    curStart = items[items.length - 1].endedAt
  }
}
```

This would afford an easy interface for reindexing items in the event of a failure.

### Acceptance Criteria (optional)
Users can:
   - `refreshRetroDiscussionTopicsMeta` refactored to utilize watermark
   - optional: followed above suggested pattern

**Estimated effort:** 13 points

**Comment by jordanh** [comment]
It also occurred to me that there could be an alternative way to solve this... we don't allow the app to add items to the EmbeddedMetadata table unless all the history has been added first.

The indexing process is a one-shot. After all the history is added, the refreshment doesn't need to happen again.

**Comment by mattkrick** [comment]
absolutely! the trick is what to do with the jobs coming from the app.

if we treated this as a migration, would could run the migration & then update the app, but we'd miss the jobs that happened in the seconds between the migration & the app starting.

we could do a 2-phase rollout:
- part 1 updates the app so all new items get added to metadata table
- part 2 is a migration that grabs the `end = min(oldest date, r.maxval)` for that metadata type in the metadata table and then processes history for `r.minval, end`.

**Comment by jordanh** [comment]
I think we decided to tackle this a different way, so I'll close this for now
