### ISSUE TITLE
typo in parabol support article "Managing your users"

### ISSUE THREAD

**Issue by ytubs** [ParabolInc/parabol#9453]
## Issue - Bug

- **How serious is the bug?** P0 
- **OS:** macOS 
- **Browser:** Chrome  + 122.0.6261.69

in https://www.parabol.co/support/managing-your-users/ , "billing details and **remote** users from the Parabol Organization" remote should be replaced with "remove"

![image](https://github.com/ParabolInc/parabol/assets/75385082/5e29003f-0799-47e4-9336-38a3eeb78db0)

hopefully it's the right place to report that, cheers

**Comment by tianrunhe** [comment]
Thanks for reporting this @ytubs ! This has been fixed.
