### ISSUE TITLE
Time-based (timer & time limit) feature in team health phase of retro does not work

### ISSUE THREAD

**Issue by dbumblis-parabol** [ParabolInc/parabol#9540]
## Issue - Bug

- **How serious is the bug?** P3
- **OS:** Any
- **Browser:** Chrome 122.0.6261.129
- **Node version:** 
- **NPM version:**  
- **RethinkDB version:** 

This was reported in P1 preprod testing and I reproduced in current Production 7.20.0

Steps to reproduce:
1. Timer doesn't behave as expected
2. Start timer for 1 minute
3. observe nothing shows a timer is running
4. no alert after timer is finished

1. Time Limit doesn't behave as expected
2. Start time limit
3. do not check Notify team via slack
4. Start
5. no change in behavior or UI

### Acceptance Criteria (optional)
Users can:
   - Start a timer during the team health phase
   - Time appears and counts down specified time
   - Create a time limit within phase, that limit it honored
   - The limit is shown on UI

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
Came by to add priority and add this to our project board
