### ISSUE TITLE
Update pricing page to reflect new template limits

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9589]
### AC

- [ ] Pricing page reflects that templates are now free and everyone can create two custom templates per meeting
- [ ] Add Org Admin Role to the Enterprise section

**Comment by Mohd-Muneeb** [comment]
Can I be assigned to this task please? I'd like to know more about this if it's possible so I contribute to it

**Comment by nickoferrall** [comment]
Sorry @Mohd-Muneeb, I've created a PR for this one as we wanted to get it updated quickly. Thank you for offering, though, and if there's another issue you're interested in, we always welcome contributions.
