### ISSUE TITLE
Persisted avatar on meeting header of solo updates

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#9632]
<img width="585" alt="Screenshot 2024-04-11 at 8 12 23 AM" src="https://github.com/ParabolInc/parabol/assets/5514175/212965d5-8116-42f4-82af-9be958ec3ace">

Repro:
- start a meeting with 2+ people
- move from person 1 to person 2 and notice on person 2's update stage the avatar still shows person 1

**Comment by Dschoordsch** [comment]
It seems it persists the avatar of whatever was open first, i.e. if you are on person 2 and refresh, it is correct. If you then move forward or back, it will stay on person 2

**Comment by ackernaut** [comment]
We noticed it in the agenda, too. I wonder if this issue is only happening for check-ins, or other meetings, too?
