### ISSUE TITLE
Chronos error on mutation ProcessRecurrence

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#9664]
## Issue - Bug

- **How serious is the bug?** P1 / P2?
- **OS:** macOS / Linux / Windows / ? our Docker images
- **Browser:** Chrome / Safari / Lynx / ? -
- **Node version:** `node --version` v20.11.0
- **NPM version:** `npm --version` 10.2.4
- **RethinkDB version:** `rethinkdb --version`

Chronos will throw the following error non-stop
```
Trace: SEND TO SENTRY TIMEOUT {"query":"\n        mutation ProcessRecurrence{\n          pro"} undefined                                                                                                           
    at sendToSentry (/home/node/parabol/dist/chronos.js:17369:11)                                                                                                                                                  
    at publishWebhookGQL (/home/node/parabol/dist/chronos.js:17340:28)
```

 (See [Datadog for that date](https://app.datadoghq.com/logs?query=-kube_namespace%3Akube-system%20env%3Aproduction%20-kube_namespace%3Adb-tools%20-kube_namespace%3Adatadog%20-kube_namespace%3Agmp-system%20kube_deployment%3Aparabol-chronos%20&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cpod_name%2Ckube_namespace&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1713252336874&to_ts=1713857136874&live=true). We only have 15 days of history in Datadog, and it has been happening for at least those 15 days.

### Acceptance Criteria (optional)
Chronos does not throw the error non-stop. And I suppose recurrence works.

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
If chronos cannot publish to the gql executor, it looks like it lost the connection to redis 🤔

**Comment by rafaelromcar-parabol** [comment]
Ah! Not clear enough on the logs IMHO. I can restart Chronos, even if it has been restarted multiple times in the last two weeks and we are getting that error message 😿 

That said, Chronos should retry connecting because Redis is up and running as the other components are using it. And the error message should state that it can't connect to Redis 🤔

**Comment by Dschoordsch** [comment]
Might be something different then. I will check the logs.

**Comment by Dschoordsch** [comment]
I checked, it's not a real issue, just a wrong timeout. The [logs 🔒](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aproduction%20resource_name%3A%22mutation%20ProcessRecurrence%22&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&historicalData=true&messageDisplay=inline&query_translation_version=v0&sort=desc&spanType=service-entry&traceQuery=&view=spans&start=1713685388668&end=1713858188668&paused=false) show that the mutation takes around 15s but the default query timeout is [10s](https://github.com/ParabolInc/parabol/blob/fb76d9a3ec977e886dcc778b96fc2a5abfd4716c/packages/server/utils/PubSubPromise.ts#L7). Nothing bad happens atm., but I think we wanted to use the 10m timeout instead, but lost it at some point.

**Comment by rafaelromcar-parabol** [comment]
Good that it is working then 😸 Still, the error message should be fixed to help catching real errors then.
