### ISSUE TITLE
Adding timeout notification

### ISSUE THREAD

**Issue by garethaledavies** [ParabolInc/parabol#9681]
**Problem**
When a user keeps a Parabol board open in the browser for a long time, it can timeout and become unresponsive for saving the input in a retro/check-in meeting. 

However, even when it has timed out, Parabol lets you add those reflections. Because of the timeout they do not save. 

I've experienced this issue a few times on my team. People keep the retro open in a tab, spend 10 minutes writing reflections and none of them save. It's a frustrating experience for everyone:

- The user wastes time writing reflections that are not saved by Parabol
- The team lead gets messages saying "it's not working" and "can you see the reflections I wrote?"

**Solution**
After a # of minutes of inactivity in the browser, Parabol could prompt people to refresh to hopefully prevent this issue. 

In the case of my team-mate, she had to close the tab, then go back into Parabol and re-log the reflections (refresh did not work for her).

**Other thoughts**
As someone bringing Parabol into an organisation this adds some friction and makes it more difficult to win the hearts and minds of team-mates when they experience friction.

**Comment by jordanh** [comment]
@garethaledavies thank you for this report

To clarify: you are not getting a message that says, "you are offline?" when this happens?

**Comment by jordanh** [comment]
I think this may have been fixed with a recent Trebuchet update. I am going to Close this one for now.
