### ISSUE TITLE
Inline pictures in emails to avoid expiring presigned URLs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#9700]
As we move towards requiring presigned URLs for UGC like avatars, if we use those links in emails then pictures in emails will fail to load after the URL expires.

To avoid this, we should try inlined attachments. We tried this once before, but perhaps we used non-inline attachments? 
https://github.com/ParabolInc/parabol/issues/2527#issuecomment-452754135

AC
- [ ] pictures in emails are self-contained in the email & do not require accessing a CDN
- [ ] the size of the email isn't so big that it sometimes bounces (base64 inlining can do this)
- [ ] pictures don't show up as downloadable attachments

**Comment by jordanh** [comment]
scrubbed

**Comment by mattkrick** [comment]
P1 doesn't allow direct access to S3, so the presigned URL strategy is no longer used.
If we do need to use a filestore, we'll have to use our server as a proxy, which is what mattermost does.
Closing until another client needs a presigned URL strategy
