### ISSUE TITLE
AL template search: Architecture

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9721]
## Goals
The Activity Library template search should be
* responsive, i.e. results should show up as the user types
* find exact text matches
* find smart matches, e.g. searching for "project end" should bring up "post-mortem"

**Comment by jordanh** [comment]
scrubbed

**Comment by Dschoordsch** [comment]
Easiest way to implement is
- embed all templates with a plaintext including all prompts and descriptions
  - don't include extra prose
- add query on the User next to `availableTemplates`
- debounce and query this from the client

**Comment by Dschoordsch** [comment]
- import historical meeting templates based on `updatedAt` field
- make sure the `updatedAt` field of the template is also updated when a prompt is changed

**Comment by Dschoordsch** [comment]
For now we'll query the embedding model instance directly from the GQL executor bypassing the separate embedder instance.
If that leads to issues in the long run, the plan is to implement some pubsub logic so we can call and await an embedding job directly from the executor in the resolver functions.
