### ISSUE TITLE
Bug: processRecurrence is slow

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9722]
The mutation takes >15s, see [logs](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20resource_name%3A%22mutation%20ProcessRecurrence%22&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=span_list&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&traceQuery=&view=spans&start=1714472919314&end=1715077719314&paused=false) 🔒 We only run it every 5min so it's not an issue at the moment, but it should be faster.
Also testing processRecurrence times out sometimes https://github.com/ParabolInc/parabol/actions/runs/8982173873/job/24669192689?pr=9720

**Comment by Dschoordsch** [comment]
`RRule.between` is the slow part, see [traces](https://app.datadoghq.com/apm/trace/4167095565530130462?colorBy=service&env=production&graphType=span_list&shouldShowLegend=true&sort=time&spanID=4167095565530130462&spanViewType=metadata&timeHint=1716382800075.002) 🔒

**Comment by Dschoordsch** [comment]
The slowness comes from the time zone processing https://github.com/jkbrzt/rrule/blob/9f2061febeeb363d03352efe33d30c33073a0242/src/datewithzone.ts#L32
When processing all RRules locally (~1100) takes 18s with tzid and only 1s when stripping tzid.
Also RRules need to always iterrate from the start to the current `between` args, so it will only get worse over time.

**Comment by mattkrick** [comment]
what in the world is that package doing internally?!?!
this is the same package that crashed our servers by creating an infinite loop 🤣

**Comment by mattkrick** [comment]
Elevating to P1 since this is a synchronous call & it lasts 23 seconds, which would cause any requests that hit the same server to timeout

**Comment by mattkrick** [comment]
https://github.com/lsndr/rrule-rust

**Comment by mattkrick** [comment]
this is basically crashing every request that comes in while processRecurrence runs.
Gonna focus on this
