### ISSUE TITLE
Inconsistency between meeting creation date and title

### ISSUE THREAD

**Issue by yedane** [ParabolInc/parabol#9813]
## Issue - Bug

Wrong date between the date when creating recurring meetings and the date printed in the title of the meeting

- **How serious is the bug?** P3
- **OS:** Windows 
- **Browser:** Chrome

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

![image](https://github.com/ParabolInc/parabol/assets/8882331/f1b571d7-ab6e-4fe3-80cd-b3ecc7a78f18)
![2024-06-03_09-59-05](https://github.com/ParabolInc/parabol/assets/8882331/f77d3a37-c03a-452a-abc6-49c2931732ff)

**Comment by jordanh** [comment]
Edited priority to P3

**Comment by Dschoordsch** [comment]
I fixed this at some point
