### ISSUE TITLE
Admin Nav: add org menu 

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9830]
### See https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=39-2965&t=ql2fzl5PH064XymP-0

![Screenshot 2024-06-06 at 15 00 40](https://github.com/ParabolInc/parabol/assets/39854876/02e693f1-891d-475c-aad6-f0c7b677264a)

### AC

- [ ] When hovering over nav items, the menu shows up looking like the designs

**Comment by nickoferrall** [comment]
Hey @ackernaut, I just want to confirm that the menu should open onHover and only when hovering over Settings & Members? It doesn't open when hovering over the team names as it's org specific?

**Comment by ackernaut** [comment]
@nickoferrall I think we should make it open on click. I want to say all of our menus open on click in the app. The Settings & Members item has the same footprint and hover state of the other nav items, but instead of going somewhere it opens a menu. How does that sound?

**Comment by nickoferrall** [comment]
Keeping it consistent makes sense to me! I'll update this issue so it opens on click instead of on hover 👍
