### ISSUE TITLE
Reflection group title missing after removal & rejoin

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#9833]
## Issue - Bug

Reproduction steps:
1. Create a reflection group by merging two cards
2. Remove a card from the group
3. Merge the card back, or put in new card
4. Observe that **NO** group title was formed and the placeholder text is shown

![2024-06-06 08 16 17](https://github.com/ParabolInc/parabol/assets/1879975/bf05ba8d-e2cc-4043-b65d-e25ba5682a05)

### Acceptance Criteria (optional)
Users can:
   - [ ] see group title after removing & rejoining a reflection group

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by jordanh** [comment]
Groomed!

**Comment by mattkrick** [comment]
this is making testing a pain, gonna fix
