### ISSUE TITLE
Add member count to Organization Members sections

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#9870]
## Issue - Enhancement

<img width="1413" alt="image" src="https://github.com/ParabolInc/parabol/assets/103000/8700233d-4d14-48c5-9409-89ada326981b">

### Acceptance Criteria (optional)
Org Admins can:
  - See a total count of Organization Members in the top header
 
**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
Resolved as part of https://github.com/ParabolInc/parabol/pull/10146
