### ISSUE TITLE
No error feedback when upgrading with insufficient funds

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9926]
@MindEvo discovered [here](https://github.com/ParabolInc/parabol/pull/9921#issuecomment-2204221500) that upgrading using a card with insufficient funds doesn't show any error feedback. The updating button just keeps looping.

### AC

- [ ] Upgrading with a card with insufficient funds shows error feedback

**Comment by jordanh** [comment]
@nickoferrall after @mattkrick's recent changes, does this bug still exist?

**Comment by nickoferrall** [comment]
Just tested this and we get the error message now 👍  I'll close the issue

<img width="495" alt="Screenshot 2024-08-22 at 11 11 07" src="https://github.com/user-attachments/assets/90e4509b-fafd-4bb6-9b34-10b8b793b3a9">
