### ISSUE TITLE
Application update notification modification or disablement for self-hosted deployments

### ISSUE THREAD

**Issue by dbumblis-parabol** [ParabolInc/parabol#9930]
## Issue - Enhancement

Self-hosted deployments contain in-app notifications about a new version of Parabol when a new container image is deployed. However, it links to the open-source repository and only the latest version, which was not necessarily the version that was deployed.

### Acceptance Criteria (optional)
Users can either:
   - Receive a notification that links to the specific application version deployed
   - Operators can disable the notification
   - Operators can update the link the notification sends the user to. For ex. to their own release notes page

**Estimated effort:** 8 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
nice issue!
Easy fix, just like you say, we should link to the specific version:

https://github.com/ParabolInc/parabol/blob/252f0db3b87f7408c556663f4edffa9eedb0a95f/packages/client/hooks/useServiceWorkerUpdater.ts

should goto e.g. https://github.com/ParabolInc/parabol/releases/tag/v7.38.0

**Comment by rafaelromcar-parabol** [comment]
[PR created](https://github.com/ParabolInc/parabol/pull/9937) to solve this. Asked review from either Matt or Georg. It's really simple, but just in case 😸
