### ISSUE TITLE
Reduce Azure DevOps scope

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9944]
Right now we're requesting the `.default` [scope](https://github.com/ParabolInc/parabol/blob/46770a048bfd4cd21c0e1cab89abdc01f8a79af3/packages/client/utils/AzureDevOpsClientManager.ts#L44) which requests access to all Azure DevOps APIs. A [customer](https://parabol.slack.com/archives/C4JAUUZ9P/p1720540202812269) 🔒 pointed out that this is excessive as it also allows source code access.

**Comment by Dschoordsch** [comment]
I think we only need `vso.project vso.work_write` [^1]

[^1]: https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?toc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Ftoc.json&view=azure-devops

**Comment by mattkrick** [comment]
I believe we need to turn it into an app so it have fine-grained permissions on a per-repo basis: https://github.com/ParabolInc/parabol/issues/7114

**Comment by Dschoordsch** [comment]
We are registered as a web app (#9531). Not sure how we can configure per repo permissions.

**Comment by mattkrick** [comment]
oh! well i'm an idiot i must've missed this!
i might be thinking of the GH integration that can do repo-specific perms. makes sense that orgs have a repo or 2 they don't want to expose to parabol
